/**
 * Extra appearance templates so each part has 50+ filmable choices.
 * Core encyclopedia entries stay in characterAppearanceKit.ts.
 */
import type {
  AppearancePartId,
  AppearanceTemplateDef
} from './characterAppearanceKit'

type Row = [
  id: string,
  labelZh: string,
  labelEn: string,
  keywordsZh: string,
  keywordsEn: string,
  structureZh: string,
  structureEn: string,
  promptBlock: string
]

function pack(part: AppearancePartId, rows: readonly Row[]): AppearanceTemplateDef[] {
  return rows.map(
    ([id, labelZh, labelEn, kz, ke, structureZh, structureEn, promptBlock]) => ({
      id,
      part,
      labelZh,
      labelEn,
      keywordsZh: kz.split('、'),
      keywordsEn: ke.split(', '),
      structureZh,
      structureEn,
      promptBlock
    })
  )
}

const FACE: Row[] = [
  ["v_line", "V字小臉", "V-line face", "精緻、偶像、下頜尖", "idol, refined, pointed jaw", "下頜急收成 V，面窄", "sharp V taper, narrow face", "V-line face, sharply tapered jaw"],
  ["u_line", "U字柔臉", "U-line face", "柔和、親和、圓頜", "soft, friendly, rounded jaw", "下頜呈 U，頰線圓", "U-shaped jaw, rounded cheeks", "U-line face, rounded jaw curve"],
  ["baby_fat", "嬰兒肥臉", "Baby-fat face", "幼態、甜、頰肉", "youthful, sweet, chubby cheeks", "頰側嬰兒肥，下頜軟", "visible baby fat, soft jaw", "baby-fat face, plump cheeks"],
  ["gaunt", "削瘦臉", "Gaunt face", "清冷、病態、骨感", "gaunt, cold, bony", "頰凹陷，顴骨浮出", "hollow cheeks, prominent bones", "gaunt face, hollow cheeks"],
  ["hollow_cheeks", "凹陷頰骨臉", "Hollow-cheek face", "時尚、冷感、立體", "fashion, cool, sculpted", "頰中凹陷深", "deep mid-cheek hollows", "hollow-cheek fashion face"],
  ["high_cheek", "高顴骨臉", "High-cheekbone face", "鋒利、大氣、立體", "sharp, grand, sculpted", "顴骨高而寬", "high wide cheekbones", "high cheekbone face, lifted malar"],
  ["wide_jaw", "寬下頜臉", "Wide-jaw face", "沉穩、力量、方正", "steady, powerful, square", "下頜寬於中庭", "jaw wider than midface", "wide-jaw face, powerful mandible"],
  ["narrow_chin", "窄下巴臉", "Narrow-chin face", "精巧、敏感、收尖", "delicate, sensitive, tapered", "下巴極窄", "very narrow chin", "narrow-chin face, delicate pointed chin"],
  ["cleft_chin", "溝下巴臉", "Cleft-chin face", "個性、西方、記憶點", "character, western, memorable", "頦中淺溝", "chin cleft groove", "cleft chin, shallow chin dimple"],
  ["lantern_jaw", "燈籠下頜", "Lantern jaw", "剛毅、江湖、厚頜", "tough, wuxia, heavy jaw", "下頜前突厚實", "projecting heavy jaw", "lantern jaw, projecting mandible"],
  ["moon", "滿月臉", "Full moon face", "喜感、福相、圓滿", "jovial, blessed, round", "全臉近圓", "almost circular full face", "full moon face, circular outline"],
  ["pear", "梨形臉", "Pear face", "穩、下盤寬、親和", "grounded, wide base, warm", "額窄頜寬", "narrow brow, wide jaw", "pear-shaped face, wide lower third"],
  ["trapezoid", "梯形臉", "Trapezoid face", "成熟、厚實、可靠", "mature, solid, reliable", "額略窄，下頜更寬", "tapered brow, wider jaw", "trapezoid face, wider jaw than forehead"],
  ["pentagon", "五角臉", "Pentagon face", "英氣、額寬、頜角利", "heroic, wide brow, angular", "額寬顴中頜角分明", "five-sided angular outline", "pentagon face, angular jaw corners"],
  ["kite", "風箏臉", "Kite face", "鋒、顴最寬、上下收", "sharp, widest malar", "顴最寬，額頜都收", "widest at cheeks", "kite face, widest cheekbones"],
  ["slim_oval", "瘦鵝蛋", "Slim oval", "清秀、修長、文氣", "refined, slender, literary", "鵝蛋再收窄", "slimmed oval, less flesh", "slim oval face, slender contour"],
  ["heavy_square", "厚實方臉", "Heavy square", "豪門、分量、方正", "powerful, weighty, square", "方臉加厚度", "thick square bone", "heavy square face, thick jaw"],
  ["soft_square", "軟方臉", "Soft square", "溫剛、親和、微方", "warm-strong, friendly", "頜角在但被軟肉包", "square under soft tissue", "soft square face, muted jaw angles"],
  ["doll", "洋娃娃臉", "Doll face", "精緻、幼、五官聚中", "doll, petite, centered", "五官偏中、面小、額飽", "small centered features", "doll face, small centered features"],
  ["statue", "雕像臉", "Statue face", "古典、大理石、對稱", "classical, marble, symmetric", "骨相極對稱", "highly symmetric carved bones", "statue-like face, marble symmetry"],
  ["opera", "戲曲臉", "Opera-stage face", "濃墨、古典、舞台", "opera, stylized, stage", "額飽顴亮，適合濃妝", "full brow, bright malar", "Chinese-opera face structure"],
  ["film_star", "老派明星臉", "Old-Hollywood face", "華麗、鏡頭臉、顴亮", "glamorous, camera, lit malar", "顴高下頜利", "high malar, camera-ready", "old-Hollywood face, camera-ready cheekbones"],
  ["idol_v", "愛豆錐子臉", "Idol cone face", "時尚、過度收尖", "idol, fashion, camera", "中下庭極窄", "extreme lower taper", "idol cone face, extremely tapered lower face"],
  ["model_long", "超模長臉", "Runway-long face", "超模、垂直、冷感", "runway, vertical, cool", "面長比誇張", "exaggerated face length", "runway-long face, extreme vertical thirds"],
  ["short_midface", "短中庭臉", "Short-midface", "幼態、鼻短區、可愛", "youthful, short mid", "鼻根到人中偏短", "short midface height", "short midface, compact nose-to-lip"],
  ["long_midface", "長中庭臉", "Long-midface", "貴、鼻長區、疏離", "noble, long mid, aloof", "中庭明顯拉長", "elongated midface", "long midface, elongated nose region"],
  ["wide_forehead", "寬額臉", "Wide-forehead face", "智、額開、天庭飽", "intellectual, open brow", "額寬飽滿", "wide full forehead", "wide forehead, open brow"],
  ["narrow_forehead", "窄額臉", "Narrow-forehead face", "秀氣、髮際低", "delicate, low hairline", "額窄，髮際近眉", "narrow brow, low hairline", "narrow forehead, low hairline"],
  ["flat_mid", "扁平中庭", "Flat midface", "東方面中、親和", "East-Asian flat, warm", "中庭前突弱", "low midface projection", "flat midface, low projection"],
  ["convex_profile", "凸面側臉", "Convex profile", "鼻突、個性、側臉強", "projected, profile", "側面中庭前凸", "convex facial profile", "convex profile, projected midface"],
  ["concave_profile", "凹面側臉", "Concave profile", "柔、鼻根凹、少女", "soft, scooped, youthful", "鼻根凹陷", "scooped profile", "concave profile, scooped nasal root"],
  ["chubby_lower", "下庭豐臉", "Full lower-face", "福、下庭肉、穩", "blessed, full lower, steady", "嘴以下豐滿", "full lower third", "full lower face, plump chin"],
  ["sharp_jaw", "利刃下頜", "Blade jaw", "冷、頜線如刃、時尚", "cold, blade jaw, fashion", "下頜緣極利", "razor jawline", "blade jawline, razor-sharp edge"],
  ["soft_jaw", "無骨感下頜", "Soft jawline", "溫、頜線隱、治癒", "warm, hidden jaw, heal", "下頜緣被軟組織蓋", "soft hidden jawline", "soft jawline, low bone definition"],
  ["androgynous_oval", "中性鵝蛋", "Androgynous oval", "中性、萬能、時尚", "androgynous, versatile", "雌雄莫辨的勻稱鵝蛋", "gender-neutral oval", "androgynous oval face, gender-neutral"],
  ["childlike_heart", "童心形臉", "Childlike heart", "童顏、額寬、頦尖", "childlike, wide brow", "額更飽、下巴更尖", "fuller brow heart", "childlike heart face, tiny chin"],
  ["mature_wide", "成熟寬臉", "Mature wide face", "歲數感、面寬、權威", "mature, wide, authority", "面寬增加", "wider mature face", "mature wide face, authoritative breadth"],
  ["athletic_face", "運動方長臉", "Athletic oblong", "健康、頜緊、陽光", "athletic, tight jaw", "長臉加緊實頜線", "oblong plus tight jaw", "athletic oblong face, tight jaw"],
  ["comic_round", "漫畫圓臉", "Comic round face", "二次元、圓、誇張頰", "anime, round, exaggerated", "圓到接近幾何", "geometric round", "comic-round face, exaggerated circular cheeks"],
  ["classic_egg", "標準蛋形", "Standard egg", "萬能、教科書、中性比例", "textbook, versatile", "最標準的蛋形比例", "textbook egg proportions", "standard egg-shaped face"],
  ["peasant_round", "鄉土圓臉", "Rustic round", "質樸、日照、親切", "rustic, sun, kind", "圓中帶厚", "thick rustic round", "rustic round face, wholesome thick cheeks"],
  ["aristocratic_long", "貴族長臉", "Aristocratic long", "世族、垂直、冷傲", "lineage, vertical, proud", "長臉加薄皮", "long thin aristocratic", "aristocratic long face, proud length"],
  ["short_wide", "短寬臉", "Short-wide face", "敦實、中庭短、面寬", "compact, short, wide", "面短而寬", "short wide canvas", "short-wide face, horizontal features"]
]

const EYES: Row[] = [
  ["monolid_almond", "單眼皮杏仁", "Monolid almond", "東方、含蓄、一線", "oriental, reserved, crease-less", "無明顯雙眼皮，杏仁長裂", "crease-less almond slit", "monolid almond eyes, no crease"],
  ["double_phoenix", "平行雙眼皮丹鳳", "Double-lid phoenix", "精緻、眼褶、上挑", "refined, crease, upturn", "平行雙眼皮加鳳眼尾", "parallel crease plus phoenix tail", "double-lid phoenix eyes, parallel crease"],
  ["inner_fold", "內雙含情眼", "Inner-fold eyes", "自然、內雙、柔", "natural, inner fold, soft", "內雙褶，眼尾柔", "inner epicanthic fold", "inner-fold eyes, soft crease"],
  ["hooded", "腫泡眼", "Hooded eyes", "慵懶、上瞼厚、欲睡", "languid, heavy lid", "上瞼蓋住褶", "hooded heavy lids", "hooded eyes, heavy upper lids"],
  ["downturned_deer", "下垂鹿眼", "Downturned deer", "無辜、哀甜", "innocent, sad-sweet", "圓鹿眼但眼尾下垂", "round deer, droop tail", "downturned deer eyes, outer drop"],
  ["wide_set_peach", "寬距桃花", "Wide-set peach", "疏離美、眼距寬", "spaced, ethereal", "眼距寬於一隻眼寬", "wide interocular", "wide-set peach blossom eyes"],
  ["close_set_fox", "近距狐眼", "Close-set fox", "專注、心機、聚中", "focused, cunning", "眼距偏近，狐尾仍挑", "close-set upturn", "close-set fox eyes, intense gaze"],
  ["sleepy", "睡眼惺忪", "Sleepy eyes", "慵懶、半睜、欲", "sleepy, half-lid, allure", "眼裂半開，上瞼沉", "half-open lids", "sleepy half-lidded eyes"],
  ["glass_gray", "琉璃灰瞳", "Glass-gray irises", "疏離、透明、冷", "detached, glass, cold", "灰瞳如玻璃", "glassy gray irises", "glassy gray irises, cold catchlights"],
  ["amber_phoenix", "琥珀丹鳳", "Amber phoenix", "貴、琥珀瞳、銳", "regal, amber, sharp", "鳳眼裂加琥珀虹膜", "phoenix slit, amber iris", "amber phoenix eyes, warm amber irises"],
  ["ink_peach", "墨黑桃花", "Ink-black peach", "深情、黑瞳大、臥蠶", "devoted, black, aegyo", "桃花形加極黑瞳", "peach shape, ink pupils", "ink-black peach eyes, huge dark pupils"],
  ["green_fox", "綠瞳狐眼", "Green fox eyes", "異域、危險、綠", "exotic, dangerous, green", "狐眼上挑加綠虹膜", "fox upturn, green iris", "green fox eyes, exotic green irises"],
  ["blue_cold", "冷藍眸", "Ice-blue eyes", "西化、冷、透明藍", "western, icy, blue", "冰藍瞳", "ice-blue irises", "ice-blue eyes, cold transparent blue"],
  ["heterochromia_soft", "柔異色瞳", "Soft heterochromia", "超常、一眼一色、柔", "uncanny, two colors, soft", "左右色差明顯但不誇張", "gentle two-tone irises", "soft heterochromia, two gentle iris colors"],
  ["red_brown", "紅棕瞳", "Red-brown eyes", "熱情、深棕偏紅", "warm, reddish brown", "虹膜深棕帶紅銅", "copper-brown irises", "red-brown irises, copper warmth"],
  ["cat_vertical", "貓瞳豎瞳", "Cat-slit pupils", "非人、夜、危險", "nonhuman, night, danger", "瞳孔豎縫", "vertical slit pupils", "cat-slit pupils, vertical pupils"],
  ["crane", "鶴眼細長", "Crane-long eyes", "仙、極細長、淡", "immortal, extra-long", "眼裂比丹鳳更細更長", "extra-long thin slit", "crane-long eyes, extremely long thin slits"],
  ["round_wet", "水汪圓眼", "Wet round eyes", "哭腔、水光、幼", "teary, wet, young", "圓眼滿水光", "wet highlight round", "wet round eyes, glassy tear highlights"],
  ["upturned_sharp", "鋒利上挑眼", "Sharp upturned", "攻擊、尾如刃", "aggressive, blade tail", "眼尾刀鋒上挑", "blade-upturn, no softness", "sharply upturned eyes, blade-like corners"],
  ["level_classic", "平視端正眼", "Level classic eyes", "端正、眼尾平、官配", "upright, level tail", "眼尾不上不下", "level outer corners", "level classic eyes, even outer corners"],
  ["deep_set", "深窩眼", "Deep-set eyes", "沉思、眼窩深、陰影", "thoughtful, deep sockets", "眶緣深", "deep orbital sockets", "deep-set eyes, strong brow-ridge shadow"],
  ["protruding_round", "微凸圓眼", "Slightly prominent", "靈、眼球略凸、光", "lively, slight bulge", "眼球略前凸", "slight proptosis", "slightly prominent round eyes"],
  ["thin_lid", "薄瞼細眼", "Thin-lid narrow", "冷、瞼薄、裂細", "cold, thin lid, narrow", "眼皮極薄", "paper-thin lids", "thin-lid narrow eyes"],
  ["thick_lid", "厚瞼媚眼", "Thick-lid glam", "濃、瞼厚、妝感", "glam, thick lid", "上瞼肉厚", "thick glam lids", "thick-lid glamorous eyes"],
  ["short_slit", "短眼裂", "Short eye slit", "含蓄、橫向短、聚", "reserved, short width", "眼裂橫向偏短", "short palpebral fissure", "short eye slits, compact width"],
  ["long_slit", "超長眼裂", "Ultra-long slit", "妖、橫向極長", "siren, extra-wide", "內眥到外眥極長", "very long fissure", "ultra-long eye slits"],
  ["high_crease", "高雙眼皮", "High crease", "洋氣、褶高、深", "western, high fold", "雙眼皮褶明顯偏高", "high eyelid crease", "high-crease double eyelids"],
  ["no_aegyo", "無臥蠶冷眼", "No aegyo-sal", "冷、下瞼平、疏離", "cold, flat lower lid", "下瞼平直無臥蠶", "flat lower lid", "flat lower lids, no aegyo-sal"],
  ["heavy_aegyo", "厚臥蠶甜眼", "Heavy aegyo-sal", "甜、下瞼肉、幼", "sweet, puffy under", "臥蠶極飽滿", "very full under-eye", "heavy aegyo-sal, very full under-eye"],
  ["red_rim", "紅血絲病眼", "Red-rimmed eyes", "病態、瞼緣紅、執", "sickly, red rim, obsessed", "瞼緣與血絲明顯", "red lash line, veins", "red-rimmed sickly eyes"],
  ["clear_white", "極白眼白", "Porcelain sclera", "乾淨、眼白亮、神聖", "clean, bright white", "鞏膜極白", "pure white sclera", "porcelain-white sclera"],
  ["narrow_brow_gap", "眉壓眼", "Low brow-eye gap", "英、眉貼眼、煞", "heroic, brows close", "眉眼距離極近", "tiny brow-eye gap", "brows almost touching lids"],
  ["wide_brow_gap", "高眉眼距", "Wide brow-eye gap", "貴、額開、疏", "noble, open, spaced", "眉與眼距離寬", "wide brow-eye distance", "wide brow-to-eye distance"],
  ["sparse_lash", "淡睫清眼", "Sparse-lash clean", "素、睫少、清", "plain, few lashes", "睫毛淡而疏", "sparse lashes", "sparse-lash clean eyes"],
  ["dense_lash", "濃睫媚眼", "Dense-lash glam", "濃、睫密、影", "glam, dense lashes", "睫毛濃密如扇", "fan-dense lashes", "dense lush lashes"],
  ["up_flick_liner", "眼線上挑", "Flicked liner eyes", "妝感、尾鋒、現代", "makeup, flick, modern", "眼尾眼線明顯上挑", "sharp liner flick", "sharp flicked eyeliner"],
  ["smoky", "煙燻眼", "Smoky eyes", "夜、煙燻、危險", "night, smoke, danger", "眼周煙燻暈開", "smoky shadow halo", "smoky eyes, darkened halo"],
  ["innocent_highlight", "星星高光眼", "Star-highlight eyes", "二次元、星點、純", "anime, star catch", "瞳內星形高光", "star-shaped catchlights", "star catchlight eyes"],
  ["dead_fish", "死魚眼", "Dead-fish eyes", "虛無、無焦、冷", "void, unfocused, cold", "無高光、焦距散", "no catchlight, vacant", "dead-fish eyes, vacant unfocused"],
  ["hunter", "獵手細眼", "Hunter-narrow", "殺、細裂、盯", "predator, thin, stare", "極細長、盯人", "predatory thin stare", "hunter-narrow eyes, unblinking stare"],
  ["scholar", "書卷細目", "Scholar eyes", "文、細目、溫", "literary, thin, warm", "細長但不鋒", "thin warm scholarly", "scholarly thin eyes, gentle gaze"],
  ["warrior_glare", "戰目圓睜", "Warrior glare", "武、圓睜、怒意可收", "martial, wide, glare", "用力時眼圓睜", "wide martial glare", "warrior glare eyes, can widen fiercely"],
  ["crescent_smile", "笑成月牙", "Crescent smiling eyes", "喜、彎月", "joy, crescent", "笑時眼成彎月", "crescent when smiling", "crescent smiling eyes, moon-slits"]
]

const NOSE: Row[] = [
  ["button", "鈕扣小鼻", "Button nose", "幼、圓、可愛", "cute, round, tiny", "極短極圓的小鼻頭", "tiny round button", "button nose, tiny rounded tip"],
  ["roman", "羅馬鼻", "Roman nose", "西、鼻樑拱、個性", "western, arched bridge", "鼻樑中段微拱", "arched roman bridge", "Roman nose, arched bridge"],
  ["greek", "希臘直鼻", "Greek straight", "古典、從額連直", "classical, straight from brow", "額到鼻幾乎一條直", "straight brow-to-tip", "Greek straight nose, brow-to-tip line"],
  ["snub", "短翹鼻", "Snub nose", "俏、短、孔可見", "pert, short, visible nares", "短而微翹", "short upturned nares", "snub nose, short upturned"],
  ["aquiline", "鷹鉤鼻", "Aquiline hook", "權、鉤、危險", "power, hook, danger", "鼻尖明顯下鉤", "hooked downward tip", "aquiline hooked nose, downward tip"],
  ["wide_alae", "寬鼻翼", "Wide alae", "親和、翼寬、穩", "warm, wide wings", "鼻翼明顯寬", "wide nasal wings", "wide alae, broad nostrils"],
  ["pinched_alae", "極收鼻翼", "Pinched alae", "精、翼貼、冷", "refined, pinched, cold", "鼻翼幾乎貼樑", "pinched to bridge", "pinched alae, wings tight to bridge"],
  ["bulbous", "圓球鼻頭", "Bulbous tip", "厚、頭圓、親切", "bulb, round, warm", "鼻頭圓球感", "rounded bulb tip", "bulbous nose tip, rounded ball tip"],
  ["pointed_tip", "尖鼻頭", "Pointed tip", "銳、頭尖、妖", "sharp, pointed, siren", "鼻頭收成尖", "pointed nasal tip", "pointed nose tip, sharp refined tip"],
  ["short_bridge", "短樑鼻", "Short-bridge nose", "幼、樑短、中庭短", "youth, short bridge", "鼻樑縱向短", "vertically short bridge", "short-bridge nose, compact length"],
  ["long_bridge", "超長鼻樑", "Extra-long bridge", "貴、樑長、中庭長", "noble, long bridge", "鼻樑明顯偏長", "extra-long nasal length", "extra-long nasal bridge"],
  ["low_root", "低鼻根", "Low nasal root", "東、根低、柔", "East-Asian, low root", "鼻根低平", "low flat root", "low nasal root, flat start at glabella"],
  ["high_root", "高鼻根", "High nasal root", "立體、根高、西", "sculpted, high root, west", "鼻根高", "high root at brow", "high nasal root, starts high at brow"],
  ["crooked_soft", "微歪鼻", "Softly crooked", "故事、微歪、人味", "story, slight crook", "樑輕微不對稱", "slight asymmetry", "softly crooked nose, slight asymmetry"],
  ["flat_wide", "扁寬鼻", "Flat-wide nose", "親、樑扁、翼寬", "warm, flat, wide", "樑低且整體寬", "flat and wide", "flat-wide nose, low bridge, broad wings"],
  ["narrow_ridge", "刀脊窄樑", "Knife-ridge", "冷、脊如刀、窄", "cold, knife ridge", "樑脊極窄鋒利", "knife-thin dorsum", "knife-ridge nose, razor-thin dorsum"],
  ["soft_dorsum", "肉樑鼻", "Fleshy dorsum", "柔、樑有肉、不骨", "soft, fleshy bridge", "樑被軟組織蓋", "fleshy covered bridge", "fleshy dorsum, soft tissue over bridge"],
  ["upturned_refined", "精緻翹鼻", "Refined upturn", "精、微翹、時尚", "refined slight upturn", "微翹但樑仍細", "subtle refined upturn", "refined upturned nose, slim"],
  ["downturned_tip", "垂尖鼻", "Downturned tip", "哀、尖下垂、戲", "melancholy, droop tip", "鼻尖略下垂", "slightly drooping tip", "downturned nasal tip"],
  ["wide_root", "寬鼻根", "Wide root", "穩、根寬、敦", "steady, wide start", "鼻根橫向寬", "wide starting root", "wide nasal root, broad start"],
  ["sculpted_tip", "精雕鼻頭", "Sculpted tip", "醫美感、頭精、對稱", "clinic, sculpted, even", "鼻頭過度精緻對稱", "over-refined tip", "sculpted clinic-perfect nasal tip"],
  ["natural_uneven", "天生微不對稱鼻", "Naturally uneven", "真人、微差、可信", "real, slight uneven", "左右鼻翼輕微不等", "slight alar unevenness", "naturally uneven nose"],
  ["celestial", "上仰天鼻", "Celestial upturn", "靈、孔微露、仙", "spirit, slight nare show", "從正面微見鼻孔", "slight nostril show", "celestial upturned nose, slight nostril show"],
  ["nubian_long", "長闊鼻", "Long broad nose", "力量、長且闊", "powerful, long and broad", "長樑加較闊翼", "long plus broad", "long broad nose, powerful length and width"],
  ["tiny_child", "幼童小鼻", "Toddler-small nose", "幼、極小、未長開", "child, tiny, unfinished", "鼻子比例像小孩", "child-scale nose", "toddler-small nose, unfinished child scale"],
  ["masculine_ridge", "男向骨樑", "Masculine ridge", "剛、骨感、寬脊", "masc, bony, wide ridge", "脊寬有骨結", "bony wide ridge", "masculine bony nasal ridge"],
  ["feminine_slim", "女向細樑", "Feminine slim", "柔、細、無結", "fem, slim, smooth", "全程細滑無骨結", "smooth slim all the way", "feminine slim nose, smooth"],
  ["bump_soft", "輕駝峰", "Soft bump", "個性、中段輕凸", "character, soft hump", "中樑輕微駝峰", "soft dorsal hump", "soft dorsal bump, gentle hump"],
  ["no_bump", "完全直樑", "Ruler-straight", "整齊、無任何凸", "neat, zero bump", "側看完全直尺", "perfectly straight side", "ruler-straight nose, zero dorsal bump"],
  ["flared_breath", "扇動寬孔", "Flared nostrils", "情緒、孔可扇、烈", "emotion, flare, fire", "鼻孔偏大可扇開", "flared capable nares", "flared nostrils, large expressive nares"],
  ["hidden_nares", "隱孔鼻", "Hidden nares", "雅、正面幾乎不見孔", "elegant, hidden holes", "正面鼻孔極隱", "nares hidden in front", "hidden nares, nostrils barely visible"],
  ["oily_shine", "高光油鼻", "Oily highlight nose", "寫實、T區油、真人", "real, T-zone shine", "鼻頭油光明顯", "oily tip shine", "oily T-zone nose, realistic sebum"],
  ["matte_powder", "霧面鼻", "Matte powder nose", "妝、霧、無油", "makeup, matte", "完全霧面無高光油", "matte no oil", "matte powdered nose, no oil shine"],
  ["red_cold", "凍紅鼻頭", "Cold-red tip", "冬、頭微紅、人味", "winter, pink tip", "鼻頭微凍紅", "pink cold tip", "cold-reddened nose tip"],
  ["pale_tip", "蒼白鼻頭", "Pale tip", "病、頭淡、血少", "sickly, pale tip", "鼻頭比面更白", "tip paler than face", "pale nose tip, bloodless"],
  ["freckled_bridge", "樑上雀斑鼻", "Freckled bridge", "日、樑斑、親", "sun, bridge spots", "鼻樑淺雀斑", "bridge freckles", "freckled nasal bridge"],
  ["scarred_bridge", "樑上淺疤鼻", "Scarred bridge", "往事、樑細疤", "history, fine scar", "鼻樑一道淺疤", "fine bridge scar", "faint scar on nasal bridge"],
  ["pierced_subtle", "細鼻環", "Subtle nose ring", "現代、細環、個性", "modern, thin ring", "一側細鼻環", "small nostril ring", "subtle nostril ring piercing"],
  ["bridge_piercing", "鼻樑釘", "Bridge piercing", "叛、樑釘、地下", "rebel, bridge studs", "鼻樑雙釘", "bridge studs", "bridge piercing, two studs on nasion"],
  ["fantasy_ridge", "紋光鼻脊", "Fantasy ridge", "幻、脊帶淡紋", "fantasy, faint rune", "鼻脊有淡幻想紋", "faint fantasy marking", "fantasy marked nasal ridge"],
  ["beast_broad", "獸寬鼻", "Beast-broad nose", "非人、極寬、動物感", "nonhuman, very wide", "鼻體極寬近獸", "bestial breadth", "beast-broad nose, animalistic width"],
  ["porcelain_carved", "瓷雕細鼻", "Porcelain carved", "瓷、細、無毛孔感", "porcelain, poreless", "細到像瓷塑", "poreless porcelain nose", "porcelain-carved slim nose"]
]

const MOUTH: Row[] = [
  ["tiny_dot", "一粒米小嘴", "Rice-grain mouth", "極小、含蓄、古典", "tiny, reserved, classic", "嘴裂極短極小", "extremely small mouth", "rice-grain tiny mouth"],
  ["wide_laugh", "闊笑嘴", "Wide laugh mouth", "開朗、裂長、笑面", "open, long slit, smile", "嘴裂明顯偏長", "long oral slit", "wide laugh mouth, long commissure"],
  ["heart_lips", "心形唇", "Heart lips", "甜、上唇心形、幼", "sweet, heart upper", "上唇中峰如心", "heart-shaped upper", "heart-shaped lips, central upper peak"],
  ["downturned_sad", "下垂哀嘴", "Downturned sad", "哀、角下、戲", "sad, dropped corners", "靜止嘴角下垂", "resting frown corners", "downturned mouth, sad dropped corners"],
  ["overbite_cute", "淺齙甜嘴", "Cute overbite", "齙、上齒微露、幼", "overbite, cute teeth", "上齒靜止微露", "slight resting overbite", "cute slight overbite"],
  ["hidden_teeth", "齒不露嘴", "Hidden-teeth", "含、笑也不怎露齒", "reserved, hidden teeth", "唇閉合少露齒", "teeth rarely shown", "hidden-teeth mouth"],
  ["gummy_smile", "露齦笑", "Gummy smile", "笑露齦、記憶點", "gummy, memorable", "大笑明顯露牙齦", "visible gums when smile", "gummy smile, visible upper gums"],
  ["thin_upper", "上薄下厚", "Thin-over-full", "反差、上薄下豐", "contrast, thin over full", "上唇薄、下唇厚", "thin upper, full lower", "thin upper over full lower lip"],
  ["full_upper", "上厚下薄", "Full-over-thin", "少見、上豐、個性", "rare, full upper", "上唇更厚", "fuller upper lip", "full upper lip over thinner lower"],
  ["equal_medium", "均厚中唇", "Even medium lips", "中、上下均、萬能", "even, medium, versatile", "上下厚度接近中等", "even medium volume", "even medium lips, balanced volume"],
  ["cracked_dry", "乾裂唇", "Chapped lips", "寫實、乾、風霜", "real, chapped, weather", "唇紋乾裂明顯", "visible chap lines", "chapped dry lips"],
  ["gloss_wet", "水光唇", "Glossy wet lips", "妝、水光、現代", "gloss, wet, modern", "高反光唇蜜感", "high-gloss finish", "high-gloss wet lips"],
  ["matte_velvet", "絲絨霧唇", "Velvet matte", "霧、絨、高級", "matte, velvet, luxe", "完全霧面絲絨", "velvet matte texture", "velvet matte lips, no shine"],
  ["ombre_gradient", "漸變咬唇", "Ombre bite lips", "咬唇妝、中深外淺", "ombre, bitten", "中央深、邊緣淺", "dark center fade", "ombre bitten lips"],
  ["dark_plum", "暗李子唇", "Dark plum lips", "暗、李、夜", "dark, plum, night", "深李子色唇", "deep plum color", "dark plum lips"],
  ["nude_bare", "裸粉唇", "Nude bare lips", "素、近膚、清", "nude, near-skin", "顏色接近膚色", "near-skin lip color", "nude bare lips"],
  ["blood_red", "正紅唇", "Blood-red lips", "正紅、攻擊、經典", "true red, classic", "高飽和正紅", "saturated true red", "blood-red lips, saturated classic red"],
  ["coral", "珊瑚橘唇", "Coral lips", "暖、珊瑚、夏", "warm, coral, summer", "珊瑚橘調", "coral-orange tint", "coral lips, warm summer orange-pink"],
  ["wine", "酒紅唇", "Wine lips", "熟、酒紅、夜宴", "mature, wine, banquet", "深酒紅", "deep wine", "wine-red lips"],
  ["pale_sick", "病白唇", "Bloodless pale lips", "病、近白、冷", "sick, pale, cold", "唇色極淡近白", "near-white lips", "bloodless pale lips"],
  ["asymmetric_smile", "歪笑嘴", "Crooked smile", "壞、一邊高、個性", "rogue, one side up", "一邊嘴角更高", "asymmetric lift", "crooked smile, one corner higher"],
  ["pout", "嘟嘴", "Pouty mouth", "撒嬌、前嘟、幼", "pout, forward, cute", "雙唇輕輕前嘟", "soft forward pout", "pouty mouth, softly pushed-forward"],
  ["compressed", "抿唇", "Compressed lips", "忍、抿緊、冷", "held, pressed, cold", "常抿成一條線", "pressed thin line", "compressed lips, habitually pressed"],
  ["open_soft", "微張柔嘴", "Softly parted", "欲、微張、氣", "parted, breath, soft", "靜止微張", "softly parted at rest", "softly parted lips"],
  ["cupid_sharp", "尖丘比特", "Sharp Cupid bow", "峰極尖、線清", "sharp bow, clear", "唇峰如兩個尖角", "very sharp cupid", "sharp Cupid bow, pointed twin peaks"],
  ["cupid_soft", "弱丘比特", "Soft Cupid bow", "峰弱、少年、清", "weak bow, youth", "唇峰不明顯", "low-definition bow", "soft Cupid bow, barely-there peaks"],
  ["long_philtrum", "長人中嘴", "Long-philtrum", "疏、人中長、貴或哀", "long philtrum, aloof", "鼻下到唇峰距離長", "long philtrum", "long philtrum"],
  ["short_philtrum", "短人中嘴", "Short-philtrum", "幼、人中短、甜", "short philtrum, cute", "人中極短", "very short philtrum", "short philtrum, youthful"],
  ["scar_lip", "唇邊淺疤", "Scarred lip corner", "往事、角疤、狠", "scar, corner, edge", "嘴角一道淺疤", "corner scar", "faint scar at mouth corner"],
  ["mole_corner", "嘴角痣唇", "Corner-mole lips", "媚、角痣、經典", "charm, corner mole", "嘴角一顆痣", "mole at commissure", "beauty mole at mouth corner"],
  ["tooth_gap", "門牙縫", "Tooth-gap smile", "縫、記憶點、真", "gap, memorable, real", "門牙中縫明顯", "visible midline gap", "tooth-gap smile, midline diastema"],
  ["fang_hint", "微虎牙", "Hint of fangs", "虎牙、靈、少年", "fang, spirited", "笑時虎牙微露", "canine peek", "hint of fangs, playful canine peek"],
  ["vampire", "尖齒嘴", "Vampiric teeth", "非人、尖齒、夜", "nonhuman, fangs, night", "尖牙明顯", "obvious fangs", "vampiric pointed canines"],
  ["braces_youth", "牙套少年嘴", "Braces youth", "牙套、校園、現", "braces, school, now", "金屬或透明牙套", "visible braces", "youth braces, school-age orthodontics"],
  ["gold_tooth", "金牙一閃", "Gold-tooth flash", "江湖、一顆金、狠", "underworld, gold, edge", "笑時一顆金牙", "one gold tooth", "gold tooth flash"],
  ["dark_inner", "深色唇內", "Dark inner lip", "對比、內深外淺", "contrast, dark inner", "唇內緣更深", "darker vermilion inner", "dark inner vermilion"],
  ["pale_rim", "淺緣唇", "Pale-rim lips", "緣淡、中間才有色", "pale rim, color center", "唇緣幾乎無色", "faded lip border", "pale-rim lips, faded border"],
  ["overdrawn", "超繪唇緣", "Overdrawn liner", "妝、緣繪大、時尚", "makeup, overdrawn", "唇線畫得比本體大", "overdrawn outline", "overdrawn lip liner"],
  ["undefined_edge", "無鋒唇緣", "Undefined edge", "緣糊、自然、素", "blurred edge, natural", "唇緣與膚漸變", "soft undefined border", "undefined lip edge, soft fade"],
  ["wide_lower", "厚下唇主導", "Heavy lower lip", "下唇極厚、欲", "heavy lower, desire", "下唇視覺主導", "lower dominates", "heavy lower lip, dominant bottom"],
  ["pinched_corners", "收緊嘴角", "Pinched corners", "角緊、克制、冷", "pinched, restrained", "嘴角像被捏緊", "pinched commissures", "pinched mouth corners"],
  ["laugh_lines", "笑紋嘴", "Laugh-line mouth", "笑紋、親切、歲", "nasolabial, warm, age", "鼻唇溝明顯連嘴", "visible laugh lines", "laugh-line mouth, nasolabial folds"]
]

const HAIR: Row[] = [
  ["buzz", "寸頭", "Buzz cut", "利、極短、軍", "severe, buzz, military", "髮長極短貼皮", "skin-close buzz", "buzz cut, skin-close military crop"],
  ["undercut", "鏟青底", "Undercut", "底鏟、頂長、現", "shaved sides, modern", "兩側鏟、頂上留長", "shaved sides, long top", "undercut, shaved sides, longer top"],
  ["mullet", "狼尾", "Mullet", "狼尾、前後差、叛", "mullet, rebel", "前短後長狼尾", "short front long back", "mullet, short front, long back"],
  ["wolf_cut", "狼尾層次", "Wolf cut", "層、狼、潮", "shaggy, wolf, trend", "臉周圍碎層、後長", "shaggy layers, long back", "wolf cut, shaggy face layers"],
  ["hime", "姬髮式", "Hime cut", "姬、齊瀏海、兩側直", "hime, blunt bangs", "齊瀏海加兩側齊切", "blunt bangs and sides", "hime cut, blunt bangs, even side cuts"],
  ["curtain_bang", "簾幕瀏海", "Curtain bangs", "中分簾、柔、現", "curtain, soft, now", "中分兩簾掃顴", "center curtain sweep", "curtain bangs, center-part face-framing"],
  ["blunt_bang", "齊瀏海", "Blunt bangs", "齊、蓋眉、幼", "blunt, brow-cover", "一條直線蓋眉", "straight brow-cover bangs", "blunt bangs, straight brow-covering fringe"],
  ["side_bang", "斜瀏海", "Side-swept bangs", "斜、遮額、神秘", "side sweep, mystery", "瀏海斜掃一眼", "sweep covering one brow", "side-swept bangs, diagonal fringe"],
  ["no_bang", "露額無瀏海", "No bangs", "露額、額開、貴", "open brow, noble", "完全無瀏海", "fully exposed forehead", "no bangs, fully exposed forehead"],
  ["afro", "爆炸捲", "Afro", "圓、捲、體積", "round, coil, volume", "球形捲髮體積大", "spherical coil volume", "afro, spherical coiled volume"],
  ["dreadlocks", "髒辮", "Dreadlocks", "辮繩、街頭、重", "locs, street, heavy", "一條條繩狀髮", "rope locs", "dreadlocks, rope-like locs"],
  ["cornrows", "玉米辮", "Cornrows", "貼頭辮、紋、俐", "cornrow, pattern", "貼頭幾何辮", "scalp geometric braids", "cornrows, geometric scalp braids"],
  ["box_braids", "盒式辮", "Box braids", "多辮、長、擺動", "many braids, swing", "大量長盒辮", "many long box braids", "box braids, many long swinging braids"],
  ["pixie", "精靈短髮", "Pixie cut", "極短、靈、耳露", "pixie, elfin, ears", "耳周極短", "elfin short, ears out", "pixie cut, elfin short"],
  ["bowl", "鍋蓋頭", "Bowl cut", "齊、鍋蓋、幼或怪", "bowl, even, odd", "一圈齊長如蓋", "even bowl length", "bowl cut, even helmet length"],
  ["mushroom", "蘑菇頭", "Mushroom cut", "圓蓋、學生、懷舊", "mushroom, student", "圓弧蓋耳蘑菇", "rounded mushroom cap", "mushroom cut, rounded cap over ears"],
  ["two_block", "兩段式", "Two-block", "韓、底短頂長", "Korean, two-block", "底部短、上段突然長", "short bottom long top", "two-block cut, Korean short bottom"],
  ["slick_wet_all", "全頭濕背", "Full wet slick", "全濕、油、夜", "all wet, oil, night", "整頭濕梳向後", "fully wet slicked", "fully wet slicked-back hair"],
  ["dry_texture", "乾枯碎感", "Dry textured", "乾、碎、寫實或病", "dry, broken, real", "髮乾無光", "dry ends, low shine", "dry textured hair, matte broken ends"],
  ["rainbow", "彩虹染", "Rainbow dye", "彩、多色、奇", "rainbow, multi, queer", "多段彩虹色", "multi rainbow sections", "rainbow-dyed hair, multiple vivid colors"],
  ["split_dye", "陰陽染", "Split dye", "中分兩色、對比", "half-and-half", "左右兩色對撞", "two-tone split", "split-dye hair, two contrasting halves"],
  ["ombre_dark_tip", "深淺漸變", "Ombre ends", "根深梢淺或相反", "ombre, gradient", "長度方向漸變色", "lengthwise gradient", "ombre hair, gradient from root to tip"],
  ["highlight_streak", "一縷挑染", "Streak highlight", "一縷異色、記憶點", "one streak, mark", "一縷明顯異色", "single contrasting streak", "single highlight streak"],
  ["white_streak", "白縷", "White streak", "一縷白、故事或魔", "white lock, story", "天生或魔性白縷", "one white lock", "white streak lock"],
  ["bald_shaved", "光頭", "Shaved bald", "光、頭皮、力量或僧", "bald, scalp, power", "無髮或極近光", "fully shaved scalp", "shaved bald head"],
  ["topknot", "武士揪", "Topknot", "高揪、武士、利", "topknot, samurai", "頂心揪起", "crown knot", "samurai topknot, high bun"],
  ["low_bun", "低丸子", "Low bun", "低盤、素、工或學", "low bun, plain", "後腦低位丸子", "nape-level bun", "low bun at the nape"],
  ["messy_bun", "凌亂抓髻", "Messy bun", "隨、抓、碎髮", "messy, pinned, wisps", "隨便一抓的髻", "loose messy bun", "messy bun, many flyaways"],
  ["half_up", "半扎髮", "Half-up", "上半扎、下半散", "half up, half down", "上半束、下半披", "upper half tied", "half-up half-down hair"],
  ["single_braid", "單麻花垂", "Single braid", "一條粗辮垂後", "one thick braid", "後垂一條辮", "one rear braid", "single thick braid down the back"],
  ["crown_braid", "皇冠辮", "Crown braid", "繞頭辮、古典、禮", "around-head, formal", "辮繞頭一圈", "braid around crown", "crown braid circling the head"],
  ["dread_mohawk", "莫霍克", "Mohawk", "中間長兩邊剃", "mohawk, sides shaved", "中央一條長，兩側光", "center strip, sides bare", "mohawk, shaved sides, center strip"],
  ["curly_short", "短捲", "Short curls", "短、天然捲、彈", "short, coil, bounce", "短髮緊捲", "tight short coils", "short curly hair, tight bounce coils"],
  ["wavy_shoulder", "及肩微波", "Shoulder waves", "及肩、慢波、日常", "shoulder, slow wave", "及肩自然波", "shoulder-length waves", "shoulder-length loose waves"],
  ["waist_straight", "及腰直髮", "Waist-length straight", "極長、直、仙或冷", "waist, straight, immortal", "直髮及腰或過腰", "straight to waist", "waist-length straight hair"],
  ["permed_tight", "緊電捲", "Tight perm", "電、緊捲、復古", "perm, tight, retro", "化學緊捲全頭", "all-over tight perm", "tight perm, all-over chemical curls"],
  ["slick_part_deep", "深偏分油頭", "Deep side oil", "深分、油、商或黑", "deep part, oil, formal", "極深側分、油光", "deep oily side part", "deep side part, oily formal hair"],
  ["fluffy_air", "空氣感蓬鬆", "Air-fluffy", "蓬、輕、韓", "fluffy, light, K", "根部蓬鬆無重力", "root lift, airy", "air-fluffy hair, weightless root lift"],
  ["greasy_unwashed", "油頭未洗", "Unwashed greasy", "寫實、油、頹", "real, grease, slump", "多日未洗的油貼", "days-unwashed grease", "unwashed greasy hair"],
  ["ornament_heavy", "步搖滿飾", "Heavy ornaments", "釵、步搖、宮", "pins, tassels, palace", "大量金銀飾壓髮", "heavy palace jewelry", "heavy hair ornaments, palace pins"],
  ["bead_braids", "珠飾辮", "Beaded braids", "珠、辮、異域", "beads, braids, foreign", "辮上串珠", "beads on braids", "beaded braids"],
  ["wet_ringlets", "濕螺旋捲", "Wet ringlets", "濕、螺旋、夜", "wet, spiral, night", "濕潤一條條螺旋", "wet spiral curls", "wet ringlets, defined spiral curls"]
]

const SKIN: Row[] = [
  ["ivory_matte", "霧象牙", "Matte ivory", "霧、牙白、無油", "matte, ivory, dry-fine", "象牙白完全霧面", "matte ivory, no oil", "matte ivory skin, no sebum"],
  ["porcelain_glow", "瓷光冷白", "Glowing porcelain", "瓷、冷、透光", "porcelain, glow, cool", "冷白帶皮下透光", "cool glow under white", "glowing porcelain, subsurface cool light"],
  ["olive", "橄欖膚", "Olive skin", "橄欖綠底、地中", "olive, mediterranean", "綠黃底中等膚", "olive undertone", "olive skin, green-gold undertone"],
  ["golden", "金箔膚", "Golden skin", "金、高光金、神或貴", "gold, divine, luxe", "膚帶金色高光", "golden sheen", "golden skin, metallic gold sheen"],
  ["bronze", "古銅膚", "Bronze skin", "銅、深暖、雕塑", "bronze, warm deep", "深暖如銅像", "bronze statue tone", "bronze skin, sculptural warm metal"],
  ["ebony", "深黑膚", "Ebony", "極深、高光沿骨", "very deep, bone light", "極深膚，高光窄", "very deep, narrow highlight", "ebony skin, very deep"],
  ["ruddy", "赤紅健康", "Ruddy healthy", "戶外紅、酒氣或凍", "ruddy, outdoor, wind", "全面偏紅健康", "all-over ruddy", "ruddy healthy skin, wind-flushed"],
  ["jaundiced", "病黃膚", "Jaundiced pallor", "病、黃、肝氣", "ill, yellow, sick", "明顯病黃", "yellow sick tone", "jaundiced pallor, sickly yellow"],
  ["cyanotic", "青紫冷膚", "Cyanotic cool", "極冷、唇指可青", "cyan, extreme cold", "冷到帶青紫", "blue-cold undertone", "cyanotic cool skin, blue-cold"],
  ["vitiligo_soft", "淡白斑", "Soft vitiligo", "白斑、不規則、真", "patches, real, unique", "不規則淺白斑", "irregular pale patches", "soft vitiligo patches"],
  ["birthmark_port", "酒紅胎記", "Port-wine mark", "胎記、酒紅塊、記憶", "birthmark, wine patch", "一塊酒紅胎記", "port-wine stain", "port-wine birthmark"],
  ["tan_lines", "曬痕膚", "Tan-line skin", "寫實、衣痕、夏", "real, tan lines, summer", "可見衣物曬痕", "visible tan lines", "tan-line skin, clothing-edge contrast"],
  ["burnish_labor", "勞動糙膚", "Labor-rough", "糙、日曬、手臉粗", "rough, sun, labor", "粗糙有斑有紋", "rough weathered", "labor-rough skin, weathered texture"],
  ["glass_skin", "玻璃肌", "Glass skin", "韓、透、反光如玻", "K-beauty, glass", "極度透亮如玻璃", "glass-like translucency", "glass skin, Korean glass translucency"],
  ["dewy", "露水肌", "Dewy skin", "露、點狀高光、嫩", "dew, dotted glow", "露珠狀高光", "dewy droplets of light", "dewy skin, droplet highlights"],
  ["oily_tzone", "油光T區", "Oily T-zone", "寫實、T油、兩頰可乾", "real, T oil", "額鼻油、頰相對乾", "oily T, drier cheeks", "oily T-zone, mixed real skin"],
  ["dry_flaky", "乾脫皮", "Dry flaky", "冬、乾、細屑", "winter, flakes", "細微脫屑", "fine flakes", "dry flaky skin, winter scale"],
  ["acne_real", "青春痘寫實", "Realistic acne", "痘、寫實、少年", "acne, real, youth", "少量活躍或痘印", "few active spots or marks", "realistic acne, a few spots"],
  ["scar_acne", "痘疤肌", "Acne-scarred", "凹疤、故事、真", "pits, story, real", "淺凹痘疤", "shallow pits", "acne-scarred skin, shallow pits"],
  ["melasma", "斑黃褐", "Melasma", "褐斑、顴、歲", "patches, cheek, age", "顴側褐斑", "malar brown patches", "melasma, brown cheek patches"],
  ["albinism", "白化膚", "Albinism", "極白、睫眉可淡", "albino, pale lash", "幾乎無色素", "near-zero pigment", "albinism, near-zero pigment"],
  ["sunburn", "曬傷紅", "Sunburn red", "新曬紅、痛感色", "fresh burn, red", "新均紅或脫皮紅", "fresh sunburn red", "sunburned skin, fresh red"],
  ["afterglow_dusk", "黃昏暖膚", "Dusk-warmed", "黃昏光、暖金包膚", "dusk, gold wrap", "被黃昏光包住的暖", "warm dusk wrap", "dusk-warmed skin, golden hour wrap"],
  ["moon_pale", "月下蒼白", "Moon-pale", "夜、月、幾乎無血", "moon, night, bloodless", "月光下的蒼", "moonlit pallor", "moon-pale skin, nocturnal bloodless"],
  ["blush_drunk", "酒醉紅", "Drunk flush", "醉、兩頰鼻頭紅", "drunk, nose and cheeks", "不均酒紅", "uneven drunk red", "drunk flush, uneven red"],
  ["blush_shy", "害羞飛紅", "Shy flush", "瞬間紅、耳也可", "sudden, ears too", "兩頰飛快的紅", "sudden cheek bloom", "shy flush, sudden blooming cheeks"],
  ["no_blush", "完全無血色", "No blush", "蠟、無紅、詭", "wax, no red, eerie", "完全沒有血色起伏", "zero flush variation", "no-blush waxen skin"],
  ["tattooed_face", "面紋膚", "Facial tattoos", "紋、面、族或黑", "tattoos, clan, ink", "臉上有可見紋身", "visible face ink", "facial tattoos, visible ink"],
  ["war_paint", "戰繪膚", "War paint", "繪、條、原始或儀式", "paint, bars, ritual", "儀式彩繪留在膚上", "ritual paint marks", "war-paint skin, ritual color bars"],
  ["scale_sheen", "鱗光膚", "Scale sheen", "非人、細鱗反光", "nonhuman, scales", "細鱗在光下閃", "fine scale shimmer", "scale-sheen skin, fine iridescent scales"],
  ["marble_vein", "大理石青筋", "Marble veins", "青筋、大理石、貴或病", "veins, marble", "淺可見青筋如紋石", "visible marble veins", "marble-veined skin"],
  ["freckle_dense", "密雀斑", "Dense freckles", "滿面斑、日、親", "dense, sun, warm", "滿臉密雀斑", "face-wide freckles", "dense freckles across the whole face"],
  ["poreless", "無毛孔", "Poreless", "超精、塑膠或瓷", "poreless, cgi or porcelain", "完全看不見毛孔", "no visible pores", "poreless skin"],
  ["large_pores", "粗毛孔", "Large pores", "寫實、鼻頰孔粗", "real, large pores", "鼻翼與頰毛孔粗", "visible large pores", "large-pore realistic skin"],
  ["sweaty", "汗濕膚", "Sweaty skin", "汗、反光點、熱或懼", "sweat, beads, heat", "汗珠與濕光", "sweat beads", "sweaty skin, visible sweat beads"],
  ["dirty_dust", "塵土膚", "Dusty dirty", "灰、戰、逃", "dust, war, flee", "面有塵與污", "dust and grime", "dusty dirty skin, travel grime"],
  ["blood_smear", "血痕膚", "Blood-smeared", "血、擦痕、戰後", "blood, smear, after", "淡血痕", "light blood smear", "light blood smear on skin"],
  ["ritual_ash", "灰塗膚", "Ash-smeared", "灰、喪或巫、額鼻", "ash, rite, brow", "額或顴抹灰", "ash on brow", "ritual ash-smeared skin"],
  ["biolume", "生物冷光膚", "Bioluminescent", "幻、皮下冷光", "fantasy, under-glow", "皮下淡淡冷光", "faint under-skin glow", "bioluminescent skin, faint inner glow"],
  ["metallic_chrome", "鍍鉻膚", "Chrome skin", "機、鉻、非人", "chrome, machine", "局部或全鉻反光", "chrome reflection", "chrome metallic skin"],
  ["wood_grain", "木紋膚", "Wood-grain", "精怪、木紋、非人", "spirit, wood, other", "膚表淺木紋", "faint wood grain", "wood-grain skin, spirit bark pattern"],
  ["stone_crack", "石裂膚", "Stone-cracked", "石、裂、魔像感", "stone, cracks, golem", "淺石裂紋", "stone crack lines", "stone-cracked skin, golem fissures"]
]

const BODY: Row[] = [
  ["willowy", "柳枝極瘦", "Willowy", "極瘦、長、風吹", "willowy, wind, long", "瘦到有柳枝感", "extreme slim length", "willowy body, extreme slim length"],
  ["stocky", "矮壯", "Stocky", "矮、壯、重心低", "short, thick, low", "身高偏矮但厚", "short thick build", "stocky body, short thick powerful"],
  ["hourglass", "沙漏", "Hourglass", "胸腰差大、經典", "hourglass, classic", "腰極細、上下豐", "tiny waist, full ends", "hourglass figure, tiny waist"],
  ["rectangle", "直筒", "Rectangle", "腰線弱、少曲線", "straight, low curve", "肩腰臀接近", "similar widths", "rectangle body, similar shoulder-waist-hip"],
  ["inverted_tri", "倒三角身", "Inverted triangle", "肩寬臀窄、力", "wide shoulder, narrow hip", "上寬下收", "wide top, narrow hip", "inverted-triangle body, swimmer shoulders"],
  ["triangle_pear", "正三角梨", "Pear body", "臀寬肩窄", "wide hip, narrow shoulder", "下盤明顯更寬", "wider hips", "pear body, wider hips than shoulders"],
  ["apple", "蘋果身", "Apple body", "中段豐、肢可細", "full mid, slimmer limbs", "腰腹分量大於肢", "fuller midsection", "apple body, fuller midsection"],
  ["petite_curve", "嬌小有曲線", "Petite curvy", "矮、有胸臀、精", "short, curvy, compact", "矮但曲線完整", "short full curves", "petite curvy, compact hourglass"],
  ["tall_lanky", "高瘦竹竿", "Tall lanky", "極高極瘦、未填", "very tall, unfilled", "高且四肢過長感", "extra-long limbs", "tall lanky, extra-long limbs"],
  ["bodybuilder", "健美塊", "Bodybuilder", "極肌、比賽感", "extreme muscle, stage", "肌肉塊明顯分離", "separated muscle heads", "bodybuilder physique"],
  ["lean_muscle", "精瘦肌", "Lean muscle", "薄肌、線條、跑", "lean, lines, runner", "脂肪極低的薄肌", "low-fat lean muscle", "lean muscle, runner-thin definition"],
  ["soft_dad", "柔軟中年", "Soft midlife", "中年軟、肚微、真", "soft, slight belly, real", "胸肩軟、微肚", "soft chest, slight belly", "soft midlife body, slight belly"],
  ["pregnant_soft", "孕態柔身", "Pregnant softness", "孕、中段圓、僅成年", "pregnant, round mid, adult", "明顯孕態圓腹", "adult pregnant mid", "adult pregnant softness, rounded mid"],
  ["hunched", "微駝", "Slight hunch", "駝、學者或老、肩前", "hunch, scholar, age", "肩微前傾駝", "forward shoulder hunch", "slight hunch, forward scholarly shoulders"],
  ["ramrod", "標槍直背", "Ramrod posture", "極直、軍、肩開", "erect, military", "背極度直", "extreme erect posture", "ramrod posture, military-straight back"],
  ["narrow_shoulder", "窄肩", "Narrow shoulders", "肩窄、文、弱或秀", "narrow, literary", "肩寬明顯小於臀", "shoulders slimmer than hips", "narrow shoulders, literary slim top"],
  ["wide_shoulder", "寬肩架", "Wide shoulder yoke", "肩極寬、衣架、力", "yoke, hanger, power", "肩如衣架", "coat-hanger shoulders", "wide shoulder yoke"],
  ["long_neck", "長頸", "Long neck", "頸長、天鵝、貴", "long neck, swan", "頸柱明顯長", "long cervical column", "long swan neck"],
  ["short_neck", "短頸", "Short neck", "頸短、敦、頭近肩", "short, compact", "頸短頭近肩", "head near shoulders", "short neck, head close to shoulders"],
  ["long_torso", "長身短腿", "Long-torso", "軀長腿相對短", "long torso, shorter legs", "胸腰長、腿比例短", "long trunk", "long torso, relatively shorter legs"],
  ["long_legs", "長腿短身", "Long-legged", "腿長、模特、身短", "long legs, model", "腿長佔身高多", "leg-dominant", "long-legged, model leg ratio"],
  ["knock_knee_soft", "微內八站", "Soft knock-knees", "內八、幼或羞、站姿", "in-toed, shy stance", "站立膝微靠", "knees slightly in", "soft knock-kneed stance"],
  ["bow_leg", "微弓步腿", "Slight bow legs", "弓、江湖或騎、站", "bow, rider, stance", "腿微外弓", "slight bow", "slight bow legs, rider stance"],
  ["large_hands", "大手", "Large hands", "手大、記憶點", "big hands, mark", "手相對頭偏大", "hands large vs head", "noticeably large hands"],
  ["small_hands", "小手", "Small hands", "手小、精、幼", "small, refined", "手相對精小", "refined small hands", "noticeably small refined hands"],
  ["long_fingers", "修長指", "Long fingers", "指長、琴、雅", "long, piano, elegant", "手指特別長", "extra-long fingers", "extra-long fingers, pianist elegant"],
  ["stubby_fingers", "短粗指", "Stubby fingers", "指短粗、力或樸", "short thick, labor", "指節短粗", "short thick digits", "stubby fingers, labor-short digits"],
  ["barrel_chest", "桶胸", "Barrel chest", "胸圍大、氣、力", "barrel, lung, power", "胸腔圓厚", "round thick chest", "barrel chest, thick round thorax"],
  ["sunken_chest", "塌胸", "Sunken chest", "胸平或凹、弱或病", "flat or sunken, frail", "胸相對塌", "concave or flat chest", "sunken chest, frail concave thorax"],
  ["wide_hip", "寬胯", "Wide hips", "胯寬、走姿擺", "wide, sway, stable", "髖明顯寬", "wide pelvic", "wide hips, obvious pelvic width"],
  ["narrow_hip", "窄胯", "Narrow hips", "胯窄、直筒下盤", "narrow, straight base", "髖窄", "narrow pelvis", "narrow hips, straight lower body"],
  ["thick_thigh", "厚腿", "Thick thighs", "腿粗有肉或肌", "thick, power or soft", "大腿圍明顯", "heavy thigh", "thick thighs"],
  ["stick_leg", "竹竿腿", "Stick legs", "腿極細、骨感", "very thin legs", "小腿大腿都細", "thin throughout", "stick-thin legs, bony"],
  ["big_calf", "肌小腿", "Muscular calves", "小腿肌、走或跳", "calf muscle, walk", "小腿肚明顯", "defined calves", "muscular calves"],
  ["flat_feet_hint", "扁平足站", "Flat-foot stance", "站姿足弓低、寫實", "low arch, real", "站立足弓偏低", "low arches standing", "flat-footed stance"],
  ["tiptoe_habit", "踮腳習慣", "Tiptoe habit", "常踮、靈或緊張", "tiptoe, tense or sprite", "習慣腳尖承重", "weight on toes", "tiptoe standing habit"],
  ["amputee_arm", "單臂義體或空袖", "One-arm prosthetic", "缺失或義肢、故事、成年", "prosthetic or absent, adult", "一臂義肢或空袖", "one prosthetic or absent arm", "one arm prosthetic or empty sleeve, adult"],
  ["wheelchair_frame", "坐姿身形", "Seated build", "輪椅或常坐、上身發展", "seated, upper developed", "上身相對發達、髖坐姿", "seated hip, strong upper", "seated-body build, developed upper"],
  ["hunched_one_shoulder", "一肩高", "Uneven shoulders", "一肩高、傷或習慣", "uneven, injury habit", "兩肩不等高", "one shoulder higher", "uneven shoulders, one side higher"],
  ["tiny_waist_exag", "誇張細腰", "Exaggerated tiny waist", "二次元細腰、戲", "anime waist, stylized", "腰細到風格化", "stylized tiny waist", "exaggerated tiny waist, stylized"],
  ["heavyset_tall", "高而豐", "Tall heavyset", "又高又厚、分量", "tall and thick", "高身材加厚度", "tall plus mass", "tall heavyset, height plus mass"],
  ["compact_muscular", "矮精肌", "Compact muscular", "矮、密實肌、拳", "short, dense, fighter", "矮但肌密", "short dense muscle", "compact muscular, short dense fighter"]
]

const MARK: Row[] = [
  ["brow_slit", "眉骨釘疤", "Brow-slit scar", "眉斷、狠、故事", "split brow, tough", "眉一道斷疤", "scar through brow", "scar slitting the eyebrow"],
  ["bridge_scar", "鼻樑一字疤", "Bridge line scar", "鼻樑疤、打手", "bridge scar, fighter", "鼻樑細一字", "line on bridge", "scar on the nasal bridge"],
  ["cheek_slash", "頰刀疤", "Cheek slash", "頰長疤、江湖", "cheek slash, jianghu", "頰上一道長淺疤", "long cheek slash", "long shallow slash scar on cheek"],
  ["lip_stitch", "唇縫疤", "Stitched lip", "唇舊縫、狠或醫", "old stitches, lip", "唇舊縫合痕", "old lip suture", "old suture marks on lip"],
  ["forehead_bindi", "額心紅點", "Forehead bindi", "額點、儀式或妝", "bindi, ritual", "額心圓點", "dot at glabella", "forehead bindi, glabella dot"],
  ["third_eye_mark", "眉心印", "Third-eye mark", "仙、眉心紋、幻", "immortal, mark, fantasy", "眉心符號或豎印", "symbol at third eye", "third-eye mark at glabella"],
  ["ear_notch", "耳缺", "Notched ear", "耳一缺口、鬥或獸", "notch, fight or beast", "耳廓缺一塊", "notch in helix", "notched ear, missing helix piece"],
  ["stretched_lobe", "擴耳", "Stretched lobes", "擴、洞、地下", "gauges, underground", "耳垂擴大孔", "stretched plugs", "stretched earlobes, gauge holes"],
  ["many_rings", "多耳釘", "Many ear rings", "多環、閃、潮", "many rings, flash", "一耳多環多釘", "multiple piercings", "many ear piercings, stacked rings"],
  ["glabella_line", "眉心到鼻疤", "Glabella-to-nose scar", "連疤、故事長", "long story scar", "從眉心到鼻的細疤", "line down glabella", "scar from glabella down the nose"],
  ["burn_cheek", "頰淺燙", "Cheek burn sheen", "燙淺痕、反光不同", "burn sheen", "頰一塊淺燙膚", "patch of burn sheen", "faint burn sheen on cheek"],
  ["birth_wine_neck", "頸胎記", "Neck birthmark", "頸側胎記、露頸見", "neck mark, collar", "頸側不規則胎記", "irregular neck mark", "birthmark on the neck"],
  ["collarbone_mole", "鎖骨痣", "Collarbone mole", "鎖骨一痣、記", "clavicle mole", "鎖骨上一顆痣", "mole on clavicle", "mole on the collarbone"],
  ["hand_scar", "手背疤", "Hand-back scar", "手背舊傷、職人", "hand scar, craft", "手背淺疤", "scar on hand back", "scar on the back of the hand"],
  ["knuckle_tat", "指節字", "Knuckle letters", "指節字、黑或潮", "knuckle ink", "指節紋身字母", "lettering on knuckles", "knuckle letter tattoos"],
  ["face_gem", "面飾寶石", "Face gem", "妝飾、眉或淚位寶石", "gem, makeup jewelry", "淚位或眉一粒寶石", "gem at tear or brow", "face gem, decorative jewel on skin"],
  ["scale_patch", "局部鱗斑", "Scale patch", "非人、一塊鱗", "nonhuman, one patch", "頰或頸一塊鱗", "patch of scales", "localized scale patch on face or neck"],
  ["cracked_porcelain", "瓷裂紋", "Porcelain cracks", "人偶、臉淺裂", "doll, fine cracks", "臉如瓷細裂", "fine doll cracks", "porcelain crackle lines on skin"],
  ["barcode_neck", "頸條碼", "Neck barcode", "科幻、後頸碼", "scifi, nape code", "後頸條碼紋身", "barcode at nape", "barcode tattoo on the nape"],
  ["clan_brand", "族烙印", "Clan brand", "烙、族、肩或頸", "brand, clan", "淺烙印紋", "brand mark", "clan brand mark on neck or shoulder"],
  ["tear_tracks", "淚痕紋", "Tear-track stains", "舊淚軌、哀或妝", "old tear tracks", "從眼下兩道淡軌", "two faint tracks", "permanent tear-track stains"],
  ["smile_scar", "強制笑疤", "Forced-smile scars", "嘴角上拉舊傷", "corner cuts", "嘴角舊傷像被拉長", "old cuts at corners", "old scars lifting the mouth corners"],
  ["freckle_one", "單顆雀斑", "Single freckle", "一顆、鼻或頰、甜", "one spot, sweet", "只有一顆明顯雀斑", "one standalone freckle", "single prominent freckle"],
  ["dimple_one", "單側酒窩", "One-sided dimple", "只一邊、不對稱甜", "one side, asymmetric", "只一側有酒窩", "only one dimple", "one-sided dimple"],
  ["chin_cleft_mark", "頦溝加深", "Deep chin cleft", "頦溝深、記", "deep cleft, mark", "下巴溝特別深", "very deep chin cleft", "deep chin cleft as identifier"],
  ["white_lash", "一撮白睫", "White lash lock", "一撮白睫毛、魔", "white lashes, magic", "一眼幾根白睫", "few white lashes", "a few white eyelashes"],
  ["red_string_mark", "紅線印", "Red-string mark", "幻、腕或指紅線印", "fate, red mark", "腕或指淡紅線印", "faint red thread mark", "faint red-string fate mark on wrist"],
  ["star_freckle", "星屑斑", "Star-dust freckles", "幻、細金斑如星", "fantasy, gold dust", "細小金色斑點", "tiny gold flecks", "star-dust freckles, tiny gold flecks"],
  ["ice_burn", "凍傷斑", "Frostbite patch", "凍、耳或顴斑", "frost, ear or cheek", "淺凍傷色素", "frostbite pigment", "frostbite pigment patch"],
  ["sun_spot", "日晒深斑", "Age sun spots", "歲、深斑、成熟", "age spots, mature", "顴或手背深斑", "solar lentigines", "age sun spots, mature pigment"],
  ["vitiligo_eye", "眼周白斑", "Periocular pale", "眼周一圈淡、超常", "pale around eye", "一眼周圍淡白", "pale halo around one eye", "pale patch around one eye"],
  ["horn_nubs", "隱角基", "Horn nubs", "非人、額隱角", "nubs, demon-lite", "額兩點角基", "two nubs at hairline", "small horn nubs at the hairline"],
  ["elf_ear_mark", "尖耳", "Pointed elf ears", "尖耳、族、幻", "pointed, elf", "耳尖明顯", "pointed pinna", "pointed elf ears"],
  ["gill_slits", "頸鰓縫", "Gill slits", "非人、頸側縫", "gills, aquatic", "頸側淺鰓縫", "slits on neck", "gill slits on the neck"],
  ["circuit_temple", "太陽穴電路", "Temple circuits", "機、鬢電路", "circuit, cyborg", "太陽穴淺電路紋", "circuit at temple", "circuit lines at the temple"],
  ["barcode_wrist", "腕條碼", "Wrist barcode", "科幻、腕內碼", "scifi, inner wrist", "手腕內側條碼", "inner-wrist code", "barcode on the inner wrist"],
  ["ring_scar", "戒指勒痕", "Ring-scar band", "無名指勒痕、故事", "ring groove, story", "指上一圈舊痕", "groove on a finger", "pale ring-scar band on a finger"],
  ["collar_scar", "項圈舊痕", "Collar scar", "頸一圈舊痕、暗", "collar band, dark", "頸一圈淺痕", "band around neck", "pale collar scar around the neck"],
  ["none_clean", "完全素面", "Completely clean", "無任何標記", "unmarked, clean", "無痣無疤無飾", "no marks at all", "completely unmarked face and skin"],
  ["lash_scar_lid", "瞼緣細疤", "Lid-edge scar", "眼皮細疤、故事", "lid scar, story", "上瞼緣一道細疤", "fine scar on lid", "fine scar on the eyelid edge"],
  ["temple_mole", "太陽穴痣", "Temple mole", "鬢邊痣、記", "temple mole", "太陽穴一顆痣", "mole at temple", "mole at the temple"],
  ["jaw_scar", "下頜線疤", "Jawline scar", "頜緣淺疤、利", "jaw scar, edge", "下頜緣一道淺疤", "scar along jaw", "faint scar along the jawline"]
]

export const APPEARANCE_TEMPLATE_EXTRAS: AppearanceTemplateDef[] = [
  ...pack('face', FACE),
  ...pack('eyes', EYES),
  ...pack('nose', NOSE),
  ...pack('mouth', MOUTH),
  ...pack('hair', HAIR),
  ...pack('skin', SKIN),
  ...pack('body', BODY),
  ...pack('mark', MARK)
]
