/**
 * camera field kit catalog (50+ templates per part).
 */
import { defineFieldKit } from '../fieldKit'

export const CAMERA_KIT = defineFieldKit({
  key: "cameraKit",
  parts: ["shot","lens","move","height","focus","lighting"] as const,
  partLabels: {
    shot: { zhHK: "景別", zhCN: "景别", en: "Shot" },
    lens: { zhHK: "鏡頭", zhCN: "镜头", en: "Lens" },
    move: { zhHK: "運動", zhCN: "运动", en: "Move" },
    height: { zhHK: "機位高", zhCN: "机位高", en: "Height" },
    focus: { zhHK: "焦點", zhCN: "焦点", en: "Focus" },
    lighting: { zhHK: "光", zhCN: "光", en: "Lighting" }
  },

  rows: {
    shot: [
    ["ecu_court", "宮廷大特寫", "court extreme close-up", "大特、膚、宮廷", "ecu, skin, courtly", "宮廷氣場下的眼或唇大特", "in a courtly register, eye or lip ECU", "courtly, extreme close-up"],
    ["ecu_street", "街頭大特寫", "street extreme close-up", "大特、膚、街頭", "ecu, skin, street", "街頭質感的眼或唇大特", "with street grit, eye or lip ECU", "street-cast, extreme close-up"],
    ["ecu_noir", "暗黑大特寫", "noir extreme close-up", "大特、膚、暗黑", "ecu, skin, noir", "暗調電影感的眼或唇大特", "in noir lighting, eye or lip ECU", "noir, extreme close-up"],
    ["ecu_soft", "柔光大特寫", "soft-light extreme close-up", "大特、膚、柔光", "ecu, skin, soft", "柔光下的眼或唇大特", "under soft light, eye or lip ECU", "soft-lit, extreme close-up"],
    ["ecu_epic", "史詩大特寫", "epic extreme close-up", "大特、膚、史詩", "ecu, skin, epic", "史詩尺度的眼或唇大特", "at epic scale, eye or lip ECU", "epic, extreme close-up"],
    ["cu_court", "宮廷特寫", "court close-up", "特、臉、宮廷", "cu, face, courtly", "宮廷氣場下的臉部特寫", "in a courtly register, face close-up", "courtly, close-up"],
    ["cu_street", "街頭特寫", "street close-up", "特、臉、街頭", "cu, face, street", "街頭質感的臉部特寫", "with street grit, face close-up", "street-cast, close-up"],
    ["cu_noir", "暗黑特寫", "noir close-up", "特、臉、暗黑", "cu, face, noir", "暗調電影感的臉部特寫", "in noir lighting, face close-up", "noir, close-up"],
    ["cu_soft", "柔光特寫", "soft-light close-up", "特、臉、柔光", "cu, face, soft", "柔光下的臉部特寫", "under soft light, face close-up", "soft-lit, close-up"],
    ["cu_epic", "史詩特寫", "epic close-up", "特、臉、史詩", "cu, face, epic", "史詩尺度的臉部特寫", "at epic scale, face close-up", "epic, close-up"],
    ["mcu_court", "宮廷近景", "court medium close-up", "近、胸、宮廷", "mcu, chest, courtly", "宮廷氣場下的胸以上近景", "in a courtly register, chest-up MCU", "courtly, medium close-up"],
    ["mcu_street", "街頭近景", "street medium close-up", "近、胸、街頭", "mcu, chest, street", "街頭質感的胸以上近景", "with street grit, chest-up MCU", "street-cast, medium close-up"],
    ["mcu_noir", "暗黑近景", "noir medium close-up", "近、胸、暗黑", "mcu, chest, noir", "暗調電影感的胸以上近景", "in noir lighting, chest-up MCU", "noir, medium close-up"],
    ["mcu_soft", "柔光近景", "soft-light medium close-up", "近、胸、柔光", "mcu, chest, soft", "柔光下的胸以上近景", "under soft light, chest-up MCU", "soft-lit, medium close-up"],
    ["mcu_epic", "史詩近景", "epic medium close-up", "近、胸、史詩", "mcu, chest, epic", "史詩尺度的胸以上近景", "at epic scale, chest-up MCU", "epic, medium close-up"],
    ["ms_court", "宮廷中景", "court medium shot", "中、腰、宮廷", "ms, waist, courtly", "宮廷氣場下的腰以上中景", "in a courtly register, waist-up medium", "courtly, medium shot"],
    ["ms_street", "街頭中景", "street medium shot", "中、腰、街頭", "ms, waist, street", "街頭質感的腰以上中景", "with street grit, waist-up medium", "street-cast, medium shot"],
    ["ms_noir", "暗黑中景", "noir medium shot", "中、腰、暗黑", "ms, waist, noir", "暗調電影感的腰以上中景", "in noir lighting, waist-up medium", "noir, medium shot"],
    ["ms_soft", "柔光中景", "soft-light medium shot", "中、腰、柔光", "ms, waist, soft", "柔光下的腰以上中景", "under soft light, waist-up medium", "soft-lit, medium shot"],
    ["ms_epic", "史詩中景", "epic medium shot", "中、腰、史詩", "ms, waist, epic", "史詩尺度的腰以上中景", "at epic scale, waist-up medium", "epic, medium shot"],
    ["fs_court", "宮廷全身", "court full shot", "全、人、宮廷", "full, body, courtly", "宮廷氣場下的全身入畫", "in a courtly register, full body in frame", "courtly, full shot"],
    ["fs_street", "街頭全身", "street full shot", "全、人、街頭", "full, body, street", "街頭質感的全身入畫", "with street grit, full body in frame", "street-cast, full shot"],
    ["fs_noir", "暗黑全身", "noir full shot", "全、人、暗黑", "full, body, noir", "暗調電影感的全身入畫", "in noir lighting, full body in frame", "noir, full shot"],
    ["fs_soft", "柔光全身", "soft-light full shot", "全、人、柔光", "full, body, soft", "柔光下的全身入畫", "under soft light, full body in frame", "soft-lit, full shot"],
    ["fs_epic", "史詩全身", "epic full shot", "全、人、史詩", "full, body, epic", "史詩尺度的全身入畫", "at epic scale, full body in frame", "epic, full shot"],
    ["ws_court", "宮廷全景", "court wide shot", "全景、地、宮廷", "wide, place, courtly", "宮廷氣場下的人小景大", "in a courtly register, figure small in space", "courtly, wide shot"],
    ["ws_street", "街頭全景", "street wide shot", "全景、地、街頭", "wide, place, street", "街頭質感的人小景大", "with street grit, figure small in space", "street-cast, wide shot"],
    ["ws_noir", "暗黑全景", "noir wide shot", "全景、地、暗黑", "wide, place, noir", "暗調電影感的人小景大", "in noir lighting, figure small in space", "noir, wide shot"],
    ["ws_soft", "柔光全景", "soft-light wide shot", "全景、地、柔光", "wide, place, soft", "柔光下的人小景大", "under soft light, figure small in space", "soft-lit, wide shot"],
    ["ws_epic", "史詩全景", "epic wide shot", "全景、地、史詩", "wide, place, epic", "史詩尺度的人小景大", "at epic scale, figure small in space", "epic, wide shot"],
    ["ews_court", "宮廷大遠", "court extreme wide", "遠、渺、宮廷", "ews, tiny, courtly", "宮廷氣場下的人極小", "in a courtly register, tiny figure", "courtly, extreme wide shot"],
    ["ews_street", "街頭大遠", "street extreme wide", "遠、渺、街頭", "ews, tiny, street", "街頭質感的人極小", "with street grit, tiny figure", "street-cast, extreme wide shot"],
    ["ews_noir", "暗黑大遠", "noir extreme wide", "遠、渺、暗黑", "ews, tiny, noir", "暗調電影感的人極小", "in noir lighting, tiny figure", "noir, extreme wide shot"],
    ["ews_soft", "柔光大遠", "soft-light extreme wide", "遠、渺、柔光", "ews, tiny, soft", "柔光下的人極小", "under soft light, tiny figure", "soft-lit, extreme wide shot"],
    ["ews_epic", "史詩大遠", "epic extreme wide", "遠、渺、史詩", "ews, tiny, epic", "史詩尺度的人極小", "at epic scale, tiny figure", "epic, extreme wide shot"],
    ["ots_court", "宮廷過肩", "court over-shoulder", "過肩、對、宮廷", "ots, dialogue, courtly", "宮廷氣場下的過肩對話", "in a courtly register, OTS dialogue", "courtly, over-shoulder shot"],
    ["ots_street", "街頭過肩", "street over-shoulder", "過肩、對、街頭", "ots, dialogue, street", "街頭質感的過肩對話", "with street grit, OTS dialogue", "street-cast, over-shoulder shot"],
    ["ots_noir", "暗黑過肩", "noir over-shoulder", "過肩、對、暗黑", "ots, dialogue, noir", "暗調電影感的過肩對話", "in noir lighting, OTS dialogue", "noir, over-shoulder shot"],
    ["ots_soft", "柔光過肩", "soft-light over-shoulder", "過肩、對、柔光", "ots, dialogue, soft", "柔光下的過肩對話", "under soft light, OTS dialogue", "soft-lit, over-shoulder shot"],
    ["ots_epic", "史詩過肩", "epic over-shoulder", "過肩、對、史詩", "ots, dialogue, epic", "史詩尺度的過肩對話", "at epic scale, OTS dialogue", "epic, over-shoulder shot"],
    ["insert_court", "宮廷插入特", "court insert", "插入、物、宮廷", "insert, object, courtly", "宮廷氣場下的物件插入", "in a courtly register, object insert", "courtly, insert shot"],
    ["insert_street", "街頭插入特", "street insert", "插入、物、街頭", "insert, object, street", "街頭質感的物件插入", "with street grit, object insert", "street-cast, insert shot"],
    ["insert_noir", "暗黑插入特", "noir insert", "插入、物、暗黑", "insert, object, noir", "暗調電影感的物件插入", "in noir lighting, object insert", "noir, insert shot"],
    ["insert_soft", "柔光插入特", "soft-light insert", "插入、物、柔光", "insert, object, soft", "柔光下的物件插入", "under soft light, object insert", "soft-lit, insert shot"],
    ["insert_epic", "史詩插入特", "epic insert", "插入、物、史詩", "insert, object, epic", "史詩尺度的物件插入", "at epic scale, object insert", "epic, insert shot"],
    ["two_shot_court", "宮廷雙人", "court two-shot", "雙、關係、宮廷", "two, relation, courtly", "宮廷氣場下的兩人同框", "in a courtly register, two people framed", "courtly, two-shot"],
    ["two_shot_street", "街頭雙人", "street two-shot", "雙、關係、街頭", "two, relation, street", "街頭質感的兩人同框", "with street grit, two people framed", "street-cast, two-shot"],
    ["two_shot_noir", "暗黑雙人", "noir two-shot", "雙、關係、暗黑", "two, relation, noir", "暗調電影感的兩人同框", "in noir lighting, two people framed", "noir, two-shot"],
    ["two_shot_soft", "柔光雙人", "soft-light two-shot", "雙、關係、柔光", "two, relation, soft", "柔光下的兩人同框", "under soft light, two people framed", "soft-lit, two-shot"],
    ["two_shot_epic", "史詩雙人", "epic two-shot", "雙、關係、史詩", "two, relation, epic", "史詩尺度的兩人同框", "at epic scale, two people framed", "epic, two-shot"]
  ],
    lens: [
    ["24_court", "宮廷超廣 24", "court 24mm wide", "廣、畸、宮廷", "wide, distort, courtly", "宮廷氣場下的超廣輕畸變", "in a courtly register, slight wide distortion", "courtly, 24mm wide lens"],
    ["24_street", "街頭超廣 24", "street 24mm wide", "廣、畸、街頭", "wide, distort, street", "街頭質感的超廣輕畸變", "with street grit, slight wide distortion", "street-cast, 24mm wide lens"],
    ["24_noir", "暗黑超廣 24", "noir 24mm wide", "廣、畸、暗黑", "wide, distort, noir", "暗調電影感的超廣輕畸變", "in noir lighting, slight wide distortion", "noir, 24mm wide lens"],
    ["24_soft", "柔光超廣 24", "soft-light 24mm wide", "廣、畸、柔光", "wide, distort, soft", "柔光下的超廣輕畸變", "under soft light, slight wide distortion", "soft-lit, 24mm wide lens"],
    ["24_epic", "史詩超廣 24", "epic 24mm wide", "廣、畸、史詩", "wide, distort, epic", "史詩尺度的超廣輕畸變", "at epic scale, slight wide distortion", "epic, 24mm wide lens"],
    ["35_court", "宮廷35 環境", "court 35mm", "35、環、宮廷", "35, env, courtly", "宮廷氣場下的環境與人平衡", "in a courtly register, env-and-person balance", "courtly, 35mm lens"],
    ["35_street", "街頭35 環境", "street 35mm", "35、環、街頭", "35, env, street", "街頭質感的環境與人平衡", "with street grit, env-and-person balance", "street-cast, 35mm lens"],
    ["35_noir", "暗黑35 環境", "noir 35mm", "35、環、暗黑", "35, env, noir", "暗調電影感的環境與人平衡", "in noir lighting, env-and-person balance", "noir, 35mm lens"],
    ["35_soft", "柔光35 環境", "soft-light 35mm", "35、環、柔光", "35, env, soft", "柔光下的環境與人平衡", "under soft light, env-and-person balance", "soft-lit, 35mm lens"],
    ["35_epic", "史詩35 環境", "epic 35mm", "35、環、史詩", "35, env, epic", "史詩尺度的環境與人平衡", "at epic scale, env-and-person balance", "epic, 35mm lens"],
    ["50_court", "宮廷50 標準", "court 50mm", "50、眼、宮廷", "50, eye, courtly", "宮廷氣場下的接近人眼", "in a courtly register, near-eye view", "courtly, 50mm lens"],
    ["50_street", "街頭50 標準", "street 50mm", "50、眼、街頭", "50, eye, street", "街頭質感的接近人眼", "with street grit, near-eye view", "street-cast, 50mm lens"],
    ["50_noir", "暗黑50 標準", "noir 50mm", "50、眼、暗黑", "50, eye, noir", "暗調電影感的接近人眼", "in noir lighting, near-eye view", "noir, 50mm lens"],
    ["50_soft", "柔光50 標準", "soft-light 50mm", "50、眼、柔光", "50, eye, soft", "柔光下的接近人眼", "under soft light, near-eye view", "soft-lit, 50mm lens"],
    ["50_epic", "史詩50 標準", "epic 50mm", "50、眼、史詩", "50, eye, epic", "史詩尺度的接近人眼", "at epic scale, near-eye view", "epic, 50mm lens"],
    ["85_court", "宮廷85 人像", "court 85mm portrait", "85、虛、宮廷", "85, bokeh, courtly", "宮廷氣場下的人像虛化", "in a courtly register, portrait compression", "courtly, 85mm portrait lens"],
    ["85_street", "街頭85 人像", "street 85mm portrait", "85、虛、街頭", "85, bokeh, street", "街頭質感的人像虛化", "with street grit, portrait compression", "street-cast, 85mm portrait lens"],
    ["85_noir", "暗黑85 人像", "noir 85mm portrait", "85、虛、暗黑", "85, bokeh, noir", "暗調電影感的人像虛化", "in noir lighting, portrait compression", "noir, 85mm portrait lens"],
    ["85_soft", "柔光85 人像", "soft-light 85mm portrait", "85、虛、柔光", "85, bokeh, soft", "柔光下的人像虛化", "under soft light, portrait compression", "soft-lit, 85mm portrait lens"],
    ["85_epic", "史詩85 人像", "epic 85mm portrait", "85、虛、史詩", "85, bokeh, epic", "史詩尺度的人像虛化", "at epic scale, portrait compression", "epic, 85mm portrait lens"],
    ["135_court", "宮廷長焦壓", "court 135mm compress", "長、壓、宮廷", "long, compress, courtly", "宮廷氣場下的空間被壓扁", "in a courtly register, compressed space", "courtly, 135mm compressed lens"],
    ["135_street", "街頭長焦壓", "street 135mm compress", "長、壓、街頭", "long, compress, street", "街頭質感的空間被壓扁", "with street grit, compressed space", "street-cast, 135mm compressed lens"],
    ["135_noir", "暗黑長焦壓", "noir 135mm compress", "長、壓、暗黑", "long, compress, noir", "暗調電影感的空間被壓扁", "in noir lighting, compressed space", "noir, 135mm compressed lens"],
    ["135_soft", "柔光長焦壓", "soft-light 135mm compress", "長、壓、柔光", "long, compress, soft", "柔光下的空間被壓扁", "under soft light, compressed space", "soft-lit, 135mm compressed lens"],
    ["135_epic", "史詩長焦壓", "epic 135mm compress", "長、壓、史詩", "long, compress, epic", "史詩尺度的空間被壓扁", "at epic scale, compressed space", "epic, 135mm compressed lens"],
    ["macro_court", "宮廷微距", "court macro", "微、紋、宮廷", "macro, texture, courtly", "宮廷氣場下的極近紋理", "in a courtly register, extreme texture", "courtly, macro lens"],
    ["macro_street", "街頭微距", "street macro", "微、紋、街頭", "macro, texture, street", "街頭質感的極近紋理", "with street grit, extreme texture", "street-cast, macro lens"],
    ["macro_noir", "暗黑微距", "noir macro", "微、紋、暗黑", "macro, texture, noir", "暗調電影感的極近紋理", "in noir lighting, extreme texture", "noir, macro lens"],
    ["macro_soft", "柔光微距", "soft-light macro", "微、紋、柔光", "macro, texture, soft", "柔光下的極近紋理", "under soft light, extreme texture", "soft-lit, macro lens"],
    ["macro_epic", "史詩微距", "epic macro", "微、紋、史詩", "macro, texture, epic", "史詩尺度的極近紋理", "at epic scale, extreme texture", "epic, macro lens"],
    ["anamorphic_court", "宮廷變形寬", "court anamorphic", "寬、橢虛、宮廷", "ana, oval bokeh, courtly", "宮廷氣場下的寬銀幕變形", "in a courtly register, widescreen anamorphic", "courtly, anamorphic lens"],
    ["anamorphic_street", "街頭變形寬", "street anamorphic", "寬、橢虛、街頭", "ana, oval bokeh, street", "街頭質感的寬銀幕變形", "with street grit, widescreen anamorphic", "street-cast, anamorphic lens"],
    ["anamorphic_noir", "暗黑變形寬", "noir anamorphic", "寬、橢虛、暗黑", "ana, oval bokeh, noir", "暗調電影感的寬銀幕變形", "in noir lighting, widescreen anamorphic", "noir, anamorphic lens"],
    ["anamorphic_soft", "柔光變形寬", "soft-light anamorphic", "寬、橢虛、柔光", "ana, oval bokeh, soft", "柔光下的寬銀幕變形", "under soft light, widescreen anamorphic", "soft-lit, anamorphic lens"],
    ["anamorphic_epic", "史詩變形寬", "epic anamorphic", "寬、橢虛、史詩", "ana, oval bokeh, epic", "史詩尺度的寬銀幕變形", "at epic scale, widescreen anamorphic", "epic, anamorphic lens"],
    ["zoom_snap_court", "宮廷急推焦", "court snap zoom", "急推、戲、宮廷", "snap, drama, courtly", "宮廷氣場下的明顯急推", "in a courtly register, visible snap zoom", "courtly, snap-zoom lens move"],
    ["zoom_snap_street", "街頭急推焦", "street snap zoom", "急推、戲、街頭", "snap, drama, street", "街頭質感的明顯急推", "with street grit, visible snap zoom", "street-cast, snap-zoom lens move"],
    ["zoom_snap_noir", "暗黑急推焦", "noir snap zoom", "急推、戲、暗黑", "snap, drama, noir", "暗調電影感的明顯急推", "in noir lighting, visible snap zoom", "noir, snap-zoom lens move"],
    ["zoom_snap_soft", "柔光急推焦", "soft-light snap zoom", "急推、戲、柔光", "snap, drama, soft", "柔光下的明顯急推", "under soft light, visible snap zoom", "soft-lit, snap-zoom lens move"],
    ["zoom_snap_epic", "史詩急推焦", "epic snap zoom", "急推、戲、史詩", "snap, drama, epic", "史詩尺度的明顯急推", "at epic scale, visible snap zoom", "epic, snap-zoom lens move"],
    ["tilt_shift_court", "宮廷移軸", "court tilt-shift", "移、微縮、宮廷", "tilt, miniature, courtly", "宮廷氣場下的微縮移軸", "in a courtly register, miniature tilt-shift", "courtly, tilt-shift lens"],
    ["tilt_shift_street", "街頭移軸", "street tilt-shift", "移、微縮、街頭", "tilt, miniature, street", "街頭質感的微縮移軸", "with street grit, miniature tilt-shift", "street-cast, tilt-shift lens"],
    ["tilt_shift_noir", "暗黑移軸", "noir tilt-shift", "移、微縮、暗黑", "tilt, miniature, noir", "暗調電影感的微縮移軸", "in noir lighting, miniature tilt-shift", "noir, tilt-shift lens"],
    ["tilt_shift_soft", "柔光移軸", "soft-light tilt-shift", "移、微縮、柔光", "tilt, miniature, soft", "柔光下的微縮移軸", "under soft light, miniature tilt-shift", "soft-lit, tilt-shift lens"],
    ["tilt_shift_epic", "史詩移軸", "epic tilt-shift", "移、微縮、史詩", "tilt, miniature, epic", "史詩尺度的微縮移軸", "at epic scale, miniature tilt-shift", "epic, tilt-shift lens"],
    ["phone_court", "宮廷手機廣", "court phone wide", "手機、現、宮廷", "phone, now, courtly", "宮廷氣場下的手機超廣感", "in a courtly register, phone-wide look", "courtly, phone-wide lens"],
    ["phone_street", "街頭手機廣", "street phone wide", "手機、現、街頭", "phone, now, street", "街頭質感的手機超廣感", "with street grit, phone-wide look", "street-cast, phone-wide lens"],
    ["phone_noir", "暗黑手機廣", "noir phone wide", "手機、現、暗黑", "phone, now, noir", "暗調電影感的手機超廣感", "in noir lighting, phone-wide look", "noir, phone-wide lens"],
    ["phone_soft", "柔光手機廣", "soft-light phone wide", "手機、現、柔光", "phone, now, soft", "柔光下的手機超廣感", "under soft light, phone-wide look", "soft-lit, phone-wide lens"],
    ["phone_epic", "史詩手機廣", "epic phone wide", "手機、現、史詩", "phone, now, epic", "史詩尺度的手機超廣感", "at epic scale, phone-wide look", "epic, phone-wide lens"]
  ],
    move: [
    ["static_court", "宮廷鎖定", "court locked-off", "鎖、靜、宮廷", "lock, still, courtly", "宮廷氣場下的三腳架鎖定", "in a courtly register, tripod locked", "courtly, locked-off camera"],
    ["static_street", "街頭鎖定", "street locked-off", "鎖、靜、街頭", "lock, still, street", "街頭質感的三腳架鎖定", "with street grit, tripod locked", "street-cast, locked-off camera"],
    ["static_noir", "暗黑鎖定", "noir locked-off", "鎖、靜、暗黑", "lock, still, noir", "暗調電影感的三腳架鎖定", "in noir lighting, tripod locked", "noir, locked-off camera"],
    ["static_soft", "柔光鎖定", "soft-light locked-off", "鎖、靜、柔光", "lock, still, soft", "柔光下的三腳架鎖定", "under soft light, tripod locked", "soft-lit, locked-off camera"],
    ["static_epic", "史詩鎖定", "epic locked-off", "鎖、靜、史詩", "lock, still, epic", "史詩尺度的三腳架鎖定", "at epic scale, tripod locked", "epic, locked-off camera"],
    ["pan_court", "宮廷橫搖", "court pan", "搖、掃、宮廷", "pan, sweep, courtly", "宮廷氣場下的水平搖", "in a courtly register, horizontal pan", "courtly, panning move"],
    ["pan_street", "街頭橫搖", "street pan", "搖、掃、街頭", "pan, sweep, street", "街頭質感的水平搖", "with street grit, horizontal pan", "street-cast, panning move"],
    ["pan_noir", "暗黑橫搖", "noir pan", "搖、掃、暗黑", "pan, sweep, noir", "暗調電影感的水平搖", "in noir lighting, horizontal pan", "noir, panning move"],
    ["pan_soft", "柔光橫搖", "soft-light pan", "搖、掃、柔光", "pan, sweep, soft", "柔光下的水平搖", "under soft light, horizontal pan", "soft-lit, panning move"],
    ["pan_epic", "史詩橫搖", "epic pan", "搖、掃、史詩", "pan, sweep, epic", "史詩尺度的水平搖", "at epic scale, horizontal pan", "epic, panning move"],
    ["tilt_court", "宮廷直搖", "court tilt", "直搖、揭、宮廷", "tilt, reveal, courtly", "宮廷氣場下的上下搖", "in a courtly register, vertical tilt", "courtly, tilting move"],
    ["tilt_street", "街頭直搖", "street tilt", "直搖、揭、街頭", "tilt, reveal, street", "街頭質感的上下搖", "with street grit, vertical tilt", "street-cast, tilting move"],
    ["tilt_noir", "暗黑直搖", "noir tilt", "直搖、揭、暗黑", "tilt, reveal, noir", "暗調電影感的上下搖", "in noir lighting, vertical tilt", "noir, tilting move"],
    ["tilt_soft", "柔光直搖", "soft-light tilt", "直搖、揭、柔光", "tilt, reveal, soft", "柔光下的上下搖", "under soft light, vertical tilt", "soft-lit, tilting move"],
    ["tilt_epic", "史詩直搖", "epic tilt", "直搖、揭、史詩", "tilt, reveal, epic", "史詩尺度的上下搖", "at epic scale, vertical tilt", "epic, tilting move"],
    ["dolly_in_court", "宮廷推近", "court dolly in", "推、壓、宮廷", "dolly, press, courtly", "宮廷氣場下的軌道推近", "in a courtly register, dolly inward", "courtly, dolly-in move"],
    ["dolly_in_street", "街頭推近", "street dolly in", "推、壓、街頭", "dolly, press, street", "街頭質感的軌道推近", "with street grit, dolly inward", "street-cast, dolly-in move"],
    ["dolly_in_noir", "暗黑推近", "noir dolly in", "推、壓、暗黑", "dolly, press, noir", "暗調電影感的軌道推近", "in noir lighting, dolly inward", "noir, dolly-in move"],
    ["dolly_in_soft", "柔光推近", "soft-light dolly in", "推、壓、柔光", "dolly, press, soft", "柔光下的軌道推近", "under soft light, dolly inward", "soft-lit, dolly-in move"],
    ["dolly_in_epic", "史詩推近", "epic dolly in", "推、壓、史詩", "dolly, press, epic", "史詩尺度的軌道推近", "at epic scale, dolly inward", "epic, dolly-in move"],
    ["dolly_out_court", "宮廷拉遠", "court dolly out", "拉、孤、宮廷", "dolly out, isolate, courtly", "宮廷氣場下的軌道拉遠", "in a courtly register, dolly outward", "courtly, dolly-out move"],
    ["dolly_out_street", "街頭拉遠", "street dolly out", "拉、孤、街頭", "dolly out, isolate, street", "街頭質感的軌道拉遠", "with street grit, dolly outward", "street-cast, dolly-out move"],
    ["dolly_out_noir", "暗黑拉遠", "noir dolly out", "拉、孤、暗黑", "dolly out, isolate, noir", "暗調電影感的軌道拉遠", "in noir lighting, dolly outward", "noir, dolly-out move"],
    ["dolly_out_soft", "柔光拉遠", "soft-light dolly out", "拉、孤、柔光", "dolly out, isolate, soft", "柔光下的軌道拉遠", "under soft light, dolly outward", "soft-lit, dolly-out move"],
    ["dolly_out_epic", "史詩拉遠", "epic dolly out", "拉、孤、史詩", "dolly out, isolate, epic", "史詩尺度的軌道拉遠", "at epic scale, dolly outward", "epic, dolly-out move"],
    ["track_court", "宮廷橫移", "court tracking", "移、隨、宮廷", "track, follow, courtly", "宮廷氣場下的平行跟隨", "in a courtly register, lateral follow", "courtly, tracking move"],
    ["track_street", "街頭橫移", "street tracking", "移、隨、街頭", "track, follow, street", "街頭質感的平行跟隨", "with street grit, lateral follow", "street-cast, tracking move"],
    ["track_noir", "暗黑橫移", "noir tracking", "移、隨、暗黑", "track, follow, noir", "暗調電影感的平行跟隨", "in noir lighting, lateral follow", "noir, tracking move"],
    ["track_soft", "柔光橫移", "soft-light tracking", "移、隨、柔光", "track, follow, soft", "柔光下的平行跟隨", "under soft light, lateral follow", "soft-lit, tracking move"],
    ["track_epic", "史詩橫移", "epic tracking", "移、隨、史詩", "track, follow, epic", "史詩尺度的平行跟隨", "at epic scale, lateral follow", "epic, tracking move"],
    ["handheld_court", "宮廷手持呼吸", "court handheld breathe", "手持、活、宮廷", "hand, live, courtly", "宮廷氣場下的輕微呼吸手持", "in a courtly register, light handheld breathe", "courtly, handheld move"],
    ["handheld_street", "街頭手持呼吸", "street handheld breathe", "手持、活、街頭", "hand, live, street", "街頭質感的輕微呼吸手持", "with street grit, light handheld breathe", "street-cast, handheld move"],
    ["handheld_noir", "暗黑手持呼吸", "noir handheld breathe", "手持、活、暗黑", "hand, live, noir", "暗調電影感的輕微呼吸手持", "in noir lighting, light handheld breathe", "noir, handheld move"],
    ["handheld_soft", "柔光手持呼吸", "soft-light handheld breathe", "手持、活、柔光", "hand, live, soft", "柔光下的輕微呼吸手持", "under soft light, light handheld breathe", "soft-lit, handheld move"],
    ["handheld_epic", "史詩手持呼吸", "epic handheld breathe", "手持、活、史詩", "hand, live, epic", "史詩尺度的輕微呼吸手持", "at epic scale, light handheld breathe", "epic, handheld move"],
    ["steadicam_court", "宮廷穩定跟", "court steadicam", "穩、遊、宮廷", "steady, float, courtly", "宮廷氣場下的穩定器遊走", "in a courtly register, floated steadicam", "courtly, steadicam move"],
    ["steadicam_street", "街頭穩定跟", "street steadicam", "穩、遊、街頭", "steady, float, street", "街頭質感的穩定器遊走", "with street grit, floated steadicam", "street-cast, steadicam move"],
    ["steadicam_noir", "暗黑穩定跟", "noir steadicam", "穩、遊、暗黑", "steady, float, noir", "暗調電影感的穩定器遊走", "in noir lighting, floated steadicam", "noir, steadicam move"],
    ["steadicam_soft", "柔光穩定跟", "soft-light steadicam", "穩、遊、柔光", "steady, float, soft", "柔光下的穩定器遊走", "under soft light, floated steadicam", "soft-lit, steadicam move"],
    ["steadicam_epic", "史詩穩定跟", "epic steadicam", "穩、遊、史詩", "steady, float, epic", "史詩尺度的穩定器遊走", "at epic scale, floated steadicam", "epic, steadicam move"],
    ["crane_court", "宮廷搖臂升", "court crane up", "臂、升、宮廷", "crane, rise, courtly", "宮廷氣場下的由低升出", "in a courtly register, crane rising out", "courtly, crane move"],
    ["crane_street", "街頭搖臂升", "street crane up", "臂、升、街頭", "crane, rise, street", "街頭質感的由低升出", "with street grit, crane rising out", "street-cast, crane move"],
    ["crane_noir", "暗黑搖臂升", "noir crane up", "臂、升、暗黑", "crane, rise, noir", "暗調電影感的由低升出", "in noir lighting, crane rising out", "noir, crane move"],
    ["crane_soft", "柔光搖臂升", "soft-light crane up", "臂、升、柔光", "crane, rise, soft", "柔光下的由低升出", "under soft light, crane rising out", "soft-lit, crane move"],
    ["crane_epic", "史詩搖臂升", "epic crane up", "臂、升、史詩", "crane, rise, epic", "史詩尺度的由低升出", "at epic scale, crane rising out", "epic, crane move"],
    ["whip_court", "宮廷甩鏡", "court whip pan", "甩、接、宮廷", "whip, cut, courtly", "宮廷氣場下的快速甩接", "in a courtly register, fast whip", "courtly, whip-pan move"],
    ["whip_street", "街頭甩鏡", "street whip pan", "甩、接、街頭", "whip, cut, street", "街頭質感的快速甩接", "with street grit, fast whip", "street-cast, whip-pan move"],
    ["whip_noir", "暗黑甩鏡", "noir whip pan", "甩、接、暗黑", "whip, cut, noir", "暗調電影感的快速甩接", "in noir lighting, fast whip", "noir, whip-pan move"],
    ["whip_soft", "柔光甩鏡", "soft-light whip pan", "甩、接、柔光", "whip, cut, soft", "柔光下的快速甩接", "under soft light, fast whip", "soft-lit, whip-pan move"],
    ["whip_epic", "史詩甩鏡", "epic whip pan", "甩、接、史詩", "whip, cut, epic", "史詩尺度的快速甩接", "at epic scale, fast whip", "epic, whip-pan move"]
  ],
    height: [
    ["eye_court", "宮廷視平", "court eye level", "平、等、宮廷", "eye, equal, courtly", "宮廷氣場下的視平線機位", "in a courtly register, eye-level camera", "courtly, eye-level height"],
    ["eye_street", "街頭視平", "street eye level", "平、等、街頭", "eye, equal, street", "街頭質感的視平線機位", "with street grit, eye-level camera", "street-cast, eye-level height"],
    ["eye_noir", "暗黑視平", "noir eye level", "平、等、暗黑", "eye, equal, noir", "暗調電影感的視平線機位", "in noir lighting, eye-level camera", "noir, eye-level height"],
    ["eye_soft", "柔光視平", "soft-light eye level", "平、等、柔光", "eye, equal, soft", "柔光下的視平線機位", "under soft light, eye-level camera", "soft-lit, eye-level height"],
    ["eye_epic", "史詩視平", "epic eye level", "平、等、史詩", "eye, equal, epic", "史詩尺度的視平線機位", "at epic scale, eye-level camera", "epic, eye-level height"],
    ["low_court", "宮廷低機", "court low angle", "低、仰、宮廷", "low, hero, courtly", "宮廷氣場下的仰拍低機", "in a courtly register, low heroic angle", "courtly, low-angle height"],
    ["low_street", "街頭低機", "street low angle", "低、仰、街頭", "low, hero, street", "街頭質感的仰拍低機", "with street grit, low heroic angle", "street-cast, low-angle height"],
    ["low_noir", "暗黑低機", "noir low angle", "低、仰、暗黑", "low, hero, noir", "暗調電影感的仰拍低機", "in noir lighting, low heroic angle", "noir, low-angle height"],
    ["low_soft", "柔光低機", "soft-light low angle", "低、仰、柔光", "low, hero, soft", "柔光下的仰拍低機", "under soft light, low heroic angle", "soft-lit, low-angle height"],
    ["low_epic", "史詩低機", "epic low angle", "低、仰、史詩", "low, hero, epic", "史詩尺度的仰拍低機", "at epic scale, low heroic angle", "epic, low-angle height"],
    ["high_court", "宮廷高機", "court high angle", "高、壓、宮廷", "high, press, courtly", "宮廷氣場下的俯壓高機", "in a courtly register, high pressing angle", "courtly, high-angle height"],
    ["high_street", "街頭高機", "street high angle", "高、壓、街頭", "high, press, street", "街頭質感的俯壓高機", "with street grit, high pressing angle", "street-cast, high-angle height"],
    ["high_noir", "暗黑高機", "noir high angle", "高、壓、暗黑", "high, press, noir", "暗調電影感的俯壓高機", "in noir lighting, high pressing angle", "noir, high-angle height"],
    ["high_soft", "柔光高機", "soft-light high angle", "高、壓、柔光", "high, press, soft", "柔光下的俯壓高機", "under soft light, high pressing angle", "soft-lit, high-angle height"],
    ["high_epic", "史詩高機", "epic high angle", "高、壓、史詩", "high, press, epic", "史詩尺度的俯壓高機", "at epic scale, high pressing angle", "epic, high-angle height"],
    ["ground_court", "宮廷貼地", "court ground", "地、蟲、宮廷", "ground, bug, courtly", "宮廷氣場下的幾乎貼地", "in a courtly register, almost on the ground", "courtly, ground-level height"],
    ["ground_street", "街頭貼地", "street ground", "地、蟲、街頭", "ground, bug, street", "街頭質感的幾乎貼地", "with street grit, almost on the ground", "street-cast, ground-level height"],
    ["ground_noir", "暗黑貼地", "noir ground", "地、蟲、暗黑", "ground, bug, noir", "暗調電影感的幾乎貼地", "in noir lighting, almost on the ground", "noir, ground-level height"],
    ["ground_soft", "柔光貼地", "soft-light ground", "地、蟲、柔光", "ground, bug, soft", "柔光下的幾乎貼地", "under soft light, almost on the ground", "soft-lit, ground-level height"],
    ["ground_epic", "史詩貼地", "epic ground", "地、蟲、史詩", "ground, bug, epic", "史詩尺度的幾乎貼地", "at epic scale, almost on the ground", "epic, ground-level height"],
    ["overhead_court", "宮廷頂視", "court overhead", "頂、圖、宮廷", "top, map, courtly", "宮廷氣場下的正頂俯視", "in a courtly register, true overhead", "courtly, overhead height"],
    ["overhead_street", "街頭頂視", "street overhead", "頂、圖、街頭", "top, map, street", "街頭質感的正頂俯視", "with street grit, true overhead", "street-cast, overhead height"],
    ["overhead_noir", "暗黑頂視", "noir overhead", "頂、圖、暗黑", "top, map, noir", "暗調電影感的正頂俯視", "in noir lighting, true overhead", "noir, overhead height"],
    ["overhead_soft", "柔光頂視", "soft-light overhead", "頂、圖、柔光", "top, map, soft", "柔光下的正頂俯視", "under soft light, true overhead", "soft-lit, overhead height"],
    ["overhead_epic", "史詩頂視", "epic overhead", "頂、圖、史詩", "top, map, epic", "史詩尺度的正頂俯視", "at epic scale, true overhead", "epic, overhead height"],
    ["hip_court", "宮廷腰位", "court hip height", "腰、跟、宮廷", "hip, follow, courtly", "宮廷氣場下的腰高跟隨", "in a courtly register, hip-height follow", "courtly, hip-height camera"],
    ["hip_street", "街頭腰位", "street hip height", "腰、跟、街頭", "hip, follow, street", "街頭質感的腰高跟隨", "with street grit, hip-height follow", "street-cast, hip-height camera"],
    ["hip_noir", "暗黑腰位", "noir hip height", "腰、跟、暗黑", "hip, follow, noir", "暗調電影感的腰高跟隨", "in noir lighting, hip-height follow", "noir, hip-height camera"],
    ["hip_soft", "柔光腰位", "soft-light hip height", "腰、跟、柔光", "hip, follow, soft", "柔光下的腰高跟隨", "under soft light, hip-height follow", "soft-lit, hip-height camera"],
    ["hip_epic", "史詩腰位", "epic hip height", "腰、跟、史詩", "hip, follow, epic", "史詩尺度的腰高跟隨", "at epic scale, hip-height follow", "epic, hip-height camera"],
    ["ceiling_court", "宮廷近天花", "court near ceiling", "天花、壓、宮廷", "ceiling, crush, courtly", "宮廷氣場下的近天花俯", "in a courtly register, near-ceiling look-down", "courtly, ceiling-height camera"],
    ["ceiling_street", "街頭近天花", "street near ceiling", "天花、壓、街頭", "ceiling, crush, street", "街頭質感的近天花俯", "with street grit, near-ceiling look-down", "street-cast, ceiling-height camera"],
    ["ceiling_noir", "暗黑近天花", "noir near ceiling", "天花、壓、暗黑", "ceiling, crush, noir", "暗調電影感的近天花俯", "in noir lighting, near-ceiling look-down", "noir, ceiling-height camera"],
    ["ceiling_soft", "柔光近天花", "soft-light near ceiling", "天花、壓、柔光", "ceiling, crush, soft", "柔光下的近天花俯", "under soft light, near-ceiling look-down", "soft-lit, ceiling-height camera"],
    ["ceiling_epic", "史詩近天花", "epic near ceiling", "天花、壓、史詩", "ceiling, crush, epic", "史詩尺度的近天花俯", "at epic scale, near-ceiling look-down", "epic, ceiling-height camera"],
    ["dutch_court", "宮廷荷蘭傾", "court dutch angle", "傾、不穩、宮廷", "dutch, unease, courtly", "宮廷氣場下的地平線斜", "in a courtly register, tilted horizon", "courtly, dutch-angle height"],
    ["dutch_street", "街頭荷蘭傾", "street dutch angle", "傾、不穩、街頭", "dutch, unease, street", "街頭質感的地平線斜", "with street grit, tilted horizon", "street-cast, dutch-angle height"],
    ["dutch_noir", "暗黑荷蘭傾", "noir dutch angle", "傾、不穩、暗黑", "dutch, unease, noir", "暗調電影感的地平線斜", "in noir lighting, tilted horizon", "noir, dutch-angle height"],
    ["dutch_soft", "柔光荷蘭傾", "soft-light dutch angle", "傾、不穩、柔光", "dutch, unease, soft", "柔光下的地平線斜", "under soft light, tilted horizon", "soft-lit, dutch-angle height"],
    ["dutch_epic", "史詩荷蘭傾", "epic dutch angle", "傾、不穩、史詩", "dutch, unease, epic", "史詩尺度的地平線斜", "at epic scale, tilted horizon", "epic, dutch-angle height"],
    ["shoulder_court", "宮廷過肩高", "court shoulder height", "肩、對、宮廷", "shoulder, talk, courtly", "宮廷氣場下的略高過肩", "in a courtly register, just over shoulder", "courtly, shoulder-height camera"],
    ["shoulder_street", "街頭過肩高", "street shoulder height", "肩、對、街頭", "shoulder, talk, street", "街頭質感的略高過肩", "with street grit, just over shoulder", "street-cast, shoulder-height camera"],
    ["shoulder_noir", "暗黑過肩高", "noir shoulder height", "肩、對、暗黑", "shoulder, talk, noir", "暗調電影感的略高過肩", "in noir lighting, just over shoulder", "noir, shoulder-height camera"],
    ["shoulder_soft", "柔光過肩高", "soft-light shoulder height", "肩、對、柔光", "shoulder, talk, soft", "柔光下的略高過肩", "under soft light, just over shoulder", "soft-lit, shoulder-height camera"],
    ["shoulder_epic", "史詩過肩高", "epic shoulder height", "肩、對、史詩", "shoulder, talk, epic", "史詩尺度的略高過肩", "at epic scale, just over shoulder", "epic, shoulder-height camera"],
    ["floating_court", "宮廷懸浮中", "court floating mid", "懸、夢、宮廷", "float, dream, courtly", "宮廷氣場下的不接地的中高", "in a courtly register, ungrounded mid-high", "courtly, floating mid height"],
    ["floating_street", "街頭懸浮中", "street floating mid", "懸、夢、街頭", "float, dream, street", "街頭質感的不接地的中高", "with street grit, ungrounded mid-high", "street-cast, floating mid height"],
    ["floating_noir", "暗黑懸浮中", "noir floating mid", "懸、夢、暗黑", "float, dream, noir", "暗調電影感的不接地的中高", "in noir lighting, ungrounded mid-high", "noir, floating mid height"],
    ["floating_soft", "柔光懸浮中", "soft-light floating mid", "懸、夢、柔光", "float, dream, soft", "柔光下的不接地的中高", "under soft light, ungrounded mid-high", "soft-lit, floating mid height"],
    ["floating_epic", "史詩懸浮中", "epic floating mid", "懸、夢、史詩", "float, dream, epic", "史詩尺度的不接地的中高", "at epic scale, ungrounded mid-high", "epic, floating mid height"]
  ],
    focus: [
    ["deep_court", "宮廷全深", "court deep focus", "深、全清、宮廷", "deep, all sharp, courtly", "宮廷氣場下的前後都清", "in a courtly register, foreground and back sharp", "courtly, deep focus"],
    ["deep_street", "街頭全深", "street deep focus", "深、全清、街頭", "deep, all sharp, street", "街頭質感的前後都清", "with street grit, foreground and back sharp", "street-cast, deep focus"],
    ["deep_noir", "暗黑全深", "noir deep focus", "深、全清、暗黑", "deep, all sharp, noir", "暗調電影感的前後都清", "in noir lighting, foreground and back sharp", "noir, deep focus"],
    ["deep_soft", "柔光全深", "soft-light deep focus", "深、全清、柔光", "deep, all sharp, soft", "柔光下的前後都清", "under soft light, foreground and back sharp", "soft-lit, deep focus"],
    ["deep_epic", "史詩全深", "epic deep focus", "深、全清、史詩", "deep, all sharp, epic", "史詩尺度的前後都清", "at epic scale, foreground and back sharp", "epic, deep focus"],
    ["shallow_court", "宮廷淺景深", "court shallow", "淺、離、宮廷", "shallow, isolate, courtly", "宮廷氣場下的主體外大虛", "in a courtly register, heavy subject isolation", "courtly, shallow focus"],
    ["shallow_street", "街頭淺景深", "street shallow", "淺、離、街頭", "shallow, isolate, street", "街頭質感的主體外大虛", "with street grit, heavy subject isolation", "street-cast, shallow focus"],
    ["shallow_noir", "暗黑淺景深", "noir shallow", "淺、離、暗黑", "shallow, isolate, noir", "暗調電影感的主體外大虛", "in noir lighting, heavy subject isolation", "noir, shallow focus"],
    ["shallow_soft", "柔光淺景深", "soft-light shallow", "淺、離、柔光", "shallow, isolate, soft", "柔光下的主體外大虛", "under soft light, heavy subject isolation", "soft-lit, shallow focus"],
    ["shallow_epic", "史詩淺景深", "epic shallow", "淺、離、史詩", "shallow, isolate, epic", "史詩尺度的主體外大虛", "at epic scale, heavy subject isolation", "epic, shallow focus"],
    ["rack_court", "宮廷移焦", "court rack focus", "移、轉、宮廷", "rack, shift, courtly", "宮廷氣場下的焦點轉移", "in a courtly register, focus racks between", "courtly, rack focus"],
    ["rack_street", "街頭移焦", "street rack focus", "移、轉、街頭", "rack, shift, street", "街頭質感的焦點轉移", "with street grit, focus racks between", "street-cast, rack focus"],
    ["rack_noir", "暗黑移焦", "noir rack focus", "移、轉、暗黑", "rack, shift, noir", "暗調電影感的焦點轉移", "in noir lighting, focus racks between", "noir, rack focus"],
    ["rack_soft", "柔光移焦", "soft-light rack focus", "移、轉、柔光", "rack, shift, soft", "柔光下的焦點轉移", "under soft light, focus racks between", "soft-lit, rack focus"],
    ["rack_epic", "史詩移焦", "epic rack focus", "移、轉、史詩", "rack, shift, epic", "史詩尺度的焦點轉移", "at epic scale, focus racks between", "epic, rack focus"],
    ["soft_court", "宮廷全柔", "court soft focus", "柔、夢、宮廷", "soft, dream, courtly", "宮廷氣場下的整體偏柔", "in a courtly register, overall soft", "courtly, soft focus"],
    ["soft_street", "街頭全柔", "street soft focus", "柔、夢、街頭", "soft, dream, street", "街頭質感的整體偏柔", "with street grit, overall soft", "street-cast, soft focus"],
    ["soft_noir", "暗黑全柔", "noir soft focus", "柔、夢、暗黑", "soft, dream, noir", "暗調電影感的整體偏柔", "in noir lighting, overall soft", "noir, soft focus"],
    ["soft_soft", "柔光全柔", "soft-light soft focus", "柔、夢、柔光", "soft, dream, soft", "柔光下的整體偏柔", "under soft light, overall soft", "soft-lit, soft focus"],
    ["soft_epic", "史詩全柔", "epic soft focus", "柔、夢、史詩", "soft, dream, epic", "史詩尺度的整體偏柔", "at epic scale, overall soft", "epic, soft focus"],
    ["split_diopter_court", "宮廷分裂屈光", "court split diopter", "裂、前後清、宮廷", "split, two sharp, courtly", "宮廷氣場下的前後兩層都清", "in a courtly register, two planes sharp", "courtly, split-diopter focus"],
    ["split_diopter_street", "街頭分裂屈光", "street split diopter", "裂、前後清、街頭", "split, two sharp, street", "街頭質感的前後兩層都清", "with street grit, two planes sharp", "street-cast, split-diopter focus"],
    ["split_diopter_noir", "暗黑分裂屈光", "noir split diopter", "裂、前後清、暗黑", "split, two sharp, noir", "暗調電影感的前後兩層都清", "in noir lighting, two planes sharp", "noir, split-diopter focus"],
    ["split_diopter_soft", "柔光分裂屈光", "soft-light split diopter", "裂、前後清、柔光", "split, two sharp, soft", "柔光下的前後兩層都清", "under soft light, two planes sharp", "soft-lit, split-diopter focus"],
    ["split_diopter_epic", "史詩分裂屈光", "epic split diopter", "裂、前後清、史詩", "split, two sharp, epic", "史詩尺度的前後兩層都清", "at epic scale, two planes sharp", "epic, split-diopter focus"],
    ["hunt_court", "宮廷找焦", "court hunting focus", "找、手持、宮廷", "hunt, live, courtly", "宮廷氣場下的微微找焦", "in a courtly register, slight focus hunt", "courtly, hunting focus"],
    ["hunt_street", "街頭找焦", "street hunting focus", "找、手持、街頭", "hunt, live, street", "街頭質感的微微找焦", "with street grit, slight focus hunt", "street-cast, hunting focus"],
    ["hunt_noir", "暗黑找焦", "noir hunting focus", "找、手持、暗黑", "hunt, live, noir", "暗調電影感的微微找焦", "in noir lighting, slight focus hunt", "noir, hunting focus"],
    ["hunt_soft", "柔光找焦", "soft-light hunting focus", "找、手持、柔光", "hunt, live, soft", "柔光下的微微找焦", "under soft light, slight focus hunt", "soft-lit, hunting focus"],
    ["hunt_epic", "史詩找焦", "epic hunting focus", "找、手持、史詩", "hunt, live, epic", "史詩尺度的微微找焦", "at epic scale, slight focus hunt", "epic, hunting focus"],
    ["face_lock_court", "宮廷鎖臉", "court face-locked", "臉、釘、宮廷", "face, pin, courtly", "宮廷氣場下的焦釘在臉", "in a courtly register, focus pinned on face", "courtly, face-locked focus"],
    ["face_lock_street", "街頭鎖臉", "street face-locked", "臉、釘、街頭", "face, pin, street", "街頭質感的焦釘在臉", "with street grit, focus pinned on face", "street-cast, face-locked focus"],
    ["face_lock_noir", "暗黑鎖臉", "noir face-locked", "臉、釘、暗黑", "face, pin, noir", "暗調電影感的焦釘在臉", "in noir lighting, focus pinned on face", "noir, face-locked focus"],
    ["face_lock_soft", "柔光鎖臉", "soft-light face-locked", "臉、釘、柔光", "face, pin, soft", "柔光下的焦釘在臉", "under soft light, focus pinned on face", "soft-lit, face-locked focus"],
    ["face_lock_epic", "史詩鎖臉", "epic face-locked", "臉、釘、史詩", "face, pin, epic", "史詩尺度的焦釘在臉", "at epic scale, focus pinned on face", "epic, face-locked focus"],
    ["bg_first_court", "宮廷先背景", "court background first", "背、揭、宮廷", "bg, reveal, courtly", "宮廷氣場下的先清背景再回", "in a courtly register, bg sharp then rack", "courtly, background-first focus"],
    ["bg_first_street", "街頭先背景", "street background first", "背、揭、街頭", "bg, reveal, street", "街頭質感的先清背景再回", "with street grit, bg sharp then rack", "street-cast, background-first focus"],
    ["bg_first_noir", "暗黑先背景", "noir background first", "背、揭、暗黑", "bg, reveal, noir", "暗調電影感的先清背景再回", "in noir lighting, bg sharp then rack", "noir, background-first focus"],
    ["bg_first_soft", "柔光先背景", "soft-light background first", "背、揭、柔光", "bg, reveal, soft", "柔光下的先清背景再回", "under soft light, bg sharp then rack", "soft-lit, background-first focus"],
    ["bg_first_epic", "史詩先背景", "epic background first", "背、揭、史詩", "bg, reveal, epic", "史詩尺度的先清背景再回", "at epic scale, bg sharp then rack", "epic, background-first focus"],
    ["edge_court", "宮廷鋒利現代", "court biting sharp", "利、現、宮廷", "sharp, modern, courtly", "宮廷氣場下的邊緣極利", "in a courtly register, biting edge sharpness", "courtly, biting-sharp focus"],
    ["edge_street", "街頭鋒利現代", "street biting sharp", "利、現、街頭", "sharp, modern, street", "街頭質感的邊緣極利", "with street grit, biting edge sharpness", "street-cast, biting-sharp focus"],
    ["edge_noir", "暗黑鋒利現代", "noir biting sharp", "利、現、暗黑", "sharp, modern, noir", "暗調電影感的邊緣極利", "in noir lighting, biting edge sharpness", "noir, biting-sharp focus"],
    ["edge_soft", "柔光鋒利現代", "soft-light biting sharp", "利、現、柔光", "sharp, modern, soft", "柔光下的邊緣極利", "under soft light, biting edge sharpness", "soft-lit, biting-sharp focus"],
    ["edge_epic", "史詩鋒利現代", "epic biting sharp", "利、現、史詩", "sharp, modern, epic", "史詩尺度的邊緣極利", "at epic scale, biting edge sharpness", "epic, biting-sharp focus"],
    ["vintage_haze_court", "宮廷舊柔霧", "court vintage haze", "霧、舊、宮廷", "haze, vintage, courtly", "宮廷氣場下的輕霧柔焦", "in a courtly register, light vintage haze", "courtly, vintage-haze focus"],
    ["vintage_haze_street", "街頭舊柔霧", "street vintage haze", "霧、舊、街頭", "haze, vintage, street", "街頭質感的輕霧柔焦", "with street grit, light vintage haze", "street-cast, vintage-haze focus"],
    ["vintage_haze_noir", "暗黑舊柔霧", "noir vintage haze", "霧、舊、暗黑", "haze, vintage, noir", "暗調電影感的輕霧柔焦", "in noir lighting, light vintage haze", "noir, vintage-haze focus"],
    ["vintage_haze_soft", "柔光舊柔霧", "soft-light vintage haze", "霧、舊、柔光", "haze, vintage, soft", "柔光下的輕霧柔焦", "under soft light, light vintage haze", "soft-lit, vintage-haze focus"],
    ["vintage_haze_epic", "史詩舊柔霧", "epic vintage haze", "霧、舊、史詩", "haze, vintage, epic", "史詩尺度的輕霧柔焦", "at epic scale, light vintage haze", "epic, vintage-haze focus"]
  ],
    lighting: [
    ["soft_key_court", "宮廷柔主光", "court soft key", "柔、美、宮廷", "soft, beauty, courtly", "宮廷氣場下的大柔主光", "in a courtly register, large soft key", "courtly, soft key lighting"],
    ["soft_key_street", "街頭柔主光", "street soft key", "柔、美、街頭", "soft, beauty, street", "街頭質感的大柔主光", "with street grit, large soft key", "street-cast, soft key lighting"],
    ["soft_key_noir", "暗黑柔主光", "noir soft key", "柔、美、暗黑", "soft, beauty, noir", "暗調電影感的大柔主光", "in noir lighting, large soft key", "noir, soft key lighting"],
    ["soft_key_soft", "柔光柔主光", "soft-light soft key", "柔、美、柔光", "soft, beauty, soft", "柔光下的大柔主光", "under soft light, large soft key", "soft-lit, soft key lighting"],
    ["soft_key_epic", "史詩柔主光", "epic soft key", "柔、美、史詩", "soft, beauty, epic", "史詩尺度的大柔主光", "at epic scale, large soft key", "epic, soft key lighting"],
    ["hard_noir_court", "宮廷硬陰影", "court hard noir", "硬、影、宮廷", "hard, noir, courtly", "宮廷氣場下的硬光深影", "in a courtly register, hard light, deep shadow", "courtly, hard noir lighting"],
    ["hard_noir_street", "街頭硬陰影", "street hard noir", "硬、影、街頭", "hard, noir, street", "街頭質感的硬光深影", "with street grit, hard light, deep shadow", "street-cast, hard noir lighting"],
    ["hard_noir_noir", "暗黑硬陰影", "noir hard noir", "硬、影、暗黑", "hard, noir, noir", "暗調電影感的硬光深影", "in noir lighting, hard light, deep shadow", "noir, hard noir lighting"],
    ["hard_noir_soft", "柔光硬陰影", "soft-light hard noir", "硬、影、柔光", "hard, noir, soft", "柔光下的硬光深影", "under soft light, hard light, deep shadow", "soft-lit, hard noir lighting"],
    ["hard_noir_epic", "史詩硬陰影", "epic hard noir", "硬、影、史詩", "hard, noir, epic", "史詩尺度的硬光深影", "at epic scale, hard light, deep shadow", "epic, hard noir lighting"],
    ["window_court", "宮廷窗光", "court window light", "窗、側、宮廷", "window, side, courtly", "宮廷氣場下的單側窗光", "in a courtly register, single window side", "courtly, window lighting"],
    ["window_street", "街頭窗光", "street window light", "窗、側、街頭", "window, side, street", "街頭質感的單側窗光", "with street grit, single window side", "street-cast, window lighting"],
    ["window_noir", "暗黑窗光", "noir window light", "窗、側、暗黑", "window, side, noir", "暗調電影感的單側窗光", "in noir lighting, single window side", "noir, window lighting"],
    ["window_soft", "柔光窗光", "soft-light window light", "窗、側、柔光", "window, side, soft", "柔光下的單側窗光", "under soft light, single window side", "soft-lit, window lighting"],
    ["window_epic", "史詩窗光", "epic window light", "窗、側、史詩", "window, side, epic", "史詩尺度的單側窗光", "at epic scale, single window side", "epic, window lighting"],
    ["top_court", "宮廷頂光壓", "court top light", "頂、骷、宮廷", "top, skull, courtly", "宮廷氣場下的頂光壓眼窩", "in a courtly register, top light in sockets", "courtly, top lighting"],
    ["top_street", "街頭頂光壓", "street top light", "頂、骷、街頭", "top, skull, street", "街頭質感的頂光壓眼窩", "with street grit, top light in sockets", "street-cast, top lighting"],
    ["top_noir", "暗黑頂光壓", "noir top light", "頂、骷、暗黑", "top, skull, noir", "暗調電影感的頂光壓眼窩", "in noir lighting, top light in sockets", "noir, top lighting"],
    ["top_soft", "柔光頂光壓", "soft-light top light", "頂、骷、柔光", "top, skull, soft", "柔光下的頂光壓眼窩", "under soft light, top light in sockets", "soft-lit, top lighting"],
    ["top_epic", "史詩頂光壓", "epic top light", "頂、骷、史詩", "top, skull, epic", "史詩尺度的頂光壓眼窩", "at epic scale, top light in sockets", "epic, top lighting"],
    ["practical_only_court", "宮廷只靠實光", "court practicals only", "實、真、宮廷", "practical, real, courtly", "宮廷氣場下的幾乎只靠道具燈", "in a courtly register, motivated practicals only", "courtly, practicals-only lighting"],
    ["practical_only_street", "街頭只靠實光", "street practicals only", "實、真、街頭", "practical, real, street", "街頭質感的幾乎只靠道具燈", "with street grit, motivated practicals only", "street-cast, practicals-only lighting"],
    ["practical_only_noir", "暗黑只靠實光", "noir practicals only", "實、真、暗黑", "practical, real, noir", "暗調電影感的幾乎只靠道具燈", "in noir lighting, motivated practicals only", "noir, practicals-only lighting"],
    ["practical_only_soft", "柔光只靠實光", "soft-light practicals only", "實、真、柔光", "practical, real, soft", "柔光下的幾乎只靠道具燈", "under soft light, motivated practicals only", "soft-lit, practicals-only lighting"],
    ["practical_only_epic", "史詩只靠實光", "epic practicals only", "實、真、史詩", "practical, real, epic", "史詩尺度的幾乎只靠道具燈", "at epic scale, motivated practicals only", "epic, practicals-only lighting"],
    ["neon_mix_court", "宮廷霓虹混", "court mixed neon", "霓、色、宮廷", "neon, mix, courtly", "宮廷氣場下的多色霓虹混", "in a courtly register, mixed neon colors", "courtly, mixed neon lighting"],
    ["neon_mix_street", "街頭霓虹混", "street mixed neon", "霓、色、街頭", "neon, mix, street", "街頭質感的多色霓虹混", "with street grit, mixed neon colors", "street-cast, mixed neon lighting"],
    ["neon_mix_noir", "暗黑霓虹混", "noir mixed neon", "霓、色、暗黑", "neon, mix, noir", "暗調電影感的多色霓虹混", "in noir lighting, mixed neon colors", "noir, mixed neon lighting"],
    ["neon_mix_soft", "柔光霓虹混", "soft-light mixed neon", "霓、色、柔光", "neon, mix, soft", "柔光下的多色霓虹混", "under soft light, mixed neon colors", "soft-lit, mixed neon lighting"],
    ["neon_mix_epic", "史詩霓虹混", "epic mixed neon", "霓、色、史詩", "neon, mix, epic", "史詩尺度的多色霓虹混", "at epic scale, mixed neon colors", "epic, mixed neon lighting"],
    ["golden_court", "宮廷金色時", "court golden hour", "金、側暖、宮廷", "gold, warm side, courtly", "宮廷氣場下的低角度暖金", "in a courtly register, low warm gold", "courtly, golden-hour lighting"],
    ["golden_street", "街頭金色時", "street golden hour", "金、側暖、街頭", "gold, warm side, street", "街頭質感的低角度暖金", "with street grit, low warm gold", "street-cast, golden-hour lighting"],
    ["golden_noir", "暗黑金色時", "noir golden hour", "金、側暖、暗黑", "gold, warm side, noir", "暗調電影感的低角度暖金", "in noir lighting, low warm gold", "noir, golden-hour lighting"],
    ["golden_soft", "柔光金色時", "soft-light golden hour", "金、側暖、柔光", "gold, warm side, soft", "柔光下的低角度暖金", "under soft light, low warm gold", "soft-lit, golden-hour lighting"],
    ["golden_epic", "史詩金色時", "epic golden hour", "金、側暖、史詩", "gold, warm side, epic", "史詩尺度的低角度暖金", "at epic scale, low warm gold", "epic, golden-hour lighting"],
    ["overcast_court", "宮廷陰天軟", "court overcast", "陰、無影、宮廷", "overcast, soft, courtly", "宮廷氣場下的陰天無硬影", "in a courtly register, soft overcast, no hard shadow", "courtly, overcast lighting"],
    ["overcast_street", "街頭陰天軟", "street overcast", "陰、無影、街頭", "overcast, soft, street", "街頭質感的陰天無硬影", "with street grit, soft overcast, no hard shadow", "street-cast, overcast lighting"],
    ["overcast_noir", "暗黑陰天軟", "noir overcast", "陰、無影、暗黑", "overcast, soft, noir", "暗調電影感的陰天無硬影", "in noir lighting, soft overcast, no hard shadow", "noir, overcast lighting"],
    ["overcast_soft", "柔光陰天軟", "soft-light overcast", "陰、無影、柔光", "overcast, soft, soft", "柔光下的陰天無硬影", "under soft light, soft overcast, no hard shadow", "soft-lit, overcast lighting"],
    ["overcast_epic", "史詩陰天軟", "epic overcast", "陰、無影、史詩", "overcast, soft, epic", "史詩尺度的陰天無硬影", "at epic scale, soft overcast, no hard shadow", "epic, overcast lighting"],
    ["moon_court", "宮廷月光藍", "court moon blue", "月、藍、宮廷", "moon, blue, courtly", "宮廷氣場下的冷藍月感", "in a courtly register, cool blue moonlight", "courtly, moonlight lighting"],
    ["moon_street", "街頭月光藍", "street moon blue", "月、藍、街頭", "moon, blue, street", "街頭質感的冷藍月感", "with street grit, cool blue moonlight", "street-cast, moonlight lighting"],
    ["moon_noir", "暗黑月光藍", "noir moon blue", "月、藍、暗黑", "moon, blue, noir", "暗調電影感的冷藍月感", "in noir lighting, cool blue moonlight", "noir, moonlight lighting"],
    ["moon_soft", "柔光月光藍", "soft-light moon blue", "月、藍、柔光", "moon, blue, soft", "柔光下的冷藍月感", "under soft light, cool blue moonlight", "soft-lit, moonlight lighting"],
    ["moon_epic", "史詩月光藍", "epic moon blue", "月、藍、史詩", "moon, blue, epic", "史詩尺度的冷藍月感", "at epic scale, cool blue moonlight", "epic, moonlight lighting"],
    ["strobe_court", "宮廷閃斷", "court strobe", "閃、斷、宮廷", "strobe, cut, courtly", "宮廷氣場下的間斷閃光", "in a courtly register, interrupted strobe", "courtly, strobe lighting"],
    ["strobe_street", "街頭閃斷", "street strobe", "閃、斷、街頭", "strobe, cut, street", "街頭質感的間斷閃光", "with street grit, interrupted strobe", "street-cast, strobe lighting"],
    ["strobe_noir", "暗黑閃斷", "noir strobe", "閃、斷、暗黑", "strobe, cut, noir", "暗調電影感的間斷閃光", "in noir lighting, interrupted strobe", "noir, strobe lighting"],
    ["strobe_soft", "柔光閃斷", "soft-light strobe", "閃、斷、柔光", "strobe, cut, soft", "柔光下的間斷閃光", "under soft light, interrupted strobe", "soft-lit, strobe lighting"],
    ["strobe_epic", "史詩閃斷", "epic strobe", "閃、斷、史詩", "strobe, cut, epic", "史詩尺度的間斷閃光", "at epic scale, interrupted strobe", "epic, strobe lighting"]
  ]
  }
})
