/**
 * costume field kit catalog (50+ templates per part).
 */
import { defineFieldKit } from '../fieldKit'

export const COSTUME_KIT = defineFieldKit({
  key: "costumeKit",
  parts: ["silhouette","top","bottom","outer","footwear","accessory","fabric","palette"] as const,
  partLabels: {
    silhouette: { zhHK: "輪廓", zhCN: "轮廓", en: "Silhouette" },
    top: { zhHK: "上裝", zhCN: "上装", en: "Top" },
    bottom: { zhHK: "下裝", zhCN: "下装", en: "Bottom" },
    outer: { zhHK: "外套", zhCN: "外套", en: "Outer" },
    footwear: { zhHK: "鞋履", zhCN: "鞋履", en: "Footwear" },
    accessory: { zhHK: "飾物", zhCN: "饰物", en: "Accessory" },
    fabric: { zhHK: "質地", zhCN: "质地", en: "Fabric" },
    palette: { zhHK: "色盤", zhCN: "色盘", en: "Palette" }
  },

  rows: {
    silhouette: [
    ["sheath_court", "宮廷修身直筒", "court slim sheath", "修身、利落、宮廷", "slim, sleek, courtly", "宮廷氣場下的貼身直筒輪廓", "in a courtly register, close sheath line", "courtly, slim sheath silhouette"],
    ["sheath_street", "街頭修身直筒", "street slim sheath", "修身、利落、街頭", "slim, sleek, street", "街頭質感的貼身直筒輪廓", "with street grit, close sheath line", "street-cast, slim sheath silhouette"],
    ["sheath_noir", "暗黑修身直筒", "noir slim sheath", "修身、利落、暗黑", "slim, sleek, noir", "暗調電影感的貼身直筒輪廓", "in noir lighting, close sheath line", "noir, slim sheath silhouette"],
    ["sheath_soft", "柔光修身直筒", "soft-light slim sheath", "修身、利落、柔光", "slim, sleek, soft", "柔光下的貼身直筒輪廓", "under soft light, close sheath line", "soft-lit, slim sheath silhouette"],
    ["sheath_epic", "史詩修身直筒", "epic slim sheath", "修身、利落、史詩", "slim, sleek, epic", "史詩尺度的貼身直筒輪廓", "at epic scale, close sheath line", "epic, slim sheath silhouette"],
    ["a_line_court", "宮廷A 字擺", "court A-line", "開擺、柔、宮廷", "flared, soft, courtly", "宮廷氣場下的腰收擺開", "in a courtly register, fitted waist, flared hem", "courtly, A-line silhouette"],
    ["a_line_street", "街頭A 字擺", "street A-line", "開擺、柔、街頭", "flared, soft, street", "街頭質感的腰收擺開", "with street grit, fitted waist, flared hem", "street-cast, A-line silhouette"],
    ["a_line_noir", "暗黑A 字擺", "noir A-line", "開擺、柔、暗黑", "flared, soft, noir", "暗調電影感的腰收擺開", "in noir lighting, fitted waist, flared hem", "noir, A-line silhouette"],
    ["a_line_soft", "柔光A 字擺", "soft-light A-line", "開擺、柔、柔光", "flared, soft, soft", "柔光下的腰收擺開", "under soft light, fitted waist, flared hem", "soft-lit, A-line silhouette"],
    ["a_line_epic", "史詩A 字擺", "epic A-line", "開擺、柔、史詩", "flared, soft, epic", "史詩尺度的腰收擺開", "at epic scale, fitted waist, flared hem", "epic, A-line silhouette"],
    ["oversized_court", "宮廷寬鬆落肩", "court oversized drop", "寬鬆、潮、宮廷", "oversized, street, courtly", "宮廷氣場下的落肩寬廓", "in a courtly register, dropped-shoulder volume", "courtly, oversized drop-shoulder silhouette"],
    ["oversized_street", "街頭寬鬆落肩", "street oversized drop", "寬鬆、潮、街頭", "oversized, street, street", "街頭質感的落肩寬廓", "with street grit, dropped-shoulder volume", "street-cast, oversized drop-shoulder silhouette"],
    ["oversized_noir", "暗黑寬鬆落肩", "noir oversized drop", "寬鬆、潮、暗黑", "oversized, street, noir", "暗調電影感的落肩寬廓", "in noir lighting, dropped-shoulder volume", "noir, oversized drop-shoulder silhouette"],
    ["oversized_soft", "柔光寬鬆落肩", "soft-light oversized drop", "寬鬆、潮、柔光", "oversized, street, soft", "柔光下的落肩寬廓", "under soft light, dropped-shoulder volume", "soft-lit, oversized drop-shoulder silhouette"],
    ["oversized_epic", "史詩寬鬆落肩", "epic oversized drop", "寬鬆、潮、史詩", "oversized, street, epic", "史詩尺度的落肩寬廓", "at epic scale, dropped-shoulder volume", "epic, oversized drop-shoulder silhouette"],
    ["hourglass_court", "宮廷沙漏曲線", "court hourglass", "曲線、經典、宮廷", "curvy, classic, courtly", "宮廷氣場下的肩腰臀對比強", "in a courtly register, marked waist contrast", "courtly, hourglass costume silhouette"],
    ["hourglass_street", "街頭沙漏曲線", "street hourglass", "曲線、經典、街頭", "curvy, classic, street", "街頭質感的肩腰臀對比強", "with street grit, marked waist contrast", "street-cast, hourglass costume silhouette"],
    ["hourglass_noir", "暗黑沙漏曲線", "noir hourglass", "曲線、經典、暗黑", "curvy, classic, noir", "暗調電影感的肩腰臀對比強", "in noir lighting, marked waist contrast", "noir, hourglass costume silhouette"],
    ["hourglass_soft", "柔光沙漏曲線", "soft-light hourglass", "曲線、經典、柔光", "curvy, classic, soft", "柔光下的肩腰臀對比強", "under soft light, marked waist contrast", "soft-lit, hourglass costume silhouette"],
    ["hourglass_epic", "史詩沙漏曲線", "epic hourglass", "曲線、經典、史詩", "curvy, classic, epic", "史詩尺度的肩腰臀對比強", "at epic scale, marked waist contrast", "epic, hourglass costume silhouette"],
    ["column_court", "宮廷直筒柱形", "court column", "直線、冷、宮廷", "column, cool, courtly", "宮廷氣場下的少分割直線", "in a courtly register, straight column, few breaks", "courtly, column silhouette"],
    ["column_street", "街頭直筒柱形", "street column", "直線、冷、街頭", "column, cool, street", "街頭質感的少分割直線", "with street grit, straight column, few breaks", "street-cast, column silhouette"],
    ["column_noir", "暗黑直筒柱形", "noir column", "直線、冷、暗黑", "column, cool, noir", "暗調電影感的少分割直線", "in noir lighting, straight column, few breaks", "noir, column silhouette"],
    ["column_soft", "柔光直筒柱形", "soft-light column", "直線、冷、柔光", "column, cool, soft", "柔光下的少分割直線", "under soft light, straight column, few breaks", "soft-lit, column silhouette"],
    ["column_epic", "史詩直筒柱形", "epic column", "直線、冷、史詩", "column, cool, epic", "史詩尺度的少分割直線", "at epic scale, straight column, few breaks", "epic, column silhouette"],
    ["layered_court", "宮廷多層疊穿", "court layered", "層次、雜誌、宮廷", "layered, editorial, courtly", "宮廷氣場下的兩三層可見疊", "in a courtly register, two-three visible layers", "courtly, layered editorial silhouette"],
    ["layered_street", "街頭多層疊穿", "street layered", "層次、雜誌、街頭", "layered, editorial, street", "街頭質感的兩三層可見疊", "with street grit, two-three visible layers", "street-cast, layered editorial silhouette"],
    ["layered_noir", "暗黑多層疊穿", "noir layered", "層次、雜誌、暗黑", "layered, editorial, noir", "暗調電影感的兩三層可見疊", "in noir lighting, two-three visible layers", "noir, layered editorial silhouette"],
    ["layered_soft", "柔光多層疊穿", "soft-light layered", "層次、雜誌、柔光", "layered, editorial, soft", "柔光下的兩三層可見疊", "under soft light, two-three visible layers", "soft-lit, layered editorial silhouette"],
    ["layered_epic", "史詩多層疊穿", "epic layered", "層次、雜誌、史詩", "layered, editorial, epic", "史詩尺度的兩三層可見疊", "at epic scale, two-three visible layers", "epic, layered editorial silhouette"],
    ["armor_court", "宮廷甲片結構", "court armored", "甲、戰、宮廷", "armor, martial, courtly", "宮廷氣場下的硬結構肩胸", "in a courtly register, hard structured torso", "courtly, armored costume silhouette"],
    ["armor_street", "街頭甲片結構", "street armored", "甲、戰、街頭", "armor, martial, street", "街頭質感的硬結構肩胸", "with street grit, hard structured torso", "street-cast, armored costume silhouette"],
    ["armor_noir", "暗黑甲片結構", "noir armored", "甲、戰、暗黑", "armor, martial, noir", "暗調電影感的硬結構肩胸", "in noir lighting, hard structured torso", "noir, armored costume silhouette"],
    ["armor_soft", "柔光甲片結構", "soft-light armored", "甲、戰、柔光", "armor, martial, soft", "柔光下的硬結構肩胸", "under soft light, hard structured torso", "soft-lit, armored costume silhouette"],
    ["armor_epic", "史詩甲片結構", "epic armored", "甲、戰、史詩", "armor, martial, epic", "史詩尺度的硬結構肩胸", "at epic scale, hard structured torso", "epic, armored costume silhouette"],
    ["robe_court", "宮廷長袍垂墜", "court robe drape", "袍、垂、宮廷", "robe, drape, courtly", "宮廷氣場下的長袍垂直墜感", "in a courtly register, long vertical drape", "courtly, long robe drape silhouette"],
    ["robe_street", "街頭長袍垂墜", "street robe drape", "袍、垂、街頭", "robe, drape, street", "街頭質感的長袍垂直墜感", "with street grit, long vertical drape", "street-cast, long robe drape silhouette"],
    ["robe_noir", "暗黑長袍垂墜", "noir robe drape", "袍、垂、暗黑", "robe, drape, noir", "暗調電影感的長袍垂直墜感", "in noir lighting, long vertical drape", "noir, long robe drape silhouette"],
    ["robe_soft", "柔光長袍垂墜", "soft-light robe drape", "袍、垂、柔光", "robe, drape, soft", "柔光下的長袍垂直墜感", "under soft light, long vertical drape", "soft-lit, long robe drape silhouette"],
    ["robe_epic", "史詩長袍垂墜", "epic robe drape", "袍、垂、史詩", "robe, drape, epic", "史詩尺度的長袍垂直墜感", "at epic scale, long vertical drape", "epic, long robe drape silhouette"],
    ["crop_set_court", "宮廷短裝套系", "court cropped set", "短裝、年輕、宮廷", "crop, youth, courtly", "宮廷氣場下的上短下比例拉長", "in a courtly register, cropped top, long legs", "courtly, cropped coordinated set"],
    ["crop_set_street", "街頭短裝套系", "street cropped set", "短裝、年輕、街頭", "crop, youth, street", "街頭質感的上短下比例拉長", "with street grit, cropped top, long legs", "street-cast, cropped coordinated set"],
    ["crop_set_noir", "暗黑短裝套系", "noir cropped set", "短裝、年輕、暗黑", "crop, youth, noir", "暗調電影感的上短下比例拉長", "in noir lighting, cropped top, long legs", "noir, cropped coordinated set"],
    ["crop_set_soft", "柔光短裝套系", "soft-light cropped set", "短裝、年輕、柔光", "crop, youth, soft", "柔光下的上短下比例拉長", "under soft light, cropped top, long legs", "soft-lit, cropped coordinated set"],
    ["crop_set_epic", "史詩短裝套系", "epic cropped set", "短裝、年輕、史詩", "crop, youth, epic", "史詩尺度的上短下比例拉長", "at epic scale, cropped top, long legs", "epic, cropped coordinated set"],
    ["cape_line_court", "宮廷披風剪影", "court cape line", "披風、戲劇、宮廷", "cape, drama, courtly", "宮廷氣場下的肩後開披風線", "in a courtly register, cape line off shoulders", "courtly, cape-line silhouette"],
    ["cape_line_street", "街頭披風剪影", "street cape line", "披風、戲劇、街頭", "cape, drama, street", "街頭質感的肩後開披風線", "with street grit, cape line off shoulders", "street-cast, cape-line silhouette"],
    ["cape_line_noir", "暗黑披風剪影", "noir cape line", "披風、戲劇、暗黑", "cape, drama, noir", "暗調電影感的肩後開披風線", "in noir lighting, cape line off shoulders", "noir, cape-line silhouette"],
    ["cape_line_soft", "柔光披風剪影", "soft-light cape line", "披風、戲劇、柔光", "cape, drama, soft", "柔光下的肩後開披風線", "under soft light, cape line off shoulders", "soft-lit, cape-line silhouette"],
    ["cape_line_epic", "史詩披風剪影", "epic cape line", "披風、戲劇、史詩", "cape, drama, epic", "史詩尺度的肩後開披風線", "at epic scale, cape line off shoulders", "epic, cape-line silhouette"]
  ],
    top: [
    ["mandarin_court", "宮廷立領衫", "court mandarin collar", "立領、東方、宮廷", "mandarin, oriental, courtly", "宮廷氣場下的高立領上衣", "in a courtly register, high mandarin collar top", "courtly, mandarin-collar top"],
    ["mandarin_street", "街頭立領衫", "street mandarin collar", "立領、東方、街頭", "mandarin, oriental, street", "街頭質感的高立領上衣", "with street grit, high mandarin collar top", "street-cast, mandarin-collar top"],
    ["mandarin_noir", "暗黑立領衫", "noir mandarin collar", "立領、東方、暗黑", "mandarin, oriental, noir", "暗調電影感的高立領上衣", "in noir lighting, high mandarin collar top", "noir, mandarin-collar top"],
    ["mandarin_soft", "柔光立領衫", "soft-light mandarin collar", "立領、東方、柔光", "mandarin, oriental, soft", "柔光下的高立領上衣", "under soft light, high mandarin collar top", "soft-lit, mandarin-collar top"],
    ["mandarin_epic", "史詩立領衫", "epic mandarin collar", "立領、東方、史詩", "mandarin, oriental, epic", "史詩尺度的高立領上衣", "at epic scale, high mandarin collar top", "epic, mandarin-collar top"],
    ["shirt_court", "宮廷修身襯衫", "court fitted shirt", "襯衫、俐落、宮廷", "shirt, neat, courtly", "宮廷氣場下的修身有領襯衫", "in a courtly register, fitted collared shirt", "courtly, fitted dress shirt"],
    ["shirt_street", "街頭修身襯衫", "street fitted shirt", "襯衫、俐落、街頭", "shirt, neat, street", "街頭質感的修身有領襯衫", "with street grit, fitted collared shirt", "street-cast, fitted dress shirt"],
    ["shirt_noir", "暗黑修身襯衫", "noir fitted shirt", "襯衫、俐落、暗黑", "shirt, neat, noir", "暗調電影感的修身有領襯衫", "in noir lighting, fitted collared shirt", "noir, fitted dress shirt"],
    ["shirt_soft", "柔光修身襯衫", "soft-light fitted shirt", "襯衫、俐落、柔光", "shirt, neat, soft", "柔光下的修身有領襯衫", "under soft light, fitted collared shirt", "soft-lit, fitted dress shirt"],
    ["shirt_epic", "史詩修身襯衫", "epic fitted shirt", "襯衫、俐落、史詩", "shirt, neat, epic", "史詩尺度的修身有領襯衫", "at epic scale, fitted collared shirt", "epic, fitted dress shirt"],
    ["tank_court", "宮廷貼身背心", "court tank", "背心、簡、宮廷", "tank, simple, courtly", "宮廷氣場下的貼身上背心", "in a courtly register, close tank top", "courtly, fitted tank top"],
    ["tank_street", "街頭貼身背心", "street tank", "背心、簡、街頭", "tank, simple, street", "街頭質感的貼身上背心", "with street grit, close tank top", "street-cast, fitted tank top"],
    ["tank_noir", "暗黑貼身背心", "noir tank", "背心、簡、暗黑", "tank, simple, noir", "暗調電影感的貼身上背心", "in noir lighting, close tank top", "noir, fitted tank top"],
    ["tank_soft", "柔光貼身背心", "soft-light tank", "背心、簡、柔光", "tank, simple, soft", "柔光下的貼身上背心", "under soft light, close tank top", "soft-lit, fitted tank top"],
    ["tank_epic", "史詩貼身背心", "epic tank", "背心、簡、史詩", "tank, simple, epic", "史詩尺度的貼身上背心", "at epic scale, close tank top", "epic, fitted tank top"],
    ["blouse_court", "宮廷柔紗罩衫", "court soft blouse", "紗、柔、宮廷", "sheer, soft, courtly", "宮廷氣場下的輕透罩衫", "in a courtly register, soft sheer blouse", "courtly, soft blouse, slight sheen"],
    ["blouse_street", "街頭柔紗罩衫", "street soft blouse", "紗、柔、街頭", "sheer, soft, street", "街頭質感的輕透罩衫", "with street grit, soft sheer blouse", "street-cast, soft blouse, slight sheen"],
    ["blouse_noir", "暗黑柔紗罩衫", "noir soft blouse", "紗、柔、暗黑", "sheer, soft, noir", "暗調電影感的輕透罩衫", "in noir lighting, soft sheer blouse", "noir, soft blouse, slight sheen"],
    ["blouse_soft", "柔光柔紗罩衫", "soft-light soft blouse", "紗、柔、柔光", "sheer, soft, soft", "柔光下的輕透罩衫", "under soft light, soft sheer blouse", "soft-lit, soft blouse, slight sheen"],
    ["blouse_epic", "史詩柔紗罩衫", "epic soft blouse", "紗、柔、史詩", "sheer, soft, epic", "史詩尺度的輕透罩衫", "at epic scale, soft sheer blouse", "epic, soft blouse, slight sheen"],
    ["sweater_court", "宮廷細織毛衣", "court fine knit", "織、暖、宮廷", "knit, warm, courtly", "宮廷氣場下的貼身細針織", "in a courtly register, fine close knit", "courtly, fine-knit sweater"],
    ["sweater_street", "街頭細織毛衣", "street fine knit", "織、暖、街頭", "knit, warm, street", "街頭質感的貼身細針織", "with street grit, fine close knit", "street-cast, fine-knit sweater"],
    ["sweater_noir", "暗黑細織毛衣", "noir fine knit", "織、暖、暗黑", "knit, warm, noir", "暗調電影感的貼身細針織", "in noir lighting, fine close knit", "noir, fine-knit sweater"],
    ["sweater_soft", "柔光細織毛衣", "soft-light fine knit", "織、暖、柔光", "knit, warm, soft", "柔光下的貼身細針織", "under soft light, fine close knit", "soft-lit, fine-knit sweater"],
    ["sweater_epic", "史詩細織毛衣", "epic fine knit", "織、暖、史詩", "knit, warm, epic", "史詩尺度的貼身細針織", "at epic scale, fine close knit", "epic, fine-knit sweater"],
    ["hanfu_top_court", "宮廷交領中衣", "court cross-collar", "交領、古、宮廷", "cross-collar, period, courtly", "宮廷氣場下的交領右衽中衣", "in a courtly register, cross-collar inner robe", "courtly, cross-collar hanfu top"],
    ["hanfu_top_street", "街頭交領中衣", "street cross-collar", "交領、古、街頭", "cross-collar, period, street", "街頭質感的交領右衽中衣", "with street grit, cross-collar inner robe", "street-cast, cross-collar hanfu top"],
    ["hanfu_top_noir", "暗黑交領中衣", "noir cross-collar", "交領、古、暗黑", "cross-collar, period, noir", "暗調電影感的交領右衽中衣", "in noir lighting, cross-collar inner robe", "noir, cross-collar hanfu top"],
    ["hanfu_top_soft", "柔光交領中衣", "soft-light cross-collar", "交領、古、柔光", "cross-collar, period, soft", "柔光下的交領右衽中衣", "under soft light, cross-collar inner robe", "soft-lit, cross-collar hanfu top"],
    ["hanfu_top_epic", "史詩交領中衣", "epic cross-collar", "交領、古、史詩", "cross-collar, period, epic", "史詩尺度的交領右衽中衣", "at epic scale, cross-collar inner robe", "epic, cross-collar hanfu top"],
    ["jacket_crop_court", "宮廷短夾克", "court crop jacket", "短夾克、酷、宮廷", "crop jacket, cool, courtly", "宮廷氣場下的齊腰短夾克", "in a courtly register, waist-length jacket", "courtly, cropped jacket top"],
    ["jacket_crop_street", "街頭短夾克", "street crop jacket", "短夾克、酷、街頭", "crop jacket, cool, street", "街頭質感的齊腰短夾克", "with street grit, waist-length jacket", "street-cast, cropped jacket top"],
    ["jacket_crop_noir", "暗黑短夾克", "noir crop jacket", "短夾克、酷、暗黑", "crop jacket, cool, noir", "暗調電影感的齊腰短夾克", "in noir lighting, waist-length jacket", "noir, cropped jacket top"],
    ["jacket_crop_soft", "柔光短夾克", "soft-light crop jacket", "短夾克、酷、柔光", "crop jacket, cool, soft", "柔光下的齊腰短夾克", "under soft light, waist-length jacket", "soft-lit, cropped jacket top"],
    ["jacket_crop_epic", "史詩短夾克", "epic crop jacket", "短夾克、酷、史詩", "crop jacket, cool, epic", "史詩尺度的齊腰短夾克", "at epic scale, waist-length jacket", "epic, cropped jacket top"],
    ["turtleneck_court", "宮廷高領", "court turtleneck", "高領、冷、宮廷", "turtleneck, cool, courtly", "宮廷氣場下的貼頸高領", "in a courtly register, close turtleneck", "courtly, fitted turtleneck"],
    ["turtleneck_street", "街頭高領", "street turtleneck", "高領、冷、街頭", "turtleneck, cool, street", "街頭質感的貼頸高領", "with street grit, close turtleneck", "street-cast, fitted turtleneck"],
    ["turtleneck_noir", "暗黑高領", "noir turtleneck", "高領、冷、暗黑", "turtleneck, cool, noir", "暗調電影感的貼頸高領", "in noir lighting, close turtleneck", "noir, fitted turtleneck"],
    ["turtleneck_soft", "柔光高領", "soft-light turtleneck", "高領、冷、柔光", "turtleneck, cool, soft", "柔光下的貼頸高領", "under soft light, close turtleneck", "soft-lit, fitted turtleneck"],
    ["turtleneck_epic", "史詩高領", "epic turtleneck", "高領、冷、史詩", "turtleneck, cool, epic", "史詩尺度的貼頸高領", "at epic scale, close turtleneck", "epic, fitted turtleneck"],
    ["armor_chest_court", "宮廷胸甲上衣", "court chest plate", "甲、戰、宮廷", "plate, war, courtly", "宮廷氣場下的胸甲壓上衣", "in a courtly register, chest plate over cloth", "courtly, chest-plate top"],
    ["armor_chest_street", "街頭胸甲上衣", "street chest plate", "甲、戰、街頭", "plate, war, street", "街頭質感的胸甲壓上衣", "with street grit, chest plate over cloth", "street-cast, chest-plate top"],
    ["armor_chest_noir", "暗黑胸甲上衣", "noir chest plate", "甲、戰、暗黑", "plate, war, noir", "暗調電影感的胸甲壓上衣", "in noir lighting, chest plate over cloth", "noir, chest-plate top"],
    ["armor_chest_soft", "柔光胸甲上衣", "soft-light chest plate", "甲、戰、柔光", "plate, war, soft", "柔光下的胸甲壓上衣", "under soft light, chest plate over cloth", "soft-lit, chest-plate top"],
    ["armor_chest_epic", "史詩胸甲上衣", "epic chest plate", "甲、戰、史詩", "plate, war, epic", "史詩尺度的胸甲壓上衣", "at epic scale, chest plate over cloth", "epic, chest-plate top"],
    ["open_collar_court", "宮廷敞開領", "court open collar", "敞開、鬆、宮廷", "open, loose, courtly", "宮廷氣場下的領口鬆敞", "in a courtly register, open relaxed collar", "courtly, open-collar shirt"],
    ["open_collar_street", "街頭敞開領", "street open collar", "敞開、鬆、街頭", "open, loose, street", "街頭質感的領口鬆敞", "with street grit, open relaxed collar", "street-cast, open-collar shirt"],
    ["open_collar_noir", "暗黑敞開領", "noir open collar", "敞開、鬆、暗黑", "open, loose, noir", "暗調電影感的領口鬆敞", "in noir lighting, open relaxed collar", "noir, open-collar shirt"],
    ["open_collar_soft", "柔光敞開領", "soft-light open collar", "敞開、鬆、柔光", "open, loose, soft", "柔光下的領口鬆敞", "under soft light, open relaxed collar", "soft-lit, open-collar shirt"],
    ["open_collar_epic", "史詩敞開領", "epic open collar", "敞開、鬆、史詩", "open, loose, epic", "史詩尺度的領口鬆敞", "at epic scale, open relaxed collar", "epic, open-collar shirt"]
  ],
    bottom: [
    ["slim_trouser_court", "宮廷窄管西褲", "court slim trousers", "窄管、正、宮廷", "slim, formal, courtly", "宮廷氣場下的窄管長褲", "in a courtly register, slim long trousers", "courtly, slim tailored trousers"],
    ["slim_trouser_street", "街頭窄管西褲", "street slim trousers", "窄管、正、街頭", "slim, formal, street", "街頭質感的窄管長褲", "with street grit, slim long trousers", "street-cast, slim tailored trousers"],
    ["slim_trouser_noir", "暗黑窄管西褲", "noir slim trousers", "窄管、正、暗黑", "slim, formal, noir", "暗調電影感的窄管長褲", "in noir lighting, slim long trousers", "noir, slim tailored trousers"],
    ["slim_trouser_soft", "柔光窄管西褲", "soft-light slim trousers", "窄管、正、柔光", "slim, formal, soft", "柔光下的窄管長褲", "under soft light, slim long trousers", "soft-lit, slim tailored trousers"],
    ["slim_trouser_epic", "史詩窄管西褲", "epic slim trousers", "窄管、正、史詩", "slim, formal, epic", "史詩尺度的窄管長褲", "at epic scale, slim long trousers", "epic, slim tailored trousers"],
    ["wide_pant_court", "宮廷闊腿褲", "court wide pants", "闊腿、潮、宮廷", "wide, fashion, courtly", "宮廷氣場下的垂墜闊腿", "in a courtly register, draped wide legs", "courtly, wide-leg trousers"],
    ["wide_pant_street", "街頭闊腿褲", "street wide pants", "闊腿、潮、街頭", "wide, fashion, street", "街頭質感的垂墜闊腿", "with street grit, draped wide legs", "street-cast, wide-leg trousers"],
    ["wide_pant_noir", "暗黑闊腿褲", "noir wide pants", "闊腿、潮、暗黑", "wide, fashion, noir", "暗調電影感的垂墜闊腿", "in noir lighting, draped wide legs", "noir, wide-leg trousers"],
    ["wide_pant_soft", "柔光闊腿褲", "soft-light wide pants", "闊腿、潮、柔光", "wide, fashion, soft", "柔光下的垂墜闊腿", "under soft light, draped wide legs", "soft-lit, wide-leg trousers"],
    ["wide_pant_epic", "史詩闊腿褲", "epic wide pants", "闊腿、潮、史詩", "wide, fashion, epic", "史詩尺度的垂墜闊腿", "at epic scale, draped wide legs", "epic, wide-leg trousers"],
    ["pencil_court", "宮廷包裙", "court pencil skirt", "包裙、利、宮廷", "pencil, sleek, courtly", "宮廷氣場下的過膝包裙", "in a courtly register, knee-or-below pencil", "courtly, pencil skirt"],
    ["pencil_street", "街頭包裙", "street pencil skirt", "包裙、利、街頭", "pencil, sleek, street", "街頭質感的過膝包裙", "with street grit, knee-or-below pencil", "street-cast, pencil skirt"],
    ["pencil_noir", "暗黑包裙", "noir pencil skirt", "包裙、利、暗黑", "pencil, sleek, noir", "暗調電影感的過膝包裙", "in noir lighting, knee-or-below pencil", "noir, pencil skirt"],
    ["pencil_soft", "柔光包裙", "soft-light pencil skirt", "包裙、利、柔光", "pencil, sleek, soft", "柔光下的過膝包裙", "under soft light, knee-or-below pencil", "soft-lit, pencil skirt"],
    ["pencil_epic", "史詩包裙", "epic pencil skirt", "包裙、利、史詩", "pencil, sleek, epic", "史詩尺度的過膝包裙", "at epic scale, knee-or-below pencil", "epic, pencil skirt"],
    ["pleat_court", "宮廷百褶裙", "court pleated skirt", "褶、動、宮廷", "pleats, motion, courtly", "宮廷氣場下的流動百褶", "in a courtly register, moving pleats", "courtly, pleated skirt"],
    ["pleat_street", "街頭百褶裙", "street pleated skirt", "褶、動、街頭", "pleats, motion, street", "街頭質感的流動百褶", "with street grit, moving pleats", "street-cast, pleated skirt"],
    ["pleat_noir", "暗黑百褶裙", "noir pleated skirt", "褶、動、暗黑", "pleats, motion, noir", "暗調電影感的流動百褶", "in noir lighting, moving pleats", "noir, pleated skirt"],
    ["pleat_soft", "柔光百褶裙", "soft-light pleated skirt", "褶、動、柔光", "pleats, motion, soft", "柔光下的流動百褶", "under soft light, moving pleats", "soft-lit, pleated skirt"],
    ["pleat_epic", "史詩百褶裙", "epic pleated skirt", "褶、動、史詩", "pleats, motion, epic", "史詩尺度的流動百褶", "at epic scale, moving pleats", "epic, pleated skirt"],
    ["jean_court", "宮廷修身牛仔褲", "court slim jeans", "牛仔、日常、宮廷", "denim, daily, courtly", "宮廷氣場下的修身丹寧", "in a courtly register, slim denim", "courtly, slim jeans"],
    ["jean_street", "街頭修身牛仔褲", "street slim jeans", "牛仔、日常、街頭", "denim, daily, street", "街頭質感的修身丹寧", "with street grit, slim denim", "street-cast, slim jeans"],
    ["jean_noir", "暗黑修身牛仔褲", "noir slim jeans", "牛仔、日常、暗黑", "denim, daily, noir", "暗調電影感的修身丹寧", "in noir lighting, slim denim", "noir, slim jeans"],
    ["jean_soft", "柔光修身牛仔褲", "soft-light slim jeans", "牛仔、日常、柔光", "denim, daily, soft", "柔光下的修身丹寧", "under soft light, slim denim", "soft-lit, slim jeans"],
    ["jean_epic", "史詩修身牛仔褲", "epic slim jeans", "牛仔、日常、史詩", "denim, daily, epic", "史詩尺度的修身丹寧", "at epic scale, slim denim", "epic, slim jeans"],
    ["hanfu_skirt_court", "宮廷馬面／褶裙", "court period skirt", "古裙、層、宮廷", "period, layered, courtly", "宮廷氣場下的古風長裙", "in a courtly register, long period skirt", "courtly, layered period skirt"],
    ["hanfu_skirt_street", "街頭馬面／褶裙", "street period skirt", "古裙、層、街頭", "period, layered, street", "街頭質感的古風長裙", "with street grit, long period skirt", "street-cast, layered period skirt"],
    ["hanfu_skirt_noir", "暗黑馬面／褶裙", "noir period skirt", "古裙、層、暗黑", "period, layered, noir", "暗調電影感的古風長裙", "in noir lighting, long period skirt", "noir, layered period skirt"],
    ["hanfu_skirt_soft", "柔光馬面／褶裙", "soft-light period skirt", "古裙、層、柔光", "period, layered, soft", "柔光下的古風長裙", "under soft light, long period skirt", "soft-lit, layered period skirt"],
    ["hanfu_skirt_epic", "史詩馬面／褶裙", "epic period skirt", "古裙、層、史詩", "period, layered, epic", "史詩尺度的古風長裙", "at epic scale, long period skirt", "epic, layered period skirt"],
    ["shorts_court", "宮廷俐落短褲", "court tailored shorts", "短褲、利、宮廷", "shorts, neat, courtly", "宮廷氣場下的齊膝短褲", "in a courtly register, knee tailored shorts", "courtly, tailored shorts"],
    ["shorts_street", "街頭俐落短褲", "street tailored shorts", "短褲、利、街頭", "shorts, neat, street", "街頭質感的齊膝短褲", "with street grit, knee tailored shorts", "street-cast, tailored shorts"],
    ["shorts_noir", "暗黑俐落短褲", "noir tailored shorts", "短褲、利、暗黑", "shorts, neat, noir", "暗調電影感的齊膝短褲", "in noir lighting, knee tailored shorts", "noir, tailored shorts"],
    ["shorts_soft", "柔光俐落短褲", "soft-light tailored shorts", "短褲、利、柔光", "shorts, neat, soft", "柔光下的齊膝短褲", "under soft light, knee tailored shorts", "soft-lit, tailored shorts"],
    ["shorts_epic", "史詩俐落短褲", "epic tailored shorts", "短褲、利、史詩", "shorts, neat, epic", "史詩尺度的齊膝短褲", "at epic scale, knee tailored shorts", "epic, tailored shorts"],
    ["hakama_court", "宮廷袴型寬褲", "court hakama pants", "袴、武、宮廷", "hakama, martial, courtly", "宮廷氣場下的寬褶袴", "in a courtly register, wide pleated hakama", "courtly, hakama-cut pants"],
    ["hakama_street", "街頭袴型寬褲", "street hakama pants", "袴、武、街頭", "hakama, martial, street", "街頭質感的寬褶袴", "with street grit, wide pleated hakama", "street-cast, hakama-cut pants"],
    ["hakama_noir", "暗黑袴型寬褲", "noir hakama pants", "袴、武、暗黑", "hakama, martial, noir", "暗調電影感的寬褶袴", "in noir lighting, wide pleated hakama", "noir, hakama-cut pants"],
    ["hakama_soft", "柔光袴型寬褲", "soft-light hakama pants", "袴、武、柔光", "hakama, martial, soft", "柔光下的寬褶袴", "under soft light, wide pleated hakama", "soft-lit, hakama-cut pants"],
    ["hakama_epic", "史詩袴型寬褲", "epic hakama pants", "袴、武、史詩", "hakama, martial, epic", "史詩尺度的寬褶袴", "at epic scale, wide pleated hakama", "epic, hakama-cut pants"],
    ["leggings_court", "宮廷緊身褲", "court leggings", "緊、動、宮廷", "tight, athletic, courtly", "宮廷氣場下的貼腿長褲", "in a courtly register, close leggings", "courtly, fitted leggings"],
    ["leggings_street", "街頭緊身褲", "street leggings", "緊、動、街頭", "tight, athletic, street", "街頭質感的貼腿長褲", "with street grit, close leggings", "street-cast, fitted leggings"],
    ["leggings_noir", "暗黑緊身褲", "noir leggings", "緊、動、暗黑", "tight, athletic, noir", "暗調電影感的貼腿長褲", "in noir lighting, close leggings", "noir, fitted leggings"],
    ["leggings_soft", "柔光緊身褲", "soft-light leggings", "緊、動、柔光", "tight, athletic, soft", "柔光下的貼腿長褲", "under soft light, close leggings", "soft-lit, fitted leggings"],
    ["leggings_epic", "史詩緊身褲", "epic leggings", "緊、動、史詩", "tight, athletic, epic", "史詩尺度的貼腿長褲", "at epic scale, close leggings", "epic, fitted leggings"],
    ["armor_greave_court", "宮廷甲裙／護腿", "court armored skirt", "甲裙、戰、宮廷", "armor skirt, war, courtly", "宮廷氣場下的硬質下甲", "in a courtly register, hard lower armor", "courtly, armored skirt or greaves"],
    ["armor_greave_street", "街頭甲裙／護腿", "street armored skirt", "甲裙、戰、街頭", "armor skirt, war, street", "街頭質感的硬質下甲", "with street grit, hard lower armor", "street-cast, armored skirt or greaves"],
    ["armor_greave_noir", "暗黑甲裙／護腿", "noir armored skirt", "甲裙、戰、暗黑", "armor skirt, war, noir", "暗調電影感的硬質下甲", "in noir lighting, hard lower armor", "noir, armored skirt or greaves"],
    ["armor_greave_soft", "柔光甲裙／護腿", "soft-light armored skirt", "甲裙、戰、柔光", "armor skirt, war, soft", "柔光下的硬質下甲", "under soft light, hard lower armor", "soft-lit, armored skirt or greaves"],
    ["armor_greave_epic", "史詩甲裙／護腿", "epic armored skirt", "甲裙、戰、史詩", "armor skirt, war, epic", "史詩尺度的硬質下甲", "at epic scale, hard lower armor", "epic, armored skirt or greaves"]
  ],
    outer: [
    ["trench_court", "宮廷風衣", "court trench", "風衣、冷、宮廷", "trench, cool, courtly", "宮廷氣場下的過膝風衣", "in a courtly register, knee-plus trench", "courtly, long trench coat"],
    ["trench_street", "街頭風衣", "street trench", "風衣、冷、街頭", "trench, cool, street", "街頭質感的過膝風衣", "with street grit, knee-plus trench", "street-cast, long trench coat"],
    ["trench_noir", "暗黑風衣", "noir trench", "風衣、冷、暗黑", "trench, cool, noir", "暗調電影感的過膝風衣", "in noir lighting, knee-plus trench", "noir, long trench coat"],
    ["trench_soft", "柔光風衣", "soft-light trench", "風衣、冷、柔光", "trench, cool, soft", "柔光下的過膝風衣", "under soft light, knee-plus trench", "soft-lit, long trench coat"],
    ["trench_epic", "史詩風衣", "epic trench", "風衣、冷、史詩", "trench, cool, epic", "史詩尺度的過膝風衣", "at epic scale, knee-plus trench", "epic, long trench coat"],
    ["blazer_court", "宮廷修身西裝褸", "court blazer", "西裝、利、宮廷", "blazer, sharp, courtly", "宮廷氣場下的修身西裝褸", "in a courtly register, fitted blazer", "courtly, fitted blazer"],
    ["blazer_street", "街頭修身西裝褸", "street blazer", "西裝、利、街頭", "blazer, sharp, street", "街頭質感的修身西裝褸", "with street grit, fitted blazer", "street-cast, fitted blazer"],
    ["blazer_noir", "暗黑修身西裝褸", "noir blazer", "西裝、利、暗黑", "blazer, sharp, noir", "暗調電影感的修身西裝褸", "in noir lighting, fitted blazer", "noir, fitted blazer"],
    ["blazer_soft", "柔光修身西裝褸", "soft-light blazer", "西裝、利、柔光", "blazer, sharp, soft", "柔光下的修身西裝褸", "under soft light, fitted blazer", "soft-lit, fitted blazer"],
    ["blazer_epic", "史詩修身西裝褸", "epic blazer", "西裝、利、史詩", "blazer, sharp, epic", "史詩尺度的修身西裝褸", "at epic scale, fitted blazer", "epic, fitted blazer"],
    ["cloak_court", "宮廷連帽斗篷", "court hooded cloak", "斗篷、謎、宮廷", "cloak, mystery, courtly", "宮廷氣場下的連帽長斗篷", "in a courtly register, hooded long cloak", "courtly, hooded cloak"],
    ["cloak_street", "街頭連帽斗篷", "street hooded cloak", "斗篷、謎、街頭", "cloak, mystery, street", "街頭質感的連帽長斗篷", "with street grit, hooded long cloak", "street-cast, hooded cloak"],
    ["cloak_noir", "暗黑連帽斗篷", "noir hooded cloak", "斗篷、謎、暗黑", "cloak, mystery, noir", "暗調電影感的連帽長斗篷", "in noir lighting, hooded long cloak", "noir, hooded cloak"],
    ["cloak_soft", "柔光連帽斗篷", "soft-light hooded cloak", "斗篷、謎、柔光", "cloak, mystery, soft", "柔光下的連帽長斗篷", "under soft light, hooded long cloak", "soft-lit, hooded cloak"],
    ["cloak_epic", "史詩連帽斗篷", "epic hooded cloak", "斗篷、謎、史詩", "cloak, mystery, epic", "史詩尺度的連帽長斗篷", "at epic scale, hooded long cloak", "epic, hooded cloak"],
    ["leather_court", "宮廷皮褸", "court leather jacket", "皮、叛、宮廷", "leather, rebel, courtly", "宮廷氣場下的短皮褸", "in a courtly register, short leather jacket", "courtly, leather jacket"],
    ["leather_street", "街頭皮褸", "street leather jacket", "皮、叛、街頭", "leather, rebel, street", "街頭質感的短皮褸", "with street grit, short leather jacket", "street-cast, leather jacket"],
    ["leather_noir", "暗黑皮褸", "noir leather jacket", "皮、叛、暗黑", "leather, rebel, noir", "暗調電影感的短皮褸", "in noir lighting, short leather jacket", "noir, leather jacket"],
    ["leather_soft", "柔光皮褸", "soft-light leather jacket", "皮、叛、柔光", "leather, rebel, soft", "柔光下的短皮褸", "under soft light, short leather jacket", "soft-lit, leather jacket"],
    ["leather_epic", "史詩皮褸", "epic leather jacket", "皮、叛、史詩", "leather, rebel, epic", "史詩尺度的短皮褸", "at epic scale, short leather jacket", "epic, leather jacket"],
    ["fur_collar_court", "宮廷毛領大衣", "court fur-collar coat", "毛領、貴、宮廷", "fur collar, luxe, courtly", "宮廷氣場下的厚毛領長大衣", "in a courtly register, fur-collar overcoat", "courtly, fur-collar coat"],
    ["fur_collar_street", "街頭毛領大衣", "street fur-collar coat", "毛領、貴、街頭", "fur collar, luxe, street", "街頭質感的厚毛領長大衣", "with street grit, fur-collar overcoat", "street-cast, fur-collar coat"],
    ["fur_collar_noir", "暗黑毛領大衣", "noir fur-collar coat", "毛領、貴、暗黑", "fur collar, luxe, noir", "暗調電影感的厚毛領長大衣", "in noir lighting, fur-collar overcoat", "noir, fur-collar coat"],
    ["fur_collar_soft", "柔光毛領大衣", "soft-light fur-collar coat", "毛領、貴、柔光", "fur collar, luxe, soft", "柔光下的厚毛領長大衣", "under soft light, fur-collar overcoat", "soft-lit, fur-collar coat"],
    ["fur_collar_epic", "史詩毛領大衣", "epic fur-collar coat", "毛領、貴、史詩", "fur collar, luxe, epic", "史詩尺度的厚毛領長大衣", "at epic scale, fur-collar overcoat", "epic, fur-collar coat"],
    ["none_court", "宮廷無外套", "court no outer layer", "無外、簡、宮廷", "none, simple, courtly", "宮廷氣場下的不穿外套", "in a courtly register, no coat layer", "courtly, no outerwear"],
    ["none_street", "街頭無外套", "street no outer layer", "無外、簡、街頭", "none, simple, street", "街頭質感的不穿外套", "with street grit, no coat layer", "street-cast, no outerwear"],
    ["none_noir", "暗黑無外套", "noir no outer layer", "無外、簡、暗黑", "none, simple, noir", "暗調電影感的不穿外套", "in noir lighting, no coat layer", "noir, no outerwear"],
    ["none_soft", "柔光無外套", "soft-light no outer layer", "無外、簡、柔光", "none, simple, soft", "柔光下的不穿外套", "under soft light, no coat layer", "soft-lit, no outerwear"],
    ["none_epic", "史詩無外套", "epic no outer layer", "無外、簡、史詩", "none, simple, epic", "史詩尺度的不穿外套", "at epic scale, no coat layer", "epic, no outerwear"],
    ["capelet_court", "宮廷短披肩", "court capelet", "披肩、飾、宮廷", "capelet, accent, courtly", "宮廷氣場下的肩上短披", "in a courtly register, short shoulder cape", "courtly, capelet"],
    ["capelet_street", "街頭短披肩", "street capelet", "披肩、飾、街頭", "capelet, accent, street", "街頭質感的肩上短披", "with street grit, short shoulder cape", "street-cast, capelet"],
    ["capelet_noir", "暗黑短披肩", "noir capelet", "披肩、飾、暗黑", "capelet, accent, noir", "暗調電影感的肩上短披", "in noir lighting, short shoulder cape", "noir, capelet"],
    ["capelet_soft", "柔光短披肩", "soft-light capelet", "披肩、飾、柔光", "capelet, accent, soft", "柔光下的肩上短披", "under soft light, short shoulder cape", "soft-lit, capelet"],
    ["capelet_epic", "史詩短披肩", "epic capelet", "披肩、飾、史詩", "capelet, accent, epic", "史詩尺度的肩上短披", "at epic scale, short shoulder cape", "epic, capelet"],
    ["haori_court", "宮廷羽織", "court haori", "羽織、和、宮廷", "haori, wash, courtly", "宮廷氣場下的及髖羽織", "in a courtly register, hip-length haori", "courtly, haori jacket"],
    ["haori_street", "街頭羽織", "street haori", "羽織、和、街頭", "haori, wash, street", "街頭質感的及髖羽織", "with street grit, hip-length haori", "street-cast, haori jacket"],
    ["haori_noir", "暗黑羽織", "noir haori", "羽織、和、暗黑", "haori, wash, noir", "暗調電影感的及髖羽織", "in noir lighting, hip-length haori", "noir, haori jacket"],
    ["haori_soft", "柔光羽織", "soft-light haori", "羽織、和、柔光", "haori, wash, soft", "柔光下的及髖羽織", "under soft light, hip-length haori", "soft-lit, haori jacket"],
    ["haori_epic", "史詩羽織", "epic haori", "羽織、和、史詩", "haori, wash, epic", "史詩尺度的及髖羽織", "at epic scale, hip-length haori", "epic, haori jacket"],
    ["armor_pauldron_court", "宮廷肩甲外層", "court pauldron layer", "肩甲、戰、宮廷", "pauldron, war, courtly", "宮廷氣場下的可見肩甲", "in a courtly register, visible pauldrons", "courtly, pauldron outer layer"],
    ["armor_pauldron_street", "街頭肩甲外層", "street pauldron layer", "肩甲、戰、街頭", "pauldron, war, street", "街頭質感的可見肩甲", "with street grit, visible pauldrons", "street-cast, pauldron outer layer"],
    ["armor_pauldron_noir", "暗黑肩甲外層", "noir pauldron layer", "肩甲、戰、暗黑", "pauldron, war, noir", "暗調電影感的可見肩甲", "in noir lighting, visible pauldrons", "noir, pauldron outer layer"],
    ["armor_pauldron_soft", "柔光肩甲外層", "soft-light pauldron layer", "肩甲、戰、柔光", "pauldron, war, soft", "柔光下的可見肩甲", "under soft light, visible pauldrons", "soft-lit, pauldron outer layer"],
    ["armor_pauldron_epic", "史詩肩甲外層", "epic pauldron layer", "肩甲、戰、史詩", "pauldron, war, epic", "史詩尺度的可見肩甲", "at epic scale, visible pauldrons", "epic, pauldron outer layer"],
    ["kimono_outer_court", "宮廷外掛長衫", "court long outer robe", "長衫、垂、宮廷", "robe, drape, courtly", "宮廷氣場下的開襟長外衫", "in a courtly register, open long robe", "courtly, long open outer robe"],
    ["kimono_outer_street", "街頭外掛長衫", "street long outer robe", "長衫、垂、街頭", "robe, drape, street", "街頭質感的開襟長外衫", "with street grit, open long robe", "street-cast, long open outer robe"],
    ["kimono_outer_noir", "暗黑外掛長衫", "noir long outer robe", "長衫、垂、暗黑", "robe, drape, noir", "暗調電影感的開襟長外衫", "in noir lighting, open long robe", "noir, long open outer robe"],
    ["kimono_outer_soft", "柔光外掛長衫", "soft-light long outer robe", "長衫、垂、柔光", "robe, drape, soft", "柔光下的開襟長外衫", "under soft light, open long robe", "soft-lit, long open outer robe"],
    ["kimono_outer_epic", "史詩外掛長衫", "epic long outer robe", "長衫、垂、史詩", "robe, drape, epic", "史詩尺度的開襟長外衫", "at epic scale, open long robe", "epic, long open outer robe"]
  ],
    footwear: [
    ["boot_knee_court", "宮廷過膝靴", "court knee boots", "靴、利、宮廷", "boots, sharp, courtly", "宮廷氣場下的過膝長靴", "in a courtly register, knee-high boots", "courtly, knee-high boots"],
    ["boot_knee_street", "街頭過膝靴", "street knee boots", "靴、利、街頭", "boots, sharp, street", "街頭質感的過膝長靴", "with street grit, knee-high boots", "street-cast, knee-high boots"],
    ["boot_knee_noir", "暗黑過膝靴", "noir knee boots", "靴、利、暗黑", "boots, sharp, noir", "暗調電影感的過膝長靴", "in noir lighting, knee-high boots", "noir, knee-high boots"],
    ["boot_knee_soft", "柔光過膝靴", "soft-light knee boots", "靴、利、柔光", "boots, sharp, soft", "柔光下的過膝長靴", "under soft light, knee-high boots", "soft-lit, knee-high boots"],
    ["boot_knee_epic", "史詩過膝靴", "epic knee boots", "靴、利、史詩", "boots, sharp, epic", "史詩尺度的過膝長靴", "at epic scale, knee-high boots", "epic, knee-high boots"],
    ["oxford_court", "宮廷牛津鞋", "court oxfords", "牛津、正、宮廷", "oxford, formal, courtly", "宮廷氣場下的繫帶皮鞋", "in a courtly register, laced leather oxfords", "courtly, leather oxfords"],
    ["oxford_street", "街頭牛津鞋", "street oxfords", "牛津、正、街頭", "oxford, formal, street", "街頭質感的繫帶皮鞋", "with street grit, laced leather oxfords", "street-cast, leather oxfords"],
    ["oxford_noir", "暗黑牛津鞋", "noir oxfords", "牛津、正、暗黑", "oxford, formal, noir", "暗調電影感的繫帶皮鞋", "in noir lighting, laced leather oxfords", "noir, leather oxfords"],
    ["oxford_soft", "柔光牛津鞋", "soft-light oxfords", "牛津、正、柔光", "oxford, formal, soft", "柔光下的繫帶皮鞋", "under soft light, laced leather oxfords", "soft-lit, leather oxfords"],
    ["oxford_epic", "史詩牛津鞋", "epic oxfords", "牛津、正、史詩", "oxford, formal, epic", "史詩尺度的繫帶皮鞋", "at epic scale, laced leather oxfords", "epic, leather oxfords"],
    ["sneaker_court", "宮廷舊白波鞋", "court worn sneakers", "波鞋、街、宮廷", "sneaker, street, courtly", "宮廷氣場下的舊白球鞋", "in a courtly register, slightly worn white sneakers", "courtly, worn white sneakers"],
    ["sneaker_street", "街頭舊白波鞋", "street worn sneakers", "波鞋、街、街頭", "sneaker, street, street", "街頭質感的舊白球鞋", "with street grit, slightly worn white sneakers", "street-cast, worn white sneakers"],
    ["sneaker_noir", "暗黑舊白波鞋", "noir worn sneakers", "波鞋、街、暗黑", "sneaker, street, noir", "暗調電影感的舊白球鞋", "in noir lighting, slightly worn white sneakers", "noir, worn white sneakers"],
    ["sneaker_soft", "柔光舊白波鞋", "soft-light worn sneakers", "波鞋、街、柔光", "sneaker, street, soft", "柔光下的舊白球鞋", "under soft light, slightly worn white sneakers", "soft-lit, worn white sneakers"],
    ["sneaker_epic", "史詩舊白波鞋", "epic worn sneakers", "波鞋、街、史詩", "sneaker, street, epic", "史詩尺度的舊白球鞋", "at epic scale, slightly worn white sneakers", "epic, worn white sneakers"],
    ["heel_court", "宮廷細跟高跟鞋", "court stiletto", "高跟、鋒、宮廷", "heel, edge, courtly", "宮廷氣場下的細跟高跟鞋", "in a courtly register, stiletto heels", "courtly, stiletto heels"],
    ["heel_street", "街頭細跟高跟鞋", "street stiletto", "高跟、鋒、街頭", "heel, edge, street", "街頭質感的細跟高跟鞋", "with street grit, stiletto heels", "street-cast, stiletto heels"],
    ["heel_noir", "暗黑細跟高跟鞋", "noir stiletto", "高跟、鋒、暗黑", "heel, edge, noir", "暗調電影感的細跟高跟鞋", "in noir lighting, stiletto heels", "noir, stiletto heels"],
    ["heel_soft", "柔光細跟高跟鞋", "soft-light stiletto", "高跟、鋒、柔光", "heel, edge, soft", "柔光下的細跟高跟鞋", "under soft light, stiletto heels", "soft-lit, stiletto heels"],
    ["heel_epic", "史詩細跟高跟鞋", "epic stiletto", "高跟、鋒、史詩", "heel, edge, epic", "史詩尺度的細跟高跟鞋", "at epic scale, stiletto heels", "epic, stiletto heels"],
    ["flats_court", "宮廷平底軟鞋", "court soft flats", "平底、靜、宮廷", "flats, quiet, courtly", "宮廷氣場下的軟底平底", "in a courtly register, soft flat shoes", "courtly, soft flats"],
    ["flats_street", "街頭平底軟鞋", "street soft flats", "平底、靜、街頭", "flats, quiet, street", "街頭質感的軟底平底", "with street grit, soft flat shoes", "street-cast, soft flats"],
    ["flats_noir", "暗黑平底軟鞋", "noir soft flats", "平底、靜、暗黑", "flats, quiet, noir", "暗調電影感的軟底平底", "in noir lighting, soft flat shoes", "noir, soft flats"],
    ["flats_soft", "柔光平底軟鞋", "soft-light soft flats", "平底、靜、柔光", "flats, quiet, soft", "柔光下的軟底平底", "under soft light, soft flat shoes", "soft-lit, soft flats"],
    ["flats_epic", "史詩平底軟鞋", "epic soft flats", "平底、靜、史詩", "flats, quiet, epic", "史詩尺度的軟底平底", "at epic scale, soft flat shoes", "epic, soft flats"],
    ["combat_court", "宮廷作戰靴", "court combat boots", "戰靴、沉、宮廷", "combat, heavy, courtly", "宮廷氣場下的厚底戰靴", "in a courtly register, heavy combat boots", "courtly, combat boots"],
    ["combat_street", "街頭作戰靴", "street combat boots", "戰靴、沉、街頭", "combat, heavy, street", "街頭質感的厚底戰靴", "with street grit, heavy combat boots", "street-cast, combat boots"],
    ["combat_noir", "暗黑作戰靴", "noir combat boots", "戰靴、沉、暗黑", "combat, heavy, noir", "暗調電影感的厚底戰靴", "in noir lighting, heavy combat boots", "noir, combat boots"],
    ["combat_soft", "柔光作戰靴", "soft-light combat boots", "戰靴、沉、柔光", "combat, heavy, soft", "柔光下的厚底戰靴", "under soft light, heavy combat boots", "soft-lit, combat boots"],
    ["combat_epic", "史詩作戰靴", "epic combat boots", "戰靴、沉、史詩", "combat, heavy, epic", "史詩尺度的厚底戰靴", "at epic scale, heavy combat boots", "epic, combat boots"],
    ["cloth_shoe_court", "宮廷布履", "court cloth shoes", "布履、古、宮廷", "cloth, period, courtly", "宮廷氣場下的古風布鞋", "in a courtly register, period cloth shoes", "courtly, cloth period shoes"],
    ["cloth_shoe_street", "街頭布履", "street cloth shoes", "布履、古、街頭", "cloth, period, street", "街頭質感的古風布鞋", "with street grit, period cloth shoes", "street-cast, cloth period shoes"],
    ["cloth_shoe_noir", "暗黑布履", "noir cloth shoes", "布履、古、暗黑", "cloth, period, noir", "暗調電影感的古風布鞋", "in noir lighting, period cloth shoes", "noir, cloth period shoes"],
    ["cloth_shoe_soft", "柔光布履", "soft-light cloth shoes", "布履、古、柔光", "cloth, period, soft", "柔光下的古風布鞋", "under soft light, period cloth shoes", "soft-lit, cloth period shoes"],
    ["cloth_shoe_epic", "史詩布履", "epic cloth shoes", "布履、古、史詩", "cloth, period, epic", "史詩尺度的古風布鞋", "at epic scale, period cloth shoes", "epic, cloth period shoes"],
    ["bare_court", "宮廷赤足／薄襪", "court bare or socks", "赤足、弱、宮廷", "bare, vulnerable, courtly", "宮廷氣場下的幾乎赤足", "in a courtly register, nearly bare feet", "courtly, bare feet or thin socks"],
    ["bare_street", "街頭赤足／薄襪", "street bare or socks", "赤足、弱、街頭", "bare, vulnerable, street", "街頭質感的幾乎赤足", "with street grit, nearly bare feet", "street-cast, bare feet or thin socks"],
    ["bare_noir", "暗黑赤足／薄襪", "noir bare or socks", "赤足、弱、暗黑", "bare, vulnerable, noir", "暗調電影感的幾乎赤足", "in noir lighting, nearly bare feet", "noir, bare feet or thin socks"],
    ["bare_soft", "柔光赤足／薄襪", "soft-light bare or socks", "赤足、弱、柔光", "bare, vulnerable, soft", "柔光下的幾乎赤足", "under soft light, nearly bare feet", "soft-lit, bare feet or thin socks"],
    ["bare_epic", "史詩赤足／薄襪", "epic bare or socks", "赤足、弱、史詩", "bare, vulnerable, epic", "史詩尺度的幾乎赤足", "at epic scale, nearly bare feet", "epic, bare feet or thin socks"],
    ["platform_court", "宮廷厚底", "court platforms", "厚底、誇、宮廷", "platform, bold, courtly", "宮廷氣場下的明顯厚底", "in a courtly register, visible platforms", "courtly, platform shoes"],
    ["platform_street", "街頭厚底", "street platforms", "厚底、誇、街頭", "platform, bold, street", "街頭質感的明顯厚底", "with street grit, visible platforms", "street-cast, platform shoes"],
    ["platform_noir", "暗黑厚底", "noir platforms", "厚底、誇、暗黑", "platform, bold, noir", "暗調電影感的明顯厚底", "in noir lighting, visible platforms", "noir, platform shoes"],
    ["platform_soft", "柔光厚底", "soft-light platforms", "厚底、誇、柔光", "platform, bold, soft", "柔光下的明顯厚底", "under soft light, visible platforms", "soft-lit, platform shoes"],
    ["platform_epic", "史詩厚底", "epic platforms", "厚底、誇、史詩", "platform, bold, epic", "史詩尺度的明顯厚底", "at epic scale, visible platforms", "epic, platform shoes"],
    ["sandal_court", "宮廷綁帶涼鞋", "court strappy sandals", "涼鞋、露、宮廷", "sandal, open, courtly", "宮廷氣場下的腳背綁帶", "in a courtly register, strappy open sandals", "courtly, strappy sandals"],
    ["sandal_street", "街頭綁帶涼鞋", "street strappy sandals", "涼鞋、露、街頭", "sandal, open, street", "街頭質感的腳背綁帶", "with street grit, strappy open sandals", "street-cast, strappy sandals"],
    ["sandal_noir", "暗黑綁帶涼鞋", "noir strappy sandals", "涼鞋、露、暗黑", "sandal, open, noir", "暗調電影感的腳背綁帶", "in noir lighting, strappy open sandals", "noir, strappy sandals"],
    ["sandal_soft", "柔光綁帶涼鞋", "soft-light strappy sandals", "涼鞋、露、柔光", "sandal, open, soft", "柔光下的腳背綁帶", "under soft light, strappy open sandals", "soft-lit, strappy sandals"],
    ["sandal_epic", "史詩綁帶涼鞋", "epic strappy sandals", "涼鞋、露、史詩", "sandal, open, epic", "史詩尺度的腳背綁帶", "at epic scale, strappy open sandals", "epic, strappy sandals"]
  ],
    accessory: [
    ["earring_one_court", "宮廷單邊耳飾", "court single earring", "單耳、記、宮廷", "one earring, mark, courtly", "宮廷氣場下的只一邊耳飾", "in a courtly register, one-sided earring", "courtly, single statement earring"],
    ["earring_one_street", "街頭單邊耳飾", "street single earring", "單耳、記、街頭", "one earring, mark, street", "街頭質感的只一邊耳飾", "with street grit, one-sided earring", "street-cast, single statement earring"],
    ["earring_one_noir", "暗黑單邊耳飾", "noir single earring", "單耳、記、暗黑", "one earring, mark, noir", "暗調電影感的只一邊耳飾", "in noir lighting, one-sided earring", "noir, single statement earring"],
    ["earring_one_soft", "柔光單邊耳飾", "soft-light single earring", "單耳、記、柔光", "one earring, mark, soft", "柔光下的只一邊耳飾", "under soft light, one-sided earring", "soft-lit, single statement earring"],
    ["earring_one_epic", "史詩單邊耳飾", "epic single earring", "單耳、記、史詩", "one earring, mark, epic", "史詩尺度的只一邊耳飾", "at epic scale, one-sided earring", "epic, single statement earring"],
    ["necklace_thin_court", "宮廷細鏈", "court thin chain", "細鏈、鎖骨、宮廷", "thin chain, clavicle, courtly", "宮廷氣場下的鎖骨細鏈", "in a courtly register, clavicle chain", "courtly, thin necklace"],
    ["necklace_thin_street", "街頭細鏈", "street thin chain", "細鏈、鎖骨、街頭", "thin chain, clavicle, street", "街頭質感的鎖骨細鏈", "with street grit, clavicle chain", "street-cast, thin necklace"],
    ["necklace_thin_noir", "暗黑細鏈", "noir thin chain", "細鏈、鎖骨、暗黑", "thin chain, clavicle, noir", "暗調電影感的鎖骨細鏈", "in noir lighting, clavicle chain", "noir, thin necklace"],
    ["necklace_thin_soft", "柔光細鏈", "soft-light thin chain", "細鏈、鎖骨、柔光", "thin chain, clavicle, soft", "柔光下的鎖骨細鏈", "under soft light, clavicle chain", "soft-lit, thin necklace"],
    ["necklace_thin_epic", "史詩細鏈", "epic thin chain", "細鏈、鎖骨、史詩", "thin chain, clavicle, epic", "史詩尺度的鎖骨細鏈", "at epic scale, clavicle chain", "epic, thin necklace"],
    ["glove_court", "宮廷手套", "court gloves", "手套、距、宮廷", "gloves, distance, courtly", "宮廷氣場下的過腕手套", "in a courtly register, wrist-plus gloves", "courtly, fitted gloves"],
    ["glove_street", "街頭手套", "street gloves", "手套、距、街頭", "gloves, distance, street", "街頭質感的過腕手套", "with street grit, wrist-plus gloves", "street-cast, fitted gloves"],
    ["glove_noir", "暗黑手套", "noir gloves", "手套、距、暗黑", "gloves, distance, noir", "暗調電影感的過腕手套", "in noir lighting, wrist-plus gloves", "noir, fitted gloves"],
    ["glove_soft", "柔光手套", "soft-light gloves", "手套、距、柔光", "gloves, distance, soft", "柔光下的過腕手套", "under soft light, wrist-plus gloves", "soft-lit, fitted gloves"],
    ["glove_epic", "史詩手套", "epic gloves", "手套、距、史詩", "gloves, distance, epic", "史詩尺度的過腕手套", "at epic scale, wrist-plus gloves", "epic, fitted gloves"],
    ["hairpin_court", "宮廷簪／釵", "court hairpin", "簪、古、宮廷", "pin, period, courtly", "宮廷氣場下的髮間一簪", "in a courtly register, one hairpin", "courtly, ornate hairpin"],
    ["hairpin_street", "街頭簪／釵", "street hairpin", "簪、古、街頭", "pin, period, street", "街頭質感的髮間一簪", "with street grit, one hairpin", "street-cast, ornate hairpin"],
    ["hairpin_noir", "暗黑簪／釵", "noir hairpin", "簪、古、暗黑", "pin, period, noir", "暗調電影感的髮間一簪", "in noir lighting, one hairpin", "noir, ornate hairpin"],
    ["hairpin_soft", "柔光簪／釵", "soft-light hairpin", "簪、古、柔光", "pin, period, soft", "柔光下的髮間一簪", "under soft light, one hairpin", "soft-lit, ornate hairpin"],
    ["hairpin_epic", "史詩簪／釵", "epic hairpin", "簪、古、史詩", "pin, period, epic", "史詩尺度的髮間一簪", "at epic scale, one hairpin", "epic, ornate hairpin"],
    ["glasses_court", "宮廷細框眼鏡", "court thin glasses", "眼鏡、知、宮廷", "glasses, intellect, courtly", "宮廷氣場下的細金屬框", "in a courtly register, thin metal frames", "courtly, thin-rim glasses"],
    ["glasses_street", "街頭細框眼鏡", "street thin glasses", "眼鏡、知、街頭", "glasses, intellect, street", "街頭質感的細金屬框", "with street grit, thin metal frames", "street-cast, thin-rim glasses"],
    ["glasses_noir", "暗黑細框眼鏡", "noir thin glasses", "眼鏡、知、暗黑", "glasses, intellect, noir", "暗調電影感的細金屬框", "in noir lighting, thin metal frames", "noir, thin-rim glasses"],
    ["glasses_soft", "柔光細框眼鏡", "soft-light thin glasses", "眼鏡、知、柔光", "glasses, intellect, soft", "柔光下的細金屬框", "under soft light, thin metal frames", "soft-lit, thin-rim glasses"],
    ["glasses_epic", "史詩細框眼鏡", "epic thin glasses", "眼鏡、知、史詩", "glasses, intellect, epic", "史詩尺度的細金屬框", "at epic scale, thin metal frames", "epic, thin-rim glasses"],
    ["watch_court", "宮廷冷金屬錶", "court cool metal watch", "錶、冷、宮廷", "watch, cool, courtly", "宮廷氣場下的金屬腕錶", "in a courtly register, metal wristwatch", "courtly, cool metal watch"],
    ["watch_street", "街頭冷金屬錶", "street cool metal watch", "錶、冷、街頭", "watch, cool, street", "街頭質感的金屬腕錶", "with street grit, metal wristwatch", "street-cast, cool metal watch"],
    ["watch_noir", "暗黑冷金屬錶", "noir cool metal watch", "錶、冷、暗黑", "watch, cool, noir", "暗調電影感的金屬腕錶", "in noir lighting, metal wristwatch", "noir, cool metal watch"],
    ["watch_soft", "柔光冷金屬錶", "soft-light cool metal watch", "錶、冷、柔光", "watch, cool, soft", "柔光下的金屬腕錶", "under soft light, metal wristwatch", "soft-lit, cool metal watch"],
    ["watch_epic", "史詩冷金屬錶", "epic cool metal watch", "錶、冷、史詩", "watch, cool, epic", "史詩尺度的金屬腕錶", "at epic scale, metal wristwatch", "epic, cool metal watch"],
    ["belt_wide_court", "宮廷寬腰帶", "court wide belt", "寬帶、腰、宮廷", "wide belt, waist, courtly", "宮廷氣場下的強調腰線寬帶", "in a courtly register, waist-cinching belt", "courtly, wide statement belt"],
    ["belt_wide_street", "街頭寬腰帶", "street wide belt", "寬帶、腰、街頭", "wide belt, waist, street", "街頭質感的強調腰線寬帶", "with street grit, waist-cinching belt", "street-cast, wide statement belt"],
    ["belt_wide_noir", "暗黑寬腰帶", "noir wide belt", "寬帶、腰、暗黑", "wide belt, waist, noir", "暗調電影感的強調腰線寬帶", "in noir lighting, waist-cinching belt", "noir, wide statement belt"],
    ["belt_wide_soft", "柔光寬腰帶", "soft-light wide belt", "寬帶、腰、柔光", "wide belt, waist, soft", "柔光下的強調腰線寬帶", "under soft light, waist-cinching belt", "soft-lit, wide statement belt"],
    ["belt_wide_epic", "史詩寬腰帶", "epic wide belt", "寬帶、腰、史詩", "wide belt, waist, epic", "史詩尺度的強調腰線寬帶", "at epic scale, waist-cinching belt", "epic, wide statement belt"],
    ["mask_court", "宮廷半臉面具", "court half mask", "面具、謎、宮廷", "mask, mystery, courtly", "宮廷氣場下的半臉硬面具", "in a courtly register, hard half mask", "courtly, half-face mask"],
    ["mask_street", "街頭半臉面具", "street half mask", "面具、謎、街頭", "mask, mystery, street", "街頭質感的半臉硬面具", "with street grit, hard half mask", "street-cast, half-face mask"],
    ["mask_noir", "暗黑半臉面具", "noir half mask", "面具、謎、暗黑", "mask, mystery, noir", "暗調電影感的半臉硬面具", "in noir lighting, hard half mask", "noir, half-face mask"],
    ["mask_soft", "柔光半臉面具", "soft-light half mask", "面具、謎、柔光", "mask, mystery, soft", "柔光下的半臉硬面具", "under soft light, hard half mask", "soft-lit, half-face mask"],
    ["mask_epic", "史詩半臉面具", "epic half mask", "面具、謎、史詩", "mask, mystery, epic", "史詩尺度的半臉硬面具", "at epic scale, hard half mask", "epic, half-face mask"],
    ["none_court", "宮廷無飾", "court no accessory", "無飾、淨、宮廷", "none, clean, courtly", "宮廷氣場下的幾乎無飾物", "in a courtly register, almost no jewelry", "courtly, no accessories"],
    ["none_street", "街頭無飾", "street no accessory", "無飾、淨、街頭", "none, clean, street", "街頭質感的幾乎無飾物", "with street grit, almost no jewelry", "street-cast, no accessories"],
    ["none_noir", "暗黑無飾", "noir no accessory", "無飾、淨、暗黑", "none, clean, noir", "暗調電影感的幾乎無飾物", "in noir lighting, almost no jewelry", "noir, no accessories"],
    ["none_soft", "柔光無飾", "soft-light no accessory", "無飾、淨、柔光", "none, clean, soft", "柔光下的幾乎無飾物", "under soft light, almost no jewelry", "soft-lit, no accessories"],
    ["none_epic", "史詩無飾", "epic no accessory", "無飾、淨、史詩", "none, clean, epic", "史詩尺度的幾乎無飾物", "at epic scale, almost no jewelry", "epic, no accessories"],
    ["ring_signet_court", "宮廷印章戒指", "court signet ring", "印戒、權、宮廷", "signet, power, courtly", "宮廷氣場下的一枚印章戒", "in a courtly register, one signet ring", "courtly, signet ring"],
    ["ring_signet_street", "街頭印章戒指", "street signet ring", "印戒、權、街頭", "signet, power, street", "街頭質感的一枚印章戒", "with street grit, one signet ring", "street-cast, signet ring"],
    ["ring_signet_noir", "暗黑印章戒指", "noir signet ring", "印戒、權、暗黑", "signet, power, noir", "暗調電影感的一枚印章戒", "in noir lighting, one signet ring", "noir, signet ring"],
    ["ring_signet_soft", "柔光印章戒指", "soft-light signet ring", "印戒、權、柔光", "signet, power, soft", "柔光下的一枚印章戒", "under soft light, one signet ring", "soft-lit, signet ring"],
    ["ring_signet_epic", "史詩印章戒指", "epic signet ring", "印戒、權、史詩", "signet, power, epic", "史詩尺度的一枚印章戒", "at epic scale, one signet ring", "epic, signet ring"]
  ],
    fabric: [
    ["silk_court", "宮廷冷絲", "court cool silk", "絲、光、宮廷", "silk, sheen, courtly", "宮廷氣場下的冷光絲綢", "in a courtly register, cool silk sheen", "courtly, cool silk fabric"],
    ["silk_street", "街頭冷絲", "street cool silk", "絲、光、街頭", "silk, sheen, street", "街頭質感的冷光絲綢", "with street grit, cool silk sheen", "street-cast, cool silk fabric"],
    ["silk_noir", "暗黑冷絲", "noir cool silk", "絲、光、暗黑", "silk, sheen, noir", "暗調電影感的冷光絲綢", "in noir lighting, cool silk sheen", "noir, cool silk fabric"],
    ["silk_soft", "柔光冷絲", "soft-light cool silk", "絲、光、柔光", "silk, sheen, soft", "柔光下的冷光絲綢", "under soft light, cool silk sheen", "soft-lit, cool silk fabric"],
    ["silk_epic", "史詩冷絲", "epic cool silk", "絲、光、史詩", "silk, sheen, epic", "史詩尺度的冷光絲綢", "at epic scale, cool silk sheen", "epic, cool silk fabric"],
    ["wool_court", "宮廷細羊毛", "court fine wool", "毛、沉、宮廷", "wool, matte, courtly", "宮廷氣場下的啞光細羊毛", "in a courtly register, matte fine wool", "courtly, fine wool"],
    ["wool_street", "街頭細羊毛", "street fine wool", "毛、沉、街頭", "wool, matte, street", "街頭質感的啞光細羊毛", "with street grit, matte fine wool", "street-cast, fine wool"],
    ["wool_noir", "暗黑細羊毛", "noir fine wool", "毛、沉、暗黑", "wool, matte, noir", "暗調電影感的啞光細羊毛", "in noir lighting, matte fine wool", "noir, fine wool"],
    ["wool_soft", "柔光細羊毛", "soft-light fine wool", "毛、沉、柔光", "wool, matte, soft", "柔光下的啞光細羊毛", "under soft light, matte fine wool", "soft-lit, fine wool"],
    ["wool_epic", "史詩細羊毛", "epic fine wool", "毛、沉、史詩", "wool, matte, epic", "史詩尺度的啞光細羊毛", "at epic scale, matte fine wool", "epic, fine wool"],
    ["linen_court", "宮廷亞麻", "court linen", "麻、透氣、宮廷", "linen, breath, courtly", "宮廷氣場下的可見麻紋", "in a courtly register, visible linen weave", "courtly, linen weave"],
    ["linen_street", "街頭亞麻", "street linen", "麻、透氣、街頭", "linen, breath, street", "街頭質感的可見麻紋", "with street grit, visible linen weave", "street-cast, linen weave"],
    ["linen_noir", "暗黑亞麻", "noir linen", "麻、透氣、暗黑", "linen, breath, noir", "暗調電影感的可見麻紋", "in noir lighting, visible linen weave", "noir, linen weave"],
    ["linen_soft", "柔光亞麻", "soft-light linen", "麻、透氣、柔光", "linen, breath, soft", "柔光下的可見麻紋", "under soft light, visible linen weave", "soft-lit, linen weave"],
    ["linen_epic", "史詩亞麻", "epic linen", "麻、透氣、史詩", "linen, breath, epic", "史詩尺度的可見麻紋", "at epic scale, visible linen weave", "epic, linen weave"],
    ["leather_court", "宮廷霧面皮", "court matte leather", "皮、硬、宮廷", "leather, hard, courtly", "宮廷氣場下的霧面皮革", "in a courtly register, matte leather", "courtly, matte leather"],
    ["leather_street", "街頭霧面皮", "street matte leather", "皮、硬、街頭", "leather, hard, street", "街頭質感的霧面皮革", "with street grit, matte leather", "street-cast, matte leather"],
    ["leather_noir", "暗黑霧面皮", "noir matte leather", "皮、硬、暗黑", "leather, hard, noir", "暗調電影感的霧面皮革", "in noir lighting, matte leather", "noir, matte leather"],
    ["leather_soft", "柔光霧面皮", "soft-light matte leather", "皮、硬、柔光", "leather, hard, soft", "柔光下的霧面皮革", "under soft light, matte leather", "soft-lit, matte leather"],
    ["leather_epic", "史詩霧面皮", "epic matte leather", "皮、硬、史詩", "leather, hard, epic", "史詩尺度的霧面皮革", "at epic scale, matte leather", "epic, matte leather"],
    ["denim_court", "宮廷洗水牛仔", "court washed denim", "牛仔、舊、宮廷", "denim, worn, courtly", "宮廷氣場下的輕洗水丹寧", "in a courtly register, light-washed denim", "courtly, washed denim"],
    ["denim_street", "街頭洗水牛仔", "street washed denim", "牛仔、舊、街頭", "denim, worn, street", "街頭質感的輕洗水丹寧", "with street grit, light-washed denim", "street-cast, washed denim"],
    ["denim_noir", "暗黑洗水牛仔", "noir washed denim", "牛仔、舊、暗黑", "denim, worn, noir", "暗調電影感的輕洗水丹寧", "in noir lighting, light-washed denim", "noir, washed denim"],
    ["denim_soft", "柔光洗水牛仔", "soft-light washed denim", "牛仔、舊、柔光", "denim, worn, soft", "柔光下的輕洗水丹寧", "under soft light, light-washed denim", "soft-lit, washed denim"],
    ["denim_epic", "史詩洗水牛仔", "epic washed denim", "牛仔、舊、史詩", "denim, worn, epic", "史詩尺度的輕洗水丹寧", "at epic scale, light-washed denim", "epic, washed denim"],
    ["velvet_court", "宮廷絲絨", "court velvet", "絨、貴、宮廷", "velvet, luxe, courtly", "宮廷氣場下的吸光絲絨", "in a courtly register, light-absorbing velvet", "courtly, velvet"],
    ["velvet_street", "街頭絲絨", "street velvet", "絨、貴、街頭", "velvet, luxe, street", "街頭質感的吸光絲絨", "with street grit, light-absorbing velvet", "street-cast, velvet"],
    ["velvet_noir", "暗黑絲絨", "noir velvet", "絨、貴、暗黑", "velvet, luxe, noir", "暗調電影感的吸光絲絨", "in noir lighting, light-absorbing velvet", "noir, velvet"],
    ["velvet_soft", "柔光絲絨", "soft-light velvet", "絨、貴、柔光", "velvet, luxe, soft", "柔光下的吸光絲絨", "under soft light, light-absorbing velvet", "soft-lit, velvet"],
    ["velvet_epic", "史詩絲絨", "epic velvet", "絨、貴、史詩", "velvet, luxe, epic", "史詩尺度的吸光絲絨", "at epic scale, light-absorbing velvet", "epic, velvet"],
    ["chiffon_court", "宮廷雪紡", "court chiffon", "紗、飄、宮廷", "chiffon, float, courtly", "宮廷氣場下的輕透雪紡", "in a courtly register, sheer chiffon", "courtly, chiffon"],
    ["chiffon_street", "街頭雪紡", "street chiffon", "紗、飄、街頭", "chiffon, float, street", "街頭質感的輕透雪紡", "with street grit, sheer chiffon", "street-cast, chiffon"],
    ["chiffon_noir", "暗黑雪紡", "noir chiffon", "紗、飄、暗黑", "chiffon, float, noir", "暗調電影感的輕透雪紡", "in noir lighting, sheer chiffon", "noir, chiffon"],
    ["chiffon_soft", "柔光雪紡", "soft-light chiffon", "紗、飄、柔光", "chiffon, float, soft", "柔光下的輕透雪紡", "under soft light, sheer chiffon", "soft-lit, chiffon"],
    ["chiffon_epic", "史詩雪紡", "epic chiffon", "紗、飄、史詩", "chiffon, float, epic", "史詩尺度的輕透雪紡", "at epic scale, sheer chiffon", "epic, chiffon"],
    ["brocade_court", "宮廷織錦", "court brocade", "錦、古、宮廷", "brocade, period, courtly", "宮廷氣場下的暗紋織錦", "in a courtly register, figured brocade", "courtly, brocade"],
    ["brocade_street", "街頭織錦", "street brocade", "錦、古、街頭", "brocade, period, street", "街頭質感的暗紋織錦", "with street grit, figured brocade", "street-cast, brocade"],
    ["brocade_noir", "暗黑織錦", "noir brocade", "錦、古、暗黑", "brocade, period, noir", "暗調電影感的暗紋織錦", "in noir lighting, figured brocade", "noir, brocade"],
    ["brocade_soft", "柔光織錦", "soft-light brocade", "錦、古、柔光", "brocade, period, soft", "柔光下的暗紋織錦", "under soft light, figured brocade", "soft-lit, brocade"],
    ["brocade_epic", "史詩織錦", "epic brocade", "錦、古、史詩", "brocade, period, epic", "史詩尺度的暗紋織錦", "at epic scale, figured brocade", "epic, brocade"],
    ["tech_court", "宮廷機能面", "court tech shell", "機能、現、宮廷", "tech, modern, courtly", "宮廷氣場下的啞光機能布", "in a courtly register, matte technical shell", "courtly, technical shell fabric"],
    ["tech_street", "街頭機能面", "street tech shell", "機能、現、街頭", "tech, modern, street", "街頭質感的啞光機能布", "with street grit, matte technical shell", "street-cast, technical shell fabric"],
    ["tech_noir", "暗黑機能面", "noir tech shell", "機能、現、暗黑", "tech, modern, noir", "暗調電影感的啞光機能布", "in noir lighting, matte technical shell", "noir, technical shell fabric"],
    ["tech_soft", "柔光機能面", "soft-light tech shell", "機能、現、柔光", "tech, modern, soft", "柔光下的啞光機能布", "under soft light, matte technical shell", "soft-lit, technical shell fabric"],
    ["tech_epic", "史詩機能面", "epic tech shell", "機能、現、史詩", "tech, modern, epic", "史詩尺度的啞光機能布", "at epic scale, matte technical shell", "epic, technical shell fabric"],
    ["cotton_court", "宮廷軟棉", "court soft cotton", "棉、親、宮廷", "cotton, soft, courtly", "宮廷氣場下的霧面軟棉", "in a courtly register, matte soft cotton", "courtly, soft cotton"],
    ["cotton_street", "街頭軟棉", "street soft cotton", "棉、親、街頭", "cotton, soft, street", "街頭質感的霧面軟棉", "with street grit, matte soft cotton", "street-cast, soft cotton"],
    ["cotton_noir", "暗黑軟棉", "noir soft cotton", "棉、親、暗黑", "cotton, soft, noir", "暗調電影感的霧面軟棉", "in noir lighting, matte soft cotton", "noir, soft cotton"],
    ["cotton_soft", "柔光軟棉", "soft-light soft cotton", "棉、親、柔光", "cotton, soft, soft", "柔光下的霧面軟棉", "under soft light, matte soft cotton", "soft-lit, soft cotton"],
    ["cotton_epic", "史詩軟棉", "epic soft cotton", "棉、親、史詩", "cotton, soft, epic", "史詩尺度的霧面軟棉", "at epic scale, matte soft cotton", "epic, soft cotton"]
  ],
    palette: [
    ["ink_court", "宮廷墨黑冷灰", "court ink and cool gray", "墨、冷、宮廷", "ink, cool, courtly", "宮廷氣場下的黑灰為主", "in a courtly register, ink-black and gray", "courtly, ink-black cool-gray palette"],
    ["ink_street", "街頭墨黑冷灰", "street ink and cool gray", "墨、冷、街頭", "ink, cool, street", "街頭質感的黑灰為主", "with street grit, ink-black and gray", "street-cast, ink-black cool-gray palette"],
    ["ink_noir", "暗黑墨黑冷灰", "noir ink and cool gray", "墨、冷、暗黑", "ink, cool, noir", "暗調電影感的黑灰為主", "in noir lighting, ink-black and gray", "noir, ink-black cool-gray palette"],
    ["ink_soft", "柔光墨黑冷灰", "soft-light ink and cool gray", "墨、冷、柔光", "ink, cool, soft", "柔光下的黑灰為主", "under soft light, ink-black and gray", "soft-lit, ink-black cool-gray palette"],
    ["ink_epic", "史詩墨黑冷灰", "epic ink and cool gray", "墨、冷、史詩", "ink, cool, epic", "史詩尺度的黑灰為主", "at epic scale, ink-black and gray", "epic, ink-black cool-gray palette"],
    ["ivory_gold_court", "宮廷牙白淡金", "court ivory gold", "牙白、金、宮廷", "ivory, gold, courtly", "宮廷氣場下的淺金點綴牙白", "in a courtly register, ivory with pale gold", "courtly, ivory and pale gold"],
    ["ivory_gold_street", "街頭牙白淡金", "street ivory gold", "牙白、金、街頭", "ivory, gold, street", "街頭質感的淺金點綴牙白", "with street grit, ivory with pale gold", "street-cast, ivory and pale gold"],
    ["ivory_gold_noir", "暗黑牙白淡金", "noir ivory gold", "牙白、金、暗黑", "ivory, gold, noir", "暗調電影感的淺金點綴牙白", "in noir lighting, ivory with pale gold", "noir, ivory and pale gold"],
    ["ivory_gold_soft", "柔光牙白淡金", "soft-light ivory gold", "牙白、金、柔光", "ivory, gold, soft", "柔光下的淺金點綴牙白", "under soft light, ivory with pale gold", "soft-lit, ivory and pale gold"],
    ["ivory_gold_epic", "史詩牙白淡金", "epic ivory gold", "牙白、金、史詩", "ivory, gold, epic", "史詩尺度的淺金點綴牙白", "at epic scale, ivory with pale gold", "epic, ivory and pale gold"],
    ["blood_court", "宮廷黑與一點紅", "court black with a blood accent", "黑、血、宮廷", "black, blood, courtly", "宮廷氣場下的全黑一點紅", "in a courtly register, all black, one red accent", "courtly, black with a blood-red accent"],
    ["blood_street", "街頭黑與一點紅", "street black with a blood accent", "黑、血、街頭", "black, blood, street", "街頭質感的全黑一點紅", "with street grit, all black, one red accent", "street-cast, black with a blood-red accent"],
    ["blood_noir", "暗黑黑與一點紅", "noir black with a blood accent", "黑、血、暗黑", "black, blood, noir", "暗調電影感的全黑一點紅", "in noir lighting, all black, one red accent", "noir, black with a blood-red accent"],
    ["blood_soft", "柔光黑與一點紅", "soft-light black with a blood accent", "黑、血、柔光", "black, blood, soft", "柔光下的全黑一點紅", "under soft light, all black, one red accent", "soft-lit, black with a blood-red accent"],
    ["blood_epic", "史詩黑與一點紅", "epic black with a blood accent", "黑、血、史詩", "black, blood, epic", "史詩尺度的全黑一點紅", "at epic scale, all black, one red accent", "epic, black with a blood-red accent"],
    ["navy_court", "宮廷藏青白", "court navy and white", "藏青、淨、宮廷", "navy, clean, courtly", "宮廷氣場下的藏青配白", "in a courtly register, navy with white", "courtly, navy-and-white palette"],
    ["navy_street", "街頭藏青白", "street navy and white", "藏青、淨、街頭", "navy, clean, street", "街頭質感的藏青配白", "with street grit, navy with white", "street-cast, navy-and-white palette"],
    ["navy_noir", "暗黑藏青白", "noir navy and white", "藏青、淨、暗黑", "navy, clean, noir", "暗調電影感的藏青配白", "in noir lighting, navy with white", "noir, navy-and-white palette"],
    ["navy_soft", "柔光藏青白", "soft-light navy and white", "藏青、淨、柔光", "navy, clean, soft", "柔光下的藏青配白", "under soft light, navy with white", "soft-lit, navy-and-white palette"],
    ["navy_epic", "史詩藏青白", "epic navy and white", "藏青、淨、史詩", "navy, clean, epic", "史詩尺度的藏青配白", "at epic scale, navy with white", "epic, navy-and-white palette"],
    ["earth_court", "宮廷褐土橄欖", "court earth olive", "褐、地、宮廷", "earth, olive, courtly", "宮廷氣場下的褐綠土色", "in a courtly register, brown-olive earth", "courtly, earth olive palette"],
    ["earth_street", "街頭褐土橄欖", "street earth olive", "褐、地、街頭", "earth, olive, street", "街頭質感的褐綠土色", "with street grit, brown-olive earth", "street-cast, earth olive palette"],
    ["earth_noir", "暗黑褐土橄欖", "noir earth olive", "褐、地、暗黑", "earth, olive, noir", "暗調電影感的褐綠土色", "in noir lighting, brown-olive earth", "noir, earth olive palette"],
    ["earth_soft", "柔光褐土橄欖", "soft-light earth olive", "褐、地、柔光", "earth, olive, soft", "柔光下的褐綠土色", "under soft light, brown-olive earth", "soft-lit, earth olive palette"],
    ["earth_epic", "史詩褐土橄欖", "epic earth olive", "褐、地、史詩", "earth, olive, epic", "史詩尺度的褐綠土色", "at epic scale, brown-olive earth", "epic, earth olive palette"],
    ["pastel_court", "宮廷低飽和粉彩", "court muted pastel", "粉彩、柔、宮廷", "pastel, soft, courtly", "宮廷氣場下的低飽和粉", "in a courtly register, desaturated pastels", "courtly, muted pastel palette"],
    ["pastel_street", "街頭低飽和粉彩", "street muted pastel", "粉彩、柔、街頭", "pastel, soft, street", "街頭質感的低飽和粉", "with street grit, desaturated pastels", "street-cast, muted pastel palette"],
    ["pastel_noir", "暗黑低飽和粉彩", "noir muted pastel", "粉彩、柔、暗黑", "pastel, soft, noir", "暗調電影感的低飽和粉", "in noir lighting, desaturated pastels", "noir, muted pastel palette"],
    ["pastel_soft", "柔光低飽和粉彩", "soft-light muted pastel", "粉彩、柔、柔光", "pastel, soft, soft", "柔光下的低飽和粉", "under soft light, desaturated pastels", "soft-lit, muted pastel palette"],
    ["pastel_epic", "史詩低飽和粉彩", "epic muted pastel", "粉彩、柔、史詩", "pastel, soft, epic", "史詩尺度的低飽和粉", "at epic scale, desaturated pastels", "epic, muted pastel palette"],
    ["jewel_court", "宮廷寶石濃色", "court jewel tones", "寶石、濃、宮廷", "jewel, rich, courtly", "宮廷氣場下的寶石飽和色", "in a courtly register, saturated jewel colors", "courtly, jewel-tone palette"],
    ["jewel_street", "街頭寶石濃色", "street jewel tones", "寶石、濃、街頭", "jewel, rich, street", "街頭質感的寶石飽和色", "with street grit, saturated jewel colors", "street-cast, jewel-tone palette"],
    ["jewel_noir", "暗黑寶石濃色", "noir jewel tones", "寶石、濃、暗黑", "jewel, rich, noir", "暗調電影感的寶石飽和色", "in noir lighting, saturated jewel colors", "noir, jewel-tone palette"],
    ["jewel_soft", "柔光寶石濃色", "soft-light jewel tones", "寶石、濃、柔光", "jewel, rich, soft", "柔光下的寶石飽和色", "under soft light, saturated jewel colors", "soft-lit, jewel-tone palette"],
    ["jewel_epic", "史詩寶石濃色", "epic jewel tones", "寶石、濃、史詩", "jewel, rich, epic", "史詩尺度的寶石飽和色", "at epic scale, saturated jewel colors", "epic, jewel-tone palette"],
    ["monochrome_court", "宮廷單色灰階", "court monochrome", "單色、影、宮廷", "mono, graphic, courtly", "宮廷氣場下的近灰階單色", "in a courtly register, near-gray monochrome", "courtly, monochrome palette"],
    ["monochrome_street", "街頭單色灰階", "street monochrome", "單色、影、街頭", "mono, graphic, street", "街頭質感的近灰階單色", "with street grit, near-gray monochrome", "street-cast, monochrome palette"],
    ["monochrome_noir", "暗黑單色灰階", "noir monochrome", "單色、影、暗黑", "mono, graphic, noir", "暗調電影感的近灰階單色", "in noir lighting, near-gray monochrome", "noir, monochrome palette"],
    ["monochrome_soft", "柔光單色灰階", "soft-light monochrome", "單色、影、柔光", "mono, graphic, soft", "柔光下的近灰階單色", "under soft light, near-gray monochrome", "soft-lit, monochrome palette"],
    ["monochrome_epic", "史詩單色灰階", "epic monochrome", "單色、影、史詩", "mono, graphic, epic", "史詩尺度的近灰階單色", "at epic scale, near-gray monochrome", "epic, monochrome palette"],
    ["teal_amber_court", "宮廷青與琥珀", "court teal and amber", "青、琥珀、宮廷", "teal, amber, courtly", "宮廷氣場下的青橙對比", "in a courtly register, teal-amber contrast", "courtly, teal and amber"],
    ["teal_amber_street", "街頭青與琥珀", "street teal and amber", "青、琥珀、街頭", "teal, amber, street", "街頭質感的青橙對比", "with street grit, teal-amber contrast", "street-cast, teal and amber"],
    ["teal_amber_noir", "暗黑青與琥珀", "noir teal and amber", "青、琥珀、暗黑", "teal, amber, noir", "暗調電影感的青橙對比", "in noir lighting, teal-amber contrast", "noir, teal and amber"],
    ["teal_amber_soft", "柔光青與琥珀", "soft-light teal and amber", "青、琥珀、柔光", "teal, amber, soft", "柔光下的青橙對比", "under soft light, teal-amber contrast", "soft-lit, teal and amber"],
    ["teal_amber_epic", "史詩青與琥珀", "epic teal and amber", "青、琥珀、史詩", "teal, amber, epic", "史詩尺度的青橙對比", "at epic scale, teal-amber contrast", "epic, teal and amber"],
    ["white_court", "宮廷冷白為主", "court cool white lead", "白、冷、宮廷", "white, cool, courtly", "宮廷氣場下的大面積冷白", "in a courtly register, large cool white fields", "courtly, cool-white-led palette"],
    ["white_street", "街頭冷白為主", "street cool white lead", "白、冷、街頭", "white, cool, street", "街頭質感的大面積冷白", "with street grit, large cool white fields", "street-cast, cool-white-led palette"],
    ["white_noir", "暗黑冷白為主", "noir cool white lead", "白、冷、暗黑", "white, cool, noir", "暗調電影感的大面積冷白", "in noir lighting, large cool white fields", "noir, cool-white-led palette"],
    ["white_soft", "柔光冷白為主", "soft-light cool white lead", "白、冷、柔光", "white, cool, soft", "柔光下的大面積冷白", "under soft light, large cool white fields", "soft-lit, cool-white-led palette"],
    ["white_epic", "史詩冷白為主", "epic cool white lead", "白、冷、史詩", "white, cool, epic", "史詩尺度的大面積冷白", "at epic scale, large cool white fields", "epic, cool-white-led palette"]
  ]
  }
})
