/**
 * hardRules field kit catalog (50+ templates per part).
 */
import { defineFieldKit } from '../fieldKit'

export const HARDRULES_KIT = defineFieldKit({
  key: "hardRulesKit",
  parts: ["faceLock","bodyLock","costumeLock","anatomyBan","textStyleBan","continuity"] as const,
  partLabels: {
    faceLock: { zhHK: "臉鎖", zhCN: "脸锁", en: "Face lock" },
    bodyLock: { zhHK: "身鎖", zhCN: "身锁", en: "Body lock" },
    costumeLock: { zhHK: "裝鎖", zhCN: "装锁", en: "Costume lock" },
    anatomyBan: { zhHK: "解剖禁", zhCN: "解剖禁", en: "Anatomy ban" },
    textStyleBan: { zhHK: "字風禁", zhCN: "字风禁", en: "Text/style ban" },
    continuity: { zhHK: "連續", zhCN: "连续", en: "Continuity" }
  },
  assembleMode: "rules",
  ruleKind: {"faceLock":"must","bodyLock":"must","costumeLock":"must","anatomyBan":"mustNot","textStyleBan":"mustNot","continuity":"must"},
  rows: {
    faceLock: [
    ["same_face_court", "宮廷同一張臉", "court same face", "臉、同、宮廷", "face, same, courtly", "宮廷氣場下的整段同一張臉", "in a courtly register, same face throughout", "courtly, keep the exact same face"],
    ["same_face_street", "街頭同一張臉", "street same face", "臉、同、街頭", "face, same, street", "街頭質感的整段同一張臉", "with street grit, same face throughout", "street-cast, keep the exact same face"],
    ["same_face_noir", "暗黑同一張臉", "noir same face", "臉、同、暗黑", "face, same, noir", "暗調電影感的整段同一張臉", "in noir lighting, same face throughout", "noir, keep the exact same face"],
    ["same_face_soft", "柔光同一張臉", "soft-light same face", "臉、同、柔光", "face, same, soft", "柔光下的整段同一張臉", "under soft light, same face throughout", "soft-lit, keep the exact same face"],
    ["same_face_epic", "史詩同一張臉", "epic same face", "臉、同、史詩", "face, same, epic", "史詩尺度的整段同一張臉", "at epic scale, same face throughout", "epic, keep the exact same face"],
    ["no_beauty_court", "宮廷不整容美顏", "court no beautify", "美顏、禁、宮廷", "beauty, ban, courtly", "宮廷氣場下的不要美顏變形", "in a courtly register, no beautifying warp", "courtly, do not beautify or warp the face"],
    ["no_beauty_street", "街頭不整容美顏", "street no beautify", "美顏、禁、街頭", "beauty, ban, street", "街頭質感的不要美顏變形", "with street grit, no beautifying warp", "street-cast, do not beautify or warp the face"],
    ["no_beauty_noir", "暗黑不整容美顏", "noir no beautify", "美顏、禁、暗黑", "beauty, ban, noir", "暗調電影感的不要美顏變形", "in noir lighting, no beautifying warp", "noir, do not beautify or warp the face"],
    ["no_beauty_soft", "柔光不整容美顏", "soft-light no beautify", "美顏、禁、柔光", "beauty, ban, soft", "柔光下的不要美顏變形", "under soft light, no beautifying warp", "soft-lit, do not beautify or warp the face"],
    ["no_beauty_epic", "史詩不整容美顏", "epic no beautify", "美顏、禁、史詩", "beauty, ban, epic", "史詩尺度的不要美顏變形", "at epic scale, no beautifying warp", "epic, do not beautify or warp the face"],
    ["keep_mole_court", "宮廷保留痣", "court keep moles", "痣、留、宮廷", "mole, keep, courtly", "宮廷氣場下的臉上標記保留", "in a courtly register, keep facial marks", "courtly, keep moles and facial marks"],
    ["keep_mole_street", "街頭保留痣", "street keep moles", "痣、留、街頭", "mole, keep, street", "街頭質感的臉上標記保留", "with street grit, keep facial marks", "street-cast, keep moles and facial marks"],
    ["keep_mole_noir", "暗黑保留痣", "noir keep moles", "痣、留、暗黑", "mole, keep, noir", "暗調電影感的臉上標記保留", "in noir lighting, keep facial marks", "noir, keep moles and facial marks"],
    ["keep_mole_soft", "柔光保留痣", "soft-light keep moles", "痣、留、柔光", "mole, keep, soft", "柔光下的臉上標記保留", "under soft light, keep facial marks", "soft-lit, keep moles and facial marks"],
    ["keep_mole_epic", "史詩保留痣", "epic keep moles", "痣、留、史詩", "mole, keep, epic", "史詩尺度的臉上標記保留", "at epic scale, keep facial marks", "epic, keep moles and facial marks"],
    ["eye_color_court", "宮廷瞳色不變", "court iris lock", "瞳、鎖、宮廷", "iris, lock, courtly", "宮廷氣場下的瞳色鎖定", "in a courtly register, lock iris color", "courtly, keep the same iris color"],
    ["eye_color_street", "街頭瞳色不變", "street iris lock", "瞳、鎖、街頭", "iris, lock, street", "街頭質感的瞳色鎖定", "with street grit, lock iris color", "street-cast, keep the same iris color"],
    ["eye_color_noir", "暗黑瞳色不變", "noir iris lock", "瞳、鎖、暗黑", "iris, lock, noir", "暗調電影感的瞳色鎖定", "in noir lighting, lock iris color", "noir, keep the same iris color"],
    ["eye_color_soft", "柔光瞳色不變", "soft-light iris lock", "瞳、鎖、柔光", "iris, lock, soft", "柔光下的瞳色鎖定", "under soft light, lock iris color", "soft-lit, keep the same iris color"],
    ["eye_color_epic", "史詩瞳色不變", "epic iris lock", "瞳、鎖、史詩", "iris, lock, epic", "史詩尺度的瞳色鎖定", "at epic scale, lock iris color", "epic, keep the same iris color"],
    ["age_court", "宮廷年齡不變", "court age lock", "齡、鎖、宮廷", "age, lock, courtly", "宮廷氣場下的看起來同年齡", "in a courtly register, same apparent age", "courtly, keep the same apparent age"],
    ["age_street", "街頭年齡不變", "street age lock", "齡、鎖、街頭", "age, lock, street", "街頭質感的看起來同年齡", "with street grit, same apparent age", "street-cast, keep the same apparent age"],
    ["age_noir", "暗黑年齡不變", "noir age lock", "齡、鎖、暗黑", "age, lock, noir", "暗調電影感的看起來同年齡", "in noir lighting, same apparent age", "noir, keep the same apparent age"],
    ["age_soft", "柔光年齡不變", "soft-light age lock", "齡、鎖、柔光", "age, lock, soft", "柔光下的看起來同年齡", "under soft light, same apparent age", "soft-lit, keep the same apparent age"],
    ["age_epic", "史詩年齡不變", "epic age lock", "齡、鎖、史詩", "age, lock, epic", "史詩尺度的看起來同年齡", "at epic scale, same apparent age", "epic, keep the same apparent age"],
    ["no_extra_face_court", "宮廷不多臉", "court no extra faces", "多臉、禁、宮廷", "extra face, ban, courtly", "宮廷氣場下的畫面不要多張臉", "in a courtly register, no extra faces in frame", "courtly, do not add extra faces"],
    ["no_extra_face_street", "街頭不多臉", "street no extra faces", "多臉、禁、街頭", "extra face, ban, street", "街頭質感的畫面不要多張臉", "with street grit, no extra faces in frame", "street-cast, do not add extra faces"],
    ["no_extra_face_noir", "暗黑不多臉", "noir no extra faces", "多臉、禁、暗黑", "extra face, ban, noir", "暗調電影感的畫面不要多張臉", "in noir lighting, no extra faces in frame", "noir, do not add extra faces"],
    ["no_extra_face_soft", "柔光不多臉", "soft-light no extra faces", "多臉、禁、柔光", "extra face, ban, soft", "柔光下的畫面不要多張臉", "under soft light, no extra faces in frame", "soft-lit, do not add extra faces"],
    ["no_extra_face_epic", "史詩不多臉", "epic no extra faces", "多臉、禁、史詩", "extra face, ban, epic", "史詩尺度的畫面不要多張臉", "at epic scale, no extra faces in frame", "epic, do not add extra faces"],
    ["identity_ref_court", "宮廷跟參考臉", "court match reference face", "參、跟、宮廷", "ref, match, courtly", "宮廷氣場下的跟參考圖的臉", "in a courtly register, match the reference face", "courtly, match the reference still face"],
    ["identity_ref_street", "街頭跟參考臉", "street match reference face", "參、跟、街頭", "ref, match, street", "街頭質感的跟參考圖的臉", "with street grit, match the reference face", "street-cast, match the reference still face"],
    ["identity_ref_noir", "暗黑跟參考臉", "noir match reference face", "參、跟、暗黑", "ref, match, noir", "暗調電影感的跟參考圖的臉", "in noir lighting, match the reference face", "noir, match the reference still face"],
    ["identity_ref_soft", "柔光跟參考臉", "soft-light match reference face", "參、跟、柔光", "ref, match, soft", "柔光下的跟參考圖的臉", "under soft light, match the reference face", "soft-lit, match the reference still face"],
    ["identity_ref_epic", "史詩跟參考臉", "epic match reference face", "參、跟、史詩", "ref, match, epic", "史詩尺度的跟參考圖的臉", "at epic scale, match the reference face", "epic, match the reference still face"],
    ["expression_range_court", "宮廷表情可動但骨不變", "court expression ok, bone lock", "骨、鎖、宮廷", "bone, lock, courtly", "宮廷氣場下的骨相不變只動表情", "in a courtly register, bones stay, expression may move", "courtly, lock bone structure, allow expression"],
    ["expression_range_street", "街頭表情可動但骨不變", "street expression ok, bone lock", "骨、鎖、街頭", "bone, lock, street", "街頭質感的骨相不變只動表情", "with street grit, bones stay, expression may move", "street-cast, lock bone structure, allow expression"],
    ["expression_range_noir", "暗黑表情可動但骨不變", "noir expression ok, bone lock", "骨、鎖、暗黑", "bone, lock, noir", "暗調電影感的骨相不變只動表情", "in noir lighting, bones stay, expression may move", "noir, lock bone structure, allow expression"],
    ["expression_range_soft", "柔光表情可動但骨不變", "soft-light expression ok, bone lock", "骨、鎖、柔光", "bone, lock, soft", "柔光下的骨相不變只動表情", "under soft light, bones stay, expression may move", "soft-lit, lock bone structure, allow expression"],
    ["expression_range_epic", "史詩表情可動但骨不變", "epic expression ok, bone lock", "骨、鎖、史詩", "bone, lock, epic", "史詩尺度的骨相不變只動表情", "at epic scale, bones stay, expression may move", "epic, lock bone structure, allow expression"],
    ["no_morph_court", "宮廷不融臉", "court no face morph", "融、禁、宮廷", "morph, ban, courtly", "宮廷氣場下的不要漸變成別人", "in a courtly register, do not morph into another person", "courtly, do not morph the face"],
    ["no_morph_street", "街頭不融臉", "street no face morph", "融、禁、街頭", "morph, ban, street", "街頭質感的不要漸變成別人", "with street grit, do not morph into another person", "street-cast, do not morph the face"],
    ["no_morph_noir", "暗黑不融臉", "noir no face morph", "融、禁、暗黑", "morph, ban, noir", "暗調電影感的不要漸變成別人", "in noir lighting, do not morph into another person", "noir, do not morph the face"],
    ["no_morph_soft", "柔光不融臉", "soft-light no face morph", "融、禁、柔光", "morph, ban, soft", "柔光下的不要漸變成別人", "under soft light, do not morph into another person", "soft-lit, do not morph the face"],
    ["no_morph_epic", "史詩不融臉", "epic no face morph", "融、禁、史詩", "morph, ban, epic", "史詩尺度的不要漸變成別人", "at epic scale, do not morph into another person", "epic, do not morph the face"],
    ["scars_stay_court", "宮廷疤留下", "court scars stay", "疤、留、宮廷", "scar, stay, courtly", "宮廷氣場下的疤與傷留下", "in a courtly register, scars remain", "courtly, keep scars on the face"],
    ["scars_stay_street", "街頭疤留下", "street scars stay", "疤、留、街頭", "scar, stay, street", "街頭質感的疤與傷留下", "with street grit, scars remain", "street-cast, keep scars on the face"],
    ["scars_stay_noir", "暗黑疤留下", "noir scars stay", "疤、留、暗黑", "scar, stay, noir", "暗調電影感的疤與傷留下", "in noir lighting, scars remain", "noir, keep scars on the face"],
    ["scars_stay_soft", "柔光疤留下", "soft-light scars stay", "疤、留、柔光", "scar, stay, soft", "柔光下的疤與傷留下", "under soft light, scars remain", "soft-lit, keep scars on the face"],
    ["scars_stay_epic", "史詩疤留下", "epic scars stay", "疤、留、史詩", "scar, stay, epic", "史詩尺度的疤與傷留下", "at epic scale, scars remain", "epic, keep scars on the face"]
  ],
    bodyLock: [
    ["two_hands_court", "宮廷兩手兩腳", "court two hands two feet", "肢、數、宮廷", "limb, count, courtly", "宮廷氣場下的恰好兩手兩腳", "in a courtly register, exactly two hands and feet", "courtly, exactly two hands and two feet"],
    ["two_hands_street", "街頭兩手兩腳", "street two hands two feet", "肢、數、街頭", "limb, count, street", "街頭質感的恰好兩手兩腳", "with street grit, exactly two hands and feet", "street-cast, exactly two hands and two feet"],
    ["two_hands_noir", "暗黑兩手兩腳", "noir two hands two feet", "肢、數、暗黑", "limb, count, noir", "暗調電影感的恰好兩手兩腳", "in noir lighting, exactly two hands and feet", "noir, exactly two hands and two feet"],
    ["two_hands_soft", "柔光兩手兩腳", "soft-light two hands two feet", "肢、數、柔光", "limb, count, soft", "柔光下的恰好兩手兩腳", "under soft light, exactly two hands and feet", "soft-lit, exactly two hands and two feet"],
    ["two_hands_epic", "史詩兩手兩腳", "epic two hands two feet", "肢、數、史詩", "limb, count, epic", "史詩尺度的恰好兩手兩腳", "at epic scale, exactly two hands and feet", "epic, exactly two hands and two feet"],
    ["height_court", "宮廷身高比例", "court height lock", "高、比、宮廷", "height, ratio, courtly", "宮廷氣場下的身高體型鎖定", "in a courtly register, lock height and build", "courtly, keep the same height and build"],
    ["height_street", "街頭身高比例", "street height lock", "高、比、街頭", "height, ratio, street", "街頭質感的身高體型鎖定", "with street grit, lock height and build", "street-cast, keep the same height and build"],
    ["height_noir", "暗黑身高比例", "noir height lock", "高、比、暗黑", "height, ratio, noir", "暗調電影感的身高體型鎖定", "in noir lighting, lock height and build", "noir, keep the same height and build"],
    ["height_soft", "柔光身高比例", "soft-light height lock", "高、比、柔光", "height, ratio, soft", "柔光下的身高體型鎖定", "under soft light, lock height and build", "soft-lit, keep the same height and build"],
    ["height_epic", "史詩身高比例", "epic height lock", "高、比、史詩", "height, ratio, epic", "史詩尺度的身高體型鎖定", "at epic scale, lock height and build", "epic, keep the same height and build"],
    ["no_extra_limb_court", "宮廷不多肢", "court no extra limbs", "多肢、禁、宮廷", "extra, ban, courtly", "宮廷氣場下的不要多手臂腿", "in a courtly register, no extra arms or legs", "courtly, no extra limbs"],
    ["no_extra_limb_street", "街頭不多肢", "street no extra limbs", "多肢、禁、街頭", "extra, ban, street", "街頭質感的不要多手臂腿", "with street grit, no extra arms or legs", "street-cast, no extra limbs"],
    ["no_extra_limb_noir", "暗黑不多肢", "noir no extra limbs", "多肢、禁、暗黑", "extra, ban, noir", "暗調電影感的不要多手臂腿", "in noir lighting, no extra arms or legs", "noir, no extra limbs"],
    ["no_extra_limb_soft", "柔光不多肢", "soft-light no extra limbs", "多肢、禁、柔光", "extra, ban, soft", "柔光下的不要多手臂腿", "under soft light, no extra arms or legs", "soft-lit, no extra limbs"],
    ["no_extra_limb_epic", "史詩不多肢", "epic no extra limbs", "多肢、禁、史詩", "extra, ban, epic", "史詩尺度的不要多手臂腿", "at epic scale, no extra arms or legs", "epic, no extra limbs"],
    ["hands_visible_court", "宮廷手要完整", "court complete hands", "手、指、宮廷", "hand, finger, courtly", "宮廷氣場下的手指數正確", "in a courtly register, correct finger count", "courtly, complete hands, correct fingers"],
    ["hands_visible_street", "街頭手要完整", "street complete hands", "手、指、街頭", "hand, finger, street", "街頭質感的手指數正確", "with street grit, correct finger count", "street-cast, complete hands, correct fingers"],
    ["hands_visible_noir", "暗黑手要完整", "noir complete hands", "手、指、暗黑", "hand, finger, noir", "暗調電影感的手指數正確", "in noir lighting, correct finger count", "noir, complete hands, correct fingers"],
    ["hands_visible_soft", "柔光手要完整", "soft-light complete hands", "手、指、柔光", "hand, finger, soft", "柔光下的手指數正確", "under soft light, correct finger count", "soft-lit, complete hands, correct fingers"],
    ["hands_visible_epic", "史詩手要完整", "epic complete hands", "手、指、史詩", "hand, finger, epic", "史詩尺度的手指數正確", "at epic scale, correct finger count", "epic, complete hands, correct fingers"],
    ["no_crop_head_court", "宮廷不切頭", "court no cropped head", "切頭、禁、宮廷", "crop head, ban, courtly", "宮廷氣場下的頭要完整", "in a courtly register, head fully in frame when intended", "courtly, do not crop off the head"],
    ["no_crop_head_street", "街頭不切頭", "street no cropped head", "切頭、禁、街頭", "crop head, ban, street", "街頭質感的頭要完整", "with street grit, head fully in frame when intended", "street-cast, do not crop off the head"],
    ["no_crop_head_noir", "暗黑不切頭", "noir no cropped head", "切頭、禁、暗黑", "crop head, ban, noir", "暗調電影感的頭要完整", "in noir lighting, head fully in frame when intended", "noir, do not crop off the head"],
    ["no_crop_head_soft", "柔光不切頭", "soft-light no cropped head", "切頭、禁、柔光", "crop head, ban, soft", "柔光下的頭要完整", "under soft light, head fully in frame when intended", "soft-lit, do not crop off the head"],
    ["no_crop_head_epic", "史詩不切頭", "epic no cropped head", "切頭、禁、史詩", "crop head, ban, epic", "史詩尺度的頭要完整", "at epic scale, head fully in frame when intended", "epic, do not crop off the head"],
    ["body_type_court", "宮廷體型不變", "court body type lock", "型、鎖、宮廷", "type, lock, courtly", "宮廷氣場下的胖瘦肌骨不變", "in a courtly register, same body type", "courtly, keep the same body type"],
    ["body_type_street", "街頭體型不變", "street body type lock", "型、鎖、街頭", "type, lock, street", "街頭質感的胖瘦肌骨不變", "with street grit, same body type", "street-cast, keep the same body type"],
    ["body_type_noir", "暗黑體型不變", "noir body type lock", "型、鎖、暗黑", "type, lock, noir", "暗調電影感的胖瘦肌骨不變", "in noir lighting, same body type", "noir, keep the same body type"],
    ["body_type_soft", "柔光體型不變", "soft-light body type lock", "型、鎖、柔光", "type, lock, soft", "柔光下的胖瘦肌骨不變", "under soft light, same body type", "soft-lit, keep the same body type"],
    ["body_type_epic", "史詩體型不變", "epic body type lock", "型、鎖、史詩", "type, lock, epic", "史詩尺度的胖瘦肌骨不變", "at epic scale, same body type", "epic, keep the same body type"],
    ["no_float_court", "宮廷腳要落地", "court feet grounded", "地、腳、宮廷", "ground, feet, courtly", "宮廷氣場下的除非動作需要否則落地", "in a courtly register, feet grounded unless the action needs otherwise", "courtly, keep feet grounded"],
    ["no_float_street", "街頭腳要落地", "street feet grounded", "地、腳、街頭", "ground, feet, street", "街頭質感的除非動作需要否則落地", "with street grit, feet grounded unless the action needs otherwise", "street-cast, keep feet grounded"],
    ["no_float_noir", "暗黑腳要落地", "noir feet grounded", "地、腳、暗黑", "ground, feet, noir", "暗調電影感的除非動作需要否則落地", "in noir lighting, feet grounded unless the action needs otherwise", "noir, keep feet grounded"],
    ["no_float_soft", "柔光腳要落地", "soft-light feet grounded", "地、腳、柔光", "ground, feet, soft", "柔光下的除非動作需要否則落地", "under soft light, feet grounded unless the action needs otherwise", "soft-lit, keep feet grounded"],
    ["no_float_epic", "史詩腳要落地", "epic feet grounded", "地、腳、史詩", "ground, feet, epic", "史詩尺度的除非動作需要否則落地", "at epic scale, feet grounded unless the action needs otherwise", "epic, keep feet grounded"],
    ["skin_tone_court", "宮廷膚色不變", "court skin tone lock", "膚、鎖、宮廷", "skin, lock, courtly", "宮廷氣場下的膚色鎖定", "in a courtly register, lock skin tone", "courtly, keep the same skin tone"],
    ["skin_tone_street", "街頭膚色不變", "street skin tone lock", "膚、鎖、街頭", "skin, lock, street", "街頭質感的膚色鎖定", "with street grit, lock skin tone", "street-cast, keep the same skin tone"],
    ["skin_tone_noir", "暗黑膚色不變", "noir skin tone lock", "膚、鎖、暗黑", "skin, lock, noir", "暗調電影感的膚色鎖定", "in noir lighting, lock skin tone", "noir, keep the same skin tone"],
    ["skin_tone_soft", "柔光膚色不變", "soft-light skin tone lock", "膚、鎖、柔光", "skin, lock, soft", "柔光下的膚色鎖定", "under soft light, lock skin tone", "soft-lit, keep the same skin tone"],
    ["skin_tone_epic", "史詩膚色不變", "epic skin tone lock", "膚、鎖、史詩", "skin, lock, epic", "史詩尺度的膚色鎖定", "at epic scale, lock skin tone", "epic, keep the same skin tone"],
    ["no_wings_court", "宮廷不長翼", "court no unasked wings", "翼、禁、宮廷", "wing, ban, courtly", "宮廷氣場下的沒寫就不要翼", "in a courtly register, no wings unless specified", "courtly, no unasked wings or extra appendages"],
    ["no_wings_street", "街頭不長翼", "street no unasked wings", "翼、禁、街頭", "wing, ban, street", "街頭質感的沒寫就不要翼", "with street grit, no wings unless specified", "street-cast, no unasked wings or extra appendages"],
    ["no_wings_noir", "暗黑不長翼", "noir no unasked wings", "翼、禁、暗黑", "wing, ban, noir", "暗調電影感的沒寫就不要翼", "in noir lighting, no wings unless specified", "noir, no unasked wings or extra appendages"],
    ["no_wings_soft", "柔光不長翼", "soft-light no unasked wings", "翼、禁、柔光", "wing, ban, soft", "柔光下的沒寫就不要翼", "under soft light, no wings unless specified", "soft-lit, no unasked wings or extra appendages"],
    ["no_wings_epic", "史詩不長翼", "epic no unasked wings", "翼、禁、史詩", "wing, ban, epic", "史詩尺度的沒寫就不要翼", "at epic scale, no wings unless specified", "epic, no unasked wings or extra appendages"],
    ["costume_body_fit_court", "宮廷衣服合身不融肉", "court cloth not fused", "融、禁、宮廷", "fuse, ban, courtly", "宮廷氣場下的布與肉分開", "in a courtly register, cloth separate from flesh", "courtly, do not fuse clothing into the body"],
    ["costume_body_fit_street", "街頭衣服合身不融肉", "street cloth not fused", "融、禁、街頭", "fuse, ban, street", "街頭質感的布與肉分開", "with street grit, cloth separate from flesh", "street-cast, do not fuse clothing into the body"],
    ["costume_body_fit_noir", "暗黑衣服合身不融肉", "noir cloth not fused", "融、禁、暗黑", "fuse, ban, noir", "暗調電影感的布與肉分開", "in noir lighting, cloth separate from flesh", "noir, do not fuse clothing into the body"],
    ["costume_body_fit_soft", "柔光衣服合身不融肉", "soft-light cloth not fused", "融、禁、柔光", "fuse, ban, soft", "柔光下的布與肉分開", "under soft light, cloth separate from flesh", "soft-lit, do not fuse clothing into the body"],
    ["costume_body_fit_epic", "史詩衣服合身不融肉", "epic cloth not fused", "融、禁、史詩", "fuse, ban, epic", "史詩尺度的布與肉分開", "at epic scale, cloth separate from flesh", "epic, do not fuse clothing into the body"]
  ],
    costumeLock: [
    ["same_outfit_court", "宮廷同一套", "court same outfit", "套、同、宮廷", "outfit, same, courtly", "宮廷氣場下的整段同一套服裝", "in a courtly register, same outfit throughout", "courtly, keep the same outfit"],
    ["same_outfit_street", "街頭同一套", "street same outfit", "套、同、街頭", "outfit, same, street", "街頭質感的整段同一套服裝", "with street grit, same outfit throughout", "street-cast, keep the same outfit"],
    ["same_outfit_noir", "暗黑同一套", "noir same outfit", "套、同、暗黑", "outfit, same, noir", "暗調電影感的整段同一套服裝", "in noir lighting, same outfit throughout", "noir, keep the same outfit"],
    ["same_outfit_soft", "柔光同一套", "soft-light same outfit", "套、同、柔光", "outfit, same, soft", "柔光下的整段同一套服裝", "under soft light, same outfit throughout", "soft-lit, keep the same outfit"],
    ["same_outfit_epic", "史詩同一套", "epic same outfit", "套、同、史詩", "outfit, same, epic", "史詩尺度的整段同一套服裝", "at epic scale, same outfit throughout", "epic, keep the same outfit"],
    ["no_random_hat_court", "宮廷不亂加帽", "court no random hat", "帽、禁、宮廷", "hat, ban, courtly", "宮廷氣場下的不要亂加帽", "in a courtly register, do not add a random hat", "courtly, no unasked hat"],
    ["no_random_hat_street", "街頭不亂加帽", "street no random hat", "帽、禁、街頭", "hat, ban, street", "街頭質感的不要亂加帽", "with street grit, do not add a random hat", "street-cast, no unasked hat"],
    ["no_random_hat_noir", "暗黑不亂加帽", "noir no random hat", "帽、禁、暗黑", "hat, ban, noir", "暗調電影感的不要亂加帽", "in noir lighting, do not add a random hat", "noir, no unasked hat"],
    ["no_random_hat_soft", "柔光不亂加帽", "soft-light no random hat", "帽、禁、柔光", "hat, ban, soft", "柔光下的不要亂加帽", "under soft light, do not add a random hat", "soft-lit, no unasked hat"],
    ["no_random_hat_epic", "史詩不亂加帽", "epic no random hat", "帽、禁、史詩", "hat, ban, epic", "史詩尺度的不要亂加帽", "at epic scale, do not add a random hat", "epic, no unasked hat"],
    ["keep_color_court", "宮廷服裝色不變", "court wardrobe colors lock", "色、鎖、宮廷", "color, lock, courtly", "宮廷氣場下的服裝色盤鎖定", "in a courtly register, lock wardrobe colors", "courtly, keep wardrobe colors"],
    ["keep_color_street", "街頭服裝色不變", "street wardrobe colors lock", "色、鎖、街頭", "color, lock, street", "街頭質感的服裝色盤鎖定", "with street grit, lock wardrobe colors", "street-cast, keep wardrobe colors"],
    ["keep_color_noir", "暗黑服裝色不變", "noir wardrobe colors lock", "色、鎖、暗黑", "color, lock, noir", "暗調電影感的服裝色盤鎖定", "in noir lighting, lock wardrobe colors", "noir, keep wardrobe colors"],
    ["keep_color_soft", "柔光服裝色不變", "soft-light wardrobe colors lock", "色、鎖、柔光", "color, lock, soft", "柔光下的服裝色盤鎖定", "under soft light, lock wardrobe colors", "soft-lit, keep wardrobe colors"],
    ["keep_color_epic", "史詩服裝色不變", "epic wardrobe colors lock", "色、鎖、史詩", "color, lock, epic", "史詩尺度的服裝色盤鎖定", "at epic scale, lock wardrobe colors", "epic, keep wardrobe colors"],
    ["no_logo_court", "宮廷無品牌 logo", "court no brand logos", "logo、禁、宮廷", "logo, ban, courtly", "宮廷氣場下的不要品牌標", "in a courtly register, no brand logos", "courtly, no brand logos on clothes"],
    ["no_logo_street", "街頭無品牌 logo", "street no brand logos", "logo、禁、街頭", "logo, ban, street", "街頭質感的不要品牌標", "with street grit, no brand logos", "street-cast, no brand logos on clothes"],
    ["no_logo_noir", "暗黑無品牌 logo", "noir no brand logos", "logo、禁、暗黑", "logo, ban, noir", "暗調電影感的不要品牌標", "in noir lighting, no brand logos", "noir, no brand logos on clothes"],
    ["no_logo_soft", "柔光無品牌 logo", "soft-light no brand logos", "logo、禁、柔光", "logo, ban, soft", "柔光下的不要品牌標", "under soft light, no brand logos", "soft-lit, no brand logos on clothes"],
    ["no_logo_epic", "史詩無品牌 logo", "epic no brand logos", "logo、禁、史詩", "logo, ban, epic", "史詩尺度的不要品牌標", "at epic scale, no brand logos", "epic, no brand logos on clothes"],
    ["keep_weapon_court", "宮廷道具在身上", "court keep worn props", "道、留、宮廷", "prop, keep, courtly", "宮廷氣場下的已有的佩戴留下", "in a courtly register, keep already worn props", "courtly, keep worn props and weapons"],
    ["keep_weapon_street", "街頭道具在身上", "street keep worn props", "道、留、街頭", "prop, keep, street", "街頭質感的已有的佩戴留下", "with street grit, keep already worn props", "street-cast, keep worn props and weapons"],
    ["keep_weapon_noir", "暗黑道具在身上", "noir keep worn props", "道、留、暗黑", "prop, keep, noir", "暗調電影感的已有的佩戴留下", "in noir lighting, keep already worn props", "noir, keep worn props and weapons"],
    ["keep_weapon_soft", "柔光道具在身上", "soft-light keep worn props", "道、留、柔光", "prop, keep, soft", "柔光下的已有的佩戴留下", "under soft light, keep already worn props", "soft-lit, keep worn props and weapons"],
    ["keep_weapon_epic", "史詩道具在身上", "epic keep worn props", "道、留、史詩", "prop, keep, epic", "史詩尺度的已有的佩戴留下", "at epic scale, keep already worn props", "epic, keep worn props and weapons"],
    ["no_nude_court", "宮廷不無故裸", "court no unasked nude", "裸、禁、宮廷", "nude, ban, courtly", "宮廷氣場下的不要無故裸", "in a courtly register, no unasked nudity", "courtly, no unasked nudity"],
    ["no_nude_street", "街頭不無故裸", "street no unasked nude", "裸、禁、街頭", "nude, ban, street", "街頭質感的不要無故裸", "with street grit, no unasked nudity", "street-cast, no unasked nudity"],
    ["no_nude_noir", "暗黑不無故裸", "noir no unasked nude", "裸、禁、暗黑", "nude, ban, noir", "暗調電影感的不要無故裸", "in noir lighting, no unasked nudity", "noir, no unasked nudity"],
    ["no_nude_soft", "柔光不無故裸", "soft-light no unasked nude", "裸、禁、柔光", "nude, ban, soft", "柔光下的不要無故裸", "under soft light, no unasked nudity", "soft-lit, no unasked nudity"],
    ["no_nude_epic", "史詩不無故裸", "epic no unasked nude", "裸、禁、史詩", "nude, ban, epic", "史詩尺度的不要無故裸", "at epic scale, no unasked nudity", "epic, no unasked nudity"],
    ["layer_count_court", "宮廷層數不變", "court layer count lock", "層、鎖、宮廷", "layer, lock, courtly", "宮廷氣場下的穿幾層就幾層", "in a courtly register, keep the same layer count", "courtly, keep the same clothing layers"],
    ["layer_count_street", "街頭層數不變", "street layer count lock", "層、鎖、街頭", "layer, lock, street", "街頭質感的穿幾層就幾層", "with street grit, keep the same layer count", "street-cast, keep the same clothing layers"],
    ["layer_count_noir", "暗黑層數不變", "noir layer count lock", "層、鎖、暗黑", "layer, lock, noir", "暗調電影感的穿幾層就幾層", "in noir lighting, keep the same layer count", "noir, keep the same clothing layers"],
    ["layer_count_soft", "柔光層數不變", "soft-light layer count lock", "層、鎖、柔光", "layer, lock, soft", "柔光下的穿幾層就幾層", "under soft light, keep the same layer count", "soft-lit, keep the same clothing layers"],
    ["layer_count_epic", "史詩層數不變", "epic layer count lock", "層、鎖、史詩", "layer, lock, epic", "史詩尺度的穿幾層就幾層", "at epic scale, keep the same layer count", "epic, keep the same clothing layers"],
    ["no_modern_mix_court", "宮廷不亂混現代", "court no random modern mix", "混、禁、宮廷", "mix, ban, courtly", "宮廷氣場下的不要亂加現代單品", "in a courtly register, no random modern pieces", "courtly, do not mix in random modern clothes"],
    ["no_modern_mix_street", "街頭不亂混現代", "street no random modern mix", "混、禁、街頭", "mix, ban, street", "街頭質感的不要亂加現代單品", "with street grit, no random modern pieces", "street-cast, do not mix in random modern clothes"],
    ["no_modern_mix_noir", "暗黑不亂混現代", "noir no random modern mix", "混、禁、暗黑", "mix, ban, noir", "暗調電影感的不要亂加現代單品", "in noir lighting, no random modern pieces", "noir, do not mix in random modern clothes"],
    ["no_modern_mix_soft", "柔光不亂混現代", "soft-light no random modern mix", "混、禁、柔光", "mix, ban, soft", "柔光下的不要亂加現代單品", "under soft light, no random modern pieces", "soft-lit, do not mix in random modern clothes"],
    ["no_modern_mix_epic", "史詩不亂混現代", "epic no random modern mix", "混、禁、史詩", "mix, ban, epic", "史詩尺度的不要亂加現代單品", "at epic scale, no random modern pieces", "epic, do not mix in random modern clothes"],
    ["keep_shoes_court", "宮廷鞋留下", "court keep shoes", "鞋、留、宮廷", "shoe, keep, courtly", "宮廷氣場下的不要無故赤足除非寫了", "in a courtly register, keep shoes unless specified barefoot", "courtly, keep the same footwear"],
    ["keep_shoes_street", "街頭鞋留下", "street keep shoes", "鞋、留、街頭", "shoe, keep, street", "街頭質感的不要無故赤足除非寫了", "with street grit, keep shoes unless specified barefoot", "street-cast, keep the same footwear"],
    ["keep_shoes_noir", "暗黑鞋留下", "noir keep shoes", "鞋、留、暗黑", "shoe, keep, noir", "暗調電影感的不要無故赤足除非寫了", "in noir lighting, keep shoes unless specified barefoot", "noir, keep the same footwear"],
    ["keep_shoes_soft", "柔光鞋留下", "soft-light keep shoes", "鞋、留、柔光", "shoe, keep, soft", "柔光下的不要無故赤足除非寫了", "under soft light, keep shoes unless specified barefoot", "soft-lit, keep the same footwear"],
    ["keep_shoes_epic", "史詩鞋留下", "epic keep shoes", "鞋、留、史詩", "shoe, keep, epic", "史詩尺度的不要無故赤足除非寫了", "at epic scale, keep shoes unless specified barefoot", "epic, keep the same footwear"],
    ["damage_lock_court", "宮廷破損程度不變", "court damage lock", "破、鎖、宮廷", "damage, lock, courtly", "宮廷氣場下的衣服破到哪就停哪", "in a courtly register, clothing damage stays as specified", "courtly, do not change costume damage"],
    ["damage_lock_street", "街頭破損程度不變", "street damage lock", "破、鎖、街頭", "damage, lock, street", "街頭質感的衣服破到哪就停哪", "with street grit, clothing damage stays as specified", "street-cast, do not change costume damage"],
    ["damage_lock_noir", "暗黑破損程度不變", "noir damage lock", "破、鎖、暗黑", "damage, lock, noir", "暗調電影感的衣服破到哪就停哪", "in noir lighting, clothing damage stays as specified", "noir, do not change costume damage"],
    ["damage_lock_soft", "柔光破損程度不變", "soft-light damage lock", "破、鎖、柔光", "damage, lock, soft", "柔光下的衣服破到哪就停哪", "under soft light, clothing damage stays as specified", "soft-lit, do not change costume damage"],
    ["damage_lock_epic", "史詩破損程度不變", "epic damage lock", "破、鎖、史詩", "damage, lock, epic", "史詩尺度的衣服破到哪就停哪", "at epic scale, clothing damage stays as specified", "epic, do not change costume damage"]
  ],
    anatomyBan: [
    ["no_extra_finger_court", "宮廷不多指", "court no extra fingers", "指、多、宮廷", "finger, extra, courtly", "宮廷氣場下的不要第六指", "in a courtly register, no sixth finger", "courtly, no extra fingers"],
    ["no_extra_finger_street", "街頭不多指", "street no extra fingers", "指、多、街頭", "finger, extra, street", "街頭質感的不要第六指", "with street grit, no sixth finger", "street-cast, no extra fingers"],
    ["no_extra_finger_noir", "暗黑不多指", "noir no extra fingers", "指、多、暗黑", "finger, extra, noir", "暗調電影感的不要第六指", "in noir lighting, no sixth finger", "noir, no extra fingers"],
    ["no_extra_finger_soft", "柔光不多指", "soft-light no extra fingers", "指、多、柔光", "finger, extra, soft", "柔光下的不要第六指", "under soft light, no sixth finger", "soft-lit, no extra fingers"],
    ["no_extra_finger_epic", "史詩不多指", "epic no extra fingers", "指、多、史詩", "finger, extra, epic", "史詩尺度的不要第六指", "at epic scale, no sixth finger", "epic, no extra fingers"],
    ["no_melt_court", "宮廷不融體", "court no melting anatomy", "融、體、宮廷", "melt, body, courtly", "宮廷氣場下的肢體不要融化", "in a courtly register, no melting limbs", "courtly, no melting anatomy"],
    ["no_melt_street", "街頭不融體", "street no melting anatomy", "融、體、街頭", "melt, body, street", "街頭質感的肢體不要融化", "with street grit, no melting limbs", "street-cast, no melting anatomy"],
    ["no_melt_noir", "暗黑不融體", "noir no melting anatomy", "融、體、暗黑", "melt, body, noir", "暗調電影感的肢體不要融化", "in noir lighting, no melting limbs", "noir, no melting anatomy"],
    ["no_melt_soft", "柔光不融體", "soft-light no melting anatomy", "融、體、柔光", "melt, body, soft", "柔光下的肢體不要融化", "under soft light, no melting limbs", "soft-lit, no melting anatomy"],
    ["no_melt_epic", "史詩不融體", "epic no melting anatomy", "融、體、史詩", "melt, body, epic", "史詩尺度的肢體不要融化", "at epic scale, no melting limbs", "epic, no melting anatomy"],
    ["no_asym_face_bug_court", "宮廷五官不錯位", "court no misplaced features", "錯位、禁、宮廷", "misplace, ban, courtly", "宮廷氣場下的眼耳口位置正確", "in a courtly register, eyes ears mouth placed correctly", "courtly, no misplaced facial features"],
    ["no_asym_face_bug_street", "街頭五官不錯位", "street no misplaced features", "錯位、禁、街頭", "misplace, ban, street", "街頭質感的眼耳口位置正確", "with street grit, eyes ears mouth placed correctly", "street-cast, no misplaced facial features"],
    ["no_asym_face_bug_noir", "暗黑五官不錯位", "noir no misplaced features", "錯位、禁、暗黑", "misplace, ban, noir", "暗調電影感的眼耳口位置正確", "in noir lighting, eyes ears mouth placed correctly", "noir, no misplaced facial features"],
    ["no_asym_face_bug_soft", "柔光五官不錯位", "soft-light no misplaced features", "錯位、禁、柔光", "misplace, ban, soft", "柔光下的眼耳口位置正確", "under soft light, eyes ears mouth placed correctly", "soft-lit, no misplaced facial features"],
    ["no_asym_face_bug_epic", "史詩五官不錯位", "epic no misplaced features", "錯位、禁、史詩", "misplace, ban, epic", "史詩尺度的眼耳口位置正確", "at epic scale, eyes ears mouth placed correctly", "epic, no misplaced facial features"],
    ["no_joint_break_court", "宮廷關節方向對", "court joints bend right", "關、向、宮廷", "joint, way, courtly", "宮廷氣場下的關節不要反折除非動作需要", "in a courtly register, joints bend the right way", "courtly, no broken joint directions"],
    ["no_joint_break_street", "街頭關節方向對", "street joints bend right", "關、向、街頭", "joint, way, street", "街頭質感的關節不要反折除非動作需要", "with street grit, joints bend the right way", "street-cast, no broken joint directions"],
    ["no_joint_break_noir", "暗黑關節方向對", "noir joints bend right", "關、向、暗黑", "joint, way, noir", "暗調電影感的關節不要反折除非動作需要", "in noir lighting, joints bend the right way", "noir, no broken joint directions"],
    ["no_joint_break_soft", "柔光關節方向對", "soft-light joints bend right", "關、向、柔光", "joint, way, soft", "柔光下的關節不要反折除非動作需要", "under soft light, joints bend the right way", "soft-lit, no broken joint directions"],
    ["no_joint_break_epic", "史詩關節方向對", "epic joints bend right", "關、向、史詩", "joint, way, epic", "史詩尺度的關節不要反折除非動作需要", "at epic scale, joints bend the right way", "epic, no broken joint directions"],
    ["no_double_pupil_court", "宮廷不多瞳", "court no extra pupils", "瞳、多、宮廷", "pupil, extra, courtly", "宮廷氣場下的每眼一瞳", "in a courtly register, one pupil per eye", "courtly, no extra pupils"],
    ["no_double_pupil_street", "街頭不多瞳", "street no extra pupils", "瞳、多、街頭", "pupil, extra, street", "街頭質感的每眼一瞳", "with street grit, one pupil per eye", "street-cast, no extra pupils"],
    ["no_double_pupil_noir", "暗黑不多瞳", "noir no extra pupils", "瞳、多、暗黑", "pupil, extra, noir", "暗調電影感的每眼一瞳", "in noir lighting, one pupil per eye", "noir, no extra pupils"],
    ["no_double_pupil_soft", "柔光不多瞳", "soft-light no extra pupils", "瞳、多、柔光", "pupil, extra, soft", "柔光下的每眼一瞳", "under soft light, one pupil per eye", "soft-lit, no extra pupils"],
    ["no_double_pupil_epic", "史詩不多瞳", "epic no extra pupils", "瞳、多、史詩", "pupil, extra, epic", "史詩尺度的每眼一瞳", "at epic scale, one pupil per eye", "epic, no extra pupils"],
    ["no_teeth_mess_court", "宮廷牙列正常", "court normal teeth", "牙、亂、宮廷", "teeth, mess, courtly", "宮廷氣場下的不要滿嘴錯牙除非角色如此", "in a courtly register, normal teeth unless the character is written that way", "courtly, no messy extra teeth"],
    ["no_teeth_mess_street", "街頭牙列正常", "street normal teeth", "牙、亂、街頭", "teeth, mess, street", "街頭質感的不要滿嘴錯牙除非角色如此", "with street grit, normal teeth unless the character is written that way", "street-cast, no messy extra teeth"],
    ["no_teeth_mess_noir", "暗黑牙列正常", "noir normal teeth", "牙、亂、暗黑", "teeth, mess, noir", "暗調電影感的不要滿嘴錯牙除非角色如此", "in noir lighting, normal teeth unless the character is written that way", "noir, no messy extra teeth"],
    ["no_teeth_mess_soft", "柔光牙列正常", "soft-light normal teeth", "牙、亂、柔光", "teeth, mess, soft", "柔光下的不要滿嘴錯牙除非角色如此", "under soft light, normal teeth unless the character is written that way", "soft-lit, no messy extra teeth"],
    ["no_teeth_mess_epic", "史詩牙列正常", "epic normal teeth", "牙、亂、史詩", "teeth, mess, epic", "史詩尺度的不要滿嘴錯牙除非角色如此", "at epic scale, normal teeth unless the character is written that way", "epic, no messy extra teeth"],
    ["no_long_neck_court", "宮廷頸長正常", "court normal neck length", "頸、長、宮廷", "neck, long, courtly", "宮廷氣場下的不要無故長頸", "in a courtly register, no unasked long neck", "courtly, no unnaturally long neck"],
    ["no_long_neck_street", "街頭頸長正常", "street normal neck length", "頸、長、街頭", "neck, long, street", "街頭質感的不要無故長頸", "with street grit, no unasked long neck", "street-cast, no unnaturally long neck"],
    ["no_long_neck_noir", "暗黑頸長正常", "noir normal neck length", "頸、長、暗黑", "neck, long, noir", "暗調電影感的不要無故長頸", "in noir lighting, no unasked long neck", "noir, no unnaturally long neck"],
    ["no_long_neck_soft", "柔光頸長正常", "soft-light normal neck length", "頸、長、柔光", "neck, long, soft", "柔光下的不要無故長頸", "under soft light, no unasked long neck", "soft-lit, no unnaturally long neck"],
    ["no_long_neck_epic", "史詩頸長正常", "epic normal neck length", "頸、長、史詩", "neck, long, epic", "史詩尺度的不要無故長頸", "at epic scale, no unasked long neck", "epic, no unnaturally long neck"],
    ["no_tiny_hand_court", "宮廷手腳比例對", "court hand-foot proportion", "比、手、宮廷", "prop, hand, courtly", "宮廷氣場下的手腳不要過小過大", "in a courtly register, hands and feet in proportion", "courtly, no tiny or giant hands"],
    ["no_tiny_hand_street", "街頭手腳比例對", "street hand-foot proportion", "比、手、街頭", "prop, hand, street", "街頭質感的手腳不要過小過大", "with street grit, hands and feet in proportion", "street-cast, no tiny or giant hands"],
    ["no_tiny_hand_noir", "暗黑手腳比例對", "noir hand-foot proportion", "比、手、暗黑", "prop, hand, noir", "暗調電影感的手腳不要過小過大", "in noir lighting, hands and feet in proportion", "noir, no tiny or giant hands"],
    ["no_tiny_hand_soft", "柔光手腳比例對", "soft-light hand-foot proportion", "比、手、柔光", "prop, hand, soft", "柔光下的手腳不要過小過大", "under soft light, hands and feet in proportion", "soft-lit, no tiny or giant hands"],
    ["no_tiny_hand_epic", "史詩手腳比例對", "epic hand-foot proportion", "比、手、史詩", "prop, hand, epic", "史詩尺度的手腳不要過小過大", "at epic scale, hands and feet in proportion", "epic, no tiny or giant hands"],
    ["no_extra_joint_court", "宮廷不多關節", "court no extra joints", "關、多、宮廷", "joint, extra, courtly", "宮廷氣場下的不要多一截肢", "in a courtly register, no extra limb segments", "courtly, no extra joints"],
    ["no_extra_joint_street", "街頭不多關節", "street no extra joints", "關、多、街頭", "joint, extra, street", "街頭質感的不要多一截肢", "with street grit, no extra limb segments", "street-cast, no extra joints"],
    ["no_extra_joint_noir", "暗黑不多關節", "noir no extra joints", "關、多、暗黑", "joint, extra, noir", "暗調電影感的不要多一截肢", "in noir lighting, no extra limb segments", "noir, no extra joints"],
    ["no_extra_joint_soft", "柔光不多關節", "soft-light no extra joints", "關、多、柔光", "joint, extra, soft", "柔光下的不要多一截肢", "under soft light, no extra limb segments", "soft-lit, no extra joints"],
    ["no_extra_joint_epic", "史詩不多關節", "epic no extra joints", "關、多、史詩", "joint, extra, epic", "史詩尺度的不要多一截肢", "at epic scale, no extra limb segments", "epic, no extra joints"],
    ["no_gore_unasked_court", "宮廷不無故血腥解剖", "court no unasked gore", "血、禁、宮廷", "gore, ban, courtly", "宮廷氣場下的不要無故開膛", "in a courtly register, no unasked gore or opened bodies", "courtly, no unasked gore"],
    ["no_gore_unasked_street", "街頭不無故血腥解剖", "street no unasked gore", "血、禁、街頭", "gore, ban, street", "街頭質感的不要無故開膛", "with street grit, no unasked gore or opened bodies", "street-cast, no unasked gore"],
    ["no_gore_unasked_noir", "暗黑不無故血腥解剖", "noir no unasked gore", "血、禁、暗黑", "gore, ban, noir", "暗調電影感的不要無故開膛", "in noir lighting, no unasked gore or opened bodies", "noir, no unasked gore"],
    ["no_gore_unasked_soft", "柔光不無故血腥解剖", "soft-light no unasked gore", "血、禁、柔光", "gore, ban, soft", "柔光下的不要無故開膛", "under soft light, no unasked gore or opened bodies", "soft-lit, no unasked gore"],
    ["no_gore_unasked_epic", "史詩不無故血腥解剖", "epic no unasked gore", "血、禁、史詩", "gore, ban, epic", "史詩尺度的不要無故開膛", "at epic scale, no unasked gore or opened bodies", "epic, no unasked gore"]
  ],
    textStyleBan: [
    ["no_watermark_court", "宮廷無浮水印", "court no watermark", "印、禁、宮廷", "watermark, ban, courtly", "宮廷氣場下的不要浮水印", "in a courtly register, no watermark", "courtly, no watermarks"],
    ["no_watermark_street", "街頭無浮水印", "street no watermark", "印、禁、街頭", "watermark, ban, street", "街頭質感的不要浮水印", "with street grit, no watermark", "street-cast, no watermarks"],
    ["no_watermark_noir", "暗黑無浮水印", "noir no watermark", "印、禁、暗黑", "watermark, ban, noir", "暗調電影感的不要浮水印", "in noir lighting, no watermark", "noir, no watermarks"],
    ["no_watermark_soft", "柔光無浮水印", "soft-light no watermark", "印、禁、柔光", "watermark, ban, soft", "柔光下的不要浮水印", "under soft light, no watermark", "soft-lit, no watermarks"],
    ["no_watermark_epic", "史詩無浮水印", "epic no watermark", "印、禁、史詩", "watermark, ban, epic", "史詩尺度的不要浮水印", "at epic scale, no watermark", "epic, no watermarks"],
    ["no_subtitles_court", "宮廷無字幕", "court no subtitles", "字幕、禁、宮廷", "sub, ban, courtly", "宮廷氣場下的畫面不要字幕", "in a courtly register, no burned-in subtitles", "courtly, no subtitles on the image"],
    ["no_subtitles_street", "街頭無字幕", "street no subtitles", "字幕、禁、街頭", "sub, ban, street", "街頭質感的畫面不要字幕", "with street grit, no burned-in subtitles", "street-cast, no subtitles on the image"],
    ["no_subtitles_noir", "暗黑無字幕", "noir no subtitles", "字幕、禁、暗黑", "sub, ban, noir", "暗調電影感的畫面不要字幕", "in noir lighting, no burned-in subtitles", "noir, no subtitles on the image"],
    ["no_subtitles_soft", "柔光無字幕", "soft-light no subtitles", "字幕、禁、柔光", "sub, ban, soft", "柔光下的畫面不要字幕", "under soft light, no burned-in subtitles", "soft-lit, no subtitles on the image"],
    ["no_subtitles_epic", "史詩無字幕", "epic no subtitles", "字幕、禁、史詩", "sub, ban, epic", "史詩尺度的畫面不要字幕", "at epic scale, no burned-in subtitles", "epic, no subtitles on the image"],
    ["no_logo_court", "宮廷無平台 logo", "court no platform logo", "logo、禁、宮廷", "logo, ban, courtly", "宮廷氣場下的不要平台標", "in a courtly register, no platform logos", "courtly, no platform logos"],
    ["no_logo_street", "街頭無平台 logo", "street no platform logo", "logo、禁、街頭", "logo, ban, street", "街頭質感的不要平台標", "with street grit, no platform logos", "street-cast, no platform logos"],
    ["no_logo_noir", "暗黑無平台 logo", "noir no platform logo", "logo、禁、暗黑", "logo, ban, noir", "暗調電影感的不要平台標", "in noir lighting, no platform logos", "noir, no platform logos"],
    ["no_logo_soft", "柔光無平台 logo", "soft-light no platform logo", "logo、禁、柔光", "logo, ban, soft", "柔光下的不要平台標", "under soft light, no platform logos", "soft-lit, no platform logos"],
    ["no_logo_epic", "史詩無平台 logo", "epic no platform logo", "logo、禁、史詩", "logo, ban, epic", "史詩尺度的不要平台標", "at epic scale, no platform logos", "epic, no platform logos"],
    ["no_ui_court", "宮廷無 UI 框", "court no UI chrome", "UI、禁、宮廷", "ui, ban, courtly", "宮廷氣場下的不要手機 UI", "in a courtly register, no phone or app UI", "courtly, no UI chrome"],
    ["no_ui_street", "街頭無 UI 框", "street no UI chrome", "UI、禁、街頭", "ui, ban, street", "街頭質感的不要手機 UI", "with street grit, no phone or app UI", "street-cast, no UI chrome"],
    ["no_ui_noir", "暗黑無 UI 框", "noir no UI chrome", "UI、禁、暗黑", "ui, ban, noir", "暗調電影感的不要手機 UI", "in noir lighting, no phone or app UI", "noir, no UI chrome"],
    ["no_ui_soft", "柔光無 UI 框", "soft-light no UI chrome", "UI、禁、柔光", "ui, ban, soft", "柔光下的不要手機 UI", "under soft light, no phone or app UI", "soft-lit, no UI chrome"],
    ["no_ui_epic", "史詩無 UI 框", "epic no UI chrome", "UI、禁、史詩", "ui, ban, epic", "史詩尺度的不要手機 UI", "at epic scale, no phone or app UI", "epic, no UI chrome"],
    ["no_artist_sign_court", "宮廷無簽名", "court no artist signature", "簽、禁、宮廷", "sign, ban, courtly", "宮廷氣場下的不要畫家簽名", "in a courtly register, no artist signature", "courtly, no artist signatures"],
    ["no_artist_sign_street", "街頭無簽名", "street no artist signature", "簽、禁、街頭", "sign, ban, street", "街頭質感的不要畫家簽名", "with street grit, no artist signature", "street-cast, no artist signatures"],
    ["no_artist_sign_noir", "暗黑無簽名", "noir no artist signature", "簽、禁、暗黑", "sign, ban, noir", "暗調電影感的不要畫家簽名", "in noir lighting, no artist signature", "noir, no artist signatures"],
    ["no_artist_sign_soft", "柔光無簽名", "soft-light no artist signature", "簽、禁、柔光", "sign, ban, soft", "柔光下的不要畫家簽名", "under soft light, no artist signature", "soft-lit, no artist signatures"],
    ["no_artist_sign_epic", "史詩無簽名", "epic no artist signature", "簽、禁、史詩", "sign, ban, epic", "史詩尺度的不要畫家簽名", "at epic scale, no artist signature", "epic, no artist signatures"],
    ["no_text_random_court", "宮廷無亂字", "court no random text", "亂字、禁、宮廷", "text, random, courtly", "宮廷氣場下的不要亂碼字", "in a courtly register, no random glyphs", "courtly, no random text"],
    ["no_text_random_street", "街頭無亂字", "street no random text", "亂字、禁、街頭", "text, random, street", "街頭質感的不要亂碼字", "with street grit, no random glyphs", "street-cast, no random text"],
    ["no_text_random_noir", "暗黑無亂字", "noir no random text", "亂字、禁、暗黑", "text, random, noir", "暗調電影感的不要亂碼字", "in noir lighting, no random glyphs", "noir, no random text"],
    ["no_text_random_soft", "柔光無亂字", "soft-light no random text", "亂字、禁、柔光", "text, random, soft", "柔光下的不要亂碼字", "under soft light, no random glyphs", "soft-lit, no random text"],
    ["no_text_random_epic", "史詩無亂字", "epic no random text", "亂字、禁、史詩", "text, random, epic", "史詩尺度的不要亂碼字", "at epic scale, no random glyphs", "epic, no random text"],
    ["no_style_shift_court", "宮廷不跳畫風", "court no style jump", "風、跳、宮廷", "style, jump, courtly", "宮廷氣場下的中途不要換畫風", "in a courtly register, do not jump art style mid-sequence", "courtly, no sudden style shift"],
    ["no_style_shift_street", "街頭不跳畫風", "street no style jump", "風、跳、街頭", "style, jump, street", "街頭質感的中途不要換畫風", "with street grit, do not jump art style mid-sequence", "street-cast, no sudden style shift"],
    ["no_style_shift_noir", "暗黑不跳畫風", "noir no style jump", "風、跳、暗黑", "style, jump, noir", "暗調電影感的中途不要換畫風", "in noir lighting, do not jump art style mid-sequence", "noir, no sudden style shift"],
    ["no_style_shift_soft", "柔光不跳畫風", "soft-light no style jump", "風、跳、柔光", "style, jump, soft", "柔光下的中途不要換畫風", "under soft light, do not jump art style mid-sequence", "soft-lit, no sudden style shift"],
    ["no_style_shift_epic", "史詩不跳畫風", "epic no style jump", "風、跳、史詩", "style, jump, epic", "史詩尺度的中途不要換畫風", "at epic scale, do not jump art style mid-sequence", "epic, no sudden style shift"],
    ["no_3d_mix_court", "宮廷不混無求 3D", "court no unasked 3D mix", "3D、混、宮廷", "3d, mix, courtly", "宮廷氣場下的不要突然 3D 渲染感除非設定", "in a courtly register, no sudden unasked 3D render look", "courtly, no unasked 3D mix"],
    ["no_3d_mix_street", "街頭不混無求 3D", "street no unasked 3D mix", "3D、混、街頭", "3d, mix, street", "街頭質感的不要突然 3D 渲染感除非設定", "with street grit, no sudden unasked 3D render look", "street-cast, no unasked 3D mix"],
    ["no_3d_mix_noir", "暗黑不混無求 3D", "noir no unasked 3D mix", "3D、混、暗黑", "3d, mix, noir", "暗調電影感的不要突然 3D 渲染感除非設定", "in noir lighting, no sudden unasked 3D render look", "noir, no unasked 3D mix"],
    ["no_3d_mix_soft", "柔光不混無求 3D", "soft-light no unasked 3D mix", "3D、混、柔光", "3d, mix, soft", "柔光下的不要突然 3D 渲染感除非設定", "under soft light, no sudden unasked 3D render look", "soft-lit, no unasked 3D mix"],
    ["no_3d_mix_epic", "史詩不混無求 3D", "epic no unasked 3D mix", "3D、混、史詩", "3d, mix, epic", "史詩尺度的不要突然 3D 渲染感除非設定", "at epic scale, no sudden unasked 3D render look", "epic, no unasked 3D mix"],
    ["no_stock_court", "宮廷不像圖庫", "court no stock look", "庫、假、宮廷", "stock, fake, courtly", "宮廷氣場下的不要圖庫微笑空景", "in a courtly register, no stock-photo emptiness", "courtly, no stock-photo look"],
    ["no_stock_street", "街頭不像圖庫", "street no stock look", "庫、假、街頭", "stock, fake, street", "街頭質感的不要圖庫微笑空景", "with street grit, no stock-photo emptiness", "street-cast, no stock-photo look"],
    ["no_stock_noir", "暗黑不像圖庫", "noir no stock look", "庫、假、暗黑", "stock, fake, noir", "暗調電影感的不要圖庫微笑空景", "in noir lighting, no stock-photo emptiness", "noir, no stock-photo look"],
    ["no_stock_soft", "柔光不像圖庫", "soft-light no stock look", "庫、假、柔光", "stock, fake, soft", "柔光下的不要圖庫微笑空景", "under soft light, no stock-photo emptiness", "soft-lit, no stock-photo look"],
    ["no_stock_epic", "史詩不像圖庫", "epic no stock look", "庫、假、史詩", "stock, fake, epic", "史詩尺度的不要圖庫微笑空景", "at epic scale, no stock-photo emptiness", "epic, no stock-photo look"],
    ["no_filter_name_court", "宮廷無濾鏡名", "court no filter labels", "濾、名、宮廷", "filter, label, courtly", "宮廷氣場下的不要寫著濾鏡名", "in a courtly register, no filter-name labels", "courtly, no filter labels"],
    ["no_filter_name_street", "街頭無濾鏡名", "street no filter labels", "濾、名、街頭", "filter, label, street", "街頭質感的不要寫著濾鏡名", "with street grit, no filter-name labels", "street-cast, no filter labels"],
    ["no_filter_name_noir", "暗黑無濾鏡名", "noir no filter labels", "濾、名、暗黑", "filter, label, noir", "暗調電影感的不要寫著濾鏡名", "in noir lighting, no filter-name labels", "noir, no filter labels"],
    ["no_filter_name_soft", "柔光無濾鏡名", "soft-light no filter labels", "濾、名、柔光", "filter, label, soft", "柔光下的不要寫著濾鏡名", "under soft light, no filter-name labels", "soft-lit, no filter labels"],
    ["no_filter_name_epic", "史詩無濾鏡名", "epic no filter labels", "濾、名、史詩", "filter, label, epic", "史詩尺度的不要寫著濾鏡名", "at epic scale, no filter-name labels", "epic, no filter labels"]
  ],
    continuity: [
    ["same_wardrobe_shot_court", "宮廷鏡間服裝同", "court wardrobe continuity", "裝、連、宮廷", "wardrobe, cont, courtly", "宮廷氣場下的相鄰鏡服裝同一套", "in a courtly register, same wardrobe across adjacent shots", "courtly, keep wardrobe continuity"],
    ["same_wardrobe_shot_street", "街頭鏡間服裝同", "street wardrobe continuity", "裝、連、街頭", "wardrobe, cont, street", "街頭質感的相鄰鏡服裝同一套", "with street grit, same wardrobe across adjacent shots", "street-cast, keep wardrobe continuity"],
    ["same_wardrobe_shot_noir", "暗黑鏡間服裝同", "noir wardrobe continuity", "裝、連、暗黑", "wardrobe, cont, noir", "暗調電影感的相鄰鏡服裝同一套", "in noir lighting, same wardrobe across adjacent shots", "noir, keep wardrobe continuity"],
    ["same_wardrobe_shot_soft", "柔光鏡間服裝同", "soft-light wardrobe continuity", "裝、連、柔光", "wardrobe, cont, soft", "柔光下的相鄰鏡服裝同一套", "under soft light, same wardrobe across adjacent shots", "soft-lit, keep wardrobe continuity"],
    ["same_wardrobe_shot_epic", "史詩鏡間服裝同", "epic wardrobe continuity", "裝、連、史詩", "wardrobe, cont, epic", "史詩尺度的相鄰鏡服裝同一套", "at epic scale, same wardrobe across adjacent shots", "epic, keep wardrobe continuity"],
    ["time_of_day_court", "宮廷時段不變", "court time-of-day lock", "時、鎖、宮廷", "tod, lock, courtly", "宮廷氣場下的除非轉場否則同一時段", "in a courtly register, same time of day unless a transition", "courtly, lock time of day"],
    ["time_of_day_street", "街頭時段不變", "street time-of-day lock", "時、鎖、街頭", "tod, lock, street", "街頭質感的除非轉場否則同一時段", "with street grit, same time of day unless a transition", "street-cast, lock time of day"],
    ["time_of_day_noir", "暗黑時段不變", "noir time-of-day lock", "時、鎖、暗黑", "tod, lock, noir", "暗調電影感的除非轉場否則同一時段", "in noir lighting, same time of day unless a transition", "noir, lock time of day"],
    ["time_of_day_soft", "柔光時段不變", "soft-light time-of-day lock", "時、鎖、柔光", "tod, lock, soft", "柔光下的除非轉場否則同一時段", "under soft light, same time of day unless a transition", "soft-lit, lock time of day"],
    ["time_of_day_epic", "史詩時段不變", "epic time-of-day lock", "時、鎖、史詩", "tod, lock, epic", "史詩尺度的除非轉場否則同一時段", "at epic scale, same time of day unless a transition", "epic, lock time of day"],
    ["weather_court", "宮廷天氣不變", "court weather lock", "天、鎖、宮廷", "weather, lock, courtly", "宮廷氣場下的不要無故轉晴雨", "in a courtly register, do not flip weather unasked", "courtly, keep weather continuity"],
    ["weather_street", "街頭天氣不變", "street weather lock", "天、鎖、街頭", "weather, lock, street", "街頭質感的不要無故轉晴雨", "with street grit, do not flip weather unasked", "street-cast, keep weather continuity"],
    ["weather_noir", "暗黑天氣不變", "noir weather lock", "天、鎖、暗黑", "weather, lock, noir", "暗調電影感的不要無故轉晴雨", "in noir lighting, do not flip weather unasked", "noir, keep weather continuity"],
    ["weather_soft", "柔光天氣不變", "soft-light weather lock", "天、鎖、柔光", "weather, lock, soft", "柔光下的不要無故轉晴雨", "under soft light, do not flip weather unasked", "soft-lit, keep weather continuity"],
    ["weather_epic", "史詩天氣不變", "epic weather lock", "天、鎖、史詩", "weather, lock, epic", "史詩尺度的不要無故轉晴雨", "at epic scale, do not flip weather unasked", "epic, keep weather continuity"],
    ["wound_court", "宮廷傷勢連續", "court wound continuity", "傷、連、宮廷", "wound, cont, courtly", "宮廷氣場下的傷不要無故痊癒或加深", "in a courtly register, wounds do not heal or worsen unasked", "courtly, keep wound continuity"],
    ["wound_street", "街頭傷勢連續", "street wound continuity", "傷、連、街頭", "wound, cont, street", "街頭質感的傷不要無故痊癒或加深", "with street grit, wounds do not heal or worsen unasked", "street-cast, keep wound continuity"],
    ["wound_noir", "暗黑傷勢連續", "noir wound continuity", "傷、連、暗黑", "wound, cont, noir", "暗調電影感的傷不要無故痊癒或加深", "in noir lighting, wounds do not heal or worsen unasked", "noir, keep wound continuity"],
    ["wound_soft", "柔光傷勢連續", "soft-light wound continuity", "傷、連、柔光", "wound, cont, soft", "柔光下的傷不要無故痊癒或加深", "under soft light, wounds do not heal or worsen unasked", "soft-lit, keep wound continuity"],
    ["wound_epic", "史詩傷勢連續", "epic wound continuity", "傷、連、史詩", "wound, cont, epic", "史詩尺度的傷不要無故痊癒或加深", "at epic scale, wounds do not heal or worsen unasked", "epic, keep wound continuity"],
    ["prop_hand_court", "宮廷道具在哪手", "court prop-hand lock", "手、道、宮廷", "hand, prop, courtly", "宮廷氣場下的道具在哪手就留哪手", "in a courtly register, prop stays in the same hand", "courtly, keep prop-hand continuity"],
    ["prop_hand_street", "街頭道具在哪手", "street prop-hand lock", "手、道、街頭", "hand, prop, street", "街頭質感的道具在哪手就留哪手", "with street grit, prop stays in the same hand", "street-cast, keep prop-hand continuity"],
    ["prop_hand_noir", "暗黑道具在哪手", "noir prop-hand lock", "手、道、暗黑", "hand, prop, noir", "暗調電影感的道具在哪手就留哪手", "in noir lighting, prop stays in the same hand", "noir, keep prop-hand continuity"],
    ["prop_hand_soft", "柔光道具在哪手", "soft-light prop-hand lock", "手、道、柔光", "hand, prop, soft", "柔光下的道具在哪手就留哪手", "under soft light, prop stays in the same hand", "soft-lit, keep prop-hand continuity"],
    ["prop_hand_epic", "史詩道具在哪手", "epic prop-hand lock", "手、道、史詩", "hand, prop, epic", "史詩尺度的道具在哪手就留哪手", "at epic scale, prop stays in the same hand", "epic, keep prop-hand continuity"],
    ["hair_court", "宮廷髮型連續", "court hair continuity", "髮、連、宮廷", "hair, cont, courtly", "宮廷氣場下的髮不要無故改長改色", "in a courtly register, hair does not change length or color unasked", "courtly, keep hair continuity"],
    ["hair_street", "街頭髮型連續", "street hair continuity", "髮、連、街頭", "hair, cont, street", "街頭質感的髮不要無故改長改色", "with street grit, hair does not change length or color unasked", "street-cast, keep hair continuity"],
    ["hair_noir", "暗黑髮型連續", "noir hair continuity", "髮、連、暗黑", "hair, cont, noir", "暗調電影感的髮不要無故改長改色", "in noir lighting, hair does not change length or color unasked", "noir, keep hair continuity"],
    ["hair_soft", "柔光髮型連續", "soft-light hair continuity", "髮、連、柔光", "hair, cont, soft", "柔光下的髮不要無故改長改色", "under soft light, hair does not change length or color unasked", "soft-lit, keep hair continuity"],
    ["hair_epic", "史詩髮型連續", "epic hair continuity", "髮、連、史詩", "hair, cont, epic", "史詩尺度的髮不要無故改長改色", "at epic scale, hair does not change length or color unasked", "epic, keep hair continuity"],
    ["set_court", "宮廷場景連續", "court set continuity", "場、連、宮廷", "set, cont, courtly", "宮廷氣場下的同一場的牆與窗留下", "in a courtly register, same walls and windows in the scene", "courtly, keep set continuity"],
    ["set_street", "街頭場景連續", "street set continuity", "場、連、街頭", "set, cont, street", "街頭質感的同一場的牆與窗留下", "with street grit, same walls and windows in the scene", "street-cast, keep set continuity"],
    ["set_noir", "暗黑場景連續", "noir set continuity", "場、連、暗黑", "set, cont, noir", "暗調電影感的同一場的牆與窗留下", "in noir lighting, same walls and windows in the scene", "noir, keep set continuity"],
    ["set_soft", "柔光場景連續", "soft-light set continuity", "場、連、柔光", "set, cont, soft", "柔光下的同一場的牆與窗留下", "under soft light, same walls and windows in the scene", "soft-lit, keep set continuity"],
    ["set_epic", "史詩場景連續", "epic set continuity", "場、連、史詩", "set, cont, epic", "史詩尺度的同一場的牆與窗留下", "at epic scale, same walls and windows in the scene", "epic, keep set continuity"],
    ["light_dir_court", "宮廷光向連續", "court light direction lock", "光、向、宮廷", "light, dir, courtly", "宮廷氣場下的主光方向不要跳", "in a courtly register, key light direction does not jump", "courtly, keep light-direction continuity"],
    ["light_dir_street", "街頭光向連續", "street light direction lock", "光、向、街頭", "light, dir, street", "街頭質感的主光方向不要跳", "with street grit, key light direction does not jump", "street-cast, keep light-direction continuity"],
    ["light_dir_noir", "暗黑光向連續", "noir light direction lock", "光、向、暗黑", "light, dir, noir", "暗調電影感的主光方向不要跳", "in noir lighting, key light direction does not jump", "noir, keep light-direction continuity"],
    ["light_dir_soft", "柔光光向連續", "soft-light light direction lock", "光、向、柔光", "light, dir, soft", "柔光下的主光方向不要跳", "under soft light, key light direction does not jump", "soft-lit, keep light-direction continuity"],
    ["light_dir_epic", "史詩光向連續", "epic light direction lock", "光、向、史詩", "light, dir, epic", "史詩尺度的主光方向不要跳", "at epic scale, key light direction does not jump", "epic, keep light-direction continuity"],
    ["cast_count_court", "宮廷人數連續", "court cast-count lock", "人、數、宮廷", "cast, count, courtly", "宮廷氣場下的不要無故加减人", "in a courtly register, do not add or drop people unasked", "courtly, keep cast-count continuity"],
    ["cast_count_street", "街頭人數連續", "street cast-count lock", "人、數、街頭", "cast, count, street", "街頭質感的不要無故加减人", "with street grit, do not add or drop people unasked", "street-cast, keep cast-count continuity"],
    ["cast_count_noir", "暗黑人數連續", "noir cast-count lock", "人、數、暗黑", "cast, count, noir", "暗調電影感的不要無故加减人", "in noir lighting, do not add or drop people unasked", "noir, keep cast-count continuity"],
    ["cast_count_soft", "柔光人數連續", "soft-light cast-count lock", "人、數、柔光", "cast, count, soft", "柔光下的不要無故加减人", "under soft light, do not add or drop people unasked", "soft-lit, keep cast-count continuity"],
    ["cast_count_epic", "史詩人數連續", "epic cast-count lock", "人、數、史詩", "cast, count, epic", "史詩尺度的不要無故加减人", "at epic scale, do not add or drop people unasked", "epic, keep cast-count continuity"],
    ["screen_dir_court", "宮廷視線方向", "court eyeline lock", "視、向、宮廷", "eye, line, courtly", "宮廷氣場下的對視方向不要跳軸除非切", "in a courtly register, eyelines stay consistent unless a cut is intended", "courtly, keep eyeline continuity"],
    ["screen_dir_street", "街頭視線方向", "street eyeline lock", "視、向、街頭", "eye, line, street", "街頭質感的對視方向不要跳軸除非切", "with street grit, eyelines stay consistent unless a cut is intended", "street-cast, keep eyeline continuity"],
    ["screen_dir_noir", "暗黑視線方向", "noir eyeline lock", "視、向、暗黑", "eye, line, noir", "暗調電影感的對視方向不要跳軸除非切", "in noir lighting, eyelines stay consistent unless a cut is intended", "noir, keep eyeline continuity"],
    ["screen_dir_soft", "柔光視線方向", "soft-light eyeline lock", "視、向、柔光", "eye, line, soft", "柔光下的對視方向不要跳軸除非切", "under soft light, eyelines stay consistent unless a cut is intended", "soft-lit, keep eyeline continuity"],
    ["screen_dir_epic", "史詩視線方向", "epic eyeline lock", "視、向、史詩", "eye, line, epic", "史詩尺度的對視方向不要跳軸除非切", "at epic scale, eyelines stay consistent unless a cut is intended", "epic, keep eyeline continuity"]
  ]
  }
})
