/**
 * location field kit catalog (50+ templates per part).
 */
import { defineFieldKit } from '../fieldKit'

export const LOCATION_KIT = defineFieldKit({
  key: "locationKit",
  parts: ["architecture","scale","era","interior","landmark","vegetation"] as const,
  partLabels: {
    architecture: { zhHK: "建築", zhCN: "建筑", en: "Architecture" },
    scale: { zhHK: "尺度", zhCN: "尺度", en: "Scale" },
    era: { zhHK: "年代", zhCN: "年代", en: "Era" },
    interior: { zhHK: "室內感", zhCN: "室内感", en: "Interior" },
    landmark: { zhHK: "地標", zhCN: "地标", en: "Landmark" },
    vegetation: { zhHK: "植被", zhCN: "植被", en: "Vegetation" }
  },

  rows: {
    architecture: [
    ["siheyuan_court", "宮廷四合院", "court courtyard house", "合院、中、宮廷", "courtyard, chinese, courtly", "宮廷氣場下的圍合四合院", "in a courtly register, enclosed siheyuan", "courtly, siheyuan courtyard architecture"],
    ["siheyuan_street", "街頭四合院", "street courtyard house", "合院、中、街頭", "courtyard, chinese, street", "街頭質感的圍合四合院", "with street grit, enclosed siheyuan", "street-cast, siheyuan courtyard architecture"],
    ["siheyuan_noir", "暗黑四合院", "noir courtyard house", "合院、中、暗黑", "courtyard, chinese, noir", "暗調電影感的圍合四合院", "in noir lighting, enclosed siheyuan", "noir, siheyuan courtyard architecture"],
    ["siheyuan_soft", "柔光四合院", "soft-light courtyard house", "合院、中、柔光", "courtyard, chinese, soft", "柔光下的圍合四合院", "under soft light, enclosed siheyuan", "soft-lit, siheyuan courtyard architecture"],
    ["siheyuan_epic", "史詩四合院", "epic courtyard house", "合院、中、史詩", "courtyard, chinese, epic", "史詩尺度的圍合四合院", "at epic scale, enclosed siheyuan", "epic, siheyuan courtyard architecture"],
    ["tower_court", "宮廷高層玻璃", "court glass tower", "塔、現、宮廷", "tower, modern, courtly", "宮廷氣場下的玻璃高層", "in a courtly register, glass high-rise", "courtly, glass tower architecture"],
    ["tower_street", "街頭高層玻璃", "street glass tower", "塔、現、街頭", "tower, modern, street", "街頭質感的玻璃高層", "with street grit, glass high-rise", "street-cast, glass tower architecture"],
    ["tower_noir", "暗黑高層玻璃", "noir glass tower", "塔、現、暗黑", "tower, modern, noir", "暗調電影感的玻璃高層", "in noir lighting, glass high-rise", "noir, glass tower architecture"],
    ["tower_soft", "柔光高層玻璃", "soft-light glass tower", "塔、現、柔光", "tower, modern, soft", "柔光下的玻璃高層", "under soft light, glass high-rise", "soft-lit, glass tower architecture"],
    ["tower_epic", "史詩高層玻璃", "epic glass tower", "塔、現、史詩", "tower, modern, epic", "史詩尺度的玻璃高層", "at epic scale, glass high-rise", "epic, glass tower architecture"],
    ["hutong_court", "宮廷窄巷磚", "court brick alley", "巷、磚、宮廷", "alley, brick, courtly", "宮廷氣場下的磚牆窄巷", "in a courtly register, narrow brick hutong", "courtly, brick hutong architecture"],
    ["hutong_street", "街頭窄巷磚", "street brick alley", "巷、磚、街頭", "alley, brick, street", "街頭質感的磚牆窄巷", "with street grit, narrow brick hutong", "street-cast, brick hutong architecture"],
    ["hutong_noir", "暗黑窄巷磚", "noir brick alley", "巷、磚、暗黑", "alley, brick, noir", "暗調電影感的磚牆窄巷", "in noir lighting, narrow brick hutong", "noir, brick hutong architecture"],
    ["hutong_soft", "柔光窄巷磚", "soft-light brick alley", "巷、磚、柔光", "alley, brick, soft", "柔光下的磚牆窄巷", "under soft light, narrow brick hutong", "soft-lit, brick hutong architecture"],
    ["hutong_epic", "史詩窄巷磚", "epic brick alley", "巷、磚、史詩", "alley, brick, epic", "史詩尺度的磚牆窄巷", "at epic scale, narrow brick hutong", "epic, brick hutong architecture"],
    ["temple_court", "宮廷飛簷廟", "court upturned eaves temple", "廟、簷、宮廷", "temple, eaves, courtly", "宮廷氣場下的飛簷寺廟", "in a courtly register, temple with flying eaves", "courtly, temple architecture"],
    ["temple_street", "街頭飛簷廟", "street upturned eaves temple", "廟、簷、街頭", "temple, eaves, street", "街頭質感的飛簷寺廟", "with street grit, temple with flying eaves", "street-cast, temple architecture"],
    ["temple_noir", "暗黑飛簷廟", "noir upturned eaves temple", "廟、簷、暗黑", "temple, eaves, noir", "暗調電影感的飛簷寺廟", "in noir lighting, temple with flying eaves", "noir, temple architecture"],
    ["temple_soft", "柔光飛簷廟", "soft-light upturned eaves temple", "廟、簷、柔光", "temple, eaves, soft", "柔光下的飛簷寺廟", "under soft light, temple with flying eaves", "soft-lit, temple architecture"],
    ["temple_epic", "史詩飛簷廟", "epic upturned eaves temple", "廟、簷、史詩", "temple, eaves, epic", "史詩尺度的飛簷寺廟", "at epic scale, temple with flying eaves", "epic, temple architecture"],
    ["warehouse_court", "宮廷舊倉", "court warehouse", "倉、工業、宮廷", "warehouse, industrial, courtly", "宮廷氣場下的高敞舊倉", "in a courtly register, high old warehouse", "courtly, warehouse architecture"],
    ["warehouse_street", "街頭舊倉", "street warehouse", "倉、工業、街頭", "warehouse, industrial, street", "街頭質感的高敞舊倉", "with street grit, high old warehouse", "street-cast, warehouse architecture"],
    ["warehouse_noir", "暗黑舊倉", "noir warehouse", "倉、工業、暗黑", "warehouse, industrial, noir", "暗調電影感的高敞舊倉", "in noir lighting, high old warehouse", "noir, warehouse architecture"],
    ["warehouse_soft", "柔光舊倉", "soft-light warehouse", "倉、工業、柔光", "warehouse, industrial, soft", "柔光下的高敞舊倉", "under soft light, high old warehouse", "soft-lit, warehouse architecture"],
    ["warehouse_epic", "史詩舊倉", "epic warehouse", "倉、工業、史詩", "warehouse, industrial, epic", "史詩尺度的高敞舊倉", "at epic scale, high old warehouse", "epic, warehouse architecture"],
    ["villa_court", "宮廷獨棟別墅", "court villa", "墅、私、宮廷", "villa, private, courtly", "宮廷氣場下的獨棟宅", "in a courtly register, detached villa", "courtly, villa architecture"],
    ["villa_street", "街頭獨棟別墅", "street villa", "墅、私、街頭", "villa, private, street", "街頭質感的獨棟宅", "with street grit, detached villa", "street-cast, villa architecture"],
    ["villa_noir", "暗黑獨棟別墅", "noir villa", "墅、私、暗黑", "villa, private, noir", "暗調電影感的獨棟宅", "in noir lighting, detached villa", "noir, villa architecture"],
    ["villa_soft", "柔光獨棟別墅", "soft-light villa", "墅、私、柔光", "villa, private, soft", "柔光下的獨棟宅", "under soft light, detached villa", "soft-lit, villa architecture"],
    ["villa_epic", "史詩獨棟別墅", "epic villa", "墅、私、史詩", "villa, private, epic", "史詩尺度的獨棟宅", "at epic scale, detached villa", "epic, villa architecture"],
    ["ruin_court", "宮廷殘垣", "court ruins", "殘、舊、宮廷", "ruin, broken, courtly", "宮廷氣場下的半塌殘垣", "in a courtly register, half-collapsed ruins", "courtly, ruined architecture"],
    ["ruin_street", "街頭殘垣", "street ruins", "殘、舊、街頭", "ruin, broken, street", "街頭質感的半塌殘垣", "with street grit, half-collapsed ruins", "street-cast, ruined architecture"],
    ["ruin_noir", "暗黑殘垣", "noir ruins", "殘、舊、暗黑", "ruin, broken, noir", "暗調電影感的半塌殘垣", "in noir lighting, half-collapsed ruins", "noir, ruined architecture"],
    ["ruin_soft", "柔光殘垣", "soft-light ruins", "殘、舊、柔光", "ruin, broken, soft", "柔光下的半塌殘垣", "under soft light, half-collapsed ruins", "soft-lit, ruined architecture"],
    ["ruin_epic", "史詩殘垣", "epic ruins", "殘、舊、史詩", "ruin, broken, epic", "史詩尺度的半塌殘垣", "at epic scale, half-collapsed ruins", "epic, ruined architecture"],
    ["palace_court", "宮廷宮殿廊", "court palace colonnade", "宮、廊、宮廷", "palace, colonnade, courtly", "宮廷氣場下的長廊宮殿", "in a courtly register, palace colonnades", "courtly, palace architecture"],
    ["palace_street", "街頭宮殿廊", "street palace colonnade", "宮、廊、街頭", "palace, colonnade, street", "街頭質感的長廊宮殿", "with street grit, palace colonnades", "street-cast, palace architecture"],
    ["palace_noir", "暗黑宮殿廊", "noir palace colonnade", "宮、廊、暗黑", "palace, colonnade, noir", "暗調電影感的長廊宮殿", "in noir lighting, palace colonnades", "noir, palace architecture"],
    ["palace_soft", "柔光宮殿廊", "soft-light palace colonnade", "宮、廊、柔光", "palace, colonnade, soft", "柔光下的長廊宮殿", "under soft light, palace colonnades", "soft-lit, palace architecture"],
    ["palace_epic", "史詩宮殿廊", "epic palace colonnade", "宮、廊、史詩", "palace, colonnade, epic", "史詩尺度的長廊宮殿", "at epic scale, palace colonnades", "epic, palace architecture"],
    ["station_court", "宮廷車站大廳", "court station hall", "站、穹、宮廷", "station, vault, courtly", "宮廷氣場下的高天花車站", "in a courtly register, vaulted station hall", "courtly, station-hall architecture"],
    ["station_street", "街頭車站大廳", "street station hall", "站、穹、街頭", "station, vault, street", "街頭質感的高天花車站", "with street grit, vaulted station hall", "street-cast, station-hall architecture"],
    ["station_noir", "暗黑車站大廳", "noir station hall", "站、穹、暗黑", "station, vault, noir", "暗調電影感的高天花車站", "in noir lighting, vaulted station hall", "noir, station-hall architecture"],
    ["station_soft", "柔光車站大廳", "soft-light station hall", "站、穹、柔光", "station, vault, soft", "柔光下的高天花車站", "under soft light, vaulted station hall", "soft-lit, station-hall architecture"],
    ["station_epic", "史詩車站大廳", "epic station hall", "站、穹、史詩", "station, vault, epic", "史詩尺度的高天花車站", "at epic scale, vaulted station hall", "epic, station-hall architecture"],
    ["capsule_court", "宮廷艙體未來", "court capsule future", "艙、科、宮廷", "capsule, scifi, courtly", "宮廷氣場下的模組艙體", "in a courtly register, modular capsules", "courtly, capsule futurist architecture"],
    ["capsule_street", "街頭艙體未來", "street capsule future", "艙、科、街頭", "capsule, scifi, street", "街頭質感的模組艙體", "with street grit, modular capsules", "street-cast, capsule futurist architecture"],
    ["capsule_noir", "暗黑艙體未來", "noir capsule future", "艙、科、暗黑", "capsule, scifi, noir", "暗調電影感的模組艙體", "in noir lighting, modular capsules", "noir, capsule futurist architecture"],
    ["capsule_soft", "柔光艙體未來", "soft-light capsule future", "艙、科、柔光", "capsule, scifi, soft", "柔光下的模組艙體", "under soft light, modular capsules", "soft-lit, capsule futurist architecture"],
    ["capsule_epic", "史詩艙體未來", "epic capsule future", "艙、科、史詩", "capsule, scifi, epic", "史詩尺度的模組艙體", "at epic scale, modular capsules", "epic, capsule futurist architecture"]
  ],
    scale: [
    ["intimate_court", "宮廷貼身小", "court intimate small", "小、近、宮廷", "small, close, courtly", "宮廷氣場下的空間很近", "in a courtly register, very close scale", "courtly, intimate small scale"],
    ["intimate_street", "街頭貼身小", "street intimate small", "小、近、街頭", "small, close, street", "街頭質感的空間很近", "with street grit, very close scale", "street-cast, intimate small scale"],
    ["intimate_noir", "暗黑貼身小", "noir intimate small", "小、近、暗黑", "small, close, noir", "暗調電影感的空間很近", "in noir lighting, very close scale", "noir, intimate small scale"],
    ["intimate_soft", "柔光貼身小", "soft-light intimate small", "小、近、柔光", "small, close, soft", "柔光下的空間很近", "under soft light, very close scale", "soft-lit, intimate small scale"],
    ["intimate_epic", "史詩貼身小", "epic intimate small", "小、近、史詩", "small, close, epic", "史詩尺度的空間很近", "at epic scale, very close scale", "epic, intimate small scale"],
    ["room_court", "宮廷單房", "court single room", "房、人、宮廷", "room, human, courtly", "宮廷氣場下的一間房尺度", "in a courtly register, one-room human scale", "courtly, single-room scale"],
    ["room_street", "街頭單房", "street single room", "房、人、街頭", "room, human, street", "街頭質感的一間房尺度", "with street grit, one-room human scale", "street-cast, single-room scale"],
    ["room_noir", "暗黑單房", "noir single room", "房、人、暗黑", "room, human, noir", "暗調電影感的一間房尺度", "in noir lighting, one-room human scale", "noir, single-room scale"],
    ["room_soft", "柔光單房", "soft-light single room", "房、人、柔光", "room, human, soft", "柔光下的一間房尺度", "under soft light, one-room human scale", "soft-lit, single-room scale"],
    ["room_epic", "史詩單房", "epic single room", "房、人、史詩", "room, human, epic", "史詩尺度的一間房尺度", "at epic scale, one-room human scale", "epic, single-room scale"],
    ["hall_court", "宮廷大廳", "court great hall", "廳、回、宮廷", "hall, echo, courtly", "宮廷氣場下的可回聲大廳", "in a courtly register, echoing hall", "courtly, great-hall scale"],
    ["hall_street", "街頭大廳", "street great hall", "廳、回、街頭", "hall, echo, street", "街頭質感的可回聲大廳", "with street grit, echoing hall", "street-cast, great-hall scale"],
    ["hall_noir", "暗黑大廳", "noir great hall", "廳、回、暗黑", "hall, echo, noir", "暗調電影感的可回聲大廳", "in noir lighting, echoing hall", "noir, great-hall scale"],
    ["hall_soft", "柔光大廳", "soft-light great hall", "廳、回、柔光", "hall, echo, soft", "柔光下的可回聲大廳", "under soft light, echoing hall", "soft-lit, great-hall scale"],
    ["hall_epic", "史詩大廳", "epic great hall", "廳、回、史詩", "hall, echo, epic", "史詩尺度的可回聲大廳", "at epic scale, echoing hall", "epic, great-hall scale"],
    ["street_court", "宮廷整條街", "court full street", "街、長、宮廷", "street, long, courtly", "宮廷氣場下的一條街長", "in a courtly register, full street length", "courtly, street-length scale"],
    ["street_street", "街頭整條街", "street full street", "街、長、街頭", "street, long, street", "街頭質感的一條街長", "with street grit, full street length", "street-cast, street-length scale"],
    ["street_noir", "暗黑整條街", "noir full street", "街、長、暗黑", "street, long, noir", "暗調電影感的一條街長", "in noir lighting, full street length", "noir, street-length scale"],
    ["street_soft", "柔光整條街", "soft-light full street", "街、長、柔光", "street, long, soft", "柔光下的一條街長", "under soft light, full street length", "soft-lit, street-length scale"],
    ["street_epic", "史詩整條街", "epic full street", "街、長、史詩", "street, long, epic", "史詩尺度的一條街長", "at epic scale, full street length", "epic, street-length scale"],
    ["plaza_court", "宮廷廣場", "court plaza", "廣場、空、宮廷", "plaza, open, courtly", "宮廷氣場下的開敞廣場", "in a courtly register, open plaza", "courtly, plaza scale"],
    ["plaza_street", "街頭廣場", "street plaza", "廣場、空、街頭", "plaza, open, street", "街頭質感的開敞廣場", "with street grit, open plaza", "street-cast, plaza scale"],
    ["plaza_noir", "暗黑廣場", "noir plaza", "廣場、空、暗黑", "plaza, open, noir", "暗調電影感的開敞廣場", "in noir lighting, open plaza", "noir, plaza scale"],
    ["plaza_soft", "柔光廣場", "soft-light plaza", "廣場、空、柔光", "plaza, open, soft", "柔光下的開敞廣場", "under soft light, open plaza", "soft-lit, plaza scale"],
    ["plaza_epic", "史詩廣場", "epic plaza", "廣場、空、史詩", "plaza, open, epic", "史詩尺度的開敞廣場", "at epic scale, open plaza", "epic, plaza scale"],
    ["campus_court", "宮廷園區", "court campus", "園、散、宮廷", "campus, spread, courtly", "宮廷氣場下的多棟園區", "in a courtly register, spread campus", "courtly, campus scale"],
    ["campus_street", "街頭園區", "street campus", "園、散、街頭", "campus, spread, street", "街頭質感的多棟園區", "with street grit, spread campus", "street-cast, campus scale"],
    ["campus_noir", "暗黑園區", "noir campus", "園、散、暗黑", "campus, spread, noir", "暗調電影感的多棟園區", "in noir lighting, spread campus", "noir, campus scale"],
    ["campus_soft", "柔光園區", "soft-light campus", "園、散、柔光", "campus, spread, soft", "柔光下的多棟園區", "under soft light, spread campus", "soft-lit, campus scale"],
    ["campus_epic", "史詩園區", "epic campus", "園、散、史詩", "campus, spread, epic", "史詩尺度的多棟園區", "at epic scale, spread campus", "epic, campus scale"],
    ["city_court", "宮廷城市遠", "court city-wide", "城、遠、宮廷", "city, far, courtly", "宮廷氣場下的可見城市天際", "in a courtly register, city skyline scale", "courtly, city-wide scale"],
    ["city_street", "街頭城市遠", "street city-wide", "城、遠、街頭", "city, far, street", "街頭質感的可見城市天際", "with street grit, city skyline scale", "street-cast, city-wide scale"],
    ["city_noir", "暗黑城市遠", "noir city-wide", "城、遠、暗黑", "city, far, noir", "暗調電影感的可見城市天際", "in noir lighting, city skyline scale", "noir, city-wide scale"],
    ["city_soft", "柔光城市遠", "soft-light city-wide", "城、遠、柔光", "city, far, soft", "柔光下的可見城市天際", "under soft light, city skyline scale", "soft-lit, city-wide scale"],
    ["city_epic", "史詩城市遠", "epic city-wide", "城、遠、史詩", "city, far, epic", "史詩尺度的可見城市天際", "at epic scale, city skyline scale", "epic, city-wide scale"],
    ["canyon_court", "宮廷峽谷巨", "court canyon-huge", "峽、巨、宮廷", "canyon, huge, courtly", "宮廷氣場下的垂直巨尺度", "in a courtly register, vertical canyon scale", "courtly, canyon-huge scale"],
    ["canyon_street", "街頭峽谷巨", "street canyon-huge", "峽、巨、街頭", "canyon, huge, street", "街頭質感的垂直巨尺度", "with street grit, vertical canyon scale", "street-cast, canyon-huge scale"],
    ["canyon_noir", "暗黑峽谷巨", "noir canyon-huge", "峽、巨、暗黑", "canyon, huge, noir", "暗調電影感的垂直巨尺度", "in noir lighting, vertical canyon scale", "noir, canyon-huge scale"],
    ["canyon_soft", "柔光峽谷巨", "soft-light canyon-huge", "峽、巨、柔光", "canyon, huge, soft", "柔光下的垂直巨尺度", "under soft light, vertical canyon scale", "soft-lit, canyon-huge scale"],
    ["canyon_epic", "史詩峽谷巨", "epic canyon-huge", "峽、巨、史詩", "canyon, huge, epic", "史詩尺度的垂直巨尺度", "at epic scale, vertical canyon scale", "epic, canyon-huge scale"],
    ["corridor_court", "宮廷長廊窄", "court long corridor", "廊、壓、宮廷", "corridor, press, courtly", "宮廷氣場下的窄而極長", "in a courtly register, narrow endless corridor", "courtly, corridor scale"],
    ["corridor_street", "街頭長廊窄", "street long corridor", "廊、壓、街頭", "corridor, press, street", "街頭質感的窄而極長", "with street grit, narrow endless corridor", "street-cast, corridor scale"],
    ["corridor_noir", "暗黑長廊窄", "noir long corridor", "廊、壓、暗黑", "corridor, press, noir", "暗調電影感的窄而極長", "in noir lighting, narrow endless corridor", "noir, corridor scale"],
    ["corridor_soft", "柔光長廊窄", "soft-light long corridor", "廊、壓、柔光", "corridor, press, soft", "柔光下的窄而極長", "under soft light, narrow endless corridor", "soft-lit, corridor scale"],
    ["corridor_epic", "史詩長廊窄", "epic long corridor", "廊、壓、史詩", "corridor, press, epic", "史詩尺度的窄而極長", "at epic scale, narrow endless corridor", "epic, corridor scale"],
    ["pocket_court", "宮廷口袋空間", "court pocket space", "袋、藏、宮廷", "pocket, hidden, courtly", "宮廷氣場下的藏起來的小", "in a courtly register, hidden pocket space", "courtly, pocket-space scale"],
    ["pocket_street", "街頭口袋空間", "street pocket space", "袋、藏、街頭", "pocket, hidden, street", "街頭質感的藏起來的小", "with street grit, hidden pocket space", "street-cast, pocket-space scale"],
    ["pocket_noir", "暗黑口袋空間", "noir pocket space", "袋、藏、暗黑", "pocket, hidden, noir", "暗調電影感的藏起來的小", "in noir lighting, hidden pocket space", "noir, pocket-space scale"],
    ["pocket_soft", "柔光口袋空間", "soft-light pocket space", "袋、藏、柔光", "pocket, hidden, soft", "柔光下的藏起來的小", "under soft light, hidden pocket space", "soft-lit, pocket-space scale"],
    ["pocket_epic", "史詩口袋空間", "epic pocket space", "袋、藏、史詩", "pocket, hidden, epic", "史詩尺度的藏起來的小", "at epic scale, hidden pocket space", "epic, pocket-space scale"]
  ],
    era: [
    ["ancient_court", "宮廷上古", "court ancient", "古、神話、宮廷", "ancient, myth, courtly", "宮廷氣場下的上古未名年代", "in a courtly register, unnamed ancient era", "courtly, ancient-era setting"],
    ["ancient_street", "街頭上古", "street ancient", "古、神話、街頭", "ancient, myth, street", "街頭質感的上古未名年代", "with street grit, unnamed ancient era", "street-cast, ancient-era setting"],
    ["ancient_noir", "暗黑上古", "noir ancient", "古、神話、暗黑", "ancient, myth, noir", "暗調電影感的上古未名年代", "in noir lighting, unnamed ancient era", "noir, ancient-era setting"],
    ["ancient_soft", "柔光上古", "soft-light ancient", "古、神話、柔光", "ancient, myth, soft", "柔光下的上古未名年代", "under soft light, unnamed ancient era", "soft-lit, ancient-era setting"],
    ["ancient_epic", "史詩上古", "epic ancient", "古、神話、史詩", "ancient, myth, epic", "史詩尺度的上古未名年代", "at epic scale, unnamed ancient era", "epic, ancient-era setting"],
    ["tang_court", "宮廷盛唐感", "court Tang-like", "唐、盛、宮廷", "tang, peak, courtly", "宮廷氣場下的盛唐氣象", "in a courtly register, high Tang atmosphere", "courtly, Tang-dynasty-like era"],
    ["tang_street", "街頭盛唐感", "street Tang-like", "唐、盛、街頭", "tang, peak, street", "街頭質感的盛唐氣象", "with street grit, high Tang atmosphere", "street-cast, Tang-dynasty-like era"],
    ["tang_noir", "暗黑盛唐感", "noir Tang-like", "唐、盛、暗黑", "tang, peak, noir", "暗調電影感的盛唐氣象", "in noir lighting, high Tang atmosphere", "noir, Tang-dynasty-like era"],
    ["tang_soft", "柔光盛唐感", "soft-light Tang-like", "唐、盛、柔光", "tang, peak, soft", "柔光下的盛唐氣象", "under soft light, high Tang atmosphere", "soft-lit, Tang-dynasty-like era"],
    ["tang_epic", "史詩盛唐感", "epic Tang-like", "唐、盛、史詩", "tang, peak, epic", "史詩尺度的盛唐氣象", "at epic scale, high Tang atmosphere", "epic, Tang-dynasty-like era"],
    ["qing_court", "宮廷晚清民初", "court late Qing", "清、末、宮廷", "qing, late, courtly", "宮廷氣場下的辮與洋樓縫", "in a courtly register, queue-and-treaty-port seam", "courtly, late-Qing era"],
    ["qing_street", "街頭晚清民初", "street late Qing", "清、末、街頭", "qing, late, street", "街頭質感的辮與洋樓縫", "with street grit, queue-and-treaty-port seam", "street-cast, late-Qing era"],
    ["qing_noir", "暗黑晚清民初", "noir late Qing", "清、末、暗黑", "qing, late, noir", "暗調電影感的辮與洋樓縫", "in noir lighting, queue-and-treaty-port seam", "noir, late-Qing era"],
    ["qing_soft", "柔光晚清民初", "soft-light late Qing", "清、末、柔光", "qing, late, soft", "柔光下的辮與洋樓縫", "under soft light, queue-and-treaty-port seam", "soft-lit, late-Qing era"],
    ["qing_epic", "史詩晚清民初", "epic late Qing", "清、末、史詩", "qing, late, epic", "史詩尺度的辮與洋樓縫", "at epic scale, queue-and-treaty-port seam", "epic, late-Qing era"],
    ["republic_court", "宮廷民國", "court Republican", "民國、旗袍、宮廷", "republic, qipao, courtly", "宮廷氣場下的民國街道", "in a courtly register, Republican streets", "courtly, Republican-era China"],
    ["republic_street", "街頭民國", "street Republican", "民國、旗袍、街頭", "republic, qipao, street", "街頭質感的民國街道", "with street grit, Republican streets", "street-cast, Republican-era China"],
    ["republic_noir", "暗黑民國", "noir Republican", "民國、旗袍、暗黑", "republic, qipao, noir", "暗調電影感的民國街道", "in noir lighting, Republican streets", "noir, Republican-era China"],
    ["republic_soft", "柔光民國", "soft-light Republican", "民國、旗袍、柔光", "republic, qipao, soft", "柔光下的民國街道", "under soft light, Republican streets", "soft-lit, Republican-era China"],
    ["republic_epic", "史詩民國", "epic Republican", "民國、旗袍、史詩", "republic, qipao, epic", "史詩尺度的民國街道", "at epic scale, Republican streets", "epic, Republican-era China"],
    ["80s_court", "宮廷八十年代", "court 1980s", "八十、舊彩、宮廷", "80s, faded, courtly", "宮廷氣場下的八十年代彩", "in a courtly register, 1980s faded color", "courtly, 1980s era"],
    ["80s_street", "街頭八十年代", "street 1980s", "八十、舊彩、街頭", "80s, faded, street", "街頭質感的八十年代彩", "with street grit, 1980s faded color", "street-cast, 1980s era"],
    ["80s_noir", "暗黑八十年代", "noir 1980s", "八十、舊彩、暗黑", "80s, faded, noir", "暗調電影感的八十年代彩", "in noir lighting, 1980s faded color", "noir, 1980s era"],
    ["80s_soft", "柔光八十年代", "soft-light 1980s", "八十、舊彩、柔光", "80s, faded, soft", "柔光下的八十年代彩", "under soft light, 1980s faded color", "soft-lit, 1980s era"],
    ["80s_epic", "史詩八十年代", "epic 1980s", "八十、舊彩、史詩", "80s, faded, epic", "史詩尺度的八十年代彩", "at epic scale, 1980s faded color", "epic, 1980s era"],
    ["now_court", "宮廷當代", "court contemporary", "當、現、宮廷", "now, current, courtly", "宮廷氣場下的當下都市", "in a courtly register, present-day city", "courtly, contemporary era"],
    ["now_street", "街頭當代", "street contemporary", "當、現、街頭", "now, current, street", "街頭質感的當下都市", "with street grit, present-day city", "street-cast, contemporary era"],
    ["now_noir", "暗黑當代", "noir contemporary", "當、現、暗黑", "now, current, noir", "暗調電影感的當下都市", "in noir lighting, present-day city", "noir, contemporary era"],
    ["now_soft", "柔光當代", "soft-light contemporary", "當、現、柔光", "now, current, soft", "柔光下的當下都市", "under soft light, present-day city", "soft-lit, contemporary era"],
    ["now_epic", "史詩當代", "epic contemporary", "當、現、史詩", "now, current, epic", "史詩尺度的當下都市", "at epic scale, present-day city", "epic, contemporary era"],
    ["near_future_court", "宮廷近未來", "court near future", "近未、科、宮廷", "near future, tech, courtly", "宮廷氣場下的十年後科技", "in a courtly register, tech ten years on", "courtly, near-future era"],
    ["near_future_street", "街頭近未來", "street near future", "近未、科、街頭", "near future, tech, street", "街頭質感的十年後科技", "with street grit, tech ten years on", "street-cast, near-future era"],
    ["near_future_noir", "暗黑近未來", "noir near future", "近未、科、暗黑", "near future, tech, noir", "暗調電影感的十年後科技", "in noir lighting, tech ten years on", "noir, near-future era"],
    ["near_future_soft", "柔光近未來", "soft-light near future", "近未、科、柔光", "near future, tech, soft", "柔光下的十年後科技", "under soft light, tech ten years on", "soft-lit, near-future era"],
    ["near_future_epic", "史詩近未來", "epic near future", "近未、科、史詩", "near future, tech, epic", "史詩尺度的十年後科技", "at epic scale, tech ten years on", "epic, near-future era"],
    ["far_future_court", "宮廷遠未來", "court far future", "遠、異、宮廷", "far, alien, courtly", "宮廷氣場下的遠到陌生", "in a courtly register, distant unfamiliar future", "courtly, far-future era"],
    ["far_future_street", "街頭遠未來", "street far future", "遠、異、街頭", "far, alien, street", "街頭質感的遠到陌生", "with street grit, distant unfamiliar future", "street-cast, far-future era"],
    ["far_future_noir", "暗黑遠未來", "noir far future", "遠、異、暗黑", "far, alien, noir", "暗調電影感的遠到陌生", "in noir lighting, distant unfamiliar future", "noir, far-future era"],
    ["far_future_soft", "柔光遠未來", "soft-light far future", "遠、異、柔光", "far, alien, soft", "柔光下的遠到陌生", "under soft light, distant unfamiliar future", "soft-lit, far-future era"],
    ["far_future_epic", "史詩遠未來", "epic far future", "遠、異、史詩", "far, alien, epic", "史詩尺度的遠到陌生", "at epic scale, distant unfamiliar future", "epic, far-future era"],
    ["mixed_court", "宮廷時代疊", "court anachronistic mix", "疊、錯、宮廷", "mix, anachronism, courtly", "宮廷氣場下的幾個年代疊", "in a courtly register, eras stacked", "courtly, anachronistic mixed era"],
    ["mixed_street", "街頭時代疊", "street anachronistic mix", "疊、錯、街頭", "mix, anachronism, street", "街頭質感的幾個年代疊", "with street grit, eras stacked", "street-cast, anachronistic mixed era"],
    ["mixed_noir", "暗黑時代疊", "noir anachronistic mix", "疊、錯、暗黑", "mix, anachronism, noir", "暗調電影感的幾個年代疊", "in noir lighting, eras stacked", "noir, anachronistic mixed era"],
    ["mixed_soft", "柔光時代疊", "soft-light anachronistic mix", "疊、錯、柔光", "mix, anachronism, soft", "柔光下的幾個年代疊", "under soft light, eras stacked", "soft-lit, anachronistic mixed era"],
    ["mixed_epic", "史詩時代疊", "epic anachronistic mix", "疊、錯、史詩", "mix, anachronism, epic", "史詩尺度的幾個年代疊", "at epic scale, eras stacked", "epic, anachronistic mixed era"],
    ["wartime_court", "宮廷戰時", "court wartime", "戰、宵、宮廷", "war, curfew, courtly", "宮廷氣場下的戰時宵禁感", "in a courtly register, wartime curfew feel", "courtly, wartime era"],
    ["wartime_street", "街頭戰時", "street wartime", "戰、宵、街頭", "war, curfew, street", "街頭質感的戰時宵禁感", "with street grit, wartime curfew feel", "street-cast, wartime era"],
    ["wartime_noir", "暗黑戰時", "noir wartime", "戰、宵、暗黑", "war, curfew, noir", "暗調電影感的戰時宵禁感", "in noir lighting, wartime curfew feel", "noir, wartime era"],
    ["wartime_soft", "柔光戰時", "soft-light wartime", "戰、宵、柔光", "war, curfew, soft", "柔光下的戰時宵禁感", "under soft light, wartime curfew feel", "soft-lit, wartime era"],
    ["wartime_epic", "史詩戰時", "epic wartime", "戰、宵、史詩", "war, curfew, epic", "史詩尺度的戰時宵禁感", "at epic scale, wartime curfew feel", "epic, wartime era"]
  ],
    interior: [
    ["bare_court", "宮廷空房", "court bare room", "空、回、宮廷", "bare, echo, courtly", "宮廷氣場下的幾乎沒傢俬", "in a courtly register, almost no furniture", "courtly, bare interior"],
    ["bare_street", "街頭空房", "street bare room", "空、回、街頭", "bare, echo, street", "街頭質感的幾乎沒傢俬", "with street grit, almost no furniture", "street-cast, bare interior"],
    ["bare_noir", "暗黑空房", "noir bare room", "空、回、暗黑", "bare, echo, noir", "暗調電影感的幾乎沒傢俬", "in noir lighting, almost no furniture", "noir, bare interior"],
    ["bare_soft", "柔光空房", "soft-light bare room", "空、回、柔光", "bare, echo, soft", "柔光下的幾乎沒傢俬", "under soft light, almost no furniture", "soft-lit, bare interior"],
    ["bare_epic", "史詩空房", "epic bare room", "空、回、史詩", "bare, echo, epic", "史詩尺度的幾乎沒傢俬", "at epic scale, almost no furniture", "epic, bare interior"],
    ["clutter_warm_court", "宮廷暖雜", "court warm clutter", "雜、暖、宮廷", "clutter, warm, courtly", "宮廷氣場下的生活雜物暖", "in a courtly register, warm lived clutter", "courtly, warm cluttered interior"],
    ["clutter_warm_street", "街頭暖雜", "street warm clutter", "雜、暖、街頭", "clutter, warm, street", "街頭質感的生活雜物暖", "with street grit, warm lived clutter", "street-cast, warm cluttered interior"],
    ["clutter_warm_noir", "暗黑暖雜", "noir warm clutter", "雜、暖、暗黑", "clutter, warm, noir", "暗調電影感的生活雜物暖", "in noir lighting, warm lived clutter", "noir, warm cluttered interior"],
    ["clutter_warm_soft", "柔光暖雜", "soft-light warm clutter", "雜、暖、柔光", "clutter, warm, soft", "柔光下的生活雜物暖", "under soft light, warm lived clutter", "soft-lit, warm cluttered interior"],
    ["clutter_warm_epic", "史詩暖雜", "epic warm clutter", "雜、暖、史詩", "clutter, warm, epic", "史詩尺度的生活雜物暖", "at epic scale, warm lived clutter", "epic, warm cluttered interior"],
    ["hotel_court", "宮廷酒店冷", "court hotel-cold", "酒店、無根、宮廷", "hotel, rootless, courtly", "宮廷氣場下的無個性酒店", "in a courtly register, anonymous hotel", "courtly, cold hotel interior"],
    ["hotel_street", "街頭酒店冷", "street hotel-cold", "酒店、無根、街頭", "hotel, rootless, street", "街頭質感的無個性酒店", "with street grit, anonymous hotel", "street-cast, cold hotel interior"],
    ["hotel_noir", "暗黑酒店冷", "noir hotel-cold", "酒店、無根、暗黑", "hotel, rootless, noir", "暗調電影感的無個性酒店", "in noir lighting, anonymous hotel", "noir, cold hotel interior"],
    ["hotel_soft", "柔光酒店冷", "soft-light hotel-cold", "酒店、無根、柔光", "hotel, rootless, soft", "柔光下的無個性酒店", "under soft light, anonymous hotel", "soft-lit, cold hotel interior"],
    ["hotel_epic", "史詩酒店冷", "epic hotel-cold", "酒店、無根、史詩", "hotel, rootless, epic", "史詩尺度的無個性酒店", "at epic scale, anonymous hotel", "epic, cold hotel interior"],
    ["office_court", "宮廷開放辦", "court open office", "辦、螢、宮廷", "office, glow, courtly", "宮廷氣場下的螢幕辦公室", "in a courtly register, screen-lit office", "courtly, open-office interior"],
    ["office_street", "街頭開放辦", "street open office", "辦、螢、街頭", "office, glow, street", "街頭質感的螢幕辦公室", "with street grit, screen-lit office", "street-cast, open-office interior"],
    ["office_noir", "暗黑開放辦", "noir open office", "辦、螢、暗黑", "office, glow, noir", "暗調電影感的螢幕辦公室", "in noir lighting, screen-lit office", "noir, open-office interior"],
    ["office_soft", "柔光開放辦", "soft-light open office", "辦、螢、柔光", "office, glow, soft", "柔光下的螢幕辦公室", "under soft light, screen-lit office", "soft-lit, open-office interior"],
    ["office_epic", "史詩開放辦", "epic open office", "辦、螢、史詩", "office, glow, epic", "史詩尺度的螢幕辦公室", "at epic scale, screen-lit office", "epic, open-office interior"],
    ["temple_in_court", "宮廷殿內香", "court temple hall", "殿、香、宮廷", "hall, incense, courtly", "宮廷氣場下的香煙殿內", "in a courtly register, incense-filled hall", "courtly, temple interior"],
    ["temple_in_street", "街頭殿內香", "street temple hall", "殿、香、街頭", "hall, incense, street", "街頭質感的香煙殿內", "with street grit, incense-filled hall", "street-cast, temple interior"],
    ["temple_in_noir", "暗黑殿內香", "noir temple hall", "殿、香、暗黑", "hall, incense, noir", "暗調電影感的香煙殿內", "in noir lighting, incense-filled hall", "noir, temple interior"],
    ["temple_in_soft", "柔光殿內香", "soft-light temple hall", "殿、香、柔光", "hall, incense, soft", "柔光下的香煙殿內", "under soft light, incense-filled hall", "soft-lit, temple interior"],
    ["temple_in_epic", "史詩殿內香", "epic temple hall", "殿、香、史詩", "hall, incense, epic", "史詩尺度的香煙殿內", "at epic scale, incense-filled hall", "epic, temple interior"],
    ["lab_court", "宮廷實驗室", "court lab", "實、白、宮廷", "lab, white, courtly", "宮廷氣場下的冷白實驗", "in a courtly register, cold white lab", "courtly, laboratory interior"],
    ["lab_street", "街頭實驗室", "street lab", "實、白、街頭", "lab, white, street", "街頭質感的冷白實驗", "with street grit, cold white lab", "street-cast, laboratory interior"],
    ["lab_noir", "暗黑實驗室", "noir lab", "實、白、暗黑", "lab, white, noir", "暗調電影感的冷白實驗", "in noir lighting, cold white lab", "noir, laboratory interior"],
    ["lab_soft", "柔光實驗室", "soft-light lab", "實、白、柔光", "lab, white, soft", "柔光下的冷白實驗", "under soft light, cold white lab", "soft-lit, laboratory interior"],
    ["lab_epic", "史詩實驗室", "epic lab", "實、白、史詩", "lab, white, epic", "史詩尺度的冷白實驗", "at epic scale, cold white lab", "epic, laboratory interior"],
    ["kitchen_court", "宮廷生活廚", "court lived kitchen", "廚、煙、宮廷", "kitchen, steam, courtly", "宮廷氣場下的有煙火廚房", "in a courtly register, steamy lived kitchen", "courtly, lived-in kitchen"],
    ["kitchen_street", "街頭生活廚", "street lived kitchen", "廚、煙、街頭", "kitchen, steam, street", "街頭質感的有煙火廚房", "with street grit, steamy lived kitchen", "street-cast, lived-in kitchen"],
    ["kitchen_noir", "暗黑生活廚", "noir lived kitchen", "廚、煙、暗黑", "kitchen, steam, noir", "暗調電影感的有煙火廚房", "in noir lighting, steamy lived kitchen", "noir, lived-in kitchen"],
    ["kitchen_soft", "柔光生活廚", "soft-light lived kitchen", "廚、煙、柔光", "kitchen, steam, soft", "柔光下的有煙火廚房", "under soft light, steamy lived kitchen", "soft-lit, lived-in kitchen"],
    ["kitchen_epic", "史詩生活廚", "epic lived kitchen", "廚、煙、史詩", "kitchen, steam, epic", "史詩尺度的有煙火廚房", "at epic scale, steamy lived kitchen", "epic, lived-in kitchen"],
    ["throne_court", "宮廷廳堂威", "court throne hall", "廳、威、宮廷", "hall, authority, courtly", "宮廷氣場下的威儀廳堂", "in a courtly register, authoritative hall", "courtly, throne-hall interior"],
    ["throne_street", "街頭廳堂威", "street throne hall", "廳、威、街頭", "hall, authority, street", "街頭質感的威儀廳堂", "with street grit, authoritative hall", "street-cast, throne-hall interior"],
    ["throne_noir", "暗黑廳堂威", "noir throne hall", "廳、威、暗黑", "hall, authority, noir", "暗調電影感的威儀廳堂", "in noir lighting, authoritative hall", "noir, throne-hall interior"],
    ["throne_soft", "柔光廳堂威", "soft-light throne hall", "廳、威、柔光", "hall, authority, soft", "柔光下的威儀廳堂", "under soft light, authoritative hall", "soft-lit, throne-hall interior"],
    ["throne_epic", "史詩廳堂威", "epic throne hall", "廳、威、史詩", "hall, authority, epic", "史詩尺度的威儀廳堂", "at epic scale, authoritative hall", "epic, throne-hall interior"],
    ["basement_court", "宮廷地下濕", "court damp basement", "地、濕、宮廷", "basement, damp, courtly", "宮廷氣場下的潮濕地下", "in a courtly register, damp basement", "courtly, damp basement interior"],
    ["basement_street", "街頭地下濕", "street damp basement", "地、濕、街頭", "basement, damp, street", "街頭質感的潮濕地下", "with street grit, damp basement", "street-cast, damp basement interior"],
    ["basement_noir", "暗黑地下濕", "noir damp basement", "地、濕、暗黑", "basement, damp, noir", "暗調電影感的潮濕地下", "in noir lighting, damp basement", "noir, damp basement interior"],
    ["basement_soft", "柔光地下濕", "soft-light damp basement", "地、濕、柔光", "basement, damp, soft", "柔光下的潮濕地下", "under soft light, damp basement", "soft-lit, damp basement interior"],
    ["basement_epic", "史詩地下濕", "epic damp basement", "地、濕、史詩", "basement, damp, epic", "史詩尺度的潮濕地下", "at epic scale, damp basement", "epic, damp basement interior"],
    ["loft_court", "宮廷工業閣樓", "court industrial loft", "閣、梁、宮廷", "loft, beam, courtly", "宮廷氣場下的露梁閣樓", "in a courtly register, exposed-beam loft", "courtly, industrial loft interior"],
    ["loft_street", "街頭工業閣樓", "street industrial loft", "閣、梁、街頭", "loft, beam, street", "街頭質感的露梁閣樓", "with street grit, exposed-beam loft", "street-cast, industrial loft interior"],
    ["loft_noir", "暗黑工業閣樓", "noir industrial loft", "閣、梁、暗黑", "loft, beam, noir", "暗調電影感的露梁閣樓", "in noir lighting, exposed-beam loft", "noir, industrial loft interior"],
    ["loft_soft", "柔光工業閣樓", "soft-light industrial loft", "閣、梁、柔光", "loft, beam, soft", "柔光下的露梁閣樓", "under soft light, exposed-beam loft", "soft-lit, industrial loft interior"],
    ["loft_epic", "史詩工業閣樓", "epic industrial loft", "閣、梁、史詩", "loft, beam, epic", "史詩尺度的露梁閣樓", "at epic scale, exposed-beam loft", "epic, industrial loft interior"]
  ],
    landmark: [
    ["gate_court", "宮廷舊城門", "court old city gate", "門、城、宮廷", "gate, city, courtly", "宮廷氣場下的可見舊城門", "in a courtly register, visible old gate", "courtly, old city-gate landmark"],
    ["gate_street", "街頭舊城門", "street old city gate", "門、城、街頭", "gate, city, street", "街頭質感的可見舊城門", "with street grit, visible old gate", "street-cast, old city-gate landmark"],
    ["gate_noir", "暗黑舊城門", "noir old city gate", "門、城、暗黑", "gate, city, noir", "暗調電影感的可見舊城門", "in noir lighting, visible old gate", "noir, old city-gate landmark"],
    ["gate_soft", "柔光舊城門", "soft-light old city gate", "門、城、柔光", "gate, city, soft", "柔光下的可見舊城門", "under soft light, visible old gate", "soft-lit, old city-gate landmark"],
    ["gate_epic", "史詩舊城門", "epic old city gate", "門、城、史詩", "gate, city, epic", "史詩尺度的可見舊城門", "at epic scale, visible old gate", "epic, old city-gate landmark"],
    ["tower_clock_court", "宮廷鐘樓", "court clock tower", "鐘、高、宮廷", "clock, tall, courtly", "宮廷氣場下的高鐘樓", "in a courtly register, tall clock tower", "courtly, clock-tower landmark"],
    ["tower_clock_street", "街頭鐘樓", "street clock tower", "鐘、高、街頭", "clock, tall, street", "街頭質感的高鐘樓", "with street grit, tall clock tower", "street-cast, clock-tower landmark"],
    ["tower_clock_noir", "暗黑鐘樓", "noir clock tower", "鐘、高、暗黑", "clock, tall, noir", "暗調電影感的高鐘樓", "in noir lighting, tall clock tower", "noir, clock-tower landmark"],
    ["tower_clock_soft", "柔光鐘樓", "soft-light clock tower", "鐘、高、柔光", "clock, tall, soft", "柔光下的高鐘樓", "under soft light, tall clock tower", "soft-lit, clock-tower landmark"],
    ["tower_clock_epic", "史詩鐘樓", "epic clock tower", "鐘、高、史詩", "clock, tall, epic", "史詩尺度的高鐘樓", "at epic scale, tall clock tower", "epic, clock-tower landmark"],
    ["bridge_court", "宮廷長橋", "court long bridge", "橋、水、宮廷", "bridge, water, courtly", "宮廷氣場下的跨水長橋", "in a courtly register, long water bridge", "courtly, long-bridge landmark"],
    ["bridge_street", "街頭長橋", "street long bridge", "橋、水、街頭", "bridge, water, street", "街頭質感的跨水長橋", "with street grit, long water bridge", "street-cast, long-bridge landmark"],
    ["bridge_noir", "暗黑長橋", "noir long bridge", "橋、水、暗黑", "bridge, water, noir", "暗調電影感的跨水長橋", "in noir lighting, long water bridge", "noir, long-bridge landmark"],
    ["bridge_soft", "柔光長橋", "soft-light long bridge", "橋、水、柔光", "bridge, water, soft", "柔光下的跨水長橋", "under soft light, long water bridge", "soft-lit, long-bridge landmark"],
    ["bridge_epic", "史詩長橋", "epic long bridge", "橋、水、史詩", "bridge, water, epic", "史詩尺度的跨水長橋", "at epic scale, long water bridge", "epic, long-bridge landmark"],
    ["statue_court", "宮廷巨像", "court colossal statue", "像、巨、宮廷", "statue, huge, courtly", "宮廷氣場下的廣場巨像", "in a courtly register, plaza colossus", "courtly, colossal-statue landmark"],
    ["statue_street", "街頭巨像", "street colossal statue", "像、巨、街頭", "statue, huge, street", "街頭質感的廣場巨像", "with street grit, plaza colossus", "street-cast, colossal-statue landmark"],
    ["statue_noir", "暗黑巨像", "noir colossal statue", "像、巨、暗黑", "statue, huge, noir", "暗調電影感的廣場巨像", "in noir lighting, plaza colossus", "noir, colossal-statue landmark"],
    ["statue_soft", "柔光巨像", "soft-light colossal statue", "像、巨、柔光", "statue, huge, soft", "柔光下的廣場巨像", "under soft light, plaza colossus", "soft-lit, colossal-statue landmark"],
    ["statue_epic", "史詩巨像", "epic colossal statue", "像、巨、史詩", "statue, huge, epic", "史詩尺度的廣場巨像", "at epic scale, plaza colossus", "epic, colossal-statue landmark"],
    ["neon_sign_court", "宮廷巨霓虹", "court giant neon", "霓虹、夜、宮廷", "neon, night, courtly", "宮廷氣場下的樓面巨霓虹", "in a courtly register, building-scale neon", "courtly, giant neon landmark"],
    ["neon_sign_street", "街頭巨霓虹", "street giant neon", "霓虹、夜、街頭", "neon, night, street", "街頭質感的樓面巨霓虹", "with street grit, building-scale neon", "street-cast, giant neon landmark"],
    ["neon_sign_noir", "暗黑巨霓虹", "noir giant neon", "霓虹、夜、暗黑", "neon, night, noir", "暗調電影感的樓面巨霓虹", "in noir lighting, building-scale neon", "noir, giant neon landmark"],
    ["neon_sign_soft", "柔光巨霓虹", "soft-light giant neon", "霓虹、夜、柔光", "neon, night, soft", "柔光下的樓面巨霓虹", "under soft light, building-scale neon", "soft-lit, giant neon landmark"],
    ["neon_sign_epic", "史詩巨霓虹", "epic giant neon", "霓虹、夜、史詩", "neon, night, epic", "史詩尺度的樓面巨霓虹", "at epic scale, building-scale neon", "epic, giant neon landmark"],
    ["none_court", "宮廷無地標", "court no landmark", "無、純、宮廷", "none, pure, courtly", "宮廷氣場下的沒有單一地標", "in a courtly register, no single landmark", "courtly, no landmark"],
    ["none_street", "街頭無地標", "street no landmark", "無、純、街頭", "none, pure, street", "街頭質感的沒有單一地標", "with street grit, no single landmark", "street-cast, no landmark"],
    ["none_noir", "暗黑無地標", "noir no landmark", "無、純、暗黑", "none, pure, noir", "暗調電影感的沒有單一地標", "in noir lighting, no single landmark", "noir, no landmark"],
    ["none_soft", "柔光無地標", "soft-light no landmark", "無、純、柔光", "none, pure, soft", "柔光下的沒有單一地標", "under soft light, no single landmark", "soft-lit, no landmark"],
    ["none_epic", "史詩無地標", "epic no landmark", "無、純、史詩", "none, pure, epic", "史詩尺度的沒有單一地標", "at epic scale, no single landmark", "epic, no landmark"],
    ["pagoda_court", "宮廷塔影", "court pagoda", "塔、影、宮廷", "pagoda, silhouette, courtly", "宮廷氣場下的遠處塔影", "in a courtly register, distant pagoda", "courtly, pagoda landmark"],
    ["pagoda_street", "街頭塔影", "street pagoda", "塔、影、街頭", "pagoda, silhouette, street", "街頭質感的遠處塔影", "with street grit, distant pagoda", "street-cast, pagoda landmark"],
    ["pagoda_noir", "暗黑塔影", "noir pagoda", "塔、影、暗黑", "pagoda, silhouette, noir", "暗調電影感的遠處塔影", "in noir lighting, distant pagoda", "noir, pagoda landmark"],
    ["pagoda_soft", "柔光塔影", "soft-light pagoda", "塔、影、柔光", "pagoda, silhouette, soft", "柔光下的遠處塔影", "under soft light, distant pagoda", "soft-lit, pagoda landmark"],
    ["pagoda_epic", "史詩塔影", "epic pagoda", "塔、影、史詩", "pagoda, silhouette, epic", "史詩尺度的遠處塔影", "at epic scale, distant pagoda", "epic, pagoda landmark"],
    ["crane_court", "宮廷吊臂天際", "court crane skyline", "吊、建、宮廷", "crane, build, courtly", "宮廷氣場下的塔吊林立", "in a courtly register, construction cranes", "courtly, crane-skyline landmark"],
    ["crane_street", "街頭吊臂天際", "street crane skyline", "吊、建、街頭", "crane, build, street", "街頭質感的塔吊林立", "with street grit, construction cranes", "street-cast, crane-skyline landmark"],
    ["crane_noir", "暗黑吊臂天際", "noir crane skyline", "吊、建、暗黑", "crane, build, noir", "暗調電影感的塔吊林立", "in noir lighting, construction cranes", "noir, crane-skyline landmark"],
    ["crane_soft", "柔光吊臂天際", "soft-light crane skyline", "吊、建、柔光", "crane, build, soft", "柔光下的塔吊林立", "under soft light, construction cranes", "soft-lit, crane-skyline landmark"],
    ["crane_epic", "史詩吊臂天際", "epic crane skyline", "吊、建、史詩", "crane, build, epic", "史詩尺度的塔吊林立", "at epic scale, construction cranes", "epic, crane-skyline landmark"],
    ["river_court", "宮廷河彎", "court river bend", "河、彎、宮廷", "river, bend, courtly", "宮廷氣場下的城市河彎", "in a courtly register, city river bend", "courtly, river-bend landmark"],
    ["river_street", "街頭河彎", "street river bend", "河、彎、街頭", "river, bend, street", "街頭質感的城市河彎", "with street grit, city river bend", "street-cast, river-bend landmark"],
    ["river_noir", "暗黑河彎", "noir river bend", "河、彎、暗黑", "river, bend, noir", "暗調電影感的城市河彎", "in noir lighting, city river bend", "noir, river-bend landmark"],
    ["river_soft", "柔光河彎", "soft-light river bend", "河、彎、柔光", "river, bend, soft", "柔光下的城市河彎", "under soft light, city river bend", "soft-lit, river-bend landmark"],
    ["river_epic", "史詩河彎", "epic river bend", "河、彎、史詩", "river, bend, epic", "史詩尺度的城市河彎", "at epic scale, city river bend", "epic, river-bend landmark"],
    ["wall_court", "宮廷舊城牆", "court old city wall", "牆、磚、宮廷", "wall, brick, courtly", "宮廷氣場下的可走的舊牆", "in a courtly register, walkable old wall", "courtly, city-wall landmark"],
    ["wall_street", "街頭舊城牆", "street old city wall", "牆、磚、街頭", "wall, brick, street", "街頭質感的可走的舊牆", "with street grit, walkable old wall", "street-cast, city-wall landmark"],
    ["wall_noir", "暗黑舊城牆", "noir old city wall", "牆、磚、暗黑", "wall, brick, noir", "暗調電影感的可走的舊牆", "in noir lighting, walkable old wall", "noir, city-wall landmark"],
    ["wall_soft", "柔光舊城牆", "soft-light old city wall", "牆、磚、柔光", "wall, brick, soft", "柔光下的可走的舊牆", "under soft light, walkable old wall", "soft-lit, city-wall landmark"],
    ["wall_epic", "史詩舊城牆", "epic old city wall", "牆、磚、史詩", "wall, brick, epic", "史詩尺度的可走的舊牆", "at epic scale, walkable old wall", "epic, city-wall landmark"]
  ],
    vegetation: [
    ["none_court", "宮廷幾乎無綠", "court almost none", "無綠、硬、宮廷", "none, hard, courtly", "宮廷氣場下的少植物", "in a courtly register, almost no plants", "courtly, almost no vegetation"],
    ["none_street", "街頭幾乎無綠", "street almost none", "無綠、硬、街頭", "none, hard, street", "街頭質感的少植物", "with street grit, almost no plants", "street-cast, almost no vegetation"],
    ["none_noir", "暗黑幾乎無綠", "noir almost none", "無綠、硬、暗黑", "none, hard, noir", "暗調電影感的少植物", "in noir lighting, almost no plants", "noir, almost no vegetation"],
    ["none_soft", "柔光幾乎無綠", "soft-light almost none", "無綠、硬、柔光", "none, hard, soft", "柔光下的少植物", "under soft light, almost no plants", "soft-lit, almost no vegetation"],
    ["none_epic", "史詩幾乎無綠", "epic almost none", "無綠、硬、史詩", "none, hard, epic", "史詩尺度的少植物", "at epic scale, almost no plants", "epic, almost no vegetation"],
    ["plane_tree_court", "宮廷行道梧桐", "court plane trees", "梧桐、街、宮廷", "plane, street, courtly", "宮廷氣場下的街邊梧桐", "in a courtly register, street plane trees", "courtly, plane-tree vegetation"],
    ["plane_tree_street", "街頭行道梧桐", "street plane trees", "梧桐、街、街頭", "plane, street, street", "街頭質感的街邊梧桐", "with street grit, street plane trees", "street-cast, plane-tree vegetation"],
    ["plane_tree_noir", "暗黑行道梧桐", "noir plane trees", "梧桐、街、暗黑", "plane, street, noir", "暗調電影感的街邊梧桐", "in noir lighting, street plane trees", "noir, plane-tree vegetation"],
    ["plane_tree_soft", "柔光行道梧桐", "soft-light plane trees", "梧桐、街、柔光", "plane, street, soft", "柔光下的街邊梧桐", "under soft light, street plane trees", "soft-lit, plane-tree vegetation"],
    ["plane_tree_epic", "史詩行道梧桐", "epic plane trees", "梧桐、街、史詩", "plane, street, epic", "史詩尺度的街邊梧桐", "at epic scale, street plane trees", "epic, plane-tree vegetation"],
    ["bamboo_court", "宮廷竹叢", "court bamboo", "竹、密、宮廷", "bamboo, dense, courtly", "宮廷氣場下的密竹", "in a courtly register, dense bamboo", "courtly, bamboo grove"],
    ["bamboo_street", "街頭竹叢", "street bamboo", "竹、密、街頭", "bamboo, dense, street", "街頭質感的密竹", "with street grit, dense bamboo", "street-cast, bamboo grove"],
    ["bamboo_noir", "暗黑竹叢", "noir bamboo", "竹、密、暗黑", "bamboo, dense, noir", "暗調電影感的密竹", "in noir lighting, dense bamboo", "noir, bamboo grove"],
    ["bamboo_soft", "柔光竹叢", "soft-light bamboo", "竹、密、柔光", "bamboo, dense, soft", "柔光下的密竹", "under soft light, dense bamboo", "soft-lit, bamboo grove"],
    ["bamboo_epic", "史詩竹叢", "epic bamboo", "竹、密、史詩", "bamboo, dense, epic", "史詩尺度的密竹", "at epic scale, dense bamboo", "epic, bamboo grove"],
    ["pine_court", "宮廷松", "court pines", "松、骨、宮廷", "pine, bone, courtly", "宮廷氣場下的瘦松", "in a courtly register, spare pines", "courtly, pine vegetation"],
    ["pine_street", "街頭松", "street pines", "松、骨、街頭", "pine, bone, street", "街頭質感的瘦松", "with street grit, spare pines", "street-cast, pine vegetation"],
    ["pine_noir", "暗黑松", "noir pines", "松、骨、暗黑", "pine, bone, noir", "暗調電影感的瘦松", "in noir lighting, spare pines", "noir, pine vegetation"],
    ["pine_soft", "柔光松", "soft-light pines", "松、骨、柔光", "pine, bone, soft", "柔光下的瘦松", "under soft light, spare pines", "soft-lit, pine vegetation"],
    ["pine_epic", "史詩松", "epic pines", "松、骨、史詩", "pine, bone, epic", "史詩尺度的瘦松", "at epic scale, spare pines", "epic, pine vegetation"],
    ["weed_court", "宮廷野草縫", "court weeds in cracks", "草、縫、宮廷", "weed, crack, courtly", "宮廷氣場下的磚縫野草", "in a courtly register, weeds in brick cracks", "courtly, weed-in-crack vegetation"],
    ["weed_street", "街頭野草縫", "street weeds in cracks", "草、縫、街頭", "weed, crack, street", "街頭質感的磚縫野草", "with street grit, weeds in brick cracks", "street-cast, weed-in-crack vegetation"],
    ["weed_noir", "暗黑野草縫", "noir weeds in cracks", "草、縫、暗黑", "weed, crack, noir", "暗調電影感的磚縫野草", "in noir lighting, weeds in brick cracks", "noir, weed-in-crack vegetation"],
    ["weed_soft", "柔光野草縫", "soft-light weeds in cracks", "草、縫、柔光", "weed, crack, soft", "柔光下的磚縫野草", "under soft light, weeds in brick cracks", "soft-lit, weed-in-crack vegetation"],
    ["weed_epic", "史詩野草縫", "epic weeds in cracks", "草、縫、史詩", "weed, crack, epic", "史詩尺度的磚縫野草", "at epic scale, weeds in brick cracks", "epic, weed-in-crack vegetation"],
    ["lotus_court", "宮廷荷塘", "court lotus pond", "荷、水、宮廷", "lotus, water, courtly", "宮廷氣場下的荷葉水面", "in a courtly register, lotus-covered water", "courtly, lotus-pond vegetation"],
    ["lotus_street", "街頭荷塘", "street lotus pond", "荷、水、街頭", "lotus, water, street", "街頭質感的荷葉水面", "with street grit, lotus-covered water", "street-cast, lotus-pond vegetation"],
    ["lotus_noir", "暗黑荷塘", "noir lotus pond", "荷、水、暗黑", "lotus, water, noir", "暗調電影感的荷葉水面", "in noir lighting, lotus-covered water", "noir, lotus-pond vegetation"],
    ["lotus_soft", "柔光荷塘", "soft-light lotus pond", "荷、水、柔光", "lotus, water, soft", "柔光下的荷葉水面", "under soft light, lotus-covered water", "soft-lit, lotus-pond vegetation"],
    ["lotus_epic", "史詩荷塘", "epic lotus pond", "荷、水、史詩", "lotus, water, epic", "史詩尺度的荷葉水面", "at epic scale, lotus-covered water", "epic, lotus-pond vegetation"],
    ["dead_court", "宮廷枯枝", "court dead branches", "枯、冬、宮廷", "dead, winter, courtly", "宮廷氣場下的枯枝為主", "in a courtly register, mostly dead branches", "courtly, dead-branch vegetation"],
    ["dead_street", "街頭枯枝", "street dead branches", "枯、冬、街頭", "dead, winter, street", "街頭質感的枯枝為主", "with street grit, mostly dead branches", "street-cast, dead-branch vegetation"],
    ["dead_noir", "暗黑枯枝", "noir dead branches", "枯、冬、暗黑", "dead, winter, noir", "暗調電影感的枯枝為主", "in noir lighting, mostly dead branches", "noir, dead-branch vegetation"],
    ["dead_soft", "柔光枯枝", "soft-light dead branches", "枯、冬、柔光", "dead, winter, soft", "柔光下的枯枝為主", "under soft light, mostly dead branches", "soft-lit, dead-branch vegetation"],
    ["dead_epic", "史詩枯枝", "epic dead branches", "枯、冬、史詩", "dead, winter, epic", "史詩尺度的枯枝為主", "at epic scale, mostly dead branches", "epic, dead-branch vegetation"],
    ["jungle_court", "宮廷熱帶密", "court jungle dense", "熱、密、宮廷", "jungle, dense, courtly", "宮廷氣場下的熱帶密葉", "in a courtly register, dense tropical leaf", "courtly, jungle vegetation"],
    ["jungle_street", "街頭熱帶密", "street jungle dense", "熱、密、街頭", "jungle, dense, street", "街頭質感的熱帶密葉", "with street grit, dense tropical leaf", "street-cast, jungle vegetation"],
    ["jungle_noir", "暗黑熱帶密", "noir jungle dense", "熱、密、暗黑", "jungle, dense, noir", "暗調電影感的熱帶密葉", "in noir lighting, dense tropical leaf", "noir, jungle vegetation"],
    ["jungle_soft", "柔光熱帶密", "soft-light jungle dense", "熱、密、柔光", "jungle, dense, soft", "柔光下的熱帶密葉", "under soft light, dense tropical leaf", "soft-lit, jungle vegetation"],
    ["jungle_epic", "史詩熱帶密", "epic jungle dense", "熱、密、史詩", "jungle, dense, epic", "史詩尺度的熱帶密葉", "at epic scale, dense tropical leaf", "epic, jungle vegetation"],
    ["bonsai_court", "宮廷盆景點", "court bonsai accents", "盆、控、宮廷", "bonsai, control, courtly", "宮廷氣場下的幾盆精修", "in a courtly register, few trained bonsai", "courtly, bonsai-accent vegetation"],
    ["bonsai_street", "街頭盆景點", "street bonsai accents", "盆、控、街頭", "bonsai, control, street", "街頭質感的幾盆精修", "with street grit, few trained bonsai", "street-cast, bonsai-accent vegetation"],
    ["bonsai_noir", "暗黑盆景點", "noir bonsai accents", "盆、控、暗黑", "bonsai, control, noir", "暗調電影感的幾盆精修", "in noir lighting, few trained bonsai", "noir, bonsai-accent vegetation"],
    ["bonsai_soft", "柔光盆景點", "soft-light bonsai accents", "盆、控、柔光", "bonsai, control, soft", "柔光下的幾盆精修", "under soft light, few trained bonsai", "soft-lit, bonsai-accent vegetation"],
    ["bonsai_epic", "史詩盆景點", "epic bonsai accents", "盆、控、史詩", "bonsai, control, epic", "史詩尺度的幾盆精修", "at epic scale, few trained bonsai", "epic, bonsai-accent vegetation"],
    ["ivy_court", "宮廷爬藤", "court ivy", "藤、牆、宮廷", "ivy, wall, courtly", "宮廷氣場下的牆面爬藤", "in a courtly register, ivy on walls", "courtly, ivy vegetation"],
    ["ivy_street", "街頭爬藤", "street ivy", "藤、牆、街頭", "ivy, wall, street", "街頭質感的牆面爬藤", "with street grit, ivy on walls", "street-cast, ivy vegetation"],
    ["ivy_noir", "暗黑爬藤", "noir ivy", "藤、牆、暗黑", "ivy, wall, noir", "暗調電影感的牆面爬藤", "in noir lighting, ivy on walls", "noir, ivy vegetation"],
    ["ivy_soft", "柔光爬藤", "soft-light ivy", "藤、牆、柔光", "ivy, wall, soft", "柔光下的牆面爬藤", "under soft light, ivy on walls", "soft-lit, ivy vegetation"],
    ["ivy_epic", "史詩爬藤", "epic ivy", "藤、牆、史詩", "ivy, wall, epic", "史詩尺度的牆面爬藤", "at epic scale, ivy on walls", "epic, ivy vegetation"]
  ]
  }
})
