/**
 * mannerism field kit catalog (50+ templates per part).
 */
import { defineFieldKit } from '../fieldKit'

export const MANNERISM_KIT = defineFieldKit({
  key: "mannerismKit",
  parts: ["gait","hands","gaze","speech","posture","tic"] as const,
  partLabels: {
    gait: { zhHK: "步態", zhCN: "步态", en: "Gait" },
    hands: { zhHK: "手勢", zhCN: "手势", en: "Hands" },
    gaze: { zhHK: "視線", zhCN: "视线", en: "Gaze" },
    speech: { zhHK: "說話習慣", zhCN: "说话习惯", en: "Speech habit" },
    posture: { zhHK: "體態", zhCN: "体态", en: "Posture" },
    tic: { zhHK: "小動作", zhCN: "小动作", en: "Tic" }
  },

  rows: {
    gait: [
    ["glide_court", "宮廷滑步", "court glide", "滑、靜、宮廷", "glide, quiet, courtly", "宮廷氣場下的幾乎無聲滑", "in a courtly register, near-silent glide", "courtly, gliding quiet gait"],
    ["glide_street", "街頭滑步", "street glide", "滑、靜、街頭", "glide, quiet, street", "街頭質感的幾乎無聲滑", "with street grit, near-silent glide", "street-cast, gliding quiet gait"],
    ["glide_noir", "暗黑滑步", "noir glide", "滑、靜、暗黑", "glide, quiet, noir", "暗調電影感的幾乎無聲滑", "in noir lighting, near-silent glide", "noir, gliding quiet gait"],
    ["glide_soft", "柔光滑步", "soft-light glide", "滑、靜、柔光", "glide, quiet, soft", "柔光下的幾乎無聲滑", "under soft light, near-silent glide", "soft-lit, gliding quiet gait"],
    ["glide_epic", "史詩滑步", "epic glide", "滑、靜、史詩", "glide, quiet, epic", "史詩尺度的幾乎無聲滑", "at epic scale, near-silent glide", "epic, gliding quiet gait"],
    ["stride_court", "宮廷大步", "court long stride", "大步、佔、宮廷", "stride, occupy, courtly", "宮廷氣場下的步幅偏大", "in a courtly register, long occupying stride", "courtly, long stride"],
    ["stride_street", "街頭大步", "street long stride", "大步、佔、街頭", "stride, occupy, street", "街頭質感的步幅偏大", "with street grit, long occupying stride", "street-cast, long stride"],
    ["stride_noir", "暗黑大步", "noir long stride", "大步、佔、暗黑", "stride, occupy, noir", "暗調電影感的步幅偏大", "in noir lighting, long occupying stride", "noir, long stride"],
    ["stride_soft", "柔光大步", "soft-light long stride", "大步、佔、柔光", "stride, occupy, soft", "柔光下的步幅偏大", "under soft light, long occupying stride", "soft-lit, long stride"],
    ["stride_epic", "史詩大步", "epic long stride", "大步、佔、史詩", "stride, occupy, epic", "史詩尺度的步幅偏大", "at epic scale, long occupying stride", "epic, long stride"],
    ["quick_step_court", "宮廷碎步快", "court quick steps", "碎、快、宮廷", "quick, small, courtly", "宮廷氣場下的碎而快", "in a courtly register, small quick steps", "courtly, quick small-step gait"],
    ["quick_step_street", "街頭碎步快", "street quick steps", "碎、快、街頭", "quick, small, street", "街頭質感的碎而快", "with street grit, small quick steps", "street-cast, quick small-step gait"],
    ["quick_step_noir", "暗黑碎步快", "noir quick steps", "碎、快、暗黑", "quick, small, noir", "暗調電影感的碎而快", "in noir lighting, small quick steps", "noir, quick small-step gait"],
    ["quick_step_soft", "柔光碎步快", "soft-light quick steps", "碎、快、柔光", "quick, small, soft", "柔光下的碎而快", "under soft light, small quick steps", "soft-lit, quick small-step gait"],
    ["quick_step_epic", "史詩碎步快", "epic quick steps", "碎、快、史詩", "quick, small, epic", "史詩尺度的碎而快", "at epic scale, small quick steps", "epic, quick small-step gait"],
    ["limp_faint_court", "宮廷輕跛", "court faint limp", "跛、記、宮廷", "limp, mark, courtly", "宮廷氣場下的可察輕跛", "in a courtly register, faint visible limp", "courtly, faint limp"],
    ["limp_faint_street", "街頭輕跛", "street faint limp", "跛、記、街頭", "limp, mark, street", "街頭質感的可察輕跛", "with street grit, faint visible limp", "street-cast, faint limp"],
    ["limp_faint_noir", "暗黑輕跛", "noir faint limp", "跛、記、暗黑", "limp, mark, noir", "暗調電影感的可察輕跛", "in noir lighting, faint visible limp", "noir, faint limp"],
    ["limp_faint_soft", "柔光輕跛", "soft-light faint limp", "跛、記、柔光", "limp, mark, soft", "柔光下的可察輕跛", "under soft light, faint visible limp", "soft-lit, faint limp"],
    ["limp_faint_epic", "史詩輕跛", "epic faint limp", "跛、記、史詩", "limp, mark, epic", "史詩尺度的可察輕跛", "at epic scale, faint visible limp", "epic, faint limp"],
    ["military_court", "宮廷軍步", "court military", "軍、齊、宮廷", "military, even, courtly", "宮廷氣場下的齊整軍步", "in a courtly register, even military step", "courtly, military gait"],
    ["military_street", "街頭軍步", "street military", "軍、齊、街頭", "military, even, street", "街頭質感的齊整軍步", "with street grit, even military step", "street-cast, military gait"],
    ["military_noir", "暗黑軍步", "noir military", "軍、齊、暗黑", "military, even, noir", "暗調電影感的齊整軍步", "in noir lighting, even military step", "noir, military gait"],
    ["military_soft", "柔光軍步", "soft-light military", "軍、齊、柔光", "military, even, soft", "柔光下的齊整軍步", "under soft light, even military step", "soft-lit, military gait"],
    ["military_epic", "史詩軍步", "epic military", "軍、齊、史詩", "military, even, epic", "史詩尺度的齊整軍步", "at epic scale, even military step", "epic, military gait"],
    ["saunter_court", "宮廷閒晃", "court saunter", "閒、鬆、宮廷", "saunter, loose, courtly", "宮廷氣場下的肩鬆閒晃", "in a courtly register, loose saunter", "courtly, sauntering gait"],
    ["saunter_street", "街頭閒晃", "street saunter", "閒、鬆、街頭", "saunter, loose, street", "街頭質感的肩鬆閒晃", "with street grit, loose saunter", "street-cast, sauntering gait"],
    ["saunter_noir", "暗黑閒晃", "noir saunter", "閒、鬆、暗黑", "saunter, loose, noir", "暗調電影感的肩鬆閒晃", "in noir lighting, loose saunter", "noir, sauntering gait"],
    ["saunter_soft", "柔光閒晃", "soft-light saunter", "閒、鬆、柔光", "saunter, loose, soft", "柔光下的肩鬆閒晃", "under soft light, loose saunter", "soft-lit, sauntering gait"],
    ["saunter_epic", "史詩閒晃", "epic saunter", "閒、鬆、史詩", "saunter, loose, epic", "史詩尺度的肩鬆閒晃", "at epic scale, loose saunter", "epic, sauntering gait"],
    ["tiptoe_court", "宮廷踮", "court tiptoe", "踮、偷、宮廷", "tiptoe, stealth, courtly", "宮廷氣場下的常踮腳", "in a courtly register, often on toes", "courtly, tiptoe gait"],
    ["tiptoe_street", "街頭踮", "street tiptoe", "踮、偷、街頭", "tiptoe, stealth, street", "街頭質感的常踮腳", "with street grit, often on toes", "street-cast, tiptoe gait"],
    ["tiptoe_noir", "暗黑踮", "noir tiptoe", "踮、偷、暗黑", "tiptoe, stealth, noir", "暗調電影感的常踮腳", "in noir lighting, often on toes", "noir, tiptoe gait"],
    ["tiptoe_soft", "柔光踮", "soft-light tiptoe", "踮、偷、柔光", "tiptoe, stealth, soft", "柔光下的常踮腳", "under soft light, often on toes", "soft-lit, tiptoe gait"],
    ["tiptoe_epic", "史詩踮", "epic tiptoe", "踮、偷、史詩", "tiptoe, stealth, epic", "史詩尺度的常踮腳", "at epic scale, often on toes", "epic, tiptoe gait"],
    ["heavy_court", "宮廷沉重", "court heavy", "重、地、宮廷", "heavy, ground, courtly", "宮廷氣場下的踏地偏重", "in a courtly register, heavy footfall", "courtly, heavy gait"],
    ["heavy_street", "街頭沉重", "street heavy", "重、地、街頭", "heavy, ground, street", "街頭質感的踏地偏重", "with street grit, heavy footfall", "street-cast, heavy gait"],
    ["heavy_noir", "暗黑沉重", "noir heavy", "重、地、暗黑", "heavy, ground, noir", "暗調電影感的踏地偏重", "in noir lighting, heavy footfall", "noir, heavy gait"],
    ["heavy_soft", "柔光沉重", "soft-light heavy", "重、地、柔光", "heavy, ground, soft", "柔光下的踏地偏重", "under soft light, heavy footfall", "soft-lit, heavy gait"],
    ["heavy_epic", "史詩沉重", "epic heavy", "重、地、史詩", "heavy, ground, epic", "史詩尺度的踏地偏重", "at epic scale, heavy footfall", "epic, heavy gait"],
    ["dance_court", "宮廷帶舞性", "court dance-like", "舞、轉、宮廷", "dance, turn, courtly", "宮廷氣場下的轉身帶弧", "in a courtly register, arced dance turns", "courtly, dance-like gait"],
    ["dance_street", "街頭帶舞性", "street dance-like", "舞、轉、街頭", "dance, turn, street", "街頭質感的轉身帶弧", "with street grit, arced dance turns", "street-cast, dance-like gait"],
    ["dance_noir", "暗黑帶舞性", "noir dance-like", "舞、轉、暗黑", "dance, turn, noir", "暗調電影感的轉身帶弧", "in noir lighting, arced dance turns", "noir, dance-like gait"],
    ["dance_soft", "柔光帶舞性", "soft-light dance-like", "舞、轉、柔光", "dance, turn, soft", "柔光下的轉身帶弧", "under soft light, arced dance turns", "soft-lit, dance-like gait"],
    ["dance_epic", "史詩帶舞性", "epic dance-like", "舞、轉、史詩", "dance, turn, epic", "史詩尺度的轉身帶弧", "at epic scale, arced dance turns", "epic, dance-like gait"],
    ["stiff_court", "宮廷僵直", "court stiff", "僵、控、宮廷", "stiff, control, courtly", "宮廷氣場下的膝踝偏僵", "in a courtly register, stiff knees", "courtly, stiff gait"],
    ["stiff_street", "街頭僵直", "street stiff", "僵、控、街頭", "stiff, control, street", "街頭質感的膝踝偏僵", "with street grit, stiff knees", "street-cast, stiff gait"],
    ["stiff_noir", "暗黑僵直", "noir stiff", "僵、控、暗黑", "stiff, control, noir", "暗調電影感的膝踝偏僵", "in noir lighting, stiff knees", "noir, stiff gait"],
    ["stiff_soft", "柔光僵直", "soft-light stiff", "僵、控、柔光", "stiff, control, soft", "柔光下的膝踝偏僵", "under soft light, stiff knees", "soft-lit, stiff gait"],
    ["stiff_epic", "史詩僵直", "epic stiff", "僵、控、史詩", "stiff, control, epic", "史詩尺度的膝踝偏僵", "at epic scale, stiff knees", "epic, stiff gait"]
  ],
    hands: [
    ["pockets_court", "宮廷常插袋", "court pockets", "袋、藏、宮廷", "pockets, hide, courtly", "宮廷氣場下的手常在袋", "in a courtly register, hands in pockets", "courtly, hands in pockets"],
    ["pockets_street", "街頭常插袋", "street pockets", "袋、藏、街頭", "pockets, hide, street", "街頭質感的手常在袋", "with street grit, hands in pockets", "street-cast, hands in pockets"],
    ["pockets_noir", "暗黑常插袋", "noir pockets", "袋、藏、暗黑", "pockets, hide, noir", "暗調電影感的手常在袋", "in noir lighting, hands in pockets", "noir, hands in pockets"],
    ["pockets_soft", "柔光常插袋", "soft-light pockets", "袋、藏、柔光", "pockets, hide, soft", "柔光下的手常在袋", "under soft light, hands in pockets", "soft-lit, hands in pockets"],
    ["pockets_epic", "史詩常插袋", "epic pockets", "袋、藏、史詩", "pockets, hide, epic", "史詩尺度的手常在袋", "at epic scale, hands in pockets", "epic, hands in pockets"],
    ["still_court", "宮廷極靜", "court still", "靜、控、宮廷", "still, control, courtly", "宮廷氣場下的手很少動", "in a courtly register, rarely moving hands", "courtly, very still hands"],
    ["still_street", "街頭極靜", "street still", "靜、控、街頭", "still, control, street", "街頭質感的手很少動", "with street grit, rarely moving hands", "street-cast, very still hands"],
    ["still_noir", "暗黑極靜", "noir still", "靜、控、暗黑", "still, control, noir", "暗調電影感的手很少動", "in noir lighting, rarely moving hands", "noir, very still hands"],
    ["still_soft", "柔光極靜", "soft-light still", "靜、控、柔光", "still, control, soft", "柔光下的手很少動", "under soft light, rarely moving hands", "soft-lit, very still hands"],
    ["still_epic", "史詩極靜", "epic still", "靜、控、史詩", "still, control, epic", "史詩尺度的手很少動", "at epic scale, rarely moving hands", "epic, very still hands"],
    ["talk_court", "宮廷說話揮", "court talking hands", "揮、述、宮廷", "gesture, narrate, courtly", "宮廷氣場下的邊說邊比", "in a courtly register, gestures while talking", "courtly, talking-hand gestures"],
    ["talk_street", "街頭說話揮", "street talking hands", "揮、述、街頭", "gesture, narrate, street", "街頭質感的邊說邊比", "with street grit, gestures while talking", "street-cast, talking-hand gestures"],
    ["talk_noir", "暗黑說話揮", "noir talking hands", "揮、述、暗黑", "gesture, narrate, noir", "暗調電影感的邊說邊比", "in noir lighting, gestures while talking", "noir, talking-hand gestures"],
    ["talk_soft", "柔光說話揮", "soft-light talking hands", "揮、述、柔光", "gesture, narrate, soft", "柔光下的邊說邊比", "under soft light, gestures while talking", "soft-lit, talking-hand gestures"],
    ["talk_epic", "史詩說話揮", "epic talking hands", "揮、述、史詩", "gesture, narrate, epic", "史詩尺度的邊說邊比", "at epic scale, gestures while talking", "epic, talking-hand gestures"],
    ["fidget_ring_court", "宮廷轉戒", "court ring fidget", "戒、躁、宮廷", "ring, fidget, courtly", "宮廷氣場下的轉戒指", "in a courtly register, turns a ring", "courtly, ring-fidget hands"],
    ["fidget_ring_street", "街頭轉戒", "street ring fidget", "戒、躁、街頭", "ring, fidget, street", "街頭質感的轉戒指", "with street grit, turns a ring", "street-cast, ring-fidget hands"],
    ["fidget_ring_noir", "暗黑轉戒", "noir ring fidget", "戒、躁、暗黑", "ring, fidget, noir", "暗調電影感的轉戒指", "in noir lighting, turns a ring", "noir, ring-fidget hands"],
    ["fidget_ring_soft", "柔光轉戒", "soft-light ring fidget", "戒、躁、柔光", "ring, fidget, soft", "柔光下的轉戒指", "under soft light, turns a ring", "soft-lit, ring-fidget hands"],
    ["fidget_ring_epic", "史詩轉戒", "epic ring fidget", "戒、躁、史詩", "ring, fidget, epic", "史詩尺度的轉戒指", "at epic scale, turns a ring", "epic, ring-fidget hands"],
    ["fist_court", "宮廷易握拳", "court easy fists", "拳、壓、宮廷", "fist, press, courtly", "宮廷氣場下的情緒握拳", "in a courtly register, fists when tense", "courtly, easy fists"],
    ["fist_street", "街頭易握拳", "street easy fists", "拳、壓、街頭", "fist, press, street", "街頭質感的情緒握拳", "with street grit, fists when tense", "street-cast, easy fists"],
    ["fist_noir", "暗黑易握拳", "noir easy fists", "拳、壓、暗黑", "fist, press, noir", "暗調電影感的情緒握拳", "in noir lighting, fists when tense", "noir, easy fists"],
    ["fist_soft", "柔光易握拳", "soft-light easy fists", "拳、壓、柔光", "fist, press, soft", "柔光下的情緒握拳", "under soft light, fists when tense", "soft-lit, easy fists"],
    ["fist_epic", "史詩易握拳", "epic easy fists", "拳、壓、史詩", "fist, press, epic", "史詩尺度的情緒握拳", "at epic scale, fists when tense", "epic, easy fists"],
    ["sleeves_court", "宮廷藏袖", "court in sleeves", "袖、藏、宮廷", "sleeves, hide, courtly", "宮廷氣場下的手藏袖裡", "in a courtly register, hands in sleeves", "courtly, hands hidden in sleeves"],
    ["sleeves_street", "街頭藏袖", "street in sleeves", "袖、藏、街頭", "sleeves, hide, street", "街頭質感的手藏袖裡", "with street grit, hands in sleeves", "street-cast, hands hidden in sleeves"],
    ["sleeves_noir", "暗黑藏袖", "noir in sleeves", "袖、藏、暗黑", "sleeves, hide, noir", "暗調電影感的手藏袖裡", "in noir lighting, hands in sleeves", "noir, hands hidden in sleeves"],
    ["sleeves_soft", "柔光藏袖", "soft-light in sleeves", "袖、藏、柔光", "sleeves, hide, soft", "柔光下的手藏袖裡", "under soft light, hands in sleeves", "soft-lit, hands hidden in sleeves"],
    ["sleeves_epic", "史詩藏袖", "epic in sleeves", "袖、藏、史詩", "sleeves, hide, epic", "史詩尺度的手藏袖裡", "at epic scale, hands in sleeves", "epic, hands hidden in sleeves"],
    ["touch_face_court", "宮廷碰臉", "court face-touch", "臉、想、宮廷", "face, think, courtly", "宮廷氣場下的思考碰唇或眉", "in a courtly register, touches lip or brow", "courtly, face-touching hands"],
    ["touch_face_street", "街頭碰臉", "street face-touch", "臉、想、街頭", "face, think, street", "街頭質感的思考碰唇或眉", "with street grit, touches lip or brow", "street-cast, face-touching hands"],
    ["touch_face_noir", "暗黑碰臉", "noir face-touch", "臉、想、暗黑", "face, think, noir", "暗調電影感的思考碰唇或眉", "in noir lighting, touches lip or brow", "noir, face-touching hands"],
    ["touch_face_soft", "柔光碰臉", "soft-light face-touch", "臉、想、柔光", "face, think, soft", "柔光下的思考碰唇或眉", "under soft light, touches lip or brow", "soft-lit, face-touching hands"],
    ["touch_face_epic", "史詩碰臉", "epic face-touch", "臉、想、史詩", "face, think, epic", "史詩尺度的思考碰唇或眉", "at epic scale, touches lip or brow", "epic, face-touching hands"],
    ["precise_court", "宮廷精準小", "court precise small", "準、小、宮廷", "precise, small, courtly", "宮廷氣場下的小而準的手", "in a courtly register, small precise motions", "courtly, precise small hands"],
    ["precise_street", "街頭精準小", "street precise small", "準、小、街頭", "precise, small, street", "街頭質感的小而準的手", "with street grit, small precise motions", "street-cast, precise small hands"],
    ["precise_noir", "暗黑精準小", "noir precise small", "準、小、暗黑", "precise, small, noir", "暗調電影感的小而準的手", "in noir lighting, small precise motions", "noir, precise small hands"],
    ["precise_soft", "柔光精準小", "soft-light precise small", "準、小、柔光", "precise, small, soft", "柔光下的小而準的手", "under soft light, small precise motions", "soft-lit, precise small hands"],
    ["precise_epic", "史詩精準小", "epic precise small", "準、小、史詩", "precise, small, epic", "史詩尺度的小而準的手", "at epic scale, small precise motions", "epic, precise small hands"],
    ["weapon_rest_court", "宮廷如按劍", "court weapon-rest", "劍、備、宮廷", "blade, ready, courtly", "宮廷氣場下的手常按腰側", "in a courtly register, hand at hip as if armed", "courtly, weapon-rest hand"],
    ["weapon_rest_street", "街頭如按劍", "street weapon-rest", "劍、備、街頭", "blade, ready, street", "街頭質感的手常按腰側", "with street grit, hand at hip as if armed", "street-cast, weapon-rest hand"],
    ["weapon_rest_noir", "暗黑如按劍", "noir weapon-rest", "劍、備、暗黑", "blade, ready, noir", "暗調電影感的手常按腰側", "in noir lighting, hand at hip as if armed", "noir, weapon-rest hand"],
    ["weapon_rest_soft", "柔光如按劍", "soft-light weapon-rest", "劍、備、柔光", "blade, ready, soft", "柔光下的手常按腰側", "under soft light, hand at hip as if armed", "soft-lit, weapon-rest hand"],
    ["weapon_rest_epic", "史詩如按劍", "epic weapon-rest", "劍、備、史詩", "blade, ready, epic", "史詩尺度的手常按腰側", "at epic scale, hand at hip as if armed", "epic, weapon-rest hand"],
    ["open_palm_court", "宮廷常攤掌", "court open palms", "攤、真、宮廷", "open, honest, courtly", "宮廷氣場下的說話攤掌", "in a courtly register, open palms when speaking", "courtly, open-palm hands"],
    ["open_palm_street", "街頭常攤掌", "street open palms", "攤、真、街頭", "open, honest, street", "街頭質感的說話攤掌", "with street grit, open palms when speaking", "street-cast, open-palm hands"],
    ["open_palm_noir", "暗黑常攤掌", "noir open palms", "攤、真、暗黑", "open, honest, noir", "暗調電影感的說話攤掌", "in noir lighting, open palms when speaking", "noir, open-palm hands"],
    ["open_palm_soft", "柔光常攤掌", "soft-light open palms", "攤、真、柔光", "open, honest, soft", "柔光下的說話攤掌", "under soft light, open palms when speaking", "soft-lit, open-palm hands"],
    ["open_palm_epic", "史詩常攤掌", "epic open palms", "攤、真、史詩", "open, honest, epic", "史詩尺度的說話攤掌", "at epic scale, open palms when speaking", "epic, open-palm hands"]
  ],
    gaze: [
    ["direct_court", "宮廷直視", "court direct", "直、壓、宮廷", "direct, press, courtly", "宮廷氣場下的對視不避", "in a courtly register, holds eye contact", "courtly, direct unwavering gaze"],
    ["direct_street", "街頭直視", "street direct", "直、壓、街頭", "direct, press, street", "街頭質感的對視不避", "with street grit, holds eye contact", "street-cast, direct unwavering gaze"],
    ["direct_noir", "暗黑直視", "noir direct", "直、壓、暗黑", "direct, press, noir", "暗調電影感的對視不避", "in noir lighting, holds eye contact", "noir, direct unwavering gaze"],
    ["direct_soft", "柔光直視", "soft-light direct", "直、壓、柔光", "direct, press, soft", "柔光下的對視不避", "under soft light, holds eye contact", "soft-lit, direct unwavering gaze"],
    ["direct_epic", "史詩直視", "epic direct", "直、壓、史詩", "direct, press, epic", "史詩尺度的對視不避", "at epic scale, holds eye contact", "epic, direct unwavering gaze"],
    ["avoid_court", "宮廷避開", "court avoiding", "避、軟、宮廷", "avoid, soft, courtly", "宮廷氣場下的常避開對視", "in a courtly register, avoids eye contact", "courtly, avoiding gaze"],
    ["avoid_street", "街頭避開", "street avoiding", "避、軟、街頭", "avoid, soft, street", "街頭質感的常避開對視", "with street grit, avoids eye contact", "street-cast, avoiding gaze"],
    ["avoid_noir", "暗黑避開", "noir avoiding", "避、軟、暗黑", "avoid, soft, noir", "暗調電影感的常避開對視", "in noir lighting, avoids eye contact", "noir, avoiding gaze"],
    ["avoid_soft", "柔光避開", "soft-light avoiding", "避、軟、柔光", "avoid, soft, soft", "柔光下的常避開對視", "under soft light, avoids eye contact", "soft-lit, avoiding gaze"],
    ["avoid_epic", "史詩避開", "epic avoiding", "避、軟、史詩", "avoid, soft, epic", "史詩尺度的常避開對視", "at epic scale, avoids eye contact", "epic, avoiding gaze"],
    ["down_court", "宮廷下視", "court downcast", "下、思、宮廷", "down, think, courtly", "宮廷氣場下的視線偏低", "in a courtly register, eyes often down", "courtly, downcast gaze"],
    ["down_street", "街頭下視", "street downcast", "下、思、街頭", "down, think, street", "街頭質感的視線偏低", "with street grit, eyes often down", "street-cast, downcast gaze"],
    ["down_noir", "暗黑下視", "noir downcast", "下、思、暗黑", "down, think, noir", "暗調電影感的視線偏低", "in noir lighting, eyes often down", "noir, downcast gaze"],
    ["down_soft", "柔光下視", "soft-light downcast", "下、思、柔光", "down, think, soft", "柔光下的視線偏低", "under soft light, eyes often down", "soft-lit, downcast gaze"],
    ["down_epic", "史詩下視", "epic downcast", "下、思、史詩", "down, think, epic", "史詩尺度的視線偏低", "at epic scale, eyes often down", "epic, downcast gaze"],
    ["scan_court", "宮廷掃描", "court scanning", "掃、警、宮廷", "scan, alert, courtly", "宮廷氣場下的不停掃場", "in a courtly register, scans the room", "courtly, scanning gaze"],
    ["scan_street", "街頭掃描", "street scanning", "掃、警、街頭", "scan, alert, street", "街頭質感的不停掃場", "with street grit, scans the room", "street-cast, scanning gaze"],
    ["scan_noir", "暗黑掃描", "noir scanning", "掃、警、暗黑", "scan, alert, noir", "暗調電影感的不停掃場", "in noir lighting, scans the room", "noir, scanning gaze"],
    ["scan_soft", "柔光掃描", "soft-light scanning", "掃、警、柔光", "scan, alert, soft", "柔光下的不停掃場", "under soft light, scans the room", "soft-lit, scanning gaze"],
    ["scan_epic", "史詩掃描", "epic scanning", "掃、警、史詩", "scan, alert, epic", "史詩尺度的不停掃場", "at epic scale, scans the room", "epic, scanning gaze"],
    ["half_lid_court", "宮廷半眼皮", "court half-lidded", "半、懶、宮廷", "half, lazy, courtly", "宮廷氣場下的眼皮半掛", "in a courtly register, half-lidded look", "courtly, half-lidded gaze"],
    ["half_lid_street", "街頭半眼皮", "street half-lidded", "半、懶、街頭", "half, lazy, street", "街頭質感的眼皮半掛", "with street grit, half-lidded look", "street-cast, half-lidded gaze"],
    ["half_lid_noir", "暗黑半眼皮", "noir half-lidded", "半、懶、暗黑", "half, lazy, noir", "暗調電影感的眼皮半掛", "in noir lighting, half-lidded look", "noir, half-lidded gaze"],
    ["half_lid_soft", "柔光半眼皮", "soft-light half-lidded", "半、懶、柔光", "half, lazy, soft", "柔光下的眼皮半掛", "under soft light, half-lidded look", "soft-lit, half-lidded gaze"],
    ["half_lid_epic", "史詩半眼皮", "epic half-lidded", "半、懶、史詩", "half, lazy, epic", "史詩尺度的眼皮半掛", "at epic scale, half-lidded look", "epic, half-lidded gaze"],
    ["stare_through_court", "宮廷看穿", "court through-stare", "穿、冷、宮廷", "through, cold, courtly", "宮廷氣場下的像看穿人", "in a courtly register, looks through people", "courtly, through-stare gaze"],
    ["stare_through_street", "街頭看穿", "street through-stare", "穿、冷、街頭", "through, cold, street", "街頭質感的像看穿人", "with street grit, looks through people", "street-cast, through-stare gaze"],
    ["stare_through_noir", "暗黑看穿", "noir through-stare", "穿、冷、暗黑", "through, cold, noir", "暗調電影感的像看穿人", "in noir lighting, looks through people", "noir, through-stare gaze"],
    ["stare_through_soft", "柔光看穿", "soft-light through-stare", "穿、冷、柔光", "through, cold, soft", "柔光下的像看穿人", "under soft light, looks through people", "soft-lit, through-stare gaze"],
    ["stare_through_epic", "史詩看穿", "epic through-stare", "穿、冷、史詩", "through, cold, epic", "史詩尺度的像看穿人", "at epic scale, looks through people", "epic, through-stare gaze"],
    ["flicker_court", "宮廷閃避閃回", "court flicker", "閃、謊、宮廷", "flicker, lie, courtly", "宮廷氣場下的對視閃一下又回", "in a courtly register, flicks away then back", "courtly, flickering gaze"],
    ["flicker_street", "街頭閃避閃回", "street flicker", "閃、謊、街頭", "flicker, lie, street", "街頭質感的對視閃一下又回", "with street grit, flicks away then back", "street-cast, flickering gaze"],
    ["flicker_noir", "暗黑閃避閃回", "noir flicker", "閃、謊、暗黑", "flicker, lie, noir", "暗調電影感的對視閃一下又回", "in noir lighting, flicks away then back", "noir, flickering gaze"],
    ["flicker_soft", "柔光閃避閃回", "soft-light flicker", "閃、謊、柔光", "flicker, lie, soft", "柔光下的對視閃一下又回", "under soft light, flicks away then back", "soft-lit, flickering gaze"],
    ["flicker_epic", "史詩閃避閃回", "epic flicker", "閃、謊、史詩", "flicker, lie, epic", "史詩尺度的對視閃一下又回", "at epic scale, flicks away then back", "epic, flickering gaze"],
    ["soft_focus_court", "宮廷失焦柔", "court soft focus", "柔、遠、宮廷", "soft, far, courtly", "宮廷氣場下的焦點偏遠", "in a courtly register, focus slightly far", "courtly, soft-focus gaze"],
    ["soft_focus_street", "街頭失焦柔", "street soft focus", "柔、遠、街頭", "soft, far, street", "街頭質感的焦點偏遠", "with street grit, focus slightly far", "street-cast, soft-focus gaze"],
    ["soft_focus_noir", "暗黑失焦柔", "noir soft focus", "柔、遠、暗黑", "soft, far, noir", "暗調電影感的焦點偏遠", "in noir lighting, focus slightly far", "noir, soft-focus gaze"],
    ["soft_focus_soft", "柔光失焦柔", "soft-light soft focus", "柔、遠、柔光", "soft, far, soft", "柔光下的焦點偏遠", "under soft light, focus slightly far", "soft-lit, soft-focus gaze"],
    ["soft_focus_epic", "史詩失焦柔", "epic soft focus", "柔、遠、史詩", "soft, far, epic", "史詩尺度的焦點偏遠", "at epic scale, focus slightly far", "epic, soft-focus gaze"],
    ["predatory_court", "宮廷捕食", "court predatory", "捕食、鎖、宮廷", "prey, lock, courtly", "宮廷氣場下的鎖定獵物般", "in a courtly register, locks like prey-sight", "courtly, predatory gaze"],
    ["predatory_street", "街頭捕食", "street predatory", "捕食、鎖、街頭", "prey, lock, street", "街頭質感的鎖定獵物般", "with street grit, locks like prey-sight", "street-cast, predatory gaze"],
    ["predatory_noir", "暗黑捕食", "noir predatory", "捕食、鎖、暗黑", "prey, lock, noir", "暗調電影感的鎖定獵物般", "in noir lighting, locks like prey-sight", "noir, predatory gaze"],
    ["predatory_soft", "柔光捕食", "soft-light predatory", "捕食、鎖、柔光", "prey, lock, soft", "柔光下的鎖定獵物般", "under soft light, locks like prey-sight", "soft-lit, predatory gaze"],
    ["predatory_epic", "史詩捕食", "epic predatory", "捕食、鎖、史詩", "prey, lock, epic", "史詩尺度的鎖定獵物般", "at epic scale, locks like prey-sight", "epic, predatory gaze"],
    ["wet_court", "宮廷水光易濕", "court wet-eyed", "濕、感、宮廷", "wet, feel, courtly", "宮廷氣場下的眼易濕", "in a courtly register, eyes wet easily", "courtly, wet-eyed gaze"],
    ["wet_street", "街頭水光易濕", "street wet-eyed", "濕、感、街頭", "wet, feel, street", "街頭質感的眼易濕", "with street grit, eyes wet easily", "street-cast, wet-eyed gaze"],
    ["wet_noir", "暗黑水光易濕", "noir wet-eyed", "濕、感、暗黑", "wet, feel, noir", "暗調電影感的眼易濕", "in noir lighting, eyes wet easily", "noir, wet-eyed gaze"],
    ["wet_soft", "柔光水光易濕", "soft-light wet-eyed", "濕、感、柔光", "wet, feel, soft", "柔光下的眼易濕", "under soft light, eyes wet easily", "soft-lit, wet-eyed gaze"],
    ["wet_epic", "史詩水光易濕", "epic wet-eyed", "濕、感、史詩", "wet, feel, epic", "史詩尺度的眼易濕", "at epic scale, eyes wet easily", "epic, wet-eyed gaze"]
  ],
    speech: [
    ["short_court", "宮廷極短句", "court short lines", "短、砍、宮廷", "short, cut, courtly", "宮廷氣場下的很少長句", "in a courtly register, rarely long sentences", "courtly, very short speech"],
    ["short_street", "街頭極短句", "street short lines", "短、砍、街頭", "short, cut, street", "街頭質感的很少長句", "with street grit, rarely long sentences", "street-cast, very short speech"],
    ["short_noir", "暗黑極短句", "noir short lines", "短、砍、暗黑", "short, cut, noir", "暗調電影感的很少長句", "in noir lighting, rarely long sentences", "noir, very short speech"],
    ["short_soft", "柔光極短句", "soft-light short lines", "短、砍、柔光", "short, cut, soft", "柔光下的很少長句", "under soft light, rarely long sentences", "soft-lit, very short speech"],
    ["short_epic", "史詩極短句", "epic short lines", "短、砍、史詩", "short, cut, epic", "史詩尺度的很少長句", "at epic scale, rarely long sentences", "epic, very short speech"],
    ["polite_court", "宮廷過禮", "court over-polite", "禮、距、宮廷", "polite, distance, courtly", "宮廷氣場下的過度禮貌", "in a courtly register, excessively polite", "courtly, over-polite speech"],
    ["polite_street", "街頭過禮", "street over-polite", "禮、距、街頭", "polite, distance, street", "街頭質感的過度禮貌", "with street grit, excessively polite", "street-cast, over-polite speech"],
    ["polite_noir", "暗黑過禮", "noir over-polite", "禮、距、暗黑", "polite, distance, noir", "暗調電影感的過度禮貌", "in noir lighting, excessively polite", "noir, over-polite speech"],
    ["polite_soft", "柔光過禮", "soft-light over-polite", "禮、距、柔光", "polite, distance, soft", "柔光下的過度禮貌", "under soft light, excessively polite", "soft-lit, over-polite speech"],
    ["polite_epic", "史詩過禮", "epic over-polite", "禮、距、史詩", "polite, distance, epic", "史詩尺度的過度禮貌", "at epic scale, excessively polite", "epic, over-polite speech"],
    ["tease_court", "宮廷愛嘲", "court teasing", "嘲、鉤、宮廷", "tease, hook, courtly", "宮廷氣場下的帶刺調侃", "in a courtly register, barbed teasing", "courtly, teasing speech habit"],
    ["tease_street", "街頭愛嘲", "street teasing", "嘲、鉤、街頭", "tease, hook, street", "街頭質感的帶刺調侃", "with street grit, barbed teasing", "street-cast, teasing speech habit"],
    ["tease_noir", "暗黑愛嘲", "noir teasing", "嘲、鉤、暗黑", "tease, hook, noir", "暗調電影感的帶刺調侃", "in noir lighting, barbed teasing", "noir, teasing speech habit"],
    ["tease_soft", "柔光愛嘲", "soft-light teasing", "嘲、鉤、柔光", "tease, hook, soft", "柔光下的帶刺調侃", "under soft light, barbed teasing", "soft-lit, teasing speech habit"],
    ["tease_epic", "史詩愛嘲", "epic teasing", "嘲、鉤、史詩", "tease, hook, epic", "史詩尺度的帶刺調侃", "at epic scale, barbed teasing", "epic, teasing speech habit"],
    ["repeat_court", "宮廷重複關鍵", "court repeats key", "重複、釘、宮廷", "repeat, pin, courtly", "宮廷氣場下的重複關鍵詞", "in a courtly register, repeats key words", "courtly, key-word repetition"],
    ["repeat_street", "街頭重複關鍵", "street repeats key", "重複、釘、街頭", "repeat, pin, street", "街頭質感的重複關鍵詞", "with street grit, repeats key words", "street-cast, key-word repetition"],
    ["repeat_noir", "暗黑重複關鍵", "noir repeats key", "重複、釘、暗黑", "repeat, pin, noir", "暗調電影感的重複關鍵詞", "in noir lighting, repeats key words", "noir, key-word repetition"],
    ["repeat_soft", "柔光重複關鍵", "soft-light repeats key", "重複、釘、柔光", "repeat, pin, soft", "柔光下的重複關鍵詞", "under soft light, repeats key words", "soft-lit, key-word repetition"],
    ["repeat_epic", "史詩重複關鍵", "epic repeats key", "重複、釘、史詩", "repeat, pin, epic", "史詩尺度的重複關鍵詞", "at epic scale, repeats key words", "epic, key-word repetition"],
    ["trail_court", "宮廷說一半", "court trails off", "半、吞、宮廷", "trail, swallow, courtly", "宮廷氣場下的常說一半", "in a courtly register, often trails off", "courtly, trailing-off speech"],
    ["trail_street", "街頭說一半", "street trails off", "半、吞、街頭", "trail, swallow, street", "街頭質感的常說一半", "with street grit, often trails off", "street-cast, trailing-off speech"],
    ["trail_noir", "暗黑說一半", "noir trails off", "半、吞、暗黑", "trail, swallow, noir", "暗調電影感的常說一半", "in noir lighting, often trails off", "noir, trailing-off speech"],
    ["trail_soft", "柔光說一半", "soft-light trails off", "半、吞、柔光", "trail, swallow, soft", "柔光下的常說一半", "under soft light, often trails off", "soft-lit, trailing-off speech"],
    ["trail_epic", "史詩說一半", "epic trails off", "半、吞、史詩", "trail, swallow, epic", "史詩尺度的常說一半", "at epic scale, often trails off", "epic, trailing-off speech"],
    ["formal_court", "宮廷書面", "court formal", "書面、古、宮廷", "formal, literary, courtly", "宮廷氣場下的偏書面", "in a courtly register, literary formal", "courtly, formal speech"],
    ["formal_street", "街頭書面", "street formal", "書面、古、街頭", "formal, literary, street", "街頭質感的偏書面", "with street grit, literary formal", "street-cast, formal speech"],
    ["formal_noir", "暗黑書面", "noir formal", "書面、古、暗黑", "formal, literary, noir", "暗調電影感的偏書面", "in noir lighting, literary formal", "noir, formal speech"],
    ["formal_soft", "柔光書面", "soft-light formal", "書面、古、柔光", "formal, literary, soft", "柔光下的偏書面", "under soft light, literary formal", "soft-lit, formal speech"],
    ["formal_epic", "史詩書面", "epic formal", "書面、古、史詩", "formal, literary, epic", "史詩尺度的偏書面", "at epic scale, literary formal", "epic, formal speech"],
    ["slang_court", "宮廷口語髒", "court slangy", "俗、快、宮廷", "slang, fast, courtly", "宮廷氣場下的口語多", "in a courtly register, lots of slang", "courtly, slangy speech"],
    ["slang_street", "街頭口語髒", "street slangy", "俗、快、街頭", "slang, fast, street", "街頭質感的口語多", "with street grit, lots of slang", "street-cast, slangy speech"],
    ["slang_noir", "暗黑口語髒", "noir slangy", "俗、快、暗黑", "slang, fast, noir", "暗調電影感的口語多", "in noir lighting, lots of slang", "noir, slangy speech"],
    ["slang_soft", "柔光口語髒", "soft-light slangy", "俗、快、柔光", "slang, fast, soft", "柔光下的口語多", "under soft light, lots of slang", "soft-lit, slangy speech"],
    ["slang_epic", "史詩口語髒", "epic slangy", "俗、快、史詩", "slang, fast, epic", "史詩尺度的口語多", "at epic scale, lots of slang", "epic, slangy speech"],
    ["question_court", "宮廷反問多", "court questions", "問、推、宮廷", "question, push, courtly", "宮廷氣場下的常用反問", "in a courtly register, often questions back", "courtly, questioning speech"],
    ["question_street", "街頭反問多", "street questions", "問、推、街頭", "question, push, street", "街頭質感的常用反問", "with street grit, often questions back", "street-cast, questioning speech"],
    ["question_noir", "暗黑反問多", "noir questions", "問、推、暗黑", "question, push, noir", "暗調電影感的常用反問", "in noir lighting, often questions back", "noir, questioning speech"],
    ["question_soft", "柔光反問多", "soft-light questions", "問、推、柔光", "question, push, soft", "柔光下的常用反問", "under soft light, often questions back", "soft-lit, questioning speech"],
    ["question_epic", "史詩反問多", "epic questions", "問、推、史詩", "question, push, epic", "史詩尺度的常用反問", "at epic scale, often questions back", "epic, questioning speech"],
    ["silent_court", "宮廷能不說就不說", "court silent-first", "默、省、宮廷", "silent, spare, courtly", "宮廷氣場下的先沉默", "in a courtly register, silence first", "courtly, silent-first habit"],
    ["silent_street", "街頭能不說就不說", "street silent-first", "默、省、街頭", "silent, spare, street", "街頭質感的先沉默", "with street grit, silence first", "street-cast, silent-first habit"],
    ["silent_noir", "暗黑能不說就不說", "noir silent-first", "默、省、暗黑", "silent, spare, noir", "暗調電影感的先沉默", "in noir lighting, silence first", "noir, silent-first habit"],
    ["silent_soft", "柔光能不說就不說", "soft-light silent-first", "默、省、柔光", "silent, spare, soft", "柔光下的先沉默", "under soft light, silence first", "soft-lit, silent-first habit"],
    ["silent_epic", "史詩能不說就不說", "epic silent-first", "默、省、史詩", "silent, spare, epic", "史詩尺度的先沉默", "at epic scale, silence first", "epic, silent-first habit"],
    ["narrate_court", "宮廷自言", "court self-narrate", "自言、戲、宮廷", "narrate, play, courtly", "宮廷氣場下的偶爾自語", "in a courtly register, occasional self-talk", "courtly, self-narrating speech"],
    ["narrate_street", "街頭自言", "street self-narrate", "自言、戲、街頭", "narrate, play, street", "街頭質感的偶爾自語", "with street grit, occasional self-talk", "street-cast, self-narrating speech"],
    ["narrate_noir", "暗黑自言", "noir self-narrate", "自言、戲、暗黑", "narrate, play, noir", "暗調電影感的偶爾自語", "in noir lighting, occasional self-talk", "noir, self-narrating speech"],
    ["narrate_soft", "柔光自言", "soft-light self-narrate", "自言、戲、柔光", "narrate, play, soft", "柔光下的偶爾自語", "under soft light, occasional self-talk", "soft-lit, self-narrating speech"],
    ["narrate_epic", "史詩自言", "epic self-narrate", "自言、戲、史詩", "narrate, play, epic", "史詩尺度的偶爾自語", "at epic scale, occasional self-talk", "epic, self-narrating speech"]
  ],
    posture: [
    ["upright_court", "宮廷極直", "court upright", "直、禮、宮廷", "upright, formal, courtly", "宮廷氣場下的背極直", "in a courtly register, very straight back", "courtly, upright posture"],
    ["upright_street", "街頭極直", "street upright", "直、禮、街頭", "upright, formal, street", "街頭質感的背極直", "with street grit, very straight back", "street-cast, upright posture"],
    ["upright_noir", "暗黑極直", "noir upright", "直、禮、暗黑", "upright, formal, noir", "暗調電影感的背極直", "in noir lighting, very straight back", "noir, upright posture"],
    ["upright_soft", "柔光極直", "soft-light upright", "直、禮、柔光", "upright, formal, soft", "柔光下的背極直", "under soft light, very straight back", "soft-lit, upright posture"],
    ["upright_epic", "史詩極直", "epic upright", "直、禮、史詩", "upright, formal, epic", "史詩尺度的背極直", "at epic scale, very straight back", "epic, upright posture"],
    ["slouch_court", "宮廷微塌", "court slouch", "塌、散、宮廷", "slouch, loose, courtly", "宮廷氣場下的肩微塌", "in a courtly register, slight slouch", "courtly, slouched posture"],
    ["slouch_street", "街頭微塌", "street slouch", "塌、散、街頭", "slouch, loose, street", "街頭質感的肩微塌", "with street grit, slight slouch", "street-cast, slouched posture"],
    ["slouch_noir", "暗黑微塌", "noir slouch", "塌、散、暗黑", "slouch, loose, noir", "暗調電影感的肩微塌", "in noir lighting, slight slouch", "noir, slouched posture"],
    ["slouch_soft", "柔光微塌", "soft-light slouch", "塌、散、柔光", "slouch, loose, soft", "柔光下的肩微塌", "under soft light, slight slouch", "soft-lit, slouched posture"],
    ["slouch_epic", "史詩微塌", "epic slouch", "塌、散、史詩", "slouch, loose, epic", "史詩尺度的肩微塌", "at epic scale, slight slouch", "epic, slouched posture"],
    ["lean_wall_court", "宮廷愛靠", "court leaning", "靠、懶、宮廷", "lean, lazy, courtly", "宮廷氣場下的常靠牆或桌", "in a courtly register, leans on walls", "courtly, leaning posture"],
    ["lean_wall_street", "街頭愛靠", "street leaning", "靠、懶、街頭", "lean, lazy, street", "街頭質感的常靠牆或桌", "with street grit, leans on walls", "street-cast, leaning posture"],
    ["lean_wall_noir", "暗黑愛靠", "noir leaning", "靠、懶、暗黑", "lean, lazy, noir", "暗調電影感的常靠牆或桌", "in noir lighting, leans on walls", "noir, leaning posture"],
    ["lean_wall_soft", "柔光愛靠", "soft-light leaning", "靠、懶、柔光", "lean, lazy, soft", "柔光下的常靠牆或桌", "under soft light, leans on walls", "soft-lit, leaning posture"],
    ["lean_wall_epic", "史詩愛靠", "epic leaning", "靠、懶、史詩", "lean, lazy, epic", "史詩尺度的常靠牆或桌", "at epic scale, leans on walls", "epic, leaning posture"],
    ["closed_court", "宮廷雙臂收", "court closed", "收、防、宮廷", "closed, guard, courtly", "宮廷氣場下的手臂常收", "in a courtly register, arms often closed", "courtly, closed posture"],
    ["closed_street", "街頭雙臂收", "street closed", "收、防、街頭", "closed, guard, street", "街頭質感的手臂常收", "with street grit, arms often closed", "street-cast, closed posture"],
    ["closed_noir", "暗黑雙臂收", "noir closed", "收、防、暗黑", "closed, guard, noir", "暗調電影感的手臂常收", "in noir lighting, arms often closed", "noir, closed posture"],
    ["closed_soft", "柔光雙臂收", "soft-light closed", "收、防、柔光", "closed, guard, soft", "柔光下的手臂常收", "under soft light, arms often closed", "soft-lit, closed posture"],
    ["closed_epic", "史詩雙臂收", "epic closed", "收、防、史詩", "closed, guard, epic", "史詩尺度的手臂常收", "at epic scale, arms often closed", "epic, closed posture"],
    ["open_chest_court", "宮廷開胸", "court open chest", "開、佔、宮廷", "open, occupy, courtly", "宮廷氣場下的胸打開", "in a courtly register, open chest", "courtly, open-chest posture"],
    ["open_chest_street", "街頭開胸", "street open chest", "開、佔、街頭", "open, occupy, street", "街頭質感的胸打開", "with street grit, open chest", "street-cast, open-chest posture"],
    ["open_chest_noir", "暗黑開胸", "noir open chest", "開、佔、暗黑", "open, occupy, noir", "暗調電影感的胸打開", "in noir lighting, open chest", "noir, open-chest posture"],
    ["open_chest_soft", "柔光開胸", "soft-light open chest", "開、佔、柔光", "open, occupy, soft", "柔光下的胸打開", "under soft light, open chest", "soft-lit, open-chest posture"],
    ["open_chest_epic", "史詩開胸", "epic open chest", "開、佔、史詩", "open, occupy, epic", "史詩尺度的胸打開", "at epic scale, open chest", "epic, open-chest posture"],
    ["head_tilt_court", "宮廷歪頭", "court head tilt", "歪、探、宮廷", "tilt, probe, courtly", "宮廷氣場下的思考歪頭", "in a courtly register, tilts head to think", "courtly, head-tilt posture"],
    ["head_tilt_street", "街頭歪頭", "street head tilt", "歪、探、街頭", "tilt, probe, street", "街頭質感的思考歪頭", "with street grit, tilts head to think", "street-cast, head-tilt posture"],
    ["head_tilt_noir", "暗黑歪頭", "noir head tilt", "歪、探、暗黑", "tilt, probe, noir", "暗調電影感的思考歪頭", "in noir lighting, tilts head to think", "noir, head-tilt posture"],
    ["head_tilt_soft", "柔光歪頭", "soft-light head tilt", "歪、探、柔光", "tilt, probe, soft", "柔光下的思考歪頭", "under soft light, tilts head to think", "soft-lit, head-tilt posture"],
    ["head_tilt_epic", "史詩歪頭", "epic head tilt", "歪、探、史詩", "tilt, probe, epic", "史詩尺度的思考歪頭", "at epic scale, tilts head to think", "epic, head-tilt posture"],
    ["chin_high_court", "宮廷頦抬", "court high chin", "抬、傲、宮廷", "chin, pride, courtly", "宮廷氣場下的下巴微抬", "in a courtly register, chin slightly high", "courtly, high-chin posture"],
    ["chin_high_street", "街頭頦抬", "street high chin", "抬、傲、街頭", "chin, pride, street", "街頭質感的下巴微抬", "with street grit, chin slightly high", "street-cast, high-chin posture"],
    ["chin_high_noir", "暗黑頦抬", "noir high chin", "抬、傲、暗黑", "chin, pride, noir", "暗調電影感的下巴微抬", "in noir lighting, chin slightly high", "noir, high-chin posture"],
    ["chin_high_soft", "柔光頦抬", "soft-light high chin", "抬、傲、柔光", "chin, pride, soft", "柔光下的下巴微抬", "under soft light, chin slightly high", "soft-lit, high-chin posture"],
    ["chin_high_epic", "史詩頦抬", "epic high chin", "抬、傲、史詩", "chin, pride, epic", "史詩尺度的下巴微抬", "at epic scale, chin slightly high", "epic, high-chin posture"],
    ["ready_stance_court", "宮廷隨時可動", "court ready stance", "備、戰、宮廷", "ready, fight, courtly", "宮廷氣場下的重心可瞬間動", "in a courtly register, weight ready to move", "courtly, ready-stance posture"],
    ["ready_stance_street", "街頭隨時可動", "street ready stance", "備、戰、街頭", "ready, fight, street", "街頭質感的重心可瞬間動", "with street grit, weight ready to move", "street-cast, ready-stance posture"],
    ["ready_stance_noir", "暗黑隨時可動", "noir ready stance", "備、戰、暗黑", "ready, fight, noir", "暗調電影感的重心可瞬間動", "in noir lighting, weight ready to move", "noir, ready-stance posture"],
    ["ready_stance_soft", "柔光隨時可動", "soft-light ready stance", "備、戰、柔光", "ready, fight, soft", "柔光下的重心可瞬間動", "under soft light, weight ready to move", "soft-lit, ready-stance posture"],
    ["ready_stance_epic", "史詩隨時可動", "epic ready stance", "備、戰、史詩", "ready, fight, epic", "史詩尺度的重心可瞬間動", "at epic scale, weight ready to move", "epic, ready-stance posture"],
    ["fold_small_court", "宮廷把自己折小", "court folded small", "小、藏、宮廷", "small, hide, courtly", "宮廷氣場下的坐站都收細", "in a courtly register, makes self smaller", "courtly, folded-small posture"],
    ["fold_small_street", "街頭把自己折小", "street folded small", "小、藏、街頭", "small, hide, street", "街頭質感的坐站都收細", "with street grit, makes self smaller", "street-cast, folded-small posture"],
    ["fold_small_noir", "暗黑把自己折小", "noir folded small", "小、藏、暗黑", "small, hide, noir", "暗調電影感的坐站都收細", "in noir lighting, makes self smaller", "noir, folded-small posture"],
    ["fold_small_soft", "柔光把自己折小", "soft-light folded small", "小、藏、柔光", "small, hide, soft", "柔光下的坐站都收細", "under soft light, makes self smaller", "soft-lit, folded-small posture"],
    ["fold_small_epic", "史詩把自己折小", "epic folded small", "小、藏、史詩", "small, hide, epic", "史詩尺度的坐站都收細", "at epic scale, makes self smaller", "epic, folded-small posture"],
    ["one_hip_court", "宮廷單胯", "court weight on one hip", "胯、鬆、宮廷", "hip, loose, courtly", "宮廷氣場下的重心偏一胯", "in a courtly register, weight on one hip", "courtly, one-hip posture"],
    ["one_hip_street", "街頭單胯", "street weight on one hip", "胯、鬆、街頭", "hip, loose, street", "街頭質感的重心偏一胯", "with street grit, weight on one hip", "street-cast, one-hip posture"],
    ["one_hip_noir", "暗黑單胯", "noir weight on one hip", "胯、鬆、暗黑", "hip, loose, noir", "暗調電影感的重心偏一胯", "in noir lighting, weight on one hip", "noir, one-hip posture"],
    ["one_hip_soft", "柔光單胯", "soft-light weight on one hip", "胯、鬆、柔光", "hip, loose, soft", "柔光下的重心偏一胯", "under soft light, weight on one hip", "soft-lit, one-hip posture"],
    ["one_hip_epic", "史詩單胯", "epic weight on one hip", "胯、鬆、史詩", "hip, loose, epic", "史詩尺度的重心偏一胯", "at epic scale, weight on one hip", "epic, one-hip posture"]
  ],
    tic: [
    ["hair_tuck_court", "宮廷撥髮", "court hair tuck", "髮、隙、宮廷", "hair, beat, courtly", "宮廷氣場下的緊張撥髮", "in a courtly register, tucks hair when tense", "courtly, hair-tuck tic"],
    ["hair_tuck_street", "街頭撥髮", "street hair tuck", "髮、隙、街頭", "hair, beat, street", "街頭質感的緊張撥髮", "with street grit, tucks hair when tense", "street-cast, hair-tuck tic"],
    ["hair_tuck_noir", "暗黑撥髮", "noir hair tuck", "髮、隙、暗黑", "hair, beat, noir", "暗調電影感的緊張撥髮", "in noir lighting, tucks hair when tense", "noir, hair-tuck tic"],
    ["hair_tuck_soft", "柔光撥髮", "soft-light hair tuck", "髮、隙、柔光", "hair, beat, soft", "柔光下的緊張撥髮", "under soft light, tucks hair when tense", "soft-lit, hair-tuck tic"],
    ["hair_tuck_epic", "史詩撥髮", "epic hair tuck", "髮、隙、史詩", "hair, beat, epic", "史詩尺度的緊張撥髮", "at epic scale, tucks hair when tense", "epic, hair-tuck tic"],
    ["lip_court", "宮廷咬唇", "court lip bite", "唇、壓、宮廷", "lip, press, courtly", "宮廷氣場下的輕咬下唇", "in a courtly register, bites lower lip", "courtly, lip-bite tic"],
    ["lip_street", "街頭咬唇", "street lip bite", "唇、壓、街頭", "lip, press, street", "街頭質感的輕咬下唇", "with street grit, bites lower lip", "street-cast, lip-bite tic"],
    ["lip_noir", "暗黑咬唇", "noir lip bite", "唇、壓、暗黑", "lip, press, noir", "暗調電影感的輕咬下唇", "in noir lighting, bites lower lip", "noir, lip-bite tic"],
    ["lip_soft", "柔光咬唇", "soft-light lip bite", "唇、壓、柔光", "lip, press, soft", "柔光下的輕咬下唇", "under soft light, bites lower lip", "soft-lit, lip-bite tic"],
    ["lip_epic", "史詩咬唇", "epic lip bite", "唇、壓、史詩", "lip, press, epic", "史詩尺度的輕咬下唇", "at epic scale, bites lower lip", "epic, lip-bite tic"],
    ["thumb_court", "宮廷轉拇指", "court thumb roll", "拇、想、宮廷", "thumb, think, courtly", "宮廷氣場下的轉拇指", "in a courtly register, rolls a thumb", "courtly, thumb-roll tic"],
    ["thumb_street", "街頭轉拇指", "street thumb roll", "拇、想、街頭", "thumb, think, street", "街頭質感的轉拇指", "with street grit, rolls a thumb", "street-cast, thumb-roll tic"],
    ["thumb_noir", "暗黑轉拇指", "noir thumb roll", "拇、想、暗黑", "thumb, think, noir", "暗調電影感的轉拇指", "in noir lighting, rolls a thumb", "noir, thumb-roll tic"],
    ["thumb_soft", "柔光轉拇指", "soft-light thumb roll", "拇、想、柔光", "thumb, think, soft", "柔光下的轉拇指", "under soft light, rolls a thumb", "soft-lit, thumb-roll tic"],
    ["thumb_epic", "史詩轉拇指", "epic thumb roll", "拇、想、史詩", "thumb, think, epic", "史詩尺度的轉拇指", "at epic scale, rolls a thumb", "epic, thumb-roll tic"],
    ["blink_slow_court", "宮廷慢眨眼", "court slow blink", "眨、冷、宮廷", "blink, cool, courtly", "宮廷氣場下的故意慢眨", "in a courtly register, slow deliberate blink", "courtly, slow-blink tic"],
    ["blink_slow_street", "街頭慢眨眼", "street slow blink", "眨、冷、街頭", "blink, cool, street", "街頭質感的故意慢眨", "with street grit, slow deliberate blink", "street-cast, slow-blink tic"],
    ["blink_slow_noir", "暗黑慢眨眼", "noir slow blink", "眨、冷、暗黑", "blink, cool, noir", "暗調電影感的故意慢眨", "in noir lighting, slow deliberate blink", "noir, slow-blink tic"],
    ["blink_slow_soft", "柔光慢眨眼", "soft-light slow blink", "眨、冷、柔光", "blink, cool, soft", "柔光下的故意慢眨", "under soft light, slow deliberate blink", "soft-lit, slow-blink tic"],
    ["blink_slow_epic", "史詩慢眨眼", "epic slow blink", "眨、冷、史詩", "blink, cool, epic", "史詩尺度的故意慢眨", "at epic scale, slow deliberate blink", "epic, slow-blink tic"],
    ["neck_court", "宮廷扭頸", "court neck crack", "頸、鬆、宮廷", "neck, reset, courtly", "宮廷氣場下的不時扭頸", "in a courtly register, cracks neck often", "courtly, neck-crack tic"],
    ["neck_street", "街頭扭頸", "street neck crack", "頸、鬆、街頭", "neck, reset, street", "街頭質感的不時扭頸", "with street grit, cracks neck often", "street-cast, neck-crack tic"],
    ["neck_noir", "暗黑扭頸", "noir neck crack", "頸、鬆、暗黑", "neck, reset, noir", "暗調電影感的不時扭頸", "in noir lighting, cracks neck often", "noir, neck-crack tic"],
    ["neck_soft", "柔光扭頸", "soft-light neck crack", "頸、鬆、柔光", "neck, reset, soft", "柔光下的不時扭頸", "under soft light, cracks neck often", "soft-lit, neck-crack tic"],
    ["neck_epic", "史詩扭頸", "epic neck crack", "頸、鬆、史詩", "neck, reset, epic", "史詩尺度的不時扭頸", "at epic scale, cracks neck often", "epic, neck-crack tic"],
    ["none_court", "宮廷幾乎無 tic", "court almost none", "無、淨、宮廷", "none, clean, courtly", "宮廷氣場下的少有重複小動作", "in a courtly register, almost no tic", "courtly, almost no tic"],
    ["none_street", "街頭幾乎無 tic", "street almost none", "無、淨、街頭", "none, clean, street", "街頭質感的少有重複小動作", "with street grit, almost no tic", "street-cast, almost no tic"],
    ["none_noir", "暗黑幾乎無 tic", "noir almost none", "無、淨、暗黑", "none, clean, noir", "暗調電影感的少有重複小動作", "in noir lighting, almost no tic", "noir, almost no tic"],
    ["none_soft", "柔光幾乎無 tic", "soft-light almost none", "無、淨、柔光", "none, clean, soft", "柔光下的少有重複小動作", "under soft light, almost no tic", "soft-lit, almost no tic"],
    ["none_epic", "史詩幾乎無 tic", "epic almost none", "無、淨、史詩", "none, clean, epic", "史詩尺度的少有重複小動作", "at epic scale, almost no tic", "epic, almost no tic"],
    ["watch_check_court", "宮廷看錶", "court watch check", "錶、時、宮廷", "watch, time, courtly", "宮廷氣場下的常看腕錶", "in a courtly register, checks a watch", "courtly, watch-check tic"],
    ["watch_check_street", "街頭看錶", "street watch check", "錶、時、街頭", "watch, time, street", "街頭質感的常看腕錶", "with street grit, checks a watch", "street-cast, watch-check tic"],
    ["watch_check_noir", "暗黑看錶", "noir watch check", "錶、時、暗黑", "watch, time, noir", "暗調電影感的常看腕錶", "in noir lighting, checks a watch", "noir, watch-check tic"],
    ["watch_check_soft", "柔光看錶", "soft-light watch check", "錶、時、柔光", "watch, time, soft", "柔光下的常看腕錶", "under soft light, checks a watch", "soft-lit, watch-check tic"],
    ["watch_check_epic", "史詩看錶", "epic watch check", "錶、時、史詩", "watch, time, epic", "史詩尺度的常看腕錶", "at epic scale, checks a watch", "epic, watch-check tic"],
    ["smile_flash_court", "宮廷閃笑", "court flash smile", "閃笑、假、宮廷", "flash, fake, courtly", "宮廷氣場下的極短假笑", "in a courtly register, very short fake smile", "courtly, flash-smile tic"],
    ["smile_flash_street", "街頭閃笑", "street flash smile", "閃笑、假、街頭", "flash, fake, street", "街頭質感的極短假笑", "with street grit, very short fake smile", "street-cast, flash-smile tic"],
    ["smile_flash_noir", "暗黑閃笑", "noir flash smile", "閃笑、假、暗黑", "flash, fake, noir", "暗調電影感的極短假笑", "in noir lighting, very short fake smile", "noir, flash-smile tic"],
    ["smile_flash_soft", "柔光閃笑", "soft-light flash smile", "閃笑、假、柔光", "flash, fake, soft", "柔光下的極短假笑", "under soft light, very short fake smile", "soft-lit, flash-smile tic"],
    ["smile_flash_epic", "史詩閃笑", "epic flash smile", "閃笑、假、史詩", "flash, fake, epic", "史詩尺度的極短假笑", "at epic scale, very short fake smile", "epic, flash-smile tic"],
    ["collar_court", "宮廷整領", "court collar fix", "領、整、宮廷", "collar, fix, courtly", "宮廷氣場下的不整衣領", "in a courtly register, adjusts collar", "courtly, collar-fix tic"],
    ["collar_street", "街頭整領", "street collar fix", "領、整、街頭", "collar, fix, street", "街頭質感的不整衣領", "with street grit, adjusts collar", "street-cast, collar-fix tic"],
    ["collar_noir", "暗黑整領", "noir collar fix", "領、整、暗黑", "collar, fix, noir", "暗調電影感的不整衣領", "in noir lighting, adjusts collar", "noir, collar-fix tic"],
    ["collar_soft", "柔光整領", "soft-light collar fix", "領、整、柔光", "collar, fix, soft", "柔光下的不整衣領", "under soft light, adjusts collar", "soft-lit, collar-fix tic"],
    ["collar_epic", "史詩整領", "epic collar fix", "領、整、史詩", "collar, fix, epic", "史詩尺度的不整衣領", "at epic scale, adjusts collar", "epic, collar-fix tic"],
    ["count_court", "宮廷輕數", "court quiet count", "數、控、宮廷", "count, control, courtly", "宮廷氣場下的小聲數拍", "in a courtly register, quietly counts beats", "courtly, quiet-count tic"],
    ["count_street", "街頭輕數", "street quiet count", "數、控、街頭", "count, control, street", "街頭質感的小聲數拍", "with street grit, quietly counts beats", "street-cast, quiet-count tic"],
    ["count_noir", "暗黑輕數", "noir quiet count", "數、控、暗黑", "count, control, noir", "暗調電影感的小聲數拍", "in noir lighting, quietly counts beats", "noir, quiet-count tic"],
    ["count_soft", "柔光輕數", "soft-light quiet count", "數、控、柔光", "count, control, soft", "柔光下的小聲數拍", "under soft light, quietly counts beats", "soft-lit, quiet-count tic"],
    ["count_epic", "史詩輕數", "epic quiet count", "數、控、史詩", "count, control, epic", "史詩尺度的小聲數拍", "at epic scale, quietly counts beats", "epic, quiet-count tic"]
  ]
  }
})
