/**
 * motion field kit catalog (50+ templates per part).
 */
import { defineFieldKit } from '../fieldKit'

export const MOTION_KIT = defineFieldKit({
  key: "motionKit",
  parts: ["body","limbs","energy","path","tempo","weight"] as const,
  partLabels: {
    body: { zhHK: "身體", zhCN: "身体", en: "Body" },
    limbs: { zhHK: "肢", zhCN: "肢", en: "Limbs" },
    energy: { zhHK: "能量", zhCN: "能量", en: "Energy" },
    path: { zhHK: "路徑", zhCN: "路径", en: "Path" },
    tempo: { zhHK: "速度", zhCN: "速度", en: "Tempo" },
    weight: { zhHK: "重量", zhCN: "重量", en: "Weight" }
  },

  rows: {
    body: [
    ["core_lead_court", "宮廷核心先", "court core-led", "核、先、宮廷", "core, first, courtly", "宮廷氣場下的腰腹先動", "in a courtly register, core initiates", "courtly, core-led body"],
    ["core_lead_street", "街頭核心先", "street core-led", "核、先、街頭", "core, first, street", "街頭質感的腰腹先動", "with street grit, core initiates", "street-cast, core-led body"],
    ["core_lead_noir", "暗黑核心先", "noir core-led", "核、先、暗黑", "core, first, noir", "暗調電影感的腰腹先動", "in noir lighting, core initiates", "noir, core-led body"],
    ["core_lead_soft", "柔光核心先", "soft-light core-led", "核、先、柔光", "core, first, soft", "柔光下的腰腹先動", "under soft light, core initiates", "soft-lit, core-led body"],
    ["core_lead_epic", "史詩核心先", "epic core-led", "核、先、史詩", "core, first, epic", "史詩尺度的腰腹先動", "at epic scale, core initiates", "epic, core-led body"],
    ["collapse_court", "宮廷塌陷", "court collapse", "塌、卸、宮廷", "collapse, dump, courtly", "宮廷氣場下的中段突然塌", "in a courtly register, midsection collapses", "courtly, collapsing body"],
    ["collapse_street", "街頭塌陷", "street collapse", "塌、卸、街頭", "collapse, dump, street", "街頭質感的中段突然塌", "with street grit, midsection collapses", "street-cast, collapsing body"],
    ["collapse_noir", "暗黑塌陷", "noir collapse", "塌、卸、暗黑", "collapse, dump, noir", "暗調電影感的中段突然塌", "in noir lighting, midsection collapses", "noir, collapsing body"],
    ["collapse_soft", "柔光塌陷", "soft-light collapse", "塌、卸、柔光", "collapse, dump, soft", "柔光下的中段突然塌", "under soft light, midsection collapses", "soft-lit, collapsing body"],
    ["collapse_epic", "史詩塌陷", "epic collapse", "塌、卸、史詩", "collapse, dump, epic", "史詩尺度的中段突然塌", "at epic scale, midsection collapses", "epic, collapsing body"],
    ["arch_court", "宮廷反弓", "court arch", "弓、張、宮廷", "arch, tension, courtly", "宮廷氣場下的胸背反弓", "in a courtly register, chest-back arch", "courtly, arching body"],
    ["arch_street", "街頭反弓", "street arch", "弓、張、街頭", "arch, tension, street", "街頭質感的胸背反弓", "with street grit, chest-back arch", "street-cast, arching body"],
    ["arch_noir", "暗黑反弓", "noir arch", "弓、張、暗黑", "arch, tension, noir", "暗調電影感的胸背反弓", "in noir lighting, chest-back arch", "noir, arching body"],
    ["arch_soft", "柔光反弓", "soft-light arch", "弓、張、柔光", "arch, tension, soft", "柔光下的胸背反弓", "under soft light, chest-back arch", "soft-lit, arching body"],
    ["arch_epic", "史詩反弓", "epic arch", "弓、張、史詩", "arch, tension, epic", "史詩尺度的胸背反弓", "at epic scale, chest-back arch", "epic, arching body"],
    ["twist_court", "宮廷扭轉", "court twist", "扭、螺、宮廷", "twist, screw, courtly", "宮廷氣場下的軀幹螺轉", "in a courtly register, torso corkscrew", "courtly, twisting body"],
    ["twist_street", "街頭扭轉", "street twist", "扭、螺、街頭", "twist, screw, street", "街頭質感的軀幹螺轉", "with street grit, torso corkscrew", "street-cast, twisting body"],
    ["twist_noir", "暗黑扭轉", "noir twist", "扭、螺、暗黑", "twist, screw, noir", "暗調電影感的軀幹螺轉", "in noir lighting, torso corkscrew", "noir, twisting body"],
    ["twist_soft", "柔光扭轉", "soft-light twist", "扭、螺、柔光", "twist, screw, soft", "柔光下的軀幹螺轉", "under soft light, torso corkscrew", "soft-lit, twisting body"],
    ["twist_epic", "史詩扭轉", "epic twist", "扭、螺、史詩", "twist, screw, epic", "史詩尺度的軀幹螺轉", "at epic scale, torso corkscrew", "epic, twisting body"],
    ["still_core_court", "宮廷中段鎖", "court locked core", "鎖、靜、宮廷", "lock, still, courtly", "宮廷氣場下的軀幹幾乎不動", "in a courtly register, torso nearly still", "courtly, locked-core body"],
    ["still_core_street", "街頭中段鎖", "street locked core", "鎖、靜、街頭", "lock, still, street", "街頭質感的軀幹幾乎不動", "with street grit, torso nearly still", "street-cast, locked-core body"],
    ["still_core_noir", "暗黑中段鎖", "noir locked core", "鎖、靜、暗黑", "lock, still, noir", "暗調電影感的軀幹幾乎不動", "in noir lighting, torso nearly still", "noir, locked-core body"],
    ["still_core_soft", "柔光中段鎖", "soft-light locked core", "鎖、靜、柔光", "lock, still, soft", "柔光下的軀幹幾乎不動", "under soft light, torso nearly still", "soft-lit, locked-core body"],
    ["still_core_epic", "史詩中段鎖", "epic locked core", "鎖、靜、史詩", "lock, still, epic", "史詩尺度的軀幹幾乎不動", "at epic scale, torso nearly still", "epic, locked-core body"],
    ["wave_court", "宮廷波傳", "court wave", "波、傳、宮廷", "wave, pass, courtly", "宮廷氣場下的力如波傳", "in a courtly register, force travels as wave", "courtly, wave body"],
    ["wave_street", "街頭波傳", "street wave", "波、傳、街頭", "wave, pass, street", "街頭質感的力如波傳", "with street grit, force travels as wave", "street-cast, wave body"],
    ["wave_noir", "暗黑波傳", "noir wave", "波、傳、暗黑", "wave, pass, noir", "暗調電影感的力如波傳", "in noir lighting, force travels as wave", "noir, wave body"],
    ["wave_soft", "柔光波傳", "soft-light wave", "波、傳、柔光", "wave, pass, soft", "柔光下的力如波傳", "under soft light, force travels as wave", "soft-lit, wave body"],
    ["wave_epic", "史詩波傳", "epic wave", "波、傳、史詩", "wave, pass, epic", "史詩尺度的力如波傳", "at epic scale, force travels as wave", "epic, wave body"],
    ["drop_court", "宮廷下沉", "court drop", "沉、跪、宮廷", "drop, kneel, courtly", "宮廷氣場下的重心突沉", "in a courtly register, sudden weight drop", "courtly, dropping body"],
    ["drop_street", "街頭下沉", "street drop", "沉、跪、街頭", "drop, kneel, street", "街頭質感的重心突沉", "with street grit, sudden weight drop", "street-cast, dropping body"],
    ["drop_noir", "暗黑下沉", "noir drop", "沉、跪、暗黑", "drop, kneel, noir", "暗調電影感的重心突沉", "in noir lighting, sudden weight drop", "noir, dropping body"],
    ["drop_soft", "柔光下沉", "soft-light drop", "沉、跪、柔光", "drop, kneel, soft", "柔光下的重心突沉", "under soft light, sudden weight drop", "soft-lit, dropping body"],
    ["drop_epic", "史詩下沉", "epic drop", "沉、跪、史詩", "drop, kneel, epic", "史詩尺度的重心突沉", "at epic scale, sudden weight drop", "epic, dropping body"],
    ["rise_court", "宮廷拔起", "court rise", "拔、站、宮廷", "rise, stand, courtly", "宮廷氣場下的由低拔直", "in a courtly register, rises from low", "courtly, rising body"],
    ["rise_street", "街頭拔起", "street rise", "拔、站、街頭", "rise, stand, street", "街頭質感的由低拔直", "with street grit, rises from low", "street-cast, rising body"],
    ["rise_noir", "暗黑拔起", "noir rise", "拔、站、暗黑", "rise, stand, noir", "暗調電影感的由低拔直", "in noir lighting, rises from low", "noir, rising body"],
    ["rise_soft", "柔光拔起", "soft-light rise", "拔、站、柔光", "rise, stand, soft", "柔光下的由低拔直", "under soft light, rises from low", "soft-lit, rising body"],
    ["rise_epic", "史詩拔起", "epic rise", "拔、站、史詩", "rise, stand, epic", "史詩尺度的由低拔直", "at epic scale, rises from low", "epic, rising body"],
    ["tilt_court", "宮廷傾斜", "court tilt", "傾、險、宮廷", "tilt, risk, courtly", "宮廷氣場下的整身側傾", "in a courtly register, whole-body lean", "courtly, tilting body"],
    ["tilt_street", "街頭傾斜", "street tilt", "傾、險、街頭", "tilt, risk, street", "街頭質感的整身側傾", "with street grit, whole-body lean", "street-cast, tilting body"],
    ["tilt_noir", "暗黑傾斜", "noir tilt", "傾、險、暗黑", "tilt, risk, noir", "暗調電影感的整身側傾", "in noir lighting, whole-body lean", "noir, tilting body"],
    ["tilt_soft", "柔光傾斜", "soft-light tilt", "傾、險、柔光", "tilt, risk, soft", "柔光下的整身側傾", "under soft light, whole-body lean", "soft-lit, tilting body"],
    ["tilt_epic", "史詩傾斜", "epic tilt", "傾、險、史詩", "tilt, risk, epic", "史詩尺度的整身側傾", "at epic scale, whole-body lean", "epic, tilting body"],
    ["recoil_court", "宮廷後坐", "court recoil", "坐、震、宮廷", "recoil, shock, courtly", "宮廷氣場下的受擊後坐", "in a courtly register, recoils after impact", "courtly, recoiling body"],
    ["recoil_street", "街頭後坐", "street recoil", "坐、震、街頭", "recoil, shock, street", "街頭質感的受擊後坐", "with street grit, recoils after impact", "street-cast, recoiling body"],
    ["recoil_noir", "暗黑後坐", "noir recoil", "坐、震、暗黑", "recoil, shock, noir", "暗調電影感的受擊後坐", "in noir lighting, recoils after impact", "noir, recoiling body"],
    ["recoil_soft", "柔光後坐", "soft-light recoil", "坐、震、柔光", "recoil, shock, soft", "柔光下的受擊後坐", "under soft light, recoils after impact", "soft-lit, recoiling body"],
    ["recoil_epic", "史詩後坐", "epic recoil", "坐、震、史詩", "recoil, shock, epic", "史詩尺度的受擊後坐", "at epic scale, recoils after impact", "epic, recoiling body"]
  ],
    limbs: [
    ["whip_arm_court", "宮廷鞭臂", "court whip arm", "鞭、臂、宮廷", "whip, arm, courtly", "宮廷氣場下的手臂如鞭", "in a courtly register, arm like a whip", "courtly, whip-arm limbs"],
    ["whip_arm_street", "街頭鞭臂", "street whip arm", "鞭、臂、街頭", "whip, arm, street", "街頭質感的手臂如鞭", "with street grit, arm like a whip", "street-cast, whip-arm limbs"],
    ["whip_arm_noir", "暗黑鞭臂", "noir whip arm", "鞭、臂、暗黑", "whip, arm, noir", "暗調電影感的手臂如鞭", "in noir lighting, arm like a whip", "noir, whip-arm limbs"],
    ["whip_arm_soft", "柔光鞭臂", "soft-light whip arm", "鞭、臂、柔光", "whip, arm, soft", "柔光下的手臂如鞭", "under soft light, arm like a whip", "soft-lit, whip-arm limbs"],
    ["whip_arm_epic", "史詩鞭臂", "epic whip arm", "鞭、臂、史詩", "whip, arm, epic", "史詩尺度的手臂如鞭", "at epic scale, arm like a whip", "epic, whip-arm limbs"],
    ["guard_court", "宮廷始終護", "court guarding limbs", "護、收、宮廷", "guard, close, courtly", "宮廷氣場下的手不離護", "in a courtly register, hands stay on guard", "courtly, guarding limbs"],
    ["guard_street", "街頭始終護", "street guarding limbs", "護、收、街頭", "guard, close, street", "街頭質感的手不離護", "with street grit, hands stay on guard", "street-cast, guarding limbs"],
    ["guard_noir", "暗黑始終護", "noir guarding limbs", "護、收、暗黑", "guard, close, noir", "暗調電影感的手不離護", "in noir lighting, hands stay on guard", "noir, guarding limbs"],
    ["guard_soft", "柔光始終護", "soft-light guarding limbs", "護、收、柔光", "guard, close, soft", "柔光下的手不離護", "under soft light, hands stay on guard", "soft-lit, guarding limbs"],
    ["guard_epic", "史詩始終護", "epic guarding limbs", "護、收、史詩", "guard, close, epic", "史詩尺度的手不離護", "at epic scale, hands stay on guard", "epic, guarding limbs"],
    ["reach_court", "宮廷極伸", "court full reach", "伸、要、宮廷", "reach, want, courtly", "宮廷氣場下的手臂盡伸", "in a courtly register, arms at full reach", "courtly, full-reach limbs"],
    ["reach_street", "街頭極伸", "street full reach", "伸、要、街頭", "reach, want, street", "街頭質感的手臂盡伸", "with street grit, arms at full reach", "street-cast, full-reach limbs"],
    ["reach_noir", "暗黑極伸", "noir full reach", "伸、要、暗黑", "reach, want, noir", "暗調電影感的手臂盡伸", "in noir lighting, arms at full reach", "noir, full-reach limbs"],
    ["reach_soft", "柔光極伸", "soft-light full reach", "伸、要、柔光", "reach, want, soft", "柔光下的手臂盡伸", "under soft light, arms at full reach", "soft-lit, full-reach limbs"],
    ["reach_epic", "史詩極伸", "epic full reach", "伸、要、史詩", "reach, want, epic", "史詩尺度的手臂盡伸", "at epic scale, arms at full reach", "epic, full-reach limbs"],
    ["stomp_court", "宮廷踏", "court stomp", "踏、腿、宮廷", "stomp, leg, courtly", "宮廷氣場下的腿下踏明顯", "in a courtly register, clear stomps", "courtly, stomping limbs"],
    ["stomp_street", "街頭踏", "street stomp", "踏、腿、街頭", "stomp, leg, street", "街頭質感的腿下踏明顯", "with street grit, clear stomps", "street-cast, stomping limbs"],
    ["stomp_noir", "暗黑踏", "noir stomp", "踏、腿、暗黑", "stomp, leg, noir", "暗調電影感的腿下踏明顯", "in noir lighting, clear stomps", "noir, stomping limbs"],
    ["stomp_soft", "柔光踏", "soft-light stomp", "踏、腿、柔光", "stomp, leg, soft", "柔光下的腿下踏明顯", "under soft light, clear stomps", "soft-lit, stomping limbs"],
    ["stomp_epic", "史詩踏", "epic stomp", "踏、腿、史詩", "stomp, leg, epic", "史詩尺度的腿下踏明顯", "at epic scale, clear stomps", "epic, stomping limbs"],
    ["float_foot_court", "宮廷腳不實", "court uncommitted feet", "浮、不實、宮廷", "float, light, courtly", "宮廷氣場下的腳跟不落地", "in a courtly register, heels barely land", "courtly, uncommitted feet"],
    ["float_foot_street", "街頭腳不實", "street uncommitted feet", "浮、不實、街頭", "float, light, street", "街頭質感的腳跟不落地", "with street grit, heels barely land", "street-cast, uncommitted feet"],
    ["float_foot_noir", "暗黑腳不實", "noir uncommitted feet", "浮、不實、暗黑", "float, light, noir", "暗調電影感的腳跟不落地", "in noir lighting, heels barely land", "noir, uncommitted feet"],
    ["float_foot_soft", "柔光腳不實", "soft-light uncommitted feet", "浮、不實、柔光", "float, light, soft", "柔光下的腳跟不落地", "under soft light, heels barely land", "soft-lit, uncommitted feet"],
    ["float_foot_epic", "史詩腳不實", "epic uncommitted feet", "浮、不實、史詩", "float, light, epic", "史詩尺度的腳跟不落地", "at epic scale, heels barely land", "epic, uncommitted feet"],
    ["precise_finger_court", "宮廷指極準", "court precise fingers", "指、準、宮廷", "finger, precise, courtly", "宮廷氣場下的手指極清楚", "in a courtly register, very clear fingers", "courtly, precise-finger limbs"],
    ["precise_finger_street", "街頭指極準", "street precise fingers", "指、準、街頭", "finger, precise, street", "街頭質感的手指極清楚", "with street grit, very clear fingers", "street-cast, precise-finger limbs"],
    ["precise_finger_noir", "暗黑指極準", "noir precise fingers", "指、準、暗黑", "finger, precise, noir", "暗調電影感的手指極清楚", "in noir lighting, very clear fingers", "noir, precise-finger limbs"],
    ["precise_finger_soft", "柔光指極準", "soft-light precise fingers", "指、準、柔光", "finger, precise, soft", "柔光下的手指極清楚", "under soft light, very clear fingers", "soft-lit, precise-finger limbs"],
    ["precise_finger_epic", "史詩指極準", "epic precise fingers", "指、準、史詩", "finger, precise, epic", "史詩尺度的手指極清楚", "at epic scale, very clear fingers", "epic, precise-finger limbs"],
    ["dead_arm_court", "宮廷臂無力", "court dead arms", "死、垂、宮廷", "dead, hang, courtly", "宮廷氣場下的臂幾乎垂", "in a courtly register, arms nearly hang", "courtly, dead-arm limbs"],
    ["dead_arm_street", "街頭臂無力", "street dead arms", "死、垂、街頭", "dead, hang, street", "街頭質感的臂幾乎垂", "with street grit, arms nearly hang", "street-cast, dead-arm limbs"],
    ["dead_arm_noir", "暗黑臂無力", "noir dead arms", "死、垂、暗黑", "dead, hang, noir", "暗調電影感的臂幾乎垂", "in noir lighting, arms nearly hang", "noir, dead-arm limbs"],
    ["dead_arm_soft", "柔光臂無力", "soft-light dead arms", "死、垂、柔光", "dead, hang, soft", "柔光下的臂幾乎垂", "under soft light, arms nearly hang", "soft-lit, dead-arm limbs"],
    ["dead_arm_epic", "史詩臂無力", "epic dead arms", "死、垂、史詩", "dead, hang, epic", "史詩尺度的臂幾乎垂", "at epic scale, arms nearly hang", "epic, dead-arm limbs"],
    ["kick_line_court", "宮廷腿線長", "court long kick line", "腿、線、宮廷", "kick, line, courtly", "宮廷氣場下的踢腿拉長線", "in a courtly register, kicks draw long lines", "courtly, long-kick-line limbs"],
    ["kick_line_street", "街頭腿線長", "street long kick line", "腿、線、街頭", "kick, line, street", "街頭質感的踢腿拉長線", "with street grit, kicks draw long lines", "street-cast, long-kick-line limbs"],
    ["kick_line_noir", "暗黑腿線長", "noir long kick line", "腿、線、暗黑", "kick, line, noir", "暗調電影感的踢腿拉長線", "in noir lighting, kicks draw long lines", "noir, long-kick-line limbs"],
    ["kick_line_soft", "柔光腿線長", "soft-light long kick line", "腿、線、柔光", "kick, line, soft", "柔光下的踢腿拉長線", "under soft light, kicks draw long lines", "soft-lit, long-kick-line limbs"],
    ["kick_line_epic", "史詩腿線長", "epic long kick line", "腿、線、史詩", "kick, line, epic", "史詩尺度的踢腿拉長線", "at epic scale, kicks draw long lines", "epic, long-kick-line limbs"],
    ["clinch_court", "宮廷纏抱", "court clinch", "纏、近、宮廷", "clinch, close, courtly", "宮廷氣場下的肢纏在一起", "in a courtly register, limbs tangle close", "courtly, clinching limbs"],
    ["clinch_street", "街頭纏抱", "street clinch", "纏、近、街頭", "clinch, close, street", "街頭質感的肢纏在一起", "with street grit, limbs tangle close", "street-cast, clinching limbs"],
    ["clinch_noir", "暗黑纏抱", "noir clinch", "纏、近、暗黑", "clinch, close, noir", "暗調電影感的肢纏在一起", "in noir lighting, limbs tangle close", "noir, clinching limbs"],
    ["clinch_soft", "柔光纏抱", "soft-light clinch", "纏、近、柔光", "clinch, close, soft", "柔光下的肢纏在一起", "under soft light, limbs tangle close", "soft-lit, clinching limbs"],
    ["clinch_epic", "史詩纏抱", "epic clinch", "纏、近、史詩", "clinch, close, epic", "史詩尺度的肢纏在一起", "at epic scale, limbs tangle close", "epic, clinching limbs"],
    ["point_court", "宮廷常指", "court pointing", "指、令、宮廷", "point, order, courtly", "宮廷氣場下的動作含指向", "in a courtly register, motion includes pointing", "courtly, pointing limbs"],
    ["point_street", "街頭常指", "street pointing", "指、令、街頭", "point, order, street", "街頭質感的動作含指向", "with street grit, motion includes pointing", "street-cast, pointing limbs"],
    ["point_noir", "暗黑常指", "noir pointing", "指、令、暗黑", "point, order, noir", "暗調電影感的動作含指向", "in noir lighting, motion includes pointing", "noir, pointing limbs"],
    ["point_soft", "柔光常指", "soft-light pointing", "指、令、柔光", "point, order, soft", "柔光下的動作含指向", "under soft light, motion includes pointing", "soft-lit, pointing limbs"],
    ["point_epic", "史詩常指", "epic pointing", "指、令、史詩", "point, order, epic", "史詩尺度的動作含指向", "at epic scale, motion includes pointing", "epic, pointing limbs"]
  ],
    energy: [
    ["explosive_court", "宮廷爆", "court explosive", "爆、瞬、宮廷", "burst, instant, courtly", "宮廷氣場下的瞬間爆發", "in a courtly register, instant burst", "courtly, explosive energy"],
    ["explosive_street", "街頭爆", "street explosive", "爆、瞬、街頭", "burst, instant, street", "街頭質感的瞬間爆發", "with street grit, instant burst", "street-cast, explosive energy"],
    ["explosive_noir", "暗黑爆", "noir explosive", "爆、瞬、暗黑", "burst, instant, noir", "暗調電影感的瞬間爆發", "in noir lighting, instant burst", "noir, explosive energy"],
    ["explosive_soft", "柔光爆", "soft-light explosive", "爆、瞬、柔光", "burst, instant, soft", "柔光下的瞬間爆發", "under soft light, instant burst", "soft-lit, explosive energy"],
    ["explosive_epic", "史詩爆", "epic explosive", "爆、瞬、史詩", "burst, instant, epic", "史詩尺度的瞬間爆發", "at epic scale, instant burst", "epic, explosive energy"],
    ["simmer_court", "宮廷悶燒", "court simmering", "悶、壓、宮廷", "simmer, press, courtly", "宮廷氣場下的一直壓著的力", "in a courtly register, force kept pressed", "courtly, simmering energy"],
    ["simmer_street", "街頭悶燒", "street simmering", "悶、壓、街頭", "simmer, press, street", "街頭質感的一直壓著的力", "with street grit, force kept pressed", "street-cast, simmering energy"],
    ["simmer_noir", "暗黑悶燒", "noir simmering", "悶、壓、暗黑", "simmer, press, noir", "暗調電影感的一直壓著的力", "in noir lighting, force kept pressed", "noir, simmering energy"],
    ["simmer_soft", "柔光悶燒", "soft-light simmering", "悶、壓、柔光", "simmer, press, soft", "柔光下的一直壓著的力", "under soft light, force kept pressed", "soft-lit, simmering energy"],
    ["simmer_epic", "史詩悶燒", "epic simmering", "悶、壓、史詩", "simmer, press, epic", "史詩尺度的一直壓著的力", "at epic scale, force kept pressed", "epic, simmering energy"],
    ["drained_court", "宮廷空", "court drained", "空、盡、宮廷", "empty, spent, courtly", "宮廷氣場下的幾乎沒餘力", "in a courtly register, almost no reserve", "courtly, drained energy"],
    ["drained_street", "街頭空", "street drained", "空、盡、街頭", "empty, spent, street", "街頭質感的幾乎沒餘力", "with street grit, almost no reserve", "street-cast, drained energy"],
    ["drained_noir", "暗黑空", "noir drained", "空、盡、暗黑", "empty, spent, noir", "暗調電影感的幾乎沒餘力", "in noir lighting, almost no reserve", "noir, drained energy"],
    ["drained_soft", "柔光空", "soft-light drained", "空、盡、柔光", "empty, spent, soft", "柔光下的幾乎沒餘力", "under soft light, almost no reserve", "soft-lit, drained energy"],
    ["drained_epic", "史詩空", "epic drained", "空、盡、史詩", "empty, spent, epic", "史詩尺度的幾乎沒餘力", "at epic scale, almost no reserve", "epic, drained energy"],
    ["manic_court", "宮廷狂", "court manic", "狂、多、宮廷", "manic, too much, courtly", "宮廷氣場下的力過多失控", "in a courtly register, too much force", "courtly, manic energy"],
    ["manic_street", "街頭狂", "street manic", "狂、多、街頭", "manic, too much, street", "街頭質感的力過多失控", "with street grit, too much force", "street-cast, manic energy"],
    ["manic_noir", "暗黑狂", "noir manic", "狂、多、暗黑", "manic, too much, noir", "暗調電影感的力過多失控", "in noir lighting, too much force", "noir, manic energy"],
    ["manic_soft", "柔光狂", "soft-light manic", "狂、多、柔光", "manic, too much, soft", "柔光下的力過多失控", "under soft light, too much force", "soft-lit, manic energy"],
    ["manic_epic", "史詩狂", "epic manic", "狂、多、史詩", "manic, too much, epic", "史詩尺度的力過多失控", "at epic scale, too much force", "epic, manic energy"],
    ["cold_court", "宮廷冷準", "court cold precise", "冷、準、宮廷", "cold, precise, courtly", "宮廷氣場下的無情緒的準", "in a courtly register, emotionless precision", "courtly, cold precise energy"],
    ["cold_street", "街頭冷準", "street cold precise", "冷、準、街頭", "cold, precise, street", "街頭質感的無情緒的準", "with street grit, emotionless precision", "street-cast, cold precise energy"],
    ["cold_noir", "暗黑冷準", "noir cold precise", "冷、準、暗黑", "cold, precise, noir", "暗調電影感的無情緒的準", "in noir lighting, emotionless precision", "noir, cold precise energy"],
    ["cold_soft", "柔光冷準", "soft-light cold precise", "冷、準、柔光", "cold, precise, soft", "柔光下的無情緒的準", "under soft light, emotionless precision", "soft-lit, cold precise energy"],
    ["cold_epic", "史詩冷準", "epic cold precise", "冷、準、史詩", "cold, precise, epic", "史詩尺度的無情緒的準", "at epic scale, emotionless precision", "epic, cold precise energy"],
    ["playful_court", "宮廷玩", "court playful", "玩、輕、宮廷", "play, light, courtly", "宮廷氣場下的帶玩的力", "in a courtly register, force with play", "courtly, playful energy"],
    ["playful_street", "街頭玩", "street playful", "玩、輕、街頭", "play, light, street", "街頭質感的帶玩的力", "with street grit, force with play", "street-cast, playful energy"],
    ["playful_noir", "暗黑玩", "noir playful", "玩、輕、暗黑", "play, light, noir", "暗調電影感的帶玩的力", "in noir lighting, force with play", "noir, playful energy"],
    ["playful_soft", "柔光玩", "soft-light playful", "玩、輕、柔光", "play, light, soft", "柔光下的帶玩的力", "under soft light, force with play", "soft-lit, playful energy"],
    ["playful_epic", "史詩玩", "epic playful", "玩、輕、史詩", "play, light, epic", "史詩尺度的帶玩的力", "at epic scale, force with play", "epic, playful energy"],
    ["desperate_court", "宮廷拼命", "court desperate", "命、撲、宮廷", "desperate, lunge, courtly", "宮廷氣場下的不顧後的撲", "in a courtly register, lunges without reserve", "courtly, desperate energy"],
    ["desperate_street", "街頭拼命", "street desperate", "命、撲、街頭", "desperate, lunge, street", "街頭質感的不顧後的撲", "with street grit, lunges without reserve", "street-cast, desperate energy"],
    ["desperate_noir", "暗黑拼命", "noir desperate", "命、撲、暗黑", "desperate, lunge, noir", "暗調電影感的不顧後的撲", "in noir lighting, lunges without reserve", "noir, desperate energy"],
    ["desperate_soft", "柔光拼命", "soft-light desperate", "命、撲、柔光", "desperate, lunge, soft", "柔光下的不顧後的撲", "under soft light, lunges without reserve", "soft-lit, desperate energy"],
    ["desperate_epic", "史詩拼命", "epic desperate", "命、撲、史詩", "desperate, lunge, epic", "史詩尺度的不顧後的撲", "at epic scale, lunges without reserve", "epic, desperate energy"],
    ["ritual_court", "宮廷儀式勻", "court ritual even", "儀、勻、宮廷", "ritual, even, courtly", "宮廷氣場下的勻得像儀式", "in a courtly register, even like ritual", "courtly, ritual energy"],
    ["ritual_street", "街頭儀式勻", "street ritual even", "儀、勻、街頭", "ritual, even, street", "街頭質感的勻得像儀式", "with street grit, even like ritual", "street-cast, ritual energy"],
    ["ritual_noir", "暗黑儀式勻", "noir ritual even", "儀、勻、暗黑", "ritual, even, noir", "暗調電影感的勻得像儀式", "in noir lighting, even like ritual", "noir, ritual energy"],
    ["ritual_soft", "柔光儀式勻", "soft-light ritual even", "儀、勻、柔光", "ritual, even, soft", "柔光下的勻得像儀式", "under soft light, even like ritual", "soft-lit, ritual energy"],
    ["ritual_epic", "史詩儀式勻", "epic ritual even", "儀、勻、史詩", "ritual, even, epic", "史詩尺度的勻得像儀式", "at epic scale, even like ritual", "epic, ritual energy"],
    ["electric_court", "宮廷電", "court electric", "電、顫、宮廷", "electric, jitter, courtly", "宮廷氣場下的帶顫的電", "in a courtly register, jittery electric", "courtly, electric energy"],
    ["electric_street", "街頭電", "street electric", "電、顫、街頭", "electric, jitter, street", "街頭質感的帶顫的電", "with street grit, jittery electric", "street-cast, electric energy"],
    ["electric_noir", "暗黑電", "noir electric", "電、顫、暗黑", "electric, jitter, noir", "暗調電影感的帶顫的電", "in noir lighting, jittery electric", "noir, electric energy"],
    ["electric_soft", "柔光電", "soft-light electric", "電、顫、柔光", "electric, jitter, soft", "柔光下的帶顫的電", "under soft light, jittery electric", "soft-lit, electric energy"],
    ["electric_epic", "史詩電", "epic electric", "電、顫、史詩", "electric, jitter, epic", "史詩尺度的帶顫的電", "at epic scale, jittery electric", "epic, electric energy"],
    ["heavy_sad_court", "宮廷沉哀", "court heavy grief", "沉、哀、宮廷", "heavy, grief, courtly", "宮廷氣場下的力被哀拖住", "in a courtly register, force dragged by grief", "courtly, heavy-grief energy"],
    ["heavy_sad_street", "街頭沉哀", "street heavy grief", "沉、哀、街頭", "heavy, grief, street", "街頭質感的力被哀拖住", "with street grit, force dragged by grief", "street-cast, heavy-grief energy"],
    ["heavy_sad_noir", "暗黑沉哀", "noir heavy grief", "沉、哀、暗黑", "heavy, grief, noir", "暗調電影感的力被哀拖住", "in noir lighting, force dragged by grief", "noir, heavy-grief energy"],
    ["heavy_sad_soft", "柔光沉哀", "soft-light heavy grief", "沉、哀、柔光", "heavy, grief, soft", "柔光下的力被哀拖住", "under soft light, force dragged by grief", "soft-lit, heavy-grief energy"],
    ["heavy_sad_epic", "史詩沉哀", "epic heavy grief", "沉、哀、史詩", "heavy, grief, epic", "史詩尺度的力被哀拖住", "at epic scale, force dragged by grief", "epic, heavy-grief energy"]
  ],
    path: [
    ["straight_court", "宮廷直線", "court straight line", "直、最短、宮廷", "straight, shortest, courtly", "宮廷氣場下的最短直線", "in a courtly register, shortest straight path", "courtly, straight path"],
    ["straight_street", "街頭直線", "street straight line", "直、最短、街頭", "straight, shortest, street", "街頭質感的最短直線", "with street grit, shortest straight path", "street-cast, straight path"],
    ["straight_noir", "暗黑直線", "noir straight line", "直、最短、暗黑", "straight, shortest, noir", "暗調電影感的最短直線", "in noir lighting, shortest straight path", "noir, straight path"],
    ["straight_soft", "柔光直線", "soft-light straight line", "直、最短、柔光", "straight, shortest, soft", "柔光下的最短直線", "under soft light, shortest straight path", "soft-lit, straight path"],
    ["straight_epic", "史詩直線", "epic straight line", "直、最短、史詩", "straight, shortest, epic", "史詩尺度的最短直線", "at epic scale, shortest straight path", "epic, straight path"],
    ["arc_court", "宮廷弧", "court arc", "弧、繞、宮廷", "arc, around, courtly", "宮廷氣場下的大弧線", "in a courtly register, wide arc path", "courtly, arc path"],
    ["arc_street", "街頭弧", "street arc", "弧、繞、街頭", "arc, around, street", "街頭質感的大弧線", "with street grit, wide arc path", "street-cast, arc path"],
    ["arc_noir", "暗黑弧", "noir arc", "弧、繞、暗黑", "arc, around, noir", "暗調電影感的大弧線", "in noir lighting, wide arc path", "noir, arc path"],
    ["arc_soft", "柔光弧", "soft-light arc", "弧、繞、柔光", "arc, around, soft", "柔光下的大弧線", "under soft light, wide arc path", "soft-lit, arc path"],
    ["arc_epic", "史詩弧", "epic arc", "弧、繞、史詩", "arc, around, epic", "史詩尺度的大弧線", "at epic scale, wide arc path", "epic, arc path"],
    ["zigzag_court", "宮廷折線", "court zigzag", "折、躲、宮廷", "zig, evade, courtly", "宮廷氣場下的折來折去", "in a courtly register, zigzag evasion", "courtly, zigzag path"],
    ["zigzag_street", "街頭折線", "street zigzag", "折、躲、街頭", "zig, evade, street", "街頭質感的折來折去", "with street grit, zigzag evasion", "street-cast, zigzag path"],
    ["zigzag_noir", "暗黑折線", "noir zigzag", "折、躲、暗黑", "zig, evade, noir", "暗調電影感的折來折去", "in noir lighting, zigzag evasion", "noir, zigzag path"],
    ["zigzag_soft", "柔光折線", "soft-light zigzag", "折、躲、柔光", "zig, evade, soft", "柔光下的折來折去", "under soft light, zigzag evasion", "soft-lit, zigzag path"],
    ["zigzag_epic", "史詩折線", "epic zigzag", "折、躲、史詩", "zig, evade, epic", "史詩尺度的折來折去", "at epic scale, zigzag evasion", "epic, zigzag path"],
    ["circle_court", "宮廷圈", "court circle", "圈、困、宮廷", "circle, trap, courtly", "宮廷氣場下的繞圈", "in a courtly register, circling path", "courtly, circular path"],
    ["circle_street", "街頭圈", "street circle", "圈、困、街頭", "circle, trap, street", "街頭質感的繞圈", "with street grit, circling path", "street-cast, circular path"],
    ["circle_noir", "暗黑圈", "noir circle", "圈、困、暗黑", "circle, trap, noir", "暗調電影感的繞圈", "in noir lighting, circling path", "noir, circular path"],
    ["circle_soft", "柔光圈", "soft-light circle", "圈、困、柔光", "circle, trap, soft", "柔光下的繞圈", "under soft light, circling path", "soft-lit, circular path"],
    ["circle_epic", "史詩圈", "epic circle", "圈、困、史詩", "circle, trap, epic", "史詩尺度的繞圈", "at epic scale, circling path", "epic, circular path"],
    ["advance_court", "宮廷只進", "court only forward", "進、壓、宮廷", "forward, press, courtly", "宮廷氣場下的幾乎不退", "in a courtly register, almost no retreat", "courtly, forward-only path"],
    ["advance_street", "街頭只進", "street only forward", "進、壓、街頭", "forward, press, street", "街頭質感的幾乎不退", "with street grit, almost no retreat", "street-cast, forward-only path"],
    ["advance_noir", "暗黑只進", "noir only forward", "進、壓、暗黑", "forward, press, noir", "暗調電影感的幾乎不退", "in noir lighting, almost no retreat", "noir, forward-only path"],
    ["advance_soft", "柔光只進", "soft-light only forward", "進、壓、柔光", "forward, press, soft", "柔光下的幾乎不退", "under soft light, almost no retreat", "soft-lit, forward-only path"],
    ["advance_epic", "史詩只進", "epic only forward", "進、壓、史詩", "forward, press, epic", "史詩尺度的幾乎不退", "at epic scale, almost no retreat", "epic, forward-only path"],
    ["retreat_court", "宮廷邊打邊退", "court fighting retreat", "退、守、宮廷", "back, guard, courtly", "宮廷氣場下的後退中動作", "in a courtly register, moving back while acting", "courtly, retreat path"],
    ["retreat_street", "街頭邊打邊退", "street fighting retreat", "退、守、街頭", "back, guard, street", "街頭質感的後退中動作", "with street grit, moving back while acting", "street-cast, retreat path"],
    ["retreat_noir", "暗黑邊打邊退", "noir fighting retreat", "退、守、暗黑", "back, guard, noir", "暗調電影感的後退中動作", "in noir lighting, moving back while acting", "noir, retreat path"],
    ["retreat_soft", "柔光邊打邊退", "soft-light fighting retreat", "退、守、柔光", "back, guard, soft", "柔光下的後退中動作", "under soft light, moving back while acting", "soft-lit, retreat path"],
    ["retreat_epic", "史詩邊打邊退", "epic fighting retreat", "退、守、史詩", "back, guard, epic", "史詩尺度的後退中動作", "at epic scale, moving back while acting", "epic, retreat path"],
    ["vertical_court", "宮廷上下", "court vertical", "上、下、宮廷", "up, down, courtly", "宮廷氣場下的主要上下", "in a courtly register, mostly up and down", "courtly, vertical path"],
    ["vertical_street", "街頭上下", "street vertical", "上、下、街頭", "up, down, street", "街頭質感的主要上下", "with street grit, mostly up and down", "street-cast, vertical path"],
    ["vertical_noir", "暗黑上下", "noir vertical", "上、下、暗黑", "up, down, noir", "暗調電影感的主要上下", "in noir lighting, mostly up and down", "noir, vertical path"],
    ["vertical_soft", "柔光上下", "soft-light vertical", "上、下、柔光", "up, down, soft", "柔光下的主要上下", "under soft light, mostly up and down", "soft-lit, vertical path"],
    ["vertical_epic", "史詩上下", "epic vertical", "上、下、史詩", "up, down, epic", "史詩尺度的主要上下", "at epic scale, mostly up and down", "epic, vertical path"],
    ["spiral_court", "宮廷螺旋", "court spiral", "螺、收、宮廷", "spiral, close, courtly", "宮廷氣場下的螺旋接近", "in a courtly register, spirals inward", "courtly, spiral path"],
    ["spiral_street", "街頭螺旋", "street spiral", "螺、收、街頭", "spiral, close, street", "街頭質感的螺旋接近", "with street grit, spirals inward", "street-cast, spiral path"],
    ["spiral_noir", "暗黑螺旋", "noir spiral", "螺、收、暗黑", "spiral, close, noir", "暗調電影感的螺旋接近", "in noir lighting, spirals inward", "noir, spiral path"],
    ["spiral_soft", "柔光螺旋", "soft-light spiral", "螺、收、柔光", "spiral, close, soft", "柔光下的螺旋接近", "under soft light, spirals inward", "soft-lit, spiral path"],
    ["spiral_epic", "史詩螺旋", "epic spiral", "螺、收、史詩", "spiral, close, epic", "史詩尺度的螺旋接近", "at epic scale, spirals inward", "epic, spiral path"],
    ["stop_start_court", "宮廷停再衝", "court stop-start", "停、衝、宮廷", "stop, burst, courtly", "宮廷氣場下的完全停再衝", "in a courtly register, full stop then burst", "courtly, stop-start path"],
    ["stop_start_street", "街頭停再衝", "street stop-start", "停、衝、街頭", "stop, burst, street", "街頭質感的完全停再衝", "with street grit, full stop then burst", "street-cast, stop-start path"],
    ["stop_start_noir", "暗黑停再衝", "noir stop-start", "停、衝、暗黑", "stop, burst, noir", "暗調電影感的完全停再衝", "in noir lighting, full stop then burst", "noir, stop-start path"],
    ["stop_start_soft", "柔光停再衝", "soft-light stop-start", "停、衝、柔光", "stop, burst, soft", "柔光下的完全停再衝", "under soft light, full stop then burst", "soft-lit, stop-start path"],
    ["stop_start_epic", "史詩停再衝", "epic stop-start", "停、衝、史詩", "stop, burst, epic", "史詩尺度的完全停再衝", "at epic scale, full stop then burst", "epic, stop-start path"],
    ["wall_court", "宮廷借牆", "court wall-using", "牆、借、宮廷", "wall, use, courtly", "宮廷氣場下的路徑貼牆", "in a courtly register, path uses walls", "courtly, wall-using path"],
    ["wall_street", "街頭借牆", "street wall-using", "牆、借、街頭", "wall, use, street", "街頭質感的路徑貼牆", "with street grit, path uses walls", "street-cast, wall-using path"],
    ["wall_noir", "暗黑借牆", "noir wall-using", "牆、借、暗黑", "wall, use, noir", "暗調電影感的路徑貼牆", "in noir lighting, path uses walls", "noir, wall-using path"],
    ["wall_soft", "柔光借牆", "soft-light wall-using", "牆、借、柔光", "wall, use, soft", "柔光下的路徑貼牆", "under soft light, path uses walls", "soft-lit, wall-using path"],
    ["wall_epic", "史詩借牆", "epic wall-using", "牆、借、史詩", "wall, use, epic", "史詩尺度的路徑貼牆", "at epic scale, path uses walls", "epic, wall-using path"]
  ],
    tempo: [
    ["slowmo_court", "宮廷慢", "court slow-motion feel", "慢、重、宮廷", "slow, weight, courtly", "宮廷氣場下的像慢鏡", "in a courtly register, slow-motion feel", "courtly, slow-motion tempo"],
    ["slowmo_street", "街頭慢", "street slow-motion feel", "慢、重、街頭", "slow, weight, street", "街頭質感的像慢鏡", "with street grit, slow-motion feel", "street-cast, slow-motion tempo"],
    ["slowmo_noir", "暗黑慢", "noir slow-motion feel", "慢、重、暗黑", "slow, weight, noir", "暗調電影感的像慢鏡", "in noir lighting, slow-motion feel", "noir, slow-motion tempo"],
    ["slowmo_soft", "柔光慢", "soft-light slow-motion feel", "慢、重、柔光", "slow, weight, soft", "柔光下的像慢鏡", "under soft light, slow-motion feel", "soft-lit, slow-motion tempo"],
    ["slowmo_epic", "史詩慢", "epic slow-motion feel", "慢、重、史詩", "slow, weight, epic", "史詩尺度的像慢鏡", "at epic scale, slow-motion feel", "epic, slow-motion tempo"],
    ["walk_court", "宮廷步行速", "court walk tempo", "走、常、宮廷", "walk, normal, courtly", "宮廷氣場下的日常步速", "in a courtly register, everyday walk speed", "courtly, walk tempo"],
    ["walk_street", "街頭步行速", "street walk tempo", "走、常、街頭", "walk, normal, street", "街頭質感的日常步速", "with street grit, everyday walk speed", "street-cast, walk tempo"],
    ["walk_noir", "暗黑步行速", "noir walk tempo", "走、常、暗黑", "walk, normal, noir", "暗調電影感的日常步速", "in noir lighting, everyday walk speed", "noir, walk tempo"],
    ["walk_soft", "柔光步行速", "soft-light walk tempo", "走、常、柔光", "walk, normal, soft", "柔光下的日常步速", "under soft light, everyday walk speed", "soft-lit, walk tempo"],
    ["walk_epic", "史詩步行速", "epic walk tempo", "走、常、史詩", "walk, normal, epic", "史詩尺度的日常步速", "at epic scale, everyday walk speed", "epic, walk tempo"],
    ["hurry_court", "宮廷趕", "court hurried", "趕、喘、宮廷", "hurry, breath, courtly", "宮廷氣場下的明顯在趕", "in a courtly register, clearly hurried", "courtly, hurried tempo"],
    ["hurry_street", "街頭趕", "street hurried", "趕、喘、街頭", "hurry, breath, street", "街頭質感的明顯在趕", "with street grit, clearly hurried", "street-cast, hurried tempo"],
    ["hurry_noir", "暗黑趕", "noir hurried", "趕、喘、暗黑", "hurry, breath, noir", "暗調電影感的明顯在趕", "in noir lighting, clearly hurried", "noir, hurried tempo"],
    ["hurry_soft", "柔光趕", "soft-light hurried", "趕、喘、柔光", "hurry, breath, soft", "柔光下的明顯在趕", "under soft light, clearly hurried", "soft-lit, hurried tempo"],
    ["hurry_epic", "史詩趕", "epic hurried", "趕、喘、史詩", "hurry, breath, epic", "史詩尺度的明顯在趕", "at epic scale, clearly hurried", "epic, hurried tempo"],
    ["sprint_court", "宮廷衝刺", "court sprint", "刺、盡、宮廷", "sprint, max, courtly", "宮廷氣場下的接近衝刺", "in a courtly register, near sprint", "courtly, sprint tempo"],
    ["sprint_street", "街頭衝刺", "street sprint", "刺、盡、街頭", "sprint, max, street", "街頭質感的接近衝刺", "with street grit, near sprint", "street-cast, sprint tempo"],
    ["sprint_noir", "暗黑衝刺", "noir sprint", "刺、盡、暗黑", "sprint, max, noir", "暗調電影感的接近衝刺", "in noir lighting, near sprint", "noir, sprint tempo"],
    ["sprint_soft", "柔光衝刺", "soft-light sprint", "刺、盡、柔光", "sprint, max, soft", "柔光下的接近衝刺", "under soft light, near sprint", "soft-lit, sprint tempo"],
    ["sprint_epic", "史詩衝刺", "epic sprint", "刺、盡、史詩", "sprint, max, epic", "史詩尺度的接近衝刺", "at epic scale, near sprint", "epic, sprint tempo"],
    ["half_court", "宮廷半速壓", "court half-speed press", "半、壓、宮廷", "half, press, courtly", "宮廷氣場下的故意半速", "in a courtly register, deliberately half speed", "courtly, half-speed tempo"],
    ["half_street", "街頭半速壓", "street half-speed press", "半、壓、街頭", "half, press, street", "街頭質感的故意半速", "with street grit, deliberately half speed", "street-cast, half-speed tempo"],
    ["half_noir", "暗黑半速壓", "noir half-speed press", "半、壓、暗黑", "half, press, noir", "暗調電影感的故意半速", "in noir lighting, deliberately half speed", "noir, half-speed tempo"],
    ["half_soft", "柔光半速壓", "soft-light half-speed press", "半、壓、柔光", "half, press, soft", "柔光下的故意半速", "under soft light, deliberately half speed", "soft-lit, half-speed tempo"],
    ["half_epic", "史詩半速壓", "epic half-speed press", "半、壓、史詩", "half, press, epic", "史詩尺度的故意半速", "at epic scale, deliberately half speed", "epic, half-speed tempo"],
    ["accel_court", "宮廷越後越快", "court accelerating", "加、後、宮廷", "accel, late, courtly", "宮廷氣場下的後面加快", "in a courtly register, speeds up late", "courtly, accelerating tempo"],
    ["accel_street", "街頭越後越快", "street accelerating", "加、後、街頭", "accel, late, street", "街頭質感的後面加快", "with street grit, speeds up late", "street-cast, accelerating tempo"],
    ["accel_noir", "暗黑越後越快", "noir accelerating", "加、後、暗黑", "accel, late, noir", "暗調電影感的後面加快", "in noir lighting, speeds up late", "noir, accelerating tempo"],
    ["accel_soft", "柔光越後越快", "soft-light accelerating", "加、後、柔光", "accel, late, soft", "柔光下的後面加快", "under soft light, speeds up late", "soft-lit, accelerating tempo"],
    ["accel_epic", "史詩越後越快", "epic accelerating", "加、後、史詩", "accel, late, epic", "史詩尺度的後面加快", "at epic scale, speeds up late", "epic, accelerating tempo"],
    ["decel_court", "宮廷越後越慢", "court decelerating", "減、沉、宮廷", "decel, sink, courtly", "宮廷氣場下的後面沉慢", "in a courtly register, slows and sinks", "courtly, decelerating tempo"],
    ["decel_street", "街頭越後越慢", "street decelerating", "減、沉、街頭", "decel, sink, street", "街頭質感的後面沉慢", "with street grit, slows and sinks", "street-cast, decelerating tempo"],
    ["decel_noir", "暗黑越後越慢", "noir decelerating", "減、沉、暗黑", "decel, sink, noir", "暗調電影感的後面沉慢", "in noir lighting, slows and sinks", "noir, decelerating tempo"],
    ["decel_soft", "柔光越後越慢", "soft-light decelerating", "減、沉、柔光", "decel, sink, soft", "柔光下的後面沉慢", "under soft light, slows and sinks", "soft-lit, decelerating tempo"],
    ["decel_epic", "史詩越後越慢", "epic decelerating", "減、沉、史詩", "decel, sink, epic", "史詩尺度的後面沉慢", "at epic scale, slows and sinks", "epic, decelerating tempo"],
    ["syncopate_court", "宮廷切分", "court syncopated", "切、錯、宮廷", "sync, offbeat, courtly", "宮廷氣場下的不在正拍", "in a courtly register, off the downbeat", "courtly, syncopated tempo"],
    ["syncopate_street", "街頭切分", "street syncopated", "切、錯、街頭", "sync, offbeat, street", "街頭質感的不在正拍", "with street grit, off the downbeat", "street-cast, syncopated tempo"],
    ["syncopate_noir", "暗黑切分", "noir syncopated", "切、錯、暗黑", "sync, offbeat, noir", "暗調電影感的不在正拍", "in noir lighting, off the downbeat", "noir, syncopated tempo"],
    ["syncopate_soft", "柔光切分", "soft-light syncopated", "切、錯、柔光", "sync, offbeat, soft", "柔光下的不在正拍", "under soft light, off the downbeat", "soft-lit, syncopated tempo"],
    ["syncopate_epic", "史詩切分", "epic syncopated", "切、錯、史詩", "sync, offbeat, epic", "史詩尺度的不在正拍", "at epic scale, off the downbeat", "epic, syncopated tempo"],
    ["freeze_court", "宮廷中間凍", "court mid-freeze", "凍、劇、宮廷", "freeze, drama, courtly", "宮廷氣場下的中段完全凍", "in a courtly register, full mid freeze", "courtly, mid-freeze tempo"],
    ["freeze_street", "街頭中間凍", "street mid-freeze", "凍、劇、街頭", "freeze, drama, street", "街頭質感的中段完全凍", "with street grit, full mid freeze", "street-cast, mid-freeze tempo"],
    ["freeze_noir", "暗黑中間凍", "noir mid-freeze", "凍、劇、暗黑", "freeze, drama, noir", "暗調電影感的中段完全凍", "in noir lighting, full mid freeze", "noir, mid-freeze tempo"],
    ["freeze_soft", "柔光中間凍", "soft-light mid-freeze", "凍、劇、柔光", "freeze, drama, soft", "柔光下的中段完全凍", "under soft light, full mid freeze", "soft-lit, mid-freeze tempo"],
    ["freeze_epic", "史詩中間凍", "epic mid-freeze", "凍、劇、史詩", "freeze, drama, epic", "史詩尺度的中段完全凍", "at epic scale, full mid freeze", "epic, mid-freeze tempo"],
    ["machine_court", "宮廷節拍器", "court metronomic", "均、機、宮廷", "even, machine, courtly", "宮廷氣場下的等速機械", "in a courtly register, even machine time", "courtly, metronomic tempo"],
    ["machine_street", "街頭節拍器", "street metronomic", "均、機、街頭", "even, machine, street", "街頭質感的等速機械", "with street grit, even machine time", "street-cast, metronomic tempo"],
    ["machine_noir", "暗黑節拍器", "noir metronomic", "均、機、暗黑", "even, machine, noir", "暗調電影感的等速機械", "in noir lighting, even machine time", "noir, metronomic tempo"],
    ["machine_soft", "柔光節拍器", "soft-light metronomic", "均、機、柔光", "even, machine, soft", "柔光下的等速機械", "under soft light, even machine time", "soft-lit, metronomic tempo"],
    ["machine_epic", "史詩節拍器", "epic metronomic", "均、機、史詩", "even, machine, epic", "史詩尺度的等速機械", "at epic scale, even machine time", "epic, metronomic tempo"]
  ],
    weight: [
    ["feather_court", "宮廷羽", "court feather", "羽、無、宮廷", "feather, none, courtly", "宮廷氣場下的幾乎無重量", "in a courtly register, almost no weight", "courtly, feather weight"],
    ["feather_street", "街頭羽", "street feather", "羽、無、街頭", "feather, none, street", "街頭質感的幾乎無重量", "with street grit, almost no weight", "street-cast, feather weight"],
    ["feather_noir", "暗黑羽", "noir feather", "羽、無、暗黑", "feather, none, noir", "暗調電影感的幾乎無重量", "in noir lighting, almost no weight", "noir, feather weight"],
    ["feather_soft", "柔光羽", "soft-light feather", "羽、無、柔光", "feather, none, soft", "柔光下的幾乎無重量", "under soft light, almost no weight", "soft-lit, feather weight"],
    ["feather_epic", "史詩羽", "epic feather", "羽、無、史詩", "feather, none, epic", "史詩尺度的幾乎無重量", "at epic scale, almost no weight", "epic, feather weight"],
    ["light_court", "宮廷輕", "court light", "輕、靈、宮廷", "light, nimble, courtly", "宮廷氣場下的偏輕", "in a courtly register, on the light side", "courtly, light weight"],
    ["light_street", "街頭輕", "street light", "輕、靈、街頭", "light, nimble, street", "街頭質感的偏輕", "with street grit, on the light side", "street-cast, light weight"],
    ["light_noir", "暗黑輕", "noir light", "輕、靈、暗黑", "light, nimble, noir", "暗調電影感的偏輕", "in noir lighting, on the light side", "noir, light weight"],
    ["light_soft", "柔光輕", "soft-light light", "輕、靈、柔光", "light, nimble, soft", "柔光下的偏輕", "under soft light, on the light side", "soft-lit, light weight"],
    ["light_epic", "史詩輕", "epic light", "輕、靈、史詩", "light, nimble, epic", "史詩尺度的偏輕", "at epic scale, on the light side", "epic, light weight"],
    ["neutral_court", "宮廷中", "court neutral", "中、人、宮廷", "mid, human, courtly", "宮廷氣場下的正常人體重", "in a courtly register, normal human weight", "courtly, neutral weight"],
    ["neutral_street", "街頭中", "street neutral", "中、人、街頭", "mid, human, street", "街頭質感的正常人體重", "with street grit, normal human weight", "street-cast, neutral weight"],
    ["neutral_noir", "暗黑中", "noir neutral", "中、人、暗黑", "mid, human, noir", "暗調電影感的正常人體重", "in noir lighting, normal human weight", "noir, neutral weight"],
    ["neutral_soft", "柔光中", "soft-light neutral", "中、人、柔光", "mid, human, soft", "柔光下的正常人體重", "under soft light, normal human weight", "soft-lit, neutral weight"],
    ["neutral_epic", "史詩中", "epic neutral", "中、人、史詩", "mid, human, epic", "史詩尺度的正常人體重", "at epic scale, normal human weight", "epic, neutral weight"],
    ["heavy_court", "宮廷重", "court heavy", "重、墜、宮廷", "heavy, sink, courtly", "宮廷氣場下的明顯偏重", "in a courtly register, clearly heavy", "courtly, heavy weight"],
    ["heavy_street", "街頭重", "street heavy", "重、墜、街頭", "heavy, sink, street", "街頭質感的明顯偏重", "with street grit, clearly heavy", "street-cast, heavy weight"],
    ["heavy_noir", "暗黑重", "noir heavy", "重、墜、暗黑", "heavy, sink, noir", "暗調電影感的明顯偏重", "in noir lighting, clearly heavy", "noir, heavy weight"],
    ["heavy_soft", "柔光重", "soft-light heavy", "重、墜、柔光", "heavy, sink, soft", "柔光下的明顯偏重", "under soft light, clearly heavy", "soft-lit, heavy weight"],
    ["heavy_epic", "史詩重", "epic heavy", "重、墜、史詩", "heavy, sink, epic", "史詩尺度的明顯偏重", "at epic scale, clearly heavy", "epic, heavy weight"],
    ["lead_court", "宮廷鉛", "court lead", "鉛、拖、宮廷", "lead, drag, courtly", "宮廷氣場下的像灌鉛", "in a courtly register, as if lead-filled", "courtly, lead weight"],
    ["lead_street", "街頭鉛", "street lead", "鉛、拖、街頭", "lead, drag, street", "街頭質感的像灌鉛", "with street grit, as if lead-filled", "street-cast, lead weight"],
    ["lead_noir", "暗黑鉛", "noir lead", "鉛、拖、暗黑", "lead, drag, noir", "暗調電影感的像灌鉛", "in noir lighting, as if lead-filled", "noir, lead weight"],
    ["lead_soft", "柔光鉛", "soft-light lead", "鉛、拖、柔光", "lead, drag, soft", "柔光下的像灌鉛", "under soft light, as if lead-filled", "soft-lit, lead weight"],
    ["lead_epic", "史詩鉛", "epic lead", "鉛、拖、史詩", "lead, drag, epic", "史詩尺度的像灌鉛", "at epic scale, as if lead-filled", "epic, lead weight"],
    ["uneven_court", "宮廷一側重", "court uneven", "偏、跛、宮廷", "uneven, limp, courtly", "宮廷氣場下的左右重量不均", "in a courtly register, uneven left-right weight", "courtly, uneven weight"],
    ["uneven_street", "街頭一側重", "street uneven", "偏、跛、街頭", "uneven, limp, street", "街頭質感的左右重量不均", "with street grit, uneven left-right weight", "street-cast, uneven weight"],
    ["uneven_noir", "暗黑一側重", "noir uneven", "偏、跛、暗黑", "uneven, limp, noir", "暗調電影感的左右重量不均", "in noir lighting, uneven left-right weight", "noir, uneven weight"],
    ["uneven_soft", "柔光一側重", "soft-light uneven", "偏、跛、柔光", "uneven, limp, soft", "柔光下的左右重量不均", "under soft light, uneven left-right weight", "soft-lit, uneven weight"],
    ["uneven_epic", "史詩一側重", "epic uneven", "偏、跛、史詩", "uneven, limp, epic", "史詩尺度的左右重量不均", "at epic scale, uneven left-right weight", "epic, uneven weight"],
    ["impact_court", "宮廷著地重", "court heavy landings", "著、震、宮廷", "land, thud, courtly", "宮廷氣場下的落地特別重", "in a courtly register, landings thud", "courtly, heavy-landing weight"],
    ["impact_street", "街頭著地重", "street heavy landings", "著、震、街頭", "land, thud, street", "街頭質感的落地特別重", "with street grit, landings thud", "street-cast, heavy-landing weight"],
    ["impact_noir", "暗黑著地重", "noir heavy landings", "著、震、暗黑", "land, thud, noir", "暗調電影感的落地特別重", "in noir lighting, landings thud", "noir, heavy-landing weight"],
    ["impact_soft", "柔光著地重", "soft-light heavy landings", "著、震、柔光", "land, thud, soft", "柔光下的落地特別重", "under soft light, landings thud", "soft-lit, heavy-landing weight"],
    ["impact_epic", "史詩著地重", "epic heavy landings", "著、震、史詩", "land, thud, epic", "史詩尺度的落地特別重", "at epic scale, landings thud", "epic, heavy-landing weight"],
    ["hover_court", "宮廷似不著地", "court hovering", "懸、幻、宮廷", "hover, unreal, courtly", "宮廷氣場下的落地聲極輕", "in a courtly register, almost no landing sound", "courtly, hovering weight"],
    ["hover_street", "街頭似不著地", "street hovering", "懸、幻、街頭", "hover, unreal, street", "街頭質感的落地聲極輕", "with street grit, almost no landing sound", "street-cast, hovering weight"],
    ["hover_noir", "暗黑似不著地", "noir hovering", "懸、幻、暗黑", "hover, unreal, noir", "暗調電影感的落地聲極輕", "in noir lighting, almost no landing sound", "noir, hovering weight"],
    ["hover_soft", "柔光似不著地", "soft-light hovering", "懸、幻、柔光", "hover, unreal, soft", "柔光下的落地聲極輕", "under soft light, almost no landing sound", "soft-lit, hovering weight"],
    ["hover_epic", "史詩似不著地", "epic hovering", "懸、幻、史詩", "hover, unreal, epic", "史詩尺度的落地聲極輕", "at epic scale, almost no landing sound", "epic, hovering weight"],
    ["carry_court", "宮廷負重", "court encumbered", "負、慢、宮廷", "carry, slow, courtly", "宮廷氣場下的像扛著東西", "in a courtly register, as if carrying a load", "courtly, encumbered weight"],
    ["carry_street", "街頭負重", "street encumbered", "負、慢、街頭", "carry, slow, street", "街頭質感的像扛著東西", "with street grit, as if carrying a load", "street-cast, encumbered weight"],
    ["carry_noir", "暗黑負重", "noir encumbered", "負、慢、暗黑", "carry, slow, noir", "暗調電影感的像扛著東西", "in noir lighting, as if carrying a load", "noir, encumbered weight"],
    ["carry_soft", "柔光負重", "soft-light encumbered", "負、慢、柔光", "carry, slow, soft", "柔光下的像扛著東西", "under soft light, as if carrying a load", "soft-lit, encumbered weight"],
    ["carry_epic", "史詩負重", "epic encumbered", "負、慢、史詩", "carry, slow, epic", "史詩尺度的像扛著東西", "at epic scale, as if carrying a load", "epic, encumbered weight"],
    ["shift_court", "宮廷重量 vis 轉移", "court visible weight shift", "移、看、宮廷", "shift, see, courtly", "宮廷氣場下的重心轉移看得見", "in a courtly register, weight shifts read clearly", "courtly, visible weight-shift"],
    ["shift_street", "街頭重量 vis 轉移", "street visible weight shift", "移、看、街頭", "shift, see, street", "街頭質感的重心轉移看得見", "with street grit, weight shifts read clearly", "street-cast, visible weight-shift"],
    ["shift_noir", "暗黑重量 vis 轉移", "noir visible weight shift", "移、看、暗黑", "shift, see, noir", "暗調電影感的重心轉移看得見", "in noir lighting, weight shifts read clearly", "noir, visible weight-shift"],
    ["shift_soft", "柔光重量 vis 轉移", "soft-light visible weight shift", "移、看、柔光", "shift, see, soft", "柔光下的重心轉移看得見", "under soft light, weight shifts read clearly", "soft-lit, visible weight-shift"],
    ["shift_epic", "史詩重量 vis 轉移", "epic visible weight shift", "移、看、史詩", "shift, see, epic", "史詩尺度的重心轉移看得見", "at epic scale, weight shifts read clearly", "epic, visible weight-shift"]
  ]
  }
})
