/**
 * propLook field kit catalog (50+ templates per part).
 */
import { defineFieldKit } from '../fieldKit'

export const PROPLOOK_KIT = defineFieldKit({
  key: "propLookKit",
  parts: ["form","era","material","condition","scale","ornament"] as const,
  partLabels: {
    form: { zhHK: "形", zhCN: "形", en: "Form" },
    era: { zhHK: "年代", zhCN: "年代", en: "Era" },
    material: { zhHK: "材質", zhCN: "材质", en: "Material" },
    condition: { zhHK: "狀態", zhCN: "状态", en: "Condition" },
    scale: { zhHK: "尺度", zhCN: "尺度", en: "Scale" },
    ornament: { zhHK: "紋飾", zhCN: "纹饰", en: "Ornament" }
  },

  rows: {
    form: [
    ["box_court", "宮廷方盒", "court boxy", "方、穩、宮廷", "box, steady, courtly", "宮廷氣場下的方正盒形", "in a courtly register, rectilinear box form", "courtly, boxy form"],
    ["box_street", "街頭方盒", "street boxy", "方、穩、街頭", "box, steady, street", "街頭質感的方正盒形", "with street grit, rectilinear box form", "street-cast, boxy form"],
    ["box_noir", "暗黑方盒", "noir boxy", "方、穩、暗黑", "box, steady, noir", "暗調電影感的方正盒形", "in noir lighting, rectilinear box form", "noir, boxy form"],
    ["box_soft", "柔光方盒", "soft-light boxy", "方、穩、柔光", "box, steady, soft", "柔光下的方正盒形", "under soft light, rectilinear box form", "soft-lit, boxy form"],
    ["box_epic", "史詩方盒", "epic boxy", "方、穩、史詩", "box, steady, epic", "史詩尺度的方正盒形", "at epic scale, rectilinear box form", "epic, boxy form"],
    ["blade_court", "宮廷刃形", "court blade", "刃、利、宮廷", "blade, edge, courtly", "宮廷氣場下的薄而利", "in a courtly register, thin edged form", "courtly, blade form"],
    ["blade_street", "街頭刃形", "street blade", "刃、利、街頭", "blade, edge, street", "街頭質感的薄而利", "with street grit, thin edged form", "street-cast, blade form"],
    ["blade_noir", "暗黑刃形", "noir blade", "刃、利、暗黑", "blade, edge, noir", "暗調電影感的薄而利", "in noir lighting, thin edged form", "noir, blade form"],
    ["blade_soft", "柔光刃形", "soft-light blade", "刃、利、柔光", "blade, edge, soft", "柔光下的薄而利", "under soft light, thin edged form", "soft-lit, blade form"],
    ["blade_epic", "史詩刃形", "epic blade", "刃、利、史詩", "blade, edge, epic", "史詩尺度的薄而利", "at epic scale, thin edged form", "epic, blade form"],
    ["orb_court", "宮廷球", "court orb", "球、完、宮廷", "orb, complete, courtly", "宮廷氣場下的近球形", "in a courtly register, near-spherical", "courtly, orb form"],
    ["orb_street", "街頭球", "street orb", "球、完、街頭", "orb, complete, street", "街頭質感的近球形", "with street grit, near-spherical", "street-cast, orb form"],
    ["orb_noir", "暗黑球", "noir orb", "球、完、暗黑", "orb, complete, noir", "暗調電影感的近球形", "in noir lighting, near-spherical", "noir, orb form"],
    ["orb_soft", "柔光球", "soft-light orb", "球、完、柔光", "orb, complete, soft", "柔光下的近球形", "under soft light, near-spherical", "soft-lit, orb form"],
    ["orb_epic", "史詩球", "epic orb", "球、完、史詩", "orb, complete, epic", "史詩尺度的近球形", "at epic scale, near-spherical", "epic, orb form"],
    ["tube_court", "宮廷管", "court tube", "管、長、宮廷", "tube, long, courtly", "宮廷氣場下的細長管", "in a courtly register, long thin tube", "courtly, tube form"],
    ["tube_street", "街頭管", "street tube", "管、長、街頭", "tube, long, street", "街頭質感的細長管", "with street grit, long thin tube", "street-cast, tube form"],
    ["tube_noir", "暗黑管", "noir tube", "管、長、暗黑", "tube, long, noir", "暗調電影感的細長管", "in noir lighting, long thin tube", "noir, tube form"],
    ["tube_soft", "柔光管", "soft-light tube", "管、長、柔光", "tube, long, soft", "柔光下的細長管", "under soft light, long thin tube", "soft-lit, tube form"],
    ["tube_epic", "史詩管", "epic tube", "管、長、史詩", "tube, long, epic", "史詩尺度的細長管", "at epic scale, long thin tube", "epic, tube form"],
    ["fold_court", "宮廷可摺", "court folding", "摺、變、宮廷", "fold, change, courtly", "宮廷氣場下的可摺結構", "in a courtly register, folding structure", "courtly, folding form"],
    ["fold_street", "街頭可摺", "street folding", "摺、變、街頭", "fold, change, street", "街頭質感的可摺結構", "with street grit, folding structure", "street-cast, folding form"],
    ["fold_noir", "暗黑可摺", "noir folding", "摺、變、暗黑", "fold, change, noir", "暗調電影感的可摺結構", "in noir lighting, folding structure", "noir, folding form"],
    ["fold_soft", "柔光可摺", "soft-light folding", "摺、變、柔光", "fold, change, soft", "柔光下的可摺結構", "under soft light, folding structure", "soft-lit, folding form"],
    ["fold_epic", "史詩可摺", "epic folding", "摺、變、史詩", "fold, change, epic", "史詩尺度的可摺結構", "at epic scale, folding structure", "epic, folding form"],
    ["organic_court", "宮廷有機不規則", "court organic irregular", "有機、不規則、宮廷", "organic, irregular, courtly", "宮廷氣場下的非幾何有機", "in a courtly register, non-geometric organic", "courtly, organic irregular form"],
    ["organic_street", "街頭有機不規則", "street organic irregular", "有機、不規則、街頭", "organic, irregular, street", "街頭質感的非幾何有機", "with street grit, non-geometric organic", "street-cast, organic irregular form"],
    ["organic_noir", "暗黑有機不規則", "noir organic irregular", "有機、不規則、暗黑", "organic, irregular, noir", "暗調電影感的非幾何有機", "in noir lighting, non-geometric organic", "noir, organic irregular form"],
    ["organic_soft", "柔光有機不規則", "soft-light organic irregular", "有機、不規則、柔光", "organic, irregular, soft", "柔光下的非幾何有機", "under soft light, non-geometric organic", "soft-lit, organic irregular form"],
    ["organic_epic", "史詩有機不規則", "epic organic irregular", "有機、不規則、史詩", "organic, irregular, epic", "史詩尺度的非幾何有機", "at epic scale, non-geometric organic", "epic, organic irregular form"],
    ["stack_court", "宮廷層疊", "court stacked", "疊、層、宮廷", "stack, layer, courtly", "宮廷氣場下的多層疊", "in a courtly register, stacked layers", "courtly, stacked form"],
    ["stack_street", "街頭層疊", "street stacked", "疊、層、街頭", "stack, layer, street", "街頭質感的多層疊", "with street grit, stacked layers", "street-cast, stacked form"],
    ["stack_noir", "暗黑層疊", "noir stacked", "疊、層、暗黑", "stack, layer, noir", "暗調電影感的多層疊", "in noir lighting, stacked layers", "noir, stacked form"],
    ["stack_soft", "柔光層疊", "soft-light stacked", "疊、層、柔光", "stack, layer, soft", "柔光下的多層疊", "under soft light, stacked layers", "soft-lit, stacked form"],
    ["stack_epic", "史詩層疊", "epic stacked", "疊、層、史詩", "stack, layer, epic", "史詩尺度的多層疊", "at epic scale, stacked layers", "epic, stacked form"],
    ["ring_court", "宮廷環", "court ring", "環、圈、宮廷", "ring, loop, courtly", "宮廷氣場下的中空環", "in a courtly register, hollow ring", "courtly, ring form"],
    ["ring_street", "街頭環", "street ring", "環、圈、街頭", "ring, loop, street", "街頭質感的中空環", "with street grit, hollow ring", "street-cast, ring form"],
    ["ring_noir", "暗黑環", "noir ring", "環、圈、暗黑", "ring, loop, noir", "暗調電影感的中空環", "in noir lighting, hollow ring", "noir, ring form"],
    ["ring_soft", "柔光環", "soft-light ring", "環、圈、柔光", "ring, loop, soft", "柔光下的中空環", "under soft light, hollow ring", "soft-lit, ring form"],
    ["ring_epic", "史詩環", "epic ring", "環、圈、史詩", "ring, loop, epic", "史詩尺度的中空環", "at epic scale, hollow ring", "epic, ring form"],
    ["tablet_court", "宮廷板", "court tablet", "板、平、宮廷", "slab, flat, courtly", "宮廷氣場下的薄平板", "in a courtly register, flat slab", "courtly, tablet form"],
    ["tablet_street", "街頭板", "street tablet", "板、平、街頭", "slab, flat, street", "街頭質感的薄平板", "with street grit, flat slab", "street-cast, tablet form"],
    ["tablet_noir", "暗黑板", "noir tablet", "板、平、暗黑", "slab, flat, noir", "暗調電影感的薄平板", "in noir lighting, flat slab", "noir, tablet form"],
    ["tablet_soft", "柔光板", "soft-light tablet", "板、平、柔光", "slab, flat, soft", "柔光下的薄平板", "under soft light, flat slab", "soft-lit, tablet form"],
    ["tablet_epic", "史詩板", "epic tablet", "板、平、史詩", "slab, flat, epic", "史詩尺度的薄平板", "at epic scale, flat slab", "epic, tablet form"],
    ["cluster_court", "宮廷簇", "court cluster", "簇、多、宮廷", "cluster, many, courtly", "宮廷氣場下的多件成簇", "in a courtly register, cluster of pieces", "courtly, cluster form"],
    ["cluster_street", "街頭簇", "street cluster", "簇、多、街頭", "cluster, many, street", "街頭質感的多件成簇", "with street grit, cluster of pieces", "street-cast, cluster form"],
    ["cluster_noir", "暗黑簇", "noir cluster", "簇、多、暗黑", "cluster, many, noir", "暗調電影感的多件成簇", "in noir lighting, cluster of pieces", "noir, cluster form"],
    ["cluster_soft", "柔光簇", "soft-light cluster", "簇、多、柔光", "cluster, many, soft", "柔光下的多件成簇", "under soft light, cluster of pieces", "soft-lit, cluster form"],
    ["cluster_epic", "史詩簇", "epic cluster", "簇、多、史詩", "cluster, many, epic", "史詩尺度的多件成簇", "at epic scale, cluster of pieces", "epic, cluster form"]
  ],
    era: [
    ["bronze_court", "宮廷青銅古", "court bronze-age", "銅、古、宮廷", "bronze, ancient, courtly", "宮廷氣場下的青銅時代感", "in a courtly register, bronze-age feel", "courtly, bronze-age prop era"],
    ["bronze_street", "街頭青銅古", "street bronze-age", "銅、古、街頭", "bronze, ancient, street", "街頭質感的青銅時代感", "with street grit, bronze-age feel", "street-cast, bronze-age prop era"],
    ["bronze_noir", "暗黑青銅古", "noir bronze-age", "銅、古、暗黑", "bronze, ancient, noir", "暗調電影感的青銅時代感", "in noir lighting, bronze-age feel", "noir, bronze-age prop era"],
    ["bronze_soft", "柔光青銅古", "soft-light bronze-age", "銅、古、柔光", "bronze, ancient, soft", "柔光下的青銅時代感", "under soft light, bronze-age feel", "soft-lit, bronze-age prop era"],
    ["bronze_epic", "史詩青銅古", "epic bronze-age", "銅、古、史詩", "bronze, ancient, epic", "史詩尺度的青銅時代感", "at epic scale, bronze-age feel", "epic, bronze-age prop era"],
    ["dynastic_court", "宮廷帝制工藝", "court dynastic craft", "帝、工、宮廷", "dynastic, craft, courtly", "宮廷氣場下的帝制作坊感", "in a courtly register, imperial workshop feel", "courtly, dynastic prop era"],
    ["dynastic_street", "街頭帝制工藝", "street dynastic craft", "帝、工、街頭", "dynastic, craft, street", "街頭質感的帝制作坊感", "with street grit, imperial workshop feel", "street-cast, dynastic prop era"],
    ["dynastic_noir", "暗黑帝制工藝", "noir dynastic craft", "帝、工、暗黑", "dynastic, craft, noir", "暗調電影感的帝制作坊感", "in noir lighting, imperial workshop feel", "noir, dynastic prop era"],
    ["dynastic_soft", "柔光帝制工藝", "soft-light dynastic craft", "帝、工、柔光", "dynastic, craft, soft", "柔光下的帝制作坊感", "under soft light, imperial workshop feel", "soft-lit, dynastic prop era"],
    ["dynastic_epic", "史詩帝制工藝", "epic dynastic craft", "帝、工、史詩", "dynastic, craft, epic", "史詩尺度的帝制作坊感", "at epic scale, imperial workshop feel", "epic, dynastic prop era"],
    ["republic_court", "宮廷民國洋貨", "court Republican import", "民國、洋、宮廷", "republic, import, courtly", "宮廷氣場下的民國洋貨", "in a courtly register, Republican imported goods", "courtly, Republican prop era"],
    ["republic_street", "街頭民國洋貨", "street Republican import", "民國、洋、街頭", "republic, import, street", "街頭質感的民國洋貨", "with street grit, Republican imported goods", "street-cast, Republican prop era"],
    ["republic_noir", "暗黑民國洋貨", "noir Republican import", "民國、洋、暗黑", "republic, import, noir", "暗調電影感的民國洋貨", "in noir lighting, Republican imported goods", "noir, Republican prop era"],
    ["republic_soft", "柔光民國洋貨", "soft-light Republican import", "民國、洋、柔光", "republic, import, soft", "柔光下的民國洋貨", "under soft light, Republican imported goods", "soft-lit, Republican prop era"],
    ["republic_epic", "史詩民國洋貨", "epic Republican import", "民國、洋、史詩", "republic, import, epic", "史詩尺度的民國洋貨", "at epic scale, Republican imported goods", "epic, Republican prop era"],
    ["industrial_court", "宮廷工業革命", "court industrial", "工、鐵、宮廷", "industrial, iron, courtly", "宮廷氣場下的鑄鐵工業", "in a courtly register, cast-iron industrial", "courtly, industrial prop era"],
    ["industrial_street", "街頭工業革命", "street industrial", "工、鐵、街頭", "industrial, iron, street", "街頭質感的鑄鐵工業", "with street grit, cast-iron industrial", "street-cast, industrial prop era"],
    ["industrial_noir", "暗黑工業革命", "noir industrial", "工、鐵、暗黑", "industrial, iron, noir", "暗調電影感的鑄鐵工業", "in noir lighting, cast-iron industrial", "noir, industrial prop era"],
    ["industrial_soft", "柔光工業革命", "soft-light industrial", "工、鐵、柔光", "industrial, iron, soft", "柔光下的鑄鐵工業", "under soft light, cast-iron industrial", "soft-lit, industrial prop era"],
    ["industrial_epic", "史詩工業革命", "epic industrial", "工、鐵、史詩", "industrial, iron, epic", "史詩尺度的鑄鐵工業", "at epic scale, cast-iron industrial", "epic, industrial prop era"],
    ["80s_plastic_court", "宮廷八十塑", "court 1980s plastic", "八十、塑、宮廷", "80s, plastic, courtly", "宮廷氣場下的八十年代塑膠", "in a courtly register, 1980s plastic goods", "courtly, 1980s prop era"],
    ["80s_plastic_street", "街頭八十塑", "street 1980s plastic", "八十、塑、街頭", "80s, plastic, street", "街頭質感的八十年代塑膠", "with street grit, 1980s plastic goods", "street-cast, 1980s prop era"],
    ["80s_plastic_noir", "暗黑八十塑", "noir 1980s plastic", "八十、塑、暗黑", "80s, plastic, noir", "暗調電影感的八十年代塑膠", "in noir lighting, 1980s plastic goods", "noir, 1980s prop era"],
    ["80s_plastic_soft", "柔光八十塑", "soft-light 1980s plastic", "八十、塑、柔光", "80s, plastic, soft", "柔光下的八十年代塑膠", "under soft light, 1980s plastic goods", "soft-lit, 1980s prop era"],
    ["80s_plastic_epic", "史詩八十塑", "epic 1980s plastic", "八十、塑、史詩", "80s, plastic, epic", "史詩尺度的八十年代塑膠", "at epic scale, 1980s plastic goods", "epic, 1980s prop era"],
    ["now_consumer_court", "宮廷當代消費", "court current consumer", "當、消、宮廷", "now, consumer, courtly", "宮廷氣場下的當下消費品", "in a courtly register, current consumer good", "courtly, contemporary prop era"],
    ["now_consumer_street", "街頭當代消費", "street current consumer", "當、消、街頭", "now, consumer, street", "街頭質感的當下消費品", "with street grit, current consumer good", "street-cast, contemporary prop era"],
    ["now_consumer_noir", "暗黑當代消費", "noir current consumer", "當、消、暗黑", "now, consumer, noir", "暗調電影感的當下消費品", "in noir lighting, current consumer good", "noir, contemporary prop era"],
    ["now_consumer_soft", "柔光當代消費", "soft-light current consumer", "當、消、柔光", "now, consumer, soft", "柔光下的當下消費品", "under soft light, current consumer good", "soft-lit, contemporary prop era"],
    ["now_consumer_epic", "史詩當代消費", "epic current consumer", "當、消、史詩", "now, consumer, epic", "史詩尺度的當下消費品", "at epic scale, current consumer good", "epic, contemporary prop era"],
    ["mil_spec_court", "宮廷軍規現", "court modern mil-spec", "軍、現、宮廷", "mil, now, courtly", "宮廷氣場下的現代軍規", "in a courtly register, modern mil-spec", "courtly, mil-spec prop era"],
    ["mil_spec_street", "街頭軍規現", "street modern mil-spec", "軍、現、街頭", "mil, now, street", "街頭質感的現代軍規", "with street grit, modern mil-spec", "street-cast, mil-spec prop era"],
    ["mil_spec_noir", "暗黑軍規現", "noir modern mil-spec", "軍、現、暗黑", "mil, now, noir", "暗調電影感的現代軍規", "in noir lighting, modern mil-spec", "noir, mil-spec prop era"],
    ["mil_spec_soft", "柔光軍規現", "soft-light modern mil-spec", "軍、現、柔光", "mil, now, soft", "柔光下的現代軍規", "under soft light, modern mil-spec", "soft-lit, mil-spec prop era"],
    ["mil_spec_epic", "史詩軍規現", "epic modern mil-spec", "軍、現、史詩", "mil, now, epic", "史詩尺度的現代軍規", "at epic scale, modern mil-spec", "epic, mil-spec prop era"],
    ["far_scifi_court", "宮廷遠科幻", "court far scifi", "科、遠、宮廷", "scifi, far, courtly", "宮廷氣場下的遠未來工業", "in a courtly register, far-future industry", "courtly, far-scifi prop era"],
    ["far_scifi_street", "街頭遠科幻", "street far scifi", "科、遠、街頭", "scifi, far, street", "街頭質感的遠未來工業", "with street grit, far-future industry", "street-cast, far-scifi prop era"],
    ["far_scifi_noir", "暗黑遠科幻", "noir far scifi", "科、遠、暗黑", "scifi, far, noir", "暗調電影感的遠未來工業", "in noir lighting, far-future industry", "noir, far-scifi prop era"],
    ["far_scifi_soft", "柔光遠科幻", "soft-light far scifi", "科、遠、柔光", "scifi, far, soft", "柔光下的遠未來工業", "under soft light, far-future industry", "soft-lit, far-scifi prop era"],
    ["far_scifi_epic", "史詩遠科幻", "epic far scifi", "科、遠、史詩", "scifi, far, epic", "史詩尺度的遠未來工業", "at epic scale, far-future industry", "epic, far-scifi prop era"],
    ["handmade_court", "宮廷手作無年", "court timeless handmade", "手、無年、宮廷", "hand, timeless, courtly", "宮廷氣場下的看不出年代的手作", "in a courtly register, undated handmade", "courtly, timeless handmade era"],
    ["handmade_street", "街頭手作無年", "street timeless handmade", "手、無年、街頭", "hand, timeless, street", "街頭質感的看不出年代的手作", "with street grit, undated handmade", "street-cast, timeless handmade era"],
    ["handmade_noir", "暗黑手作無年", "noir timeless handmade", "手、無年、暗黑", "hand, timeless, noir", "暗調電影感的看不出年代的手作", "in noir lighting, undated handmade", "noir, timeless handmade era"],
    ["handmade_soft", "柔光手作無年", "soft-light timeless handmade", "手、無年、柔光", "hand, timeless, soft", "柔光下的看不出年代的手作", "under soft light, undated handmade", "soft-lit, timeless handmade era"],
    ["handmade_epic", "史詩手作無年", "epic timeless handmade", "手、無年、史詩", "hand, timeless, epic", "史詩尺度的看不出年代的手作", "at epic scale, undated handmade", "epic, timeless handmade era"],
    ["anachron_court", "宮廷錯代", "court anachronistic", "錯、疊、宮廷", "wrong, stack, courtly", "宮廷氣場下的不該出現的年代", "in a courtly register, wrong-era object", "courtly, anachronistic prop era"],
    ["anachron_street", "街頭錯代", "street anachronistic", "錯、疊、街頭", "wrong, stack, street", "街頭質感的不該出現的年代", "with street grit, wrong-era object", "street-cast, anachronistic prop era"],
    ["anachron_noir", "暗黑錯代", "noir anachronistic", "錯、疊、暗黑", "wrong, stack, noir", "暗調電影感的不該出現的年代", "in noir lighting, wrong-era object", "noir, anachronistic prop era"],
    ["anachron_soft", "柔光錯代", "soft-light anachronistic", "錯、疊、柔光", "wrong, stack, soft", "柔光下的不該出現的年代", "under soft light, wrong-era object", "soft-lit, anachronistic prop era"],
    ["anachron_epic", "史詩錯代", "epic anachronistic", "錯、疊、史詩", "wrong, stack, epic", "史詩尺度的不該出現的年代", "at epic scale, wrong-era object", "epic, anachronistic prop era"]
  ],
    material: [
    ["jade_court", "宮廷玉", "court jade", "玉、潤、宮廷", "jade, oily, courtly", "宮廷氣場下的潤玉", "in a courtly register, oily jade", "courtly, jade material"],
    ["jade_street", "街頭玉", "street jade", "玉、潤、街頭", "jade, oily, street", "街頭質感的潤玉", "with street grit, oily jade", "street-cast, jade material"],
    ["jade_noir", "暗黑玉", "noir jade", "玉、潤、暗黑", "jade, oily, noir", "暗調電影感的潤玉", "in noir lighting, oily jade", "noir, jade material"],
    ["jade_soft", "柔光玉", "soft-light jade", "玉、潤、柔光", "jade, oily, soft", "柔光下的潤玉", "under soft light, oily jade", "soft-lit, jade material"],
    ["jade_epic", "史詩玉", "epic jade", "玉、潤、史詩", "jade, oily, epic", "史詩尺度的潤玉", "at epic scale, oily jade", "epic, jade material"],
    ["iron_court", "宮廷黑鐵", "court black iron", "鐵、沉、宮廷", "iron, heavy, courtly", "宮廷氣場下的黑鐵", "in a courtly register, black iron", "courtly, black-iron material"],
    ["iron_street", "街頭黑鐵", "street black iron", "鐵、沉、街頭", "iron, heavy, street", "街頭質感的黑鐵", "with street grit, black iron", "street-cast, black-iron material"],
    ["iron_noir", "暗黑黑鐵", "noir black iron", "鐵、沉、暗黑", "iron, heavy, noir", "暗調電影感的黑鐵", "in noir lighting, black iron", "noir, black-iron material"],
    ["iron_soft", "柔光黑鐵", "soft-light black iron", "鐵、沉、柔光", "iron, heavy, soft", "柔光下的黑鐵", "under soft light, black iron", "soft-lit, black-iron material"],
    ["iron_epic", "史詩黑鐵", "epic black iron", "鐵、沉、史詩", "iron, heavy, epic", "史詩尺度的黑鐵", "at epic scale, black iron", "epic, black-iron material"],
    ["gold_court", "宮廷鈍金", "court dull gold", "金、舊、宮廷", "gold, dull, courtly", "宮廷氣場下的不亮的金", "in a courtly register, unpolished gold", "courtly, dull gold material"],
    ["gold_street", "街頭鈍金", "street dull gold", "金、舊、街頭", "gold, dull, street", "街頭質感的不亮的金", "with street grit, unpolished gold", "street-cast, dull gold material"],
    ["gold_noir", "暗黑鈍金", "noir dull gold", "金、舊、暗黑", "gold, dull, noir", "暗調電影感的不亮的金", "in noir lighting, unpolished gold", "noir, dull gold material"],
    ["gold_soft", "柔光鈍金", "soft-light dull gold", "金、舊、柔光", "gold, dull, soft", "柔光下的不亮的金", "under soft light, unpolished gold", "soft-lit, dull gold material"],
    ["gold_epic", "史詩鈍金", "epic dull gold", "金、舊、史詩", "gold, dull, epic", "史詩尺度的不亮的金", "at epic scale, unpolished gold", "epic, dull gold material"],
    ["wood_court", "宮廷舊木", "court aged wood", "木、紋、宮廷", "wood, grain, courtly", "宮廷氣場下的可見木紋", "in a courtly register, visible wood grain", "courtly, aged wood material"],
    ["wood_street", "街頭舊木", "street aged wood", "木、紋、街頭", "wood, grain, street", "街頭質感的可見木紋", "with street grit, visible wood grain", "street-cast, aged wood material"],
    ["wood_noir", "暗黑舊木", "noir aged wood", "木、紋、暗黑", "wood, grain, noir", "暗調電影感的可見木紋", "in noir lighting, visible wood grain", "noir, aged wood material"],
    ["wood_soft", "柔光舊木", "soft-light aged wood", "木、紋、柔光", "wood, grain, soft", "柔光下的可見木紋", "under soft light, visible wood grain", "soft-lit, aged wood material"],
    ["wood_epic", "史詩舊木", "epic aged wood", "木、紋、史詩", "wood, grain, epic", "史詩尺度的可見木紋", "at epic scale, visible wood grain", "epic, aged wood material"],
    ["plastic_court", "宮廷廉價塑", "court cheap plastic", "塑、輕、宮廷", "plastic, cheap, courtly", "宮廷氣場下的輕廉價塑", "in a courtly register, cheap light plastic", "courtly, cheap plastic material"],
    ["plastic_street", "街頭廉價塑", "street cheap plastic", "塑、輕、街頭", "plastic, cheap, street", "街頭質感的輕廉價塑", "with street grit, cheap light plastic", "street-cast, cheap plastic material"],
    ["plastic_noir", "暗黑廉價塑", "noir cheap plastic", "塑、輕、暗黑", "plastic, cheap, noir", "暗調電影感的輕廉價塑", "in noir lighting, cheap light plastic", "noir, cheap plastic material"],
    ["plastic_soft", "柔光廉價塑", "soft-light cheap plastic", "塑、輕、柔光", "plastic, cheap, soft", "柔光下的輕廉價塑", "under soft light, cheap light plastic", "soft-lit, cheap plastic material"],
    ["plastic_epic", "史詩廉價塑", "epic cheap plastic", "塑、輕、史詩", "plastic, cheap, epic", "史詩尺度的輕廉價塑", "at epic scale, cheap light plastic", "epic, cheap plastic material"],
    ["glass_court", "宮廷薄玻", "court thin glass", "玻、脆、宮廷", "glass, fragile, courtly", "宮廷氣場下的薄而易碎", "in a courtly register, thin fragile glass", "courtly, thin glass material"],
    ["glass_street", "街頭薄玻", "street thin glass", "玻、脆、街頭", "glass, fragile, street", "街頭質感的薄而易碎", "with street grit, thin fragile glass", "street-cast, thin glass material"],
    ["glass_noir", "暗黑薄玻", "noir thin glass", "玻、脆、暗黑", "glass, fragile, noir", "暗調電影感的薄而易碎", "in noir lighting, thin fragile glass", "noir, thin glass material"],
    ["glass_soft", "柔光薄玻", "soft-light thin glass", "玻、脆、柔光", "glass, fragile, soft", "柔光下的薄而易碎", "under soft light, thin fragile glass", "soft-lit, thin glass material"],
    ["glass_epic", "史詩薄玻", "epic thin glass", "玻、脆、史詩", "glass, fragile, epic", "史詩尺度的薄而易碎", "at epic scale, thin fragile glass", "epic, thin glass material"],
    ["leather_court", "宮廷舊皮", "court aged leather", "皮、皺、宮廷", "leather, crease, courtly", "宮廷氣場下的皺舊皮", "in a courtly register, creased old leather", "courtly, aged leather material"],
    ["leather_street", "街頭舊皮", "street aged leather", "皮、皺、街頭", "leather, crease, street", "街頭質感的皺舊皮", "with street grit, creased old leather", "street-cast, aged leather material"],
    ["leather_noir", "暗黑舊皮", "noir aged leather", "皮、皺、暗黑", "leather, crease, noir", "暗調電影感的皺舊皮", "in noir lighting, creased old leather", "noir, aged leather material"],
    ["leather_soft", "柔光舊皮", "soft-light aged leather", "皮、皺、柔光", "leather, crease, soft", "柔光下的皺舊皮", "under soft light, creased old leather", "soft-lit, aged leather material"],
    ["leather_epic", "史詩舊皮", "epic aged leather", "皮、皺、史詩", "leather, crease, epic", "史詩尺度的皺舊皮", "at epic scale, creased old leather", "epic, aged leather material"],
    ["ceramic_court", "宮廷瓷", "court ceramic", "瓷、釉、宮廷", "ceramic, glaze, courtly", "宮廷氣場下的釉面瓷", "in a courtly register, glazed ceramic", "courtly, ceramic material"],
    ["ceramic_street", "街頭瓷", "street ceramic", "瓷、釉、街頭", "ceramic, glaze, street", "街頭質感的釉面瓷", "with street grit, glazed ceramic", "street-cast, ceramic material"],
    ["ceramic_noir", "暗黑瓷", "noir ceramic", "瓷、釉、暗黑", "ceramic, glaze, noir", "暗調電影感的釉面瓷", "in noir lighting, glazed ceramic", "noir, ceramic material"],
    ["ceramic_soft", "柔光瓷", "soft-light ceramic", "瓷、釉、柔光", "ceramic, glaze, soft", "柔光下的釉面瓷", "under soft light, glazed ceramic", "soft-lit, ceramic material"],
    ["ceramic_epic", "史詩瓷", "epic ceramic", "瓷、釉、史詩", "ceramic, glaze, epic", "史詩尺度的釉面瓷", "at epic scale, glazed ceramic", "epic, ceramic material"],
    ["carbon_court", "宮廷碳纖", "court carbon fiber", "碳、現、宮廷", "carbon, now, courtly", "宮廷氣場下的織紋碳纖", "in a courtly register, woven carbon", "courtly, carbon-fiber material"],
    ["carbon_street", "街頭碳纖", "street carbon fiber", "碳、現、街頭", "carbon, now, street", "街頭質感的織紋碳纖", "with street grit, woven carbon", "street-cast, carbon-fiber material"],
    ["carbon_noir", "暗黑碳纖", "noir carbon fiber", "碳、現、暗黑", "carbon, now, noir", "暗調電影感的織紋碳纖", "in noir lighting, woven carbon", "noir, carbon-fiber material"],
    ["carbon_soft", "柔光碳纖", "soft-light carbon fiber", "碳、現、柔光", "carbon, now, soft", "柔光下的織紋碳纖", "under soft light, woven carbon", "soft-lit, carbon-fiber material"],
    ["carbon_epic", "史詩碳纖", "epic carbon fiber", "碳、現、史詩", "carbon, now, epic", "史詩尺度的織紋碳纖", "at epic scale, woven carbon", "epic, carbon-fiber material"],
    ["bone_court", "宮廷骨角", "court bone", "骨、巫、宮廷", "bone, ritual, courtly", "宮廷氣場下的骨或角", "in a courtly register, bone or horn", "courtly, bone material"],
    ["bone_street", "街頭骨角", "street bone", "骨、巫、街頭", "bone, ritual, street", "街頭質感的骨或角", "with street grit, bone or horn", "street-cast, bone material"],
    ["bone_noir", "暗黑骨角", "noir bone", "骨、巫、暗黑", "bone, ritual, noir", "暗調電影感的骨或角", "in noir lighting, bone or horn", "noir, bone material"],
    ["bone_soft", "柔光骨角", "soft-light bone", "骨、巫、柔光", "bone, ritual, soft", "柔光下的骨或角", "under soft light, bone or horn", "soft-lit, bone material"],
    ["bone_epic", "史詩骨角", "epic bone", "骨、巫、史詩", "bone, ritual, epic", "史詩尺度的骨或角", "at epic scale, bone or horn", "epic, bone material"]
  ],
    condition: [
    ["mint_court", "宮廷近全新", "court near mint", "新、淨、宮廷", "mint, clean, courtly", "宮廷氣場下的幾乎無損", "in a courtly register, almost unused", "courtly, near-mint condition"],
    ["mint_street", "街頭近全新", "street near mint", "新、淨、街頭", "mint, clean, street", "街頭質感的幾乎無損", "with street grit, almost unused", "street-cast, near-mint condition"],
    ["mint_noir", "暗黑近全新", "noir near mint", "新、淨、暗黑", "mint, clean, noir", "暗調電影感的幾乎無損", "in noir lighting, almost unused", "noir, near-mint condition"],
    ["mint_soft", "柔光近全新", "soft-light near mint", "新、淨、柔光", "mint, clean, soft", "柔光下的幾乎無損", "under soft light, almost unused", "soft-lit, near-mint condition"],
    ["mint_epic", "史詩近全新", "epic near mint", "新、淨、史詩", "mint, clean, epic", "史詩尺度的幾乎無損", "at epic scale, almost unused", "epic, near-mint condition"],
    ["used_court", "宮廷使用痕", "court used", "用、手、宮廷", "used, hand, courtly", "宮廷氣場下的正常使用痕", "in a courtly register, normal use wear", "courtly, used condition"],
    ["used_street", "街頭使用痕", "street used", "用、手、街頭", "used, hand, street", "街頭質感的正常使用痕", "with street grit, normal use wear", "street-cast, used condition"],
    ["used_noir", "暗黑使用痕", "noir used", "用、手、暗黑", "used, hand, noir", "暗調電影感的正常使用痕", "in noir lighting, normal use wear", "noir, used condition"],
    ["used_soft", "柔光使用痕", "soft-light used", "用、手、柔光", "used, hand, soft", "柔光下的正常使用痕", "under soft light, normal use wear", "soft-lit, used condition"],
    ["used_epic", "史詩使用痕", "epic used", "用、手、史詩", "used, hand, epic", "史詩尺度的正常使用痕", "at epic scale, normal use wear", "epic, used condition"],
    ["worn_court", "宮廷明顯舊", "court heavily worn", "舊、磨、宮廷", "worn, rub, courtly", "宮廷氣場下的邊角磨穿", "in a courtly register, edges rubbed through", "courtly, heavily worn condition"],
    ["worn_street", "街頭明顯舊", "street heavily worn", "舊、磨、街頭", "worn, rub, street", "街頭質感的邊角磨穿", "with street grit, edges rubbed through", "street-cast, heavily worn condition"],
    ["worn_noir", "暗黑明顯舊", "noir heavily worn", "舊、磨、暗黑", "worn, rub, noir", "暗調電影感的邊角磨穿", "in noir lighting, edges rubbed through", "noir, heavily worn condition"],
    ["worn_soft", "柔光明顯舊", "soft-light heavily worn", "舊、磨、柔光", "worn, rub, soft", "柔光下的邊角磨穿", "under soft light, edges rubbed through", "soft-lit, heavily worn condition"],
    ["worn_epic", "史詩明顯舊", "epic heavily worn", "舊、磨、史詩", "worn, rub, epic", "史詩尺度的邊角磨穿", "at epic scale, edges rubbed through", "epic, heavily worn condition"],
    ["cracked_court", "宮廷裂", "court cracked", "裂、危、宮廷", "crack, risk, courtly", "宮廷氣場下的可見裂縫", "in a courtly register, visible crack", "courtly, cracked condition"],
    ["cracked_street", "街頭裂", "street cracked", "裂、危、街頭", "crack, risk, street", "街頭質感的可見裂縫", "with street grit, visible crack", "street-cast, cracked condition"],
    ["cracked_noir", "暗黑裂", "noir cracked", "裂、危、暗黑", "crack, risk, noir", "暗調電影感的可見裂縫", "in noir lighting, visible crack", "noir, cracked condition"],
    ["cracked_soft", "柔光裂", "soft-light cracked", "裂、危、柔光", "crack, risk, soft", "柔光下的可見裂縫", "under soft light, visible crack", "soft-lit, cracked condition"],
    ["cracked_epic", "史詩裂", "epic cracked", "裂、危、史詩", "crack, risk, epic", "史詩尺度的可見裂縫", "at epic scale, visible crack", "epic, cracked condition"],
    ["rusty_court", "宮廷鏽", "court rusty", "鏽、橙、宮廷", "rust, orange, courtly", "宮廷氣場下的橙鏽斑", "in a courtly register, orange rust patches", "courtly, rusty condition"],
    ["rusty_street", "街頭鏽", "street rusty", "鏽、橙、街頭", "rust, orange, street", "街頭質感的橙鏽斑", "with street grit, orange rust patches", "street-cast, rusty condition"],
    ["rusty_noir", "暗黑鏽", "noir rusty", "鏽、橙、暗黑", "rust, orange, noir", "暗調電影感的橙鏽斑", "in noir lighting, orange rust patches", "noir, rusty condition"],
    ["rusty_soft", "柔光鏽", "soft-light rusty", "鏽、橙、柔光", "rust, orange, soft", "柔光下的橙鏽斑", "under soft light, orange rust patches", "soft-lit, rusty condition"],
    ["rusty_epic", "史詩鏽", "epic rusty", "鏽、橙、史詩", "rust, orange, epic", "史詩尺度的橙鏽斑", "at epic scale, orange rust patches", "epic, rusty condition"],
    ["bloodied_court", "宮廷殘血", "court blood-stained", "血、舊、宮廷", "blood, old, courtly", "宮廷氣場下的舊血斑", "in a courtly register, old blood stains", "courtly, blood-stained condition"],
    ["bloodied_street", "街頭殘血", "street blood-stained", "血、舊、街頭", "blood, old, street", "街頭質感的舊血斑", "with street grit, old blood stains", "street-cast, blood-stained condition"],
    ["bloodied_noir", "暗黑殘血", "noir blood-stained", "血、舊、暗黑", "blood, old, noir", "暗調電影感的舊血斑", "in noir lighting, old blood stains", "noir, blood-stained condition"],
    ["bloodied_soft", "柔光殘血", "soft-light blood-stained", "血、舊、柔光", "blood, old, soft", "柔光下的舊血斑", "under soft light, old blood stains", "soft-lit, blood-stained condition"],
    ["bloodied_epic", "史詩殘血", "epic blood-stained", "血、舊、史詩", "blood, old, epic", "史詩尺度的舊血斑", "at epic scale, old blood stains", "epic, blood-stained condition"],
    ["repaired_court", "宮廷補過", "court repaired", "補、線、宮廷", "repair, seam, courtly", "宮廷氣場下的可見修補", "in a courtly register, visible repair", "courtly, repaired condition"],
    ["repaired_street", "街頭補過", "street repaired", "補、線、街頭", "repair, seam, street", "街頭質感的可見修補", "with street grit, visible repair", "street-cast, repaired condition"],
    ["repaired_noir", "暗黑補過", "noir repaired", "補、線、暗黑", "repair, seam, noir", "暗調電影感的可見修補", "in noir lighting, visible repair", "noir, repaired condition"],
    ["repaired_soft", "柔光補過", "soft-light repaired", "補、線、柔光", "repair, seam, soft", "柔光下的可見修補", "under soft light, visible repair", "soft-lit, repaired condition"],
    ["repaired_epic", "史詩補過", "epic repaired", "補、線、史詩", "repair, seam, epic", "史詩尺度的可見修補", "at epic scale, visible repair", "epic, repaired condition"],
    ["wrapped_court", "宮廷布裹", "court cloth-wrapped", "裹、藏、宮廷", "wrap, hide, courtly", "宮廷氣場下的布條裹住", "in a courtly register, wrapped in cloth", "courtly, cloth-wrapped condition"],
    ["wrapped_street", "街頭布裹", "street cloth-wrapped", "裹、藏、街頭", "wrap, hide, street", "街頭質感的布條裹住", "with street grit, wrapped in cloth", "street-cast, cloth-wrapped condition"],
    ["wrapped_noir", "暗黑布裹", "noir cloth-wrapped", "裹、藏、暗黑", "wrap, hide, noir", "暗調電影感的布條裹住", "in noir lighting, wrapped in cloth", "noir, cloth-wrapped condition"],
    ["wrapped_soft", "柔光布裹", "soft-light cloth-wrapped", "裹、藏、柔光", "wrap, hide, soft", "柔光下的布條裹住", "under soft light, wrapped in cloth", "soft-lit, cloth-wrapped condition"],
    ["wrapped_epic", "史詩布裹", "epic cloth-wrapped", "裹、藏、史詩", "wrap, hide, epic", "史詩尺度的布條裹住", "at epic scale, wrapped in cloth", "epic, cloth-wrapped condition"],
    ["wet_court", "宮廷濕", "court wet", "濕、反、宮廷", "wet, sheen, courtly", "宮廷氣場下的表面潮濕", "in a courtly register, surface wet", "courtly, wet condition"],
    ["wet_street", "街頭濕", "street wet", "濕、反、街頭", "wet, sheen, street", "街頭質感的表面潮濕", "with street grit, surface wet", "street-cast, wet condition"],
    ["wet_noir", "暗黑濕", "noir wet", "濕、反、暗黑", "wet, sheen, noir", "暗調電影感的表面潮濕", "in noir lighting, surface wet", "noir, wet condition"],
    ["wet_soft", "柔光濕", "soft-light wet", "濕、反、柔光", "wet, sheen, soft", "柔光下的表面潮濕", "under soft light, surface wet", "soft-lit, wet condition"],
    ["wet_epic", "史詩濕", "epic wet", "濕、反、史詩", "wet, sheen, epic", "史詩尺度的表面潮濕", "at epic scale, surface wet", "epic, wet condition"],
    ["burnt_court", "宮廷燒過", "court fire-scarred", "燒、黑、宮廷", "burn, black, courtly", "宮廷氣場下的燒焦邊", "in a courtly register, charred edges", "courtly, fire-scarred condition"],
    ["burnt_street", "街頭燒過", "street fire-scarred", "燒、黑、街頭", "burn, black, street", "街頭質感的燒焦邊", "with street grit, charred edges", "street-cast, fire-scarred condition"],
    ["burnt_noir", "暗黑燒過", "noir fire-scarred", "燒、黑、暗黑", "burn, black, noir", "暗調電影感的燒焦邊", "in noir lighting, charred edges", "noir, fire-scarred condition"],
    ["burnt_soft", "柔光燒過", "soft-light fire-scarred", "燒、黑、柔光", "burn, black, soft", "柔光下的燒焦邊", "under soft light, charred edges", "soft-lit, fire-scarred condition"],
    ["burnt_epic", "史詩燒過", "epic fire-scarred", "燒、黑、史詩", "burn, black, epic", "史詩尺度的燒焦邊", "at epic scale, charred edges", "epic, fire-scarred condition"]
  ],
    scale: [
    ["palm_court", "宮廷掌心", "court palm-sized", "掌、可握、宮廷", "palm, hold, courtly", "宮廷氣場下的可單掌握", "in a courtly register, fits one palm", "courtly, palm-sized scale"],
    ["palm_street", "街頭掌心", "street palm-sized", "掌、可握、街頭", "palm, hold, street", "街頭質感的可單掌握", "with street grit, fits one palm", "street-cast, palm-sized scale"],
    ["palm_noir", "暗黑掌心", "noir palm-sized", "掌、可握、暗黑", "palm, hold, noir", "暗調電影感的可單掌握", "in noir lighting, fits one palm", "noir, palm-sized scale"],
    ["palm_soft", "柔光掌心", "soft-light palm-sized", "掌、可握、柔光", "palm, hold, soft", "柔光下的可單掌握", "under soft light, fits one palm", "soft-lit, palm-sized scale"],
    ["palm_epic", "史詩掌心", "epic palm-sized", "掌、可握、史詩", "palm, hold, epic", "史詩尺度的可單掌握", "at epic scale, fits one palm", "epic, palm-sized scale"],
    ["pocket_court", "宮廷袋裝", "court pocket", "袋、藏、宮廷", "pocket, hide, courtly", "宮廷氣場下的可入袋", "in a courtly register, fits a pocket", "courtly, pocket scale"],
    ["pocket_street", "街頭袋裝", "street pocket", "袋、藏、街頭", "pocket, hide, street", "街頭質感的可入袋", "with street grit, fits a pocket", "street-cast, pocket scale"],
    ["pocket_noir", "暗黑袋裝", "noir pocket", "袋、藏、暗黑", "pocket, hide, noir", "暗調電影感的可入袋", "in noir lighting, fits a pocket", "noir, pocket scale"],
    ["pocket_soft", "柔光袋裝", "soft-light pocket", "袋、藏、柔光", "pocket, hide, soft", "柔光下的可入袋", "under soft light, fits a pocket", "soft-lit, pocket scale"],
    ["pocket_epic", "史詩袋裝", "epic pocket", "袋、藏、史詩", "pocket, hide, epic", "史詩尺度的可入袋", "at epic scale, fits a pocket", "epic, pocket scale"],
    ["hand_court", "宮廷單手具", "court one-hand tool", "單手、用、宮廷", "one hand, use, courtly", "宮廷氣場下的單手工具長", "in a courtly register, one-hand tool length", "courtly, one-hand scale"],
    ["hand_street", "街頭單手具", "street one-hand tool", "單手、用、街頭", "one hand, use, street", "街頭質感的單手工具長", "with street grit, one-hand tool length", "street-cast, one-hand scale"],
    ["hand_noir", "暗黑單手具", "noir one-hand tool", "單手、用、暗黑", "one hand, use, noir", "暗調電影感的單手工具長", "in noir lighting, one-hand tool length", "noir, one-hand scale"],
    ["hand_soft", "柔光單手具", "soft-light one-hand tool", "單手、用、柔光", "one hand, use, soft", "柔光下的單手工具長", "under soft light, one-hand tool length", "soft-lit, one-hand scale"],
    ["hand_epic", "史詩單手具", "epic one-hand tool", "單手、用、史詩", "one hand, use, epic", "史詩尺度的單手工具長", "at epic scale, one-hand tool length", "epic, one-hand scale"],
    ["two_hand_court", "宮廷雙手", "court two-handed", "雙、長、宮廷", "two, long, courtly", "宮廷氣場下的需雙手", "in a courtly register, needs two hands", "courtly, two-handed scale"],
    ["two_hand_street", "街頭雙手", "street two-handed", "雙、長、街頭", "two, long, street", "街頭質感的需雙手", "with street grit, needs two hands", "street-cast, two-handed scale"],
    ["two_hand_noir", "暗黑雙手", "noir two-handed", "雙、長、暗黑", "two, long, noir", "暗調電影感的需雙手", "in noir lighting, needs two hands", "noir, two-handed scale"],
    ["two_hand_soft", "柔光雙手", "soft-light two-handed", "雙、長、柔光", "two, long, soft", "柔光下的需雙手", "under soft light, needs two hands", "soft-lit, two-handed scale"],
    ["two_hand_epic", "史詩雙手", "epic two-handed", "雙、長、史詩", "two, long, epic", "史詩尺度的需雙手", "at epic scale, needs two hands", "epic, two-handed scale"],
    ["table_court", "宮廷桌面件", "court tabletop", "桌、擺、宮廷", "table, set, courtly", "宮廷氣場下的佔半張桌", "in a courtly register, half a tabletop", "courtly, tabletop scale"],
    ["table_street", "街頭桌面件", "street tabletop", "桌、擺、街頭", "table, set, street", "街頭質感的佔半張桌", "with street grit, half a tabletop", "street-cast, tabletop scale"],
    ["table_noir", "暗黑桌面件", "noir tabletop", "桌、擺、暗黑", "table, set, noir", "暗調電影感的佔半張桌", "in noir lighting, half a tabletop", "noir, tabletop scale"],
    ["table_soft", "柔光桌面件", "soft-light tabletop", "桌、擺、柔光", "table, set, soft", "柔光下的佔半張桌", "under soft light, half a tabletop", "soft-lit, tabletop scale"],
    ["table_epic", "史詩桌面件", "epic tabletop", "桌、擺、史詩", "table, set, epic", "史詩尺度的佔半張桌", "at epic scale, half a tabletop", "epic, tabletop scale"],
    ["human_court", "宮廷近人身高", "court near human height", "人、高、宮廷", "human, tall, courtly", "宮廷氣場下的接近人身高", "in a courtly register, near human height", "courtly, human-height scale"],
    ["human_street", "街頭近人身高", "street near human height", "人、高、街頭", "human, tall, street", "街頭質感的接近人身高", "with street grit, near human height", "street-cast, human-height scale"],
    ["human_noir", "暗黑近人身高", "noir near human height", "人、高、暗黑", "human, tall, noir", "暗調電影感的接近人身高", "in noir lighting, near human height", "noir, human-height scale"],
    ["human_soft", "柔光近人身高", "soft-light near human height", "人、高、柔光", "human, tall, soft", "柔光下的接近人身高", "under soft light, near human height", "soft-lit, human-height scale"],
    ["human_epic", "史詩近人身高", "epic near human height", "人、高、史詩", "human, tall, epic", "史詩尺度的接近人身高", "at epic scale, near human height", "epic, human-height scale"],
    ["tiny_court", "宮廷極小", "court tiny", "極小、細、宮廷", "tiny, fine, courtly", "宮廷氣場下的幾乎要湊近", "in a courtly register, must lean in to see", "courtly, tiny scale"],
    ["tiny_street", "街頭極小", "street tiny", "極小、細、街頭", "tiny, fine, street", "街頭質感的幾乎要湊近", "with street grit, must lean in to see", "street-cast, tiny scale"],
    ["tiny_noir", "暗黑極小", "noir tiny", "極小、細、暗黑", "tiny, fine, noir", "暗調電影感的幾乎要湊近", "in noir lighting, must lean in to see", "noir, tiny scale"],
    ["tiny_soft", "柔光極小", "soft-light tiny", "極小、細、柔光", "tiny, fine, soft", "柔光下的幾乎要湊近", "under soft light, must lean in to see", "soft-lit, tiny scale"],
    ["tiny_epic", "史詩極小", "epic tiny", "極小、細、史詩", "tiny, fine, epic", "史詩尺度的幾乎要湊近", "at epic scale, must lean in to see", "epic, tiny scale"],
    ["oversized_court", "宮廷誇張大", "court oversized", "誇、戲、宮廷", "over, drama, courtly", "宮廷氣場下的比真實大", "in a courtly register, larger than real", "courtly, oversized scale"],
    ["oversized_street", "街頭誇張大", "street oversized", "誇、戲、街頭", "over, drama, street", "街頭質感的比真實大", "with street grit, larger than real", "street-cast, oversized scale"],
    ["oversized_noir", "暗黑誇張大", "noir oversized", "誇、戲、暗黑", "over, drama, noir", "暗調電影感的比真實大", "in noir lighting, larger than real", "noir, oversized scale"],
    ["oversized_soft", "柔光誇張大", "soft-light oversized", "誇、戲、柔光", "over, drama, soft", "柔光下的比真實大", "under soft light, larger than real", "soft-lit, oversized scale"],
    ["oversized_epic", "史詩誇張大", "epic oversized", "誇、戲、史詩", "over, drama, epic", "史詩尺度的比真實大", "at epic scale, larger than real", "epic, oversized scale"],
    ["wearable_court", "宮廷可穿戴", "court wearable", "戴、身、宮廷", "wear, body, courtly", "宮廷氣場下的穿在身上", "in a courtly register, worn on the body", "courtly, wearable scale"],
    ["wearable_street", "街頭可穿戴", "street wearable", "戴、身、街頭", "wear, body, street", "街頭質感的穿在身上", "with street grit, worn on the body", "street-cast, wearable scale"],
    ["wearable_noir", "暗黑可穿戴", "noir wearable", "戴、身、暗黑", "wear, body, noir", "暗調電影感的穿在身上", "in noir lighting, worn on the body", "noir, wearable scale"],
    ["wearable_soft", "柔光可穿戴", "soft-light wearable", "戴、身、柔光", "wear, body, soft", "柔光下的穿在身上", "under soft light, worn on the body", "soft-lit, wearable scale"],
    ["wearable_epic", "史詩可穿戴", "epic wearable", "戴、身、史詩", "wear, body, epic", "史詩尺度的穿在身上", "at epic scale, worn on the body", "epic, wearable scale"],
    ["vehicle_court", "宮廷載具級", "court vehicle-scale", "載、巨、宮廷", "vehicle, huge, courtly", "宮廷氣場下的需車載的大", "in a courtly register, vehicle-scale large", "courtly, vehicle scale"],
    ["vehicle_street", "街頭載具級", "street vehicle-scale", "載、巨、街頭", "vehicle, huge, street", "街頭質感的需車載的大", "with street grit, vehicle-scale large", "street-cast, vehicle scale"],
    ["vehicle_noir", "暗黑載具級", "noir vehicle-scale", "載、巨、暗黑", "vehicle, huge, noir", "暗調電影感的需車載的大", "in noir lighting, vehicle-scale large", "noir, vehicle scale"],
    ["vehicle_soft", "柔光載具級", "soft-light vehicle-scale", "載、巨、柔光", "vehicle, huge, soft", "柔光下的需車載的大", "under soft light, vehicle-scale large", "soft-lit, vehicle scale"],
    ["vehicle_epic", "史詩載具級", "epic vehicle-scale", "載、巨、史詩", "vehicle, huge, epic", "史詩尺度的需車載的大", "at epic scale, vehicle-scale large", "epic, vehicle scale"]
  ],
    ornament: [
    ["none_court", "宮廷素面", "court unornamented", "素、淨、宮廷", "plain, clean, courtly", "宮廷氣場下的無紋飾", "in a courtly register, no ornament", "courtly, unornamented"],
    ["none_street", "街頭素面", "street unornamented", "素、淨、街頭", "plain, clean, street", "街頭質感的無紋飾", "with street grit, no ornament", "street-cast, unornamented"],
    ["none_noir", "暗黑素面", "noir unornamented", "素、淨、暗黑", "plain, clean, noir", "暗調電影感的無紋飾", "in noir lighting, no ornament", "noir, unornamented"],
    ["none_soft", "柔光素面", "soft-light unornamented", "素、淨、柔光", "plain, clean, soft", "柔光下的無紋飾", "under soft light, no ornament", "soft-lit, unornamented"],
    ["none_epic", "史詩素面", "epic unornamented", "素、淨、史詩", "plain, clean, epic", "史詩尺度的無紋飾", "at epic scale, no ornament", "epic, unornamented"],
    ["cloud_court", "宮廷雲紋", "court cloud motif", "雲、中、宮廷", "cloud, chinese, courtly", "宮廷氣場下的淺雲紋", "in a courtly register, shallow cloud motif", "courtly, cloud-motif ornament"],
    ["cloud_street", "街頭雲紋", "street cloud motif", "雲、中、街頭", "cloud, chinese, street", "街頭質感的淺雲紋", "with street grit, shallow cloud motif", "street-cast, cloud-motif ornament"],
    ["cloud_noir", "暗黑雲紋", "noir cloud motif", "雲、中、暗黑", "cloud, chinese, noir", "暗調電影感的淺雲紋", "in noir lighting, shallow cloud motif", "noir, cloud-motif ornament"],
    ["cloud_soft", "柔光雲紋", "soft-light cloud motif", "雲、中、柔光", "cloud, chinese, soft", "柔光下的淺雲紋", "under soft light, shallow cloud motif", "soft-lit, cloud-motif ornament"],
    ["cloud_epic", "史詩雲紋", "epic cloud motif", "雲、中、史詩", "cloud, chinese, epic", "史詩尺度的淺雲紋", "at epic scale, shallow cloud motif", "epic, cloud-motif ornament"],
    ["dragon_court", "宮廷龍紋", "court dragon motif", "龍、權、宮廷", "dragon, power, courtly", "宮廷氣場下的盤龍紋", "in a courtly register, coiling dragon motif", "courtly, dragon-motif ornament"],
    ["dragon_street", "街頭龍紋", "street dragon motif", "龍、權、街頭", "dragon, power, street", "街頭質感的盤龍紋", "with street grit, coiling dragon motif", "street-cast, dragon-motif ornament"],
    ["dragon_noir", "暗黑龍紋", "noir dragon motif", "龍、權、暗黑", "dragon, power, noir", "暗調電影感的盤龍紋", "in noir lighting, coiling dragon motif", "noir, dragon-motif ornament"],
    ["dragon_soft", "柔光龍紋", "soft-light dragon motif", "龍、權、柔光", "dragon, power, soft", "柔光下的盤龍紋", "under soft light, coiling dragon motif", "soft-lit, dragon-motif ornament"],
    ["dragon_epic", "史詩龍紋", "epic dragon motif", "龍、權、史詩", "dragon, power, epic", "史詩尺度的盤龍紋", "at epic scale, coiling dragon motif", "epic, dragon-motif ornament"],
    ["engrave_name_court", "宮廷刻名", "court engraved name", "名、記、宮廷", "name, mark, courtly", "宮廷氣場下的刻了一個名", "in a courtly register, a name engraved", "courtly, engraved-name ornament"],
    ["engrave_name_street", "街頭刻名", "street engraved name", "名、記、街頭", "name, mark, street", "街頭質感的刻了一個名", "with street grit, a name engraved", "street-cast, engraved-name ornament"],
    ["engrave_name_noir", "暗黑刻名", "noir engraved name", "名、記、暗黑", "name, mark, noir", "暗調電影感的刻了一個名", "in noir lighting, a name engraved", "noir, engraved-name ornament"],
    ["engrave_name_soft", "柔光刻名", "soft-light engraved name", "名、記、柔光", "name, mark, soft", "柔光下的刻了一個名", "under soft light, a name engraved", "soft-lit, engraved-name ornament"],
    ["engrave_name_epic", "史詩刻名", "epic engraved name", "名、記、史詩", "name, mark, epic", "史詩尺度的刻了一個名", "at epic scale, a name engraved", "epic, engraved-name ornament"],
    ["gem_court", "宮廷嵌石", "court inset gem", "石、一點、宮廷", "gem, one, courtly", "宮廷氣場下的嵌一粒石", "in a courtly register, one inset stone", "courtly, inset-gem ornament"],
    ["gem_street", "街頭嵌石", "street inset gem", "石、一點、街頭", "gem, one, street", "街頭質感的嵌一粒石", "with street grit, one inset stone", "street-cast, inset-gem ornament"],
    ["gem_noir", "暗黑嵌石", "noir inset gem", "石、一點、暗黑", "gem, one, noir", "暗調電影感的嵌一粒石", "in noir lighting, one inset stone", "noir, inset-gem ornament"],
    ["gem_soft", "柔光嵌石", "soft-light inset gem", "石、一點、柔光", "gem, one, soft", "柔光下的嵌一粒石", "under soft light, one inset stone", "soft-lit, inset-gem ornament"],
    ["gem_epic", "史詩嵌石", "epic inset gem", "石、一點、史詩", "gem, one, epic", "史詩尺度的嵌一粒石", "at epic scale, one inset stone", "epic, inset-gem ornament"],
    ["rust_paint_court", "宮廷舊漆層", "court old paint layers", "漆、層、宮廷", "paint, layers, courtly", "宮廷氣場下的剝落舊漆", "in a courtly register, flaking old paint", "courtly, old-paint ornament"],
    ["rust_paint_street", "街頭舊漆層", "street old paint layers", "漆、層、街頭", "paint, layers, street", "街頭質感的剝落舊漆", "with street grit, flaking old paint", "street-cast, old-paint ornament"],
    ["rust_paint_noir", "暗黑舊漆層", "noir old paint layers", "漆、層、暗黑", "paint, layers, noir", "暗調電影感的剝落舊漆", "in noir lighting, flaking old paint", "noir, old-paint ornament"],
    ["rust_paint_soft", "柔光舊漆層", "soft-light old paint layers", "漆、層、柔光", "paint, layers, soft", "柔光下的剝落舊漆", "under soft light, flaking old paint", "soft-lit, old-paint ornament"],
    ["rust_paint_epic", "史詩舊漆層", "epic old paint layers", "漆、層、史詩", "paint, layers, epic", "史詩尺度的剝落舊漆", "at epic scale, flaking old paint", "epic, old-paint ornament"],
    ["circuit_court", "宮廷電路紋", "court circuit lines", "電、科、宮廷", "circuit, tech, courtly", "宮廷氣場下的淺電路紋", "in a courtly register, shallow circuit lines", "courtly, circuit-line ornament"],
    ["circuit_street", "街頭電路紋", "street circuit lines", "電、科、街頭", "circuit, tech, street", "街頭質感的淺電路紋", "with street grit, shallow circuit lines", "street-cast, circuit-line ornament"],
    ["circuit_noir", "暗黑電路紋", "noir circuit lines", "電、科、暗黑", "circuit, tech, noir", "暗調電影感的淺電路紋", "in noir lighting, shallow circuit lines", "noir, circuit-line ornament"],
    ["circuit_soft", "柔光電路紋", "soft-light circuit lines", "電、科、柔光", "circuit, tech, soft", "柔光下的淺電路紋", "under soft light, shallow circuit lines", "soft-lit, circuit-line ornament"],
    ["circuit_epic", "史詩電路紋", "epic circuit lines", "電、科、史詩", "circuit, tech, epic", "史詩尺度的淺電路紋", "at epic scale, shallow circuit lines", "epic, circuit-line ornament"],
    ["blood_seal_court", "宮廷血印", "court blood seal", "印、巫、宮廷", "seal, ritual, courtly", "宮廷氣場下的紅印或血印", "in a courtly register, red or blood seal", "courtly, blood-seal ornament"],
    ["blood_seal_street", "街頭血印", "street blood seal", "印、巫、街頭", "seal, ritual, street", "街頭質感的紅印或血印", "with street grit, red or blood seal", "street-cast, blood-seal ornament"],
    ["blood_seal_noir", "暗黑血印", "noir blood seal", "印、巫、暗黑", "seal, ritual, noir", "暗調電影感的紅印或血印", "in noir lighting, red or blood seal", "noir, blood-seal ornament"],
    ["blood_seal_soft", "柔光血印", "soft-light blood seal", "印、巫、柔光", "seal, ritual, soft", "柔光下的紅印或血印", "under soft light, red or blood seal", "soft-lit, blood-seal ornament"],
    ["blood_seal_epic", "史詩血印", "epic blood seal", "印、巫、史詩", "seal, ritual, epic", "史詩尺度的紅印或血印", "at epic scale, red or blood seal", "epic, blood-seal ornament"],
    ["scratches_court", "宮廷刻痕數", "court count scratches", "痕、數、宮廷", "scratch, count, courtly", "宮廷氣場下的一排計數刻", "in a courtly register, counted scratch marks", "courtly, count-scratch ornament"],
    ["scratches_street", "街頭刻痕數", "street count scratches", "痕、數、街頭", "scratch, count, street", "街頭質感的一排計數刻", "with street grit, counted scratch marks", "street-cast, count-scratch ornament"],
    ["scratches_noir", "暗黑刻痕數", "noir count scratches", "痕、數、暗黑", "scratch, count, noir", "暗調電影感的一排計數刻", "in noir lighting, counted scratch marks", "noir, count-scratch ornament"],
    ["scratches_soft", "柔光刻痕數", "soft-light count scratches", "痕、數、柔光", "scratch, count, soft", "柔光下的一排計數刻", "under soft light, counted scratch marks", "soft-lit, count-scratch ornament"],
    ["scratches_epic", "史詩刻痕數", "epic count scratches", "痕、數、史詩", "scratch, count, epic", "史詩尺度的一排計數刻", "at epic scale, counted scratch marks", "epic, count-scratch ornament"],
    ["gold_inlay_court", "宮廷金絲錯", "court gold inlay", "金絲、貴、宮廷", "gold, inlay, courtly", "宮廷氣場下的錯金細線", "in a courtly register, fine gold inlay", "courtly, gold-inlay ornament"],
    ["gold_inlay_street", "街頭金絲錯", "street gold inlay", "金絲、貴、街頭", "gold, inlay, street", "街頭質感的錯金細線", "with street grit, fine gold inlay", "street-cast, gold-inlay ornament"],
    ["gold_inlay_noir", "暗黑金絲錯", "noir gold inlay", "金絲、貴、暗黑", "gold, inlay, noir", "暗調電影感的錯金細線", "in noir lighting, fine gold inlay", "noir, gold-inlay ornament"],
    ["gold_inlay_soft", "柔光金絲錯", "soft-light gold inlay", "金絲、貴、柔光", "gold, inlay, soft", "柔光下的錯金細線", "under soft light, fine gold inlay", "soft-lit, gold-inlay ornament"],
    ["gold_inlay_epic", "史詩金絲錯", "epic gold inlay", "金絲、貴、史詩", "gold, inlay, epic", "史詩尺度的錯金細線", "at epic scale, fine gold inlay", "epic, gold-inlay ornament"]
  ]
  }
})
