/**
 * setDressing field kit catalog (50+ templates per part).
 */
import { defineFieldKit } from '../fieldKit'

export const SETDRESSING_KIT = defineFieldKit({
  key: "setDressingKit",
  parts: ["furniture","clutter","signage","practicalLight","textile","debris"] as const,
  partLabels: {
    furniture: { zhHK: "傢俬", zhCN: "家具", en: "Furniture" },
    clutter: { zhHK: "雜物", zhCN: "杂物", en: "Clutter" },
    signage: { zhHK: "招牌字", zhCN: "招牌字", en: "Signage" },
    practicalLight: { zhHK: "實用光", zhCN: "实用光", en: "Practical light" },
    textile: { zhHK: "布藝", zhCN: "布艺", en: "Textile" },
    debris: { zhHK: "殘件", zhCN: "残件", en: "Debris" }
  },

  rows: {
    furniture: [
    ["rosewood_court", "宮廷紅木桌椅", "court rosewood set", "紅木、沉、宮廷", "rosewood, heavy, courtly", "宮廷氣場下的紅木八仙桌", "in a courtly register, rosewood square table", "courtly, rosewood furniture"],
    ["rosewood_street", "街頭紅木桌椅", "street rosewood set", "紅木、沉、街頭", "rosewood, heavy, street", "街頭質感的紅木八仙桌", "with street grit, rosewood square table", "street-cast, rosewood furniture"],
    ["rosewood_noir", "暗黑紅木桌椅", "noir rosewood set", "紅木、沉、暗黑", "rosewood, heavy, noir", "暗調電影感的紅木八仙桌", "in noir lighting, rosewood square table", "noir, rosewood furniture"],
    ["rosewood_soft", "柔光紅木桌椅", "soft-light rosewood set", "紅木、沉、柔光", "rosewood, heavy, soft", "柔光下的紅木八仙桌", "under soft light, rosewood square table", "soft-lit, rosewood furniture"],
    ["rosewood_epic", "史詩紅木桌椅", "epic rosewood set", "紅木、沉、史詩", "rosewood, heavy, epic", "史詩尺度的紅木八仙桌", "at epic scale, rosewood square table", "epic, rosewood furniture"],
    ["ikea_court", "宮廷淺木現代", "court light modern", "淺木、現、宮廷", "light wood, now, courtly", "宮廷氣場下的淺木簡傢俬", "in a courtly register, light modern furniture", "courtly, light modern furniture"],
    ["ikea_street", "街頭淺木現代", "street light modern", "淺木、現、街頭", "light wood, now, street", "街頭質感的淺木簡傢俬", "with street grit, light modern furniture", "street-cast, light modern furniture"],
    ["ikea_noir", "暗黑淺木現代", "noir light modern", "淺木、現、暗黑", "light wood, now, noir", "暗調電影感的淺木簡傢俬", "in noir lighting, light modern furniture", "noir, light modern furniture"],
    ["ikea_soft", "柔光淺木現代", "soft-light light modern", "淺木、現、柔光", "light wood, now, soft", "柔光下的淺木簡傢俬", "under soft light, light modern furniture", "soft-lit, light modern furniture"],
    ["ikea_epic", "史詩淺木現代", "epic light modern", "淺木、現、史詩", "light wood, now, epic", "史詩尺度的淺木簡傢俬", "at epic scale, light modern furniture", "epic, light modern furniture"],
    ["metal_court", "宮廷金屬摺", "court metal fold", "金屬、冷、宮廷", "metal, cold, courtly", "宮廷氣場下的摺椅鐵桌", "in a courtly register, folding metal table", "courtly, metal folding furniture"],
    ["metal_street", "街頭金屬摺", "street metal fold", "金屬、冷、街頭", "metal, cold, street", "街頭質感的摺椅鐵桌", "with street grit, folding metal table", "street-cast, metal folding furniture"],
    ["metal_noir", "暗黑金屬摺", "noir metal fold", "金屬、冷、暗黑", "metal, cold, noir", "暗調電影感的摺椅鐵桌", "in noir lighting, folding metal table", "noir, metal folding furniture"],
    ["metal_soft", "柔光金屬摺", "soft-light metal fold", "金屬、冷、柔光", "metal, cold, soft", "柔光下的摺椅鐵桌", "under soft light, folding metal table", "soft-lit, metal folding furniture"],
    ["metal_epic", "史詩金屬摺", "epic metal fold", "金屬、冷、史詩", "metal, cold, epic", "史詩尺度的摺椅鐵桌", "at epic scale, folding metal table", "epic, metal folding furniture"],
    ["throne_court", "宮廷寶座", "court throne seat", "座、權、宮廷", "throne, power, courtly", "宮廷氣場下的高背寶座", "in a courtly register, high-back throne", "courtly, throne furniture"],
    ["throne_street", "街頭寶座", "street throne seat", "座、權、街頭", "throne, power, street", "街頭質感的高背寶座", "with street grit, high-back throne", "street-cast, throne furniture"],
    ["throne_noir", "暗黑寶座", "noir throne seat", "座、權、暗黑", "throne, power, noir", "暗調電影感的高背寶座", "in noir lighting, high-back throne", "noir, throne furniture"],
    ["throne_soft", "柔光寶座", "soft-light throne seat", "座、權、柔光", "throne, power, soft", "柔光下的高背寶座", "under soft light, high-back throne", "soft-lit, throne furniture"],
    ["throne_epic", "史詩寶座", "epic throne seat", "座、權、史詩", "throne, power, epic", "史詩尺度的高背寶座", "at epic scale, high-back throne", "epic, throne furniture"],
    ["bed_low_court", "宮廷矮榻", "court low couch", "榻、低、宮廷", "couch, low, courtly", "宮廷氣場下的低臥榻", "in a courtly register, low daybed", "courtly, low couch furniture"],
    ["bed_low_street", "街頭矮榻", "street low couch", "榻、低、街頭", "couch, low, street", "街頭質感的低臥榻", "with street grit, low daybed", "street-cast, low couch furniture"],
    ["bed_low_noir", "暗黑矮榻", "noir low couch", "榻、低、暗黑", "couch, low, noir", "暗調電影感的低臥榻", "in noir lighting, low daybed", "noir, low couch furniture"],
    ["bed_low_soft", "柔光矮榻", "soft-light low couch", "榻、低、柔光", "couch, low, soft", "柔光下的低臥榻", "under soft light, low daybed", "soft-lit, low couch furniture"],
    ["bed_low_epic", "史詩矮榻", "epic low couch", "榻、低、史詩", "couch, low, epic", "史詩尺度的低臥榻", "at epic scale, low daybed", "epic, low couch furniture"],
    ["none_court", "宮廷幾乎無傢俬", "court almost none", "空、無、宮廷", "empty, none, courtly", "宮廷氣場下的少傢俬", "in a courtly register, almost no furniture", "courtly, almost no furniture"],
    ["none_street", "街頭幾乎無傢俬", "street almost none", "空、無、街頭", "empty, none, street", "街頭質感的少傢俬", "with street grit, almost no furniture", "street-cast, almost no furniture"],
    ["none_noir", "暗黑幾乎無傢俬", "noir almost none", "空、無、暗黑", "empty, none, noir", "暗調電影感的少傢俬", "in noir lighting, almost no furniture", "noir, almost no furniture"],
    ["none_soft", "柔光幾乎無傢俬", "soft-light almost none", "空、無、柔光", "empty, none, soft", "柔光下的少傢俬", "under soft light, almost no furniture", "soft-lit, almost no furniture"],
    ["none_epic", "史詩幾乎無傢俬", "epic almost none", "空、無、史詩", "empty, none, epic", "史詩尺度的少傢俬", "at epic scale, almost no furniture", "epic, almost no furniture"],
    ["school_court", "宮廷課桌椅", "court school desks", "課、齊、宮廷", "school, rows, courtly", "宮廷氣場下的成排課桌", "in a courtly register, rows of desks", "courtly, school-desk furniture"],
    ["school_street", "街頭課桌椅", "street school desks", "課、齊、街頭", "school, rows, street", "街頭質感的成排課桌", "with street grit, rows of desks", "street-cast, school-desk furniture"],
    ["school_noir", "暗黑課桌椅", "noir school desks", "課、齊、暗黑", "school, rows, noir", "暗調電影感的成排課桌", "in noir lighting, rows of desks", "noir, school-desk furniture"],
    ["school_soft", "柔光課桌椅", "soft-light school desks", "課、齊、柔光", "school, rows, soft", "柔光下的成排課桌", "under soft light, rows of desks", "soft-lit, school-desk furniture"],
    ["school_epic", "史詩課桌椅", "epic school desks", "課、齊、史詩", "school, rows, epic", "史詩尺度的成排課桌", "at epic scale, rows of desks", "epic, school-desk furniture"],
    ["bar_court", "宮廷吧台高凳", "court bar stools", "吧、夜、宮廷", "bar, night, courtly", "宮廷氣場下的吧台與高凳", "in a courtly register, bar and stools", "courtly, bar-stool furniture"],
    ["bar_street", "街頭吧台高凳", "street bar stools", "吧、夜、街頭", "bar, night, street", "街頭質感的吧台與高凳", "with street grit, bar and stools", "street-cast, bar-stool furniture"],
    ["bar_noir", "暗黑吧台高凳", "noir bar stools", "吧、夜、暗黑", "bar, night, noir", "暗調電影感的吧台與高凳", "in noir lighting, bar and stools", "noir, bar-stool furniture"],
    ["bar_soft", "柔光吧台高凳", "soft-light bar stools", "吧、夜、柔光", "bar, night, soft", "柔光下的吧台與高凳", "under soft light, bar and stools", "soft-lit, bar-stool furniture"],
    ["bar_epic", "史詩吧台高凳", "epic bar stools", "吧、夜、史詩", "bar, night, epic", "史詩尺度的吧台與高凳", "at epic scale, bar and stools", "epic, bar-stool furniture"],
    ["hospital_court", "宮廷病床簾", "court hospital bed", "病、白、宮廷", "hospital, white, courtly", "宮廷氣場下的鐵架病床", "in a courtly register, metal hospital bed", "courtly, hospital-bed furniture"],
    ["hospital_street", "街頭病床簾", "street hospital bed", "病、白、街頭", "hospital, white, street", "街頭質感的鐵架病床", "with street grit, metal hospital bed", "street-cast, hospital-bed furniture"],
    ["hospital_noir", "暗黑病床簾", "noir hospital bed", "病、白、暗黑", "hospital, white, noir", "暗調電影感的鐵架病床", "in noir lighting, metal hospital bed", "noir, hospital-bed furniture"],
    ["hospital_soft", "柔光病床簾", "soft-light hospital bed", "病、白、柔光", "hospital, white, soft", "柔光下的鐵架病床", "under soft light, metal hospital bed", "soft-lit, hospital-bed furniture"],
    ["hospital_epic", "史詩病床簾", "epic hospital bed", "病、白、史詩", "hospital, white, epic", "史詩尺度的鐵架病床", "at epic scale, metal hospital bed", "epic, hospital-bed furniture"],
    ["antique_mix_court", "宮廷舊洋雜", "court mixed antiques", "舊洋、雜、宮廷", "antique mix, courtly", "宮廷氣場下的中西舊傢俬混", "in a courtly register, mixed antique pieces", "courtly, mixed antique furniture"],
    ["antique_mix_street", "街頭舊洋雜", "street mixed antiques", "舊洋、雜、街頭", "antique mix, street", "街頭質感的中西舊傢俬混", "with street grit, mixed antique pieces", "street-cast, mixed antique furniture"],
    ["antique_mix_noir", "暗黑舊洋雜", "noir mixed antiques", "舊洋、雜、暗黑", "antique mix, noir", "暗調電影感的中西舊傢俬混", "in noir lighting, mixed antique pieces", "noir, mixed antique furniture"],
    ["antique_mix_soft", "柔光舊洋雜", "soft-light mixed antiques", "舊洋、雜、柔光", "antique mix, soft", "柔光下的中西舊傢俬混", "under soft light, mixed antique pieces", "soft-lit, mixed antique furniture"],
    ["antique_mix_epic", "史詩舊洋雜", "epic mixed antiques", "舊洋、雜、史詩", "antique mix, epic", "史詩尺度的中西舊傢俬混", "at epic scale, mixed antique pieces", "epic, mixed antique furniture"]
  ],
    clutter: [
    ["papers_court", "宮廷紙山", "court paper stacks", "紙、亂、宮廷", "paper, mess, courtly", "宮廷氣場下的文件堆", "in a courtly register, stacks of paper", "courtly, paper-stack clutter"],
    ["papers_street", "街頭紙山", "street paper stacks", "紙、亂、街頭", "paper, mess, street", "街頭質感的文件堆", "with street grit, stacks of paper", "street-cast, paper-stack clutter"],
    ["papers_noir", "暗黑紙山", "noir paper stacks", "紙、亂、暗黑", "paper, mess, noir", "暗調電影感的文件堆", "in noir lighting, stacks of paper", "noir, paper-stack clutter"],
    ["papers_soft", "柔光紙山", "soft-light paper stacks", "紙、亂、柔光", "paper, mess, soft", "柔光下的文件堆", "under soft light, stacks of paper", "soft-lit, paper-stack clutter"],
    ["papers_epic", "史詩紙山", "epic paper stacks", "紙、亂、史詩", "paper, mess, epic", "史詩尺度的文件堆", "at epic scale, stacks of paper", "epic, paper-stack clutter"],
    ["dishes_court", "宮廷碗碟", "court dishes", "碗、生活、宮廷", "dishes, life, courtly", "宮廷氣場下的未洗碗", "in a courtly register, unwashed dishes", "courtly, dish clutter"],
    ["dishes_street", "街頭碗碟", "street dishes", "碗、生活、街頭", "dishes, life, street", "街頭質感的未洗碗", "with street grit, unwashed dishes", "street-cast, dish clutter"],
    ["dishes_noir", "暗黑碗碟", "noir dishes", "碗、生活、暗黑", "dishes, life, noir", "暗調電影感的未洗碗", "in noir lighting, unwashed dishes", "noir, dish clutter"],
    ["dishes_soft", "柔光碗碟", "soft-light dishes", "碗、生活、柔光", "dishes, life, soft", "柔光下的未洗碗", "under soft light, unwashed dishes", "soft-lit, dish clutter"],
    ["dishes_epic", "史詩碗碟", "epic dishes", "碗、生活、史詩", "dishes, life, epic", "史詩尺度的未洗碗", "at epic scale, unwashed dishes", "epic, dish clutter"],
    ["cables_court", "宮廷線材", "court cables", "線、現、宮廷", "cable, now, courtly", "宮廷氣場下的纏線", "in a courtly register, tangled cables", "courtly, cable clutter"],
    ["cables_street", "街頭線材", "street cables", "線、現、街頭", "cable, now, street", "街頭質感的纏線", "with street grit, tangled cables", "street-cast, cable clutter"],
    ["cables_noir", "暗黑線材", "noir cables", "線、現、暗黑", "cable, now, noir", "暗調電影感的纏線", "in noir lighting, tangled cables", "noir, cable clutter"],
    ["cables_soft", "柔光線材", "soft-light cables", "線、現、柔光", "cable, now, soft", "柔光下的纏線", "under soft light, tangled cables", "soft-lit, cable clutter"],
    ["cables_epic", "史詩線材", "epic cables", "線、現、史詩", "cable, now, epic", "史詩尺度的纏線", "at epic scale, tangled cables", "epic, cable clutter"],
    ["none_court", "宮廷極淨", "court very clean", "淨、控、宮廷", "clean, control, courtly", "宮廷氣場下的幾乎無雜", "in a courtly register, almost no clutter", "courtly, no clutter"],
    ["none_street", "街頭極淨", "street very clean", "淨、控、街頭", "clean, control, street", "街頭質感的幾乎無雜", "with street grit, almost no clutter", "street-cast, no clutter"],
    ["none_noir", "暗黑極淨", "noir very clean", "淨、控、暗黑", "clean, control, noir", "暗調電影感的幾乎無雜", "in noir lighting, almost no clutter", "noir, no clutter"],
    ["none_soft", "柔光極淨", "soft-light very clean", "淨、控、柔光", "clean, control, soft", "柔光下的幾乎無雜", "under soft light, almost no clutter", "soft-lit, no clutter"],
    ["none_epic", "史詩極淨", "epic very clean", "淨、控、史詩", "clean, control, epic", "史詩尺度的幾乎無雜", "at epic scale, almost no clutter", "epic, no clutter"],
    ["toys_court", "宮廷舊玩具", "court old toys", "玩、童、宮廷", "toy, child, courtly", "宮廷氣場下的幾件舊玩具", "in a courtly register, a few old toys", "courtly, old-toy clutter"],
    ["toys_street", "街頭舊玩具", "street old toys", "玩、童、街頭", "toy, child, street", "街頭質感的幾件舊玩具", "with street grit, a few old toys", "street-cast, old-toy clutter"],
    ["toys_noir", "暗黑舊玩具", "noir old toys", "玩、童、暗黑", "toy, child, noir", "暗調電影感的幾件舊玩具", "in noir lighting, a few old toys", "noir, old-toy clutter"],
    ["toys_soft", "柔光舊玩具", "soft-light old toys", "玩、童、柔光", "toy, child, soft", "柔光下的幾件舊玩具", "under soft light, a few old toys", "soft-lit, old-toy clutter"],
    ["toys_epic", "史詩舊玩具", "epic old toys", "玩、童、史詩", "toy, child, epic", "史詩尺度的幾件舊玩具", "at epic scale, a few old toys", "epic, old-toy clutter"],
    ["bottles_court", "宮廷瓶罐", "court bottles", "瓶、夜、宮廷", "bottle, night, courtly", "宮廷氣場下的空酒瓶", "in a courtly register, empty bottles", "courtly, bottle clutter"],
    ["bottles_street", "街頭瓶罐", "street bottles", "瓶、夜、街頭", "bottle, night, street", "街頭質感的空酒瓶", "with street grit, empty bottles", "street-cast, bottle clutter"],
    ["bottles_noir", "暗黑瓶罐", "noir bottles", "瓶、夜、暗黑", "bottle, night, noir", "暗調電影感的空酒瓶", "in noir lighting, empty bottles", "noir, bottle clutter"],
    ["bottles_soft", "柔光瓶罐", "soft-light bottles", "瓶、夜、柔光", "bottle, night, soft", "柔光下的空酒瓶", "under soft light, empty bottles", "soft-lit, bottle clutter"],
    ["bottles_epic", "史詩瓶罐", "epic bottles", "瓶、夜、史詩", "bottle, night, epic", "史詩尺度的空酒瓶", "at epic scale, empty bottles", "epic, bottle clutter"],
    ["books_court", "宮廷書疊", "court book piles", "書、斜、宮廷", "book, lean, courtly", "宮廷氣場下的歪書疊", "in a courtly register, leaning book piles", "courtly, book-pile clutter"],
    ["books_street", "街頭書疊", "street book piles", "書、斜、街頭", "book, lean, street", "街頭質感的歪書疊", "with street grit, leaning book piles", "street-cast, book-pile clutter"],
    ["books_noir", "暗黑書疊", "noir book piles", "書、斜、暗黑", "book, lean, noir", "暗調電影感的歪書疊", "in noir lighting, leaning book piles", "noir, book-pile clutter"],
    ["books_soft", "柔光書疊", "soft-light book piles", "書、斜、柔光", "book, lean, soft", "柔光下的歪書疊", "under soft light, leaning book piles", "soft-lit, book-pile clutter"],
    ["books_epic", "史詩書疊", "epic book piles", "書、斜、史詩", "book, lean, epic", "史詩尺度的歪書疊", "at epic scale, leaning book piles", "epic, book-pile clutter"],
    ["makeup_court", "宮廷化妝品散", "court makeup scatter", "妝、台、宮廷", "makeup, desk, courtly", "宮廷氣場下的梳妝散物", "in a courtly register, scattered makeup", "courtly, makeup clutter"],
    ["makeup_street", "街頭化妝品散", "street makeup scatter", "妝、台、街頭", "makeup, desk, street", "街頭質感的梳妝散物", "with street grit, scattered makeup", "street-cast, makeup clutter"],
    ["makeup_noir", "暗黑化妝品散", "noir makeup scatter", "妝、台、暗黑", "makeup, desk, noir", "暗調電影感的梳妝散物", "in noir lighting, scattered makeup", "noir, makeup clutter"],
    ["makeup_soft", "柔光化妝品散", "soft-light makeup scatter", "妝、台、柔光", "makeup, desk, soft", "柔光下的梳妝散物", "under soft light, scattered makeup", "soft-lit, makeup clutter"],
    ["makeup_epic", "史詩化妝品散", "epic makeup scatter", "妝、台、史詩", "makeup, desk, epic", "史詩尺度的梳妝散物", "at epic scale, scattered makeup", "epic, makeup clutter"],
    ["tools_court", "宮廷工具攤", "court tool spread", "工、油、宮廷", "tool, oil, courtly", "宮廷氣場下的攤開工具", "in a courtly register, spread tools", "courtly, tool clutter"],
    ["tools_street", "街頭工具攤", "street tool spread", "工、油、街頭", "tool, oil, street", "街頭質感的攤開工具", "with street grit, spread tools", "street-cast, tool clutter"],
    ["tools_noir", "暗黑工具攤", "noir tool spread", "工、油、暗黑", "tool, oil, noir", "暗調電影感的攤開工具", "in noir lighting, spread tools", "noir, tool clutter"],
    ["tools_soft", "柔光工具攤", "soft-light tool spread", "工、油、柔光", "tool, oil, soft", "柔光下的攤開工具", "under soft light, spread tools", "soft-lit, tool clutter"],
    ["tools_epic", "史詩工具攤", "epic tool spread", "工、油、史詩", "tool, oil, epic", "史詩尺度的攤開工具", "at epic scale, spread tools", "epic, tool clutter"],
    ["offerings_court", "宮廷香燭供", "court offerings", "供、香、宮廷", "offering, incense, courtly", "宮廷氣場下的供桌香燭", "in a courtly register, altar offerings", "courtly, offering clutter"],
    ["offerings_street", "街頭香燭供", "street offerings", "供、香、街頭", "offering, incense, street", "街頭質感的供桌香燭", "with street grit, altar offerings", "street-cast, offering clutter"],
    ["offerings_noir", "暗黑香燭供", "noir offerings", "供、香、暗黑", "offering, incense, noir", "暗調電影感的供桌香燭", "in noir lighting, altar offerings", "noir, offering clutter"],
    ["offerings_soft", "柔光香燭供", "soft-light offerings", "供、香、柔光", "offering, incense, soft", "柔光下的供桌香燭", "under soft light, altar offerings", "soft-lit, offering clutter"],
    ["offerings_epic", "史詩香燭供", "epic offerings", "供、香、史詩", "offering, incense, epic", "史詩尺度的供桌香燭", "at epic scale, altar offerings", "epic, offering clutter"]
  ],
    signage: [
    ["neon_zh_court", "宮廷中文霓虹", "court Chinese neon", "霓虹、中、宮廷", "neon, chinese, courtly", "宮廷氣場下的中文霓虹字", "in a courtly register, Chinese neon signs", "courtly, Chinese neon signage"],
    ["neon_zh_street", "街頭中文霓虹", "street Chinese neon", "霓虹、中、街頭", "neon, chinese, street", "街頭質感的中文霓虹字", "with street grit, Chinese neon signs", "street-cast, Chinese neon signage"],
    ["neon_zh_noir", "暗黑中文霓虹", "noir Chinese neon", "霓虹、中、暗黑", "neon, chinese, noir", "暗調電影感的中文霓虹字", "in noir lighting, Chinese neon signs", "noir, Chinese neon signage"],
    ["neon_zh_soft", "柔光中文霓虹", "soft-light Chinese neon", "霓虹、中、柔光", "neon, chinese, soft", "柔光下的中文霓虹字", "under soft light, Chinese neon signs", "soft-lit, Chinese neon signage"],
    ["neon_zh_epic", "史詩中文霓虹", "epic Chinese neon", "霓虹、中、史詩", "neon, chinese, epic", "史詩尺度的中文霓虹字", "at epic scale, Chinese neon signs", "epic, Chinese neon signage"],
    ["hand_paint_court", "宮廷手繪舊招", "court hand-painted", "手繪、舊、宮廷", "hand, faded, courtly", "宮廷氣場下的手繪褪色招", "in a courtly register, faded hand-painted signs", "courtly, hand-painted signage"],
    ["hand_paint_street", "街頭手繪舊招", "street hand-painted", "手繪、舊、街頭", "hand, faded, street", "街頭質感的手繪褪色招", "with street grit, faded hand-painted signs", "street-cast, hand-painted signage"],
    ["hand_paint_noir", "暗黑手繪舊招", "noir hand-painted", "手繪、舊、暗黑", "hand, faded, noir", "暗調電影感的手繪褪色招", "in noir lighting, faded hand-painted signs", "noir, hand-painted signage"],
    ["hand_paint_soft", "柔光手繪舊招", "soft-light hand-painted", "手繪、舊、柔光", "hand, faded, soft", "柔光下的手繪褪色招", "under soft light, faded hand-painted signs", "soft-lit, hand-painted signage"],
    ["hand_paint_epic", "史詩手繪舊招", "epic hand-painted", "手繪、舊、史詩", "hand, faded, epic", "史詩尺度的手繪褪色招", "at epic scale, faded hand-painted signs", "epic, hand-painted signage"],
    ["led_court", "宮廷LED 字幕", "court LED ticker", "LED、走、宮廷", "led, scroll, courtly", "宮廷氣場下的走字 LED", "in a courtly register, scrolling LED", "courtly, LED ticker signage"],
    ["led_street", "街頭LED 字幕", "street LED ticker", "LED、走、街頭", "led, scroll, street", "街頭質感的走字 LED", "with street grit, scrolling LED", "street-cast, LED ticker signage"],
    ["led_noir", "暗黑LED 字幕", "noir LED ticker", "LED、走、暗黑", "led, scroll, noir", "暗調電影感的走字 LED", "in noir lighting, scrolling LED", "noir, LED ticker signage"],
    ["led_soft", "柔光LED 字幕", "soft-light LED ticker", "LED、走、柔光", "led, scroll, soft", "柔光下的走字 LED", "under soft light, scrolling LED", "soft-lit, LED ticker signage"],
    ["led_epic", "史詩LED 字幕", "epic LED ticker", "LED、走、史詩", "led, scroll, epic", "史詩尺度的走字 LED", "at epic scale, scrolling LED", "epic, LED ticker signage"],
    ["none_court", "宮廷無字", "court no text", "無字、淨、宮廷", "none, clean, courtly", "宮廷氣場下的沒有招牌字", "in a courtly register, no signage text", "courtly, no signage"],
    ["none_street", "街頭無字", "street no text", "無字、淨、街頭", "none, clean, street", "街頭質感的沒有招牌字", "with street grit, no signage text", "street-cast, no signage"],
    ["none_noir", "暗黑無字", "noir no text", "無字、淨、暗黑", "none, clean, noir", "暗調電影感的沒有招牌字", "in noir lighting, no signage text", "noir, no signage"],
    ["none_soft", "柔光無字", "soft-light no text", "無字、淨、柔光", "none, clean, soft", "柔光下的沒有招牌字", "under soft light, no signage text", "soft-lit, no signage"],
    ["none_epic", "史詩無字", "epic no text", "無字、淨、史詩", "none, clean, epic", "史詩尺度的沒有招牌字", "at epic scale, no signage text", "epic, no signage"],
    ["english_court", "宮廷英文招牌", "court English signs", "英、商、宮廷", "english, shop, courtly", "宮廷氣場下的英文店招", "in a courtly register, English shop signs", "courtly, English signage"],
    ["english_street", "街頭英文招牌", "street English signs", "英、商、街頭", "english, shop, street", "街頭質感的英文店招", "with street grit, English shop signs", "street-cast, English signage"],
    ["english_noir", "暗黑英文招牌", "noir English signs", "英、商、暗黑", "english, shop, noir", "暗調電影感的英文店招", "in noir lighting, English shop signs", "noir, English signage"],
    ["english_soft", "柔光英文招牌", "soft-light English signs", "英、商、柔光", "english, shop, soft", "柔光下的英文店招", "under soft light, English shop signs", "soft-lit, English signage"],
    ["english_epic", "史詩英文招牌", "epic English signs", "英、商、史詩", "english, shop, epic", "史詩尺度的英文店招", "at epic scale, English shop signs", "epic, English signage"],
    ["warning_court", "宮廷警告牌", "court warning signs", "警、黃、宮廷", "warning, yellow, courtly", "宮廷氣場下的黃黑警告", "in a courtly register, yellow-black warnings", "courtly, warning signage"],
    ["warning_street", "街頭警告牌", "street warning signs", "警、黃、街頭", "warning, yellow, street", "街頭質感的黃黑警告", "with street grit, yellow-black warnings", "street-cast, warning signage"],
    ["warning_noir", "暗黑警告牌", "noir warning signs", "警、黃、暗黑", "warning, yellow, noir", "暗調電影感的黃黑警告", "in noir lighting, yellow-black warnings", "noir, warning signage"],
    ["warning_soft", "柔光警告牌", "soft-light warning signs", "警、黃、柔光", "warning, yellow, soft", "柔光下的黃黑警告", "under soft light, yellow-black warnings", "soft-lit, warning signage"],
    ["warning_epic", "史詩警告牌", "epic warning signs", "警、黃、史詩", "warning, yellow, epic", "史詩尺度的黃黑警告", "at epic scale, yellow-black warnings", "epic, warning signage"],
    ["paper_notice_court", "宮廷紙告示", "court paper notices", "紙、貼、宮廷", "paper, taped, courtly", "宮廷氣場下的膠帶紙告示", "in a courtly register, taped paper notices", "courtly, paper-notice signage"],
    ["paper_notice_street", "街頭紙告示", "street paper notices", "紙、貼、街頭", "paper, taped, street", "街頭質感的膠帶紙告示", "with street grit, taped paper notices", "street-cast, paper-notice signage"],
    ["paper_notice_noir", "暗黑紙告示", "noir paper notices", "紙、貼、暗黑", "paper, taped, noir", "暗調電影感的膠帶紙告示", "in noir lighting, taped paper notices", "noir, paper-notice signage"],
    ["paper_notice_soft", "柔光紙告示", "soft-light paper notices", "紙、貼、柔光", "paper, taped, soft", "柔光下的膠帶紙告示", "under soft light, taped paper notices", "soft-lit, paper-notice signage"],
    ["paper_notice_epic", "史詩紙告示", "epic paper notices", "紙、貼、史詩", "paper, taped, epic", "史詩尺度的膠帶紙告示", "at epic scale, taped paper notices", "epic, paper-notice signage"],
    ["banner_court", "宮廷直幡", "court vertical banners", "幡、紅、宮廷", "banner, red, courtly", "宮廷氣場下的紅直幡", "in a courtly register, red vertical banners", "courtly, vertical-banner signage"],
    ["banner_street", "街頭直幡", "street vertical banners", "幡、紅、街頭", "banner, red, street", "街頭質感的紅直幡", "with street grit, red vertical banners", "street-cast, vertical-banner signage"],
    ["banner_noir", "暗黑直幡", "noir vertical banners", "幡、紅、暗黑", "banner, red, noir", "暗調電影感的紅直幡", "in noir lighting, red vertical banners", "noir, vertical-banner signage"],
    ["banner_soft", "柔光直幡", "soft-light vertical banners", "幡、紅、柔光", "banner, red, soft", "柔光下的紅直幡", "under soft light, red vertical banners", "soft-lit, vertical-banner signage"],
    ["banner_epic", "史詩直幡", "epic vertical banners", "幡、紅、史詩", "banner, red, epic", "史詩尺度的紅直幡", "at epic scale, red vertical banners", "epic, vertical-banner signage"],
    ["hologram_court", "宮廷全息字", "court hologram type", "全息、未、宮廷", "holo, future, courtly", "宮廷氣場下的懸浮全息字", "in a courtly register, floating holotype", "courtly, hologram signage"],
    ["hologram_street", "街頭全息字", "street hologram type", "全息、未、街頭", "holo, future, street", "街頭質感的懸浮全息字", "with street grit, floating holotype", "street-cast, hologram signage"],
    ["hologram_noir", "暗黑全息字", "noir hologram type", "全息、未、暗黑", "holo, future, noir", "暗調電影感的懸浮全息字", "in noir lighting, floating holotype", "noir, hologram signage"],
    ["hologram_soft", "柔光全息字", "soft-light hologram type", "全息、未、柔光", "holo, future, soft", "柔光下的懸浮全息字", "under soft light, floating holotype", "soft-lit, hologram signage"],
    ["hologram_epic", "史詩全息字", "epic hologram type", "全息、未、史詩", "holo, future, epic", "史詩尺度的懸浮全息字", "at epic scale, floating holotype", "epic, hologram signage"],
    ["graffiti_court", "宮廷塗鴉字", "court graffiti type", "塗、牆、宮廷", "graffiti, wall, courtly", "宮廷氣場下的牆面塗鴉字", "in a courtly register, wall graffiti type", "courtly, graffiti signage"],
    ["graffiti_street", "街頭塗鴉字", "street graffiti type", "塗、牆、街頭", "graffiti, wall, street", "街頭質感的牆面塗鴉字", "with street grit, wall graffiti type", "street-cast, graffiti signage"],
    ["graffiti_noir", "暗黑塗鴉字", "noir graffiti type", "塗、牆、暗黑", "graffiti, wall, noir", "暗調電影感的牆面塗鴉字", "in noir lighting, wall graffiti type", "noir, graffiti signage"],
    ["graffiti_soft", "柔光塗鴉字", "soft-light graffiti type", "塗、牆、柔光", "graffiti, wall, soft", "柔光下的牆面塗鴉字", "under soft light, wall graffiti type", "soft-lit, graffiti signage"],
    ["graffiti_epic", "史詩塗鴉字", "epic graffiti type", "塗、牆、史詩", "graffiti, wall, epic", "史詩尺度的牆面塗鴉字", "at epic scale, wall graffiti type", "epic, graffiti signage"]
  ],
    practicalLight: [
    ["tungsten_court", "宮廷鎢絲暖", "court tungsten practicals", "鎢、暖、宮廷", "tungsten, warm, courtly", "宮廷氣場下的桌燈鎢絲", "in a courtly register, warm tungsten lamps", "courtly, tungsten practical lights"],
    ["tungsten_street", "街頭鎢絲暖", "street tungsten practicals", "鎢、暖、街頭", "tungsten, warm, street", "街頭質感的桌燈鎢絲", "with street grit, warm tungsten lamps", "street-cast, tungsten practical lights"],
    ["tungsten_noir", "暗黑鎢絲暖", "noir tungsten practicals", "鎢、暖、暗黑", "tungsten, warm, noir", "暗調電影感的桌燈鎢絲", "in noir lighting, warm tungsten lamps", "noir, tungsten practical lights"],
    ["tungsten_soft", "柔光鎢絲暖", "soft-light tungsten practicals", "鎢、暖、柔光", "tungsten, warm, soft", "柔光下的桌燈鎢絲", "under soft light, warm tungsten lamps", "soft-lit, tungsten practical lights"],
    ["tungsten_epic", "史詩鎢絲暖", "epic tungsten practicals", "鎢、暖、史詩", "tungsten, warm, epic", "史詩尺度的桌燈鎢絲", "at epic scale, warm tungsten lamps", "epic, tungsten practical lights"],
    ["fluorescent_court", "宮廷日光管", "court fluorescent", "管、綠、宮廷", "tube, green, courtly", "宮廷氣場下的頂管偏綠", "in a courtly register, greenish tubes", "courtly, fluorescent practicals"],
    ["fluorescent_street", "街頭日光管", "street fluorescent", "管、綠、街頭", "tube, green, street", "街頭質感的頂管偏綠", "with street grit, greenish tubes", "street-cast, fluorescent practicals"],
    ["fluorescent_noir", "暗黑日光管", "noir fluorescent", "管、綠、暗黑", "tube, green, noir", "暗調電影感的頂管偏綠", "in noir lighting, greenish tubes", "noir, fluorescent practicals"],
    ["fluorescent_soft", "柔光日光管", "soft-light fluorescent", "管、綠、柔光", "tube, green, soft", "柔光下的頂管偏綠", "under soft light, greenish tubes", "soft-lit, fluorescent practicals"],
    ["fluorescent_epic", "史詩日光管", "epic fluorescent", "管、綠、史詩", "tube, green, epic", "史詩尺度的頂管偏綠", "at epic scale, greenish tubes", "epic, fluorescent practicals"],
    ["lantern_court", "宮廷紙燈籠", "court paper lanterns", "籠、暖點、宮廷", "lantern, warm dots, courtly", "宮廷氣場下的紙燈籠點", "in a courtly register, paper lantern dots", "courtly, paper-lantern practicals"],
    ["lantern_street", "街頭紙燈籠", "street paper lanterns", "籠、暖點、街頭", "lantern, warm dots, street", "街頭質感的紙燈籠點", "with street grit, paper lantern dots", "street-cast, paper-lantern practicals"],
    ["lantern_noir", "暗黑紙燈籠", "noir paper lanterns", "籠、暖點、暗黑", "lantern, warm dots, noir", "暗調電影感的紙燈籠點", "in noir lighting, paper lantern dots", "noir, paper-lantern practicals"],
    ["lantern_soft", "柔光紙燈籠", "soft-light paper lanterns", "籠、暖點、柔光", "lantern, warm dots, soft", "柔光下的紙燈籠點", "under soft light, paper lantern dots", "soft-lit, paper-lantern practicals"],
    ["lantern_epic", "史詩紙燈籠", "epic paper lanterns", "籠、暖點、史詩", "lantern, warm dots, epic", "史詩尺度的紙燈籠點", "at epic scale, paper lantern dots", "epic, paper-lantern practicals"],
    ["neon_prac_court", "宮廷霓虹實光", "court neon practicals", "霓虹、色、宮廷", "neon, color, courtly", "宮廷氣場下的店招霓虹照人", "in a courtly register, neon lighting faces", "courtly, neon practical lights"],
    ["neon_prac_street", "街頭霓虹實光", "street neon practicals", "霓虹、色、街頭", "neon, color, street", "街頭質感的店招霓虹照人", "with street grit, neon lighting faces", "street-cast, neon practical lights"],
    ["neon_prac_noir", "暗黑霓虹實光", "noir neon practicals", "霓虹、色、暗黑", "neon, color, noir", "暗調電影感的店招霓虹照人", "in noir lighting, neon lighting faces", "noir, neon practical lights"],
    ["neon_prac_soft", "柔光霓虹實光", "soft-light neon practicals", "霓虹、色、柔光", "neon, color, soft", "柔光下的店招霓虹照人", "under soft light, neon lighting faces", "soft-lit, neon practical lights"],
    ["neon_prac_epic", "史詩霓虹實光", "epic neon practicals", "霓虹、色、史詩", "neon, color, epic", "史詩尺度的店招霓虹照人", "at epic scale, neon lighting faces", "epic, neon practical lights"],
    ["candle_court", "宮廷燭", "court candles", "燭、跳、宮廷", "candle, flicker, courtly", "宮廷氣場下的燭火跳動", "in a courtly register, flickering candles", "courtly, candle practicals"],
    ["candle_street", "街頭燭", "street candles", "燭、跳、街頭", "candle, flicker, street", "街頭質感的燭火跳動", "with street grit, flickering candles", "street-cast, candle practicals"],
    ["candle_noir", "暗黑燭", "noir candles", "燭、跳、暗黑", "candle, flicker, noir", "暗調電影感的燭火跳動", "in noir lighting, flickering candles", "noir, candle practicals"],
    ["candle_soft", "柔光燭", "soft-light candles", "燭、跳、柔光", "candle, flicker, soft", "柔光下的燭火跳動", "under soft light, flickering candles", "soft-lit, candle practicals"],
    ["candle_epic", "史詩燭", "epic candles", "燭、跳、史詩", "candle, flicker, epic", "史詩尺度的燭火跳動", "at epic scale, flickering candles", "epic, candle practicals"],
    ["phone_court", "宮廷手機光", "court phone glow", "手機、冷、宮廷", "phone, cool, courtly", "宮廷氣場下的臉被手機照", "in a courtly register, face lit by phone", "courtly, phone-glow practical"],
    ["phone_street", "街頭手機光", "street phone glow", "手機、冷、街頭", "phone, cool, street", "街頭質感的臉被手機照", "with street grit, face lit by phone", "street-cast, phone-glow practical"],
    ["phone_noir", "暗黑手機光", "noir phone glow", "手機、冷、暗黑", "phone, cool, noir", "暗調電影感的臉被手機照", "in noir lighting, face lit by phone", "noir, phone-glow practical"],
    ["phone_soft", "柔光手機光", "soft-light phone glow", "手機、冷、柔光", "phone, cool, soft", "柔光下的臉被手機照", "under soft light, face lit by phone", "soft-lit, phone-glow practical"],
    ["phone_epic", "史詩手機光", "epic phone glow", "手機、冷、史詩", "phone, cool, epic", "史詩尺度的臉被手機照", "at epic scale, face lit by phone", "epic, phone-glow practical"],
    ["none_court", "宮廷無實用光", "court no practicals", "無、淨、宮廷", "none, clean, courtly", "宮廷氣場下的不靠道具燈", "in a courtly register, no practical lamps", "courtly, no practical lights"],
    ["none_street", "街頭無實用光", "street no practicals", "無、淨、街頭", "none, clean, street", "街頭質感的不靠道具燈", "with street grit, no practical lamps", "street-cast, no practical lights"],
    ["none_noir", "暗黑無實用光", "noir no practicals", "無、淨、暗黑", "none, clean, noir", "暗調電影感的不靠道具燈", "in noir lighting, no practical lamps", "noir, no practical lights"],
    ["none_soft", "柔光無實用光", "soft-light no practicals", "無、淨、柔光", "none, clean, soft", "柔光下的不靠道具燈", "under soft light, no practical lamps", "soft-lit, no practical lights"],
    ["none_epic", "史詩無實用光", "epic no practicals", "無、淨、史詩", "none, clean, epic", "史詩尺度的不靠道具燈", "at epic scale, no practical lamps", "epic, no practical lights"],
    ["exit_court", "宮廷安全出口綠", "court exit green", "出口、綠、宮廷", "exit, green, courtly", "宮廷氣場下的安全出口綠光", "in a courtly register, green exit glow", "courtly, exit-sign practicals"],
    ["exit_street", "街頭安全出口綠", "street exit green", "出口、綠、街頭", "exit, green, street", "街頭質感的安全出口綠光", "with street grit, green exit glow", "street-cast, exit-sign practicals"],
    ["exit_noir", "暗黑安全出口綠", "noir exit green", "出口、綠、暗黑", "exit, green, noir", "暗調電影感的安全出口綠光", "in noir lighting, green exit glow", "noir, exit-sign practicals"],
    ["exit_soft", "柔光安全出口綠", "soft-light exit green", "出口、綠、柔光", "exit, green, soft", "柔光下的安全出口綠光", "under soft light, green exit glow", "soft-lit, exit-sign practicals"],
    ["exit_epic", "史詩安全出口綠", "epic exit green", "出口、綠、史詩", "exit, green, epic", "史詩尺度的安全出口綠光", "at epic scale, green exit glow", "epic, exit-sign practicals"],
    ["monitor_court", "宮廷螢幕光", "court monitor glow", "螢、藍、宮廷", "monitor, blue, courtly", "宮廷氣場下的多螢幕藍光", "in a courtly register, blue monitor glow", "courtly, monitor-glow practicals"],
    ["monitor_street", "街頭螢幕光", "street monitor glow", "螢、藍、街頭", "monitor, blue, street", "街頭質感的多螢幕藍光", "with street grit, blue monitor glow", "street-cast, monitor-glow practicals"],
    ["monitor_noir", "暗黑螢幕光", "noir monitor glow", "螢、藍、暗黑", "monitor, blue, noir", "暗調電影感的多螢幕藍光", "in noir lighting, blue monitor glow", "noir, monitor-glow practicals"],
    ["monitor_soft", "柔光螢幕光", "soft-light monitor glow", "螢、藍、柔光", "monitor, blue, soft", "柔光下的多螢幕藍光", "under soft light, blue monitor glow", "soft-lit, monitor-glow practicals"],
    ["monitor_epic", "史詩螢幕光", "epic monitor glow", "螢、藍、史詩", "monitor, blue, epic", "史詩尺度的多螢幕藍光", "at epic scale, blue monitor glow", "epic, monitor-glow practicals"],
    ["streetlamp_court", "宮廷路燈橙", "court streetlamp orange", "路、橙、宮廷", "street, orange, courtly", "宮廷氣場下的窗外路燈橙", "in a courtly register, orange street spill", "courtly, streetlamp practicals"],
    ["streetlamp_street", "街頭路燈橙", "street streetlamp orange", "路、橙、街頭", "street, orange, street", "街頭質感的窗外路燈橙", "with street grit, orange street spill", "street-cast, streetlamp practicals"],
    ["streetlamp_noir", "暗黑路燈橙", "noir streetlamp orange", "路、橙、暗黑", "street, orange, noir", "暗調電影感的窗外路燈橙", "in noir lighting, orange street spill", "noir, streetlamp practicals"],
    ["streetlamp_soft", "柔光路燈橙", "soft-light streetlamp orange", "路、橙、柔光", "street, orange, soft", "柔光下的窗外路燈橙", "under soft light, orange street spill", "soft-lit, streetlamp practicals"],
    ["streetlamp_epic", "史詩路燈橙", "epic streetlamp orange", "路、橙、史詩", "street, orange, epic", "史詩尺度的窗外路燈橙", "at epic scale, orange street spill", "epic, streetlamp practicals"]
  ],
    textile: [
    ["sheer_curtain_court", "宮廷薄紗簾", "court sheer curtains", "紗、窗、宮廷", "sheer, window, courtly", "宮廷氣場下的薄窗紗", "in a courtly register, sheer window cloth", "courtly, sheer curtain textiles"],
    ["sheer_curtain_street", "街頭薄紗簾", "street sheer curtains", "紗、窗、街頭", "sheer, window, street", "街頭質感的薄窗紗", "with street grit, sheer window cloth", "street-cast, sheer curtain textiles"],
    ["sheer_curtain_noir", "暗黑薄紗簾", "noir sheer curtains", "紗、窗、暗黑", "sheer, window, noir", "暗調電影感的薄窗紗", "in noir lighting, sheer window cloth", "noir, sheer curtain textiles"],
    ["sheer_curtain_soft", "柔光薄紗簾", "soft-light sheer curtains", "紗、窗、柔光", "sheer, window, soft", "柔光下的薄窗紗", "under soft light, sheer window cloth", "soft-lit, sheer curtain textiles"],
    ["sheer_curtain_epic", "史詩薄紗簾", "epic sheer curtains", "紗、窗、史詩", "sheer, window, epic", "史詩尺度的薄窗紗", "at epic scale, sheer window cloth", "epic, sheer curtain textiles"],
    ["heavy_drape_court", "宮廷厚絨簾", "court heavy drapes", "絨、遮、宮廷", "velvet, block, courtly", "宮廷氣場下的厚遮光簾", "in a courtly register, heavy blackout drapes", "courtly, heavy drape textiles"],
    ["heavy_drape_street", "街頭厚絨簾", "street heavy drapes", "絨、遮、街頭", "velvet, block, street", "街頭質感的厚遮光簾", "with street grit, heavy blackout drapes", "street-cast, heavy drape textiles"],
    ["heavy_drape_noir", "暗黑厚絨簾", "noir heavy drapes", "絨、遮、暗黑", "velvet, block, noir", "暗調電影感的厚遮光簾", "in noir lighting, heavy blackout drapes", "noir, heavy drape textiles"],
    ["heavy_drape_soft", "柔光厚絨簾", "soft-light heavy drapes", "絨、遮、柔光", "velvet, block, soft", "柔光下的厚遮光簾", "under soft light, heavy blackout drapes", "soft-lit, heavy drape textiles"],
    ["heavy_drape_epic", "史詩厚絨簾", "epic heavy drapes", "絨、遮、史詩", "velvet, block, epic", "史詩尺度的厚遮光簾", "at epic scale, heavy blackout drapes", "epic, heavy drape textiles"],
    ["bedsheet_mess_court", "宮廷亂床單", "court messy sheets", "床、亂、宮廷", "bed, mess, courtly", "宮廷氣場下的未摺床單", "in a courtly register, unmade sheets", "courtly, messy-sheet textiles"],
    ["bedsheet_mess_street", "街頭亂床單", "street messy sheets", "床、亂、街頭", "bed, mess, street", "街頭質感的未摺床單", "with street grit, unmade sheets", "street-cast, messy-sheet textiles"],
    ["bedsheet_mess_noir", "暗黑亂床單", "noir messy sheets", "床、亂、暗黑", "bed, mess, noir", "暗調電影感的未摺床單", "in noir lighting, unmade sheets", "noir, messy-sheet textiles"],
    ["bedsheet_mess_soft", "柔光亂床單", "soft-light messy sheets", "床、亂、柔光", "bed, mess, soft", "柔光下的未摺床單", "under soft light, unmade sheets", "soft-lit, messy-sheet textiles"],
    ["bedsheet_mess_epic", "史詩亂床單", "epic messy sheets", "床、亂、史詩", "bed, mess, epic", "史詩尺度的未摺床單", "at epic scale, unmade sheets", "epic, messy-sheet textiles"],
    ["none_court", "宮廷少布", "court few textiles", "少、硬、宮廷", "few, hard, courtly", "宮廷氣場下的幾乎無軟布", "in a courtly register, almost no soft cloth", "courtly, few textiles"],
    ["none_street", "街頭少布", "street few textiles", "少、硬、街頭", "few, hard, street", "街頭質感的幾乎無軟布", "with street grit, almost no soft cloth", "street-cast, few textiles"],
    ["none_noir", "暗黑少布", "noir few textiles", "少、硬、暗黑", "few, hard, noir", "暗調電影感的幾乎無軟布", "in noir lighting, almost no soft cloth", "noir, few textiles"],
    ["none_soft", "柔光少布", "soft-light few textiles", "少、硬、柔光", "few, hard, soft", "柔光下的幾乎無軟布", "under soft light, almost no soft cloth", "soft-lit, few textiles"],
    ["none_epic", "史詩少布", "epic few textiles", "少、硬、史詩", "few, hard, epic", "史詩尺度的幾乎無軟布", "at epic scale, almost no soft cloth", "epic, few textiles"],
    ["flags_court", "宮廷旗幡", "court flags", "旗、動、宮廷", "flag, move, courtly", "宮廷氣場下的可動旗幡", "in a courtly register, moving flags", "courtly, flag textiles"],
    ["flags_street", "街頭旗幡", "street flags", "旗、動、街頭", "flag, move, street", "街頭質感的可動旗幡", "with street grit, moving flags", "street-cast, flag textiles"],
    ["flags_noir", "暗黑旗幡", "noir flags", "旗、動、暗黑", "flag, move, noir", "暗調電影感的可動旗幡", "in noir lighting, moving flags", "noir, flag textiles"],
    ["flags_soft", "柔光旗幡", "soft-light flags", "旗、動、柔光", "flag, move, soft", "柔光下的可動旗幡", "under soft light, moving flags", "soft-lit, flag textiles"],
    ["flags_epic", "史詩旗幡", "epic flags", "旗、動、史詩", "flag, move, epic", "史詩尺度的可動旗幡", "at epic scale, moving flags", "epic, flag textiles"],
    ["plastic_court", "宮廷膠布防塵", "court plastic sheets", "膠、塵、宮廷", "plastic, dust, courtly", "宮廷氣場下的防塵膠布", "in a courtly register, dust plastic sheets", "courtly, plastic-sheet textiles"],
    ["plastic_street", "街頭膠布防塵", "street plastic sheets", "膠、塵、街頭", "plastic, dust, street", "街頭質感的防塵膠布", "with street grit, dust plastic sheets", "street-cast, plastic-sheet textiles"],
    ["plastic_noir", "暗黑膠布防塵", "noir plastic sheets", "膠、塵、暗黑", "plastic, dust, noir", "暗調電影感的防塵膠布", "in noir lighting, dust plastic sheets", "noir, plastic-sheet textiles"],
    ["plastic_soft", "柔光膠布防塵", "soft-light plastic sheets", "膠、塵、柔光", "plastic, dust, soft", "柔光下的防塵膠布", "under soft light, dust plastic sheets", "soft-lit, plastic-sheet textiles"],
    ["plastic_epic", "史詩膠布防塵", "epic plastic sheets", "膠、塵、史詩", "plastic, dust, epic", "史詩尺度的防塵膠布", "at epic scale, dust plastic sheets", "epic, plastic-sheet textiles"],
    ["rug_court", "宮廷舊地毯", "court old rug", "毯、舊、宮廷", "rug, old, courtly", "宮廷氣場下的舊花地毯", "in a courtly register, worn patterned rug", "courtly, old-rug textiles"],
    ["rug_street", "街頭舊地毯", "street old rug", "毯、舊、街頭", "rug, old, street", "街頭質感的舊花地毯", "with street grit, worn patterned rug", "street-cast, old-rug textiles"],
    ["rug_noir", "暗黑舊地毯", "noir old rug", "毯、舊、暗黑", "rug, old, noir", "暗調電影感的舊花地毯", "in noir lighting, worn patterned rug", "noir, old-rug textiles"],
    ["rug_soft", "柔光舊地毯", "soft-light old rug", "毯、舊、柔光", "rug, old, soft", "柔光下的舊花地毯", "under soft light, worn patterned rug", "soft-lit, old-rug textiles"],
    ["rug_epic", "史詩舊地毯", "epic old rug", "毯、舊、史詩", "rug, old, epic", "史詩尺度的舊花地毯", "at epic scale, worn patterned rug", "epic, old-rug textiles"],
    ["mosquito_court", "宮廷蚊帳", "court mosquito net", "帳、紗、宮廷", "net, gauze, courtly", "宮廷氣場下的床上蚊帳", "in a courtly register, bed mosquito net", "courtly, mosquito-net textiles"],
    ["mosquito_street", "街頭蚊帳", "street mosquito net", "帳、紗、街頭", "net, gauze, street", "街頭質感的床上蚊帳", "with street grit, bed mosquito net", "street-cast, mosquito-net textiles"],
    ["mosquito_noir", "暗黑蚊帳", "noir mosquito net", "帳、紗、暗黑", "net, gauze, noir", "暗調電影感的床上蚊帳", "in noir lighting, bed mosquito net", "noir, mosquito-net textiles"],
    ["mosquito_soft", "柔光蚊帳", "soft-light mosquito net", "帳、紗、柔光", "net, gauze, soft", "柔光下的床上蚊帳", "under soft light, bed mosquito net", "soft-lit, mosquito-net textiles"],
    ["mosquito_epic", "史詩蚊帳", "epic mosquito net", "帳、紗、史詩", "net, gauze, epic", "史詩尺度的床上蚊帳", "at epic scale, bed mosquito net", "epic, mosquito-net textiles"],
    ["tapestry_court", "宮廷壁毯", "court wall tapestry", "壁、織、宮廷", "wall, weave, courtly", "宮廷氣場下的牆上織毯", "in a courtly register, woven wall hanging", "courtly, tapestry textiles"],
    ["tapestry_street", "街頭壁毯", "street wall tapestry", "壁、織、街頭", "wall, weave, street", "街頭質感的牆上織毯", "with street grit, woven wall hanging", "street-cast, tapestry textiles"],
    ["tapestry_noir", "暗黑壁毯", "noir wall tapestry", "壁、織、暗黑", "wall, weave, noir", "暗調電影感的牆上織毯", "in noir lighting, woven wall hanging", "noir, tapestry textiles"],
    ["tapestry_soft", "柔光壁毯", "soft-light wall tapestry", "壁、織、柔光", "wall, weave, soft", "柔光下的牆上織毯", "under soft light, woven wall hanging", "soft-lit, tapestry textiles"],
    ["tapestry_epic", "史詩壁毯", "epic wall tapestry", "壁、織、史詩", "wall, weave, epic", "史詩尺度的牆上織毯", "at epic scale, woven wall hanging", "epic, tapestry textiles"],
    ["laundry_court", "宮廷晾衣", "court hanging laundry", "晾、生活、宮廷", "laundry, life, courtly", "宮廷氣場下的橫杆晾衣", "in a courtly register, laundry on a line", "courtly, hanging-laundry textiles"],
    ["laundry_street", "街頭晾衣", "street hanging laundry", "晾、生活、街頭", "laundry, life, street", "街頭質感的橫杆晾衣", "with street grit, laundry on a line", "street-cast, hanging-laundry textiles"],
    ["laundry_noir", "暗黑晾衣", "noir hanging laundry", "晾、生活、暗黑", "laundry, life, noir", "暗調電影感的橫杆晾衣", "in noir lighting, laundry on a line", "noir, hanging-laundry textiles"],
    ["laundry_soft", "柔光晾衣", "soft-light hanging laundry", "晾、生活、柔光", "laundry, life, soft", "柔光下的橫杆晾衣", "under soft light, laundry on a line", "soft-lit, hanging-laundry textiles"],
    ["laundry_epic", "史詩晾衣", "epic hanging laundry", "晾、生活、史詩", "laundry, life, epic", "史詩尺度的橫杆晾衣", "at epic scale, laundry on a line", "epic, hanging-laundry textiles"]
  ],
    debris: [
    ["none_court", "宮廷無殘件", "court no debris", "無、淨、宮廷", "none, clean, courtly", "宮廷氣場下的地面乾淨", "in a courtly register, clean floor", "courtly, no debris"],
    ["none_street", "街頭無殘件", "street no debris", "無、淨、街頭", "none, clean, street", "街頭質感的地面乾淨", "with street grit, clean floor", "street-cast, no debris"],
    ["none_noir", "暗黑無殘件", "noir no debris", "無、淨、暗黑", "none, clean, noir", "暗調電影感的地面乾淨", "in noir lighting, clean floor", "noir, no debris"],
    ["none_soft", "柔光無殘件", "soft-light no debris", "無、淨、柔光", "none, clean, soft", "柔光下的地面乾淨", "under soft light, clean floor", "soft-lit, no debris"],
    ["none_epic", "史詩無殘件", "epic no debris", "無、淨、史詩", "none, clean, epic", "史詩尺度的地面乾淨", "at epic scale, clean floor", "epic, no debris"],
    ["rubble_court", "宮廷磚碎", "court rubble", "磚、碎、宮廷", "brick, break, courtly", "宮廷氣場下的磚石碎", "in a courtly register, brick rubble", "courtly, rubble debris"],
    ["rubble_street", "街頭磚碎", "street rubble", "磚、碎、街頭", "brick, break, street", "街頭質感的磚石碎", "with street grit, brick rubble", "street-cast, rubble debris"],
    ["rubble_noir", "暗黑磚碎", "noir rubble", "磚、碎、暗黑", "brick, break, noir", "暗調電影感的磚石碎", "in noir lighting, brick rubble", "noir, rubble debris"],
    ["rubble_soft", "柔光磚碎", "soft-light rubble", "磚、碎、柔光", "brick, break, soft", "柔光下的磚石碎", "under soft light, brick rubble", "soft-lit, rubble debris"],
    ["rubble_epic", "史詩磚碎", "epic rubble", "磚、碎、史詩", "brick, break, epic", "史詩尺度的磚石碎", "at epic scale, brick rubble", "epic, rubble debris"],
    ["glass_court", "宮廷碎玻璃", "court broken glass", "玻、閃、宮廷", "glass, glint, courtly", "宮廷氣場下的地上碎玻璃", "in a courtly register, glass on floor", "courtly, broken-glass debris"],
    ["glass_street", "街頭碎玻璃", "street broken glass", "玻、閃、街頭", "glass, glint, street", "街頭質感的地上碎玻璃", "with street grit, glass on floor", "street-cast, broken-glass debris"],
    ["glass_noir", "暗黑碎玻璃", "noir broken glass", "玻、閃、暗黑", "glass, glint, noir", "暗調電影感的地上碎玻璃", "in noir lighting, glass on floor", "noir, broken-glass debris"],
    ["glass_soft", "柔光碎玻璃", "soft-light broken glass", "玻、閃、柔光", "glass, glint, soft", "柔光下的地上碎玻璃", "under soft light, glass on floor", "soft-lit, broken-glass debris"],
    ["glass_epic", "史詩碎玻璃", "epic broken glass", "玻、閃、史詩", "glass, glint, epic", "史詩尺度的地上碎玻璃", "at epic scale, glass on floor", "epic, broken-glass debris"],
    ["leaves_court", "宮廷落葉", "court fallen leaves", "葉、風、宮廷", "leaf, wind, courtly", "宮廷氣場下的地面落葉", "in a courtly register, leaves on ground", "courtly, leaf debris"],
    ["leaves_street", "街頭落葉", "street fallen leaves", "葉、風、街頭", "leaf, wind, street", "街頭質感的地面落葉", "with street grit, leaves on ground", "street-cast, leaf debris"],
    ["leaves_noir", "暗黑落葉", "noir fallen leaves", "葉、風、暗黑", "leaf, wind, noir", "暗調電影感的地面落葉", "in noir lighting, leaves on ground", "noir, leaf debris"],
    ["leaves_soft", "柔光落葉", "soft-light fallen leaves", "葉、風、柔光", "leaf, wind, soft", "柔光下的地面落葉", "under soft light, leaves on ground", "soft-lit, leaf debris"],
    ["leaves_epic", "史詩落葉", "epic fallen leaves", "葉、風、史詩", "leaf, wind, epic", "史詩尺度的地面落葉", "at epic scale, leaves on ground", "epic, leaf debris"],
    ["ash_court", "宮廷灰燼", "court ash", "灰、火、宮廷", "ash, fire, courtly", "宮廷氣場下的薄灰燼", "in a courtly register, thin ash layer", "courtly, ash debris"],
    ["ash_street", "街頭灰燼", "street ash", "灰、火、街頭", "ash, fire, street", "街頭質感的薄灰燼", "with street grit, thin ash layer", "street-cast, ash debris"],
    ["ash_noir", "暗黑灰燼", "noir ash", "灰、火、暗黑", "ash, fire, noir", "暗調電影感的薄灰燼", "in noir lighting, thin ash layer", "noir, ash debris"],
    ["ash_soft", "柔光灰燼", "soft-light ash", "灰、火、柔光", "ash, fire, soft", "柔光下的薄灰燼", "under soft light, thin ash layer", "soft-lit, ash debris"],
    ["ash_epic", "史詩灰燼", "epic ash", "灰、火、史詩", "ash, fire, epic", "史詩尺度的薄灰燼", "at epic scale, thin ash layer", "epic, ash debris"],
    ["snow_court", "宮廷殘雪泥", "court dirty snow", "雪、泥、宮廷", "snow, mud, courtly", "宮廷氣場下的髒雪泥", "in a courtly register, dirty snow slush", "courtly, dirty-snow debris"],
    ["snow_street", "街頭殘雪泥", "street dirty snow", "雪、泥、街頭", "snow, mud, street", "街頭質感的髒雪泥", "with street grit, dirty snow slush", "street-cast, dirty-snow debris"],
    ["snow_noir", "暗黑殘雪泥", "noir dirty snow", "雪、泥、暗黑", "snow, mud, noir", "暗調電影感的髒雪泥", "in noir lighting, dirty snow slush", "noir, dirty-snow debris"],
    ["snow_soft", "柔光殘雪泥", "soft-light dirty snow", "雪、泥、柔光", "snow, mud, soft", "柔光下的髒雪泥", "under soft light, dirty snow slush", "soft-lit, dirty-snow debris"],
    ["snow_epic", "史詩殘雪泥", "epic dirty snow", "雪、泥、史詩", "snow, mud, epic", "史詩尺度的髒雪泥", "at epic scale, dirty snow slush", "epic, dirty-snow debris"],
    ["trash_court", "宮廷塑膠袋", "court plastic trash", "塑、風、宮廷", "plastic, wind, courtly", "宮廷氣場下的風吹塑膠袋", "in a courtly register, windblown plastic", "courtly, plastic-trash debris"],
    ["trash_street", "街頭塑膠袋", "street plastic trash", "塑、風、街頭", "plastic, wind, street", "街頭質感的風吹塑膠袋", "with street grit, windblown plastic", "street-cast, plastic-trash debris"],
    ["trash_noir", "暗黑塑膠袋", "noir plastic trash", "塑、風、暗黑", "plastic, wind, noir", "暗調電影感的風吹塑膠袋", "in noir lighting, windblown plastic", "noir, plastic-trash debris"],
    ["trash_soft", "柔光塑膠袋", "soft-light plastic trash", "塑、風、柔光", "plastic, wind, soft", "柔光下的風吹塑膠袋", "under soft light, windblown plastic", "soft-lit, plastic-trash debris"],
    ["trash_epic", "史詩塑膠袋", "epic plastic trash", "塑、風、史詩", "plastic, wind, epic", "史詩尺度的風吹塑膠袋", "at epic scale, windblown plastic", "epic, plastic-trash debris"],
    ["petals_court", "宮廷落花", "court fallen petals", "花、地、宮廷", "petal, ground, courtly", "宮廷氣場下的地面落花", "in a courtly register, petals on ground", "courtly, petal debris"],
    ["petals_street", "街頭落花", "street fallen petals", "花、地、街頭", "petal, ground, street", "街頭質感的地面落花", "with street grit, petals on ground", "street-cast, petal debris"],
    ["petals_noir", "暗黑落花", "noir fallen petals", "花、地、暗黑", "petal, ground, noir", "暗調電影感的地面落花", "in noir lighting, petals on ground", "noir, petal debris"],
    ["petals_soft", "柔光落花", "soft-light fallen petals", "花、地、柔光", "petal, ground, soft", "柔光下的地面落花", "under soft light, petals on ground", "soft-lit, petal debris"],
    ["petals_epic", "史詩落花", "epic fallen petals", "花、地、史詩", "petal, ground, epic", "史詩尺度的地面落花", "at epic scale, petals on ground", "epic, petal debris"],
    ["shell_court", "宮廷彈殼", "court shell casings", "彈、金、宮廷", "casing, metal, courtly", "宮廷氣場下的幾枚彈殼", "in a courtly register, a few casings", "courtly, shell-casing debris"],
    ["shell_street", "街頭彈殼", "street shell casings", "彈、金、街頭", "casing, metal, street", "街頭質感的幾枚彈殼", "with street grit, a few casings", "street-cast, shell-casing debris"],
    ["shell_noir", "暗黑彈殼", "noir shell casings", "彈、金、暗黑", "casing, metal, noir", "暗調電影感的幾枚彈殼", "in noir lighting, a few casings", "noir, shell-casing debris"],
    ["shell_soft", "柔光彈殼", "soft-light shell casings", "彈、金、柔光", "casing, metal, soft", "柔光下的幾枚彈殼", "under soft light, a few casings", "soft-lit, shell-casing debris"],
    ["shell_epic", "史詩彈殼", "epic shell casings", "彈、金、史詩", "casing, metal, epic", "史詩尺度的幾枚彈殼", "at epic scale, a few casings", "epic, shell-casing debris"],
    ["water_court", "宮廷積水反光", "court standing water", "水、反、宮廷", "water, reflect, courtly", "宮廷氣場下的地面積水", "in a courtly register, floor puddles", "courtly, standing-water debris"],
    ["water_street", "街頭積水反光", "street standing water", "水、反、街頭", "water, reflect, street", "街頭質感的地面積水", "with street grit, floor puddles", "street-cast, standing-water debris"],
    ["water_noir", "暗黑積水反光", "noir standing water", "水、反、暗黑", "water, reflect, noir", "暗調電影感的地面積水", "in noir lighting, floor puddles", "noir, standing-water debris"],
    ["water_soft", "柔光積水反光", "soft-light standing water", "水、反、柔光", "water, reflect, soft", "柔光下的地面積水", "under soft light, floor puddles", "soft-lit, standing-water debris"],
    ["water_epic", "史詩積水反光", "epic standing water", "水、反、史詩", "water, reflect, epic", "史詩尺度的地面積水", "at epic scale, floor puddles", "epic, standing-water debris"]
  ]
  }
})
