/**
 * styleNote field kit catalog (50+ templates per part).
 */
import { defineFieldKit } from '../fieldKit'

export const STYLENOTE_KIT = defineFieldKit({
  key: "styleNoteKit",
  parts: ["palette","grain","contrast","eraGrade","atmosphere","lensFeel"] as const,
  partLabels: {
    palette: { zhHK: "色盤", zhCN: "色盘", en: "Palette" },
    grain: { zhHK: "顆粒", zhCN: "颗粒", en: "Grain" },
    contrast: { zhHK: "反差", zhCN: "反差", en: "Contrast" },
    eraGrade: { zhHK: "調色年代", zhCN: "调色年代", en: "Grade era" },
    atmosphere: { zhHK: "空氣", zhCN: "空气", en: "Atmosphere" },
    lensFeel: { zhHK: "鏡頭感", zhCN: "镜头感", en: "Lens feel" }
  },

  rows: {
    palette: [
    ["teal_orange_court", "宮廷青橙", "court teal-orange", "青、橙、宮廷", "teal, orange, courtly", "宮廷氣場下的商業青橙", "in a courtly register, commercial teal-orange", "courtly, teal-orange palette"],
    ["teal_orange_street", "街頭青橙", "street teal-orange", "青、橙、街頭", "teal, orange, street", "街頭質感的商業青橙", "with street grit, commercial teal-orange", "street-cast, teal-orange palette"],
    ["teal_orange_noir", "暗黑青橙", "noir teal-orange", "青、橙、暗黑", "teal, orange, noir", "暗調電影感的商業青橙", "in noir lighting, commercial teal-orange", "noir, teal-orange palette"],
    ["teal_orange_soft", "柔光青橙", "soft-light teal-orange", "青、橙、柔光", "teal, orange, soft", "柔光下的商業青橙", "under soft light, commercial teal-orange", "soft-lit, teal-orange palette"],
    ["teal_orange_epic", "史詩青橙", "epic teal-orange", "青、橙、史詩", "teal, orange, epic", "史詩尺度的商業青橙", "at epic scale, commercial teal-orange", "epic, teal-orange palette"],
    ["bleach_court", "宮廷冷青漂白", "court bleach bypass cold", "漂、冷、宮廷", "bleach, cold, courtly", "宮廷氣場下的冷青漂白", "in a courtly register, cold bleach tones", "courtly, bleach-bypass palette"],
    ["bleach_street", "街頭冷青漂白", "street bleach bypass cold", "漂、冷、街頭", "bleach, cold, street", "街頭質感的冷青漂白", "with street grit, cold bleach tones", "street-cast, bleach-bypass palette"],
    ["bleach_noir", "暗黑冷青漂白", "noir bleach bypass cold", "漂、冷、暗黑", "bleach, cold, noir", "暗調電影感的冷青漂白", "in noir lighting, cold bleach tones", "noir, bleach-bypass palette"],
    ["bleach_soft", "柔光冷青漂白", "soft-light bleach bypass cold", "漂、冷、柔光", "bleach, cold, soft", "柔光下的冷青漂白", "under soft light, cold bleach tones", "soft-lit, bleach-bypass palette"],
    ["bleach_epic", "史詩冷青漂白", "epic bleach bypass cold", "漂、冷、史詩", "bleach, cold, epic", "史詩尺度的冷青漂白", "at epic scale, cold bleach tones", "epic, bleach-bypass palette"],
    ["candy_court", "宮廷糖果高飽", "court candy sat", "糖、飽、宮廷", "candy, sat, courtly", "宮廷氣場下的高飽和糖色", "in a courtly register, high-sat candy colors", "courtly, candy palette"],
    ["candy_street", "街頭糖果高飽", "street candy sat", "糖、飽、街頭", "candy, sat, street", "街頭質感的高飽和糖色", "with street grit, high-sat candy colors", "street-cast, candy palette"],
    ["candy_noir", "暗黑糖果高飽", "noir candy sat", "糖、飽、暗黑", "candy, sat, noir", "暗調電影感的高飽和糖色", "in noir lighting, high-sat candy colors", "noir, candy palette"],
    ["candy_soft", "柔光糖果高飽", "soft-light candy sat", "糖、飽、柔光", "candy, sat, soft", "柔光下的高飽和糖色", "under soft light, high-sat candy colors", "soft-lit, candy palette"],
    ["candy_epic", "史詩糖果高飽", "epic candy sat", "糖、飽、史詩", "candy, sat, epic", "史詩尺度的高飽和糖色", "at epic scale, high-sat candy colors", "epic, candy palette"],
    ["ink_wash_court", "宮廷水墨淡", "court ink-wash", "墨、淡、宮廷", "ink, pale, courtly", "宮廷氣場下的近水墨淡彩", "in a courtly register, near ink-wash pale", "courtly, ink-wash palette"],
    ["ink_wash_street", "街頭水墨淡", "street ink-wash", "墨、淡、街頭", "ink, pale, street", "街頭質感的近水墨淡彩", "with street grit, near ink-wash pale", "street-cast, ink-wash palette"],
    ["ink_wash_noir", "暗黑水墨淡", "noir ink-wash", "墨、淡、暗黑", "ink, pale, noir", "暗調電影感的近水墨淡彩", "in noir lighting, near ink-wash pale", "noir, ink-wash palette"],
    ["ink_wash_soft", "柔光水墨淡", "soft-light ink-wash", "墨、淡、柔光", "ink, pale, soft", "柔光下的近水墨淡彩", "under soft light, near ink-wash pale", "soft-lit, ink-wash palette"],
    ["ink_wash_epic", "史詩水墨淡", "epic ink-wash", "墨、淡、史詩", "ink, pale, epic", "史詩尺度的近水墨淡彩", "at epic scale, near ink-wash pale", "epic, ink-wash palette"],
    ["night_blue_court", "宮廷夜藍", "court night blue", "夜、藍、宮廷", "night, blue, courtly", "宮廷氣場下的大面積夜藍", "in a courtly register, large night blue", "courtly, night-blue palette"],
    ["night_blue_street", "街頭夜藍", "street night blue", "夜、藍、街頭", "night, blue, street", "街頭質感的大面積夜藍", "with street grit, large night blue", "street-cast, night-blue palette"],
    ["night_blue_noir", "暗黑夜藍", "noir night blue", "夜、藍、暗黑", "night, blue, noir", "暗調電影感的大面積夜藍", "in noir lighting, large night blue", "noir, night-blue palette"],
    ["night_blue_soft", "柔光夜藍", "soft-light night blue", "夜、藍、柔光", "night, blue, soft", "柔光下的大面積夜藍", "under soft light, large night blue", "soft-lit, night-blue palette"],
    ["night_blue_epic", "史詩夜藍", "epic night blue", "夜、藍、史詩", "night, blue, epic", "史詩尺度的大面積夜藍", "at epic scale, large night blue", "epic, night-blue palette"],
    ["amber_court", "宮廷全琥珀", "court all amber", "琥、暖、宮廷", "amber, warm, courtly", "宮廷氣場下的幾乎全暖琥", "in a courtly register, almost all amber", "courtly, amber palette"],
    ["amber_street", "街頭全琥珀", "street all amber", "琥、暖、街頭", "amber, warm, street", "街頭質感的幾乎全暖琥", "with street grit, almost all amber", "street-cast, amber palette"],
    ["amber_noir", "暗黑全琥珀", "noir all amber", "琥、暖、暗黑", "amber, warm, noir", "暗調電影感的幾乎全暖琥", "in noir lighting, almost all amber", "noir, amber palette"],
    ["amber_soft", "柔光全琥珀", "soft-light all amber", "琥、暖、柔光", "amber, warm, soft", "柔光下的幾乎全暖琥", "under soft light, almost all amber", "soft-lit, amber palette"],
    ["amber_epic", "史詩全琥珀", "epic all amber", "琥、暖、史詩", "amber, warm, epic", "史詩尺度的幾乎全暖琥", "at epic scale, almost all amber", "epic, amber palette"],
    ["bw_court", "宮廷黑白", "court black and white", "黑白、骨、宮廷", "bw, bone, courtly", "宮廷氣場下的去色黑白", "in a courtly register, desaturated B&W", "courtly, black-and-white palette"],
    ["bw_street", "街頭黑白", "street black and white", "黑白、骨、街頭", "bw, bone, street", "街頭質感的去色黑白", "with street grit, desaturated B&W", "street-cast, black-and-white palette"],
    ["bw_noir", "暗黑黑白", "noir black and white", "黑白、骨、暗黑", "bw, bone, noir", "暗調電影感的去色黑白", "in noir lighting, desaturated B&W", "noir, black-and-white palette"],
    ["bw_soft", "柔光黑白", "soft-light black and white", "黑白、骨、柔光", "bw, bone, soft", "柔光下的去色黑白", "under soft light, desaturated B&W", "soft-lit, black-and-white palette"],
    ["bw_epic", "史詩黑白", "epic black and white", "黑白、骨、史詩", "bw, bone, epic", "史詩尺度的去色黑白", "at epic scale, desaturated B&W", "epic, black-and-white palette"],
    ["pastel_fade_court", "宮廷舊粉", "court faded pastel", "粉、舊、宮廷", "pastel, fade, courtly", "宮廷氣場下的褪了的粉", "in a courtly register, faded pastels", "courtly, faded-pastel palette"],
    ["pastel_fade_street", "街頭舊粉", "street faded pastel", "粉、舊、街頭", "pastel, fade, street", "街頭質感的褪了的粉", "with street grit, faded pastels", "street-cast, faded-pastel palette"],
    ["pastel_fade_noir", "暗黑舊粉", "noir faded pastel", "粉、舊、暗黑", "pastel, fade, noir", "暗調電影感的褪了的粉", "in noir lighting, faded pastels", "noir, faded-pastel palette"],
    ["pastel_fade_soft", "柔光舊粉", "soft-light faded pastel", "粉、舊、柔光", "pastel, fade, soft", "柔光下的褪了的粉", "under soft light, faded pastels", "soft-lit, faded-pastel palette"],
    ["pastel_fade_epic", "史詩舊粉", "epic faded pastel", "粉、舊、史詩", "pastel, fade, epic", "史詩尺度的褪了的粉", "at epic scale, faded pastels", "epic, faded-pastel palette"],
    ["neon_night_court", "宮廷霓虹夜", "court neon night", "霓、夜、宮廷", "neon, night, courtly", "宮廷氣場下的霓虹切夜黑", "in a courtly register, neon cutting night black", "courtly, neon-night palette"],
    ["neon_night_street", "街頭霓虹夜", "street neon night", "霓、夜、街頭", "neon, night, street", "街頭質感的霓虹切夜黑", "with street grit, neon cutting night black", "street-cast, neon-night palette"],
    ["neon_night_noir", "暗黑霓虹夜", "noir neon night", "霓、夜、暗黑", "neon, night, noir", "暗調電影感的霓虹切夜黑", "in noir lighting, neon cutting night black", "noir, neon-night palette"],
    ["neon_night_soft", "柔光霓虹夜", "soft-light neon night", "霓、夜、柔光", "neon, night, soft", "柔光下的霓虹切夜黑", "under soft light, neon cutting night black", "soft-lit, neon-night palette"],
    ["neon_night_epic", "史詩霓虹夜", "epic neon night", "霓、夜、史詩", "neon, night, epic", "史詩尺度的霓虹切夜黑", "at epic scale, neon cutting night black", "epic, neon-night palette"],
    ["earth_court", "宮廷土色克制", "court restrained earth", "土、克、宮廷", "earth, hold, courtly", "宮廷氣場下的褐綠克制", "in a courtly register, held brown-green", "courtly, restrained earth palette"],
    ["earth_street", "街頭土色克制", "street restrained earth", "土、克、街頭", "earth, hold, street", "街頭質感的褐綠克制", "with street grit, held brown-green", "street-cast, restrained earth palette"],
    ["earth_noir", "暗黑土色克制", "noir restrained earth", "土、克、暗黑", "earth, hold, noir", "暗調電影感的褐綠克制", "in noir lighting, held brown-green", "noir, restrained earth palette"],
    ["earth_soft", "柔光土色克制", "soft-light restrained earth", "土、克、柔光", "earth, hold, soft", "柔光下的褐綠克制", "under soft light, held brown-green", "soft-lit, restrained earth palette"],
    ["earth_epic", "史詩土色克制", "epic restrained earth", "土、克、史詩", "earth, hold, epic", "史詩尺度的褐綠克制", "at epic scale, held brown-green", "epic, restrained earth palette"]
  ],
    grain: [
    ["clean_court", "宮廷極淨", "court clean digital", "淨、數、宮廷", "clean, digital, courtly", "宮廷氣場下的幾乎無顆粒", "in a courtly register, almost no grain", "courtly, clean digital grain"],
    ["clean_street", "街頭極淨", "street clean digital", "淨、數、街頭", "clean, digital, street", "街頭質感的幾乎無顆粒", "with street grit, almost no grain", "street-cast, clean digital grain"],
    ["clean_noir", "暗黑極淨", "noir clean digital", "淨、數、暗黑", "clean, digital, noir", "暗調電影感的幾乎無顆粒", "in noir lighting, almost no grain", "noir, clean digital grain"],
    ["clean_soft", "柔光極淨", "soft-light clean digital", "淨、數、柔光", "clean, digital, soft", "柔光下的幾乎無顆粒", "under soft light, almost no grain", "soft-lit, clean digital grain"],
    ["clean_epic", "史詩極淨", "epic clean digital", "淨、數、史詩", "clean, digital, epic", "史詩尺度的幾乎無顆粒", "at epic scale, almost no grain", "epic, clean digital grain"],
    ["16mm_court", "宮廷16 毫米", "court 16mm grain", "16、粗、宮廷", "16, coarse, courtly", "宮廷氣場下的粗 16 顆粒", "in a courtly register, coarse 16mm grain", "courtly, 16mm grain"],
    ["16mm_street", "街頭16 毫米", "street 16mm grain", "16、粗、街頭", "16, coarse, street", "街頭質感的粗 16 顆粒", "with street grit, coarse 16mm grain", "street-cast, 16mm grain"],
    ["16mm_noir", "暗黑16 毫米", "noir 16mm grain", "16、粗、暗黑", "16, coarse, noir", "暗調電影感的粗 16 顆粒", "in noir lighting, coarse 16mm grain", "noir, 16mm grain"],
    ["16mm_soft", "柔光16 毫米", "soft-light 16mm grain", "16、粗、柔光", "16, coarse, soft", "柔光下的粗 16 顆粒", "under soft light, coarse 16mm grain", "soft-lit, 16mm grain"],
    ["16mm_epic", "史詩16 毫米", "epic 16mm grain", "16、粗、史詩", "16, coarse, epic", "史詩尺度的粗 16 顆粒", "at epic scale, coarse 16mm grain", "epic, 16mm grain"],
    ["35mm_court", "宮廷35 細", "court 35mm fine", "35、細、宮廷", "35, fine, courtly", "宮廷氣場下的細 35 顆粒", "in a courtly register, fine 35mm grain", "courtly, 35mm grain"],
    ["35mm_street", "街頭35 細", "street 35mm fine", "35、細、街頭", "35, fine, street", "街頭質感的細 35 顆粒", "with street grit, fine 35mm grain", "street-cast, 35mm grain"],
    ["35mm_noir", "暗黑35 細", "noir 35mm fine", "35、細、暗黑", "35, fine, noir", "暗調電影感的細 35 顆粒", "in noir lighting, fine 35mm grain", "noir, 35mm grain"],
    ["35mm_soft", "柔光35 細", "soft-light 35mm fine", "35、細、柔光", "35, fine, soft", "柔光下的細 35 顆粒", "under soft light, fine 35mm grain", "soft-lit, 35mm grain"],
    ["35mm_epic", "史詩35 細", "epic 35mm fine", "35、細、史詩", "35, fine, epic", "史詩尺度的細 35 顆粒", "at epic scale, fine 35mm grain", "epic, 35mm grain"],
    ["phone_court", "宮廷手機噪", "court phone noise", "手機、噪、宮廷", "phone, noise, courtly", "宮廷氣場下的數碼噪點", "in a courtly register, digital phone noise", "courtly, phone-noise grain"],
    ["phone_street", "街頭手機噪", "street phone noise", "手機、噪、街頭", "phone, noise, street", "街頭質感的數碼噪點", "with street grit, digital phone noise", "street-cast, phone-noise grain"],
    ["phone_noir", "暗黑手機噪", "noir phone noise", "手機、噪、暗黑", "phone, noise, noir", "暗調電影感的數碼噪點", "in noir lighting, digital phone noise", "noir, phone-noise grain"],
    ["phone_soft", "柔光手機噪", "soft-light phone noise", "手機、噪、柔光", "phone, noise, soft", "柔光下的數碼噪點", "under soft light, digital phone noise", "soft-lit, phone-noise grain"],
    ["phone_epic", "史詩手機噪", "epic phone noise", "手機、噪、史詩", "phone, noise, epic", "史詩尺度的數碼噪點", "at epic scale, digital phone noise", "epic, phone-noise grain"],
    ["halation_court", "宮廷鹵化紅邊", "court halation", "紅邊、膠、宮廷", "halo, film, courtly", "宮廷氣場下的高光紅暈", "in a courtly register, highlight red halo", "courtly, halation grain"],
    ["halation_street", "街頭鹵化紅邊", "street halation", "紅邊、膠、街頭", "halo, film, street", "街頭質感的高光紅暈", "with street grit, highlight red halo", "street-cast, halation grain"],
    ["halation_noir", "暗黑鹵化紅邊", "noir halation", "紅邊、膠、暗黑", "halo, film, noir", "暗調電影感的高光紅暈", "in noir lighting, highlight red halo", "noir, halation grain"],
    ["halation_soft", "柔光鹵化紅邊", "soft-light halation", "紅邊、膠、柔光", "halo, film, soft", "柔光下的高光紅暈", "under soft light, highlight red halo", "soft-lit, halation grain"],
    ["halation_epic", "史詩鹵化紅邊", "epic halation", "紅邊、膠、史詩", "halo, film, epic", "史詩尺度的高光紅暈", "at epic scale, highlight red halo", "epic, halation grain"],
    ["gate_weave_court", "宮廷輕抖片門", "court gate weave", "抖、膠、宮廷", "weave, film, courtly", "宮廷氣場下的輕微片門抖", "in a courtly register, slight gate weave", "courtly, gate-weave grain"],
    ["gate_weave_street", "街頭輕抖片門", "street gate weave", "抖、膠、街頭", "weave, film, street", "街頭質感的輕微片門抖", "with street grit, slight gate weave", "street-cast, gate-weave grain"],
    ["gate_weave_noir", "暗黑輕抖片門", "noir gate weave", "抖、膠、暗黑", "weave, film, noir", "暗調電影感的輕微片門抖", "in noir lighting, slight gate weave", "noir, gate-weave grain"],
    ["gate_weave_soft", "柔光輕抖片門", "soft-light gate weave", "抖、膠、柔光", "weave, film, soft", "柔光下的輕微片門抖", "under soft light, slight gate weave", "soft-lit, gate-weave grain"],
    ["gate_weave_epic", "史詩輕抖片門", "epic gate weave", "抖、膠、史詩", "weave, film, epic", "史詩尺度的輕微片門抖", "at epic scale, slight gate weave", "epic, gate-weave grain"],
    ["crushed_court", "宮廷壓黑噪", "court crushed-black noise", "壓、噪、宮廷", "crush, noise, courtly", "宮廷氣場下的黑位裡的噪", "in a courtly register, noise in crushed blacks", "courtly, crushed-black grain"],
    ["crushed_street", "街頭壓黑噪", "street crushed-black noise", "壓、噪、街頭", "crush, noise, street", "街頭質感的黑位裡的噪", "with street grit, noise in crushed blacks", "street-cast, crushed-black grain"],
    ["crushed_noir", "暗黑壓黑噪", "noir crushed-black noise", "壓、噪、暗黑", "crush, noise, noir", "暗調電影感的黑位裡的噪", "in noir lighting, noise in crushed blacks", "noir, crushed-black grain"],
    ["crushed_soft", "柔光壓黑噪", "soft-light crushed-black noise", "壓、噪、柔光", "crush, noise, soft", "柔光下的黑位裡的噪", "under soft light, noise in crushed blacks", "soft-lit, crushed-black grain"],
    ["crushed_epic", "史詩壓黑噪", "epic crushed-black noise", "壓、噪、史詩", "crush, noise, epic", "史詩尺度的黑位裡的噪", "at epic scale, noise in crushed blacks", "epic, crushed-black grain"],
    ["vhs_court", "宮廷錄影帶", "court VHS", "帶、紋、宮廷", "vhs, line, courtly", "宮廷氣場下的帶狀磁噪", "in a courtly register, tape noise lines", "courtly, VHS grain"],
    ["vhs_street", "街頭錄影帶", "street VHS", "帶、紋、街頭", "vhs, line, street", "街頭質感的帶狀磁噪", "with street grit, tape noise lines", "street-cast, VHS grain"],
    ["vhs_noir", "暗黑錄影帶", "noir VHS", "帶、紋、暗黑", "vhs, line, noir", "暗調電影感的帶狀磁噪", "in noir lighting, tape noise lines", "noir, VHS grain"],
    ["vhs_soft", "柔光錄影帶", "soft-light VHS", "帶、紋、柔光", "vhs, line, soft", "柔光下的帶狀磁噪", "under soft light, tape noise lines", "soft-lit, VHS grain"],
    ["vhs_epic", "史詩錄影帶", "epic VHS", "帶、紋、史詩", "vhs, line, epic", "史詩尺度的帶狀磁噪", "at epic scale, tape noise lines", "epic, VHS grain"],
    ["none_sharp_court", "宮廷銳無粒", "court sharp no grain", "銳、無、宮廷", "sharp, none, courtly", "宮廷氣場下的銳利無粒", "in a courtly register, sharp with no grain", "courtly, no-grain sharp"],
    ["none_sharp_street", "街頭銳無粒", "street sharp no grain", "銳、無、街頭", "sharp, none, street", "街頭質感的銳利無粒", "with street grit, sharp with no grain", "street-cast, no-grain sharp"],
    ["none_sharp_noir", "暗黑銳無粒", "noir sharp no grain", "銳、無、暗黑", "sharp, none, noir", "暗調電影感的銳利無粒", "in noir lighting, sharp with no grain", "noir, no-grain sharp"],
    ["none_sharp_soft", "柔光銳無粒", "soft-light sharp no grain", "銳、無、柔光", "sharp, none, soft", "柔光下的銳利無粒", "under soft light, sharp with no grain", "soft-lit, no-grain sharp"],
    ["none_sharp_epic", "史詩銳無粒", "epic sharp no grain", "銳、無、史詩", "sharp, none, epic", "史詩尺度的銳利無粒", "at epic scale, sharp with no grain", "epic, no-grain sharp"],
    ["heavy_push_court", "宮廷強推", "court heavy push", "推、粗、宮廷", "push, coarse, courtly", "宮廷氣場下的像強推的粗粒", "in a courtly register, heavy-push coarse grain", "courtly, heavy-push grain"],
    ["heavy_push_street", "街頭強推", "street heavy push", "推、粗、街頭", "push, coarse, street", "街頭質感的像強推的粗粒", "with street grit, heavy-push coarse grain", "street-cast, heavy-push grain"],
    ["heavy_push_noir", "暗黑強推", "noir heavy push", "推、粗、暗黑", "push, coarse, noir", "暗調電影感的像強推的粗粒", "in noir lighting, heavy-push coarse grain", "noir, heavy-push grain"],
    ["heavy_push_soft", "柔光強推", "soft-light heavy push", "推、粗、柔光", "push, coarse, soft", "柔光下的像強推的粗粒", "under soft light, heavy-push coarse grain", "soft-lit, heavy-push grain"],
    ["heavy_push_epic", "史詩強推", "epic heavy push", "推、粗、史詩", "push, coarse, epic", "史詩尺度的像強推的粗粒", "at epic scale, heavy-push coarse grain", "epic, heavy-push grain"]
  ],
    contrast: [
    ["flat_court", "宮廷平", "court flat", "平、紀、宮廷", "flat, doc, courtly", "宮廷氣場下的反差很低", "in a courtly register, very low contrast", "courtly, flat contrast"],
    ["flat_street", "街頭平", "street flat", "平、紀、街頭", "flat, doc, street", "街頭質感的反差很低", "with street grit, very low contrast", "street-cast, flat contrast"],
    ["flat_noir", "暗黑平", "noir flat", "平、紀、暗黑", "flat, doc, noir", "暗調電影感的反差很低", "in noir lighting, very low contrast", "noir, flat contrast"],
    ["flat_soft", "柔光平", "soft-light flat", "平、紀、柔光", "flat, doc, soft", "柔光下的反差很低", "under soft light, very low contrast", "soft-lit, flat contrast"],
    ["flat_epic", "史詩平", "epic flat", "平、紀、史詩", "flat, doc, epic", "史詩尺度的反差很低", "at epic scale, very low contrast", "epic, flat contrast"],
    ["medium_court", "宮廷中", "court medium", "中、常、宮廷", "mid, normal, courtly", "宮廷氣場下的中等反差", "in a courtly register, medium contrast", "courtly, medium contrast"],
    ["medium_street", "街頭中", "street medium", "中、常、街頭", "mid, normal, street", "街頭質感的中等反差", "with street grit, medium contrast", "street-cast, medium contrast"],
    ["medium_noir", "暗黑中", "noir medium", "中、常、暗黑", "mid, normal, noir", "暗調電影感的中等反差", "in noir lighting, medium contrast", "noir, medium contrast"],
    ["medium_soft", "柔光中", "soft-light medium", "中、常、柔光", "mid, normal, soft", "柔光下的中等反差", "under soft light, medium contrast", "soft-lit, medium contrast"],
    ["medium_epic", "史詩中", "epic medium", "中、常、史詩", "mid, normal, epic", "史詩尺度的中等反差", "at epic scale, medium contrast", "epic, medium contrast"],
    ["hard_court", "宮廷硬", "court hard", "硬、塊、宮廷", "hard, block, courtly", "宮廷氣場下的硬塊反差", "in a courtly register, blocky hard contrast", "courtly, hard contrast"],
    ["hard_street", "街頭硬", "street hard", "硬、塊、街頭", "hard, block, street", "街頭質感的硬塊反差", "with street grit, blocky hard contrast", "street-cast, hard contrast"],
    ["hard_noir", "暗黑硬", "noir hard", "硬、塊、暗黑", "hard, block, noir", "暗調電影感的硬塊反差", "in noir lighting, blocky hard contrast", "noir, hard contrast"],
    ["hard_soft", "柔光硬", "soft-light hard", "硬、塊、柔光", "hard, block, soft", "柔光下的硬塊反差", "under soft light, blocky hard contrast", "soft-lit, hard contrast"],
    ["hard_epic", "史詩硬", "epic hard", "硬、塊、史詩", "hard, block, epic", "史詩尺度的硬塊反差", "at epic scale, blocky hard contrast", "epic, hard contrast"],
    ["crushed_black_court", "宮廷死黑", "court crushed blacks", "死黑、密、宮廷", "crush, sealed, courtly", "宮廷氣場下的黑位切死", "in a courtly register, blacks crushed shut", "courtly, crushed-black contrast"],
    ["crushed_black_street", "街頭死黑", "street crushed blacks", "死黑、密、街頭", "crush, sealed, street", "街頭質感的黑位切死", "with street grit, blacks crushed shut", "street-cast, crushed-black contrast"],
    ["crushed_black_noir", "暗黑死黑", "noir crushed blacks", "死黑、密、暗黑", "crush, sealed, noir", "暗調電影感的黑位切死", "in noir lighting, blacks crushed shut", "noir, crushed-black contrast"],
    ["crushed_black_soft", "柔光死黑", "soft-light crushed blacks", "死黑、密、柔光", "crush, sealed, soft", "柔光下的黑位切死", "under soft light, blacks crushed shut", "soft-lit, crushed-black contrast"],
    ["crushed_black_epic", "史詩死黑", "epic crushed blacks", "死黑、密、史詩", "crush, sealed, epic", "史詩尺度的黑位切死", "at epic scale, blacks crushed shut", "epic, crushed-black contrast"],
    ["lifted_court", "宮廷灰霧抬黑", "court lifted blacks", "抬、霧、宮廷", "lift, fog, courtly", "宮廷氣場下的黑位發灰", "in a courtly register, blacks lifted to gray", "courtly, lifted-black contrast"],
    ["lifted_street", "街頭灰霧抬黑", "street lifted blacks", "抬、霧、街頭", "lift, fog, street", "街頭質感的黑位發灰", "with street grit, blacks lifted to gray", "street-cast, lifted-black contrast"],
    ["lifted_noir", "暗黑灰霧抬黑", "noir lifted blacks", "抬、霧、暗黑", "lift, fog, noir", "暗調電影感的黑位發灰", "in noir lighting, blacks lifted to gray", "noir, lifted-black contrast"],
    ["lifted_soft", "柔光灰霧抬黑", "soft-light lifted blacks", "抬、霧、柔光", "lift, fog, soft", "柔光下的黑位發灰", "under soft light, blacks lifted to gray", "soft-lit, lifted-black contrast"],
    ["lifted_epic", "史詩灰霧抬黑", "epic lifted blacks", "抬、霧、史詩", "lift, fog, epic", "史詩尺度的黑位發灰", "at epic scale, blacks lifted to gray", "epic, lifted-black contrast"],
    ["bloom_court", "宮廷高光溢", "court blooming highlights", "溢、夢、宮廷", "bloom, dream, courtly", "宮廷氣場下的高光開花", "in a courtly register, highlights bloom", "courtly, bloom contrast"],
    ["bloom_street", "街頭高光溢", "street blooming highlights", "溢、夢、街頭", "bloom, dream, street", "街頭質感的高光開花", "with street grit, highlights bloom", "street-cast, bloom contrast"],
    ["bloom_noir", "暗黑高光溢", "noir blooming highlights", "溢、夢、暗黑", "bloom, dream, noir", "暗調電影感的高光開花", "in noir lighting, highlights bloom", "noir, bloom contrast"],
    ["bloom_soft", "柔光高光溢", "soft-light blooming highlights", "溢、夢、柔光", "bloom, dream, soft", "柔光下的高光開花", "under soft light, highlights bloom", "soft-lit, bloom contrast"],
    ["bloom_epic", "史詩高光溢", "epic blooming highlights", "溢、夢、史詩", "bloom, dream, epic", "史詩尺度的高光開花", "at epic scale, highlights bloom", "epic, bloom contrast"],
    ["hdr_harsh_court", "宮廷假 HDR", "court harsh HDR", "HDR、假、宮廷", "hdr, fake, courtly", "宮廷氣場下的過清晰假 HDR", "in a courtly register, over-clear harsh HDR", "courtly, harsh HDR contrast"],
    ["hdr_harsh_street", "街頭假 HDR", "street harsh HDR", "HDR、假、街頭", "hdr, fake, street", "街頭質感的過清晰假 HDR", "with street grit, over-clear harsh HDR", "street-cast, harsh HDR contrast"],
    ["hdr_harsh_noir", "暗黑假 HDR", "noir harsh HDR", "HDR、假、暗黑", "hdr, fake, noir", "暗調電影感的過清晰假 HDR", "in noir lighting, over-clear harsh HDR", "noir, harsh HDR contrast"],
    ["hdr_harsh_soft", "柔光假 HDR", "soft-light harsh HDR", "HDR、假、柔光", "hdr, fake, soft", "柔光下的過清晰假 HDR", "under soft light, over-clear harsh HDR", "soft-lit, harsh HDR contrast"],
    ["hdr_harsh_epic", "史詩假 HDR", "epic harsh HDR", "HDR、假、史詩", "hdr, fake, epic", "史詩尺度的過清晰假 HDR", "at epic scale, over-clear harsh HDR", "epic, harsh HDR contrast"],
    ["silhouette_court", "宮廷剪影", "court silhouette contrast", "影、邊、宮廷", "silo, edge, courtly", "宮廷氣場下的常剪影", "in a courtly register, frequent silhouettes", "courtly, silhouette contrast"],
    ["silhouette_street", "街頭剪影", "street silhouette contrast", "影、邊、街頭", "silo, edge, street", "街頭質感的常剪影", "with street grit, frequent silhouettes", "street-cast, silhouette contrast"],
    ["silhouette_noir", "暗黑剪影", "noir silhouette contrast", "影、邊、暗黑", "silo, edge, noir", "暗調電影感的常剪影", "in noir lighting, frequent silhouettes", "noir, silhouette contrast"],
    ["silhouette_soft", "柔光剪影", "soft-light silhouette contrast", "影、邊、柔光", "silo, edge, soft", "柔光下的常剪影", "under soft light, frequent silhouettes", "soft-lit, silhouette contrast"],
    ["silhouette_epic", "史詩剪影", "epic silhouette contrast", "影、邊、史詩", "silo, edge, epic", "史詩尺度的常剪影", "at epic scale, frequent silhouettes", "epic, silhouette contrast"],
    ["face_protect_court", "宮廷護臉柔", "court face-protected", "臉、護、宮廷", "face, protect, courtly", "宮廷氣場下的臉不過曝過黑", "in a courtly register, faces protected", "courtly, face-protected contrast"],
    ["face_protect_street", "街頭護臉柔", "street face-protected", "臉、護、街頭", "face, protect, street", "街頭質感的臉不過曝過黑", "with street grit, faces protected", "street-cast, face-protected contrast"],
    ["face_protect_noir", "暗黑護臉柔", "noir face-protected", "臉、護、暗黑", "face, protect, noir", "暗調電影感的臉不過曝過黑", "in noir lighting, faces protected", "noir, face-protected contrast"],
    ["face_protect_soft", "柔光護臉柔", "soft-light face-protected", "臉、護、柔光", "face, protect, soft", "柔光下的臉不過曝過黑", "under soft light, faces protected", "soft-lit, face-protected contrast"],
    ["face_protect_epic", "史詩護臉柔", "epic face-protected", "臉、護、史詩", "face, protect, epic", "史詩尺度的臉不過曝過黑", "at epic scale, faces protected", "epic, face-protected contrast"],
    ["ink_court", "宮廷墨塊", "court ink-block", "墨、圖、宮廷", "ink, graphic, courtly", "宮廷氣場下的像墨塊對比", "in a courtly register, graphic ink blocks", "courtly, ink-block contrast"],
    ["ink_street", "街頭墨塊", "street ink-block", "墨、圖、街頭", "ink, graphic, street", "街頭質感的像墨塊對比", "with street grit, graphic ink blocks", "street-cast, ink-block contrast"],
    ["ink_noir", "暗黑墨塊", "noir ink-block", "墨、圖、暗黑", "ink, graphic, noir", "暗調電影感的像墨塊對比", "in noir lighting, graphic ink blocks", "noir, ink-block contrast"],
    ["ink_soft", "柔光墨塊", "soft-light ink-block", "墨、圖、柔光", "ink, graphic, soft", "柔光下的像墨塊對比", "under soft light, graphic ink blocks", "soft-lit, ink-block contrast"],
    ["ink_epic", "史詩墨塊", "epic ink-block", "墨、圖、史詩", "ink, graphic, epic", "史詩尺度的像墨塊對比", "at epic scale, graphic ink blocks", "epic, ink-block contrast"]
  ],
    eraGrade: [
    ["now_clean_court", "宮廷當下淨", "court present clean", "當、淨、宮廷", "now, clean, courtly", "宮廷氣場下的當下廣告淨調", "in a courtly register, present commercial clean", "courtly, present-clean grade"],
    ["now_clean_street", "街頭當下淨", "street present clean", "當、淨、街頭", "now, clean, street", "街頭質感的當下廣告淨調", "with street grit, present commercial clean", "street-cast, present-clean grade"],
    ["now_clean_noir", "暗黑當下淨", "noir present clean", "當、淨、暗黑", "now, clean, noir", "暗調電影感的當下廣告淨調", "in noir lighting, present commercial clean", "noir, present-clean grade"],
    ["now_clean_soft", "柔光當下淨", "soft-light present clean", "當、淨、柔光", "now, clean, soft", "柔光下的當下廣告淨調", "under soft light, present commercial clean", "soft-lit, present-clean grade"],
    ["now_clean_epic", "史詩當下淨", "epic present clean", "當、淨、史詩", "now, clean, epic", "史詩尺度的當下廣告淨調", "at epic scale, present commercial clean", "epic, present-clean grade"],
    ["70s_court", "宮廷七十暖", "court 1970s warm", "七十、暖、宮廷", "70s, warm, courtly", "宮廷氣場下的七十年代暖調", "in a courtly register, 1970s warm grade", "courtly, 1970s grade"],
    ["70s_street", "街頭七十暖", "street 1970s warm", "七十、暖、街頭", "70s, warm, street", "街頭質感的七十年代暖調", "with street grit, 1970s warm grade", "street-cast, 1970s grade"],
    ["70s_noir", "暗黑七十暖", "noir 1970s warm", "七十、暖、暗黑", "70s, warm, noir", "暗調電影感的七十年代暖調", "in noir lighting, 1970s warm grade", "noir, 1970s grade"],
    ["70s_soft", "柔光七十暖", "soft-light 1970s warm", "七十、暖、柔光", "70s, warm, soft", "柔光下的七十年代暖調", "under soft light, 1970s warm grade", "soft-lit, 1970s grade"],
    ["70s_epic", "史詩七十暖", "epic 1970s warm", "七十、暖、史詩", "70s, warm, epic", "史詩尺度的七十年代暖調", "at epic scale, 1970s warm grade", "epic, 1970s grade"],
    ["80s_vhs_court", "宮廷八十帶", "court 1980s tape", "八十、帶、宮廷", "80s, tape, courtly", "宮廷氣場下的八十錄影調", "in a courtly register, 1980s tape grade", "courtly, 1980s tape grade"],
    ["80s_vhs_street", "街頭八十帶", "street 1980s tape", "八十、帶、街頭", "80s, tape, street", "街頭質感的八十錄影調", "with street grit, 1980s tape grade", "street-cast, 1980s tape grade"],
    ["80s_vhs_noir", "暗黑八十帶", "noir 1980s tape", "八十、帶、暗黑", "80s, tape, noir", "暗調電影感的八十錄影調", "in noir lighting, 1980s tape grade", "noir, 1980s tape grade"],
    ["80s_vhs_soft", "柔光八十帶", "soft-light 1980s tape", "八十、帶、柔光", "80s, tape, soft", "柔光下的八十錄影調", "under soft light, 1980s tape grade", "soft-lit, 1980s tape grade"],
    ["80s_vhs_epic", "史詩八十帶", "epic 1980s tape", "八十、帶、史詩", "80s, tape, epic", "史詩尺度的八十錄影調", "at epic scale, 1980s tape grade", "epic, 1980s tape grade"],
    ["90s_hk_court", "宮廷九十港", "court 1990s HK", "九十、港、宮廷", "90s, hk, courtly", "宮廷氣場下的九十港片調", "in a courtly register, 1990s Hong Kong grade", "courtly, 1990s HK grade"],
    ["90s_hk_street", "街頭九十港", "street 1990s HK", "九十、港、街頭", "90s, hk, street", "街頭質感的九十港片調", "with street grit, 1990s Hong Kong grade", "street-cast, 1990s HK grade"],
    ["90s_hk_noir", "暗黑九十港", "noir 1990s HK", "九十、港、暗黑", "90s, hk, noir", "暗調電影感的九十港片調", "in noir lighting, 1990s Hong Kong grade", "noir, 1990s HK grade"],
    ["90s_hk_soft", "柔光九十港", "soft-light 1990s HK", "九十、港、柔光", "90s, hk, soft", "柔光下的九十港片調", "under soft light, 1990s Hong Kong grade", "soft-lit, 1990s HK grade"],
    ["90s_hk_epic", "史詩九十港", "epic 1990s HK", "九十、港、史詩", "90s, hk, epic", "史詩尺度的九十港片調", "at epic scale, 1990s Hong Kong grade", "epic, 1990s HK grade"],
    ["2000s_tv_court", "宮廷千禧劇", "court 2000s TV", "千禧、劇、宮廷", "2000s, tv, courtly", "宮廷氣場下的千禧電視劇調", "in a courtly register, 2000s TV grade", "courtly, 2000s TV grade"],
    ["2000s_tv_street", "街頭千禧劇", "street 2000s TV", "千禧、劇、街頭", "2000s, tv, street", "街頭質感的千禧電視劇調", "with street grit, 2000s TV grade", "street-cast, 2000s TV grade"],
    ["2000s_tv_noir", "暗黑千禧劇", "noir 2000s TV", "千禧、劇、暗黑", "2000s, tv, noir", "暗調電影感的千禧電視劇調", "in noir lighting, 2000s TV grade", "noir, 2000s TV grade"],
    ["2000s_tv_soft", "柔光千禧劇", "soft-light 2000s TV", "千禧、劇、柔光", "2000s, tv, soft", "柔光下的千禧電視劇調", "under soft light, 2000s TV grade", "soft-lit, 2000s TV grade"],
    ["2000s_tv_epic", "史詩千禧劇", "epic 2000s TV", "千禧、劇、史詩", "2000s, tv, epic", "史詩尺度的千禧電視劇調", "at epic scale, 2000s TV grade", "epic, 2000s TV grade"],
    ["period_desat_court", "宮廷古裝去飽", "court period desat", "古、淡、宮廷", "period, pale, courtly", "宮廷氣場下的古裝低飽", "in a courtly register, period low saturation", "courtly, period-desat grade"],
    ["period_desat_street", "街頭古裝去飽", "street period desat", "古、淡、街頭", "period, pale, street", "街頭質感的古裝低飽", "with street grit, period low saturation", "street-cast, period-desat grade"],
    ["period_desat_noir", "暗黑古裝去飽", "noir period desat", "古、淡、暗黑", "period, pale, noir", "暗調電影感的古裝低飽", "in noir lighting, period low saturation", "noir, period-desat grade"],
    ["period_desat_soft", "柔光古裝去飽", "soft-light period desat", "古、淡、柔光", "period, pale, soft", "柔光下的古裝低飽", "under soft light, period low saturation", "soft-lit, period-desat grade"],
    ["period_desat_epic", "史詩古裝去飽", "epic period desat", "古、淡、史詩", "period, pale, epic", "史詩尺度的古裝低飽", "at epic scale, period low saturation", "epic, period-desat grade"],
    ["future_cool_court", "宮廷未來冷", "court future cool", "未、冷、宮廷", "future, cool, courtly", "宮廷氣場下的未來冷青", "in a courtly register, future cool cyan", "courtly, future-cool grade"],
    ["future_cool_street", "街頭未來冷", "street future cool", "未、冷、街頭", "future, cool, street", "街頭質感的未來冷青", "with street grit, future cool cyan", "street-cast, future-cool grade"],
    ["future_cool_noir", "暗黑未來冷", "noir future cool", "未、冷、暗黑", "future, cool, noir", "暗調電影感的未來冷青", "in noir lighting, future cool cyan", "noir, future-cool grade"],
    ["future_cool_soft", "柔光未來冷", "soft-light future cool", "未、冷、柔光", "future, cool, soft", "柔光下的未來冷青", "under soft light, future cool cyan", "soft-lit, future-cool grade"],
    ["future_cool_epic", "史詩未來冷", "epic future cool", "未、冷、史詩", "future, cool, epic", "史詩尺度的未來冷青", "at epic scale, future cool cyan", "epic, future-cool grade"],
    ["newsreel_court", "宮廷舊新聞", "court newsreel", "聞、高對、宮廷", "news, contrast, courtly", "宮廷氣場下的舊新聞高反", "in a courtly register, old newsreel contrast", "courtly, newsreel grade"],
    ["newsreel_street", "街頭舊新聞", "street newsreel", "聞、高對、街頭", "news, contrast, street", "街頭質感的舊新聞高反", "with street grit, old newsreel contrast", "street-cast, newsreel grade"],
    ["newsreel_noir", "暗黑舊新聞", "noir newsreel", "聞、高對、暗黑", "news, contrast, noir", "暗調電影感的舊新聞高反", "in noir lighting, old newsreel contrast", "noir, newsreel grade"],
    ["newsreel_soft", "柔光舊新聞", "soft-light newsreel", "聞、高對、柔光", "news, contrast, soft", "柔光下的舊新聞高反", "under soft light, old newsreel contrast", "soft-lit, newsreel grade"],
    ["newsreel_epic", "史詩舊新聞", "epic newsreel", "聞、高對、史詩", "news, contrast, epic", "史詩尺度的舊新聞高反", "at epic scale, old newsreel contrast", "epic, newsreel grade"],
    ["wedding_court", "宮廷婚禮甜", "court wedding sweet", "婚、甜、宮廷", "wedding, sweet, courtly", "宮廷氣場下的偏甜婚禮調", "in a courtly register, sweet wedding grade", "courtly, wedding-sweet grade"],
    ["wedding_street", "街頭婚禮甜", "street wedding sweet", "婚、甜、街頭", "wedding, sweet, street", "街頭質感的偏甜婚禮調", "with street grit, sweet wedding grade", "street-cast, wedding-sweet grade"],
    ["wedding_noir", "暗黑婚禮甜", "noir wedding sweet", "婚、甜、暗黑", "wedding, sweet, noir", "暗調電影感的偏甜婚禮調", "in noir lighting, sweet wedding grade", "noir, wedding-sweet grade"],
    ["wedding_soft", "柔光婚禮甜", "soft-light wedding sweet", "婚、甜、柔光", "wedding, sweet, soft", "柔光下的偏甜婚禮調", "under soft light, sweet wedding grade", "soft-lit, wedding-sweet grade"],
    ["wedding_epic", "史詩婚禮甜", "epic wedding sweet", "婚、甜、史詩", "wedding, sweet, epic", "史詩尺度的偏甜婚禮調", "at epic scale, sweet wedding grade", "epic, wedding-sweet grade"],
    ["horror_green_court", "宮廷恐綠", "court horror green", "恐、綠、宮廷", "horror, green, courtly", "宮廷氣場下的病態綠調", "in a courtly register, sick green grade", "courtly, horror-green grade"],
    ["horror_green_street", "街頭恐綠", "street horror green", "恐、綠、街頭", "horror, green, street", "街頭質感的病態綠調", "with street grit, sick green grade", "street-cast, horror-green grade"],
    ["horror_green_noir", "暗黑恐綠", "noir horror green", "恐、綠、暗黑", "horror, green, noir", "暗調電影感的病態綠調", "in noir lighting, sick green grade", "noir, horror-green grade"],
    ["horror_green_soft", "柔光恐綠", "soft-light horror green", "恐、綠、柔光", "horror, green, soft", "柔光下的病態綠調", "under soft light, sick green grade", "soft-lit, horror-green grade"],
    ["horror_green_epic", "史詩恐綠", "epic horror green", "恐、綠、史詩", "horror, green, epic", "史詩尺度的病態綠調", "at epic scale, sick green grade", "epic, horror-green grade"]
  ],
    atmosphere: [
    ["clear_court", "宮廷透", "court clear air", "透、乾、宮廷", "clear, dry, courtly", "宮廷氣場下的空氣很透", "in a courtly register, very clear air", "courtly, clear atmosphere"],
    ["clear_street", "街頭透", "street clear air", "透、乾、街頭", "clear, dry, street", "街頭質感的空氣很透", "with street grit, very clear air", "street-cast, clear atmosphere"],
    ["clear_noir", "暗黑透", "noir clear air", "透、乾、暗黑", "clear, dry, noir", "暗調電影感的空氣很透", "in noir lighting, very clear air", "noir, clear atmosphere"],
    ["clear_soft", "柔光透", "soft-light clear air", "透、乾、柔光", "clear, dry, soft", "柔光下的空氣很透", "under soft light, very clear air", "soft-lit, clear atmosphere"],
    ["clear_epic", "史詩透", "epic clear air", "透、乾、史詩", "clear, dry, epic", "史詩尺度的空氣很透", "at epic scale, very clear air", "epic, clear atmosphere"],
    ["haze_court", "宮廷薄霾", "court thin haze", "霾、遠、宮廷", "haze, far, courtly", "宮廷氣場下的遠處薄霾", "in a courtly register, thin distant haze", "courtly, thin-haze atmosphere"],
    ["haze_street", "街頭薄霾", "street thin haze", "霾、遠、街頭", "haze, far, street", "街頭質感的遠處薄霾", "with street grit, thin distant haze", "street-cast, thin-haze atmosphere"],
    ["haze_noir", "暗黑薄霾", "noir thin haze", "霾、遠、暗黑", "haze, far, noir", "暗調電影感的遠處薄霾", "in noir lighting, thin distant haze", "noir, thin-haze atmosphere"],
    ["haze_soft", "柔光薄霾", "soft-light thin haze", "霾、遠、柔光", "haze, far, soft", "柔光下的遠處薄霾", "under soft light, thin distant haze", "soft-lit, thin-haze atmosphere"],
    ["haze_epic", "史詩薄霾", "epic thin haze", "霾、遠、史詩", "haze, far, epic", "史詩尺度的遠處薄霾", "at epic scale, thin distant haze", "epic, thin-haze atmosphere"],
    ["fog_court", "宮廷霧", "court fog", "霧、吞、宮廷", "fog, swallow, courtly", "宮廷氣場下的霧吞中景", "in a courtly register, fog eats midground", "courtly, fog atmosphere"],
    ["fog_street", "街頭霧", "street fog", "霧、吞、街頭", "fog, swallow, street", "街頭質感的霧吞中景", "with street grit, fog eats midground", "street-cast, fog atmosphere"],
    ["fog_noir", "暗黑霧", "noir fog", "霧、吞、暗黑", "fog, swallow, noir", "暗調電影感的霧吞中景", "in noir lighting, fog eats midground", "noir, fog atmosphere"],
    ["fog_soft", "柔光霧", "soft-light fog", "霧、吞、柔光", "fog, swallow, soft", "柔光下的霧吞中景", "under soft light, fog eats midground", "soft-lit, fog atmosphere"],
    ["fog_epic", "史詩霧", "epic fog", "霧、吞、史詩", "fog, swallow, epic", "史詩尺度的霧吞中景", "at epic scale, fog eats midground", "epic, fog atmosphere"],
    ["rain_court", "宮廷雨絲", "court rain streaks", "雨、絲、宮廷", "rain, streak, courtly", "宮廷氣場下的可見雨絲", "in a courtly register, visible rain streaks", "courtly, rain atmosphere"],
    ["rain_street", "街頭雨絲", "street rain streaks", "雨、絲、街頭", "rain, streak, street", "街頭質感的可見雨絲", "with street grit, visible rain streaks", "street-cast, rain atmosphere"],
    ["rain_noir", "暗黑雨絲", "noir rain streaks", "雨、絲、暗黑", "rain, streak, noir", "暗調電影感的可見雨絲", "in noir lighting, visible rain streaks", "noir, rain atmosphere"],
    ["rain_soft", "柔光雨絲", "soft-light rain streaks", "雨、絲、柔光", "rain, streak, soft", "柔光下的可見雨絲", "under soft light, visible rain streaks", "soft-lit, rain atmosphere"],
    ["rain_epic", "史詩雨絲", "epic rain streaks", "雨、絲、史詩", "rain, streak, epic", "史詩尺度的可見雨絲", "at epic scale, visible rain streaks", "epic, rain atmosphere"],
    ["dust_court", "宮廷塵柱", "court dust shafts", "塵、束、宮廷", "dust, shaft, courtly", "宮廷氣場下的光裡塵柱", "in a courtly register, dust in light shafts", "courtly, dust atmosphere"],
    ["dust_street", "街頭塵柱", "street dust shafts", "塵、束、街頭", "dust, shaft, street", "街頭質感的光裡塵柱", "with street grit, dust in light shafts", "street-cast, dust atmosphere"],
    ["dust_noir", "暗黑塵柱", "noir dust shafts", "塵、束、暗黑", "dust, shaft, noir", "暗調電影感的光裡塵柱", "in noir lighting, dust in light shafts", "noir, dust atmosphere"],
    ["dust_soft", "柔光塵柱", "soft-light dust shafts", "塵、束、柔光", "dust, shaft, soft", "柔光下的光裡塵柱", "under soft light, dust in light shafts", "soft-lit, dust atmosphere"],
    ["dust_epic", "史詩塵柱", "epic dust shafts", "塵、束、史詩", "dust, shaft, epic", "史詩尺度的光裡塵柱", "at epic scale, dust in light shafts", "epic, dust atmosphere"],
    ["smoke_court", "宮廷煙", "court smoke", "煙、層、宮廷", "smoke, layer, courtly", "宮廷氣場下的分層煙", "in a courtly register, layered smoke", "courtly, smoke atmosphere"],
    ["smoke_street", "街頭煙", "street smoke", "煙、層、街頭", "smoke, layer, street", "街頭質感的分層煙", "with street grit, layered smoke", "street-cast, smoke atmosphere"],
    ["smoke_noir", "暗黑煙", "noir smoke", "煙、層、暗黑", "smoke, layer, noir", "暗調電影感的分層煙", "in noir lighting, layered smoke", "noir, smoke atmosphere"],
    ["smoke_soft", "柔光煙", "soft-light smoke", "煙、層、柔光", "smoke, layer, soft", "柔光下的分層煙", "under soft light, layered smoke", "soft-lit, smoke atmosphere"],
    ["smoke_epic", "史詩煙", "epic smoke", "煙、層、史詩", "smoke, layer, epic", "史詩尺度的分層煙", "at epic scale, layered smoke", "epic, smoke atmosphere"],
    ["snow_court", "宮廷雪", "court snow", "雪、靜、宮廷", "snow, still, courtly", "宮廷氣場下的落雪", "in a courtly register, falling snow", "courtly, snow atmosphere"],
    ["snow_street", "街頭雪", "street snow", "雪、靜、街頭", "snow, still, street", "街頭質感的落雪", "with street grit, falling snow", "street-cast, snow atmosphere"],
    ["snow_noir", "暗黑雪", "noir snow", "雪、靜、暗黑", "snow, still, noir", "暗調電影感的落雪", "in noir lighting, falling snow", "noir, snow atmosphere"],
    ["snow_soft", "柔光雪", "soft-light snow", "雪、靜、柔光", "snow, still, soft", "柔光下的落雪", "under soft light, falling snow", "soft-lit, snow atmosphere"],
    ["snow_epic", "史詩雪", "epic snow", "雪、靜、史詩", "snow, still, epic", "史詩尺度的落雪", "at epic scale, falling snow", "epic, snow atmosphere"],
    ["heat_court", "宮廷熱浪", "court heat shimmer", "熱、顫、宮廷", "heat, shimmer, courtly", "宮廷氣場下的遠處熱顫", "in a courtly register, distant heat shimmer", "courtly, heat-shimmer atmosphere"],
    ["heat_street", "街頭熱浪", "street heat shimmer", "熱、顫、街頭", "heat, shimmer, street", "街頭質感的遠處熱顫", "with street grit, distant heat shimmer", "street-cast, heat-shimmer atmosphere"],
    ["heat_noir", "暗黑熱浪", "noir heat shimmer", "熱、顫、暗黑", "heat, shimmer, noir", "暗調電影感的遠處熱顫", "in noir lighting, distant heat shimmer", "noir, heat-shimmer atmosphere"],
    ["heat_soft", "柔光熱浪", "soft-light heat shimmer", "熱、顫、柔光", "heat, shimmer, soft", "柔光下的遠處熱顫", "under soft light, distant heat shimmer", "soft-lit, heat-shimmer atmosphere"],
    ["heat_epic", "史詩熱浪", "epic heat shimmer", "熱、顫、史詩", "heat, shimmer, epic", "史詩尺度的遠處熱顫", "at epic scale, distant heat shimmer", "epic, heat-shimmer atmosphere"],
    ["night_wet_court", "宮廷濕夜", "court wet night", "濕、反、宮廷", "wet, reflect, courtly", "宮廷氣場下的地面全濕反光", "in a courtly register, wet reflective ground", "courtly, wet-night atmosphere"],
    ["night_wet_street", "街頭濕夜", "street wet night", "濕、反、街頭", "wet, reflect, street", "街頭質感的地面全濕反光", "with street grit, wet reflective ground", "street-cast, wet-night atmosphere"],
    ["night_wet_noir", "暗黑濕夜", "noir wet night", "濕、反、暗黑", "wet, reflect, noir", "暗調電影感的地面全濕反光", "in noir lighting, wet reflective ground", "noir, wet-night atmosphere"],
    ["night_wet_soft", "柔光濕夜", "soft-light wet night", "濕、反、柔光", "wet, reflect, soft", "柔光下的地面全濕反光", "under soft light, wet reflective ground", "soft-lit, wet-night atmosphere"],
    ["night_wet_epic", "史詩濕夜", "epic wet night", "濕、反、史詩", "wet, reflect, epic", "史詩尺度的地面全濕反光", "at epic scale, wet reflective ground", "epic, wet-night atmosphere"],
    ["pollen_court", "宮廷金色塵", "court golden motes", "金塵、幻、宮廷", "gold, mote, courtly", "宮廷氣場下的金色浮塵", "in a courtly register, golden floating motes", "courtly, golden-mote atmosphere"],
    ["pollen_street", "街頭金色塵", "street golden motes", "金塵、幻、街頭", "gold, mote, street", "街頭質感的金色浮塵", "with street grit, golden floating motes", "street-cast, golden-mote atmosphere"],
    ["pollen_noir", "暗黑金色塵", "noir golden motes", "金塵、幻、暗黑", "gold, mote, noir", "暗調電影感的金色浮塵", "in noir lighting, golden floating motes", "noir, golden-mote atmosphere"],
    ["pollen_soft", "柔光金色塵", "soft-light golden motes", "金塵、幻、柔光", "gold, mote, soft", "柔光下的金色浮塵", "under soft light, golden floating motes", "soft-lit, golden-mote atmosphere"],
    ["pollen_epic", "史詩金色塵", "epic golden motes", "金塵、幻、史詩", "gold, mote, epic", "史詩尺度的金色浮塵", "at epic scale, golden floating motes", "epic, golden-mote atmosphere"]
  ],
    lensFeel: [
    ["clinical_court", "宮廷臨床銳", "court clinical sharp", "銳、醫、宮廷", "sharp, clinical, courtly", "宮廷氣場下的臨床般銳", "in a courtly register, clinical sharpness", "courtly, clinical lens feel"],
    ["clinical_street", "街頭臨床銳", "street clinical sharp", "銳、醫、街頭", "sharp, clinical, street", "街頭質感的臨床般銳", "with street grit, clinical sharpness", "street-cast, clinical lens feel"],
    ["clinical_noir", "暗黑臨床銳", "noir clinical sharp", "銳、醫、暗黑", "sharp, clinical, noir", "暗調電影感的臨床般銳", "in noir lighting, clinical sharpness", "noir, clinical lens feel"],
    ["clinical_soft", "柔光臨床銳", "soft-light clinical sharp", "銳、醫、柔光", "sharp, clinical, soft", "柔光下的臨床般銳", "under soft light, clinical sharpness", "soft-lit, clinical lens feel"],
    ["clinical_epic", "史詩臨床銳", "epic clinical sharp", "銳、醫、史詩", "sharp, clinical, epic", "史詩尺度的臨床般銳", "at epic scale, clinical sharpness", "epic, clinical lens feel"],
    ["vintage_court", "宮廷舊鍍膜", "court vintage coating", "舊、暖邊、宮廷", "vintage, warm edge, courtly", "宮廷氣場下的舊鍍膜光暈", "in a courtly register, vintage coating glow", "courtly, vintage lens feel"],
    ["vintage_street", "街頭舊鍍膜", "street vintage coating", "舊、暖邊、街頭", "vintage, warm edge, street", "街頭質感的舊鍍膜光暈", "with street grit, vintage coating glow", "street-cast, vintage lens feel"],
    ["vintage_noir", "暗黑舊鍍膜", "noir vintage coating", "舊、暖邊、暗黑", "vintage, warm edge, noir", "暗調電影感的舊鍍膜光暈", "in noir lighting, vintage coating glow", "noir, vintage lens feel"],
    ["vintage_soft", "柔光舊鍍膜", "soft-light vintage coating", "舊、暖邊、柔光", "vintage, warm edge, soft", "柔光下的舊鍍膜光暈", "under soft light, vintage coating glow", "soft-lit, vintage lens feel"],
    ["vintage_epic", "史詩舊鍍膜", "epic vintage coating", "舊、暖邊、史詩", "vintage, warm edge, epic", "史詩尺度的舊鍍膜光暈", "at epic scale, vintage coating glow", "epic, vintage lens feel"],
    ["anamorphic_streak_court", "宮廷變形光條", "court anamorphic streak", "條、寬、宮廷", "streak, wide, courtly", "宮廷氣場下的水平光條", "in a courtly register, horizontal streaks", "courtly, anamorphic-streak feel"],
    ["anamorphic_streak_street", "街頭變形光條", "street anamorphic streak", "條、寬、街頭", "streak, wide, street", "街頭質感的水平光條", "with street grit, horizontal streaks", "street-cast, anamorphic-streak feel"],
    ["anamorphic_streak_noir", "暗黑變形光條", "noir anamorphic streak", "條、寬、暗黑", "streak, wide, noir", "暗調電影感的水平光條", "in noir lighting, horizontal streaks", "noir, anamorphic-streak feel"],
    ["anamorphic_streak_soft", "柔光變形光條", "soft-light anamorphic streak", "條、寬、柔光", "streak, wide, soft", "柔光下的水平光條", "under soft light, horizontal streaks", "soft-lit, anamorphic-streak feel"],
    ["anamorphic_streak_epic", "史詩變形光條", "epic anamorphic streak", "條、寬、史詩", "streak, wide, epic", "史詩尺度的水平光條", "at epic scale, horizontal streaks", "epic, anamorphic-streak feel"],
    ["vignette_court", "宮廷暗角", "court vignette", "角、收、宮廷", "vignette, close, courtly", "宮廷氣場下的明顯暗角", "in a courtly register, visible vignette", "courtly, vignette lens feel"],
    ["vignette_street", "街頭暗角", "street vignette", "角、收、街頭", "vignette, close, street", "街頭質感的明顯暗角", "with street grit, visible vignette", "street-cast, vignette lens feel"],
    ["vignette_noir", "暗黑暗角", "noir vignette", "角、收、暗黑", "vignette, close, noir", "暗調電影感的明顯暗角", "in noir lighting, visible vignette", "noir, vignette lens feel"],
    ["vignette_soft", "柔光暗角", "soft-light vignette", "角、收、柔光", "vignette, close, soft", "柔光下的明顯暗角", "under soft light, visible vignette", "soft-lit, vignette lens feel"],
    ["vignette_epic", "史詩暗角", "epic vignette", "角、收、史詩", "vignette, close, epic", "史詩尺度的明顯暗角", "at epic scale, visible vignette", "epic, vignette lens feel"],
    ["wide_distort_court", "宮廷廣角畸", "court wide distortion", "畸、近大、宮廷", "distort, near-big, courtly", "宮廷氣場下的近大遠小誇", "in a courtly register, exaggerated wide distortion", "courtly, wide-distort lens feel"],
    ["wide_distort_street", "街頭廣角畸", "street wide distortion", "畸、近大、街頭", "distort, near-big, street", "街頭質感的近大遠小誇", "with street grit, exaggerated wide distortion", "street-cast, wide-distort lens feel"],
    ["wide_distort_noir", "暗黑廣角畸", "noir wide distortion", "畸、近大、暗黑", "distort, near-big, noir", "暗調電影感的近大遠小誇", "in noir lighting, exaggerated wide distortion", "noir, wide-distort lens feel"],
    ["wide_distort_soft", "柔光廣角畸", "soft-light wide distortion", "畸、近大、柔光", "distort, near-big, soft", "柔光下的近大遠小誇", "under soft light, exaggerated wide distortion", "soft-lit, wide-distort lens feel"],
    ["wide_distort_epic", "史詩廣角畸", "epic wide distortion", "畸、近大、史詩", "distort, near-big, epic", "史詩尺度的近大遠小誇", "at epic scale, exaggerated wide distortion", "epic, wide-distort lens feel"],
    ["long_compress_court", "宮廷長焦壓", "court long compress", "壓、貼、宮廷", "compress, stack, courtly", "宮廷氣場下的層層被壓", "in a courtly register, planes stacked", "courtly, long-compress lens feel"],
    ["long_compress_street", "街頭長焦壓", "street long compress", "壓、貼、街頭", "compress, stack, street", "街頭質感的層層被壓", "with street grit, planes stacked", "street-cast, long-compress lens feel"],
    ["long_compress_noir", "暗黑長焦壓", "noir long compress", "壓、貼、暗黑", "compress, stack, noir", "暗調電影感的層層被壓", "in noir lighting, planes stacked", "noir, long-compress lens feel"],
    ["long_compress_soft", "柔光長焦壓", "soft-light long compress", "壓、貼、柔光", "compress, stack, soft", "柔光下的層層被壓", "under soft light, planes stacked", "soft-lit, long-compress lens feel"],
    ["long_compress_epic", "史詩長焦壓", "epic long compress", "壓、貼、史詩", "compress, stack, epic", "史詩尺度的層層被壓", "at epic scale, planes stacked", "epic, long-compress lens feel"],
    ["dream_smear_court", "宮廷夢 smear", "court dream smear", "夢、抹、宮廷", "dream, smear, courtly", "宮廷氣場下的邊緣被抹", "in a courtly register, edges smeared", "courtly, dream-smear lens feel"],
    ["dream_smear_street", "街頭夢 smear", "street dream smear", "夢、抹、街頭", "dream, smear, street", "街頭質感的邊緣被抹", "with street grit, edges smeared", "street-cast, dream-smear lens feel"],
    ["dream_smear_noir", "暗黑夢 smear", "noir dream smear", "夢、抹、暗黑", "dream, smear, noir", "暗調電影感的邊緣被抹", "in noir lighting, edges smeared", "noir, dream-smear lens feel"],
    ["dream_smear_soft", "柔光夢 smear", "soft-light dream smear", "夢、抹、柔光", "dream, smear, soft", "柔光下的邊緣被抹", "under soft light, edges smeared", "soft-lit, dream-smear lens feel"],
    ["dream_smear_epic", "史詩夢 smear", "epic dream smear", "夢、抹、史詩", "dream, smear, epic", "史詩尺度的邊緣被抹", "at epic scale, edges smeared", "epic, dream-smear lens feel"],
    ["security_court", "宮廷監控", "court security cam", "監、頂、宮廷", "security, top, courtly", "宮廷氣場下的監控廣角頂", "in a courtly register, top security-cam wide", "courtly, security-cam lens feel"],
    ["security_street", "街頭監控", "street security cam", "監、頂、街頭", "security, top, street", "街頭質感的監控廣角頂", "with street grit, top security-cam wide", "street-cast, security-cam lens feel"],
    ["security_noir", "暗黑監控", "noir security cam", "監、頂、暗黑", "security, top, noir", "暗調電影感的監控廣角頂", "in noir lighting, top security-cam wide", "noir, security-cam lens feel"],
    ["security_soft", "柔光監控", "soft-light security cam", "監、頂、柔光", "security, top, soft", "柔光下的監控廣角頂", "under soft light, top security-cam wide", "soft-lit, security-cam lens feel"],
    ["security_epic", "史詩監控", "epic security cam", "監、頂、史詩", "security, top, epic", "史詩尺度的監控廣角頂", "at epic scale, top security-cam wide", "epic, security-cam lens feel"],
    ["finder_court", "宮廷取景器黑", "court viewfinder black", "取、黑框、宮廷", "finder, black, courtly", "宮廷氣場下的像從取景器看", "in a courtly register, looks through a finder", "courtly, viewfinder lens feel"],
    ["finder_street", "街頭取景器黑", "street viewfinder black", "取、黑框、街頭", "finder, black, street", "街頭質感的像從取景器看", "with street grit, looks through a finder", "street-cast, viewfinder lens feel"],
    ["finder_noir", "暗黑取景器黑", "noir viewfinder black", "取、黑框、暗黑", "finder, black, noir", "暗調電影感的像從取景器看", "in noir lighting, looks through a finder", "noir, viewfinder lens feel"],
    ["finder_soft", "柔光取景器黑", "soft-light viewfinder black", "取、黑框、柔光", "finder, black, soft", "柔光下的像從取景器看", "under soft light, looks through a finder", "soft-lit, viewfinder lens feel"],
    ["finder_epic", "史詩取景器黑", "epic viewfinder black", "取、黑框、史詩", "finder, black, epic", "史詩尺度的像從取景器看", "at epic scale, looks through a finder", "epic, viewfinder lens feel"],
    ["prism_court", "宮廷棱鏡漏", "court prism leak", "棱、彩、宮廷", "prism, leak, courtly", "宮廷氣場下的邊緣彩漏", "in a courtly register, edge color leaks", "courtly, prism-leak lens feel"],
    ["prism_street", "街頭棱鏡漏", "street prism leak", "棱、彩、街頭", "prism, leak, street", "街頭質感的邊緣彩漏", "with street grit, edge color leaks", "street-cast, prism-leak lens feel"],
    ["prism_noir", "暗黑棱鏡漏", "noir prism leak", "棱、彩、暗黑", "prism, leak, noir", "暗調電影感的邊緣彩漏", "in noir lighting, edge color leaks", "noir, prism-leak lens feel"],
    ["prism_soft", "柔光棱鏡漏", "soft-light prism leak", "棱、彩、柔光", "prism, leak, soft", "柔光下的邊緣彩漏", "under soft light, edge color leaks", "soft-lit, prism-leak lens feel"],
    ["prism_epic", "史詩棱鏡漏", "epic prism leak", "棱、彩、史詩", "prism, leak, epic", "史詩尺度的邊緣彩漏", "at epic scale, edge color leaks", "epic, prism-leak lens feel"]
  ]
  }
})
