/**
 * voice field kit catalog (50+ templates per part).
 */
import { defineFieldKit } from '../fieldKit'

export const VOICE_KIT = defineFieldKit({
  key: "voiceKit",
  parts: ["pitch","texture","pace","register","breath","accent"] as const,
  partLabels: {
    pitch: { zhHK: "音高", zhCN: "音高", en: "Pitch" },
    texture: { zhHK: "質地", zhCN: "质地", en: "Texture" },
    pace: { zhHK: "節奏", zhCN: "节奏", en: "Pace" },
    register: { zhHK: "聲線位", zhCN: "声线位", en: "Register" },
    breath: { zhHK: "氣息", zhCN: "气息", en: "Breath" },
    accent: { zhHK: "口音", zhCN: "口音", en: "Accent" }
  },

  rows: {
    pitch: [
    ["low_court", "宮廷偏低", "court low", "低、沉、宮廷", "low, deep, courtly", "宮廷氣場下的整體偏低", "in a courtly register, overall low pitch", "courtly, low speaking pitch"],
    ["low_street", "街頭偏低", "street low", "低、沉、街頭", "low, deep, street", "街頭質感的整體偏低", "with street grit, overall low pitch", "street-cast, low speaking pitch"],
    ["low_noir", "暗黑偏低", "noir low", "低、沉、暗黑", "low, deep, noir", "暗調電影感的整體偏低", "in noir lighting, overall low pitch", "noir, low speaking pitch"],
    ["low_soft", "柔光偏低", "soft-light low", "低、沉、柔光", "low, deep, soft", "柔光下的整體偏低", "under soft light, overall low pitch", "soft-lit, low speaking pitch"],
    ["low_epic", "史詩偏低", "epic low", "低、沉、史詩", "low, deep, epic", "史詩尺度的整體偏低", "at epic scale, overall low pitch", "epic, low speaking pitch"],
    ["mid_court", "宮廷中音", "court mid", "中、穩、宮廷", "mid, steady, courtly", "宮廷氣場下的中音區", "in a courtly register, mid speaking range", "courtly, mid speaking pitch"],
    ["mid_street", "街頭中音", "street mid", "中、穩、街頭", "mid, steady, street", "街頭質感的中音區", "with street grit, mid speaking range", "street-cast, mid speaking pitch"],
    ["mid_noir", "暗黑中音", "noir mid", "中、穩、暗黑", "mid, steady, noir", "暗調電影感的中音區", "in noir lighting, mid speaking range", "noir, mid speaking pitch"],
    ["mid_soft", "柔光中音", "soft-light mid", "中、穩、柔光", "mid, steady, soft", "柔光下的中音區", "under soft light, mid speaking range", "soft-lit, mid speaking pitch"],
    ["mid_epic", "史詩中音", "epic mid", "中、穩、史詩", "mid, steady, epic", "史詩尺度的中音區", "at epic scale, mid speaking range", "epic, mid speaking pitch"],
    ["high_soft_court", "宮廷偏高但軟", "court high soft", "高、軟、宮廷", "high, soft, courtly", "宮廷氣場下的偏高不尖", "in a courtly register, high but not shrill", "courtly, high soft pitch"],
    ["high_soft_street", "街頭偏高但軟", "street high soft", "高、軟、街頭", "high, soft, street", "街頭質感的偏高不尖", "with street grit, high but not shrill", "street-cast, high soft pitch"],
    ["high_soft_noir", "暗黑偏高但軟", "noir high soft", "高、軟、暗黑", "high, soft, noir", "暗調電影感的偏高不尖", "in noir lighting, high but not shrill", "noir, high soft pitch"],
    ["high_soft_soft", "柔光偏高但軟", "soft-light high soft", "高、軟、柔光", "high, soft, soft", "柔光下的偏高不尖", "under soft light, high but not shrill", "soft-lit, high soft pitch"],
    ["high_soft_epic", "史詩偏高但軟", "epic high soft", "高、軟、史詩", "high, soft, epic", "史詩尺度的偏高不尖", "at epic scale, high but not shrill", "epic, high soft pitch"],
    ["very_low_court", "宮廷極低", "court very low", "極低、壓、宮廷", "very low, weight, courtly", "宮廷氣場下的明顯偏低", "in a courtly register, noticeably low", "courtly, very low pitch"],
    ["very_low_street", "街頭極低", "street very low", "極低、壓、街頭", "very low, weight, street", "街頭質感的明顯偏低", "with street grit, noticeably low", "street-cast, very low pitch"],
    ["very_low_noir", "暗黑極低", "noir very low", "極低、壓、暗黑", "very low, weight, noir", "暗調電影感的明顯偏低", "in noir lighting, noticeably low", "noir, very low pitch"],
    ["very_low_soft", "柔光極低", "soft-light very low", "極低、壓、柔光", "very low, weight, soft", "柔光下的明顯偏低", "under soft light, noticeably low", "soft-lit, very low pitch"],
    ["very_low_epic", "史詩極低", "epic very low", "極低、壓、史詩", "very low, weight, epic", "史詩尺度的明顯偏低", "at epic scale, noticeably low", "epic, very low pitch"],
    ["youth_high_court", "宮廷少年偏高", "court youthful high", "少年、高、宮廷", "youth, high, courtly", "宮廷氣場下的未完全降的高", "in a courtly register, not fully dropped", "courtly, youthful higher pitch"],
    ["youth_high_street", "街頭少年偏高", "street youthful high", "少年、高、街頭", "youth, high, street", "街頭質感的未完全降的高", "with street grit, not fully dropped", "street-cast, youthful higher pitch"],
    ["youth_high_noir", "暗黑少年偏高", "noir youthful high", "少年、高、暗黑", "youth, high, noir", "暗調電影感的未完全降的高", "in noir lighting, not fully dropped", "noir, youthful higher pitch"],
    ["youth_high_soft", "柔光少年偏高", "soft-light youthful high", "少年、高、柔光", "youth, high, soft", "柔光下的未完全降的高", "under soft light, not fully dropped", "soft-lit, youthful higher pitch"],
    ["youth_high_epic", "史詩少年偏高", "epic youthful high", "少年、高、史詩", "youth, high, epic", "史詩尺度的未完全降的高", "at epic scale, not fully dropped", "epic, youthful higher pitch"],
    ["androgynous_court", "宮廷中性音高", "court androgynous", "中性、混、宮廷", "andro, mixed, courtly", "宮廷氣場下的難判性別的中", "in a courtly register, gender-ambiguous mid", "courtly, androgynous mid pitch"],
    ["androgynous_street", "街頭中性音高", "street androgynous", "中性、混、街頭", "andro, mixed, street", "街頭質感的難判性別的中", "with street grit, gender-ambiguous mid", "street-cast, androgynous mid pitch"],
    ["androgynous_noir", "暗黑中性音高", "noir androgynous", "中性、混、暗黑", "andro, mixed, noir", "暗調電影感的難判性別的中", "in noir lighting, gender-ambiguous mid", "noir, androgynous mid pitch"],
    ["androgynous_soft", "柔光中性音高", "soft-light androgynous", "中性、混、柔光", "andro, mixed, soft", "柔光下的難判性別的中", "under soft light, gender-ambiguous mid", "soft-lit, androgynous mid pitch"],
    ["androgynous_epic", "史詩中性音高", "epic androgynous", "中性、混、史詩", "andro, mixed, epic", "史詩尺度的難判性別的中", "at epic scale, gender-ambiguous mid", "epic, androgynous mid pitch"],
    ["drop_court", "宮廷句尾下沉", "court end-drop", "下沉、冷、宮廷", "drop, cool, courtly", "宮廷氣場下的句末音高下沉", "in a courtly register, pitch drops at ends", "courtly, end-drop pitch"],
    ["drop_street", "街頭句尾下沉", "street end-drop", "下沉、冷、街頭", "drop, cool, street", "街頭質感的句末音高下沉", "with street grit, pitch drops at ends", "street-cast, end-drop pitch"],
    ["drop_noir", "暗黑句尾下沉", "noir end-drop", "下沉、冷、暗黑", "drop, cool, noir", "暗調電影感的句末音高下沉", "in noir lighting, pitch drops at ends", "noir, end-drop pitch"],
    ["drop_soft", "柔光句尾下沉", "soft-light end-drop", "下沉、冷、柔光", "drop, cool, soft", "柔光下的句末音高下沉", "under soft light, pitch drops at ends", "soft-lit, end-drop pitch"],
    ["drop_epic", "史詩句尾下沉", "epic end-drop", "下沉、冷、史詩", "drop, cool, epic", "史詩尺度的句末音高下沉", "at epic scale, pitch drops at ends", "epic, end-drop pitch"],
    ["lift_court", "宮廷句尾上揚", "court end-lift", "上揚、問、宮廷", "lift, query, courtly", "宮廷氣場下的句末微揚", "in a courtly register, slight rise at ends", "courtly, end-lift pitch"],
    ["lift_street", "街頭句尾上揚", "street end-lift", "上揚、問、街頭", "lift, query, street", "街頭質感的句末微揚", "with street grit, slight rise at ends", "street-cast, end-lift pitch"],
    ["lift_noir", "暗黑句尾上揚", "noir end-lift", "上揚、問、暗黑", "lift, query, noir", "暗調電影感的句末微揚", "in noir lighting, slight rise at ends", "noir, end-lift pitch"],
    ["lift_soft", "柔光句尾上揚", "soft-light end-lift", "上揚、問、柔光", "lift, query, soft", "柔光下的句末微揚", "under soft light, slight rise at ends", "soft-lit, end-lift pitch"],
    ["lift_epic", "史詩句尾上揚", "epic end-lift", "上揚、問、史詩", "lift, query, epic", "史詩尺度的句末微揚", "at epic scale, slight rise at ends", "epic, end-lift pitch"],
    ["narrow_court", "宮廷音域窄", "court narrow range", "窄、平、宮廷", "narrow, flat, courtly", "宮廷氣場下的少大跳", "in a courtly register, little pitch leap", "courtly, narrow pitch range"],
    ["narrow_street", "街頭音域窄", "street narrow range", "窄、平、街頭", "narrow, flat, street", "街頭質感的少大跳", "with street grit, little pitch leap", "street-cast, narrow pitch range"],
    ["narrow_noir", "暗黑音域窄", "noir narrow range", "窄、平、暗黑", "narrow, flat, noir", "暗調電影感的少大跳", "in noir lighting, little pitch leap", "noir, narrow pitch range"],
    ["narrow_soft", "柔光音域窄", "soft-light narrow range", "窄、平、柔光", "narrow, flat, soft", "柔光下的少大跳", "under soft light, little pitch leap", "soft-lit, narrow pitch range"],
    ["narrow_epic", "史詩音域窄", "epic narrow range", "窄、平、史詩", "narrow, flat, epic", "史詩尺度的少大跳", "at epic scale, little pitch leap", "epic, narrow pitch range"],
    ["wide_court", "宮廷音域寬", "court wide range", "寬、戲、宮廷", "wide, dramatic, courtly", "宮廷氣場下的情緒時大跳", "in a courtly register, wide leaps in emotion", "courtly, wide pitch range"],
    ["wide_street", "街頭音域寬", "street wide range", "寬、戲、街頭", "wide, dramatic, street", "街頭質感的情緒時大跳", "with street grit, wide leaps in emotion", "street-cast, wide pitch range"],
    ["wide_noir", "暗黑音域寬", "noir wide range", "寬、戲、暗黑", "wide, dramatic, noir", "暗調電影感的情緒時大跳", "in noir lighting, wide leaps in emotion", "noir, wide pitch range"],
    ["wide_soft", "柔光音域寬", "soft-light wide range", "寬、戲、柔光", "wide, dramatic, soft", "柔光下的情緒時大跳", "under soft light, wide leaps in emotion", "soft-lit, wide pitch range"],
    ["wide_epic", "史詩音域寬", "epic wide range", "寬、戲、史詩", "wide, dramatic, epic", "史詩尺度的情緒時大跳", "at epic scale, wide leaps in emotion", "epic, wide pitch range"]
  ],
    texture: [
    ["velvet_court", "宮廷絲絨", "court velvet", "絨、暖、宮廷", "velvet, warm, courtly", "宮廷氣場下的暖而包的質地", "in a courtly register, warm wrapped texture", "courtly, velvet voice texture"],
    ["velvet_street", "街頭絲絨", "street velvet", "絨、暖、街頭", "velvet, warm, street", "街頭質感的暖而包的質地", "with street grit, warm wrapped texture", "street-cast, velvet voice texture"],
    ["velvet_noir", "暗黑絲絨", "noir velvet", "絨、暖、暗黑", "velvet, warm, noir", "暗調電影感的暖而包的質地", "in noir lighting, warm wrapped texture", "noir, velvet voice texture"],
    ["velvet_soft", "柔光絲絨", "soft-light velvet", "絨、暖、柔光", "velvet, warm, soft", "柔光下的暖而包的質地", "under soft light, warm wrapped texture", "soft-lit, velvet voice texture"],
    ["velvet_epic", "史詩絲絨", "epic velvet", "絨、暖、史詩", "velvet, warm, epic", "史詩尺度的暖而包的質地", "at epic scale, warm wrapped texture", "epic, velvet voice texture"],
    ["raspy_court", "宮廷微沙", "court raspy", "沙、煙、宮廷", "rasp, smoke, courtly", "宮廷氣場下的輕微沙啞", "in a courtly register, light rasp", "courtly, light raspy texture"],
    ["raspy_street", "街頭微沙", "street raspy", "沙、煙、街頭", "rasp, smoke, street", "街頭質感的輕微沙啞", "with street grit, light rasp", "street-cast, light raspy texture"],
    ["raspy_noir", "暗黑微沙", "noir raspy", "沙、煙、暗黑", "rasp, smoke, noir", "暗調電影感的輕微沙啞", "in noir lighting, light rasp", "noir, light raspy texture"],
    ["raspy_soft", "柔光微沙", "soft-light raspy", "沙、煙、柔光", "rasp, smoke, soft", "柔光下的輕微沙啞", "under soft light, light rasp", "soft-lit, light raspy texture"],
    ["raspy_epic", "史詩微沙", "epic raspy", "沙、煙、史詩", "rasp, smoke, epic", "史詩尺度的輕微沙啞", "at epic scale, light rasp", "epic, light raspy texture"],
    ["glass_court", "宮廷玻璃清", "court glassy", "清、冷、宮廷", "clear, cool, courtly", "宮廷氣場下的過清近玻璃", "in a courtly register, very clear glassy", "courtly, glassy clear texture"],
    ["glass_street", "街頭玻璃清", "street glassy", "清、冷、街頭", "clear, cool, street", "街頭質感的過清近玻璃", "with street grit, very clear glassy", "street-cast, glassy clear texture"],
    ["glass_noir", "暗黑玻璃清", "noir glassy", "清、冷、暗黑", "clear, cool, noir", "暗調電影感的過清近玻璃", "in noir lighting, very clear glassy", "noir, glassy clear texture"],
    ["glass_soft", "柔光玻璃清", "soft-light glassy", "清、冷、柔光", "clear, cool, soft", "柔光下的過清近玻璃", "under soft light, very clear glassy", "soft-lit, glassy clear texture"],
    ["glass_epic", "史詩玻璃清", "epic glassy", "清、冷、史詩", "clear, cool, epic", "史詩尺度的過清近玻璃", "at epic scale, very clear glassy", "epic, glassy clear texture"],
    ["breathy_tex_court", "宮廷氣聲多", "court breathy", "氣、柔、宮廷", "air, soft, courtly", "宮廷氣場下的明顯氣聲", "in a courtly register, audible breath noise", "courtly, breathy texture"],
    ["breathy_tex_street", "街頭氣聲多", "street breathy", "氣、柔、街頭", "air, soft, street", "街頭質感的明顯氣聲", "with street grit, audible breath noise", "street-cast, breathy texture"],
    ["breathy_tex_noir", "暗黑氣聲多", "noir breathy", "氣、柔、暗黑", "air, soft, noir", "暗調電影感的明顯氣聲", "in noir lighting, audible breath noise", "noir, breathy texture"],
    ["breathy_tex_soft", "柔光氣聲多", "soft-light breathy", "氣、柔、柔光", "air, soft, soft", "柔光下的明顯氣聲", "under soft light, audible breath noise", "soft-lit, breathy texture"],
    ["breathy_tex_epic", "史詩氣聲多", "epic breathy", "氣、柔、史詩", "air, soft, epic", "史詩尺度的明顯氣聲", "at epic scale, audible breath noise", "epic, breathy texture"],
    ["metallic_court", "宮廷金屬亮", "court metallic", "亮、利、宮廷", "bright, edge, courtly", "宮廷氣場下的偏亮帶金屬", "in a courtly register, bright metallic edge", "courtly, metallic texture"],
    ["metallic_street", "街頭金屬亮", "street metallic", "亮、利、街頭", "bright, edge, street", "街頭質感的偏亮帶金屬", "with street grit, bright metallic edge", "street-cast, metallic texture"],
    ["metallic_noir", "暗黑金屬亮", "noir metallic", "亮、利、暗黑", "bright, edge, noir", "暗調電影感的偏亮帶金屬", "in noir lighting, bright metallic edge", "noir, metallic texture"],
    ["metallic_soft", "柔光金屬亮", "soft-light metallic", "亮、利、柔光", "bright, edge, soft", "柔光下的偏亮帶金屬", "under soft light, bright metallic edge", "soft-lit, metallic texture"],
    ["metallic_epic", "史詩金屬亮", "epic metallic", "亮、利、史詩", "bright, edge, epic", "史詩尺度的偏亮帶金屬", "at epic scale, bright metallic edge", "epic, metallic texture"],
    ["husky_court", "宮廷厚啞", "court husky", "厚、啞、宮廷", "husky, thick, courtly", "宮廷氣場下的較厚的啞", "in a courtly register, thicker husk", "courtly, husky texture"],
    ["husky_street", "街頭厚啞", "street husky", "厚、啞、街頭", "husky, thick, street", "街頭質感的較厚的啞", "with street grit, thicker husk", "street-cast, husky texture"],
    ["husky_noir", "暗黑厚啞", "noir husky", "厚、啞、暗黑", "husky, thick, noir", "暗調電影感的較厚的啞", "in noir lighting, thicker husk", "noir, husky texture"],
    ["husky_soft", "柔光厚啞", "soft-light husky", "厚、啞、柔光", "husky, thick, soft", "柔光下的較厚的啞", "under soft light, thicker husk", "soft-lit, husky texture"],
    ["husky_epic", "史詩厚啞", "epic husky", "厚、啞、史詩", "husky, thick, epic", "史詩尺度的較厚的啞", "at epic scale, thicker husk", "epic, husky texture"],
    ["nasal_light_court", "宮廷輕鼻音", "court light nasal", "鼻、記、宮廷", "nasal, mark, courtly", "宮廷氣場下的輕度鼻音", "in a courtly register, light nasal color", "courtly, light nasal texture"],
    ["nasal_light_street", "街頭輕鼻音", "street light nasal", "鼻、記、街頭", "nasal, mark, street", "街頭質感的輕度鼻音", "with street grit, light nasal color", "street-cast, light nasal texture"],
    ["nasal_light_noir", "暗黑輕鼻音", "noir light nasal", "鼻、記、暗黑", "nasal, mark, noir", "暗調電影感的輕度鼻音", "in noir lighting, light nasal color", "noir, light nasal texture"],
    ["nasal_light_soft", "柔光輕鼻音", "soft-light light nasal", "鼻、記、柔光", "nasal, mark, soft", "柔光下的輕度鼻音", "under soft light, light nasal color", "soft-lit, light nasal texture"],
    ["nasal_light_epic", "史詩輕鼻音", "epic light nasal", "鼻、記、史詩", "nasal, mark, epic", "史詩尺度的輕度鼻音", "at epic scale, light nasal color", "epic, light nasal texture"],
    ["dry_court", "宮廷乾薄", "court dry thin", "乾、薄、宮廷", "dry, thin, courtly", "宮廷氣場下的少潤的薄", "in a courtly register, dry thin tone", "courtly, dry thin texture"],
    ["dry_street", "街頭乾薄", "street dry thin", "乾、薄、街頭", "dry, thin, street", "街頭質感的少潤的薄", "with street grit, dry thin tone", "street-cast, dry thin texture"],
    ["dry_noir", "暗黑乾薄", "noir dry thin", "乾、薄、暗黑", "dry, thin, noir", "暗調電影感的少潤的薄", "in noir lighting, dry thin tone", "noir, dry thin texture"],
    ["dry_soft", "柔光乾薄", "soft-light dry thin", "乾、薄、柔光", "dry, thin, soft", "柔光下的少潤的薄", "under soft light, dry thin tone", "soft-lit, dry thin texture"],
    ["dry_epic", "史詩乾薄", "epic dry thin", "乾、薄、史詩", "dry, thin, epic", "史詩尺度的少潤的薄", "at epic scale, dry thin tone", "epic, dry thin texture"],
    ["warm_round_court", "宮廷圓潤暖", "court warm round", "圓、暖、宮廷", "round, warm, courtly", "宮廷氣場下的圓而暖", "in a courtly register, round warm tone", "courtly, warm round texture"],
    ["warm_round_street", "街頭圓潤暖", "street warm round", "圓、暖、街頭", "round, warm, street", "街頭質感的圓而暖", "with street grit, round warm tone", "street-cast, warm round texture"],
    ["warm_round_noir", "暗黑圓潤暖", "noir warm round", "圓、暖、暗黑", "round, warm, noir", "暗調電影感的圓而暖", "in noir lighting, round warm tone", "noir, warm round texture"],
    ["warm_round_soft", "柔光圓潤暖", "soft-light warm round", "圓、暖、柔光", "round, warm, soft", "柔光下的圓而暖", "under soft light, round warm tone", "soft-lit, warm round texture"],
    ["warm_round_epic", "史詩圓潤暖", "epic warm round", "圓、暖、史詩", "round, warm, epic", "史詩尺度的圓而暖", "at epic scale, round warm tone", "epic, warm round texture"],
    ["cracked_court", "宮廷裂紋", "court cracked", "裂、傷、宮廷", "crack, wound, courtly", "宮廷氣場下的偶爾裂一下", "in a courtly register, occasional crack", "courtly, cracked texture"],
    ["cracked_street", "街頭裂紋", "street cracked", "裂、傷、街頭", "crack, wound, street", "街頭質感的偶爾裂一下", "with street grit, occasional crack", "street-cast, cracked texture"],
    ["cracked_noir", "暗黑裂紋", "noir cracked", "裂、傷、暗黑", "crack, wound, noir", "暗調電影感的偶爾裂一下", "in noir lighting, occasional crack", "noir, cracked texture"],
    ["cracked_soft", "柔光裂紋", "soft-light cracked", "裂、傷、柔光", "crack, wound, soft", "柔光下的偶爾裂一下", "under soft light, occasional crack", "soft-lit, cracked texture"],
    ["cracked_epic", "史詩裂紋", "epic cracked", "裂、傷、史詩", "crack, wound, epic", "史詩尺度的偶爾裂一下", "at epic scale, occasional crack", "epic, cracked texture"]
  ],
    pace: [
    ["slow_court", "宮廷偏慢", "court slow", "慢、壓、宮廷", "slow, weight, courtly", "宮廷氣場下的整體偏慢", "in a courtly register, overall slow", "courtly, slow speaking pace"],
    ["slow_street", "街頭偏慢", "street slow", "慢、壓、街頭", "slow, weight, street", "街頭質感的整體偏慢", "with street grit, overall slow", "street-cast, slow speaking pace"],
    ["slow_noir", "暗黑偏慢", "noir slow", "慢、壓、暗黑", "slow, weight, noir", "暗調電影感的整體偏慢", "in noir lighting, overall slow", "noir, slow speaking pace"],
    ["slow_soft", "柔光偏慢", "soft-light slow", "慢、壓、柔光", "slow, weight, soft", "柔光下的整體偏慢", "under soft light, overall slow", "soft-lit, slow speaking pace"],
    ["slow_epic", "史詩偏慢", "epic slow", "慢、壓、史詩", "slow, weight, epic", "史詩尺度的整體偏慢", "at epic scale, overall slow", "epic, slow speaking pace"],
    ["measured_court", "宮廷計量", "court measured", "計量、控、宮廷", "measured, control, courtly", "宮廷氣場下的字與字有距", "in a courtly register, spaced measured words", "courtly, measured pace"],
    ["measured_street", "街頭計量", "street measured", "計量、控、街頭", "measured, control, street", "街頭質感的字與字有距", "with street grit, spaced measured words", "street-cast, measured pace"],
    ["measured_noir", "暗黑計量", "noir measured", "計量、控、暗黑", "measured, control, noir", "暗調電影感的字與字有距", "in noir lighting, spaced measured words", "noir, measured pace"],
    ["measured_soft", "柔光計量", "soft-light measured", "計量、控、柔光", "measured, control, soft", "柔光下的字與字有距", "under soft light, spaced measured words", "soft-lit, measured pace"],
    ["measured_epic", "史詩計量", "epic measured", "計量、控、史詩", "measured, control, epic", "史詩尺度的字與字有距", "at epic scale, spaced measured words", "epic, measured pace"],
    ["medium_court", "宮廷中速", "court medium", "中、常、宮廷", "medium, normal, courtly", "宮廷氣場下的日常中速", "in a courtly register, everyday medium", "courtly, medium pace"],
    ["medium_street", "街頭中速", "street medium", "中、常、街頭", "medium, normal, street", "街頭質感的日常中速", "with street grit, everyday medium", "street-cast, medium pace"],
    ["medium_noir", "暗黑中速", "noir medium", "中、常、暗黑", "medium, normal, noir", "暗調電影感的日常中速", "in noir lighting, everyday medium", "noir, medium pace"],
    ["medium_soft", "柔光中速", "soft-light medium", "中、常、柔光", "medium, normal, soft", "柔光下的日常中速", "under soft light, everyday medium", "soft-lit, medium pace"],
    ["medium_epic", "史詩中速", "epic medium", "中、常、史詩", "medium, normal, epic", "史詩尺度的日常中速", "at epic scale, everyday medium", "epic, medium pace"],
    ["quick_court", "宮廷偏快", "court quick", "快、利、宮廷", "quick, sharp, courtly", "宮廷氣場下的整體偏快", "in a courtly register, overall quick", "courtly, quick pace"],
    ["quick_street", "街頭偏快", "street quick", "快、利、街頭", "quick, sharp, street", "街頭質感的整體偏快", "with street grit, overall quick", "street-cast, quick pace"],
    ["quick_noir", "暗黑偏快", "noir quick", "快、利、暗黑", "quick, sharp, noir", "暗調電影感的整體偏快", "in noir lighting, overall quick", "noir, quick pace"],
    ["quick_soft", "柔光偏快", "soft-light quick", "快、利、柔光", "quick, sharp, soft", "柔光下的整體偏快", "under soft light, overall quick", "soft-lit, quick pace"],
    ["quick_epic", "史詩偏快", "epic quick", "快、利、史詩", "quick, sharp, epic", "史詩尺度的整體偏快", "at epic scale, overall quick", "epic, quick pace"],
    ["staccato_court", "宮廷頓挫", "court staccato", "頓、斷、宮廷", "staccato, cut, courtly", "宮廷氣場下的短促切斷", "in a courtly register, cut short beats", "courtly, staccato pace"],
    ["staccato_street", "街頭頓挫", "street staccato", "頓、斷、街頭", "staccato, cut, street", "街頭質感的短促切斷", "with street grit, cut short beats", "street-cast, staccato pace"],
    ["staccato_noir", "暗黑頓挫", "noir staccato", "頓、斷、暗黑", "staccato, cut, noir", "暗調電影感的短促切斷", "in noir lighting, cut short beats", "noir, staccato pace"],
    ["staccato_soft", "柔光頓挫", "soft-light staccato", "頓、斷、柔光", "staccato, cut, soft", "柔光下的短促切斷", "under soft light, cut short beats", "soft-lit, staccato pace"],
    ["staccato_epic", "史詩頓挫", "epic staccato", "頓、斷、史詩", "staccato, cut, epic", "史詩尺度的短促切斷", "at epic scale, cut short beats", "epic, staccato pace"],
    ["rush_then_stop_court", "宮廷衝再停", "court rush-stop", "衝、停、宮廷", "rush, halt, courtly", "宮廷氣場下的先衝後急停", "in a courtly register, rush then hard stop", "courtly, rush-then-stop pace"],
    ["rush_then_stop_street", "街頭衝再停", "street rush-stop", "衝、停、街頭", "rush, halt, street", "街頭質感的先衝後急停", "with street grit, rush then hard stop", "street-cast, rush-then-stop pace"],
    ["rush_then_stop_noir", "暗黑衝再停", "noir rush-stop", "衝、停、暗黑", "rush, halt, noir", "暗調電影感的先衝後急停", "in noir lighting, rush then hard stop", "noir, rush-then-stop pace"],
    ["rush_then_stop_soft", "柔光衝再停", "soft-light rush-stop", "衝、停、柔光", "rush, halt, soft", "柔光下的先衝後急停", "under soft light, rush then hard stop", "soft-lit, rush-then-stop pace"],
    ["rush_then_stop_epic", "史詩衝再停", "epic rush-stop", "衝、停、史詩", "rush, halt, epic", "史詩尺度的先衝後急停", "at epic scale, rush then hard stop", "epic, rush-then-stop pace"],
    ["drawl_court", "宮廷拖尾", "court drawl", "拖、懶、宮廷", "drawl, lazy, courtly", "宮廷氣場下的元音拖長", "in a courtly register, drawn vowels", "courtly, drawling pace"],
    ["drawl_street", "街頭拖尾", "street drawl", "拖、懶、街頭", "drawl, lazy, street", "街頭質感的元音拖長", "with street grit, drawn vowels", "street-cast, drawling pace"],
    ["drawl_noir", "暗黑拖尾", "noir drawl", "拖、懶、暗黑", "drawl, lazy, noir", "暗調電影感的元音拖長", "in noir lighting, drawn vowels", "noir, drawling pace"],
    ["drawl_soft", "柔光拖尾", "soft-light drawl", "拖、懶、柔光", "drawl, lazy, soft", "柔光下的元音拖長", "under soft light, drawn vowels", "soft-lit, drawling pace"],
    ["drawl_epic", "史詩拖尾", "epic drawl", "拖、懶、史詩", "drawl, lazy, epic", "史詩尺度的元音拖長", "at epic scale, drawn vowels", "epic, drawling pace"],
    ["machine_court", "宮廷均速機", "court metronomic", "均、機、宮廷", "even, machine, courtly", "宮廷氣場下的幾乎等速", "in a courtly register, almost even tempo", "courtly, metronomic pace"],
    ["machine_street", "街頭均速機", "street metronomic", "均、機、街頭", "even, machine, street", "街頭質感的幾乎等速", "with street grit, almost even tempo", "street-cast, metronomic pace"],
    ["machine_noir", "暗黑均速機", "noir metronomic", "均、機、暗黑", "even, machine, noir", "暗調電影感的幾乎等速", "in noir lighting, almost even tempo", "noir, metronomic pace"],
    ["machine_soft", "柔光均速機", "soft-light metronomic", "均、機、柔光", "even, machine, soft", "柔光下的幾乎等速", "under soft light, almost even tempo", "soft-lit, metronomic pace"],
    ["machine_epic", "史詩均速機", "epic metronomic", "均、機、史詩", "even, machine, epic", "史詩尺度的幾乎等速", "at epic scale, almost even tempo", "epic, metronomic pace"],
    ["hesitant_court", "宮廷遲疑", "court hesitant", "遲、想、宮廷", "hesitant, think, courtly", "宮廷氣場下的中間常頓", "in a courtly register, frequent mid pauses", "courtly, hesitant pace"],
    ["hesitant_street", "街頭遲疑", "street hesitant", "遲、想、街頭", "hesitant, think, street", "街頭質感的中間常頓", "with street grit, frequent mid pauses", "street-cast, hesitant pace"],
    ["hesitant_noir", "暗黑遲疑", "noir hesitant", "遲、想、暗黑", "hesitant, think, noir", "暗調電影感的中間常頓", "in noir lighting, frequent mid pauses", "noir, hesitant pace"],
    ["hesitant_soft", "柔光遲疑", "soft-light hesitant", "遲、想、柔光", "hesitant, think, soft", "柔光下的中間常頓", "under soft light, frequent mid pauses", "soft-lit, hesitant pace"],
    ["hesitant_epic", "史詩遲疑", "epic hesitant", "遲、想、史詩", "hesitant, think, epic", "史詩尺度的中間常頓", "at epic scale, frequent mid pauses", "epic, hesitant pace"],
    ["pressing_court", "宮廷催逼", "court pressing", "催、壓、宮廷", "press, push, courtly", "宮廷氣場下的不斷往前催", "in a courtly register, forward pressing", "courtly, pressing pace"],
    ["pressing_street", "街頭催逼", "street pressing", "催、壓、街頭", "press, push, street", "街頭質感的不斷往前催", "with street grit, forward pressing", "street-cast, pressing pace"],
    ["pressing_noir", "暗黑催逼", "noir pressing", "催、壓、暗黑", "press, push, noir", "暗調電影感的不斷往前催", "in noir lighting, forward pressing", "noir, pressing pace"],
    ["pressing_soft", "柔光催逼", "soft-light pressing", "催、壓、柔光", "press, push, soft", "柔光下的不斷往前催", "under soft light, forward pressing", "soft-lit, pressing pace"],
    ["pressing_epic", "史詩催逼", "epic pressing", "催、壓、史詩", "press, push, epic", "史詩尺度的不斷往前催", "at epic scale, forward pressing", "epic, pressing pace"]
  ],
    register: [
    ["chest_court", "宮廷胸聲", "court chest", "胸、穩、宮廷", "chest, grounded, courtly", "宮廷氣場下的以胸聲為主", "in a courtly register, mostly chest voice", "courtly, chest-register voice"],
    ["chest_street", "街頭胸聲", "street chest", "胸、穩、街頭", "chest, grounded, street", "街頭質感的以胸聲為主", "with street grit, mostly chest voice", "street-cast, chest-register voice"],
    ["chest_noir", "暗黑胸聲", "noir chest", "胸、穩、暗黑", "chest, grounded, noir", "暗調電影感的以胸聲為主", "in noir lighting, mostly chest voice", "noir, chest-register voice"],
    ["chest_soft", "柔光胸聲", "soft-light chest", "胸、穩、柔光", "chest, grounded, soft", "柔光下的以胸聲為主", "under soft light, mostly chest voice", "soft-lit, chest-register voice"],
    ["chest_epic", "史詩胸聲", "epic chest", "胸、穩、史詩", "chest, grounded, epic", "史詩尺度的以胸聲為主", "at epic scale, mostly chest voice", "epic, chest-register voice"],
    ["head_court", "宮廷頭聲偏多", "court heady", "頭、飄、宮廷", "head, float, courtly", "宮廷氣場下的頭聲比例高", "in a courtly register, more head voice", "courtly, head-register lean"],
    ["head_street", "街頭頭聲偏多", "street heady", "頭、飄、街頭", "head, float, street", "街頭質感的頭聲比例高", "with street grit, more head voice", "street-cast, head-register lean"],
    ["head_noir", "暗黑頭聲偏多", "noir heady", "頭、飄、暗黑", "head, float, noir", "暗調電影感的頭聲比例高", "in noir lighting, more head voice", "noir, head-register lean"],
    ["head_soft", "柔光頭聲偏多", "soft-light heady", "頭、飄、柔光", "head, float, soft", "柔光下的頭聲比例高", "under soft light, more head voice", "soft-lit, head-register lean"],
    ["head_epic", "史詩頭聲偏多", "epic heady", "頭、飄、史詩", "head, float, epic", "史詩尺度的頭聲比例高", "at epic scale, more head voice", "epic, head-register lean"],
    ["mix_court", "宮廷混聲", "court mixed", "混、均、宮廷", "mix, blend, courtly", "宮廷氣場下的胸頭混合", "in a courtly register, blended mix", "courtly, mixed register"],
    ["mix_street", "街頭混聲", "street mixed", "混、均、街頭", "mix, blend, street", "街頭質感的胸頭混合", "with street grit, blended mix", "street-cast, mixed register"],
    ["mix_noir", "暗黑混聲", "noir mixed", "混、均、暗黑", "mix, blend, noir", "暗調電影感的胸頭混合", "in noir lighting, blended mix", "noir, mixed register"],
    ["mix_soft", "柔光混聲", "soft-light mixed", "混、均、柔光", "mix, blend, soft", "柔光下的胸頭混合", "under soft light, blended mix", "soft-lit, mixed register"],
    ["mix_epic", "史詩混聲", "epic mixed", "混、均、史詩", "mix, blend, epic", "史詩尺度的胸頭混合", "at epic scale, blended mix", "epic, mixed register"],
    ["falsetto_edge_court", "宮廷偶假聲", "court falsetto edge", "假、隙、宮廷", "falsetto, crack, courtly", "宮廷氣場下的情緒時假聲", "in a courtly register, falsetto on emotion", "courtly, occasional falsetto edge"],
    ["falsetto_edge_street", "街頭偶假聲", "street falsetto edge", "假、隙、街頭", "falsetto, crack, street", "街頭質感的情緒時假聲", "with street grit, falsetto on emotion", "street-cast, occasional falsetto edge"],
    ["falsetto_edge_noir", "暗黑偶假聲", "noir falsetto edge", "假、隙、暗黑", "falsetto, crack, noir", "暗調電影感的情緒時假聲", "in noir lighting, falsetto on emotion", "noir, occasional falsetto edge"],
    ["falsetto_edge_soft", "柔光偶假聲", "soft-light falsetto edge", "假、隙、柔光", "falsetto, crack, soft", "柔光下的情緒時假聲", "under soft light, falsetto on emotion", "soft-lit, occasional falsetto edge"],
    ["falsetto_edge_epic", "史詩偶假聲", "epic falsetto edge", "假、隙、史詩", "falsetto, crack, epic", "史詩尺度的情緒時假聲", "at epic scale, falsetto on emotion", "epic, occasional falsetto edge"],
    ["spoken_sung_court", "宮廷似念似唱", "court speak-sing", "念唱、調、宮廷", "chant, tone, courtly", "宮廷氣場下的帶音高的說話", "in a courtly register, pitched speaking", "courtly, speak-sing register"],
    ["spoken_sung_street", "街頭似念似唱", "street speak-sing", "念唱、調、街頭", "chant, tone, street", "街頭質感的帶音高的說話", "with street grit, pitched speaking", "street-cast, speak-sing register"],
    ["spoken_sung_noir", "暗黑似念似唱", "noir speak-sing", "念唱、調、暗黑", "chant, tone, noir", "暗調電影感的帶音高的說話", "in noir lighting, pitched speaking", "noir, speak-sing register"],
    ["spoken_sung_soft", "柔光似念似唱", "soft-light speak-sing", "念唱、調、柔光", "chant, tone, soft", "柔光下的帶音高的說話", "under soft light, pitched speaking", "soft-lit, speak-sing register"],
    ["spoken_sung_epic", "史詩似念似唱", "epic speak-sing", "念唱、調、史詩", "chant, tone, epic", "史詩尺度的帶音高的說話", "at epic scale, pitched speaking", "epic, speak-sing register"],
    ["whisp_reg_court", "宮廷氣聲位", "court whisper register", "氣、近、宮廷", "whisper, close, courtly", "宮廷氣場下的近耳語氣位", "in a courtly register, close whisper placement", "courtly, whisper register"],
    ["whisp_reg_street", "街頭氣聲位", "street whisper register", "氣、近、街頭", "whisper, close, street", "街頭質感的近耳語氣位", "with street grit, close whisper placement", "street-cast, whisper register"],
    ["whisp_reg_noir", "暗黑氣聲位", "noir whisper register", "氣、近、暗黑", "whisper, close, noir", "暗調電影感的近耳語氣位", "in noir lighting, close whisper placement", "noir, whisper register"],
    ["whisp_reg_soft", "柔光氣聲位", "soft-light whisper register", "氣、近、柔光", "whisper, close, soft", "柔光下的近耳語氣位", "under soft light, close whisper placement", "soft-lit, whisper register"],
    ["whisp_reg_epic", "史詩氣聲位", "epic whisper register", "氣、近、史詩", "whisper, close, epic", "史詩尺度的近耳語氣位", "at epic scale, close whisper placement", "epic, whisper register"],
    ["bark_court", "宮廷短喝", "court bark", "喝、令、宮廷", "bark, order, courtly", "宮廷氣場下的命令短喝", "in a courtly register, short barked orders", "courtly, bark register"],
    ["bark_street", "街頭短喝", "street bark", "喝、令、街頭", "bark, order, street", "街頭質感的命令短喝", "with street grit, short barked orders", "street-cast, bark register"],
    ["bark_noir", "暗黑短喝", "noir bark", "喝、令、暗黑", "bark, order, noir", "暗調電影感的命令短喝", "in noir lighting, short barked orders", "noir, bark register"],
    ["bark_soft", "柔光短喝", "soft-light bark", "喝、令、柔光", "bark, order, soft", "柔光下的命令短喝", "under soft light, short barked orders", "soft-lit, bark register"],
    ["bark_epic", "史詩短喝", "epic bark", "喝、令、史詩", "bark, order, epic", "史詩尺度的命令短喝", "at epic scale, short barked orders", "epic, bark register"],
    ["murmur_court", "宮廷低喃位", "court murmur", "喃、內、宮廷", "murmur, inner, courtly", "宮廷氣場下的偏低喃", "in a courtly register, low murmur placement", "courtly, murmur register"],
    ["murmur_street", "街頭低喃位", "street murmur", "喃、內、街頭", "murmur, inner, street", "街頭質感的偏低喃", "with street grit, low murmur placement", "street-cast, murmur register"],
    ["murmur_noir", "暗黑低喃位", "noir murmur", "喃、內、暗黑", "murmur, inner, noir", "暗調電影感的偏低喃", "in noir lighting, low murmur placement", "noir, murmur register"],
    ["murmur_soft", "柔光低喃位", "soft-light murmur", "喃、內、柔光", "murmur, inner, soft", "柔光下的偏低喃", "under soft light, low murmur placement", "soft-lit, murmur register"],
    ["murmur_epic", "史詩低喃位", "epic murmur", "喃、內、史詩", "murmur, inner, epic", "史詩尺度的偏低喃", "at epic scale, low murmur placement", "epic, murmur register"],
    ["announce_court", "宮廷宣告位", "court announcer", "宣告、開、宮廷", "announce, open, courtly", "宮廷氣場下的打開的宣告", "in a courtly register, open announcing", "courtly, announcer register"],
    ["announce_street", "街頭宣告位", "street announcer", "宣告、開、街頭", "announce, open, street", "街頭質感的打開的宣告", "with street grit, open announcing", "street-cast, announcer register"],
    ["announce_noir", "暗黑宣告位", "noir announcer", "宣告、開、暗黑", "announce, open, noir", "暗調電影感的打開的宣告", "in noir lighting, open announcing", "noir, announcer register"],
    ["announce_soft", "柔光宣告位", "soft-light announcer", "宣告、開、柔光", "announce, open, soft", "柔光下的打開的宣告", "under soft light, open announcing", "soft-lit, announcer register"],
    ["announce_epic", "史詩宣告位", "epic announcer", "宣告、開、史詩", "announce, open, epic", "史詩尺度的打開的宣告", "at epic scale, open announcing", "epic, announcer register"],
    ["child_place_court", "宮廷偏幼位", "court youth placement", "幼、前、宮廷", "youth, forward, courtly", "宮廷氣場下的靠前幼位", "in a courtly register, forward youthful", "courtly, youthful placement"],
    ["child_place_street", "街頭偏幼位", "street youth placement", "幼、前、街頭", "youth, forward, street", "街頭質感的靠前幼位", "with street grit, forward youthful", "street-cast, youthful placement"],
    ["child_place_noir", "暗黑偏幼位", "noir youth placement", "幼、前、暗黑", "youth, forward, noir", "暗調電影感的靠前幼位", "in noir lighting, forward youthful", "noir, youthful placement"],
    ["child_place_soft", "柔光偏幼位", "soft-light youth placement", "幼、前、柔光", "youth, forward, soft", "柔光下的靠前幼位", "under soft light, forward youthful", "soft-lit, youthful placement"],
    ["child_place_epic", "史詩偏幼位", "epic youth placement", "幼、前、史詩", "youth, forward, epic", "史詩尺度的靠前幼位", "at epic scale, forward youthful", "epic, youthful placement"]
  ],
    breath: [
    ["hidden_court", "宮廷藏氣", "court hidden breath", "藏、控、宮廷", "hidden, control, courtly", "宮廷氣場下的幾乎聽不到換氣", "in a courtly register, breaths hidden", "courtly, hidden breaths"],
    ["hidden_street", "街頭藏氣", "street hidden breath", "藏、控、街頭", "hidden, control, street", "街頭質感的幾乎聽不到換氣", "with street grit, breaths hidden", "street-cast, hidden breaths"],
    ["hidden_noir", "暗黑藏氣", "noir hidden breath", "藏、控、暗黑", "hidden, control, noir", "暗調電影感的幾乎聽不到換氣", "in noir lighting, breaths hidden", "noir, hidden breaths"],
    ["hidden_soft", "柔光藏氣", "soft-light hidden breath", "藏、控、柔光", "hidden, control, soft", "柔光下的幾乎聽不到換氣", "under soft light, breaths hidden", "soft-lit, hidden breaths"],
    ["hidden_epic", "史詩藏氣", "epic hidden breath", "藏、控、史詩", "hidden, control, epic", "史詩尺度的幾乎聽不到換氣", "at epic scale, breaths hidden", "epic, hidden breaths"],
    ["audible_court", "宮廷可聞換氣", "court audible", "可聞、近、宮廷", "audible, close, courtly", "宮廷氣場下的換氣聽得見", "in a courtly register, breaths audible", "courtly, audible breaths"],
    ["audible_street", "街頭可聞換氣", "street audible", "可聞、近、街頭", "audible, close, street", "街頭質感的換氣聽得見", "with street grit, breaths audible", "street-cast, audible breaths"],
    ["audible_noir", "暗黑可聞換氣", "noir audible", "可聞、近、暗黑", "audible, close, noir", "暗調電影感的換氣聽得見", "in noir lighting, breaths audible", "noir, audible breaths"],
    ["audible_soft", "柔光可聞換氣", "soft-light audible", "可聞、近、柔光", "audible, close, soft", "柔光下的換氣聽得見", "under soft light, breaths audible", "soft-lit, audible breaths"],
    ["audible_epic", "史詩可聞換氣", "epic audible", "可聞、近、史詩", "audible, close, epic", "史詩尺度的換氣聽得見", "at epic scale, breaths audible", "epic, audible breaths"],
    ["sigh_court", "宮廷常嘆氣", "court sighing", "嘆、疲、宮廷", "sigh, tired, courtly", "宮廷氣場下的句間嘆氣", "in a courtly register, sighs between lines", "courtly, sighing breath"],
    ["sigh_street", "街頭常嘆氣", "street sighing", "嘆、疲、街頭", "sigh, tired, street", "街頭質感的句間嘆氣", "with street grit, sighs between lines", "street-cast, sighing breath"],
    ["sigh_noir", "暗黑常嘆氣", "noir sighing", "嘆、疲、暗黑", "sigh, tired, noir", "暗調電影感的句間嘆氣", "in noir lighting, sighs between lines", "noir, sighing breath"],
    ["sigh_soft", "柔光常嘆氣", "soft-light sighing", "嘆、疲、柔光", "sigh, tired, soft", "柔光下的句間嘆氣", "under soft light, sighs between lines", "soft-lit, sighing breath"],
    ["sigh_epic", "史詩常嘆氣", "epic sighing", "嘆、疲、史詩", "sigh, tired, epic", "史詩尺度的句間嘆氣", "at epic scale, sighs between lines", "epic, sighing breath"],
    ["held_court", "宮廷長閉氣", "court held", "閉、緊、宮廷", "held, tight, courtly", "宮廷氣場下的說完才換", "in a courtly register, holds then breathes", "courtly, held breath pattern"],
    ["held_street", "街頭長閉氣", "street held", "閉、緊、街頭", "held, tight, street", "街頭質感的說完才換", "with street grit, holds then breathes", "street-cast, held breath pattern"],
    ["held_noir", "暗黑長閉氣", "noir held", "閉、緊、暗黑", "held, tight, noir", "暗調電影感的說完才換", "in noir lighting, holds then breathes", "noir, held breath pattern"],
    ["held_soft", "柔光長閉氣", "soft-light held", "閉、緊、柔光", "held, tight, soft", "柔光下的說完才換", "under soft light, holds then breathes", "soft-lit, held breath pattern"],
    ["held_epic", "史詩長閉氣", "epic held", "閉、緊、史詩", "held, tight, epic", "史詩尺度的說完才換", "at epic scale, holds then breathes", "epic, held breath pattern"],
    ["shallow_court", "宮廷淺快", "court shallow", "淺、緊張、宮廷", "shallow, tense, courtly", "宮廷氣場下的淺而快", "in a courtly register, shallow quick breaths", "courtly, shallow breathing"],
    ["shallow_street", "街頭淺快", "street shallow", "淺、緊張、街頭", "shallow, tense, street", "街頭質感的淺而快", "with street grit, shallow quick breaths", "street-cast, shallow breathing"],
    ["shallow_noir", "暗黑淺快", "noir shallow", "淺、緊張、暗黑", "shallow, tense, noir", "暗調電影感的淺而快", "in noir lighting, shallow quick breaths", "noir, shallow breathing"],
    ["shallow_soft", "柔光淺快", "soft-light shallow", "淺、緊張、柔光", "shallow, tense, soft", "柔光下的淺而快", "under soft light, shallow quick breaths", "soft-lit, shallow breathing"],
    ["shallow_epic", "史詩淺快", "epic shallow", "淺、緊張、史詩", "shallow, tense, epic", "史詩尺度的淺而快", "at epic scale, shallow quick breaths", "epic, shallow breathing"],
    ["deep_court", "宮廷深長", "court deep", "深、穩、宮廷", "deep, steady, courtly", "宮廷氣場下的深長換氣", "in a courtly register, deep long breaths", "courtly, deep breathing"],
    ["deep_street", "街頭深長", "street deep", "深、穩、街頭", "deep, steady, street", "街頭質感的深長換氣", "with street grit, deep long breaths", "street-cast, deep breathing"],
    ["deep_noir", "暗黑深長", "noir deep", "深、穩、暗黑", "deep, steady, noir", "暗調電影感的深長換氣", "in noir lighting, deep long breaths", "noir, deep breathing"],
    ["deep_soft", "柔光深長", "soft-light deep", "深、穩、柔光", "deep, steady, soft", "柔光下的深長換氣", "under soft light, deep long breaths", "soft-lit, deep breathing"],
    ["deep_epic", "史詩深長", "epic deep", "深、穩、史詩", "deep, steady, epic", "史詩尺度的深長換氣", "at epic scale, deep long breaths", "epic, deep breathing"],
    ["laugh_breath_court", "宮廷笑氣", "court laugh-breath", "笑、破、宮廷", "laugh, break, courtly", "宮廷氣場下的氣裡帶笑", "in a courtly register, laugh inside breath", "courtly, laugh-tinged breath"],
    ["laugh_breath_street", "街頭笑氣", "street laugh-breath", "笑、破、街頭", "laugh, break, street", "街頭質感的氣裡帶笑", "with street grit, laugh inside breath", "street-cast, laugh-tinged breath"],
    ["laugh_breath_noir", "暗黑笑氣", "noir laugh-breath", "笑、破、暗黑", "laugh, break, noir", "暗調電影感的氣裡帶笑", "in noir lighting, laugh inside breath", "noir, laugh-tinged breath"],
    ["laugh_breath_soft", "柔光笑氣", "soft-light laugh-breath", "笑、破、柔光", "laugh, break, soft", "柔光下的氣裡帶笑", "under soft light, laugh inside breath", "soft-lit, laugh-tinged breath"],
    ["laugh_breath_epic", "史詩笑氣", "epic laugh-breath", "笑、破、史詩", "laugh, break, epic", "史詩尺度的氣裡帶笑", "at epic scale, laugh inside breath", "epic, laugh-tinged breath"],
    ["cold_court", "宮廷冷白氣", "court cold vapor", "冷、白、宮廷", "cold, vapor, courtly", "宮廷氣場下的像呵出白氣", "in a courtly register, visible-cold feel", "courtly, cold vapor breath"],
    ["cold_street", "街頭冷白氣", "street cold vapor", "冷、白、街頭", "cold, vapor, street", "街頭質感的像呵出白氣", "with street grit, visible-cold feel", "street-cast, cold vapor breath"],
    ["cold_noir", "暗黑冷白氣", "noir cold vapor", "冷、白、暗黑", "cold, vapor, noir", "暗調電影感的像呵出白氣", "in noir lighting, visible-cold feel", "noir, cold vapor breath"],
    ["cold_soft", "柔光冷白氣", "soft-light cold vapor", "冷、白、柔光", "cold, vapor, soft", "柔光下的像呵出白氣", "under soft light, visible-cold feel", "soft-lit, cold vapor breath"],
    ["cold_epic", "史詩冷白氣", "epic cold vapor", "冷、白、史詩", "cold, vapor, epic", "史詩尺度的像呵出白氣", "at epic scale, visible-cold feel", "epic, cold vapor breath"],
    ["catch_court", "宮廷倒抽", "court catch", "倒抽、驚、宮廷", "catch, startle, courtly", "宮廷氣場下的句中倒抽", "in a courtly register, mid-line catch", "courtly, catch-breath"],
    ["catch_street", "街頭倒抽", "street catch", "倒抽、驚、街頭", "catch, startle, street", "街頭質感的句中倒抽", "with street grit, mid-line catch", "street-cast, catch-breath"],
    ["catch_noir", "暗黑倒抽", "noir catch", "倒抽、驚、暗黑", "catch, startle, noir", "暗調電影感的句中倒抽", "in noir lighting, mid-line catch", "noir, catch-breath"],
    ["catch_soft", "柔光倒抽", "soft-light catch", "倒抽、驚、柔光", "catch, startle, soft", "柔光下的句中倒抽", "under soft light, mid-line catch", "soft-lit, catch-breath"],
    ["catch_epic", "史詩倒抽", "epic catch", "倒抽、驚、史詩", "catch, startle, epic", "史詩尺度的句中倒抽", "at epic scale, mid-line catch", "epic, catch-breath"],
    ["smoke_court", "宮廷煙嗓換氣", "court smoke breath", "煙、慢、宮廷", "smoke, slow, courtly", "宮廷氣場下的像煙的慢換", "in a courtly register, slow smoky breath", "courtly, smoky breath"],
    ["smoke_street", "街頭煙嗓換氣", "street smoke breath", "煙、慢、街頭", "smoke, slow, street", "街頭質感的像煙的慢換", "with street grit, slow smoky breath", "street-cast, smoky breath"],
    ["smoke_noir", "暗黑煙嗓換氣", "noir smoke breath", "煙、慢、暗黑", "smoke, slow, noir", "暗調電影感的像煙的慢換", "in noir lighting, slow smoky breath", "noir, smoky breath"],
    ["smoke_soft", "柔光煙嗓換氣", "soft-light smoke breath", "煙、慢、柔光", "smoke, slow, soft", "柔光下的像煙的慢換", "under soft light, slow smoky breath", "soft-lit, smoky breath"],
    ["smoke_epic", "史詩煙嗓換氣", "epic smoke breath", "煙、慢、史詩", "smoke, slow, epic", "史詩尺度的像煙的慢換", "at epic scale, slow smoky breath", "epic, smoky breath"]
  ],
    accent: [
    ["neutral_court", "宮廷中性普通", "court neutral", "中性、淨、宮廷", "neutral, clean, courtly", "宮廷氣場下的無明顯地域", "in a courtly register, no strong regional", "courtly, neutral accent"],
    ["neutral_street", "街頭中性普通", "street neutral", "中性、淨、街頭", "neutral, clean, street", "街頭質感的無明顯地域", "with street grit, no strong regional", "street-cast, neutral accent"],
    ["neutral_noir", "暗黑中性普通", "noir neutral", "中性、淨、暗黑", "neutral, clean, noir", "暗調電影感的無明顯地域", "in noir lighting, no strong regional", "noir, neutral accent"],
    ["neutral_soft", "柔光中性普通", "soft-light neutral", "中性、淨、柔光", "neutral, clean, soft", "柔光下的無明顯地域", "under soft light, no strong regional", "soft-lit, neutral accent"],
    ["neutral_epic", "史詩中性普通", "epic neutral", "中性、淨、史詩", "neutral, clean, epic", "史詩尺度的無明顯地域", "at epic scale, no strong regional", "epic, neutral accent"],
    ["cantonese_base_court", "宮廷粵語底", "court Cantonese base", "粵、底、宮廷", "Cantonese, base, courtly", "宮廷氣場下的粵語節奏底", "in a courtly register, Cantonese rhythm base", "courtly, Cantonese-based accent"],
    ["cantonese_base_street", "街頭粵語底", "street Cantonese base", "粵、底、街頭", "Cantonese, base, street", "街頭質感的粵語節奏底", "with street grit, Cantonese rhythm base", "street-cast, Cantonese-based accent"],
    ["cantonese_base_noir", "暗黑粵語底", "noir Cantonese base", "粵、底、暗黑", "Cantonese, base, noir", "暗調電影感的粵語節奏底", "in noir lighting, Cantonese rhythm base", "noir, Cantonese-based accent"],
    ["cantonese_base_soft", "柔光粵語底", "soft-light Cantonese base", "粵、底、柔光", "Cantonese, base, soft", "柔光下的粵語節奏底", "under soft light, Cantonese rhythm base", "soft-lit, Cantonese-based accent"],
    ["cantonese_base_epic", "史詩粵語底", "epic Cantonese base", "粵、底、史詩", "Cantonese, base, epic", "史詩尺度的粵語節奏底", "at epic scale, Cantonese rhythm base", "epic, Cantonese-based accent"],
    ["mandarin_std_court", "宮廷普通話標準", "court standard Mandarin", "普、標、宮廷", "Mandarin, standard, courtly", "宮廷氣場下的標準普通話", "in a courtly register, standard Mandarin", "courtly, standard Mandarin accent"],
    ["mandarin_std_street", "街頭普通話標準", "street standard Mandarin", "普、標、街頭", "Mandarin, standard, street", "街頭質感的標準普通話", "with street grit, standard Mandarin", "street-cast, standard Mandarin accent"],
    ["mandarin_std_noir", "暗黑普通話標準", "noir standard Mandarin", "普、標、暗黑", "Mandarin, standard, noir", "暗調電影感的標準普通話", "in noir lighting, standard Mandarin", "noir, standard Mandarin accent"],
    ["mandarin_std_soft", "柔光普通話標準", "soft-light standard Mandarin", "普、標、柔光", "Mandarin, standard, soft", "柔光下的標準普通話", "under soft light, standard Mandarin", "soft-lit, standard Mandarin accent"],
    ["mandarin_std_epic", "史詩普通話標準", "epic standard Mandarin", "普、標、史詩", "Mandarin, standard, epic", "史詩尺度的標準普通話", "at epic scale, standard Mandarin", "epic, standard Mandarin accent"],
    ["english_light_court", "宮廷輕英語腔", "court light English", "英、輕、宮廷", "English, light, courtly", "宮廷氣場下的輕英語痕跡", "in a courtly register, light English color", "courtly, light English accent"],
    ["english_light_street", "街頭輕英語腔", "street light English", "英、輕、街頭", "English, light, street", "街頭質感的輕英語痕跡", "with street grit, light English color", "street-cast, light English accent"],
    ["english_light_noir", "暗黑輕英語腔", "noir light English", "英、輕、暗黑", "English, light, noir", "暗調電影感的輕英語痕跡", "in noir lighting, light English color", "noir, light English accent"],
    ["english_light_soft", "柔光輕英語腔", "soft-light light English", "英、輕、柔光", "English, light, soft", "柔光下的輕英語痕跡", "under soft light, light English color", "soft-lit, light English accent"],
    ["english_light_epic", "史詩輕英語腔", "epic light English", "英、輕、史詩", "English, light, epic", "史詩尺度的輕英語痕跡", "at epic scale, light English color", "epic, light English accent"],
    ["jp_light_court", "宮廷輕日語腔", "court light Japanese", "日、輕、宮廷", "Japanese, light, courtly", "宮廷氣場下的輕日語痕跡", "in a courtly register, light Japanese color", "courtly, light Japanese accent"],
    ["jp_light_street", "街頭輕日語腔", "street light Japanese", "日、輕、街頭", "Japanese, light, street", "街頭質感的輕日語痕跡", "with street grit, light Japanese color", "street-cast, light Japanese accent"],
    ["jp_light_noir", "暗黑輕日語腔", "noir light Japanese", "日、輕、暗黑", "Japanese, light, noir", "暗調電影感的輕日語痕跡", "in noir lighting, light Japanese color", "noir, light Japanese accent"],
    ["jp_light_soft", "柔光輕日語腔", "soft-light light Japanese", "日、輕、柔光", "Japanese, light, soft", "柔光下的輕日語痕跡", "under soft light, light Japanese color", "soft-lit, light Japanese accent"],
    ["jp_light_epic", "史詩輕日語腔", "epic light Japanese", "日、輕、史詩", "Japanese, light, epic", "史詩尺度的輕日語痕跡", "at epic scale, light Japanese color", "epic, light Japanese accent"],
    ["rural_court", "宮廷鄉土", "court rural", "鄉、樸、宮廷", "rural, plain, courtly", "宮廷氣場下的帶鄉土", "in a courtly register, rural coloring", "courtly, rural accent"],
    ["rural_street", "街頭鄉土", "street rural", "鄉、樸、街頭", "rural, plain, street", "街頭質感的帶鄉土", "with street grit, rural coloring", "street-cast, rural accent"],
    ["rural_noir", "暗黑鄉土", "noir rural", "鄉、樸、暗黑", "rural, plain, noir", "暗調電影感的帶鄉土", "in noir lighting, rural coloring", "noir, rural accent"],
    ["rural_soft", "柔光鄉土", "soft-light rural", "鄉、樸、柔光", "rural, plain, soft", "柔光下的帶鄉土", "under soft light, rural coloring", "soft-lit, rural accent"],
    ["rural_epic", "史詩鄉土", "epic rural", "鄉、樸、史詩", "rural, plain, epic", "史詩尺度的帶鄉土", "at epic scale, rural coloring", "epic, rural accent"],
    ["aristocrat_court", "宮廷貴族腔", "court aristocratic", "貴、圓、宮廷", "noble, round, courtly", "宮廷氣場下的圓而貴", "in a courtly register, rounded noble", "courtly, aristocratic accent"],
    ["aristocrat_street", "街頭貴族腔", "street aristocratic", "貴、圓、街頭", "noble, round, street", "街頭質感的圓而貴", "with street grit, rounded noble", "street-cast, aristocratic accent"],
    ["aristocrat_noir", "暗黑貴族腔", "noir aristocratic", "貴、圓、暗黑", "noble, round, noir", "暗調電影感的圓而貴", "in noir lighting, rounded noble", "noir, aristocratic accent"],
    ["aristocrat_soft", "柔光貴族腔", "soft-light aristocratic", "貴、圓、柔光", "noble, round, soft", "柔光下的圓而貴", "under soft light, rounded noble", "soft-lit, aristocratic accent"],
    ["aristocrat_epic", "史詩貴族腔", "epic aristocratic", "貴、圓、史詩", "noble, round, epic", "史詩尺度的圓而貴", "at epic scale, rounded noble", "epic, aristocratic accent"],
    ["street_slang_court", "宮廷街腔", "court street slang", "街、快、宮廷", "street, fast, courtly", "宮廷氣場下的街頭用詞腔", "in a courtly register, street slang color", "courtly, street-slang accent"],
    ["street_slang_street", "街頭街腔", "street street slang", "街、快、街頭", "street, fast, street", "街頭質感的街頭用詞腔", "with street grit, street slang color", "street-cast, street-slang accent"],
    ["street_slang_noir", "暗黑街腔", "noir street slang", "街、快、暗黑", "street, fast, noir", "暗調電影感的街頭用詞腔", "in noir lighting, street slang color", "noir, street-slang accent"],
    ["street_slang_soft", "柔光街腔", "soft-light street slang", "街、快、柔光", "street, fast, soft", "柔光下的街頭用詞腔", "under soft light, street slang color", "soft-lit, street-slang accent"],
    ["street_slang_epic", "史詩街腔", "epic street slang", "街、快、史詩", "street, fast, epic", "史詩尺度的街頭用詞腔", "at epic scale, street slang color", "epic, street-slang accent"],
    ["period_classic_court", "宮廷古白腔", "court period classical", "古、文、宮廷", "period, literary, courtly", "宮廷氣場下的帶文言節奏", "in a courtly register, literary period rhythm", "courtly, classical period accent"],
    ["period_classic_street", "街頭古白腔", "street period classical", "古、文、街頭", "period, literary, street", "街頭質感的帶文言節奏", "with street grit, literary period rhythm", "street-cast, classical period accent"],
    ["period_classic_noir", "暗黑古白腔", "noir period classical", "古、文、暗黑", "period, literary, noir", "暗調電影感的帶文言節奏", "in noir lighting, literary period rhythm", "noir, classical period accent"],
    ["period_classic_soft", "柔光古白腔", "soft-light period classical", "古、文、柔光", "period, literary, soft", "柔光下的帶文言節奏", "under soft light, literary period rhythm", "soft-lit, classical period accent"],
    ["period_classic_epic", "史詩古白腔", "epic period classical", "古、文、史詩", "period, literary, epic", "史詩尺度的帶文言節奏", "at epic scale, literary period rhythm", "epic, classical period accent"],
    ["foreign_mix_court", "宮廷混血腔", "court mixed foreign", "混、隙、宮廷", "mixed, gap, courtly", "宮廷氣場下的兩種語言縫", "in a courtly register, two-language seam", "courtly, mixed foreign accent"],
    ["foreign_mix_street", "街頭混血腔", "street mixed foreign", "混、隙、街頭", "mixed, gap, street", "街頭質感的兩種語言縫", "with street grit, two-language seam", "street-cast, mixed foreign accent"],
    ["foreign_mix_noir", "暗黑混血腔", "noir mixed foreign", "混、隙、暗黑", "mixed, gap, noir", "暗調電影感的兩種語言縫", "in noir lighting, two-language seam", "noir, mixed foreign accent"],
    ["foreign_mix_soft", "柔光混血腔", "soft-light mixed foreign", "混、隙、柔光", "mixed, gap, soft", "柔光下的兩種語言縫", "under soft light, two-language seam", "soft-lit, mixed foreign accent"],
    ["foreign_mix_epic", "史詩混血腔", "epic mixed foreign", "混、隙、史詩", "mixed, gap, epic", "史詩尺度的兩種語言縫", "at epic scale, two-language seam", "epic, mixed foreign accent"]
  ]
  }
})
