import type { PromptCopyTable } from './keys'

export const arPromptCopy: PromptCopyTable = {
  "speechLock.named": "SPEECH LOCK · الشخصية «{{who}}»: الكلام المسموع ومزامنة الشفاه يجب أن تكون {{primaryName}} ({{primary}}) فقط. لا تتحدث {{forbid}} ولا أي لغة أخرى. أبقِ اللغة نفسها في كل مقطع. لا تترجم الحوار.",
  "speechLock.unnamed": "SPEECH LOCK · الشخصيات المتحدثة: الكلام المسموع ومزامنة الشفاه يجب أن تكون {{primaryName}} ({{primary}}) فقط. لا تتحدث {{forbid}} ولا أي لغة أخرى. أبقِ اللغة نفسها في كل مقطع. لا تترجم الحوار.",
  "speechLock.namedMulti": "SPEECH LOCK · الشخصية «{{who}}»: الكلام المسموع ومزامنة الشفاه يجب أن تكون {{primaryName}} ({{primary}}). لغات أخرى فقط إذا كان سطر النص بهذه اللغة أصلًا: {{extras}}. لغة ثالثة ممنوعة. لا تبدّل اللغة بين المقاطع. لا تنتقل إلى {{forbid}}. لا تترجم.",
  "speechLock.unnamedMulti": "SPEECH LOCK · الشخصيات المتحدثة: الكلام المسموع ومزامنة الشفاه يجب أن تكون {{primaryName}} ({{primary}}). لغات أخرى فقط إذا كان سطر النص بهذه اللغة أصلًا: {{extras}}. لغة ثالثة ممنوعة. لا تبدّل اللغة بين المقاطع. لا تنتقل إلى {{forbid}}. لا تترجم.",
  "storyBeats.system": "You write short-drama TIMELINE BEATS for AI video.\nEach beat = ONE short clip screenplay (not a single spoken line).\nA beat MUST include rich performance content: mood, atmosphere, actions, expressions, optional camera/sfx, and zero or more spoken dialogue lines (1–4 lines common).\nReturn ONLY a JSON array (no fences). Each item shape:\n{\"characterName\":\"…\",\"characterNames\":[\"…\"],\"sceneHint\":\"…\",\"propName\":\"…\",\"mood\":\"…\",\"atmosphere\":\"…\",\"camera\":\"…\",\"sfx\":\"…\",\"units\":[{\"type\":\"action\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"expression\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"dialogue\",\"who\":\"…\",\"line\":\"…\",\"tone\":\"…\",\"parenthetical\":\"…\"},{\"type\":\"note\",\"text\":\"…\"}]}\nRules:\n- units.type dialogue.line = ONLY words the character speaks (no stage directions inside line).\n- Put physical business in action; face/micro-performance in expression; delivery in tone/parenthetical.\n- Multiple dialogue units in one beat are encouraged when the clip has a short exchange or self-talk.\n- Pure action beats (no dialogue) are allowed.\n- Write 4–8 beats. Use only cast names provided.\n- Prefer conflict, clear visual action, filmable detail.\n- Stay faithful to the title, style, cast, and scenes provided; if thin, invent freely within that cast/world.\n- SPEECH: write each dialogue.line in that speaker's primary spoken language from the cast list. Do not switch languages between beats. Do not translate lines unless that is the character's listed language.",
  "storyBeats.userLead": "أنشئ إيقاعات سيناريو المقطع باستخدام كل الطاقم والمشاهد والإكسسوارات والأسلوب والفكرة أدناه.",
  "storyBeats.eachBeat": "كل إيقاع يحتاج مزاجًا + أجواء + أفعال/تعبيرات + حوارًا اختياريًا.",
  "storyBeats.story": "القصة: {{title}}",
  "storyBeats.style": "الأسلوب: {{style}}",
  "storyBeats.userDir": "توجيه المستخدم: {{idea}}",
  "storyBeats.cast": "الطاقم:",
  "storyBeats.scenes": "المشاهد:",
  "storyBeats.props": "الإكسسوارات: {{props}}",
  "storyBeats.returnJson": "أرجع مصفوفة JSON للإيقاعات فقط.",
  "storyBeats.noCast": "(لا طاقم)",
  "storyBeats.noScenes": "(لا مشاهد — اخترع الأماكن في sceneHint)",
  "storyBeats.none": "(لا شيء)",
  "videoPolish.system": "You write ONE final image-to-video prompt for a short-drama AI video model.\nReturn ONLY the prompt text — no markdown fences, no title, no explanation.\nRules:\n- Write the director prompt in the user interface language; keep character names and required dialogue language codes clear.\n- Person still: IDENTITY LOCK (face, hair, body, wardrobe, colors). Location plate: SPACE LOCK (architecture, materials, layout, signage, palette) — empty set preferred; no new cast faces.\n- Use ALL provided profile / soul / beat / location facts that affect look, motion, speech, or atmosphere; ignore empty fields.\n- Invent only what is needed to complete a filmable clip from the materials and seed — do not import a fixed sample world, Demo story, or facts not present in materials/seed.\n- Condense long soul.md into actionable performance + identity beats; do not dump the whole bible verbatim.\n- Duration 6–10s; continuous action; cinematic; no text overlays, logos, watermarks, or extra unrelated people.\n- Anatomically correct humans unless the script requires otherwise (two hands, two arms, two legs).\n- If multi-character, keep each listed subject consistent; primary focus first.\n- If HARD RULES appear in materials, keep them and place them at the end of your output (highest priority).\n- SPEECH LOCK is mandatory: never drop, rewrite, or translate it. Expand language codes to full names. Every clip must use the character primary spoken language; do not switch languages between clips; do not translate dialogue lines.\n- Director revision may refine style/action but must NOT violate HARD RULES.",
  "videoPolish.hardRulesKeep": "HARD RULES (HIGHEST PRIORITY — keep every line; object labels like [Character · Name] must stay). Place the full HARD RULES block at the END of your output. Do not weaken, drop, or reassign rules.",
  "clip.task": "المهمة: مقطع خط زمني لدراما قصيرة (صورة إلى فيديو).",
  "clip.hasRef": "A reference still may be attached — lock identity/location continuity to it when relevant.",
  "clip.characters": "الشخصيات:",
  "clip.scene": "المشهد:",
  "clip.prop": "الإكسسوار:",
  "clip.action": "دليل الحركة:",
  "clip.beat": "الإيقاع / الحوار:",
  "clip.prev": "استمرارية المقطع السابق:",
  "clip.revision": "مراجعة المخرج (إلزامية):",
  "clip.templateDraft": "مسودة القالب (حسّنها):",
  "intro.task": "المهمة: مقطع تعريف للتمثيل (صورة إلى فيديو).",
  "intro.hasRef": "Reference still is attached to the video API — lock identity to that image.",
  "intro.noRef": "No reference still path in this text; still lock to profile appearance/costume.",
  "intro.dossier": "ملف الشخصية:",
  "intro.templateDraft": "مسودة القالب (حسّنها؛ لا تتجاهل الملف):",
  "common.durationAspect": "المدة: {{seconds}} ث. النسبة: {{aspect}}.",
  "common.templateDraft": "مسودة القالب:",
  "improve.mode": "وضع التحسين: اددمج كل المصادر في نتيجة كاملة. أبقِ الهوية ما لم يطلب المستخدم التغيير.",
  "improve.draftDefault": "حقول النموذج الحالية:",
  "improve.userRequest": "طلب التحسين (فارغ = لمّع وادمج الكل):",
  "improve.emptyDefault": "(لمّع كل الحقول للاستمرارية)",
  "improve.createDefault": "فكرة / اتجاه:",
  "improve.explicitContext": "سياق صريح لهذا الطلب فقط (استمرارية؛ لا تستورد عالماً نموذجياً آخر):",
  "improve.storyTitle": "العنوان: {{title}}",
  "improve.styleNote": "ملاحظة الأسلوب: {{style}}",
  "improve.closingDefault": "أخرج النتيجة الكاملة الآن.",
  "storyMeta.system": "أنت شورنر دراما قصيرة. اكتب إنجيلًا بصريًا وقواعد صارمة. JSON فقط.",
  "storyMeta.draftLabel": "حقول القصة الحالية:",
  "storyMeta.createLabel": "فكرة / عنوان القصة:",
  "storyMeta.emptyPolish": "(لمّع الإنجيل البصري وhardRules)",
  "storyMeta.closing": "JSON فقط: {\"styleNote\":\"…\",\"hardRules\":\"…\"}. المفتاحان إلزاميان.",
  "storyMeta.contextLabel": "السياق (طاقم / مشاهد / إكسسوارات):",
  "character.system": "أنت مصمم شخصيات. JSON واحد فقط. spokenLanguages = مصفوفة BCP-47.",
  "character.draftLabel": "حقول الملف الحالية:",
  "character.soulLabel": "soul.md / الإنجيل المرتبط:",
  "character.createLabel": "فكرة الشخصية:",
  "character.emptyPolish": "(لمّع وادمج soul)",
  "character.closing": "JSON كامل الآن. المفاتيح: {{keys}}.",
  "scene.system": "أنت مصمم مواقع. إنجيل المكان + سكربت هذا المشهد. JSON فقط.",
  "scene.draftLabel": "حقول المشهد الحالية:",
  "scene.charsLabel": "شخصيات القصة:",
  "scene.propsLabel": "إكسسوارات القصة:",
  "scene.priorLabel": "مشاهد سابقة (استمرارية):",
  "scene.createLabel": "فكرة المشهد:",
  "scene.emptyPolish": "(لمّع المكان والسكربت)",
  "scene.closing": "JSON كامل. المفاتيح: {{keys}}.",
  "prop.system": "أنت مصمم إكسسوارات. JSON واحد. المظهر والخامة والحالة واضحة.",
  "prop.draftLabel": "حقول الإكسسوار الحالية:",
  "prop.createLabel": "فكرة الإكسسوار:",
  "prop.emptyPolish": "(لمّع مظهر الإكسسوار)",
  "prop.closing": "JSON كامل. المفاتيح: {{keys}}.",
  "prop.fallbackName": "إكسسوار",
  "action.system": "أنت مخرج حركة. JSON صالح فقط. الجسد والإيقاع والوزن والمسارات.",
  "action.storyContext": "سياق القصة (اختياري): {{title}}",
  "action.styleNote": "ملاحظة الأسلوب: {{style}}",
  "action.existingDraft": "مسودة موجودة للصقل:",
  "action.userIdea": "فكرة المستخدم: {{idea}}",
  "action.closing": "JSON فقط. المفاتيح: {{keys}}.",
  "profile.mustEveryKey": "يجب إخراج كل مفتاح في القائمة: {{keys}}.",
  "profile.valuesAreStrings": "كل قيمة يجب أن تكون سلسلة JSON. فارغة فقط إن جُهلت.",
  "profile.visualTagsRule": "visualTags: سلسلة مفصولة بفواصل. ليست مصفوفة JSON.",
  "profile.fillConcrete": "املأ بتفاصيل ملموسة.",
  "common.rules": "القواعد:",
  "common.none": "(لا شيء)",
  "intro.soul": "soul.md (مصدر الأداء/الهوية):\n{{soul}}",
  "intro.matchBible": "(اتبع لغة إنجيل الشخصية)",
  "invent.sources": "مصادر الحقيقة بالترتيب: (1) الفكرة/الطلب، (2) النموذج، (3) الإضافات فقط إن وردت في هذا الأمر، (4) الصورة المرفقة.",
  "invent.create": "وضع الإنشاء: ابتكر بحرية من الفكرة/الصورة؛ لا تترك مفاتيح إلزامية فارغة.",
  "invent.improve": "وضع التحسين: لمّع المسودة؛ لا تغيّر الهوية إلا بطلب صريح.",
  "invent.noImport": "لا تستورد هوية أو حبكة أو طقسًا أو مهنة أو مكانًا أو عصرًا أو أسلوبًا مما ليس في هذا الأمر.",
  "invent.storyBlock": "كتلة القصة/الأسلوب للاستمرارية فقط؛ لا تطغَ على الفكرة الصريحة.",
  "character.keysLead": "كائن JSON واحد فقط بالمفاتيح: {{keys}}",
  "character.ruleSpoken": "spokenLanguages: مصفوفة BCP-47 للغات التي يتكلمها. [] إن كان صامتًا.",
  "character.ruleIdentity": "حافظ على الهوية عبر الألواح والفيديو.",
  "character.fallbackPersonality": "حضور دافئ وواضح",
  "character.fallbackManner": "إيماءات دقيقة طبيعية",
  "character.fallbackVoice": "صوت واضح",
  "scene.keysLead": "كائن JSON واحد فقط بالمفاتيح: {{keys}}",
  "scene.suggestLead": "اقترح موقعًا جاهزًا كمشهد رقم {{n}} لقصة «{{title}}».",
  "scene.suggestPlotFocus": "بؤرة الحبكة: {{label}}",
  "scene.suggestStyle": "الأسلوب: {{style}}",
  "scene.suggestExisting": "مواقع موجودة: {{titles}}",
  "scene.suggestChars": "شخصيات (سياق):",
  "scene.suggestProps": "إكسسوارات (سياق):",
  "scene.suggestSegment": "تفاصيل المقطع المختار:",
  "scene.suggestBeats": "مشاهد / نبضات:",
  "scene.suggestClosing": "أرجع JSON المشهد كاملًا. صمّم مكانًا مستقلًا قابلًا لإعادة الاستخدام.",
  "scene.fallbackName": "موقع",
  "scene.fallbackMood": "جو سينمائي",
  "scene.fallbackLighting": "يطابق اللقطة",
  "scene.fallbackCamera": "اقتراب تأسيس لطيف أو تحريك بطيء",
  "scene.ideaFromImage": "املأ ملف الموقع كاملًا من الصورة المرفقة.",
  "scene.polishIdea": "لمّع",
  "prop.keysLead": "كائن JSON واحد فقط بالمفاتيح: {{keys}}",
  "action.fieldsLead": "الحقول: {{keys}}.",
  "soul.system": "تكتب soul.md للإنتاج. ماركداون كامل فقط. احترم spokenLanguages. لغة الواجهة.",
  "soul.improveMode": "وضع التحسين: ادمج الملف + soul القائم في soul.md كامل.",
  "soul.createMode": "اكتب soul.md كاملًا من هذا الملف (لا تستبدل الشخص):",
  "soul.profileFields": "حقول الملف:",
  "soul.existing": "soul.md القائم (ادمج؛ لا ترمِ التفصيل المفيد):",
  "soul.userRequest": "طلب المستخدم: {{request}}",
  "soul.extraContext": "سياق إضافي (إن نفع؛ الملف يغلب):",
  "soul.returnOnly": "أرجع ماركداون soul.md فقط.",
  "wardrobe.system": "أنت مستشار أزياء. JSON واحد. artStyle من: {{styleIds}}. خامات وظل واضحة. لا تُجنّس القُصّر.",
  "wardrobe.improveMode": "وضع التحسين / الاقتراح: استخدم كل الحقول والسياق.",
  "wardrobe.characterForm": "الشخصية (النموذج الكامل):",
  "wardrobe.soulExcerpt": "مقتطف soul.md:\n{{soul}}",
  "wardrobe.userRequest": "الطلب: {{request}}",
  "wardrobe.storyContext": "سياق الإنتاج (إن وُجد؛ لا تخترع عالمًا آخر):",
  "wardrobe.style": "الأسلوب: {{style}}",
  "wardrobe.segment": "المقطع المختار: {{label}}",
  "wardrobe.sceneContext": "المشهد / النبضة:",
  "wardrobe.noScenes": "(لا مشاهد بعد)",
  "wardrobe.proposeNew": "اقترح مظهرًا جديدًا يناسب الحبكة (لا تكرر).",
  "fill.system": "تُكمل الحقول الفارغة. JSON بهذه المفاتيح فقط: {{keys}}. كل قيمة سلسلة غير فارغة. ليست مصفوفة.",
  "fill.userPartial": "ملف جزئي (لا تناقض):",
  "fill.userOnly": "املأ هذه المفاتيح فقط: {{keys}}.",
  "fill.userReturn": "JSON بتلك المفاتيح فقط؛ قيم غير فارغة.",
  "imageGen.multiRef": "{{n}} لقطات إضافية: الأولى هي القاعدة؛ حافظ على الهوية في الكل.",
  "residual.sceneLink": "المشهد {{n}}: {{short}}",
  "residual.beatSegment": "نبضة {{n}} · {{who}}{{tail}}",
  "residual.unknown": "غير محدد",
  "residual.story": "قصة",
  "beat.mood": "[MOOD] {{text}}",
  "beat.atmo": "[ATMO] {{text}}",
  "beat.camera": "[CAMERA] {{text}}",
  "beat.sfx": "[SFX] {{text}}",
  "beat.action": "[ACTION] {{text}}",
  "beat.actionWho": "[ACTION|{{who}}] {{text}}",
  "beat.expr": "[EXPR] {{text}}",
  "beat.exprWho": "[EXPR|{{who}}] {{text}}",
  "beat.dialogue": "[DIALOGUE|{{who}}] {{body}}",
  "beat.dialogueTone": "[DIALOGUE|{{who}}|{{tone}}] {{body}}",
  "beat.whoUnknown": "?",
  "beat.template": "[MOOD] tense, hesitant\n[ATMO] door-gap warm light; rain on ground\n[CAMERA] medium shot, push to hands\n[SFX] rain, fabric rustle\n[ACTION|Name] removes helmet; stares at the door light; hand into jacket pocket\n[EXPR|Name] furrowed brow, breath catches\n[DIALOGUE|Name|low, hoarse] Raining again…\n[DIALOGUE|Name|aside] (beat) Are you… still there?",
  "vision.preamble": "لقطة مرجعية مرفقة. املأ كل حقول هذا {{what}} أساسًا من الصورة.",
  "vision.character": "الهوية (الاسم، المظهر، الزي، العمر، الجنس، الوسوم)",
  "vision.scene": "الموقع (العنوان، الوصف، الضوء، المزاج، الديكور، الوسوم)",
  "vision.prop": "الإكسسوار (الاسم، الوصف، الخامة، الحجم، الحالة، الوسوم)",
  "vision.action": "الحركة (الاسم، الوصف، الإيقاع، القصد، الكاميرا، الوسوم)",
  "vision.costume": "الزي (الاسم، وصف كامل)",
  "still.header": "SINGLE KEYFRAME STILL for short-drama video continuity (not a multi-panel sheet). Produce one cinematic hero frame that matches the planned shot below. No text, logos, watermarks, UI chrome. Sharp, production-ready.",
  "still.revision": "تحسين المستخدم لهذه اللقطة (إلزامي): {{notes}}",
  "still.regenTask": "المهمة: نقّح أمر المخرج image-to-video وأبقِه صالحًا كموجز إطار مفتاحي.",
  "still.userImprove": "طلب التحسين:\n{{notes}}",
  "still.currentPrompt": "الأمر المهني الحالي:",
  "still.hardRules": "HARD RULES (في النهاية؛ لا تُضعفها):",
  "mediaGen.writeOne": "اكتب أمر صورة نهائي واحد للقطة دراما قصيرة.",
  "mediaGen.returnOnly": "نص الأمر فقط — بلا ماركداون.",
  "mediaGen.singleComposite": "صف صورة مركّبة واحدة.",
  "mediaGen.lockRefs": "الصور المرفقة حقيقة بصرية بترتيب Ref#. لا تخترع شخصًا أو متجرًا أو غرضًا آخر.",
  "mediaGen.videoSystem": "تكتب أوامر مخرج image-to-video.",
  "mediaGen.videoMerge": "ادمج المواد في أمر فيديو واحد.",
  "mediaGen.videoInclude": "ضمّن: قفل الهوية، الكاميرا، الأداء/الحوار، الإيقاع، الضوء.",
  "mediaGen.videoFacts": "حقائق المواد وseed فقط. لا Demo.",
  "mediaGen.videoNoSwap": "مع المراجع لا تبدّل الممثل أو الموقع أو الإكسسوار.",
  "mediaGen.videoHardRules": "HARD RULES في النهاية إن وُجدت.",
  "mediaGen.imageSystem": "أنت مخرج أوامر الصورة.",
  "mediaGen.imageMergeStills": "ادمج المواد واللقطات في أمر صورة واحد.",
  "mediaGen.imageMergeText": "ادمج النصوص في أمر صورة واحد.",
  "mediaGen.imagePriority": "الأولوية: الوجوه/الأزياء/الأماكن/الإكسسوار من الصور.",
  "mediaGen.imageNoSwap": "لا تستبدل بمشهور أو موقع غريب إن وُجدت لقطات الطاقم.",
  "mediaGen.imageFacts": "حقائق المواد وseed فقط.",
  "mediaGen.imageLayout": "إن تعددت الألواح فاحفظ العدد الدقيق.",
  "mediaGen.imagePackage": "إن وُجد LAYOUT يجب تنفيذ ذلك التخطيط حرفيًا.",
  "mediaGen.imageHardRules": "HARD RULES في النهاية إن وُجدت.",
  "mediaGen.directorFallback": "صورة-إلى-فيديو: حرّك هذا الإطار. اقفل الهوية والزي والموقع والإطار.",
  "mediaGen.directorFallbackCam": "كاميرا وأداء واضحان؛ بلا ترجمة أو علامة مائية.",
  "charIntro.task": "صورة-إلى-فيديو: حرّك الشخص نفسه في تقديم قصير.",
  "charIntro.identityLock": "قفل الهوية: الوجه والشعر والجسد والعمر والزي والألوان نفسها.",
  "charIntro.personality": "الشخصية / الحضور: {{personality}}.",
  "charIntro.backstory": "الخلفية: {{backstory}}.",
  "charIntro.relationships": "العلاقات: {{relationships}}.",
  "charIntro.soul": "مقتطف soul (مصدر الأداء): {{soul}}",
  "charIntro.performance": "الأداء: اقتراب لطيف أو كاميرا محمولة؛ ينظر إلى العدسة؛ {{manner}}.",
  "charIntro.speech": "الكلام: الفم يتحرك كتقديم قصير؛ الصوت: {{voice}}.",
  "charIntro.beat": "ثبات طبيعي → ابتسامة أو إيماءة → إشارة قصيرة → ثبات.",
  "charIntro.lighting": "ضوء يطابق اللقطة؛ بلا نص أو شعار أو أشخاص إضافيين.",
  "charIntro.duration": "يناسب تقديمًا من 6–10 ثوانٍ.",
  "sceneIntro.task": "صورة-إلى-فيديو: حرّك المكان نفسه كلقطة تأسيس.",
  "sceneIntro.spaceLock": "قفل المكان: العمارة والخامات واللافتات والمخطط واللون نفسها.",
  "sceneIntro.name": "اسم المكان: {{name}}.",
  "sceneIntro.place": "الوصف: {{place}}.",
  "sceneIntro.spaceType": "نوع الفضاء: {{type}}.",
  "sceneIntro.time": "وقت اليوم: {{time}}.",
  "sceneIntro.weather": "الطقس: {{weather}}.",
  "sceneIntro.moodLight": "المزاج: {{mood}}. الإضاءة: {{lighting}}.",
  "sceneIntro.palette": "لوحة الألوان: {{palette}}.",
  "sceneIntro.setDressing": "الديكور: {{set}}.",
  "sceneIntro.tags": "وسوم بصرية: {{tags}}.",
  "sceneIntro.art": "الأسلوب: {{art}}.",
  "sceneIntro.ambient": "الجو (بلا نص واجهة): {{sound}}.",
  "sceneIntro.scriptCue": "إشارة النبضة (جو فقط): {{cue}}.",
  "sceneIntro.camera": "الكاميرا: {{camera}}؛ مجموعة فارغة مفضلة؛ بلا وجوه أو شعارات جديدة.",
  "sceneIntro.beat": "تأسيس → حياة بيئية خفيفة → ثبات.",
  "sceneIntro.duration": "يناسب مقدمة موقع 6–10 ثوانٍ.",
  "propIntro.task": "صورة-إلى-فيديو: حرّك الإكسسوار نفسه كمقدمة بطل.",
  "propIntro.objectLock": "قفل الغرض: الظل والخامات والألوان والنقوش والتآكل نفسها.",
  "propIntro.name": "الاسم: {{name}}.",
  "propIntro.look": "المظهر: {{look}}.",
  "propIntro.material": "الخامة: {{material}}.",
  "propIntro.size": "الحجم: {{size}}.",
  "propIntro.condition": "الحالة: {{condition}}.",
  "propIntro.tags": "الوسوم: {{tags}}.",
  "propIntro.art": "الأسلوب: {{art}}.",
  "propIntro.camera": "مدار لطيف أو اقتراب بطيء على طاولة نظيفة؛ ضوء يطابق اللقطة.",
  "propIntro.beat": "ثبات → لمعان / دوران دقيق → ثبات.",
  "propIntro.noHands": "بلا أيدٍ أو وجوه جديدة إن لم تكن في اللقطة؛ بلا نص أو إكسسوار إضافي.",
  "propIntro.duration": "يناسب مقدمة إكسسوار 6–10 ثوانٍ.",
  "costumeIntro.task": "صورة-إلى-فيديو: حرّك المظهر نفسه كمقدمة زي.",
  "costumeIntro.wardrobeLock": "قفل الزي: الظل والأقمشة والألوان والطبقات والإكسسوار نفسها.",
  "costumeIntro.identityOrProduct": "إن وُجد شخص: اقفل الوجه/الجسد؛ إن كان مانيكان/بسط: إطار منتج.",
  "costumeIntro.name": "اسم المظهر: {{name}}.",
  "costumeIntro.desc": "الزي: {{look}}.",
  "costumeIntro.art": "الأسلوب: {{art}}.",
  "costumeIntro.camera": "اقتراب لطيف أو مدار؛ ضوء أزياء يطابق اللقطة.",
  "costumeIntro.beat": "ثبات → تدلي القماش / لمعان المعدن → ثبات.",
  "costumeIntro.forbid": "بلا وجوه جديدة أو نص أو شعار أو وضع إيروتيكي.",
  "costumeIntro.duration": "يناسب مقدمة زي 6–10 ثوانٍ.",
  "costumeIntro.fallbackName": "مظهر",
  "actionIntro.lead": "فيديو عرض الحركة «{{name}}».",
  "actionIntro.intention": "القصد: {{intention}}",
  "actionIntro.body": "الجسد/الإيقاع: {{body}}",
  "actionIntro.camera": "الكاميرا: {{camera}}",
  "actionIntro.closing": "حركة متصلة سينمائية بلا نص؛ اتبع الإطار المفتاحي.",
  "sceneIntroPolish.task": "المهمة: مقدمة موقع (صورة-إلى-فيديو).",
  "sceneIntroPolish.hasRef": "لقطة موقع مرفقة — اقفل هوية المكان.",
  "sceneIntroPolish.noRef": "لا لقطة؛ اقفل بإنجيل المكان.",
  "sceneIntroPolish.dossier": "ملف الموقع:",
  "sceneIntroPolish.scriptCue": "إشارة السكربت (جو فقط):\n{{script}}",
  "sceneIntroPolish.emptySet": "مجموعة فارغة؛ بلا وجوه جديدة. بلا نص أو شعار.",
  "propIntroPolish.task": "المهمة: مقدمة بطل الإكسسوار (صورة-إلى-فيديو).",
  "propIntroPolish.hasRef": "لقطة إكسسوار مرفقة — اقفل الغرض.",
  "propIntroPolish.noRef": "لا لقطة؛ اقفل بالملف.",
  "propIntroPolish.dossier": "ملف الإكسسوار:",
  "propIntroPolish.noHands": "بلا أيدٍ أو وجوه جديدة. بلا نص أو شعار.",
  "costumeIntroPolish.task": "المهمة: مقدمة زي (صورة-إلى-فيديو).",
  "costumeIntroPolish.hasRef": "لقطة مرفقة — شخص: هوية+زي؛ مانيكان: ظل وخامات.",
  "costumeIntroPolish.noRef": "لا لقطة؛ اقفل بالوصف.",
  "costumeIntroPolish.dossier": "ملف الزي:",
  "costumeIntroPolish.fabric": "تدلي خفيف؛ بلا وجوه جديدة أو نص.",
  "actionIntroPolish.task": "المهمة: مقدمة دليل حركة (صورة-إلى-فيديو).",
  "actionIntroPolish.hasRef": "لقطة مرفقة — اقفل هوية الأداء بذلك الإطار.",
  "actionIntroPolish.templateKeepRules": "مسودة القالب (حسّن؛ HARD RULES في النهاية):",
  "cover.posterLead": "ملصق / KEY ART احترافي 16:9. ليس نموذج واجهة. بلا نص أو شعار أو علامة مائية.",
  "cover.titleMood": "العنوان (مزاج فقط، لا تكتبه على الصورة): {{title}}.",
  "cover.styleBible": "إنجيل الأسلوب: {{style}}",
  "cover.extraDir": "اتجاه إضافي: {{idea}}",
  "cover.establishing": "إطار تأسيس مزاجي لغلاف المكتبة.",
  "cover.medium": "طابق الوسيط؛ ظل قوي.",
  "cover.editPrefix": "IMAGE EDIT: تكوين ملصق جديد. احتفظ بالهوية/المزاج. ",
  "cover.label": "غلاف القصة",
  "costumeFill.system": "أنت مصمم أزياء. JSON مضغوط فقط. إن وُجدت صورة فصف ذلك الزي بأمانة.",
  "costumeFill.idea": "الفكرة: {{idea}}",
  "costumeFill.polish": "لمّع مسودة الزي.",
  "costumeFill.required": "المفاتيح: name, description, artStyle, hardRules. النقص يُبطل.",
  "costumeFill.fallbackName": "مظهر",
  "segment.entireStory": "القصة كاملة (كل المشاهد)",
  "segment.noStory": "لم تُختر قصة (بيانات الشخصية فقط)",
  "vision.inventFromImage": "صف وابتكر ملف {{kind}} كاملًا من الصورة المرفقة.",
  "vision.polishAll": "لمّع وادمج كل الحقول",
  "story.untitled": "دراما قصيرة بلا عنوان"
}
