import type { PromptCopyTable } from './keys'

export const enPromptCopy: PromptCopyTable = {
  "speechLock.named": "Dialogue lock · Character \"{{who}}\": audible speech AND lip-sync MUST be {{primaryName}} ({{primary}}) only. Do not speak {{forbid}} or any other language. Keep the same speech language on every clip. Do not translate dialogue.",
  "speechLock.unnamed": "Dialogue lock · Speaking characters: audible speech AND lip-sync MUST be {{primaryName}} ({{primary}}) only. Do not speak {{forbid}} or any other language. Keep the same speech language on every clip. Do not translate dialogue.",
  "speechLock.namedMulti": "Dialogue lock · Character \"{{who}}\": audible speech AND lip-sync MUST be {{primaryName}} ({{primary}}). Other allowed languages ONLY if the written script line is already in that language: {{extras}}. Never invent a third language. Never switch languages between clips. Do not switch to {{forbid}}. Do not translate dialogue.",
  "speechLock.unnamedMulti": "Dialogue lock · Speaking characters: audible speech AND lip-sync MUST be {{primaryName}} ({{primary}}). Other allowed languages ONLY if the written script line is already in that language: {{extras}}. Never invent a third language. Never switch languages between clips. Do not switch to {{forbid}}. Do not translate dialogue.",
  "hardRules.sealHeader": "Hard rules (highest priority — must obey; override any conflicting earlier details):",
  "hardRules.sealFooter": "If any earlier instruction conflicts with Hard rules, follow Hard rules.",
  "hardRules.labelStory": "Story",
  "hardRules.labelCharacter": "Character",
  "hardRules.labelScene": "Scene",
  "hardRules.labelProp": "Prop",
  "hardRules.labelAction": "Action",
  "continuity.lockHeader": "Continuity lock (must obey for short-drama sequence):",
  "continuity.hasImage": "The attached image is the END FRAME / KEYFRAME of beat #{{n}}. This new shot continues from that exact visual state.",
  "continuity.noImage": "Continue from beat #{{n}} (no still available — match dossier only).",
  "continuity.identity": "IDENTITY: same person — face, hair, body proportions, wardrobe colors, accessories. No restyle, no age shift.",
  "continuity.space": "SPACE: same location — architecture, materials, layout, light direction. Only subtle time-of-day drift if the beat requires it.",
  "continuity.action": "ACTION: pick up motion/pose/gaze from the previous frame; do not hard-cut to a different setup.",
  "continuity.prevContext": "Previous beat context: {{snippet}}",
  "continuity.noText": "No text overlays, logos, watermarks.",
  "directorLabel.lock": "Dialogue lock",
  "directorLabel.story": "Story: ",
  "directorLabel.style": "Style: ",
  "directorLabel.cast": "Cast: ",
  "directorLabel.location": "Location: ",
  "directorLabel.prop": "Prop: ",
  "directorLabel.primaryChar": "Primary character: ",
  "directorLabel.mood": "Mood: ",
  "directorLabel.atmo": "Atmosphere: ",
  "directorLabel.camera": "Camera: ",
  "directorLabel.sfx": "Sound: ",
  "directorLabel.action": "Action: ",
  "directorLabel.expr": "Expression: ",
  "directorLabel.speech": "Dialogue: ",
  "directorLabel.notes": "Notes: ",
  "directorLabel.identity": "Identity: ",
  "directorLabel.space": "Space: ",
  "directorLabel.ref": "Still ",
  "directorLabel.beatN": "Beat #{{n}} · ",
  "directorLabel.beatNsec": "Beat #{{n}} · {{s}}s clip",
  "directorLabel.hardRules": "Hard rules",
  "directorLabel.identityLock": "Identity lock",
  "directorLabel.spaceLock": "Space lock",
  "storyBeats.system": "You write short-drama TIMELINE BEATS for AI video.\nEach beat = ONE short clip screenplay (not a single spoken line).\nA beat MUST include rich performance content: mood, atmosphere, actions, expressions, optional camera/sfx, and zero or more spoken dialogue lines (1–4 lines common).\nReturn ONLY a JSON array (no fences). Each item shape:\n{\"characterName\":\"…\",\"characterNames\":[\"…\"],\"sceneHint\":\"…\",\"sceneHints\":[\"…\"],\"propName\":\"…\",\"propNames\":[\"…\"],\"actionName\":\"…\",\"actionNames\":[\"…\"],\"mood\":\"…\",\"atmosphere\":\"…\",\"camera\":\"…\",\"sfx\":\"…\",\"units\":[{\"type\":\"action\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"expression\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"dialogue\",\"who\":\"…\",\"line\":\"…\",\"tone\":\"…\",\"parenthetical\":\"…\"},{\"type\":\"note\",\"text\":\"…\"}]}\nRules:\n- units.type dialogue.line = ONLY words the character speaks (no stage directions inside line).\n- Put physical business in action; face/micro-performance in expression; delivery in tone/parenthetical.\n- Multiple dialogue units in one beat are encouraged when the clip has a short exchange or self-talk.\n- Pure action beats (no dialogue) are allowed.\n- Do NOT default to one beat per chapter. Split by filmable clips: new location, time jump, new conflict, or action/dialogue that cannot fit in one 6–10s shot → a new beat. Typically 1–3 beats per chapter. Total at most {{maxBeats}} beats.\n- List EVERY library character, scene, prop, and action that appears in THIS clip (characterNames, sceneHints, propNames, actionNames). Caps: 4 characters, 2 scenes, 4 props, 4 actions. Do not fill only one of each.\n- If the clip has physical performance, actionNames is REQUIRED using the library original names from the story action list the user already chose. Never leave actionNames empty when there is physical performance; prefer selecting those listed actions over leaving none.\n- Max 4 units per beat (1–2 action, 0–1 expression, 0–2 dialogue). Keep fields short so JSON finishes in one reply. Use only cast names provided.\n- Prefer conflict, clear visual action, filmable detail.\n- Stay faithful to the title, style, cast, and scenes provided.\n- SPEECH: write each dialogue.line in that speaker's primary spoken language from the cast list. Do not switch languages between beats. Do not translate lines unless that is the character's listed language.",
  "storyBeats.userLead": "GENERATE full clip screenplay beats using ALL cast, scenes, props, actions, style, and idea below.",
  "storyBeats.eachBeat": "Each beat needs mood + atmosphere + actions/expressions + optional multi-line dialogue.",
  "storyBeats.story": "Story: {{title}}",
  "storyBeats.style": "Style: {{style}}",
  "storyBeats.userDir": "User direction: {{idea}}",
  "storyBeats.cast": "Cast:",
  "storyBeats.scenes": "Scenes:",
  "storyBeats.props": "Props: {{props}}",
  "storyBeats.actions": "Actions (motion): {{actions}}",
  "storyBeats.returnJson": "Return beats JSON array only.",
  "storyBeats.noCast": "(no cast)",
  "storyBeats.noScenes": "(no scenes — invent locations in sceneHint)",
  "storyBeats.none": "(none)",
  "storyBeats.chapters": "Story chapters (primary plot source — break these into filmable beats):",
  "storyBeats.chapterBlock": "Chapter {{n}} · {{title}}\n{{body}}",
  "storyChapters.system": "You write short-drama CHAPTERS — the narrative soul of the story, not clip screenplays.\nEach chapter is a compact prose beat (about {{words}} words): conflict, location, who is there, what they want, what changes.\nReturn ONLY a JSON array (no markdown). Each item: {\"title\":\"…\",\"body\":\"…\"}.\nWrite exactly {{count}} chapters. Stay loyal to the title, style bible, hard rules, and user idea. Do not invent a different world. Keep bodies short so the JSON fits in one reply.",
  "storyChapters.userLead": "Write the story as ordered chapters (treatment / 章節). These chapters will later generate characters, scenes, props, actions, then shooting beats.",
  "storyChapters.story": "Story: {{title}}",
  "storyChapters.style": "Style bible: {{style}}",
  "storyChapters.rules": "Hard rules: {{rules}}",
  "storyChapters.userDir": "User idea: {{idea}}",
  "storyChapters.returnJson": "Return JSON array only: [{\"title\":\"…\",\"body\":\"…\"}, …]",
  "storyChapters.polishSystem": "You polish ONE short-drama chapter. Keep plot facts, names, and outcome. Make it more filmable (concrete places, bodies, props, conflict). Return ONLY JSON: {\"title\":\"…\",\"body\":\"…\"}.",
  "storyChapters.polishUser": "Story: {{story}}\nCurrent title: {{title}}\nCurrent body:\n{{body}}\nOptional direction: {{idea}}\nReturn polished JSON {\"title\",\"body\"}.",
  "storyCastFromChapters.system": "You extract a production bible from story chapters: characters, locations/scenes, key props, and signature actions/motions.\nReturn ONLY JSON (no markdown):\n{\"characters\":[{\"name\":\"\",\"description\":\"\",\"appearance\":\"\",\"personality\":\"\",\"costume\":\"\",\"roleNote\":\"\"}],\"scenes\":[{\"title\":\"\",\"description\":\"\",\"locationType\":\"\",\"timeOfDay\":\"\",\"mood\":\"\"}],\"props\":[{\"name\":\"\",\"description\":\"\"}],\"actions\":[{\"name\":\"\",\"description\":\"\",\"motionNotes\":\"\",\"intention\":\"\"}]}\nRules: only entities that appear in the chapters. Reuse existing names when listed. Distinct people/places/objects/moves. Concrete visual detail. Empty arrays allowed. Do NOT emit one character / one scene / one prop / one action per chapter. One chapter may contain two people, several locations, many props and motions. Extract every distinct entity that actually appears. Example: two people talking → two characters; alley then shrine → two scenes. Do not invent extras to pad a quota.",
  "storyCastFromChapters.userLead": "Extract EVERY distinct character, scene, prop, and action that appears in the chapters — not one of each per chapter.",
  "storyCastFromChapters.story": "Story: {{title}}",
  "storyCastFromChapters.style": "Style: {{style}}",
  "storyCastFromChapters.chapters": "Chapters:\n{{chapters}}",
  "storyCastFromChapters.existingCast": "Already in this story (reuse these names): {{names}}",
  "storyCastFromChapters.returnJson": "Return the JSON object only.",
  "videoPolish.system": "You write ONE final image-to-video prompt for a short-drama AI video model.\nReturn ONLY the prompt text — no markdown fences, no title, no explanation.\nRules:\n- Write the director prompt in the user interface language; keep character names and required dialogue language codes clear.\n- Person still: Identity lock (face, hair, body, wardrobe, colors). Location plate: Space lock (architecture, materials, layout, signage, palette). Do not add new cast faces unless the materials name them.\n- Use ALL provided profile / soul / beat / location facts that affect look, motion, speech, or atmosphere; ignore empty fields.\n- Invent only what is needed to complete a filmable clip from the materials and seed — do not import a fixed sample world, Demo story, or facts not present in materials/seed.\n- Condense long soul.md into actionable performance + identity beats; do not dump the whole bible verbatim.\n- Use the duration given in the materials (the clip's actual seconds). Continuous action. No text overlays, logos, watermarks, or extra unrelated people.\n- Anatomically correct humans unless the script requires otherwise (two hands, two arms, two legs).\n- If multi-character, keep each listed subject consistent; primary focus first.\n- If Hard rules appear in materials, keep them and place them at the end of your output (highest priority).\n- Dialogue lock is mandatory: never drop, rewrite, or translate it. Expand language codes to full names. Every clip must use the character primary spoken language; do not switch languages between clips; do not translate dialogue lines.\n- Director revision may refine style/action but must NOT violate Hard rules.",
  "videoPolish.hardRulesKeep": "Hard rules (highest priority — keep every line; object labels like [Character · Name] must stay). Place the full hard-rules block at the END of your output. Do not weaken, drop, or reassign rules.",
  "clip.task": "TASK: Short-drama timeline clip (image-to-video).",
  "clip.hasRef": "A reference still may be attached — lock identity/location continuity to it when relevant.",
  "clip.characters": "Characters:",
  "clip.scene": "Scene:",
  "clip.prop": "Prop:",
  "clip.action": "Action / motion guide:",
  "clip.beat": "Beat / dialogue:",
  "clip.prev": "Previous clip continuity:",
  "clip.revision": "DIRECTOR REVISION (must follow):",
  "clip.templateDraft": "Template draft (improve):",
  "intro.task": "TASK: Self-introduction casting clip (image-to-video).",
  "intro.hasRef": "Reference still is attached to the video API — lock identity to that image.",
  "intro.noRef": "No reference still path in this text; still lock to profile appearance/costume.",
  "intro.dossier": "Character dossier:",
  "intro.templateDraft": "Template draft (improve; do not ignore dossier):",
  "common.durationAspect": "Duration: {{seconds}}s. Aspect: {{aspect}}.",
  "common.templateDraft": "Template draft:",
  "improve.mode": "IMPROVE MODE: Merge ALL sources below into a complete result. Keep core identity unless the user explicitly asks to change it. Prefer rich extra context when form fields are sparse; prefer explicit user request when it asks for a change.",
  "improve.draftDefault": "Current form fields (all filled inputs):",
  "improve.userRequest": "User improvement request (may be empty = polish & merge everything):",
  "improve.emptyDefault": "(polish all fields for short-drama continuity)",
  "improve.createDefault": "Idea / direction:",
  "improve.explicitContext": "Explicit context in THIS request only (use for continuity; do not import any other sample world; user idea/draft wins on conflict):",
  "improve.storyTitle": "Story title: {{title}}",
  "improve.styleNote": "Style note: {{style}}",
  "improve.closingDefault": "Output the complete result now.",
  "storyMeta.system": "You are a short-drama showrunner. Given a story title and optional idea, write a concise visual style bible AND hard rules for cover + clip generation. Return ONLY JSON (no fences): {\"styleNote\":\"2-5 sentences: tone, lighting, camera, color, pacing\",\"hardRules\":\"3-8 MUST/MUST-NOT lines for image & video\"}. Concrete, filmable language for AI video continuity. Use title, idea, existing style note / hard rules, and any context snippets.",
  "storyMeta.draftLabel": "Current story fields:",
  "storyMeta.createLabel": "Story idea / title:",
  "storyMeta.emptyPolish": "(polish visual style bible + hardRules for AI video continuity)",
  "storyMeta.closing": "Return ONLY JSON: {\"styleNote\":\"…\",\"hardRules\":\"…\"}. Both keys required and non-empty.",
  "storyMeta.contextLabel": "Story context (cast / scenes / props):",
  "character.system": "You are a professional short-drama character designer for AI video production. Given a short idea from the user, produce a complete, filmable character bible. A character may be human, animal, spirit, monster, robot, virtual avatar, or other designed entity — follow the idea; do not force a human if the idea is non-human. Return ONLY a single JSON object (no markdown fences, no commentary). Prefer vivid, concrete sensory detail. Keep identity consistent for multi-angle sheets and video. spokenLanguages: JSON array of BCP-47 codes this character SPEAKS, e.g. [\"yue\",\"en\"] or [\"ja\"]. Empty array if non-verbal.",
  "character.draftLabel": "Current Profile form fields (all filled inputs):",
  "character.soulLabel": "Linked soul.md / character bible (primary identity & personality source):",
  "character.createLabel": "Character idea:",
  "character.emptyPolish": "(polish all fields; integrate soul into profile)",
  "character.closing": "Output complete JSON now. Required keys: {{keys}}. visualTags = comma-separated string (not array). spokenLanguages may be a code array.",
  "scene.system": "You are a short-drama location & scene designer for AI video. Produce a filmable location bible + playable scene script fragment. Return ONLY one JSON object (no markdown). title = short location name; description = architecture/materials/landmarks; script = dialogue + action + camera for THIS scene.",
  "scene.draftLabel": "Current scene form fields (all filled inputs):",
  "scene.charsLabel": "Characters in story:",
  "scene.propsLabel": "Props in story:",
  "scene.priorLabel": "Prior scenes (continuity):",
  "scene.createLabel": "Scene idea:",
  "scene.emptyPolish": "(polish place + script for video continuity)",
  "scene.closing": "Output complete JSON now. Required keys: {{keys}}. Missing keys = invalid. visualTags must be a comma-separated string, not an array.",
  "prop.system": "You are a short-drama prop designer for AI video continuity. Return ONLY one JSON object. description: detailed look; material/sizeNotes/condition concrete.",
  "prop.draftLabel": "Current prop form fields (all filled inputs):",
  "prop.createLabel": "Prop idea:",
  "prop.emptyPolish": "(polish prop look for video continuity)",
  "prop.closing": "Output complete JSON now. Required keys: {{keys}}. Missing keys = invalid. visualTags must be a comma-separated string, not an array.",
  "prop.fallbackName": "Prop",
  "action.system": "You are a short-drama motion director. Output ONLY valid JSON for an action/motion guide asset. Be concrete: body parts, tempo, weight, prop paths, staging. No markdown.",
  "action.storyContext": "Story context (optional): {{title}}",
  "action.styleNote": "Style note: {{style}}",
  "action.existingDraft": "Existing draft JSON to polish:",
  "action.userIdea": "User idea: {{idea}}",
  "action.closing": "Return JSON only. Required keys: {{keys}}. visualTags = comma-separated string, not array.",
  "profile.mustEveryKey": "You MUST output EVERY key in this list: {{keys}}.",
  "profile.valuesAreStrings": "Every value MUST be a JSON string (not null, not a JSON array). Empty string only if truly unknown.",
  "profile.visualTagsRule": "visualTags: single comma-separated string in the user interface language — NEVER a JSON array.",
  "profile.fillConcrete": "Prefer filling all keys with concrete detail for short-drama continuity.",
  "common.rules": "Rules:",
  "common.none": "(none)",
  "intro.soul": "soul.md (use fully as performance/identity source):\n{{soul}}",
  "intro.matchBible": "(match character bible)",
  "invent.sources": "Sources of truth, in order: (1) user idea / request, (2) filled form fields, (3) linked extras (soul, cast lists, story blocks) only when they appear in THIS prompt, (4) attached reference image.",
  "invent.create": "Create mode (thin/empty form): invent freely from the idea/image so every critical key is filmable and related — do not leave required keys empty.",
  "invent.improve": "Improve mode (form has content): polish and complete missing fields consistent with the draft; do not replace core identity unless the user asks.",
  "invent.noImport": "Do NOT import identity, plot, weather, job, location, era, or style from anything not written in this prompt (no active story, no Demo seed, no app default world).",
  "invent.storyBlock": "When a story/style block IS present below, use it only for production continuity; never override an explicit user idea.",
  "character.keysLead": "Return ONLY a single JSON object with keys: {{keys}}",
  "character.ruleSpoken": "spokenLanguages: JSON array of BCP-47/ISO codes this character SPEAKS (multi OK), e.g. [\"yue\",\"en\"] or [\"ja\"]. Empty array if non-verbal.",
  "character.ruleIdentity": "Keep identity consistent for multi-angle reference sheets and video gen.",
  "scene.keysLead": "Return ONLY one JSON object (no markdown) with keys: {{keys}}",
  "scene.suggestLead": "Propose a production-ready LOCATION plate as scene #{{n}} for story \"{{title}}\".",
  "scene.suggestPlotFocus": "Plot focus: {{label}}",
  "scene.suggestStyle": "Style: {{style}}",
  "scene.suggestExisting": "Already have locations: {{titles}}",
  "scene.suggestChars": "Characters (context):",
  "scene.suggestProps": "Props (context):",
  "scene.suggestSegment": "Selected plot segment detail:",
  "scene.suggestBeats": "Story scenes / beats:",
  "scene.suggestClosing": "Return full scene JSON. Design a DISTINCT reusable location that fits this plot focus (global library asset — not only for one story).",
  "scene.fallbackName": "Location",
  "scene.ideaFromImage": "Describe and invent a full location profile from the attached reference photo.",
  "scene.polishIdea": "Polish",
  "prop.keysLead": "Return ONLY one JSON object with keys: {{keys}}",
  "action.fieldsLead": "Fields: {{keys}}.",
  "soul.system": "You write production soul.md files for AI agents and short-drama characters.\nOutput ONLY a complete Markdown document (no code fences, no commentary).\nStructure (use these ## headings):\n# {Character name}\n## Identity\n## Appearance\n## Costume & silhouette\n## Personality & voice\n## Spoken languages\n## Mannerisms\n## Backstory\n## Relationships\n## Performance & dialogue style\n## Hard rules for consistency\n## Visual tags\nRules:\n- Adult short-drama / film production context; concrete, filmable detail.\n- Sources of truth: profile form + existing soul + user request. Do not invent from sources not provided in this request unless the chosen recipe allows it.\n- Identity and appearance must stay consistent across multi-angle sheets and video.\n- Spoken languages: honor profile spokenLanguages codes for dialogue/TTS.\n- Hard rules: 5–10 bullet constraints (do/don't) for image & dialogue AI.\n- Write the soul in the user interface language unless the profile is clearly another language.\n- Optional YAML frontmatter at top with name, role, tags is allowed but not required.",
  "soul.improveMode": "IMPROVE MODE: Merge profile form + existing soul into an updated full soul.md. Keep core identity unless asked to change it.",
  "soul.createMode": "Build a full soul.md from this character profile (fill gaps reasonably; do not invent a different person):",
  "soul.profileFields": "Profile form fields (all filled inputs):",
  "soul.existing": "Existing soul.md (merge / improve; do not discard useful detail):",
  "soul.userRequest": "User request: {{request}}",
  "soul.extraContext": "Additional context provided with this request (use if helpful; profile still wins):",
  "soul.returnOnly": "Return the full soul.md markdown only.",
  "wardrobe.system": "You are a short-drama costume & visual-style consultant. Given a character and plot context, propose ONE cohesive wardrobe look. Reply with ONLY a single JSON object (no markdown fences): {\"name\":\"short look name\",\"costume\":\"detailed outer wardrobe for image/video prompts\",\"artStyle\":\"one id from list\",\"rationale\":\"1-2 sentences\"} artStyle MUST be exactly one of: {{styleIds}} costume must be specific materials, colors, silhouette, shoes, accessories. Respect age-appropriate presentation. Never eroticize minors. Prefer continuity with existing appearance; invent only wardrobe/style. Use character fields + any plot segment / story context provided.",
  "wardrobe.improveMode": "IMPROVE / SUGGEST MODE: Use ALL character fields + plot context below.",
  "wardrobe.characterForm": "Character (full form):",
  "wardrobe.soulExcerpt": "soul.md excerpt:\n{{soul}}",
  "wardrobe.userRequest": "User request: {{request}}",
  "wardrobe.storyContext": "Story / production context (use when provided; do not invent a different world):",
  "wardrobe.style": "style: {{style}}",
  "wardrobe.segment": "Selected plot segment: {{label}}",
  "wardrobe.sceneContext": "Scene / beat context:",
  "wardrobe.noScenes": "(no scenes yet)",
  "wardrobe.proposeNew": "Propose a NEW wardrobe look that fits the plot (not a duplicate of existing looks).",
  "fill.system": "You complete short-drama asset profile fields that were left empty.\nReturn ONLY one JSON object with EXACTLY these keys (and no others): {{keys}}.\nEach value MUST be a non-empty JSON string (never null, never a JSON array).\nvisualTags (if present): comma-separated string in the user interface language (format example only: \"gold, necklace\") — NEVER an array; invent tags that match THIS asset, do not copy the example.\nStay consistent with the partial profile and any attached reference image only — do not invent a different plot, location, or sample world not already implied by the partial/image.\nNo markdown fences, no commentary.",
  "fill.userPartial": "Partial profile (already filled — do not contradict):",
  "fill.userOnly": "Fill ONLY these missing keys: {{keys}}.",
  "fill.userReturn": "Return JSON with those keys only; every value a non-empty string.",
  "imageGen.multiRef": "Additional identity stills selected ({{n}} more): keep object/subject identity consistent with all selected references; primary edit base is the first still.",
  "residual.sceneLink": "Scene {{n}}: {{short}}",
  "residual.beatSegment": "Beat {{n}} · {{who}}{{tail}}",
  "residual.unknown": "Unknown",
  "residual.story": "Story",
  "beat.mood": "[MOOD] {{text}}",
  "beat.atmo": "[ATMO] {{text}}",
  "beat.camera": "[CAMERA] {{text}}",
  "beat.sfx": "[SFX] {{text}}",
  "beat.action": "[ACTION] {{text}}",
  "beat.actionWho": "[ACTION|{{who}}] {{text}}",
  "beat.expr": "[EXPR] {{text}}",
  "beat.exprWho": "[EXPR|{{who}}] {{text}}",
  "beat.dialogue": "[DIALOGUE|{{who}}] {{body}}",
  "beat.dialogueTone": "[DIALOGUE|{{who}}|{{tone}}] {{body}}",
  "beat.whoUnknown": "?",
  "beat.template": "[MOOD] tense, hesitant\n[ATMO] door-gap warm light; rain on ground\n[CAMERA] medium shot, push to hands\n[SFX] rain, fabric rustle\n[ACTION|Name] removes helmet; stares at the door light; hand into jacket pocket\n[EXPR|Name] furrowed brow, breath catches\n[DIALOGUE|Name|low, hoarse] Raining again…\n[DIALOGUE|Name|aside] (beat) Are you… still there?",
  "vision.preamble": "A reference still is attached. Fill ALL profile fields for this {{what}} primarily FROM THE IMAGE. Optionally refine with any idea/draft text.",
  "vision.character": "character identity (name, appearance, costume, age, gender, tags)",
  "vision.scene": "location profile (title, description, lighting, mood, set dressing, tags)",
  "vision.prop": "prop profile (name, description, material, size, condition, tags)",
  "vision.action": "action profile (name, description, motion, intention, camera notes, tags)",
  "vision.costume": "wardrobe (name, full costume description)",
  "still.header": "SINGLE KEYFRAME STILL for short-drama video continuity (not a multi-panel sheet). Produce one hero frame that matches the planned shot below. No text, logos, watermarks, UI chrome. Sharp, production-ready.",
  "still.revision": "USER IMPROVEMENT FOR THIS STILL (must apply): {{notes}}",
  "still.regenTask": "TASK: Revise the image-to-video director prompt AND keep it usable as a still keyframe brief.",
  "still.userImprove": "USER IMPROVEMENT REQUEST:\n{{notes}}",
  "still.currentPrompt": "Current professional prompt:",
  "still.hardRules": "Hard rules (must keep at end of output; do not drop or weaken):",
  "mediaGen.writeOne": "Write ONE final image-generation prompt for a short-drama production still.",
  "mediaGen.returnOnly": "Return ONLY the prompt text — no markdown fences, no title, no explanation.",
  "mediaGen.singleComposite": "Output must describe a SINGLE composite image (one export frame).",
  "mediaGen.lockRefs": "Attached images are ground-truth references in the same order as Ref# below. Lock identity/wardrobe/location/prop to those stills. Do NOT invent a different person, shop, or prop.",
  "mediaGen.videoSystem": "You are a short-drama video director prompt writer (image-to-video).",
  "mediaGen.videoMerge": "Merge materials into ONE professional video prompt for a short clip.",
  "mediaGen.videoInclude": "Include: subject identity locks from stills, camera move, performance/dialogue, pacing, lighting continuity.",
  "mediaGen.videoFacts": "Use only facts present in materials and seed; do not import a fixed sample world or Demo story.",
  "mediaGen.videoNoSwap": "Do not invent a different actor, location, or prop when refs are attached.",
  "mediaGen.videoHardRules": "Hard rules at end if supplied.",
  "mediaGen.imageSystem": "You are a short-drama image prompt director.",
  "mediaGen.imageMergeStills": "Merge the selected materials and attached reference stills into ONE image prompt.",
  "mediaGen.imageMergeText": "Merge the selected text materials into ONE image prompt.",
  "mediaGen.imagePriority": "Highest priority: match faces/wardrobe/locations/props from attached images.",
  "mediaGen.imageNoSwap": "Never substitute a different celebrity, salon clerk, or unrelated set when cast stills are provided.",
  "mediaGen.imageFacts": "Use only facts present in materials and seed; do not import a fixed sample world or Demo story.",
  "mediaGen.imageLayout": "If multi-panel geometry is required, keep exact panel count and gutters.",
  "mediaGen.imagePackage": "If a LAYOUT / package section is present, the final prompt MUST implement that exact layout (panel count, poses, crop).",
  "mediaGen.imageHardRules": "Hard rules at end if supplied.",
  "mediaGen.directorFallback": "IMAGE-TO-VIDEO: animate this keyframe as a short-drama clip. Lock identity, wardrobe, set, and framing to the keyframe.",
  "comic.taskHint": "Story “{{title}}”, comic page {{n}}: one finished comic page with exactly {{count}} panel(s). Keep character identity, wardrobe, and location continuous on the whole page. No watermark, no UI chrome.",
  "comic.panelCount": "Panel count is fixed: exactly {{n}} panel(s).",
  "comic.lockSplash": "Layout lock: one full-page splash. Forbidden: extra frames, split panels, collage.",
  "comic.lockYonkoma": "Layout lock: vertical 4-koma, 4 rows × 1 column, top to bottom. Forbidden: 2×2 grid or horizontal strip.",
  "comic.lockGrid2x2": "Layout lock: 2 rows × 2 columns. Forbidden: strip, 2×3, full-page splash.",
  "comic.lockGrid2x3": "Layout lock: 2 rows × 3 columns. Top 1-2-3, bottom 4-5-6. Forbidden: 2×2 or 3×3.",
  "comic.lockGrid3x3": "Layout lock: 3 rows × 3 columns = nine panels. Forbidden: 2×2, 2×3, or fewer panels.",
  "comic.lockStrip": "Layout lock: one horizontal row with exactly {{n}} panels. Forbidden: multi-row grids.",
  "comic.layoutSplash1": "One tall comic page: exactly one full-bleed splash, no gutters, no extra frames.",
  "comic.layoutStrip2": "One landscape comic page: two equal panels side by side, thick white gutters.",
  "comic.layoutStrip3": "One landscape comic page: three equal panels in one row, thick white gutters.",
  "comic.layoutYonkoma": "One tall comic page: a vertical 4-koma (4 rows × 1 column), thick white gutters, read top to bottom.",
  "comic.layoutGrid2x2": "One square comic page: a 2×2 grid, exactly four equal panels, thick white gutters, left-to-right then top-to-bottom.",
  "comic.layoutStrip4": "One wide landscape comic page: four equal panels in one row, thick white gutters.",
  "comic.layoutGrid2x3": "One landscape comic page: exactly six equal panels as 2 rows × 3 columns (top 1-2-3, bottom 4-5-6), thick white gutters, left-to-right then top-to-bottom.",
  "comic.layoutGrid3x3": "One square comic page: a 3×3 grid, exactly nine equal panels, thick white gutters, left-to-right then top-to-bottom.",
  "comic.layoutWidePlusTwo": "One tall comic page: a wide hero panel on the top (~60% of the height), then two equal smaller panels side by side below, thick white gutters.",
  "comic.layoutTwoPlusWide": "One tall comic page: two equal smaller panels side by side on top, then one wide closer panel on the bottom (~60%), thick white gutters.",
  "comic.layoutTallLeftTwo": "One tall comic page: a full-height tall panel on the left half, two stacked panels on the right, thick white gutters.",
  "comic.layoutHeroPlusThree": "One tall comic page: a wide hero panel on the top half, then three equal smaller panels in one row below, thick white gutters.",
  "comic.layoutFocusQuad": "One tall comic page: a medium panel top-left, two stacked small panels top-right, one large wide panel on the bottom half, thick white gutters.",
  "comic.layoutStaggerFour": "One tall comic page: staggered two-plus-two — top row wide then narrow, bottom row narrow then wide, thick white gutters.",
  "comic.layoutDiagPairPlus": "One tall comic page: the top half is split by a diagonal gutter into two wedge panels; the bottom half is one wide rectangle, thick white gutters.",
  "comic.layoutHeroPlusFour": "One tall comic page: a wide hero panel on the top half, then four smaller panels as a 2×2 on the bottom half, thick white gutters.",
  "comic.lockWidePlusTwo": "Layout lock: top panel is a wide hero. Bottom is exactly two smaller panels. Forbidden: three equal strips or a 2×2 grid.",
  "comic.lockTwoPlusWide": "Layout lock: top is exactly two smaller panels. Bottom is one wide closer. Forbidden: three equal strips or a 2×2 grid.",
  "comic.lockTallLeftTwo": "Layout lock: left panel is full page height. Right side is two stacked panels. Forbidden: 2×2 equal grid or a horizontal strip.",
  "comic.lockHeroPlusThree": "Layout lock: top half is one wide hero. Bottom is exactly three smaller panels in one row. Forbidden: 2×2 grid or four equal panels.",
  "comic.lockFocusQuad": "Layout lock: top-left medium, two small stacked on the top-right, one large panel on the bottom half. Forbidden: equal 2×2 squares.",
  "comic.lockStaggerFour": "Layout lock: staggered sizes — top wide+narrow, bottom narrow+wide. Forbidden: four equal squares.",
  "comic.lockDiagPairPlus": "Layout lock: top half must be two wedge panels split by a diagonal gutter; bottom half one wide rectangle. Forbidden: three equal strips or a 2×2.",
  "comic.lockHeroPlusFour": "Layout lock: top half one wide hero; bottom half a 2×2 of four smaller panels. Exactly five panels. Forbidden: 3×3 or a whole-page 2×2.",
  "comic.readingYonkoma": "Reading order: top to bottom only (vertical 4-koma).",
  "comic.readingWidePlusTwo": "Reading order: the wide top panel first, then left to right on the two smaller panels.",
  "comic.readingTwoPlusWide": "Reading order: left then right on the top pair, then the wide bottom panel.",
  "comic.readingTallLeftTwo": "Reading order: the tall left panel first, then the upper right, then the lower right.",
  "comic.readingHeroPlusThree": "Reading order: the wide top panel first, then the three smaller panels left to right.",
  "comic.readingFocusQuad": "Reading order: top-left medium, then the two small stacked panels top to bottom, then the large bottom panel.",
  "comic.readingStaggerFour": "Reading order: top-left, top-right, then bottom-left, bottom-right.",
  "comic.readingDiagPairPlus": "Reading order: the upper-left wedge, then the lower-right wedge, then the wide bottom panel.",
  "comic.readingHeroPlusFour": "Reading order: the wide top panel first, then the four smaller panels left to right, top to bottom.",
  "comic.readingOrder": "Reading order: left → right, then top → bottom (vertical 4-koma: top → bottom only).",
  "comic.panelNumbers": "Small panel numbers 1–{{n}} at the top-left of each panel.",
  "comic.panelLine": "Panel {{i}}/{{n}} ({{label}}): {{cap}}",
  "comic.panelEmpty": "Panel {{i}}/{{n}} ({{label}}): a distinct sequential story moment.",
  "comic.identity": "Same character identity, wardrobe, and location across every panel on this page.",
  "comic.finished": "This is a finished comic page, not a collage of unrelated photos, not a UI mockup.",
  "comic.layoutLead": "Layout: {{layout}}",
  "comic.prevPage": "Previous comic page. Keep character identity, wardrobe, and location continuous. Do not copy the previous panel grid.",
  "comic.ownPage": "Existing render of this page. Use as identity / layout edit base when revising.",
  "comic.galleryRef": "Cast or set identity still. Match faces, wardrobe, and location when included.",
  "comic.profileLine": "Comic page {{n}} for story “{{title}}”.",
  "comic.styleBible": "Story style note: {{note}}",
  "comic.artMedium": "Art medium: {{art}}",
  "comic.fallbackClose": "A finished printed comic page. Thick white gutters. Small panel numbers. No watermark, no app UI, no photo-album collage.",
  "comic.hardRules": "Hard rules",
  "comic.introTask": "IMAGE-TO-VIDEO: animate the finished comic page of story “{{title}}”, page {{n}}, exactly {{count}} panel(s). Lock identity, wardrobe, and layout to the attached page still.",
  "comic.introLock": "Lock: same faces, clothes, places, gutters, and panel numbers as the still. Do not invent a different page or a different person.",
  "comic.introLayout": "Keep this page layout: {{layout}}",
  "comic.introCamera": "Camera: slow push-in or a gentle pan that reads the panels in order. Soft paper/print motion only. No hard cut to a new layout.",
  "comic.introClose": "No watermark, no UI chrome, no extra speech captions beyond what is already drawn on the page.",
  "comic.dramaStillLock": "Lock identity, wardrobe, and place to the attached comic-page still, but play it as a live short-drama shot — not a paper pan across printed panels.",
  "comic.dramaCamera": "Camera and performance: short-drama pacing, clear acting, lip-sync to the written panel lines. Continue from the previous page when a still is attached.",
  "comic.formatLockTall": "PAGE FORMAT LOCK: the whole page must be a tall 9:16 comic page. No landscape widescreen composition.",
  "comic.formatLockSquare": "PAGE FORMAT LOCK: the whole page must be a square 1:1 comic page.",
  "comic.formatLockWide": "PAGE FORMAT LOCK: the whole page must be a wide 16:9 comic page.",
  "art.photoCinematic": "Mandatory medium: live-action photoreal film still. Real camera look, naturalistic materials, cinematic grade, optional film grain. Must look like a photograph or movie frame. Forbidden: anime, cel-shading, 2D illustration, cartoon outlines, clay, plastic CGI.",
  "art.photoPortrait": "Mandatory medium: photoreal studio portrait photography. Softbox lighting, commercial headshot clarity, real lens bokeh. Must be a photograph. Forbidden: anime, comic ink, 3D toy render, flat cel color.",
  "art.photoDocumentary": "Mandatory medium: photoreal documentary photo. Natural available light, honest textures, low glamour. Must look shot on a real camera. Forbidden: anime, stylized CGI, illustration.",
  "art.cgiFilm": "Mandatory medium: film-quality 3D CGI character render. Physically based materials, ray-traced highlights, clean silhouette. Must look 3D-rendered, not a real photo and not 2D anime. Forbidden: live-action photography, anime lineart, flat comic ink.",
  "art.cgiStylized": "Mandatory medium: stylized premium 3D (feature-animation CGI). Rounded readable forms, soft PBR, expressive proportions. Must be 3D CGI. Forbidden: photoreal live-action, 2D anime cel, sketchy comic.",
  "art.cgiClay": "Mandatory medium: 3D clay / sculpt character. Soft matte clay, sculpted forms, stop-motion lighting. Must read as clay sculpture. Forbidden: photoreal skin photo, anime cel, ink comic.",
  "art.animeModern": "Mandatory medium: 2D modern Japanese TV anime. Clean digital lineart, soft cel-shading, anime eyes and hair, flat or gradient color. The whole image must be 2D anime. Forbidden: photoreal photography, real skin pores, 3D render, Western comic ink only, oil painting.",
  "art.animeShonen": "Mandatory medium: 2D shonen anime key visual. Bold linework, high-contrast cel color, sharp anime eyes, dynamic silhouette. Must be shonen anime 2D. Forbidden: photoreal photo, 3D CGI, soft watercolor only.",
  "art.animeShoujo": "Mandatory medium: 2D shoujo anime. Delicate lineart, soft gradients, luminous anime eyes, gentle color. Must be shoujo anime. Forbidden: photoreal photo, hard 3D render, gritty comic ink.",
  "art.animeGekiga": "Mandatory medium: 2D gekiga / realist anime. Mature line quality, restrained palette, still clearly 2D anime. Forbidden: live-action photo, chibi, pure 3D CGI.",
  "art.animeChibi": "Mandatory medium: 2D chibi / super-deformed anime. Large head, small body, cute simplified features, clean flat colors. Must be chibi anime. Forbidden: photoreal proportions, realistic 3D, detailed live-action.",
  "art.donghua": "Mandatory medium: Chinese donghua character key art. Refined costume detail, elegant silhouette, high-quality 2D or 2.5D animation look. Must read as donghua, not a Hollywood photo. Forbidden: photoreal live-action, Western newspaper comic only.",
  "art.manhwa": "Mandatory medium: Korean manhwa / webtoon full-color art. Soft digital paint, clean contours, glossy hair. Must be manhwa 2D. Forbidden: photoreal photo, clay 3D, American superhero ink only.",
  "art.comicWestern": "Mandatory medium: Western comic-book art. Confident ink lines, flat or limited cel color, graphic shapes, design-sheet comic style. Must be comic illustration. Forbidden: photoreal photo, pure anime-eye style only, clay render.",
  "art.conceptGame": "Mandatory medium: AAA game character concept art. Paintover design sheet, strong silhouette, production concept quality. Must look like concept art, not a game screenshot and not a live-action photo. Forbidden: pure photoreal portrait photo, chibi anime only.",
  "art.illustrationSoft": "Mandatory medium: soft digital illustration. Gentle brush rendering, storybook-adjacent polish, coherent character design. Must be painted illustration. Forbidden: photoreal camera photo, hard anime cel only, clay 3D.",
  "mediaGen.polishTask": "Task: {{hint}}",
  "mediaGen.polishKind": "Kind: {{kind}}",
  "mediaGen.polishMaterials": "--- MATERIALS ---",
  "mediaGen.polishEndMaterials": "--- END MATERIALS ---",
  "mediaGen.polishRef": "Ref#{{n}} — {{title}}",
  "mediaGen.videoTaskHint": "Write a professional image-to-video director prompt from the keyframe ({{kind}}). Include camera, performance, and pacing; lock to the keyframe still.",
  "mediaGen.directorFallbackCam": "Camera motion and performance clear; no captions or watermark.",
  "charIntro.task": "IMAGE-TO-VIDEO: animate the exact person in the reference image as a short self-introduction clip for short-drama casting.",
  "charIntro.identityLock": "Identity lock: same face, hair, body, age, wardrobe, and colors as the reference still — do not invent a different person.",
  "charIntro.personality": "Personality / vibe: {{personality}}.",
  "charIntro.backstory": "Backstory cue: {{backstory}}.",
  "charIntro.relationships": "Relationships cue: {{relationships}}.",
  "charIntro.soul": "Soul bible excerpt (performance source): {{soul}}",
  "charIntro.performance": "Performance: gentle camera push-in or subtle handheld; character looks toward camera or slightly off-camera; {{manner}}.",
  "charIntro.speech": "Speech: mouth moves as if introducing themselves briefly; voice tone: {{voice}}.",
  "charIntro.beat": "Action beat: natural idle → small smile or nod → short spoken intro gesture (hand optional) → hold.",
  "charIntro.lighting": "Cinematic lighting consistent with the still; no text overlays, no logos, no extra people.",
  "sceneIntro.task": "IMAGE-TO-VIDEO: animate the exact location in the reference still as a short location-intro / establishing clip for short-drama production.",
  "sceneIntro.spaceLock": "Space lock: same architecture, materials, signage, layout, and color language as the reference plate — do not invent a different place.",
  "sceneIntro.name": "Location name: {{name}}.",
  "sceneIntro.place": "Place description: {{place}}.",
  "sceneIntro.spaceType": "Space type: {{type}}.",
  "sceneIntro.time": "Time of day: {{time}}.",
  "sceneIntro.weather": "Weather: {{weather}}.",
  "sceneIntro.moodLight": "Mood: {{mood}}. Lighting: {{lighting}}.",
  "sceneIntro.palette": "Color palette: {{palette}}.",
  "sceneIntro.setDressing": "Set dressing: {{set}}.",
  "sceneIntro.tags": "Visual tags: {{tags}}.",
  "sceneIntro.art": "Art style: {{art}}.",
  "sceneIntro.ambient": "Ambient feel (no UI text): {{sound}}.",
  "sceneIntro.scriptCue": "Beat cue (atmosphere only, no hero faces unless already in still): {{cue}}.",
  "sceneIntro.camera": "Camera: {{camera}}; continuous gentle motion. Do not add new cast faces, logos, or text overlays unless the materials already show them.",
  "sceneIntro.beat": "Action beat: hold establishing → subtle environmental life (light shift, weather particles, fabric/tree if already present) → settle.",
  "propIntro.task": "IMAGE-TO-VIDEO: animate the exact prop in the reference still as a short product/hero intro clip for short-drama continuity.",
  "propIntro.objectLock": "OBJECT LOCK: same silhouette, materials, colors, logos/engravings, wear, and proportions as the reference — do not invent a different object.",
  "propIntro.name": "Prop name: {{name}}.",
  "propIntro.look": "Look description: {{look}}.",
  "propIntro.material": "Material: {{material}}.",
  "propIntro.size": "Size notes: {{size}}.",
  "propIntro.condition": "Condition / wear: {{condition}}.",
  "propIntro.tags": "Visual tags: {{tags}}.",
  "propIntro.art": "Art style: {{art}}.",
  "propIntro.camera": "Camera: gentle orbit or slow push-in on a clean tabletop/hero stage; soft cinematic light consistent with the still.",
  "propIntro.beat": "Action beat: hold hero still → subtle light glint / micro-rotation or fabric/metal shimmer if present → settle.",
  "propIntro.noHands": "No hands unless already in the still; no new cast faces; no text overlays, logos watermarks, or extra props.",
  "costumeIntro.task": "IMAGE-TO-VIDEO: animate the exact wardrobe look in the reference still as a short costume intro clip for short-drama wardrobe library.",
  "costumeIntro.wardrobeLock": "WARDROBE LOCK: same silhouette, fabrics, colors, layers, accessories, and wear as the reference — do not invent a different outfit.",
  "costumeIntro.identityOrProduct": "If a person is in the still: Identity lock on face/body while fabric may gently move; if mannequin or flat-lay: keep product framing.",
  "costumeIntro.name": "Look name: {{name}}.",
  "costumeIntro.desc": "Costume description: {{look}}.",
  "costumeIntro.art": "Art style: {{art}}.",
  "costumeIntro.camera": "Camera: gentle push-in or subtle orbit; fashion-look lighting consistent with the still.",
  "costumeIntro.beat": "Action beat: hold pose/still → fabric drape / sleeve hem micro-motion / light glint on hardware → settle.",
  "costumeIntro.forbid": "No new cast faces; no text overlays, logos, or erotic posing.",
  "costumeIntro.fallbackName": "Look",
  "actionIntro.lead": "Short-drama motion demo video of action \"{{name}}\".",
  "actionIntro.intention": "Intention: {{intention}}",
  "actionIntro.body": "Body/tempo: {{body}}",
  "actionIntro.camera": "Camera: {{camera}}",
  "actionIntro.closing": "Smooth continuous motion, no text overlays, follow the keyframe still.",
  "sceneIntroPolish.task": "TASK: Location intro / establishing clip (image-to-video).",
  "sceneIntroPolish.hasRef": "Reference location still is attached to the video API — lock SPACE identity to that plate.",
  "sceneIntroPolish.noRef": "No reference still path in this text; still lock to location bible description.",
  "sceneIntroPolish.dossier": "Location dossier:",
  "sceneIntroPolish.scriptCue": "script cue (atmosphere only):\n{{script}}",
  "sceneIntroPolish.emptySet": "Prefer empty set; no new cast faces unless already in the still. No text overlays or logos.",
  "propIntroPolish.task": "TASK: Prop / object hero intro clip (image-to-video).",
  "propIntroPolish.hasRef": "Reference prop still is attached — lock OBJECT identity to that image.",
  "propIntroPolish.noRef": "No reference still path in this text; still lock to prop dossier.",
  "propIntroPolish.dossier": "Prop dossier:",
  "propIntroPolish.noHands": "No new hands or cast faces unless already in the still. No text overlays or logos.",
  "costumeIntroPolish.task": "TASK: Costume / wardrobe look intro clip (image-to-video).",
  "costumeIntroPolish.hasRef": "Reference still is attached — if person present lock IDENTITY + wardrobe; if mannequin/flat-lay lock garment silhouette and materials.",
  "costumeIntroPolish.noRef": "No reference still path; lock to costume description.",
  "costumeIntroPolish.dossier": "Costume dossier:",
  "costumeIntroPolish.fabric": "Show fabric drape/motion subtly; no new cast faces; no text overlays or logos.",
  "actionIntroPolish.task": "TASK: Action / motion-guide intro clip (image-to-video).",
  "actionIntroPolish.hasRef": "Reference still attached — lock performance identity to that frame.",
  "actionIntroPolish.templateKeepRules": "Template draft (improve; keep Hard rules at end):",
  "cover.posterLead": "PROFESSIONAL SHORT-DRAMA POSTER / KEY ART (16:9 still). Not a UI mockup. No text, no logo, no watermark, no title caption.",
  "cover.titleMood": "Story title (mood only, do not letter it): {{title}}.",
  "cover.styleBible": "Style bible: {{style}}",
  "cover.extraDir": "Extra direction: {{idea}}",
  "cover.establishing": "Evocative establishing mood frame suitable as a library card cover.",
  "cover.medium": "Match the art medium; strong silhouette and readable mood.",
  "cover.editPrefix": "IMAGE EDIT: create a new short-drama poster composition. Keep identity/mood of subjects if present. ",
  "cover.label": "Story cover",
  "costumeFill.system": "You are a film wardrobe designer. Reply with ONLY compact JSON: {\"name\":\"short label\",\"description\":\"full wardrobe description for image gen (layers, fabric, colors, accessories; no brand logos)\",\"artStyle\":\"optional style id or empty string\",\"hardRules\":\"3-8 MUST/MUST-NOT lines\"} Every key present as a JSON string (not null/array). No markdown. If an image is provided, describe THAT outfit faithfully for short-drama generation.",
  "costumeFill.idea": "Idea: {{idea}}",
  "costumeFill.polish": "Polish the draft wardrobe.",
  "costumeFill.required": "Required keys: name, description, artStyle, hardRules. Missing keys = invalid.",
  "costumeFill.fallbackName": "Look",
  "segment.entireStory": "Entire story (all scenes)",
  "segment.noStory": "No story selected",
  "vision.inventFromImage": "Describe and invent a full {{kind}} profile from the attached reference photo.",
  "vision.polishAll": "Polish and merge all fields",
  "story.untitled": "Untitled short drama",
  "action.castIdentityNote": "Cast identity stills ({{count}}): match face/body of attached cast references in every panel.",
  "tpl.system.polishOnly": "RECIPE polish-only: Keep core identity and world. Polish wording. Do not invent era, weather, job, location, or a sample world. Do not invent spoken language. Do not write default Hard rules into the profile.",
  "tpl.system.fillBlanks": "RECIPE fill-blanks: Fill ONLY empty keys. Do not rewrite filled fields. Do not invent a new world.",
  "tpl.system.invent": "RECIPE invent: The user asked you to create freely from the idea. Invent filmable detail so every required key is complete. Still do not import Demo or any world not implied by this request.",
  "tpl.system.fromStory": "RECIPE from-story: Use the story title/style/cast/scenes provided in THIS request only, for continuity. User idea still wins on conflict.",
  "tpl.system.followAsset": "RECIPE follow-asset: Follow the asset and story style already provided. Do not force cinematic look, empty-set, or a 6–10s duration unless the materials say so. Use the clip's actual duration.",
  "tpl.system.cinematicLock": "RECIPE cinematic-lock: Cinematic short-drama look; empty set preferred for locations; no watermarks, logos, or extra faces; human anatomy two hands/arms/legs unless non-human.",
  "tpl.system.identityLock": "RECIPE identity-lock: Lock face/body/wardrobe/location/prop identity to attached stills. Do not substitute a different person, place, or object.",
  "tpl.system.restyle": "RECIPE restyle: Keep the same character identity. Wardrobe, location dressing, and era may change as the user asked. Do not invent a different person.",
  "pipeline.character.system": "You refine character bibles for short-form AI video drama. Keep each character to 3-5 lines: look, voice, motivation, signature gesture. Use only facts already in this request.",
  "pipeline.scene.system": "You expand short-drama scenes into visual beat sheets. Fit each beat to the clip duration in the materials — do not assume 6–10 seconds. Use only provided scenes.",
  "pipeline.props.system": "You refine prop continuity notes for short-drama production. Note color, size, and when the prop appears. Do not invent props that are not listed.",
  "pipeline.script.system": "You are a professional short-drama screenwriter. For each scene, write a compact screenplay block for AI video. Use the story’s actual clip durations; do not force a 10-second cap. Format every scene as:\n### SCENE <number> | id=<id>\n<script body>",
  "pipeline.script.noScenes": "(no scenes — do not invent locations)",
  "keyArt.task": "KEY ART still {{n}} for story “{{title}}”. One finished publicity image. No comic gutters, no panel numbers, no app UI.",
  "keyArt.lockCover": "COVER POSTER: landscape key art for a story card. Leave a quiet title-safe band. Faces readable. Do not invent a logo or a fake credit block.",
  "keyArt.lockPoster": "TALL POSTER: a single upright one-sheet. Hero readable from a phone. No extra posters in the frame.",
  "keyArt.lockStill": "PRODUCTION STILL: one cinematic film frame as if grabbed from the drama. Natural acting, real space. Not a collage.",
  "keyArt.lockPromo": "PROMO KEY ART: marketing image of character and world together. Strong silhouette, one mood. Not a contact sheet.",
  "keyArt.lockSocial": "SOCIAL STORY: tall 9:16 teaser frame. Subject large. Safe margins for on-screen type.",
  "keyArt.lockHeadshot": "HERO HEADSHOT: one front face filling the frame, identity locked to the attached refs. Shoulders allowed. No extra people.",
  "keyArt.lockBust": "BUST PROMO: chest-up portrait, costume collar visible, looking toward camera.",
  "keyArt.lockGroup": "CAST LINEUP: all named attached characters in one frame, same world, same light. Do not drop or swap a face.",
  "keyArt.formatLockTall": "FORMAT LOCK: the whole image is a tall 9:16 frame. No landscape widescreen crop.",
  "keyArt.formatLockSquare": "FORMAT LOCK: the whole image is a square 1:1 frame.",
  "keyArt.formatLockWide": "FORMAT LOCK: the whole image is a wide 16:9 frame.",
  "keyArt.methodFreshLock": "MAKE METHOD: generate a new still. Use refs for identity only. Do not copy the pixel layout of an old take.",
  "keyArt.methodEditLock": "MAKE METHOD: edit the attached own still. Keep composition unless the brief asks to change it.",
  "keyArt.methodIdentityLock": "MAKE METHOD: lock faces to the character refs. Pose, crop, and wardrobe may change.",
  "keyArt.methodContinueLock": "MAKE METHOD: continue from the previous still. Same people and place, next beat of the same shoot.",
  "keyArt.briefLine": "Director brief: {{brief}}",
  "keyArt.beatLine": "Bound beat: {{beat}}",
  "keyArt.close": "Finished {{aspect}} still. No watermark, no UI chrome, no extra captions.",
}
