import type { PromptCopyTable } from './keys'

export const enPromptCopy: PromptCopyTable = {
  "speechLock.named": "SPEECH LOCK · Character \"{{who}}\": audible speech AND lip-sync MUST be {{primaryName}} ({{primary}}) only. Do not speak {{forbid}} or any other language. Keep the same speech language on every clip. Do not translate dialogue.",
  "speechLock.unnamed": "SPEECH LOCK · Speaking characters: audible speech AND lip-sync MUST be {{primaryName}} ({{primary}}) only. Do not speak {{forbid}} or any other language. Keep the same speech language on every clip. Do not translate dialogue.",
  "speechLock.namedMulti": "SPEECH LOCK · Character \"{{who}}\": audible speech AND lip-sync MUST be {{primaryName}} ({{primary}}). Other allowed languages ONLY if the written script line is already in that language: {{extras}}. Never invent a third language. Never switch languages between clips. Do not switch to {{forbid}}. Do not translate dialogue.",
  "speechLock.unnamedMulti": "SPEECH LOCK · Speaking characters: audible speech AND lip-sync MUST be {{primaryName}} ({{primary}}). Other allowed languages ONLY if the written script line is already in that language: {{extras}}. Never invent a third language. Never switch languages between clips. Do not switch to {{forbid}}. Do not translate dialogue.",
  "storyBeats.system": "You write short-drama TIMELINE BEATS for AI video.\nEach beat = ONE short clip screenplay (not a single spoken line).\nA beat MUST include rich performance content: mood, atmosphere, actions, expressions, optional camera/sfx, and zero or more spoken dialogue lines (1–4 lines common).\nReturn ONLY a JSON array (no fences). Each item shape:\n{\"characterName\":\"…\",\"characterNames\":[\"…\"],\"sceneHint\":\"…\",\"propName\":\"…\",\"mood\":\"…\",\"atmosphere\":\"…\",\"camera\":\"…\",\"sfx\":\"…\",\"units\":[{\"type\":\"action\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"expression\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"dialogue\",\"who\":\"…\",\"line\":\"…\",\"tone\":\"…\",\"parenthetical\":\"…\"},{\"type\":\"note\",\"text\":\"…\"}]}\nRules:\n- units.type dialogue.line = ONLY words the character speaks (no stage directions inside line).\n- Put physical business in action; face/micro-performance in expression; delivery in tone/parenthetical.\n- Multiple dialogue units in one beat are encouraged when the clip has a short exchange or self-talk.\n- Pure action beats (no dialogue) are allowed.\n- Write 4–8 beats. Use only cast names provided.\n- Prefer conflict, clear visual action, filmable detail.\n- Stay faithful to the title, style, cast, and scenes provided; if thin, invent freely within that cast/world.\n- SPEECH: write each dialogue.line in that speaker's primary spoken language from the cast list. Do not switch languages between beats. Do not translate lines unless that is the character's listed language.",
  "storyBeats.userLead": "GENERATE full clip screenplay beats using ALL cast, scenes, props, style, and idea below.",
  "storyBeats.eachBeat": "Each beat needs mood + atmosphere + actions/expressions + optional multi-line dialogue.",
  "storyBeats.story": "Story: {{title}}",
  "storyBeats.style": "Style: {{style}}",
  "storyBeats.userDir": "User direction: {{idea}}",
  "storyBeats.cast": "Cast:",
  "storyBeats.scenes": "Scenes:",
  "storyBeats.props": "Props: {{props}}",
  "storyBeats.returnJson": "Return beats JSON array only.",
  "storyBeats.noCast": "(no cast)",
  "storyBeats.noScenes": "(no scenes — invent locations in sceneHint)",
  "storyBeats.none": "(none)",
  "videoPolish.system": "You write ONE final image-to-video prompt for a short-drama AI video model.\nReturn ONLY the prompt text — no markdown fences, no title, no explanation.\nRules:\n- Write the director prompt in the user interface language; keep character names and required dialogue language codes clear.\n- Person still: IDENTITY LOCK (face, hair, body, wardrobe, colors). Location plate: SPACE LOCK (architecture, materials, layout, signage, palette) — empty set preferred; no new cast faces.\n- Use ALL provided profile / soul / beat / location facts that affect look, motion, speech, or atmosphere; ignore empty fields.\n- Invent only what is needed to complete a filmable clip from the materials and seed — do not import a fixed sample world, Demo story, or facts not present in materials/seed.\n- Condense long soul.md into actionable performance + identity beats; do not dump the whole bible verbatim.\n- Duration 6–10s; continuous action; cinematic; no text overlays, logos, watermarks, or extra unrelated people.\n- Anatomically correct humans unless the script requires otherwise (two hands, two arms, two legs).\n- If multi-character, keep each listed subject consistent; primary focus first.\n- If HARD RULES appear in materials, keep them and place them at the end of your output (highest priority).\n- SPEECH LOCK is mandatory: never drop, rewrite, or translate it. Expand language codes to full names. Every clip must use the character primary spoken language; do not switch languages between clips; do not translate dialogue lines.\n- Director revision may refine style/action but must NOT violate HARD RULES.",
  "videoPolish.hardRulesKeep": "HARD RULES (HIGHEST PRIORITY — keep every line; object labels like [Character · Name] must stay). Place the full HARD RULES block at the END of your output. Do not weaken, drop, or reassign rules.",
  "clip.task": "TASK: Short-drama timeline clip (image-to-video).",
  "clip.hasRef": "A reference still may be attached — lock identity/location continuity to it when relevant.",
  "clip.characters": "Characters:",
  "clip.scene": "Scene:",
  "clip.prop": "Prop:",
  "clip.action": "Action / motion guide:",
  "clip.beat": "Beat / dialogue:",
  "clip.prev": "Previous clip continuity:",
  "clip.revision": "DIRECTOR REVISION (must follow):",
  "clip.templateDraft": "Template draft (improve):",
  "intro.task": "TASK: Self-introduction casting clip (image-to-video).",
  "intro.hasRef": "Reference still is attached to the video API — lock identity to that image.",
  "intro.noRef": "No reference still path in this text; still lock to profile appearance/costume.",
  "intro.dossier": "Character dossier:",
  "intro.templateDraft": "Template draft (improve; do not ignore dossier):",
  "common.durationAspect": "Duration: {{seconds}}s. Aspect: {{aspect}}.",
  "common.templateDraft": "Template draft:",
  "improve.mode": "IMPROVE MODE: Merge ALL sources below into a complete result. Keep core identity unless the user explicitly asks to change it. Prefer rich extra context when form fields are sparse; prefer explicit user request when it asks for a change.",
  "improve.draftDefault": "Current form fields (all filled inputs):",
  "improve.userRequest": "User improvement request (may be empty = polish & merge everything):",
  "improve.emptyDefault": "(polish all fields for short-drama continuity)",
  "improve.createDefault": "Idea / direction:",
  "improve.explicitContext": "Explicit context in THIS request only (use for continuity; do not import any other sample world; user idea/draft wins on conflict):",
  "improve.storyTitle": "Story title: {{title}}",
  "improve.styleNote": "Style note: {{style}}",
  "improve.closingDefault": "Output the complete result now.",
  "storyMeta.system": "You are a short-drama showrunner. Given a story title and optional idea, write a concise visual style bible AND hard rules for cover + clip generation. Return ONLY JSON (no fences): {\"styleNote\":\"2-5 sentences: tone, lighting, camera, color, pacing\",\"hardRules\":\"3-8 MUST/MUST-NOT lines for image & video\"}. Concrete, filmable language for AI video continuity. Use title, idea, existing style note / hard rules, and any context snippets; if thin, invent freely a coherent style bible + rules.",
  "storyMeta.draftLabel": "Current story fields:",
  "storyMeta.createLabel": "Story idea / title:",
  "storyMeta.emptyPolish": "(polish visual style bible + hardRules for AI video continuity)",
  "storyMeta.closing": "Return ONLY JSON: {\"styleNote\":\"…\",\"hardRules\":\"…\"}. Both keys required and non-empty.",
  "storyMeta.contextLabel": "Story context (cast / scenes / props):",
  "character.system": "You are a professional short-drama character designer for AI video production. Given a short idea from the user, invent a complete, filmable character bible. A character may be human, animal, spirit, monster, robot, virtual avatar, or other designed entity — follow the idea; do not force a human if the idea is non-human. Return ONLY a single JSON object (no markdown fences, no commentary). Prefer vivid, concrete sensory detail. Keep identity consistent for multi-angle sheets and video. spokenLanguages: JSON array of BCP-47 codes this character SPEAKS, e.g. [\"yue\",\"en\"] or [\"ja\"]. Empty array if non-verbal.",
  "character.draftLabel": "Current Profile form fields (all filled inputs):",
  "character.soulLabel": "Linked soul.md / character bible (primary identity & personality source):",
  "character.createLabel": "Character idea:",
  "character.emptyPolish": "(polish all fields; integrate soul into profile)",
  "character.closing": "Output complete JSON now. Required keys: {{keys}}. visualTags = comma-separated string (not array). spokenLanguages may be a code array.",
  "scene.system": "You are a short-drama location & scene designer for AI video. Produce a filmable location bible + playable scene script fragment. Return ONLY one JSON object (no markdown). title = short location name; description = architecture/materials/landmarks; script = dialogue + action + camera for THIS scene.",
  "scene.draftLabel": "Current scene form fields (all filled inputs):",
  "scene.charsLabel": "Characters in story:",
  "scene.propsLabel": "Props in story:",
  "scene.priorLabel": "Prior scenes (continuity):",
  "scene.createLabel": "Scene idea:",
  "scene.emptyPolish": "(polish place + script for video continuity)",
  "scene.closing": "Output complete JSON now. Required keys: {{keys}}. Missing keys = invalid. visualTags must be a comma-separated string, not an array.",
  "prop.system": "You are a short-drama prop designer for AI video continuity. Return ONLY one JSON object. description: detailed look; material/sizeNotes/condition concrete.",
  "prop.draftLabel": "Current prop form fields (all filled inputs):",
  "prop.createLabel": "Prop idea:",
  "prop.emptyPolish": "(polish prop look for video continuity)",
  "prop.closing": "Output complete JSON now. Required keys: {{keys}}. Missing keys = invalid. visualTags must be a comma-separated string, not an array.",
  "prop.fallbackName": "Prop",
  "action.system": "You are a short-drama motion director. Output ONLY valid JSON for an action/motion guide asset. Be concrete: body parts, tempo, weight, prop paths, staging. No markdown.",
  "action.storyContext": "Story context (optional): {{title}}",
  "action.styleNote": "Style note: {{style}}",
  "action.existingDraft": "Existing draft JSON to polish:",
  "action.userIdea": "User idea: {{idea}}",
  "action.closing": "Return JSON only. Required keys: {{keys}}. visualTags = comma-separated string, not array.",
  "profile.mustEveryKey": "You MUST output EVERY key in this list: {{keys}}.",
  "profile.valuesAreStrings": "Every value MUST be a JSON string (not null, not a JSON array). Empty string only if truly unknown.",
  "profile.visualTagsRule": "visualTags: single comma-separated string in the user interface language — NEVER a JSON array.",
  "profile.fillConcrete": "Prefer filling all keys with concrete detail for short-drama continuity.",
  "common.rules": "Rules:",
  "common.none": "(none)",
  "intro.soul": "soul.md (use fully as performance/identity source):\n{{soul}}",
  "intro.matchBible": "(match character bible)",
  "invent.sources": "Sources of truth, in order: (1) user idea / request, (2) filled form fields, (3) linked extras (soul, cast lists, story blocks) only when they appear in THIS prompt, (4) attached reference image.",
  "invent.create": "Create mode (thin/empty form): invent freely from the idea/image so every critical key is filmable and related — do not leave required keys empty.",
  "invent.improve": "Improve mode (form has content): polish and complete missing fields consistent with the draft; do not replace core identity unless the user asks.",
  "invent.noImport": "Do NOT import identity, plot, weather, job, location, era, or style from anything not written in this prompt (no active story, no Demo seed, no app default world).",
  "invent.storyBlock": "When a story/style block IS present below, use it only for production continuity; never override an explicit user idea.",
  "character.keysLead": "Return ONLY a single JSON object with keys: {{keys}}",
  "character.ruleSpoken": "spokenLanguages: JSON array of BCP-47/ISO codes this character SPEAKS (multi OK), e.g. [\"yue\",\"en\"] or [\"ja\"]. Empty array if non-verbal.",
  "character.ruleIdentity": "Keep identity consistent for multi-angle reference sheets and video gen.",
  "character.fallbackPersonality": "warm, clear presence",
  "character.fallbackManner": "natural micro-gestures",
  "character.fallbackVoice": "clear speaking voice",
  "scene.keysLead": "Return ONLY one JSON object (no markdown) with keys: {{keys}}",
  "scene.suggestLead": "Propose a production-ready LOCATION plate as scene #{{n}} for story \"{{title}}\".",
  "scene.suggestPlotFocus": "Plot focus: {{label}}",
  "scene.suggestStyle": "Style: {{style}}",
  "scene.suggestExisting": "Already have locations: {{titles}}",
  "scene.suggestChars": "Characters (context):",
  "scene.suggestProps": "Props (context):",
  "scene.suggestSegment": "Selected plot segment detail:",
  "scene.suggestBeats": "Story scenes / beats:",
  "scene.suggestClosing": "Return full scene JSON. Design a DISTINCT reusable location that fits this plot focus (global library asset — not only for one story).",
  "scene.fallbackName": "Location",
  "scene.fallbackMood": "cinematic atmosphere",
  "scene.fallbackLighting": "match the still",
  "scene.fallbackCamera": "gentle establishing push-in or slow pan",
  "scene.ideaFromImage": "Describe and invent a full location profile from the attached reference photo.",
  "scene.polishIdea": "Polish",
  "prop.keysLead": "Return ONLY one JSON object with keys: {{keys}}",
  "action.fieldsLead": "Fields: {{keys}}.",
  "soul.system": "You write production soul.md files for AI agents and short-drama characters.\nOutput ONLY a complete Markdown document (no code fences, no commentary).\nStructure (use these ## headings):\n# {Character name}\n## Identity\n## Appearance\n## Costume & silhouette\n## Personality & voice\n## Spoken languages\n## Mannerisms\n## Backstory\n## Relationships\n## Performance & dialogue style\n## Hard rules for consistency\n## Visual tags\nRules:\n- Adult short-drama / film production context; concrete, filmable detail.\n- Sources of truth: profile form + existing soul + user request. If sparse, invent freely to complete the soul; do not invent from sources not provided in this request.\n- Identity and appearance must stay consistent across multi-angle sheets and video.\n- Spoken languages: honor profile spokenLanguages codes for dialogue/TTS.\n- Hard rules: 5–10 bullet constraints (do/don't) for image & dialogue AI.\n- Write the soul in the user interface language unless the profile is clearly another language.\n- Optional YAML frontmatter at top with name, role, tags is allowed but not required.",
  "soul.improveMode": "IMPROVE MODE: Merge profile form + existing soul into an updated full soul.md. Keep core identity unless asked to change it.",
  "soul.createMode": "Build a full soul.md from this character profile (fill gaps reasonably; do not invent a different person):",
  "soul.profileFields": "Profile form fields (all filled inputs):",
  "soul.existing": "Existing soul.md (merge / improve; do not discard useful detail):",
  "soul.userRequest": "User request: {{request}}",
  "soul.extraContext": "Additional context provided with this request (use if helpful; profile still wins):",
  "soul.returnOnly": "Return the full soul.md markdown only.",
  "wardrobe.system": "You are a short-drama costume & visual-style consultant. Given a character and plot context, propose ONE cohesive wardrobe look. Reply with ONLY a single JSON object (no markdown fences): {\"name\":\"short look name\",\"costume\":\"detailed outer wardrobe for image/video prompts\",\"artStyle\":\"one id from list\",\"rationale\":\"1-2 sentences\"} artStyle MUST be exactly one of: {{styleIds}} costume must be specific materials, colors, silhouette, shoes, accessories. Respect age-appropriate presentation. Never eroticize minors. Prefer continuity with existing appearance; invent only wardrobe/style. Use character fields + any plot segment / story context provided; if thin, invent a cohesive look freely.",
  "wardrobe.improveMode": "IMPROVE / SUGGEST MODE: Use ALL character fields + plot context below.",
  "wardrobe.characterForm": "Character (full form):",
  "wardrobe.soulExcerpt": "soul.md excerpt:\n{{soul}}",
  "wardrobe.userRequest": "User request: {{request}}",
  "wardrobe.storyContext": "Story / production context (use when provided; do not invent a different world):",
  "wardrobe.style": "style: {{style}}",
  "wardrobe.segment": "Selected plot segment: {{label}}",
  "wardrobe.sceneContext": "Scene / beat context:",
  "wardrobe.noScenes": "(no scenes yet)",
  "wardrobe.proposeNew": "Propose a NEW wardrobe look that fits the plot (not a duplicate of existing looks).",
  "fill.system": "You complete short-drama asset profile fields that were left empty.\nReturn ONLY one JSON object with EXACTLY these keys (and no others): {{keys}}.\nEach value MUST be a non-empty JSON string (never null, never a JSON array).\nvisualTags (if present): comma-separated string in the user interface language (format example only: \"gold, necklace\") — NEVER an array; invent tags that match THIS asset, do not copy the example.\nStay consistent with the partial profile and any attached reference image only — do not invent a different plot, location, or sample world not already implied by the partial/image.\nNo markdown fences, no commentary.",
  "fill.userPartial": "Partial profile (already filled — do not contradict):",
  "fill.userOnly": "Fill ONLY these missing keys: {{keys}}.",
  "fill.userReturn": "Return JSON with those keys only; every value a non-empty string.",
  "imageGen.multiRef": "Additional identity stills selected ({{n}} more): keep object/subject identity consistent with all selected references; primary edit base is the first still.",
  "residual.sceneLink": "Scene {{n}}: {{short}}",
  "residual.beatSegment": "Beat {{n}} · {{who}}{{tail}}",
  "residual.unknown": "Unknown",
  "residual.story": "Story",
  "beat.mood": "[MOOD] {{text}}",
  "beat.atmo": "[ATMO] {{text}}",
  "beat.camera": "[CAMERA] {{text}}",
  "beat.sfx": "[SFX] {{text}}",
  "beat.action": "[ACTION] {{text}}",
  "beat.actionWho": "[ACTION|{{who}}] {{text}}",
  "beat.expr": "[EXPR] {{text}}",
  "beat.exprWho": "[EXPR|{{who}}] {{text}}",
  "beat.dialogue": "[DIALOGUE|{{who}}] {{body}}",
  "beat.dialogueTone": "[DIALOGUE|{{who}}|{{tone}}] {{body}}",
  "beat.whoUnknown": "?",
  "beat.template": "[MOOD] tense, hesitant\n[ATMO] door-gap warm light; rain on ground\n[CAMERA] medium shot, push to hands\n[SFX] rain, fabric rustle\n[ACTION|Name] removes helmet; stares at the door light; hand into jacket pocket\n[EXPR|Name] furrowed brow, breath catches\n[DIALOGUE|Name|low, hoarse] Raining again…\n[DIALOGUE|Name|aside] (beat) Are you… still there?",
  "vision.preamble": "A reference still is attached. Fill ALL profile fields for this {{what}} primarily FROM THE IMAGE. Optionally refine with any idea/draft text.",
  "vision.character": "character identity (name, appearance, costume, age, gender, tags)",
  "vision.scene": "location profile (title, description, lighting, mood, set dressing, tags)",
  "vision.prop": "prop profile (name, description, material, size, condition, tags)",
  "vision.action": "action profile (name, description, motion, intention, camera notes, tags)",
  "vision.costume": "wardrobe (name, full costume description)",
  "still.header": "SINGLE KEYFRAME STILL for short-drama video continuity (not a multi-panel sheet). Produce one cinematic hero frame that matches the planned shot below. No text, logos, watermarks, UI chrome. Sharp, production-ready.",
  "still.revision": "USER IMPROVEMENT FOR THIS STILL (must apply): {{notes}}",
  "still.regenTask": "TASK: Revise the image-to-video director prompt AND keep it usable as a still keyframe brief.",
  "still.userImprove": "USER IMPROVEMENT REQUEST:\n{{notes}}",
  "still.currentPrompt": "Current professional prompt:",
  "still.hardRules": "HARD RULES (must keep at end of output; do not drop or weaken):",
  "mediaGen.writeOne": "Write ONE final image-generation prompt for a short-drama production still.",
  "mediaGen.returnOnly": "Return ONLY the prompt text — no markdown fences, no title, no explanation.",
  "mediaGen.singleComposite": "Output must describe a SINGLE composite image (one export frame).",
  "mediaGen.lockRefs": "Attached images are ground-truth references in the same order as Ref# below. Lock identity/wardrobe/location/prop to those stills. Do NOT invent a different person, shop, or prop.",
  "mediaGen.videoSystem": "You are a short-drama video director prompt writer (image-to-video).",
  "mediaGen.videoMerge": "Merge materials into ONE professional video prompt for a short clip.",
  "mediaGen.videoInclude": "Include: subject identity locks from stills, camera move, performance/dialogue, pacing, lighting continuity.",
  "mediaGen.videoFacts": "Use only facts present in materials and seed; do not import a fixed sample world or Demo story.",
  "mediaGen.videoNoSwap": "Do not invent a different actor, location, or prop when refs are attached.",
  "mediaGen.videoHardRules": "Hard rules at end if supplied.",
  "mediaGen.imageSystem": "You are a short-drama image prompt director.",
  "mediaGen.imageMergeStills": "Merge the selected materials and attached reference stills into ONE image prompt.",
  "mediaGen.imageMergeText": "Merge the selected text materials into ONE image prompt.",
  "mediaGen.imagePriority": "Highest priority: match faces/wardrobe/locations/props from attached images.",
  "mediaGen.imageNoSwap": "Never substitute a different celebrity, salon clerk, or unrelated set when cast stills are provided.",
  "mediaGen.imageFacts": "Use only facts present in materials and seed; do not import a fixed sample world or Demo story.",
  "mediaGen.imageLayout": "If multi-panel geometry is required, keep exact panel count and gutters.",
  "mediaGen.imagePackage": "If a LAYOUT / package section is present, the final prompt MUST implement that exact layout (panel count, poses, crop).",
  "mediaGen.imageHardRules": "Hard rules at end if supplied.",
  "mediaGen.directorFallback": "IMAGE-TO-VIDEO: animate this keyframe as a short-drama clip. Lock identity, wardrobe, set, and framing to the keyframe.",
  "mediaGen.directorFallbackCam": "Camera motion and performance clear; no captions or watermark.",
  "charIntro.task": "IMAGE-TO-VIDEO: animate the exact person in the reference image as a short self-introduction clip for short-drama casting.",
  "charIntro.identityLock": "IDENTITY LOCK: same face, hair, body, age, wardrobe, and colors as the reference still — do not invent a different person.",
  "charIntro.personality": "Personality / vibe: {{personality}}.",
  "charIntro.backstory": "Backstory cue: {{backstory}}.",
  "charIntro.relationships": "Relationships cue: {{relationships}}.",
  "charIntro.soul": "Soul bible excerpt (performance source): {{soul}}",
  "charIntro.performance": "Performance: gentle camera push-in or subtle handheld; character looks toward camera or slightly off-camera; {{manner}}.",
  "charIntro.speech": "Speech: mouth moves as if introducing themselves briefly; voice tone: {{voice}}.",
  "charIntro.beat": "Action beat: natural idle → small smile or nod → short spoken intro gesture (hand optional) → hold.",
  "charIntro.lighting": "Cinematic lighting consistent with the still; no text overlays, no logos, no extra people.",
  "charIntro.duration": "Duration fits a 6–10s vertical-or-horizontal casting self-intro clip.",
  "sceneIntro.task": "IMAGE-TO-VIDEO: animate the exact location in the reference still as a short location-intro / establishing clip for short-drama production.",
  "sceneIntro.spaceLock": "SPACE LOCK: same architecture, materials, signage, layout, and color language as the reference plate — do not invent a different place.",
  "sceneIntro.name": "Location name: {{name}}.",
  "sceneIntro.place": "Place description: {{place}}.",
  "sceneIntro.spaceType": "Space type: {{type}}.",
  "sceneIntro.time": "Time of day: {{time}}.",
  "sceneIntro.weather": "Weather: {{weather}}.",
  "sceneIntro.moodLight": "Mood: {{mood}}. Lighting: {{lighting}}.",
  "sceneIntro.palette": "Color palette: {{palette}}.",
  "sceneIntro.setDressing": "Set dressing: {{set}}.",
  "sceneIntro.tags": "Visual tags: {{tags}}.",
  "sceneIntro.art": "Art style: {{art}}.",
  "sceneIntro.ambient": "Ambient feel (no UI text): {{sound}}.",
  "sceneIntro.scriptCue": "Beat cue (atmosphere only, no hero faces unless already in still): {{cue}}.",
  "sceneIntro.camera": "Camera: {{camera}}; continuous gentle motion; empty-set preferred — no new cast faces, no logos, no text overlays.",
  "sceneIntro.beat": "Action beat: hold establishing → subtle environmental life (light shift, weather particles, fabric/tree if already present) → settle.",
  "sceneIntro.duration": "Duration fits a 6–10s establishing intro clip.",
  "propIntro.task": "IMAGE-TO-VIDEO: animate the exact prop in the reference still as a short product/hero intro clip for short-drama continuity.",
  "propIntro.objectLock": "OBJECT LOCK: same silhouette, materials, colors, logos/engravings, wear, and proportions as the reference — do not invent a different object.",
  "propIntro.name": "Prop name: {{name}}.",
  "propIntro.look": "Look description: {{look}}.",
  "propIntro.material": "Material: {{material}}.",
  "propIntro.size": "Size notes: {{size}}.",
  "propIntro.condition": "Condition / wear: {{condition}}.",
  "propIntro.tags": "Visual tags: {{tags}}.",
  "propIntro.art": "Art style: {{art}}.",
  "propIntro.camera": "Camera: gentle orbit or slow push-in on a clean tabletop/hero stage; soft cinematic light consistent with the still.",
  "propIntro.beat": "Action beat: hold hero still → subtle light glint / micro-rotation or fabric/metal shimmer if present → settle.",
  "propIntro.noHands": "No hands unless already in the still; no new cast faces; no text overlays, logos watermarks, or extra props.",
  "propIntro.duration": "Duration fits a 6–10s prop intro clip.",
  "costumeIntro.task": "IMAGE-TO-VIDEO: animate the exact wardrobe look in the reference still as a short costume intro clip for short-drama wardrobe library.",
  "costumeIntro.wardrobeLock": "WARDROBE LOCK: same silhouette, fabrics, colors, layers, accessories, and wear as the reference — do not invent a different outfit.",
  "costumeIntro.identityOrProduct": "If a person is in the still: IDENTITY LOCK on face/body while fabric may gently move; if mannequin or flat-lay: keep product framing.",
  "costumeIntro.name": "Look name: {{name}}.",
  "costumeIntro.desc": "Costume description: {{look}}.",
  "costumeIntro.art": "Art style: {{art}}.",
  "costumeIntro.camera": "Camera: gentle push-in or subtle orbit; fashion-look lighting consistent with the still.",
  "costumeIntro.beat": "Action beat: hold pose/still → fabric drape / sleeve hem micro-motion / light glint on hardware → settle.",
  "costumeIntro.forbid": "No new cast faces; no text overlays, logos, or erotic posing.",
  "costumeIntro.duration": "Duration fits a 6–10s wardrobe intro clip.",
  "costumeIntro.fallbackName": "Look",
  "actionIntro.lead": "Short-drama motion demo video of action \"{{name}}\".",
  "actionIntro.intention": "Intention: {{intention}}",
  "actionIntro.body": "Body/tempo: {{body}}",
  "actionIntro.camera": "Camera: {{camera}}",
  "actionIntro.closing": "Smooth continuous motion, cinematic, no text overlays, follow the keyframe still.",
  "sceneIntroPolish.task": "TASK: Location intro / establishing clip (image-to-video).",
  "sceneIntroPolish.hasRef": "Reference location still is attached to the video API — lock SPACE identity to that plate.",
  "sceneIntroPolish.noRef": "No reference still path in this text; still lock to location bible description.",
  "sceneIntroPolish.dossier": "Location dossier:",
  "sceneIntroPolish.scriptCue": "script cue (atmosphere only):\n{{script}}",
  "sceneIntroPolish.emptySet": "Prefer empty set; no new cast faces unless already in the still. No text overlays or logos.",
  "propIntroPolish.task": "TASK: Prop / object hero intro clip (image-to-video).",
  "propIntroPolish.hasRef": "Reference prop still is attached — lock OBJECT identity to that image.",
  "propIntroPolish.noRef": "No reference still path in this text; still lock to prop dossier.",
  "propIntroPolish.dossier": "Prop dossier:",
  "propIntroPolish.noHands": "No new hands or cast faces unless already in the still. No text overlays or logos.",
  "costumeIntroPolish.task": "TASK: Costume / wardrobe look intro clip (image-to-video).",
  "costumeIntroPolish.hasRef": "Reference still is attached — if person present lock IDENTITY + wardrobe; if mannequin/flat-lay lock garment silhouette and materials.",
  "costumeIntroPolish.noRef": "No reference still path; lock to costume description.",
  "costumeIntroPolish.dossier": "Costume dossier:",
  "costumeIntroPolish.fabric": "Show fabric drape/motion subtly; no new cast faces; no text overlays or logos.",
  "actionIntroPolish.task": "TASK: Action / motion-guide intro clip (image-to-video).",
  "actionIntroPolish.hasRef": "Reference still attached — lock performance identity to that frame.",
  "actionIntroPolish.templateKeepRules": "Template draft (improve; keep HARD RULES at end):",
  "cover.posterLead": "PROFESSIONAL SHORT-DRAMA POSTER / KEY ART (16:9 cinematic still). Not a UI mockup. No text, no logo, no watermark, no title caption.",
  "cover.titleMood": "Story title (mood only, do not letter it): {{title}}.",
  "cover.styleBible": "Style bible: {{style}}",
  "cover.extraDir": "Extra direction: {{idea}}",
  "cover.establishing": "Evocative establishing mood frame suitable as a library card cover.",
  "cover.medium": "Match the art medium; strong silhouette and readable mood.",
  "cover.editPrefix": "IMAGE EDIT: create a new short-drama poster composition. Keep identity/mood of subjects if present. ",
  "cover.label": "Story cover",
  "costumeFill.system": "You are a film wardrobe designer. Reply with ONLY compact JSON: {\"name\":\"short label\",\"description\":\"full wardrobe description for image gen (layers, fabric, colors, accessories; no brand logos)\",\"artStyle\":\"optional style id or empty string\",\"hardRules\":\"3-8 MUST/MUST-NOT lines\"} Every key present as a JSON string (not null/array). No markdown. If an image is provided, describe THAT outfit faithfully for short-drama generation.",
  "costumeFill.idea": "Idea: {{idea}}",
  "costumeFill.polish": "Polish the draft wardrobe.",
  "costumeFill.required": "Required keys: name, description, artStyle, hardRules. Missing keys = invalid.",
  "costumeFill.fallbackName": "Look",
  "segment.entireStory": "Entire story (all scenes)",
  "segment.noStory": "No story selected",
  "vision.inventFromImage": "Describe and invent a full {{kind}} profile from the attached reference photo.",
  "vision.polishAll": "Polish and merge all fields",
  "story.untitled": "Untitled short drama"
}
