import type { PromptCopyTable } from './keys'

export const esPromptCopy: PromptCopyTable = {
  "speechLock.named": "Bloqueo de diálogo · Personaje \"{{who}}\": el habla audible Y el lip-sync DEBEN ser solo {{primaryName}} ({{primary}}). No hables {{forbid}} ni otro idioma. Mantén el mismo idioma en cada clip. No traduzcas el diálogo.",
  "speechLock.unnamed": "Bloqueo de diálogo · Personajes que hablan: el habla audible Y el lip-sync DEBEN ser solo {{primaryName}} ({{primary}}). No hables {{forbid}} ni otro idioma. Mantén el mismo idioma en cada clip. No traduzcas el diálogo.",
  "speechLock.namedMulti": "Bloqueo de diálogo · Personaje \"{{who}}\": el habla audible Y el lip-sync DEBEN ser {{primaryName}} ({{primary}}). Otros idiomas SOLO si la línea del guion ya está en ese idioma: {{extras}}. Nunca un tercer idioma. No cambies de idioma entre clips. No pases a {{forbid}}. No traduzcas el diálogo.",
  "speechLock.unnamedMulti": "Bloqueo de diálogo · Personajes que hablan: el habla audible Y el lip-sync DEBEN ser {{primaryName}} ({{primary}}). Otros idiomas SOLO si la línea del guion ya está en ese idioma: {{extras}}. Nunca un tercer idioma. No cambies de idioma entre clips. No pases a {{forbid}}. No traduzcas el diálogo.",
  "hardRules.sealHeader": "REGLAS FIRMES (máxima prioridad — cumplir; prevalecen ante cualquier conflicto):",
  "hardRules.sealFooter": "Si una instrucción anterior choca con las REGLAS FIRMES, siga las REGLAS FIRMES.",
  "hardRules.labelStory": "Historia",
  "hardRules.labelCharacter": "Personaje",
  "hardRules.labelScene": "Lugar",
  "hardRules.labelProp": "Atrezo",
  "hardRules.labelAction": "Acción",
  "continuity.lockHeader": "BLOQUEO DE CONTINUIDAD (obligatorio en la secuencia):",
  "continuity.hasImage": "La imagen adjunta es el FOTOGRAMA FINAL / clave del plano {{n}}. Este plano continúa desde ese estado visual, sin corte brusco a otro decorado.",
  "continuity.noImage": "Continuar desde el plano {{n}} (sin fotograma: alinear solo con el dossier).",
  "continuity.identity": "IDENTIDAD: la misma persona — cara, pelo, proporciones, colores de vestuario, accesorios. Sin restyle ni cambio de edad.",
  "continuity.space": "ESPACIO: el mismo lugar — arquitectura, materiales, planta, luz. Solo un leve cambio de hora si el plano lo pide.",
  "continuity.action": "ACCIÓN: retomar pose, mirada y movimiento del fotograma anterior; no cortes a otra disposición.",
  "continuity.prevContext": "Contexto del plano anterior: {{snippet}}",
  "continuity.noText": "Sin subtítulos, logos ni marcas de agua.",
  "directorLabel.lock": "Bloqueo de diálogo",
  "directorLabel.story": "Historia: ",
  "directorLabel.style": "Estilo: ",
  "directorLabel.cast": "Reparto: ",
  "directorLabel.location": "Lugar: ",
  "directorLabel.prop": "Atrezo: ",
  "directorLabel.primaryChar": "Personaje principal: ",
  "directorLabel.mood": "Ánimo: ",
  "directorLabel.atmo": "Atmósfera: ",
  "directorLabel.camera": "Cámara: ",
  "directorLabel.sfx": "Sonido: ",
  "directorLabel.action": "Acción: ",
  "directorLabel.expr": "Expresión: ",
  "directorLabel.speech": "Diálogo: ",
  "directorLabel.notes": "Notas: ",
  "directorLabel.identity": "Identidad: ",
  "directorLabel.space": "Espacio: ",
  "directorLabel.ref": "Fotograma ",
  "directorLabel.beatN": "Plano {{n}} · ",
  "directorLabel.beatNsec": "Plano {{n}} · {{s}} s",
  "directorLabel.hardRules": "REGLAS FIRMES",
  "directorLabel.identityLock": "Bloqueo de identidad",
  "directorLabel.spaceLock": "Bloqueo espacial",
  "storyBeats.system": "Escribes PULSOS de la línea de tiempo para vídeo de corto dramático.\nCada pulso = el guion de UN clip corto (no una sola réplica).\nDebe incluir humor, atmósfera, acciones, expresiones, cámara/sfx opcional y 0 o más réplicas (lo habitual: 1–4).\nDevuelve SOLO un array JSON (sin vallas). Forma de cada ítem:\n{\"characterName\":\"…\",\"characterNames\":[\"…\"],\"sceneHint\":\"…\",\"sceneHints\":[\"…\"],\"propName\":\"…\",\"propNames\":[\"…\"],\"actionName\":\"…\",\"actionNames\":[\"…\"],\"mood\":\"…\",\"atmosphere\":\"…\",\"camera\":\"…\",\"sfx\":\"…\",\"units\":[{\"type\":\"action\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"expression\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"dialogue\",\"who\":\"…\",\"line\":\"…\",\"tone\":\"…\",\"parenthetical\":\"…\"},{\"type\":\"note\",\"text\":\"…\"}]}\nReglas:\n- dialogue.line son SOLO las palabras dichas; nada de acotaciones dentro.\n- El cuerpo va en action; el rostro en expression; el tono en tone/parenthetical.\n- En un intercambio breve o un monólogo, varios dialogue en el mismo pulso.\n- Se permiten pulsos de solo acción.\n- NO un pulso por capítulo por defecto. Divide por clips filmables: nuevo lugar, salto de tiempo, nuevo conflicto, o acción/diálogo que no cabe en 6–10s → otro pulso. Típicamente 1–3 por capítulo. Como máximo {{maxBeats}} pulsos en total.\n- Lista TODO personaje, escena, prop y acción de la biblioteca que aparezca en ESTE clip (characterNames, sceneHints, propNames, actionNames). Límites: 4 / 2 / 4 / 4. No pongas solo uno de cada.\n- Si hay actuación física, actionNames es OBLIGATORIO con el nombre original de la lista de acciones ya elegida. No lo dejes vacío; mejor marcar esas acciones que dejar ninguna.\n- Máx. 4 units por pulso (1–2 action, 0–1 expression, 0–2 dialogue). Textos cortos; un JSON. Solo nombres del elenco dado.\n- Conflicto, acción visible, detalle filmable.\n- Fiel al título, estilo, elenco y escenas. No ensanches el mundo.\n- Cada dialogue.line en la lengua principal del hablante (lista de elenco). No cambies de lengua entre pulsos. No traduzcas salvo que sea la lengua listada.",
  "storyBeats.userLead": "GENERA beats de guion de clip usando TODO el elenco, escenas, props, acciones, estilo e idea de abajo.",
  "storyBeats.eachBeat": "Cada beat necesita ánimo + atmósfera + acciones/expresiones + diálogo opcional.",
  "storyBeats.story": "Historia: {{title}}",
  "storyBeats.style": "Estilo: {{style}}",
  "storyBeats.userDir": "Indicación del usuario: {{idea}}",
  "storyBeats.cast": "Elenco:",
  "storyBeats.scenes": "Escenas:",
  "storyBeats.props": "Atrezzo: {{props}}",
  "storyBeats.actions": "Acciones (movimiento): {{actions}}",
  "storyBeats.returnJson": "Devuelve solo el array JSON de beats.",
  "storyBeats.noCast": "(sin elenco)",
  "storyBeats.noScenes": "(sin escenas — puedes nombrar un lugar en sceneHint; no inventes un mundo nuevo)",
  "storyBeats.none": "(ninguno)",
  "storyBeats.chapters": "Capítulos de la historia (fuente principal — desglósalos en beats filmables):",
  "storyBeats.chapterBlock": "Capítulo {{n}} · {{title}}\n{{body}}",
  "storyChapters.system": "Escribes CAPÍTULOS de un corto dramático: el alma narrativa, no el guion de clip.\nCada capítulo es prosa breve (unas {{words}} palabras): conflicto, lugar, quién está, qué quieren, qué cambia.\nDevuelve SOLO un array JSON. Cada ítem: {\"title\":\"…\",\"body\":\"…\"}.\nEscribe exactamente {{count}} capítulos. Sé fiel al título, estilo, reglas y la idea. Cuerpos cortos; un solo JSON.",
  "storyChapters.userLead": "Escribe la historia en capítulos ordenados. Luego se usarán para generar elenco, escenarios, props y acciones.",
  "storyChapters.story": "Historia: {{title}}",
  "storyChapters.style": "Biblia de estilo: {{style}}",
  "storyChapters.rules": "Reglas duras: {{rules}}",
  "storyChapters.userDir": "Idea del usuario: {{idea}}",
  "storyChapters.returnJson": "Devuelve solo el array JSON: [{\"title\":\"…\",\"body\":\"…\"}, …]",
  "storyChapters.polishSystem": "Pules UN capítulo. Conserva hechos, nombres y desenlace; hazlo más filmable. Devuelve SOLO JSON {\"title\":\"…\",\"body\":\"…\"}.",
  "storyChapters.polishUser": "Historia: {{story}}\nTítulo actual: {{title}}\nCuerpo:\n{{body}}\nDirección opcional: {{idea}}\nDevuelve JSON {\"title\",\"body\"}.",
  "storyCastFromChapters.system": "Extraes biblia de producción de los capítulos: personajes, locaciones, props clave y acciones.\nDevuelve SOLO JSON con characters, scenes, props, actions. Solo entidades que aparecen. Reutiliza nombres existentes. Detalle visual concreto. NO uno por capítulo. Un capítulo puede tener dos personas, varios lugares, muchos props y acciones. Extrae cada entidad distinta que aparezca. Diálogo de dos → dos characters; callejón luego santuario → dos scenes. No inventes para rellenar.",
  "storyCastFromChapters.userLead": "Extrae CADA personaje, escena, prop y acción distintos que aparezcan — no uno de cada por capítulo.",
  "storyCastFromChapters.story": "Historia: {{title}}",
  "storyCastFromChapters.style": "Estilo: {{style}}",
  "storyCastFromChapters.chapters": "Capítulos:\n{{chapters}}",
  "storyCastFromChapters.existingCast": "Ya en esta historia (reutiliza estos nombres): {{names}}",
  "storyCastFromChapters.returnJson": "Devuelve solo el objeto JSON.",
  "videoPolish.system": "Escribes UN prompt final imagen a vídeo para un modelo de vídeo de drama corto.\nDevuelve SOLO el texto del prompt: sin vallas markdown, título ni explicación.\nReglas:\n- Escribe el prompt de dirección en el idioma de la interfaz; deja claros los nombres y los códigos de idioma del diálogo.\n- Still de persona: Bloqueo de identidad. Placa de lugar: Bloqueo espacial. No añadas caras nuevas salvo que los materiales las nombren.\n- Usa TODOS los datos de perfil / soul / beat / lugar que afecten aspecto, movimiento, habla o atmósfera; ignora campos vacíos.\n- Inventa solo lo necesario para un clip filmable a partir de los materiales y el seed; no importes un mundo de muestra, Demo u otros hechos.\n- Condensa un soul.md largo en beats de actuación e identidad; no pegues la biblia entera.\n- Usa la duración de los materiales (segundos reales del clip). Acción continua. Sin texto, logos, marcas de agua ni gente extra.\n- Anatomía humana correcta salvo que el guion pida otra (dos manos, dos brazos, dos piernas).\n- Si hay varios personajes, mantén a cada sujeto; el foco principal primero.\n- Si hay REGLAS FIRMES, consérvalas y ponlas al final (máxima prioridad).\n- Bloqueo de diálogo es obligatorio: no lo borres, reescribas ni traduzcas. Expande códigos a nombres. Cada clip usa la lengua principal del personaje; no cambies de idioma entre clips; no traduzcas diálogos.\n- La revisión de dirección puede pulir estilo/acción pero NO violar REGLAS FIRMES.",
  "videoPolish.hardRulesKeep": "REGLAS FIRMES (prioridad máxima — conserve cada línea; las etiquetas de objeto como [Personaje · Nombre] deben quedarse). Coloque el bloque completo de reglas firmes al FINAL de la salida. No las debilite, elimine ni reasigne.",
  "clip.task": "TAREA: clip de línea de tiempo de drama corto (imagen a vídeo).",
  "clip.hasRef": "Puede ir una imagen de referencia: bloquea identidad y lugar cuando corresponda.",
  "clip.characters": "Personajes:",
  "clip.scene": "Escena:",
  "clip.prop": "Atrezzo:",
  "clip.action": "Guía de acción / movimiento:",
  "clip.beat": "Beat / diálogo:",
  "clip.prev": "Continuidad del clip anterior:",
  "clip.revision": "REVISIÓN DEL DIRECTOR (obligatoria):",
  "clip.templateDraft": "Borrador de plantilla (mejora):",
  "intro.task": "TAREA: clip de presentación de casting (imagen a vídeo).",
  "intro.hasRef": "La imagen de referencia se envía a la API de vídeo: bloquea la identidad a esa foto.",
  "intro.noRef": "No hay ruta de imagen en este texto; aun así bloquea el aspecto y el vestuario del perfil.",
  "intro.dossier": "Dossier del personaje:",
  "intro.templateDraft": "Borrador de plantilla (mejora; no ignores el dossier):",
  "common.durationAspect": "Duración: {{seconds}}s. Relación: {{aspect}}.",
  "common.templateDraft": "Borrador de plantilla:",
  "improve.mode": "MODO MEJORAR: fusiona TODAS las fuentes en un resultado completo. Conserva la identidad salvo que el usuario pida cambiarla.",
  "improve.draftDefault": "Campos actuales del formulario:",
  "improve.userRequest": "Petición de mejora (vacío = pulir y fusionar todo):",
  "improve.emptyDefault": "(pulir todos los campos para continuidad)",
  "improve.createDefault": "Idea / dirección:",
  "improve.explicitContext": "Contexto explícito SOLO de esta petición (continuidad; no importes otro mundo muestra):",
  "improve.storyTitle": "Título: {{title}}",
  "improve.styleNote": "Nota de estilo: {{style}}",
  "improve.closingDefault": "Devuelve el resultado completo ahora.",
  "storyMeta.system": "Eres showrunner de drama corto. Escribe biblia visual y reglas duras. SOLO JSON.",
  "storyMeta.draftLabel": "Campos actuales de la historia:",
  "storyMeta.createLabel": "Idea / título de la historia:",
  "storyMeta.emptyPolish": "(pulir biblia visual y hardRules)",
  "storyMeta.closing": "SOLO JSON: {\"styleNote\":\"…\",\"hardRules\":\"…\"}. Ambas claves obligatorias.",
  "storyMeta.contextLabel": "Contexto (elenco / escenas / atrezzo):",
  "character.system": "Eres diseñador de personajes de drama corto para vídeo IA. Devuelve SOLO un JSON. spokenLanguages = array BCP-47.",
  "character.draftLabel": "Campos actuales del perfil:",
  "character.soulLabel": "soul.md / biblia vinculada:",
  "character.createLabel": "Idea de personaje:",
  "character.emptyPolish": "(pulir e integrar soul)",
  "character.closing": "JSON completo ahora. Claves: {{keys}}.",
  "scene.system": "Eres diseñador de localizaciones. Biblia del lugar + guion de esta escena. SOLO JSON.",
  "scene.draftLabel": "Campos actuales de la escena:",
  "scene.charsLabel": "Personajes de la historia:",
  "scene.propsLabel": "Atrezzo de la historia:",
  "scene.priorLabel": "Escenas previas (continuidad):",
  "scene.createLabel": "Idea de escena:",
  "scene.emptyPolish": "(pulir lugar + guion)",
  "scene.closing": "JSON completo. Claves: {{keys}}.",
  "prop.system": "Eres diseñador de atrezzo. SOLO un JSON. Aspecto, material y estado concretos.",
  "prop.draftLabel": "Campos actuales del atrezzo:",
  "prop.createLabel": "Idea de atrezzo:",
  "prop.emptyPolish": "(pulir aspecto del atrezzo)",
  "prop.closing": "JSON completo. Claves: {{keys}}.",
  "prop.fallbackName": "Atrezzo",
  "action.system": "Eres director de movimiento. SOLO JSON válido. Cuerpo, tempo, peso, trayectorias.",
  "action.storyContext": "Contexto de historia (opcional): {{title}}",
  "action.styleNote": "Nota de estilo: {{style}}",
  "action.existingDraft": "Borrador existente a pulir:",
  "action.userIdea": "Idea del usuario: {{idea}}",
  "action.closing": "Solo JSON. Claves: {{keys}}.",
  "profile.mustEveryKey": "DEBES emitir CADA clave de esta lista: {{keys}}.",
  "profile.valuesAreStrings": "Cada valor DEBE ser una cadena JSON. Vacío solo si es desconocido.",
  "profile.visualTagsRule": "visualTags: una cadena separada por comas. NUNCA un array JSON.",
  "profile.fillConcrete": "Rellena con detalle concreto para continuidad.",
  "common.rules": "Reglas:",
  "common.none": "(ninguno)",
  "intro.soul": "soul.md (fuente de interpretación/identidad):\n{{soul}}",
  "intro.matchBible": "(seguir la biblia del personaje)",
  "invent.sources": "Fuentes de verdad, en orden: (1) idea/petición, (2) formulario, (3) extras solo si están en ESTE prompt, (4) imagen adjunta.",
  "invent.create": "Modo crear: inventa con libertad desde la idea/imagen; no dejes claves obligatorias vacías.",
  "invent.improve": "Modo mejorar: pule y completa el borrador; no cambies la identidad salvo petición.",
  "invent.noImport": "NO importes identidad, trama, clima, oficio, lugar, época o estilo de lo que no esté en este prompt.",
  "invent.storyBlock": "Si hay bloque de historia/estilo, úsalo solo para continuidad; no anules la idea explícita.",
  "character.keysLead": "SOLO un JSON con claves: {{keys}}",
  "character.ruleSpoken": "spokenLanguages: array BCP-47 de idiomas que HABLA. [] si no verbal.",
  "character.ruleIdentity": "Identidad coherente en láminas y vídeo.",
  "scene.keysLead": "SOLO un JSON con claves: {{keys}}",
  "scene.suggestLead": "Propón una LOCALIZACIÓN lista como escena nº {{n}} de \"{{title}}\".",
  "scene.suggestPlotFocus": "Foco argumental: {{label}}",
  "scene.suggestStyle": "Estilo: {{style}}",
  "scene.suggestExisting": "Localizaciones ya existentes: {{titles}}",
  "scene.suggestChars": "Personajes (contexto):",
  "scene.suggestProps": "Atrezzo (contexto):",
  "scene.suggestSegment": "Detalle del segmento:",
  "scene.suggestBeats": "Escenas / beats:",
  "scene.suggestClosing": "Devuelve el JSON completo. Diseña un lugar reutilizable y distinto.",
  "scene.fallbackName": "Localización",
  "scene.ideaFromImage": "Inventa el perfil completo de localización a partir de la foto adjunta.",
  "scene.polishIdea": "Pulir",
  "prop.keysLead": "SOLO un JSON con claves: {{keys}}",
  "action.fieldsLead": "Campos: {{keys}}.",
  "soul.system": "Escribes soul.md de producción. SOLO markdown completo. Respeta spokenLanguages. Escribe en el idioma de la interfaz.",
  "soul.improveMode": "MODO MEJORAR: fusiona perfil + soul existente en un soul.md completo.",
  "soul.createMode": "Crea un soul.md completo a partir de este perfil (no inventes a otra persona):",
  "soul.profileFields": "Campos del perfil:",
  "soul.existing": "soul.md existente (fusiona; no descartes detalle útil):",
  "soul.userRequest": "Petición del usuario: {{request}}",
  "soul.extraContext": "Contexto adicional (útil sí; gana el perfil):",
  "soul.returnOnly": "Devuelve solo el markdown del soul.md.",
  "wardrobe.system": "Eres consultor de vestuario. SOLO un JSON. artStyle debe ser uno de: {{styleIds}}. Materiales y silueta concretos. Nunca erotices menores.",
  "wardrobe.improveMode": "MODO MEJORAR / SUGERIR: usa TODOS los campos y el contexto argumental.",
  "wardrobe.characterForm": "Personaje (formulario completo):",
  "wardrobe.soulExcerpt": "Extracto soul.md:\n{{soul}}",
  "wardrobe.userRequest": "Petición: {{request}}",
  "wardrobe.storyContext": "Contexto de producción (úsalo si está; no inventes otro mundo):",
  "wardrobe.style": "estilo: {{style}}",
  "wardrobe.segment": "Segmento elegido: {{label}}",
  "wardrobe.sceneContext": "Escena / beat:",
  "wardrobe.noScenes": "(aún no hay escenas)",
  "wardrobe.proposeNew": "Propón un look NUEVO que encaje (no dupliques).",
  "fill.system": "Completas campos vacíos. SOLO JSON con estas claves: {{keys}}. Cada valor es una cadena no vacía. Nunca un array.",
  "fill.userPartial": "Perfil parcial (no contradigas):",
  "fill.userOnly": "Rellena SOLO estas claves: {{keys}}.",
  "fill.userReturn": "JSON solo con esas claves; valores no vacíos.",
  "imageGen.multiRef": "{{n}} stills extra: la primera es la base; mantén la identidad en todas.",
  "residual.sceneLink": "Escena {{n}}: {{short}}",
  "residual.beatSegment": "Pulso {{n}} · {{who}}{{tail}}",
  "residual.unknown": "Desconocido",
  "residual.story": "Historia",
  "beat.mood": "【ÁNIMO】 {{text}}",
  "beat.atmo": "【ATMÓSFERA】 {{text}}",
  "beat.camera": "【CÁMARA】 {{text}}",
  "beat.sfx": "【SFX】 {{text}}",
  "beat.action": "【ACCIÓN】 {{text}}",
  "beat.actionWho": "【ACCIÓN｜{{who}}】 {{text}}",
  "beat.expr": "【EXPRESIÓN】 {{text}}",
  "beat.exprWho": "【EXPRESIÓN｜{{who}}】 {{text}}",
  "beat.dialogue": "【DIÁLOGO｜{{who}}】 {{body}}",
  "beat.dialogueTone": "【DIÁLOGO｜{{who}}｜{{tone}}】 {{body}}",
  "beat.whoUnknown": "sin nombre",
  "beat.template": "【ÁNIMO】tenso, indeciso\n【ATMÓSFERA】luz cálida en la rendija de la puerta; lluvia en el suelo\n【CÁMARA】plano medio, empuje hacia las manos\n【SFX】lluvia, roce de tela\n【ACCIÓN｜Nombre】se quita el casco; mira la luz de la puerta; la mano entra en el bolsillo del abrigo\n【EXPRESIÓN｜Nombre】ceño fruncido, el aliento se corta\n【DIÁLOGO｜Nombre｜bajo, ronco】Otra vez llueve…\n【DIÁLOGO｜Nombre｜aparte】（pausa）¿Sigues… ahí?",
  "vision.preamble": "Hay un still adjunto. Rellena TODOS los campos de este {{what}} sobre todo DESDE LA IMAGEN.",
  "vision.character": "identidad (nombre, aspecto, vestuario, edad, género, tags)",
  "vision.scene": "localización (título, descripción, luz, ánimo, atrezzo, tags)",
  "vision.prop": "atrezzo (nombre, descripción, material, tamaño, estado, tags)",
  "vision.action": "acción (nombre, descripción, tempo, intención, cámara, tags)",
  "vision.costume": "vestuario (nombre, descripción completa)",
  "still.header": "UN SOLO FOTOGRAMA CLAVE para continuidad de vídeo (no un tablero multipanel). Un fotograma héroe que coincida con el plano previsto. Sin texto, logos, marcas ni UI.",
  "still.revision": "MEJORA DEL USUARIO PARA ESTE STILL (obligatoria): {{notes}}",
  "still.regenTask": "TAREA: revisa el prompt de director imagen a vídeo y mantenlo usable como brief de fotograma fijo.",
  "still.userImprove": "PETICIÓN DE MEJORA:\n{{notes}}",
  "still.currentPrompt": "Prompt profesional actual:",
  "still.hardRules": "REGLAS FIRMES (al final; no las debilites):",
  "mediaGen.writeOne": "Escribe UN prompt final de imagen para un still de drama corto.",
  "mediaGen.returnOnly": "SOLO el texto del prompt — sin markdown.",
  "mediaGen.singleComposite": "Describe UNA sola imagen compuesta.",
  "mediaGen.lockRefs": "Las imágenes adjuntas son la verdad visual (orden Ref#). No inventes otra persona, tienda u objeto.",
  "mediaGen.videoSystem": "Eres redactor de prompts de director imagen a vídeo para cortos. Devuelve un solo cuerpo. Usa la duración real de los materiales. Solo hechos de los materiales. Si hay un bloque de plantilla de cámara, obedece; no vuelvas al push-in o handheld genérico. Pon las reglas firmes al final si hay.",
  "mediaGen.videoMerge": "Fusiona los materiales en UN prompt de vídeo.",
  "mediaGen.videoInclude": "Incluye: bloqueo de identidad, cámara, interpretación/diálogo, ritmo, luz.",
  "mediaGen.videoFacts": "Solo hechos de materiales y seed. Nada de Demo.",
  "mediaGen.videoNoSwap": "Con refs, no cambies actor, localización ni atrezzo.",
  "mediaGen.videoHardRules": "REGLAS FIRMES al final si hay.",
  "mediaGen.imageSystem": "Eres director de prompts de still / tablero multipanel para cortos. Devuelve solo el cuerpo — sin vallas, título ni explicación. Usa solo hechos de los materiales; no importes un mundo de muestra. Si hay plantilla de cámara, obedece; no vuelvas al push-in genérico. Pon las reglas firmes al final si hay.",
  "mediaGen.imageMergeStills": "Fusiona materiales y stills en UN prompt de imagen.",
  "mediaGen.imageMergeText": "Fusiona los textos en UN prompt de imagen.",
  "mediaGen.imagePriority": "Prioridad: caras/vestuario/lugares/atrezzo de las imágenes.",
  "mediaGen.imageNoSwap": "No sustituyas por otro famoso o set ajeno si hay stills de elenco.",
  "mediaGen.imageFacts": "Solo hechos de materiales y seed.",
  "mediaGen.imageLayout": "Si hay multipanel, conserva el recuento exacto.",
  "mediaGen.imagePackage": "Si hay LAYOUT, el prompt DEBE aplicar ese layout exacto.",
  "mediaGen.imageHardRules": "REGLAS FIRMES al final si hay.",
  "mediaGen.directorFallback": "IMAGEN-A-VÍDEO: anima este fotograma fijo. Bloquea identidad, vestuario, set y encuadre.",
  "comic.taskHint": "Historia «{{title}}», página de cómic {{n}}: una página terminada con exactamente {{count}} viñeta(s). Identidad, vestuario y lugar continuos en toda la página. Sin marca de agua ni marco de interfaz.",
  "comic.panelCount": "El recuento de viñetas es fijo: exactamente {{n}}.",
  "comic.lockSplash": "Bloqueo de maquetación: una viñeta a página completa. Prohibido: marcos extra, divisiones, collage.",
  "comic.lockYonkoma": "Bloqueo: 4-koma vertical, 4 filas × 1 columna, de arriba abajo. Prohibido: 2×2 o tira horizontal.",
  "comic.lockGrid2x2": "Bloqueo: 2 filas × 2 columnas. Prohibido: tira, 2×3, splash a página completa.",
  "comic.lockGrid2x3": "Bloqueo: 2 filas × 3 columnas. Arriba 1-2-3, abajo 4-5-6. Prohibido: 2×2 o 3×3.",
  "comic.lockGrid3x3": "Bloqueo: 3 filas × 3 columnas = nueve viñetas. Prohibido: 2×2, 2×3 o menos.",
  "comic.lockStrip": "Bloqueo: una sola fila horizontal con exactamente {{n}} viñetas. Prohibido: varias filas.",
  "comic.layoutSplash1": "Una página alta: exactamente una viñeta a sangrado completo, sin canalillos ni marcos extra.",
  "comic.layoutStrip2": "Una página apaisada: dos viñetas iguales lado a lado, canalillos blancos gruesos.",
  "comic.layoutStrip3": "Una página apaisada: tres viñetas iguales en una fila, canalillos blancos gruesos.",
  "comic.layoutYonkoma": "Una página alta: 4-koma vertical (4×1), canalillos blancos gruesos, lectura de arriba abajo.",
  "comic.layoutGrid2x2": "Una página cuadrada: cuadrícula 2×2, exactamente cuatro viñetas, canalillos blancos, izquierda→derecha y luego arriba→abajo.",
  "comic.layoutStrip4": "Una página apaisada ancha: cuatro viñetas en una fila, canalillos blancos gruesos.",
  "comic.layoutGrid2x3": "Una página apaisada: exactamente seis viñetas, 2 filas × 3 columnas (arriba 1-2-3, abajo 4-5-6), canalillos blancos, izquierda→derecha y luego arriba→abajo.",
  "comic.layoutGrid3x3": "Una página cuadrada: cuadrícula 3×3, exactamente nueve viñetas, canalillos blancos, izquierda→derecha y luego arriba→abajo.",
  "comic.layoutWidePlusTwo": "Una página alta: viñeta ancha arriba (~60 %) y dos pequeñas abajo, canalillos blancos gruesos.",
  "comic.layoutTwoPlusWide": "Una página alta: dos viñetas pequeñas arriba y una ancha de cierre abajo (~60 %), canalillos blancos gruesos.",
  "comic.layoutTallLeftTwo": "Una página alta: viñeta alta a toda altura a la izquierda y dos apiladas a la derecha, canalillos blancos gruesos.",
  "comic.layoutHeroPlusThree": "Una página alta: viñeta ancha arriba y tres pequeñas en una fila abajo, canalillos blancos gruesos.",
  "comic.layoutFocusQuad": "Una página alta: media arriba a la izquierda, dos pequeñas apiladas a la derecha, grande abajo, canalillos blancos gruesos.",
  "comic.layoutStaggerFour": "Una página alta: 2+2 escalonado — arriba ancha+estrecha, abajo estrecha+ancha, canalillos blancos gruesos.",
  "comic.layoutDiagPairPlus": "Una página alta: la mitad superior se parte en diagonal en dos cuñas; abajo un rectángulo ancho, canalillos blancos gruesos.",
  "comic.layoutHeroPlusFour": "Una página alta: viñeta ancha arriba y cuatro pequeñas en 2×2 abajo, canalillos blancos gruesos.",
  "comic.lockWidePlusTwo": "Bloqueo: arriba una viñeta ancha. Abajo exactamente dos pequeñas. Prohibido: tres tiras iguales o 2×2.",
  "comic.lockTwoPlusWide": "Bloqueo: dos pequeñas arriba, una ancha abajo. Prohibido: tres tiras iguales o 2×2.",
  "comic.lockTallLeftTwo": "Bloqueo: la izquierda ocupa toda la altura. Derecha: dos apiladas. Prohibido: 2×2 igual o tira horizontal.",
  "comic.lockHeroPlusThree": "Bloqueo: mitad superior una ancha. Abajo exactamente tres pequeñas. Prohibido: 2×2 o cuatro iguales.",
  "comic.lockFocusQuad": "Bloqueo: media arriba izquierda, dos pequeñas apiladas, grande abajo. Prohibido: 2×2 igual.",
  "comic.lockStaggerFour": "Bloqueo: tamaños escalonados — arriba ancha+estrecha, abajo estrecha+ancha. Prohibido: cuatro cuadrados iguales.",
  "comic.lockDiagPairPlus": "Bloqueo: arriba dos cuñas en diagonal; abajo un rectángulo ancho. Prohibido: tres tiras o 2×2.",
  "comic.lockHeroPlusFour": "Bloqueo: ancha arriba; 2×2 de cuatro abajo. Exactamente cinco. Prohibido: 3×3 o 2×2 de página entera.",
  "comic.readingYonkoma": "Lectura: solo de arriba abajo (4-koma vertical).",
  "comic.readingWidePlusTwo": "Lectura: primero la ancha de arriba, luego las dos pequeñas de izquierda a derecha.",
  "comic.readingTwoPlusWide": "Lectura: izquierda y derecha arriba, luego la ancha de abajo.",
  "comic.readingTallLeftTwo": "Lectura: la alta de la izquierda, luego arriba derecha, luego abajo derecha.",
  "comic.readingHeroPlusThree": "Lectura: la ancha de arriba, luego las tres pequeñas de izquierda a derecha.",
  "comic.readingFocusQuad": "Lectura: media arriba izquierda, las dos pequeñas de arriba abajo, luego la grande de abajo.",
  "comic.readingStaggerFour": "Lectura: arriba izquierda, arriba derecha, abajo izquierda, abajo derecha.",
  "comic.readingDiagPairPlus": "Lectura: cuña superior izquierda, cuña inferior derecha, luego la ancha de abajo.",
  "comic.readingHeroPlusFour": "Lectura: la ancha de arriba, luego las cuatro pequeñas izquierda→derecha y arriba→abajo.",
  "comic.readingOrder": "Lectura: izquierda → derecha, luego arriba → abajo (4-koma vertical: solo arriba → abajo).",
  "comic.panelNumbers": "Números pequeños 1–{{n}} arriba a la izquierda de cada viñeta.",
  "comic.panelLine": "Viñeta {{i}}/{{n}} ({{label}}): {{cap}}",
  "comic.panelEmpty": "Viñeta {{i}}/{{n}} ({{label}}): un instante de historia distinto y seguido.",
  "comic.identity": "Misma identidad, vestuario y lugar en todas las viñetas de esta página.",
  "comic.finished": "Es una página de cómic terminada, no un collage de fotos ni un mockup de interfaz.",
  "comic.layoutLead": "Maquetación: {{layout}}",
  "comic.prevPage": "Página anterior. Conserva identidad, vestuario y lugar; no copies la cuadrícula anterior.",
  "comic.ownPage": "Render existente de esta página. Úsalo como base de identidad / maquetación al revisar.",
  "comic.galleryRef": "Still de identidad (elenco o set). Haz coincidir caras, vestuario y lugar.",
  "comic.profileLine": "Página de cómic {{n}} de la historia «{{title}}».",
  "comic.styleBible": "Nota de estilo: {{note}}",
  "comic.artMedium": "Estilo artístico: {{art}}",
  "comic.fallbackClose": "Página de cómic impresa y terminada. Canalillos blancos gruesos. Números pequeños. Sin marca de agua, UI ni collage de álbum.",
  "comic.hardRules": "Reglas férreas",
  "comic.introTask": "IMAGEN-A-VÍDEO: anima la página de cómic terminada de «{{title}}», página {{n}}, exactamente {{count}} viñeta(s). Bloquea identidad, vestuario y maquetación a la imagen adjunta.",
  "comic.introLock": "Bloqueo: mismas caras, ropa, lugares, canalillos y números que la imagen. No inventes otra página ni otra persona.",
  "comic.introLayout": "Mantén esta maquetación: {{layout}}",
  "comic.introCamera": "Cámara: empuje lento o paneo suave en el orden de lectura. Solo movimiento de papel. Sin corte a otra maquetación.",
  "comic.introClose": "Sin marca de agua ni marco de interfaz; no añadas subtítulos además de los globos ya dibujados.",
  "comic.dramaStillLock": "Bloquea identidad, vestuario y lugar a la lámina adjunta, pero rueda un plano de corto en vivo, no un barrido sobre papel impreso.",
  "comic.dramaCamera": "Cámara y actuación: ritmo de corto dramático, interpretación clara, sincronía de labios con las líneas de las viñetas. Continúa la página anterior si hay imagen.",
  "comic.formatLockTall": "Formato de página: la plancha entera debe ser vertical 9:16. Sin composición apaisada.",
  "comic.formatLockSquare": "Formato de página: la plancha entera debe ser cuadrada 1:1.",
  "comic.formatLockWide": "Formato de página: la plancha entera debe ser horizontal 16:9.",
  "art.photoCinematic": "Medio obligatorio: fotograma cinematográfico fotorrealista. Cámara real, materiales naturales, etalonaje de cine. Debe parecer una foto o un fotograma. Prohibido: anime, cel, ilustración 2D, contorno cartoon, arcilla, CGI plástico.",
  "art.photoPortrait": "Medio obligatorio: retrato de estudio fotorrealista. Luz de softbox, nitidez de headshot comercial. Debe ser una fotografía. Prohibido: anime, tinta de cómic, juguete 3D, cel plano.",
  "art.photoDocumentary": "Medio obligatorio: foto documental fotorrealista. Luz natural, texturas honestas. Debe parecer tomada con cámara real. Prohibido: anime, CGI estilizado, ilustración.",
  "art.cgiFilm": "Medio obligatorio: personaje 3D CGI de calidad cinematográfica. Materiales PBR, brillos con ray tracing. Debe verse renderizado 3D, no foto real ni anime 2D. Prohibido: foto en vivo, lineart anime, tinta plana de cómic.",
  "art.cgiStylized": "Medio obligatorio: 3D estilizado premium (CGI de largometraje). Formas legibles, PBR suave. Debe ser CGI 3D. Prohibido: live fotorrealista, cel 2D, cómic a lápiz.",
  "art.cgiClay": "Medio obligatorio: personaje 3D de arcilla / escultura. Arcilla mate, formas esculpidas. Debe leerse como escultura de arcilla. Prohibido: foto de piel, cel anime, cómic a tinta.",
  "art.animeModern": "Medio obligatorio: anime de TV japonés moderno 2D. Línea digital limpia, cel suave, ojos y mechones anime. Toda la imagen debe ser anime 2D. Prohibido: foto, poros reales, render 3D, tinta western sola, óleo.",
  "art.animeShonen": "Medio obligatorio: visual clave shonen 2D. Trazo fuerte, cel contrastado, ojos anime nítidos. Debe ser shonen 2D. Prohibido: foto, CGI 3D, acuarela sola.",
  "art.animeShoujo": "Medio obligatorio: anime shoujo 2D. Línea delicada, degradados suaves, ojos luminosos. Debe ser shoujo. Prohibido: foto, 3D duro, tinta de cómic áspera.",
  "art.animeGekiga": "Medio obligatorio: anime gekiga / realista 2D. Línea madura, paleta contenida, claramente 2D. Prohibido: foto en vivo, chibi, CGI 3D puro.",
  "art.animeChibi": "Medio obligatorio: chibi / superdeformado 2D. Cabeza grande, cuerpo pequeño, rasgos simplificados. Debe ser chibi. Prohibido: proporciones fotorrealistas, 3D realista, live detallado.",
  "art.donghua": "Medio obligatorio: key art de donghua chino. Traje refinado, silueta elegante, 2D o 2,5D. Debe leerse como donghua. Prohibido: live de Hollywood, cómic de periódico western solo.",
  "art.manhwa": "Medio obligatorio: manhwa / webtoon coreano a color. Pintura digital suave, contornos limpios, pelo brillante. Debe ser manhwa 2D. Prohibido: foto, arcilla 3D, tinta de superhéroe sola.",
  "art.comicWestern": "Medio obligatorio: cómic occidental. Tinta segura, aplanados o cel limitado, formas gráficas. Debe ser ilustración de cómic. Prohibido: foto, solo ojos anime, render de arcilla.",
  "art.conceptGame": "Medio obligatorio: concept art de personaje AAA. Hoja pintada, silueta fuerte. Debe parecer concept, no captura ni foto. Prohibido: retrato foto puro, solo chibi.",
  "art.illustrationSoft": "Medio obligatorio: ilustración digital suave. Pincel delicado, acabado de álbum. Debe ser ilustración pintada. Prohibido: foto de cámara, cel duro, arcilla 3D.",
  "mediaGen.polishTask": "Tarea: {{hint}}",
  "mediaGen.polishKind": "Tipo: {{kind}}",
  "mediaGen.polishMaterials": "—— Materiales ——",
  "mediaGen.polishEndMaterials": "—— Fin de materiales ——",
  "mediaGen.polishRef": "Ref. n.º{{n}} — {{title}}",
  "mediaGen.videoTaskHint": "Escribe una consigna de director imagen-a-vídeo desde el fotograma clave ({{kind}}). Cámara, actuación y ritmo; bloquea el fotograma.",
  "mediaGen.directorFallbackCam": "Cámara e interpretación claras; sin subtítulos ni marca de agua.",
  "charIntro.task": "IMAGEN-A-VÍDEO: anima a la misma persona del still en un autocasting breve.",
  "charIntro.identityLock": "BLOQUEO DE IDENTIDAD: misma cara, pelo, cuerpo, edad, vestuario y colores.",
  "charIntro.personality": "Personalidad / vibe: {{personality}}.",
  "charIntro.backstory": "Trasfondo: {{backstory}}.",
  "charIntro.relationships": "Relaciones: {{relationships}}.",
  "charIntro.soul": "Extracto soul (fuente de interpretación): {{soul}}",
  "charIntro.performance": "Manerismos: {{manner}}.",
  "charIntro.speech": "Habla: la boca se mueve como presentándose; voz: {{voice}}.",
  "charIntro.beat": "Idle natural → sonrisa o asentimiento → gesto breve → hold.",
  "charIntro.lighting": "Luz coherente con el still; sin texto, logos ni extra gente.",
  "sceneIntro.task": "IMAGEN-A-VÍDEO: anima el mismo lugar como plano de establecimiento.",
  "sceneIntro.spaceLock": "BLOQUEO DE ESPACIO: misma arquitectura, materiales, letreros, planta y color.",
  "sceneIntro.name": "Nombre del lugar: {{name}}.",
  "sceneIntro.place": "Descripción: {{place}}.",
  "sceneIntro.spaceType": "Tipo de espacio: {{type}}.",
  "sceneIntro.time": "Hora del día: {{time}}.",
  "sceneIntro.weather": "Clima: {{weather}}.",
  "sceneIntro.moodLight": "Ánimo: {{mood}}. Luz: {{lighting}}.",
  "sceneIntro.palette": "Paleta: {{palette}}.",
  "sceneIntro.setDressing": "Atrezzo de set: {{set}}.",
  "sceneIntro.tags": "Tags visuales: {{tags}}.",
  "sceneIntro.art": "Estilo: {{art}}.",
  "sceneIntro.ambient": "Ambiente (sin texto UI): {{sound}}.",
  "sceneIntro.scriptCue": "Pista de beat (solo atmósfera): {{cue}}.",
  "sceneIntro.camera": "Cámara: {{camera}}; movimiento continuo. No añadas caras, logos ni texto salvo que los materiales ya los muestren.",
  "sceneIntro.beat": "Establecer → vida ambiental sutil → hold.",
  "propIntro.task": "IMAGEN-A-VÍDEO: anima el mismo atrezzo como intro de producto.",
  "propIntro.objectLock": "BLOQUEO DE OBJETO: misma silueta, materiales, colores, grabados y desgaste.",
  "propIntro.name": "Nombre: {{name}}.",
  "propIntro.look": "Aspecto: {{look}}.",
  "propIntro.material": "Composición: {{material}}.",
  "propIntro.size": "Tamaño: {{size}}.",
  "propIntro.condition": "Estado: {{condition}}.",
  "propIntro.tags": "Tags: {{tags}}.",
  "propIntro.art": "Estilo: {{art}}.",
  "propIntro.camera": "Órbita suave o travelling lento en mesa limpia; luz coherente.",
  "propIntro.beat": "Hold → brillo / microgiro → hold.",
  "propIntro.noHands": "Sin manos ni caras nuevas si no están en el still; sin texto ni extras.",
  "costumeIntro.task": "IMAGEN-A-VÍDEO: anima el mismo look como intro de vestuario.",
  "costumeIntro.wardrobeLock": "BLOQUEO DE VESTUARIO: misma silueta, telas, colores, capas y accesorios.",
  "costumeIntro.identityOrProduct": "Si hay persona: bloquea cara/cuerpo; si maniquí/plano: encuadre de producto.",
  "costumeIntro.name": "Nombre del look: {{name}}.",
  "costumeIntro.desc": "Vestuario: {{look}}.",
  "costumeIntro.art": "Estilo: {{art}}.",
  "costumeIntro.camera": "Leve travelling u órbita; luz de moda coherente.",
  "costumeIntro.beat": "Hold → caída de tela / brillo de herrajes → hold.",
  "costumeIntro.forbid": "Sin caras nuevas, texto, logos ni pose erótica.",
  "costumeIntro.fallbackName": "Estilo",
  "actionIntro.lead": "Vídeo demo de acción \"{{name}}\".",
  "actionIntro.intention": "Intención: {{intention}}",
  "actionIntro.body": "Cuerpo/tempo: {{body}}",
  "actionIntro.camera": "Cámara: {{camera}}",
  "actionIntro.closing": "Movimiento continuo, sin texto; sigue el still.",
  "sceneIntroPolish.task": "TAREA: intro de localización (imagen-a-vídeo).",
  "sceneIntroPolish.hasRef": "Still de lugar adjunto — bloquea la identidad ESPACIAL.",
  "sceneIntroPolish.noRef": "Sin still; bloquea a la biblia del lugar.",
  "sceneIntroPolish.dossier": "Dossier de localización:",
  "sceneIntroPolish.scriptCue": "pista de guion (solo atmósfera):\n{{script}}",
  "sceneIntroPolish.emptySet": "Set vacío; sin caras nuevas. Sin texto ni logos.",
  "propIntroPolish.task": "TAREA: intro héroe de atrezzo (imagen-a-vídeo).",
  "propIntroPolish.hasRef": "Still de atrezzo adjunto — bloquea el OBJETO.",
  "propIntroPolish.noRef": "Sin still; bloquea al dossier.",
  "propIntroPolish.dossier": "Dossier de atrezzo:",
  "propIntroPolish.noHands": "Sin manos ni caras nuevas. Sin texto ni logos.",
  "costumeIntroPolish.task": "TAREA: intro de vestuario (imagen-a-vídeo).",
  "costumeIntroPolish.hasRef": "Still adjunto — persona: identidad+ropa; maniquí: silueta y materiales.",
  "costumeIntroPolish.noRef": "Sin still; bloquea a la descripción.",
  "costumeIntroPolish.dossier": "Dossier de vestuario:",
  "costumeIntroPolish.fabric": "Caída sutil de tela; sin caras nuevas ni texto.",
  "actionIntroPolish.task": "TAREA: intro de guía de movimiento (imagen-a-vídeo).",
  "actionIntroPolish.hasRef": "Still adjunto — bloquea la identidad interpretativa.",
  "actionIntroPolish.templateKeepRules": "Borrador plantilla (mejora; REGLAS FIRMES al final):",
  "cover.posterLead": "PÓSTER / KEY ART profesional 16:9. No es mockup UI. Sin texto, logo ni marca.",
  "cover.titleMood": "Título (solo ánimo, no lo escribas en imagen): {{title}}.",
  "cover.styleBible": "Biblia de estilo: {{style}}",
  "cover.extraDir": "Dirección extra: {{idea}}",
  "cover.establishing": "Plano de establecimiento evocador para portada de biblioteca.",
  "cover.medium": "Respeta el medium; silueta fuerte.",
  "cover.editPrefix": "Edición de imagen: nueva composición de póster. Conserva identidad y ánimo. ",
  "cover.label": "Portada de historia",
  "costumeFill.system": "Eres diseñador de vestuario. SOLO JSON compacto. Si hay imagen, describe ESE outfit con fidelidad.",
  "costumeFill.idea": "Premisa: {{idea}}",
  "costumeFill.polish": "Pule el borrador de vestuario.",
  "costumeFill.required": "Claves: name, description, artStyle, hardRules. Faltar = inválido.",
  "costumeFill.fallbackName": "Estilo",
  "segment.entireStory": "Toda la historia (todas las escenas)",
  "segment.noStory": "Sin historia (solo ficha de personaje)",
  "vision.inventFromImage": "Describe e inventa un perfil completo de {{kind}} a partir de la foto adjunta.",
  "vision.polishAll": "Pule y fusiona todos los campos",
  "story.untitled": "Drama corto sin título",
  "action.castIdentityNote": "Stills de identidad ({{count}}): el rostro/cuerpo debe coincidir con las referencias de elenco en cada viñeta.",
  "tpl.system.polishOnly": "RECETA solo pulir: conserva identidad y mundo. Pule el texto. No inventes era, clima, oficio, lugar ni un mundo muestra. No inventes idioma hablado. No escribas REGLAS FIRMES por defecto en el perfil.",
  "tpl.system.fillBlanks": "RECETA solo vacíos: rellena SOLO claves vacías. No reescribas lo ya lleno. No inventes otro mundo.",
  "tpl.system.invent": "RECETA inventar: el usuario autorizó crear con libertad. Completa cada clave filmable. No importes Demo ni un mundo no implícito.",
  "tpl.system.fromStory": "RECETA desde historia: usa solo título/estilo/elenco/escenas de ESTA petición. En conflicto gana la idea del usuario.",
  "tpl.system.followAsset": "RECETA seguir activo: sigue el estilo ya dado. No fuerces cine, set vacío ni 6–10 s salvo que los materiales lo digan. Usa la duración real del clip.",
  "tpl.system.cinematicLock": "RECETA cine+anti-alucinación: look cinematográfico; set vacío; sin marcas, logos ni caras extra; dos manos/brazos/piernas salvo no humano.",
  "tpl.system.identityLock": "RECETA bloqueo de identidad: bloquea cara/cuerpo/ropa/lugar/atrezzo a los stills. No sustituyas persona, lugar u objeto.",
  "tpl.system.restyle": "RECETA restyle: misma persona. Vestuario, set y época pueden cambiar si el usuario lo pide. No cambies de persona.",
  "pipeline.character.system": "Refinas biblias de personaje para drama corto IA. 3–5 líneas por personaje: look, voz, motivo, gesto. Solo hechos de esta petición.",
  "pipeline.scene.system": "Expandes escenas a hojas de beats visuales. Usa la duración real de los materiales; no asumas 6–10 s. Solo escenas dadas.",
  "pipeline.props.system": "Refinas continuidad de atrezzo. Color, tamaño y cuándo aparece. No inventes atrezzo no listado.",
  "pipeline.script.system": "Eres guionista de drama corto. Un bloque compacto por escena para vídeo IA. Duración real; no fuerces 10 s. Formato:\n### SCENE <number> | id=<id>\n<script body>",
  "pipeline.script.noScenes": "(sin escenas — no inventes lugares)",
  "keyArt.task": "Fotograma clave {{n}} de la historia «{{title}}». Una imagen publicitaria terminada. Sin viñetas de cómic, sin números de viñeta, sin interfaz.",
  "keyArt.lockCover": "CARTEL DE PORTADA: arte clave apaisado para la ficha. Deja una franja segura para el título. Rostros legibles. No inventes un logotipo ni un bloque de créditos falso.",
  "keyArt.lockPoster": "CARTEL VERTICAL: un único one-sheet. El protagonista se lee en el teléfono. No pongas otros carteles dentro del encuadre.",
  "keyArt.lockStill": "FOTOGRAMA: un fotograma cinematográfico, como sacado del drama. Actuación natural, espacio real. No es un collage.",
  "keyArt.lockPromo": "ARTE PROMOCIONAL: personaje y mundo en el mismo encuadre. Silueta fuerte, un solo ánimo. No es una hoja de contactos.",
  "keyArt.lockSocial": "HISTORIA SOCIAL: fotograma vertical 9:16. Sujeto grande. Márgenes para texto en pantalla.",
  "keyArt.lockHeadshot": "PRIMER PLANO DEL PROTAGONISTA: un rostro de frente que llena el encuadre, idéntico a las referencias. Se permiten hombros. Nadie más.",
  "keyArt.lockBust": "PROMO DE BUSTO: de pecho hacia arriba, cuello del vestuario visible, mirada a cámara.",
  "keyArt.lockGroup": "REPARTO: todos los personajes nombrados en un encuadre, mismo mundo y misma luz. No omitas ni cambies un rostro.",
  "keyArt.formatLockTall": "BLOQUEO DE FORMATO: toda la imagen es un encuadre alto 9:16. Sin composición apaisada.",
  "keyArt.formatLockSquare": "BLOQUEO DE FORMATO: toda la imagen es un encuadre cuadrado 1:1.",
  "keyArt.formatLockWide": "BLOQUEO DE FORMATO: toda la imagen es un encuadre ancho 16:9.",
  "keyArt.methodFreshLock": "MÉTODO: generar una imagen nueva. Las referencias solo fijan identidad. No copies el recorte de una toma anterior.",
  "keyArt.methodEditLock": "MÉTODO: editar la imagen propia adjunta. Conserva la composición salvo que el brief pida lo contrario.",
  "keyArt.methodIdentityLock": "MÉTODO: fija los rostros a las referencias del personaje. Pose, recorte y vestuario pueden cambiar.",
  "keyArt.methodContinueLock": "MÉTODO: continúa desde la imagen anterior. Las mismas personas y el mismo lugar, el siguiente plano del mismo rodaje.",
  "keyArt.briefLine": "Brief de dirección: {{brief}}",
  "keyArt.beatLine": "Pulso vinculado: {{beat}}",
  "keyArt.close": "Imagen {{aspect}} terminada. Sin marca de agua, sin marco de interfaz, sin subtítulos extra.",
  "charIntro.manner": "Manerismos: {{manner}}.",
  "charIntro.cameraDefault": "Cámara de interpretación: push-in suave o handheld sutil; el personaje mira a cámara o ligeramente fuera de cámara.",
  "mediaGen.honorCameraTemplate": "Si los materiales incluyen un bloque de plantilla de cámara, sigue ese encuadre y movimiento al pie de la letra. No lo sustituyas por un push-in o handheld genérico.",
  "sceneIntro.cameraNotes": "Notas de cámara: {{camera}}.",
  "sceneIntro.cameraDefault": "Cámara: movimiento continuo suave. No añadas caras nuevas del elenco, logos ni superposiciones de texto salvo que los materiales ya los muestren.",
  "quality.family.photo": "Calidad: enfoque nítido en ojos o rasgos principales de cara/cabeza, microdetalle alto propio del medio fotorrealista, iluminación de estudio profesional de tres puntos salvo que el estilo indique otra, look de objetivo fijo (50–85 mm), sin desenfoque de movimiento, sin filtro de belleza que suavice el rostro, sin marca de agua ni texto.",
  "quality.family.cgi": "Calidad: presentación 3D limpia del personaje, materiales legibles (PBR), silueta de topología coherente, formas primarias nítidas, HDRI de estudio o luz CG de tres puntos, sin grano salvo estilo de arcilla, sin marca de agua ni texto, no es una fotografía real.",
  "quality.family.anime": "Calidad: oficio de lámina de diseño 2D limpio, grosor de línea coherente, modelo facial estable en todos los paneles, color cel o sombreado suave controlado, evita fotografía fotorrealista, evita look de acción real, evita sombreado SSS fotográfico 3D, sin marca de agua ni etiquetas de texto.",
  "quality.family.illust": "Calidad: claridad profesional de lámina de ilustración, diseño de personaje coherente, silueta y vestuario/materiales legibles, fondo de estudio neutro, sin marca de agua, sin subtítulos de interfaz.",
  "sheet.lock.lead": "Crea un still de referencia de personaje para continuidad de vídeo IA.",
  "sheet.lock.sexPrefix": "Bloqueo de sexo (máxima prioridad — moño, cara ovalada, piel clara, complexión delgada o túnicas no deben invertir el sexo): {{lock}}",
  "sheet.lock.identity": "Bloqueo de identidad: exactamente un sujeto personaje en cada panel (puede ser humano, animal, criatura, espíritu, robot u otra entidad diseñada — pero nunca cambies de especie ni de diseño a mitad de lámina).",
  "sheet.lock.noSecond": "No inventes un segundo personaje; mantén el mismo plan corporal, marcas, colores y diseño de cabeza en todos los paneles.",
  "sheet.lock.head": "Cabeza/rostro (o equivalente) debe permanecer coherente: mismos ojos o sensores, misma silueta de cabeza, mismos colores de superficie e identificadores clave.",
  "sheet.lock.camera": "Cámara: encuadre de referencia estable, verticales rectas, sin ojo de pez salvo que la maquetación pida un ángulo especial.",
  "sheet.lock.background": "Fondo: ciclorama de estudio limpio, continuo, gris claro o blanco hueso, vacío y uniforme; sin desorden salvo que la maquetación pida un detalle pequeño de vestuario/atrezzo.",
  "sheet.lock.forbidden": "Prohibido: marcas de agua, logos, pies de foto, texto, cromado de interfaz, extremidades extra aleatorias, extremos deformados (salvo que el plano sea intencionadamente solo manos/detalle).",
  "sheet.lock.subject": "Nombre/concepto del sujeto: {{name}}",
  "sheet.lock.age": "Edad o presentación de madurez: {{age}}",
  "sheet.lock.gender": "Género / presentación: {{gender}}",
  "sheet.lock.appearance": "Aspecto (debe coincidir exactamente): {{appearance}}",
  "sheet.lock.appearanceFaceOnly": "Aspecto — solo rostro / pelo / proporciones corporales (debe coincidir): {{appearance}}. Elimina de esta descripción cualquier ropa, abrigos, paraguas, bolsos, zapatos, joyas o atrezzo — no deben aparecer.",
  "sheet.lock.ignoreCostume": "Vestuario exterior / atrezzo: ignóralos por completo en esta lámina. Sin paraguas, bolso, abrigo ni artículos de moda. Solo placa de cuerpo o de capa base.",
  "sheet.lock.costume": "Vestuario / diseño exterior (debe coincidir exactamente): {{costume}}",
  "sheet.lock.tags": "Tags visuales: {{tags}}",
  "sheet.lock.tagsIdentity": "Tags visuales (solo identidad; descarta tags de ropa/atrezzo): {{tags}}",
  "sheet.lock.manner": "Solo pistas sutiles de pose/manerismo (no cambies la identidad): {{manner}}",
  "sheet.scaffold.repeatMedium": "Reitera: el medio de la imagen final debe ser exactamente el id de estilo \"{{id}}\" ({{family}}).",
  "sheet.scaffold.wardrobeTag": "Etiqueta de capa de vestuario: {{tag}}.",
  "sheet.scaffold.layoutLead": "Maquetación: {{layout}}",
  "sheet.scaffold.finalCheck": "Comprobación final: si la imagen parece el medio equivocado, regenera en el medio correcto: {{medium}}",
  "sheet.edit.task": "Tarea de edición de imagen / cambio de maquetación (máxima prioridad — léela entera):",
  "sheet.edit.target": "Id del paquete de lámina objetivo: \"{{id}}\". Capa de vestuario: {{tag}}.",
  "sheet.edit.ignoreLayout": "Ignora por completo la maquetación de la imagen fuente: recuento de paneles, canalillos, ángulos de cámara, recorte y encuadre de la fuente no deben copiarse.",
  "sheet.edit.ignoreWardrobe": "Ignora el vestuario/ropa de la fuente si entra en conflicto con la capa de vestuario objetivo de abajo.",
  "sheet.edit.keepIdentity": "Conserva solo la identidad del personaje de la fuente: diseño de rostro/cabeza, pelo, proporciones corporales, especie/plan corporal, marcas de piel o superficie, presentación de edad.",
  "sheet.edit.stripOuter": "Quita toda la ropa/armadura exterior de la fuente. En placas de cuerpo: solo malla integral tono piel. En capa base: solo ropa interior simple. No conserves el atuendo de la fuente.",
  "sheet.edit.applyProfileCostume": "Puedes aplicar la descripción de vestuario del perfil en el prompt del cuerpo; no te limites a recolorear o recortar los paneles de vestuario de la fuente.",
  "sheet.edit.changeMedium": "Cambia por completo el medio de render si hace falta para coincidir con el estilo artístico obligatorio.",
  "sheet.edit.noNewPerson": "No inventes un personaje distinto. No te limites a recortar, ampliar o recolorear la fuente.",
  "sheet.edit.newComposition": "Produce una composición de lámina de referencia enteramente nueva que coincida exactamente con el bloque de maquetación (recuento de paneles y poses).",
  "sheet.edit.checklist": "Lista final: (1) la identidad coincide con el rostro/cuerpo de la fuente (2) la maquetación coincide con el paquete \"{{id}}\", no con la lámina fuente (3) capa de vestuario {{tag}} (4) medio = {{style}}.",
  "sheet.wardrobe.nude": "Placa de producción de proporciones corporales para diseño de vestuario (no es contenido adulto, no es fotografía sin ropa): iluminación de estudio clínica y neutra, ciclorama gris liso, pose profesional de dibujo de figura. Sin fotografía de moda, sin estilismo de lencería, sin dormitorio ni set glamoroso. El sujeto lleva una malla integral mate tono piel sin costuras / traje base de cuerpo entero ceñido (o traje corporal mate sólido adecuado a la especie) que revela la silueta y las proporciones exactas — rostro y pelo visibles; sin vestuario exterior, sin logos, sin atrezzo, sin zapatos, sin accesorios. La malla es solo traje interior de producción (como una malla corporal de CG), nunca vestuario exterior. Conserva rostro, pelo, proporciones corporales y marcas de superficie para el vestuario CG posterior. Ignora cualquier descripción de vestuario exterior en esta lámina. Explícitamente vestido con malla — nunca sin ropa.",
  "sheet.wardrobe.halfBareUpper": "Referencia parcial de producción del torso superior para medidas de diseño de vestuario (solo personaje adulto; estudio clínico de figura; no erótico; no pornografía; no sugerente): iluminación de estudio clínica y neutra, ciclorama gris liso, pose de pie profesional de maniquí / estudio médico. Sin fotografía de moda, sin estilismo de lencería, sin set de dormitorio, sin cámara sexualizada. Mitad superior descubierta: torso, pecho, hombros, brazos y cuello al descubierto; rostro y pelo totalmente visibles. Mitad inferior cubierta solo con un bajo mate opaco simple, neutro o tono piel (shorts lisos, slip o envoltorio simple — cobertura de producción, no lencería de moda, sin encaje, sin transparencia). Sin prenda superior de vestuario exterior, sin sujetador como prenda de moda, sin atrezzo, sin zapatos, sin accesorios, sin logos. Conserva rostro, pelo, proporciones corporales y marcas de superficie para el vestuario CG / prueba de figurín posterior. Ignora cualquier descripción de vestuario exterior en esta lámina.",
  "sheet.wardrobe.halfBareLower": "Referencia parcial de producción de la mitad inferior para medidas de diseño de vestuario (solo personaje adulto; estudio clínico de figura; no erótico; no pornografía; no sugerente): iluminación de estudio clínica y neutra, ciclorama gris liso, pose de pie profesional de maniquí / estudio médico. Sin fotografía de moda, sin estilismo de lencería, sin set de dormitorio, sin cámara sexualizada. Mitad inferior descubierta: caderas, muslos, piernas y pies al descubierto; rostro y pelo totalmente visibles. Zonas íntimas solo: cobertura opaca mínima mate tono piel o neutra (slip simple — solo producción, no lencería de moda). Mitad superior cubierta solo con una prenda superior mate sólida neutra simple (camiseta de tirantes lisa, camiseta interior o envoltorio — cobertura de producción, sin estilismo de moda, sin logos). Sin vestuario exterior, sin atrezzo, sin zapatos, sin accesorios. Conserva rostro, pelo, proporciones corporales y marcas de superficie para el vestuario CG / prueba de figurín posterior. Ignora cualquier descripción de vestuario exterior en esta lámina.",
  "sheet.wardrobe.bare": "Referencia anatómica completa de producción para medidas de diseño de vestuario (solo personaje adulto; estudio clínico de figura; no erótico; no pornografía; no sugerente): iluminación de estudio clínica y neutra, ciclorama gris liso, pose de pie profesional de maniquí / estudio médico. Sin fotografía de moda, sin pose de lencería, sin set de dormitorio, sin cámara sexualizada. El sujeto está por completo sin prendas (forma corporal desnuda completa, o superficie desnuda adecuada a la especie) con solo rostro y pelo — sin ropa, sin coberturas parciales, sin vestuario exterior, sin atrezzo, sin zapatos, sin accesorios. Conserva rostro, pelo, proporciones corporales y marcas de superficie para el vestuario CG / prueba de figurín posterior. Ignora cualquier descripción de vestuario exterior en esta lámina.",
  "sheet.wardrobe.base": "Referencia de capa base de producción (ropa interior / capa base para cambio de vestuario, no erótico): solo ropa interior sólida neutra simple o cobertura base adecuada a la especie (p. ej. slip liso + camiseta interior, o envoltorio simple). Sin vestuario exterior, sin logos, sin estilismo de lencería de moda, sin pose sugerente. Luz de estudio clínica, fondo gris. Conserva la identidad para vestir trajes exteriores después. Ignora la descripción de vestuario exterior en esta lámina.",
  "sheet.wardrobe.costume": "Referencia de vestuario de producción: vestuario exterior completo según la descripción; materiales y silueta legibles para continuidad de vídeo.",
  "sheet.layout.bible": "Biblia de personaje apaisada 16:9 con exactamente tres paneles verticales iguales de izquierda a derecha: (1) cuerpo entero de pie de frente, pies visibles, brazos relajados; (2) cuerpo entero tres cuartos ~45°; (3) retrato de cabeza y hombros mirando a cámara. Cada figura llena su panel. Mismo rostro, pelo, cuerpo y vestuario en los tres. Canalillos nítidos, estudio limpio.",
  "sheet.layout.turnaround": "Rotación apaisada 16:9 con exactamente cuatro figuras de cuerpo entero a la misma escala: frente, perfil izquierdo 90°, espalda completa, perfil derecho 90°. Pose en A neutra / brazos relajados, pies plantados. Vestuario completo. Altura máxima de figura.",
  "sheet.layout.expression": "Cuadrado 1:1 compacto 2×2 de exactamente cuatro primeros planos de cabeza y hombros: neutro, sonrisa suave, ira, sorpresa. Cada rostro llena ~90 % de su celda; pelo y cuello idénticos. Sin cuerpo entero.",
  "sheet.layout.costume": "Tablero de vestuario alto 9:16: ~65 % superior con héroe de cuerpo entero grande en vestuario completo mirando a cámara; franja inferior exactamente dos recortes de detalle grandes (tejido/bolsillo + zapatos o accesorio característico). Materiales legibles.",
  "sheet.layout.identity_lock": "Bloqueo de identidad apaisado 16:9 con exactamente dos paneles: izquierda 60 % primer plano frontal grande; derecha 40 % rostro a tres cuartos. Maximiza el detalle facial para identidad de vídeo; sin cuerpo entero.",
  "sheet.layout.face_id": "Cuadrado 1:1 un solo retrato grande centrado de rostro frontal (o cabeza principal), torso superior incluido, mirando al objetivo. Rasgos primarios nítidos, enteramente en el medio artístico obligatorio. Un solo personaje.",
  "sheet.layout.hero": "Retrato héroe alto 9:16 de un solo cuerpo entero de pie, a la altura de los ojos, figura completa visible. Postura neutra centrada, fondo de estudio, vestuario completo, medio artístico obligatorio.",
  "sheet.layout.bust": "Busto medio cuadrado 1:1 (de pecho hacia arriba), cuerpo ligeramente a tres cuartos, rostro hacia cámara. Encuadre de diálogo, cuello del vestuario visible.",
  "sheet.layout.three_quarter": "Alto 9:16 cuerpo a tres cuartos (~de rodillas hacia arriba), cuerpo a 30–45°, rostro hacia cámara. Silueta de vestuario clara, manos visibles.",
  "sheet.layout.profile": "Alto 9:16 perfil puro de cuerpo entero lado izquierdo 90°, mirando a la izquierda, columna recta. Silueta verdadera; vestuario completo; un solo personaje.",
  "sheet.layout.back": "Alto 9:16 vista de espalda de cuerpo entero, de pie de espaldas a cámara, pelo y dorso del vestuario legibles. Lámina de continuidad de salida.",
  "sheet.layout.low_angle": "Alto 9:16 cuerpo entero heroico contrapicado, cámara cerca de la cintura mirando ligeramente hacia arriba, postura potente, rostro aún nítido, vestuario completo.",
  "sheet.layout.high_angle": "Alto 9:16 cuerpo a tres cuartos picado, cámara ligeramente por encima de la línea de ojos mirando hacia abajo, rostro legible, vestuario completo.",
  "sheet.layout.action": "Apaisado 16:9 fotograma congelado de acción de un personaje a mitad de movimiento (andar o alcanzar), nítido sin desenfoque de movimiento, vestuario completo, entorno gris suave.",
  "sheet.layout.dialogue": "Apaisado 16:9 encuadre de diálogo sobre el hombro: hombro suave en primer término del mismo personaje, rostro nítido al fondo mirando a la izquierda de cámara. Una sola identidad.",
  "sheet.layout.body_nude_turnaround": "Rotación de proporciones corporales apaisada 16:9 con exactamente cuatro figuras de cuerpo entero a la misma escala: frente, izquierda 90°, espalda, derecha 90°. Pose en A neutra, brazos ligeramente separados del torso para que la silueta se lea, pies plantados. Solo malla integral tono piel. Rostro y pelo coherentes.",
  "sheet.layout.body_nude_front": "Placa de proporciones corporales alta 9:16 de un solo cuerpo entero de frente, a la altura de los ojos, de cabeza a pies visible, brazos relajados. Proporciones claras para prueba de vestuario. Solo malla integral tono piel. Postura profesional neutra.",
  "sheet.layout.body_nude_t_pose": "Apaisado 16:9 un solo cuerpo entero en pose en T o pose en A (brazos horizontales o 30° hacia abajo), de frente, malla integral tono piel para referencia de rig. Pies a la anchura de hombros, rostro al frente, energía de maniquí clínico para la cadena de vestuario.",
  "sheet.layout.body_half_bare_turnaround": "Rotación de mitad superior descubierta apaisada 16:9 con exactamente cuatro figuras de cuerpo entero a la misma escala: frente, izquierda 90°, espalda, derecha 90°. Pose en A neutra, brazos ligeramente separados del torso para que la silueta superior se lea, pies plantados. Mitad superior descubierta + solo bajo simple. Rostro y pelo coherentes.",
  "sheet.layout.body_half_bare_front": "Placa alta 9:16 de un solo cuerpo entero de frente con mitad superior descubierta, a la altura de los ojos, de cabeza a pies visible, brazos relajados. Torso superior descubierto; solo bajo mate sólido simple. Proporciones claras. Postura profesional neutra.",
  "sheet.layout.body_half_bare_t_pose": "Apaisado 16:9 un solo cuerpo entero en pose en T o pose en A (brazos horizontales o 30° hacia abajo), de frente, mitad superior descubierta para referencia de rig. Solo bajo mate sólido simple. Pies a la anchura de hombros, rostro al frente, energía de maniquí clínico.",
  "sheet.layout.body_half_bare_lower_turnaround": "Rotación de mitad inferior descubierta apaisada 16:9 con exactamente cuatro figuras de cuerpo entero a la misma escala: frente, izquierda 90°, espalda, derecha 90°. Pose en A neutra, piernas ligeramente separadas para que la silueta inferior se lea, pies plantados. Mitad inferior descubierta + solo prenda superior simple. Rostro y pelo coherentes.",
  "sheet.layout.body_half_bare_lower_front": "Placa alta 9:16 de un solo cuerpo entero de frente con mitad inferior descubierta, a la altura de los ojos, de cabeza a pies visible, brazos relajados. Piernas descubiertas; solo prenda superior mate sólida simple. Proporciones claras. Postura profesional neutra.",
  "sheet.layout.body_half_bare_lower_t_pose": "Apaisado 16:9 un solo cuerpo entero en pose en T o pose en A (brazos horizontales o 30° hacia abajo), de frente, mitad inferior descubierta para referencia de rig. Solo prenda superior mate sólida simple. Pies a la anchura de hombros, rostro al frente, energía de maniquí clínico.",
  "sheet.layout.body_bare_turnaround": "Rotación anatómica completa apaisada 16:9 con exactamente cuatro figuras de cuerpo entero a la misma escala: frente, izquierda 90°, espalda, derecha 90°. Pose en A neutra, brazos ligeramente separados del torso para que la silueta se lea, pies plantados. Solo forma por completo sin prendas. Rostro y pelo coherentes.",
  "sheet.layout.body_bare_front": "Placa anatómica alta 9:16 de un solo cuerpo entero de frente, a la altura de los ojos, de cabeza a pies visible, brazos relajados. Proporciones claras para prueba de vestuario. Solo forma por completo sin prendas. Postura profesional neutra.",
  "sheet.layout.body_bare_t_pose": "Apaisado 16:9 un solo cuerpo entero en pose en T o pose en A (brazos horizontales o 30° hacia abajo), de frente, forma por completo sin prendas para referencia de rig. Pies a la anchura de hombros, rostro al frente, energía de maniquí clínico para la cadena de vestuario.",
  "sheet.layout.base_layer_turnaround": "Rotación de capa base apaisada 16:9 con exactamente cuatro figuras de cuerpo entero: frente, izquierda 90°, espalda, derecha 90°. Solo ropa interior / capa base simple (gris o beige sólido), sin vestuario exterior. Pose en A neutra.",
  "sheet.layout.base_layer_hero": "Alto 9:16 un solo cuerpo entero de frente solo con ropa interior base simple, postura de pie neutra, de cabeza a pies. Silueta limpia lista para superponer el vestuario exterior después.",
  "sheet.layout.costume_hero": "Alto 9:16 un solo cuerpo entero de frente con el vestuario exterior completo según el diseño, pose héroe de pie, de cabeza a pies, materiales legibles.",
  "sheet.layout.costume_turnaround": "Rotación de vestuario completo apaisada 16:9, exactamente cuatro figuras de cuerpo entero: frente, izquierda 90°, espalda, derecha 90°. Misma escala, pose en A, vestuario exterior completo incluidos zapatos y capas exteriores.",
  "sheet.layout.costume_detail_board": "Tablero de detalle cuadrado 1:1 con exactamente cuatro primeros planos grandes del vestuario completo: tejido, cierre/botón, zapatos o botas, accesorio característico. Sin cuerpo entero; fidelidad de material para continuidad de vestuario.",
  "sheet.layout.hands": "Estudio cercano cuadrado 1:1 de las manos del personaje (atrezzo pequeño opcional). Tono de piel/superficie coincide con la identidad; nudillos nítidos. Lámina de detalle de continuidad.",
  "sheet.layout.feet_shoes": "Cuadrado 1:1 con exactamente dos paneles grandes: izquierda pies desnudos (o patas/equivalente desnudas) de pie en suelo continuo; derecha zapatos/botas o calzado diseñado coincidente si el vestuario tiene alguno. Silueta clara para cambio de vestuario.",
  "sheet.layout.accessories": "Tablero de accesorios cuadrado 1:1: hasta cuatro primeros planos grandes estilo producto de sombrero, bolso, arma, joyas o atrezzo característico de la descripción de vestuario. Estudio limpio, sin cuerpo entero.",
  "sheet.layout.silhouette": "Alto 9:16 silueta sólida negra pura del personaje de cuerpo entero de frente sobre blanco puro o gris claro, sin detalle interno, contorno exterior legible para comprobar proporciones al cambiar vestuario. Segundo panel lateral tenue opcional si cabe el espacio — preferir una sola silueta frontal fuerte.",
  "plate.scene.emptySet": "Placa de localización vacía para continuidad de drama corto: sin rostros de personaje héroe, sin actores nombrados; como máximo siluetas lejanas minúsculas si hace falta escala. Conserva arquitectura, materiales, señalética y atrezzo de set clave.",
  "plate.scene.lock.lead": "Crea un still de referencia de lugar para continuidad de vídeo de drama corto IA.",
  "plate.scene.lock.identity": "Bloqueo de identidad espacial: misma arquitectura, materiales, señalética y lenguaje de planta en todos los paneles.",
  "plate.scene.lock.forbidden": "Prohibido: rostros de celebridad reconocibles, retratos de elenco nombrado, primeros planos héroe abarrotados, marcas de agua, superposiciones de texto de interfaz.",
  "plate.scene.lock.quality": "Calidad: materiales nítidos, verticales estables, fidelidad de fotografía de diseño de producción / arte conceptual profesional.",
  "plate.scene.lock.name": "Nombre del lugar: {{name}}",
  "plate.scene.lock.place": "Descripción del lugar: {{place}}",
  "plate.scene.lock.type": "Tipo de espacio: {{type}}",
  "plate.scene.lock.time": "Hora del día: {{time}}",
  "plate.scene.lock.weather": "Clima: {{weather}}",
  "plate.scene.lock.mood": "Ánimo: {{mood}}",
  "plate.scene.lock.lighting": "Diseño de luz: {{lighting}}",
  "plate.scene.lock.palette": "Paleta de color: {{palette}}",
  "plate.scene.lock.set": "Atrezzo de set: {{set}}",
  "plate.scene.lock.tags": "Tags visuales: {{tags}}",
  "plate.scene.scaffold.repeatMedium": "Reitera: el medio debe ser el id de estilo \"{{id}}\" ({{family}}).",
  "plate.scene.scaffold.layer": "Capa de placa: {{layer}}.",
  "plate.scene.scaffold.finalCheck": "Comprobación final: medio correcto {{style}}; vacío de rostros héroe; identidad del lugar bloqueada.",
  "plate.scene.edit.task": "Tarea de edición de imagen / cambio de estilo del lugar (máxima prioridad):",
  "plate.scene.edit.keep": "Conserva la identidad del lugar de la fuente: volumetría arquitectónica, materiales, señalética, planta de atrezzo de set clave.",
  "plate.scene.edit.change": "Cambia el medio y/o la maquetación de cámara según exija el paquete de placa de abajo.",
  "plate.scene.edit.forbid": "No inventes un lugar distinto. No añadas rostros de personaje héroe.",
  "plate.scene.layout.establishing": "Apaisado 16:9 plano de establecimiento del exterior completo o volumen maestro de la localización, hitos legibles, horizonte o línea de techo estable, profundidad cinematográfica.",
  "plate.scene.layout.hero_plate": "Apaisado 16:9 still héroe de localización — el encuadre de portada definitivo de este set. Composición fuerte, suelo de escenario o calle claro para el marcaje futuro.",
  "plate.scene.layout.three_quarter_space": "Apaisado 16:9 espacio a tres cuartos con marco de primer término, zona de interpretación en término medio, profundidad de fondo. Escenario de diálogo ideal vacío de rostros.",
  "plate.scene.layout.identity_lock": "Apaisado 16:9 con exactamente dos paneles iguales del mismo lugar: (1) ángulo clave frontal (2) tres cuartos ~45°. Mismos materiales, señalética, paleta.",
  "plate.scene.layout.low_angle": "Alto 9:16 contrapicado mirando hacia arriba a arquitectura / techo / dosel para escala dramática. Sin rostros.",
  "plate.scene.layout.high_angle": "Apaisado 16:9 planta picada / geometría de calle para referencia de marcaje. Vacío de rostros.",
  "plate.scene.layout.pov_enter": "Apaisado 16:9 POV de entrada en primera persona por un umbral o boca de callejón hacia la localización. Set vacío más allá del umbral.",
  "plate.scene.layout.over_shoulder_empty": "Apaisado 16:9 encuadre vacío sobre el hombro: solo silueta suave de hombro anónimo, fondo nítido de la localización para el marcaje de diálogo.",
  "plate.scene.layout.day_clear": "Apaisado 16:9 el mismo lugar bajo luz diurna clara, dirección solar natural, sombras legibles, superficies secas.",
  "plate.scene.layout.golden_hour": "Apaisado 16:9 el mismo lugar a la hora dorada: sombras largas cálidas, luz de recorte ámbar, ánimo romántico de drama corto, vacío de rostros.",
  "plate.scene.layout.night_neon": "Apaisado 16:9 el mismo lugar de noche con prácticos / neón / farolas, derrame cian-magenta opcional, humedad opcional, vacío de rostros.",
  "plate.scene.layout.rain_wet": "Apaisado 16:9 el mismo lugar bajo lluvia: asfalto mojado/reflejos, estrías de lluvia, etalonaje más frío, paraguas solo como atrezzo lejano, sin rostros.",
  "plate.scene.layout.fog_mood": "Apaisado 16:9 el mismo lugar en niebla/humo: capas de profundidad suaves, paleta apagada, ánimo de misterio, arquitectura aún legible, sin rostros.",
  "plate.scene.layout.set_dressing": "Tablero cuadrado 1:1 de atrezzo de set de mesa / mostrador / estantería con atrezzo clave de esta localización, sin personas.",
  "plate.scene.layout.material_board": "Tablero de continuidad de materiales cuadrado 1:1: muro, suelo, metal/madera, tela de esta localización. Detalle cercano, sin rostros, sin personajes de cuerpo entero.",
  "plate.scene.layout.signage_prop": "Primer plano cuadrado 1:1 de señalética / atrezzo hito legible para bloqueo de identidad del lugar. Formas de texto nítidas (pueden ser glifos inventados si hace falta). Sin rostros.",
  "plate.scene.layout.lighting_ref": "Apaisado 16:9 referencia de iluminación del set vacío: dirección de luz clave clara, relleno, prácticos, sin personajes.",
  "plate.prop.lock.lead": "Crea un still de referencia de atrezzo para continuidad de drama corto IA.",
  "plate.prop.lock.name": "Nombre del atrezzo: {{name}}",
  "plate.prop.lock.desc": "Descripción (debe coincidir): {{desc}}",
  "plate.prop.lock.material": "Composición: {{material}}",
  "plate.prop.lock.size": "Notas de tamaño: {{size}}",
  "plate.prop.lock.condition": "Estado/desgaste: {{condition}}",
  "plate.prop.lock.tags": "Etiquetas: {{tags}}",
  "plate.prop.lock.forbidden": "Prohibido: rostros de celebridad, marcas de agua, atrezzo extra ajeno que ensucie la identidad.",
  "plate.prop.scaffold.repeatMedium": "Reitera: el medio debe ser el id de estilo \"{{id}}\".",
  "plate.prop.scaffold.finalCheck": "Comprobación final: misma identidad de atrezzo; medio {{style}}.",
  "plate.prop.edit.task": "Edición de imagen / cambio de estilo del atrezzo:",
  "plate.prop.edit.keep": "Conserva la misma identidad de atrezzo de la imagen fuente (silueta, materiales, marcas).",
  "plate.prop.edit.change": "Cambia medio/cámara según se exija. No inventes un objeto distinto.",
  "plate.prop.layout.hero": "Cuadrado 1:1 still héroe de producto del atrezzo, centrado, ciclorama gris continuo limpio, materiales nítidos, sin rostros de personas, objeto completo visible.",
  "plate.prop.layout.three_quarter": "Cuadrado 1:1 vista a tres cuartos del mismo atrezzo, luz de estudio, silueta legible, sin manos salvo que hagan falta para escala.",
  "plate.prop.layout.detail": "Cuadrado 1:1 primer plano extremo del detalle característico del atrezzo (grabado, broche, pantalla, desgaste). Sin rostros.",
  "plate.prop.layout.material": "Placa de fidelidad de material cuadrada 1:1 de la superficie del atrezzo: textura de metal/madera/tela, sin personas de cuerpo entero.",
  "plate.prop.layout.in_hand_scale": "Apaisado 16:9 referencia de escala: mano anónima o silueta sosteniendo el atrezzo para el tamaño. Rostro fuera de encuadre o del todo anónimo. El atrezzo es el héroe.",
  "action.geometry.panelCount": "El recuento de viñetas es fijo: exactamente {{n}} viñeta(s). Cuéntalas: {{list}}.",
  "action.geometry.lockGrid2x3": "Bloqueo de maquetación (obligatorio): 2 filas × 3 columnas = seis viñetas en total. La fila superior debe contener las viñetas 1, 2 y 3. La fila inferior debe contener las viñetas 4, 5 y 6. Prohibido: cuadrícula 2×2, 4 viñetas, 3×2 mal contado, un solo encuadre héroe, collage con menos viñetas. Si te tienta dibujar solo cuatro viñetas — para y dibuja las seis.",
  "action.geometry.lockGrid2x2": "Bloqueo de maquetación (obligatorio): 2 filas × 2 columnas = cuatro viñetas en total. Prohibido: cuadrícula 2×3 de seis viñetas, tiras horizontales, un solo encuadre.",
  "action.geometry.lockStrip": "Bloqueo de maquetación (obligatorio): una fila horizontal con exactamente {{n}} viñetas (1 fila × {{n}} columnas). Prohibido: cuadrícula 2×2, menos de {{n}} viñetas, varias filas apiladas salvo que se especifique.",
  "action.geometry.order": "El orden de viñetas es la línea de tiempo de la acción: Viñeta 1 = primer pulso de acción, Viñeta {{n}} = último pulso de acción.",
  "action.geometry.reading": "Orden de lectura: izquierda → derecha, luego arriba → abajo (si hay varias filas).",
  "action.geometry.numbers": "Números de esquina grandes y en negrita del 1 al {{n}} en cada viñeta (arriba a la izquierda de esa viñeta). Cada entero de 1 a {{n}} debe aparecer una vez.",
  "action.geometry.panelLine": "Viñeta {{i}}/{{n}} ({{label}}): un instante secuencial distinto — pose/fase diferente de las demás viñetas; no copies ni repitas poses.",
  "action.geometry.caption": "Pie de viñeta pequeño en español bajo cada viñeta, coincidiendo con la etiqueta del pulso.",
  "action.geometry.identity": "Misma identidad de personaje / vestuario / continuidad de atrezzo en todas las viñetas.",
  "action.geometry.layout.strip-2": "Una sola imagen apaisada: tira de viñetas horizontal con exactamente 2 viñetas iguales lado a lado (1 fila × 2 columnas), canalillos gruesos y claros entre viñetas",
  "action.geometry.layout.strip-3": "Una sola imagen apaisada: tira de viñetas horizontal con exactamente 3 viñetas iguales en una fila (1 fila × 3 columnas), canalillos gruesos y claros",
  "action.geometry.layout.grid-2x2": "Una sola imagen cuadrada: cuadrícula de viñetas 2×2 con exactamente 4 viñetas iguales (2 filas × 2 columnas), canalillos gruesos y claros, orden de lectura izquierda a derecha y luego arriba abajo",
  "action.geometry.layout.strip-4": "Una sola imagen apaisada ancha: tira de viñetas horizontal con exactamente 4 viñetas iguales en una fila (1 fila × 4 columnas), canalillos gruesos y claros",
  "action.geometry.layout.strip-5": "Una sola imagen apaisada ancha: tira de viñetas horizontal con exactamente 5 viñetas iguales en una fila (1 fila × 5 columnas), canalillos gruesos y claros",
  "action.geometry.layout.grid-2x3": "Una sola imagen apaisada: cuadrícula de viñetas con exactamente 6 viñetas iguales en 2 filas × 3 columnas (fila superior viñetas 1-2-3, fila inferior viñetas 4-5-6), canalillos gruesos y claros, orden de lectura izquierda a derecha y luego arriba abajo",
  "swap.costume.task": "Tarea de edición de imagen / cambio de vestuario (máxima prioridad — léela entera antes de pintar):",
  "swap.costume.sameCharacter": "Vistes al mismo personaje de la imagen fuente solo con un vestuario exterior nuevo.",
  "swap.costume.identity": "Bloqueo de identidad (no cambiar nunca): forma de rostro/cabeza, ojos, color y corte de pelo, proporciones corporales, especie/plan corporal, marcas de piel o superficie, presentación de edad.",
  "swap.costume.pose": "Bloqueo de pose: conserva la misma pose corporal y el encuadre de cámara de la fuente salvo que la maquetación de abajo exija una lámina de varias vistas.",
  "swap.costume.replace": "Sustitución de vestuario (siempre): quita toda la ropa exterior previa, armadura, abrigos, vestidos, uniformes, equipo exterior y zapatos que no coincidan de la fuente.",
  "swap.costume.paint": "Luego pinta solo el vestuario exterior nuevo descrito abajo — cobertura completa, silueta correcta, materiales legibles, calzado y accesorios exteriores coincidentes.",
  "swap.costume.new": "Nuevo vestuario exterior (debe coincidir exactamente, alta prioridad): {{costume}}",
  "swap.costume.add": "Si la fuente está sin prendas o solo con ropa interior de capa base: añade el vestuario exterior completo encima conservando la anatomía y la lógica de la capa interior.",
  "swap.costume.complete": "Si la fuente ya lleva un vestuario: sustitúyelo por completo — no mezcles, superpongas ni dejes fantasma del atuendo viejo bajo el nuevo.",
  "swap.costume.edges": "Los bordes de la ropa deben asentarse bien en hombros, cintura, muñecas y tobillos; sin tela flotante, sin extremidades fusionadas.",
  "swap.costume.forbidden": "Prohibido: cambiar de especie, edad, identidad facial, forma corporal, segundo personaje, pose erótica, marcas de agua, pies de foto, cromado de interfaz.",
  "swap.costume.nonHuman": "Sujetos no humanos: cobertura / equipo exterior adecuado a la especie que coincida con la descripción de vestuario.",
  "swap.costume.subject": "Sujeto: {{name}}",
  "swap.costume.age": "Edad / madurez: {{age}}",
  "swap.costume.gender": "Género / presentación: {{gender}}",
  "swap.costume.appearance": "Bloqueo de aspecto: {{appearance}}",
  "swap.costume.tags": "Tags visuales: {{tags}}",
  "swap.costume.manner": "Solo pistas de manerismo: {{manner}}",
  "swap.costume.checklist": "Lista final: (1) mismo rostro/cuerpo que la fuente (2) solo el vestuario nuevo visible (3) medio = {{style}} (4) estudio limpio o fondo neutro.",
  "swap.costume.layout.hero_front": "Alto 9:16 una sola pose de pie de cuerpo entero de frente, de cabeza a pies visible, postura héroe neutra, brazos relajados, pies plantados. Un solo personaje.",
  "swap.costume.layout.three_quarter": "Cuadrado 1:1 un solo retrato de cuerpo entero a tres cuartos (~45°), de preferencia de cabeza a pies, silueta del vestuario nuevo legible.",
  "swap.costume.layout.profile": "Alto 9:16 un solo perfil verdadero de cuerpo entero (vista lateral 90°), de cabeza a pies, postura neutra, silueta de vestuario y costuras laterales del todo legibles. Un solo personaje.",
  "swap.costume.layout.back": "Alto 9:16 una sola vista trasera de cuerpo entero, de cabeza a pies, brazos ligeramente separados del cuerpo para que el dorso de abrigo/vestido/pelo y la silueta posterior se lean. Un solo personaje.",
  "swap.costume.layout.bust": "Alto 3:4 un solo retrato de busto de torso superior (de pecho hacia arriba), cuello, escote, hombros, capas exteriores y joyas faciales legibles; no es un recorte de cuerpo entero. Un solo personaje.",
  "swap.costume.layout.detail_fabric": "Tablero de detalle de vestuario cuadrado 1:1: primeros planos de tejido, botones, cremalleras, bordado, herrajes de cinturón y transiciones de material solo del vestuario exterior nuevo; sin escena completa, sin segundo personaje.",
  "swap.costume.layout.turnaround": "Rotación apaisada 16:9 con exactamente cuatro figuras de cuerpo entero a la misma escala: frente, izquierda 90°, espalda, derecha 90°. Pose en A neutra, vestuario nuevo completo en cada vista.",
  "swap.atmosphere.task": "Tarea de edición de imagen / cambio de atmósfera (máxima prioridad):",
  "swap.atmosphere.keep": "Conserva la identidad del lugar de la fuente: volumetría de edificios, muros, pistas de planta, señalética, disposición del mobiliario, ángulo de cámara.",
  "swap.atmosphere.replace": "Sustituye por completo: hora del día, clima, cielo, color de iluminación práctica, humedad, niebla, intensidad de neón según la descripción.",
  "swap.atmosphere.new": "Nueva atmósfera (debe coincidir exactamente): {{atmo}}",
  "swap.atmosphere.forbidden": "Prohibido: convertir la arquitectura en un lugar distinto, añadir rostros héroe, marcas de agua, pies de foto.",
  "swap.atmosphere.location": "Lugar: {{title}}",
  "swap.atmosphere.place": "Lugar base: {{place}}",
  "swap.atmosphere.set": "Bloqueo de atrezzo de set: {{set}}",
  "swap.atmosphere.tags": "Etiquetas: {{tags}}",
  "swap.atmosphere.checklist": "Lista final: misma geometría del lugar; solo cambió la atmósfera; medio {{style}}; sin rostros héroe.",
  "swap.atmosphere.repeatMedium": "Reitera: el medio debe ser el id de estilo \"{{id}}\" ({{family}}).",
  "swap.atmosphere.layout.wide": "Apaisado 16:9 encuadre completo de localización coincidiendo con la composición de la fuente lo más posible.",
  "swap.atmosphere.layout.hero": "Apaisado 16:9 still héroe de localización, misma arquitectura, solo atmósfera actualizada.",
  "swap.atmosphere.layout.detail": "Cuadrado 1:1 detalle atmosférico de superficies mojadas / luces prácticas / cielo, aún reconocible como el mismo set.",
}
