import type { PromptCopyTable } from './keys'

export const esPromptCopy: PromptCopyTable = {
  "speechLock.named": "SPEECH LOCK · Personaje \"{{who}}\": el habla audible Y el lip-sync DEBEN ser solo {{primaryName}} ({{primary}}). No hables {{forbid}} ni otro idioma. Mantén el mismo idioma en cada clip. No traduzcas el diálogo.",
  "speechLock.unnamed": "SPEECH LOCK · Personajes que hablan: el habla audible Y el lip-sync DEBEN ser solo {{primaryName}} ({{primary}}). No hables {{forbid}} ni otro idioma. Mantén el mismo idioma en cada clip. No traduzcas el diálogo.",
  "speechLock.namedMulti": "SPEECH LOCK · Personaje \"{{who}}\": el habla audible Y el lip-sync DEBEN ser {{primaryName}} ({{primary}}). Otros idiomas SOLO si la línea del guion ya está en ese idioma: {{extras}}. Nunca un tercer idioma. No cambies de idioma entre clips. No pases a {{forbid}}. No traduzcas el diálogo.",
  "speechLock.unnamedMulti": "SPEECH LOCK · Personajes que hablan: el habla audible Y el lip-sync DEBEN ser {{primaryName}} ({{primary}}). Otros idiomas SOLO si la línea del guion ya está en ese idioma: {{extras}}. Nunca un tercer idioma. No cambies de idioma entre clips. No pases a {{forbid}}. No traduzcas el diálogo.",
  "storyBeats.system": "You write short-drama TIMELINE BEATS for AI video.\nEach beat = ONE short clip screenplay (not a single spoken line).\nA beat MUST include rich performance content: mood, atmosphere, actions, expressions, optional camera/sfx, and zero or more spoken dialogue lines (1–4 lines common).\nReturn ONLY a JSON array (no fences). Each item shape:\n{\"characterName\":\"…\",\"characterNames\":[\"…\"],\"sceneHint\":\"…\",\"propName\":\"…\",\"mood\":\"…\",\"atmosphere\":\"…\",\"camera\":\"…\",\"sfx\":\"…\",\"units\":[{\"type\":\"action\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"expression\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"dialogue\",\"who\":\"…\",\"line\":\"…\",\"tone\":\"…\",\"parenthetical\":\"…\"},{\"type\":\"note\",\"text\":\"…\"}]}\nRules:\n- units.type dialogue.line = ONLY words the character speaks (no stage directions inside line).\n- Put physical business in action; face/micro-performance in expression; delivery in tone/parenthetical.\n- Multiple dialogue units in one beat are encouraged when the clip has a short exchange or self-talk.\n- Pure action beats (no dialogue) are allowed.\n- Write 4–8 beats. Use only cast names provided.\n- Prefer conflict, clear visual action, filmable detail.\n- Stay faithful to the title, style, cast, and scenes provided; if thin, invent freely within that cast/world.\n- SPEECH: write each dialogue.line in that speaker's primary spoken language from the cast list. Do not switch languages between beats. Do not translate lines unless that is the character's listed language.",
  "storyBeats.userLead": "GENERA beats de guion de clip usando TODO el elenco, escenas, props, estilo e idea de abajo.",
  "storyBeats.eachBeat": "Cada beat necesita ánimo + atmósfera + acciones/expresiones + diálogo opcional.",
  "storyBeats.story": "Historia: {{title}}",
  "storyBeats.style": "Estilo: {{style}}",
  "storyBeats.userDir": "Indicación del usuario: {{idea}}",
  "storyBeats.cast": "Elenco:",
  "storyBeats.scenes": "Escenas:",
  "storyBeats.props": "Atrezzo: {{props}}",
  "storyBeats.returnJson": "Devuelve solo el array JSON de beats.",
  "storyBeats.noCast": "(sin elenco)",
  "storyBeats.noScenes": "(sin escenas — inventa lugares en sceneHint)",
  "storyBeats.none": "(ninguno)",
  "videoPolish.system": "You write ONE final image-to-video prompt for a short-drama AI video model.\nReturn ONLY the prompt text — no markdown fences, no title, no explanation.\nRules:\n- Write the director prompt in the user interface language; keep character names and required dialogue language codes clear.\n- Person still: IDENTITY LOCK (face, hair, body, wardrobe, colors). Location plate: SPACE LOCK (architecture, materials, layout, signage, palette) — empty set preferred; no new cast faces.\n- Use ALL provided profile / soul / beat / location facts that affect look, motion, speech, or atmosphere; ignore empty fields.\n- Invent only what is needed to complete a filmable clip from the materials and seed — do not import a fixed sample world, Demo story, or facts not present in materials/seed.\n- Condense long soul.md into actionable performance + identity beats; do not dump the whole bible verbatim.\n- Duration 6–10s; continuous action; cinematic; no text overlays, logos, watermarks, or extra unrelated people.\n- Anatomically correct humans unless the script requires otherwise (two hands, two arms, two legs).\n- If multi-character, keep each listed subject consistent; primary focus first.\n- If HARD RULES appear in materials, keep them and place them at the end of your output (highest priority).\n- SPEECH LOCK is mandatory: never drop, rewrite, or translate it. Expand language codes to full names. Every clip must use the character primary spoken language; do not switch languages between clips; do not translate dialogue lines.\n- Director revision may refine style/action but must NOT violate HARD RULES.",
  "videoPolish.hardRulesKeep": "HARD RULES (HIGHEST PRIORITY — keep every line; object labels like [Character · Name] must stay). Place the full HARD RULES block at the END of your output. Do not weaken, drop, or reassign rules.",
  "clip.task": "TAREA: clip de línea de tiempo de drama corto (imagen a vídeo).",
  "clip.hasRef": "A reference still may be attached — lock identity/location continuity to it when relevant.",
  "clip.characters": "Personajes:",
  "clip.scene": "Escena:",
  "clip.prop": "Atrezzo:",
  "clip.action": "Guía de acción / movimiento:",
  "clip.beat": "Beat / diálogo:",
  "clip.prev": "Continuidad del clip anterior:",
  "clip.revision": "REVISIÓN DEL DIRECTOR (obligatoria):",
  "clip.templateDraft": "Borrador de plantilla (mejora):",
  "intro.task": "TAREA: clip de presentación de casting (imagen a vídeo).",
  "intro.hasRef": "Reference still is attached to the video API — lock identity to that image.",
  "intro.noRef": "No reference still path in this text; still lock to profile appearance/costume.",
  "intro.dossier": "Dossier del personaje:",
  "intro.templateDraft": "Borrador de plantilla (mejora; no ignores el dossier):",
  "common.durationAspect": "Duración: {{seconds}}s. Relación: {{aspect}}.",
  "common.templateDraft": "Borrador de plantilla:",
  "improve.mode": "MODO MEJORAR: fusiona TODAS las fuentes en un resultado completo. Conserva la identidad salvo que el usuario pida cambiarla.",
  "improve.draftDefault": "Campos actuales del formulario:",
  "improve.userRequest": "Petición de mejora (vacío = pulir y fusionar todo):",
  "improve.emptyDefault": "(pulir todos los campos para continuidad)",
  "improve.createDefault": "Idea / dirección:",
  "improve.explicitContext": "Contexto explícito SOLO de esta petición (continuidad; no importes otro mundo muestra):",
  "improve.storyTitle": "Título: {{title}}",
  "improve.styleNote": "Nota de estilo: {{style}}",
  "improve.closingDefault": "Devuelve el resultado completo ahora.",
  "storyMeta.system": "Eres showrunner de drama corto. Escribe biblia visual y reglas duras. SOLO JSON.",
  "storyMeta.draftLabel": "Campos actuales de la historia:",
  "storyMeta.createLabel": "Idea / título de la historia:",
  "storyMeta.emptyPolish": "(pulir biblia visual y hardRules)",
  "storyMeta.closing": "SOLO JSON: {\"styleNote\":\"…\",\"hardRules\":\"…\"}. Ambas claves obligatorias.",
  "storyMeta.contextLabel": "Contexto (elenco / escenas / atrezzo):",
  "character.system": "Eres diseñador de personajes de drama corto para vídeo IA. Devuelve SOLO un JSON. spokenLanguages = array BCP-47.",
  "character.draftLabel": "Campos actuales del perfil:",
  "character.soulLabel": "soul.md / biblia vinculada:",
  "character.createLabel": "Idea de personaje:",
  "character.emptyPolish": "(pulir e integrar soul)",
  "character.closing": "JSON completo ahora. Claves: {{keys}}.",
  "scene.system": "Eres diseñador de localizaciones. Biblia del lugar + guion de esta escena. SOLO JSON.",
  "scene.draftLabel": "Campos actuales de la escena:",
  "scene.charsLabel": "Personajes de la historia:",
  "scene.propsLabel": "Atrezzo de la historia:",
  "scene.priorLabel": "Escenas previas (continuidad):",
  "scene.createLabel": "Idea de escena:",
  "scene.emptyPolish": "(pulir lugar + guion)",
  "scene.closing": "JSON completo. Claves: {{keys}}.",
  "prop.system": "Eres diseñador de atrezzo. SOLO un JSON. Aspecto, material y estado concretos.",
  "prop.draftLabel": "Campos actuales del atrezzo:",
  "prop.createLabel": "Idea de atrezzo:",
  "prop.emptyPolish": "(pulir aspecto del atrezzo)",
  "prop.closing": "JSON completo. Claves: {{keys}}.",
  "prop.fallbackName": "Atrezzo",
  "action.system": "Eres director de movimiento. SOLO JSON válido. Cuerpo, tempo, peso, trayectorias.",
  "action.storyContext": "Contexto de historia (opcional): {{title}}",
  "action.styleNote": "Nota de estilo: {{style}}",
  "action.existingDraft": "Borrador existente a pulir:",
  "action.userIdea": "Idea del usuario: {{idea}}",
  "action.closing": "Solo JSON. Claves: {{keys}}.",
  "profile.mustEveryKey": "DEBES emitir CADA clave de esta lista: {{keys}}.",
  "profile.valuesAreStrings": "Cada valor DEBE ser una cadena JSON. Vacío solo si es desconocido.",
  "profile.visualTagsRule": "visualTags: una cadena separada por comas. NUNCA un array JSON.",
  "profile.fillConcrete": "Rellena con detalle concreto para continuidad.",
  "common.rules": "Reglas:",
  "common.none": "(ninguno)",
  "intro.soul": "soul.md (fuente de interpretación/identidad):\n{{soul}}",
  "intro.matchBible": "(seguir la biblia del personaje)",
  "invent.sources": "Fuentes de verdad, en orden: (1) idea/petición, (2) formulario, (3) extras solo si están en ESTE prompt, (4) imagen adjunta.",
  "invent.create": "Modo crear: inventa con libertad desde la idea/imagen; no dejes claves obligatorias vacías.",
  "invent.improve": "Modo mejorar: pule y completa el borrador; no cambies la identidad salvo petición.",
  "invent.noImport": "NO importes identidad, trama, clima, oficio, lugar, época o estilo de lo que no esté en este prompt.",
  "invent.storyBlock": "Si hay bloque de historia/estilo, úsalo solo para continuidad; no anules la idea explícita.",
  "character.keysLead": "SOLO un JSON con claves: {{keys}}",
  "character.ruleSpoken": "spokenLanguages: array BCP-47 de idiomas que HABLA. [] si no verbal.",
  "character.ruleIdentity": "Identidad coherente en láminas y vídeo.",
  "character.fallbackPersonality": "presencia cálida y clara",
  "character.fallbackManner": "microgestos naturales",
  "character.fallbackVoice": "voz clara",
  "scene.keysLead": "SOLO un JSON con claves: {{keys}}",
  "scene.suggestLead": "Propón una LOCALIZACIÓN lista como escena nº {{n}} de \"{{title}}\".",
  "scene.suggestPlotFocus": "Foco argumental: {{label}}",
  "scene.suggestStyle": "Estilo: {{style}}",
  "scene.suggestExisting": "Localizaciones ya existentes: {{titles}}",
  "scene.suggestChars": "Personajes (contexto):",
  "scene.suggestProps": "Atrezzo (contexto):",
  "scene.suggestSegment": "Detalle del segmento:",
  "scene.suggestBeats": "Escenas / beats:",
  "scene.suggestClosing": "Devuelve el JSON completo. Diseña un lugar reutilizable y distinto.",
  "scene.fallbackName": "Localización",
  "scene.fallbackMood": "atmósfera cinematográfica",
  "scene.fallbackLighting": "igual que el still",
  "scene.fallbackCamera": "leve travelling de establecimiento o paneo lento",
  "scene.ideaFromImage": "Inventa el perfil completo de localización a partir de la foto adjunta.",
  "scene.polishIdea": "Pulir",
  "prop.keysLead": "SOLO un JSON con claves: {{keys}}",
  "action.fieldsLead": "Campos: {{keys}}.",
  "soul.system": "Escribes soul.md de producción. SOLO markdown completo. Respeta spokenLanguages. Escribe en el idioma de la interfaz.",
  "soul.improveMode": "MODO MEJORAR: fusiona perfil + soul existente en un soul.md completo.",
  "soul.createMode": "Crea un soul.md completo a partir de este perfil (no inventes a otra persona):",
  "soul.profileFields": "Campos del perfil:",
  "soul.existing": "soul.md existente (fusiona; no descartes detalle útil):",
  "soul.userRequest": "Petición del usuario: {{request}}",
  "soul.extraContext": "Contexto adicional (útil sí; gana el perfil):",
  "soul.returnOnly": "Devuelve solo el markdown del soul.md.",
  "wardrobe.system": "Eres consultor de vestuario. SOLO un JSON. artStyle debe ser uno de: {{styleIds}}. Materiales y silueta concretos. Nunca erotices menores.",
  "wardrobe.improveMode": "MODO MEJORAR / SUGERIR: usa TODOS los campos y el contexto argumental.",
  "wardrobe.characterForm": "Personaje (formulario completo):",
  "wardrobe.soulExcerpt": "Extracto soul.md:\n{{soul}}",
  "wardrobe.userRequest": "Petición: {{request}}",
  "wardrobe.storyContext": "Contexto de producción (úsalo si está; no inventes otro mundo):",
  "wardrobe.style": "estilo: {{style}}",
  "wardrobe.segment": "Segmento elegido: {{label}}",
  "wardrobe.sceneContext": "Escena / beat:",
  "wardrobe.noScenes": "(aún no hay escenas)",
  "wardrobe.proposeNew": "Propón un look NUEVO que encaje (no dupliques).",
  "fill.system": "Completas campos vacíos. SOLO JSON con estas claves: {{keys}}. Cada valor es una cadena no vacía. Nunca un array.",
  "fill.userPartial": "Perfil parcial (no contradigas):",
  "fill.userOnly": "Rellena SOLO estas claves: {{keys}}.",
  "fill.userReturn": "JSON solo con esas claves; valores no vacíos.",
  "imageGen.multiRef": "{{n}} stills extra: la primera es la base; mantén la identidad en todas.",
  "residual.sceneLink": "Escena {{n}}: {{short}}",
  "residual.beatSegment": "Beat {{n}} · {{who}}{{tail}}",
  "residual.unknown": "Desconocido",
  "residual.story": "Historia",
  "beat.mood": "[MOOD] {{text}}",
  "beat.atmo": "[ATMO] {{text}}",
  "beat.camera": "[CAMERA] {{text}}",
  "beat.sfx": "[SFX] {{text}}",
  "beat.action": "[ACTION] {{text}}",
  "beat.actionWho": "[ACTION|{{who}}] {{text}}",
  "beat.expr": "[EXPR] {{text}}",
  "beat.exprWho": "[EXPR|{{who}}] {{text}}",
  "beat.dialogue": "[DIALOGUE|{{who}}] {{body}}",
  "beat.dialogueTone": "[DIALOGUE|{{who}}|{{tone}}] {{body}}",
  "beat.whoUnknown": "?",
  "beat.template": "[MOOD] tense, hesitant\n[ATMO] door-gap warm light; rain on ground\n[CAMERA] medium shot, push to hands\n[SFX] rain, fabric rustle\n[ACTION|Name] removes helmet; stares at the door light; hand into jacket pocket\n[EXPR|Name] furrowed brow, breath catches\n[DIALOGUE|Name|low, hoarse] Raining again…\n[DIALOGUE|Name|aside] (beat) Are you… still there?",
  "vision.preamble": "Hay un still adjunto. Rellena TODOS los campos de este {{what}} sobre todo DESDE LA IMAGEN.",
  "vision.character": "identidad (nombre, aspecto, vestuario, edad, género, tags)",
  "vision.scene": "localización (título, descripción, luz, ánimo, atrezzo, tags)",
  "vision.prop": "atrezzo (nombre, descripción, material, tamaño, estado, tags)",
  "vision.action": "acción (nombre, descripción, tempo, intención, cámara, tags)",
  "vision.costume": "vestuario (nombre, descripción completa)",
  "still.header": "SINGLE KEYFRAME STILL for short-drama video continuity (not a multi-panel sheet). Produce one cinematic hero frame that matches the planned shot below. No text, logos, watermarks, UI chrome. Sharp, production-ready.",
  "still.revision": "MEJORA DEL USUARIO PARA ESTE STILL (obligatoria): {{notes}}",
  "still.regenTask": "TAREA: revisa el prompt de director image-to-video y mantenlo usable como brief de keyframe.",
  "still.userImprove": "PETICIÓN DE MEJORA:\n{{notes}}",
  "still.currentPrompt": "Prompt profesional actual:",
  "still.hardRules": "HARD RULES (al final; no las debilites):",
  "mediaGen.writeOne": "Escribe UN prompt final de imagen para un still de drama corto.",
  "mediaGen.returnOnly": "SOLO el texto del prompt — sin markdown.",
  "mediaGen.singleComposite": "Describe UNA sola imagen compuesta.",
  "mediaGen.lockRefs": "Las imágenes adjuntas son la verdad visual (orden Ref#). No inventes otra persona, tienda u objeto.",
  "mediaGen.videoSystem": "Eres redactor de prompts de director image-to-video.",
  "mediaGen.videoMerge": "Fusiona los materiales en UN prompt de vídeo.",
  "mediaGen.videoInclude": "Incluye: bloqueo de identidad, cámara, interpretación/diálogo, ritmo, luz.",
  "mediaGen.videoFacts": "Solo hechos de materiales y seed. Nada de Demo.",
  "mediaGen.videoNoSwap": "Con refs, no cambies actor, localización ni atrezzo.",
  "mediaGen.videoHardRules": "HARD RULES al final si hay.",
  "mediaGen.imageSystem": "Eres director de prompts de imagen.",
  "mediaGen.imageMergeStills": "Fusiona materiales y stills en UN prompt de imagen.",
  "mediaGen.imageMergeText": "Fusiona los textos en UN prompt de imagen.",
  "mediaGen.imagePriority": "Prioridad: caras/vestuario/lugares/atrezzo de las imágenes.",
  "mediaGen.imageNoSwap": "No sustituyas por otro famoso o set ajeno si hay stills de elenco.",
  "mediaGen.imageFacts": "Solo hechos de materiales y seed.",
  "mediaGen.imageLayout": "Si hay multipanel, conserva el recuento exacto.",
  "mediaGen.imagePackage": "Si hay LAYOUT, el prompt DEBE aplicar ese layout exacto.",
  "mediaGen.imageHardRules": "HARD RULES al final si hay.",
  "mediaGen.directorFallback": "IMAGEN-A-VÍDEO: anima este keyframe. Bloquea identidad, vestuario, set y encuadre.",
  "mediaGen.directorFallbackCam": "Cámara e interpretación claras; sin subtítulos ni marca de agua.",
  "charIntro.task": "IMAGEN-A-VÍDEO: anima a la misma persona del still en un autocasting breve.",
  "charIntro.identityLock": "BLOQUEO DE IDENTIDAD: misma cara, pelo, cuerpo, edad, vestuario y colores.",
  "charIntro.personality": "Personalidad / vibe: {{personality}}.",
  "charIntro.backstory": "Trasfondo: {{backstory}}.",
  "charIntro.relationships": "Relaciones: {{relationships}}.",
  "charIntro.soul": "Extracto soul (fuente de interpretación): {{soul}}",
  "charIntro.performance": "Interpretación: leve travelling o cámara en mano; mira a cámara; {{manner}}.",
  "charIntro.speech": "Habla: la boca se mueve como presentándose; voz: {{voice}}.",
  "charIntro.beat": "Idle natural → sonrisa o asentimiento → gesto breve → hold.",
  "charIntro.lighting": "Luz coherente con el still; sin texto, logos ni extra gente.",
  "charIntro.duration": "Cabe en 6–10s de autocasting.",
  "sceneIntro.task": "IMAGEN-A-VÍDEO: anima el mismo lugar como plano de establecimiento.",
  "sceneIntro.spaceLock": "BLOQUEO DE ESPACIO: misma arquitectura, materiales, letreros, planta y color.",
  "sceneIntro.name": "Nombre del lugar: {{name}}.",
  "sceneIntro.place": "Descripción: {{place}}.",
  "sceneIntro.spaceType": "Tipo de espacio: {{type}}.",
  "sceneIntro.time": "Hora del día: {{time}}.",
  "sceneIntro.weather": "Clima: {{weather}}.",
  "sceneIntro.moodLight": "Ánimo: {{mood}}. Luz: {{lighting}}.",
  "sceneIntro.palette": "Paleta: {{palette}}.",
  "sceneIntro.setDressing": "Atrezzo de set: {{set}}.",
  "sceneIntro.tags": "Tags visuales: {{tags}}.",
  "sceneIntro.art": "Estilo: {{art}}.",
  "sceneIntro.ambient": "Ambiente (sin texto UI): {{sound}}.",
  "sceneIntro.scriptCue": "Pista de beat (solo atmósfera): {{cue}}.",
  "sceneIntro.camera": "Cámara: {{camera}}; set vacío preferible; sin caras nuevas ni logos.",
  "sceneIntro.beat": "Establecer → vida ambiental sutil → hold.",
  "sceneIntro.duration": "Cabe en 6–10s de intro de lugar.",
  "propIntro.task": "IMAGEN-A-VÍDEO: anima el mismo atrezzo como intro de producto.",
  "propIntro.objectLock": "BLOQUEO DE OBJETO: misma silueta, materiales, colores, grabados y desgaste.",
  "propIntro.name": "Nombre: {{name}}.",
  "propIntro.look": "Aspecto: {{look}}.",
  "propIntro.material": "Material: {{material}}.",
  "propIntro.size": "Tamaño: {{size}}.",
  "propIntro.condition": "Estado: {{condition}}.",
  "propIntro.tags": "Tags: {{tags}}.",
  "propIntro.art": "Estilo: {{art}}.",
  "propIntro.camera": "Órbita suave o travelling lento en mesa limpia; luz coherente.",
  "propIntro.beat": "Hold → brillo / microgiro → hold.",
  "propIntro.noHands": "Sin manos ni caras nuevas si no están en el still; sin texto ni extras.",
  "propIntro.duration": "Cabe en 6–10s de intro de atrezzo.",
  "costumeIntro.task": "IMAGEN-A-VÍDEO: anima el mismo look como intro de vestuario.",
  "costumeIntro.wardrobeLock": "BLOQUEO DE VESTUARIO: misma silueta, telas, colores, capas y accesorios.",
  "costumeIntro.identityOrProduct": "Si hay persona: bloquea cara/cuerpo; si maniquí/plano: encuadre de producto.",
  "costumeIntro.name": "Nombre del look: {{name}}.",
  "costumeIntro.desc": "Vestuario: {{look}}.",
  "costumeIntro.art": "Estilo: {{art}}.",
  "costumeIntro.camera": "Leve travelling u órbita; luz de moda coherente.",
  "costumeIntro.beat": "Hold → caída de tela / brillo de herrajes → hold.",
  "costumeIntro.forbid": "Sin caras nuevas, texto, logos ni pose erótica.",
  "costumeIntro.duration": "Cabe en 6–10s de intro de vestuario.",
  "costumeIntro.fallbackName": "Look",
  "actionIntro.lead": "Vídeo demo de acción \"{{name}}\".",
  "actionIntro.intention": "Intención: {{intention}}",
  "actionIntro.body": "Cuerpo/tempo: {{body}}",
  "actionIntro.camera": "Cámara: {{camera}}",
  "actionIntro.closing": "Movimiento continuo, cinematográfico, sin texto; sigue el still.",
  "sceneIntroPolish.task": "TAREA: intro de localización (imagen-a-vídeo).",
  "sceneIntroPolish.hasRef": "Still de lugar adjunto — bloquea la identidad ESPACIAL.",
  "sceneIntroPolish.noRef": "Sin still; bloquea a la biblia del lugar.",
  "sceneIntroPolish.dossier": "Dossier de localización:",
  "sceneIntroPolish.scriptCue": "pista de guion (solo atmósfera):\n{{script}}",
  "sceneIntroPolish.emptySet": "Set vacío; sin caras nuevas. Sin texto ni logos.",
  "propIntroPolish.task": "TAREA: intro héroe de atrezzo (imagen-a-vídeo).",
  "propIntroPolish.hasRef": "Still de atrezzo adjunto — bloquea el OBJETO.",
  "propIntroPolish.noRef": "Sin still; bloquea al dossier.",
  "propIntroPolish.dossier": "Dossier de atrezzo:",
  "propIntroPolish.noHands": "Sin manos ni caras nuevas. Sin texto ni logos.",
  "costumeIntroPolish.task": "TAREA: intro de vestuario (imagen-a-vídeo).",
  "costumeIntroPolish.hasRef": "Still adjunto — persona: identidad+ropa; maniquí: silueta y materiales.",
  "costumeIntroPolish.noRef": "Sin still; bloquea a la descripción.",
  "costumeIntroPolish.dossier": "Dossier de vestuario:",
  "costumeIntroPolish.fabric": "Caída sutil de tela; sin caras nuevas ni texto.",
  "actionIntroPolish.task": "TAREA: intro de guía de movimiento (imagen-a-vídeo).",
  "actionIntroPolish.hasRef": "Still adjunto — bloquea la identidad interpretativa.",
  "actionIntroPolish.templateKeepRules": "Borrador plantilla (mejora; HARD RULES al final):",
  "cover.posterLead": "PÓSTER / KEY ART profesional 16:9. No es mockup UI. Sin texto, logo ni marca.",
  "cover.titleMood": "Título (solo ánimo, no lo escribas en imagen): {{title}}.",
  "cover.styleBible": "Biblia de estilo: {{style}}",
  "cover.extraDir": "Dirección extra: {{idea}}",
  "cover.establishing": "Plano de establecimiento evocador para portada de biblioteca.",
  "cover.medium": "Respeta el medium; silueta fuerte.",
  "cover.editPrefix": "IMAGE EDIT: nueva composición de póster. Conserva identidad/ánimo. ",
  "cover.label": "Portada de historia",
  "costumeFill.system": "Eres diseñador de vestuario. SOLO JSON compacto. Si hay imagen, describe ESE outfit con fidelidad.",
  "costumeFill.idea": "Idea: {{idea}}",
  "costumeFill.polish": "Pule el borrador de vestuario.",
  "costumeFill.required": "Claves: name, description, artStyle, hardRules. Faltar = inválido.",
  "costumeFill.fallbackName": "Look",
  "segment.entireStory": "Toda la historia (todas las escenas)",
  "segment.noStory": "Sin historia (solo ficha de personaje)",
  "vision.inventFromImage": "Describe e inventa un perfil completo de {{kind}} a partir de la foto adjunta.",
  "vision.polishAll": "Pule y fusiona todos los campos",
  "story.untitled": "Drama corto sin título",
  "action.castIdentityNote": "Stills de identidad ({{count}}): el rostro/cuerpo debe coincidir con las referencias de elenco en cada viñeta."
}
