import type { PromptCopyTable } from './keys'

export const frPromptCopy: PromptCopyTable = {
  "speechLock.named": "Verrouillage des répliques · Personnage « {{who}} » : la voix audible ET le lip-sync DOIVENT être uniquement {{primaryName}} ({{primary}}). Ne passez pas à {{forbid}} ni à une autre langue. Gardez la même langue à chaque clip. Ne traduisez pas les répliques.",
  "speechLock.unnamed": "Verrouillage des répliques · Personnages parlants : la voix audible ET le lip-sync DOIVENT être uniquement {{primaryName}} ({{primary}}). Ne passez pas à {{forbid}} ni à une autre langue. Gardez la même langue à chaque clip. Ne traduisez pas les répliques.",
  "speechLock.namedMulti": "Verrouillage des répliques · Personnage « {{who}} » : la voix audible ET le lip-sync DOIVENT être {{primaryName}} ({{primary}}). Autres langues UNIQUEMENT si la réplique écrite est déjà dans cette langue : {{extras}}. Jamais une troisième langue. Ne changez pas de langue entre les clips. Ne passez pas à {{forbid}}. Ne traduisez pas.",
  "speechLock.unnamedMulti": "Verrouillage des répliques · Personnages parlants : la voix audible ET le lip-sync DOIVENT être {{primaryName}} ({{primary}}). Autres langues UNIQUEMENT si la réplique écrite est déjà dans cette langue : {{extras}}. Jamais une troisième langue. Ne changez pas de langue entre les clips. Ne passez pas à {{forbid}}. Ne traduisez pas.",
  "hardRules.sealHeader": "RÈGLES FERMES (priorité maximale — à respecter ; primer en cas de conflit) :",
  "hardRules.sealFooter": "En cas de conflit avec une instruction antérieure, suivez les RÈGLES FERMES.",
  "hardRules.labelStory": "Histoire",
  "hardRules.labelCharacter": "Personnage",
  "hardRules.labelScene": "Lieu",
  "hardRules.labelProp": "Accessoire",
  "hardRules.labelAction": "Action",
  "continuity.lockHeader": "VERROU DE CONTINUITÉ (à respecter pour la séquence) :",
  "continuity.hasImage": "L’image jointe est la DERNIÈRE IMAGE / image clé du plan {{n}}. Ce plan continue depuis cet état visuel, sans coupe sèche vers un autre décor.",
  "continuity.noImage": "Enchaîner depuis le plan {{n}} (pas de photogramme — s’aligner sur le dossier).",
  "continuity.identity": "IDENTITÉ : même personne — visage, cheveux, proportions, couleurs de costume, accessoires. Pas de restyle ni changement d’âge.",
  "continuity.space": "ESPACE : même lieu — architecture, matériaux, plan, lumière. Dérive d’heure seulement si le plan l’exige.",
  "continuity.action": "ACTION : reprendre pose, regard et mouvement de l’image précédente ; pas de coupe vers une autre installation.",
  "continuity.prevContext": "Contexte du plan précédent : {{snippet}}",
  "continuity.noText": "Pas de sous-titres, logos ni filigranes.",
  "directorLabel.lock": "Verrouillage des répliques",
  "directorLabel.story": "Histoire : ",
  "directorLabel.style": "Style : ",
  "directorLabel.cast": "Distribution : ",
  "directorLabel.location": "Lieu : ",
  "directorLabel.prop": "Accessoire : ",
  "directorLabel.primaryChar": "Personnage principal : ",
  "directorLabel.mood": "Humeur : ",
  "directorLabel.atmo": "Atmosphère : ",
  "directorLabel.camera": "Caméra : ",
  "directorLabel.sfx": "Sons : ",
  "directorLabel.action": "Action : ",
  "directorLabel.expr": "Expression : ",
  "directorLabel.speech": "Répliques : ",
  "directorLabel.notes": "Notes : ",
  "directorLabel.identity": "Identité : ",
  "directorLabel.space": "Espace : ",
  "directorLabel.ref": "Photogramme ",
  "directorLabel.beatN": "Plan {{n}} · ",
  "directorLabel.beatNsec": "Plan {{n}} · {{s}} s",
  "directorLabel.hardRules": "RÈGLES FERMES",
  "directorLabel.identityLock": "Verrouillage d'identité",
  "directorLabel.spaceLock": "Verrouillage spatial",
  "storyBeats.system": "Tu écris les TEMPS FORTS de la chronologie pour une vidéo de court-métrage.\nChaque temps fort = le scénario d’UN clip court (pas une seule réplique).\nIl doit inclure humeur, atmosphère, actions, expressions, caméra/sfx facultatifs, et 0 à plusieurs répliques (souvent 1–4).\nRenvoie UNIQUEMENT un tableau JSON (sans clôtures). Forme de chaque élément :\n{\"characterName\":\"…\",\"characterNames\":[\"…\"],\"sceneHint\":\"…\",\"propName\":\"…\",\"mood\":\"…\",\"atmosphere\":\"…\",\"camera\":\"…\",\"sfx\":\"…\",\"units\":[{\"type\":\"action\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"expression\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"dialogue\",\"who\":\"…\",\"line\":\"…\",\"tone\":\"…\",\"parenthetical\":\"…\"},{\"type\":\"note\",\"text\":\"…\"}]}\nRègles :\n- dialogue.line = les seuls mots dits ; pas de didascalie dans la réplique.\n- Le corps va dans action ; le visage dans expression ; le jeu dans tone/parenthetical.\n- Un échange court ou un monologue : plusieurs dialogue dans le même temps fort.\n- Un temps fort sans réplique est permis.\n- Écris 4–8 temps forts. Noms du casting fourni uniquement.\n- Conflit, action visible, détail filmable.\n- Fidèle au titre, au style, au casting et aux scènes. N’élargis pas le monde.\n- Chaque dialogue.line dans la langue principale du locuteur (liste de casting). Pas de changement de langue entre temps forts. Ne traduis que si c’est la langue listée.",
  "storyBeats.userLead": "GÉNÉREZ des beats de scénario de clip avec TOUT le casting, scènes, accessoires, style et idée ci-dessous.",
  "storyBeats.eachBeat": "Chaque beat doit avoir humeur + atmosphère + actions/expressions + dialogues optionnels.",
  "storyBeats.story": "Histoire : {{title}}",
  "storyBeats.style": "Style : {{style}}",
  "storyBeats.userDir": "Consigne utilisateur : {{idea}}",
  "storyBeats.cast": "Casting :",
  "storyBeats.scenes": "Scènes :",
  "storyBeats.props": "Accessoires : {{props}}",
  "storyBeats.returnJson": "Renvoyez uniquement le tableau JSON des beats.",
  "storyBeats.noCast": "(pas de casting)",
  "storyBeats.noScenes": "(pas de scènes — inventez les lieux dans sceneHint)",
  "storyBeats.none": "(aucun)",
  "videoPolish.system": "Vous rédigez UN prompt final image vers vidéo pour un modèle vidéo de court-métrage.\nRenvoyez UNIQUEMENT le texte du prompt — pas de clôtures markdown, titre ni explication.\nRègles :\n- Rédigez le prompt de mise en scène dans la langue de l'interface ; noms et codes de langue des répliques clairement indiqués.\n- Still personne : Verrouillage d'identité. Plaque de lieu : Verrouillage spatial. N'ajoutez pas de visages sauf si les matériaux les nomment.\n- Utilisez TOUS les faits de profil / soul / beat / lieu qui touchent look, mouvement, parole ou atmosphère ; ignorez les champs vides.\n- N'inventez que le nécessaire pour un clip filmable à partir des matériaux et du seed — pas de monde échantillon, Demo ni faits absents.\n- Condenser un long soul.md en beats de jeu et d'identité ; ne pas coller toute la bible.\n- Utilisez la durée indiquée dans les matériaux (secondes réelles). Action continue. Pas de texte, logos, filigranes ni passants hors sujet.\n- Anatomie humaine correcte sauf exigence du script (deux mains, deux bras, deux jambes).\n- Si plusieurs personnages, chacun reste cohérent ; foyer principal d'abord.\n- Si RÈGLES FERMES figurent, gardez-les et placez-les à la fin (priorité maximale).\n- Verrouillage des répliques est obligatoire : ne pas le supprimer, réécrire ni traduire. Développer les codes en noms. Chaque clip suit la langue principale du personnage ; pas de changement entre clips ; pas de traduction des répliques.\n- Une révision de mise en scène peut affiner style/action mais NE DOIT PAS violer RÈGLES FERMES.",
  "videoPolish.hardRulesKeep": "RÈGLES FERMES (priorité maximale — conservez chaque ligne ; les étiquettes d’objet comme [Personnage · Nom] doivent rester). Placez le bloc complet des règles fermes à la FIN de la sortie. Ne les affaiblissez pas, ne les supprimez pas et ne les réattribuez pas.",
  "clip.task": "TÂCHE : clip de timeline de court-métrage (image vers vidéo).",
  "clip.hasRef": "Une image de référence peut être jointe — verrouillez identité et lieu quand c’est pertinent.",
  "clip.characters": "Personnages :",
  "clip.scene": "Scène :",
  "clip.prop": "Accessoire :",
  "clip.action": "Guide d’action / mouvement :",
  "clip.beat": "Beat / dialogues :",
  "clip.prev": "Continuité du clip précédent :",
  "clip.revision": "RÉVISION DU RÉALISATEUR (obligatoire) :",
  "clip.templateDraft": "Brouillon de modèle (à améliorer) :",
  "intro.task": "TÂCHE : clip de présentation de casting (image vers vidéo).",
  "intro.hasRef": "L’image de référence est envoyée à l’API vidéo — verrouillez l’identité sur cette photo.",
  "intro.noRef": "Pas de chemin d’image dans ce texte ; verrouillez quand même l’apparence et le costume du profil.",
  "intro.dossier": "Dossier personnage :",
  "intro.templateDraft": "Brouillon de modèle (améliorez ; n’ignorez pas le dossier) :",
  "common.durationAspect": "Durée : {{seconds}} s. Format : {{aspect}}.",
  "common.templateDraft": "Brouillon de modèle :",
  "improve.mode": "MODE AMÉLIORER : fusionnez TOUTES les sources en un résultat complet. Gardez l’identité sauf demande explicite.",
  "improve.draftDefault": "Champs actuels du formulaire :",
  "improve.userRequest": "Demande d’amélioration (vide = tout peaufiner) :",
  "improve.emptyDefault": "(peaufiner tous les champs pour la continuité)",
  "improve.createDefault": "Idée / direction :",
  "improve.explicitContext": "Contexte explicite de CETTE requête seulement (continuité ; n’importez aucun autre monde) :",
  "improve.storyTitle": "Titre : {{title}}",
  "improve.styleNote": "Note de style : {{style}}",
  "improve.closingDefault": "Produisez le résultat complet maintenant.",
  "storyMeta.system": "Vous êtes showrunner. Écrivez bible visuelle + règles dures. JSON uniquement.",
  "storyMeta.draftLabel": "Champs actuels de l’histoire :",
  "storyMeta.createLabel": "Idée / titre :",
  "storyMeta.emptyPolish": "(peaufiner bible + hardRules)",
  "storyMeta.closing": "JSON uniquement : {\"styleNote\":\"…\",\"hardRules\":\"…\"}. Les deux clés sont obligatoires.",
  "storyMeta.contextLabel": "Contexte (cast / scènes / accessoires) :",
  "character.system": "Vous êtes designer de personnages. Un seul JSON. spokenLanguages = tableau BCP-47.",
  "character.draftLabel": "Champs profil actuels :",
  "character.soulLabel": "soul.md / bible liée :",
  "character.createLabel": "Idée de personnage :",
  "character.emptyPolish": "(peaufiner et intégrer le soul)",
  "character.closing": "JSON complet. Clés : {{keys}}.",
  "scene.system": "Vous êtes designer de lieux. Bible du lieu + script de cette scène. JSON seul.",
  "scene.draftLabel": "Champs scène actuels :",
  "scene.charsLabel": "Personnages de l’histoire :",
  "scene.propsLabel": "Accessoires de l’histoire :",
  "scene.priorLabel": "Scènes déjà là (continuité) :",
  "scene.createLabel": "Idée de scène :",
  "scene.emptyPolish": "(peaufiner lieu + script)",
  "scene.closing": "JSON complet. Clés : {{keys}}.",
  "prop.system": "Vous êtes designer d’accessoires. Un seul JSON. Aspect, matière, état concrets.",
  "prop.draftLabel": "Champs accessoire actuels :",
  "prop.createLabel": "Idée d’accessoire :",
  "prop.emptyPolish": "(peaufiner l’aspect)",
  "prop.closing": "JSON complet. Clés : {{keys}}.",
  "prop.fallbackName": "Accessoire",
  "action.system": "Vous êtes directeur de mouvement. JSON valide seulement. Corps, tempo, poids, trajectoires.",
  "action.storyContext": "Contexte d’histoire (optionnel) : {{title}}",
  "action.styleNote": "Note de style : {{style}}",
  "action.existingDraft": "Brouillon existant à peaufiner :",
  "action.userIdea": "Idée utilisateur : {{idea}}",
  "action.closing": "JSON seulement. Clés : {{keys}}.",
  "profile.mustEveryKey": "Vous DEVEZ produire CHAQUE clé : {{keys}}.",
  "profile.valuesAreStrings": "Chaque valeur DOIT être une chaîne JSON. Vide seulement si inconnu.",
  "profile.visualTagsRule": "visualTags : une chaîne séparée par des virgules. JAMAIS un tableau JSON.",
  "profile.fillConcrete": "Remplissez avec des détails concrets.",
  "common.rules": "Règles :",
  "common.none": "(aucun)",
  "intro.soul": "soul.md (source d’interprétation / identité) :\n{{soul}}",
  "intro.matchBible": "(suivre la bible du personnage)",
  "invent.sources": "Sources de vérité, dans l’ordre : (1) idée / demande, (2) formulaire, (3) extras seulement s’ils sont dans CE prompt, (4) image jointe.",
  "invent.create": "Mode créer : inventez librement depuis l’idée/image ; ne laissez aucune clé obligatoire vide.",
  "invent.improve": "Mode améliorer : peaufinez le brouillon ; ne changez l’identité que sur demande.",
  "invent.noImport": "N’importez ni identité, intrigue, météo, métier, lieu, époque ou style hors de ce prompt.",
  "invent.storyBlock": "Un bloc histoire/style ne sert qu’à la continuité ; n’écrasez pas l’idée explicite.",
  "character.keysLead": "UN SEUL JSON avec les clés : {{keys}}",
  "character.ruleSpoken": "spokenLanguages : tableau BCP-47 des langues PARLÉES. [] si non verbal.",
  "character.ruleIdentity": "Identité cohérente pour planches et vidéo.",
  "scene.keysLead": "UN SEUL JSON avec les clés : {{keys}}",
  "scene.suggestLead": "Proposez un LIEU prêt comme scène n° {{n}} pour « {{title}} ».",
  "scene.suggestPlotFocus": "Foyer narratif : {{label}}",
  "scene.suggestStyle": "Style : {{style}}",
  "scene.suggestExisting": "Lieux déjà là : {{titles}}",
  "scene.suggestChars": "Personnages (contexte) :",
  "scene.suggestProps": "Accessoires (contexte) :",
  "scene.suggestSegment": "Détail du segment :",
  "scene.suggestBeats": "Scènes / beats :",
  "scene.suggestClosing": "Renvoyez le JSON complet. Concevez un lieu distinct et réutilisable.",
  "scene.fallbackName": "Lieu",
  "scene.ideaFromImage": "Inventez le profil de lieu complet à partir de la photo jointe.",
  "scene.polishIdea": "Peaufiner",
  "prop.keysLead": "UN SEUL JSON avec les clés : {{keys}}",
  "action.fieldsLead": "Champs : {{keys}}.",
  "soul.system": "Vous rédigez des soul.md de production. Markdown complet seulement. Respectez spokenLanguages. Langue de l’interface.",
  "soul.improveMode": "MODE AMÉLIORER : fusionnez profil + soul existant en un soul.md complet.",
  "soul.createMode": "Rédigez un soul.md complet à partir de ce profil (pas une autre personne) :",
  "soul.profileFields": "Champs du profil :",
  "soul.existing": "soul.md existant (fusionnez ; ne jetez pas le détail utile) :",
  "soul.userRequest": "Demande : {{request}}",
  "soul.extraContext": "Contexte supplémentaire (utile oui ; le profil gagne) :",
  "soul.returnOnly": "Renvoyez uniquement le markdown du soul.md.",
  "wardrobe.system": "Vous êtes consultant costumes. UN seul JSON. artStyle parmi : {{styleIds}}. Matières et silhouette concrètes. Jamais d’érotisation mineure.",
  "wardrobe.improveMode": "MODE AMÉLIORER / SUGGÉRER : utilisez TOUS les champs et le contexte.",
  "wardrobe.characterForm": "Personnage (formulaire complet) :",
  "wardrobe.soulExcerpt": "Extrait soul.md :\n{{soul}}",
  "wardrobe.userRequest": "Demande : {{request}}",
  "wardrobe.storyContext": "Contexte de production (s’il est là ; n’inventez pas un autre monde) :",
  "wardrobe.style": "style : {{style}}",
  "wardrobe.segment": "Segment choisi : {{label}}",
  "wardrobe.sceneContext": "Scène / beat :",
  "wardrobe.noScenes": "(pas encore de scènes)",
  "wardrobe.proposeNew": "Proposez un look NOUVEAU qui colle (pas un doublon).",
  "fill.system": "Vous complétez les champs vides. JSON avec EXACTEMENT ces clés : {{keys}}. Chaque valeur est une chaîne non vide. Jamais un tableau.",
  "fill.userPartial": "Profil partiel (ne contredisez pas) :",
  "fill.userOnly": "Remplissez SEULEMENT ces clés : {{keys}}.",
  "fill.userReturn": "JSON avec ces clés seulement ; valeurs non vides.",
  "imageGen.multiRef": "{{n}} stills de plus : le premier est la base ; gardez l’identité partout.",
  "residual.sceneLink": "Scène {{n}} : {{short}}",
  "residual.beatSegment": "Temps fort {{n}} · {{who}}{{tail}}",
  "residual.unknown": "Inconnu",
  "residual.story": "Histoire",
  "beat.mood": "[MOOD] {{text}}",
  "beat.atmo": "[ATMO] {{text}}",
  "beat.camera": "[CAMERA] {{text}}",
  "beat.sfx": "[SFX] {{text}}",
  "beat.action": "[ACTION] {{text}}",
  "beat.actionWho": "[ACTION|{{who}}] {{text}}",
  "beat.expr": "[EXPR] {{text}}",
  "beat.exprWho": "[EXPR|{{who}}] {{text}}",
  "beat.dialogue": "[DIALOGUE|{{who}}] {{body}}",
  "beat.dialogueTone": "[DIALOGUE|{{who}}|{{tone}}] {{body}}",
  "beat.whoUnknown": "?",
  "beat.template": "[MOOD] tense, hesitant\n[ATMO] door-gap warm light; rain on ground\n[CAMERA] medium shot, push to hands\n[SFX] rain, fabric rustle\n[ACTION|Name] removes helmet; stares at the door light; hand into jacket pocket\n[EXPR|Name] furrowed brow, breath catches\n[DIALOGUE|Name|low, hoarse] Raining again…\n[DIALOGUE|Name|aside] (beat) Are you… still there?",
  "vision.preamble": "Un still est joint. Remplissez TOUS les champs de ce {{what}} surtout DEPUIS L’IMAGE.",
  "vision.character": "identité (nom, apparence, costume, âge, genre, tags)",
  "vision.scene": "lieu (titre, description, lumière, humeur, décor, tags)",
  "vision.prop": "accessoire (nom, description, matière, taille, état, tags)",
  "vision.action": "action (nom, description, tempo, intention, caméra, tags)",
  "vision.costume": "costume (nom, description complète)",
  "still.header": "UNE SEULE IMAGE CLÉ pour la continuité vidéo (pas un plateau multi-vignettes). Un photogramme héros qui correspond au plan prévu. Pas de texte, logos, filigranes ni UI.",
  "still.revision": "AMÉLIORATION UTILISATEUR POUR CE STILL (obligatoire) : {{notes}}",
  "still.regenTask": "TÂCHE : révisez le prompt directeur image vers vidéo et gardez-le utilisable comme brief de keyframe.",
  "still.userImprove": "DEMANDE D’AMÉLIORATION :\n{{notes}}",
  "still.currentPrompt": "Prompt professionnel actuel :",
  "still.hardRules": "RÈGLES FERMES (à la fin ; ne les affaiblissez pas) :",
  "mediaGen.writeOne": "Rédigez UN prompt d’image final pour un still de drama court.",
  "mediaGen.returnOnly": "SEULEMENT le texte du prompt — pas de markdown.",
  "mediaGen.singleComposite": "Décrivez UNE seule image composite.",
  "mediaGen.lockRefs": "Les images jointes sont la vérité visuelle (ordre Ref#). N’inventez pas une autre personne, boutique ou objet.",
  "mediaGen.videoSystem": "Vous rédigez des prompts de réalisateur image vers vidéo.",
  "mediaGen.videoMerge": "Fusionnez les matériaux en UN prompt vidéo.",
  "mediaGen.videoInclude": "Inclure : verrou d’identité, caméra, jeu/dialogue, rythme, lumière.",
  "mediaGen.videoFacts": "Faits des matériaux et du seed seulement. Pas de Demo.",
  "mediaGen.videoNoSwap": "Avec refs, ne changez ni acteur, lieu ni accessoire.",
  "mediaGen.videoHardRules": "RÈGLES FERMES à la fin s’il y en a.",
  "mediaGen.imageSystem": "Vous êtes directeur de prompts image.",
  "mediaGen.imageMergeStills": "Fusionnez matériaux et stills en UN prompt image.",
  "mediaGen.imageMergeText": "Fusionnez les textes en UN prompt image.",
  "mediaGen.imagePriority": "Priorité : visages/costumes/lieux/accessoires des images.",
  "mediaGen.imageNoSwap": "Ne substituez pas une autre célébrité ou un autre set s’il y a des stills de cast.",
  "mediaGen.imageFacts": "Faits des matériaux et du seed seulement.",
  "mediaGen.imageLayout": "Multipan visé : conservez le nombre exact de cases.",
  "mediaGen.imagePackage": "S’il y a un LAYOUT, le prompt DOIT l’appliquer exactement.",
  "mediaGen.imageHardRules": "RÈGLES FERMES à la fin s’il y en a.",
  "mediaGen.directorFallback": "Image vers vidéo : animez ce photogramme. Verrouillez identité, costume, décor et cadrage.",
  "comic.taskHint": "Histoire « {{title}} », page BD {{n}} : une page terminée, exactement {{count}} case(s). Identité, costume et lieu continus sur toute la page. Pas de filigrane ni de cadre d’interface.",
  "comic.panelCount": "Nombre de cases fixe : exactement {{n}} case(s).",
  "comic.lockSplash": "Verrou de mise en page : une case pleine page. Interdit : cadres en plus, découpe, collage.",
  "comic.lockYonkoma": "Verrou : 4-koma vertical, 4 rangées × 1 colonne, haut vers bas. Interdit : grille 2×2 ou bandeau.",
  "comic.lockGrid2x2": "Verrou : 2 rangées × 2 colonnes. Interdit : bandeau, 2×3, splash pleine page.",
  "comic.lockGrid2x3": "Verrou : 2 rangées × 3 colonnes. Haut 1-2-3, bas 4-5-6. Interdit : 2×2 ou 3×3.",
  "comic.lockGrid3x3": "Verrou : 3 rangées × 3 colonnes = neuf cases. Interdit : 2×2, 2×3, ou moins de cases.",
  "comic.lockStrip": "Verrou : une seule rangée horizontale de exactement {{n}} cases. Interdit : grilles multi-rangées.",
  "comic.layoutSplash1": "Une page BD verticale : exactement une case pleine page, sans gouttières ni cadres extra.",
  "comic.layoutStrip2": "Une page paysage : deux cases égales côte à côte, gouttières blanches épaisses.",
  "comic.layoutStrip3": "Une page paysage : trois cases égales sur une rangée, gouttières blanches épaisses.",
  "comic.layoutYonkoma": "Une page verticale : 4-koma empilé (4×1), gouttières blanches épaisses, lecture haut vers bas.",
  "comic.layoutGrid2x2": "Une page carrée : grille 2×2, exactement quatre cases, gouttières blanches, gauche→droite puis haut→bas.",
  "comic.layoutStrip4": "Une large page paysage : quatre cases sur une rangée, gouttières blanches épaisses.",
  "comic.layoutGrid2x3": "Une page paysage : exactement six cases, 2 rangées × 3 colonnes (haut 1-2-3, bas 4-5-6), gouttières blanches, gauche→droite puis haut→bas.",
  "comic.layoutGrid3x3": "Une page carrée : grille 3×3, exactement neuf cases, gouttières blanches, gauche→droite puis haut→bas.",
  "comic.layoutWidePlusTwo": "Une page BD verticale : grande case pleine largeur en haut (~60 %), puis deux petites cases côte à côte, gouttières blanches épaisses.",
  "comic.layoutTwoPlusWide": "Une page verticale : deux petites cases en haut, puis une large case de clôture en bas (~60 %), gouttières blanches épaisses.",
  "comic.layoutTallLeftTwo": "Une page verticale : case haute sur toute la hauteur à gauche, deux cases empilées à droite, gouttières blanches épaisses.",
  "comic.layoutHeroPlusThree": "Une page verticale : grande case en haut, puis trois petites cases en une rangée, gouttières blanches épaisses.",
  "comic.layoutFocusQuad": "Une page verticale : case moyenne en haut à gauche, deux petites empilées à droite, grande case en bas, gouttières blanches épaisses.",
  "comic.layoutStaggerFour": "Une page verticale : 2+2 décalé — haut large puis étroit, bas étroit puis large, gouttières blanches épaisses.",
  "comic.layoutDiagPairPlus": "Une page verticale : la moitié haute est coupée en diagonale en deux coins ; le bas est un rectangle large, gouttières blanches épaisses.",
  "comic.layoutHeroPlusFour": "Une page verticale : grande case en haut, puis quatre petites en 2×2 en bas, gouttières blanches épaisses.",
  "comic.lockWidePlusTwo": "Verrouillage : case haute large. En bas exactement deux petites. Interdit : trois bandes égales ou grille 2×2.",
  "comic.lockTwoPlusWide": "Verrouillage : deux petites en haut, une large en bas. Interdit : trois bandes égales ou 2×2.",
  "comic.lockTallLeftTwo": "Verrouillage : case gauche sur toute la hauteur. Droite : deux empilées. Interdit : 2×2 égal ou bande horizontale.",
  "comic.lockHeroPlusThree": "Verrouillage : grande case en haut. En bas exactement trois petites. Interdit : 2×2 ou quatre cases égales.",
  "comic.lockFocusQuad": "Verrouillage : moyenne en haut à gauche, deux petites empilées, grande en bas. Interdit : 2×2 égal.",
  "comic.lockStaggerFour": "Verrouillage : tailles décalées — haut large+étroit, bas étroit+large. Interdit : quatre carrés égaux.",
  "comic.lockDiagPairPlus": "Verrouillage : haut en deux coins diagonaux ; bas un rectangle large. Interdit : trois bandes ou 2×2.",
  "comic.lockHeroPlusFour": "Verrouillage : grande case en haut ; 2×2 de quatre petites en bas. Exactement cinq. Interdit : 3×3 ou 2×2 pleine page.",
  "comic.readingYonkoma": "Lecture : uniquement de haut en bas (4-koma vertical).",
  "comic.readingWidePlusTwo": "Lecture : grande case du haut, puis les deux petites de gauche à droite.",
  "comic.readingTwoPlusWide": "Lecture : gauche puis droite en haut, puis la large du bas.",
  "comic.readingTallLeftTwo": "Lecture : case haute de gauche, puis haut droit, puis bas droit.",
  "comic.readingHeroPlusThree": "Lecture : grande case du haut, puis les trois petites de gauche à droite.",
  "comic.readingFocusQuad": "Lecture : moyenne en haut à gauche, deux petites de haut en bas, puis grande du bas.",
  "comic.readingStaggerFour": "Lecture : haut gauche, haut droit, bas gauche, bas droit.",
  "comic.readingDiagPairPlus": "Lecture : coin haut-gauche, coin bas-droit, puis large du bas.",
  "comic.readingHeroPlusFour": "Lecture : grande case du haut, puis les quatre petites gauche→droite et haut→bas.",
  "comic.readingOrder": "Lecture : gauche → droite, puis haut → bas (4-koma vertical : haut → bas seulement).",
  "comic.panelNumbers": "Petits numéros 1–{{n}} en haut à gauche de chaque case.",
  "comic.panelLine": "Case {{i}}/{{n}} ({{label}}) : {{cap}}",
  "comic.panelEmpty": "Case {{i}}/{{n}} ({{label}}) : un instant d’histoire distinct et enchaîné.",
  "comic.identity": "Même identité, costume et lieu dans toutes les cases de cette page.",
  "comic.finished": "C’est une page BD terminée, pas un collage de photos ni une maquette d’interface.",
  "comic.layoutLead": "Mise en page : {{layout}}",
  "comic.prevPage": "Page précédente. Gardez identité, costume et lieu, sans copier la grille précédente.",
  "comic.ownPage": "Rendu existant de cette page. Sert de base d’identité / de mise en page pour une révision.",
  "comic.galleryRef": "Still d’identité (cast ou décor). Faire correspondre visages, costumes et lieu.",
  "comic.profileLine": "Page BD {{n}} de l’histoire « {{title}} ».",
  "comic.styleBible": "Note de style : {{note}}",
  "comic.artMedium": "Style graphique : {{art}}",
  "comic.fallbackClose": "Page BD imprimée terminée. Gouttières blanches épaisses. Petits numéros. Pas de filigrane, d’UI ni de collage album.",
  "comic.hardRules": "Règles fermes",
  "comic.introTask": "Image vers vidéo : animer la planche terminée de « {{title}} », planche {{n}}, exactement {{count}} case(s). Verrouiller identité, costume et mise en page sur l’image jointe.",
  "comic.introLock": "Verrou : mêmes visages, costumes, lieux, gouttières et numéros que l’image. Ne pas inventer une autre page ni une autre personne.",
  "comic.introLayout": "Conserver cette mise en page : {{layout}}",
  "comic.introCamera": "Caméra : lent travelling avant ou léger panoramique dans l’ordre de lecture. Léger mouvement papier uniquement. Pas de coupe vers une autre mise en page.",
  "comic.introClose": "Pas de filigrane ni de cadre d’interface ; pas de sous-titres en plus des bulles déjà dessinées.",
  "comic.dramaStillLock": "Verrouiller identité, costume et lieu sur la planche jointe, mais jouer un plan de court-métrage live — pas un travelling sur du papier imprimé.",
  "comic.dramaCamera": "Caméra et jeu : rythme de court-métrage, jeu clair, synchro labiale aux répliques des cases. Continuité avec la page précédente si une image est jointe.",
  "comic.formatLockTall": "Format de page : la planche entière doit être verticale 9:16. Pas de composition paysage.",
  "comic.formatLockSquare": "Format de page : la planche entière doit être carrée 1:1.",
  "comic.formatLockWide": "Format de page : la planche entière doit être horizontale 16:9.",
  "art.photoCinematic": "Support obligatoire : photogramme cinématographique photoréaliste. Rendu caméra réelle, matières naturelles, étalonnage cinéma. Doit ressembler à une photo ou une image de film. Interdit : anime, cellulo, illustration 2D, contours cartoon, argile, CGI plastique.",
  "art.photoPortrait": "Support obligatoire : portrait studio photoréaliste. Éclairage boîte à lumière, clarté de headshot commercial. Doit être une photographie. Interdit : anime, encre de BD, jouet 3D, aplat cellulo.",
  "art.photoDocumentary": "Support obligatoire : photo documentaire photoréaliste. Lumière naturelle, textures honnêtes. Doit sembler prise sur un vrai appareil. Interdit : anime, CGI stylisé, illustration.",
  "art.cgiFilm": "Support obligatoire : personnage 3D CGI de qualité cinéma. Matériaux PBR, reflets ray-tracés. Doit paraître rendu 3D, ni photo réelle ni anime 2D. Interdit : photo live, lineart anime, encre de BD plate.",
  "art.cgiStylized": "Support obligatoire : 3D stylisé premium (CGI de long métrage). Formes lisibles, PBR doux. Doit être du CGI 3D. Interdit : live photoréaliste, cellulo 2D, BD esquissée.",
  "art.cgiClay": "Support obligatoire : personnage 3D argile / sculpture. Argile mate, formes sculptées. Doit se lire comme une sculpture d’argile. Interdit : photo de peau, cellulo anime, BD à l’encre.",
  "art.animeModern": "Support obligatoire : anime TV japonais moderne 2D. Trait numérique propre, cellulo doux, yeux et mèches anime. Toute l’image doit être de l’anime 2D. Interdit : photo, pores réels, rendu 3D, encre western seule, peinture à l’huile.",
  "art.animeShonen": "Support obligatoire : visuel clé shonen 2D. Trait fort, cellulo contrasté, yeux anime nets. Doit être du shonen 2D. Interdit : photo, CGI 3D, aquarelle seule.",
  "art.animeShoujo": "Support obligatoire : anime shoujo 2D. Trait délicat, dégradés doux, yeux lumineux. Doit être du shoujo. Interdit : photo, 3D dur, encre de BD rude.",
  "art.animeGekiga": "Support obligatoire : anime gekiga / réaliste 2D. Trait mature, palette retenue, clairement 2D. Interdit : photo live, chibi, CGI 3D pur.",
  "art.animeChibi": "Support obligatoire : chibi / super-deformed 2D. Grande tête, petit corps, traits simplifiés. Doit être du chibi. Interdit : proportions photoréalistes, 3D réaliste, live détaillé.",
  "art.donghua": "Support obligatoire : key art de donghua chinois. Costume raffiné, silhouette élégante, 2D ou 2,5D. Doit se lire comme du donghua. Interdit : live hollywoodien, BD de journal western seule.",
  "art.manhwa": "Support obligatoire : manhwa / webtoon coréen en couleurs. Peinture numérique douce, contours nets, cheveux lustrés. Doit être du manhwa 2D. Interdit : photo, argile 3D, encre super-héros seule.",
  "art.comicWestern": "Support obligatoire : bande dessinée occidentale. Encre assurée, aplats ou cellulo limité, formes graphiques. Doit être une illustration de BD. Interdit : photo, style yeux anime seul, rendu argile.",
  "art.conceptGame": "Support obligatoire : concept art de personnage AAA. Feuille peinte, silhouette forte. Doit ressembler à du concept, pas à une capture ni à une photo. Interdit : portrait photo pur, chibi seul.",
  "art.illustrationSoft": "Support obligatoire : illustration numérique douce. Pinceau délicat, fini proche de l’album. Doit être une illustration peinte. Interdit : photo caméra, cellulo dur, argile 3D.",
  "mediaGen.polishTask": "Tâche : {{hint}}",
  "mediaGen.polishKind": "Type : {{kind}}",
  "mediaGen.polishMaterials": "—— Matériaux ——",
  "mediaGen.polishEndMaterials": "—— Fin des matériaux ——",
  "mediaGen.polishRef": "Réf. n°{{n}} — {{title}}",
  "mediaGen.videoTaskHint": "Rédiger une consigne réalisateur image-vers-vidéo à partir de l’image clé ({{kind}}). Caméra, jeu, rythme ; verrouiller l’image clé.",
  "mediaGen.directorFallbackCam": "Caméra et jeu clairs ; pas de sous-titres ni filigrane.",
  "charIntro.task": "Image vers vidéo : animez la même personne pour un court auto-casting.",
  "charIntro.identityLock": "VERROU D’IDENTITÉ : même visage, cheveux, corps, âge, costume et couleurs.",
  "charIntro.personality": "Personnalité / vibe : {{personality}}.",
  "charIntro.backstory": "Histoire : {{backstory}}.",
  "charIntro.relationships": "Relations : {{relationships}}.",
  "charIntro.soul": "Extrait soul (source de jeu) : {{soul}}",
  "charIntro.performance": "Jeu : léger travelling ou caméra à l’épaule ; regard caméra ; {{manner}}.",
  "charIntro.speech": "Parole : la bouche bouge comme une courte présentation ; voix : {{voice}}.",
  "charIntro.beat": "Idle naturel → sourire ou hochement → geste bref → hold.",
  "charIntro.lighting": "Lumière cohérente avec le still ; pas de texte, logo ni figurants.",
  "sceneIntro.task": "Image vers vidéo : animez le même lieu en plan d’établissement.",
  "sceneIntro.spaceLock": "VERROU D’ESPACE : même architecture, matières, enseignes, plan et couleurs.",
  "sceneIntro.name": "Nom du lieu : {{name}}.",
  "sceneIntro.place": "Description : {{place}}.",
  "sceneIntro.spaceType": "Type d’espace : {{type}}.",
  "sceneIntro.time": "Moment : {{time}}.",
  "sceneIntro.weather": "Météo : {{weather}}.",
  "sceneIntro.moodLight": "Humeur : {{mood}}. Lumière : {{lighting}}.",
  "sceneIntro.palette": "Palette : {{palette}}.",
  "sceneIntro.setDressing": "Décor : {{set}}.",
  "sceneIntro.tags": "Tags visuels : {{tags}}.",
  "sceneIntro.art": "Style : {{art}}.",
  "sceneIntro.ambient": "Ambiance (sans texte UI) : {{sound}}.",
  "sceneIntro.scriptCue": "Indice de beat (atmosphère seulement) : {{cue}}.",
  "sceneIntro.camera": "Caméra : {{camera}} ; mouvement continu. N’ajoutez pas de visages, logos ni texte sauf si les matériaux les montrent déjà.",
  "sceneIntro.beat": "Établir → vie environnementale subtile → hold.",
  "propIntro.task": "Image vers vidéo : animez le même accessoire en intro produit.",
  "propIntro.objectLock": "VERROU D’OBJET : même silhouette, matières, couleurs, gravures et usure.",
  "propIntro.name": "Nom : {{name}}.",
  "propIntro.look": "Apparence : {{look}}.",
  "propIntro.material": "Matière : {{material}}.",
  "propIntro.size": "Taille : {{size}}.",
  "propIntro.condition": "État : {{condition}}.",
  "propIntro.tags": "Tags : {{tags}}.",
  "propIntro.art": "Style : {{art}}.",
  "propIntro.camera": "Orbite douce ou travelling lent sur table propre ; lumière cohérente.",
  "propIntro.beat": "Hold → éclat / micro-rotation → hold.",
  "propIntro.noHands": "Pas de mains ni visages nouveaux s’ils n’y sont pas ; pas de texte ni extras.",
  "costumeIntro.task": "Image vers vidéo : animez le même look en intro costume.",
  "costumeIntro.wardrobeLock": "VERROU DE COSTUME : même silhouette, tissus, couleurs, couches et accessoires.",
  "costumeIntro.identityOrProduct": "Personne : verrouillez visage/corps ; mannequin / à plat : cadrage produit.",
  "costumeIntro.name": "Nom du look : {{name}}.",
  "costumeIntro.desc": "Costume : {{look}}.",
  "costumeIntro.art": "Style : {{art}}.",
  "costumeIntro.camera": "Léger travelling ou orbite ; lumière mode cohérente.",
  "costumeIntro.beat": "Hold → tombé de tissu / éclat de quincaillerie → hold.",
  "costumeIntro.forbid": "Pas de nouveaux visages, texte, logos ni pose érotique.",
  "costumeIntro.fallbackName": "Tenue",
  "actionIntro.lead": "Démo de mouvement « {{name}} ».",
  "actionIntro.intention": "Intention : {{intention}}",
  "actionIntro.body": "Corps/tempo : {{body}}",
  "actionIntro.camera": "Caméra : {{camera}}",
  "actionIntro.closing": "Mouvement continu, sans texte ; suivez le still.",
  "sceneIntroPolish.task": "TÂCHE : intro de lieu (image-vers-vidéo).",
  "sceneIntroPolish.hasRef": "Still de lieu joint — verrouillez l’identité SPATIALE.",
  "sceneIntroPolish.noRef": "Pas de still ; verrouillez à la bible du lieu.",
  "sceneIntroPolish.dossier": "Dossier du lieu :",
  "sceneIntroPolish.scriptCue": "indice de script (atmosphère seulement) :\n{{script}}",
  "sceneIntroPolish.emptySet": "Plateau vide ; pas de nouveaux visages. Pas de texte ni logos.",
  "propIntroPolish.task": "TÂCHE : intro héros d’accessoire (image-vers-vidéo).",
  "propIntroPolish.hasRef": "Still d’accessoire joint — verrouillez l’OBJET.",
  "propIntroPolish.noRef": "Pas de still ; verrouillez au dossier.",
  "propIntroPolish.dossier": "Dossier accessoire :",
  "propIntroPolish.noHands": "Pas de nouvelles mains ni visages. Pas de texte ni logos.",
  "costumeIntroPolish.task": "TÂCHE : intro costume / look (image-vers-vidéo).",
  "costumeIntroPolish.hasRef": "Still joint — personne : identité+costume ; mannequin : silhouette et matières.",
  "costumeIntroPolish.noRef": "Pas de still ; verrouillez à la description.",
  "costumeIntroPolish.dossier": "Dossier costume :",
  "costumeIntroPolish.fabric": "Tombé subtil ; pas de nouveaux visages ni texte.",
  "actionIntroPolish.task": "TÂCHE : intro de guide de mouvement (image-vers-vidéo).",
  "actionIntroPolish.hasRef": "Still joint — verrouillez l’identité de jeu à ce cadre.",
  "actionIntroPolish.templateKeepRules": "Brouillon modèle (améliorez ; RÈGLES FERMES à la fin) :",
  "cover.posterLead": "AFFICHE / KEY ART professionnel 16:9. Pas de mockup UI. Pas de texte, logo ni filigrane.",
  "cover.titleMood": "Titre (humeur seulement, ne l’écrivez pas) : {{title}}.",
  "cover.styleBible": "Bible de style : {{style}}",
  "cover.extraDir": "Direction extra : {{idea}}",
  "cover.establishing": "Plan d’établissement évocateur pour une couverture de bibliothèque.",
  "cover.medium": "Respectez le medium ; silhouette forte.",
  "cover.editPrefix": "Édition d’image : nouvelle composition d’affiche. Gardez identité et humeur. ",
  "cover.label": "Couverture d’histoire",
  "costumeFill.system": "Vous êtes costumier. JSON compact seulement. Si image, décrivez CET habit fidèlement.",
  "costumeFill.idea": "Idée : {{idea}}",
  "costumeFill.polish": "Peaufinez le brouillon de costume.",
  "costumeFill.required": "Clés : name, description, artStyle, hardRules. Manquer = invalide.",
  "costumeFill.fallbackName": "Tenue",
  "segment.entireStory": "Toute l’histoire (toutes les scènes)",
  "segment.noStory": "Aucune histoire (fiche personnage seulement)",
  "vision.inventFromImage": "Décrivez et inventez un profil {{kind}} complet à partir de la photo jointe.",
  "vision.polishAll": "Peaufinez et fusionnez tous les champs",
  "story.untitled": "Drama court sans titre",
  "action.castIdentityNote": "Stills d’identité ({{count}}) : visage/corps identiques aux références de cast dans chaque case.",
  "tpl.system.polishOnly": "RECETTE peaufiner seulement : gardez identité et monde. Peaufinez le texte. N’inventez ni ère, météo, métier, lieu ni monde échantillon. N’inventez pas la langue parlée. N’écrivez pas de RÈGLES FERMES par défaut dans le profil.",
  "tpl.system.fillBlanks": "RECETTE vides seulement : remplissez UNIQUEMENT les clés vides. Ne réécrivez pas les champs remplis. N’inventez pas un autre monde.",
  "tpl.system.invent": "RECETTE inventer : l’utilisateur autorise la création libre. Complétez chaque clé filmable. N’importez aucun Demo ni monde non impliqué.",
  "tpl.system.fromStory": "RECETTE depuis l’histoire : utilisez seulement titre/style/cast/scènes de CETTE requête. En conflit, l’idée utilisateur gagne.",
  "tpl.system.followAsset": "RECETTE suivre l’actif : suivez le style déjà fourni. N’imposez pas le cinéma, le plateau vide ni 6–10 s sauf si les matériaux le disent. Utilisez la durée réelle du clip.",
  "tpl.system.cinematicLock": "RECETTE ciné+anti-hallu : look cinématographique ; plateau vide ; pas de filigrane, logo ni visage en trop ; deux mains/bras/jambes sauf non-humain.",
  "tpl.system.identityLock": "RECETTE verrou d’identité : verrouillez visage/corps/costume/lieu/accessoire aux stills. Ne substituez pas une autre personne, un autre lieu ou objet.",
  "tpl.system.restyle": "RECETTE restyle : même personne. Costume, décor et époque peuvent changer si demandé. Pas une autre personne.",
  "pipeline.character.system": "Vous peaufinez les bibles de personnages. 3–5 lignes : look, voix, motif, geste. Uniquement les faits de cette requête.",
  "pipeline.scene.system": "Vous déployez les scènes en feuilles de beats. Durée réelle des matériaux ; n’assumez pas 6–10 s. Scènes fournies seulement.",
  "pipeline.props.system": "Vous peaufinez la continuité des accessoires. Couleur, taille, apparition. N’inventez pas d’accessoires absents.",
  "pipeline.script.system": "Vous êtes scénariste. Un bloc compact par scène pour la vidéo IA. Durée réelle ; pas de plafond 10 s. Format :\n### SCENE <number> | id=<id>\n<script body>",
  "pipeline.script.noScenes": "(pas de scènes — n’inventez pas de lieux)",
  "keyArt.task": "Image clé {{n}} de l’histoire « {{title}} ». Une image publicitaire achevée. Pas de cases de bande dessinée, pas de numéros, pas d’interface.",
  "keyArt.lockCover": "AFFICHE DE COUVERTURE : visuel paysage pour la fiche. Laisse une bande sûre pour le titre. Visages lisibles. N’invente ni logo ni faux générique.",
  "keyArt.lockPoster": "AFFICHE VERTICALE : un seul one-sheet. Le héros se lit sur téléphone. Aucune autre affiche dans le cadre.",
  "keyArt.lockStill": "PHOTogramme : un plan cinéma, comme extrait du drama. Jeu naturel, espace réel. Pas un collage.",
  "keyArt.lockPromo": "VISUEL PROMO : personnage et monde dans le même cadre. Silhouette forte, une seule humeur. Pas une planche-contact.",
  "keyArt.lockSocial": "STORY SOCIALE : cadre vertical 9:16. Sujet large. Marges pour le texte à l’écran.",
  "keyArt.lockHeadshot": "GROS PLAN DU HÉROS : un visage de face qui remplit le cadre, identique aux références. Épaules permises. Personne d’autre.",
  "keyArt.lockBust": "PROMO BUSTE : buste, col du costume visible, regard caméra.",
  "keyArt.lockGroup": "DISTRIBUTION : tous les personnages nommés dans un cadre, même monde, même lumière. Ne retire ni ne change un visage.",
  "keyArt.formatLockTall": "VERROU FORMAT : toute l’image est un cadre haut 9:16. Pas de composition paysage.",
  "keyArt.formatLockSquare": "VERROU FORMAT : toute l’image est un cadre carré 1:1.",
  "keyArt.formatLockWide": "VERROU FORMAT : toute l’image est un cadre large 16:9.",
  "keyArt.methodFreshLock": "MÉTHODE : générer une nouvelle image. Les références ne servent qu’à l’identité. Ne copie pas le cadrage d’une ancienne prise.",
  "keyArt.methodEditLock": "MÉTHODE : modifier l’image jointe. Garde la composition sauf si le brief demande le contraire.",
  "keyArt.methodIdentityLock": "MÉTHODE : verrouille les visages sur les références du personnage. Pose, recadrage et costume peuvent changer.",
  "keyArt.methodContinueLock": "MÉTHODE : enchaîne depuis l’image précédente. Mêmes personnes, même lieu, plan suivant du même tournage.",
  "keyArt.briefLine": "Brief de mise en scène : {{brief}}",
  "keyArt.beatLine": "Beat lié : {{beat}}",
  "keyArt.close": "Image {{aspect}} achevée. Pas de filigrane, pas de cadre d’interface, pas de sous-titres en plus.",
}
