import type { PromptCopyTable } from './keys'

export const frPromptCopy: PromptCopyTable = {
  "speechLock.named": "SPEECH LOCK · Personnage « {{who}} » : la voix audible ET le lip-sync DOIVENT être uniquement {{primaryName}} ({{primary}}). Ne passez pas à {{forbid}} ni à une autre langue. Gardez la même langue à chaque clip. Ne traduisez pas les répliques.",
  "speechLock.unnamed": "SPEECH LOCK · Personnages parlants : la voix audible ET le lip-sync DOIVENT être uniquement {{primaryName}} ({{primary}}). Ne passez pas à {{forbid}} ni à une autre langue. Gardez la même langue à chaque clip. Ne traduisez pas les répliques.",
  "speechLock.namedMulti": "SPEECH LOCK · Personnage « {{who}} » : la voix audible ET le lip-sync DOIVENT être {{primaryName}} ({{primary}}). Autres langues UNIQUEMENT si la réplique écrite est déjà dans cette langue : {{extras}}. Jamais une troisième langue. Ne changez pas de langue entre les clips. Ne passez pas à {{forbid}}. Ne traduisez pas.",
  "speechLock.unnamedMulti": "SPEECH LOCK · Personnages parlants : la voix audible ET le lip-sync DOIVENT être {{primaryName}} ({{primary}}). Autres langues UNIQUEMENT si la réplique écrite est déjà dans cette langue : {{extras}}. Jamais une troisième langue. Ne changez pas de langue entre les clips. Ne passez pas à {{forbid}}. Ne traduisez pas.",
  "storyBeats.system": "You write short-drama TIMELINE BEATS for AI video.\nEach beat = ONE short clip screenplay (not a single spoken line).\nA beat MUST include rich performance content: mood, atmosphere, actions, expressions, optional camera/sfx, and zero or more spoken dialogue lines (1–4 lines common).\nReturn ONLY a JSON array (no fences). Each item shape:\n{\"characterName\":\"…\",\"characterNames\":[\"…\"],\"sceneHint\":\"…\",\"propName\":\"…\",\"mood\":\"…\",\"atmosphere\":\"…\",\"camera\":\"…\",\"sfx\":\"…\",\"units\":[{\"type\":\"action\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"expression\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"dialogue\",\"who\":\"…\",\"line\":\"…\",\"tone\":\"…\",\"parenthetical\":\"…\"},{\"type\":\"note\",\"text\":\"…\"}]}\nRules:\n- units.type dialogue.line = ONLY words the character speaks (no stage directions inside line).\n- Put physical business in action; face/micro-performance in expression; delivery in tone/parenthetical.\n- Multiple dialogue units in one beat are encouraged when the clip has a short exchange or self-talk.\n- Pure action beats (no dialogue) are allowed.\n- Write 4–8 beats. Use only cast names provided.\n- Prefer conflict, clear visual action, filmable detail.\n- Stay faithful to the title, style, cast, and scenes provided; if thin, invent freely within that cast/world.\n- SPEECH: write each dialogue.line in that speaker's primary spoken language from the cast list. Do not switch languages between beats. Do not translate lines unless that is the character's listed language.",
  "storyBeats.userLead": "GÉNÉREZ des beats de scénario de clip avec TOUT le casting, scènes, accessoires, style et idée ci-dessous.",
  "storyBeats.eachBeat": "Chaque beat doit avoir humeur + atmosphère + actions/expressions + dialogues optionnels.",
  "storyBeats.story": "Histoire : {{title}}",
  "storyBeats.style": "Style : {{style}}",
  "storyBeats.userDir": "Consigne utilisateur : {{idea}}",
  "storyBeats.cast": "Casting :",
  "storyBeats.scenes": "Scènes :",
  "storyBeats.props": "Accessoires : {{props}}",
  "storyBeats.returnJson": "Renvoyez uniquement le tableau JSON des beats.",
  "storyBeats.noCast": "(pas de casting)",
  "storyBeats.noScenes": "(pas de scènes — inventez les lieux dans sceneHint)",
  "storyBeats.none": "(aucun)",
  "videoPolish.system": "You write ONE final image-to-video prompt for a short-drama AI video model.\nReturn ONLY the prompt text — no markdown fences, no title, no explanation.\nRules:\n- Write the director prompt in the user interface language; keep character names and required dialogue language codes clear.\n- Person still: IDENTITY LOCK (face, hair, body, wardrobe, colors). Location plate: SPACE LOCK (architecture, materials, layout, signage, palette) — empty set preferred; no new cast faces.\n- Use ALL provided profile / soul / beat / location facts that affect look, motion, speech, or atmosphere; ignore empty fields.\n- Invent only what is needed to complete a filmable clip from the materials and seed — do not import a fixed sample world, Demo story, or facts not present in materials/seed.\n- Condense long soul.md into actionable performance + identity beats; do not dump the whole bible verbatim.\n- Duration 6–10s; continuous action; cinematic; no text overlays, logos, watermarks, or extra unrelated people.\n- Anatomically correct humans unless the script requires otherwise (two hands, two arms, two legs).\n- If multi-character, keep each listed subject consistent; primary focus first.\n- If HARD RULES appear in materials, keep them and place them at the end of your output (highest priority).\n- SPEECH LOCK is mandatory: never drop, rewrite, or translate it. Expand language codes to full names. Every clip must use the character primary spoken language; do not switch languages between clips; do not translate dialogue lines.\n- Director revision may refine style/action but must NOT violate HARD RULES.",
  "videoPolish.hardRulesKeep": "HARD RULES (HIGHEST PRIORITY — keep every line; object labels like [Character · Name] must stay). Place the full HARD RULES block at the END of your output. Do not weaken, drop, or reassign rules.",
  "clip.task": "TÂCHE : clip de timeline de court-métrage (image vers vidéo).",
  "clip.hasRef": "A reference still may be attached — lock identity/location continuity to it when relevant.",
  "clip.characters": "Personnages :",
  "clip.scene": "Scène :",
  "clip.prop": "Accessoire :",
  "clip.action": "Guide d’action / mouvement :",
  "clip.beat": "Beat / dialogues :",
  "clip.prev": "Continuité du clip précédent :",
  "clip.revision": "RÉVISION DU RÉALISATEUR (obligatoire) :",
  "clip.templateDraft": "Brouillon de modèle (à améliorer) :",
  "intro.task": "TÂCHE : clip de présentation de casting (image vers vidéo).",
  "intro.hasRef": "Reference still is attached to the video API — lock identity to that image.",
  "intro.noRef": "No reference still path in this text; still lock to profile appearance/costume.",
  "intro.dossier": "Dossier personnage :",
  "intro.templateDraft": "Brouillon de modèle (améliorez ; n’ignorez pas le dossier) :",
  "common.durationAspect": "Durée : {{seconds}} s. Format : {{aspect}}.",
  "common.templateDraft": "Brouillon de modèle :",
  "improve.mode": "MODE AMÉLIORER : fusionnez TOUTES les sources en un résultat complet. Gardez l’identité sauf demande explicite.",
  "improve.draftDefault": "Champs actuels du formulaire :",
  "improve.userRequest": "Demande d’amélioration (vide = tout peaufiner) :",
  "improve.emptyDefault": "(peaufiner tous les champs pour la continuité)",
  "improve.createDefault": "Idée / direction :",
  "improve.explicitContext": "Contexte explicite de CETTE requête seulement (continuité ; n’importez aucun autre monde) :",
  "improve.storyTitle": "Titre : {{title}}",
  "improve.styleNote": "Note de style : {{style}}",
  "improve.closingDefault": "Produisez le résultat complet maintenant.",
  "storyMeta.system": "Vous êtes showrunner. Écrivez bible visuelle + règles dures. JSON uniquement.",
  "storyMeta.draftLabel": "Champs actuels de l’histoire :",
  "storyMeta.createLabel": "Idée / titre :",
  "storyMeta.emptyPolish": "(peaufiner bible + hardRules)",
  "storyMeta.closing": "JSON uniquement : {\"styleNote\":\"…\",\"hardRules\":\"…\"}. Les deux clés sont obligatoires.",
  "storyMeta.contextLabel": "Contexte (cast / scènes / accessoires) :",
  "character.system": "Vous êtes designer de personnages. Un seul JSON. spokenLanguages = tableau BCP-47.",
  "character.draftLabel": "Champs profil actuels :",
  "character.soulLabel": "soul.md / bible liée :",
  "character.createLabel": "Idée de personnage :",
  "character.emptyPolish": "(peaufiner et intégrer le soul)",
  "character.closing": "JSON complet. Clés : {{keys}}.",
  "scene.system": "Vous êtes designer de lieux. Bible du lieu + script de cette scène. JSON seul.",
  "scene.draftLabel": "Champs scène actuels :",
  "scene.charsLabel": "Personnages de l’histoire :",
  "scene.propsLabel": "Accessoires de l’histoire :",
  "scene.priorLabel": "Scènes déjà là (continuité) :",
  "scene.createLabel": "Idée de scène :",
  "scene.emptyPolish": "(peaufiner lieu + script)",
  "scene.closing": "JSON complet. Clés : {{keys}}.",
  "prop.system": "Vous êtes designer d’accessoires. Un seul JSON. Aspect, matière, état concrets.",
  "prop.draftLabel": "Champs accessoire actuels :",
  "prop.createLabel": "Idée d’accessoire :",
  "prop.emptyPolish": "(peaufiner l’aspect)",
  "prop.closing": "JSON complet. Clés : {{keys}}.",
  "prop.fallbackName": "Accessoire",
  "action.system": "Vous êtes directeur de mouvement. JSON valide seulement. Corps, tempo, poids, trajectoires.",
  "action.storyContext": "Contexte d’histoire (optionnel) : {{title}}",
  "action.styleNote": "Note de style : {{style}}",
  "action.existingDraft": "Brouillon existant à peaufiner :",
  "action.userIdea": "Idée utilisateur : {{idea}}",
  "action.closing": "JSON seulement. Clés : {{keys}}.",
  "profile.mustEveryKey": "Vous DEVEZ produire CHAQUE clé : {{keys}}.",
  "profile.valuesAreStrings": "Chaque valeur DOIT être une chaîne JSON. Vide seulement si inconnu.",
  "profile.visualTagsRule": "visualTags : une chaîne séparée par des virgules. JAMAIS un tableau JSON.",
  "profile.fillConcrete": "Remplissez avec des détails concrets.",
  "common.rules": "Règles :",
  "common.none": "(aucun)",
  "intro.soul": "soul.md (source d’interprétation / identité) :\n{{soul}}",
  "intro.matchBible": "(suivre la bible du personnage)",
  "invent.sources": "Sources de vérité, dans l’ordre : (1) idée / demande, (2) formulaire, (3) extras seulement s’ils sont dans CE prompt, (4) image jointe.",
  "invent.create": "Mode créer : inventez librement depuis l’idée/image ; ne laissez aucune clé obligatoire vide.",
  "invent.improve": "Mode améliorer : peaufinez le brouillon ; ne changez l’identité que sur demande.",
  "invent.noImport": "N’importez ni identité, intrigue, météo, métier, lieu, époque ou style hors de ce prompt.",
  "invent.storyBlock": "Un bloc histoire/style ne sert qu’à la continuité ; n’écrasez pas l’idée explicite.",
  "character.keysLead": "UN SEUL JSON avec les clés : {{keys}}",
  "character.ruleSpoken": "spokenLanguages : tableau BCP-47 des langues PARLÉES. [] si non verbal.",
  "character.ruleIdentity": "Identité cohérente pour planches et vidéo.",
  "character.fallbackPersonality": "présence chaleureuse et nette",
  "character.fallbackManner": "micro-gestes naturels",
  "character.fallbackVoice": "voix claire",
  "scene.keysLead": "UN SEUL JSON avec les clés : {{keys}}",
  "scene.suggestLead": "Proposez un LIEU prêt comme scène n° {{n}} pour « {{title}} ».",
  "scene.suggestPlotFocus": "Foyer narratif : {{label}}",
  "scene.suggestStyle": "Style : {{style}}",
  "scene.suggestExisting": "Lieux déjà là : {{titles}}",
  "scene.suggestChars": "Personnages (contexte) :",
  "scene.suggestProps": "Accessoires (contexte) :",
  "scene.suggestSegment": "Détail du segment :",
  "scene.suggestBeats": "Scènes / beats :",
  "scene.suggestClosing": "Renvoyez le JSON complet. Concevez un lieu distinct et réutilisable.",
  "scene.fallbackName": "Lieu",
  "scene.fallbackMood": "atmosphère cinématographique",
  "scene.fallbackLighting": "comme le still",
  "scene.fallbackCamera": "léger travelling d’établissement ou panoramique lent",
  "scene.ideaFromImage": "Inventez le profil de lieu complet à partir de la photo jointe.",
  "scene.polishIdea": "Peaufiner",
  "prop.keysLead": "UN SEUL JSON avec les clés : {{keys}}",
  "action.fieldsLead": "Champs : {{keys}}.",
  "soul.system": "Vous rédigez des soul.md de production. Markdown complet seulement. Respectez spokenLanguages. Langue de l’interface.",
  "soul.improveMode": "MODE AMÉLIORER : fusionnez profil + soul existant en un soul.md complet.",
  "soul.createMode": "Rédigez un soul.md complet à partir de ce profil (pas une autre personne) :",
  "soul.profileFields": "Champs du profil :",
  "soul.existing": "soul.md existant (fusionnez ; ne jetez pas le détail utile) :",
  "soul.userRequest": "Demande : {{request}}",
  "soul.extraContext": "Contexte supplémentaire (utile oui ; le profil gagne) :",
  "soul.returnOnly": "Renvoyez uniquement le markdown du soul.md.",
  "wardrobe.system": "Vous êtes consultant costumes. UN seul JSON. artStyle parmi : {{styleIds}}. Matières et silhouette concrètes. Jamais d’érotisation mineure.",
  "wardrobe.improveMode": "MODE AMÉLIORER / SUGGÉRER : utilisez TOUS les champs et le contexte.",
  "wardrobe.characterForm": "Personnage (formulaire complet) :",
  "wardrobe.soulExcerpt": "Extrait soul.md :\n{{soul}}",
  "wardrobe.userRequest": "Demande : {{request}}",
  "wardrobe.storyContext": "Contexte de production (s’il est là ; n’inventez pas un autre monde) :",
  "wardrobe.style": "style : {{style}}",
  "wardrobe.segment": "Segment choisi : {{label}}",
  "wardrobe.sceneContext": "Scène / beat :",
  "wardrobe.noScenes": "(pas encore de scènes)",
  "wardrobe.proposeNew": "Proposez un look NOUVEAU qui colle (pas un doublon).",
  "fill.system": "Vous complétez les champs vides. JSON avec EXACTEMENT ces clés : {{keys}}. Chaque valeur est une chaîne non vide. Jamais un tableau.",
  "fill.userPartial": "Profil partiel (ne contredisez pas) :",
  "fill.userOnly": "Remplissez SEULEMENT ces clés : {{keys}}.",
  "fill.userReturn": "JSON avec ces clés seulement ; valeurs non vides.",
  "imageGen.multiRef": "{{n}} stills de plus : le premier est la base ; gardez l’identité partout.",
  "residual.sceneLink": "Scène {{n}} : {{short}}",
  "residual.beatSegment": "Beat {{n}} · {{who}}{{tail}}",
  "residual.unknown": "Inconnu",
  "residual.story": "Histoire",
  "beat.mood": "[MOOD] {{text}}",
  "beat.atmo": "[ATMO] {{text}}",
  "beat.camera": "[CAMERA] {{text}}",
  "beat.sfx": "[SFX] {{text}}",
  "beat.action": "[ACTION] {{text}}",
  "beat.actionWho": "[ACTION|{{who}}] {{text}}",
  "beat.expr": "[EXPR] {{text}}",
  "beat.exprWho": "[EXPR|{{who}}] {{text}}",
  "beat.dialogue": "[DIALOGUE|{{who}}] {{body}}",
  "beat.dialogueTone": "[DIALOGUE|{{who}}|{{tone}}] {{body}}",
  "beat.whoUnknown": "?",
  "beat.template": "[MOOD] tense, hesitant\n[ATMO] door-gap warm light; rain on ground\n[CAMERA] medium shot, push to hands\n[SFX] rain, fabric rustle\n[ACTION|Name] removes helmet; stares at the door light; hand into jacket pocket\n[EXPR|Name] furrowed brow, breath catches\n[DIALOGUE|Name|low, hoarse] Raining again…\n[DIALOGUE|Name|aside] (beat) Are you… still there?",
  "vision.preamble": "Un still est joint. Remplissez TOUS les champs de ce {{what}} surtout DEPUIS L’IMAGE.",
  "vision.character": "identité (nom, apparence, costume, âge, genre, tags)",
  "vision.scene": "lieu (titre, description, lumière, humeur, décor, tags)",
  "vision.prop": "accessoire (nom, description, matière, taille, état, tags)",
  "vision.action": "action (nom, description, tempo, intention, caméra, tags)",
  "vision.costume": "costume (nom, description complète)",
  "still.header": "SINGLE KEYFRAME STILL for short-drama video continuity (not a multi-panel sheet). Produce one cinematic hero frame that matches the planned shot below. No text, logos, watermarks, UI chrome. Sharp, production-ready.",
  "still.revision": "AMÉLIORATION UTILISATEUR POUR CE STILL (obligatoire) : {{notes}}",
  "still.regenTask": "TÂCHE : révisez le prompt directeur image-to-video et gardez-le utilisable comme brief de keyframe.",
  "still.userImprove": "DEMANDE D’AMÉLIORATION :\n{{notes}}",
  "still.currentPrompt": "Prompt professionnel actuel :",
  "still.hardRules": "HARD RULES (à la fin ; ne les affaiblissez pas) :",
  "mediaGen.writeOne": "Rédigez UN prompt d’image final pour un still de drama court.",
  "mediaGen.returnOnly": "SEULEMENT le texte du prompt — pas de markdown.",
  "mediaGen.singleComposite": "Décrivez UNE seule image composite.",
  "mediaGen.lockRefs": "Les images jointes sont la vérité visuelle (ordre Ref#). N’inventez pas une autre personne, boutique ou objet.",
  "mediaGen.videoSystem": "Vous rédigez des prompts de réalisateur image-to-video.",
  "mediaGen.videoMerge": "Fusionnez les matériaux en UN prompt vidéo.",
  "mediaGen.videoInclude": "Inclure : verrou d’identité, caméra, jeu/dialogue, rythme, lumière.",
  "mediaGen.videoFacts": "Faits des matériaux et du seed seulement. Pas de Demo.",
  "mediaGen.videoNoSwap": "Avec refs, ne changez ni acteur, lieu ni accessoire.",
  "mediaGen.videoHardRules": "HARD RULES à la fin s’il y en a.",
  "mediaGen.imageSystem": "Vous êtes directeur de prompts image.",
  "mediaGen.imageMergeStills": "Fusionnez matériaux et stills en UN prompt image.",
  "mediaGen.imageMergeText": "Fusionnez les textes en UN prompt image.",
  "mediaGen.imagePriority": "Priorité : visages/costumes/lieux/accessoires des images.",
  "mediaGen.imageNoSwap": "Ne substituez pas une autre célébrité ou un autre set s’il y a des stills de cast.",
  "mediaGen.imageFacts": "Faits des matériaux et du seed seulement.",
  "mediaGen.imageLayout": "Multipan visé : conservez le nombre exact de cases.",
  "mediaGen.imagePackage": "S’il y a un LAYOUT, le prompt DOIT l’appliquer exactement.",
  "mediaGen.imageHardRules": "HARD RULES à la fin s’il y en a.",
  "mediaGen.directorFallback": "IMAGE-VERS-VIDÉO : animez ce keyframe. Verrouillez identité, costume, décor et cadrage.",
  "mediaGen.directorFallbackCam": "Caméra et jeu clairs ; pas de sous-titres ni filigrane.",
  "charIntro.task": "IMAGE-VERS-VIDÉO : animez la même personne pour un court auto-casting.",
  "charIntro.identityLock": "VERROU D’IDENTITÉ : même visage, cheveux, corps, âge, costume et couleurs.",
  "charIntro.personality": "Personnalité / vibe : {{personality}}.",
  "charIntro.backstory": "Histoire : {{backstory}}.",
  "charIntro.relationships": "Relations : {{relationships}}.",
  "charIntro.soul": "Extrait soul (source de jeu) : {{soul}}",
  "charIntro.performance": "Jeu : léger travelling ou caméra à l’épaule ; regard caméra ; {{manner}}.",
  "charIntro.speech": "Parole : la bouche bouge comme une courte présentation ; voix : {{voice}}.",
  "charIntro.beat": "Idle naturel → sourire ou hochement → geste bref → hold.",
  "charIntro.lighting": "Lumière cohérente avec le still ; pas de texte, logo ni figurants.",
  "charIntro.duration": "Convient à 6–10 s d’auto-casting.",
  "sceneIntro.task": "IMAGE-VERS-VIDÉO : animez le même lieu en plan d’établissement.",
  "sceneIntro.spaceLock": "VERROU D’ESPACE : même architecture, matières, enseignes, plan et couleurs.",
  "sceneIntro.name": "Nom du lieu : {{name}}.",
  "sceneIntro.place": "Description : {{place}}.",
  "sceneIntro.spaceType": "Type d’espace : {{type}}.",
  "sceneIntro.time": "Moment : {{time}}.",
  "sceneIntro.weather": "Météo : {{weather}}.",
  "sceneIntro.moodLight": "Humeur : {{mood}}. Lumière : {{lighting}}.",
  "sceneIntro.palette": "Palette : {{palette}}.",
  "sceneIntro.setDressing": "Décor : {{set}}.",
  "sceneIntro.tags": "Tags visuels : {{tags}}.",
  "sceneIntro.art": "Style : {{art}}.",
  "sceneIntro.ambient": "Ambiance (sans texte UI) : {{sound}}.",
  "sceneIntro.scriptCue": "Indice de beat (atmosphère seulement) : {{cue}}.",
  "sceneIntro.camera": "Caméra : {{camera}} ; plateau vide de préférence ; pas de nouveaux visages ni logos.",
  "sceneIntro.beat": "Établir → vie environnementale subtile → hold.",
  "sceneIntro.duration": "Convient à 6–10 s d’intro de lieu.",
  "propIntro.task": "IMAGE-VERS-VIDÉO : animez le même accessoire en intro produit.",
  "propIntro.objectLock": "VERROU D’OBJET : même silhouette, matières, couleurs, gravures et usure.",
  "propIntro.name": "Nom : {{name}}.",
  "propIntro.look": "Apparence : {{look}}.",
  "propIntro.material": "Matière : {{material}}.",
  "propIntro.size": "Taille : {{size}}.",
  "propIntro.condition": "État : {{condition}}.",
  "propIntro.tags": "Tags : {{tags}}.",
  "propIntro.art": "Style : {{art}}.",
  "propIntro.camera": "Orbite douce ou travelling lent sur table propre ; lumière cohérente.",
  "propIntro.beat": "Hold → éclat / micro-rotation → hold.",
  "propIntro.noHands": "Pas de mains ni visages nouveaux s’ils n’y sont pas ; pas de texte ni extras.",
  "propIntro.duration": "Convient à 6–10 s d’intro d’accessoire.",
  "costumeIntro.task": "IMAGE-VERS-VIDÉO : animez le même look en intro costume.",
  "costumeIntro.wardrobeLock": "VERROU DE COSTUME : même silhouette, tissus, couleurs, couches et accessoires.",
  "costumeIntro.identityOrProduct": "Personne : verrouillez visage/corps ; mannequin / à plat : cadrage produit.",
  "costumeIntro.name": "Nom du look : {{name}}.",
  "costumeIntro.desc": "Costume : {{look}}.",
  "costumeIntro.art": "Style : {{art}}.",
  "costumeIntro.camera": "Léger travelling ou orbite ; lumière mode cohérente.",
  "costumeIntro.beat": "Hold → tombé de tissu / éclat de quincaillerie → hold.",
  "costumeIntro.forbid": "Pas de nouveaux visages, texte, logos ni pose érotique.",
  "costumeIntro.duration": "Convient à 6–10 s d’intro costume.",
  "costumeIntro.fallbackName": "Look",
  "actionIntro.lead": "Démo de mouvement « {{name}} ».",
  "actionIntro.intention": "Intention : {{intention}}",
  "actionIntro.body": "Corps/tempo : {{body}}",
  "actionIntro.camera": "Caméra : {{camera}}",
  "actionIntro.closing": "Mouvement continu, cinématographique, sans texte ; suivez le still.",
  "sceneIntroPolish.task": "TÂCHE : intro de lieu (image-vers-vidéo).",
  "sceneIntroPolish.hasRef": "Still de lieu joint — verrouillez l’identité SPATIALE.",
  "sceneIntroPolish.noRef": "Pas de still ; verrouillez à la bible du lieu.",
  "sceneIntroPolish.dossier": "Dossier du lieu :",
  "sceneIntroPolish.scriptCue": "indice de script (atmosphère seulement) :\n{{script}}",
  "sceneIntroPolish.emptySet": "Plateau vide ; pas de nouveaux visages. Pas de texte ni logos.",
  "propIntroPolish.task": "TÂCHE : intro héros d’accessoire (image-vers-vidéo).",
  "propIntroPolish.hasRef": "Still d’accessoire joint — verrouillez l’OBJET.",
  "propIntroPolish.noRef": "Pas de still ; verrouillez au dossier.",
  "propIntroPolish.dossier": "Dossier accessoire :",
  "propIntroPolish.noHands": "Pas de nouvelles mains ni visages. Pas de texte ni logos.",
  "costumeIntroPolish.task": "TÂCHE : intro costume / look (image-vers-vidéo).",
  "costumeIntroPolish.hasRef": "Still joint — personne : identité+costume ; mannequin : silhouette et matières.",
  "costumeIntroPolish.noRef": "Pas de still ; verrouillez à la description.",
  "costumeIntroPolish.dossier": "Dossier costume :",
  "costumeIntroPolish.fabric": "Tombé subtil ; pas de nouveaux visages ni texte.",
  "actionIntroPolish.task": "TÂCHE : intro de guide de mouvement (image-vers-vidéo).",
  "actionIntroPolish.hasRef": "Still joint — verrouillez l’identité de jeu à ce cadre.",
  "actionIntroPolish.templateKeepRules": "Brouillon modèle (améliorez ; HARD RULES à la fin) :",
  "cover.posterLead": "AFFICHE / KEY ART professionnel 16:9. Pas de mockup UI. Pas de texte, logo ni filigrane.",
  "cover.titleMood": "Titre (humeur seulement, ne l’écrivez pas) : {{title}}.",
  "cover.styleBible": "Bible de style : {{style}}",
  "cover.extraDir": "Direction extra : {{idea}}",
  "cover.establishing": "Plan d’établissement évocateur pour une couverture de bibliothèque.",
  "cover.medium": "Respectez le medium ; silhouette forte.",
  "cover.editPrefix": "IMAGE EDIT : nouvelle composition d’affiche. Gardez identité/humeur. ",
  "cover.label": "Couverture d’histoire",
  "costumeFill.system": "Vous êtes costumier. JSON compact seulement. Si image, décrivez CET habit fidèlement.",
  "costumeFill.idea": "Idée : {{idea}}",
  "costumeFill.polish": "Peaufinez le brouillon de costume.",
  "costumeFill.required": "Clés : name, description, artStyle, hardRules. Manquer = invalide.",
  "costumeFill.fallbackName": "Look",
  "segment.entireStory": "Toute l’histoire (toutes les scènes)",
  "segment.noStory": "Aucune histoire (fiche personnage seulement)",
  "vision.inventFromImage": "Décrivez et inventez un profil {{kind}} complet à partir de la photo jointe.",
  "vision.polishAll": "Peaufinez et fusionnez tous les champs",
  "story.untitled": "Drama court sans titre",
  "action.castIdentityNote": "Stills d’identité ({{count}}) : visage/corps identiques aux références de cast dans chaque case."
}
