import type { PromptCopyTable } from './keys'

export const frPromptCopy: PromptCopyTable = {
  "speechLock.named": "Verrouillage des répliques · Personnage « {{who}} » : la voix audible ET le lip-sync DOIVENT être uniquement {{primaryName}} ({{primary}}). Ne passez pas à {{forbid}} ni à une autre langue. Gardez la même langue à chaque clip. Ne traduisez pas les répliques.",
  "speechLock.unnamed": "Verrouillage des répliques · Personnages parlants : la voix audible ET le lip-sync DOIVENT être uniquement {{primaryName}} ({{primary}}). Ne passez pas à {{forbid}} ni à une autre langue. Gardez la même langue à chaque clip. Ne traduisez pas les répliques.",
  "speechLock.namedMulti": "Verrouillage des répliques · Personnage « {{who}} » : la voix audible ET le lip-sync DOIVENT être {{primaryName}} ({{primary}}). Autres langues UNIQUEMENT si la réplique écrite est déjà dans cette langue : {{extras}}. Jamais une troisième langue. Ne changez pas de langue entre les clips. Ne passez pas à {{forbid}}. Ne traduisez pas.",
  "speechLock.unnamedMulti": "Verrouillage des répliques · Personnages parlants : la voix audible ET le lip-sync DOIVENT être {{primaryName}} ({{primary}}). Autres langues UNIQUEMENT si la réplique écrite est déjà dans cette langue : {{extras}}. Jamais une troisième langue. Ne changez pas de langue entre les clips. Ne passez pas à {{forbid}}. Ne traduisez pas.",
  "hardRules.sealHeader": "RÈGLES FERMES (priorité maximale — à respecter ; primer en cas de conflit) :",
  "hardRules.sealFooter": "En cas de conflit avec une instruction antérieure, suivez les RÈGLES FERMES.",
  "hardRules.labelStory": "Histoire",
  "hardRules.labelCharacter": "Personnage",
  "hardRules.labelScene": "Lieu",
  "hardRules.labelProp": "Accessoire",
  "hardRules.labelAction": "Mouvement",
  "continuity.lockHeader": "VERROU DE CONTINUITÉ (à respecter pour la séquence) :",
  "continuity.hasImage": "L’image jointe est la DERNIÈRE IMAGE / image clé du plan {{n}}. Ce plan continue depuis cet état visuel, sans coupe sèche vers un autre décor.",
  "continuity.noImage": "Enchaîner depuis le plan {{n}} (pas de photogramme — s’aligner sur le dossier).",
  "continuity.identity": "IDENTITÉ : même personne — visage, cheveux, proportions, couleurs de costume, accessoires. Pas de restyle ni changement d’âge.",
  "continuity.space": "ESPACE : même lieu — architecture, matériaux, plan, lumière. Dérive d’heure seulement si le plan l’exige.",
  "continuity.action": "ACTION : reprendre pose, regard et mouvement de l’image précédente ; pas de coupe vers une autre installation.",
  "continuity.prevContext": "Contexte du plan précédent : {{snippet}}",
  "continuity.noText": "Pas de sous-titres, logos ni filigranes.",
  "directorLabel.lock": "Verrouillage des répliques",
  "directorLabel.story": "Histoire : ",
  "directorLabel.style": "Style : ",
  "directorLabel.cast": "Distribution : ",
  "directorLabel.location": "Lieu : ",
  "directorLabel.prop": "Accessoire : ",
  "directorLabel.primaryChar": "Personnage principal : ",
  "directorLabel.mood": "Humeur : ",
  "directorLabel.atmo": "Atmosphère : ",
  "directorLabel.camera": "Caméra : ",
  "directorLabel.sfx": "Sons : ",
  "directorLabel.action": "Action : ",
  "directorLabel.expr": "Expression : ",
  "directorLabel.speech": "Répliques : ",
  "directorLabel.notes": "Notes : ",
  "directorLabel.identity": "Identité : ",
  "directorLabel.space": "Espace : ",
  "directorLabel.ref": "Photogramme ",
  "directorLabel.beatN": "Plan {{n}} · ",
  "directorLabel.beatNsec": "Plan {{n}} · {{s}} s",
  "directorLabel.hardRules": "RÈGLES FERMES",
  "directorLabel.identityLock": "Verrouillage d'identité",
  "directorLabel.spaceLock": "Verrouillage spatial",
  "storyBeats.system": "Tu écris les TEMPS FORTS de la chronologie pour une vidéo de court-métrage.\nChaque temps fort = le scénario d’UN clip court (pas une seule réplique).\nIl doit inclure humeur, atmosphère, actions, expressions, caméra/sfx facultatifs, et 0 à plusieurs répliques (souvent 1–4).\nRenvoie UNIQUEMENT un tableau JSON (sans clôtures). Forme de chaque élément :\n{\"characterName\":\"…\",\"characterNames\":[\"…\"],\"sceneHint\":\"…\",\"sceneHints\":[\"…\"],\"propName\":\"…\",\"propNames\":[\"…\"],\"actionName\":\"…\",\"actionNames\":[\"…\"],\"mood\":\"…\",\"atmosphere\":\"…\",\"camera\":\"…\",\"sfx\":\"…\",\"units\":[{\"type\":\"action\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"expression\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"dialogue\",\"who\":\"…\",\"line\":\"…\",\"tone\":\"…\",\"parenthetical\":\"…\"},{\"type\":\"note\",\"text\":\"…\"}]}\nRègles :\n- dialogue.line = les seuls mots dits ; pas de didascalie dans la réplique.\n- Le corps va dans action ; le visage dans expression ; le jeu dans tone/parenthetical.\n- Un échange court ou un monologue : plusieurs dialogue dans le même temps fort.\n- Un temps fort sans réplique est permis.\n- Ne mets PAS un temps fort par chapitre par défaut. Découpe en clips filmables : nouveau lieu, saut de temps, nouveau conflit, ou action/dialogue trop long pour 6–10s → un nouveau temps fort. En général 1–3 par chapitre. Au plus {{maxBeats}} au total.\n- Liste TOUS les personnages, scènes, accessoires et actions de la liste présents dans CE clip (characterNames, sceneHints, propNames, actionNames). Plafonds : 4 / 2 / 4 / 4. Pas un seul de chaque.\n- S’il y a du jeu physique, actionNames est OBLIGATOIRE avec les noms d’origine de la liste d’actions déjà choisie. Ne laisse pas vide : mieux vaut cocher ces actions que n’en mettre aucune.\n- Max 4 units par temps fort (1–2 action, 0–1 expression, 0–2 dialogue). Textes courts, un seul JSON. Noms du casting fourni uniquement.\n- Conflit, action visible, détail filmable.\n- Fidèle au titre, au style, au casting et aux scènes. N’élargis pas le monde.\n- Chaque dialogue.line dans la langue principale du locuteur (liste de casting). Pas de changement de langue entre temps forts. Ne traduis que si c’est la langue listée.",
  "storyBeats.userLead": "GÉNÉREZ des beats de scénario de clip avec TOUT le casting, scènes, accessoires, actions, style et idée ci-dessous.",
  "storyBeats.eachBeat": "Chaque beat doit avoir humeur + atmosphère + actions/expressions + dialogues optionnels.",
  "storyBeats.story": "Histoire : {{title}}",
  "storyBeats.style": "Style : {{style}}",
  "storyBeats.userDir": "Consigne utilisateur : {{idea}}",
  "storyBeats.cast": "Casting :",
  "storyBeats.scenes": "Scènes :",
  "storyBeats.props": "Accessoires : {{props}}",
  "storyBeats.actions": "Actions (mouvement) : {{actions}}",
  "storyBeats.returnJson": "Renvoyez uniquement le tableau JSON des beats.",
  "storyBeats.noCast": "(pas de casting)",
  "storyBeats.noScenes": "(pas de scènes — vous pouvez nommer un lieu dans sceneHint ; n’inventez pas un autre monde)",
  "storyBeats.none": "(aucun)",
  "storyBeats.chapters": "Chapitres (source principale — découpez-les en beats filmables) :",
  "storyBeats.chapterBlock": "Chapitre {{n}} · {{title}}\n{{body}}",
  "storyChapters.system": "Tu écris des CHAPITRES de court-métrage : l’âme narrative, pas le script de clip.\nChaque chapitre est une prose courte (environ {{words}} mots) : conflit, lieu, qui est là, ce qu’ils veulent, ce qui change.\nRenvoie UNIQUEMENT un tableau JSON. Chaque item : {\"title\":\"…\",\"body\":\"…\"}.\nÉcris exactement {{count}} chapitres. Reste fidèle au titre, au style, aux règles et à l’idée. Textes courts, un seul JSON.",
  "storyChapters.userLead": "Écris l’histoire en chapitres ordonnés. Ils serviront ensuite à générer personnages, scènes, accessoires et actions.",
  "storyChapters.story": "Histoire : {{title}}",
  "storyChapters.style": "Bible de style : {{style}}",
  "storyChapters.rules": "Règles strictes : {{rules}}",
  "storyChapters.userDir": "Idée : {{idea}}",
  "storyChapters.returnJson": "Renvoie uniquement le tableau JSON : [{\"title\":\"…\",\"body\":\"…\"}, …]",
  "storyChapters.polishSystem": "Tu peaufines UN chapitre. Garde les faits, noms et issue ; rends-le plus filmable. JSON uniquement {\"title\":\"…\",\"body\":\"…\"}.",
  "storyChapters.polishUser": "Histoire : {{story}}\nTitre actuel : {{title}}\nTexte :\n{{body}}\nIndication : {{idea}}\nRenvoie JSON {\"title\",\"body\"}.",
  "storyCastFromChapters.system": "Tu extraits une bible de production des chapitres : personnages, lieux, accessoires, actions.\nJSON uniquement avec characters, scenes, props, actions. Uniquement les entités présentes. Réutilise les noms existants. PAS un de chaque par chapitre. Un chapitre peut avoir deux personnes, plusieurs lieux, beaucoup d’accessoires et d’actions. Extraire chaque entité distincte. Deux interlocuteurs → deux characters ; ruelle puis sanctuaire → deux scenes. Ne pas inventer pour remplir.",
  "storyCastFromChapters.userLead": "Extrais CHAQUE personnage, scène, accessoire et action distincts — pas un de chaque par chapitre.",
  "storyCastFromChapters.story": "Histoire : {{title}}",
  "storyCastFromChapters.style": "Style : {{style}}",
  "storyCastFromChapters.chapters": "Chapitres :\n{{chapters}}",
  "storyCastFromChapters.existingCast": "Déjà dans cette histoire (réutilise ces noms) : {{names}}",
  "storyCastFromChapters.returnJson": "Renvoie uniquement l’objet JSON.",
  "videoPolish.system": "Vous rédigez UN prompt final image vers vidéo pour un modèle vidéo de court-métrage.\nRenvoyez UNIQUEMENT le texte du prompt — pas de clôtures markdown, titre ni explication.\nRègles :\n- Rédigez le prompt de mise en scène dans la langue de l'interface ; noms et codes de langue des répliques clairement indiqués.\n- Still personne : Verrouillage d'identité. Plaque de lieu : Verrouillage spatial. N'ajoutez pas de visages sauf si les matériaux les nomment.\n- Utilisez TOUS les faits de profil / soul / beat / lieu qui touchent look, mouvement, parole ou atmosphère ; ignorez les champs vides.\n- N'inventez que le nécessaire pour un clip filmable à partir des matériaux et du seed — pas de monde échantillon, Demo ni faits absents.\n- Condenser un long soul.md en beats de jeu et d'identité ; ne pas coller toute la bible.\n- Utilisez la durée indiquée dans les matériaux (secondes réelles). Action continue. Pas de texte, logos, filigranes ni passants hors sujet.\n- Anatomie humaine correcte sauf exigence du script (deux mains, deux bras, deux jambes).\n- Si plusieurs personnages, chacun reste cohérent ; foyer principal d'abord.\n- Si RÈGLES FERMES figurent, gardez-les et placez-les à la fin (priorité maximale).\n- Verrouillage des répliques est obligatoire : ne pas le supprimer, réécrire ni traduire. Développer les codes en noms. Chaque clip suit la langue principale du personnage ; pas de changement entre clips ; pas de traduction des répliques.\n- Une révision de mise en scène peut affiner style/action mais NE DOIT PAS violer RÈGLES FERMES.",
  "videoPolish.hardRulesKeep": "RÈGLES FERMES (priorité maximale — conservez chaque ligne ; les étiquettes d’objet comme [Personnage · Nom] doivent rester). Placez le bloc complet des règles fermes à la FIN de la sortie. Ne les affaiblissez pas, ne les supprimez pas et ne les réattribuez pas.",
  "clip.task": "TÂCHE : clip de timeline de court-métrage (image vers vidéo).",
  "clip.hasRef": "Une image de référence peut être jointe — verrouillez identité et lieu quand c’est pertinent.",
  "clip.characters": "Personnages :",
  "clip.scene": "Scène :",
  "clip.prop": "Accessoire :",
  "clip.action": "Guide d’action / mouvement :",
  "clip.beat": "Beat / dialogues :",
  "clip.prev": "Continuité du clip précédent :",
  "clip.revision": "RÉVISION DU RÉALISATEUR (obligatoire) :",
  "clip.templateDraft": "Brouillon de modèle (à améliorer) :",
  "intro.task": "TÂCHE : clip de présentation de casting (image vers vidéo).",
  "intro.hasRef": "L’image de référence est envoyée à l’API vidéo — verrouillez l’identité sur cette photo.",
  "intro.noRef": "Pas de chemin d’image dans ce texte ; verrouillez quand même l’apparence et le costume du profil.",
  "intro.dossier": "Dossier personnage :",
  "intro.templateDraft": "Brouillon de modèle (améliorez ; n’ignorez pas le dossier) :",
  "common.durationAspect": "Durée : {{seconds}} s. Format : {{aspect}}.",
  "common.templateDraft": "Brouillon de modèle :",
  "improve.mode": "MODE AMÉLIORER : fusionnez TOUTES les sources en un résultat complet. Gardez l’identité sauf demande explicite.",
  "improve.draftDefault": "Champs actuels du formulaire :",
  "improve.userRequest": "Demande d’amélioration (vide = tout peaufiner) :",
  "improve.emptyDefault": "(peaufiner tous les champs pour la continuité)",
  "improve.createDefault": "Idée / direction :",
  "improve.explicitContext": "Contexte explicite de CETTE requête seulement (continuité ; n’importez aucun autre monde) :",
  "improve.storyTitle": "Titre : {{title}}",
  "improve.styleNote": "Note de style : {{style}}",
  "improve.closingDefault": "Produisez le résultat complet maintenant.",
  "storyMeta.system": "Vous êtes showrunner. Écrivez bible visuelle + règles dures. JSON uniquement.",
  "storyMeta.draftLabel": "Champs actuels de l’histoire :",
  "storyMeta.createLabel": "Idée / titre :",
  "storyMeta.emptyPolish": "(peaufiner bible + hardRules)",
  "storyMeta.closing": "JSON uniquement : {\"styleNote\":\"…\",\"hardRules\":\"…\"}. Les deux clés sont obligatoires.",
  "storyMeta.contextLabel": "Contexte (cast / scènes / accessoires) :",
  "character.system": "Vous êtes designer de personnages. Un seul JSON. spokenLanguages = tableau BCP-47.",
  "character.draftLabel": "Champs profil actuels :",
  "character.soulLabel": "soul.md / bible liée :",
  "character.createLabel": "Idée de personnage :",
  "character.emptyPolish": "(peaufiner et intégrer le soul)",
  "character.closing": "JSON complet. Clés : {{keys}}.",
  "scene.system": "Vous êtes designer de lieux. Bible du lieu + script de cette scène. JSON seul.",
  "scene.draftLabel": "Champs scène actuels :",
  "scene.charsLabel": "Personnages de l’histoire :",
  "scene.propsLabel": "Accessoires de l’histoire :",
  "scene.priorLabel": "Scènes déjà là (continuité) :",
  "scene.createLabel": "Idée de scène :",
  "scene.emptyPolish": "(peaufiner lieu + script)",
  "scene.closing": "JSON complet. Clés : {{keys}}.",
  "prop.system": "Vous êtes designer d’accessoires. Un seul JSON. Aspect, matière, état concrets.",
  "prop.draftLabel": "Champs accessoire actuels :",
  "prop.createLabel": "Idée d’accessoire :",
  "prop.emptyPolish": "(peaufiner l’aspect)",
  "prop.closing": "JSON complet. Clés : {{keys}}.",
  "prop.fallbackName": "Accessoire",
  "action.system": "Vous êtes directeur de mouvement. JSON valide seulement. Corps, tempo, poids, trajectoires.",
  "action.storyContext": "Contexte d’histoire (optionnel) : {{title}}",
  "action.styleNote": "Note de style : {{style}}",
  "action.existingDraft": "Brouillon existant à peaufiner :",
  "action.userIdea": "Idée utilisateur : {{idea}}",
  "action.closing": "JSON seulement. Clés : {{keys}}.",
  "profile.mustEveryKey": "Vous DEVEZ produire CHAQUE clé : {{keys}}.",
  "profile.valuesAreStrings": "Chaque valeur DOIT être une chaîne JSON. Vide seulement si inconnu.",
  "profile.visualTagsRule": "visualTags : une chaîne séparée par des virgules. JAMAIS un tableau JSON.",
  "profile.fillConcrete": "Remplissez avec des détails concrets.",
  "common.rules": "Règles :",
  "common.none": "(aucun)",
  "intro.soul": "soul.md (source d’interprétation / identité) :\n{{soul}}",
  "intro.matchBible": "(suivre la bible du personnage)",
  "invent.sources": "Sources de vérité, dans l’ordre : (1) idée / demande, (2) formulaire, (3) extras seulement s’ils sont dans CE prompt, (4) image jointe.",
  "invent.create": "Mode créer : inventez librement depuis l’idée/image ; ne laissez aucune clé obligatoire vide.",
  "invent.improve": "Mode améliorer : peaufinez le brouillon ; ne changez l’identité que sur demande.",
  "invent.noImport": "N’importez ni identité, intrigue, météo, métier, lieu, époque ou style hors de ce prompt.",
  "invent.storyBlock": "Un bloc histoire/style ne sert qu’à la continuité ; n’écrasez pas l’idée explicite.",
  "character.keysLead": "UN SEUL JSON avec les clés : {{keys}}",
  "character.ruleSpoken": "spokenLanguages : tableau BCP-47 des langues PARLÉES. [] si non verbal.",
  "character.ruleIdentity": "Identité cohérente pour planches et vidéo.",
  "scene.keysLead": "UN SEUL JSON avec les clés : {{keys}}",
  "scene.suggestLead": "Proposez un LIEU prêt comme scène n° {{n}} pour « {{title}} ».",
  "scene.suggestPlotFocus": "Foyer narratif : {{label}}",
  "scene.suggestStyle": "Style : {{style}}",
  "scene.suggestExisting": "Lieux déjà là : {{titles}}",
  "scene.suggestChars": "Personnages (contexte) :",
  "scene.suggestProps": "Accessoires (contexte) :",
  "scene.suggestSegment": "Détail du segment :",
  "scene.suggestBeats": "Scènes / beats :",
  "scene.suggestClosing": "Renvoyez le JSON complet. Concevez un lieu distinct et réutilisable.",
  "scene.fallbackName": "Lieu",
  "scene.ideaFromImage": "Inventez le profil de lieu complet à partir de la photo jointe.",
  "scene.polishIdea": "Peaufiner",
  "prop.keysLead": "UN SEUL JSON avec les clés : {{keys}}",
  "action.fieldsLead": "Champs : {{keys}}.",
  "soul.system": "Vous rédigez des soul.md de production. Markdown complet seulement. Respectez spokenLanguages. Langue de l’interface.",
  "soul.improveMode": "MODE AMÉLIORER : fusionnez profil + soul existant en un soul.md complet.",
  "soul.createMode": "Rédigez un soul.md complet à partir de ce profil (pas une autre personne) :",
  "soul.profileFields": "Champs du profil :",
  "soul.existing": "soul.md existant (fusionnez ; ne jetez pas le détail utile) :",
  "soul.userRequest": "Demande : {{request}}",
  "soul.extraContext": "Contexte supplémentaire (utile oui ; le profil gagne) :",
  "soul.returnOnly": "Renvoyez uniquement le markdown du soul.md.",
  "wardrobe.system": "Vous êtes consultant costumes. UN seul JSON. artStyle parmi : {{styleIds}}. Matières et silhouette concrètes. Jamais d’érotisation mineure.",
  "wardrobe.improveMode": "MODE AMÉLIORER / SUGGÉRER : utilisez TOUS les champs et le contexte.",
  "wardrobe.characterForm": "Personnage (formulaire complet) :",
  "wardrobe.soulExcerpt": "Extrait soul.md :\n{{soul}}",
  "wardrobe.userRequest": "Demande : {{request}}",
  "wardrobe.storyContext": "Contexte de production (s’il est là ; n’inventez pas un autre monde) :",
  "wardrobe.style": "style : {{style}}",
  "wardrobe.segment": "Segment choisi : {{label}}",
  "wardrobe.sceneContext": "Scène / beat :",
  "wardrobe.noScenes": "(pas encore de scènes)",
  "wardrobe.proposeNew": "Proposez un look NOUVEAU qui colle (pas un doublon).",
  "fill.system": "Vous complétez les champs vides. JSON avec EXACTEMENT ces clés : {{keys}}. Chaque valeur est une chaîne non vide. Jamais un tableau.",
  "fill.userPartial": "Profil partiel (ne contredisez pas) :",
  "fill.userOnly": "Remplissez SEULEMENT ces clés : {{keys}}.",
  "fill.userReturn": "JSON avec ces clés seulement ; valeurs non vides.",
  "imageGen.multiRef": "{{n}} stills de plus : le premier est la base ; gardez l’identité partout.",
  "residual.sceneLink": "Scène {{n}} : {{short}}",
  "residual.beatSegment": "Temps fort {{n}} · {{who}}{{tail}}",
  "residual.unknown": "Inconnu",
  "residual.story": "Histoire",
  "beat.mood": "【HUMEUR】 {{text}}",
  "beat.atmo": "【ATMOSPHÈRE】 {{text}}",
  "beat.camera": "【CAMÉRA】 {{text}}",
  "beat.sfx": "【SFX】 {{text}}",
  "beat.action": "【MOUVEMENT】 {{text}}",
  "beat.actionWho": "【MOUVEMENT｜{{who}}】 {{text}}",
  "beat.expr": "【EXPRESSION】 {{text}}",
  "beat.exprWho": "【EXPRESSION｜{{who}}】 {{text}}",
  "beat.dialogue": "【RÉPLIQUE｜{{who}}】 {{body}}",
  "beat.dialogueTone": "【RÉPLIQUE｜{{who}}｜{{tone}}】 {{body}}",
  "beat.whoUnknown": "inconnu",
  "beat.template": "【HUMEUR】tendu, hésitant\n【ATMOSPHÈRE】lumière chaude dans l’entrebâillement ; pluie au sol\n【CAMÉRA】plan moyen, poussée vers les mains\n【SFX】pluie, frottement de tissu\n【MOUVEMENT｜Nom】retire le casque ; fixe la lumière de la porte ; la main entre dans la poche du manteau\n【EXPRESSION｜Nom】sourcils froncés, le souffle se coupe\n【RÉPLIQUE｜Nom｜bas, rauque】Encore la pluie…\n【RÉPLIQUE｜Nom｜à part】（pause）Tu es… encore là ?",
  "vision.preamble": "Un still est joint. Remplissez TOUS les champs de ce {{what}} surtout DEPUIS L’IMAGE.",
  "vision.character": "identité (nom, apparence, costume, âge, genre, tags)",
  "vision.scene": "lieu (titre, description, lumière, humeur, décor, tags)",
  "vision.prop": "accessoire (nom, description, matière, taille, état, tags)",
  "vision.action": "action (nom, description, tempo, intention, caméra, tags)",
  "vision.costume": "costume (nom, description complète)",
  "still.header": "UNE SEULE IMAGE CLÉ pour la continuité vidéo (pas un plateau multi-vignettes). Un photogramme héros qui correspond au plan prévu. Pas de texte, logos, filigranes ni UI.",
  "still.revision": "AMÉLIORATION UTILISATEUR POUR CE STILL (obligatoire) : {{notes}}",
  "still.regenTask": "TÂCHE : révisez le prompt directeur image vers vidéo et gardez-le utilisable comme brief d’image fixe.",
  "still.userImprove": "DEMANDE D’AMÉLIORATION :\n{{notes}}",
  "still.currentPrompt": "Prompt professionnel actuel :",
  "still.hardRules": "RÈGLES FERMES (à la fin ; ne les affaiblissez pas) :",
  "mediaGen.writeOne": "Rédigez UN prompt d’image final pour un still de drama court.",
  "mediaGen.returnOnly": "SEULEMENT le texte du prompt — pas de markdown.",
  "mediaGen.singleComposite": "Décrivez UNE seule image composite.",
  "mediaGen.lockRefs": "Les images jointes sont la vérité visuelle (ordre Ref#). N’inventez pas une autre personne, boutique ou objet.",
  "mediaGen.videoSystem": "Vous rédigez des prompts de réalisateur image vers vidéo pour un court. Un seul corps. Durée réelle des matériaux. Faits des matériaux seulement. Si un bloc de modèle de caméra est présent, obéissez ; ne revenez pas au travelling avant ou à la caméra à l’épaule génériques. Placez les règles fermes à la fin si fournies.",
  "mediaGen.videoMerge": "Fusionnez les matériaux en UN prompt vidéo.",
  "mediaGen.videoInclude": "Inclure : verrou d’identité, caméra, jeu/dialogue, rythme, lumière.",
  "mediaGen.videoFacts": "Faits des matériaux et du seed seulement. Pas de Demo.",
  "mediaGen.videoNoSwap": "Avec refs, ne changez ni acteur, lieu ni accessoire.",
  "mediaGen.videoHardRules": "RÈGLES FERMES à la fin s’il y en a.",
  "mediaGen.imageSystem": "Vous êtes directeur de prompts still / planche multi-vignettes pour un court. Renvoyez seulement le corps — pas de clôtures, titre ni explication. Faits des matériaux seulement ; n’importez pas un monde d’échantillon. Si un modèle de caméra est présent, obéissez ; ne revenez pas au travelling générique. Placez les règles fermes à la fin si fournies.",
  "mediaGen.imageMergeStills": "Fusionnez matériaux et stills en UN prompt image.",
  "mediaGen.imageMergeText": "Fusionnez les textes en UN prompt image.",
  "mediaGen.imagePriority": "Priorité : visages/costumes/lieux/accessoires des images.",
  "mediaGen.imageNoSwap": "Ne substituez pas une autre célébrité ou un autre set s’il y a des stills de cast.",
  "mediaGen.imageFacts": "Faits des matériaux et du seed seulement.",
  "mediaGen.imageLayout": "Multipan visé : conservez le nombre exact de cases.",
  "mediaGen.imagePackage": "S’il y a un LAYOUT, le prompt DOIT l’appliquer exactement.",
  "mediaGen.imageHardRules": "RÈGLES FERMES à la fin s’il y en a.",
  "mediaGen.directorFallback": "Image vers vidéo : animez ce photogramme. Verrouillez identité, costume, décor et cadrage.",
  "comic.taskHint": "Histoire « {{title}} », page BD {{n}} : une page terminée, exactement {{count}} case(s). Identité, costume et lieu continus sur toute la page. Pas de filigrane ni de cadre d’interface.",
  "comic.panelCount": "Nombre de cases fixe : exactement {{n}} case(s).",
  "comic.lockSplash": "Verrou de mise en page : une case pleine page. Interdit : cadres en plus, découpe, collage.",
  "comic.lockYonkoma": "Verrou : 4-koma vertical, 4 rangées × 1 colonne, haut vers bas. Interdit : grille 2×2 ou bandeau.",
  "comic.lockGrid2x2": "Verrou : 2 rangées × 2 colonnes. Interdit : bandeau, 2×3, splash pleine page.",
  "comic.lockGrid2x3": "Verrou : 2 rangées × 3 colonnes. Haut 1-2-3, bas 4-5-6. Interdit : 2×2 ou 3×3.",
  "comic.lockGrid3x3": "Verrou : 3 rangées × 3 colonnes = neuf cases. Interdit : 2×2, 2×3, ou moins de cases.",
  "comic.lockStrip": "Verrou : une seule rangée horizontale de exactement {{n}} cases. Interdit : grilles multi-rangées.",
  "comic.layoutSplash1": "Une page BD verticale : exactement une case pleine page, sans gouttières ni cadres extra.",
  "comic.layoutStrip2": "Une page paysage : deux cases égales côte à côte, gouttières blanches épaisses.",
  "comic.layoutStrip3": "Une page paysage : trois cases égales sur une rangée, gouttières blanches épaisses.",
  "comic.layoutYonkoma": "Une page verticale : 4-koma empilé (4×1), gouttières blanches épaisses, lecture haut vers bas.",
  "comic.layoutGrid2x2": "Une page carrée : grille 2×2, exactement quatre cases, gouttières blanches, gauche→droite puis haut→bas.",
  "comic.layoutStrip4": "Une large page paysage : quatre cases sur une rangée, gouttières blanches épaisses.",
  "comic.layoutGrid2x3": "Une page paysage : exactement six cases, 2 rangées × 3 colonnes (haut 1-2-3, bas 4-5-6), gouttières blanches, gauche→droite puis haut→bas.",
  "comic.layoutGrid3x3": "Une page carrée : grille 3×3, exactement neuf cases, gouttières blanches, gauche→droite puis haut→bas.",
  "comic.layoutWidePlusTwo": "Une page BD verticale : grande case pleine largeur en haut (~60 %), puis deux petites cases côte à côte, gouttières blanches épaisses.",
  "comic.layoutTwoPlusWide": "Une page verticale : deux petites cases en haut, puis une large case de clôture en bas (~60 %), gouttières blanches épaisses.",
  "comic.layoutTallLeftTwo": "Une page verticale : case haute sur toute la hauteur à gauche, deux cases empilées à droite, gouttières blanches épaisses.",
  "comic.layoutHeroPlusThree": "Une page verticale : grande case en haut, puis trois petites cases en une rangée, gouttières blanches épaisses.",
  "comic.layoutFocusQuad": "Une page verticale : case moyenne en haut à gauche, deux petites empilées à droite, grande case en bas, gouttières blanches épaisses.",
  "comic.layoutStaggerFour": "Une page verticale : 2+2 décalé — haut large puis étroit, bas étroit puis large, gouttières blanches épaisses.",
  "comic.layoutDiagPairPlus": "Une page verticale : la moitié haute est coupée en diagonale en deux coins ; le bas est un rectangle large, gouttières blanches épaisses.",
  "comic.layoutHeroPlusFour": "Une page verticale : grande case en haut, puis quatre petites en 2×2 en bas, gouttières blanches épaisses.",
  "comic.lockWidePlusTwo": "Verrouillage : case haute large. En bas exactement deux petites. Interdit : trois bandes égales ou grille 2×2.",
  "comic.lockTwoPlusWide": "Verrouillage : deux petites en haut, une large en bas. Interdit : trois bandes égales ou 2×2.",
  "comic.lockTallLeftTwo": "Verrouillage : case gauche sur toute la hauteur. Droite : deux empilées. Interdit : 2×2 égal ou bande horizontale.",
  "comic.lockHeroPlusThree": "Verrouillage : grande case en haut. En bas exactement trois petites. Interdit : 2×2 ou quatre cases égales.",
  "comic.lockFocusQuad": "Verrouillage : moyenne en haut à gauche, deux petites empilées, grande en bas. Interdit : 2×2 égal.",
  "comic.lockStaggerFour": "Verrouillage : tailles décalées — haut large+étroit, bas étroit+large. Interdit : quatre carrés égaux.",
  "comic.lockDiagPairPlus": "Verrouillage : haut en deux coins diagonaux ; bas un rectangle large. Interdit : trois bandes ou 2×2.",
  "comic.lockHeroPlusFour": "Verrouillage : grande case en haut ; 2×2 de quatre petites en bas. Exactement cinq. Interdit : 3×3 ou 2×2 pleine page.",
  "comic.readingYonkoma": "Lecture : uniquement de haut en bas (4-koma vertical).",
  "comic.readingWidePlusTwo": "Lecture : grande case du haut, puis les deux petites de gauche à droite.",
  "comic.readingTwoPlusWide": "Lecture : gauche puis droite en haut, puis la large du bas.",
  "comic.readingTallLeftTwo": "Lecture : case haute de gauche, puis haut droit, puis bas droit.",
  "comic.readingHeroPlusThree": "Lecture : grande case du haut, puis les trois petites de gauche à droite.",
  "comic.readingFocusQuad": "Lecture : moyenne en haut à gauche, deux petites de haut en bas, puis grande du bas.",
  "comic.readingStaggerFour": "Lecture : haut gauche, haut droit, bas gauche, bas droit.",
  "comic.readingDiagPairPlus": "Lecture : coin haut-gauche, coin bas-droit, puis large du bas.",
  "comic.readingHeroPlusFour": "Lecture : grande case du haut, puis les quatre petites gauche→droite et haut→bas.",
  "comic.readingOrder": "Lecture : gauche → droite, puis haut → bas (4-koma vertical : haut → bas seulement).",
  "comic.panelNumbers": "Petits numéros 1–{{n}} en haut à gauche de chaque case.",
  "comic.panelLine": "Case {{i}}/{{n}} ({{label}}) : {{cap}}",
  "comic.panelEmpty": "Case {{i}}/{{n}} ({{label}}) : un instant d’histoire distinct et enchaîné.",
  "comic.identity": "Même identité, costume et lieu dans toutes les cases de cette page.",
  "comic.finished": "C’est une page BD terminée, pas un collage de photos ni une maquette d’interface.",
  "comic.layoutLead": "Mise en page : {{layout}}",
  "comic.prevPage": "Page précédente. Gardez identité, costume et lieu, sans copier la grille précédente.",
  "comic.ownPage": "Rendu existant de cette page. Sert de base d’identité / de mise en page pour une révision.",
  "comic.galleryRef": "Still d’identité (cast ou décor). Faire correspondre visages, costumes et lieu.",
  "comic.profileLine": "Page BD {{n}} de l’histoire « {{title}} ».",
  "comic.styleBible": "Note de style : {{note}}",
  "comic.artMedium": "Style graphique : {{art}}",
  "comic.fallbackClose": "Page BD imprimée terminée. Gouttières blanches épaisses. Petits numéros. Pas de filigrane, d’UI ni de collage album.",
  "comic.hardRules": "Règles fermes",
  "comic.introTask": "Image vers vidéo : animer la planche terminée de « {{title}} », planche {{n}}, exactement {{count}} case(s). Verrouiller identité, costume et mise en page sur l’image jointe.",
  "comic.introLock": "Verrou : mêmes visages, costumes, lieux, gouttières et numéros que l’image. Ne pas inventer une autre page ni une autre personne.",
  "comic.introLayout": "Conserver cette mise en page : {{layout}}",
  "comic.introCamera": "Caméra : lent travelling avant ou léger panoramique dans l’ordre de lecture. Léger mouvement papier uniquement. Pas de coupe vers une autre mise en page.",
  "comic.introClose": "Pas de filigrane ni de cadre d’interface ; pas de sous-titres en plus des bulles déjà dessinées.",
  "comic.dramaStillLock": "Verrouiller identité, costume et lieu sur la planche jointe, mais jouer un plan de court-métrage live — pas un travelling sur du papier imprimé.",
  "comic.dramaCamera": "Caméra et jeu : rythme de court-métrage, jeu clair, synchro labiale aux répliques des cases. Continuité avec la page précédente si une image est jointe.",
  "comic.formatLockTall": "Format de page : la planche entière doit être verticale 9:16. Pas de composition paysage.",
  "comic.formatLockSquare": "Format de page : la planche entière doit être carrée 1:1.",
  "comic.formatLockWide": "Format de page : la planche entière doit être horizontale 16:9.",
  "art.photoCinematic": "Support obligatoire : photogramme cinématographique photoréaliste. Rendu caméra réelle, matières naturelles, étalonnage cinéma. Doit ressembler à une photo ou une image de film. Interdit : anime, cellulo, illustration 2D, contours cartoon, argile, CGI plastique.",
  "art.photoPortrait": "Support obligatoire : portrait studio photoréaliste. Éclairage boîte à lumière, clarté de headshot commercial. Doit être une photographie. Interdit : anime, encre de BD, jouet 3D, aplat cellulo.",
  "art.photoDocumentary": "Support obligatoire : photo documentaire photoréaliste. Lumière naturelle, textures honnêtes. Doit sembler prise sur un vrai appareil. Interdit : anime, CGI stylisé, illustration.",
  "art.cgiFilm": "Support obligatoire : personnage 3D CGI de qualité cinéma. Matériaux PBR, reflets ray-tracés. Doit paraître rendu 3D, ni photo réelle ni anime 2D. Interdit : photo live, lineart anime, encre de BD plate.",
  "art.cgiStylized": "Support obligatoire : 3D stylisé premium (CGI de long métrage). Formes lisibles, PBR doux. Doit être du CGI 3D. Interdit : live photoréaliste, cellulo 2D, BD esquissée.",
  "art.cgiClay": "Support obligatoire : personnage 3D argile / sculpture. Argile mate, formes sculptées. Doit se lire comme une sculpture d’argile. Interdit : photo de peau, cellulo anime, BD à l’encre.",
  "art.animeModern": "Support obligatoire : anime TV japonais moderne 2D. Trait numérique propre, cellulo doux, yeux et mèches anime. Toute l’image doit être de l’anime 2D. Interdit : photo, pores réels, rendu 3D, encre western seule, peinture à l’huile.",
  "art.animeShonen": "Support obligatoire : visuel clé shonen 2D. Trait fort, cellulo contrasté, yeux anime nets. Doit être du shonen 2D. Interdit : photo, CGI 3D, aquarelle seule.",
  "art.animeShoujo": "Support obligatoire : anime shoujo 2D. Trait délicat, dégradés doux, yeux lumineux. Doit être du shoujo. Interdit : photo, 3D dur, encre de BD rude.",
  "art.animeGekiga": "Support obligatoire : anime gekiga / réaliste 2D. Trait mature, palette retenue, clairement 2D. Interdit : photo live, chibi, CGI 3D pur.",
  "art.animeChibi": "Support obligatoire : chibi / super-deformed 2D. Grande tête, petit corps, traits simplifiés. Doit être du chibi. Interdit : proportions photoréalistes, 3D réaliste, live détaillé.",
  "art.donghua": "Support obligatoire : key art de donghua chinois. Costume raffiné, silhouette élégante, 2D ou 2,5D. Doit se lire comme du donghua. Interdit : live hollywoodien, BD de journal western seule.",
  "art.manhwa": "Support obligatoire : manhwa / webtoon coréen en couleurs. Peinture numérique douce, contours nets, cheveux lustrés. Doit être du manhwa 2D. Interdit : photo, argile 3D, encre super-héros seule.",
  "art.comicWestern": "Support obligatoire : bande dessinée occidentale. Encre assurée, aplats ou cellulo limité, formes graphiques. Doit être une illustration de BD. Interdit : photo, style yeux anime seul, rendu argile.",
  "art.conceptGame": "Support obligatoire : concept art de personnage AAA. Feuille peinte, silhouette forte. Doit ressembler à du concept, pas à une capture ni à une photo. Interdit : portrait photo pur, chibi seul.",
  "art.illustrationSoft": "Support obligatoire : illustration numérique douce. Pinceau délicat, fini proche de l’album. Doit être une illustration peinte. Interdit : photo caméra, cellulo dur, argile 3D.",
  "mediaGen.polishTask": "Tâche : {{hint}}",
  "mediaGen.polishKind": "Type : {{kind}}",
  "mediaGen.polishMaterials": "—— Matériaux ——",
  "mediaGen.polishEndMaterials": "—— Fin des matériaux ——",
  "mediaGen.polishRef": "Réf. n°{{n}} — {{title}}",
  "mediaGen.videoTaskHint": "Rédiger une consigne réalisateur image-vers-vidéo à partir de l’image clé ({{kind}}). Caméra, jeu, rythme ; verrouiller l’image clé.",
  "mediaGen.directorFallbackCam": "Caméra et jeu clairs ; pas de sous-titres ni filigrane.",
  "charIntro.task": "Image vers vidéo : animez la même personne pour un court auto-casting.",
  "charIntro.identityLock": "VERROU D’IDENTITÉ : même visage, cheveux, corps, âge, costume et couleurs.",
  "charIntro.personality": "Personnalité / vibe : {{personality}}.",
  "charIntro.backstory": "Histoire : {{backstory}}.",
  "charIntro.relationships": "Relations : {{relationships}}.",
  "charIntro.soul": "Extrait soul (source de jeu) : {{soul}}",
  "charIntro.performance": "Tics : {{manner}}.",
  "charIntro.speech": "Parole : la bouche bouge comme une courte présentation ; voix : {{voice}}.",
  "charIntro.beat": "Idle naturel → sourire ou hochement → geste bref → hold.",
  "charIntro.lighting": "Lumière cohérente avec le still ; pas de texte, logo ni figurants.",
  "sceneIntro.task": "Image vers vidéo : animez le même lieu en plan d’établissement.",
  "sceneIntro.spaceLock": "VERROU D’ESPACE : même architecture, matières, enseignes, plan et couleurs.",
  "sceneIntro.name": "Nom du lieu : {{name}}.",
  "sceneIntro.place": "Description : {{place}}.",
  "sceneIntro.spaceType": "Type d’espace : {{type}}.",
  "sceneIntro.time": "Moment : {{time}}.",
  "sceneIntro.weather": "Météo : {{weather}}.",
  "sceneIntro.moodLight": "Humeur : {{mood}}. Lumière : {{lighting}}.",
  "sceneIntro.palette": "Palette : {{palette}}.",
  "sceneIntro.setDressing": "Décor : {{set}}.",
  "sceneIntro.tags": "Tags visuels : {{tags}}.",
  "sceneIntro.art": "Style : {{art}}.",
  "sceneIntro.ambient": "Ambiance (sans texte UI) : {{sound}}.",
  "sceneIntro.scriptCue": "Indice de beat (atmosphère seulement) : {{cue}}.",
  "sceneIntro.camera": "Caméra : {{camera}} ; mouvement continu. N’ajoutez pas de visages, logos ni texte sauf si les matériaux les montrent déjà.",
  "sceneIntro.beat": "Établir → vie environnementale subtile → hold.",
  "propIntro.task": "Image vers vidéo : animez le même accessoire en intro produit.",
  "propIntro.objectLock": "VERROU D’OBJET : même silhouette, matières, couleurs, gravures et usure.",
  "propIntro.name": "Nom : {{name}}.",
  "propIntro.look": "Apparence : {{look}}.",
  "propIntro.material": "Matière : {{material}}.",
  "propIntro.size": "Taille : {{size}}.",
  "propIntro.condition": "État : {{condition}}.",
  "propIntro.tags": "Tags : {{tags}}.",
  "propIntro.art": "Style : {{art}}.",
  "propIntro.camera": "Orbite douce ou travelling lent sur table propre ; lumière cohérente.",
  "propIntro.beat": "Hold → éclat / micro-rotation → hold.",
  "propIntro.noHands": "Pas de mains ni visages nouveaux s’ils n’y sont pas ; pas de texte ni extras.",
  "costumeIntro.task": "Image vers vidéo : animez le même look en intro costume.",
  "costumeIntro.wardrobeLock": "VERROU DE COSTUME : même silhouette, tissus, couleurs, couches et accessoires.",
  "costumeIntro.identityOrProduct": "Personne : verrouillez visage/corps ; mannequin / à plat : cadrage produit.",
  "costumeIntro.name": "Nom du look : {{name}}.",
  "costumeIntro.desc": "Costume : {{look}}.",
  "costumeIntro.art": "Style : {{art}}.",
  "costumeIntro.camera": "Léger travelling ou orbite ; lumière mode cohérente.",
  "costumeIntro.beat": "Hold → tombé de tissu / éclat de quincaillerie → hold.",
  "costumeIntro.forbid": "Pas de nouveaux visages, texte, logos ni pose érotique.",
  "costumeIntro.fallbackName": "Tenue",
  "actionIntro.lead": "Démo de mouvement « {{name}} ».",
  "actionIntro.intention": "Intention : {{intention}}",
  "actionIntro.body": "Corps/tempo : {{body}}",
  "actionIntro.camera": "Caméra : {{camera}}",
  "actionIntro.closing": "Mouvement continu, sans texte ; suivez le still.",
  "sceneIntroPolish.task": "TÂCHE : intro de lieu (image-vers-vidéo).",
  "sceneIntroPolish.hasRef": "Still de lieu joint — verrouillez l’identité SPATIALE.",
  "sceneIntroPolish.noRef": "Pas de still ; verrouillez à la bible du lieu.",
  "sceneIntroPolish.dossier": "Dossier du lieu :",
  "sceneIntroPolish.scriptCue": "indice de script (atmosphère seulement) :\n{{script}}",
  "sceneIntroPolish.emptySet": "Plateau vide ; pas de nouveaux visages. Pas de texte ni logos.",
  "propIntroPolish.task": "TÂCHE : intro héros d’accessoire (image-vers-vidéo).",
  "propIntroPolish.hasRef": "Still d’accessoire joint — verrouillez l’OBJET.",
  "propIntroPolish.noRef": "Pas de still ; verrouillez au dossier.",
  "propIntroPolish.dossier": "Dossier accessoire :",
  "propIntroPolish.noHands": "Pas de nouvelles mains ni visages. Pas de texte ni logos.",
  "costumeIntroPolish.task": "TÂCHE : intro costume / look (image-vers-vidéo).",
  "costumeIntroPolish.hasRef": "Still joint — personne : identité+costume ; mannequin : silhouette et matières.",
  "costumeIntroPolish.noRef": "Pas de still ; verrouillez à la description.",
  "costumeIntroPolish.dossier": "Dossier costume :",
  "costumeIntroPolish.fabric": "Tombé subtil ; pas de nouveaux visages ni texte.",
  "actionIntroPolish.task": "TÂCHE : intro de guide de mouvement (image-vers-vidéo).",
  "actionIntroPolish.hasRef": "Still joint — verrouillez l’identité de jeu à ce cadre.",
  "actionIntroPolish.templateKeepRules": "Brouillon modèle (améliorez ; RÈGLES FERMES à la fin) :",
  "cover.posterLead": "AFFICHE / KEY ART professionnel 16:9. Pas de mockup UI. Pas de texte, logo ni filigrane.",
  "cover.titleMood": "Titre (humeur seulement, ne l’écrivez pas) : {{title}}.",
  "cover.styleBible": "Bible de style : {{style}}",
  "cover.extraDir": "Direction extra : {{idea}}",
  "cover.establishing": "Plan d’établissement évocateur pour une couverture de bibliothèque.",
  "cover.medium": "Respectez le medium ; silhouette forte.",
  "cover.editPrefix": "Édition d’image : nouvelle composition d’affiche. Gardez identité et humeur. ",
  "cover.label": "Couverture d’histoire",
  "costumeFill.system": "Vous êtes costumier. JSON compact seulement. Si image, décrivez CET habit fidèlement.",
  "costumeFill.idea": "Idée : {{idea}}",
  "costumeFill.polish": "Peaufinez le brouillon de costume.",
  "costumeFill.required": "Clés : name, description, artStyle, hardRules. Manquer = invalide.",
  "costumeFill.fallbackName": "Tenue",
  "segment.entireStory": "Toute l’histoire (toutes les scènes)",
  "segment.noStory": "Aucune histoire (fiche personnage seulement)",
  "vision.inventFromImage": "Décrivez et inventez un profil {{kind}} complet à partir de la photo jointe.",
  "vision.polishAll": "Peaufinez et fusionnez tous les champs",
  "story.untitled": "Drama court sans titre",
  "action.castIdentityNote": "Stills d’identité ({{count}}) : visage/corps identiques aux références de cast dans chaque case.",
  "tpl.system.polishOnly": "RECETTE peaufiner seulement : gardez identité et monde. Peaufinez le texte. N’inventez ni ère, météo, métier, lieu ni monde échantillon. N’inventez pas la langue parlée. N’écrivez pas de RÈGLES FERMES par défaut dans le profil.",
  "tpl.system.fillBlanks": "RECETTE vides seulement : remplissez UNIQUEMENT les clés vides. Ne réécrivez pas les champs remplis. N’inventez pas un autre monde.",
  "tpl.system.invent": "RECETTE inventer : l’utilisateur autorise la création libre. Complétez chaque clé filmable. N’importez aucun Demo ni monde non impliqué.",
  "tpl.system.fromStory": "RECETTE depuis l’histoire : utilisez seulement titre/style/cast/scènes de CETTE requête. En conflit, l’idée utilisateur gagne.",
  "tpl.system.followAsset": "RECETTE suivre l’actif : suivez le style déjà fourni. N’imposez pas le cinéma, le plateau vide ni 6–10 s sauf si les matériaux le disent. Utilisez la durée réelle du clip.",
  "tpl.system.cinematicLock": "RECETTE ciné+anti-hallu : look cinématographique ; plateau vide ; pas de filigrane, logo ni visage en trop ; deux mains/bras/jambes sauf non-humain.",
  "tpl.system.identityLock": "RECETTE verrou d’identité : verrouillez visage/corps/costume/lieu/accessoire aux stills. Ne substituez pas une autre personne, un autre lieu ou objet.",
  "tpl.system.restyle": "RECETTE restyle : même personne. Costume, décor et époque peuvent changer si demandé. Pas une autre personne.",
  "pipeline.character.system": "Vous peaufinez les bibles de personnages. 3–5 lignes : look, voix, motif, geste. Uniquement les faits de cette requête.",
  "pipeline.scene.system": "Vous déployez les scènes en feuilles de beats. Durée réelle des matériaux ; n’assumez pas 6–10 s. Scènes fournies seulement.",
  "pipeline.props.system": "Vous peaufinez la continuité des accessoires. Couleur, taille, apparition. N’inventez pas d’accessoires absents.",
  "pipeline.script.system": "Vous êtes scénariste. Un bloc compact par scène pour la vidéo IA. Durée réelle ; pas de plafond 10 s. Format :\n### SCENE <number> | id=<id>\n<script body>",
  "pipeline.script.noScenes": "(pas de scènes — n’inventez pas de lieux)",
  "keyArt.task": "Image clé {{n}} de l’histoire « {{title}} ». Une image publicitaire achevée. Pas de cases de bande dessinée, pas de numéros, pas d’interface.",
  "keyArt.lockCover": "AFFICHE DE COUVERTURE : visuel paysage pour la fiche. Laisse une bande sûre pour le titre. Visages lisibles. N’invente ni logo ni faux générique.",
  "keyArt.lockPoster": "AFFICHE VERTICALE : un seul one-sheet. Le héros se lit sur téléphone. Aucune autre affiche dans le cadre.",
  "keyArt.lockStill": "PHOTogramme : un plan cinéma, comme extrait du drama. Jeu naturel, espace réel. Pas un collage.",
  "keyArt.lockPromo": "VISUEL PROMO : personnage et monde dans le même cadre. Silhouette forte, une seule humeur. Pas une planche-contact.",
  "keyArt.lockSocial": "STORY SOCIALE : cadre vertical 9:16. Sujet large. Marges pour le texte à l’écran.",
  "keyArt.lockHeadshot": "GROS PLAN DU HÉROS : un visage de face qui remplit le cadre, identique aux références. Épaules permises. Personne d’autre.",
  "keyArt.lockBust": "PROMO BUSTE : buste, col du costume visible, regard caméra.",
  "keyArt.lockGroup": "DISTRIBUTION : tous les personnages nommés dans un cadre, même monde, même lumière. Ne retire ni ne change un visage.",
  "keyArt.formatLockTall": "VERROU FORMAT : toute l’image est un cadre haut 9:16. Pas de composition paysage.",
  "keyArt.formatLockSquare": "VERROU FORMAT : toute l’image est un cadre carré 1:1.",
  "keyArt.formatLockWide": "VERROU FORMAT : toute l’image est un cadre large 16:9.",
  "keyArt.methodFreshLock": "MÉTHODE : générer une nouvelle image. Les références ne servent qu’à l’identité. Ne copie pas le cadrage d’une ancienne prise.",
  "keyArt.methodEditLock": "MÉTHODE : modifier l’image jointe. Garde la composition sauf si le brief demande le contraire.",
  "keyArt.methodIdentityLock": "MÉTHODE : verrouille les visages sur les références du personnage. Pose, recadrage et costume peuvent changer.",
  "keyArt.methodContinueLock": "MÉTHODE : enchaîne depuis l’image précédente. Mêmes personnes, même lieu, plan suivant du même tournage.",
  "keyArt.briefLine": "Brief de mise en scène : {{brief}}",
  "keyArt.beatLine": "Beat lié : {{beat}}",
  "keyArt.close": "Image {{aspect}} achevée. Pas de filigrane, pas de cadre d’interface, pas de sous-titres en plus.",
  "charIntro.manner": "Tics : {{manner}}.",
  "charIntro.cameraDefault": "Caméra de jeu : léger travelling avant ou caméra à l’épaule discrète ; le personnage regarde vers la caméra ou légèrement hors champ.",
  "mediaGen.honorCameraTemplate": "Si les matériaux contiennent un bloc de modèle de caméra, suivez exactement ce cadrage et ce mouvement. Ne le remplacez pas par un travelling avant ou une caméra à l’épaule génériques.",
  "mediaGen.refRoles": "Chaque still a un métier : IDENTITY (visage/costume), SPATIAL (blocking et caméra du modèle blanc — ne pas copier le gris argile comme look final), MOTION (rythme/geste) ou STYLE (palette/lumière). Un still ne doit pas tout commander.",
  "sceneIntro.cameraNotes": "Notes de caméra : {{camera}}.",
  "sceneIntro.cameraDefault": "Caméra : mouvement continu et doux. N’ajoutez pas de visages de distribution, de logos ni d’incrustations de texte sauf si les matériaux les montrent déjà.",
  "quality.family.photo": "Qualité : mise au point piquée sur les yeux ou les traits principaux du visage/de la tête, micro-détail élevé adapté au support photoréaliste, éclairage studio trois points professionnel sauf si le style en dit autrement, rendu d’optique à focale fixe (50–85 mm), pas de flou de mouvement, pas de filtre beauté trop lissant, pas de filigrane ni de texte.",
  "quality.family.cgi": "Qualité : présentation 3D propre du personnage, matières lisibles (PBR), silhouette de topologie cohérente, formes primaires nettes, HDRI studio ou lumière CG trois points, pas de grain sauf style argile, pas de filigrane ni de texte, ce n’est pas une photographie réelle.",
  "quality.family.anime": "Qualité : planche de design personnage 2D propre, poids de trait constant, modèle de visage stable d’une case à l’autre, couleur cellulo ou ombrage doux maîtrisé ; éviter la photographie photoréaliste, le rendu live et l’ombrage photo 3D SSS ; pas de filigrane ni d’étiquettes texte.",
  "quality.family.illust": "Qualité : clarté de planche d’illustration professionnelle, design de personnage cohérent, silhouette et costume/matières lisibles, fond studio neutre, pas de filigrane, pas de légendes d’interface.",
  "sheet.lock.lead": "Créez un still de référence personnage pour la continuité vidéo IA.",
  "sheet.lock.sexPrefix": "Verrouillage de sexe (priorité maximale — chignon, visage ovale, peau pâle, morphologie mince ou robes ne doivent pas inverser le sexe) : {{lock}}",
  "sheet.lock.identity": "Verrouillage d’identité : exactement un sujet personnage dans chaque case (humain, animal, créature, esprit, robot ou autre entité conçue — mais jamais de changement d’espèce ni de design au milieu de la planche).",
  "sheet.lock.noSecond": "N’inventez pas un second personnage ; gardez le même plan corporel, les mêmes marques, couleurs et design de tête dans toutes les cases.",
  "sheet.lock.head": "La tête/le visage (ou équivalent) doit rester cohérent : mêmes yeux ou capteurs, même silhouette de tête, mêmes couleurs de surface et identifiants clés.",
  "sheet.lock.camera": "Caméra : cadrage de référence stable, verticales droites, pas d’œil de poisson sauf si la mise en page exige un angle spécial.",
  "sheet.lock.background": "Fond : cyclorama studio gris clair ou blanc cassé, sans couture, vide, uniforme ; pas d’encombrement sauf si la mise en page demande un petit détail de costume/accessoire.",
  "sheet.lock.forbidden": "Interdit : filigranes, logos, légendes, texte, cadre d’interface, membres surnuméraires, extrémités déformées (sauf si le plan est volontairement mains/détail seulement).",
  "sheet.lock.subject": "Nom/concept du sujet : {{name}}",
  "sheet.lock.age": "Âge ou présentation de maturité : {{age}}",
  "sheet.lock.gender": "Genre / présentation : {{gender}}",
  "sheet.lock.appearance": "Apparence (doit correspondre exactement) : {{appearance}}",
  "sheet.lock.appearanceFaceOnly": "Apparence — visage / cheveux / proportions du corps seulement (doit correspondre) : {{appearance}}. Retirez de cette description tout vêtement, manteau, parapluie, sac, chaussures, bijoux ou accessoires — ils ne doivent pas apparaître.",
  "sheet.lock.ignoreCostume": "Costume extérieur / accessoires : ignorez-les complètement pour cette planche. Pas de parapluie, sac, manteau ni articles de mode. Plaque de corps ou de couche de base seulement.",
  "sheet.lock.costume": "Costume / design extérieur (doit correspondre exactement) : {{costume}}",
  "sheet.lock.tags": "Tags visuels : {{tags}}",
  "sheet.lock.tagsIdentity": "Tags visuels (identité seulement ; écartez les tags vêtement/accessoire) : {{tags}}",
  "sheet.lock.manner": "Indices subtils de pose/tic seulement (ne changez pas l’identité) : {{manner}}",
  "sheet.scaffold.repeatMedium": "Rappel : le support de l’image finale doit être exactement l’id de style « {{id}} » ({{family}}).",
  "sheet.scaffold.wardrobeTag": "Marqueur de couche vestimentaire : {{tag}}.",
  "sheet.scaffold.layoutLead": "Mise en page : {{layout}}",
  "sheet.scaffold.finalCheck": "Vérification finale : si l’image semble du mauvais support, régénérez dans le support correct : {{medium}}",
  "sheet.edit.task": "Tâche d’édition d’image / changement de mise en page (priorité maximale — lisez entièrement) :",
  "sheet.edit.target": "Id du paquet de planche cible : « {{id}} ». Couche vestimentaire : {{tag}}.",
  "sheet.edit.ignoreLayout": "Ignorez complètement la mise en page de l’image source : nombre de cases, gouttières, angles de caméra, recadrage et cadrage de la source ne doivent pas être copiés.",
  "sheet.edit.ignoreWardrobe": "Ignorez le costume/vêtement source s’il entre en conflit avec la couche vestimentaire cible ci-dessous.",
  "sheet.edit.keepIdentity": "Ne gardez de la source que l’identité du personnage : design visage/tête, cheveux, proportions du corps, espèce/plan corporel, peau ou marques de surface, présentation d’âge.",
  "sheet.edit.stripOuter": "Retirez tout vêtement/armure extérieur de la source. Pour les plaques de corps : justaucorps couleur chair seulement. Pour la couche de base : sous-vêtements simples seulement. Ne conservez pas la tenue source.",
  "sheet.edit.applyProfileCostume": "Vous pouvez appliquer la description de costume du profil dans le prompt de corps ; ne vous contentez pas de recolorier ou recadrer les cases de costume source.",
  "sheet.edit.changeMedium": "Changez complètement le support de rendu si besoin pour correspondre au style graphique obligatoire.",
  "sheet.edit.noNewPerson": "N’inventez pas un personnage différent. Ne vous contentez pas de recadrer, zoomer ou recolorier la source.",
  "sheet.edit.newComposition": "Produisez une composition de planche de référence entièrement nouvelle qui correspond exactement au bloc de mise en page (nombre de cases et poses).",
  "sheet.edit.checklist": "Liste finale : (1) l’identité correspond au visage/corps source (2) la mise en page suit le paquet « {{id}} », pas la planche source (3) couche vestimentaire {{tag}} (4) support = {{style}}.",
  "sheet.wardrobe.nude": "Plaque de proportions corporelles pour le design de costume (pas un contenu adulte, pas une photographie de nu) : éclairage studio clinique neutre, cyclorama gris uni, pose professionnelle de dessin d’après modèle. Pas de photographie de mode, pas de stylisme lingerie, pas de chambre ni de décor glamour. Le sujet porte un justaucorps mat sans couture couleur chair / combinaison moulante intégrale (ou combinaison mate unie adaptée à l’espèce) qui révèle la silhouette et les proportions exactes — visage et cheveux visibles ; pas de costume extérieur, logos, accessoires, chaussures ni bijoux. Le justaucorps est uniquement une sous-combinaison de production (comme un maillage corporel CG), jamais un costume extérieur. Conservez visage, cheveux, proportions et marques de surface pour le CG vestimentaire ultérieur. Ignorez toute description de costume extérieur pour cette planche. Explicitement vêtu d’un justaucorps — jamais dénudé.",
  "sheet.wardrobe.halfBareUpper": "Référence partielle du haut du corps pour les mesures de design de costume (personnage adulte uniquement ; étude de figure clinique ; pas érotique ; pas pornographique ; pas suggestif) : éclairage studio clinique neutre, cyclorama gris uni, pose debout médicale / mannequin professionnelle. Pas de photographie de mode, pas de stylisme lingerie, pas de chambre, pas de caméra sexualisée. Haut du corps nu : torse, poitrine, épaules, bras et cou nus ; visage et cheveux entièrement visibles. Bas du corps couvert uniquement d’un bas opaque simple, mat, neutre ou couleur chair (short uni, slip ou drapé simple — couverture de production seulement, pas de lingerie de mode, pas de dentelle, pas de transparence). Pas de haut de costume extérieur, pas de soutien-gorge comme article de mode, pas d’accessoires, chaussures, bijoux ni logos. Conservez visage, cheveux, proportions et marques de surface pour le CG vestimentaire / l’essayage ultérieur. Ignorez toute description de costume extérieur pour cette planche.",
  "sheet.wardrobe.halfBareLower": "Référence partielle du bas du corps pour les mesures de design de costume (personnage adulte uniquement ; étude de figure clinique ; pas érotique ; pas pornographique ; pas suggestif) : éclairage studio clinique neutre, cyclorama gris uni, pose debout médicale / mannequin professionnelle. Pas de photographie de mode, pas de stylisme lingerie, pas de chambre, pas de caméra sexualisée. Bas du corps nu : hanches, cuisses, jambes et pieds nus ; visage et cheveux entièrement visibles. Zones intimes seulement : couverture opaque minimale mate couleur chair ou neutre (slip simple — production seulement, pas de lingerie de mode). Haut du corps couvert uniquement d’un haut opaque simple mat et neutre (débardeur uni, maillot de corps ou drapé — couverture de production seulement, pas de stylisme mode, pas de logos). Pas de costume extérieur, accessoires, chaussures ni bijoux. Conservez visage, cheveux, proportions et marques de surface pour le CG vestimentaire / l’essayage ultérieur. Ignorez toute description de costume extérieur pour cette planche.",
  "sheet.wardrobe.bare": "Référence anatomique corporelle complète pour les mesures de design de costume (personnage adulte uniquement ; étude de figure clinique ; pas érotique ; pas pornographique ; pas suggestif) : éclairage studio clinique neutre, cyclorama gris uni, pose debout médicale / mannequin professionnelle. Pas de photographie de mode, pas de pose lingerie, pas de chambre, pas de caméra sexualisée. Le sujet est entièrement sans vêtement (forme corporelle nue complète, ou surface nue adaptée à l’espèce) avec visage et cheveux seulement — pas de vêtement, pas de couvertures partielles, pas de costume extérieur, accessoires, chaussures ni bijoux. Conservez visage, cheveux, proportions et marques de surface pour le CG vestimentaire / l’essayage ultérieur. Ignorez toute description de costume extérieur pour cette planche.",
  "sheet.wardrobe.base": "Référence de couche de base de production (sous-vêtements / vêtement de base pour l’échange de costume, pas érotique) : sous-vêtements unis simples neutres ou couverture de base adaptée à l’espèce seulement (ex. slip uni + maillot de corps, ou drapé simple). Pas de costume extérieur, logos, stylisme lingerie de mode ni pose suggestive. Lumière studio clinique, fond gris. Conservez l’identité pour habiller les costumes extérieurs plus tard. Ignorez la description de costume extérieur pour cette planche.",
  "sheet.wardrobe.costume": "Référence de costume de production : garde-robe extérieure complète telle que décrite ; matières et silhouette lisibles pour la continuité vidéo.",
  "sheet.layout.bible": "Planche bible de personnage paysage 16:9 avec exactement trois cases verticales égales de gauche à droite : (1) corps entier debout de face, pieds visibles, bras détendus ; (2) corps entier trois-quarts ~45° ; (3) portrait tête-et-épaules face caméra. Chaque figure remplit sa case. Même visage, cheveux, corps et costume dans les trois. Gouttières nettes, studio propre.",
  "sheet.layout.turnaround": "Vues tournantes paysage 16:9 avec exactement quatre figures corps entier à la même échelle : face, profil gauche 90°, dos entier, profil droit 90°. Pose en A neutre / bras détendus, pieds au sol. Costume complet. Hauteur de figure maximale.",
  "sheet.layout.expression": "Carré 1:1 grille 2×2 serrée d’exactement quatre gros plans tête-et-épaules : neutre, sourire léger, colère, surprise. Chaque visage remplit ~90 % de sa cellule ; cheveux et col identiques. Pas de corps entier.",
  "sheet.layout.costume": "Planche costume verticale 9:16 : haut ~65 % grand héros corps entier en costume complet face caméra ; bande inférieure exactement deux grands recadrages de détail (tissu/poche + chaussures ou accessoire emblématique). Matières lisibles.",
  "sheet.layout.identity_lock": "Verrouillage d’identité paysage 16:9 avec exactement deux cases : gauche 60 % gros plan de face large ; droite 40 % visage trois-quarts. Maximisez le détail facial pour l’identité vidéo ; pas de corps entier.",
  "sheet.layout.face_id": "Carré 1:1 unique grand portrait de face centré (ou tête principale), haut du corps inclus, regard dans l’objectif. Traits primaires nets, entièrement dans le support graphique obligatoire. Un seul personnage.",
  "sheet.layout.hero": "Portrait héros unique corps entier vertical 9:16, hauteur des yeux, figure entière visible. Posture neutre centrée, fond studio, costume complet, support graphique obligatoire.",
  "sheet.layout.bust": "Carré 1:1 buste moyen (poitrine vers le haut), corps légèrement trois-quarts, visage vers la caméra. Cadrage de dialogue, col du costume visible.",
  "sheet.layout.three_quarter": "Vertical 9:16 corps trois-quarts (~genoux vers le haut), corps à 30–45°, visage vers la caméra. Silhouette de costume claire, mains visibles.",
  "sheet.layout.profile": "Vertical 9:16 profil gauche pur corps entier 90°, regard à gauche, colonne droite. Vraie silhouette ; costume complet ; un seul personnage.",
  "sheet.layout.back": "Vertical 9:16 vue de dos corps entier, dos à la caméra, cheveux et dos du costume lisibles. Planche de continuité de sortie.",
  "sheet.layout.low_angle": "Vertical 9:16 corps entier contre-plongée héroïque, caméra près de la taille légèrement vers le haut, posture puissante, visage encore net, costume complet.",
  "sheet.layout.high_angle": "Vertical 9:16 corps trois-quarts plongée, caméra légèrement au-dessus de la ligne des yeux vers le bas, visage lisible, costume complet.",
  "sheet.layout.action": "Paysage 16:9 arrêt sur image d’action d’un personnage en plein mouvement (marche ou extension du bras), net sans flou de mouvement, costume complet, environnement gris doux.",
  "sheet.layout.dialogue": "Paysage 16:9 cadrage de dialogue par-dessus l’épaule : épaule floue au premier plan du même personnage, visage net au fond regardant vers la gauche de la caméra. Une seule identité.",
  "sheet.layout.body_nude_turnaround": "Vues tournantes de proportions corporelles paysage 16:9 avec exactement quatre figures corps entier à la même échelle : face, gauche 90°, dos, droite 90°. Pose en A neutre, bras légèrement écartés du torse pour une silhouette claire, pieds au sol. Justaucorps couleur chair seulement. Visage et cheveux cohérents.",
  "sheet.layout.body_nude_front": "Plaque unique de proportions corporelles verticale 9:16, corps entier de face, hauteur des yeux, tête aux pieds visible, bras détendus. Proportions claires pour l’essayage de costume. Justaucorps couleur chair seulement. Posture professionnelle neutre.",
  "sheet.layout.body_nude_t_pose": "Paysage 16:9 unique corps entier en pose en T ou pose en A (bras horizontaux ou baissés de 30°), de face, justaucorps couleur chair pour référence de skinning / de rig. Pieds à largeur d’épaules, visage vers l’avant, allure de mannequin clinique pour la chaîne vestimentaire.",
  "sheet.layout.body_half_bare_turnaround": "Vues tournantes haut du corps nu paysage 16:9 avec exactement quatre figures corps entier à la même échelle : face, gauche 90°, dos, droite 90°. Pose en A neutre, bras légèrement écartés du torse pour une silhouette haute claire, pieds au sol. Haut du corps nu + bas simple seulement. Visage et cheveux cohérents.",
  "sheet.layout.body_half_bare_front": "Plaque unique verticale 9:16 corps entier de face, haut du corps nu, hauteur des yeux, tête aux pieds visible, bras détendus. Torse nu ; bas unis simples seulement. Proportions claires. Posture professionnelle neutre.",
  "sheet.layout.body_half_bare_t_pose": "Paysage 16:9 unique corps entier en pose en T ou pose en A (bras horizontaux ou baissés de 30°), de face, haut du corps nu pour référence de skinning / de rig. Bas unis simples seulement. Pieds à largeur d’épaules, visage vers l’avant, allure de mannequin clinique.",
  "sheet.layout.body_half_bare_lower_turnaround": "Vues tournantes bas du corps nu paysage 16:9 avec exactement quatre figures corps entier à la même échelle : face, gauche 90°, dos, droite 90°. Pose en A neutre, jambes légèrement écartées pour une silhouette basse claire, pieds au sol. Bas du corps nu + haut simple seulement. Visage et cheveux cohérents.",
  "sheet.layout.body_half_bare_lower_front": "Plaque unique verticale 9:16 corps entier de face, bas du corps nu, hauteur des yeux, tête aux pieds visible, bras détendus. Jambes nues ; haut uni simple seulement. Proportions claires. Posture professionnelle neutre.",
  "sheet.layout.body_half_bare_lower_t_pose": "Paysage 16:9 unique corps entier en pose en T ou pose en A (bras horizontaux ou baissés de 30°), de face, bas du corps nu pour référence de skinning / de rig. Haut uni simple seulement. Pieds à largeur d’épaules, visage vers l’avant, allure de mannequin clinique.",
  "sheet.layout.body_bare_turnaround": "Vues tournantes anatomiques paysage 16:9 avec exactement quatre figures corps entier à la même échelle : face, gauche 90°, dos, droite 90°. Pose en A neutre, bras légèrement écartés du torse pour une silhouette claire, pieds au sol. Forme entièrement sans vêtement seulement. Visage et cheveux cohérents.",
  "sheet.layout.body_bare_front": "Plaque anatomique unique verticale 9:16, corps entier de face, hauteur des yeux, tête aux pieds visible, bras détendus. Proportions claires pour l’essayage de costume. Forme entièrement sans vêtement seulement. Posture professionnelle neutre.",
  "sheet.layout.body_bare_t_pose": "Paysage 16:9 unique corps entier en pose en T ou pose en A (bras horizontaux ou baissés de 30°), de face, forme entièrement sans vêtement pour référence de skinning / de rig. Pieds à largeur d’épaules, visage vers l’avant, allure de mannequin clinique pour la chaîne vestimentaire.",
  "sheet.layout.base_layer_turnaround": "Vues tournantes de couche de base paysage 16:9 avec exactement quatre figures corps entier : face, gauche 90°, dos, droite 90°. Seulement des sous-vêtements / vêtements de base simples (gris ou beige unis), pas de costume extérieur. Pose en A neutre.",
  "sheet.layout.base_layer_hero": "Vertical 9:16 unique corps entier de face en sous-vêtements de base simples seulement, pose debout neutre, tête aux pieds. Silhouette propre, prête pour superposer le costume extérieur plus tard.",
  "sheet.layout.costume_hero": "Vertical 9:16 unique corps entier de face en costume extérieur complet tel que conçu, pose héros debout, tête aux pieds, matières lisibles.",
  "sheet.layout.costume_turnaround": "Vues tournantes costume complet paysage 16:9, exactement quatre figures corps entier : face, gauche 90°, dos, droite 90°. Même échelle, pose en A, garde-robe extérieure complète y compris chaussures et couches extérieures.",
  "sheet.layout.costume_detail_board": "Planche de détail carrée 1:1 avec exactement quatre gros plans larges du costume complet : armure du tissu, attache/bouton, chaussures ou bottes, accessoire emblématique. Pas de corps entier ; fidélité matière pour la continuité vestimentaire.",
  "sheet.layout.hands": "Carré 1:1 étude rapprochée des mains du personnage (petit accessoire facultatif). Ton de peau/surface conforme à l’identité ; articulations nettes. Planche de détail de continuité.",
  "sheet.layout.feet_shoes": "Carré 1:1 avec exactement deux grandes cases : à gauche pieds nus (ou pattes nues/équivalent) sur sol sans couture ; à droite chaussures/bottes ou chaussage conçu correspondant si le costume en a. Silhouette claire pour l’échange vestimentaire.",
  "sheet.layout.accessories": "Planche d’accessoires carrée 1:1 : jusqu’à quatre gros plans style produit de chapeau, sac, arme, bijoux ou accessoires emblématiques de la description de costume. Studio propre, pas de corps entier.",
  "sheet.layout.silhouette": "Vertical 9:16 silhouette pleine noire du personnage corps entier de face sur blanc pur ou gris clair, sans détail intérieur, contour extérieur lisible pour les contrôles de proportions lors de l’échange de costume. Seconde case latérale pâle facultative si l’espace le permet — préférez une seule silhouette de face forte.",
  "plate.scene.emptySet": "Plaque de lieu vide pour la continuité de drama court : pas de visages de personnage héros, pas d’acteurs nommés, tout au plus de minuscules silhouettes lointaines si besoin d’échelle. Conservez architecture, matières, enseignes et habillage de plateau clé.",
  "plate.scene.lock.lead": "Créez un still de référence de lieu pour la continuité vidéo de drama court IA.",
  "plate.scene.lock.identity": "Verrouillage d’identité spatiale : même architecture, matières, enseignes et langage de mise en page dans toutes les cases.",
  "plate.scene.lock.forbidden": "Interdit : visages de célébrités reconnaissables, portraits de distribution nommés, gros plans héros encombrés, filigranes, incrustations de texte d’interface.",
  "plate.scene.lock.quality": "Qualité : matières nettes, verticales stables, fidélité de photographie de direction artistique / d’art conceptuel professionnelle.",
  "plate.scene.lock.name": "Nom du lieu : {{name}}",
  "plate.scene.lock.place": "Description du lieu : {{place}}",
  "plate.scene.lock.type": "Type d’espace : {{type}}",
  "plate.scene.lock.time": "Moment de la journée : {{time}}",
  "plate.scene.lock.weather": "Météo : {{weather}}",
  "plate.scene.lock.mood": "Humeur : {{mood}}",
  "plate.scene.lock.lighting": "Conception lumière : {{lighting}}",
  "plate.scene.lock.palette": "Palette de couleurs : {{palette}}",
  "plate.scene.lock.set": "Habillage de plateau : {{set}}",
  "plate.scene.lock.tags": "Tags visuels : {{tags}}",
  "plate.scene.scaffold.repeatMedium": "Rappel : le support doit être l’id de style « {{id}} » ({{family}}).",
  "plate.scene.scaffold.layer": "Couche de plaque : {{layer}}.",
  "plate.scene.scaffold.finalCheck": "Vérification finale : support {{style}} correct ; vide de visages héros ; identité du lieu verrouillée.",
  "plate.scene.edit.task": "Tâche d’édition d’image / changement de style du lieu (priorité maximale) :",
  "plate.scene.edit.keep": "Gardez l’identité du lieu depuis la source : masses architecturales, matières, enseignes, disposition clé de l’habillage de plateau.",
  "plate.scene.edit.change": "Changez le support et/ou la mise en page caméra selon le paquet de plaque ci-dessous.",
  "plate.scene.edit.forbid": "N’inventez pas un autre lieu. N’ajoutez pas de visages de personnage héros.",
  "plate.scene.layout.establishing": "Paysage 16:9 plan d’établissement de l’extérieur complet du lieu ou du volume maître, repères lisibles, ligne d’horizon ou de plafond stable, profondeur cinématographique.",
  "plate.scene.layout.hero_plate": "Paysage 16:9 still héros du lieu — le cadre de couverture définitif de ce plateau. Composition forte, sol de scène ou rue clair pour le placement futur.",
  "plate.scene.layout.three_quarter_space": "Paysage 16:9 espace trois-quarts avec cadre de premier plan, zone de jeu au second plan, profondeur d’arrière-plan. Idéal comme scène de dialogue vide de visages.",
  "plate.scene.layout.identity_lock": "Paysage 16:9 avec exactement deux cases égales du même lieu : (1) angle clé frontal (2) trois-quarts ~45°. Mêmes matières, enseignes, palette.",
  "plate.scene.layout.low_angle": "Vertical 9:16 contre-plongée vers l’architecture / le plafond / le dais pour l’échelle dramatique. Pas de visages.",
  "plate.scene.layout.high_angle": "Paysage 16:9 plongée du plan au sol / de la géométrie de rue pour référence de placement. Vide de visages.",
  "plate.scene.layout.pov_enter": "Paysage 16:9 entrée à la première personne par une porte ou l’embouchure d’une ruelle dans le lieu. Plateau vide au-delà du seuil.",
  "plate.scene.layout.over_shoulder_empty": "Paysage 16:9 cadre vide par-dessus l’épaule : seulement une silhouette d’épaule anonyme floue, arrière-plan net du lieu pour le placement de dialogue.",
  "plate.scene.layout.day_clear": "Paysage 16:9 même lieu sous lumière de jour claire, direction naturelle du soleil, ombres lisibles, surfaces sèches.",
  "plate.scene.layout.golden_hour": "Paysage 16:9 même lieu à l’heure dorée : longues ombres chaudes, liseré ambré, humeur de drama court romantique, vide de visages.",
  "plate.scene.layout.night_neon": "Paysage 16:9 même lieu de nuit avec sources pratiques / néon / lampadaires, débord cyan-magenta facultatif, humidité facultative, vide de visages.",
  "plate.scene.layout.rain_wet": "Paysage 16:9 même lieu sous la pluie : asphalte mouillé/reflets, traînées de pluie, étalonnage plus froid, parapluies seulement comme accessoires lointains, pas de visages.",
  "plate.scene.layout.fog_mood": "Paysage 16:9 même lieu dans le brouillard/la fumée : couches de profondeur douces, palette assourdie, humeur de mystère, architecture encore lisible, pas de visages.",
  "plate.scene.layout.set_dressing": "Planche d’habillage de plateau carrée 1:1 table / comptoir / étagère des accessoires clés de ce lieu, pas de personnes.",
  "plate.scene.layout.material_board": "Planche de continuité matière carrée 1:1 : mur, sol, métal/bois, tissu de ce lieu. Détail rapproché, pas de visages, pas de personnages corps entier.",
  "plate.scene.layout.signage_prop": "Carré 1:1 gros plan d’enseigne / accessoire-repère lisible pour le verrouillage d’identité du lieu. Formes nettes de type texte (glyphes inventés permis si besoin). Pas de visages.",
  "plate.scene.layout.lighting_ref": "Paysage 16:9 référence lumière du plateau vide : direction de lumière principale claire, lumière d’appoint, sources pratiques, pas de personnages.",
  "plate.prop.lock.lead": "Créez un still de référence d’accessoire pour la continuité de drama court IA.",
  "plate.prop.lock.name": "Nom de l’accessoire : {{name}}",
  "plate.prop.lock.desc": "Description (doit correspondre) : {{desc}}",
  "plate.prop.lock.material": "Matière : {{material}}",
  "plate.prop.lock.size": "Notes de taille : {{size}}",
  "plate.prop.lock.condition": "État/usure : {{condition}}",
  "plate.prop.lock.tags": "Tags : {{tags}}",
  "plate.prop.lock.forbidden": "Interdit : visages de célébrités, filigranes, accessoires extra hors sujet qui brouillent l’identité.",
  "plate.prop.scaffold.repeatMedium": "Rappel : le support doit être l’id de style « {{id}} ».",
  "plate.prop.scaffold.finalCheck": "Vérification finale : même identité d’accessoire ; support {{style}}.",
  "plate.prop.edit.task": "Édition d’image / changement de style de l’accessoire :",
  "plate.prop.edit.keep": "Gardez la même identité d’accessoire depuis l’image source (silhouette, matières, marques).",
  "plate.prop.edit.change": "Changez le support/la caméra selon le besoin. N’inventez pas un autre objet.",
  "plate.prop.layout.hero": "Carré 1:1 still produit héros unique de l’accessoire, centré, cyclorama gris sans couture, matières nettes, pas de visages, objet entier visible.",
  "plate.prop.layout.three_quarter": "Carré 1:1 vue trois-quarts du même accessoire, lumière studio, silhouette lisible, pas de mains sauf besoin d’échelle.",
  "plate.prop.layout.detail": "Carré 1:1 très gros plan du détail emblématique de l’accessoire (gravure, fermoir, écran, usure). Pas de visages.",
  "plate.prop.layout.material": "Carré 1:1 plaque de fidélité matière de la surface de l’accessoire : texture métal/bois/tissu, pas de personnes corps entier.",
  "plate.prop.layout.in_hand_scale": "Paysage 16:9 référence d’échelle : main anonyme ou silhouette tenant l’accessoire pour la taille. Visage hors cadre ou entièrement anonyme. L’accessoire est le héros.",
  "action.geometry.panelCount": "Nombre de cases fixe : exactement {{n}} case(s). Comptez-les : {{list}}.",
  "action.geometry.lockGrid2x3": "Verrouillage de mise en page (obligatoire) : 2 rangées × 3 colonnes = six cases au total. La rangée du haut doit contenir les cases 1, 2, 3. La rangée du bas doit contenir les cases 4, 5, 6. Interdit : grille 2×2, 4 cases, 3×2 mal compté, cadre héros unique, collage de moins de cases. Si vous êtes tenté de n’en dessiner que quatre — arrêtez-vous et dessinez les six.",
  "action.geometry.lockGrid2x2": "Verrouillage de mise en page (obligatoire) : 2 rangées × 2 colonnes = quatre cases au total. Interdit : grille 2×3 à six cases, bandes horizontales, cadre unique.",
  "action.geometry.lockStrip": "Verrouillage de mise en page (obligatoire) : une rangée horizontale d’exactement {{n}} cases (1 rangée × {{n}} colonnes). Interdit : grille 2×2, moins de {{n}} cases, plusieurs rangées empilées sauf indication.",
  "action.geometry.order": "L’ordre des cases est la chronologie de l’action : case 1 = premier temps fort, case {{n}} = dernier temps fort.",
  "action.geometry.reading": "Ordre de lecture : gauche → droite, puis haut → bas (si plusieurs rangées).",
  "action.geometry.numbers": "Grands numéros gras d’angle 1 à {{n}} sur chaque case (haut-gauche de cette case). Chaque entier de 1 à {{n}} doit apparaître une fois.",
  "action.geometry.panelLine": "Case {{i}}/{{n}} ({{label}}) : un instant séquentiel distinct — pose/phase différente de toutes les autres cases ; ne copiez ni ne répétez les poses.",
  "action.geometry.caption": "Petite légende en français sous chaque case, correspondant au libellé du temps fort.",
  "action.geometry.identity": "Même identité de personnage / costume / continuité d’accessoire dans toutes les cases.",
  "action.geometry.layout.strip-2": "Une seule image paysage : bande de découpage horizontale d’exactement 2 cases égales côte à côte (1 rangée × 2 colonnes), gouttières épaisses et nettes entre les cases",
  "action.geometry.layout.strip-3": "Une seule image paysage : bande de découpage horizontale d’exactement 3 cases égales sur une rangée (1 rangée × 3 colonnes), gouttières épaisses et nettes",
  "action.geometry.layout.grid-2x2": "Une seule image carrée : grille de découpage 2×2 d’exactement 4 cases égales (2 rangées × 2 colonnes), gouttières épaisses et nettes, lecture gauche-à-droite puis haut-vers-bas",
  "action.geometry.layout.strip-4": "Une seule image paysage large : bande de découpage horizontale d’exactement 4 cases égales sur une rangée (1 rangée × 4 colonnes), gouttières épaisses et nettes",
  "action.geometry.layout.strip-5": "Une seule image paysage large : bande de découpage horizontale d’exactement 5 cases égales sur une rangée (1 rangée × 5 colonnes), gouttières épaisses et nettes",
  "action.geometry.layout.grid-2x3": "Une seule image paysage : grille de découpage d’exactement 6 cases égales en 2 rangées × 3 colonnes (rangée du haut cases 1-2-3, rangée du bas cases 4-5-6), gouttières épaisses et nettes, lecture gauche-à-droite puis haut-vers-bas",
  "swap.costume.task": "Tâche d’édition d’image / échange de costume (priorité maximale — lisez entièrement avant de peindre) :",
  "swap.costume.sameCharacter": "Vous habillez le même personnage de l’image source d’une nouvelle garde-robe extérieure seulement.",
  "swap.costume.identity": "Verrouillage d’identité (ne jamais changer) : forme du visage/de la tête, yeux, couleur et coupe des cheveux, proportions du corps, espèce/plan corporel, peau ou marques de surface, présentation d’âge.",
  "swap.costume.pose": "Verrouillage de pose : gardez la même pose corporelle et le même cadrage caméra de la source, sauf si la mise en page ci-dessous exige une planche multi-vues.",
  "swap.costume.replace": "Remplacement vestimentaire (toujours) : retirez tout vêtement extérieur précédent, armure, manteau, robe, uniforme, équipement extérieur et chaussures discordantes de la source.",
  "swap.costume.paint": "Puis peignez seulement le nouveau costume extérieur décrit ci-dessous — couverture complète, silhouette correcte, matières lisibles, chaussures et accessoires extérieurs correspondants.",
  "swap.costume.new": "Nouveau costume extérieur (doit correspondre exactement, haute priorité) : {{costume}}",
  "swap.costume.add": "Si la source est nue ou en sous-vêtements de couche de base seulement : ajoutez le costume extérieur complet par-dessus tout en préservant l’anatomie et la logique de sous-couche.",
  "swap.costume.complete": "Si la source porte déjà un costume : remplacez-le complètement — ne mélangez pas, ne superposez pas et ne laissez pas l’ancienne tenue en fantôme sous la nouvelle.",
  "swap.costume.edges": "Les bords des vêtements doivent s’asseoir correctement sur les épaules, la taille, les poignets, les chevilles ; pas de tissu flottant, pas de membres fusionnés.",
  "swap.costume.forbidden": "Interdit : changer d’espèce, d’âge, d’identité de visage, de morphologie, second personnage, pose érotique, filigranes, légendes texte, cadre d’interface.",
  "swap.costume.nonHuman": "Sujets non humains : couverture / équipement extérieur adapté à l’espèce, conforme à la description de costume.",
  "swap.costume.subject": "Sujet : {{name}}",
  "swap.costume.age": "Âge / maturité : {{age}}",
  "swap.costume.gender": "Genre / présentation : {{gender}}",
  "swap.costume.appearance": "Verrouillage d’apparence : {{appearance}}",
  "swap.costume.tags": "Tags visuels : {{tags}}",
  "swap.costume.manner": "Indices de tic seulement : {{manner}}",
  "swap.costume.checklist": "Liste finale : (1) même visage/corps que la source (2) seulement le nouveau costume visible (3) support = {{style}} (4) studio propre ou fond neutre.",
  "swap.costume.layout.hero_front": "Vertical 9:16 unique pose debout corps entier de face, tête aux pieds visible, posture héros neutre, bras détendus, pieds au sol. Un seul personnage.",
  "swap.costume.layout.three_quarter": "Carré 1:1 unique portrait corps entier trois-quarts (~45°), tête aux pieds de préférence, silhouette du nouveau costume lisible.",
  "swap.costume.layout.profile": "Vertical 9:16 unique vrai profil corps entier (vue de côté 90°), tête aux pieds, posture neutre, silhouette de costume et coutures latérales pleinement lisibles. Un seul personnage.",
  "swap.costume.layout.back": "Vertical 9:16 unique vue de dos corps entier, tête aux pieds, bras légèrement écartés du corps pour que le dos du manteau/de la robe/des cheveux et la silhouette arrière soient clairs. Un seul personnage.",
  "swap.costume.layout.bust": "Vertical 3:4 unique portrait buste du haut du corps (poitrine vers le haut), col, encolure, épaules, couches extérieures et bijoux de visage lisibles ; pas un recadrage corps entier. Un seul personnage.",
  "swap.costume.layout.detail_fabric": "Planche de détail costume carrée 1:1 : gros plans de l’armure du tissu, boutons, fermetures éclair, broderie, quincaillerie de ceinture et transitions de matières du nouveau costume extérieur seulement ; pas de scène complète, pas de second personnage.",
  "swap.costume.layout.turnaround": "Vues tournantes paysage 16:9 avec exactement quatre figures corps entier à la même échelle : face, gauche 90°, dos, droite 90°. Pose en A neutre, nouveau costume complet sur chaque vue.",
  "swap.atmosphere.task": "Tâche d’édition d’image / échange d’atmosphère (priorité maximale) :",
  "swap.atmosphere.keep": "Gardez l’identité du lieu depuis la source : masses de bâtiments, murs, indices de plan au sol, enseignes, disposition du mobilier, angle de caméra.",
  "swap.atmosphere.replace": "Remplacez complètement : moment de la journée, météo, ciel, couleur des sources pratiques, humidité, brouillard, intensité du néon tels que décrits.",
  "swap.atmosphere.new": "Nouvelle atmosphère (doit correspondre exactement) : {{atmo}}",
  "swap.atmosphere.forbidden": "Interdit : transformer l’architecture en un autre lieu, ajouter des visages héros, filigranes, légendes texte.",
  "swap.atmosphere.location": "Lieu : {{title}}",
  "swap.atmosphere.place": "Lieu de base : {{place}}",
  "swap.atmosphere.set": "Verrouillage d’habillage de plateau : {{set}}",
  "swap.atmosphere.tags": "Tags : {{tags}}",
  "swap.atmosphere.checklist": "Liste finale : même géométrie de lieu ; seule l’atmosphère a changé ; support {{style}} ; pas de visages héros.",
  "swap.atmosphere.repeatMedium": "Rappel : le support doit être l’id de style « {{id}} » ({{family}}).",
  "swap.atmosphere.layout.wide": "Paysage 16:9 cadre complet du lieu, collant autant que possible à la composition source.",
  "swap.atmosphere.layout.hero": "Paysage 16:9 still héros du lieu, même architecture, atmosphère mise à jour seulement.",
  "swap.atmosphere.layout.detail": "Carré 1:1 détail atmosphérique de surfaces mouillées / sources pratiques / ciel, encore reconnaissable comme le même plateau.",
}
