import type { PromptCopyTable } from './keys'

export const hiPromptCopy: PromptCopyTable = {
  "speechLock.named": "संवाद लॉक · पात्र \"{{who}}\": सुनाई देने वाली बोली और होंठों की गति केवल {{primaryName}} ({{primary}}) हो। {{forbid}} या कोई और भाषा न बोलें। हर क्लिप पर वही भाषा रखें। संवाद का अनुवाद न करें।",
  "speechLock.unnamed": "संवाद लॉक · बोलने वाले पात्र: सुनाई देने वाली बोली और होंठों की गति केवल {{primaryName}} ({{primary}}) हो। {{forbid}} या कोई और भाषा न बोलें। हर क्लिप पर वही भाषा रखें। संवाद का अनुवाद न करें।",
  "speechLock.namedMulti": "संवाद लॉक · पात्र \"{{who}}\": सुनाई देने वाली बोली और होंठों की गति {{primaryName}} ({{primary}}) हो। दूसरी भाषा तभी जब पंक्ति पहले से उस भाषा में हो: {{extras}}। तीसरी भाषा वर्जित। क्लिप के बीच भाषा न बदलें। {{forbid}} पर न जाएँ। अनुवाद न करें।",
  "speechLock.unnamedMulti": "संवाद लॉक · बोलने वाले पात्र: सुनाई देने वाली बोली और होंठों की गति {{primaryName}} ({{primary}}) हो। दूसरी भाषा तभी जब पंक्ति पहले से उस भाषा में हो: {{extras}}। तीसरी भाषा वर्जित। क्लिप के बीच भाषा न बदलें। {{forbid}} पर न जाएँ। अनुवाद न करें।",
  "hardRules.sealHeader": "कठोर नियम (सर्वोच्च प्राथमिकता — मानना अनिवार्य; टकराव पर ये मान्य):",
  "hardRules.sealFooter": "यदि पहले का निर्देश कठोर नियमों से टकराए तो कठोर नियमों का पालन करें।",
  "hardRules.labelStory": "कहानी",
  "hardRules.labelCharacter": "पात्र",
  "hardRules.labelScene": "स्थान",
  "hardRules.labelProp": "वस्तु",
  "hardRules.labelAction": "क्रिया",
  "continuity.lockHeader": "निरंतरता लॉक (अनुक्रम में अनिवार्य):",
  "continuity.hasImage": "संलग्न चित्र बीट {{n}} का अंत फ्रेम／कीफ्रेम है। यह शॉट उसी दृश्य स्थिति से जारी रहे; दूसरे सेट पर अचानक कट न करें।",
  "continuity.noImage": "बीट {{n}} से जारी रखें (स्थिर चित्र नहीं — केवल दस्तावेज़ मिलाएँ)।",
  "continuity.identity": "पहचान: वही व्यक्ति — चेहरा, बाल, अनुपात, वस्त्र रंग, सहायक वस्तुएँ। रीस्टाइल या उम्र बदलना मना।",
  "continuity.space": "स्थान: वही जगह — वास्तुकला, सामग्री, लेआउट, प्रकाश दिशा। केवल कथा माँगे तो हल्का समय-परिवर्तन।",
  "continuity.action": "क्रिया: पिछले फ्रेम की मुद्रा, दृष्टि और गति उठाएँ; दूसरी व्यवस्था पर कट न करें।",
  "continuity.prevContext": "पिछली बीट का संदर्भ: {{snippet}}",
  "continuity.noText": "कोई उपशीर्षक, लोगो या वॉटरमार्क नहीं।",
  "directorLabel.lock": "संवाद लॉक",
  "directorLabel.story": "कहानी: ",
  "directorLabel.style": "शैली: ",
  "directorLabel.cast": "कलाकार: ",
  "directorLabel.location": "स्थान: ",
  "directorLabel.prop": "वस्तु: ",
  "directorLabel.primaryChar": "मुख्य पात्र: ",
  "directorLabel.mood": "मनोदशा: ",
  "directorLabel.atmo": "वातावरण: ",
  "directorLabel.camera": "कैमरा: ",
  "directorLabel.sfx": "ध्वनि: ",
  "directorLabel.action": "क्रिया: ",
  "directorLabel.expr": "अभिव्यक्ति: ",
  "directorLabel.speech": "संवाद: ",
  "directorLabel.notes": "टिप्पणियाँ: ",
  "directorLabel.identity": "पहचान: ",
  "directorLabel.space": "स्थान: ",
  "directorLabel.ref": "स्थिर चित्र ",
  "directorLabel.beatN": "बीट {{n}} · ",
  "directorLabel.beatNsec": "बीट {{n}} · {{s}} सेकंड",
  "directorLabel.hardRules": "कठोर नियम",
  "directorLabel.identityLock": "पहचान लॉक",
  "directorLabel.spaceLock": "स्थान लॉक",
  "storyBeats.system": "You write short-drama TIMELINE BEATS for AI video.\nEach beat = ONE short clip screenplay (not a single spoken line).\nA beat MUST include rich performance content: mood, atmosphere, actions, expressions, optional camera/sfx, and zero or more spoken dialogue lines (1–4 lines common).\nReturn ONLY a JSON array (no fences). Each item shape:\n{\"characterName\":\"…\",\"characterNames\":[\"…\"],\"sceneHint\":\"…\",\"propName\":\"…\",\"mood\":\"…\",\"atmosphere\":\"…\",\"camera\":\"…\",\"sfx\":\"…\",\"units\":[{\"type\":\"action\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"expression\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"dialogue\",\"who\":\"…\",\"line\":\"…\",\"tone\":\"…\",\"parenthetical\":\"…\"},{\"type\":\"note\",\"text\":\"…\"}]}\nRules:\n- units.type dialogue.line = ONLY words the character speaks (no stage directions inside line).\n- Put physical business in action; face/micro-performance in expression; delivery in tone/parenthetical.\n- Multiple dialogue units in one beat are encouraged when the clip has a short exchange or self-talk.\n- Pure action beats (no dialogue) are allowed.\n- Write 4–8 beats. Use only cast names provided.\n- Prefer conflict, clear visual action, filmable detail.\n- Stay faithful to the title, style, cast, and scenes provided.\n- SPEECH: write each dialogue.line in that speaker's primary spoken language from the cast list. Do not switch languages between beats. Do not translate lines unless that is the character's listed language.",
  "storyBeats.userLead": "नीचे का पूरा कास्ट, दृश्य, प्रॉप्स, शैली और विचार इस्तेमाल कर क्लिप पटकथा बीट बनाएँ।",
  "storyBeats.eachBeat": "हर बीट में मूड + माहौल + क्रिया/अभिव्यक्ति + वैकल्पिक संवाद चाहिए।",
  "storyBeats.story": "कहानी: {{title}}",
  "storyBeats.style": "शैली: {{style}}",
  "storyBeats.userDir": "उपयोगकर्ता निर्देश: {{idea}}",
  "storyBeats.cast": "कास्ट:",
  "storyBeats.scenes": "दृश्य:",
  "storyBeats.props": "प्रॉप्स: {{props}}",
  "storyBeats.returnJson": "केवल बीट्स का JSON ऐरे लौटाएँ।",
  "storyBeats.noCast": "(कोई कास्ट नहीं)",
  "storyBeats.noScenes": "(कोई दृश्य नहीं — sceneHint में स्थान लिखें)",
  "storyBeats.none": "(कोई नहीं)",
  "videoPolish.system": "आप शॉर्ट-ड्रामा AI वीडियो मॉडल के लिए एक अंतिम चित्र-से-वीडियो प्रॉम्प्ट लिखते हैं।\nकेवल प्रॉम्प्ट पाठ लौटाएँ — कोई markdown बाड़, शीर्षक या व्याख्या नहीं।\nनियम:\n- निर्देशक प्रॉम्प्ट इंटरफ़ेस भाषा में लिखें; पात्र नाम और संवाद भाषा कोड स्पष्ट रखें।\n- व्यक्ति स्टिल: पहचान लॉक। स्थान प्लेट: स्थान लॉक। सामग्री नाम न दे तो नए चेहरे न जोड़ें।\n- रूप, गति, वाणी या वातावरण पर असर डालने वाले सभी प्रोफ़ाइल / soul / बीट / स्थान तथ्य इस्तेमाल करें; खाली फ़ील्ड छोड़ें।\n- सामग्री और seed से फिल्म करने योग्य क्लिप के लिए ही गढ़ें — नमूना संसार, Demo या बाहर के तथ्य न लाएँ।\n- लंबा soul.md अभिनय और पहचान बीट में समेटें; पूरी बाइबल न चिपकाएँ।\n- अवधि सामग्री की वास्तविक सेकंड। सतत क्रिया। बिना पाठ, लोगो, वॉटरमार्क या अतिरिक्त लोगों के।\n- जब तक स्क्रिप्ट न कहे, सामान्य शरीर (दो हाथ, दो बाँह, दो टाँग)।\n- कई पात्र हों तो प्रत्येक सुसंगत; मुख्य फ़ोकस पहले।\n- कठोर नियम हों तो रखें और अंत में रखें (सर्वोच्च प्राथमिकता)।\n- संवाद लॉक अनिवार्य: न हटाएँ, न लिखें, न अनुवाद करें। कोड पूरे नाम में खोलें। हर क्लिप पात्र की मुख्य भाषा; क्लिप के बीच भाषा न बदलें; संवाद का अनुवाद न करें।\n- निर्देशक संशोधन शैली/क्रिया निखार सकता है पर कठोर नियम नहीं तोड़ सकता।",
  "videoPolish.hardRulesKeep": "कठोर नियम (सर्वोच्च प्राथमिकता — हर पंक्ति रखें; [पात्र · नाम] जैसी वस्तु-चिप्पियाँ रहनी चाहिए)। पूरा कठोर-नियम खंड आउटपुट के अंत में रखें। कमज़ोर न करें, न हटाएँ, न किसी और पर लगाएँ।",
  "clip.task": "कार्य: लघु नाटक टाइमलाइन क्लिप (छवि से वीडियो)।",
  "clip.hasRef": "A reference still may be attached — lock identity/location continuity to it when relevant.",
  "clip.characters": "पात्र:",
  "clip.scene": "दृश्य:",
  "clip.prop": "प्रॉप:",
  "clip.action": "क्रिया / गति गाइड:",
  "clip.beat": "बीट / संवाद:",
  "clip.prev": "पिछले क्लिप की निरंतरता:",
  "clip.revision": "निर्देशक संशोधन (पालन अनिवार्य):",
  "clip.templateDraft": "टेम्पलेट मसौदा (सुधारें):",
  "intro.task": "कार्य: कास्टिंग परिचय क्लिप (छवि से वीडियो)।",
  "intro.hasRef": "Reference still is attached to the video API — lock identity to that image.",
  "intro.noRef": "No reference still path in this text; still lock to profile appearance/costume.",
  "intro.dossier": "पात्र डोजियर:",
  "intro.templateDraft": "टेम्पलेट मसौदा (सुधारें; डोजियर न छोड़ें):",
  "common.durationAspect": "अवधि: {{seconds}} सेकंड। अनुपात: {{aspect}}।",
  "common.templateDraft": "टेम्पलेट मसौदा:",
  "improve.mode": "सुधार मोड: नीचे के सभी स्रोत मिलाकर पूरा परिणाम दो। उपयोगकर्ता न कहे तो पहचान बनाए रखो।",
  "improve.draftDefault": "वर्तमान फ़ॉर्म फ़ील्ड:",
  "improve.userRequest": "सुधार अनुरोध (खाली = सब पॉलिश करो):",
  "improve.emptyDefault": "(निरंतरता के लिए सभी फ़ील्ड पॉलिश करो)",
  "improve.createDefault": "विचार / दिशा:",
  "improve.explicitContext": "केवल इसी अनुरोध का स्पष्ट संदर्भ (निरंतरता; कोई और नमूना संसार न लाओ):",
  "improve.storyTitle": "शीर्षक: {{title}}",
  "improve.styleNote": "शैली नोट: {{style}}",
  "improve.closingDefault": "अभी पूरा परिणाम दो।",
  "storyMeta.system": "तुम शॉर्ट-ड्रामा शोरनर हो। विज़ुअल बाइबल और सख्त नियम लिखो। केवल JSON।",
  "storyMeta.draftLabel": "वर्तमान कहानी फ़ील्ड:",
  "storyMeta.createLabel": "कहानी विचार / शीर्षक:",
  "storyMeta.emptyPolish": "(विज़ुअल बाइबल + hardRules पॉलिश करो)",
  "storyMeta.closing": "केवल JSON: {\"styleNote\":\"…\",\"hardRules\":\"…\"}। दोनों कुंजी ज़रूरी।",
  "storyMeta.contextLabel": "संदर्भ (कास्ट / दृश्य / प्रॉप्स):",
  "character.system": "तुम पात्र डिज़ाइनर हो। केवल एक JSON। spokenLanguages = BCP-47 ऐरे।",
  "character.draftLabel": "वर्तमान प्रोफ़ाइल फ़ील्ड:",
  "character.soulLabel": "लिंक किया soul.md / बाइबल:",
  "character.createLabel": "पात्र idea:",
  "character.emptyPolish": "(soul मिलाकर पॉलिश करो)",
  "character.closing": "पूरा JSON अभी। कुंजियाँ: {{keys}}।",
  "scene.system": "तुम लोकेशन डिज़ाइनर हो। स्थान बाइबल + इस दृश्य की पटकथा। केवल JSON।",
  "scene.draftLabel": "वर्तमान दृश्य फ़ील्ड:",
  "scene.charsLabel": "कहानी के पात्र:",
  "scene.propsLabel": "कहानी के प्रॉप्स:",
  "scene.priorLabel": "पिछले दृश्य (निरंतरता):",
  "scene.createLabel": "दृश्य idea:",
  "scene.emptyPolish": "(स्थान + पटकथा पॉलिश करो)",
  "scene.closing": "पूरा JSON। कुंजियाँ: {{keys}}।",
  "prop.system": "तुम प्रॉप डिज़ाइनर हो। केवल एक JSON। रूप, सामग्री, स्थिति स्पष्ट।",
  "prop.draftLabel": "वर्तमान प्रॉप फ़ील्ड:",
  "prop.createLabel": "प्रॉप idea:",
  "prop.emptyPolish": "(प्रॉप का रूप पॉलिश करो)",
  "prop.closing": "पूरा JSON। कुंजियाँ: {{keys}}।",
  "prop.fallbackName": "प्रॉप",
  "action.system": "तुम मोशन डायरेक्टर हो। केवल वैध JSON। अंग, गति, भार, पथ।",
  "action.storyContext": "कहानी संदर्भ (वैकल्पिक): {{title}}",
  "action.styleNote": "शैली नोट: {{style}}",
  "action.existingDraft": "मौजूदा ड्राफ्ट (पॉलिश करो):",
  "action.userIdea": "उपयोगकर्ता विचार: {{idea}}",
  "action.closing": "केवल JSON। कुंजियाँ: {{keys}}।",
  "profile.mustEveryKey": "इस सूची की हर कुंजी दो: {{keys}}।",
  "profile.valuesAreStrings": "हर मान JSON स्ट्रिंग हो। अज्ञात हो तभी खाली।",
  "profile.visualTagsRule": "visualTags: कॉमा से अलग एक स्ट्रिंग। JSON ऐरे नहीं।",
  "profile.fillConcrete": "ठोस विवरण से भरो।",
  "common.rules": "नियम:",
  "common.none": "(कोई नहीं)",
  "intro.soul": "soul.md (अभिनय/पहचान स्रोत):\n{{soul}}",
  "intro.matchBible": "(पात्र बाइबल की भाषा अपनाओ)",
  "invent.sources": "सत्य स्रोत क्रम से: (1) विचार/अनुरोध, (2) फ़ॉर्म, (3) अतिरिक्त केवल यदि इसी प्रॉम्प्ट में हों, (4) संलग्न चित्र।",
  "invent.create": "रचना मोड: विचार/चित्र से स्वतंत्र भरें; अनिवार्य कुंजी खाली न छोड़ें।",
  "invent.improve": "सुधार मोड: ड्राफ्ट संगत रखें; बिना अनुरोध पहचान न बदलें।",
  "invent.noImport": "जो इस प्रॉम्प्ट में नहीं है उसे न लाएँ — पहचान, कथानक, मौसम, पेशा, स्थान, युग, शैली।",
  "invent.storyBlock": "कहानी/शैली ब्लॉक केवल निरंतरता के लिए; स्पष्ट विचार न ढकें।",
  "character.keysLead": "केवल एक JSON, कुंजियाँ: {{keys}}",
  "character.ruleSpoken": "spokenLanguages: बोली जाने वाली भाषाओं की BCP-47 ऐरे। मौन हो तो []।",
  "character.ruleIdentity": "शीट और वीडियो में पहचान एक जैसी रखें।",
  "scene.keysLead": "केवल एक JSON, कुंजियाँ: {{keys}}",
  "scene.suggestLead": "कहानी «{{title}}» के दृश्य #{{n}} के लिए तैयार स्थान सुझाएँ।",
  "scene.suggestPlotFocus": "कथानक केंद्र: {{label}}",
  "scene.suggestStyle": "शैली: {{style}}",
  "scene.suggestExisting": "पहले से स्थान: {{titles}}",
  "scene.suggestChars": "पात्र (संदर्भ):",
  "scene.suggestProps": "प्रॉप्स (संदर्भ):",
  "scene.suggestSegment": "चयनित खंड विस्तार:",
  "scene.suggestBeats": "दृश्य / बीट:",
  "scene.suggestClosing": "पूरा दृश्य JSON दें। अलग, पुनः उपयोग योग्य स्थान बनाएँ।",
  "scene.fallbackName": "स्थान",
  "scene.ideaFromImage": "संलग्न फ़ोटो से पूरा स्थान प्रोफ़ाइल भरें।",
  "scene.polishIdea": "निखारें",
  "prop.keysLead": "केवल एक JSON, कुंजियाँ: {{keys}}",
  "action.fieldsLead": "फ़ील्ड: {{keys}}।",
  "soul.system": "आप production soul.md लिखते हैं। केवल पूरा मार्कडाउन। spokenLanguages का सम्मान। इंटरफ़ेस भाषा।",
  "soul.improveMode": "सुधार मोड: प्रोफ़ाइल + मौजूदा soul मिलाकर पूरा soul.md दें।",
  "soul.createMode": "इस प्रोफ़ाइल से पूरा soul.md लिखें (दूसरा व्यक्ति न बनाएँ):",
  "soul.profileFields": "प्रोफ़ाइल फ़ील्ड:",
  "soul.existing": "मौजूदा soul.md (मिलाएँ; उपयोगी विस्तार न फेंकें):",
  "soul.userRequest": "अनुरोध: {{request}}",
  "soul.extraContext": "अतिरिक्त संदर्भ (लाभ हो तो; प्रोफ़ाइल जीते):",
  "soul.returnOnly": "केवल soul.md मार्कडाउन लौटाएँ।",
  "wardrobe.system": "आप कॉस्ट्यूम सलाहकार हैं। एक JSON। artStyle इनमें से: {{styleIds}}। ठोस कपड़ा/सिल्हूट। नाबालिग का यौनीकरण वर्जित।",
  "wardrobe.improveMode": "सुधार / सुझाव: नीचे के सभी फ़ील्ड और कथानक इस्तेमाल करें।",
  "wardrobe.characterForm": "पात्र (पूरा फ़ॉर्म):",
  "wardrobe.soulExcerpt": "soul.md अंश:\n{{soul}}",
  "wardrobe.userRequest": "अनुरोध: {{request}}",
  "wardrobe.storyContext": "निर्माण संदर्भ (हो तो उपयोग; दूसरा संसार न बनाएँ):",
  "wardrobe.style": "शैली: {{style}}",
  "wardrobe.segment": "चयनित खंड: {{label}}",
  "wardrobe.sceneContext": "दृश्य / बीट:",
  "wardrobe.noScenes": "(अभी दृश्य नहीं)",
  "wardrobe.proposeNew": "कथानक से मेल खाता नया लुक दें (डुप्लिकेट नहीं)।",
  "fill.system": "खाली फ़ील्ड भरें। ठीक इन कुंजियों का JSON: {{keys}}। प्रत्येक मान गैर-खाली स्ट्रिंग। ऐरे नहीं।",
  "fill.userPartial": "आंशिक प्रोफ़ाइल (विरोध न करें):",
  "fill.userOnly": "केवल ये कुंजियाँ भरें: {{keys}}।",
  "fill.userReturn": "केवल उन्हीं कुंजियों का JSON; मान खाली न हों।",
  "imageGen.multiRef": "{{n}} और स्टिल: पहला आधार है; सभी में पहचान एक जैसी रखें।",
  "residual.sceneLink": "दृश्य {{n}}: {{short}}",
  "residual.beatSegment": "बीट {{n}} · {{who}}{{tail}}",
  "residual.unknown": "अज्ञात",
  "residual.story": "कहानी",
  "beat.mood": "[MOOD] {{text}}",
  "beat.atmo": "[ATMO] {{text}}",
  "beat.camera": "[CAMERA] {{text}}",
  "beat.sfx": "[SFX] {{text}}",
  "beat.action": "[ACTION] {{text}}",
  "beat.actionWho": "[ACTION|{{who}}] {{text}}",
  "beat.expr": "[EXPR] {{text}}",
  "beat.exprWho": "[EXPR|{{who}}] {{text}}",
  "beat.dialogue": "[DIALOGUE|{{who}}] {{body}}",
  "beat.dialogueTone": "[DIALOGUE|{{who}}|{{tone}}] {{body}}",
  "beat.whoUnknown": "?",
  "beat.template": "[MOOD] tense, hesitant\n[ATMO] door-gap warm light; rain on ground\n[CAMERA] medium shot, push to hands\n[SFX] rain, fabric rustle\n[ACTION|Name] removes helmet; stares at the door light; hand into jacket pocket\n[EXPR|Name] furrowed brow, breath catches\n[DIALOGUE|Name|low, hoarse] Raining again…\n[DIALOGUE|Name|aside] (beat) Are you… still there?",
  "vision.preamble": "संदर्भ स्टिल लगा है। इस {{what}} के सभी फ़ील्ड मुख्यतः चित्र से भरें।",
  "vision.character": "पहचान (नाम, रूप, पोशाक, उम्र, लिंग, टैग)",
  "vision.scene": "स्थान (शीर्षक, वर्णन, रोशनी, मूड, सेट, टैग)",
  "vision.prop": "प्रॉप (नाम, वर्णन, सामग्री, आकार, स्थिति, टैग)",
  "vision.action": "क्रिया (नाम, वर्णन, लय, इरादा, कैमरा, टैग)",
  "vision.costume": "पोशाक (नाम, पूरा वर्णन)",
  "still.header": "वीडियो निरंतरता के लिए एक कीफ़्रेम स्टिल (मल्टी-पैनल बोर्ड नहीं)। नियोजित शॉट से मेल खाता हीरो फ़्रेम। बिना पाठ, लोगो, वॉटरमार्क, UI।",
  "still.revision": "इस स्टिल के लिए उपयोगकर्ता सुधार (अनिवार्य): {{notes}}",
  "still.regenTask": "कार्य: चित्र-से-वीडियो निर्देशक प्रॉम्प्ट संशोधित करें और कीफ़्रेम ब्रीफ़ के रूप में रखें।",
  "still.userImprove": "सुधार अनुरोध:\n{{notes}}",
  "still.currentPrompt": "वर्तमान पेशेवर प्रॉम्प्ट:",
  "still.hardRules": "कठोर नियम (अंत में रखें; कमज़ोर न करें):",
  "mediaGen.writeOne": "शॉर्ट-ड्रामा स्टिल के लिए एक अंतिम इमेज प्रॉम्प्ट लिखें।",
  "mediaGen.returnOnly": "केवल प्रॉम्प्ट पाठ — मार्कडाउन नहीं।",
  "mediaGen.singleComposite": "एक ही संयुक्त छवि का वर्णन।",
  "mediaGen.lockRefs": "संलग्न चित्र Ref# क्रम में सत्य हैं। दूसरा व्यक्ति/दुकान/वस्तु न बनाएँ।",
  "mediaGen.videoSystem": "आप चित्र-से-वीडियो निर्देशक प्रॉम्प्ट लिखते हैं।",
  "mediaGen.videoMerge": "सामग्री को एक वीडियो प्रॉम्प्ट में मिलाएँ।",
  "mediaGen.videoInclude": "शामिल करें: पहचान लॉक, कैमरा, अभिनय/संवाद, लय, रोशनी।",
  "mediaGen.videoFacts": "केवल सामग्री और seed के तथ्य। Demo नहीं।",
  "mediaGen.videoNoSwap": "रेफ़ हों तो अभिनेता, स्थान या प्रॉप न बदलें।",
  "mediaGen.videoHardRules": "कठोर नियम हों तो अंत में।",
  "mediaGen.imageSystem": "आप इमेज प्रॉम्प्ट निर्देशक हैं।",
  "mediaGen.imageMergeStills": "चयनित सामग्री और स्टिल को एक इमेज प्रॉम्प्ट बनाएँ।",
  "mediaGen.imageMergeText": "चयनित पाठ को एक इमेज प्रॉम्प्ट बनाएँ।",
  "mediaGen.imagePriority": "सर्वोच्च: चित्रों के चेहरे/पोशाक/स्थान/प्रॉप।",
  "mediaGen.imageNoSwap": "कास्ट स्टिल हों तो कोई और सेलिब्रिटी या सेट न लगाएँ।",
  "mediaGen.imageFacts": "केवल सामग्री और seed के तथ्य।",
  "mediaGen.imageLayout": "मल्टी-पैनल हो तो सही पैनल संख्या रखें।",
  "mediaGen.imagePackage": "LAYOUT हो तो वही लेआउट सख्ती से लागू करें।",
  "mediaGen.imageHardRules": "कठोर नियम हों तो अंत में।",
  "mediaGen.directorFallback": "चित्र-से-वीडियो: इस कीफ़्रेम को चलाएँ। पहचान, पोशाक, सेट, फ़्रेमिंग लॉक।",
  "mediaGen.directorFallbackCam": "कैमरा और अभिनय स्पष्ट; कैप्शन/वॉटरमार्क नहीं।",
  "charIntro.task": "चित्र-से-वीडियो: उसी व्यक्ति का छोटा आत्म-परिचय।",
  "charIntro.identityLock": "पहचान लॉक: वही चेहरा, बाल, शरीर, उम्र, पोशाक, रंग।",
  "charIntro.personality": "स्वभाव: {{personality}}।",
  "charIntro.backstory": "पृष्ठभूमि: {{backstory}}।",
  "charIntro.relationships": "संबंध: {{relationships}}।",
  "charIntro.soul": "Soul अंश (अभिनय स्रोत): {{soul}}",
  "charIntro.performance": "अभिनय: हल्की पुश-इन या हैंडहेल्ड; कैमरा देखें; {{manner}}।",
  "charIntro.speech": "बोल: मुँह छोटे परिचय जैसा हिले; आवाज़: {{voice}}।",
  "charIntro.beat": "स्वाभाविक स्थिर → मुस्कान/सिर हिलाना → छोटा इशारा → hold।",
  "charIntro.lighting": "स्टिल जैसी रोशनी; पाठ, लोगो, अतिरिक्त लोग नहीं।",
  "sceneIntro.task": "चित्र-से-वीडियो: उसी स्थान का स्थापना क्लिप।",
  "sceneIntro.spaceLock": "स्थान लॉक: वही वास्तुकला, सामग्री, साइन, लेआउट, रंग।",
  "sceneIntro.name": "स्थान नाम: {{name}}।",
  "sceneIntro.place": "वर्णन: {{place}}।",
  "sceneIntro.spaceType": "स्थान प्रकार: {{type}}।",
  "sceneIntro.time": "समय: {{time}}।",
  "sceneIntro.weather": "मौसम: {{weather}}।",
  "sceneIntro.moodLight": "मूड: {{mood}}। रोशनी: {{lighting}}।",
  "sceneIntro.palette": "पैलेट: {{palette}}।",
  "sceneIntro.setDressing": "सेट: {{set}}।",
  "sceneIntro.tags": "विज़ुअल टैग: {{tags}}।",
  "sceneIntro.art": "शैली: {{art}}।",
  "sceneIntro.ambient": "माहौल (UI पाठ नहीं): {{sound}}।",
  "sceneIntro.scriptCue": "बीट संकेत (केवल माहौल): {{cue}}।",
  "sceneIntro.camera": "कैमरा: {{camera}}; सतत गति। सामग्री में न हों तो नए चेहरे, लोगो या पाठ न जोड़ें।",
  "sceneIntro.beat": "स्थापना → सूक्ष्म पर्यावरण जीवन → hold।",
  "propIntro.task": "चित्र-से-वीडियो: उसी प्रॉप का हीरो परिचय।",
  "propIntro.objectLock": "वस्तु लॉक: वही सिल्हूट, सामग्री, रंग, नक्काशी, घिसाव।",
  "propIntro.name": "नाम: {{name}}।",
  "propIntro.look": "रूप: {{look}}।",
  "propIntro.material": "सामग्री: {{material}}।",
  "propIntro.size": "आकार: {{size}}।",
  "propIntro.condition": "स्थिति: {{condition}}।",
  "propIntro.tags": "टैग: {{tags}}।",
  "propIntro.art": "शैली: {{art}}।",
  "propIntro.camera": "साफ़ मेज़ पर हल्की परिक्रमा या धीमी पुश-इन।",
  "propIntro.beat": "Hold → चमक / सूक्ष्म घुमाव → hold।",
  "propIntro.noHands": "स्टिल में न हों तो हाथ/चेहरे नहीं; पाठ/अतिरिक्त प्रॉप नहीं।",
  "costumeIntro.task": "चित्र-से-वीडियो: उसी लुक का कॉस्ट्यूम परिचय।",
  "costumeIntro.wardrobeLock": "पोशाक लॉक: वही सिल्हूट, कपड़ा, रंग, परतें, सहायक।",
  "costumeIntro.identityOrProduct": "व्यक्ति हो तो चेहरा/शरीर लॉक; मैनक्विन/फ़्लैट-ले तो उत्पाद फ़्रेम।",
  "costumeIntro.name": "लुक नाम: {{name}}।",
  "costumeIntro.desc": "पोशाक: {{look}}।",
  "costumeIntro.art": "शैली: {{art}}।",
  "costumeIntro.camera": "हल्की पुश-इन या परिक्रमा; स्टिल जैसी फ़ैशन रोशनी।",
  "costumeIntro.beat": "Hold → कपड़े की लटकन / हार्डवेयर चमक → hold।",
  "costumeIntro.forbid": "नए चेहरे, पाठ, लोगो, कामुक पोज़ नहीं।",
  "costumeIntro.fallbackName": "लुक",
  "actionIntro.lead": "क्रिया डेमो «{{name}}».",
  "actionIntro.intention": "इरादा: {{intention}}",
  "actionIntro.body": "शरीर/लय: {{body}}",
  "actionIntro.camera": "कैमरा: {{camera}}",
  "actionIntro.closing": "धाराप्रवाह गति, बिना पाठ; कीफ़्रेम का पालन।",
  "sceneIntroPolish.task": "कार्य: स्थान परिचय (चित्र-से-वीडियो)।",
  "sceneIntroPolish.hasRef": "स्थान स्टिल लगा — स्थान पहचान लॉक।",
  "sceneIntroPolish.noRef": "स्टिल नहीं; स्थान बाइबल पर लॉक।",
  "sceneIntroPolish.dossier": "स्थान फ़ाइल:",
  "sceneIntroPolish.scriptCue": "स्क्रिप्ट संकेत (केवल माहौल):\n{{script}}",
  "sceneIntroPolish.emptySet": "खाली सेट; नए चेहरे नहीं। पाठ/लोगो नहीं।",
  "propIntroPolish.task": "कार्य: प्रॉप हीरो परिचय (चित्र-से-वीडियो)।",
  "propIntroPolish.hasRef": "प्रॉप स्टिल लगा — वस्तु पहचान लॉक।",
  "propIntroPolish.noRef": "स्टिल नहीं; प्रॉप फ़ाइल पर लॉक।",
  "propIntroPolish.dossier": "प्रॉप फ़ाइल:",
  "propIntroPolish.noHands": "नए हाथ/चेहरे नहीं। पाठ/लोगो नहीं।",
  "costumeIntroPolish.task": "कार्य: पोशाक परिचय (चित्र-से-वीडियो)।",
  "costumeIntroPolish.hasRef": "स्टिल लगा — व्यक्ति: पहचान+पोशाक; मैनक्विन: सिल्हूट और सामग्री।",
  "costumeIntroPolish.noRef": "स्टिल नहीं; वर्णन पर लॉक।",
  "costumeIntroPolish.dossier": "पोशाक फ़ाइल:",
  "costumeIntroPolish.fabric": "हल्की लटकन; नए चेहरे/पाठ नहीं।",
  "actionIntroPolish.task": "कार्य: गति-गाइड परिचय (चित्र-से-वीडियो)।",
  "actionIntroPolish.hasRef": "स्टिल लगा — अभिनय पहचान उस फ़्रेम पर लॉक।",
  "actionIntroPolish.templateKeepRules": "टेम्पलेट ड्राफ्ट (निखारें; कठोर नियम अंत में):",
  "cover.posterLead": "पेशेवर शॉर्ट-ड्रामा पोस्टर / KEY ART 16:9। UI मॉकअप नहीं। पाठ/लोगो/वॉटरमार्क नहीं।",
  "cover.titleMood": "शीर्षक (केवल मूड, चित्र पर अक्षर न लिखें): {{title}}।",
  "cover.styleBible": "शैली बाइबल: {{style}}",
  "cover.extraDir": "अतिरिक्त दिशा: {{idea}}",
  "cover.establishing": "पुस्तकालय कवर जैसा स्थापना मूड फ़्रेम।",
  "cover.medium": "माध्यम का पालन; मज़बूत सिल्हूट।",
  "cover.editPrefix": "IMAGE EDIT: नया पोस्टर कंपोज़िशन। पहचान/मूड रखें। ",
  "cover.label": "कहानी कवर",
  "costumeFill.system": "आप फ़िल्म वॉर्डरोब डिज़ाइनर हैं। केवल संक्षिप्त JSON। चित्र हो तो उसी पोशाक का ईमानदार वर्णन।",
  "costumeFill.idea": "विचार: {{idea}}",
  "costumeFill.polish": "पोशाक ड्राफ्ट निखारें।",
  "costumeFill.required": "कुंजियाँ: name, description, artStyle, hardRules। कमी = अमान्य।",
  "costumeFill.fallbackName": "लुक",
  "segment.entireStory": "पूरी कहानी (सभी दृश्य)",
  "segment.noStory": "कहानी नहीं चुनी (केवल पात्र विवरण)",
  "vision.inventFromImage": "संलग्न फ़ोटो से इस {{kind}} की पूरी प्रोफ़ाइल भरें।",
  "vision.polishAll": "सभी फ़ील्ड निखारकर मिलाएँ",
  "story.untitled": "बिना शीर्षक का शॉर्ट ड्रामा",
  "action.castIdentityNote": "पहचान स्टिल ({{count}}): हर पैनल में चेहरा/शरीर संलग्न कास्ट से मेल खाए।",
  "tpl.system.polishOnly": "रेसिपी केवल पॉलिश: पहचान और संसार बनाए रखें। शब्द निखारें। युग, मौसम, पेशा, स्थान या नमूना संसार न गढ़ें। बोली भाषा न गढ़ें। डिफ़ॉल्ट कठोर नियम प्रोफ़ाइल में न लिखें।",
  "tpl.system.fillBlanks": "रेसिपी केवल खाली: केवल खाली कुंजियाँ भरें। भरी फ़ील्ड न बदलें। नया संसार न गढ़ें।",
  "tpl.system.invent": "रेसिपी आविष्कार: उपयोगकर्ता ने स्वतंत्र रचना दी। हर फ़िल्माई कुंजी पूरी करें। Demo या इस अनुरोध से बाहर संसार न लाएँ।",
  "tpl.system.fromStory": "रेसिपी कहानी से: केवल इसी अनुरोध का शीर्षक/शैली/कास्ट/दृश्य continuity के लिए। टकराव में उपयोगकर्ता idea जीते।",
  "tpl.system.followAsset": "रेसिपी संपत्ति के अनुसार: दी गई शैली अपनाएँ। सामग्री न कहे तो सिनेमाई लुक, खाली सेट, 6–10 सेकंड न थोपें। अवधि क्लिप की असली सेकंड।",
  "tpl.system.cinematicLock": "रेसिपी सिनेमा+भ्रम-रोध: सिनेमाई लुक; खाली सेट; वॉटरमार्क/लोगो/अतिरिक्त चेहरे नहीं; दो हाथ/बाँह/टाँग जब तक गैर-मानव न हो।",
  "tpl.system.identityLock": "रेसिपी पहचान ताला: चेहरा/शरीर/पोशाक/स्थान/प्रॉप स्टिल पर ताला। दूसरा व्यक्ति/स्थान/वस्तु न बदलें।",
  "tpl.system.restyle": "रेसिपी restyle: वही व्यक्ति। पोशाक, सेट, युग उपयोगकर्ता कहे तो बदल सकते हैं। दूसरा व्यक्ति नहीं।",
  "pipeline.character.system": "आप पात्र बाइबल निखारते हैं। प्रत्येक 3–5 पंक्तियाँ: रूप, आवाज़, प्रेरणा, इशारा। केवल इस अनुरोध के तथ्य।",
  "pipeline.scene.system": "दृश्यों को दृश्य बीट शीट में फैलाएँ। वास्तविक अवधि; 6–10 सेकंड न मानें। केवल दिए दृश्य।",
  "pipeline.props.system": "प्रॉप निरंतरता निखारें। रंग, आकार, कब आए। सूची से बाहर प्रॉप न गढ़ें।",
  "pipeline.script.system": "आप पटकथा लेखक हैं। प्रत्येक दृश्य के लिए संक्षिप्त स्क्रीनप्ले। वास्तविक अवधि; 10 सेकंड न थोपें। प्रारूप:\n### SCENE <number> | id=<id>\n<script body>",
  "pipeline.script.noScenes": "(कोई दृश्य नहीं — स्थान न गढ़ें)"
}