import type { PromptCopyTable } from './keys'

export const jaPromptCopy: PromptCopyTable = {
  "speechLock.named": "台詞ロック · キャラクター「{{who}}」：聞こえる音声と口の動きは必ず{{primaryName}}（{{primary}}）のみ。{{forbid}}や他言語に切り替えるな。クリップごとに言語を変えるな。台詞を翻訳するな。",
  "speechLock.unnamed": "台詞ロック · 出演キャラクター：聞こえる音声と口の動きは必ず{{primaryName}}（{{primary}}）のみ。{{forbid}}や他言語に切り替えるな。クリップごとに言語を変えるな。台詞を翻訳するな。",
  "speechLock.namedMulti": "台詞ロック · キャラクター「{{who}}」：聞こえる音声と口の動きは必ず{{primaryName}}（{{primary}}）。台本のその行が既にその言語である場合のみ第二言語を許可：{{extras}}。第三言語は禁止。クリップ間で切り替えるな。{{forbid}}へ変えるな。台詞を翻訳するな。",
  "speechLock.unnamedMulti": "台詞ロック · 出演キャラクター：聞こえる音声と口の動きは必ず{{primaryName}}（{{primary}}）。台本のその行が既にその言語である場合のみ第二言語を許可：{{extras}}。第三言語は禁止。クリップ間で切り替えるな。{{forbid}}へ変えるな。台詞を翻訳するな。",
  "hardRules.sealHeader": "生成の鉄則（最優先。必ず守る。前文と矛盾したらこちらを優先）：",
  "hardRules.sealFooter": "前文が生成の鉄則と矛盾する場合は、生成の鉄則に従う。",
  "hardRules.labelStory": "物語",
  "hardRules.labelCharacter": "キャラクター",
  "hardRules.labelScene": "場所",
  "hardRules.labelProp": "小道具",
  "hardRules.labelAction": "アクション",
  "continuity.lockHeader": "画面連続ロック（短編の順序を必ず守れ）：",
  "continuity.hasImage": "添付は第{{n}}段の終了フレーム／キーフレーム。このショットはその画面状態から続ける。別セットへハードカットするな。",
  "continuity.noImage": "第{{n}}段から続ける（静止画なし——文字資料のみ合わせる）。",
  "continuity.identity": "身元：同一人物——顔・髪・体型・衣装色・小物。リスタイルや年齢変更をするな。",
  "continuity.space": "空間：同じ場所——建築・素材・間取り・光の向き。劇が求めるときだけわずかな時間変化可。",
  "continuity.action": "動作：前フレームの姿勢・視線・動きを引き継げ。別の立ち位置へ切るな。",
  "continuity.prevContext": "前段の文脈：{{snippet}}",
  "continuity.noText": "字幕・ロゴ・透かしなし。",
  "directorLabel.lock": "台詞ロック",
  "directorLabel.story": "物語：",
  "directorLabel.style": "作風：",
  "directorLabel.cast": "出演：",
  "directorLabel.location": "場所：",
  "directorLabel.prop": "小道具：",
  "directorLabel.primaryChar": "主役：",
  "directorLabel.mood": "心情：",
  "directorLabel.atmo": "雰囲気：",
  "directorLabel.camera": "カメラ：",
  "directorLabel.sfx": "効果音：",
  "directorLabel.action": "動作：",
  "directorLabel.expr": "表情：",
  "directorLabel.speech": "台詞：",
  "directorLabel.notes": "演出メモ：",
  "directorLabel.identity": "身元：",
  "directorLabel.space": "空間：",
  "directorLabel.ref": "参考図",
  "directorLabel.beatN": "第{{n}}段 · ",
  "directorLabel.beatNsec": "第{{n}}段 · {{s}}秒",
  "directorLabel.hardRules": "生成の鉄則",
  "directorLabel.identityLock": "身元ロック",
  "directorLabel.spaceLock": "空間ロック",
  "storyBeats.system": "あなたはAI動画用の短編ドラマ「タイムライン・ビート」を書く。\n各ビート＝短いクリップ一本分の撮影脚本（一言の台詞ではない）。\n心情・雰囲気・動作・表情・任意のカメラ／効果音、0〜複数の台詞（よく1–4）を必ず含める。\nJSON配列だけを返す（フェンス禁止）。各要素の形：\n{\"characterName\":\"…\",\"characterNames\":[\"…\"],\"sceneHint\":\"…\",\"sceneHints\":[\"…\"],\"propName\":\"…\",\"propNames\":[\"…\"],\"actionName\":\"…\",\"actionNames\":[\"…\"],\"mood\":\"…\",\"atmosphere\":\"…\",\"camera\":\"…\",\"sfx\":\"…\",\"units\":[{\"type\":\"action\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"expression\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"dialogue\",\"who\":\"…\",\"line\":\"…\",\"tone\":\"…\",\"parenthetical\":\"…\"},{\"type\":\"note\",\"text\":\"…\"}]}\n規則：\n- dialogue.line は口に出す言葉だけ。ト書きを混ぜない。\n- 身体動作は action、表情は expression、言い方は tone／parenthetical。\n- 短い会話や独白では複数の dialogue を勧める。\n- 台詞なしの動作ビートも可。\n- 章とビートを1対1にしない。撮れるクリップで分割：場所変更・時間飛び・新しい対立、または6–10秒に収まらない動作／台詞 → 新しいビート。各章は通常1–3本。合計は最大 {{maxBeats}} 本。\n- このクリップに出る名簿上のキャラ／場所／小道具／動作をすべて列挙（characterNames、sceneHints、propNames、actionNames）。上限：キャラ4、場所2、小道具4、動作4。各1つだけにしない。\n- 身体演技があるなら actionNames は必須。物語で既に選んだ動作ライブラリの原名を使う。演技があるのに空は禁止。空よりリストから選ぶ。\n- 各ビート units は最大4（action 1–2、expression 0–1、dialogue 0–2）。短く一度で返す。キャスト名は提供リストのみ。\n- 対立・見える動作・撮れる細部。\n- タイトル・作風・キャスト・場面に忠実。勝手に世界を広げるな。\n- 台詞はキャスト表の主言語で書く。ビートごとに言語を変えない。指定以外へ翻訳しない。",
  "storyBeats.userLead": "以下のキャスト・場面・小道具・動作・作風・指示をすべて使い、短いクリップ脚本ビートを生成せよ。",
  "storyBeats.eachBeat": "各ビートに心情・雰囲気・動作／表情、任意の複数台詞が必要。",
  "storyBeats.story": "物語：{{title}}",
  "storyBeats.style": "作風：{{style}}",
  "storyBeats.userDir": "ユーザー指示：{{idea}}",
  "storyBeats.cast": "キャスト：",
  "storyBeats.scenes": "場面：",
  "storyBeats.props": "小道具：{{props}}",
  "storyBeats.actions": "動作（身体）：{{actions}}",
  "storyBeats.returnJson": "ビートのJSON配列だけを返せ。",
  "storyBeats.noCast": "（キャストなし）",
  "storyBeats.noScenes": "（場面なし — sceneHint に場所を書いてよい。別世界を作るな）",
  "storyBeats.none": "（なし）",
  "storyBeats.chapters": "物語の章（撮影ビートに分解する主ソース）：",
  "storyBeats.chapterBlock": "第{{n}}章 · {{title}}\n{{body}}",
  "storyChapters.system": "短編ドラマの「章」を書く。物語の魂であり、クリップ脚本ではない。\n各章は約{{words}}字の散文：対立、場所、誰がいるか、何を望むか、何が変わるか。\nJSON配列のみ返す。各要素 {\"title\":\"…\",\"body\":\"…\"}.\n必ず{{count}}章。タイトル・作風・鉄則・アイデアに忠実。別世界を作らない。短く一度で返す。",
  "storyChapters.userLead": "物語を順序ある章として書く。後でキャラ・場所・小道具・動作を生成し、撮影ビートに分解する。",
  "storyChapters.story": "物語：{{title}}",
  "storyChapters.style": "作風：{{style}}",
  "storyChapters.rules": "生成鉄則：{{rules}}",
  "storyChapters.userDir": "アイデア：{{idea}}",
  "storyChapters.returnJson": "JSON配列のみ：[{\"title\":\"…\",\"body\":\"…\"}, …]",
  "storyChapters.polishSystem": "短編の「一章」を磨く。事実・名前・結末は保ち、より撮れる文章にする。JSONのみ {\"title\":\"…\",\"body\":\"…\"}。",
  "storyChapters.polishUser": "物語：{{story}}\n現在の題：{{title}}\n本文：\n{{body}}\n指示：{{idea}}\nJSON {\"title\",\"body\"} を返す。",
  "storyCastFromChapters.system": "章から制作バイブルを抽出：キャラ、場所、小道具、動作。\nJSONのみ。章に出るものだけ。既存名は再利用。視覚は具体的に。章ごとにキャラ／場所／小道具／動作を1つずつ出さない。1章に人物2人・場所複数・小道具／動作多数があり得る。実際に出る区別できるものだけ。会話2人→characters2、路地から祠→scenes2。枠埋めの捏造禁止。",
  "storyCastFromChapters.userLead": "章に出るすべての区別できるキャラ・場所・小道具・動作を抽出。章ごとに1つずつにしない。",
  "storyCastFromChapters.story": "物語：{{title}}",
  "storyCastFromChapters.style": "作風：{{style}}",
  "storyCastFromChapters.chapters": "章：\n{{chapters}}",
  "storyCastFromChapters.existingCast": "この物語に既にある（これらの名を使う）：{{names}}",
  "storyCastFromChapters.returnJson": "JSONオブジェクトのみ返す。",
  "videoPolish.system": "短編ドラマ用AIの 画像から動画 向けに、最終演出プロンプトを一条だけ書く。\nプロンプト本文だけを返す。markdownフェンス・見出し・解説は禁止。\n規則：\n- 演出文はユーザー界面言語。キャラ名と台詞言語の指定は明確に。\n- 人物スチール：身元ロック。場所プレート：空間ロック。材料が指名しない新しい顔を足すな。\n- 見た目・動き・台詞・雰囲気に効く資料はすべて使え。空欄は略してよい。\n- 材料とseedだけで撮れる細部を補う。固定サンプル世界やDemo事実を持ち込むな。\n- 長い soul.md は演技と身元の要点に圧縮し、全文貼るな。\n- 尺は材料の実秒数。動作は連続。字幕・ロゴ・透かし・無関係な通行人なし。\n- 脚本が求めない限り人体は正常（両手両足）。\n- 複数キャラは各自を一貫。主焦点を先に。\n- 生成の鉄則 があれば残し、出力の末尾へ（最優先）。\n- 台詞ロック は必須。削除・改変・翻訳するな。言語コードはフルネームに。主言語を守れ。クリップ間で言語を変えるな。\n- 演出修正は雰囲気／動作のみ。生成の鉄則 を破るな。",
  "videoPolish.hardRulesKeep": "生成の鉄則（最優先——各行を残せ。[キャラクター · 名] などのラベルを消すな）。完全な生成の鉄則ブロックを出力の末尾に置け。弱めたり付け替えたりするな。",
  "clip.task": "任務：短編ドラマのタイムライン・クリップ（画像から動画）。",
  "clip.hasRef": "参照スチールが付く場合あり——関係するなら身元／場所の連続性をロック。",
  "clip.characters": "キャラクター：",
  "clip.scene": "場面：",
  "clip.prop": "小道具：",
  "clip.action": "動作ガイド：",
  "clip.beat": "ビート／台詞：",
  "clip.prev": "前クリップの連続性：",
  "clip.revision": "演出修正（必ず従え）：",
  "clip.templateDraft": "テンプレ草案（改善せよ）：",
  "intro.task": "任務：自己紹介のキャスティング短編（画像から動画）。",
  "intro.hasRef": "参照スチールは動画APIへ渡す——その画像の身元にロックせよ。",
  "intro.noRef": "本文にスチール経路はない。それでもプロフィールの外見／衣装にロック。",
  "intro.dossier": "キャラクター資料：",
  "intro.templateDraft": "テンプレ草案（改善せよ。資料を無視するな）：",
  "common.durationAspect": "尺：{{seconds}}秒。画角：{{aspect}}。",
  "common.templateDraft": "テンプレ草案：",
  "improve.mode": "改善モード：以下の全ソースを統合して完全な結果を出せ。ユーザーが身元変更を明示しない限り核は保て。",
  "improve.draftDefault": "現在のフォーム欄（入力済み）：",
  "improve.userRequest": "ユーザー改善要求（空＝すべて磨いて統合）：",
  "improve.emptyDefault": "（短編ドラマ continuity のため全欄を磨く）",
  "improve.createDefault": "構想／方向：",
  "improve.explicitContext": "本リクエストに明示された文脈のみ（continuity 用。他のサンプル世界を持ち込むな）：",
  "improve.storyTitle": "物語タイトル：{{title}}",
  "improve.styleNote": "作風メモ：{{style}}",
  "improve.closingDefault": "完全な結果を今すぐ出力せよ。",
  "storyMeta.system": "あなたは短編ドラマのショーランナー。タイトルと構想から視覚スタイル聖書と生成鉄則を書け。JSONのみ返せ。",
  "storyMeta.draftLabel": "現在の物語フィールド：",
  "storyMeta.createLabel": "物語の構想／タイトル：",
  "storyMeta.emptyPolish": "（視覚スタイルと鉄則を磨く）",
  "storyMeta.closing": "JSONのみ：{\"styleNote\":\"…\",\"hardRules\":\"…\"}。両キー必須。",
  "storyMeta.contextLabel": "物語コンテキスト（キャスト／場面／小道具）：",
  "character.system": "あなたはAI動画向けの短編ドラマ・キャラクター設定者。ideaに従い完全なキャラ聖書をJSONだけで出せ。spokenLanguagesはBCP-47配列。",
  "character.draftLabel": "現在のプロフィール欄：",
  "character.soulLabel": "リンク済み soul.md／キャラ聖書：",
  "character.createLabel": "キャラクター idea：",
  "character.emptyPolish": "（soulとフォームを統合して磨く）",
  "character.closing": "完全なJSONを今すぐ。必須キー：{{keys}}。",
  "scene.system": "あなたは短編ドラマの場所／場面デザイナー。撮れる場所聖書＋本場の脚本断片をJSONだけで出せ。",
  "scene.draftLabel": "現在の場面フォーム：",
  "scene.charsLabel": "物語のキャラ：",
  "scene.propsLabel": "物語の小道具：",
  "scene.priorLabel": "既存場面（continuity）：",
  "scene.createLabel": "場面 idea：",
  "scene.emptyPolish": "（場所と脚本を磨く）",
  "scene.closing": "完全なJSONを今すぐ。必須キー：{{keys}}。",
  "prop.system": "あなたは短編ドラマの小道具デザイナー。JSONだけ返せ。見た目・材質・状態を具体的に。",
  "prop.draftLabel": "現在の小道具フォーム：",
  "prop.createLabel": "小道具 idea：",
  "prop.emptyPolish": "（小道具の見た目を磨く）",
  "prop.closing": "完全なJSONを今すぐ。必須キー：{{keys}}。",
  "prop.fallbackName": "小道具",
  "action.system": "あなたは短編ドラマの動作監督。有効なJSONだけ出せ。部位・テンポ・重量・経路を具体的に。",
  "action.storyContext": "物語脈絡（任意）：{{title}}",
  "action.styleNote": "作風メモ：{{style}}",
  "action.existingDraft": "既存ドラフト（磨いて補完）：",
  "action.userIdea": "ユーザー構想：{{idea}}",
  "action.closing": "JSONのみ。必須キー：{{keys}}。",
  "profile.mustEveryKey": "このリストの全キーを必ず出せ：{{keys}}。",
  "profile.valuesAreStrings": "各値はJSON文字列。nullや配列は不可。本当に不明なときだけ空文字。",
  "profile.visualTagsRule": "visualTagsは界面言語のカンマ区切り文字列。JSON配列は禁止。",
  "profile.fillConcrete": "短編ドラマ continuity のため具体的に埋めよ。",
  "common.rules": "規則：",
  "common.none": "（なし）",
  "intro.soul": "soul.md（演技／身元の完全な出典）：\n{{soul}}",
  "intro.matchBible": "（キャラ聖書の言語に合わせる）",
  "invent.sources": "根拠の優先順：（1）ユーザー構想／指示、（2）記入済みフォーム、（3）このプロンプトに書かれた追加文脈のみ、（4）添付参照画像。",
  "invent.create": "作成モード（空／薄いフォーム）：構想／画像から自由に創作し、必須キーを空にするな。",
  "invent.improve": "改善モード：下書きと一貫するよう磨き、欠欄を埋めよ。身元変更は明示されたときだけ。",
  "invent.noImport": "このプロンプトに無い身元・筋・天候・職業・場所・時代・作風を持ち込むな（active 物語、Demo、既定世界禁止）。",
  "invent.storyBlock": "物語／作風ブロックがある場合は continuity のみに使え。明示された構想を上書きするな。",
  "character.keysLead": "JSONオブジェクトのみ。キー：{{keys}}",
  "character.ruleSpoken": "spokenLanguages：話す言語の BCP-47 配列。無言なら []。",
  "character.ruleIdentity": "多角度シートと動画で身元を一貫させよ。",
  "scene.keysLead": "JSONオブジェクトのみ。キー：{{keys}}",
  "scene.suggestLead": "物語「{{title}}」の第{{n}}場として使える場所を提案せよ。",
  "scene.suggestPlotFocus": "筋の焦点：{{label}}",
  "scene.suggestStyle": "作風：{{style}}",
  "scene.suggestExisting": "既存の場所：{{titles}}",
  "scene.suggestChars": "キャラ（文脈）：",
  "scene.suggestProps": "小道具（文脈）：",
  "scene.suggestSegment": "選んだ筋の詳細：",
  "scene.suggestBeats": "物語の場／ビート：",
  "scene.suggestClosing": "完全な場面JSONを返せ。再利用できる独立した場所を設計せよ。",
  "scene.fallbackName": "場所",
  "scene.ideaFromImage": "添付写真から場所プロフィールを完全に埋めよ。",
  "scene.polishIdea": "磨く",
  "prop.keysLead": "JSONのみ。キー：{{keys}}",
  "action.fieldsLead": "欄：{{keys}}。",
  "soul.system": "短編ドラマ用 production soul.md を書け。完全なMarkdownのみ。見出しを守れ。spokenLanguages を尊重せよ。界面言語で書け。",
  "soul.improveMode": "改善モード：プロフィール＋既存soulを統合した完全な soul.md を出せ。",
  "soul.createMode": "このプロフィールから完全な soul.md を書け（別人にすり替えるな）：",
  "soul.profileFields": "プロフィール欄：",
  "soul.existing": "既存 soul.md（有用な細部を捨てるな）：",
  "soul.userRequest": "ユーザー指示：{{request}}",
  "soul.extraContext": "追加文脈（有用なら使え；プロフィール優先）：",
  "soul.returnOnly": "soul.md の本文だけ返せ。",
  "wardrobe.system": "短編ドラマの衣装顧問。JSON一つだけ。artStyle は {{styleIds}} のいずれか。具体的な素材・色・輪郭。未成年の性化禁止。",
  "wardrobe.improveMode": "改善／提案：下の全欄と筋を使え。",
  "wardrobe.characterForm": "キャラ（全フォーム）：",
  "wardrobe.soulExcerpt": "soul.md 抜粋：\n{{soul}}",
  "wardrobe.userRequest": "ユーザー指示：{{request}}",
  "wardrobe.storyContext": "物語／制作文脈（あれば使え；別世界を作るな）：",
  "wardrobe.style": "作風：{{style}}",
  "wardrobe.segment": "選んだ筋：{{label}}",
  "wardrobe.sceneContext": "場面／ビート抜粋：",
  "wardrobe.noScenes": "（場面はまだ無い）",
  "wardrobe.proposeNew": "筋に合う新しい衣装を提案（既存と重複させるな）。",
  "fill.system": "空欄だけ埋めよ。これらのキーだけのJSON：{{keys}}。各値は非空文字列。配列禁止。",
  "fill.userPartial": "既存の部分設定（矛盾させるな）：",
  "fill.userOnly": "これらの空キーだけ埋めよ：{{keys}}。",
  "fill.userReturn": "そのキーだけのJSON。各値は非空文字列。",
  "imageGen.multiRef": "追加参照が{{n}}枚。第一枚が編集ベース。身元を全参照と一致させよ。",
  "residual.sceneLink": "第{{n}}場：{{short}}",
  "residual.beatSegment": "ビート {{n}} · {{who}}{{tail}}",
  "residual.unknown": "未指定",
  "residual.story": "物語",
  "beat.mood": "【心情】 {{text}}",
  "beat.atmo": "【雰囲気】 {{text}}",
  "beat.camera": "【カメラ】 {{text}}",
  "beat.sfx": "【効果音】 {{text}}",
  "beat.action": "【動作】 {{text}}",
  "beat.actionWho": "【動作｜{{who}}】 {{text}}",
  "beat.expr": "【表情】 {{text}}",
  "beat.exprWho": "【表情｜{{who}}】 {{text}}",
  "beat.dialogue": "【台詞｜{{who}}】 {{body}}",
  "beat.dialogueTone": "【台詞｜{{who}}｜{{tone}}】 {{body}}",
  "beat.whoUnknown": "？",
  "beat.template": "【心情】緊張、ためらい\n【雰囲気】ドアの隙間の暖光；地面の雨\n【カメラ】ミディアム、手元へプッシュ\n【効果音】雨、布の擦れ\n【動作｜名前】ヘルメットを外す；ドアの光を見つめる；手を上着のポケットへ\n【表情｜名前】眉間に皺、息が止まる\n【台詞｜名前｜低く、かすれて】また雨か……\n【台詞｜名前｜傍白】（間）まだ、そこにいるのか？",
  "vision.preamble": "参照静止画が添付されている。この{{what}}の全欄を主に画像から埋めよ。構想／下書きで補ってよい。",
  "vision.character": "キャラ（名、外見、衣装、年齢、性別、タグ）",
  "vision.scene": "場所（題、説明、光、雰囲気、装置、タグ）",
  "vision.prop": "小道具（名、説明、材質、寸法、状態、タグ）",
  "vision.action": "動作（名、説明、テンポ、意図、カメラ、タグ）",
  "vision.costume": "衣装（名、完全な造形）",
  "still.header": "短編ドラマ用の単一キーフレーム静止画。計画ショットに合うヒーローフレーム。文字・ロゴ・透かし禁止。",
  "still.revision": "この静止画への改善要求（必須）：{{notes}}",
  "still.regenTask": "任務：画像から動画 監督プロンプトを改訂し、キーフレーム概要としても使えるようにせよ。",
  "still.userImprove": "ユーザー改善要求：\n{{notes}}",
  "still.currentPrompt": "現在の専門プロンプト：",
  "still.hardRules": "生成の鉄則（出力末尾に残せ。弱めるな）：",
  "mediaGen.writeOne": "短編ドラマ用の最終静止画プロンプトを「1本」書け。",
  "mediaGen.returnOnly": "プロンプト本文だけ。markdown禁止。",
  "mediaGen.singleComposite": "単一合成画像を記述せよ。",
  "mediaGen.lockRefs": "添付画像は Ref# 順の根拠。身元／衣装／場所／小道具をロック。別物に替えるな。",
  "mediaGen.videoSystem": "短編ドラマの画像から動画の監督プロンプト作者。本文一条だけ返す。尺は材料の実秒数。材料の事実だけを使う。カメラ範本ブロックがあればその構図と動きに従え。汎用のプッシュインや手持ちに戻すな。生成の鉄則があれば末尾へ。",
  "mediaGen.videoMerge": "材料を1本の専門ビデオプロンプトに統合せよ。",
  "mediaGen.videoInclude": "身元ロック、カメラ、演技／台詞、リズム、光の連続。",
  "mediaGen.videoFacts": "材料と seed の事実だけ。Demo 世界を持ち込むな。",
  "mediaGen.videoNoSwap": "参照があるとき別俳優／場所／小道具に替えるな。",
  "mediaGen.videoHardRules": "生成の鉄則 があれば末尾へ。",
  "mediaGen.imageSystem": "短編ドラマの静止画／マルチパネル用プロンプト監督。プロンプト本文だけを返す——フェンス・見出し・解説は禁止。材料の事実だけを使い、サンプル世界を持ち込むな。カメラ範本ブロックがあれば従え。汎用のプッシュインや手持ちに戻すな。生成の鉄則があれば末尾へ。",
  "mediaGen.imageMergeStills": "選んだ材料と添付静止画を1本の出図プロンプトにせよ。",
  "mediaGen.imageMergeText": "選んだテキスト材料を1本の出図プロンプトにせよ。",
  "mediaGen.imagePriority": "最優先：添付の顔／衣装／場所／小道具を一致させよ。",
  "mediaGen.imageNoSwap": "キャスト静止画があるとき無関係な人物や店に替えるな。",
  "mediaGen.imageFacts": "材料と seed の事実だけ。",
  "mediaGen.imageLayout": "多コマなら正確なコマ数と溝を保て。",
  "mediaGen.imagePackage": "LAYOUT があるならそのレイアウトを厳密に実行せよ。",
  "mediaGen.imageHardRules": "生成の鉄則 があれば末尾へ。",
  "mediaGen.directorFallback": "図生動画：このキーフレームから短編クリップを動かせ。身元・衣装・場所・構図をロック。",
  "comic.taskHint": "物語「{{title}}」漫画 {{n}} ページ：完成した漫画ページ1枚、コマはちょうど {{count}}。全ページで身元・衣装・場所を揃える。透かし・UI枠なし。",
  "comic.panelCount": "コマ数は固定：ちょうど {{n}} コマ。",
  "comic.lockSplash": "レイアウト固定：見開き1コマ。追加枠・分割・コラージュ禁止。",
  "comic.lockYonkoma": "レイアウト固定：縦4コマ、4行×1列、上から下。2×2や横帯は禁止。",
  "comic.lockGrid2x2": "レイアウト固定：2行×2列。横帯・2×3・全面1コマは禁止。",
  "comic.lockGrid2x3": "レイアウト固定：2行×3列。上段1-2-3、下段4-5-6。2×2や3×3は禁止。",
  "comic.lockGrid3x3": "レイアウト固定：3行×3列＝9コマ。2×2、2×3、それ未満は禁止。",
  "comic.lockStrip": "レイアウト固定：横1行ちょうど {{n}} コマ。複数行は禁止。",
  "comic.layoutSplash1": "縦長の漫画ページ1枚：全面1コマ。溝なし、余分な枠なし。",
  "comic.layoutStrip2": "横長の漫画ページ：横並び2コマ、太い白溝。",
  "comic.layoutStrip3": "横長の漫画ページ：1行3コマ、太い白溝。",
  "comic.layoutYonkoma": "縦長の漫画ページ：縦4コマ（4行×1列）、太い白溝、上から下へ読む。",
  "comic.layoutGrid2x2": "正方形の漫画ページ：2×2、ちょうど4コマ、太い白溝、左→右、上→下。",
  "comic.layoutStrip4": "広い横長ページ：1行4コマ、太い白溝。",
  "comic.layoutGrid2x3": "横長ページ：ちょうど6コマ、2行×3列（上1-2-3、下4-5-6）、太い白溝、左→右、上→下。",
  "comic.layoutGrid3x3": "正方形ページ：3×3、ちょうど9コマ、太い白溝、左→右、上→下。",
  "comic.layoutWidePlusTwo": "縦長の漫画ページ：上部約6割が全幅の大コマ、下部に横並び小コマ2つ。太い白溝。",
  "comic.layoutTwoPlusWide": "縦長ページ：上部に横並び小コマ2つ、下部約6割が全幅の締めコマ。太い白溝。",
  "comic.layoutTallLeftTwo": "縦長ページ：左半分は全高の縦コマ、右は上下2コマ。太い白溝。",
  "comic.layoutHeroPlusThree": "縦長ページ：上半分が全幅の大コマ、下は1行3つの小コマ。太い白溝。",
  "comic.layoutFocusQuad": "縦長ページ：左上に中コマ、右上に小コマ2つ縦積み、下半分に全幅の大コマ。太い白溝。",
  "comic.layoutStaggerFour": "縦長ページ：段違いの2+2。上段は広＋狭、下段は狭＋広。太い白溝。",
  "comic.layoutDiagPairPlus": "縦長ページ：上半分を斜め溝で楔形2コマ、下半分は全幅の横コマ。太い白溝。",
  "comic.layoutHeroPlusFour": "縦長ページ：上半分が全幅の大コマ、下半分は2×2の小コマ4つ。太い白溝。",
  "comic.lockWidePlusTwo": "レイアウト固定：上は全幅の大コマ。下は小コマ2つだけ。等分3コマ帯や2×2は禁止。",
  "comic.lockTwoPlusWide": "レイアウト固定：上は小コマ2つ。下は全幅の締め。等分3コマ帯や2×2は禁止。",
  "comic.lockTallLeftTwo": "レイアウト固定：左コマはページ全高。右は上下2コマ。等分2×2や横帯は禁止。",
  "comic.lockHeroPlusThree": "レイアウト固定：上半分は全幅の大コマ。下は1行ちょうど3つの小コマ。2×2や4等分は禁止。",
  "comic.lockFocusQuad": "レイアウト固定：左上中コマ、右上に小2つ縦積み、下半分に大コマ。等分2×2は禁止。",
  "comic.lockStaggerFour": "レイアウト固定：段違い。上は広＋狭、下は狭＋広。4つの等しい正方形は禁止。",
  "comic.lockDiagPairPlus": "レイアウト固定：上半分は斜め2楔、下半分は全幅1コマ。等分3帯や2×2は禁止。",
  "comic.lockHeroPlusFour": "レイアウト固定：上半分は全幅大コマ、下半分は2×2の4小コマ。ちょうど5コマ。3×3や全ページ2×2は禁止。",
  "comic.readingYonkoma": "読み順：上から下のみ（縦4コマ）。",
  "comic.readingWidePlusTwo": "読み順：上の大コマ、次に下の小コマを左から右。",
  "comic.readingTwoPlusWide": "読み順：上の2コマを左→右、次に下の全幅。",
  "comic.readingTallLeftTwo": "読み順：左の縦コマ、右上、右下。",
  "comic.readingHeroPlusThree": "読み順：上の大コマ、次に下の3小コマを左から右。",
  "comic.readingFocusQuad": "読み順：左上の中コマ、右上の小コマを上から下、最後に下の大コマ。",
  "comic.readingStaggerFour": "読み順：左上、右上、左下、右下。",
  "comic.readingDiagPairPlus": "読み順：左上の楔、右下の楔、下の全幅。",
  "comic.readingHeroPlusFour": "読み順：上の大コマ、次に下の4小コマを左→右・上→下。",
  "comic.readingOrder": "読み順：左→右、その後上→下（縦4コマは上→下のみ）。",
  "comic.panelNumbers": "各コマ左上に小さな番号 1〜{{n}}。",
  "comic.panelLine": "コマ {{i}}／{{n}}（{{label}}）：{{cap}}",
  "comic.panelEmpty": "コマ {{i}}／{{n}}（{{label}}）：連続する独立した物語の瞬間。",
  "comic.identity": "このページの全コマで身元・衣装・場所を揃える。",
  "comic.finished": "完成した漫画ページ。無関係な写真のコラージュやUI草稿ではない。",
  "comic.layoutLead": "レイアウト：{{layout}}",
  "comic.prevPage": "前のページ。身元・衣装・場所は連続させるが、前ページのコマ割りをコピーするな。",
  "comic.ownPage": "このページの既存画。改稿時は身元／レイアウトの下絵に使う。",
  "comic.galleryRef": "キャストまたは場所の身元静止画。顔・衣装・場所を合わせよ。",
  "comic.profileLine": "物語「{{title}}」漫画 {{n}} ページ。",
  "comic.styleBible": "物語の作風：{{note}}",
  "comic.artMedium": "画風：{{art}}",
  "comic.fallbackClose": "完成した印刷漫画ページ。太い白溝。小さなコマ番号。透かし・アプリUI・アルバム風コラージュなし。",
  "comic.hardRules": "生成の鉄則",
  "comic.introTask": "画像から動画：物語「{{title}}」{{n}}ページの完成漫画（コマちょうど{{count}}）を短編にする。身元・衣装・コマ割りは添付ページに固定。",
  "comic.introLock": "固定：顔・衣装・場所・溝・コマ番号は静止画と同じ。別ページや別人に差し替えない。",
  "comic.introLayout": "このページのコマ割りを保て：{{layout}}",
  "comic.introCamera": "カメラ：ゆっくり寄る、または読み順に軽く横へ動く。紙／印刷の微動のみ。別のコマ割りへのカットは禁止。",
  "comic.introClose": "透かし・UI枠なし。ページに描いてある台詞以外の字幕を重ねない。",
  "comic.dramaStillLock": "添付の漫画ページに身元・衣装・場所を固定するが、印刷コマをなぞるのではなく実写短編として演じよ。",
  "comic.dramaCamera": "カメラと演技：短編のリズム、はっきりした演技、コマ台詞に合わせた口パク。前ページの静止画があれば連続させる。",
  "comic.formatLockTall": "判型固定：ページ全体を縦9:16の漫画ページにせよ。横長ワイド構図は禁止。",
  "comic.formatLockSquare": "判型固定：ページ全体を正方形1:1の漫画ページにせよ。",
  "comic.formatLockWide": "判型固定：ページ全体を横16:9の漫画ページにせよ。",
  "art.photoCinematic": "必須媒体：実写フォトリアル映画スチル。実在カメラ感、自然な質感、映画グレーディング。写真または映画の1コマに見えること。禁止：アニメ、セル、2Dイラスト、漫画線、粘土、プラスチックCG。",
  "art.photoPortrait": "必須媒体：フォトリアルスタジオ肖像写真。ソフトボックス照明、商業ヘッドショットの鮮明さ。写真であること。禁止：アニメ、漫画インク、3D玩具、フラットセル。",
  "art.photoDocumentary": "必須媒体：フォトリアルドキュメンタリー写真。自然光、正直な質感。実在カメラで撮ったように。禁止：アニメ、様式化CG、イラスト。",
  "art.cgiFilm": "必須媒体：映画品質の3D CGIキャラクター。物理ベース材質、レイトレースハイライト。3Dレンダーであり実写でも2Dアニメでもない。禁止：実写写真、アニメ線画、平塗り漫画インク。",
  "art.cgiStylized": "必須媒体：様式化した高品質3D（長編アニメCGI）。読みやすい丸み、柔らかいPBR。3D CGIであること。禁止：実写、2Dセル、走り描き漫画。",
  "art.cgiClay": "必須媒体：3D粘土／彫刻キャラクター。マットな粘土、彫刻フォルム。粘土彫刻に見えること。禁止：実写肌写真、アニメセル、インク漫画。",
  "art.animeModern": "必須媒体：現代日本テレビアニメ。清潔なデジタル線、柔らかいセル、アニメ目と髪。全体が2Dアニメであること。禁止：実写写真、毛穴、3Dレンダー、西洋漫画インクのみ、油絵。",
  "art.animeShonen": "必須媒体：少年アニメキービジュアル。太い線、高コントラストセル、鋭いアニメ目。少年アニメ2Dであること。禁止：実写、3D CGI、水彩のみ。",
  "art.animeShoujo": "必須媒体：少女アニメ。繊細な線、柔らかいグラデ、輝くアニメ目。少女アニメであること。禁止：実写、硬い3D、荒い漫画インク。",
  "art.animeGekiga": "必須媒体：劇画／写実アニメ。成熟した線、抑制された色、なお2Dアニメ。禁止：実写写真、ちび、純粋3D。",
  "art.animeChibi": "必須媒体：ちび／スーパーデフォルメアニメ。頭大・体小、簡略化した可愛い顔。ちびアニメであること。禁止：写実比率、写実3D、細密実写。",
  "art.donghua": "必須媒体：中国国漫のキャラクターキーアート。衣装の洗練、優雅なシルエット、高品質2D／2.5D。国漫に見えること。禁止：実写、西洋新聞漫画のみ。",
  "art.manhwa": "必須媒体：韓国マンファ／ウェブトゥーンフルカラー。柔らかいデジタル塗、清潔な輪郭、艶のある髪。マンファ2Dであること。禁止：実写、粘土3D、アメコミインクのみ。",
  "art.comicWestern": "必須媒体：西洋コミック。確かなインク線、平塗りまたは限定セル、グラフィックな形。コミックイラストであること。禁止：実写写真、純粋アニメ目、粘土レンダー。",
  "art.conceptGame": "必須媒体：AAAゲームキャラクターコンセプト。ペイントオーバー設定、強いシルエット。コンセプトアートでありスクショでも実写でもない。禁止：純粋実写ポートレート、ちびアニメのみ。",
  "art.illustrationSoft": "必須媒体：柔らかいデジタルイラスト。優しい筆、絵本寄りの完成度。描いたイラストであること。禁止：実写カメラ写真、硬いアニメセル、粘土3D。",
  "mediaGen.polishTask": "任務：{{hint}}",
  "mediaGen.polishKind": "種類：{{kind}}",
  "mediaGen.polishMaterials": "—— 材料 ——",
  "mediaGen.polishEndMaterials": "—— 材料終わり ——",
  "mediaGen.polishRef": "参考図{{n}} — {{title}}",
  "mediaGen.videoTaskHint": "キーフレームから専門の画像→動画演出文を書く（{{kind}}）。カメラ・演技・リズムを含め、キーフレームに固定する。",
  "mediaGen.directorFallbackCam": "カメラと演技を明確に。字幕・透かし禁止。",
  "charIntro.task": "図生動画：参照の同一人物で短い自己紹介クリップ。",
  "charIntro.identityLock": "身元ロック：顔・髪・体・年齢・衣装・色を参照と一致させよ。",
  "charIntro.personality": "性格／気配：{{personality}}。",
  "charIntro.backstory": "背景：{{backstory}}。",
  "charIntro.relationships": "関係：{{relationships}}。",
  "charIntro.soul": "キャラクター聖書の抜粋（演技出典）：{{soul}}",
  "charIntro.performance": "癖：{{manner}}。",
  "charIntro.speech": "口：短い自己紹介のように動く。声：{{voice}}。",
  "charIntro.beat": "自然な静止 → 微笑／会釈 → 短い紹介ジェスチャ → ホールド。",
  "charIntro.lighting": "静止画と一致する光。字幕・ロゴ・他人禁止。",
  "sceneIntro.task": "図生動画：同一場所の紹介／確立ショット。",
  "sceneIntro.spaceLock": "空間ロック：建築・材質・看板・間取り・色を参照と一致させよ。",
  "sceneIntro.name": "地名：{{name}}。",
  "sceneIntro.place": "場所の説明：{{place}}。",
  "sceneIntro.spaceType": "空間タイプ：{{type}}。",
  "sceneIntro.time": "時間帯：{{time}}。",
  "sceneIntro.weather": "天候：{{weather}}。",
  "sceneIntro.moodLight": "雰囲気：{{mood}}。照明：{{lighting}}。",
  "sceneIntro.palette": "色：{{palette}}。",
  "sceneIntro.setDressing": "装置：{{set}}。",
  "sceneIntro.tags": "視覚タグ：{{tags}}。",
  "sceneIntro.art": "作風：{{art}}。",
  "sceneIntro.ambient": "環境（UI字幕なし）：{{sound}}。",
  "sceneIntro.scriptCue": "場のヒント（雰囲気のみ）：{{cue}}。",
  "sceneIntro.camera": "カメラ：{{camera}}。材料に無い新しい顔・ロゴ・字幕を足すな。",
  "sceneIntro.beat": "確立 → 環境の微動 → 静止。",
  "propIntro.task": "図生動画：同一小道具のヒーロー紹介。",
  "propIntro.objectLock": "物体ロック：輪郭・材質・色・刻印・摩耗・比率を参照と一致させよ。",
  "propIntro.name": "小道具名：{{name}}。",
  "propIntro.look": "外見：{{look}}。",
  "propIntro.material": "材質：{{material}}。",
  "propIntro.size": "寸法：{{size}}。",
  "propIntro.condition": "状態：{{condition}}。",
  "propIntro.tags": "視覚タグ：{{tags}}。",
  "propIntro.art": "作風：{{art}}。",
  "propIntro.camera": "きれいな卓上でゆるい周回またはプッシュイン。",
  "propIntro.beat": "ヒーロー静止 → 微光／微回転 → 静止。",
  "propIntro.noHands": "静止画に無い手・顔・字幕・透かし・余分な小道具禁止。",
  "costumeIntro.task": "図生動画：同一衣装の紹介クリップ。",
  "costumeIntro.wardrobeLock": "衣装ロック：輪郭・布・色・層・小物を参照と一致させよ。",
  "costumeIntro.identityOrProduct": "人がいれば顔／体をロックし布は微動可。トルソー／平置きなら商品構図。",
  "costumeIntro.name": "ルック名：{{name}}。",
  "costumeIntro.desc": "衣装：{{look}}。",
  "costumeIntro.art": "作風：{{art}}。",
  "costumeIntro.camera": "ゆるいプッシュインまたは周回。",
  "costumeIntro.beat": "静止 → 布の垂れ／袖口の微動／金具の反射 → 静止。",
  "costumeIntro.forbid": "新しい顔・字幕・ロゴ・エロポーズ禁止。",
  "costumeIntro.fallbackName": "ルック",
  "actionIntro.lead": "短編ドラマ動作デモ：「{{name}}」。",
  "actionIntro.intention": "意図：{{intention}}",
  "actionIntro.body": "身体／テンポ：{{body}}",
  "actionIntro.camera": "カメラ：{{camera}}",
  "actionIntro.closing": "滑らか。字幕なし。キーフレームに従え。",
  "sceneIntroPolish.task": "任務：場所紹介／確立クリップ（図生動画）。",
  "sceneIntroPolish.hasRef": "参照場所静止画あり — 空間身元をロック。",
  "sceneIntroPolish.noRef": "静止画パスなし。場所聖書にロック。",
  "sceneIntroPolish.dossier": "場所ファイル：",
  "sceneIntroPolish.scriptCue": "脚本ヒント（雰囲気のみ）：\n{{script}}",
  "sceneIntroPolish.emptySet": "空セット優先。新しい顔禁止。字幕・ロゴ禁止。",
  "propIntroPolish.task": "任務：小道具ヒーロー紹介（図生動画）。",
  "propIntroPolish.hasRef": "参照小道具静止画あり — 物体身元をロック。",
  "propIntroPolish.noRef": "静止画パスなし。小道具ファイルにロック。",
  "propIntroPolish.dossier": "小道具ファイル：",
  "propIntroPolish.noHands": "新しい手や顔禁止。字幕・ロゴ禁止。",
  "costumeIntroPolish.task": "任務：衣装／ルック紹介（図生動画）。",
  "costumeIntroPolish.hasRef": "参照あり — 人なら身元＋衣装、トルソーなら輪郭と材質。",
  "costumeIntroPolish.noRef": "静止画なし。衣装説明にロック。",
  "costumeIntroPolish.dossier": "衣装ファイル：",
  "costumeIntroPolish.fabric": "布の微動のみ。新しい顔・字幕・ロゴ禁止。",
  "actionIntroPolish.task": "任務：動作指導紹介クリップ（図生動画）。",
  "actionIntroPolish.hasRef": "参照あり — 演技身元をそのフレームにロック。",
  "actionIntroPolish.templateKeepRules": "テンプレート下書き（磨け；生成の鉄則 は末尾）：",
  "cover.posterLead": "短編ドラマのポスター／キーアート（16:9）。UIモック禁止。文字・ロゴ・透かし禁止。",
  "cover.titleMood": "物語タイトル（雰囲気のみ、画面に文字を出すな）：{{title}}。",
  "cover.styleBible": "作風：{{style}}",
  "cover.extraDir": "追加指示：{{idea}}",
  "cover.establishing": "ライブラリ表紙向きの確立ムード。強いシルエット。",
  "cover.medium": "指定 medium に合わせ、構図をはっきり。",
  "cover.editPrefix": "画像編集：新しいポスター構図。主体の身元／雰囲気は残せ。",
  "cover.label": "物語カバー",
  "costumeFill.system": "映画衣装デザイナー。コンパクトJSONのみ。各値は文字列。画像があればその衣装を忠実に。",
  "costumeFill.idea": "構想：{{idea}}",
  "costumeFill.polish": "衣装下書きを磨け。",
  "costumeFill.required": "必須キー：name, description, artStyle, hardRules。欠けると無効。",
  "costumeFill.fallbackName": "ルック",
  "segment.entireStory": "全編（すべての場）",
  "segment.noStory": "物語未選択（キャラ資料のみ）",
  "vision.inventFromImage": "添付の参照画像からこの{{kind}}のプロフィールを完全に埋めよ。",
  "vision.polishAll": "全欄を磨いて統合せよ",
  "story.untitled": "無題の短編ドラマ",
  "action.castIdentityNote": "参照素材 {{count}} 枚：各パネルで顔／体を添付キャストと一致させよ。",
  "tpl.system.polishOnly": "レシピ polish-only：核の身元と世界を保て。文言だけ磨け。時代・天候・職業・場所やサンプル世界を発明するな。口語を発明するな。既定の鉄則をプロファイルに書くな。",
  "tpl.system.fillBlanks": "レシピ fill-blanks：空欄だけ埋めよ。記入済みは書き換えるな。新しい世界を作るな。",
  "tpl.system.invent": "レシピ invent：ユーザーが自由創作を許した。撮れる細部で必須欄を埋めよ。Demo や本リクエストに無い世界は持ち込むな。",
  "tpl.system.fromStory": "レシピ from-story：このリクエストに書かれたタイトル／作風／キャスト／場面だけを continuity に使え。衝突時はユーザー構想が勝つ。",
  "tpl.system.followAsset": "レシピ follow-asset：既にある作風と鉄則に従え。材料に無い映画的ルック・空セット・6–10秒を強いるな。尺はクリップの実秒数。",
  "tpl.system.cinematicLock": "レシピ cinematic-lock：映画的短編。場所は空セット優先。透かし・ロゴ・余分な顔禁止。人間は両手両腕両脚（非人以外）。",
  "tpl.system.identityLock": "レシピ identity-lock：顔／体／衣装／場所／小道具を添付スチールにロック。別人・別場所・別物に替えるな。",
  "tpl.system.restyle": "レシピ restyle：同一人物を保て。衣装・場所・時代はユーザーが求めたら変えてよい。別人にするな。",
  "pipeline.character.system": "短編AIドラマのキャラ聖書を磨く。各キャラ3–5行：見た目・声・動機・決め動作。この依頼にある事実だけ使え。",
  "pipeline.scene.system": "場面を視覚ビート表に展開。尺は材料の実秒。6–10秒と決めるな。提供された場面だけ。",
  "pipeline.props.system": "小道具の連続性を磨く。色・サイズ・登場時機。名簿に無い小道具を発明するな。",
  "pipeline.script.system": "短編ドラマの脚本家。各場面をAI動画向けの短い脚本に。実尺を使え。10秒上限を強いるな。形式：\n### SCENE <number> | id=<id>\n<script body>",
  "pipeline.script.noScenes": "（場面なし — 場所を発明するな）",
  "keyArt.task": "物語「{{title}}」のキーアート第{{n}}点。完成した宣材／スチル1枚。漫画コマ割り・コマ番号・アプリUIは禁止。",
  "keyArt.lockCover": "カバーポスター：横位置の物語カード用キービジュアル。タイトル安全域を残す。顔は判別できること。架空ロゴや偽クレジットは作らない。",
  "keyArt.lockPoster": "縦ポスター：1枚の直立ワンシート。スマホでも主役が読める。画面内に別ポスターを置かない。",
  "keyArt.lockStill": "スチル：短編から抜き出したような映画的1フレーム。自然な演技と実在空間。コラージュ禁止。",
  "keyArt.lockPromo": "宣材：人物と世界を同じ画に収めた販促キーアート。輪郭は強く、気分は一つ。コンタクトシートではない。",
  "keyArt.lockSocial": "縦型SNS：9:16の予告フレーム。被写体は大きく。テロップ余白を残す。",
  "keyArt.lockHeadshot": "主人公クローズアップ：正面の顔が画面を満たす。添付資料と同一人物。肩まで可。他人は入れない。",
  "keyArt.lockBust": "バストアップ宣材：胸から上。衣装の襟が見え、カメラを向く。",
  "keyArt.lockGroup": "群像：指名された全キャラを同一光・同一世界で1画に。顔の欠落や入れ替えは禁止。",
  "keyArt.formatLockTall": "判型固定：画面全体は縦9:16。横位置ワイド構図は禁止。",
  "keyArt.formatLockSquare": "判型固定：画面全体は正方形1:1。",
  "keyArt.formatLockWide": "判型固定：画面全体は横16:9。",
  "keyArt.methodFreshLock": "作り方：新規生成。参照は身元固定のみ。旧テイクの画素構図をコピーしない。",
  "keyArt.methodEditLock": "作り方：添付の現行スチルを編集。指示が無い限り構図は維持。",
  "keyArt.methodIdentityLock": "作り方：顔はキャラ参照に固定。ポーズ・トリミング・衣装は変えてよい。",
  "keyArt.methodContinueLock": "作り方：前カットから続ける。同じ人・同じ場所、同じ撮影の次のカット。",
  "keyArt.briefLine": "演出メモ：{{brief}}",
  "keyArt.beatLine": "紐付けビート：{{beat}}",
  "keyArt.close": "完成した{{aspect}}スチル。透かし・UI枠・余分な字幕は禁止。",
  "charIntro.manner": "癖：{{manner}}。",
  "charIntro.cameraDefault": "演技カメラ：ゆるいプッシュイン、またはわずかな手持ち揺れ。キャラクターはレンズを見るか、わずかに外す。",
  "mediaGen.honorCameraTemplate": "材料にカメラ範本ブロックがある場合は、その構図と動きに正確に従え。汎用のプッシュインや手持ちに差し替えるな。",
  "mediaGen.refRoles": "添付静止画は役割を分ける：IDENTITY（顔と衣装）、SPATIAL（白模の配置とカメラ経路のみ。粘土の灰色を完成見た目に使うな）、MOTION（間と所作）、STYLE（色と光）。一枚で全部を支配させるな。",
  "sceneIntro.cameraNotes": "カメラ備考：{{camera}}。",
  "sceneIntro.cameraDefault": "カメラ：連続したゆるい動き。材料に無い新しい出演者の顔・ロゴ・字幕を足すな。",
  "quality.family.photo": "画質：目または主顔／頭部の特徴に鋭く合焦。フォトリアル媒体に見合う微細ディテール。作風が別に定めない限りプロの三点スタジオ照明。単焦点レンズ感（50–85mm）。モーションブラーなし、過度な美肌フィルタなし、透かし・文字なし。",
  "quality.family.cgi": "画質：清潔な3Dキャラ提示、読みやすい材質（PBR）、一貫したトポロジー輪郭、主フォルムはシャープ。スタジオHDRIまたは三点CGライト。粘土スタイル以外は粒状ノイズなし。透かし・文字なし。実写写真ではない。",
  "quality.family.anime": "画質：清潔な2Dキャラ設定シート。線の太さは一定、各コマで顔モデルが安定、制御されたセルまたは柔らかい陰影。フォトリアル写真・実写風・3Dの皮下散乱写真陰影を避ける。透かし・文字ラベルなし。",
  "quality.family.illust": "画質：プロのイラスト設定シートの明瞭さ。キャラデザインは一貫、輪郭と衣装／材質は読みやすい。中性スタジオ背景。透かしなし、UI字幕なし。",
  "sheet.lock.lead": "AI動画の画面連続用にキャラクター参照静止画を作れ。",
  "sheet.lock.sexPrefix": "性別ロック（最優先——お団子髪、卵型顔、色白、細い体型、袍服のいずれも性別を反転させるな）：{{lock}}",
  "sheet.lock.identity": "身元ロック：どのコマも主体はちょうど一人（人・動物・生物・霊・ロボット・その他の設計体でよい——ただし同一シートの途中で種やデザインを差し替えるな）。",
  "sheet.lock.noSecond": "第二のキャラを発明するな。全コマで同じ身体設計、模様、色、頭部デザインを保て。",
  "sheet.lock.head": "頭／顔（または相当部位）は一貫：同じ目またはセンサー、同じ頭部輪郭、同じ表面色と識別点。",
  "sheet.lock.camera": "カメラ：安定した参照構図、垂直線は真っ直ぐ。レイアウトが特殊角度を求めない限り魚眼は使うな。",
  "sheet.lock.background": "背景：清潔な継ぎ目なしライトグレーまたはオフホワイトのスタジオサイクラマ。空で均一。レイアウトが小さな衣装／小道具ディテールを求めない限り雑物なし。",
  "sheet.lock.forbidden": "禁止：透かし、ロゴ、キャプション、文字、UI枠、余分な四肢、変形した末端（手／ディテール専用ショットを除く）。",
  "sheet.lock.subject": "主体の名／構想：{{name}}",
  "sheet.lock.age": "年齢または成熟の見え方：{{age}}",
  "sheet.lock.gender": "性別／提示：{{gender}}",
  "sheet.lock.appearance": "外見（必ず一致）：{{appearance}}",
  "sheet.lock.appearanceFaceOnly": "外見——顔／髪／体型比のみ（必ず一致）：{{appearance}}。この記述から衣服、コート、傘、鞄、靴、装身具、小道具は除け——画面に出すな。",
  "sheet.lock.ignoreCostume": "表衣装／小道具：このシートでは完全に無視。傘、鞄、コート、ファッション小物なし。体型またはベースレイヤー板のみ。",
  "sheet.lock.costume": "衣装／外装デザイン（必ず一致）：{{costume}}",
  "sheet.lock.tags": "視覚タグ：{{tags}}",
  "sheet.lock.tagsIdentity": "視覚タグ（身元のみ。衣服／小道具タグは捨てる）：{{tags}}",
  "sheet.lock.manner": "わずかなポーズ／癖のヒントのみ（身元を変えるな）：{{manner}}",
  "sheet.scaffold.repeatMedium": "再掲：最終画像の媒体はスタイル id「{{id}}」（{{family}}）でなければならない。",
  "sheet.scaffold.wardrobeTag": "衣装レイヤー標記：{{tag}}。",
  "sheet.scaffold.layoutLead": "レイアウト：{{layout}}",
  "sheet.scaffold.finalCheck": "最終確認：媒体が違って見えるなら正しい媒体でやり直せ：{{medium}}",
  "sheet.edit.task": "画像編集／レイアウト変更任務（最優先——最後まで読め）：",
  "sheet.edit.target": "目標シート案 id：「{{id}}」。衣装レイヤー：{{tag}}。",
  "sheet.edit.ignoreLayout": "元画像のレイアウトは完全に無視：コマ数、溝、カメラ角、トリミング、構図をコピーするな。",
  "sheet.edit.ignoreWardrobe": "下記の目標衣装レイヤーと衝突するなら、元画像の衣装は無視せよ。",
  "sheet.edit.keepIdentity": "元画像から残すのは身元のみ：顔／頭デザイン、髪、体型比、種／身体設計、肌または表面模様、年齢感。",
  "sheet.edit.stripOuter": "元画像の表衣・鎧をすべて剥げ。体型板：肌色ユニタードのみ。ベースレイヤー：簡素な下着のみ。元の衣装は残すな。",
  "sheet.edit.applyProfileCostume": "本文プロンプトのプロフィール衣装説明を適用してよい。元の衣装コマを塗り替える・切り抜くだけにするな。",
  "sheet.edit.changeMedium": "必須媒体の画風に合わせるため、必要ならレンダリング媒体を完全に変えよ。",
  "sheet.edit.noNewPerson": "別人を発明するな。トリミング・拡大・再着色だけで済ませるな。",
  "sheet.edit.newComposition": "レイアウトブロックに正確に合う、まったく新しい設定シート構図を出せ（コマ数とポーズ）。",
  "sheet.edit.checklist": "最終チェックリスト：（1）身元は元の顔／体と一致（2）レイアウトは案「{{id}}」に合わせ、元シートではない（3）衣装レイヤー {{tag}}（4）媒体 = {{style}}。",
  "sheet.wardrobe.nude": "制作用の衣装デザイン体型比プレート（成人向け内容ではない、裸の写真ではない）：中性の臨床スタジオ照明、無地グレーのサイクラマ、プロの人体デッサンポーズ。ファッション写真、ランジェリー演出、寝室や華美なセットは禁止。主体は継ぎ目のないマットな肌色ユニタード／全身密着ベーススーツ（または種に応じた無地マットのボディスーツ）を着用し、正確な体型輪郭と比率を示す——顔と髪は見える。表衣装、ロゴ、小道具、靴、アクセサリーなし。ユニタードは制作用下地のみ（CGボディメッシュと同様）であり、表衣装ではない。後の衣装CGのため顔・髪・体型比・表面模様を保て。このシートでは表衣装の記述を無視せよ。明確にユニタード着用——着衣なしにするな。",
  "sheet.wardrobe.halfBareUpper": "制作用の上半身部分参照（成人キャラのみ。臨床的人体研究。色情ではない。ポルノではない。性的暗示ではない）：中性の臨床スタジオ照明、無地グレーのサイクラマ、プロの医療／マネキン立ち。ファッション写真、ランジェリー演出、寝室セット、性化したカメラは禁止。上半身は露出：胴・胸・肩・腕・首。顔と髪は完全に見える。下半身は無地マットの中性または肌色の不透明ボトムのみ（プレーンなショーツ、ブリーフ、または簡素な巻き布——制作用の被覆のみ。ファッションランジェリーではない。レース・透けなし）。表の上衣、ファッションとしてのブラ、小道具、靴、アクセサリー、ロゴなし。後の衣装CG／衣装合わせのため顔・髪・体型比・表面模様を保て。このシートでは表衣装の記述を無視せよ。",
  "sheet.wardrobe.halfBareLower": "制作用の下半身部分参照（成人キャラのみ。臨床的人体研究。色情ではない。ポルノではない。性的暗示ではない）：中性の臨床スタジオ照明、無地グレーのサイクラマ、プロの医療／マネキン立ち。ファッション写真、ランジェリー演出、寝室セット、性化したカメラは禁止。下半身は露出：腰・大腿・脚・足。顔と髪は完全に見える。局部のみ最小限のマットな肌色または中性の不透明被覆（簡素なブリーフ——制作用のみ。ファッションランジェリーではない）。上半身は無地マットの中性トップのみ（プレーンなタンクトップ、アンダーシャツ、または巻き布——制作用の被覆のみ。ファッション演出なし、ロゴなし）。表衣装、小道具、靴、アクセサリーなし。後の衣装CG／衣装合わせのため顔・髪・体型比・表面模様を保て。このシートでは表衣装の記述を無視せよ。",
  "sheet.wardrobe.bare": "制作用の全身解剖体型参照（成人キャラのみ。臨床的人体研究。色情ではない。ポルノではない。性的暗示ではない）：中性の臨床スタジオ照明、無地グレーのサイクラマ、プロの医療／マネキン立ち。ファッション写真、ランジェリーポーズ、寝室セット、性化したカメラは禁止。主体は完全に着衣なし（全身の裸形、または種に応じた露出表面）。顔と髪のみ——衣服、部分被覆、表衣装、小道具、靴、アクセサリーなし。後の衣装CG／衣装合わせのため顔・髪・体型比・表面模様を保て。このシートでは表衣装の記述を無視せよ。",
  "sheet.wardrobe.base": "制作用ベースレイヤー参照（衣装差し替え用の下着／下地。色情ではない）：簡素な無地中性下着、または種に応じた下地被覆のみ（例：プレーンなブリーフ＋アンダーシャツ、または簡素な巻き布）。表衣装、ロゴ、ファッションランジェリー演出、性的ポーズなし。臨床スタジオ光、グレー背景。後に表衣装を着せるため身元を保て。このシートでは表衣装の記述を無視せよ。",
  "sheet.wardrobe.costume": "制作用衣装参照：記述どおりの完成した表衣装。動画の画面連続のため材質と輪郭が読めること。",
  "sheet.layout.bible": "横16:9のキャラ聖書。左右ちょうど3つの等しい縦コマ：（1）全身正面立ち、足が見え、腕は自然；（2）全身斜め約45°；（3）頭肩のポートレートでレンズを向く。各コマで人物が枠を満たす。3コマとも同じ顔・髪・体・衣装。はっきりした溝、清潔なスタジオ。",
  "sheet.layout.turnaround": "横16:9のターンアラウンド。同じ縮尺の全身ちょうど4体：正面、左90°側面、全背面、右90°側面。中性のAポーズ／腕は自然、足は接地。完全な衣装。人物はできるだけ高く。",
  "sheet.layout.expression": "正方形1:1の密な2×2。頭肩クローズアップちょうど4コマ：無表情、柔らかい微笑、怒り、驚き。各顔はセルの約9割。髪と襟は同一。全身は出すな。",
  "sheet.layout.costume": "縦9:16の衣装ボード：上約65%は全身ヒーローでカメラを向く完全衣装。下帯は大きなディテール切り抜きちょうど2つ（布／ポケット＋靴または象徴小物）。材質は読めること。",
  "sheet.layout.identity_lock": "横16:9の身元ロック、ちょうど2コマ：左60%は正面顔の大クローズアップ。右40%は斜め四分の三の顔。動画認人のため五官ディテールを最大化。全身は出すな。",
  "sheet.layout.face_id": "正方形1:1の単一・中央の正面向き顔（または主頭部）ポートレート。上半身を含みレンズを見る。主特徴はシャープ。必須媒体で完全に描く。キャラは一人のみ。",
  "sheet.layout.hero": "縦9:16の単一全身ヒーロー立ちポートレート。目線の高さ、全身が見える。中央の中性立ち、スタジオ背景、完全衣装、必須媒体。",
  "sheet.layout.bust": "正方形1:1のミディアムバスト（胸から上）。体はわずかに斜め、顔はカメラ向き。台詞用のフレーミング、衣装の襟が見える。",
  "sheet.layout.three_quarter": "縦9:16の四分の三身（膝から上）。体は30–45°、顔はカメラ向き。衣装の輪郭は明確、手は見える。",
  "sheet.layout.profile": "縦9:16の純左側全身90°側面。左を向き、背骨は真っ直ぐ。真の輪郭。完全衣装。キャラは一人。",
  "sheet.layout.back": "縦9:16の全身背面。カメラに背を向け、髪と衣装の背面が読める。退場の画面連続シート。",
  "sheet.layout.low_angle": "縦9:16の英雄的ローアングル全身。カメラは腰付近からわずかに見上げ、力強い立ち、顔はなおシャープ、完全衣装。",
  "sheet.layout.high_angle": "縦9:16のハイアングル四分の三身。カメラは視線よりわずかに上から見下ろす。顔は読める、完全衣装。",
  "sheet.layout.action": "横16:9の単人動作フリーズ（歩行または手が伸びる）。シャープでモーションブラーなし、完全衣装、柔らかいグレー環境。",
  "sheet.layout.dialogue": "横16:9の肩越し台詞構図：前景は同一人物の柔らかい肩、後景はシャープな顔がカメラ左を見る。身元は一つだけ。",
  "sheet.layout.body_nude_turnaround": "横16:9の体型比ターンアラウンド。同じ縮尺の全身ちょうど4体：正面、左90°、背面、右90°。中性Aポーズ、輪郭が分かるよう腕は胴からわずかに離し、足は接地。肌色ユニタードのみ。顔と髪は一貫。",
  "sheet.layout.body_nude_front": "縦9:16の単一全身正面体型比プレート。目線の高さ、頭から足まで見え、腕は自然。衣装合わせのため体型は明確。肌色ユニタードのみ。中性のプロ立ち。",
  "sheet.layout.body_nude_t_pose": "横16:9の単一全身TポーズまたはAポーズ（腕は水平または30°下げ）。正面向き、バインド／リグ参照用の肌色ユニタード。足は肩幅、顔は正面、衣装パイプライン向けの臨床マネキン感。",
  "sheet.layout.body_half_bare_turnaround": "横16:9の上半身露出ターンアラウンド。同じ縮尺の全身ちょうど4体：正面、左90°、背面、右90°。中性Aポーズ、上半身の輪郭が分かるよう腕は胴からわずかに離し、足は接地。上半身露出＋簡素なボトムのみ。顔と髪は一貫。",
  "sheet.layout.body_half_bare_front": "縦9:16の単一全身正面・上半身露出プレート。目線の高さ、頭から足まで見え、腕は自然。上胴は露出。簡素な無地ボトムのみ。体型は明確。中性のプロ立ち。",
  "sheet.layout.body_half_bare_t_pose": "横16:9の単一全身TポーズまたはAポーズ（腕は水平または30°下げ）。正面向き、バインド／リグ参照のため上半身露出。簡素な無地ボトムのみ。足は肩幅、顔は正面、臨床マネキン感。",
  "sheet.layout.body_half_bare_lower_turnaround": "横16:9の下半身露出ターンアラウンド。同じ縮尺の全身ちょうど4体：正面、左90°、背面、右90°。中性Aポーズ、下半身の輪郭が分かるよう脚はわずかに開き、足は接地。下半身露出＋簡素なトップのみ。顔と髪は一貫。",
  "sheet.layout.body_half_bare_lower_front": "縦9:16の単一全身正面・下半身露出プレート。目線の高さ、頭から足まで見え、腕は自然。脚は露出。簡素な無地トップのみ。体型は明確。中性のプロ立ち。",
  "sheet.layout.body_half_bare_lower_t_pose": "横16:9の単一全身TポーズまたはAポーズ（腕は水平または30°下げ）。正面向き、バインド／リグ参照のため下半身露出。簡素な無地トップのみ。足は肩幅、顔は正面、臨床マネキン感。",
  "sheet.layout.body_bare_turnaround": "横16:9の全身解剖ターンアラウンド。同じ縮尺の全身ちょうど4体：正面、左90°、背面、右90°。中性Aポーズ、輪郭が分かるよう腕は胴からわずかに離し、足は接地。完全に着衣なしの形体のみ。顔と髪は一貫。",
  "sheet.layout.body_bare_front": "縦9:16の単一全身正面の解剖プレート。目線の高さ、頭から足まで見え、腕は自然。衣装合わせのため体型は明確。完全に着衣なしの形体のみ。中性のプロ立ち。",
  "sheet.layout.body_bare_t_pose": "横16:9の単一全身TポーズまたはAポーズ（腕は水平または30°下げ）。正面向き、バインド／リグ参照のため完全に着衣なし。足は肩幅、顔は正面、衣装パイプライン向けの臨床マネキン感。",
  "sheet.layout.base_layer_turnaround": "横16:9のベースレイヤー・ターンアラウンド。全身ちょうど4体：正面、左90°、背面、右90°。簡素な下着／下地のみ（無地グレーまたはベージュ）。表衣装なし。中性Aポーズ。",
  "sheet.layout.base_layer_hero": "縦9:16の単一全身正面、簡素な下着のみ。中性立ち、頭から足まで。後に表衣装を重ねるための清潔な輪郭。",
  "sheet.layout.costume_hero": "縦9:16の単一全身正面、設計どおりの完全な表衣装。ヒーロー立ち、頭から足まで、材質は読める。",
  "sheet.layout.costume_turnaround": "横16:9の完全衣装ターンアラウンド。全身ちょうど4体：正面、左90°、背面、右90°。同じ縮尺、Aポーズ、靴と外層を含む完全な表衣装。",
  "sheet.layout.costume_detail_board": "正方形1:1のディテールボード。完全衣装の大きなクローズアップちょうど4つ：織り、留め金／ボタン、靴またはブーツ、象徴小物。全身は出すな。衣装連続のための材質忠実。",
  "sheet.layout.hands": "正方形1:1の手のクローズアップ研究（小さな小道具は任意）。肌／表面色は身元と一致。指関節はシャープ。連続ディテールシート。",
  "sheet.layout.feet_shoes": "正方形1:1、大きなコマちょうど2つ：左は裸足（または素の足／相当）が継ぎ目なしの床に立つ。右は対応する設計靴／ブーツ（衣装にあれば）。衣装差し替えのため輪郭は明確。",
  "sheet.layout.accessories": "正方形1:1の小物ボード：帽子、鞄、武器、装身具、または衣装記述の象徴小道具を最大4つの商品風クローズアップ。清潔なスタジオ、全身は出すな。",
  "sheet.layout.silhouette": "縦9:16の純黒塗りつぶし全身正面シルエット。白またはライトグレー地、内部ディテールなし。衣装差し替え時の比確認のため外輪郭は読める。余白があれば淡い側面シルエットを加えてよい——強い正面シルエット1枚を優先。",
  "plate.scene.emptySet": "短編ドラマ画面連続用の空セット場所プレート：主役の顔なし、指名俳優なし。縮尺のためなら遠くの極小シルエットのみ可。建築、材質、看板、主要な装置は保て。",
  "plate.scene.lock.lead": "AI短編ドラマの画面連続用に場所参照静止画を作れ。",
  "plate.scene.lock.identity": "空間身元ロック：全コマで同じ建築、材質、看板、間取りの言語。",
  "plate.scene.lock.forbidden": "禁止：識別できる有名人の顔、指名キャストの肖像、混雑した主役クローズアップ、透かし、UI字幕。",
  "plate.scene.lock.quality": "画質：材質はシャープ、垂直線は安定、プロの美術写真／コンセプトアートの忠実さ。",
  "plate.scene.lock.name": "地名：{{name}}",
  "plate.scene.lock.place": "場所の説明：{{place}}",
  "plate.scene.lock.type": "空間タイプ：{{type}}",
  "plate.scene.lock.time": "時間帯：{{time}}",
  "plate.scene.lock.weather": "天候：{{weather}}",
  "plate.scene.lock.mood": "雰囲気：{{mood}}",
  "plate.scene.lock.lighting": "照明デザイン：{{lighting}}",
  "plate.scene.lock.palette": "色：{{palette}}",
  "plate.scene.lock.set": "装置：{{set}}",
  "plate.scene.lock.tags": "視覚タグ：{{tags}}",
  "plate.scene.scaffold.repeatMedium": "再掲：媒体はスタイル id「{{id}}」（{{family}}）でなければならない。",
  "plate.scene.scaffold.layer": "プレート層：{{layer}}。",
  "plate.scene.scaffold.finalCheck": "最終確認：媒体 {{style}} は正しい。主役の顔なし。場所身元はロック。",
  "plate.scene.edit.task": "画像編集／場所の作風変更任務（最優先）：",
  "plate.scene.edit.keep": "元画像の場所身元を保て：建築ボリューム、材質、看板、主要な装置の配置。",
  "plate.scene.edit.change": "下記の場所プレート案が求める媒体および／またはカメラレイアウトに変えよ。",
  "plate.scene.edit.forbid": "別の場所を発明するな。主役の顔を足すな。",
  "plate.scene.layout.establishing": "横16:9の確立ショット。場所の全外観または主ボリューム。ランドマークは読める。地平または天井線は安定。映画的な奥行き。",
  "plate.scene.layout.hero_plate": "横16:9のヒーロー場所静止画——このセットの決定的カバーフレーム。強い構図。将来の立ち位置のため舞台床または街路は明確。",
  "plate.scene.layout.three_quarter_space": "横16:9の四分の三空間：前景の枠、中景の演技ゾーン、背景の奥行き。台詞ステージ向き。顔なし。",
  "plate.scene.layout.identity_lock": "横16:9、同一場所の等しいコマちょうど2つ：（1）正面のキーアングル（2）約45°斜め。同じ材質、看板、色。",
  "plate.scene.layout.low_angle": "縦9:16のローアングル。建築／天井／キャノピーを見上げ、ドラマのスケール。顔なし。",
  "plate.scene.layout.high_angle": "横16:9のハイアングル。床平面／街路幾何をブロッキング参照用に。顔なし。",
  "plate.scene.layout.pov_enter": "横16:9の主観視点。戸口または路地口から場所へ入る。敷居の先は空セット。",
  "plate.scene.layout.over_shoulder_empty": "横16:9の肩越し空フレーム：前景は匿名の肩シルエットのみ、後景は場所がシャープ。台詞ブロッキング用。",
  "plate.scene.layout.day_clear": "横16:9、同一場所の晴れ日中光。自然な日差しの向き、読める影、乾いた表面。",
  "plate.scene.layout.golden_hour": "横16:9、同一場所のゴールデンアワー：暖かい長い影、琥珀のリムライト、ロマンチックな短編の気分。顔なし。",
  "plate.scene.layout.night_neon": "横16:9、同一場所の夜。実務照明／ネオン／街灯。シアン－マゼンタの漏れは任意、濡れは任意。顔なし。",
  "plate.scene.layout.rain_wet": "横16:9、同一場所の雨：濡れたアスファルト／反射、雨筋、冷たいグレーディング。傘は遠い小道具のみ。顔なし。",
  "plate.scene.layout.fog_mood": "横16:9、同一場所の霧／煙：柔らかい奥行き層、抑えられた色、謎の気分。建築はなお読める。顔なし。",
  "plate.scene.layout.set_dressing": "正方形1:1の卓／カウンター／棚の装置ボード。この場所の主要小道具。人物なし。",
  "plate.scene.layout.material_board": "正方形1:1の材質連続ボード：この場所の壁、床、金属／木、布。クローズアップ。顔なし、全身人物なし。",
  "plate.scene.layout.signage_prop": "正方形1:1の読める看板／ランドマーク小道具クローズアップ。場所身元ロック用。シャープな文字状の形（必要なら架空グリフ可）。顔なし。",
  "plate.scene.layout.lighting_ref": "横16:9の空セット照明参照：キーライトの向き、フィル、実務照明は明確。キャラなし。",
  "plate.prop.lock.lead": "AI短編ドラマの画面連続用に小道具参照静止画を作れ。",
  "plate.prop.lock.name": "小道具名：{{name}}",
  "plate.prop.lock.desc": "説明（必ず一致）：{{desc}}",
  "plate.prop.lock.material": "材質：{{material}}",
  "plate.prop.lock.size": "寸法メモ：{{size}}",
  "plate.prop.lock.condition": "状態／摩耗：{{condition}}",
  "plate.prop.lock.tags": "タグ：{{tags}}",
  "plate.prop.lock.forbidden": "禁止：有名人の顔、透かし、身元を乱す無関係な余分な小道具。",
  "plate.prop.scaffold.repeatMedium": "再掲：媒体はスタイル id「{{id}}」でなければならない。",
  "plate.prop.scaffold.finalCheck": "最終確認：同一の小道具身元。媒体 {{style}}。",
  "plate.prop.edit.task": "画像編集／小道具の作風変更：",
  "plate.prop.edit.keep": "元画像と同じ小道具身元を保て（輪郭、材質、模様）。",
  "plate.prop.edit.change": "求められる媒体／カメラに変えよ。別の物体を発明するな。",
  "plate.prop.layout.hero": "正方形1:1の単一小道具ヒーロー静止画。中央、清潔なグレーサイクラマ、材質はシャープ、人の顔なし、物体全体が見える。",
  "plate.prop.layout.three_quarter": "正方形1:1の同一小道具の斜め四分の三。スタジオ光、輪郭は読める。縮尺に必要でない限り手は出すな。",
  "plate.prop.layout.detail": "正方形1:1の小道具象徴ディテールの極クローズアップ（刻印、留め金、画面、摩耗）。顔なし。",
  "plate.prop.layout.material": "正方形1:1の小道具表面材質プレート：金属／木／布の質感。全身人物なし。",
  "plate.prop.layout.in_hand_scale": "横16:9の縮尺参照：匿名の手またはシルエットが小道具を持つ。顔はフレーム外または完全に匿名。小道具がヒーロー。",
  "action.geometry.panelCount": "コマ数は固定：ちょうど {{n}} コマ。数えよ：{{list}}。",
  "action.geometry.lockGrid2x3": "レイアウト固定（必須）：2行×3列＝計6コマ。上段はコマ1、2、3。下段はコマ4、5、6。禁止：2×2格子、4コマ、3×2の数え違い、単一ヒーローフレーム、それ未満のコラージュ。4コマだけ描きたくなったら——止まって6コマすべて描け。",
  "action.geometry.lockGrid2x2": "レイアウト固定（必須）：2行×2列＝計4コマ。禁止：2×3の6コマ格子、横帯、単一フレーム。",
  "action.geometry.lockStrip": "レイアウト固定（必須）：横1行ちょうど {{n}} コマ（1行×{{n}}列）。禁止：2×2格子、{{n}} 未満のコマ、指定のない複数行重ね。",
  "action.geometry.order": "コマ順は動作のタイムライン：コマ1＝最初の動作ビート、コマ {{n}}＝最後の動作ビート。",
  "action.geometry.reading": "読み順：左→右、その後上→下（複数行の場合）。",
  "action.geometry.numbers": "各コマ左上に大きく太い番号 1 から {{n}}。1 から {{n}} までの整数が一度ずつ現れなければならない。",
  "action.geometry.panelLine": "コマ {{i}}／{{n}}（{{label}}）：連続する独立した瞬間——ポーズ／段階は他のどのコマとも違う。ポーズをコピー／反復するな。",
  "action.geometry.caption": "各コマの下に、ビートラベルに対応する小さな日本語キャプション。",
  "action.geometry.identity": "全コマで同一のキャラ身元／衣装／小道具の連続。",
  "action.geometry.layout.strip-2": "横長の画像1枚：横並びストーリーボード帯、等しいコマちょうど2つ（1行×2列）、太い明瞭な溝。",
  "action.geometry.layout.strip-3": "横長の画像1枚：1行の横ストーリーボード帯、等しいコマちょうど3つ（1行×3列）、太い明瞭な溝。",
  "action.geometry.layout.grid-2x2": "正方形の画像1枚：2×2漫画ストーリーボード格子、等しいコマちょうど4つ（2行×2列）、太い明瞭な溝、読み順は左→右、その後上→下。",
  "action.geometry.layout.strip-4": "広い横長の画像1枚：1行の横ストーリーボード帯、等しいコマちょうど4つ（1行×4列）、太い明瞭な溝。",
  "action.geometry.layout.strip-5": "広い横長の画像1枚：1行の横ストーリーボード帯、等しいコマちょうど5つ（1行×5列）、太い明瞭な溝。",
  "action.geometry.layout.grid-2x3": "横長の画像1枚：漫画ストーリーボード格子、等しいコマちょうど6つを2行×3列（上段1-2-3、下段4-5-6）、太い明瞭な溝、読み順は左→右、その後上→下。",
  "swap.costume.task": "画像編集／衣装差し替え任務（最優先——描く前に最後まで読め）：",
  "swap.costume.sameCharacter": "元画像と同一人物に、新しい表衣装だけを着せている。",
  "swap.costume.identity": "身元ロック（決して変えるな）：顔／頭の形、目、髪色と髪型、体型比、種／身体設計、肌または表面模様、年齢感。",
  "swap.costume.pose": "ポーズロック：下記のレイアウトが多視点シートを求めない限り、元画像の身体ポーズとカメラ構図を保て。",
  "swap.costume.replace": "衣装置換（必須）：元画像の以前の表衣、鎧、コート、ドレス、制服、外装ギア、合わない靴をすべて剥げ。",
  "swap.costume.paint": "それから下記の新しい表衣装だけを描け——完全な被覆、正しい輪郭、読める材質、合う履物と外層小物。",
  "swap.costume.new": "新しい表衣装（必ず一致、高優先）：{{costume}}",
  "swap.costume.add": "元が裸またはベースレイヤー下着のみなら：解剖と下地の論理を保ったまま、完全な表衣装を上に加えよ。",
  "swap.costume.complete": "元が既に衣装を着ているなら：完全に置換せよ——旧装と混ぜるな、重ねるな、残像を残すな。",
  "swap.costume.edges": "衣の縁は肩・腰・手首・足首に正しく着地。浮く布、融合した四肢は禁止。",
  "swap.costume.forbidden": "禁止：種の変更、年齢変更、顔身元の変更、体型変更、第二のキャラ、色情ポーズ、透かし、字幕キャプション、UI枠。",
  "swap.costume.nonHuman": "非人主体：衣装記述に合う、種に応じた外層／装備。",
  "swap.costume.subject": "主体：{{name}}",
  "swap.costume.age": "年齢／成熟：{{age}}",
  "swap.costume.gender": "性別／提示：{{gender}}",
  "swap.costume.appearance": "外見ロック：{{appearance}}",
  "swap.costume.tags": "視覚タグ：{{tags}}",
  "swap.costume.manner": "癖のヒントのみ：{{manner}}",
  "swap.costume.checklist": "最終チェックリスト：（1）顔／体は元と同じ（2）新しい衣装だけが見える（3）媒体 = {{style}}（4）清潔なスタジオまたは中性背景。",
  "swap.costume.layout.hero_front": "縦9:16の単一全身正面立ち。頭から足まで見え、中性ヒーロー立ち、腕は自然、足は接地。キャラは一人のみ。",
  "swap.costume.layout.three_quarter": "正方形1:1の単一斜め約45°全身ポートレート。頭から足までを優先。新しい衣装の輪郭は読める。",
  "swap.costume.layout.profile": "縦9:16の単一全身の真の側面（90°）。頭から足まで、中性立ち、衣装の輪郭と側面シームは完全に読める。キャラは一人のみ。",
  "swap.costume.layout.back": "縦9:16の単一全身背面。頭から足まで、コート／ドレス／髪の背面と後輪郭が分かるよう腕は体からわずかに離す。キャラは一人のみ。",
  "swap.costume.layout.bust": "縦3:4の単一上半身バストポートレート（胸から上）。襟、ネックライン、肩、外層と顔の装身具は読める。全身切り抜きではない。キャラは一人のみ。",
  "swap.costume.layout.detail_fabric": "正方形1:1の衣装ディテールボード：新しい表衣装のみの織り、ボタン、ファスナー、刺繍、ベルト金具、材質の遷移のクローズアップ。全場面なし、第二のキャラなし。",
  "swap.costume.layout.turnaround": "横16:9のターンアラウンド。同じ縮尺の全身ちょうど4体：正面、左90°、背面、右90°。中性Aポーズ、どの視点も完全な新しい衣装。",
  "swap.atmosphere.task": "画像編集／雰囲気差し替え任務（最優先）：",
  "swap.atmosphere.keep": "元画像の場所身元を保て：建物ボリューム、壁、平面の手がかり、看板、家具配置、カメラ角度。",
  "swap.atmosphere.replace": "完全に置換せよ：時間帯、天候、空、実務照明の色、濡れ、霧、ネオンの強さは記述どおり。",
  "swap.atmosphere.new": "新しい雰囲気（必ず一致）：{{atmo}}",
  "swap.atmosphere.forbidden": "禁止：建築を別の場所へ変える、主役の顔を足す、透かし、字幕キャプション。",
  "swap.atmosphere.location": "場所：{{title}}",
  "swap.atmosphere.place": "基礎の場所：{{place}}",
  "swap.atmosphere.set": "装置ロック：{{set}}",
  "swap.atmosphere.tags": "タグ：{{tags}}",
  "swap.atmosphere.checklist": "最終チェックリスト：同じ場所幾何。雰囲気だけ変更。媒体 {{style}}。主役の顔なし。",
  "swap.atmosphere.repeatMedium": "再掲：媒体はスタイル id「{{id}}」（{{family}}）でなければならない。",
  "swap.atmosphere.layout.wide": "横16:9の全場所フレーム。元の構図にできるだけ近付ける。",
  "swap.atmosphere.layout.hero": "横16:9のヒーロー場所静止画。同じ建築、雰囲気だけ更新。",
  "swap.atmosphere.layout.detail": "正方形1:1の雰囲気ディテール：濡れた表面／実務照明／空。なお同一セットと分かる。",
}
