import type { PromptCopyTable } from './keys'

export const jaPromptCopy: PromptCopyTable = {
  "speechLock.named": "台詞ロック · キャラクター「{{who}}」：聞こえる音声と口の動きは必ず{{primaryName}}（{{primary}}）のみ。{{forbid}}や他言語に切り替えるな。クリップごとに言語を変えるな。台詞を翻訳するな。",
  "speechLock.unnamed": "台詞ロック · 出演キャラクター：聞こえる音声と口の動きは必ず{{primaryName}}（{{primary}}）のみ。{{forbid}}や他言語に切り替えるな。クリップごとに言語を変えるな。台詞を翻訳するな。",
  "speechLock.namedMulti": "台詞ロック · キャラクター「{{who}}」：聞こえる音声と口の動きは必ず{{primaryName}}（{{primary}}）。台本のその行が既にその言語である場合のみ第二言語を許可：{{extras}}。第三言語は禁止。クリップ間で切り替えるな。{{forbid}}へ変えるな。台詞を翻訳するな。",
  "speechLock.unnamedMulti": "台詞ロック · 出演キャラクター：聞こえる音声と口の動きは必ず{{primaryName}}（{{primary}}）。台本のその行が既にその言語である場合のみ第二言語を許可：{{extras}}。第三言語は禁止。クリップ間で切り替えるな。{{forbid}}へ変えるな。台詞を翻訳するな。",
  "hardRules.sealHeader": "生成の鉄則（最優先。必ず守る。前文と矛盾したらこちらを優先）：",
  "hardRules.sealFooter": "前文が生成の鉄則と矛盾する場合は、生成の鉄則に従う。",
  "hardRules.labelStory": "物語",
  "hardRules.labelCharacter": "キャラクター",
  "hardRules.labelScene": "場所",
  "hardRules.labelProp": "小道具",
  "hardRules.labelAction": "アクション",
  "continuity.lockHeader": "画面連続ロック（短編の順序を必ず守れ）：",
  "continuity.hasImage": "添付は第{{n}}段の終了フレーム／キーフレーム。このショットはその画面状態から続ける。別セットへハードカットするな。",
  "continuity.noImage": "第{{n}}段から続ける（静止画なし——文字資料のみ合わせる）。",
  "continuity.identity": "身元：同一人物——顔・髪・体型・衣装色・小物。リスタイルや年齢変更をするな。",
  "continuity.space": "空間：同じ場所——建築・素材・間取り・光の向き。劇が求めるときだけわずかな時間変化可。",
  "continuity.action": "動作：前フレームの姿勢・視線・動きを引き継げ。別の立ち位置へ切るな。",
  "continuity.prevContext": "前段の文脈：{{snippet}}",
  "continuity.noText": "字幕・ロゴ・透かしなし。",
  "directorLabel.lock": "台詞ロック",
  "directorLabel.story": "物語：",
  "directorLabel.style": "作風：",
  "directorLabel.cast": "出演：",
  "directorLabel.location": "場所：",
  "directorLabel.prop": "小道具：",
  "directorLabel.primaryChar": "主役：",
  "directorLabel.mood": "心情：",
  "directorLabel.atmo": "雰囲気：",
  "directorLabel.camera": "カメラ：",
  "directorLabel.sfx": "効果音：",
  "directorLabel.action": "動作：",
  "directorLabel.expr": "表情：",
  "directorLabel.speech": "台詞：",
  "directorLabel.notes": "演出メモ：",
  "directorLabel.identity": "身元：",
  "directorLabel.space": "空間：",
  "directorLabel.ref": "参考図",
  "directorLabel.beatN": "第{{n}}段 · ",
  "directorLabel.beatNsec": "第{{n}}段 · {{s}}秒",
  "directorLabel.hardRules": "生成の鉄則",
  "directorLabel.identityLock": "身元ロック",
  "directorLabel.spaceLock": "空間ロック",
  "storyBeats.system": "あなたはAI動画用の短編ドラマ「タイムライン・ビート」を書く。\n各ビート＝短いクリップ一本分の撮影脚本（一言の台詞ではない）。\n心情・雰囲気・動作・表情・任意のカメラ／効果音、0〜複数の台詞（よく1–4）を必ず含める。\nJSON配列だけを返す（フェンス禁止）。各要素の形：\n{\"characterName\":\"…\",\"characterNames\":[\"…\"],\"sceneHint\":\"…\",\"propName\":\"…\",\"mood\":\"…\",\"atmosphere\":\"…\",\"camera\":\"…\",\"sfx\":\"…\",\"units\":[{\"type\":\"action\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"expression\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"dialogue\",\"who\":\"…\",\"line\":\"…\",\"tone\":\"…\",\"parenthetical\":\"…\"},{\"type\":\"note\",\"text\":\"…\"}]}\n規則：\n- dialogue.line は口に出す言葉だけ。ト書きを混ぜない。\n- 身体動作は action、表情は expression、言い方は tone／parenthetical。\n- 短い会話や独白では複数の dialogue を勧める。\n- 台詞なしの動作ビートも可。\n- 4–8本。キャスト名は提供リストのみ。\n- 対立・見える動作・撮れる細部。\n- タイトル・作風・キャスト・場面に忠実。勝手に世界を広げるな。\n- 台詞はキャスト表の主言語で書く。ビートごとに言語を変えない。指定以外へ翻訳しない。",
  "storyBeats.userLead": "以下のキャスト・場面・小道具・作風・指示をすべて使い、短いクリップ脚本ビートを生成せよ。",
  "storyBeats.eachBeat": "各ビートに心情・雰囲気・動作／表情、任意の複数台詞が必要。",
  "storyBeats.story": "物語：{{title}}",
  "storyBeats.style": "作風：{{style}}",
  "storyBeats.userDir": "ユーザー指示：{{idea}}",
  "storyBeats.cast": "キャスト：",
  "storyBeats.scenes": "場面：",
  "storyBeats.props": "小道具：{{props}}",
  "storyBeats.returnJson": "ビートのJSON配列だけを返せ。",
  "storyBeats.noCast": "（キャストなし）",
  "storyBeats.noScenes": "（場面なし — sceneHint に場所を書いてよい）",
  "storyBeats.none": "（なし）",
  "videoPolish.system": "短編ドラマ用AIの 画像から動画 向けに、最終演出プロンプトを一条だけ書く。\nプロンプト本文だけを返す。markdownフェンス・見出し・解説は禁止。\n規則：\n- 演出文はユーザー界面言語。キャラ名と台詞言語の指定は明確に。\n- 人物スチール：身元ロック。場所プレート：空間ロック。材料が指名しない新しい顔を足すな。\n- 見た目・動き・台詞・雰囲気に効く資料はすべて使え。空欄は略してよい。\n- 材料とseedだけで撮れる細部を補う。固定サンプル世界やDemo事実を持ち込むな。\n- 長い soul.md は演技と身元の要点に圧縮し、全文貼るな。\n- 尺は材料の実秒数。動作は連続。字幕・ロゴ・透かし・無関係な通行人なし。\n- 脚本が求めない限り人体は正常（両手両足）。\n- 複数キャラは各自を一貫。主焦点を先に。\n- 生成の鉄則 があれば残し、出力の末尾へ（最優先）。\n- 台詞ロック は必須。削除・改変・翻訳するな。言語コードはフルネームに。主言語を守れ。クリップ間で言語を変えるな。\n- 演出修正は雰囲気／動作のみ。生成の鉄則 を破るな。",
  "videoPolish.hardRulesKeep": "生成の鉄則（最優先——各行を残せ。[キャラクター · 名] などのラベルを消すな）。完全な生成の鉄則ブロックを出力の末尾に置け。弱めたり付け替えたりするな。",
  "clip.task": "任務：短編ドラマのタイムライン・クリップ（画像から動画）。",
  "clip.hasRef": "参照スチールが付く場合あり——関係するなら身元／場所の連続性をロック。",
  "clip.characters": "キャラクター：",
  "clip.scene": "場面：",
  "clip.prop": "小道具：",
  "clip.action": "動作ガイド：",
  "clip.beat": "ビート／台詞：",
  "clip.prev": "前クリップの連続性：",
  "clip.revision": "演出修正（必ず従え）：",
  "clip.templateDraft": "テンプレ草案（改善せよ）：",
  "intro.task": "任務：自己紹介のキャスティング短編（画像から動画）。",
  "intro.hasRef": "参照スチールは動画APIへ渡す——その画像の身元にロックせよ。",
  "intro.noRef": "本文にスチール経路はない。それでもプロフィールの外見／衣装にロック。",
  "intro.dossier": "キャラクター資料：",
  "intro.templateDraft": "テンプレ草案（改善せよ。資料を無視するな）：",
  "common.durationAspect": "尺：{{seconds}}秒。画角：{{aspect}}。",
  "common.templateDraft": "テンプレ草案：",
  "improve.mode": "改善モード：以下の全ソースを統合して完全な結果を出せ。ユーザーが身元変更を明示しない限り核は保て。",
  "improve.draftDefault": "現在のフォーム欄（入力済み）：",
  "improve.userRequest": "ユーザー改善要求（空＝すべて磨いて統合）：",
  "improve.emptyDefault": "（短編ドラマ continuity のため全欄を磨く）",
  "improve.createDefault": "構想／方向：",
  "improve.explicitContext": "本リクエストに明示された文脈のみ（continuity 用。他のサンプル世界を持ち込むな）：",
  "improve.storyTitle": "物語タイトル：{{title}}",
  "improve.styleNote": "作風メモ：{{style}}",
  "improve.closingDefault": "完全な結果を今すぐ出力せよ。",
  "storyMeta.system": "あなたは短編ドラマのショーランナー。タイトルと構想から視覚スタイル聖書と生成鉄則を書け。JSONのみ返せ。",
  "storyMeta.draftLabel": "現在の物語フィールド：",
  "storyMeta.createLabel": "物語の構想／タイトル：",
  "storyMeta.emptyPolish": "（視覚スタイルと鉄則を磨く）",
  "storyMeta.closing": "JSONのみ：{\"styleNote\":\"…\",\"hardRules\":\"…\"}。両キー必須。",
  "storyMeta.contextLabel": "物語コンテキスト（キャスト／場面／小道具）：",
  "character.system": "あなたはAI動画向けの短編ドラマ・キャラクター設定者。ideaに従い完全なキャラ聖書をJSONだけで出せ。spokenLanguagesはBCP-47配列。",
  "character.draftLabel": "現在のプロフィール欄：",
  "character.soulLabel": "リンク済み soul.md／キャラ聖書：",
  "character.createLabel": "キャラクター idea：",
  "character.emptyPolish": "（soulとフォームを統合して磨く）",
  "character.closing": "完全なJSONを今すぐ。必須キー：{{keys}}。",
  "scene.system": "あなたは短編ドラマの場所／場面デザイナー。撮れる場所聖書＋本場の脚本断片をJSONだけで出せ。",
  "scene.draftLabel": "現在の場面フォーム：",
  "scene.charsLabel": "物語のキャラ：",
  "scene.propsLabel": "物語の小道具：",
  "scene.priorLabel": "既存場面（continuity）：",
  "scene.createLabel": "場面 idea：",
  "scene.emptyPolish": "（場所と脚本を磨く）",
  "scene.closing": "完全なJSONを今すぐ。必須キー：{{keys}}。",
  "prop.system": "あなたは短編ドラマの小道具デザイナー。JSONだけ返せ。見た目・材質・状態を具体的に。",
  "prop.draftLabel": "現在の小道具フォーム：",
  "prop.createLabel": "小道具 idea：",
  "prop.emptyPolish": "（小道具の見た目を磨く）",
  "prop.closing": "完全なJSONを今すぐ。必須キー：{{keys}}。",
  "prop.fallbackName": "小道具",
  "action.system": "あなたは短編ドラマの動作監督。有効なJSONだけ出せ。部位・テンポ・重量・経路を具体的に。",
  "action.storyContext": "物語脈絡（任意）：{{title}}",
  "action.styleNote": "作風メモ：{{style}}",
  "action.existingDraft": "既存ドラフト（磨いて補完）：",
  "action.userIdea": "ユーザー構想：{{idea}}",
  "action.closing": "JSONのみ。必須キー：{{keys}}。",
  "profile.mustEveryKey": "このリストの全キーを必ず出せ：{{keys}}。",
  "profile.valuesAreStrings": "各値はJSON文字列。nullや配列は不可。本当に不明なときだけ空文字。",
  "profile.visualTagsRule": "visualTagsは界面言語のカンマ区切り文字列。JSON配列は禁止。",
  "profile.fillConcrete": "短編ドラマ continuity のため具体的に埋めよ。",
  "common.rules": "規則：",
  "common.none": "（なし）",
  "intro.soul": "soul.md（演技／身元の完全な出典）：\n{{soul}}",
  "intro.matchBible": "（キャラ聖書の言語に合わせる）",
  "invent.sources": "根拠の優先順：（1）ユーザー構想／指示、（2）記入済みフォーム、（3）このプロンプトに書かれた追加文脈のみ、（4）添付参照画像。",
  "invent.create": "作成モード（空／薄いフォーム）：構想／画像から自由に創作し、必須キーを空にするな。",
  "invent.improve": "改善モード：下書きと一貫するよう磨き、欠欄を埋めよ。身元変更は明示されたときだけ。",
  "invent.noImport": "このプロンプトに無い身元・筋・天候・職業・場所・時代・作風を持ち込むな（active 物語、Demo、既定世界禁止）。",
  "invent.storyBlock": "物語／作風ブロックがある場合は continuity のみに使え。明示された構想を上書きするな。",
  "character.keysLead": "JSONオブジェクトのみ。キー：{{keys}}",
  "character.ruleSpoken": "spokenLanguages：話す言語の BCP-47 配列。無言なら []。",
  "character.ruleIdentity": "多角度シートと動画で身元を一貫させよ。",
  "scene.keysLead": "JSONオブジェクトのみ。キー：{{keys}}",
  "scene.suggestLead": "物語「{{title}}」の第{{n}}場として使える場所を提案せよ。",
  "scene.suggestPlotFocus": "筋の焦点：{{label}}",
  "scene.suggestStyle": "作風：{{style}}",
  "scene.suggestExisting": "既存の場所：{{titles}}",
  "scene.suggestChars": "キャラ（文脈）：",
  "scene.suggestProps": "小道具（文脈）：",
  "scene.suggestSegment": "選んだ筋の詳細：",
  "scene.suggestBeats": "物語の場／ビート：",
  "scene.suggestClosing": "完全な場面JSONを返せ。再利用できる独立した場所を設計せよ。",
  "scene.fallbackName": "場所",
  "scene.ideaFromImage": "添付写真から場所プロフィールを完全に埋めよ。",
  "scene.polishIdea": "磨く",
  "prop.keysLead": "JSONのみ。キー：{{keys}}",
  "action.fieldsLead": "欄：{{keys}}。",
  "soul.system": "短編ドラマ用 production soul.md を書け。完全なMarkdownのみ。見出しを守れ。spokenLanguages を尊重せよ。界面言語で書け。",
  "soul.improveMode": "改善モード：プロフィール＋既存soulを統合した完全な soul.md を出せ。",
  "soul.createMode": "このプロフィールから完全な soul.md を書け（別人にすり替えるな）：",
  "soul.profileFields": "プロフィール欄：",
  "soul.existing": "既存 soul.md（有用な細部を捨てるな）：",
  "soul.userRequest": "ユーザー指示：{{request}}",
  "soul.extraContext": "追加文脈（有用なら使え；プロフィール優先）：",
  "soul.returnOnly": "soul.md の本文だけ返せ。",
  "wardrobe.system": "短編ドラマの衣装顧問。JSON一つだけ。artStyle は {{styleIds}} のいずれか。具体的な素材・色・輪郭。未成年の性化禁止。",
  "wardrobe.improveMode": "改善／提案：下の全欄と筋を使え。",
  "wardrobe.characterForm": "キャラ（全フォーム）：",
  "wardrobe.soulExcerpt": "soul.md 抜粋：\n{{soul}}",
  "wardrobe.userRequest": "ユーザー指示：{{request}}",
  "wardrobe.storyContext": "物語／制作文脈（あれば使え；別世界を作るな）：",
  "wardrobe.style": "作風：{{style}}",
  "wardrobe.segment": "選んだ筋：{{label}}",
  "wardrobe.sceneContext": "場面／ビート抜粋：",
  "wardrobe.noScenes": "（場面はまだ無い）",
  "wardrobe.proposeNew": "筋に合う新しい衣装を提案（既存と重複させるな）。",
  "fill.system": "空欄だけ埋めよ。これらのキーだけのJSON：{{keys}}。各値は非空文字列。配列禁止。",
  "fill.userPartial": "既存の部分設定（矛盾させるな）：",
  "fill.userOnly": "これらの空キーだけ埋めよ：{{keys}}。",
  "fill.userReturn": "そのキーだけのJSON。各値は非空文字列。",
  "imageGen.multiRef": "追加参照が{{n}}枚。第一枚が編集ベース。身元を全参照と一致させよ。",
  "residual.sceneLink": "第{{n}}場：{{short}}",
  "residual.beatSegment": "ビート {{n}} · {{who}}{{tail}}",
  "residual.unknown": "未指定",
  "residual.story": "物語",
  "beat.mood": "[MOOD] {{text}}",
  "beat.atmo": "[ATMO] {{text}}",
  "beat.camera": "[CAMERA] {{text}}",
  "beat.sfx": "[SFX] {{text}}",
  "beat.action": "[ACTION] {{text}}",
  "beat.actionWho": "[ACTION|{{who}}] {{text}}",
  "beat.expr": "[EXPR] {{text}}",
  "beat.exprWho": "[EXPR|{{who}}] {{text}}",
  "beat.dialogue": "[DIALOGUE|{{who}}] {{body}}",
  "beat.dialogueTone": "[DIALOGUE|{{who}}|{{tone}}] {{body}}",
  "beat.whoUnknown": "?",
  "beat.template": "[MOOD] tense, hesitant\n[ATMO] door-gap warm light; rain on ground\n[CAMERA] medium shot, push to hands\n[SFX] rain, fabric rustle\n[ACTION|Name] removes helmet; stares at the door light; hand into jacket pocket\n[EXPR|Name] furrowed brow, breath catches\n[DIALOGUE|Name|low, hoarse] また雨か……\n[DIALOGUE|Name|aside] （間）まだ、そこにいるのか？",
  "vision.preamble": "参照静止画が添付されている。この{{what}}の全欄を主に画像から埋めよ。構想／下書きで補ってよい。",
  "vision.character": "キャラ（名、外見、衣装、年齢、性別、タグ）",
  "vision.scene": "場所（題、説明、光、雰囲気、装置、タグ）",
  "vision.prop": "小道具（名、説明、材質、寸法、状態、タグ）",
  "vision.action": "動作（名、説明、テンポ、意図、カメラ、タグ）",
  "vision.costume": "衣装（名、完全な造形）",
  "still.header": "短編ドラマ用の単一キーフレーム静止画。計画ショットに合うヒーローフレーム。文字・ロゴ・透かし禁止。",
  "still.revision": "この静止画への改善要求（必須）：{{notes}}",
  "still.regenTask": "任務：画像から動画 監督プロンプトを改訂し、キーフレーム概要としても使えるようにせよ。",
  "still.userImprove": "ユーザー改善要求：\n{{notes}}",
  "still.currentPrompt": "現在の専門プロンプト：",
  "still.hardRules": "生成の鉄則（出力末尾に残せ。弱めるな）：",
  "mediaGen.writeOne": "短編ドラマ用の最終静止画プロンプトを「1本」書け。",
  "mediaGen.returnOnly": "プロンプト本文だけ。markdown禁止。",
  "mediaGen.singleComposite": "単一合成画像を記述せよ。",
  "mediaGen.lockRefs": "添付画像は Ref# 順の根拠。身元／衣装／場所／小道具をロック。別物に替えるな。",
  "mediaGen.videoSystem": "短編ドラマの 画像から動画 監督プロンプト作者。",
  "mediaGen.videoMerge": "材料を1本の専門ビデオプロンプトに統合せよ。",
  "mediaGen.videoInclude": "身元ロック、カメラ、演技／台詞、リズム、光の連続。",
  "mediaGen.videoFacts": "材料と seed の事実だけ。Demo 世界を持ち込むな。",
  "mediaGen.videoNoSwap": "参照があるとき別俳優／場所／小道具に替えるな。",
  "mediaGen.videoHardRules": "生成の鉄則 があれば末尾へ。",
  "mediaGen.imageSystem": "短編ドラマ静止画プロンプト監督。",
  "mediaGen.imageMergeStills": "選んだ材料と添付静止画を1本の出図プロンプトにせよ。",
  "mediaGen.imageMergeText": "選んだテキスト材料を1本の出図プロンプトにせよ。",
  "mediaGen.imagePriority": "最優先：添付の顔／衣装／場所／小道具を一致させよ。",
  "mediaGen.imageNoSwap": "キャスト静止画があるとき無関係な人物や店に替えるな。",
  "mediaGen.imageFacts": "材料と seed の事実だけ。",
  "mediaGen.imageLayout": "多コマなら正確なコマ数と溝を保て。",
  "mediaGen.imagePackage": "LAYOUT があるならそのレイアウトを厳密に実行せよ。",
  "mediaGen.imageHardRules": "生成の鉄則 があれば末尾へ。",
  "mediaGen.directorFallback": "図生動画：このキーフレームから短編クリップを動かせ。身元・衣装・場所・構図をロック。",
  "mediaGen.directorFallbackCam": "カメラと演技を明確に。字幕・透かし禁止。",
  "charIntro.task": "図生動画：参照の同一人物で短い自己紹介クリップ。",
  "charIntro.identityLock": "身元ロック：顔・髪・体・年齢・衣装・色を参照と一致させよ。",
  "charIntro.personality": "性格／気配：{{personality}}。",
  "charIntro.backstory": "背景：{{backstory}}。",
  "charIntro.relationships": "関係：{{relationships}}。",
  "charIntro.soul": "Soul 抜粋（演技出典）：{{soul}}",
  "charIntro.performance": "演技：ゆるいプッシュインまたは手持ち；カメラ目線；{{manner}}。",
  "charIntro.speech": "口：短い自己紹介のように動く。声：{{voice}}。",
  "charIntro.beat": "自然な静止 → 微笑／会釈 → 短い紹介ジェスチャ → ホールド。",
  "charIntro.lighting": "静止画と一致する光。字幕・ロゴ・他人禁止。",
  "sceneIntro.task": "図生動画：同一場所の紹介／確立ショット。",
  "sceneIntro.spaceLock": "空間ロック：建築・材質・看板・間取り・色を参照と一致させよ。",
  "sceneIntro.name": "地名：{{name}}。",
  "sceneIntro.place": "場所の説明：{{place}}。",
  "sceneIntro.spaceType": "空間タイプ：{{type}}。",
  "sceneIntro.time": "時間帯：{{time}}。",
  "sceneIntro.weather": "天候：{{weather}}。",
  "sceneIntro.moodLight": "雰囲気：{{mood}}。照明：{{lighting}}。",
  "sceneIntro.palette": "色：{{palette}}。",
  "sceneIntro.setDressing": "装置：{{set}}。",
  "sceneIntro.tags": "視覚タグ：{{tags}}。",
  "sceneIntro.art": "作風：{{art}}。",
  "sceneIntro.ambient": "環境（UI字幕なし）：{{sound}}。",
  "sceneIntro.scriptCue": "場のヒント（雰囲気のみ）：{{cue}}。",
  "sceneIntro.camera": "カメラ：{{camera}}。材料に無い新しい顔・ロゴ・字幕を足すな。",
  "sceneIntro.beat": "確立 → 環境の微動 → 静止。",
  "propIntro.task": "図生動画：同一小道具のヒーロー紹介。",
  "propIntro.objectLock": "物体ロック：輪郭・材質・色・刻印・摩耗・比率を参照と一致させよ。",
  "propIntro.name": "小道具名：{{name}}。",
  "propIntro.look": "外見：{{look}}。",
  "propIntro.material": "材質：{{material}}。",
  "propIntro.size": "寸法：{{size}}。",
  "propIntro.condition": "状態：{{condition}}。",
  "propIntro.tags": "視覚タグ：{{tags}}。",
  "propIntro.art": "作風：{{art}}。",
  "propIntro.camera": "きれいな卓上でゆるい周回またはプッシュイン。",
  "propIntro.beat": "ヒーロー静止 → 微光／微回転 → 静止。",
  "propIntro.noHands": "静止画に無い手・顔・字幕・透かし・余分な小道具禁止。",
  "costumeIntro.task": "図生動画：同一衣装の紹介クリップ。",
  "costumeIntro.wardrobeLock": "衣装ロック：輪郭・布・色・層・小物を参照と一致させよ。",
  "costumeIntro.identityOrProduct": "人がいれば顔／体をロックし布は微動可。トルソー／平置きなら商品構図。",
  "costumeIntro.name": "ルック名：{{name}}。",
  "costumeIntro.desc": "衣装：{{look}}。",
  "costumeIntro.art": "作風：{{art}}。",
  "costumeIntro.camera": "ゆるいプッシュインまたは周回。",
  "costumeIntro.beat": "静止 → 布の垂れ／袖口の微動／金具の反射 → 静止。",
  "costumeIntro.forbid": "新しい顔・字幕・ロゴ・エロポーズ禁止。",
  "costumeIntro.fallbackName": "ルック",
  "actionIntro.lead": "短編ドラマ動作デモ：「{{name}}」。",
  "actionIntro.intention": "意図：{{intention}}",
  "actionIntro.body": "身体／テンポ：{{body}}",
  "actionIntro.camera": "カメラ：{{camera}}",
  "actionIntro.closing": "滑らか。字幕なし。キーフレームに従え。",
  "sceneIntroPolish.task": "任務：場所紹介／確立クリップ（図生動画）。",
  "sceneIntroPolish.hasRef": "参照場所静止画あり — 空間身元をロック。",
  "sceneIntroPolish.noRef": "静止画パスなし。場所聖書にロック。",
  "sceneIntroPolish.dossier": "場所ファイル：",
  "sceneIntroPolish.scriptCue": "脚本ヒント（雰囲気のみ）：\n{{script}}",
  "sceneIntroPolish.emptySet": "空セット優先。新しい顔禁止。字幕・ロゴ禁止。",
  "propIntroPolish.task": "任務：小道具ヒーロー紹介（図生動画）。",
  "propIntroPolish.hasRef": "参照小道具静止画あり — 物体身元をロック。",
  "propIntroPolish.noRef": "静止画パスなし。小道具ファイルにロック。",
  "propIntroPolish.dossier": "小道具ファイル：",
  "propIntroPolish.noHands": "新しい手や顔禁止。字幕・ロゴ禁止。",
  "costumeIntroPolish.task": "任務：衣装／ルック紹介（図生動画）。",
  "costumeIntroPolish.hasRef": "参照あり — 人なら身元＋衣装、トルソーなら輪郭と材質。",
  "costumeIntroPolish.noRef": "静止画なし。衣装説明にロック。",
  "costumeIntroPolish.dossier": "衣装ファイル：",
  "costumeIntroPolish.fabric": "布の微動のみ。新しい顔・字幕・ロゴ禁止。",
  "actionIntroPolish.task": "任務：動作指導紹介クリップ（図生動画）。",
  "actionIntroPolish.hasRef": "参照あり — 演技身元をそのフレームにロック。",
  "actionIntroPolish.templateKeepRules": "テンプレート下書き（磨け；生成の鉄則 は末尾）：",
  "cover.posterLead": "短編ドラマのポスター／キーアート（16:9）。UIモック禁止。文字・ロゴ・透かし禁止。",
  "cover.titleMood": "物語タイトル（雰囲気のみ、画面に文字を出すな）：{{title}}。",
  "cover.styleBible": "作風：{{style}}",
  "cover.extraDir": "追加指示：{{idea}}",
  "cover.establishing": "ライブラリ表紙向きの確立ムード。強いシルエット。",
  "cover.medium": "指定 medium に合わせ、構図をはっきり。",
  "cover.editPrefix": "IMAGE EDIT：新しいポスター構図。主体の身元／雰囲気は残せ。",
  "cover.label": "物語カバー",
  "costumeFill.system": "映画衣装デザイナー。コンパクトJSONのみ。各値は文字列。画像があればその衣装を忠実に。",
  "costumeFill.idea": "構想：{{idea}}",
  "costumeFill.polish": "衣装下書きを磨け。",
  "costumeFill.required": "必須キー：name, description, artStyle, hardRules。欠けると無効。",
  "costumeFill.fallbackName": "ルック",
  "segment.entireStory": "全編（すべての場）",
  "segment.noStory": "物語未選択（キャラ資料のみ）",
  "vision.inventFromImage": "添付の参照画像からこの{{kind}}のプロフィールを完全に埋めよ。",
  "vision.polishAll": "全欄を磨いて統合せよ",
  "story.untitled": "無題の短編ドラマ",
  "action.castIdentityNote": "参照素材 {{count}} 枚：各パネルで顔／体を添付キャストと一致させよ。",
  "tpl.system.polishOnly": "レシピ polish-only：核の身元と世界を保て。文言だけ磨け。時代・天候・職業・場所やサンプル世界を発明するな。口語を発明するな。既定の鉄則をプロファイルに書くな。",
  "tpl.system.fillBlanks": "レシピ fill-blanks：空欄だけ埋めよ。記入済みは書き換えるな。新しい世界を作るな。",
  "tpl.system.invent": "レシピ invent：ユーザーが自由創作を許した。撮れる細部で必須欄を埋めよ。Demo や本リクエストに無い世界は持ち込むな。",
  "tpl.system.fromStory": "レシピ from-story：このリクエストに書かれたタイトル／作風／キャスト／場面だけを continuity に使え。衝突時はユーザー構想が勝つ。",
  "tpl.system.followAsset": "レシピ follow-asset：既にある作風と鉄則に従え。材料に無い映画的ルック・空セット・6–10秒を強いるな。尺はクリップの実秒数。",
  "tpl.system.cinematicLock": "レシピ cinematic-lock：映画的短編。場所は空セット優先。透かし・ロゴ・余分な顔禁止。人間は両手両腕両脚（非人以外）。",
  "tpl.system.identityLock": "レシピ identity-lock：顔／体／衣装／場所／小道具を添付スチールにロック。別人・別場所・別物に替えるな。",
  "tpl.system.restyle": "レシピ restyle：同一人物を保て。衣装・場所・時代はユーザーが求めたら変えてよい。別人にするな。",
  "pipeline.character.system": "短編AIドラマのキャラ聖書を磨く。各キャラ3–5行：見た目・声・動機・決め動作。この依頼にある事実だけ使え。",
  "pipeline.scene.system": "場面を視覚ビート表に展開。尺は材料の実秒。6–10秒と決めるな。提供された場面だけ。",
  "pipeline.props.system": "小道具の連続性を磨く。色・サイズ・登場時機。名簿に無い小道具を発明するな。",
  "pipeline.script.system": "短編ドラマの脚本家。各場面をAI動画向けの短い脚本に。実尺を使え。10秒上限を強いるな。形式：\n### SCENE <number> | id=<id>\n<script body>",
  "pipeline.script.noScenes": "（場面なし — 場所を発明するな）"
}