import type { PromptCopyTable } from './keys'

export const ptBrPromptCopy: PromptCopyTable = {
  "speechLock.named": "Trava de diálogo · Personagem \"{{who}}\": a fala audível E o lip-sync DEVEM ser só {{primaryName}} ({{primary}}). Não fale {{forbid}} nem outro idioma. Mantenha o mesmo idioma em cada clipe. Não traduza o diálogo.",
  "speechLock.unnamed": "Trava de diálogo · Personagens que falam: a fala audível E o lip-sync DEVEM ser só {{primaryName}} ({{primary}}). Não fale {{forbid}} nem outro idioma. Mantenha o mesmo idioma em cada clipe. Não traduza o diálogo.",
  "speechLock.namedMulti": "Trava de diálogo · Personagem \"{{who}}\": a fala audível E o lip-sync DEVEM ser {{primaryName}} ({{primary}}). Outros idiomas SÓ se a linha do roteiro já estiver nesse idioma: {{extras}}. Nunca um terceiro idioma. Não troque de idioma entre clipes. Não mude para {{forbid}}. Não traduza.",
  "speechLock.unnamedMulti": "Trava de diálogo · Personagens que falam: a fala audível E o lip-sync DEVEM ser {{primaryName}} ({{primary}}). Outros idiomas SÓ se a linha do roteiro já estiver nesse idioma: {{extras}}. Nunca um terceiro idioma. Não troque de idioma entre clipes. Não mude para {{forbid}}. Não traduza.",
  "hardRules.sealHeader": "REGRAS RÍGIDAS (prioridade máxima — cumprir; prevalecem em conflito):",
  "hardRules.sealFooter": "Se uma instrução anterior conflitar com as REGRAS RÍGIDAS, siga as REGRAS RÍGIDAS.",
  "hardRules.labelStory": "História",
  "hardRules.labelCharacter": "Personagem",
  "hardRules.labelScene": "Lugar",
  "hardRules.labelProp": "Objeto",
  "hardRules.labelAction": "Ação",
  "continuity.lockHeader": "TRAVAMENTO DE CONTINUIDADE (obrigatório na sequência):",
  "continuity.hasImage": "A imagem anexada é o QUADRO FINAL / keyframe do plano {{n}}. Este plano continua desse estado visual, sem corte seco para outro cenário.",
  "continuity.noImage": "Continuar do plano {{n}} (sem still — alinhar só ao dossiê).",
  "continuity.identity": "IDENTIDADE: a mesma pessoa — rosto, cabelo, proporções, cores do figurino, acessórios. Sem restyle nem mudança de idade.",
  "continuity.space": "ESPAÇO: o mesmo lugar — arquitetura, materiais, planta, luz. Só deriva sutil de horário se o plano exigir.",
  "continuity.action": "AÇÃO: retomar pose, olhar e movimento do quadro anterior; sem corte para outra disposição.",
  "continuity.prevContext": "Contexto do plano anterior: {{snippet}}",
  "continuity.noText": "Sem legendas, logos nem marcas d'água.",
  "directorLabel.lock": "Trava de diálogo",
  "directorLabel.story": "História: ",
  "directorLabel.style": "Estilo: ",
  "directorLabel.cast": "Elenco: ",
  "directorLabel.location": "Lugar: ",
  "directorLabel.prop": "Objeto: ",
  "directorLabel.primaryChar": "Personagem principal: ",
  "directorLabel.mood": "Humor: ",
  "directorLabel.atmo": "Atmosfera: ",
  "directorLabel.camera": "Câmera: ",
  "directorLabel.sfx": "Som: ",
  "directorLabel.action": "Ação: ",
  "directorLabel.expr": "Expressão: ",
  "directorLabel.speech": "Fala: ",
  "directorLabel.notes": "Notas: ",
  "directorLabel.identity": "Identidade: ",
  "directorLabel.space": "Espaço: ",
  "directorLabel.ref": "Imagem ",
  "directorLabel.beatN": "Plano {{n}} · ",
  "directorLabel.beatNsec": "Plano {{n}} · {{s}} s",
  "directorLabel.hardRules": "REGRAS RÍGIDAS",
  "directorLabel.identityLock": "Trava de identidade",
  "directorLabel.spaceLock": "Trava espacial",
  "storyBeats.system": "Você escreve PULSOS da linha do tempo para vídeo de curta.\nCada pulso = o roteiro de UM clipe curto (não uma fala só).\nDeve incluir humor, atmosfera, ações, expressões, câmera/sfx opcional e 0 ou mais falas (em geral 1–4).\nDevolva SÓ um array JSON (sem cercas). Forma de cada item:\n{\"characterName\":\"…\",\"characterNames\":[\"…\"],\"sceneHint\":\"…\",\"propName\":\"…\",\"mood\":\"…\",\"atmosphere\":\"…\",\"camera\":\"…\",\"sfx\":\"…\",\"units\":[{\"type\":\"action\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"expression\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"dialogue\",\"who\":\"…\",\"line\":\"…\",\"tone\":\"…\",\"parenthetical\":\"…\"},{\"type\":\"note\",\"text\":\"…\"}]}\nRegras:\n- dialogue.line são SÓ as palavras ditas; sem rubrica dentro da fala.\n- Corpo em action; rosto em expression; tom em tone/parenthetical.\n- Troca curta ou monólogo: vários dialogue no mesmo pulso.\n- Pulso só de ação é permitido.\n- Escreva 4–8 pulsos. Só nomes do elenco dado.\n- Conflito, ação visível, detalhe filmável.\n- Fiel ao título, estilo, elenco e cenas. Não alargue o mundo.\n- Cada dialogue.line no idioma principal do falante (lista de elenco). Não troque de idioma entre pulsos. Não traduza a menos que seja o idioma listado.",
  "storyBeats.userLead": "GERE beats de roteiro de clipe usando TODO o elenco, cenas, props, estilo e ideia abaixo.",
  "storyBeats.eachBeat": "Cada beat precisa de humor + atmosfera + ações/expressões + diálogo opcional.",
  "storyBeats.story": "História: {{title}}",
  "storyBeats.style": "Estilo: {{style}}",
  "storyBeats.userDir": "Indicação do usuário: {{idea}}",
  "storyBeats.cast": "Elenco:",
  "storyBeats.scenes": "Cenas:",
  "storyBeats.props": "Objetos: {{props}}",
  "storyBeats.returnJson": "Devolva só o array JSON dos beats.",
  "storyBeats.noCast": "(sem elenco)",
  "storyBeats.noScenes": "(sem cenas — invente lugares em sceneHint)",
  "storyBeats.none": "(nenhum)",
  "videoPolish.system": "Você escreve UM prompt final imagem para vídeo para um modelo de vídeo de drama curto.\nDevolva SÓ o texto do prompt — sem cercas markdown, título ou explicação.\nRegras:\n- Escreva o prompt de direção no idioma da interface; deixe claros nomes e códigos de idioma das falas.\n- Still de pessoa: Trava de identidade. Placa de lugar: Trava espacial. Não acrescente rostos novos a menos que os materiais os nomeiem.\n- Use TODOS os fatos de perfil / soul / beat / local que afetem visual, movimento, fala ou atmosfera; ignore campos vazios.\n- Invente só o necessário para um clipe filmável a partir dos materiais e do seed — não importe mundo-amostra, Demo ou fatos ausentes.\n- Condensar soul.md longo em beats de atuação e identidade; não colar a bíblia inteira.\n- Use a duração dos materiais (segundos reais do clipe). Ação contínua. Sem texto, logos, marcas d'água nem gente extra.\n- Anatomia humana correta salvo o roteiro (duas mãos, dois braços, duas pernas).\n- Se houver vários personagens, mantenha cada um; foco principal primeiro.\n- Se houver REGRAS RÍGIDAS, conserve-as e coloque no fim (prioridade máxima).\n- Trava de diálogo é obrigatório: não apague, reescreva nem traduza. Expanda códigos para nomes. Cada clipe usa a língua principal do personagem; não mude de idioma entre clipes; não traduza falas.\n- Revisão de direção pode refinar estilo/ação, mas NÃO violar REGRAS RÍGIDAS.",
  "videoPolish.hardRulesKeep": "REGRAS RÍGIDAS (prioridade máxima — conserve cada linha; rótulos de objeto como [Personagem · Nome] devem permanecer). Coloque o bloco completo de regras rígidas no FIM da saída. Não enfraqueça, apague nem reatribua.",
  "clip.task": "TAREFA: clipe da timeline de drama curto (imagem para vídeo).",
  "clip.hasRef": "Pode haver uma imagem de referência — trave identidade e lugar quando for o caso.",
  "clip.characters": "Personagens:",
  "clip.scene": "Cena:",
  "clip.prop": "Objeto:",
  "clip.action": "Guia de ação / movimento:",
  "clip.beat": "Beat / diálogo:",
  "clip.prev": "Continuidade do clipe anterior:",
  "clip.revision": "REVISÃO DO DIRETOR (obrigatória):",
  "clip.templateDraft": "Rascunho de modelo (melhorar):",
  "intro.task": "TAREFA: clipe de apresentação de elenco (imagem para vídeo).",
  "intro.hasRef": "A imagem de referência vai para a API de vídeo — trave a identidade nessa foto.",
  "intro.noRef": "Não há caminho de imagem neste texto; mesmo assim trave aparência e figurino do perfil.",
  "intro.dossier": "Dossiê do personagem:",
  "intro.templateDraft": "Rascunho de modelo (melhore; não ignore o dossiê):",
  "common.durationAspect": "Duração: {{seconds}}s. Proporção: {{aspect}}.",
  "common.templateDraft": "Rascunho de modelo:",
  "improve.mode": "MODO MELHORAR: una TODAS as fontes num resultado completo. Mantenha a identidade salvo pedido explícito.",
  "improve.draftDefault": "Campos atuais do formulário:",
  "improve.userRequest": "Pedido de melhoria (vazio = polir e unir tudo):",
  "improve.emptyDefault": "(polir todos os campos para continuidade)",
  "improve.createDefault": "Ideia / direção:",
  "improve.explicitContext": "Contexto explícito SÓ deste pedido (continuidade; não importe outro mundo):",
  "improve.storyTitle": "Título: {{title}}",
  "improve.styleNote": "Nota de estilo: {{style}}",
  "improve.closingDefault": "Entregue o resultado completo agora.",
  "storyMeta.system": "Você é showrunner. Escreva bíblia visual e regras duras. SÓ JSON.",
  "storyMeta.draftLabel": "Campos atuais da história:",
  "storyMeta.createLabel": "Ideia / título:",
  "storyMeta.emptyPolish": "(polir bíblia + hardRules)",
  "storyMeta.closing": "SÓ JSON: {\"styleNote\":\"…\",\"hardRules\":\"…\"}. As duas chaves são obrigatórias.",
  "storyMeta.contextLabel": "Contexto (elenco / cenas / objetos):",
  "character.system": "Você é designer de personagens. SÓ um JSON. spokenLanguages = array BCP-47.",
  "character.draftLabel": "Campos atuais do perfil:",
  "character.soulLabel": "soul.md / bíblia ligada:",
  "character.createLabel": "Ideia de personagem:",
  "character.emptyPolish": "(polir e integrar soul)",
  "character.closing": "JSON completo. Chaves: {{keys}}.",
  "scene.system": "Você é designer de locações. Bíblia do lugar + roteiro desta cena. SÓ JSON.",
  "scene.draftLabel": "Campos atuais da cena:",
  "scene.charsLabel": "Personagens da história:",
  "scene.propsLabel": "Objetos da história:",
  "scene.priorLabel": "Cenas anteriores (continuidade):",
  "scene.createLabel": "Ideia de cena:",
  "scene.emptyPolish": "(polir lugar + roteiro)",
  "scene.closing": "JSON completo. Chaves: {{keys}}.",
  "prop.system": "Você é designer de objetos. SÓ um JSON. Visual, material e estado concretos.",
  "prop.draftLabel": "Campos atuais do objeto:",
  "prop.createLabel": "Ideia de objeto:",
  "prop.emptyPolish": "(polir o visual)",
  "prop.closing": "JSON completo. Chaves: {{keys}}.",
  "prop.fallbackName": "Objeto",
  "action.system": "Você é diretor de movimento. JSON válido só. Corpo, tempo, peso, trajetórias.",
  "action.storyContext": "Contexto da história (opcional): {{title}}",
  "action.styleNote": "Nota de estilo: {{style}}",
  "action.existingDraft": "Rascunho existente para polir:",
  "action.userIdea": "Ideia do usuário: {{idea}}",
  "action.closing": "Só JSON. Chaves: {{keys}}.",
  "profile.mustEveryKey": "Você DEVE emitir CADA chave: {{keys}}.",
  "profile.valuesAreStrings": "Cada valor DEVE ser string JSON. Vazio só se desconhecido.",
  "profile.visualTagsRule": "visualTags: uma string separada por vírgulas. NUNCA um array JSON.",
  "profile.fillConcrete": "Preencha com detalhe concreto.",
  "common.rules": "Regras:",
  "common.none": "(nenhum)",
  "intro.soul": "soul.md (fonte de interpretação/identidade):\n{{soul}}",
  "intro.matchBible": "(seguir a bíblia do personagem)",
  "invent.sources": "Fontes da verdade, nesta ordem: (1) ideia/pedido, (2) formulário, (3) extras só se estiverem NESTE prompt, (4) imagem anexada.",
  "invent.create": "Modo criar: invente livremente a partir da ideia/imagem; não deixe chaves obrigatórias vazias.",
  "invent.improve": "Modo melhorar: polir o rascunho; não troque a identidade salvo pedido.",
  "invent.noImport": "NÃO importe identidade, trama, clima, ofício, lugar, época ou estilo de fora deste prompt.",
  "invent.storyBlock": "Bloco de história/estilo só para continuidade; não anule a ideia explícita.",
  "character.keysLead": "APENAS um JSON com chaves: {{keys}}",
  "character.ruleSpoken": "spokenLanguages: array BCP-47 dos idiomas FALADOS. [] se não verbal.",
  "character.ruleIdentity": "Identidade coerente em pranchas e vídeo.",
  "scene.keysLead": "APENAS um JSON com chaves: {{keys}}",
  "scene.suggestLead": "Proponha um LOCAL pronto como cena nº {{n}} de \"{{title}}\".",
  "scene.suggestPlotFocus": "Foco da trama: {{label}}",
  "scene.suggestStyle": "Estilo: {{style}}",
  "scene.suggestExisting": "Locais já existentes: {{titles}}",
  "scene.suggestChars": "Personagens (contexto):",
  "scene.suggestProps": "Objetos (contexto):",
  "scene.suggestSegment": "Detalhe do segmento:",
  "scene.suggestBeats": "Cenas / beats:",
  "scene.suggestClosing": "Devolva o JSON completo. Desenhe um local reutilizável e distinto.",
  "scene.fallbackName": "Local",
  "scene.ideaFromImage": "Invente o perfil completo do local a partir da foto anexada.",
  "scene.polishIdea": "Polir",
  "prop.keysLead": "APENAS um JSON com chaves: {{keys}}",
  "action.fieldsLead": "Campos: {{keys}}.",
  "soul.system": "Você escreve soul.md de produção. Só markdown completo. Respeite spokenLanguages. Idioma da interface.",
  "soul.improveMode": "MODO MELHORAR: una perfil + soul existente num soul.md completo.",
  "soul.createMode": "Escreva um soul.md completo a partir deste perfil (não invente outra pessoa):",
  "soul.profileFields": "Campos do perfil:",
  "soul.existing": "soul.md existente (una; não descarte detalhe útil):",
  "soul.userRequest": "Pedido: {{request}}",
  "soul.extraContext": "Contexto extra (útil sim; o perfil vence):",
  "soul.returnOnly": "Devolva só o markdown do soul.md.",
  "wardrobe.system": "Você é consultor de figurino. UM JSON só. artStyle deve ser um de: {{styleIds}}. Materiais e silhueta concretos. Nunca erotize menores.",
  "wardrobe.improveMode": "MODO MELHORAR / SUGERIR: use TODOS os campos e o contexto.",
  "wardrobe.characterForm": "Personagem (formulário completo):",
  "wardrobe.soulExcerpt": "Trecho soul.md:\n{{soul}}",
  "wardrobe.userRequest": "Pedido: {{request}}",
  "wardrobe.storyContext": "Contexto de produção (use se houver; não invente outro mundo):",
  "wardrobe.style": "estilo: {{style}}",
  "wardrobe.segment": "Segmento escolhido: {{label}}",
  "wardrobe.sceneContext": "Cena / beat:",
  "wardrobe.noScenes": "(ainda sem cenas)",
  "wardrobe.proposeNew": "Proponha um look NOVO que sirva (sem duplicar).",
  "fill.system": "Você completa campos vazios. JSON com EXATAMENTE estas chaves: {{keys}}. Cada valor é string não vazia. Nunca array.",
  "fill.userPartial": "Perfil parcial (não contradiga):",
  "fill.userOnly": "Preencha SÓ estas chaves: {{keys}}.",
  "fill.userReturn": "JSON só com essas chaves; valores não vazios.",
  "imageGen.multiRef": "{{n}} stills a mais: o primeiro é a base; mantenha a identidade em todos.",
  "residual.sceneLink": "Cena {{n}}: {{short}}",
  "residual.beatSegment": "Pulso {{n}} · {{who}}{{tail}}",
  "residual.unknown": "Desconhecido",
  "residual.story": "História",
  "beat.mood": "[MOOD] {{text}}",
  "beat.atmo": "[ATMO] {{text}}",
  "beat.camera": "[CAMERA] {{text}}",
  "beat.sfx": "[SFX] {{text}}",
  "beat.action": "[ACTION] {{text}}",
  "beat.actionWho": "[ACTION|{{who}}] {{text}}",
  "beat.expr": "[EXPR] {{text}}",
  "beat.exprWho": "[EXPR|{{who}}] {{text}}",
  "beat.dialogue": "[DIALOGUE|{{who}}] {{body}}",
  "beat.dialogueTone": "[DIALOGUE|{{who}}|{{tone}}] {{body}}",
  "beat.whoUnknown": "?",
  "beat.template": "[MOOD] tense, hesitant\n[ATMO] door-gap warm light; rain on ground\n[CAMERA] medium shot, push to hands\n[SFX] rain, fabric rustle\n[ACTION|Name] removes helmet; stares at the door light; hand into jacket pocket\n[EXPR|Name] furrowed brow, breath catches\n[DIALOGUE|Name|low, hoarse] Raining again…\n[DIALOGUE|Name|aside] (beat) Are you… still there?",
  "vision.preamble": "Há um still anexado. Preencha TODOS os campos deste {{what}} principalmente A PARTIR DA IMAGEM.",
  "vision.character": "identidade (nome, aparência, figurino, idade, gênero, tags)",
  "vision.scene": "local (título, descrição, luz, clima, cenário, tags)",
  "vision.prop": "objeto (nome, descrição, material, tamanho, estado, tags)",
  "vision.action": "ação (nome, descrição, ritmo, intenção, câmera, tags)",
  "vision.costume": "figurino (nome, descrição completa)",
  "still.header": "UM ÚNICO STILL-CHAVE para continuidade de vídeo (não um board multipainel). Um fotograma herói que bata com o plano. Sem texto, logos, marcas nem UI.",
  "still.revision": "MELHORIA DO USUÁRIO PARA ESTE STILL (obrigatória): {{notes}}",
  "still.regenTask": "TAREFA: revise o prompt de diretor imagem para vídeo e mantenha-o usável como brief de keyframe.",
  "still.userImprove": "PEDIDO DE MELHORIA:\n{{notes}}",
  "still.currentPrompt": "Prompt profissional atual:",
  "still.hardRules": "REGRAS RÍGIDAS (no fim; não enfraqueça):",
  "mediaGen.writeOne": "Escreva UM prompt final de imagem para um still de drama curto.",
  "mediaGen.returnOnly": "SÓ o texto do prompt — sem markdown.",
  "mediaGen.singleComposite": "Descreva UMA única imagem composta.",
  "mediaGen.lockRefs": "As imagens anexadas são a verdade visual (ordem Ref#). Não invente outra pessoa, loja ou objeto.",
  "mediaGen.videoSystem": "Você escreve prompts de diretor imagem para vídeo.",
  "mediaGen.videoMerge": "Una os materiais num ÚNICO prompt de vídeo.",
  "mediaGen.videoInclude": "Inclua: trava de identidade, câmera, atuação/diálogo, ritmo, luz.",
  "mediaGen.videoFacts": "Só fatos dos materiais e do seed. Sem Demo.",
  "mediaGen.videoNoSwap": "Com refs, não troque ator, local nem objeto.",
  "mediaGen.videoHardRules": "REGRAS RÍGIDAS no fim se houver.",
  "mediaGen.imageSystem": "Você é diretor de prompts de imagem.",
  "mediaGen.imageMergeStills": "Una materiais e stills num ÚNICO prompt de imagem.",
  "mediaGen.imageMergeText": "Una os textos num ÚNICO prompt de imagem.",
  "mediaGen.imagePriority": "Prioridade: rostos/figurinos/locais/objetos das imagens.",
  "mediaGen.imageNoSwap": "Não substitua por outra celebridade ou set alheio se houver stills de elenco.",
  "mediaGen.imageFacts": "Só fatos dos materiais e do seed.",
  "mediaGen.imageLayout": "Se for multipainel, preserve a contagem exata.",
  "mediaGen.imagePackage": "Se houver LAYOUT, o prompt DEVE aplicar esse layout exato.",
  "mediaGen.imageHardRules": "REGRAS RÍGIDAS no fim se houver.",
  "mediaGen.directorFallback": "IMAGEM-PARA-VÍDEO: anime este keyframe. Trave identidade, figurino, set e enquadramento.",
  "comic.taskHint": "História “{{title}}”, página de quadrinhos {{n}}: uma página pronta com exatamente {{count}} quadro(s). Identidade, figurino e lugar contínuos na página toda. Sem marca d’água nem moldura de interface.",
  "comic.panelCount": "A contagem de quadros é fixa: exatamente {{n}}.",
  "comic.lockSplash": "Trava de layout: um quadro em página inteira. Proibido: molduras extras, divisão, colagem.",
  "comic.lockYonkoma": "Trava: 4-koma vertical, 4 linhas × 1 coluna, de cima para baixo. Proibido: 2×2 ou faixa.",
  "comic.lockGrid2x2": "Trava: 2 linhas × 2 colunas. Proibido: faixa, 2×3, splash de página inteira.",
  "comic.lockGrid2x3": "Trava: 2 linhas × 3 colunas. Cima 1-2-3, baixo 4-5-6. Proibido: 2×2 ou 3×3.",
  "comic.lockGrid3x3": "Trava: 3 linhas × 3 colunas = nove quadros. Proibido: 2×2, 2×3 ou menos.",
  "comic.lockStrip": "Trava: uma única linha horizontal com exatamente {{n}} quadros. Proibido: várias linhas.",
  "comic.layoutSplash1": "Uma página alta: exatamente um quadro sangrado, sem calhas nem molduras extras.",
  "comic.layoutStrip2": "Uma página paisagem: dois quadros iguais lado a lado, calhas brancas grossas.",
  "comic.layoutStrip3": "Uma página paisagem: três quadros iguais numa linha, calhas brancas grossas.",
  "comic.layoutYonkoma": "Uma página alta: 4-koma vertical (4×1), calhas brancas grossas, leitura de cima para baixo.",
  "comic.layoutGrid2x2": "Uma página quadrada: grade 2×2, exatamente quatro quadros, calhas brancas, esquerda→direita e depois cima→baixo.",
  "comic.layoutStrip4": "Uma página paisagem larga: quatro quadros numa linha, calhas brancas grossas.",
  "comic.layoutGrid2x3": "Uma página paisagem: exatamente seis quadros, 2 linhas × 3 colunas (cima 1-2-3, baixo 4-5-6), calhas brancas, esquerda→direita e depois cima→baixo.",
  "comic.layoutGrid3x3": "Uma página quadrada: grade 3×3, exatamente nove quadros, calhas brancas, esquerda→direita e depois cima→baixo.",
  "comic.layoutWidePlusTwo": "Uma página alta: quadro largo no topo (~60 %) e dois menores embaixo, calhas brancas grossas.",
  "comic.layoutTwoPlusWide": "Uma página alta: dois quadros menores no topo e um largo de fechamento embaixo (~60 %), calhas brancas grossas.",
  "comic.layoutTallLeftTwo": "Uma página alta: quadro alto em toda a altura à esquerda e dois empilhados à direita, calhas brancas grossas.",
  "comic.layoutHeroPlusThree": "Uma página alta: quadro largo em cima e três menores numa fila embaixo, calhas brancas grossas.",
  "comic.layoutFocusQuad": "Uma página alta: médio no alto à esquerda, dois pequenos empilhados à direita, grande embaixo, calhas brancas grossas.",
  "comic.layoutStaggerFour": "Uma página alta: 2+2 deslocado — cima largo+estreito, baixo estreito+largo, calhas brancas grossas.",
  "comic.layoutDiagPairPlus": "Uma página alta: a metade de cima parte em diagonal em duas cunhas; embaixo um retângulo largo, calhas brancas grossas.",
  "comic.layoutHeroPlusFour": "Uma página alta: quadro largo em cima e quatro menores em 2×2 embaixo, calhas brancas grossas.",
  "comic.lockWidePlusTwo": "Trava: em cima um quadro largo. Embaixo exatamente dois menores. Proibido: três faixas iguais ou 2×2.",
  "comic.lockTwoPlusWide": "Trava: dois menores em cima, um largo embaixo. Proibido: três faixas iguais ou 2×2.",
  "comic.lockTallLeftTwo": "Trava: a esquerda ocupa toda a altura. Direita: dois empilhados. Proibido: 2×2 igual ou faixa horizontal.",
  "comic.lockHeroPlusThree": "Trava: metade de cima um largo. Embaixo exatamente três menores. Proibido: 2×2 ou quatro iguais.",
  "comic.lockFocusQuad": "Trava: médio no alto à esquerda, dois pequenos empilhados, grande embaixo. Proibido: 2×2 igual.",
  "comic.lockStaggerFour": "Trava: tamanhos deslocados — cima largo+estreito, baixo estreito+largo. Proibido: quatro quadrados iguais.",
  "comic.lockDiagPairPlus": "Trava: em cima duas cunhas em diagonal; embaixo um retângulo largo. Proibido: três faixas ou 2×2.",
  "comic.lockHeroPlusFour": "Trava: largo em cima; 2×2 de quatro embaixo. Exatamente cinco. Proibido: 3×3 ou 2×2 de página inteira.",
  "comic.readingYonkoma": "Leitura: só de cima para baixo (4-koma vertical).",
  "comic.readingWidePlusTwo": "Leitura: o largo de cima, depois os dois menores da esquerda para a direita.",
  "comic.readingTwoPlusWide": "Leitura: esquerda e direita em cima, depois o largo de baixo.",
  "comic.readingTallLeftTwo": "Leitura: o alto da esquerda, depois o superior direito, depois o inferior direito.",
  "comic.readingHeroPlusThree": "Leitura: o largo de cima, depois os três menores da esquerda para a direita.",
  "comic.readingFocusQuad": "Leitura: médio no alto à esquerda, os dois pequenos de cima para baixo, depois o grande de baixo.",
  "comic.readingStaggerFour": "Leitura: alto esquerdo, alto direito, baixo esquerdo, baixo direito.",
  "comic.readingDiagPairPlus": "Leitura: cunha superior esquerda, cunha inferior direita, depois o largo de baixo.",
  "comic.readingHeroPlusFour": "Leitura: o largo de cima, depois os quatro menores esquerda→direita e cima→baixo.",
  "comic.readingOrder": "Leitura: esquerda → direita, depois cima → baixo (4-koma vertical: só cima → baixo).",
  "comic.panelNumbers": "Números pequenos 1–{{n}} no canto superior esquerdo de cada quadro.",
  "comic.panelLine": "Quadro {{i}}/{{n}} ({{label}}): {{cap}}",
  "comic.panelEmpty": "Quadro {{i}}/{{n}} ({{label}}): um instante de história distinto e sequencial.",
  "comic.identity": "Mesma identidade, figurino e lugar em todos os quadros desta página.",
  "comic.finished": "É uma página de quadrinhos pronta, não uma colagem de fotos nem um mockup de interface.",
  "comic.layoutLead": "Diagramação: {{layout}}",
  "comic.prevPage": "Página anterior. Mantenha identidade, figurino e lugar; não copie a grade anterior.",
  "comic.ownPage": "Render existente desta página. Use como base de identidade / layout ao revisar.",
  "comic.galleryRef": "Still de identidade (elenco ou set). Combine rostos, figurino e lugar.",
  "comic.profileLine": "Página de quadrinhos {{n}} da história “{{title}}”.",
  "comic.styleBible": "Nota de estilo: {{note}}",
  "comic.artMedium": "Estilo artístico: {{art}}",
  "comic.fallbackClose": "Página impressa pronta. Calhas brancas grossas. Números pequenos. Sem marca d’água, UI nem colagem de álbum.",
  "comic.hardRules": "Regras rígidas",
  "comic.introTask": "Imagem para vídeo: anime a página pronta de “{{title}}”, página {{n}}, exatamente {{count}} quadro(s). Trave identidade, figurino e diagramação na imagem anexada.",
  "comic.introLock": "Trava: mesmos rostos, roupas, lugares, calhas e números da imagem. Não invente outra página nem outra pessoa.",
  "comic.introLayout": "Mantenha esta diagramação: {{layout}}",
  "comic.introCamera": "Câmera: avanço lento ou deslocamento suave na ordem de leitura. Só movimento de papel. Sem corte para outra diagramação.",
  "comic.introClose": "Sem marca d’água nem moldura de interface; não empilhe legendas além dos balões já desenhados.",
  "comic.dramaStillLock": "Trave identidade, figurino e lugar na prancha anexada, mas filme um plano de curta ao vivo — não um deslocamento sobre papel impresso.",
  "comic.dramaCamera": "Câmera e atuação: ritmo de curta-metragem, atuação clara, sincronia labial com as falas dos quadros. Continue a página anterior se houver imagem.",
  "comic.formatLockTall": "Formato da página: a prancha inteira deve ser vertical 9:16. Sem composição de paisagem.",
  "comic.formatLockSquare": "Formato da página: a prancha inteira deve ser quadrada 1:1.",
  "comic.formatLockWide": "Formato da página: a prancha inteira deve ser horizontal 16:9.",
  "art.photoCinematic": "Meio obrigatório: still cinematográfico fotorrealista. Câmera real, materiais naturais, correção de cinema. Deve parecer foto ou quadro de filme. Proibido: anime, cel, ilustração 2D, contorno cartoon, argila, CGI plástico.",
  "art.photoPortrait": "Meio obrigatório: retrato de estúdio fotorrealista. Softbox, nitidez de headshot comercial. Deve ser fotografia. Proibido: anime, tinta de quadrinhos, brinquedo 3D, cel chapado.",
  "art.photoDocumentary": "Meio obrigatório: foto documental fotorrealista. Luz natural, texturas honestas. Deve parecer tirada com câmera real. Proibido: anime, CGI estilizado, ilustração.",
  "art.cgiFilm": "Meio obrigatório: personagem 3D CGI de qualidade cinematográfica. Materiais PBR, realces com ray tracing. Deve parecer render 3D, não foto real nem anime 2D. Proibido: foto ao vivo, lineart de anime, tinta chapada de HQ.",
  "art.cgiStylized": "Meio obrigatório: 3D estilizado premium (CGI de longa). Formas legíveis, PBR suave. Deve ser CGI 3D. Proibido: live fotorrealista, cel 2D, HQ rabiscada.",
  "art.cgiClay": "Meio obrigatório: personagem 3D de argila / escultura. Argila fosca, formas esculpidas. Deve ler como escultura de argila. Proibido: foto de pele, cel de anime, HQ a tinta.",
  "art.animeModern": "Meio obrigatório: anime de TV japonês moderno 2D. Linha digital limpa, cel suave, olhos e mechas de anime. A imagem inteira deve ser anime 2D. Proibido: foto, poros reais, render 3D, tinta western só, óleo.",
  "art.animeShonen": "Meio obrigatório: visual-chave shonen 2D. Traço forte, cel contrastado, olhos nítidos. Deve ser shonen 2D. Proibido: foto, CGI 3D, aquarela só.",
  "art.animeShoujo": "Meio obrigatório: anime shoujo 2D. Linha delicada, degradês suaves, olhos luminosos. Deve ser shoujo. Proibido: foto, 3D duro, tinta áspera de HQ.",
  "art.animeGekiga": "Meio obrigatório: anime gekiga / realista 2D. Linha madura, paleta contida, claramente 2D. Proibido: foto ao vivo, chibi, CGI 3D puro.",
  "art.animeChibi": "Meio obrigatório: chibi / superdeformado 2D. Cabeça grande, corpo pequeno, traços simplificados. Deve ser chibi. Proibido: proporções fotorrealistas, 3D realista, live detalhado.",
  "art.donghua": "Meio obrigatório: key art de donghua chinês. Traje refinado, silhueta elegante, 2D ou 2,5D. Deve ler como donghua. Proibido: live de Hollywood, HQ de jornal western só.",
  "art.manhwa": "Meio obrigatório: manhwa / webtoon coreano colorido. Pintura digital suave, contornos limpos, cabelo brilhante. Deve ser manhwa 2D. Proibido: foto, argila 3D, tinta de herói só.",
  "art.comicWestern": "Meio obrigatório: quadrinhos ocidentais. Tinta segura, chapados ou cel limitado, formas gráficas. Deve ser ilustração de HQ. Proibido: foto, só olhos de anime, render de argila.",
  "art.conceptGame": "Meio obrigatório: concept art de personagem AAA. Folha pintada, silhueta forte. Deve parecer concept, não captura nem foto. Proibido: retrato foto puro, só chibi.",
  "art.illustrationSoft": "Meio obrigatório: ilustração digital suave. Pincel delicado, acabamento de livro. Deve ser ilustração pintada. Proibido: foto de câmera, cel duro, argila 3D.",
  "mediaGen.polishTask": "Tarefa: {{hint}}",
  "mediaGen.polishKind": "Tipo: {{kind}}",
  "mediaGen.polishMaterials": "—— Materiais ——",
  "mediaGen.polishEndMaterials": "—— Fim dos materiais ——",
  "mediaGen.polishRef": "Ref. nº{{n}} — {{title}}",
  "mediaGen.videoTaskHint": "Escreva uma direção profissional de imagem-para-vídeo a partir do quadro-chave ({{kind}}). Câmera, atuação e ritmo; trave o quadro-chave.",
  "mediaGen.directorFallbackCam": "Câmera e atuação claras; sem legendas nem marca d’água.",
  "charIntro.task": "IMAGEM-PARA-VÍDEO: anime a mesma pessoa num auto-casting curto.",
  "charIntro.identityLock": "TRAVA DE IDENTIDADE: mesmo rosto, cabelo, corpo, idade, figurino e cores.",
  "charIntro.personality": "Personalidade / vibe: {{personality}}.",
  "charIntro.backstory": "História: {{backstory}}.",
  "charIntro.relationships": "Relações: {{relationships}}.",
  "charIntro.soul": "Trecho soul (fonte de atuação): {{soul}}",
  "charIntro.performance": "Atuação: leve travelling ou câmera na mão; olha para a câmera; {{manner}}.",
  "charIntro.speech": "Fala: a boca se move como uma apresentação breve; voz: {{voice}}.",
  "charIntro.beat": "Idle natural → sorriso ou aceno → gesto breve → hold.",
  "charIntro.lighting": "Luz coerente com o still; sem texto, logos nem extra gente.",
  "sceneIntro.task": "IMAGEM-PARA-VÍDEO: anime o mesmo local como plano de estabelecimento.",
  "sceneIntro.spaceLock": "TRAVA DE ESPAÇO: mesma arquitetura, materiais, placas, planta e cor.",
  "sceneIntro.name": "Nome do local: {{name}}.",
  "sceneIntro.place": "Descrição: {{place}}.",
  "sceneIntro.spaceType": "Tipo de espaço: {{type}}.",
  "sceneIntro.time": "Hora do dia: {{time}}.",
  "sceneIntro.weather": "Clima: {{weather}}.",
  "sceneIntro.moodLight": "Clima: {{mood}}. Luz: {{lighting}}.",
  "sceneIntro.palette": "Paleta: {{palette}}.",
  "sceneIntro.setDressing": "Cenário: {{set}}.",
  "sceneIntro.tags": "Tags visuais: {{tags}}.",
  "sceneIntro.art": "Estilo: {{art}}.",
  "sceneIntro.ambient": "Ambiente (sem texto de UI): {{sound}}.",
  "sceneIntro.scriptCue": "Dica de beat (só atmosfera): {{cue}}.",
  "sceneIntro.camera": "Câmera: {{camera}}; movimento contínuo. Não acrescente rostos, logos nem texto salvo se os materiais já os mostrarem.",
  "sceneIntro.beat": "Estabelecer → vida ambiental sutil → hold.",
  "propIntro.task": "IMAGEM-PARA-VÍDEO: anime o mesmo objeto como intro de produto.",
  "propIntro.objectLock": "TRAVA DE OBJETO: mesma silhueta, materiais, cores, gravuras e desgaste.",
  "propIntro.name": "Nome: {{name}}.",
  "propIntro.look": "Aparência: {{look}}.",
  "propIntro.material": "Material: {{material}}.",
  "propIntro.size": "Tamanho: {{size}}.",
  "propIntro.condition": "Estado: {{condition}}.",
  "propIntro.tags": "Tags: {{tags}}.",
  "propIntro.art": "Estilo: {{art}}.",
  "propIntro.camera": "Órbita suave ou travelling lento em mesa limpa; luz coerente.",
  "propIntro.beat": "Hold → brilho / microgiro → hold.",
  "propIntro.noHands": "Sem mãos nem rostos novos se não estiverem no still; sem texto nem extras.",
  "costumeIntro.task": "IMAGEM-PARA-VÍDEO: anime o mesmo look como intro de figurino.",
  "costumeIntro.wardrobeLock": "TRAVA DE FIGURINO: mesma silhueta, tecidos, cores, camadas e acessórios.",
  "costumeIntro.identityOrProduct": "Se houver pessoa: trave rosto/corpo; se manequim/plano: enquadramento de produto.",
  "costumeIntro.name": "Nome do look: {{name}}.",
  "costumeIntro.desc": "Figurino: {{look}}.",
  "costumeIntro.art": "Estilo: {{art}}.",
  "costumeIntro.camera": "Leve travelling ou órbita; luz de moda coerente.",
  "costumeIntro.beat": "Hold → queda de tecido / brilho de ferragens → hold.",
  "costumeIntro.forbid": "Sem rostos novos, texto, logos nem pose erótica.",
  "costumeIntro.fallbackName": "Visual",
  "actionIntro.lead": "Vídeo demo da ação \"{{name}}\".",
  "actionIntro.intention": "Intenção: {{intention}}",
  "actionIntro.body": "Corpo/tempo: {{body}}",
  "actionIntro.camera": "Câmera: {{camera}}",
  "actionIntro.closing": "Movimento contínuo, sem texto; siga o still.",
  "sceneIntroPolish.task": "TAREFA: intro de local (imagem-para-vídeo).",
  "sceneIntroPolish.hasRef": "Still de local anexado — trave a identidade ESPACIAL.",
  "sceneIntroPolish.noRef": "Sem still; trave à bíblia do local.",
  "sceneIntroPolish.dossier": "Dossiê do local:",
  "sceneIntroPolish.scriptCue": "dica de roteiro (só atmosfera):\n{{script}}",
  "sceneIntroPolish.emptySet": "Set vazio; sem rostos novos. Sem texto nem logos.",
  "propIntroPolish.task": "TAREFA: intro herói de objeto (imagem-para-vídeo).",
  "propIntroPolish.hasRef": "Still de objeto anexado — trave o OBJETO.",
  "propIntroPolish.noRef": "Sem still; trave ao dossiê.",
  "propIntroPolish.dossier": "Dossiê do objeto:",
  "propIntroPolish.noHands": "Sem mãos nem rostos novos. Sem texto nem logos.",
  "costumeIntroPolish.task": "TAREFA: intro de figurino (imagem-para-vídeo).",
  "costumeIntroPolish.hasRef": "Still anexado — pessoa: identidade+roupa; manequim: silhueta e materiais.",
  "costumeIntroPolish.noRef": "Sem still; trave à descrição.",
  "costumeIntroPolish.dossier": "Dossiê de figurino:",
  "costumeIntroPolish.fabric": "Queda sutil de tecido; sem rostos novos nem texto.",
  "actionIntroPolish.task": "TAREFA: intro de guia de movimento (imagem-para-vídeo).",
  "actionIntroPolish.hasRef": "Still anexado — trave a identidade de atuação àquele quadro.",
  "actionIntroPolish.templateKeepRules": "Rascunho modelo (melhore; REGRAS RÍGIDAS no fim):",
  "cover.posterLead": "PÔSTER / KEY ART profissional 16:9. Não é mockup de UI. Sem texto, logo nem marca.",
  "cover.titleMood": "Título (só clima, não escreva na imagem): {{title}}.",
  "cover.styleBible": "Bíblia de estilo: {{style}}",
  "cover.extraDir": "Direção extra: {{idea}}",
  "cover.establishing": "Plano de estabelecimento evocativo para capa da biblioteca.",
  "cover.medium": "Respeite o medium; silhueta forte.",
  "cover.editPrefix": "Edição de imagem: nova composição de pôster. Mantenha identidade e clima. ",
  "cover.label": "Capa da história",
  "costumeFill.system": "Você é figurinista. Só JSON compacto. Se houver imagem, descreva ESSE look com fidelidade.",
  "costumeFill.idea": "Ideia: {{idea}}",
  "costumeFill.polish": "Polir o rascunho de figurino.",
  "costumeFill.required": "Chaves: name, description, artStyle, hardRules. Faltar = inválido.",
  "costumeFill.fallbackName": "Visual",
  "segment.entireStory": "Toda a história (todas as cenas)",
  "segment.noStory": "Nenhuma história (só ficha do personagem)",
  "vision.inventFromImage": "Descreva e invente um perfil completo de {{kind}} a partir da foto anexada.",
  "vision.polishAll": "Polir e unir todos os campos",
  "story.untitled": "Drama curto sem título",
  "action.castIdentityNote": "Stills de identidade ({{count}}): rosto/corpo iguais às referências de elenco em cada painel.",
  "tpl.system.polishOnly": "RECEITA só polir: mantenha identidade e mundo. Polir o texto. Não invente era, clima, ofício, lugar nem mundo-amostra. Não invente idioma falado. Não grave REGRAS RÍGIDAS padrão no perfil.",
  "tpl.system.fillBlanks": "RECEITA só vazios: preencha SÓ chaves vazias. Não reescreva o que já está preenchido. Não invente outro mundo.",
  "tpl.system.invent": "RECEITA inventar: o usuário autorizou criar livremente. Complete cada chave filmável. Não importe Demo nem mundo não implícito.",
  "tpl.system.fromStory": "RECEITA da história: use só título/estilo/elenco/cenas DESTE pedido. Em conflito, a ideia do usuário vence.",
  "tpl.system.followAsset": "RECEITA seguir ativo: siga o estilo já dado. Não force cinema, set vazio nem 6–10 s salvo se os materiais disserem. Use a duração real do clipe.",
  "tpl.system.cinematicLock": "RECEITA cine+anti-alucinação: visual cinematográfico; set vazio; sem marca, logo nem rostos extras; duas mãos/braços/pernas salvo não humano.",
  "tpl.system.identityLock": "RECEITA trava de identidade: trave rosto/corpo/roupa/lugar/objeto aos stills. Não substitua pessoa, lugar ou objeto.",
  "tpl.system.restyle": "RECEITA restyle: a mesma pessoa. Figurino, set e época podem mudar se pedido. Não troque de pessoa.",
  "pipeline.character.system": "Você refina bíblias de personagem. 3–5 linhas: visual, voz, motivo, gesto. Só fatos deste pedido.",
  "pipeline.scene.system": "Você expande cenas em folhas de beats. Use a duração real; não assuma 6–10 s. Só cenas dadas.",
  "pipeline.props.system": "Você refina continuidade de objetos. Cor, tamanho e quando aparece. Não invente objetos fora da lista.",
  "pipeline.script.system": "Você é roteirista. Um bloco compacto por cena para vídeo IA. Duração real; não force 10 s. Formato:\n### SCENE <number> | id=<id>\n<script body>",
  "pipeline.script.noScenes": "(sem cenas — não invente locais)",
  "keyArt.task": "Arte-chave {{n}} da história “{{title}}”. Uma imagem publicitária pronta. Sem quadrinhos, sem números de painel, sem interface.",
  "keyArt.lockCover": "PÔSTER DE CAPA: arte paisagem para o cartão da história. Deixe faixa segura para o título. Rostos legíveis. Não invente logo nem créditos falsos.",
  "keyArt.lockPoster": "PÔSTER VERTICAL: um único one-sheet. O herói se lê no telemóvel. Sem outros pôsteres no quadro.",
  "keyArt.lockStill": "STILL: um fotograma cinematográfico, como tirado do drama. Atuação natural, espaço real. Não é colagem.",
  "keyArt.lockPromo": "ARTE PROMOCIONAL: personagem e mundo no mesmo quadro. Silhueta forte, um humor. Não é folha de contacto.",
  "keyArt.lockSocial": "STORY SOCIAL: quadro vertical 9:16. Sujeito grande. Margens para texto no ecrã.",
  "keyArt.lockHeadshot": "CLOSE DO PROTAGONISTA: um rosto de frente a preencher o quadro, idêntico às referências. Ombros permitidos. Ninguém mais.",
  "keyArt.lockBust": "PROMO BUSTO: do peito para cima, gola do figurino visível, olhar à câmara.",
  "keyArt.lockGroup": "ELENCO: todos os personagens nomeados num quadro, mesmo mundo e mesma luz. Não omita nem troque um rosto.",
  "keyArt.formatLockTall": "BLOQUEIO DE FORMATO: a imagem inteira é um quadro alto 9:16. Sem composição paisagem.",
  "keyArt.formatLockSquare": "BLOQUEIO DE FORMATO: a imagem inteira é um quadro quadrado 1:1.",
  "keyArt.formatLockWide": "BLOQUEIO DE FORMATO: a imagem inteira é um quadro largo 16:9.",
  "keyArt.methodFreshLock": "MÉTODO: gerar uma imagem nova. As referências só fixam identidade. Não copie o recorte de uma toma antiga.",
  "keyArt.methodEditLock": "MÉTODO: editar a imagem própria anexa. Mantenha a composição salvo se o brief pedir o contrário.",
  "keyArt.methodIdentityLock": "MÉTODO: fixe os rostos nas referências do personagem. Pose, recorte e figurino podem mudar.",
  "keyArt.methodContinueLock": "MÉTODO: continue a partir da imagem anterior. As mesmas pessoas e o mesmo lugar, o plano seguinte da mesma filmagem.",
  "keyArt.briefLine": "Brief de direção: {{brief}}",
  "keyArt.beatLine": "Beat ligado: {{beat}}",
  "keyArt.close": "Imagem {{aspect}} concluída. Sem marca de água, sem moldura de interface, sem legendas extra.",
}
