import type { PromptCopyTable } from './keys'

export const ptBrPromptCopy: PromptCopyTable = {
  "speechLock.named": "Trava de diálogo · Personagem \"{{who}}\": a fala audível E o lip-sync DEVEM ser só {{primaryName}} ({{primary}}). Não fale {{forbid}} nem outro idioma. Mantenha o mesmo idioma em cada clipe. Não traduza o diálogo.",
  "speechLock.unnamed": "Trava de diálogo · Personagens que falam: a fala audível E o lip-sync DEVEM ser só {{primaryName}} ({{primary}}). Não fale {{forbid}} nem outro idioma. Mantenha o mesmo idioma em cada clipe. Não traduza o diálogo.",
  "speechLock.namedMulti": "Trava de diálogo · Personagem \"{{who}}\": a fala audível E o lip-sync DEVEM ser {{primaryName}} ({{primary}}). Outros idiomas SÓ se a linha do roteiro já estiver nesse idioma: {{extras}}. Nunca um terceiro idioma. Não troque de idioma entre clipes. Não mude para {{forbid}}. Não traduza.",
  "speechLock.unnamedMulti": "Trava de diálogo · Personagens que falam: a fala audível E o lip-sync DEVEM ser {{primaryName}} ({{primary}}). Outros idiomas SÓ se a linha do roteiro já estiver nesse idioma: {{extras}}. Nunca um terceiro idioma. Não troque de idioma entre clipes. Não mude para {{forbid}}. Não traduza.",
  "hardRules.sealHeader": "REGRAS RÍGIDAS (prioridade máxima — cumprir; prevalecem em conflito):",
  "hardRules.sealFooter": "Se uma instrução anterior conflitar com as REGRAS RÍGIDAS, siga as REGRAS RÍGIDAS.",
  "hardRules.labelStory": "História",
  "hardRules.labelCharacter": "Personagem",
  "hardRules.labelScene": "Lugar",
  "hardRules.labelProp": "Objeto",
  "hardRules.labelAction": "Ação",
  "continuity.lockHeader": "TRAVAMENTO DE CONTINUIDADE (obrigatório na sequência):",
  "continuity.hasImage": "A imagem anexada é o quadro final do plano {{n}}. Este plano continua desse estado visual, sem corte seco para outro cenário.",
  "continuity.noImage": "Continuar do plano {{n}} (sem still — alinhar só ao dossiê).",
  "continuity.identity": "IDENTIDADE: a mesma pessoa — rosto, cabelo, proporções, cores do figurino, acessórios. Sem restyle nem mudança de idade.",
  "continuity.space": "ESPAÇO: o mesmo lugar — arquitetura, materiais, planta, luz. Só deriva sutil de horário se o plano exigir.",
  "continuity.action": "AÇÃO: retomar pose, olhar e movimento do quadro anterior; sem corte para outra disposição.",
  "continuity.prevContext": "Contexto do plano anterior: {{snippet}}",
  "continuity.noText": "Sem legendas, logos nem marcas d'água.",
  "directorLabel.lock": "Trava de diálogo",
  "directorLabel.story": "História: ",
  "directorLabel.style": "Estilo: ",
  "directorLabel.cast": "Elenco: ",
  "directorLabel.location": "Lugar: ",
  "directorLabel.prop": "Objeto: ",
  "directorLabel.primaryChar": "Personagem principal: ",
  "directorLabel.mood": "Humor: ",
  "directorLabel.atmo": "Atmosfera: ",
  "directorLabel.camera": "Câmera: ",
  "directorLabel.sfx": "Som: ",
  "directorLabel.action": "Ação: ",
  "directorLabel.expr": "Expressão: ",
  "directorLabel.speech": "Fala: ",
  "directorLabel.notes": "Notas: ",
  "directorLabel.identity": "Identidade: ",
  "directorLabel.space": "Espaço: ",
  "directorLabel.ref": "Imagem ",
  "directorLabel.beatN": "Plano {{n}} · ",
  "directorLabel.beatNsec": "Plano {{n}} · {{s}} s",
  "directorLabel.hardRules": "REGRAS RÍGIDAS",
  "directorLabel.identityLock": "Trava de identidade",
  "directorLabel.spaceLock": "Trava espacial",
  "storyBeats.system": "Você escreve PULSOS da linha do tempo para vídeo de curta.\nCada pulso = o roteiro de UM clipe curto (não uma fala só).\nDeve incluir humor, atmosfera, ações, expressões, câmera/sfx opcional e 0 ou mais falas (em geral 1–4).\nDevolva SÓ um array JSON (sem cercas). Forma de cada item:\n{\"characterName\":\"…\",\"characterNames\":[\"…\"],\"sceneHint\":\"…\",\"sceneHints\":[\"…\"],\"propName\":\"…\",\"propNames\":[\"…\"],\"actionName\":\"…\",\"actionNames\":[\"…\"],\"mood\":\"…\",\"atmosphere\":\"…\",\"camera\":\"…\",\"sfx\":\"…\",\"units\":[{\"type\":\"action\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"expression\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"dialogue\",\"who\":\"…\",\"line\":\"…\",\"tone\":\"…\",\"parenthetical\":\"…\"},{\"type\":\"note\",\"text\":\"…\"}]}\nRegras:\n- dialogue.line são SÓ as palavras ditas; sem rubrica dentro da fala.\n- Corpo em action; rosto em expression; tom em tone/parenthetical.\n- Troca curta ou monólogo: vários dialogue no mesmo pulso.\n- Pulso só de ação é permitido.\n- NÃO um pulso por capítulo por padrão. Divida em clipes filmáveis: novo lugar, salto de tempo, novo conflito, ou ação/diálogo que não cabe em 6–10s → outro pulso. Em geral 1–3 por capítulo. No máximo {{maxBeats}} no total.\n- Liste TODO personagem, cena, prop e ação da biblioteca neste clipe (characterNames, sceneHints, propNames, actionNames). Limites: 4 / 2 / 4 / 4. Não só um de cada.\n- Se houver atuação física, actionNames é OBRIGATÓRIO com o nome original da lista de ações já escolhida. Não deixe vazio; melhor marcar essas ações do que nenhuma.\n- Máx. 4 units por pulso (1–2 action, 0–1 expression, 0–2 dialogue). Textos curtos; um JSON. Só nomes do elenco dado.\n- Conflito, ação visível, detalhe filmável.\n- Fiel ao título, estilo, elenco e cenas. Não alargue o mundo.\n- Cada dialogue.line no idioma principal do falante (lista de elenco). Não troque de idioma entre pulsos. Não traduza a menos que seja o idioma listado.",
  "storyBeats.userLead": "GERE beats de roteiro de clipe usando TODO o elenco, cenas, props, ações, estilo e ideia abaixo.",
  "storyBeats.eachBeat": "Cada beat precisa de humor + atmosfera + ações/expressões + diálogo opcional.",
  "storyBeats.story": "História: {{title}}",
  "storyBeats.style": "Estilo: {{style}}",
  "storyBeats.userDir": "Indicação do usuário: {{idea}}",
  "storyBeats.cast": "Elenco:",
  "storyBeats.scenes": "Cenas:",
  "storyBeats.props": "Objetos: {{props}}",
  "storyBeats.actions": "Ações (movimento): {{actions}}",
  "storyBeats.returnJson": "Devolva só o array JSON dos beats.",
  "storyBeats.noCast": "(sem elenco)",
  "storyBeats.noScenes": "(sem cenas — você pode nomear um lugar em sceneHint; não invente um mundo novo)",
  "storyBeats.none": "(nenhum)",
  "storyBeats.chapters": "Capítulos da história (fonte principal — quebre em beats filmáveis):",
  "storyBeats.chapterBlock": "Capítulo {{n}} · {{title}}\n{{body}}",
  "storyChapters.system": "Você escreve CAPÍTULOS de curta-metragem: a alma narrativa, não o roteiro do clipe.\nCada capítulo é prosa curta (cerca de {{words}} palavras): conflito, lugar, quem está, o que querem, o que muda.\nRetorne APENAS um array JSON. Cada item: {\"title\":\"…\",\"body\":\"…\"}.\nEscreva exatamente {{count}} capítulos. Fiel ao título, estilo, regras e ideia. Corpos curtos; um JSON só.",
  "storyChapters.userLead": "Escreva a história em capítulos ordenados. Depois geram elenco, cenários, props e ações.",
  "storyChapters.story": "História: {{title}}",
  "storyChapters.style": "Bíblia de estilo: {{style}}",
  "storyChapters.rules": "Regras rígidas: {{rules}}",
  "storyChapters.userDir": "Ideia: {{idea}}",
  "storyChapters.returnJson": "Retorne só o array JSON: [{\"title\":\"…\",\"body\":\"…\"}, …]",
  "storyChapters.polishSystem": "Você aprimora UM capítulo. Mantenha fatos, nomes e desfecho; torne mais filmável. Só JSON {\"title\":\"…\",\"body\":\"…\"}.",
  "storyChapters.polishUser": "História: {{story}}\nTítulo atual: {{title}}\nTexto:\n{{body}}\nDireção: {{idea}}\nRetorne JSON {\"title\",\"body\"}.",
  "storyCastFromChapters.system": "Extraia a bíblia de produção dos capítulos: personagens, locações, props, ações. Só JSON. Só entidades que aparecem. Reutilize nomes existentes. NÃO um de cada por capítulo. Um capítulo pode ter duas pessoas, vários lugares, muitos props e ações. Extraia cada entidade distinta. Dois falando → dois characters; beco depois santuário → duas scenes. Não invente para preencher cota.",
  "storyCastFromChapters.userLead": "Extraia CADA personagem, cena, prop e ação distintos — não um de cada por capítulo.",
  "storyCastFromChapters.story": "História: {{title}}",
  "storyCastFromChapters.style": "Estilo: {{style}}",
  "storyCastFromChapters.chapters": "Capítulos:\n{{chapters}}",
  "storyCastFromChapters.existingCast": "Já nesta história (reutilize estes nomes): {{names}}",
  "storyCastFromChapters.returnJson": "Retorne só o objeto JSON.",
  "videoPolish.system": "Você escreve UM prompt final imagem para vídeo para um modelo de vídeo de drama curto.\nDevolva SÓ o texto do prompt — sem cercas markdown, título ou explicação.\nRegras:\n- Escreva o prompt de direção no idioma da interface; deixe claros nomes e códigos de idioma das falas.\n- Still de pessoa: Trava de identidade. Placa de lugar: Trava espacial. Não acrescente rostos novos a menos que os materiais os nomeiem.\n- Use TODOS os fatos de perfil / soul / beat / local que afetem visual, movimento, fala ou atmosfera; ignore campos vazios.\n- Invente só o necessário para um clipe filmável a partir dos materiais e do seed — não importe mundo-amostra, Demo ou fatos ausentes.\n- Condensar soul.md longo em beats de atuação e identidade; não colar a bíblia inteira.\n- Use a duração dos materiais (segundos reais do clipe). Ação contínua. Sem texto, logos, marcas d'água nem gente extra.\n- Anatomia humana correta salvo o roteiro (duas mãos, dois braços, duas pernas).\n- Se houver vários personagens, mantenha cada um; foco principal primeiro.\n- Se houver REGRAS RÍGIDAS, conserve-as e coloque no fim (prioridade máxima).\n- Trava de diálogo é obrigatório: não apague, reescreva nem traduza. Expanda códigos para nomes. Cada clipe usa a língua principal do personagem; não mude de idioma entre clipes; não traduza falas.\n- Revisão de direção pode refinar estilo/ação, mas NÃO violar REGRAS RÍGIDAS.",
  "videoPolish.hardRulesKeep": "REGRAS RÍGIDAS (prioridade máxima — conserve cada linha; rótulos de objeto como [Personagem · Nome] devem permanecer). Coloque o bloco completo de regras rígidas no FIM da saída. Não enfraqueça, apague nem reatribua.",
  "clip.task": "TAREFA: clipe da timeline de drama curto (imagem para vídeo).",
  "clip.hasRef": "Pode haver uma imagem de referência — trave identidade e lugar quando for o caso.",
  "clip.characters": "Personagens:",
  "clip.scene": "Cena:",
  "clip.prop": "Objeto:",
  "clip.action": "Guia de ação / movimento:",
  "clip.beat": "Beat / diálogo:",
  "clip.prev": "Continuidade do clipe anterior:",
  "clip.revision": "REVISÃO DO DIRETOR (obrigatória):",
  "clip.templateDraft": "Rascunho de modelo (melhorar):",
  "intro.task": "TAREFA: clipe de apresentação de elenco (imagem para vídeo).",
  "intro.hasRef": "A imagem de referência vai para a API de vídeo — trave a identidade nessa foto.",
  "intro.noRef": "Não há caminho de imagem neste texto; mesmo assim trave aparência e figurino do perfil.",
  "intro.dossier": "Dossiê do personagem:",
  "intro.templateDraft": "Rascunho de modelo (melhore; não ignore o dossiê):",
  "common.durationAspect": "Duração: {{seconds}}s. Proporção: {{aspect}}.",
  "common.templateDraft": "Rascunho de modelo:",
  "improve.mode": "MODO MELHORAR: una TODAS as fontes num resultado completo. Mantenha a identidade salvo pedido explícito.",
  "improve.draftDefault": "Campos atuais do formulário:",
  "improve.userRequest": "Pedido de melhoria (vazio = polir e unir tudo):",
  "improve.emptyDefault": "(polir todos os campos para continuidade)",
  "improve.createDefault": "Ideia / direção:",
  "improve.explicitContext": "Contexto explícito SÓ deste pedido (continuidade; não importe outro mundo):",
  "improve.storyTitle": "Título: {{title}}",
  "improve.styleNote": "Nota de estilo: {{style}}",
  "improve.closingDefault": "Entregue o resultado completo agora.",
  "storyMeta.system": "Você é showrunner. Escreva bíblia visual e regras duras. SÓ JSON.",
  "storyMeta.draftLabel": "Campos atuais da história:",
  "storyMeta.createLabel": "Ideia / título:",
  "storyMeta.emptyPolish": "(polir bíblia + hardRules)",
  "storyMeta.closing": "SÓ JSON: {\"styleNote\":\"…\",\"hardRules\":\"…\"}. As duas chaves são obrigatórias.",
  "storyMeta.contextLabel": "Contexto (elenco / cenas / objetos):",
  "character.system": "Você é designer de personagens. SÓ um JSON. spokenLanguages = array BCP-47.",
  "character.draftLabel": "Campos atuais do perfil:",
  "character.soulLabel": "soul.md / bíblia ligada:",
  "character.createLabel": "Ideia de personagem:",
  "character.emptyPolish": "(polir e integrar soul)",
  "character.closing": "JSON completo. Chaves: {{keys}}.",
  "scene.system": "Você é designer de locações. Bíblia do lugar + roteiro desta cena. SÓ JSON.",
  "scene.draftLabel": "Campos atuais da cena:",
  "scene.charsLabel": "Personagens da história:",
  "scene.propsLabel": "Objetos da história:",
  "scene.priorLabel": "Cenas anteriores (continuidade):",
  "scene.createLabel": "Ideia de cena:",
  "scene.emptyPolish": "(polir lugar + roteiro)",
  "scene.closing": "JSON completo. Chaves: {{keys}}.",
  "prop.system": "Você é designer de objetos. SÓ um JSON. Visual, material e estado concretos.",
  "prop.draftLabel": "Campos atuais do objeto:",
  "prop.createLabel": "Ideia de objeto:",
  "prop.emptyPolish": "(polir o visual)",
  "prop.closing": "JSON completo. Chaves: {{keys}}.",
  "prop.fallbackName": "Objeto",
  "action.system": "Você é diretor de movimento. JSON válido só. Corpo, tempo, peso, trajetórias.",
  "action.storyContext": "Contexto da história (opcional): {{title}}",
  "action.styleNote": "Nota de estilo: {{style}}",
  "action.existingDraft": "Rascunho existente para polir:",
  "action.userIdea": "Ideia do usuário: {{idea}}",
  "action.closing": "Só JSON. Chaves: {{keys}}.",
  "profile.mustEveryKey": "Você DEVE emitir CADA chave: {{keys}}.",
  "profile.valuesAreStrings": "Cada valor DEVE ser string JSON. Vazio só se desconhecido.",
  "profile.visualTagsRule": "visualTags: uma string separada por vírgulas. NUNCA um array JSON.",
  "profile.fillConcrete": "Preencha com detalhe concreto.",
  "common.rules": "Regras:",
  "common.none": "(nenhum)",
  "intro.soul": "soul.md (fonte de interpretação/identidade):\n{{soul}}",
  "intro.matchBible": "(seguir a bíblia do personagem)",
  "invent.sources": "Fontes da verdade, nesta ordem: (1) ideia/pedido, (2) formulário, (3) extras só se estiverem NESTE prompt, (4) imagem anexada.",
  "invent.create": "Modo criar: invente livremente a partir da ideia/imagem; não deixe chaves obrigatórias vazias.",
  "invent.improve": "Modo melhorar: polir o rascunho; não troque a identidade salvo pedido.",
  "invent.noImport": "NÃO importe identidade, trama, clima, ofício, lugar, época ou estilo de fora deste prompt.",
  "invent.storyBlock": "Bloco de história/estilo só para continuidade; não anule a ideia explícita.",
  "character.keysLead": "APENAS um JSON com chaves: {{keys}}",
  "character.ruleSpoken": "spokenLanguages: array BCP-47 dos idiomas FALADOS. [] se não verbal.",
  "character.ruleIdentity": "Identidade coerente em pranchas e vídeo.",
  "scene.keysLead": "APENAS um JSON com chaves: {{keys}}",
  "scene.suggestLead": "Proponha um LOCAL pronto como cena nº {{n}} de \"{{title}}\".",
  "scene.suggestPlotFocus": "Foco da trama: {{label}}",
  "scene.suggestStyle": "Estilo: {{style}}",
  "scene.suggestExisting": "Locais já existentes: {{titles}}",
  "scene.suggestChars": "Personagens (contexto):",
  "scene.suggestProps": "Objetos (contexto):",
  "scene.suggestSegment": "Detalhe do segmento:",
  "scene.suggestBeats": "Cenas / beats:",
  "scene.suggestClosing": "Devolva o JSON completo. Desenhe um local reutilizável e distinto.",
  "scene.fallbackName": "Local",
  "scene.ideaFromImage": "Invente o perfil completo do local a partir da foto anexada.",
  "scene.polishIdea": "Polir",
  "prop.keysLead": "APENAS um JSON com chaves: {{keys}}",
  "action.fieldsLead": "Campos: {{keys}}.",
  "soul.system": "Você escreve soul.md de produção. Só markdown completo. Respeite spokenLanguages. Idioma da interface.",
  "soul.improveMode": "MODO MELHORAR: una perfil + soul existente num soul.md completo.",
  "soul.createMode": "Escreva um soul.md completo a partir deste perfil (não invente outra pessoa):",
  "soul.profileFields": "Campos do perfil:",
  "soul.existing": "soul.md existente (una; não descarte detalhe útil):",
  "soul.userRequest": "Pedido: {{request}}",
  "soul.extraContext": "Contexto extra (útil sim; o perfil vence):",
  "soul.returnOnly": "Devolva só o markdown do soul.md.",
  "wardrobe.system": "Você é consultor de figurino. UM JSON só. artStyle deve ser um de: {{styleIds}}. Materiais e silhueta concretos. Nunca erotize menores.",
  "wardrobe.improveMode": "MODO MELHORAR / SUGERIR: use TODOS os campos e o contexto.",
  "wardrobe.characterForm": "Personagem (formulário completo):",
  "wardrobe.soulExcerpt": "Trecho soul.md:\n{{soul}}",
  "wardrobe.userRequest": "Pedido: {{request}}",
  "wardrobe.storyContext": "Contexto de produção (use se houver; não invente outro mundo):",
  "wardrobe.style": "estilo: {{style}}",
  "wardrobe.segment": "Segmento escolhido: {{label}}",
  "wardrobe.sceneContext": "Cena / beat:",
  "wardrobe.noScenes": "(ainda sem cenas)",
  "wardrobe.proposeNew": "Proponha um look NOVO que sirva (sem duplicar).",
  "fill.system": "Você completa campos vazios. JSON com EXATAMENTE estas chaves: {{keys}}. Cada valor é string não vazia. Nunca array.",
  "fill.userPartial": "Perfil parcial (não contradiga):",
  "fill.userOnly": "Preencha SÓ estas chaves: {{keys}}.",
  "fill.userReturn": "JSON só com essas chaves; valores não vazios.",
  "imageGen.multiRef": "{{n}} stills a mais: o primeiro é a base; mantenha a identidade em todos.",
  "residual.sceneLink": "Cena {{n}}: {{short}}",
  "residual.beatSegment": "Pulso {{n}} · {{who}}{{tail}}",
  "residual.unknown": "Desconhecido",
  "residual.story": "História",
  "beat.mood": "【HUMOR】 {{text}}",
  "beat.atmo": "【ATMOSFERA】 {{text}}",
  "beat.camera": "【CÂMERA】 {{text}}",
  "beat.sfx": "【SFX】 {{text}}",
  "beat.action": "【AÇÃO】 {{text}}",
  "beat.actionWho": "【AÇÃO｜{{who}}】 {{text}}",
  "beat.expr": "【EXPRESSÃO】 {{text}}",
  "beat.exprWho": "【EXPRESSÃO｜{{who}}】 {{text}}",
  "beat.dialogue": "【DIÁLOGO｜{{who}}】 {{body}}",
  "beat.dialogueTone": "【DIÁLOGO｜{{who}}｜{{tone}}】 {{body}}",
  "beat.whoUnknown": "sem nome",
  "beat.template": "【HUMOR】tenso, indeciso\n【ATMOSFERA】luz quente na fresta da porta; chuva no chão\n【CÂMERA】plano médio, empurrão até as mãos\n【SFX】chuva, tecido raspando\n【AÇÃO｜Nome】tira o capacete; fita a luz da porta; a mão entra no bolso do casaco\n【EXPRESSÃO｜Nome】sobrancelha franzida, a respiração trava\n【DIÁLOGO｜Nome｜baixo, rouco】Chovendo de novo…\n【DIÁLOGO｜Nome｜à parte】（pausa）Você… ainda está aí?",
  "vision.preamble": "Há um still anexado. Preencha TODOS os campos deste {{what}} principalmente A PARTIR DA IMAGEM.",
  "vision.character": "identidade (nome, aparência, figurino, idade, gênero, tags)",
  "vision.scene": "local (título, descrição, luz, clima, cenário, tags)",
  "vision.prop": "objeto (nome, descrição, material, tamanho, estado, tags)",
  "vision.action": "ação (nome, descrição, ritmo, intenção, câmera, tags)",
  "vision.costume": "figurino (nome, descrição completa)",
  "still.header": "UM ÚNICO STILL-CHAVE para continuidade de vídeo (não um board multipainel). Um fotograma herói que bata com o plano. Sem texto, logos, marcas nem UI.",
  "still.revision": "MELHORIA DO USUÁRIO PARA ESTE STILL (obrigatória): {{notes}}",
  "still.regenTask": "TAREFA: revise o prompt de diretor imagem para vídeo e mantenha-o usável como brief de fotograma fixo.",
  "still.userImprove": "PEDIDO DE MELHORIA:\n{{notes}}",
  "still.currentPrompt": "Prompt profissional atual:",
  "still.hardRules": "REGRAS RÍGIDAS (no fim; não enfraqueça):",
  "mediaGen.writeOne": "Escreva UM prompt final de imagem para um still de drama curto.",
  "mediaGen.returnOnly": "SÓ o texto do prompt — sem markdown.",
  "mediaGen.singleComposite": "Descreva UMA única imagem composta.",
  "mediaGen.lockRefs": "As imagens anexadas são a verdade visual (ordem Ref#). Não invente outra pessoa, loja ou objeto.",
  "mediaGen.videoSystem": "Você escreve prompts de diretor imagem para vídeo de curta. Devolva um corpo só. Use a duração real dos materiais. Só fatos dos materiais. Se houver bloco de modelo de câmera, obedeça; não volte ao push-in ou handheld genérico. Coloque regras rígidas no fim se houver.",
  "mediaGen.videoMerge": "Una os materiais num ÚNICO prompt de vídeo.",
  "mediaGen.videoInclude": "Inclua: trava de identidade, câmera, atuação/diálogo, ritmo, luz.",
  "mediaGen.videoFacts": "Só fatos dos materiais e do seed. Sem Demo.",
  "mediaGen.videoNoSwap": "Com refs, não troque ator, local nem objeto.",
  "mediaGen.videoHardRules": "REGRAS RÍGIDAS no fim se houver.",
  "mediaGen.imageSystem": "Você é diretor de prompts de still / prancha multipainel para curta. Devolva só o corpo — sem cercas, título ou explicação. Só fatos dos materiais; não importe um mundo de amostra. Se houver modelo de câmera, obedeça; não volte ao push-in genérico. Coloque regras rígidas no fim se houver.",
  "mediaGen.imageMergeStills": "Una materiais e stills num ÚNICO prompt de imagem.",
  "mediaGen.imageMergeText": "Una os textos num ÚNICO prompt de imagem.",
  "mediaGen.imagePriority": "Prioridade: rostos/figurinos/locais/objetos das imagens.",
  "mediaGen.imageNoSwap": "Não substitua por outra celebridade ou set alheio se houver stills de elenco.",
  "mediaGen.imageFacts": "Só fatos dos materiais e do seed.",
  "mediaGen.imageLayout": "Se for multipainel, preserve a contagem exata.",
  "mediaGen.imagePackage": "Se houver LAYOUT, o prompt DEVE aplicar esse layout exato.",
  "mediaGen.imageHardRules": "REGRAS RÍGIDAS no fim se houver.",
  "mediaGen.directorFallback": "IMAGEM-PARA-VÍDEO: anime este fotograma fixo. Trave identidade, figurino, set e enquadramento.",
  "comic.taskHint": "História “{{title}}”, página de quadrinhos {{n}}: uma página pronta com exatamente {{count}} quadro(s). Identidade, figurino e lugar contínuos na página toda. Sem marca d’água nem moldura de interface.",
  "comic.panelCount": "A contagem de quadros é fixa: exatamente {{n}}.",
  "comic.lockSplash": "Trava de layout: um quadro em página inteira. Proibido: molduras extras, divisão, colagem.",
  "comic.lockYonkoma": "Trava: 4-koma vertical, 4 linhas × 1 coluna, de cima para baixo. Proibido: 2×2 ou faixa.",
  "comic.lockGrid2x2": "Trava: 2 linhas × 2 colunas. Proibido: faixa, 2×3, splash de página inteira.",
  "comic.lockGrid2x3": "Trava: 2 linhas × 3 colunas. Cima 1-2-3, baixo 4-5-6. Proibido: 2×2 ou 3×3.",
  "comic.lockGrid3x3": "Trava: 3 linhas × 3 colunas = nove quadros. Proibido: 2×2, 2×3 ou menos.",
  "comic.lockStrip": "Trava: uma única linha horizontal com exatamente {{n}} quadros. Proibido: várias linhas.",
  "comic.layoutSplash1": "Uma página alta: exatamente um quadro sangrado, sem calhas nem molduras extras.",
  "comic.layoutStrip2": "Uma página paisagem: dois quadros iguais lado a lado, calhas brancas grossas.",
  "comic.layoutStrip3": "Uma página paisagem: três quadros iguais numa linha, calhas brancas grossas.",
  "comic.layoutYonkoma": "Uma página alta: 4-koma vertical (4×1), calhas brancas grossas, leitura de cima para baixo.",
  "comic.layoutGrid2x2": "Uma página quadrada: grade 2×2, exatamente quatro quadros, calhas brancas, esquerda→direita e depois cima→baixo.",
  "comic.layoutStrip4": "Uma página paisagem larga: quatro quadros numa linha, calhas brancas grossas.",
  "comic.layoutGrid2x3": "Uma página paisagem: exatamente seis quadros, 2 linhas × 3 colunas (cima 1-2-3, baixo 4-5-6), calhas brancas, esquerda→direita e depois cima→baixo.",
  "comic.layoutGrid3x3": "Uma página quadrada: grade 3×3, exatamente nove quadros, calhas brancas, esquerda→direita e depois cima→baixo.",
  "comic.layoutWidePlusTwo": "Uma página alta: quadro largo no topo (~60 %) e dois menores embaixo, calhas brancas grossas.",
  "comic.layoutTwoPlusWide": "Uma página alta: dois quadros menores no topo e um largo de fechamento embaixo (~60 %), calhas brancas grossas.",
  "comic.layoutTallLeftTwo": "Uma página alta: quadro alto em toda a altura à esquerda e dois empilhados à direita, calhas brancas grossas.",
  "comic.layoutHeroPlusThree": "Uma página alta: quadro largo em cima e três menores numa fila embaixo, calhas brancas grossas.",
  "comic.layoutFocusQuad": "Uma página alta: médio no alto à esquerda, dois pequenos empilhados à direita, grande embaixo, calhas brancas grossas.",
  "comic.layoutStaggerFour": "Uma página alta: 2+2 deslocado — cima largo+estreito, baixo estreito+largo, calhas brancas grossas.",
  "comic.layoutDiagPairPlus": "Uma página alta: a metade de cima parte em diagonal em duas cunhas; embaixo um retângulo largo, calhas brancas grossas.",
  "comic.layoutHeroPlusFour": "Uma página alta: quadro largo em cima e quatro menores em 2×2 embaixo, calhas brancas grossas.",
  "comic.lockWidePlusTwo": "Trava: em cima um quadro largo. Embaixo exatamente dois menores. Proibido: três faixas iguais ou 2×2.",
  "comic.lockTwoPlusWide": "Trava: dois menores em cima, um largo embaixo. Proibido: três faixas iguais ou 2×2.",
  "comic.lockTallLeftTwo": "Trava: a esquerda ocupa toda a altura. Direita: dois empilhados. Proibido: 2×2 igual ou faixa horizontal.",
  "comic.lockHeroPlusThree": "Trava: metade de cima um largo. Embaixo exatamente três menores. Proibido: 2×2 ou quatro iguais.",
  "comic.lockFocusQuad": "Trava: médio no alto à esquerda, dois pequenos empilhados, grande embaixo. Proibido: 2×2 igual.",
  "comic.lockStaggerFour": "Trava: tamanhos deslocados — cima largo+estreito, baixo estreito+largo. Proibido: quatro quadrados iguais.",
  "comic.lockDiagPairPlus": "Trava: em cima duas cunhas em diagonal; embaixo um retângulo largo. Proibido: três faixas ou 2×2.",
  "comic.lockHeroPlusFour": "Trava: largo em cima; 2×2 de quatro embaixo. Exatamente cinco. Proibido: 3×3 ou 2×2 de página inteira.",
  "comic.readingYonkoma": "Leitura: só de cima para baixo (4-koma vertical).",
  "comic.readingWidePlusTwo": "Leitura: o largo de cima, depois os dois menores da esquerda para a direita.",
  "comic.readingTwoPlusWide": "Leitura: esquerda e direita em cima, depois o largo de baixo.",
  "comic.readingTallLeftTwo": "Leitura: o alto da esquerda, depois o superior direito, depois o inferior direito.",
  "comic.readingHeroPlusThree": "Leitura: o largo de cima, depois os três menores da esquerda para a direita.",
  "comic.readingFocusQuad": "Leitura: médio no alto à esquerda, os dois pequenos de cima para baixo, depois o grande de baixo.",
  "comic.readingStaggerFour": "Leitura: alto esquerdo, alto direito, baixo esquerdo, baixo direito.",
  "comic.readingDiagPairPlus": "Leitura: cunha superior esquerda, cunha inferior direita, depois o largo de baixo.",
  "comic.readingHeroPlusFour": "Leitura: o largo de cima, depois os quatro menores esquerda→direita e cima→baixo.",
  "comic.readingOrder": "Leitura: esquerda → direita, depois cima → baixo (4-koma vertical: só cima → baixo).",
  "comic.panelNumbers": "Números pequenos 1–{{n}} no canto superior esquerdo de cada quadro.",
  "comic.panelLine": "Quadro {{i}}/{{n}} ({{label}}): {{cap}}",
  "comic.panelEmpty": "Quadro {{i}}/{{n}} ({{label}}): um instante de história distinto e sequencial.",
  "comic.identity": "Mesma identidade, figurino e lugar em todos os quadros desta página.",
  "comic.finished": "É uma página de quadrinhos pronta, não uma colagem de fotos nem um mockup de interface.",
  "comic.layoutLead": "Diagramação: {{layout}}",
  "comic.prevPage": "Página anterior. Mantenha identidade, figurino e lugar; não copie a grade anterior.",
  "comic.ownPage": "Render existente desta página. Use como base de identidade / layout ao revisar.",
  "comic.galleryRef": "Still de identidade (elenco ou set). Combine rostos, figurino e lugar.",
  "comic.profileLine": "Página de quadrinhos {{n}} da história “{{title}}”.",
  "comic.styleBible": "Nota de estilo: {{note}}",
  "comic.artMedium": "Estilo artístico: {{art}}",
  "comic.fallbackClose": "Página impressa pronta. Calhas brancas grossas. Números pequenos. Sem marca d’água, UI nem colagem de álbum.",
  "comic.hardRules": "Regras rígidas",
  "comic.introTask": "Imagem para vídeo: anime a página pronta de “{{title}}”, página {{n}}, exatamente {{count}} quadro(s). Trave identidade, figurino e diagramação na imagem anexada.",
  "comic.introLock": "Trava: mesmos rostos, roupas, lugares, calhas e números da imagem. Não invente outra página nem outra pessoa.",
  "comic.introLayout": "Mantenha esta diagramação: {{layout}}",
  "comic.introCamera": "Câmera: avanço lento ou deslocamento suave na ordem de leitura. Só movimento de papel. Sem corte para outra diagramação.",
  "comic.introClose": "Sem marca d’água nem moldura de interface; não empilhe legendas além dos balões já desenhados.",
  "comic.dramaStillLock": "Trave identidade, figurino e lugar na prancha anexada, mas filme um plano de curta ao vivo — não um deslocamento sobre papel impresso.",
  "comic.dramaCamera": "Câmera e atuação: ritmo de curta-metragem, atuação clara, sincronia labial com as falas dos quadros. Continue a página anterior se houver imagem.",
  "comic.formatLockTall": "Formato da página: a prancha inteira deve ser vertical 9:16. Sem composição de paisagem.",
  "comic.formatLockSquare": "Formato da página: a prancha inteira deve ser quadrada 1:1.",
  "comic.formatLockWide": "Formato da página: a prancha inteira deve ser horizontal 16:9.",
  "art.photoCinematic": "Meio obrigatório: still cinematográfico fotorrealista. Câmera real, materiais naturais, correção de cinema. Deve parecer foto ou quadro de filme. Proibido: anime, cel, ilustração 2D, contorno cartoon, argila, CGI plástico.",
  "art.photoPortrait": "Meio obrigatório: retrato de estúdio fotorrealista. Softbox, nitidez de headshot comercial. Deve ser fotografia. Proibido: anime, tinta de quadrinhos, brinquedo 3D, cel chapado.",
  "art.photoDocumentary": "Meio obrigatório: foto documental fotorrealista. Luz natural, texturas honestas. Deve parecer tirada com câmera real. Proibido: anime, CGI estilizado, ilustração.",
  "art.cgiFilm": "Meio obrigatório: personagem 3D CGI de qualidade cinematográfica. Materiais PBR, realces com ray tracing. Deve parecer render 3D, não foto real nem anime 2D. Proibido: foto ao vivo, lineart de anime, tinta chapada de HQ.",
  "art.cgiStylized": "Meio obrigatório: 3D estilizado premium (CGI de longa). Formas legíveis, PBR suave. Deve ser CGI 3D. Proibido: live fotorrealista, cel 2D, HQ rabiscada.",
  "art.cgiClay": "Meio obrigatório: personagem 3D de argila / escultura. Argila fosca, formas esculpidas. Deve ler como escultura de argila. Proibido: foto de pele, cel de anime, HQ a tinta.",
  "art.animeModern": "Meio obrigatório: anime de TV japonês moderno 2D. Linha digital limpa, cel suave, olhos e mechas de anime. A imagem inteira deve ser anime 2D. Proibido: foto, poros reais, render 3D, tinta western só, óleo.",
  "art.animeShonen": "Meio obrigatório: visual-chave shonen 2D. Traço forte, cel contrastado, olhos nítidos. Deve ser shonen 2D. Proibido: foto, CGI 3D, aquarela só.",
  "art.animeShoujo": "Meio obrigatório: anime shoujo 2D. Linha delicada, degradês suaves, olhos luminosos. Deve ser shoujo. Proibido: foto, 3D duro, tinta áspera de HQ.",
  "art.animeGekiga": "Meio obrigatório: anime gekiga / realista 2D. Linha madura, paleta contida, claramente 2D. Proibido: foto ao vivo, chibi, CGI 3D puro.",
  "art.animeChibi": "Meio obrigatório: chibi / superdeformado 2D. Cabeça grande, corpo pequeno, traços simplificados. Deve ser chibi. Proibido: proporções fotorrealistas, 3D realista, live detalhado.",
  "art.donghua": "Meio obrigatório: key art de donghua chinês. Traje refinado, silhueta elegante, 2D ou 2,5D. Deve ler como donghua. Proibido: live de Hollywood, HQ de jornal western só.",
  "art.manhwa": "Meio obrigatório: manhwa / webtoon coreano colorido. Pintura digital suave, contornos limpos, cabelo brilhante. Deve ser manhwa 2D. Proibido: foto, argila 3D, tinta de herói só.",
  "art.comicWestern": "Meio obrigatório: quadrinhos ocidentais. Tinta segura, chapados ou cel limitado, formas gráficas. Deve ser ilustração de HQ. Proibido: foto, só olhos de anime, render de argila.",
  "art.conceptGame": "Meio obrigatório: concept art de personagem AAA. Folha pintada, silhueta forte. Deve parecer concept, não captura nem foto. Proibido: retrato foto puro, só chibi.",
  "art.illustrationSoft": "Meio obrigatório: ilustração digital suave. Pincel delicado, acabamento de livro. Deve ser ilustração pintada. Proibido: foto de câmera, cel duro, argila 3D.",
  "mediaGen.polishTask": "Tarefa: {{hint}}",
  "mediaGen.polishKind": "Tipo: {{kind}}",
  "mediaGen.polishMaterials": "—— Materiais ——",
  "mediaGen.polishEndMaterials": "—— Fim dos materiais ——",
  "mediaGen.polishRef": "Ref. nº{{n}} — {{title}}",
  "mediaGen.videoTaskHint": "Escreva uma direção profissional de imagem-para-vídeo a partir do quadro-chave ({{kind}}). Câmera, atuação e ritmo; trave o quadro-chave.",
  "mediaGen.directorFallbackCam": "Câmera e atuação claras; sem legendas nem marca d’água.",
  "charIntro.task": "IMAGEM-PARA-VÍDEO: anime a mesma pessoa num auto-casting curto.",
  "charIntro.identityLock": "TRAVA DE IDENTIDADE: mesmo rosto, cabelo, corpo, idade, figurino e cores.",
  "charIntro.personality": "Personalidade / vibe: {{personality}}.",
  "charIntro.backstory": "História: {{backstory}}.",
  "charIntro.relationships": "Relações: {{relationships}}.",
  "charIntro.soul": "Trecho soul (fonte de atuação): {{soul}}",
  "charIntro.performance": "Maneirismos: {{manner}}.",
  "charIntro.speech": "Fala: a boca se move como uma apresentação breve; voz: {{voice}}.",
  "charIntro.beat": "Idle natural → sorriso ou aceno → gesto breve → hold.",
  "charIntro.lighting": "Luz coerente com o still; sem texto, logos nem extra gente.",
  "sceneIntro.task": "IMAGEM-PARA-VÍDEO: anime o mesmo local como plano de estabelecimento.",
  "sceneIntro.spaceLock": "TRAVA DE ESPAÇO: mesma arquitetura, materiais, placas, planta e cor.",
  "sceneIntro.name": "Nome do local: {{name}}.",
  "sceneIntro.place": "Descrição: {{place}}.",
  "sceneIntro.spaceType": "Tipo de espaço: {{type}}.",
  "sceneIntro.time": "Hora do dia: {{time}}.",
  "sceneIntro.weather": "Clima: {{weather}}.",
  "sceneIntro.moodLight": "Clima: {{mood}}. Luz: {{lighting}}.",
  "sceneIntro.palette": "Paleta: {{palette}}.",
  "sceneIntro.setDressing": "Cenário: {{set}}.",
  "sceneIntro.tags": "Tags visuais: {{tags}}.",
  "sceneIntro.art": "Estilo: {{art}}.",
  "sceneIntro.ambient": "Ambiente (sem texto de UI): {{sound}}.",
  "sceneIntro.scriptCue": "Dica de beat (só atmosfera): {{cue}}.",
  "sceneIntro.camera": "Câmera: {{camera}}; movimento contínuo. Não acrescente rostos, logos nem texto salvo se os materiais já os mostrarem.",
  "sceneIntro.beat": "Estabelecer → vida ambiental sutil → hold.",
  "propIntro.task": "IMAGEM-PARA-VÍDEO: anime o mesmo objeto como intro de produto.",
  "propIntro.objectLock": "TRAVA DE OBJETO: mesma silhueta, materiais, cores, gravuras e desgaste.",
  "propIntro.name": "Nome: {{name}}.",
  "propIntro.look": "Aparência: {{look}}.",
  "propIntro.material": "Composição: {{material}}.",
  "propIntro.size": "Tamanho: {{size}}.",
  "propIntro.condition": "Estado: {{condition}}.",
  "propIntro.tags": "Tags: {{tags}}.",
  "propIntro.art": "Estilo: {{art}}.",
  "propIntro.camera": "Órbita suave ou travelling lento em mesa limpa; luz coerente.",
  "propIntro.beat": "Hold → brilho / microgiro → hold.",
  "propIntro.noHands": "Sem mãos nem rostos novos se não estiverem no still; sem texto nem extras.",
  "costumeIntro.task": "IMAGEM-PARA-VÍDEO: anime o mesmo look como intro de figurino.",
  "costumeIntro.wardrobeLock": "TRAVA DE FIGURINO: mesma silhueta, tecidos, cores, camadas e acessórios.",
  "costumeIntro.identityOrProduct": "Se houver pessoa: trave rosto/corpo; se manequim/plano: enquadramento de produto.",
  "costumeIntro.name": "Nome do look: {{name}}.",
  "costumeIntro.desc": "Figurino: {{look}}.",
  "costumeIntro.art": "Estilo: {{art}}.",
  "costumeIntro.camera": "Leve travelling ou órbita; luz de moda coerente.",
  "costumeIntro.beat": "Hold → queda de tecido / brilho de ferragens → hold.",
  "costumeIntro.forbid": "Sem rostos novos, texto, logos nem pose erótica.",
  "costumeIntro.fallbackName": "Visual",
  "actionIntro.lead": "Vídeo demo da ação \"{{name}}\".",
  "actionIntro.intention": "Intenção: {{intention}}",
  "actionIntro.body": "Corpo/tempo: {{body}}",
  "actionIntro.camera": "Câmera: {{camera}}",
  "actionIntro.closing": "Movimento contínuo, sem texto; siga o still.",
  "sceneIntroPolish.task": "TAREFA: intro de local (imagem-para-vídeo).",
  "sceneIntroPolish.hasRef": "Still de local anexado — trave a identidade ESPACIAL.",
  "sceneIntroPolish.noRef": "Sem still; trave à bíblia do local.",
  "sceneIntroPolish.dossier": "Dossiê do local:",
  "sceneIntroPolish.scriptCue": "dica de roteiro (só atmosfera):\n{{script}}",
  "sceneIntroPolish.emptySet": "Set vazio; sem rostos novos. Sem texto nem logos.",
  "propIntroPolish.task": "TAREFA: intro herói de objeto (imagem-para-vídeo).",
  "propIntroPolish.hasRef": "Still de objeto anexado — trave o OBJETO.",
  "propIntroPolish.noRef": "Sem still; trave ao dossiê.",
  "propIntroPolish.dossier": "Dossiê do objeto:",
  "propIntroPolish.noHands": "Sem mãos nem rostos novos. Sem texto nem logos.",
  "costumeIntroPolish.task": "TAREFA: intro de figurino (imagem-para-vídeo).",
  "costumeIntroPolish.hasRef": "Still anexado — pessoa: identidade+roupa; manequim: silhueta e materiais.",
  "costumeIntroPolish.noRef": "Sem still; trave à descrição.",
  "costumeIntroPolish.dossier": "Dossiê de figurino:",
  "costumeIntroPolish.fabric": "Queda sutil de tecido; sem rostos novos nem texto.",
  "actionIntroPolish.task": "TAREFA: intro de guia de movimento (imagem-para-vídeo).",
  "actionIntroPolish.hasRef": "Still anexado — trave a identidade de atuação àquele quadro.",
  "actionIntroPolish.templateKeepRules": "Rascunho modelo (melhore; REGRAS RÍGIDAS no fim):",
  "cover.posterLead": "PÔSTER / KEY ART profissional 16:9. Não é mockup de UI. Sem texto, logo nem marca.",
  "cover.titleMood": "Título (só clima, não escreva na imagem): {{title}}.",
  "cover.styleBible": "Bíblia de estilo: {{style}}",
  "cover.extraDir": "Direção extra: {{idea}}",
  "cover.establishing": "Plano de estabelecimento evocativo para capa da biblioteca.",
  "cover.medium": "Respeite o medium; silhueta forte.",
  "cover.editPrefix": "Edição de imagem: nova composição de pôster. Mantenha identidade e clima. ",
  "cover.label": "Capa da história",
  "costumeFill.system": "Você é figurinista. Só JSON compacto. Se houver imagem, descreva ESSE look com fidelidade.",
  "costumeFill.idea": "Ideia: {{idea}}",
  "costumeFill.polish": "Polir o rascunho de figurino.",
  "costumeFill.required": "Chaves: name, description, artStyle, hardRules. Faltar = inválido.",
  "costumeFill.fallbackName": "Visual",
  "segment.entireStory": "Toda a história (todas as cenas)",
  "segment.noStory": "Nenhuma história (só ficha do personagem)",
  "vision.inventFromImage": "Descreva e invente um perfil completo de {{kind}} a partir da foto anexada.",
  "vision.polishAll": "Polir e unir todos os campos",
  "story.untitled": "Drama curto sem título",
  "action.castIdentityNote": "Stills de identidade ({{count}}): rosto/corpo iguais às referências de elenco em cada painel.",
  "tpl.system.polishOnly": "RECEITA só polir: mantenha identidade e mundo. Polir o texto. Não invente era, clima, ofício, lugar nem mundo-amostra. Não invente idioma falado. Não grave REGRAS RÍGIDAS padrão no perfil.",
  "tpl.system.fillBlanks": "RECEITA só vazios: preencha SÓ chaves vazias. Não reescreva o que já está preenchido. Não invente outro mundo.",
  "tpl.system.invent": "RECEITA inventar: o usuário autorizou criar livremente. Complete cada chave filmável. Não importe Demo nem mundo não implícito.",
  "tpl.system.fromStory": "RECEITA da história: use só título/estilo/elenco/cenas DESTE pedido. Em conflito, a ideia do usuário vence.",
  "tpl.system.followAsset": "RECEITA seguir ativo: siga o estilo já dado. Não force cinema, set vazio nem 6–10 s salvo se os materiais disserem. Use a duração real do clipe.",
  "tpl.system.cinematicLock": "RECEITA cine+anti-alucinação: visual cinematográfico; set vazio; sem marca, logo nem rostos extras; duas mãos/braços/pernas salvo não humano.",
  "tpl.system.identityLock": "RECEITA trava de identidade: trave rosto/corpo/roupa/lugar/objeto aos stills. Não substitua pessoa, lugar ou objeto.",
  "tpl.system.restyle": "RECEITA restyle: a mesma pessoa. Figurino, set e época podem mudar se pedido. Não troque de pessoa.",
  "pipeline.character.system": "Você refina bíblias de personagem. 3–5 linhas: visual, voz, motivo, gesto. Só fatos deste pedido.",
  "pipeline.scene.system": "Você expande cenas em folhas de beats. Use a duração real; não assuma 6–10 s. Só cenas dadas.",
  "pipeline.props.system": "Você refina continuidade de objetos. Cor, tamanho e quando aparece. Não invente objetos fora da lista.",
  "pipeline.script.system": "Você é roteirista. Um bloco compacto por cena para vídeo IA. Duração real; não force 10 s. Formato:\n### SCENE <number> | id=<id>\n<script body>",
  "pipeline.script.noScenes": "(sem cenas — não invente locais)",
  "keyArt.task": "Arte-chave {{n}} da história “{{title}}”. Uma imagem publicitária pronta. Sem quadrinhos, sem números de painel, sem interface.",
  "keyArt.lockCover": "PÔSTER DE CAPA: arte paisagem para o cartão da história. Deixe faixa segura para o título. Rostos legíveis. Não invente logo nem créditos falsos.",
  "keyArt.lockPoster": "PÔSTER VERTICAL: um único one-sheet. O herói se lê no telemóvel. Sem outros pôsteres no quadro.",
  "keyArt.lockStill": "STILL: um fotograma cinematográfico, como tirado do drama. Atuação natural, espaço real. Não é colagem.",
  "keyArt.lockPromo": "ARTE PROMOCIONAL: personagem e mundo no mesmo quadro. Silhueta forte, um humor. Não é folha de contacto.",
  "keyArt.lockSocial": "STORY SOCIAL: quadro vertical 9:16. Sujeito grande. Margens para texto no ecrã.",
  "keyArt.lockHeadshot": "CLOSE DO PROTAGONISTA: um rosto de frente a preencher o quadro, idêntico às referências. Ombros permitidos. Ninguém mais.",
  "keyArt.lockBust": "PROMO BUSTO: do peito para cima, gola do figurino visível, olhar à câmara.",
  "keyArt.lockGroup": "ELENCO: todos os personagens nomeados num quadro, mesmo mundo e mesma luz. Não omita nem troque um rosto.",
  "keyArt.formatLockTall": "BLOQUEIO DE FORMATO: a imagem inteira é um quadro alto 9:16. Sem composição paisagem.",
  "keyArt.formatLockSquare": "BLOQUEIO DE FORMATO: a imagem inteira é um quadro quadrado 1:1.",
  "keyArt.formatLockWide": "BLOQUEIO DE FORMATO: a imagem inteira é um quadro largo 16:9.",
  "keyArt.methodFreshLock": "MÉTODO: gerar uma imagem nova. As referências só fixam identidade. Não copie o recorte de uma toma antiga.",
  "keyArt.methodEditLock": "MÉTODO: editar a imagem própria anexa. Mantenha a composição salvo se o brief pedir o contrário.",
  "keyArt.methodIdentityLock": "MÉTODO: fixe os rostos nas referências do personagem. Pose, recorte e figurino podem mudar.",
  "keyArt.methodContinueLock": "MÉTODO: continue a partir da imagem anterior. As mesmas pessoas e o mesmo lugar, o plano seguinte da mesma filmagem.",
  "keyArt.briefLine": "Brief de direção: {{brief}}",
  "keyArt.beatLine": "Beat ligado: {{beat}}",
  "keyArt.close": "Imagem {{aspect}} concluída. Sem marca de água, sem moldura de interface, sem legendas extra.",
  "charIntro.manner": "Maneirismos: {{manner}}.",
  "charIntro.cameraDefault": "Câmera de atuação: aproximação suave ou leve câmera na mão; o personagem olha para a câmera ou um pouco fora do eixo.",
  "mediaGen.honorCameraTemplate": "Se os materiais incluírem um bloco de modelo de câmera, siga exatamente esse enquadramento e movimento. Não substitua por uma aproximação ou câmera na mão genéricas.",
  "mediaGen.refRoles": "Cada still tem um ofício: IDENTITY (rosto/figurino), SPATIAL (blocking e câmara do modelo branco — não copies o cinza de argila como look final), MOTION (tempo/gesto) ou STYLE (paleta/luz). Não deixes um still mandar em tudo.",
  "sceneIntro.cameraNotes": "Notas de câmera: {{camera}}.",
  "sceneIntro.cameraDefault": "Câmera: movimento contínuo e suave. Não acrescente rostos novos do elenco, logos nem sobreposições de texto, salvo se os materiais já os mostrarem.",
  "quality.family.photo": "Qualidade: foco nítido nos olhos ou nas feições principais do rosto/cabeça, microdetalhe alto adequado a meio fotorrealista, iluminação profissional de estúdio em três pontos salvo se o estilo disser o contrário, aparência de objetiva prime (50–85 mm), sem desfoque de movimento, sem filtro de embelezamento que amoleça o rosto, sem marca d'água nem texto.",
  "quality.family.cgi": "Qualidade: apresentação 3D limpa do personagem, materiais legíveis (PBR), silhueta de topologia consistente, formas primárias nítidas, HDRI de estúdio ou luz CG de três pontos, sem grão de ruído salvo estilo argila, sem marca d'água nem texto, não é fotografia real.",
  "quality.family.anime": "Qualidade: ofício limpo de folha de design 2D, peso de linha consistente, modelo de rosto estável entre quadros, cor cel ou sombreamento suave controlado, evite fotografia fotorrealista, evite visual de ação ao vivo, evite sombreamento fotográfico 3D SSS, sem marca d'água nem rótulos de texto.",
  "quality.family.illust": "Qualidade: clareza de folha de design de ilustração profissional, design de personagem consistente, silhueta e figurino/materiais legíveis, fundo de estúdio neutro, sem marca d'água, sem legendas de texto de interface.",
  "sheet.lock.lead": "Crie um still de referência de personagem para continuidade de vídeo IA.",
  "sheet.lock.sexPrefix": "Trava de sexo (prioridade máxima — coque, rosto oval, pele clara, corpo magro ou túnicas não podem inverter o sexo): {{lock}}",
  "sheet.lock.identity": "Trava de identidade: exatamente um sujeito personagem em cada quadro (pode ser humano, animal, criatura, espírito, robô ou outra entidade desenhada — mas nunca troque de espécie nem de design no meio da prancha).",
  "sheet.lock.noSecond": "Não invente um segundo personagem; mantenha o mesmo plano corporal, marcas, cores e design de cabeça em todos os quadros.",
  "sheet.lock.head": "Cabeça/rosto (ou equivalente) deve permanecer consistente: mesmos olhos ou sensores, mesma silhueta da cabeça, mesmas cores de superfície e identificadores-chave.",
  "sheet.lock.camera": "Câmera: enquadramento de referência estável, verticais retas, sem olho de peixe salvo se a diagramação exigir um ângulo especial.",
  "sheet.lock.background": "Fundo: ciclorama de estúdio cinza-claro ou branco-quebrado, limpo e sem emendas, vazio e uniforme; sem bagunça salvo se a diagramação pedir um pequeno detalhe de figurino/objeto.",
  "sheet.lock.forbidden": "Proibido: marcas d'água, logos, legendas, texto, moldura de interface, membros extras aleatórios, extremidades deformadas (salvo se o plano for intencionalmente só mãos/detalhe).",
  "sheet.lock.subject": "Nome/conceito do sujeito: {{name}}",
  "sheet.lock.age": "Idade ou apresentação de maturidade: {{age}}",
  "sheet.lock.gender": "Gênero / apresentação: {{gender}}",
  "sheet.lock.appearance": "Aparência (deve coincidir exatamente): {{appearance}}",
  "sheet.lock.appearanceFaceOnly": "Aparência — só rosto / cabelo / proporções corporais (deve coincidir): {{appearance}}. Desta descrição, retire qualquer roupa, casaco, guarda-chuva, bolsa, sapato, joia ou objeto — não devem aparecer.",
  "sheet.lock.ignoreCostume": "Figurino externo / objetos: ignore por completo nesta prancha. Sem guarda-chuva, bolsa, casaco nem itens de moda. Só placa de corpo ou de camada-base.",
  "sheet.lock.costume": "Figurino / design exterior (deve coincidir exatamente): {{costume}}",
  "sheet.lock.tags": "Tags visuais: {{tags}}",
  "sheet.lock.tagsIdentity": "Tags visuais (só identidade; descarte tags de roupa/objeto): {{tags}}",
  "sheet.lock.manner": "Só dicas sutis de pose/maneirismo (não mude a identidade): {{manner}}",
  "sheet.scaffold.repeatMedium": "Repita: o meio da imagem final deve ser exatamente o id de estilo \"{{id}}\" ({{family}}).",
  "sheet.scaffold.wardrobeTag": "Marca da camada de figurino: {{tag}}.",
  "sheet.scaffold.layoutLead": "Diagramação: {{layout}}",
  "sheet.scaffold.finalCheck": "Checagem final: se a imagem parecer o meio errado, regenere no meio correto: {{medium}}",
  "sheet.edit.task": "Tarefa de edição de imagem / mudança de diagramação (prioridade máxima — leia por completo):",
  "sheet.edit.target": "Id do pacote de prancha-alvo: \"{{id}}\". Camada de figurino: {{tag}}.",
  "sheet.edit.ignoreLayout": "Ignore por completo a diagramação da imagem-fonte: contagem de quadros, calhas, ângulos de câmera, recorte e enquadramento da fonte não devem ser copiados.",
  "sheet.edit.ignoreWardrobe": "Ignore o figurino/roupa da fonte se conflitar com a camada de figurino-alvo abaixo.",
  "sheet.edit.keepIdentity": "Da fonte, conserve só a identidade do personagem: design de rosto/cabeça, cabelo, proporções corporais, espécie/plano corporal, pele ou marcas de superfície, apresentação de idade.",
  "sheet.edit.stripOuter": "Retire toda a roupa/armadura externa da fonte. Para placas de corpo: só macaquinho na cor da pele. Para camada-base: só roupa íntima simples. Não preserve o traje da fonte.",
  "sheet.edit.applyProfileCostume": "Pode aplicar a descrição de figurino do perfil no prompt do corpo; não se limite a recolorir ou recortar os quadros de figurino da fonte.",
  "sheet.edit.changeMedium": "Mude por completo o meio de render se for preciso para corresponder ao estilo artístico obrigatório.",
  "sheet.edit.noNewPerson": "Não invente um personagem diferente. Não se limite a recortar, aproximar ou recolorir a fonte.",
  "sheet.edit.newComposition": "Produza uma composição de prancha de referência inteiramente nova que coincida exatamente com o bloco de diagramação (contagem de quadros e poses).",
  "sheet.edit.checklist": "Lista final: (1) a identidade coincide com o rosto/corpo da fonte (2) a diagramação segue o pacote \"{{id}}\", não a prancha-fonte (3) camada de figurino {{tag}} (4) meio = {{style}}.",
  "sheet.wardrobe.nude": "Prancha de proporções corporais para desenho de figurino de produção (não é conteúdo adulto, não é fotografia despida): luz de estúdio clínica e neutra, ciclorama cinza liso, pose profissional de desenho de figura. Sem fotografia de moda, sem visual de lingerie, sem quarto nem cenário glamoroso. O sujeito veste macaquinho fosco sem costura na cor da pele / malha justa de corpo inteiro (ou malha fosca sólida adequada à espécie) que revela a silhueta e as proporções exatas — rosto e cabelo visíveis; sem figurino externo, logos, objetos, sapatos nem acessórios. O macaquinho é só subcamada de produção (como uma malha CG), nunca figurino externo. Preserve rosto, cabelo, proporções corporais e marcas de superfície para CG de figurino posterior. Ignore qualquer descrição de figurino externo nesta prancha. Explicitamente vestido de macaquinho — nunca despido.",
  "sheet.wardrobe.halfBareUpper": "Referência parcial do tronco superior para medidas de desenho de figurino de produção (somente personagem adulto; estudo clínico de figura; não erótico; não pornografia; não sugestivo): luz de estúdio clínica e neutra, ciclorama cinza liso, pose em pé profissional médica / de manequim. Sem fotografia de moda, sem visual de lingerie, sem cenário de quarto, sem câmera sexualizada. Metade superior descoberta: tronco, peito, ombros, braços e pescoço nus; rosto e cabelo totalmente visíveis. Metade inferior coberta só com uma peça de baixo fosca, opaca, simples, neutra ou na cor da pele (shorts lisos, cueca/calcinha simples ou pano simples — cobertura de produção apenas, não lingerie de moda, sem renda, sem transparência). Sem parte de cima de figurino externo, sem sutiã como item de moda, sem objetos, sapatos, acessórios nem logos. Preserve rosto, cabelo, proporções corporais e marcas de superfície para CG de figurino / prova posterior. Ignore qualquer descrição de figurino externo nesta prancha.",
  "sheet.wardrobe.halfBareLower": "Referência parcial da metade inferior para medidas de desenho de figurino de produção (somente personagem adulto; estudo clínico de figura; não erótico; não pornografia; não sugestivo): luz de estúdio clínica e neutra, ciclorama cinza liso, pose em pé profissional médica / de manequim. Sem fotografia de moda, sem visual de lingerie, sem cenário de quarto, sem câmera sexualizada. Metade inferior descoberta: quadris, coxas, pernas e pés nus; rosto e cabelo totalmente visíveis. Áreas íntimas somente: cobertura mínima fosca opaca na cor da pele ou neutra (cueca/calcinha simples — só produção, não lingerie de moda). Metade superior coberta só com uma parte de cima fosca, opaca e neutra simples (regata lisa, camiseta interior ou pano — cobertura de produção apenas, sem visual de moda, sem logos). Sem figurino externo, objetos, sapatos nem acessórios. Preserve rosto, cabelo, proporções corporais e marcas de superfície para CG de figurino / prova posterior. Ignore qualquer descrição de figurino externo nesta prancha.",
  "sheet.wardrobe.bare": "Referência anatômica corporal completa para medidas de desenho de figurino de produção (somente personagem adulto; estudo clínico de figura; não erótico; não pornografia; não sugestivo): luz de estúdio clínica e neutra, ciclorama cinza liso, pose em pé profissional médica / de manequim. Sem fotografia de moda, sem pose de lingerie, sem cenário de quarto, sem câmera sexualizada. O sujeito está completamente sem roupa (forma corporal nua completa, ou superfície nua adequada à espécie), só com rosto e cabelo — sem vestimenta, sem coberturas parciais, sem figurino externo, objetos, sapatos nem acessórios. Preserve rosto, cabelo, proporções corporais e marcas de superfície para CG de figurino / prova posterior. Ignore qualquer descrição de figurino externo nesta prancha.",
  "sheet.wardrobe.base": "Referência de camada-base de produção (roupa íntima / vestimenta-base para troca de figurino, não erótico): só roupa íntima neutra sólida simples ou cobertura-base adequada à espécie (p.ex. cueca/calcinha lisa + camiseta interior, ou pano simples). Sem figurino externo, logos, visual de lingerie de moda nem pose sugestiva. Luz de estúdio clínica, fundo cinza. Preserve a identidade para vestir figurinos externos depois. Ignore a descrição de figurino externo nesta prancha.",
  "sheet.wardrobe.costume": "Referência de figurino de produção: figurino externo completo conforme descrito; materiais e silhueta legíveis para continuidade de vídeo.",
  "sheet.layout.bible": "Bíblia de personagem larga 16:9 com exatamente três quadros verticais iguais da esquerda para a direita: (1) corpo inteiro de frente em pé, pés visíveis, braços relaxados; (2) corpo inteiro três-quartos ~45°; (3) retrato cabeça-e-ombros olhando para a câmera. Cada figura preenche o seu quadro. Mesmo rosto, cabelo, corpo e figurino nos três. Calhas nítidas, estúdio limpo.",
  "sheet.layout.turnaround": "Giro largo 16:9 com exatamente quatro figuras de corpo inteiro na mesma escala: frente, perfil esquerdo 90°, costas inteiras, perfil direito 90°. A-pose neutra / braços relaxados, pés plantados. Figurino completo. Altura máxima da figura.",
  "sheet.layout.expression": "Quadrado 1:1 compacto 2×2 com exatamente quatro closes de cabeça-e-ombros: neutro, sorriso suave, raiva, surpresa. Cada rosto preenche ~90% da célula; cabelo e gola idênticos. Sem corpo inteiro.",
  "sheet.layout.costume": "Prancha de figurino alta 9:16: os ~65% superiores com herói grande de corpo inteiro de frente para a câmera em figurino completo; faixa inferior com exatamente dois recortes grandes de detalhe (tecido/bolso + sapatos ou acessório-assinatura). Materiais legíveis.",
  "sheet.layout.identity_lock": "Trava de identidade larga 16:9 com exatamente dois quadros: esquerda 60% close grande de rosto de frente; direita 40% rosto três-quartos. Maximize o detalhe facial para identidade em vídeo; sem corpo inteiro.",
  "sheet.layout.face_id": "Quadrado 1:1 um único retrato grande e centralizado de rosto de frente (ou cabeça principal), incluindo o tronco superior, olhando para a objetiva. Feições principais nítidas, inteiramente no meio artístico obrigatório. Só um personagem.",
  "sheet.layout.hero": "Retrato herói único de corpo inteiro em pé, alto 9:16, à altura dos olhos, figura inteira visível. Postura neutra centrada, fundo de estúdio, figurino completo, meio artístico obrigatório.",
  "sheet.layout.bust": "Busto médio quadrado 1:1 (do peito para cima), corpo levemente três-quartos, rosto para a câmera. Enquadramento de diálogo, gola do figurino visível.",
  "sheet.layout.three_quarter": "Corpo três-quartos alto 9:16 (~dos joelhos para cima), corpo a 30–45°, rosto para a câmera. Silhueta de figurino clara, mãos visíveis.",
  "sheet.layout.profile": "Perfil puro esquerdo de corpo inteiro 90°, alto 9:16, olhando para a esquerda, coluna reta. Silhueta verdadeira; figurino completo; um personagem.",
  "sheet.layout.back": "Vista de costas de corpo inteiro, alta 9:16, de pé de costas para a câmera, cabelo e costas do figurino legíveis. Prancha de continuidade de saída.",
  "sheet.layout.low_angle": "Corpo inteiro heroico em ângulo baixo, alto 9:16, câmera perto da cintura olhando um pouco para cima, postura poderosa, rosto ainda nítido, figurino completo.",
  "sheet.layout.high_angle": "Corpo três-quartos em ângulo alto, alto 9:16, câmera um pouco acima da linha dos olhos olhando para baixo, rosto legível, figurino completo.",
  "sheet.layout.action": "Congelamento de ação largo 16:9 de um personagem em meio movimento (andar ou alcançar), nítido sem desfoque de movimento, figurino completo, ambiente cinza suave.",
  "sheet.layout.dialogue": "Quadro de diálogo sobre o ombro, largo 16:9: ombro suave em primeiro plano do mesmo personagem, rosto nítido ao fundo olhando à esquerda da câmera. Só uma identidade.",
  "sheet.layout.body_nude_turnaround": "Giro de proporções corporais largo 16:9 com exatamente quatro figuras de corpo inteiro na mesma escala: frente, esquerda 90°, costas, direita 90°. A-pose neutra, braços um pouco afastados do tronco para a silhueta ficar clara, pés plantados. Só macaquinho na cor da pele. Rosto e cabelo consistentes.",
  "sheet.layout.body_nude_front": "Placa única de proporções corporais de frente, corpo inteiro, alta 9:16, à altura dos olhos, da cabeça aos pés visível, braços relaxados. Proporções corporais claras para prova de figurino. Só macaquinho na cor da pele. Postura profissional neutra.",
  "sheet.layout.body_nude_t_pose": "T-pose ou A-pose única de corpo inteiro, larga 16:9 (braços horizontais ou 30° para baixo), de frente, macaquinho na cor da pele para referência de bind/rig. Pés na largura dos ombros, rosto para a frente, energia de manequim clínico para o fluxo de figurino.",
  "sheet.layout.body_half_bare_turnaround": "Giro de metade superior descoberta, largo 16:9, com exatamente quatro figuras de corpo inteiro na mesma escala: frente, esquerda 90°, costas, direita 90°. A-pose neutra, braços um pouco afastados do tronco para a silhueta superior ficar clara, pés plantados. Metade superior descoberta + só peça de baixo simples. Rosto e cabelo consistentes.",
  "sheet.layout.body_half_bare_front": "Placa única de frente, corpo inteiro, metade superior descoberta, alta 9:16, à altura dos olhos, da cabeça aos pés visível, braços relaxados. Tronco superior nu; só peça de baixo sólida simples. Proporções corporais claras. Postura profissional neutra.",
  "sheet.layout.body_half_bare_t_pose": "T-pose ou A-pose única de corpo inteiro, larga 16:9 (braços horizontais ou 30° para baixo), de frente, metade superior descoberta para referência de bind/rig. Só peça de baixo sólida simples. Pés na largura dos ombros, rosto para a frente, energia de manequim clínico.",
  "sheet.layout.body_half_bare_lower_turnaround": "Giro de metade inferior descoberta, largo 16:9, com exatamente quatro figuras de corpo inteiro na mesma escala: frente, esquerda 90°, costas, direita 90°. A-pose neutra, pernas um pouco afastadas para a silhueta inferior ficar clara, pés plantados. Metade inferior descoberta + só parte de cima simples. Rosto e cabelo consistentes.",
  "sheet.layout.body_half_bare_lower_front": "Placa única de frente, corpo inteiro, metade inferior descoberta, alta 9:16, à altura dos olhos, da cabeça aos pés visível, braços relaxados. Pernas nuas; só parte de cima sólida simples. Proporções corporais claras. Postura profissional neutra.",
  "sheet.layout.body_half_bare_lower_t_pose": "T-pose ou A-pose única de corpo inteiro, larga 16:9 (braços horizontais ou 30° para baixo), de frente, metade inferior descoberta para referência de bind/rig. Só parte de cima sólida simples. Pés na largura dos ombros, rosto para a frente, energia de manequim clínico.",
  "sheet.layout.body_bare_turnaround": "Giro anatômico corporal completo, largo 16:9, com exatamente quatro figuras de corpo inteiro na mesma escala: frente, esquerda 90°, costas, direita 90°. A-pose neutra, braços um pouco afastados do tronco para a silhueta ficar clara, pés plantados. Só forma completamente sem roupa. Rosto e cabelo consistentes.",
  "sheet.layout.body_bare_front": "Placa anatômica única de frente, corpo inteiro, alta 9:16, à altura dos olhos, da cabeça aos pés visível, braços relaxados. Proporções corporais claras para prova de figurino. Só forma completamente sem roupa. Postura profissional neutra.",
  "sheet.layout.body_bare_t_pose": "T-pose ou A-pose única de corpo inteiro, larga 16:9 (braços horizontais ou 30° para baixo), de frente, forma completamente sem roupa para referência de bind/rig. Pés na largura dos ombros, rosto para a frente, energia de manequim clínico para o fluxo de figurino.",
  "sheet.layout.base_layer_turnaround": "Giro de camada-base largo 16:9 com exatamente quatro figuras de corpo inteiro: frente, esquerda 90°, costas, direita 90°. Só roupa íntima / vestimenta-base simples (cinza ou bege sólido), sem figurino externo. A-pose neutra.",
  "sheet.layout.base_layer_hero": "Único corpo inteiro de frente, alto 9:16, só com roupa íntima-base simples, pose em pé neutra, da cabeça aos pés. Silhueta limpa pronta para sobrepor o figurino externo depois.",
  "sheet.layout.costume_hero": "Único corpo inteiro de frente, alto 9:16, em figurino externo completo conforme desenhado, pose herói em pé, da cabeça aos pés, materiais legíveis.",
  "sheet.layout.costume_turnaround": "Giro de figurino completo largo 16:9 com exatamente quatro figuras de corpo inteiro: frente, esquerda 90°, costas, direita 90°. Mesma escala, A-pose, figurino externo completo incluindo sapatos e camadas externas.",
  "sheet.layout.costume_detail_board": "Prancha de detalhes quadrada 1:1 com exatamente quatro closes grandes do figurino completo: trama do tecido, fecho/botão, sapatos ou botas, acessório-assinatura. Sem corpo inteiro; fidelidade de material para continuidade de figurino.",
  "sheet.layout.hands": "Estudo de close quadrado 1:1 das mãos do personagem (objeto pequeno opcional). Tom de pele/superfície coincide com a identidade; nós dos dedos nítidos. Prancha de detalhe de continuidade.",
  "sheet.layout.feet_shoes": "Quadrado 1:1 com exatamente dois quadros grandes: à esquerda pés nus (ou patas/equivalente nus) sobre piso sem emendas; à direita sapatos/botas ou calçado desenhado correspondente, se o figurino tiver. Silhueta clara para troca de figurino.",
  "sheet.layout.accessories": "Prancha de acessórios quadrada 1:1: até quatro closes grandes estilo produto de chapéu, bolsa, arma, joia ou objetos-assinatura da descrição do figurino. Estúdio limpo, sem corpo inteiro.",
  "sheet.layout.silhouette": "Silhueta sólida preta pura do personagem de corpo inteiro de frente, alta 9:16, sobre branco puro ou cinza-claro, sem detalhe interno, contorno externo legível para checagem de proporções na troca de figurino. Segundo quadro opcional e tênue de silhueta de lado se o espaço permitir — prefira uma única silhueta frontal forte.",
  "plate.scene.emptySet": "Placa de local vazio para continuidade de curta: sem rostos de personagem herói, sem atores nomeados, no máximo silhuetas minúsculas ao longe se precisar de escala. Preserve arquitetura, materiais, placas e cenário-chave.",
  "plate.scene.lock.lead": "Crie um still de referência de local para continuidade de vídeo de curta IA.",
  "plate.scene.lock.identity": "Trava de identidade do espaço: mesma arquitetura, materiais, placas e linguagem de planta em todos os quadros.",
  "plate.scene.lock.forbidden": "Proibido: rostos de celebridade reconhecíveis, retratos de elenco nomeado, closes herói lotados, marcas d'água, sobreposições de texto de interface.",
  "plate.scene.lock.quality": "Qualidade: materiais nítidos, verticais estáveis, fidelidade de fotografia de direção de arte / concept art profissional.",
  "plate.scene.lock.name": "Nome do local: {{name}}",
  "plate.scene.lock.place": "Descrição do lugar: {{place}}",
  "plate.scene.lock.type": "Tipo de espaço: {{type}}",
  "plate.scene.lock.time": "Hora do dia: {{time}}",
  "plate.scene.lock.weather": "Clima: {{weather}}",
  "plate.scene.lock.mood": "Humor: {{mood}}",
  "plate.scene.lock.lighting": "Desenho de luz: {{lighting}}",
  "plate.scene.lock.palette": "Paleta de cores: {{palette}}",
  "plate.scene.lock.set": "Cenário: {{set}}",
  "plate.scene.lock.tags": "Tags visuais: {{tags}}",
  "plate.scene.scaffold.repeatMedium": "Repita: o meio deve ser o id de estilo \"{{id}}\" ({{family}}).",
  "plate.scene.scaffold.layer": "Camada da placa: {{layer}}.",
  "plate.scene.scaffold.finalCheck": "Checagem final: meio {{style}} correto; vazio de rostos herói; identidade do local travada.",
  "plate.scene.edit.task": "Tarefa de edição de imagem / reestilização de local (prioridade máxima):",
  "plate.scene.edit.keep": "Conserve a identidade do local da fonte: volume arquitetônico, materiais, placas, disposição do cenário-chave.",
  "plate.scene.edit.change": "Mude o meio e/ou a diagramação de câmera conforme o pacote de placa abaixo.",
  "plate.scene.edit.forbid": "Não invente um lugar diferente. Não acrescente rostos de personagem herói.",
  "plate.scene.layout.establishing": "Plano de estabelecimento largo 16:9 do exterior completo ou volume-mestre do local, marcos legíveis, linha do horizonte ou do teto estável, profundidade cinematográfica.",
  "plate.scene.layout.hero_plate": "Still herói de local largo 16:9 — o quadro de capa definitivo deste set. Composição forte, piso de palco ou rua claro para marcação futura.",
  "plate.scene.layout.three_quarter_space": "Espaço três-quartos largo 16:9 com moldura de primeiro plano, zona de atuação no médio e profundidade ao fundo. Palco de diálogo ideal vazio de rostos.",
  "plate.scene.layout.identity_lock": "Largo 16:9 com exatamente dois quadros iguais do mesmo local: (1) ângulo-chave frontal (2) três-quartos ~45°. Mesmos materiais, placas, paleta.",
  "plate.scene.layout.low_angle": "Ângulo baixo alto 9:16 olhando para cima à arquitetura / teto / dossel, para escala dramática. Sem rostos.",
  "plate.scene.layout.high_angle": "Diagramação em ângulo alto larga 16:9 da planta / geometria da rua para referência de marcação. Vazio de rostos.",
  "plate.scene.layout.pov_enter": "POV de entrada em primeira pessoa, largo 16:9, pela porta ou boca de beco até o local. Set vazio além do limiar.",
  "plate.scene.layout.over_shoulder_empty": "Quadro vazio sobre o ombro, largo 16:9: só silhueta suave de ombro anônimo, fundo nítido do local para marcação de diálogo.",
  "plate.scene.layout.day_clear": "Largo 16:9 o mesmo local sob luz diurna clara, direção natural do sol, sombras legíveis, superfícies secas.",
  "plate.scene.layout.golden_hour": "Largo 16:9 o mesmo local na hora dourada: sombras longas e quentes, luz de contorno âmbar, clima romântico de curta, vazio de rostos.",
  "plate.scene.layout.night_neon": "Largo 16:9 o mesmo local à noite com práticos / neon / lâmpadas de rua, vazamento ciano-magenta opcional, molhado opcional, vazio de rostos.",
  "plate.scene.layout.rain_wet": "Largo 16:9 o mesmo local na chuva: asfalto molhado/reflexos, fios de chuva, correção mais fria, guarda-chuvas só como objetos distantes, sem rostos.",
  "plate.scene.layout.fog_mood": "Largo 16:9 o mesmo local em neblina/fumaça: camadas de profundidade suaves, paleta contida, clima de mistério, arquitetura ainda legível, sem rostos.",
  "plate.scene.layout.set_dressing": "Prancha de cenário quadrada 1:1 de mesa / balcão / prateleira com objetos-chave deste local, sem pessoas.",
  "plate.scene.layout.material_board": "Prancha de continuidade de materiais quadrada 1:1: parede, piso, metal/madeira, tecido deste local. Detalhe próximo, sem rostos, sem personagens de corpo inteiro.",
  "plate.scene.layout.signage_prop": "Close quadrado 1:1 de placa / objeto-marco legível para trava de identidade do local. Formas nítidas tipo texto (pode inventar glifos se precisar). Sem rostos.",
  "plate.scene.layout.lighting_ref": "Referência de luz larga 16:9 do set vazio: direção clara da luz-chave, preenchimento, práticos, sem personagens.",
  "plate.prop.lock.lead": "Crie um still de referência de objeto para continuidade de curta IA.",
  "plate.prop.lock.name": "Nome do objeto: {{name}}",
  "plate.prop.lock.desc": "Descrição (deve coincidir): {{desc}}",
  "plate.prop.lock.material": "Composição: {{material}}",
  "plate.prop.lock.size": "Notas de tamanho: {{size}}",
  "plate.prop.lock.condition": "Estado/desgaste: {{condition}}",
  "plate.prop.lock.tags": "Tags visuais: {{tags}}",
  "plate.prop.lock.forbidden": "Proibido: rostos de celebridade, marcas d'água, objetos extras alheios que atrapalhem a identidade.",
  "plate.prop.scaffold.repeatMedium": "Repita: o meio deve ser o id de estilo \"{{id}}\".",
  "plate.prop.scaffold.finalCheck": "Checagem final: mesma identidade do objeto; meio {{style}}.",
  "plate.prop.edit.task": "Edição de imagem / reestilização de objeto:",
  "plate.prop.edit.keep": "Conserve a mesma identidade do objeto da imagem-fonte (silhueta, materiais, marcas).",
  "plate.prop.edit.change": "Mude o meio/câmera conforme necessário. Não invente um objeto diferente.",
  "plate.prop.layout.hero": "Still herói de produto único do objeto, quadrado 1:1, centrado, ciclorama cinza limpo sem emendas, materiais nítidos, sem rostos de pessoas, objeto inteiro visível.",
  "plate.prop.layout.three_quarter": "Vista três-quartos do mesmo objeto, quadrada 1:1, luz de estúdio, silhueta legível, sem mãos salvo se precisar de escala.",
  "plate.prop.layout.detail": "Close extremo quadrado 1:1 do detalhe-assinatura do objeto (gravação, fecho, tela, desgaste). Sem rostos.",
  "plate.prop.layout.material": "Placa de fidelidade de material quadrada 1:1 da superfície do objeto: textura de metal/madeira/tecido, sem pessoas de corpo inteiro.",
  "plate.prop.layout.in_hand_scale": "Referência de escala larga 16:9: mão anônima ou silhueta segurando o objeto para tamanho. Rosto fora de quadro ou totalmente anônimo. O objeto é o herói.",
  "action.geometry.panelCount": "A contagem de quadros é fixa: exatamente {{n}} quadro(s). Conte-os: {{list}}.",
  "action.geometry.lockGrid2x3": "Trava de diagramação (obrigatória): 2 linhas × 3 colunas = seis quadros no total. A linha de cima deve conter os quadros 1, 2, 3. A linha de baixo deve conter os quadros 4, 5, 6. Proibido: grade 2×2, 4 quadros, 3×2 com contagem errada, quadro herói único, colagem com menos quadros. Se der vontade de desenhar só quatro quadros — pare e desenhe os seis.",
  "action.geometry.lockGrid2x2": "Trava de diagramação (obrigatória): 2 linhas × 2 colunas = quatro quadros no total. Proibido: grade 2×3 de seis quadros, faixas horizontais, quadro único.",
  "action.geometry.lockStrip": "Trava de diagramação (obrigatória): uma linha horizontal com exatamente {{n}} quadros (1 linha × {{n}} colunas). Proibido: grade 2×2, menos de {{n}} quadros, várias linhas empilhadas salvo se especificado.",
  "action.geometry.order": "A ordem dos quadros é a linha do tempo da ação: Quadro 1 = primeiro beat de ação, Quadro {{n}} = último beat de ação.",
  "action.geometry.reading": "Ordem de leitura: esquerda → direita, depois cima → baixo (se houver várias linhas).",
  "action.geometry.numbers": "Números grandes e em negrito de 1 a {{n}} no canto de cada quadro (canto superior esquerdo daquele quadro). Cada inteiro de 1 a {{n}} deve aparecer uma vez.",
  "action.geometry.panelLine": "Quadro {{i}}/{{n}} ({{label}}): um instante sequencial distinto — pose/fase diferente de todos os outros quadros; não copie/repita poses.",
  "action.geometry.caption": "Legenda pequena em português brasileiro sob cada quadro, correspondente ao rótulo do beat.",
  "action.geometry.identity": "Mesma identidade de personagem / figurino / continuidade de objeto em todos os quadros.",
  "action.geometry.layout.strip-2": "Uma única imagem paisagem: uma faixa horizontal de roteiro gráfico com exatamente 2 quadros iguais lado a lado (1 linha × 2 colunas), calhas brancas grossas entre os quadros",
  "action.geometry.layout.strip-3": "Uma única imagem paisagem: uma faixa horizontal de roteiro gráfico com exatamente 3 quadros iguais numa linha (1 linha × 3 colunas), calhas brancas grossas",
  "action.geometry.layout.grid-2x2": "Uma única imagem quadrada: uma grade de roteiro gráfico 2×2 com exatamente 4 quadros iguais (2 linhas × 2 colunas), calhas brancas grossas, leitura esquerda→direita e depois cima→baixo",
  "action.geometry.layout.strip-4": "Uma única imagem paisagem larga: uma faixa horizontal de roteiro gráfico com exatamente 4 quadros iguais numa linha (1 linha × 4 colunas), calhas brancas grossas",
  "action.geometry.layout.strip-5": "Uma única imagem paisagem larga: uma faixa horizontal de roteiro gráfico com exatamente 5 quadros iguais numa linha (1 linha × 5 colunas), calhas brancas grossas",
  "action.geometry.layout.grid-2x3": "Uma única imagem paisagem: uma grade de roteiro gráfico com exatamente 6 quadros iguais em 2 linhas × 3 colunas (linha de cima quadros 1-2-3, linha de baixo quadros 4-5-6), calhas brancas grossas, leitura esquerda→direita e depois cima→baixo",
  "swap.costume.task": "Tarefa de edição de imagem / troca de figurino (prioridade máxima — leia por completo antes de pintar):",
  "swap.costume.sameCharacter": "Você está vestindo o mesmo personagem da imagem-fonte só com um figurino externo novo.",
  "swap.costume.identity": "Trava de identidade (nunca mude): forma de rosto/cabeça, olhos, cor e corte de cabelo, proporções corporais, espécie/plano corporal, pele ou marcas de superfície, apresentação de idade.",
  "swap.costume.pose": "Trava de pose: conserve a mesma pose corporal e o mesmo enquadramento da fonte, salvo se a diagramação abaixo exigir uma prancha de várias vistas.",
  "swap.costume.replace": "Substituição de figurino (sempre): retire toda a roupa externa anterior, armadura, casacos, vestidos, uniformes, equipamento externo e sapatos que não combinam da fonte.",
  "swap.costume.paint": "Depois pinte só o figurino externo novo descrito abaixo — cobertura completa, silhueta correta, materiais legíveis, calçado e acessórios externos correspondentes.",
  "swap.costume.new": "Novo figurino externo (deve coincidir exatamente, alta prioridade): {{costume}}",
  "swap.costume.add": "Se a fonte estiver nua ou só com roupa íntima de camada-base: acrescente o figurino externo completo por cima, preservando a anatomia e a lógica da subcamada.",
  "swap.costume.complete": "Se a fonte já usa um figurino: substitua por completo — não misture, empilhe nem deixe fantasma do traje antigo sob o novo.",
  "swap.costume.edges": "As bordas da roupa devem assentar corretamente em ombros, cintura, pulsos e tornozelos; sem tecido flutuando, sem membros fundidos.",
  "swap.costume.forbidden": "Proibido: mudar espécie, idade, identidade do rosto, forma do corpo, segundo personagem, pose erótica, marcas d'água, legendas de texto, moldura de interface.",
  "swap.costume.nonHuman": "Sujeitos não humanos: cobertura / equipamento externo adequado à espécie, coincidindo com a descrição do figurino.",
  "swap.costume.subject": "Sujeito: {{name}}",
  "swap.costume.age": "Idade / maturidade: {{age}}",
  "swap.costume.gender": "Gênero / apresentação: {{gender}}",
  "swap.costume.appearance": "Trava de aparência: {{appearance}}",
  "swap.costume.tags": "Tags visuais: {{tags}}",
  "swap.costume.manner": "Só dicas de maneirismo: {{manner}}",
  "swap.costume.checklist": "Lista final: (1) mesmo rosto/corpo da fonte (2) só o figurino novo visível (3) meio = {{style}} (4) estúdio limpo ou fundo neutro.",
  "swap.costume.layout.hero_front": "Única pose em pé de corpo inteiro de frente, alta 9:16, da cabeça aos pés visível, postura herói neutra, braços relaxados, pés plantados. Só um personagem.",
  "swap.costume.layout.three_quarter": "Único retrato três-quartos (~45°) de corpo inteiro, quadrado 1:1, de preferência da cabeça aos pés, silhueta do figurino novo legível.",
  "swap.costume.layout.profile": "Único perfil verdadeiro de corpo inteiro (vista lateral 90°), alto 9:16, da cabeça aos pés, postura neutra, silhueta do figurino e costuras laterais totalmente legíveis. Só um personagem.",
  "swap.costume.layout.back": "Única vista traseira de corpo inteiro, alta 9:16, da cabeça aos pés, braços um pouco afastados do corpo para as costas do casaco/vestido/cabelo e a silhueta traseira ficarem claras. Só um personagem.",
  "swap.costume.layout.bust": "Único retrato de busto do tronco superior (do peito para cima), alto 3:4, gola, decote, ombros, camadas externas e joias no rosto legíveis; não é um recorte de corpo inteiro. Só um personagem.",
  "swap.costume.layout.detail_fabric": "Prancha de detalhes de figurino quadrada 1:1: closes da trama do tecido, botões, zíperes, bordado, ferragens do cinto e transições de material só do figurino externo novo; sem cena completa, sem segundo personagem.",
  "swap.costume.layout.turnaround": "Giro largo 16:9 com exatamente quatro figuras de corpo inteiro na mesma escala: frente, esquerda 90°, costas, direita 90°. A-pose neutra, figurino novo completo em cada vista.",
  "swap.atmosphere.task": "Tarefa de edição de imagem / troca de atmosfera (prioridade máxima):",
  "swap.atmosphere.keep": "Conserve a identidade do local da fonte: volume dos edifícios, paredes, pistas de planta, placas, disposição dos móveis, ângulo de câmera.",
  "swap.atmosphere.replace": "Substitua por completo: hora do dia, clima, céu, cor da luz prática, umidade, neblina, intensidade de neon conforme descrito.",
  "swap.atmosphere.new": "Nova atmosfera (deve coincidir exatamente): {{atmo}}",
  "swap.atmosphere.forbidden": "Proibido: transformar a arquitetura em outro lugar, acrescentar rostos herói, marcas d'água, legendas de texto.",
  "swap.atmosphere.location": "Local: {{title}}",
  "swap.atmosphere.place": "Lugar-base: {{place}}",
  "swap.atmosphere.set": "Trava de cenário: {{set}}",
  "swap.atmosphere.tags": "Tags visuais: {{tags}}",
  "swap.atmosphere.checklist": "Lista final: mesma geometria do lugar; só a atmosfera mudou; meio {{style}}; sem rostos herói.",
  "swap.atmosphere.repeatMedium": "Repita: o meio deve ser o id de estilo \"{{id}}\" ({{family}}).",
  "swap.atmosphere.layout.wide": "Quadro completo do local, largo 16:9, coincidindo o mais possível com a composição da fonte.",
  "swap.atmosphere.layout.hero": "Still herói de local largo 16:9, mesma arquitetura, só a atmosfera atualizada.",
  "swap.atmosphere.layout.detail": "Detalhe atmosférico quadrado 1:1 de superfícies molhadas / luzes práticas / céu, ainda reconhecível como o mesmo set.",
}
