import type { PromptCopyTable } from './keys'

export const ptBrPromptCopy: PromptCopyTable = {
  "speechLock.named": "SPEECH LOCK · Personagem \"{{who}}\": a fala audível E o lip-sync DEVEM ser só {{primaryName}} ({{primary}}). Não fale {{forbid}} nem outro idioma. Mantenha o mesmo idioma em cada clipe. Não traduza o diálogo.",
  "speechLock.unnamed": "SPEECH LOCK · Personagens que falam: a fala audível E o lip-sync DEVEM ser só {{primaryName}} ({{primary}}). Não fale {{forbid}} nem outro idioma. Mantenha o mesmo idioma em cada clipe. Não traduza o diálogo.",
  "speechLock.namedMulti": "SPEECH LOCK · Personagem \"{{who}}\": a fala audível E o lip-sync DEVEM ser {{primaryName}} ({{primary}}). Outros idiomas SÓ se a linha do roteiro já estiver nesse idioma: {{extras}}. Nunca um terceiro idioma. Não troque de idioma entre clipes. Não mude para {{forbid}}. Não traduza.",
  "speechLock.unnamedMulti": "SPEECH LOCK · Personagens que falam: a fala audível E o lip-sync DEVEM ser {{primaryName}} ({{primary}}). Outros idiomas SÓ se a linha do roteiro já estiver nesse idioma: {{extras}}. Nunca um terceiro idioma. Não troque de idioma entre clipes. Não mude para {{forbid}}. Não traduza.",
  "storyBeats.system": "You write short-drama TIMELINE BEATS for AI video.\nEach beat = ONE short clip screenplay (not a single spoken line).\nA beat MUST include rich performance content: mood, atmosphere, actions, expressions, optional camera/sfx, and zero or more spoken dialogue lines (1–4 lines common).\nReturn ONLY a JSON array (no fences). Each item shape:\n{\"characterName\":\"…\",\"characterNames\":[\"…\"],\"sceneHint\":\"…\",\"propName\":\"…\",\"mood\":\"…\",\"atmosphere\":\"…\",\"camera\":\"…\",\"sfx\":\"…\",\"units\":[{\"type\":\"action\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"expression\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"dialogue\",\"who\":\"…\",\"line\":\"…\",\"tone\":\"…\",\"parenthetical\":\"…\"},{\"type\":\"note\",\"text\":\"…\"}]}\nRules:\n- units.type dialogue.line = ONLY words the character speaks (no stage directions inside line).\n- Put physical business in action; face/micro-performance in expression; delivery in tone/parenthetical.\n- Multiple dialogue units in one beat are encouraged when the clip has a short exchange or self-talk.\n- Pure action beats (no dialogue) are allowed.\n- Write 4–8 beats. Use only cast names provided.\n- Prefer conflict, clear visual action, filmable detail.\n- Stay faithful to the title, style, cast, and scenes provided.\n- SPEECH: write each dialogue.line in that speaker's primary spoken language from the cast list. Do not switch languages between beats. Do not translate lines unless that is the character's listed language.",
  "storyBeats.userLead": "GERE beats de roteiro de clipe usando TODO o elenco, cenas, props, estilo e ideia abaixo.",
  "storyBeats.eachBeat": "Cada beat precisa de humor + atmosfera + ações/expressões + diálogo opcional.",
  "storyBeats.story": "História: {{title}}",
  "storyBeats.style": "Estilo: {{style}}",
  "storyBeats.userDir": "Indicação do usuário: {{idea}}",
  "storyBeats.cast": "Elenco:",
  "storyBeats.scenes": "Cenas:",
  "storyBeats.props": "Objetos: {{props}}",
  "storyBeats.returnJson": "Devolva só o array JSON dos beats.",
  "storyBeats.noCast": "(sem elenco)",
  "storyBeats.noScenes": "(sem cenas — invente lugares em sceneHint)",
  "storyBeats.none": "(nenhum)",
  "videoPolish.system": "Você escreve UM prompt final image-to-video para um modelo de vídeo de drama curto.\nDevolva SÓ o texto do prompt — sem cercas markdown, título ou explicação.\nRegras:\n- Escreva o prompt de direção no idioma da interface; deixe claros nomes e códigos de idioma das falas.\n- Still de pessoa: IDENTITY LOCK. Placa de lugar: SPACE LOCK. Não acrescente rostos novos a menos que os materiais os nomeiem.\n- Use TODOS os fatos de perfil / soul / beat / local que afetem visual, movimento, fala ou atmosfera; ignore campos vazios.\n- Invente só o necessário para um clipe filmável a partir dos materiais e do seed — não importe mundo-amostra, Demo ou fatos ausentes.\n- Condensar soul.md longo em beats de atuação e identidade; não colar a bíblia inteira.\n- Use a duração dos materiais (segundos reais do clipe). Ação contínua. Sem texto, logos, marcas d'água nem gente extra.\n- Anatomia humana correta salvo o roteiro (duas mãos, dois braços, duas pernas).\n- Se houver vários personagens, mantenha cada um; foco principal primeiro.\n- Se houver HARD RULES, conserve-as e coloque no fim (prioridade máxima).\n- SPEECH LOCK é obrigatório: não apague, reescreva nem traduza. Expanda códigos para nomes. Cada clipe usa a língua principal do personagem; não mude de idioma entre clipes; não traduza falas.\n- Revisão de direção pode refinar estilo/ação, mas NÃO violar HARD RULES.",
  "videoPolish.hardRulesKeep": "HARD RULES (HIGHEST PRIORITY — keep every line; object labels like [Character · Name] must stay). Place the full HARD RULES block at the END of your output. Do not weaken, drop, or reassign rules.",
  "clip.task": "TAREFA: clipe da timeline de drama curto (imagem para vídeo).",
  "clip.hasRef": "A reference still may be attached — lock identity/location continuity to it when relevant.",
  "clip.characters": "Personagens:",
  "clip.scene": "Cena:",
  "clip.prop": "Objeto:",
  "clip.action": "Guia de ação / movimento:",
  "clip.beat": "Beat / diálogo:",
  "clip.prev": "Continuidade do clipe anterior:",
  "clip.revision": "REVISÃO DO DIRETOR (obrigatória):",
  "clip.templateDraft": "Rascunho de modelo (melhorar):",
  "intro.task": "TAREFA: clipe de apresentação de elenco (imagem para vídeo).",
  "intro.hasRef": "Reference still is attached to the video API — lock identity to that image.",
  "intro.noRef": "No reference still path in this text; still lock to profile appearance/costume.",
  "intro.dossier": "Dossiê do personagem:",
  "intro.templateDraft": "Rascunho de modelo (melhore; não ignore o dossiê):",
  "common.durationAspect": "Duração: {{seconds}}s. Proporção: {{aspect}}.",
  "common.templateDraft": "Rascunho de modelo:",
  "improve.mode": "MODO MELHORAR: una TODAS as fontes num resultado completo. Mantenha a identidade salvo pedido explícito.",
  "improve.draftDefault": "Campos atuais do formulário:",
  "improve.userRequest": "Pedido de melhoria (vazio = polir e unir tudo):",
  "improve.emptyDefault": "(polir todos os campos para continuidade)",
  "improve.createDefault": "Ideia / direção:",
  "improve.explicitContext": "Contexto explícito SÓ deste pedido (continuidade; não importe outro mundo):",
  "improve.storyTitle": "Título: {{title}}",
  "improve.styleNote": "Nota de estilo: {{style}}",
  "improve.closingDefault": "Entregue o resultado completo agora.",
  "storyMeta.system": "Você é showrunner. Escreva bíblia visual e regras duras. SÓ JSON.",
  "storyMeta.draftLabel": "Campos atuais da história:",
  "storyMeta.createLabel": "Ideia / título:",
  "storyMeta.emptyPolish": "(polir bíblia + hardRules)",
  "storyMeta.closing": "SÓ JSON: {\"styleNote\":\"…\",\"hardRules\":\"…\"}. As duas chaves são obrigatórias.",
  "storyMeta.contextLabel": "Contexto (elenco / cenas / objetos):",
  "character.system": "Você é designer de personagens. SÓ um JSON. spokenLanguages = array BCP-47.",
  "character.draftLabel": "Campos atuais do perfil:",
  "character.soulLabel": "soul.md / bíblia ligada:",
  "character.createLabel": "Ideia de personagem:",
  "character.emptyPolish": "(polir e integrar soul)",
  "character.closing": "JSON completo. Chaves: {{keys}}.",
  "scene.system": "Você é designer de locações. Bíblia do lugar + roteiro desta cena. SÓ JSON.",
  "scene.draftLabel": "Campos atuais da cena:",
  "scene.charsLabel": "Personagens da história:",
  "scene.propsLabel": "Objetos da história:",
  "scene.priorLabel": "Cenas anteriores (continuidade):",
  "scene.createLabel": "Ideia de cena:",
  "scene.emptyPolish": "(polir lugar + roteiro)",
  "scene.closing": "JSON completo. Chaves: {{keys}}.",
  "prop.system": "Você é designer de objetos. SÓ um JSON. Visual, material e estado concretos.",
  "prop.draftLabel": "Campos atuais do objeto:",
  "prop.createLabel": "Ideia de objeto:",
  "prop.emptyPolish": "(polir o visual)",
  "prop.closing": "JSON completo. Chaves: {{keys}}.",
  "prop.fallbackName": "Objeto",
  "action.system": "Você é diretor de movimento. JSON válido só. Corpo, tempo, peso, trajetórias.",
  "action.storyContext": "Contexto da história (opcional): {{title}}",
  "action.styleNote": "Nota de estilo: {{style}}",
  "action.existingDraft": "Rascunho existente para polir:",
  "action.userIdea": "Ideia do usuário: {{idea}}",
  "action.closing": "Só JSON. Chaves: {{keys}}.",
  "profile.mustEveryKey": "Você DEVE emitir CADA chave: {{keys}}.",
  "profile.valuesAreStrings": "Cada valor DEVE ser string JSON. Vazio só se desconhecido.",
  "profile.visualTagsRule": "visualTags: uma string separada por vírgulas. NUNCA um array JSON.",
  "profile.fillConcrete": "Preencha com detalhe concreto.",
  "common.rules": "Regras:",
  "common.none": "(nenhum)",
  "intro.soul": "soul.md (fonte de interpretação/identidade):\n{{soul}}",
  "intro.matchBible": "(seguir a bíblia do personagem)",
  "invent.sources": "Fontes da verdade, nesta ordem: (1) ideia/pedido, (2) formulário, (3) extras só se estiverem NESTE prompt, (4) imagem anexada.",
  "invent.create": "Modo criar: invente livremente a partir da ideia/imagem; não deixe chaves obrigatórias vazias.",
  "invent.improve": "Modo melhorar: polir o rascunho; não troque a identidade salvo pedido.",
  "invent.noImport": "NÃO importe identidade, trama, clima, ofício, lugar, época ou estilo de fora deste prompt.",
  "invent.storyBlock": "Bloco de história/estilo só para continuidade; não anule a ideia explícita.",
  "character.keysLead": "APENAS um JSON com chaves: {{keys}}",
  "character.ruleSpoken": "spokenLanguages: array BCP-47 dos idiomas FALADOS. [] se não verbal.",
  "character.ruleIdentity": "Identidade coerente em pranchas e vídeo.",
  "scene.keysLead": "APENAS um JSON com chaves: {{keys}}",
  "scene.suggestLead": "Proponha um LOCAL pronto como cena nº {{n}} de \"{{title}}\".",
  "scene.suggestPlotFocus": "Foco da trama: {{label}}",
  "scene.suggestStyle": "Estilo: {{style}}",
  "scene.suggestExisting": "Locais já existentes: {{titles}}",
  "scene.suggestChars": "Personagens (contexto):",
  "scene.suggestProps": "Objetos (contexto):",
  "scene.suggestSegment": "Detalhe do segmento:",
  "scene.suggestBeats": "Cenas / beats:",
  "scene.suggestClosing": "Devolva o JSON completo. Desenhe um local reutilizável e distinto.",
  "scene.fallbackName": "Local",
  "scene.ideaFromImage": "Invente o perfil completo do local a partir da foto anexada.",
  "scene.polishIdea": "Polir",
  "prop.keysLead": "APENAS um JSON com chaves: {{keys}}",
  "action.fieldsLead": "Campos: {{keys}}.",
  "soul.system": "Você escreve soul.md de produção. Só markdown completo. Respeite spokenLanguages. Idioma da interface.",
  "soul.improveMode": "MODO MELHORAR: una perfil + soul existente num soul.md completo.",
  "soul.createMode": "Escreva um soul.md completo a partir deste perfil (não invente outra pessoa):",
  "soul.profileFields": "Campos do perfil:",
  "soul.existing": "soul.md existente (una; não descarte detalhe útil):",
  "soul.userRequest": "Pedido: {{request}}",
  "soul.extraContext": "Contexto extra (útil sim; o perfil vence):",
  "soul.returnOnly": "Devolva só o markdown do soul.md.",
  "wardrobe.system": "Você é consultor de figurino. UM JSON só. artStyle deve ser um de: {{styleIds}}. Materiais e silhueta concretos. Nunca erotize menores.",
  "wardrobe.improveMode": "MODO MELHORAR / SUGERIR: use TODOS os campos e o contexto.",
  "wardrobe.characterForm": "Personagem (formulário completo):",
  "wardrobe.soulExcerpt": "Trecho soul.md:\n{{soul}}",
  "wardrobe.userRequest": "Pedido: {{request}}",
  "wardrobe.storyContext": "Contexto de produção (use se houver; não invente outro mundo):",
  "wardrobe.style": "estilo: {{style}}",
  "wardrobe.segment": "Segmento escolhido: {{label}}",
  "wardrobe.sceneContext": "Cena / beat:",
  "wardrobe.noScenes": "(ainda sem cenas)",
  "wardrobe.proposeNew": "Proponha um look NOVO que sirva (sem duplicar).",
  "fill.system": "Você completa campos vazios. JSON com EXATAMENTE estas chaves: {{keys}}. Cada valor é string não vazia. Nunca array.",
  "fill.userPartial": "Perfil parcial (não contradiga):",
  "fill.userOnly": "Preencha SÓ estas chaves: {{keys}}.",
  "fill.userReturn": "JSON só com essas chaves; valores não vazios.",
  "imageGen.multiRef": "{{n}} stills a mais: o primeiro é a base; mantenha a identidade em todos.",
  "residual.sceneLink": "Cena {{n}}: {{short}}",
  "residual.beatSegment": "Beat {{n}} · {{who}}{{tail}}",
  "residual.unknown": "Desconhecido",
  "residual.story": "História",
  "beat.mood": "[MOOD] {{text}}",
  "beat.atmo": "[ATMO] {{text}}",
  "beat.camera": "[CAMERA] {{text}}",
  "beat.sfx": "[SFX] {{text}}",
  "beat.action": "[ACTION] {{text}}",
  "beat.actionWho": "[ACTION|{{who}}] {{text}}",
  "beat.expr": "[EXPR] {{text}}",
  "beat.exprWho": "[EXPR|{{who}}] {{text}}",
  "beat.dialogue": "[DIALOGUE|{{who}}] {{body}}",
  "beat.dialogueTone": "[DIALOGUE|{{who}}|{{tone}}] {{body}}",
  "beat.whoUnknown": "?",
  "beat.template": "[MOOD] tense, hesitant\n[ATMO] door-gap warm light; rain on ground\n[CAMERA] medium shot, push to hands\n[SFX] rain, fabric rustle\n[ACTION|Name] removes helmet; stares at the door light; hand into jacket pocket\n[EXPR|Name] furrowed brow, breath catches\n[DIALOGUE|Name|low, hoarse] Raining again…\n[DIALOGUE|Name|aside] (beat) Are you… still there?",
  "vision.preamble": "Há um still anexado. Preencha TODOS os campos deste {{what}} principalmente A PARTIR DA IMAGEM.",
  "vision.character": "identidade (nome, aparência, figurino, idade, gênero, tags)",
  "vision.scene": "local (título, descrição, luz, clima, cenário, tags)",
  "vision.prop": "objeto (nome, descrição, material, tamanho, estado, tags)",
  "vision.action": "ação (nome, descrição, ritmo, intenção, câmera, tags)",
  "vision.costume": "figurino (nome, descrição completa)",
  "still.header": "UM ÚNICO STILL-CHAVE para continuidade de vídeo (não um board multipainel). Um fotograma herói que bata com o plano. Sem texto, logos, marcas nem UI.",
  "still.revision": "MELHORIA DO USUÁRIO PARA ESTE STILL (obrigatória): {{notes}}",
  "still.regenTask": "TAREFA: revise o prompt de diretor image-to-video e mantenha-o usável como brief de keyframe.",
  "still.userImprove": "PEDIDO DE MELHORIA:\n{{notes}}",
  "still.currentPrompt": "Prompt profissional atual:",
  "still.hardRules": "HARD RULES (no fim; não enfraqueça):",
  "mediaGen.writeOne": "Escreva UM prompt final de imagem para um still de drama curto.",
  "mediaGen.returnOnly": "SÓ o texto do prompt — sem markdown.",
  "mediaGen.singleComposite": "Descreva UMA única imagem composta.",
  "mediaGen.lockRefs": "As imagens anexadas são a verdade visual (ordem Ref#). Não invente outra pessoa, loja ou objeto.",
  "mediaGen.videoSystem": "Você escreve prompts de diretor image-to-video.",
  "mediaGen.videoMerge": "Una os materiais num ÚNICO prompt de vídeo.",
  "mediaGen.videoInclude": "Inclua: trava de identidade, câmera, atuação/diálogo, ritmo, luz.",
  "mediaGen.videoFacts": "Só fatos dos materiais e do seed. Sem Demo.",
  "mediaGen.videoNoSwap": "Com refs, não troque ator, local nem objeto.",
  "mediaGen.videoHardRules": "HARD RULES no fim se houver.",
  "mediaGen.imageSystem": "Você é diretor de prompts de imagem.",
  "mediaGen.imageMergeStills": "Una materiais e stills num ÚNICO prompt de imagem.",
  "mediaGen.imageMergeText": "Una os textos num ÚNICO prompt de imagem.",
  "mediaGen.imagePriority": "Prioridade: rostos/figurinos/locais/objetos das imagens.",
  "mediaGen.imageNoSwap": "Não substitua por outra celebridade ou set alheio se houver stills de elenco.",
  "mediaGen.imageFacts": "Só fatos dos materiais e do seed.",
  "mediaGen.imageLayout": "Se for multipainel, preserve a contagem exata.",
  "mediaGen.imagePackage": "Se houver LAYOUT, o prompt DEVE aplicar esse layout exato.",
  "mediaGen.imageHardRules": "HARD RULES no fim se houver.",
  "mediaGen.directorFallback": "IMAGEM-PARA-VÍDEO: anime este keyframe. Trave identidade, figurino, set e enquadramento.",
  "mediaGen.directorFallbackCam": "Câmera e atuação claras; sem legendas nem marca d’água.",
  "charIntro.task": "IMAGEM-PARA-VÍDEO: anime a mesma pessoa num auto-casting curto.",
  "charIntro.identityLock": "TRAVA DE IDENTIDADE: mesmo rosto, cabelo, corpo, idade, figurino e cores.",
  "charIntro.personality": "Personalidade / vibe: {{personality}}.",
  "charIntro.backstory": "História: {{backstory}}.",
  "charIntro.relationships": "Relações: {{relationships}}.",
  "charIntro.soul": "Trecho soul (fonte de atuação): {{soul}}",
  "charIntro.performance": "Atuação: leve travelling ou câmera na mão; olha para a câmera; {{manner}}.",
  "charIntro.speech": "Fala: a boca se move como uma apresentação breve; voz: {{voice}}.",
  "charIntro.beat": "Idle natural → sorriso ou aceno → gesto breve → hold.",
  "charIntro.lighting": "Luz coerente com o still; sem texto, logos nem extra gente.",
  "sceneIntro.task": "IMAGEM-PARA-VÍDEO: anime o mesmo local como plano de estabelecimento.",
  "sceneIntro.spaceLock": "TRAVA DE ESPAÇO: mesma arquitetura, materiais, placas, planta e cor.",
  "sceneIntro.name": "Nome do local: {{name}}.",
  "sceneIntro.place": "Descrição: {{place}}.",
  "sceneIntro.spaceType": "Tipo de espaço: {{type}}.",
  "sceneIntro.time": "Hora do dia: {{time}}.",
  "sceneIntro.weather": "Clima: {{weather}}.",
  "sceneIntro.moodLight": "Clima: {{mood}}. Luz: {{lighting}}.",
  "sceneIntro.palette": "Paleta: {{palette}}.",
  "sceneIntro.setDressing": "Cenário: {{set}}.",
  "sceneIntro.tags": "Tags visuais: {{tags}}.",
  "sceneIntro.art": "Estilo: {{art}}.",
  "sceneIntro.ambient": "Ambiente (sem texto de UI): {{sound}}.",
  "sceneIntro.scriptCue": "Dica de beat (só atmosfera): {{cue}}.",
  "sceneIntro.camera": "Câmera: {{camera}}; movimento contínuo. Não acrescente rostos, logos nem texto salvo se os materiais já os mostrarem.",
  "sceneIntro.beat": "Estabelecer → vida ambiental sutil → hold.",
  "propIntro.task": "IMAGEM-PARA-VÍDEO: anime o mesmo objeto como intro de produto.",
  "propIntro.objectLock": "TRAVA DE OBJETO: mesma silhueta, materiais, cores, gravuras e desgaste.",
  "propIntro.name": "Nome: {{name}}.",
  "propIntro.look": "Aparência: {{look}}.",
  "propIntro.material": "Material: {{material}}.",
  "propIntro.size": "Tamanho: {{size}}.",
  "propIntro.condition": "Estado: {{condition}}.",
  "propIntro.tags": "Tags: {{tags}}.",
  "propIntro.art": "Estilo: {{art}}.",
  "propIntro.camera": "Órbita suave ou travelling lento em mesa limpa; luz coerente.",
  "propIntro.beat": "Hold → brilho / microgiro → hold.",
  "propIntro.noHands": "Sem mãos nem rostos novos se não estiverem no still; sem texto nem extras.",
  "costumeIntro.task": "IMAGEM-PARA-VÍDEO: anime o mesmo look como intro de figurino.",
  "costumeIntro.wardrobeLock": "TRAVA DE FIGURINO: mesma silhueta, tecidos, cores, camadas e acessórios.",
  "costumeIntro.identityOrProduct": "Se houver pessoa: trave rosto/corpo; se manequim/plano: enquadramento de produto.",
  "costumeIntro.name": "Nome do look: {{name}}.",
  "costumeIntro.desc": "Figurino: {{look}}.",
  "costumeIntro.art": "Estilo: {{art}}.",
  "costumeIntro.camera": "Leve travelling ou órbita; luz de moda coerente.",
  "costumeIntro.beat": "Hold → queda de tecido / brilho de ferragens → hold.",
  "costumeIntro.forbid": "Sem rostos novos, texto, logos nem pose erótica.",
  "costumeIntro.fallbackName": "Look",
  "actionIntro.lead": "Vídeo demo da ação \"{{name}}\".",
  "actionIntro.intention": "Intenção: {{intention}}",
  "actionIntro.body": "Corpo/tempo: {{body}}",
  "actionIntro.camera": "Câmera: {{camera}}",
  "actionIntro.closing": "Movimento contínuo, sem texto; siga o still.",
  "sceneIntroPolish.task": "TAREFA: intro de local (imagem-para-vídeo).",
  "sceneIntroPolish.hasRef": "Still de local anexado — trave a identidade ESPACIAL.",
  "sceneIntroPolish.noRef": "Sem still; trave à bíblia do local.",
  "sceneIntroPolish.dossier": "Dossiê do local:",
  "sceneIntroPolish.scriptCue": "dica de roteiro (só atmosfera):\n{{script}}",
  "sceneIntroPolish.emptySet": "Set vazio; sem rostos novos. Sem texto nem logos.",
  "propIntroPolish.task": "TAREFA: intro herói de objeto (imagem-para-vídeo).",
  "propIntroPolish.hasRef": "Still de objeto anexado — trave o OBJETO.",
  "propIntroPolish.noRef": "Sem still; trave ao dossiê.",
  "propIntroPolish.dossier": "Dossiê do objeto:",
  "propIntroPolish.noHands": "Sem mãos nem rostos novos. Sem texto nem logos.",
  "costumeIntroPolish.task": "TAREFA: intro de figurino (imagem-para-vídeo).",
  "costumeIntroPolish.hasRef": "Still anexado — pessoa: identidade+roupa; manequim: silhueta e materiais.",
  "costumeIntroPolish.noRef": "Sem still; trave à descrição.",
  "costumeIntroPolish.dossier": "Dossiê de figurino:",
  "costumeIntroPolish.fabric": "Queda sutil de tecido; sem rostos novos nem texto.",
  "actionIntroPolish.task": "TAREFA: intro de guia de movimento (imagem-para-vídeo).",
  "actionIntroPolish.hasRef": "Still anexado — trave a identidade de atuação àquele quadro.",
  "actionIntroPolish.templateKeepRules": "Rascunho modelo (melhore; HARD RULES no fim):",
  "cover.posterLead": "PÔSTER / KEY ART profissional 16:9. Não é mockup de UI. Sem texto, logo nem marca.",
  "cover.titleMood": "Título (só clima, não escreva na imagem): {{title}}.",
  "cover.styleBible": "Bíblia de estilo: {{style}}",
  "cover.extraDir": "Direção extra: {{idea}}",
  "cover.establishing": "Plano de estabelecimento evocativo para capa da biblioteca.",
  "cover.medium": "Respeite o medium; silhueta forte.",
  "cover.editPrefix": "IMAGE EDIT: nova composição de pôster. Mantenha identidade/clima. ",
  "cover.label": "Capa da história",
  "costumeFill.system": "Você é figurinista. Só JSON compacto. Se houver imagem, descreva ESSE look com fidelidade.",
  "costumeFill.idea": "Ideia: {{idea}}",
  "costumeFill.polish": "Polir o rascunho de figurino.",
  "costumeFill.required": "Chaves: name, description, artStyle, hardRules. Faltar = inválido.",
  "costumeFill.fallbackName": "Look",
  "segment.entireStory": "Toda a história (todas as cenas)",
  "segment.noStory": "Nenhuma história (só ficha do personagem)",
  "vision.inventFromImage": "Descreva e invente um perfil completo de {{kind}} a partir da foto anexada.",
  "vision.polishAll": "Polir e unir todos os campos",
  "story.untitled": "Drama curto sem título",
  "action.castIdentityNote": "Stills de identidade ({{count}}): rosto/corpo iguais às referências de elenco em cada painel.",
  "tpl.system.polishOnly": "RECEITA só polir: mantenha identidade e mundo. Polir o texto. Não invente era, clima, ofício, lugar nem mundo-amostra. Não invente idioma falado. Não grave HARD RULES padrão no perfil.",
  "tpl.system.fillBlanks": "RECEITA só vazios: preencha SÓ chaves vazias. Não reescreva o que já está preenchido. Não invente outro mundo.",
  "tpl.system.invent": "RECEITA inventar: o usuário autorizou criar livremente. Complete cada chave filmável. Não importe Demo nem mundo não implícito.",
  "tpl.system.fromStory": "RECEITA da história: use só título/estilo/elenco/cenas DESTE pedido. Em conflito, a ideia do usuário vence.",
  "tpl.system.followAsset": "RECEITA seguir ativo: siga o estilo já dado. Não force cinema, set vazio nem 6–10 s salvo se os materiais disserem. Use a duração real do clipe.",
  "tpl.system.cinematicLock": "RECEITA cine+anti-alucinação: visual cinematográfico; set vazio; sem marca, logo nem rostos extras; duas mãos/braços/pernas salvo não humano.",
  "tpl.system.identityLock": "RECEITA trava de identidade: trave rosto/corpo/roupa/lugar/objeto aos stills. Não substitua pessoa, lugar ou objeto.",
  "tpl.system.restyle": "RECEITA restyle: a mesma pessoa. Figurino, set e época podem mudar se pedido. Não troque de pessoa.",
  "pipeline.character.system": "Você refina bíblias de personagem. 3–5 linhas: visual, voz, motivo, gesto. Só fatos deste pedido.",
  "pipeline.scene.system": "Você expande cenas em folhas de beats. Use a duração real; não assuma 6–10 s. Só cenas dadas.",
  "pipeline.props.system": "Você refina continuidade de objetos. Cor, tamanho e quando aparece. Não invente objetos fora da lista.",
  "pipeline.script.system": "Você é roteirista. Um bloco compacto por cena para vídeo IA. Duração real; não force 10 s. Formato:\n### SCENE <number> | id=<id>\n<script body>",
  "pipeline.script.noScenes": "(sem cenas — não invente locais)"
}