import type { PromptCopyTable } from './keys'

export const ruPromptCopy: PromptCopyTable = {
  "speechLock.named": "SPEECH LOCK · Персонаж «{{who}}»: слышимая речь И артикуляция ДОЛЖНЫ быть только {{primaryName}} ({{primary}}). Не переходите на {{forbid}} или другой язык. Один язык на всех клипах. Не переводите реплики.",
  "speechLock.unnamed": "SPEECH LOCK · Говорящие персонажи: слышимая речь И артикуляция ДОЛЖНЫ быть только {{primaryName}} ({{primary}}). Не переходите на {{forbid}} или другой язык. Один язык на всех клипах. Не переводите реплики.",
  "speechLock.namedMulti": "SPEECH LOCK · Персонаж «{{who}}»: слышимая речь И артикуляция ДОЛЖНЫ быть {{primaryName}} ({{primary}}). Другие языки ТОЛЬКО если строка сценария уже на этом языке: {{extras}}. Третий язык запрещён. Не меняйте язык между клипами. Не переходите на {{forbid}}. Не переводите.",
  "speechLock.unnamedMulti": "SPEECH LOCK · Говорящие персонажи: слышимая речь И артикуляция ДОЛЖНЫ быть {{primaryName}} ({{primary}}). Другие языки ТОЛЬКО если строка сценария уже на этом языке: {{extras}}. Третий язык запрещён. Не меняйте язык между клипами. Не переходите на {{forbid}}. Не переводите.",
  "storyBeats.system": "You write short-drama TIMELINE BEATS for AI video.\nEach beat = ONE short clip screenplay (not a single spoken line).\nA beat MUST include rich performance content: mood, atmosphere, actions, expressions, optional camera/sfx, and zero or more spoken dialogue lines (1–4 lines common).\nReturn ONLY a JSON array (no fences). Each item shape:\n{\"characterName\":\"…\",\"characterNames\":[\"…\"],\"sceneHint\":\"…\",\"propName\":\"…\",\"mood\":\"…\",\"atmosphere\":\"…\",\"camera\":\"…\",\"sfx\":\"…\",\"units\":[{\"type\":\"action\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"expression\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"dialogue\",\"who\":\"…\",\"line\":\"…\",\"tone\":\"…\",\"parenthetical\":\"…\"},{\"type\":\"note\",\"text\":\"…\"}]}\nRules:\n- units.type dialogue.line = ONLY words the character speaks (no stage directions inside line).\n- Put physical business in action; face/micro-performance in expression; delivery in tone/parenthetical.\n- Multiple dialogue units in one beat are encouraged when the clip has a short exchange or self-talk.\n- Pure action beats (no dialogue) are allowed.\n- Write 4–8 beats. Use only cast names provided.\n- Prefer conflict, clear visual action, filmable detail.\n- Stay faithful to the title, style, cast, and scenes provided.\n- SPEECH: write each dialogue.line in that speaker's primary spoken language from the cast list. Do not switch languages between beats. Do not translate lines unless that is the character's listed language.",
  "storyBeats.userLead": "Сгенерируй биты сценария клипа, используя ВЕСЬ каст, сцены, реквизит, стиль и идею ниже.",
  "storyBeats.eachBeat": "В каждом бите нужны настроение + атмосфера + действия/мимика + необязательный диалог.",
  "storyBeats.story": "История: {{title}}",
  "storyBeats.style": "Стиль: {{style}}",
  "storyBeats.userDir": "Указание пользователя: {{idea}}",
  "storyBeats.cast": "Каст:",
  "storyBeats.scenes": "Сцены:",
  "storyBeats.props": "Реквизит: {{props}}",
  "storyBeats.returnJson": "Верни только JSON-массив битов.",
  "storyBeats.noCast": "(нет каста)",
  "storyBeats.noScenes": "(нет сцен — придумай места в sceneHint)",
  "storyBeats.none": "(нет)",
  "videoPolish.system": "Ты пишешь ОДИН финальный image-to-video промпт для ИИ-видео короткой драмы.\nВерни ТОЛЬКО текст промпта — без markdown-ограждений, заголовка и пояснений.\nПравила:\n- Пиши режиссёрский промпт на языке интерфейса; имена и коды языка реплик должны быть ясны.\n- Кадр человека: IDENTITY LOCK. Пластина локации: SPACE LOCK. Не добавляй новые лица, если материалы их не называют.\n- Используй ВСЕ факты профиля / soul / бита / места, влияющие на вид, движение, речь или атмосферу; пустые поля пропускай.\n- Додумывай только то, что нужно, чтобы снять клип из материалов и seed — не тащи образец мира, Demo и чужие факты.\n- Длинный soul.md сожми в игровые и идентификационные биты; не вставляй всю библию.\n- Длительность — из материалов (реальные секунды клипа). Непрерывное действие. Без текста, лого, водяных знаков и лишних людей.\n- Нормальная анатомия, если сценарий не требует иного (две руки, две руки, две ноги).\n- Несколько персонажей — каждый последователен; главный фокус первым.\n- Если есть HARD RULES, сохрани их и поставь в конец (высший приоритет).\n- SPEECH LOCK обязателен: не удаляй, не переписывай и не переводи. Разворачивай коды в имена. Каждый клип на основном языке персонажа; не меняй язык между клипами; не переводи реплики.\n- Режиссёрская правка может уточнить стиль/действие, но НЕ нарушать HARD RULES.",
  "videoPolish.hardRulesKeep": "HARD RULES (HIGHEST PRIORITY — keep every line; object labels like [Character · Name] must stay). Place the full HARD RULES block at the END of your output. Do not weaken, drop, or reassign rules.",
  "clip.task": "ЗАДАЧА: клип шкалы короткой драмы (изображение в видео).",
  "clip.hasRef": "A reference still may be attached — lock identity/location continuity to it when relevant.",
  "clip.characters": "Персонажи:",
  "clip.scene": "Сцена:",
  "clip.prop": "Реквизит:",
  "clip.action": "Гид по действию / движению:",
  "clip.beat": "Бит / диалог:",
  "clip.prev": "Непрерывность предыдущего клипа:",
  "clip.revision": "ПРАВКА РЕЖИССЁРА (обязательно):",
  "clip.templateDraft": "Черновик шаблона (улучшить):",
  "intro.task": "ЗАДАЧА: клип самопредставления для кастинга (изображение в видео).",
  "intro.hasRef": "Reference still is attached to the video API — lock identity to that image.",
  "intro.noRef": "No reference still path in this text; still lock to profile appearance/costume.",
  "intro.dossier": "Досье персонажа:",
  "intro.templateDraft": "Черновик шаблона (улучши; не игнорируй досье):",
  "common.durationAspect": "Длительность: {{seconds}} с. Соотношение: {{aspect}}.",
  "common.templateDraft": "Черновик шаблона:",
  "improve.mode": "РЕЖИМ УЛУЧШЕНИЯ: объедини ВСЕ источники в полный результат. Сохрани идентичность, если пользователь не просит изменить.",
  "improve.draftDefault": "Текущие поля формы:",
  "improve.userRequest": "Запрос на улучшение (пусто = отполировать всё):",
  "improve.emptyDefault": "(отполировать все поля для непрерывности)",
  "improve.createDefault": "Идея / направление:",
  "improve.explicitContext": "Явный контекст ТОЛЬКО этого запроса (непрерывность; не тащи другой мир):",
  "improve.storyTitle": "Название: {{title}}",
  "improve.styleNote": "Заметка о стиле: {{style}}",
  "improve.closingDefault": "Выдай полный результат сейчас.",
  "storyMeta.system": "Ты шоураннер короткой драмы. Напиши визуальную библию и жёсткие правила. ТОЛЬКО JSON.",
  "storyMeta.draftLabel": "Текущие поля истории:",
  "storyMeta.createLabel": "Идея / название:",
  "storyMeta.emptyPolish": "(отполировать библию и hardRules)",
  "storyMeta.closing": "ТОЛЬКО JSON: {\"styleNote\":\"…\",\"hardRules\":\"…\"}. Оба ключа обязательны.",
  "storyMeta.contextLabel": "Контекст (каст / сцены / реквизит):",
  "character.system": "Ты дизайнер персонажей. ТОЛЬКО один JSON. spokenLanguages = массив BCP-47.",
  "character.draftLabel": "Текущие поля профиля:",
  "character.soulLabel": "Связанный soul.md / библия:",
  "character.createLabel": "Идея персонажа:",
  "character.emptyPolish": "(отполировать и встроить soul)",
  "character.closing": "Полный JSON. Ключи: {{keys}}.",
  "scene.system": "Ты дизайнер локаций. Библия места + сценарий этой сцены. ТОЛЬКО JSON.",
  "scene.draftLabel": "Текущие поля сцены:",
  "scene.charsLabel": "Персонажи истории:",
  "scene.propsLabel": "Реквизит истории:",
  "scene.priorLabel": "Прежние сцены (непрерывность):",
  "scene.createLabel": "Идея сцены:",
  "scene.emptyPolish": "(отполировать место + сценарий)",
  "scene.closing": "Полный JSON. Ключи: {{keys}}.",
  "prop.system": "Ты дизайнер реквизита. ТОЛЬКО один JSON. Вид, материал, состояние.",
  "prop.draftLabel": "Текущие поля реквизита:",
  "prop.createLabel": "Идея реквизита:",
  "prop.emptyPolish": "(отполировать вид)",
  "prop.closing": "Полный JSON. Ключи: {{keys}}.",
  "prop.fallbackName": "Реквизит",
  "action.system": "Ты режиссёр движения. Только валидный JSON. Тело, темп, вес, траектории.",
  "action.storyContext": "Контекст истории (необязательно): {{title}}",
  "action.styleNote": "Заметка о стиле: {{style}}",
  "action.existingDraft": "Существующий черновик:",
  "action.userIdea": "Идея пользователя: {{idea}}",
  "action.closing": "Только JSON. Ключи: {{keys}}.",
  "profile.mustEveryKey": "Нужно выдать КАЖДЫЙ ключ: {{keys}}.",
  "profile.valuesAreStrings": "Каждое значение — JSON-строка. Пусто только если неизвестно.",
  "profile.visualTagsRule": "visualTags: одна строка через запятую. НЕ JSON-массив.",
  "profile.fillConcrete": "Заполняй конкретными деталями.",
  "common.rules": "Правила:",
  "common.none": "(нет)",
  "intro.soul": "soul.md (источник игры / личности):\n{{soul}}",
  "intro.matchBible": "(следовать библии персонажа)",
  "invent.sources": "Источники истины по порядку: (1) идея/запрос, (2) форма, (3) дополнения только если они ЕСТЬ в этом промпте, (4) приложенное фото.",
  "invent.create": "Режим создания: свободно додумай из идеи/фото; не оставляй обязательные ключи пустыми.",
  "invent.improve": "Режим улучшения: шлифуй черновик; не меняй личность без просьбы.",
  "invent.noImport": "НЕ импортируй личность, сюжет, погоду, профессию, место, эпоху или стиль из того, чего нет в промпте.",
  "invent.storyBlock": "Блок истории/стиля — только для непрерывности; не перекрывай явную идею.",
  "character.keysLead": "ТОЛЬКО один JSON с ключами: {{keys}}",
  "character.ruleSpoken": "spokenLanguages: массив BCP-47 языков, на которых ГОВОРИТ. [] если нем.",
  "character.ruleIdentity": "Одна и та же личность на листах и в видео.",
  "scene.keysLead": "ТОЛЬКО один JSON с ключами: {{keys}}",
  "scene.suggestLead": "Предложи готовую ЛОКАЦИЮ как сцену № {{n}} для «{{title}}».",
  "scene.suggestPlotFocus": "Фокус сюжета: {{label}}",
  "scene.suggestStyle": "Стиль: {{style}}",
  "scene.suggestExisting": "Уже есть локации: {{titles}}",
  "scene.suggestChars": "Персонажи (контекст):",
  "scene.suggestProps": "Реквизит (контекст):",
  "scene.suggestSegment": "Детали выбранного куска:",
  "scene.suggestBeats": "Сцены / биты:",
  "scene.suggestClosing": "Верни полный JSON сцены. Сделай отдельное переиспользуемое место.",
  "scene.fallbackName": "Локация",
  "scene.ideaFromImage": "Заполни полный профиль локации по приложенному фото.",
  "scene.polishIdea": "Отшлифовать",
  "prop.keysLead": "ТОЛЬКО один JSON с ключами: {{keys}}",
  "action.fieldsLead": "Поля: {{keys}}.",
  "soul.system": "Ты пишешь production soul.md. Только полный markdown. Уважай spokenLanguages. Язык интерфейса.",
  "soul.improveMode": "РЕЖИМ УЛУЧШЕНИЯ: объедини профиль + существующий soul в полный soul.md.",
  "soul.createMode": "Напиши полный soul.md по этому профилю (не подменяй человека):",
  "soul.profileFields": "Поля профиля:",
  "soul.existing": "Существующий soul.md (слить; не выбрасывай полезное):",
  "soul.userRequest": "Запрос: {{request}}",
  "soul.extraContext": "Доп. контекст (если полезно; профиль важнее):",
  "soul.returnOnly": "Верни только markdown soul.md.",
  "wardrobe.system": "Ты консультант по костюмам. Один JSON. artStyle из: {{styleIds}}. Конкретные ткани и силуэт. Не эротизируй несовершеннолетних.",
  "wardrobe.improveMode": "РЕЖИМ УЛУЧШЕНИЯ / ПРЕДЛОЖЕНИЯ: используй ВСЕ поля и сюжет.",
  "wardrobe.characterForm": "Персонаж (полная форма):",
  "wardrobe.soulExcerpt": "Отрывок soul.md:\n{{soul}}",
  "wardrobe.userRequest": "Запрос: {{request}}",
  "wardrobe.storyContext": "Производственный контекст (если дан; не выдумывай другой мир):",
  "wardrobe.style": "стиль: {{style}}",
  "wardrobe.segment": "Выбранный кусок: {{label}}",
  "wardrobe.sceneContext": "Сцена / бит:",
  "wardrobe.noScenes": "(сцен ещё нет)",
  "wardrobe.proposeNew": "Предложи НОВЫЙ образ под сюжет (не дублируй).",
  "fill.system": "Ты заполняешь пустые поля. JSON РОВНО с ключами: {{keys}}. Каждое значение — непустая строка. Не массив.",
  "fill.userPartial": "Частичный профиль (не противоречь):",
  "fill.userOnly": "Заполни ТОЛЬКО эти ключи: {{keys}}.",
  "fill.userReturn": "JSON только с этими ключами; значения непустые.",
  "imageGen.multiRef": "Ещё {{n}} референсов: первый — база; держи личность во всех.",
  "residual.sceneLink": "Сцена {{n}}: {{short}}",
  "residual.beatSegment": "Бит {{n}} · {{who}}{{tail}}",
  "residual.unknown": "Не указано",
  "residual.story": "История",
  "beat.mood": "[MOOD] {{text}}",
  "beat.atmo": "[ATMO] {{text}}",
  "beat.camera": "[CAMERA] {{text}}",
  "beat.sfx": "[SFX] {{text}}",
  "beat.action": "[ACTION] {{text}}",
  "beat.actionWho": "[ACTION|{{who}}] {{text}}",
  "beat.expr": "[EXPR] {{text}}",
  "beat.exprWho": "[EXPR|{{who}}] {{text}}",
  "beat.dialogue": "[DIALOGUE|{{who}}] {{body}}",
  "beat.dialogueTone": "[DIALOGUE|{{who}}|{{tone}}] {{body}}",
  "beat.whoUnknown": "?",
  "beat.template": "[MOOD] tense, hesitant\n[ATMO] door-gap warm light; rain on ground\n[CAMERA] medium shot, push to hands\n[SFX] rain, fabric rustle\n[ACTION|Name] removes helmet; stares at the door light; hand into jacket pocket\n[EXPR|Name] furrowed brow, breath catches\n[DIALOGUE|Name|low, hoarse] Raining again…\n[DIALOGUE|Name|aside] (beat) Are you… still there?",
  "vision.preamble": "Приложен кадр. Заполни ВСЕ поля этого {{what}} главным образом ПО КАРТИНКЕ.",
  "vision.character": "личность (имя, внешность, костюм, возраст, пол, теги)",
  "vision.scene": "локация (название, описание, свет, настроение, декорации, теги)",
  "vision.prop": "реквизит (имя, описание, материал, размер, состояние, теги)",
  "vision.action": "действие (имя, описание, темп, намерение, камера, теги)",
  "vision.costume": "костюм (имя, полное описание)",
  "still.header": "ОДИН ключевой кадр для непрерывности видео (не мультипанель). Герой-кадр по запланированному плану. Без текста, лого, водяных знаков и UI.",
  "still.revision": "ПРАВКА ПОЛЬЗОВАТЕЛЯ ДЛЯ ЭТОГО КАДРА (обязательно): {{notes}}",
  "still.regenTask": "ЗАДАЧА: перепиши режиссёрский image-to-video промпт и оставь его пригодным как бриф кейфрейма.",
  "still.userImprove": "ЗАПРОС НА УЛУЧШЕНИЕ:\n{{notes}}",
  "still.currentPrompt": "Текущий профессиональный промпт:",
  "still.hardRules": "HARD RULES (в конце; не ослабляй):",
  "mediaGen.writeOne": "Напиши ОДИН финальный промпт изображения для кадра короткой драмы.",
  "mediaGen.returnOnly": "ТОЛЬКО текст промпта — без markdown.",
  "mediaGen.singleComposite": "Опиши ОДИН составной кадр.",
  "mediaGen.lockRefs": "Приложенные кадры — визуальная правда (порядок Ref#). Не выдумывай другого человека, магазин или предмет.",
  "mediaGen.videoSystem": "Ты пишешь режиссёрские image-to-video промпты.",
  "mediaGen.videoMerge": "Слей материалы в ОДИН видеопромпт.",
  "mediaGen.videoInclude": "Включи: замок личности, камеру, игру/реплики, ритм, свет.",
  "mediaGen.videoFacts": "Только факты из материалов и seed. Без Demo.",
  "mediaGen.videoNoSwap": "При референсах не меняй актёра, локацию и реквизит.",
  "mediaGen.videoHardRules": "HARD RULES в конце, если есть.",
  "mediaGen.imageSystem": "Ты режиссёр промптов изображений.",
  "mediaGen.imageMergeStills": "Слей материалы и кадры в ОДИН промпт изображения.",
  "mediaGen.imageMergeText": "Слей тексты в ОДИН промпт изображения.",
  "mediaGen.imagePriority": "Приоритет: лица/костюмы/места/реквизит с картинок.",
  "mediaGen.imageNoSwap": "Не подменяй другой знаменитостью или чужим сетом, если есть кадры каста.",
  "mediaGen.imageFacts": "Только факты из материалов и seed.",
  "mediaGen.imageLayout": "Если мультипанель — точное число клеток.",
  "mediaGen.imagePackage": "Если есть LAYOUT, промпт ДОЛЖЕН точно его исполнить.",
  "mediaGen.imageHardRules": "HARD RULES в конце, если есть.",
  "mediaGen.directorFallback": "КАРТИНКА-В-ВИДЕО: оживи этот кейфрейм. Замок личности, костюма, декора и кадра.",
  "mediaGen.directorFallbackCam": "Камера и игра ясные; без титров и водяных знаков.",
  "charIntro.task": "КАРТИНКА-В-ВИДЕО: та же личность — короткое самопредставление.",
  "charIntro.identityLock": "ЗАМОК ЛИЧНОСТИ: то же лицо, волосы, тело, возраст, костюм и цвета.",
  "charIntro.personality": "Характер / вайб: {{personality}}.",
  "charIntro.backstory": "Предыстория: {{backstory}}.",
  "charIntro.relationships": "Связи: {{relationships}}.",
  "charIntro.soul": "Отрывок soul (источник игры): {{soul}}",
  "charIntro.performance": "Игра: мягкий наезд или handheld; взгляд в камеру; {{manner}}.",
  "charIntro.speech": "Речь: рот двигается как при коротком представлении; голос: {{voice}}.",
  "charIntro.beat": "Спокойный idle → улыбка или кивок → короткий жест → hold.",
  "charIntro.lighting": "Свет как на кадре; без текста, логотипов и лишних людей.",
  "sceneIntro.task": "КАРТИНКА-В-ВИДЕО: то же место как установочный кадр.",
  "sceneIntro.spaceLock": "ЗАМОК ПРОСТРАНСТВА: та же архитектура, материалы, вывески, план и цвет.",
  "sceneIntro.name": "Название места: {{name}}.",
  "sceneIntro.place": "Описание: {{place}}.",
  "sceneIntro.spaceType": "Тип пространства: {{type}}.",
  "sceneIntro.time": "Время суток: {{time}}.",
  "sceneIntro.weather": "Погода: {{weather}}.",
  "sceneIntro.moodLight": "Настроение: {{mood}}. Свет: {{lighting}}.",
  "sceneIntro.palette": "Палитра: {{palette}}.",
  "sceneIntro.setDressing": "Декорации: {{set}}.",
  "sceneIntro.tags": "Визуальные теги: {{tags}}.",
  "sceneIntro.art": "Стиль: {{art}}.",
  "sceneIntro.ambient": "Атмосфера (без UI-текста): {{sound}}.",
  "sceneIntro.scriptCue": "Подсказка бита (только атмосфера): {{cue}}.",
  "sceneIntro.camera": "Камера: {{camera}}; непрерывное движение. Не добавляй лица, лого и текст, если их нет в материалах.",
  "sceneIntro.beat": "Установка → тонкая жизнь среды → hold.",
  "propIntro.task": "КАРТИНКА-В-ВИДЕО: тот же реквизит как геройский интро.",
  "propIntro.objectLock": "ЗАМОК ОБЪЕКТА: тот же силуэт, материалы, цвета, гравировка и износ.",
  "propIntro.name": "Название: {{name}}.",
  "propIntro.look": "Вид: {{look}}.",
  "propIntro.material": "Материал: {{material}}.",
  "propIntro.size": "Размер: {{size}}.",
  "propIntro.condition": "Состояние: {{condition}}.",
  "propIntro.tags": "Теги: {{tags}}.",
  "propIntro.art": "Стиль: {{art}}.",
  "propIntro.camera": "Мягкая орбита или медленный наезд на чистом столе; свет как на кадре.",
  "propIntro.beat": "Hold → блик / микроповорот → hold.",
  "propIntro.noHands": "Без новых рук и лиц, если их нет на кадре; без текста и лишнего реквизита.",
  "costumeIntro.task": "КАРТИНКА-В-ВИДЕО: тот же образ как интро костюма.",
  "costumeIntro.wardrobeLock": "ЗАМОК КОСТЮМА: тот же силуэт, ткани, цвета, слои и аксессуары.",
  "costumeIntro.identityOrProduct": "Если человек: замок лица/тела; если манекен/раскладка — продуктовый кадр.",
  "costumeIntro.name": "Имя образа: {{name}}.",
  "costumeIntro.desc": "Костюм: {{look}}.",
  "costumeIntro.art": "Стиль: {{art}}.",
  "costumeIntro.camera": "Мягкий наезд или орбита; модный свет как на кадре.",
  "costumeIntro.beat": "Hold → драпировка / блик фурнитуры → hold.",
  "costumeIntro.forbid": "Без новых лиц, текста, логотипов и эропозы.",
  "costumeIntro.fallbackName": "Образ",
  "actionIntro.lead": "Демо движения «{{name}}».",
  "actionIntro.intention": "Намерение: {{intention}}",
  "actionIntro.body": "Тело/темп: {{body}}",
  "actionIntro.camera": "Камера: {{camera}}",
  "actionIntro.closing": "Плавное движение, без текста; следуй кейфрейму.",
  "sceneIntroPolish.task": "ЗАДАЧА: интро локации (картинка-в-видео).",
  "sceneIntroPolish.hasRef": "Кадр локации приложен — замок ПРОСТРАНСТВЕННОЙ личности.",
  "sceneIntroPolish.noRef": "Нет кадра; замок к библии места.",
  "sceneIntroPolish.dossier": "Досье локации:",
  "sceneIntroPolish.scriptCue": "подсказка сценария (только атмосфера):\n{{script}}",
  "sceneIntroPolish.emptySet": "Пустой сет; без новых лиц. Без текста и логотипов.",
  "propIntroPolish.task": "ЗАДАЧА: геройское интро реквизита (картинка-в-видео).",
  "propIntroPolish.hasRef": "Кадр реквизита приложен — замок ОБЪЕКТА.",
  "propIntroPolish.noRef": "Нет кадра; замок к досье.",
  "propIntroPolish.dossier": "Досье реквизита:",
  "propIntroPolish.noHands": "Без новых рук и лиц. Без текста и логотипов.",
  "costumeIntroPolish.task": "ЗАДАЧА: интро костюма (картинка-в-видео).",
  "costumeIntroPolish.hasRef": "Кадр есть — человек: личность+костюм; манекен: силуэт и материалы.",
  "costumeIntroPolish.noRef": "Нет кадра; замок к описанию.",
  "costumeIntroPolish.dossier": "Досье костюма:",
  "costumeIntroPolish.fabric": "Тонкая драпировка; без новых лиц и текста.",
  "actionIntroPolish.task": "ЗАДАЧА: интро гайда движения (картинка-в-видео).",
  "actionIntroPolish.hasRef": "Кадр есть — замок актёрской личности к этому кадру.",
  "actionIntroPolish.templateKeepRules": "Черновик шаблона (шлифуй; HARD RULES в конце):",
  "cover.posterLead": "Профессиональный ПОСТЕР / KEY ART 16:9. Не UI-макет. Без текста, логотипа и водяного знака.",
  "cover.titleMood": "Название (только настроение, не пиши на кадре): {{title}}.",
  "cover.styleBible": "Стиль-библия: {{style}}",
  "cover.extraDir": "Доп. направление: {{idea}}",
  "cover.establishing": "Установочный кадр настроения для обложки библиотеки.",
  "cover.medium": "Соблюди medium; сильный силуэт.",
  "cover.editPrefix": "IMAGE EDIT: новая композиция постера. Сохрани личность/настроение. ",
  "cover.label": "Обложка истории",
  "costumeFill.system": "Ты художник по костюмам. Только компактный JSON. Если есть фото — опиши ИМЕННО этот наряд.",
  "costumeFill.idea": "Идея: {{idea}}",
  "costumeFill.polish": "Отшлифуй черновик костюма.",
  "costumeFill.required": "Ключи: name, description, artStyle, hardRules. Пропуск = недействительно.",
  "costumeFill.fallbackName": "Образ",
  "segment.entireStory": "Вся история (все сцены)",
  "segment.noStory": "История не выбрана (только карточка персонажа)",
  "vision.inventFromImage": "Опиши и дополни полный профиль {{kind}} по приложенному фото.",
  "vision.polishAll": "Отшлифуй и объедини все поля",
  "story.untitled": "Безымянная короткая драма",
  "action.castIdentityNote": "Кадры личности ({{count}}): лицо/тело должны совпадать с референсами каста в каждой клетке.",
  "tpl.system.polishOnly": "РЕЦЕПТ только шлифовка: сохрани личность и мир. Шлифуй текст. Не выдумывай эпоху, погоду, профессию, место и образец мира. Не выдумывай язык речи. Не пиши дефолтные HARD RULES в профиль.",
  "tpl.system.fillBlanks": "РЕЦЕПТ только пустые: заполни ТОЛЬКО пустые ключи. Не переписывай заполненное. Не выдумывай новый мир.",
  "tpl.system.invent": "РЕЦЕПТ изобретать: пользователь разрешил свободное творчество. Заполни каждый снимаемый ключ. Не тащи Demo и мир не из этого запроса.",
  "tpl.system.fromStory": "РЕЦЕПТ из истории: используй только название/стиль/каст/сцены ЭТОГО запроса. При конфликте побеждает идея пользователя.",
  "tpl.system.followAsset": "РЕЦЕПТ следовать активу: следуй уже данному стилю. Не навязывай кино, пустой сет и 6–10 с, если материалов нет. Длительность — реальные секунды клипа.",
  "tpl.system.cinematicLock": "РЕЦЕПТ кино+антигаллюцинация: кинематографичный вид; пустой сет; без водяных знаков, лого и лишних лиц; две руки/руки/ноги если не не-человек.",
  "tpl.system.identityLock": "РЕЦЕПТ замок личности: лицо/тело/костюм/место/реквизит по кадрам. Не подменяй человека, место или предмет.",
  "tpl.system.restyle": "РЕЦЕПТ restyle: тот же человек. Костюм, декорации и эпоха могут меняться по просьбе. Не другого человека.",
  "pipeline.character.system": "Ты шлифуешь библии персонажей. 3–5 строк: вид, голос, мотив, жест. Только факты этого запроса.",
  "pipeline.scene.system": "Ты раскладываешь сцены в визуальные биты. Реальная длительность материалов; не считай 6–10 с. Только данные сцены.",
  "pipeline.props.system": "Ты шлифуешь непрерывность реквизита. Цвет, размер, когда появляется. Не выдумывай реквизит вне списка.",
  "pipeline.script.system": "Ты сценарист короткой драмы. Компактный блок на сцену для ИИ-видео. Реальная длительность; не навязывай 10 с. Формат:\n### SCENE <number> | id=<id>\n<script body>",
  "pipeline.script.noScenes": "(нет сцен — не выдумывай места)"
}