import type { PromptCopyTable } from './keys'

export const zhCnPromptCopy: PromptCopyTable = {
  "speechLock.named": "SPEECH LOCK · 角色「{{who}}」：可听语音和口型必须只用{{primaryName}}（{{primary}}）。禁止改说{{forbid}}或其他语言。每段都要同一种口白。不要翻译对白。",
  "speechLock.unnamed": "SPEECH LOCK · 出场角色：可听语音和口型必须只用{{primaryName}}（{{primary}}）。禁止改说{{forbid}}或其他语言。每段都要同一种口白。不要翻译对白。",
  "speechLock.namedMulti": "SPEECH LOCK · 角色「{{who}}」：可听语音和口型必须用{{primaryName}}（{{primary}}）。只有剧本该句已经是以下语言才可以讲第二种：{{extras}}。禁止第三种语言。禁止每段转换。禁止改说{{forbid}}。不要翻译对白。",
  "speechLock.unnamedMulti": "SPEECH LOCK · 出场角色：可听语音和口型必须用{{primaryName}}（{{primary}}）。只有剧本该句已经是以下语言才可以讲第二种：{{extras}}。禁止第三种语言。禁止每段转换。禁止改说{{forbid}}。不要翻译对白。",
  "storyBeats.system": "你为短剧时间轴撰写「剧情段落」——每一段 = 一小段 AI 影片的完整拍摄脚本，而非一句对白。\n每段必须有丰富表演内容：心情、气氛、动作、表情、可选镜头／声效，以及 0 至多句口白（常见 1–4 句）。\n只回传 JSON 数组（不要代码块）。每项形状：\n{\"characterName\":\"…\",\"characterNames\":[\"…\"],\"sceneHint\":\"…\",\"propName\":\"…\",\"mood\":\"…\",\"atmosphere\":\"…\",\"camera\":\"…\",\"sfx\":\"…\",\"units\":[{\"type\":\"action\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"expression\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"dialogue\",\"who\":\"…\",\"line\":\"…\",\"tone\":\"…\",\"parenthetical\":\"…\"},{\"type\":\"note\",\"text\":\"…\"}]}\n规则：\n- dialogue.line 只写角色讲出口的话，不要把动作写进口白。\n- 肢体动作放 action；表情微表演放 expression；语气放 tone／parenthetical。\n- 一段可有多句对白（对话回合或自语）。\n- 允许纯动作段（无对白）。\n- 写 4–8 段。角色名必须用提供名单。\n- 要有冲突、可视动作、可拍细节。\n- 忠于已提供的标题、风格、选角与场景。不要擅自扩世界。\n- 口白：dialogue.line 必须用该角色主语言写（见角色名单）。禁止段与段转语言。除非角色名单写明，否则不要改写成其他语言。",
  "storyBeats.userLead": "生成完整「短片脚本」段落：使用下方全部选角、场景、道具、风格与构想。",
  "storyBeats.eachBeat": "每段要有心情、气氛、动作／表情，以及可选的多句对白。",
  "storyBeats.story": "故事：{{title}}",
  "storyBeats.style": "风格：{{style}}",
  "storyBeats.userDir": "用户指示：{{idea}}",
  "storyBeats.cast": "角色：",
  "storyBeats.scenes": "场景：",
  "storyBeats.props": "道具：{{props}}",
  "storyBeats.returnJson": "只回传段落 JSON 数组。",
  "storyBeats.noCast": "（无角色）",
  "storyBeats.noScenes": "（无场景 — sceneHint 可写地点）",
  "storyBeats.none": "（无）",
  "videoPolish.system": "你为短剧 AI 图生影片模型撰写「一条」最终 image-to-video 导演提示词。\n只回传提示词正文——不要 markdown 代码块、标题或解释。\n规则：\n- 提示词全文用用户界面语言书写；角色姓名与口白语言要求须清楚标示。\n- 人物静图：IDENTITY LOCK（脸、发、体型、服装、颜色）。场景静帧：SPACE LOCK（建筑、材质、格局、招牌、色盘）。除非材料点名，否则勿新增角色脸。\n- 凡已提供且影响外形、动作、口白、气氛或场地的人设／soul／段落／地点资料均须用上；空白栏位可略。\n- 只按材料与 seed 补齐可拍细节；勿引入固定样本世界、Demo 故事、或材料／seed 未出现的事实。\n- 长篇 soul.md 须浓缩为可拍的表演与身份要点，不可整篇照贴。\n- 片长跟材料里的实际秒数。动作连贯。无字幕、logo、浮水印、无关路人。\n- 除非剧情要求，否则解剖结构正常（双手双脚）。\n- 多角色时保持每位主体一致；主焦点优先。\n- 若材料含 HARD RULES（生成铁则），必须保留并放在输出最尾（最高优先）。\n- SPEECH LOCK 必须保留：不得删改或翻译；语言代码要写成全名。每段跟角色主口语，禁止段与段转语言，禁止翻译对白。\n- 导演修订可调整气氛／动作，但不得违反 HARD RULES。",
  "videoPolish.hardRulesKeep": "HARD RULES／生成铁则（最高优先——保留每一行；[Character · 名] 等物件标签不可删）。必须将完整 HARD RULES 区块放在输出最末。不得削弱、删除或套错主体。",
  "clip.task": "任务：短剧时间轴片段（图生影片）。",
  "clip.hasRef": "可能附有参考静图——相关时锁定身份／场地连续性。",
  "clip.characters": "角色：",
  "clip.scene": "场景：",
  "clip.prop": "道具：",
  "clip.action": "动作指导：",
  "clip.beat": "段落／对白：",
  "clip.prev": "前一段连续性：",
  "clip.revision": "导演修订（必须遵守）：",
  "clip.templateDraft": "模板草稿（请改进）：",
  "intro.task": "任务：自我介绍选角短片（图生影片）。",
  "intro.hasRef": "参考静图会交予影片 API——必须锁定该图身份。",
  "intro.noRef": "本文无静图路径；仍须锁定人设外貌／戏服。",
  "intro.dossier": "角色档案：",
  "intro.templateDraft": "模板草稿（请改进；勿忽略档案）：",
  "common.durationAspect": "时长：{{seconds}} 秒。画面比例：{{aspect}}。",
  "common.templateDraft": "模板草稿：",
  "improve.mode": "改进模式：合并下方所有来源输出完整结果。除非用户明确要求改身份，否则保持核心一致。表单稀疏时以额外上下文为准；用户明确要求更改时以指示为准。",
  "improve.draftDefault": "目前表单栏位（已填内容）：",
  "improve.userRequest": "用户改进要求（可留空 = 全面润饰并合并以上内容）：",
  "improve.emptyDefault": "（全面润饰：适合短剧／出图／出片 continuity）",
  "improve.createDefault": "构想／方向：",
  "improve.explicitContext": "仅限本次请求明确附上的上下文（作 continuity；勿引入其他样本世界；与 idea／表单冲突时以用户为准）：",
  "improve.storyTitle": "故事标题：{{title}}",
  "improve.styleNote": "风格备注：{{style}}",
  "improve.closingDefault": "请立即输出完整结果。",
  "storyMeta.system": "你是短剧主创／视觉总监。根据故事标题与构想，写简洁可拍的风格备注（Style bible）以及出图／出片「生成铁则」。只回传 JSON（不要代码块）：{\"styleNote\":\"2–5 句：气氛、光线、镜头、色调、节奏\",\"hardRules\":\"3–8 句必须／禁止\"}。要具体、适合 AI 影片／出图延续。用提供的标题、构想、现有风格／铁则与上下文。不要擅自发明风格。",
  "storyMeta.draftLabel": "目前故事栏位：",
  "storyMeta.createLabel": "故事构想／标题：",
  "storyMeta.emptyPolish": "（润饰视觉风格备注与生成铁则，利于 AI 出片 continuity）",
  "storyMeta.closing": "只回传 JSON：{\"styleNote\":\"…\",\"hardRules\":\"…\"}。两个键都必填且非空。",
  "storyMeta.contextLabel": "故事上下文（角色／场景／道具）：",
  "character.system": "你是专业短剧角色设定师，专门为 AI 影片／短剧生成「可拍、可认、可一致」的角色圣经。用户会给一段角色 idea。角色可以是人类、动物、鬼灵、魔物、机械、虚拟形象或其他设计体——依 idea 而定，勿强行写成人类。只输出一个 JSON 物件。spokenLanguages：BCP-47 代码阵列，例如 [\"yue\",\"en\"]。非语言角色用 []。避免空泛形容；用可拍摄的细节。同一角色必须视觉一致。",
  "character.draftLabel": "目前 Profile 表单栏位（已填内容）：",
  "character.soulLabel": "已连结 soul.md／角色圣经（主要身份与性格依据）：",
  "character.createLabel": "角色 idea：",
  "character.emptyPolish": "（全面润饰：将 soul 与表单合并进完整 Profile）",
  "character.closing": "请立即输出完整 JSON。必填键：{{keys}}。visualTags 为逗号分隔字串（禁止标签阵列）；spokenLanguages 可以是代码阵列。",
  "scene.system": "你是短剧场景／场景空间设计师，服务 AI 影片 continuity。请输出可拍的地点圣经 + 本场可演剧本片段。只回传一个 JSON 物件。title＝短地名；description＝建筑、物料、地标；script＝本场对白／动作／镜头。",
  "scene.draftLabel": "目前场景表单栏位（已填内容）：",
  "scene.charsLabel": "故事角色：",
  "scene.propsLabel": "故事道具：",
  "scene.priorLabel": "既有场景（continuity）：",
  "scene.createLabel": "场景 idea：",
  "scene.emptyPolish": "（全面润饰地点与本场剧本，利于出片 continuity）",
  "scene.closing": "请立即输出完整 JSON。必填键：{{keys}}。缺键无效。visualTags 必须是逗号分隔字串，禁止阵列。",
  "prop.system": "你是短剧道具设计师，服务 AI 影片 continuity。只回传一个 JSON。description：可画细节；material／sizeNotes／condition 具体。",
  "prop.draftLabel": "目前道具表单栏位（已填内容）：",
  "prop.createLabel": "道具 idea：",
  "prop.emptyPolish": "（全面润饰道具外观，利于出片 continuity）",
  "prop.closing": "请立即输出完整 JSON。必填键：{{keys}}。缺键无效。visualTags 必须是逗号分隔字串，禁止阵列。",
  "prop.fallbackName": "道具",
  "action.system": "你是短剧动作指导。只输出有效 JSON，描述一项可拍摄的动作指导。要具体：身体部位、节奏、力度、道具路径、走位。不要 markdown。",
  "action.storyContext": "故事脉络（可选）：{{title}}",
  "action.styleNote": "风格备注：{{style}}",
  "action.existingDraft": "现有草稿（请润饰补全）：",
  "action.userIdea": "用户构想：{{idea}}",
  "action.closing": "只回传 JSON。必填键：{{keys}}。visualTags 为逗号分隔字串，禁止阵列。",
  "profile.mustEveryKey": "必须输出列表中的每一个键：{{keys}}。",
  "profile.valuesAreStrings": "每个值必须是 JSON 字串（不可 null、不可用 JSON 阵列）。真的不知道才可空字串。",
  "profile.visualTagsRule": "visualTags：用用户界面语言的单一逗号分隔字串——禁止 JSON 阵列。",
  "profile.fillConcrete": "各键请尽量填具体细节，利于短剧 continuity。",
  "common.rules": "规则：",
  "common.none": "（无）",
  "intro.soul": "soul.md（作为表演／身份完整来源）：\n{{soul}}",
  "intro.matchBible": "（跟从角色人设语言）",
  "invent.sources": "依据来源（优先序）：（1）用户 idea／指示，（2）已填表单，（3）仅当「本次 prompt 已写出」的额外上下文（soul、选角、故事区块等），（4）附上的参考图。",
  "invent.create": "创作模式（表单空白／极少）：按 idea／图自由创作，补齐可拍摄的关键栏位，内容须与用户构想相关——勿留空必填键。",
  "invent.improve": "改进模式（表单已有内容）：润饰并补齐空白栏，与已填内容一致；除非用户要求，否则勿改核心身份。",
  "invent.noImport": "不得从「本次 prompt 未出现」的来源引入身份、剧情、天气、职业、地点、时代或风格（禁止 active 故事、Demo 样本、App 默认世界观）。",
  "invent.storyBlock": "若下方明确附有故事／风格区块：仅作 continuity；不可覆盖用户明确 idea。",
  "character.keysLead": "只输出一个 JSON 物件（不要 markdown），键名必须是：{{keys}}",
  "character.ruleSpoken": "spokenLanguages：角色使用的语言，JSON 字串阵列（可多选），BCP-47／ISO 代码，例如 [\"yue\",\"en\"]。非语言角色用 []。",
  "character.ruleIdentity": "同一角色必须视觉一致，方便之后多角度参考图与影片生成。",
  "scene.keysLead": "只回传一个 JSON 物件（不要 markdown），键名：{{keys}}",
  "scene.suggestLead": "为故事「{{title}}」建议第 {{n}} 个可用场景（场地／环境设定）。",
  "scene.suggestPlotFocus": "剧情焦点：{{label}}",
  "scene.suggestStyle": "风格：{{style}}",
  "scene.suggestExisting": "库内／故事已有场地：{{titles}}",
  "scene.suggestChars": "角色（上下文）：",
  "scene.suggestProps": "道具（上下文）：",
  "scene.suggestSegment": "选定剧情段落详情：",
  "scene.suggestBeats": "故事场次／段落：",
  "scene.suggestClosing": "回传完整场景 JSON。请设计一个可重复使用的独立场地（全域场景库资产），须贴合选定剧情焦点，并与已有场地有所区别。",
  "scene.fallbackName": "场景",
  "scene.ideaFromImage": "请根据附上的参考图，完整填写场景资料。",
  "scene.polishIdea": "全面润饰",
  "prop.keysLead": "只回传一个 JSON，键名：{{keys}}",
  "action.fieldsLead": "栏位：{{keys}}。",
  "soul.system": "你为短剧／影视角色撰写 production 用 soul.md（单档 Markdown）。\n只输出完整 Markdown 文件（不要代码块围栏、不要解说）。\n结构（请用以下 ## 标题）：\n# {角色名}\n## 身份 Identity\n## 外貌 Appearance\n## 服装与轮廓 Costume\n## 性格与声线 Personality & voice\n## 使用语言 Spoken languages\n## 小习惯 Mannerisms\n## 背景 Backstory\n## 关是 Relationships\n## 表演与对白风格\n## 一致性硬规则 Hard rules\n## 视觉标签 Visual tags\n规则：\n- 短剧可拍、可辨认、可一致；细节须具体。\n- 依据：Profile 表单 + 现有 soul + 用户指示。除非所选配方允许，否则勿用本次未提供的来源臆造。\n- 对白／配音必须尊重 profile 的 spokenLanguages。\n- 硬规则用 5–10 条 bullet，方便之后图像／对白 AI 遵守。\n- 用用户界面语言书写（香港书面语优先，若界面是其他语言就跟界面）。\n- 可选开头 YAML frontmatter（name / tags），非必须。",
  "soul.improveMode": "改进模式：合并 Profile 表单 + 现有 soul，输出更新后完整 soul.md。除非要求改身份，否则保持核心一致。",
  "soul.createMode": "根据以下角色设定撰写完整 soul.md（合理补齐空白；不要换成另一个人）：",
  "soul.profileFields": "Profile 表单栏位（已填内容）：",
  "soul.existing": "现有 soul.md（合并／改进；勿丢有用细节）：",
  "soul.userRequest": "用户指示：{{request}}",
  "soul.extraContext": "本次一并提供的上下文（有用就用；仍以 profile 为准）：",
  "soul.returnOnly": "只输出完整 soul.md Markdown 正文。",
  "wardrobe.system": "你是短剧服装与视觉风格顾问。根据角色与剧情，提出一套完整外装方案。只回传一个 JSON 物件（不要 markdown 围栏）：{\"name\":\"短名称\",\"costume\":\"详细外装描述（供出图／影片）\",\"artStyle\":\"下列其一\",\"rationale\":\"一两句理由\"} artStyle 必须是：{{styleIds}} costume 要具体：材质、颜色、轮廓、鞋履、配件。年龄表述须得体；禁止对未成年做性化描述。保留既有外貌身份，只设计服装与风格。用角色栏位与已提供的剧情／故事上下文。不要擅自发明造型世界。",
  "wardrobe.improveMode": "改进／建议模式：使用下方全部角色栏位与剧情上下文。",
  "wardrobe.characterForm": "角色（完整表单）：",
  "wardrobe.soulExcerpt": "soul.md 摘要：\n{{soul}}",
  "wardrobe.userRequest": "用户指示：{{request}}",
  "wardrobe.storyContext": "故事／制作上下文（有就用；勿另起一个世界）：",
  "wardrobe.style": "风格：{{style}}",
  "wardrobe.segment": "选定剧情段落：{{label}}",
  "wardrobe.sceneContext": "场景／段落／对白摘录：",
  "wardrobe.noScenes": "（尚无场景）",
  "wardrobe.proposeNew": "请提出一套符合剧情的新戏服（避免与已有造型重复）。",
  "fill.system": "你负责补齐短剧资产设定中「仍然空白」的栏位。\n只回传一个 JSON 物件，且只能包含这些键：{{keys}}。\n每个值必须是非空 JSON 字串（不可 null、不可 JSON 阵列）。\n若含 visualTags：用用户界面语言的逗号分隔字串（格式例：\"gold, necklace\"，勿照抄例子，须贴合本资产）——禁止阵列。\n只根据已有部分设定及参考图补齐；勿另起未见于 partial／图的剧情、地点或样本世界。\n不要 markdown、不要解说。",
  "fill.userPartial": "已有部分设定（勿矛盾）：",
  "fill.userOnly": "只补齐这些空白键：{{keys}}。",
  "fill.userReturn": "只回传含上述键的 JSON；每值为非空字串。",
  "imageGen.multiRef": "另有 {{n}} 张已选参考图：主编辑底图为第一张，其余作身份一致辅助，勿换成另一物件／主体。",
  "residual.sceneLink": "第 {{n}} 场：{{short}}",
  "residual.beatSegment": "段落 {{n}} · {{who}}{{tail}}",
  "residual.unknown": "未指定",
  "residual.story": "故事",
  "beat.mood": "【心情】{{text}}",
  "beat.atmo": "【气氛】{{text}}",
  "beat.camera": "【镜头】{{text}}",
  "beat.sfx": "【声效】{{text}}",
  "beat.action": "【动作】{{text}}",
  "beat.actionWho": "【动作｜{{who}}】{{text}}",
  "beat.expr": "【表情】{{text}}",
  "beat.exprWho": "【表情｜{{who}}】{{text}}",
  "beat.dialogue": "【对白｜{{who}}】{{body}}",
  "beat.dialogueTone": "【对白｜{{who}}｜{{tone}}】{{body}}",
  "beat.whoUnknown": "？",
  "beat.template": "【心情】緊繃、猶豫\n【气氛】門縫暖光；雨砸地\n【鏡头】中景，跟手推近\n【声效】雨、布料摩擦\n【动作｜角色名】摘下安全帽；盯門縫暖光；手伸進外套內袋\n【表情｜角色名】眉心緊鎖，呼吸一滯\n【对白｜角色名｜低声沙啞】又是落雨……\n【对白｜角色名｜自语】（停半拍）你……仲在度？",
  "vision.preamble": "已附上参考静图。请主要根据图片填写此{{what}}全部栏位；可结合构思／草稿润饰。",
  "vision.character": "角色（名称、外貌、戏服、年龄、性别、标签等）",
  "vision.scene": "场景（标题、描述、光影、气氛、布景、标签等）",
  "vision.prop": "道具（名称、描述、材质、尺寸、状态、标签等）",
  "vision.action": "动作（名称、说明、节奏、意图、镜头备注、标签等）",
  "vision.costume": "戏服（名称、完整造型描述）",
  "still.header": "SINGLE KEYFRAME STILL for short-drama video continuity（单格关键帧，不是多格板）。产出一张对应下方镜头的主画面。无文字、logo、浮水印、UI。清晰可制作。",
  "still.revision": "用户改进要求（必须套用）：{{notes}}",
  "still.regenTask": "任务：修订 image-to-video 导演提示词，并保持可作静帧 keyframe 简报。",
  "still.userImprove": "用户改进要求：\n{{notes}}",
  "still.currentPrompt": "目前专业提示词：",
  "still.hardRules": "HARD RULES／生成铁则（必须保留于输出最尾；不得删除或削弱）：",
  "mediaGen.writeOne": "请撰写「一条」最终短剧静图／多格指示图生成 prompt。",
  "mediaGen.returnOnly": "只回传 prompt 正文——不要 markdown 代码块、标题或解释。",
  "mediaGen.singleComposite": "输出描述「单一合成图」（只 export 一张）。",
  "mediaGen.lockRefs": "附图图序与下方 Ref# 一致，须作视觉 ground truth。身份／戏服／场景／道具必须锁定附图，禁止换成另一人、另一店或另一物。",
  "mediaGen.videoSystem": "你是短剧 image-to-video 导演 prompt 撰写者。",
  "mediaGen.videoMerge": "将材料合并为「一条」专业短片 video prompt。",
  "mediaGen.videoInclude": "须含：身份锁定、镜头运动、表演／对白、节奏、光影连续。",
  "mediaGen.videoFacts": "只用材料与 seed 中的事实；勿引入固定样本世界或 Demo 故事。",
  "mediaGen.videoNoSwap": "有附图时禁止换成另一演员、场景或道具。",
  "mediaGen.videoHardRules": "有 HARD RULES 则置于文末。",
  "mediaGen.imageSystem": "你是短剧静图／指示图 prompt 导演。",
  "mediaGen.imageMergeStills": "将用户勾选材料与附图合并为「一条」出图 prompt。",
  "mediaGen.imageMergeText": "将用户勾选文字材料合并为「一条」出图 prompt。",
  "mediaGen.imagePriority": "最高优先：附图中的脸／服装／场景／道具必须一致。",
  "mediaGen.imageNoSwap": "有角色／场景静图时，禁止换成无关沙龙店员或另一间店。",
  "mediaGen.imageFacts": "只用材料与 seed 中的事实；勿引入固定样本世界或 Demo 故事。",
  "mediaGen.imageLayout": "若要求多格板，保留精确格数与分隔。",
  "mediaGen.imagePackage": "若有 LAYOUT／出图方案区块，最终 prompt 必须严格执行该 layout（格数、姿势、构图）。",
  "mediaGen.imageHardRules": "有 HARD RULES 则置于文末。",
  "mediaGen.directorFallback": "图生影片：以这张关键帧做短剧片段。身份、戏服、场景、构图须锁定关键帧，由此画面开始动。",
  "mediaGen.directorFallbackCam": "镜头运动与表演清楚；对白口型跟着脚本；无字幕、无浮水印。",
  "charIntro.task": "图生影片：以参考图中的同一人物，拍一段短剧选角用「自我介绍」短片。",
  "charIntro.identityLock": "身份锁定：脸、发型、体型、年龄感、服装与颜色必须与参考静帧一致，不可换成另一个人。",
  "charIntro.personality": "性格／气场：{{personality}}。",
  "charIntro.backstory": "背景要点：{{backstory}}。",
  "charIntro.relationships": "关是要点：{{relationships}}。",
  "charIntro.soul": "Soul 摘要（表演来源）：{{soul}}",
  "charIntro.performance": "表演：轻微推近或手持晃动；角色望向镜头或略偏镜头；{{manner}}。",
  "charIntro.speech": "口白：嘴唇自然开合像在简短自我介绍；声线：{{voice}}。",
  "charIntro.beat": "动作节奏：自然站定 → 微笑或轻点头 → 简短介绍手势（可空手）→ 定格。",
  "charIntro.lighting": "光线与静帧一致；无字幕、无 logo、无其他人入镜。",
  "sceneIntro.task": "图生影片：以参考静帧中的同一场地，拍一段短剧用「场景介绍／建立镜头」短片。",
  "sceneIntro.spaceLock": "空间锁定：建筑、材质、招牌、格局与色彩语言必须与参考静帧一致，不可换成另一个地方。",
  "sceneIntro.name": "地点名称：{{name}}。",
  "sceneIntro.place": "场地描述：{{place}}。",
  "sceneIntro.spaceType": "空间类型：{{type}}。",
  "sceneIntro.time": "时段：{{time}}。",
  "sceneIntro.weather": "天气：{{weather}}。",
  "sceneIntro.moodLight": "气氛：{{mood}}。灯光：{{lighting}}。",
  "sceneIntro.palette": "色盘：{{palette}}。",
  "sceneIntro.setDressing": "陈设：{{set}}。",
  "sceneIntro.tags": "视觉标签：{{tags}}。",
  "sceneIntro.art": "艺术风格：{{art}}。",
  "sceneIntro.ambient": "环境氛围（无 UI 字幕）：{{sound}}。",
  "sceneIntro.scriptCue": "本场提示（只作气氛，勿新增角色脸，除非静帧已有）：{{cue}}。",
  "sceneIntro.camera": "运镜：{{camera}}；连续轻微动态。除非材料已有，否则勿新增路人脸、logo、字幕。",
  "sceneIntro.beat": "动作节奏：建立镜头定场 → 环境微动（光影、天气粒子、已有的布料／树影）→ 定格。",
  "propIntro.task": "图生影片：以参考静帧中的同一道具，拍一段短剧 continuity 用「道具介绍／主视觉」短片。",
  "propIntro.objectLock": "物件锁定：轮廓、材质、颜色、刻字／纹样、旧损与比例必须与参考图一致，不可换成另一件。",
  "propIntro.name": "道具名称：{{name}}。",
  "propIntro.look": "外观描述：{{look}}。",
  "propIntro.material": "材质：{{material}}。",
  "propIntro.size": "尺寸笔记：{{size}}。",
  "propIntro.condition": "状态／旧损：{{condition}}。",
  "propIntro.tags": "视觉标签：{{tags}}。",
  "propIntro.art": "艺术风格：{{art}}。",
  "propIntro.camera": "运镜：干净桌面／主视觉台，轻微环绕或慢推近；光线与静帧一致。",
  "propIntro.beat": "动作节奏：主视觉定格 → 微光泽／微旋转或材质闪烁（若图中已有）→ 定格。",
  "propIntro.noHands": "除非静帧已有，否则勿加手、角色脸、字幕、浮水印或额外道具。",
  "costumeIntro.task": "图生影片：以参考静帧中的同一戏服造型，拍一段短剧戏服库用「造型介绍」短片。",
  "costumeIntro.wardrobeLock": "服装锁定：轮廓、布料、颜色、层次、配件与旧损必须与参考图一致，不可换成另一套。",
  "costumeIntro.identityOrProduct": "若静帧有人：锁定脸与体型，布料可轻微摆动；若为人台／平铺：保持产品构图。",
  "costumeIntro.name": "造型名称：{{name}}。",
  "costumeIntro.desc": "戏服描述：{{look}}。",
  "costumeIntro.art": "艺术风格：{{art}}。",
  "costumeIntro.camera": "运镜：轻微推近或慢环绕；光线与静帧一致。",
  "costumeIntro.beat": "动作节奏：定格 → 布料垂坠／袖口微动／五金反光 → 定格。",
  "costumeIntro.forbid": "勿新增角色脸、字幕、logo 或色情姿势。",
  "costumeIntro.fallbackName": "造型",
  "actionIntro.lead": "短剧动作示范片：「{{name}}」。",
  "actionIntro.intention": "意图：{{intention}}",
  "actionIntro.body": "肢体节奏：{{body}}",
  "actionIntro.camera": "镜头：{{camera}}",
  "actionIntro.closing": "动作连贯流畅，无字幕水印，紧跟关键帧静图。",
  "sceneIntroPolish.task": "任务：场景介绍／建立镜头短片（图生影片）。",
  "sceneIntroPolish.hasRef": "参考场景静图会交予影片 API——必须锁定该图空间身份。",
  "sceneIntroPolish.noRef": "本文无静图路径；仍须锁定地点圣经描述。",
  "sceneIntroPolish.dossier": "场景文件：",
  "sceneIntroPolish.scriptCue": "剧本提示（只作气氛）：\n{{script}}",
  "sceneIntroPolish.emptySet": "空镜为主；除非静帧已有，否则勿新增角色脸。无字幕、logo。",
  "propIntroPolish.task": "任务：道具主视觉介绍短片（图生影片）。",
  "propIntroPolish.hasRef": "参考道具静图会交予影片 API——必须锁定该图物件身份。",
  "propIntroPolish.noRef": "本文无静图路径；仍须锁定道具文件描述。",
  "propIntroPolish.dossier": "道具文件：",
  "propIntroPolish.noHands": "除非静帧已有，否则勿新增手或角色脸。无字幕、logo。",
  "costumeIntroPolish.task": "任务：戏服／造型介绍短片（图生影片）。",
  "costumeIntroPolish.hasRef": "参考静图会交予影片 API——有人则锁定身份＋服装；人台／平铺则锁定服装轮廓与材质。",
  "costumeIntroPolish.noRef": "本文无静图路径；仍须锁定戏服描述。",
  "costumeIntroPolish.dossier": "戏服文件：",
  "costumeIntroPolish.fabric": "布料垂坠／微动即可；勿新增角色脸；无字幕、logo。",
  "actionIntroPolish.task": "任务：动作指导介绍短片（图生影片）。",
  "actionIntroPolish.hasRef": "参考静图已附——表演身份锁定该帧。",
  "actionIntroPolish.templateKeepRules": "模板草稿（请改进；HARD RULES 置于最尾）：",
  "cover.posterLead": "PROFESSIONAL SHORT-DRAMA POSTER / KEY ART（16:9 静帧）。不是 UI 模型。无文字、logo、浮水印、标题字幕。",
  "cover.titleMood": "故事标题（只取气氛，画面勿写出文字）：{{title}}。",
  "cover.styleBible": "风格备注：{{style}}",
  "cover.extraDir": "额外方向：{{idea}}",
  "cover.establishing": "适合用作片库封面的情绪建立镜头；强烈剪影、可读气氛。",
  "cover.medium": "依艺术风格 medium 出图；构图清晰。",
  "cover.editPrefix": "IMAGE EDIT：以新构图创作短剧海报。保留主体身份／气氛（如有）。",
  "cover.label": "故事封面",
  "costumeFill.system": "你是影视造型指导。只回复紧凑 JSON：{\"name\":\"短名称\",\"description\":\"完整戏服描述（分层、布料、颜色、配饰；无品牌 Logo）\",\"artStyle\":\"可选风格 id 或空字串\",\"hardRules\":\"3–8 句必须／禁止\"} 每个键必须是 JSON 字串（不可 null／阵列）。不要 markdown。若有参考图，请按图如实描述该造型，供短剧出图使用。",
  "costumeFill.idea": "构思：{{idea}}",
  "costumeFill.polish": "润饰以下戏服草稿。",
  "costumeFill.required": "必填键：name, description, artStyle, hardRules。缺键无效。",
  "costumeFill.fallbackName": "造型",
  "segment.entireStory": "全剧（所有场次）",
  "segment.noStory": "未选故事（仅角色资料）",
  "vision.inventFromImage": "请根据附上的参考图，完整填写{{kind}}资料。",
  "vision.polishAll": "全面润饰并合并所有栏位",
  "story.untitled": "未命名短剧",
  "action.castIdentityNote": "已附 {{count}} 张参考素材（角色／道具等）：每格人物身份须与参考素材一致。",
  "tpl.system.polishOnly": "配方「只润饰」：保持核心身份与世界。只润饰措辞。不要发明时代、天气、职业、地点或样本世界。不要发明口白语言。不要把预设铁则写入档。",
  "tpl.system.fillBlanks": "配方「只填空白」：只补空栏。已填栏位不要改写。不要发明新世界。",
  "tpl.system.invent": "配方「自由创作」：用户授权按 idea 自由补齐可拍细节，必填栏要齐。仍然不要引入 Demo 或本次未暗示的世界。",
  "tpl.system.fromStory": "配方「从故事建议」：只用本次请求已写出的标题／风格／选角／场景做 continuity。冲突时以用户 idea 为准。",
  "tpl.system.followAsset": "配方「跟资产／故事」：跟已提供的风格与铁则。除非材料有写，不要强加电影感、空镜或 6–10 秒。片长跟 clip 实际秒数。",
  "tpl.system.cinematicLock": "配方「电影感＋防幻觉」：电影短剧感；场地空镜优先；无水印、logo、多余脸；人类恰好两手两臂两腿（非人除外）。",
  "tpl.system.identityLock": "配方「锁身份」：脸／体／服装／场地／道具必须锁定附图。不要换成另一人、另一地或另一物。",
  "tpl.system.restyle": "配方「可改造型」：保持同一角色身份。服装、场地陈设、时代可按用户要求改。不要换成另一个人。",
  "pipeline.character.system": "你为短剧 AI 影片润饰角色圣经。每位角色 3–5 行：外形、声线、动机、招牌动作。只用本次请求已有事实。",
  "pipeline.scene.system": "你把短剧场景扩成视觉节拍表。每拍跟材料里的实际片长，不要假定 6–10 秒。只用已提供场景。",
  "pipeline.props.system": "你为短剧润饰道具连续性。记颜色、尺寸、出场时机。名单以外不要发明道具。",
  "pipeline.script.system": "你是专业短剧编剧。每场写一段适合 AI 影片的紧凑剧本。用故事实际片长，不要硬加 10 秒上限。每场格式：\n### SCENE <number> | id=<id>\n<script body>",
  "pipeline.script.noScenes": "（无场景 — 不要发明地点）"
}