import type { PromptCopyTable } from './keys'

export const zhCnPromptCopy: PromptCopyTable = {
  "speechLock.named": "对白锁定 · 角色「{{who}}」：可听语音和口型必须只用{{primaryName}}（{{primary}}）。禁止改说{{forbid}}或其他语言。每段都要同一种对白语言。不要翻译对白。",
  "speechLock.unnamed": "对白锁定 · 出场角色：可听语音和口型必须只用{{primaryName}}（{{primary}}）。禁止改说{{forbid}}或其他语言。每段都要同一种对白语言。不要翻译对白。",
  "speechLock.namedMulti": "对白锁定 · 角色「{{who}}」：可听语音和口型必须用{{primaryName}}（{{primary}}）。只有剧本该句已经是以下语言才可以讲第二种：{{extras}}。禁止第三种语言。禁止每段转换。禁止改说{{forbid}}。不要翻译对白。",
  "speechLock.unnamedMulti": "对白锁定 · 出场角色：可听语音和口型必须用{{primaryName}}（{{primary}}）。只有剧本该句已经是以下语言才可以讲第二种：{{extras}}。禁止第三种语言。禁止每段转换。禁止改说{{forbid}}。不要翻译对白。",
  "hardRules.sealHeader": "生成铁则（最高优先，必须遵守，覆盖前文冲突）：",
  "hardRules.sealFooter": "若前文与生成铁则冲突，以生成铁则为准。",
  "hardRules.labelStory": "故事",
  "hardRules.labelCharacter": "角色",
  "hardRules.labelScene": "场景",
  "hardRules.labelProp": "道具",
  "hardRules.labelAction": "动作",
  "continuity.lockHeader": "画面连续锁定（短剧顺序必须遵守）：",
  "continuity.hasImage": "附图是第 {{n}} 段的结尾格／关键帧。本段须由该画面状态接续，不可硬切到另一套布景。",
  "continuity.noImage": "承接第 {{n}} 段（无静图——只按文字档案对齐）。",
  "continuity.identity": "身份：同一人——脸、发、体型比例、服装颜色、配饰。不要改造型、不要改年龄。",
  "continuity.space": "空间：同一地点——建筑、物料、格局、光线方向。仅在剧情需要时可有轻微时段变化。",
  "continuity.action": "动作：承接上一格的姿势、视线与动向；不要硬切到另一套站位。",
  "continuity.prevContext": "上一段脉络：{{snippet}}",
  "continuity.noText": "无字幕、无标志、无浮水印。",
  "directorLabel.lock": "对白锁定",
  "directorLabel.story": "故事：",
  "directorLabel.style": "风格：",
  "directorLabel.cast": "角色：",
  "directorLabel.location": "场景：",
  "directorLabel.prop": "道具：",
  "directorLabel.primaryChar": "主角色：",
  "directorLabel.mood": "心情：",
  "directorLabel.atmo": "气氛：",
  "directorLabel.camera": "镜头：",
  "directorLabel.sfx": "声效：",
  "directorLabel.action": "动作：",
  "directorLabel.expr": "表情：",
  "directorLabel.speech": "对白：",
  "directorLabel.notes": "导演备注：",
  "directorLabel.identity": "身份：",
  "directorLabel.space": "空间：",
  "directorLabel.ref": "参考图",
  "directorLabel.beatN": "第 {{n}} 段 · ",
  "directorLabel.beatNsec": "第 {{n}} 段 · {{s}} 秒片段",
  "directorLabel.hardRules": "生成铁则",
  "directorLabel.identityLock": "身份锁定",
  "directorLabel.spaceLock": "空间锁定",
  "storyBeats.system": "你为短剧时间轴撰写「剧情段落」——每一段 = 一小段 AI 影片的完整拍摄脚本，而非一句对白。\n每段必须有丰富表演内容：心情、气氛、动作、表情、可选镜头／声效，以及 0 至多句对白（常见 1–4 句）。\n只回传 JSON 数组（不要代码块）。每项形状：\n{\"characterName\":\"…\",\"characterNames\":[\"…\"],\"sceneHint\":\"…\",\"sceneHints\":[\"…\"],\"propName\":\"…\",\"propNames\":[\"…\"],\"actionName\":\"…\",\"actionNames\":[\"…\"],\"mood\":\"…\",\"atmosphere\":\"…\",\"camera\":\"…\",\"sfx\":\"…\",\"units\":[{\"type\":\"action\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"expression\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"dialogue\",\"who\":\"…\",\"line\":\"…\",\"tone\":\"…\",\"parenthetical\":\"…\"},{\"type\":\"note\",\"text\":\"…\"}]}\n规则：\n- dialogue.line 只写角色讲出口的话，不要把动作写进对白。\n- 肢体动作放 action；表情微表演放 expression；语气放 tone／parenthetical。\n- 一段可有多句对白（对话回合或自语）。\n- 允许纯动作段（无对白）。\n- 禁止默认一章一段。按可拍短片拆：换场、跳时、新冲突、或一段 6–10 秒装不下的动作／对白 → 另开一段。一章通常 1–3 段。总数不超过 {{maxBeats}} 段。\n- 列出本 clip 出现的全部名单内角色／场景／道具／动作（characterNames、sceneHints、propNames、actionNames）。上限：角色 4、场景 2、道具 4、动作 4。不要每样只填一个。\n- 有肢体表演就必须填 actionNames，而且要用故事已选动作库的原名。有肢体就不准留空；宁可从已选名单勾上，也不要一只都不填。\n- 每段 units 最多 4 项（1–2 个 action、0–1 个 expression、0–2 句 dialogue）。角色名必须用提供名单。正文要短，一次回完 JSON。\n- 要有冲突、可视动作、可拍细节。\n- 忠于已提供的标题、风格、选角与场景。不要擅自扩世界。\n- 对白：dialogue.line 必须用该角色主语言写（见角色名单）。禁止段与段转语言。除非角色名单写明，否则不要改写成其他语言。",
  "storyBeats.userLead": "生成完整「短片脚本」段落：使用下方全部选角、场景、道具、动作、风格与构想。",
  "storyBeats.eachBeat": "每段要有心情、气氛、动作／表情，以及可选的多句对白。",
  "storyBeats.story": "故事：{{title}}",
  "storyBeats.style": "风格：{{style}}",
  "storyBeats.userDir": "用户指示：{{idea}}",
  "storyBeats.cast": "角色：",
  "storyBeats.scenes": "场景：",
  "storyBeats.props": "道具：{{props}}",
  "storyBeats.actions": "动作（肢体）：{{actions}}",
  "storyBeats.returnJson": "只回传段落 JSON 数组。",
  "storyBeats.noCast": "（无角色）",
  "storyBeats.noScenes": "（无场景 — sceneHint 可写地点）",
  "storyBeats.none": "（无）",
  "storyBeats.chapters": "故事章节（拆拍主来源——请把以下章节拆成可拍段落）：",
  "storyBeats.chapterBlock": "第 {{n}} 章 · {{title}}\n{{body}}",
  "storyChapters.system": "你为短剧撰写「章节」——这是故事灵魂（可读叙事），不是分镜脚本。\n每章约 {{words}} 字散文：冲突、地点、谁在场、想要什么、局面如何改变。\n只回传 JSON 数组（不要 markdown）。每项：{\"title\":\"…\",\"body\":\"…\"}.\n固定写 {{count}} 章。忠于标题、风格圣经、生成铁则与用户构想。不要另起世界。正文要短，一次回完 JSON。",
  "storyChapters.userLead": "把故事写成有序章节（章节／treatment）。之后会用这些章节生成角色、场景、道具、动作，再拆成拍摄段落。",
  "storyChapters.story": "故事：{{title}}",
  "storyChapters.style": "风格圣经：{{style}}",
  "storyChapters.rules": "生成铁则：{{rules}}",
  "storyChapters.userDir": "用户构想：{{idea}}",
  "storyChapters.returnJson": "只回传 JSON 数组：[{\"title\":\"…\",\"body\":\"…\"}, …]",
  "storyChapters.polishSystem": "你润饰短剧的「一章」。保留情节事实、人名与结局，写得更可拍（具体地点、身体、道具、冲突）。只回传 JSON：{\"title\":\"…\",\"body\":\"…\"}。",
  "storyChapters.polishUser": "故事：{{story}}\n现有标题：{{title}}\n现有正文：\n{{body}}\n可选指示：{{idea}}\n回传润饰后 JSON {\"title\",\"body\"}。",
  "storyCastFromChapters.system": "你从故事章节抽出制作圣经：角色、场景／地点、关键道具、标志性动作。\n只回传 JSON（不要 markdown）：\n{\"characters\":[{\"name\":\"\",\"description\":\"\",\"appearance\":\"\",\"personality\":\"\",\"costume\":\"\",\"roleNote\":\"\"}],\"scenes\":[{\"title\":\"\",\"description\":\"\",\"locationType\":\"\",\"timeOfDay\":\"\",\"mood\":\"\"}],\"props\":[{\"name\":\"\",\"description\":\"\"}],\"actions\":[{\"name\":\"\",\"description\":\"\",\"motionNotes\":\"\",\"intention\":\"\"}]}\n规则：只抽取章节里出现的实体。若已列出现有名字就沿用。人物／地点／物件／动作要可区分。视觉细节要具体。允许空数组。禁止一章一角色／一场景／一道具／一动作。一章可以有两个角色、几个地点、多件道具、多个肢体动作。只抽实际出现、可区分的实体。例如：对话两人 → 两个 characters；巷口再入祠堂 → 两个 scenes。不要为了凑数而发明。",
  "storyCastFromChapters.userLead": "抽出章节里每一个出现过的角色、场景、道具、动作——不要一章一套。",
  "storyCastFromChapters.story": "故事：{{title}}",
  "storyCastFromChapters.style": "风格：{{style}}",
  "storyCastFromChapters.chapters": "章节：\n{{chapters}}",
  "storyCastFromChapters.existingCast": "本故事已有（请沿用这些名字）：{{names}}",
  "storyCastFromChapters.returnJson": "只回传 JSON 物件。",
  "videoPolish.system": "你为短剧 AI 图生影片模型撰写「一条」最终导演提示词。\n只回传提示词正文——不要 markdown 代码块、标题或解释。\n规则：\n- 提示词全文用用户界面语言书写；角色姓名与对白语言要求须清楚标示。\n- 人物静图：身份锁定（脸、发、体型、服装、颜色）。场景静帧：空间锁定（建筑、材质、格局、招牌、色盘）。除非材料点名，否则勿新增角色脸。\n- 凡已提供且影响外形、动作、对白、气氛或场地的人设／角色圣经／段落／地点资料均须用上；空白栏位可略。\n- 只按已提供材料补齐可拍细节；勿引入固定样本世界、示范样本故事、或材料未出现的事实。\n- 长篇角色圣经（soul.md）须浓缩为可拍的表演与身份要点，不可整篇照贴。\n- 片长跟材料里的实际秒数。动作连贯。无字幕、标志、浮水印、无关路人。\n- 除非剧情要求，否则解剖结构正常（双手双脚）。\n- 多角色时保持每位主体一致；主焦点优先。\n- 若材料含生成铁则，必须保留并放在输出最尾（最高优先）。\n- 对白锁定必须保留：不得删改或翻译；语言代码要写成全名。每段跟角色主口语，禁止段与段转语言，禁止翻译对白。\n- 导演修订可调整气氛／动作，但不得违反生成铁则。",
  "videoPolish.hardRulesKeep": "生成铁则（最高优先——保留每一行；[角色 · 名] 等物件标签不可删）。必须将完整生成铁则区块放在输出最末。不得削弱、删除或套错主体。",
  "clip.task": "任务：短剧时间轴片段（图生影片）。",
  "clip.hasRef": "可能附有参考静图——相关时锁定身份／场地连续性。",
  "clip.characters": "角色：",
  "clip.scene": "场景：",
  "clip.prop": "道具：",
  "clip.action": "动作指导：",
  "clip.beat": "段落／对白：",
  "clip.prev": "前一段连续性：",
  "clip.revision": "导演修订（必须遵守）：",
  "clip.templateDraft": "模板草稿（请改进）：",
  "intro.task": "任务：自我介绍选角短片（图生影片）。",
  "intro.hasRef": "参考静图会交予影片 API——必须锁定该图身份。",
  "intro.noRef": "本文无静图路径；仍须锁定人设外貌／戏服。",
  "intro.dossier": "角色档案：",
  "intro.templateDraft": "模板草稿（请改进；勿忽略档案）：",
  "common.durationAspect": "时长：{{seconds}} 秒。画面比例：{{aspect}}。",
  "common.templateDraft": "模板草稿：",
  "improve.mode": "改进模式：合并下方所有来源输出完整结果。除非用户明确要求改身份，否则保持核心一致。表单稀疏时以额外上下文为准；用户明确要求更改时以指示为准。",
  "improve.draftDefault": "目前表单栏位（已填内容）：",
  "improve.userRequest": "用户改进要求（可留空 = 全面润饰并合并以上内容）：",
  "improve.emptyDefault": "（全面润饰：适合短剧／出图／出片画面连续）",
  "improve.createDefault": "构想／方向：",
  "improve.explicitContext": "仅限本次请求明确附上的上下文（作画面连续；勿引入其他样本世界；与 idea／表单冲突时以用户为准）：",
  "improve.storyTitle": "故事标题：{{title}}",
  "improve.styleNote": "风格备注：{{style}}",
  "improve.closingDefault": "请立即输出完整结果。",
  "storyMeta.system": "你是短剧主创／视觉总监。根据故事标题与构想，写简洁可拍的风格备注以及出图／出片「生成铁则」。只回传 JSON（不要代码块）：{\"styleNote\":\"2–5 句：气氛、光线、镜头、色调、节奏\",\"hardRules\":\"3–8 句必须／禁止\"}。要具体、适合 AI 影片／出图延续。用提供的标题、构想、现有风格／铁则与上下文。不要擅自发明风格。",
  "storyMeta.draftLabel": "目前故事栏位：",
  "storyMeta.createLabel": "故事构想／标题：",
  "storyMeta.emptyPolish": "（润饰视觉风格备注与生成铁则，利于 AI 出片画面连续）",
  "storyMeta.closing": "只回传 JSON：{\"styleNote\":\"…\",\"hardRules\":\"…\"}。两个键都必填且非空。",
  "storyMeta.contextLabel": "故事上下文（角色／场景／道具）：",
  "character.system": "你是专业短剧角色设定师，专门为 AI 影片／短剧生成「可拍、可认、可一致」的角色圣经。用户会给一段角色 idea。角色可以是人类、动物、鬼灵、魔物、机械、虚拟形象或其他设计体——依 idea 而定，勿强行写成人类。只输出一个 JSON 物件。spokenLanguages：BCP-47 代码阵列，例如 [\"yue\",\"en\"]。非语言角色用 []。避免空泛形容；用可拍摄的细节。同一角色必须视觉一致。",
  "character.draftLabel": "目前 Profile 表单栏位（已填内容）：",
  "character.soulLabel": "已连结 soul.md／角色圣经（主要身份与性格依据）：",
  "character.createLabel": "角色 idea：",
  "character.emptyPolish": "（全面润饰：将 soul 与表单合并进完整 Profile）",
  "character.closing": "请立即输出完整 JSON。必填键：{{keys}}。visualTags 为逗号分隔字串（禁止标签阵列）；spokenLanguages 可以是代码阵列。",
  "scene.system": "你是短剧场景／场景空间设计师，服务 AI 影片画面连续。请输出可拍的地点圣经 + 本场可演剧本片段。只回传一个 JSON 物件。title＝短地名；description＝建筑、物料、地标；script＝本场对白／动作／镜头。",
  "scene.draftLabel": "目前场景表单栏位（已填内容）：",
  "scene.charsLabel": "故事角色：",
  "scene.propsLabel": "故事道具：",
  "scene.priorLabel": "既有场景（画面连续）：",
  "scene.createLabel": "场景 idea：",
  "scene.emptyPolish": "（全面润饰地点与本场剧本，利于出片画面连续）",
  "scene.closing": "请立即输出完整 JSON。必填键：{{keys}}。缺键无效。visualTags 必须是逗号分隔字串，禁止阵列。",
  "prop.system": "你是短剧道具设计师，服务 AI 影片画面连续。只回传一个 JSON。description：可画细节；material／sizeNotes／condition 具体。",
  "prop.draftLabel": "目前道具表单栏位（已填内容）：",
  "prop.createLabel": "道具 idea：",
  "prop.emptyPolish": "（全面润饰道具外观，利于出片画面连续）",
  "prop.closing": "请立即输出完整 JSON。必填键：{{keys}}。缺键无效。visualTags 必须是逗号分隔字串，禁止阵列。",
  "prop.fallbackName": "道具",
  "action.system": "你是短剧动作指导。只输出有效 JSON，描述一项可拍摄的动作指导。要具体：身体部位、节奏、力度、道具路径、走位。不要 markdown。",
  "action.storyContext": "故事脉络（可选）：{{title}}",
  "action.styleNote": "风格备注：{{style}}",
  "action.existingDraft": "现有草稿（请润饰补全）：",
  "action.userIdea": "用户构想：{{idea}}",
  "action.closing": "只回传 JSON。必填键：{{keys}}。visualTags 为逗号分隔字串，禁止阵列。",
  "profile.mustEveryKey": "必须输出列表中的每一个键：{{keys}}。",
  "profile.valuesAreStrings": "每个值必须是 JSON 字串（不可 null、不可用 JSON 阵列）。真的不知道才可空字串。",
  "profile.visualTagsRule": "visualTags：用用户界面语言的单一逗号分隔字串——禁止 JSON 阵列。",
  "profile.fillConcrete": "各键请尽量填具体细节，利于短剧画面连续。",
  "common.rules": "规则：",
  "common.none": "（无）",
  "intro.soul": "soul.md（作为表演／身份完整来源）：\n{{soul}}",
  "intro.matchBible": "（跟从角色人设语言）",
  "invent.sources": "依据来源（优先序）：（1）用户 idea／指示，（2）已填表单，（3）仅当「本次提示词 已写出」的额外上下文（soul、选角、故事区块等），（4）附上的参考图。",
  "invent.create": "创作模式（表单空白／极少）：按 idea／图自由创作，补齐可拍摄的关键栏位，内容须与用户构想相关——勿留空必填键。",
  "invent.improve": "改进模式（表单已有内容）：润饰并补齐空白栏，与已填内容一致；除非用户要求，否则勿改核心身份。",
  "invent.noImport": "不得从「本次提示词 未出现」的来源引入身份、剧情、天气、职业、地点、时代或风格（禁止 active 故事、示范样本、App 默认世界观）。",
  "invent.storyBlock": "若下方明确附有故事／风格区块：仅作画面连续；不可覆盖用户明确 idea。",
  "character.keysLead": "只输出一个 JSON 物件（不要 markdown），键名必须是：{{keys}}",
  "character.ruleSpoken": "spokenLanguages：角色使用的语言，JSON 字串阵列（可多选），BCP-47／ISO 代码，例如 [\"yue\",\"en\"]。非语言角色用 []。",
  "character.ruleIdentity": "同一角色必须视觉一致，方便之后多角度参考图与影片生成。",
  "scene.keysLead": "只回传一个 JSON 物件（不要 markdown），键名：{{keys}}",
  "scene.suggestLead": "为故事「{{title}}」建议第 {{n}} 个可用场景（场地／环境设定）。",
  "scene.suggestPlotFocus": "剧情焦点：{{label}}",
  "scene.suggestStyle": "风格：{{style}}",
  "scene.suggestExisting": "库内／故事已有场地：{{titles}}",
  "scene.suggestChars": "角色（上下文）：",
  "scene.suggestProps": "道具（上下文）：",
  "scene.suggestSegment": "选定剧情段落详情：",
  "scene.suggestBeats": "故事场次／段落：",
  "scene.suggestClosing": "回传完整场景 JSON。请设计一个可重复使用的独立场地（全域场景库资产），须贴合选定剧情焦点，并与已有场地有所区别。",
  "scene.fallbackName": "场景",
  "scene.ideaFromImage": "请根据附上的参考图，完整填写场景资料。",
  "scene.polishIdea": "全面润饰",
  "prop.keysLead": "只回传一个 JSON，键名：{{keys}}",
  "action.fieldsLead": "栏位：{{keys}}。",
  "soul.system": "你为短剧／影视角色撰写制作用角色圣经（soul.md，单档 Markdown）。\n只输出完整 Markdown 文件（不要代码块围栏、不要解说）。\n结构（请用以下 ## 标题）：\n# {角色名}\n## 身份\n## 外貌\n## 服装与轮廓\n## 性格与声线\n## 使用语言\n## 小习惯\n## 背景\n## 关系\n## 表演与对白风格\n## 一致性硬规则\n## 视觉标签\n规则：\n- 短剧可拍、可辨认、可一致；细节须具体。\n- 依据：资料表单 + 现有角色圣经 + 用户指示。除非所选配方允许，否则勿用本次未提供的来源臆造。\n- 对白／配音必须尊重 profile 的 spokenLanguages。\n- 硬规则用 5–10 条 bullet，方便之后图像／对白 AI 遵守。\n- 用用户界面语言书写（中国大陆简体书面语优先，若界面是其他语言就跟界面）。\n- 可选开头 YAML frontmatter（name / tags），非必须。",
  "soul.improveMode": "改进模式：合并 Profile 表单 + 现有 soul，输出更新后完整 soul.md。除非要求改身份，否则保持核心一致。",
  "soul.createMode": "根据以下角色设定撰写完整 soul.md（合理补齐空白；不要换成另一个人）：",
  "soul.profileFields": "Profile 表单栏位（已填内容）：",
  "soul.existing": "现有 soul.md（合并／改进；勿丢有用细节）：",
  "soul.userRequest": "用户指示：{{request}}",
  "soul.extraContext": "本次一并提供的上下文（有用就用；仍以 profile 为准）：",
  "soul.returnOnly": "只输出完整 soul.md Markdown 正文。",
  "wardrobe.system": "你是短剧服装与视觉风格顾问。根据角色与剧情，提出一套完整外装方案。只回传一个 JSON 物件（不要 markdown 围栏）：{\"name\":\"短名称\",\"costume\":\"详细外装描述（供出图／影片）\",\"artStyle\":\"下列其一\",\"rationale\":\"一两句理由\"} artStyle 必须是：{{styleIds}} costume 要具体：材质、颜色、轮廓、鞋履、配件。年龄表述须得体；禁止对未成年做性化描述。保留既有外貌身份，只设计服装与风格。用角色栏位与已提供的剧情／故事上下文。不要擅自发明造型世界。",
  "wardrobe.improveMode": "改进／建议模式：使用下方全部角色栏位与剧情上下文。",
  "wardrobe.characterForm": "角色（完整表单）：",
  "wardrobe.soulExcerpt": "soul.md 摘要：\n{{soul}}",
  "wardrobe.userRequest": "用户指示：{{request}}",
  "wardrobe.storyContext": "故事／制作上下文（有就用；勿另起一个世界）：",
  "wardrobe.style": "风格：{{style}}",
  "wardrobe.segment": "选定剧情段落：{{label}}",
  "wardrobe.sceneContext": "场景／段落／对白摘录：",
  "wardrobe.noScenes": "（尚无场景）",
  "wardrobe.proposeNew": "请提出一套符合剧情的新戏服（避免与已有造型重复）。",
  "fill.system": "你负责补齐短剧资产设定中「仍然空白」的栏位。\n只回传一个 JSON 物件，且只能包含这些键：{{keys}}。\n每个值必须是非空 JSON 字串（不可 null、不可 JSON 阵列）。\n若含 visualTags：用用户界面语言的逗号分隔字串（格式例：\"gold, necklace\"，勿照抄例子，须贴合本资产）——禁止阵列。\n只根据已有部分设定及参考图补齐；勿另起未见于 partial／图的剧情、地点或样本世界。\n不要 markdown、不要解说。",
  "fill.userPartial": "已有部分设定（勿矛盾）：",
  "fill.userOnly": "只补齐这些空白键：{{keys}}。",
  "fill.userReturn": "只回传含上述键的 JSON；每值为非空字串。",
  "imageGen.multiRef": "另有 {{n}} 张已选参考图：主编辑底图为第一张，其余作身份一致辅助，勿换成另一物件／主体。",
  "residual.sceneLink": "第 {{n}} 场：{{short}}",
  "residual.beatSegment": "段落 {{n}} · {{who}}{{tail}}",
  "residual.unknown": "未指定",
  "residual.story": "故事",
  "beat.mood": "【心情】{{text}}",
  "beat.atmo": "【气氛】{{text}}",
  "beat.camera": "【镜头】{{text}}",
  "beat.sfx": "【声效】{{text}}",
  "beat.action": "【动作】{{text}}",
  "beat.actionWho": "【动作｜{{who}}】{{text}}",
  "beat.expr": "【表情】{{text}}",
  "beat.exprWho": "【表情｜{{who}}】{{text}}",
  "beat.dialogue": "【对白｜{{who}}】{{body}}",
  "beat.dialogueTone": "【对白｜{{who}}｜{{tone}}】{{body}}",
  "beat.whoUnknown": "？",
  "beat.template": "【心情】緊繃、猶豫\n【气氛】門縫暖光；雨砸地\n【鏡头】中景，跟手推近\n【声效】雨、布料摩擦\n【动作｜角色名】摘下安全帽；盯門縫暖光；手伸進外套內袋\n【表情｜角色名】眉心緊鎖，呼吸一滯\n【对白｜角色名｜低声沙啞】又是落雨……\n【对白｜角色名｜自语】（停半拍）你……仲在度？",
  "vision.preamble": "已附上参考静图。请主要根据图片填写此{{what}}全部栏位；可结合构思／草稿润饰。",
  "vision.character": "角色（名称、外貌、戏服、年龄、性别、标签等）",
  "vision.scene": "场景（标题、描述、光影、气氛、布景、标签等）",
  "vision.prop": "道具（名称、描述、材质、尺寸、状态、标签等）",
  "vision.action": "动作（名称、说明、节奏、意图、镜头备注、标签等）",
  "vision.costume": "戏服（名称、完整造型描述）",
  "still.header": "短剧画面连续用单格关键帧静图（不是多格板）。产出一张对应下方镜头的主画面。无文字、标志、浮水印、UI。清晰可制作。",
  "still.revision": "用户改进要求（必须套用）：{{notes}}",
  "still.regenTask": "任务：修订 图生影片 导演提示词，并保持可作关键帧静图 简报。",
  "still.userImprove": "用户改进要求：\n{{notes}}",
  "still.currentPrompt": "目前专业提示词：",
  "still.hardRules": "生成铁则（必须保留于输出最尾；不得删除或削弱）：",
  "mediaGen.writeOne": "请撰写「一条」最终短剧静图／多格指示图生成提示词。",
  "mediaGen.returnOnly": "只回传提示词正文——不要代码围栏、标题或解释。",
  "mediaGen.singleComposite": "输出描述「单一合成图」（只导出一张）。",
  "mediaGen.lockRefs": "附图图序与下方参考图编号一致，须作视觉准据。身份／戏服／场景／道具必须锁定附图，禁止换成另一人、另一店或另一物。",
  "mediaGen.videoSystem": "你是短剧图生影片导演提示词撰写者。",
  "mediaGen.videoMerge": "将材料合并为「一条」专业短片影片提示词。",
  "mediaGen.videoInclude": "须含：身份锁定、镜头运动、表演／对白、节奏、光影连续。",
  "mediaGen.videoFacts": "只用已提供材料 中的事实；勿引入固定样本世界或 示范样本故事。",
  "mediaGen.videoNoSwap": "有附图时禁止换成另一演员、场景或道具。",
  "mediaGen.videoHardRules": "有 生成铁则 则置于文末。",
  "mediaGen.imageSystem": "你是短剧静图／指示图提示词 导演。",
  "mediaGen.imageMergeStills": "将用户勾选材料与附图合并为「一条」出图提示词。",
  "mediaGen.imageMergeText": "将用户勾选文字材料合并为「一条」出图提示词。",
  "mediaGen.imagePriority": "最高优先：附图中的脸／服装／场景／道具必须一致。",
  "mediaGen.imageNoSwap": "有角色／场景静图时，禁止换成无关沙龙店员或另一间店。",
  "mediaGen.imageFacts": "只用已提供材料 中的事实；勿引入固定样本世界或 示范样本故事。",
  "mediaGen.imageLayout": "若要求多格板，保留精确格数与分隔。",
  "mediaGen.imagePackage": "若有出图方案区块，最终提示词必须严格执行该版面（格数、姿势、构图）。",
  "mediaGen.imageHardRules": "有 生成铁则 则置于文末。",
  "mediaGen.directorFallback": "图生影片：以这张关键帧做短剧片段。身份、戏服、场景、构图须锁定关键帧，由此画面开始动。",
  "comic.taskHint": "故事「{{title}}」漫画第 {{n}} 页：一张完整漫画页，刚好 {{count}} 格。全页角色身份、服装、场景必须连贯。无水印、无界面边框。",
  "comic.panelCount": "格数不可改：必须刚好 {{n}} 格。",
  "comic.lockSplash": "排版锁定：整页一格满版。禁止加框、分格、拼贴。",
  "comic.lockYonkoma": "排版锁定：直向四格，四行一列，由上至下。禁止二乘二网格或横条。",
  "comic.lockGrid2x2": "排版锁定：两行两列。禁止横条、二乘三、单格满版。",
  "comic.lockGrid2x3": "排版锁定：两行三列。上行一至三，下行四至六。禁止二乘二或三乘三。",
  "comic.lockGrid3x3": "排版锁定：三行三列，共九格。禁止二乘二、二乘三，或少于九格。",
  "comic.lockStrip": "排版锁定：单行横向刚好 {{n}} 格。禁止多行网格。",
  "comic.layoutSplash1": "一张直向漫画页：刚好一格满版，无分隔、无额外画框。",
  "comic.layoutStrip2": "一张横向漫画页：单行两格并排，粗白分隔。",
  "comic.layoutStrip3": "一张横向漫画页：单行三格，粗白分隔。",
  "comic.layoutYonkoma": "一张直向漫画页：四格漫画直向叠放（四行一列），粗白分隔，由上至下阅读。",
  "comic.layoutGrid2x2": "一张方形漫画页：二乘二网格，刚好四格，粗白分隔，先左至右再上至下。",
  "comic.layoutStrip4": "一张宽横向漫画页：单行四格，粗白分隔。",
  "comic.layoutGrid2x3": "一张横向漫画页：刚好六格，两行三列（上 1-2-3、下 4-5-6），粗白分隔，先左至右再上至下。",
  "comic.layoutGrid3x3": "一张方形漫画页：三乘三网格，刚好九格，粗白分隔，先左至右再上至下。",
  "comic.layoutWidePlusTwo": "一张竖向漫画页：上方约六成高为全宽大格，下方并排两小格，粗白分隔。",
  "comic.layoutTwoPlusWide": "一张竖向漫画页：上方并排两小格，下方约六成高为全宽收势格，粗白分隔。",
  "comic.layoutTallLeftTwo": "一张竖向漫画页：左半页一格直通全高，右半页上下两格，粗白分隔。",
  "comic.layoutHeroPlusThree": "一张竖向漫画页：上半页一格全宽大格，下半页单行三小格，粗白分隔。",
  "comic.layoutFocusQuad": "一张竖向漫画页：左上中格，右上两小格竖叠，下半页一格全宽大格，粗白分隔。",
  "comic.layoutStaggerFour": "一张竖向漫画页：两行错位——上行宽加窄，下行窄加宽，粗白分隔。",
  "comic.layoutDiagPairPlus": "一张竖向漫画页：上半页以斜线分成两楔形格，下半页一格全宽横格，粗白分隔。",
  "comic.layoutHeroPlusFour": "一张竖向漫画页：上半页一格全宽大格，下半页二乘二共四小格，粗白分隔。",
  "comic.lockWidePlusTwo": "排版锁定：上格为全宽大格。下方正好两小格并排。禁止三等分横条或二乘二。",
  "comic.lockTwoPlusWide": "排版锁定：上方刚好两小格。下方一格全宽收势。禁止三等分横条或二乘二。",
  "comic.lockTallLeftTwo": "排版锁定：左格直通全页高。右侧上下两格。禁止等分二乘二或单行横条。",
  "comic.lockHeroPlusThree": "排版锁定：上半页一格全宽大格。下方单行刚好三小格。禁止二乘二或四等格。",
  "comic.lockFocusQuad": "排版锁定：左上中格、右上两小格竖叠、下半页一大格。禁止等分二乘二。",
  "comic.lockStaggerFour": "排版锁定：错位大小——上行宽加窄，下行窄加宽。禁止四格等大方块。",
  "comic.lockDiagPairPlus": "排版锁定：上半页必须斜分成两楔形格；下半页一格全宽横格。禁止三等分横条或二乘二。",
  "comic.lockHeroPlusFour": "排版锁定：上半页一格全宽大格；下半页二乘二共四小格。全页刚好五格。禁止三乘三或整页二乘二。",
  "comic.readingYonkoma": "阅读顺序：只由上至下（竖向四格）。",
  "comic.readingWidePlusTwo": "阅读顺序：先读上方大格，再由左至右读下方两小格。",
  "comic.readingTwoPlusWide": "阅读顺序：先左后右读上方两格，再读下方全宽格。",
  "comic.readingTallLeftTwo": "阅读顺序：先读左侧直通格，再读右上，再读右下。",
  "comic.readingHeroPlusThree": "阅读顺序：先读上方大格，再由左至右读下方三小格。",
  "comic.readingFocusQuad": "阅读顺序：先读左上中格，再由上至下读右上两小格，最后读下方大格。",
  "comic.readingStaggerFour": "阅读顺序：左上、右上，再左下、右下。",
  "comic.readingDiagPairPlus": "阅读顺序：先读左上楔形格，再读右下楔形格，最后读下方全宽格。",
  "comic.readingHeroPlusFour": "阅读顺序：先读上方大格，再由左至右、上至下读下方四小格。",
  "comic.readingOrder": "阅读顺序：先左至右，再上至下（直向四格只由上至下）。",
  "comic.panelNumbers": "每格左上角标小格号 1 至 {{n}}。",
  "comic.panelLine": "第 {{i}}／{{n}} 格（{{label}}）：{{cap}}",
  "comic.panelEmpty": "第 {{i}}／{{n}} 格（{{label}}）：一个独立而连续的故事瞬间。",
  "comic.identity": "全页各格角色身份、服装、场景必须连贯。",
  "comic.finished": "这是一张完成的漫画页，不是无关照片拼贴，也不是界面草图。",
  "comic.layoutLead": "版式：{{layout}}",
  "comic.prevPage": "上一页漫画。保持角色身份、服装与场景连续，但不可复制上一页的分格。",
  "comic.ownPage": "本页既有成图。修订时可作身份／版式底图。",
  "comic.galleryRef": "角色或场景身份静图。纳入时须对准面容、服装与场景。",
  "comic.profileLine": "故事「{{title}}」漫画第 {{n}} 页。",
  "comic.styleBible": "故事风格说明：{{note}}",
  "comic.artMedium": "画风：{{art}}",
  "comic.fallbackClose": "完成的印刷漫画页。粗白分隔。小格号。无水印、无应用界面、无相册拼贴。",
  "comic.hardRules": "生成铁则",
  "comic.introTask": "图生影片：以故事「{{title}}」第 {{n}} 页完成漫画页（刚好 {{count}} 格）拍一段短片。身份、服装、版式必须锁定附图。",
  "comic.introLock": "锁定：面容、服装、场景、分隔与格号必须与成图一致。禁止换成另一页或另一人。",
  "comic.introLayout": "保持此页版式：{{layout}}",
  "comic.introCamera": "运镜：慢推近，或依阅读序轻轻扫过各格。只可有纸张／印刷感微动。禁止硬切成另一版式。",
  "comic.introClose": "无水印、无界面边框；除页上已画的对白外，勿再叠字幕。",
  "comic.dramaStillLock": "身份、服装、场景锁定附图的漫画页成图，但要当真人短剧镜头拍，不是在印刷格上扫过去。",
  "comic.dramaCamera": "运镜与表演：短剧节奏、表演清楚、口型跟分格对白。有上一页静图时须画面连续。",
  "comic.formatLockTall": "开本锁定：整页必须为竖向 9:16 漫画页，禁止横向宽银幕构图。",
  "comic.formatLockSquare": "开本锁定：整页必须为方形 1:1 漫画页。",
  "comic.formatLockWide": "开本锁定：整页必须为横向 16:9 漫画页。",
  "art.photoCinematic": "必须媒介：真人写实电影静帧。真实镜头质感、自然材质、电影调色，可有轻微胶片颗粒。必须像照片或电影画面。禁止：动画、赛璐璐、平面插画、卡通勾线、黏土、塑料计算机图像。",
  "art.photoPortrait": "必须媒介：写实棚拍肖像摄影。柔光箱光线、商业头像清晰度、真实镜头虚化。必须是照片。禁止：动画、漫画墨线、立体玩具渲染、平涂赛璐璐。",
  "art.photoDocumentary": "必须媒介：写实纪实照片。现场自然光、诚实质感、低华丽感。必须像真机实拍。禁止：动画、风格化计算机图像、插画。",
  "art.cgiFilm": "必须媒介：电影级立体计算机图像角色渲染。物理材质、光线追踪高光、轮廓清楚。必须是立体渲染，不是真照片，也不是平面动画。禁止：真人摄影、动画线稿、平涂漫画墨线。",
  "art.cgiStylized": "必须媒介：风格化高质量立体（长片动画计算机图像）。圆润可读形体、柔和物理材质、表情化比例。必须是立体计算机图像。禁止：写实真人、平面动画赛璐璐、潦草漫画。",
  "art.cgiClay": "必须媒介：立体黏土／雕塑角色。柔和哑光黏土、雕塑形体、定格灯光。必须读成黏土雕塑。禁止：写实皮肤照片、动画赛璐璐、墨线漫画。",
  "art.animeModern": "必须媒介：现代日系电视动画。干净数字线稿、柔和赛璐璐、动画眼与发束、平涂或渐变。整张必须是平面动画。禁止：写实摄影、真实毛孔、立体渲染、纯西式漫画墨线、油画。",
  "art.animeShonen": "必须媒介：少年向动画主视觉。粗线、高反差赛璐璐、锐利动画眼、动态剪影。必须是少年向平面动画。禁止：写实照片、立体计算机图像、纯柔和水彩。",
  "art.animeShoujo": "必须媒介：少女向动画。细线、柔和渐变、明亮动画眼、温柔色调。必须是少女向动画。禁止：写实照片、硬立体渲染、粗砺漫画墨线。",
  "art.animeGekiga": "必须媒介：剧画／写实系平面动画。成熟线质、克制色盘，仍清楚是平面动画。禁止：真人照片、Q 版、纯立体计算机图像。",
  "art.animeChibi": "必须媒介：Q 版／超变形动画。头大身小、可爱简化五官、干净平涂。必须是 Q 版动画。禁止：写实比例、写实立体、细致真人。",
  "art.donghua": "必须媒介：国漫角色主视觉。服装细节精细、轮廓优雅、高质量平面或二点五维动画感。必须读成国漫，不是好莱坞照片。禁止：写实真人、纯西式报纸漫画。",
  "art.manhwa": "必须媒介：韩漫／条漫全彩。柔和数字上色、干净轮廓、光泽头发。必须是韩漫平面。禁止：写实照片、黏土立体、纯美式英雄墨线。",
  "art.comicWestern": "必须媒介：西式漫画。肯定墨线、平涂或有限度赛璐璐色、图形化形状、设定稿漫画风格。必须是漫画插画。禁止：写实照片、纯日系大眼、黏土渲染。",
  "art.conceptGame": "必须媒介：3A 游戏角色原画。上色设定稿、剪影清楚、制作级概念品质。必须像原画，不是游戏截图，也不是真人照片。禁止：纯写实肖像照片、纯 Q 版动画。",
  "art.illustrationSoft": "必须媒介：柔和数字插画。轻柔笔触、绘本式完成度、角色设计连贯。必须是手绘插画。禁止：写实相机照片、硬动画赛璐璐、黏土立体。",
  "mediaGen.polishTask": "任务：{{hint}}",
  "mediaGen.polishKind": "种类：{{kind}}",
  "mediaGen.polishMaterials": "—— 材料 ——",
  "mediaGen.polishEndMaterials": "—— 材料完 ——",
  "mediaGen.polishRef": "参考图{{n}} — {{title}}",
  "mediaGen.videoTaskHint": "由关键帧写专业图生影片导演词（{{kind}}）。含镜头、表演、节奏；锁定关键帧静图。",
  "mediaGen.directorFallbackCam": "镜头运动与表演清楚；对白口型跟着脚本；无字幕、无浮水印。",
  "charIntro.task": "图生影片：以参考图中的同一人物，拍一段短剧选角用「自我介绍」短片。",
  "charIntro.identityLock": "身份锁定：脸、发型、体型、年龄感、服装与颜色必须与参考静帧一致，不可换成另一个人。",
  "charIntro.personality": "性格／气场：{{personality}}。",
  "charIntro.backstory": "背景要点：{{backstory}}。",
  "charIntro.relationships": "关是要点：{{relationships}}。",
  "charIntro.soul": "Soul 摘要（表演来源）：{{soul}}",
  "charIntro.performance": "表演：轻微推近或手持晃动；角色望向镜头或略偏镜头；{{manner}}。",
  "charIntro.speech": "对白：嘴唇自然开合像在简短自我介绍；声线：{{voice}}。",
  "charIntro.beat": "动作节奏：自然站定 → 微笑或轻点头 → 简短介绍手势（可空手）→ 定格。",
  "charIntro.lighting": "光线与静帧一致；无字幕、无标志、无其他人入镜。",
  "sceneIntro.task": "图生影片：以参考静帧中的同一场地，拍一段短剧用「场景介绍／建立镜头」短片。",
  "sceneIntro.spaceLock": "空间锁定：建筑、材质、招牌、格局与色彩语言必须与参考静帧一致，不可换成另一个地方。",
  "sceneIntro.name": "地点名称：{{name}}。",
  "sceneIntro.place": "场地描述：{{place}}。",
  "sceneIntro.spaceType": "空间类型：{{type}}。",
  "sceneIntro.time": "时段：{{time}}。",
  "sceneIntro.weather": "天气：{{weather}}。",
  "sceneIntro.moodLight": "气氛：{{mood}}。灯光：{{lighting}}。",
  "sceneIntro.palette": "色盘：{{palette}}。",
  "sceneIntro.setDressing": "陈设：{{set}}。",
  "sceneIntro.tags": "视觉标签：{{tags}}。",
  "sceneIntro.art": "艺术风格：{{art}}。",
  "sceneIntro.ambient": "环境氛围（无 UI 字幕）：{{sound}}。",
  "sceneIntro.scriptCue": "本场提示（只作气氛，勿新增角色脸，除非静帧已有）：{{cue}}。",
  "sceneIntro.camera": "运镜：{{camera}}；连续轻微动态。除非材料已有，否则勿新增路人脸、标志、字幕。",
  "sceneIntro.beat": "动作节奏：建立镜头定场 → 环境微动（光影、天气粒子、已有的布料／树影）→ 定格。",
  "propIntro.task": "图生影片：以参考静帧中的同一道具，拍一段短剧画面连续用「道具介绍／主视觉」短片。",
  "propIntro.objectLock": "物件锁定：轮廓、材质、颜色、刻字／纹样、旧损与比例必须与参考图一致，不可换成另一件。",
  "propIntro.name": "道具名称：{{name}}。",
  "propIntro.look": "外观描述：{{look}}。",
  "propIntro.material": "材质：{{material}}。",
  "propIntro.size": "尺寸笔记：{{size}}。",
  "propIntro.condition": "状态／旧损：{{condition}}。",
  "propIntro.tags": "视觉标签：{{tags}}。",
  "propIntro.art": "艺术风格：{{art}}。",
  "propIntro.camera": "运镜：干净桌面／主视觉台，轻微环绕或慢推近；光线与静帧一致。",
  "propIntro.beat": "动作节奏：主视觉定格 → 微光泽／微旋转或材质闪烁（若图中已有）→ 定格。",
  "propIntro.noHands": "除非静帧已有，否则勿加手、角色脸、字幕、浮水印或额外道具。",
  "costumeIntro.task": "图生影片：以参考静帧中的同一戏服造型，拍一段短剧戏服库用「造型介绍」短片。",
  "costumeIntro.wardrobeLock": "服装锁定：轮廓、布料、颜色、层次、配件与旧损必须与参考图一致，不可换成另一套。",
  "costumeIntro.identityOrProduct": "若静帧有人：锁定脸与体型，布料可轻微摆动；若为人台／平铺：保持产品构图。",
  "costumeIntro.name": "造型名称：{{name}}。",
  "costumeIntro.desc": "戏服描述：{{look}}。",
  "costumeIntro.art": "艺术风格：{{art}}。",
  "costumeIntro.camera": "运镜：轻微推近或慢环绕；光线与静帧一致。",
  "costumeIntro.beat": "动作节奏：定格 → 布料垂坠／袖口微动／五金反光 → 定格。",
  "costumeIntro.forbid": "勿新增角色脸、字幕、标志 或色情姿势。",
  "costumeIntro.fallbackName": "造型",
  "actionIntro.lead": "短剧动作示范片：「{{name}}」。",
  "actionIntro.intention": "意图：{{intention}}",
  "actionIntro.body": "肢体节奏：{{body}}",
  "actionIntro.camera": "镜头：{{camera}}",
  "actionIntro.closing": "动作连贯流畅，无字幕水印，紧跟关键帧静图。",
  "sceneIntroPolish.task": "任务：场景介绍／建立镜头短片（图生影片）。",
  "sceneIntroPolish.hasRef": "参考场景静图会交予影片 API——必须锁定该图空间身份。",
  "sceneIntroPolish.noRef": "本文无静图路径；仍须锁定地点圣经描述。",
  "sceneIntroPolish.dossier": "场景文件：",
  "sceneIntroPolish.scriptCue": "剧本提示（只作气氛）：\n{{script}}",
  "sceneIntroPolish.emptySet": "空镜为主；除非静帧已有，否则勿新增角色脸。无字幕、标志。",
  "propIntroPolish.task": "任务：道具主视觉介绍短片（图生影片）。",
  "propIntroPolish.hasRef": "参考道具静图会交予影片 API——必须锁定该图物件身份。",
  "propIntroPolish.noRef": "本文无静图路径；仍须锁定道具文件描述。",
  "propIntroPolish.dossier": "道具文件：",
  "propIntroPolish.noHands": "除非静帧已有，否则勿新增手或角色脸。无字幕、标志。",
  "costumeIntroPolish.task": "任务：戏服／造型介绍短片（图生影片）。",
  "costumeIntroPolish.hasRef": "参考静图会交予影片 API——有人则锁定身份＋服装；人台／平铺则锁定服装轮廓与材质。",
  "costumeIntroPolish.noRef": "本文无静图路径；仍须锁定戏服描述。",
  "costumeIntroPolish.dossier": "戏服文件：",
  "costumeIntroPolish.fabric": "布料垂坠／微动即可；勿新增角色脸；无字幕、标志。",
  "actionIntroPolish.task": "任务：动作指导介绍短片（图生影片）。",
  "actionIntroPolish.hasRef": "参考静图已附——表演身份锁定该帧。",
  "actionIntroPolish.templateKeepRules": "模板草稿（请改进；生成铁则 置于最尾）：",
  "cover.posterLead": "专业短剧海报／主视觉（16:9 静帧）。不是 UI 模型。无文字、标志、浮水印、标题字幕。",
  "cover.titleMood": "故事标题（只取气氛，画面勿写出文字）：{{title}}。",
  "cover.styleBible": "风格备注：{{style}}",
  "cover.extraDir": "额外方向：{{idea}}",
  "cover.establishing": "适合用作片库封面的情绪建立镜头；强烈剪影、可读气氛。",
  "cover.medium": "依艺术风格 medium 出图；构图清晰。",
  "cover.editPrefix": "图像编辑：以新构图创作短剧海报。保留主体身份／气氛（如有）。",
  "cover.label": "故事封面",
  "costumeFill.system": "你是影视造型指导。只回复紧凑 JSON：{\"name\":\"短名称\",\"description\":\"完整戏服描述（分层、布料、颜色、配饰；无品牌标志）\",\"artStyle\":\"可选风格 id 或空字串\",\"hardRules\":\"3–8 句必须／禁止\"} 每个键必须是 JSON 字串（不可 null／阵列）。不要 markdown。若有参考图，请按图如实描述该造型，供短剧出图使用。",
  "costumeFill.idea": "构思：{{idea}}",
  "costumeFill.polish": "润饰以下戏服草稿。",
  "costumeFill.required": "必填键：name, description, artStyle, hardRules。缺键无效。",
  "costumeFill.fallbackName": "造型",
  "segment.entireStory": "全剧（所有场次）",
  "segment.noStory": "未选故事（仅角色资料）",
  "vision.inventFromImage": "请根据附上的参考图，完整填写{{kind}}资料。",
  "vision.polishAll": "全面润饰并合并所有栏位",
  "story.untitled": "未命名短剧",
  "action.castIdentityNote": "已附 {{count}} 张参考素材（角色／道具等）：每格人物身份须与参考素材一致。",
  "tpl.system.polishOnly": "配方「只润饰」：保持核心身份与世界。只润饰措辞。不要发明时代、天气、职业、地点或样本世界。不要发明对白语言。不要把预设铁则写入档。",
  "tpl.system.fillBlanks": "配方「只填空白」：只补空栏。已填栏位不要改写。不要发明新世界。",
  "tpl.system.invent": "配方「自由创作」：用户授权按 idea 自由补齐可拍细节，必填栏要齐。仍然不要引入 示范样本或本次未暗示的世界。",
  "tpl.system.fromStory": "配方「从故事建议」：只用本次请求已写出的标题／风格／选角／场景做画面连续。冲突时以用户 idea 为准。",
  "tpl.system.followAsset": "配方「跟资产／故事」：跟已提供的风格与铁则。除非材料有写，不要强加电影感、空镜或 6–10 秒。片长跟 clip 实际秒数。",
  "tpl.system.cinematicLock": "配方「电影感＋防幻觉」：电影短剧感；场地空镜优先；无水印、标志、多余脸；人类恰好两手两臂两腿（非人除外）。",
  "tpl.system.identityLock": "配方「锁身份」：脸／体／服装／场地／道具必须锁定附图。不要换成另一人、另一地或另一物。",
  "tpl.system.restyle": "配方「可改造型」：保持同一角色身份。服装、场地陈设、时代可按用户要求改。不要换成另一个人。",
  "pipeline.character.system": "你为短剧 AI 影片润饰角色圣经。每位角色 3–5 行：外形、声线、动机、招牌动作。只用本次请求已有事实。",
  "pipeline.scene.system": "你把短剧场景扩成视觉节拍表。每拍跟材料里的实际片长，不要假定 6–10 秒。只用已提供场景。",
  "pipeline.props.system": "你为短剧润饰道具连续性。记颜色、尺寸、出场时机。名单以外不要发明道具。",
  "pipeline.script.system": "你是专业短剧编剧。每场写一段适合 AI 影片的紧凑剧本。用故事实际片长，不要硬加 10 秒上限。每场格式：\n### SCENE <number> | id=<id>\n<script body>",
  "pipeline.script.noScenes": "（无场景 — 不要发明地点）",
  "keyArt.task": "故事「{{title}}」第 {{n}} 张剧照。一张完成的宣传／剧照，不是漫画分格，不要格号，不要应用界面。",
  "keyArt.lockCover": "封面海报：横向故事卡关键视觉。预留安静的标题安全区。面容可辨。不要自制商标或假演职员表。",
  "keyArt.lockPoster": "竖幅海报：一张竖向单张。主体在手机画面也清楚。画面内不要再放其他海报。",
  "keyArt.lockStill": "剧照：一格电影感定格，像从短剧抽出。表演自然、空间真实。不是拼贴。",
  "keyArt.lockPromo": "宣传图：角色与世界同框的市场用关键视觉。轮廓清楚，一种情绪。不是样片拼板。",
  "keyArt.lockSocial": "社交竖图：竖向 9:16 预告画面。主体够大。预留字幕边距。",
  "keyArt.lockHeadshot": "主角大头：一张正脸充满画面，面貌必须与参考图一致。可带肩。不要其他人。",
  "keyArt.lockBust": "半身宣传：胸上肖像，戏服领可见，望向镜头。",
  "keyArt.lockGroup": "群像：所有已点名角色同框，同一世界、同一光线。不要漏脸或换脸。",
  "keyArt.formatLockTall": "开本锁定：整张必须是竖向 9:16。不要横向宽银幕构图。",
  "keyArt.formatLockSquare": "开本锁定：整张必须是方形 1:1。",
  "keyArt.formatLockWide": "开本锁定：整张必须是横向 16:9。",
  "keyArt.methodFreshLock": "出图方式：全新生成。参考图只用来锁定身份。不要沿用旧稿像素构图。",
  "keyArt.methodEditLock": "出图方式：改已附上的本张成图。除非指示要求，否则保留构图。",
  "keyArt.methodIdentityLock": "出图方式：面貌锁定参考角色。姿势、裁切与服装可以改变。",
  "keyArt.methodContinueLock": "出图方式：延续上一张。同一批人、同一场景，同一场拍摄的下一拍。",
  "keyArt.briefLine": "拍摄指示：{{brief}}",
  "keyArt.beatLine": "绑定分镜：{{beat}}",
  "keyArt.close": "完成的 {{aspect}} 静图。不要水印、不要界面边框、不要额外字幕。",
}
