import type { PromptCopyTable } from './keys'

export const zhCnPromptCopy: PromptCopyTable = {
  "speechLock.named": "SPEECH LOCK · 角色「{{who}}」：可听语音和口型必须只用{{primaryName}}（{{primary}}）。禁止改说{{forbid}}或其他语言。每段都要同一种口白。不要翻译对白。",
  "speechLock.unnamed": "SPEECH LOCK · 出场角色：可听语音和口型必须只用{{primaryName}}（{{primary}}）。禁止改说{{forbid}}或其他语言。每段都要同一种口白。不要翻译对白。",
  "speechLock.namedMulti": "SPEECH LOCK · 角色「{{who}}」：可听语音和口型必须用{{primaryName}}（{{primary}}）。只有剧本该句已经是以下语言才可以讲第二种：{{extras}}。禁止第三种语言。禁止每段转换。禁止改说{{forbid}}。不要翻译对白。",
  "speechLock.unnamedMulti": "SPEECH LOCK · 出场角色：可听语音和口型必须用{{primaryName}}（{{primary}}）。只有剧本该句已经是以下语言才可以讲第二种：{{extras}}。禁止第三种语言。禁止每段转换。禁止改说{{forbid}}。不要翻译对白。",
  "storyBeats.system": "你為短劇時間軸撰寫「劇情段落」——每一段 = 一小段 AI 影片的完整拍攝腳本，而非一句對白。\n每段必須有豐富表演內容：心情、氣氛、動作、表情、可選鏡頭／聲效，以及 0 至多句口白（常見 1–4 句）。\n只回傳 JSON 陣列（不要代碼塊）。每項形狀：\n{\"characterName\":\"…\",\"characterNames\":[\"…\"],\"sceneHint\":\"…\",\"propName\":\"…\",\"mood\":\"…\",\"atmosphere\":\"…\",\"camera\":\"…\",\"sfx\":\"…\",\"units\":[{\"type\":\"action\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"expression\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"dialogue\",\"who\":\"…\",\"line\":\"…\",\"tone\":\"…\",\"parenthetical\":\"…\"},{\"type\":\"note\",\"text\":\"…\"}]}\n規則：\n- dialogue.line 只寫角色講出口的話，不要把動作寫進口白。\n- 肢體動作放 action；表情微表演放 expression；語氣放 tone／parenthetical。\n- 一段可有多句對白（對話回合或自語）。\n- 允許純動作段（無對白）。\n- 寫 4–8 段。角色名必須用提供名單。\n- 要有衝突、可視動作、可拍細節。\n- 忠於已提供的標題、風格、選角與場景；不足就在同一世界內自由補齊。\n- 口白：dialogue.line 必須用該角色主語言寫（見角色名單）。禁止段與段轉語言。除非角色名單寫明，否則不要改寫成其他語言。",
  "storyBeats.userLead": "生成完整「短片脚本」段落：使用下方全部选角、场景、道具、风格与构想。",
  "storyBeats.eachBeat": "每段要有心情、气氛、动作／表情，以及可选的多句对白。",
  "storyBeats.story": "故事：{{title}}",
  "storyBeats.style": "风格：{{style}}",
  "storyBeats.userDir": "用户指示：{{idea}}",
  "storyBeats.cast": "角色：",
  "storyBeats.scenes": "场景：",
  "storyBeats.props": "道具：{{props}}",
  "storyBeats.returnJson": "只回传段落 JSON 数组。",
  "storyBeats.noCast": "（无角色）",
  "storyBeats.noScenes": "（无场景 — sceneHint 可写地点）",
  "storyBeats.none": "（无）",
  "videoPolish.system": "你为短劇 AI 圖生影片模型撰寫「一條」最終 image-to-video 導演提示詞。\n只回傳提示詞正文——不要 markdown 代碼塊、標題或解釋。\n規则：\n- 提示詞全文用用户介面語言書寫；角色姓名与口白語言要求须清楚標示。\n- 人物靜圖：IDENTITY LOCK（臉、髮、體型、服裝、顏色）。场景靜幀：SPACE LOCK（建築、材質、格局、招牌、色盤）——空鏡为主，勿新增角色臉。\n- 凡已提供且影響外形、動作、口白、氣氛或场地的人設／soul／段落／地點資料均须用上；空白欄位可略。\n- 只按材料与 seed 補齊可拍細節；勿引入固定樣本世界、Demo 故事、或材料／seed 未出現的事實。\n- 长篇 soul.md 须濃縮为可拍的表演与身份要點，不可整篇照貼。\n- 时长 6–10 秒；動作连貫；電影感；无字幕、logo、浮水印、无關路人。\n- 除非劇情要求，否则解剖結構正常（雙手雙腳）。\n- 多角色时保持每位主體一致；主焦點優先。\n- 若材料含 HARD RULES（生成鐵则），必须保留並放在輸出最尾（最高優先）。\n- SPEECH LOCK 必须保留：不得刪改或翻譯；語言代碼要寫成全名。每段跟角色主口語，禁止段与段轉語言，禁止翻譯對白。\n- 導演修訂可調整氣氛／動作，但不得違反 HARD RULES。",
  "videoPolish.hardRulesKeep": "HARD RULES／生成铁则（最高优先——保留每一行；[Character · 名] 等物件标签不可删）。必须将完整 HARD RULES 区块放在输出最末。不得削弱、删除或套错主体。",
  "clip.task": "任务：短剧时间轴片段（图生影片）。",
  "clip.hasRef": "可能附有参考静图——相关时锁定身份／场地连续性。",
  "clip.characters": "角色：",
  "clip.scene": "场景：",
  "clip.prop": "道具：",
  "clip.action": "动作指导：",
  "clip.beat": "段落／对白：",
  "clip.prev": "前一段连续性：",
  "clip.revision": "导演修订（必须遵守）：",
  "clip.templateDraft": "模板草稿（请改进）：",
  "intro.task": "任务：自我介绍选角短片（图生影片）。",
  "intro.hasRef": "参考静图会交予影片 API——必须锁定该图身份。",
  "intro.noRef": "本文无静图路径；仍须锁定人设外貌／戏服。",
  "intro.dossier": "角色档案：",
  "intro.templateDraft": "模板草稿（请改进；勿忽略档案）：",
  "common.durationAspect": "时长：{{seconds}} 秒。画面比例：{{aspect}}。",
  "common.templateDraft": "模板草稿：",
  "improve.mode": "改進模式：合併下方所有來源输出完整结果。除非用戶明確要求改身份，否则保持核心一致。表單稀疏時以額外上下文为準；用戶明確要求更改時以指示为準。",
  "improve.draftDefault": "目前表單欄位（已填內容）：",
  "improve.userRequest": "用戶改進要求（可留空 = 全面润饰並合併以上內容）：",
  "improve.emptyDefault": "（全面润饰：適合短劇／出圖／出片 continuity）",
  "improve.createDefault": "构想／方向：",
  "improve.explicitContext": "僅限本次请求明確附上的上下文（作 continuity；勿引入其他樣本世界；与 idea／表單衝突時以用戶为準）：",
  "improve.storyTitle": "故事標題：{{title}}",
  "improve.styleNote": "風格备註：{{style}}",
  "improve.closingDefault": "请立即输出完整结果。",
  "storyMeta.system": "你是短劇主創／視覺總監。根据故事標題与构想，寫簡潔可拍的風格备註（Style bible）以及出圖／出片「生成鐵则」。只回傳 JSON（不要代碼塊）：{\"styleNote\":\"2–5 句：氣氛、光線、鏡頭、色調、節奏\",\"hardRules\":\"3–8 句必须／禁止\"}。要具體、適合 AI 影片／出圖延續。用提供的標題、构想、现有風格／鐵则与上下文；不足就自由補齊一套连貫風格与鐵则。",
  "storyMeta.draftLabel": "目前故事欄位：",
  "storyMeta.createLabel": "故事构想／標題：",
  "storyMeta.emptyPolish": "（润饰視覺風格备註与生成鐵则，利于 AI 出片 continuity）",
  "storyMeta.closing": "只回傳 JSON：{\"styleNote\":\"…\",\"hardRules\":\"…\"}。兩个键都必填且非空。",
  "storyMeta.contextLabel": "故事上下文（角色／场景／道具）：",
  "character.system": "你是專業短劇角色設定師，專門为 AI 影片／短劇生成「可拍、可認、可一致」的角色圣经。用戶會給一段角色 idea。角色可以是人類、動物、鬼靈、魔物、機械、虛擬形象或其他設計體——依 idea 而定，勿強行寫成人類。只输出一个 JSON 物件。spokenLanguages：BCP-47 代碼阵列，例如 [\"yue\",\"en\"]。非語言角色用 []。避免空泛形容；用可拍攝的細節。同一角色必须視覺一致。",
  "character.draftLabel": "目前 Profile 表單欄位（已填內容）：",
  "character.soulLabel": "已连结 soul.md／角色圣经（主要身份与性格依据）：",
  "character.createLabel": "角色 idea：",
  "character.emptyPolish": "（全面润饰：將 soul 与表單合併進完整 Profile）",
  "character.closing": "请立即输出完整 JSON。必填键：{{keys}}。visualTags 为逗號分隔字串（禁止標籤阵列）；spokenLanguages 可以是代碼阵列。",
  "scene.system": "你是短劇场景／场景空間設計師，服務 AI 影片 continuity。请输出可拍的地點圣经 + 本场可演劇本片段。只回傳一个 JSON 物件。title＝短地名；description＝建築、物料、地標；script＝本场對白／動作／鏡頭。",
  "scene.draftLabel": "目前场景表單欄位（已填內容）：",
  "scene.charsLabel": "故事角色：",
  "scene.propsLabel": "故事道具：",
  "scene.priorLabel": "既有场景（continuity）：",
  "scene.createLabel": "场景 idea：",
  "scene.emptyPolish": "（全面润饰地點与本场劇本，利于出片 continuity）",
  "scene.closing": "请立即输出完整 JSON。必填键：{{keys}}。缺键無效。visualTags 必须是逗號分隔字串，禁止阵列。",
  "prop.system": "你是短劇道具設計師，服務 AI 影片 continuity。只回傳一个 JSON。description：可画細節；material／sizeNotes／condition 具體。",
  "prop.draftLabel": "目前道具表單欄位（已填內容）：",
  "prop.createLabel": "道具 idea：",
  "prop.emptyPolish": "（全面润饰道具外觀，利于出片 continuity）",
  "prop.closing": "请立即输出完整 JSON。必填键：{{keys}}。缺键無效。visualTags 必须是逗號分隔字串，禁止阵列。",
  "prop.fallbackName": "道具",
  "action.system": "你是短劇動作指導。只输出有效 JSON，描述一項可拍攝的動作指導。要具體：身體部位、節奏、力度、道具路徑、走位。不要 markdown。",
  "action.storyContext": "故事脈絡（可選）：{{title}}",
  "action.styleNote": "風格备註：{{style}}",
  "action.existingDraft": "现有草稿（请润饰補全）：",
  "action.userIdea": "用戶构想：{{idea}}",
  "action.closing": "只回傳 JSON。必填键：{{keys}}。visualTags 为逗號分隔字串，禁止阵列。",
  "profile.mustEveryKey": "必须输出列表中的每一个键：{{keys}}。",
  "profile.valuesAreStrings": "每个值必须是 JSON 字串（不可 null、不可用 JSON 阵列）。真的不知道才可空字串。",
  "profile.visualTagsRule": "visualTags：用用戶介面語言的單一逗號分隔字串——禁止 JSON 阵列。",
  "profile.fillConcrete": "各键请盡量填具體細節，利于短劇 continuity。",
  "common.rules": "規则：",
  "common.none": "（无）",
  "intro.soul": "soul.md（作为表演／身份完整來源）：\n{{soul}}",
  "intro.matchBible": "（跟从角色人設语言）",
  "invent.sources": "依据來源（優先序）：（1）用戶 idea／指示，（2）已填表單，（3）僅當「本次 prompt 已寫出」的額外上下文（soul、选角、故事區塊等），（4）附上的參考圖。",
  "invent.create": "創作模式（表單空白／極少）：按 idea／圖自由創作，補齊可拍攝的關键欄位，內容须与用戶构想相關——勿留空必填键。",
  "invent.improve": "改進模式（表單已有內容）：润饰並補齊空白欄，与已填內容一致；除非用戶要求，否则勿改核心身份。",
  "invent.noImport": "不得从「本次 prompt 未出现」的來源引入身份、劇情、天气、職業、地點、时代或風格（禁止 active 故事、Demo 樣本、App 預設世界觀）。",
  "invent.storyBlock": "若下方明確附有故事／風格區塊：僅作 continuity；不可覆蓋用戶明確 idea。",
  "character.keysLead": "只输出一个 JSON 物件（不要 markdown），键名必须是：{{keys}}",
  "character.ruleSpoken": "spokenLanguages：角色使用的语言，JSON 字串阵列（可多选），BCP-47／ISO 代码，例如 [\"yue\",\"en\"]。非语言角色用 []。",
  "character.ruleIdentity": "同一角色必须視覺一致，方便之後多角度參考圖与影片生成。",
  "character.fallbackPersonality": "溫暖清晰、有个性",
  "character.fallbackManner": "自然微动作",
  "character.fallbackVoice": "清晰声線",
  "scene.keysLead": "只回傳一个 JSON 物件（不要 markdown），键名：{{keys}}",
  "scene.suggestLead": "为故事「{{title}}」建議第 {{n}} 个可用场景（场地／環境設定）。",
  "scene.suggestPlotFocus": "劇情焦點：{{label}}",
  "scene.suggestStyle": "風格：{{style}}",
  "scene.suggestExisting": "庫內／故事已有场地：{{titles}}",
  "scene.suggestChars": "角色（上下文）：",
  "scene.suggestProps": "道具（上下文）：",
  "scene.suggestSegment": "选定劇情段落詳情：",
  "scene.suggestBeats": "故事场次／段落：",
  "scene.suggestClosing": "回傳完整场景 JSON。请設計一个可重複使用的獨立场地（全域场景庫資產），须貼合选定劇情焦點，並与已有场地有所區別。",
  "scene.fallbackName": "场景",
  "scene.fallbackMood": "電影气氛",
  "scene.fallbackLighting": "与靜幀一致",
  "scene.fallbackCamera": "輕微建立鏡头推近或慢搖",
  "scene.ideaFromImage": "请根据附上的參考圖，完整填寫场景資料。",
  "scene.polishIdea": "全面润饰",
  "prop.keysLead": "只回傳一个 JSON，键名：{{keys}}",
  "action.fieldsLead": "欄位：{{keys}}。",
  "soul.system": "你为短劇／影視角色撰寫 production 用 soul.md（單檔 Markdown）。\n只输出完整 Markdown 文件（不要代码塊圍欄、不要解说）。\n结构（请用以下 ## 标题）：\n# {角色名}\n## 身份 Identity\n## 外貌 Appearance\n## 服裝与輪廓 Costume\n## 性格与声線 Personality & voice\n## 使用语言 Spoken languages\n## 小習慣 Mannerisms\n## 背景 Backstory\n## 關是 Relationships\n## 表演与对白風格\n## 一致性硬規则 Hard rules\n## 視覺标籤 Visual tags\n規则：\n- 短劇可拍、可辨認、可一致；細節须具體。\n- 依据：Profile 表單 + 现有 soul + 用戶指示。不足则自由補齊；勿用本次未提供的來源臆造。\n- 对白／配音必须尊重 profile 的 spokenLanguages。\n- 硬規则用 5–10 條 bullet，方便之後圖像／对白 AI 遵守。\n- 用用戶介面语言書寫（香港書面语優先，若介面是其他语言就跟介面）。\n- 可选開头 YAML frontmatter（name / tags），非必须。",
  "soul.improveMode": "改進模式：合併 Profile 表單 + 现有 soul，输出更新後完整 soul.md。除非要求改身份，否则保持核心一致。",
  "soul.createMode": "根据以下角色設定撰寫完整 soul.md（合理補齊空白；不要換成另一个人）：",
  "soul.profileFields": "Profile 表單欄位（已填內容）：",
  "soul.existing": "现有 soul.md（合併／改進；勿丟有用細節）：",
  "soul.userRequest": "用戶指示：{{request}}",
  "soul.extraContext": "本次一併提供的上下文（有用就用；仍以 profile 为準）：",
  "soul.returnOnly": "只输出完整 soul.md Markdown 正文。",
  "wardrobe.system": "你是短劇服裝与視覺風格顧問。根据角色与劇情，提出一套完整外裝方案。只回傳一个 JSON 物件（不要 markdown 圍欄）：{\"name\":\"短名稱\",\"costume\":\"詳細外裝描述（供出圖／影片）\",\"artStyle\":\"下列其一\",\"rationale\":\"一兩句理由\"} artStyle 必须是：{{styleIds}} costume 要具體：材質、顏色、輪廓、鞋履、配件。年齡表述须得體；禁止对未成年做性化描述。保留既有外貌身份，只設計服裝与風格。用角色欄位与已提供的劇情／故事上下文；不足就自由補一套连貫造型。",
  "wardrobe.improveMode": "改進／建議模式：使用下方全部角色欄位与劇情上下文。",
  "wardrobe.characterForm": "角色（完整表單）：",
  "wardrobe.soulExcerpt": "soul.md 摘要：\n{{soul}}",
  "wardrobe.userRequest": "用戶指示：{{request}}",
  "wardrobe.storyContext": "故事／製作上下文（有就用；勿另起一个世界）：",
  "wardrobe.style": "風格：{{style}}",
  "wardrobe.segment": "选定劇情段落：{{label}}",
  "wardrobe.sceneContext": "场景／段落／对白摘录：",
  "wardrobe.noScenes": "（尚无场景）",
  "wardrobe.proposeNew": "请提出一套符合劇情的新戲服（避免与已有造型重複）。",
  "fill.system": "你負責補齊短劇資產設定中「仍然空白」的欄位。\n只回傳一个 JSON 物件，且只能包含这些键：{{keys}}。\n每个值必须是非空 JSON 字串（不可 null、不可 JSON 阵列）。\n若含 visualTags：用用戶介面语言的逗號分隔字串（格式例：\"gold, necklace\"，勿照抄例子，须貼合本資產）——禁止阵列。\n只根据已有部分設定及參考圖補齊；勿另起未見于 partial／圖的劇情、地點或樣本世界。\n不要 markdown、不要解说。",
  "fill.userPartial": "已有部分設定（勿矛盾）：",
  "fill.userOnly": "只補齊这些空白键：{{keys}}。",
  "fill.userReturn": "只回傳含上述键的 JSON；每值为非空字串。",
  "imageGen.multiRef": "另有 {{n}} 張已选參考圖：主編輯底圖为第一張，其餘作身份一致輔助，勿換成另一物件／主體。",
  "residual.sceneLink": "第 {{n}} 场：{{short}}",
  "residual.beatSegment": "段落 {{n}} · {{who}}{{tail}}",
  "residual.unknown": "未指定",
  "residual.story": "故事",
  "beat.mood": "【心情】{{text}}",
  "beat.atmo": "【气氛】{{text}}",
  "beat.camera": "【鏡头】{{text}}",
  "beat.sfx": "【声效】{{text}}",
  "beat.action": "【动作】{{text}}",
  "beat.actionWho": "【动作｜{{who}}】{{text}}",
  "beat.expr": "【表情】{{text}}",
  "beat.exprWho": "【表情｜{{who}}】{{text}}",
  "beat.dialogue": "【对白｜{{who}}】{{body}}",
  "beat.dialogueTone": "【对白｜{{who}}｜{{tone}}】{{body}}",
  "beat.whoUnknown": "？",
  "beat.template": "【心情】緊繃、猶豫\n【气氛】門縫暖光；雨砸地\n【鏡头】中景，跟手推近\n【声效】雨、布料摩擦\n【动作｜角色名】摘下安全帽；盯門縫暖光；手伸進外套內袋\n【表情｜角色名】眉心緊鎖，呼吸一滯\n【对白｜角色名｜低声沙啞】又是落雨……\n【对白｜角色名｜自语】（停半拍）你……仲在度？",
  "vision.preamble": "已附上參考靜圖。请主要根据圖片填寫此{{what}}全部欄位；可结合构思／草稿润饰。",
  "vision.character": "角色（名稱、外貌、戲服、年齡、性別、标籤等）",
  "vision.scene": "场景（标题、描述、光影、气氛、佈景、标籤等）",
  "vision.prop": "道具（名稱、描述、材質、尺寸、狀态、标籤等）",
  "vision.action": "动作（名稱、说明、節奏、意圖、鏡头备註、标籤等）",
  "vision.costume": "戲服（名稱、完整造型描述）",
  "still.header": "SINGLE KEYFRAME STILL for short-drama video continuity（單格關键幀，不是多格板）。產出一張对应下方鏡头的電影感主画面。无文字、logo、浮水印、UI。清晰可製作。",
  "still.revision": "用戶改進要求（必须套用）：{{notes}}",
  "still.regenTask": "任務：修訂 image-to-video 導演提示詞，並保持可作靜幀 keyframe 簡報。",
  "still.userImprove": "用戶改進要求：\n{{notes}}",
  "still.currentPrompt": "目前專業提示詞：",
  "still.hardRules": "HARD RULES／生成鐵则（必须保留于输出最尾；不得刪除或削弱）：",
  "mediaGen.writeOne": "请撰寫「一條」最終短劇靜圖／多格指示圖生成 prompt。",
  "mediaGen.returnOnly": "只回傳 prompt 正文——不要 markdown 代码塊、标题或解釋。",
  "mediaGen.singleComposite": "输出描述「單一合成圖」（只 export 一張）。",
  "mediaGen.lockRefs": "附圖圖序与下方 Ref# 一致，须作視覺 ground truth。身份／戲服／场景／道具必须鎖定附圖，禁止換成另一人、另一店或另一物。",
  "mediaGen.videoSystem": "你是短劇 image-to-video 導演 prompt 撰寫者。",
  "mediaGen.videoMerge": "將材料合併为「一條」專業短片 video prompt。",
  "mediaGen.videoInclude": "须含：身份鎖定、鏡头運动、表演／对白、節奏、光影连續。",
  "mediaGen.videoFacts": "只用材料与 seed 中的事實；勿引入固定樣本世界或 Demo 故事。",
  "mediaGen.videoNoSwap": "有附圖时禁止換成另一演員、场景或道具。",
  "mediaGen.videoHardRules": "有 HARD RULES 则置于文末。",
  "mediaGen.imageSystem": "你是短劇靜圖／指示圖 prompt 導演。",
  "mediaGen.imageMergeStills": "將用戶勾选材料与附圖合併为「一條」出圖 prompt。",
  "mediaGen.imageMergeText": "將用戶勾选文字材料合併为「一條」出圖 prompt。",
  "mediaGen.imagePriority": "最高優先：附圖中的臉／服裝／场景／道具必须一致。",
  "mediaGen.imageNoSwap": "有角色／场景靜圖时，禁止換成无關沙龍店員或另一间店。",
  "mediaGen.imageFacts": "只用材料与 seed 中的事實；勿引入固定樣本世界或 Demo 故事。",
  "mediaGen.imageLayout": "若要求多格板，保留精確格數与分隔。",
  "mediaGen.imagePackage": "若有 LAYOUT／出圖方案區塊，最終 prompt 必须嚴格執行該 layout（格數、姿勢、构圖）。",
  "mediaGen.imageHardRules": "有 HARD RULES 则置于文末。",
  "mediaGen.directorFallback": "圖生影片：以这张關键幀做短劇片段。身份、戲服、场景、构圖须鎖定關键幀，由此画面開始动。",
  "mediaGen.directorFallbackCam": "鏡头運动与表演清楚；对白口型跟着腳本；无字幕、无浮水印。",
  "charIntro.task": "圖生影片：以參考圖中的同一人物，拍一段短劇选角用「自我介紹」短片。",
  "charIntro.identityLock": "身份鎖定：臉、髮型、體型、年齡感、服裝与顏色必须与參考靜幀一致，不可換成另一个人。",
  "charIntro.personality": "性格／气场：{{personality}}。",
  "charIntro.backstory": "背景要點：{{backstory}}。",
  "charIntro.relationships": "關是要點：{{relationships}}。",
  "charIntro.soul": "Soul 摘要（表演來源）：{{soul}}",
  "charIntro.performance": "表演：輕微推近或手持晃动；角色望向鏡头或略偏鏡头；{{manner}}。",
  "charIntro.speech": "口白：嘴唇自然开合像在簡短自我介紹；声線：{{voice}}。",
  "charIntro.beat": "动作節奏：自然站定 → 微笑或輕點头 → 簡短介紹手勢（可空手）→ 定格。",
  "charIntro.lighting": "光線与靜幀一致；无字幕、无 logo、无其他人入鏡。",
  "charIntro.duration": "適合 6–10 秒自我介紹短片。",
  "sceneIntro.task": "圖生影片：以參考靜幀中的同一场地，拍一段短劇用「场景介紹／建立鏡头」短片。",
  "sceneIntro.spaceLock": "空间鎖定：建築、材質、招牌、格局与色彩语言必须与參考靜幀一致，不可換成另一个地方。",
  "sceneIntro.name": "地點名稱：{{name}}。",
  "sceneIntro.place": "场地描述：{{place}}。",
  "sceneIntro.spaceType": "空间類型：{{type}}。",
  "sceneIntro.time": "时段：{{time}}。",
  "sceneIntro.weather": "天气：{{weather}}。",
  "sceneIntro.moodLight": "气氛：{{mood}}。灯光：{{lighting}}。",
  "sceneIntro.palette": "色盤：{{palette}}。",
  "sceneIntro.setDressing": "陳設：{{set}}。",
  "sceneIntro.tags": "視覺标籤：{{tags}}。",
  "sceneIntro.art": "藝术風格：{{art}}。",
  "sceneIntro.ambient": "環境氛圍（无 UI 字幕）：{{sound}}。",
  "sceneIntro.scriptCue": "本场提示（只作气氛，勿新增角色臉，除非靜幀已有）：{{cue}}。",
  "sceneIntro.camera": "運鏡：{{camera}}；连續輕微动态；空鏡为主——勿新增路人臉、logo、字幕。",
  "sceneIntro.beat": "动作節奏：建立鏡头定场 → 環境微动（光影、天气粒子、已有的布料／樹影）→ 定格。",
  "sceneIntro.duration": "適合 6–10 秒场景介紹短片。",
  "propIntro.task": "圖生影片：以參考靜幀中的同一道具，拍一段短劇 continuity 用「道具介紹／主視覺」短片。",
  "propIntro.objectLock": "物件鎖定：輪廓、材質、顏色、刻字／紋樣、舊損与比例必须与參考圖一致，不可換成另一件。",
  "propIntro.name": "道具名稱：{{name}}。",
  "propIntro.look": "外觀描述：{{look}}。",
  "propIntro.material": "材質：{{material}}。",
  "propIntro.size": "尺寸筆記：{{size}}。",
  "propIntro.condition": "狀态／舊損：{{condition}}。",
  "propIntro.tags": "視覺标籤：{{tags}}。",
  "propIntro.art": "藝术風格：{{art}}。",
  "propIntro.camera": "運鏡：乾淨桌面／主視覺台，輕微環繞或慢推近；光線与靜幀一致。",
  "propIntro.beat": "动作節奏：主視覺定格 → 微光澤／微旋轉或材質閃爍（若圖中已有）→ 定格。",
  "propIntro.noHands": "除非靜幀已有，否则勿加手、角色臉、字幕、浮水印或額外道具。",
  "propIntro.duration": "適合 6–10 秒道具介紹短片。",
  "costumeIntro.task": "圖生影片：以參考靜幀中的同一戲服造型，拍一段短劇戲服庫用「造型介紹」短片。",
  "costumeIntro.wardrobeLock": "服裝鎖定：輪廓、布料、顏色、層次、配件与舊損必须与參考圖一致，不可換成另一套。",
  "costumeIntro.identityOrProduct": "若靜幀有人：鎖定臉与體型，布料可輕微擺动；若为人台／平鋪：保持產品构圖。",
  "costumeIntro.name": "造型名稱：{{name}}。",
  "costumeIntro.desc": "戲服描述：{{look}}。",
  "costumeIntro.art": "藝术風格：{{art}}。",
  "costumeIntro.camera": "運鏡：輕微推近或慢環繞；光線与靜幀一致。",
  "costumeIntro.beat": "动作節奏：定格 → 布料垂墜／袖口微动／五金反光 → 定格。",
  "costumeIntro.forbid": "勿新增角色臉、字幕、logo 或色情姿勢。",
  "costumeIntro.duration": "適合 6–10 秒造型介紹短片。",
  "costumeIntro.fallbackName": "造型",
  "actionIntro.lead": "短劇动作示範片：「{{name}}」。",
  "actionIntro.intention": "意圖：{{intention}}",
  "actionIntro.body": "肢體節奏：{{body}}",
  "actionIntro.camera": "鏡头：{{camera}}",
  "actionIntro.closing": "动作连貫流暢，電影感，无字幕水印，緊跟關键幀靜圖。",
  "sceneIntroPolish.task": "任務：场景介紹／建立鏡头短片（圖生影片）。",
  "sceneIntroPolish.hasRef": "參考场景靜圖會交予影片 API——必须鎖定該圖空间身份。",
  "sceneIntroPolish.noRef": "本文无靜圖路徑；仍须鎖定地點圣经描述。",
  "sceneIntroPolish.dossier": "场景檔案：",
  "sceneIntroPolish.scriptCue": "劇本提示（只作气氛）：\n{{script}}",
  "sceneIntroPolish.emptySet": "空鏡为主；除非靜幀已有，否则勿新增角色臉。无字幕、logo。",
  "propIntroPolish.task": "任務：道具主視覺介紹短片（圖生影片）。",
  "propIntroPolish.hasRef": "參考道具靜圖會交予影片 API——必须鎖定該圖物件身份。",
  "propIntroPolish.noRef": "本文无靜圖路徑；仍须鎖定道具檔案描述。",
  "propIntroPolish.dossier": "道具檔案：",
  "propIntroPolish.noHands": "除非靜幀已有，否则勿新增手或角色臉。无字幕、logo。",
  "costumeIntroPolish.task": "任務：戲服／造型介紹短片（圖生影片）。",
  "costumeIntroPolish.hasRef": "參考靜圖會交予影片 API——有人则鎖定身份＋服裝；人台／平鋪则鎖定服裝輪廓与材質。",
  "costumeIntroPolish.noRef": "本文无靜圖路徑；仍须鎖定戲服描述。",
  "costumeIntroPolish.dossier": "戲服檔案：",
  "costumeIntroPolish.fabric": "布料垂墜／微动即可；勿新增角色臉；无字幕、logo。",
  "actionIntroPolish.task": "任務：动作指導介紹短片（圖生影片）。",
  "actionIntroPolish.hasRef": "參考靜圖已附——表演身份鎖定該幀。",
  "actionIntroPolish.templateKeepRules": "模板草稿（请改進；HARD RULES 置于最尾）：",
  "cover.posterLead": "PROFESSIONAL SHORT-DRAMA POSTER / KEY ART（16:9 電影感靜幀）。不是 UI 模型。无文字、logo、浮水印、标题字幕。",
  "cover.titleMood": "故事标题（只取气氛，画面勿寫出文字）：{{title}}。",
  "cover.styleBible": "風格备註：{{style}}",
  "cover.extraDir": "額外方向：{{idea}}",
  "cover.establishing": "適合用作片庫封面的情緒建立鏡头；強烈剪影、可讀气氛。",
  "cover.medium": "依藝术風格 medium 出圖；构圖清晰。",
  "cover.editPrefix": "IMAGE EDIT：以新构圖創作短劇海報。保留主體身份／气氛（如有）。",
  "cover.label": "故事封面",
  "costumeFill.system": "你是影視造型指導。只回覆緊湊 JSON：{\"name\":\"短名稱\",\"description\":\"完整戲服描述（分層、布料、顏色、配饰；无品牌 Logo）\",\"artStyle\":\"可选風格 id 或空字串\",\"hardRules\":\"3–8 句必须／禁止\"} 每个键必须是 JSON 字串（不可 null／阵列）。不要 markdown。若有參考圖，请按圖如實描述該造型，供短劇出圖使用。",
  "costumeFill.idea": "构思：{{idea}}",
  "costumeFill.polish": "润饰以下戲服草稿。",
  "costumeFill.required": "必填键：name, description, artStyle, hardRules。缺键无效。",
  "costumeFill.fallbackName": "造型",
  "segment.entireStory": "全劇（所有场次）",
  "segment.noStory": "未选故事（僅角色資料）",
  "vision.inventFromImage": "请根据附上的参考图，完整填写{{kind}}资料。",
  "vision.polishAll": "全面润饰并合并所有栏位",
  "story.untitled": "未命名短剧",
  "action.castIdentityNote": "已附 {{count}} 张参考素材（角色／道具等）：每格人物身份须与参考素材一致。"
}
