import type { PromptCopyTable } from './keys'

export const zhHkPromptCopy: PromptCopyTable = {
  "speechLock.named": "對白鎖定 · 角色「{{who}}」：可聽語音與口型必須只用{{primaryName}}（{{primary}}）。禁止改講{{forbid}}或其他語言。每段都要同一種對白語言。不要翻譯對白。",
  "speechLock.unnamed": "對白鎖定 · 出場角色：可聽語音與口型必須只用{{primaryName}}（{{primary}}）。禁止改講{{forbid}}或其他語言。每段都要同一種對白語言。不要翻譯對白。",
  "speechLock.namedMulti": "對白鎖定 · 角色「{{who}}」：可聽語音與口型必須用{{primaryName}}（{{primary}}）。只有腳本該句已經是以下語言才可以講第二種：{{extras}}。禁止第三種語言。禁止每段轉換。禁止改講{{forbid}}。不要翻譯對白。",
  "speechLock.unnamedMulti": "對白鎖定 · 出場角色：可聽語音與口型必須用{{primaryName}}（{{primary}}）。只有腳本該句已經是以下語言才可以講第二種：{{extras}}。禁止第三種語言。禁止每段轉換。禁止改講{{forbid}}。不要翻譯對白。",
  "hardRules.sealHeader": "生成鐵則（最高優先，必須遵守，覆蓋前文衝突）：",
  "hardRules.sealFooter": "若前文與生成鐵則衝突，以生成鐵則為準。",
  "hardRules.labelStory": "故事",
  "hardRules.labelCharacter": "角色",
  "hardRules.labelScene": "場景",
  "hardRules.labelProp": "道具",
  "hardRules.labelAction": "動作",
  "continuity.lockHeader": "畫面連續鎖定（短劇順序必須遵守）：",
  "continuity.hasImage": "附圖是第 {{n}} 段的結尾格。本段須由該畫面狀態接續，不可硬切到另一套佈景。",
  "continuity.noImage": "承接第 {{n}} 段（無靜圖——只按文字檔案對齊）。",
  "continuity.identity": "身份：同一人——臉、髮、體型比例、服裝顏色、配飾。不要改造型、不要改年齡。",
  "continuity.space": "空間：同一地點——建築、物料、格局、光線方向。僅在劇情需要時可有輕微時段變化。",
  "continuity.action": "動作：承接上一格的姿勢、視線與動向；不要硬切到另一套站位。",
  "continuity.prevContext": "上一段脈絡：{{snippet}}",
  "continuity.noText": "無字幕、無標誌、無浮水印。",
  "directorLabel.lock": "對白鎖定",
  "directorLabel.story": "故事：",
  "directorLabel.style": "風格：",
  "directorLabel.cast": "角色：",
  "directorLabel.location": "場景：",
  "directorLabel.prop": "道具：",
  "directorLabel.primaryChar": "主角色：",
  "directorLabel.mood": "心情：",
  "directorLabel.atmo": "氣氛：",
  "directorLabel.camera": "鏡頭：",
  "directorLabel.sfx": "聲效：",
  "directorLabel.action": "動作：",
  "directorLabel.expr": "表情：",
  "directorLabel.speech": "對白：",
  "directorLabel.notes": "導演備註：",
  "directorLabel.identity": "身份：",
  "directorLabel.space": "空間：",
  "directorLabel.ref": "參考圖",
  "directorLabel.beatN": "第 {{n}} 段 · ",
  "directorLabel.beatNsec": "第 {{n}} 段 · {{s}} 秒片段",
  "directorLabel.hardRules": "生成鐵則",
  "directorLabel.identityLock": "身份鎖定",
  "directorLabel.spaceLock": "空間鎖定",
  "storyBeats.system": "你為短劇時間軸撰寫「劇情段落」——每一段 = 一小段 AI 影片的完整拍攝腳本，而非一句對白。\n每段必須有豐富表演內容：心情、氣氛、動作、表情、可選鏡頭／聲效，以及 0 至多句對白（常見 1–4 句）。\n只回傳 JSON 陣列（不要代碼塊）。每項形狀：\n{\"characterName\":\"…\",\"characterNames\":[\"…\"],\"sceneHint\":\"…\",\"sceneHints\":[\"…\"],\"propName\":\"…\",\"propNames\":[\"…\"],\"actionName\":\"…\",\"actionNames\":[\"…\"],\"mood\":\"…\",\"atmosphere\":\"…\",\"camera\":\"…\",\"sfx\":\"…\",\"units\":[{\"type\":\"action\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"expression\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"dialogue\",\"who\":\"…\",\"line\":\"…\",\"tone\":\"…\",\"parenthetical\":\"…\"},{\"type\":\"note\",\"text\":\"…\"}]}\n規則：\n- dialogue.line 只寫角色講出口的話，不要把動作寫進對白。\n- 肢體動作放 action；表情微表演放 expression；語氣放 tone／parenthetical。\n- 一段可有多句對白（對話回合或自語）。\n- 允許純動作段（無對白）。\n- 禁止預設一章一段。按可拍短片拆：換場、跳時、新衝突、或一段 6–10 秒裝不下的動作／對白 → 另開一段。一章通常 1–3 段。總數不超過 {{maxBeats}} 段。\n- 列出本片段出現的全部名單內角色／場景／道具／動作（characterNames、sceneHints、propNames、actionNames）。上限：角色 4、場景 2、道具 4、動作 4。不要每樣只填一個。\n- 有肢體表演就必須填 actionNames，而且要用故事已選動作庫的原名。有肢體就不准留空；寧可從已選名單勾上，也不要一項都不填。\n- 每段 units 最多 4 項（1–2 個 action、0–1 個 expression、0–2 句 dialogue）。角色名必須用提供名單。正文要短，一次回完 JSON。\n- 要有衝突、可視動作、可拍細節。\n- 忠於已提供的標題、風格、選角與場景。不要擅自擴世界。\n- 對白：dialogue.line 必須用該角色主語言寫（見角色名單）。禁止段與段轉語言。除非角色名單寫明，否則不要改寫成其他語言。",
  "storyBeats.userLead": "生成完整「短片腳本」段落：使用下方全部選角、場景、道具、動作、風格與構想。",
  "storyBeats.eachBeat": "每段要有心情、氣氛、動作／表情，以及可選的多句對白。",
  "storyBeats.story": "故事：{{title}}",
  "storyBeats.style": "風格：{{style}}",
  "storyBeats.userDir": "用戶指示：{{idea}}",
  "storyBeats.cast": "角色：",
  "storyBeats.scenes": "場景：",
  "storyBeats.props": "道具：{{props}}",
  "storyBeats.actions": "動作（肢體）：{{actions}}",
  "storyBeats.returnJson": "只回傳段落 JSON 陣列。",
  "storyBeats.noCast": "（無角色）",
  "storyBeats.noScenes": "（無場景 — sceneHint 可寫地點，勿另起世界）",
  "storyBeats.none": "（無）",
  "storyBeats.chapters": "故事章節（拆拍主來源——請把以下章節拆成可拍段落）：",
  "storyBeats.chapterBlock": "第 {{n}} 章 · {{title}}\n{{body}}",
  "storyChapters.system": "你為短劇撰寫「章節」——這是故事靈魂（可讀敘事），不是分鏡腳本。\n每章約 {{words}} 字散文：衝突、地點、誰在場、想要什麼、局面如何改變。\n只回傳 JSON 陣列（不要 markdown）。每項：{\"title\":\"…\",\"body\":\"…\"}.\n固定寫 {{count}} 章。忠於標題、風格聖經、生成鐵則與用戶構想。不要另起世界。正文要短，一次回完 JSON。",
  "storyChapters.userLead": "把故事寫成有序章節（章節／treatment）。之後會用這些章節生成角色、場景、道具、動作，再拆成拍攝段落。",
  "storyChapters.story": "故事：{{title}}",
  "storyChapters.style": "風格聖經：{{style}}",
  "storyChapters.rules": "生成鐵則：{{rules}}",
  "storyChapters.userDir": "用戶構想：{{idea}}",
  "storyChapters.returnJson": "只回傳 JSON 陣列：[{\"title\":\"…\",\"body\":\"…\"}, …]",
  "storyChapters.polishSystem": "你潤飾短劇的「一章」。保留情節事實、人名與結局，寫得更可拍（具體地點、身體、道具、衝突）。只回傳 JSON：{\"title\":\"…\",\"body\":\"…\"}。",
  "storyChapters.polishUser": "故事：{{story}}\n現有標題：{{title}}\n現有正文：\n{{body}}\n可選指示：{{idea}}\n回傳潤飾後 JSON {\"title\",\"body\"}。",
  "storyCastFromChapters.system": "你從故事章節抽出製作聖經：角色、場景／地點、關鍵道具、標誌性動作。\n只回傳 JSON（不要 markdown）：\n{\"characters\":[{\"name\":\"\",\"description\":\"\",\"appearance\":\"\",\"personality\":\"\",\"costume\":\"\",\"roleNote\":\"\"}],\"scenes\":[{\"title\":\"\",\"description\":\"\",\"locationType\":\"\",\"timeOfDay\":\"\",\"mood\":\"\"}],\"props\":[{\"name\":\"\",\"description\":\"\"}],\"actions\":[{\"name\":\"\",\"description\":\"\",\"motionNotes\":\"\",\"intention\":\"\"}]}\n規則：只抽取章節裡出現的實體。若已列出現有名字就沿用。人物／地點／物件／動作要可區分。視覺細節要具體。允許空陣列。禁止一章一角色／一場景／一道具／一動作。一章可以有兩個角色、幾個地點、多件道具、多個肢體動作。只抽實際出現、可區分的實體。例如：對話兩人 → 兩個 characters；巷口再入祠堂 → 兩個 scenes。不要為了湊數而發明。",
  "storyCastFromChapters.userLead": "抽出章節裡每一個出現過的角色、場景、道具、動作——不要一章一套。",
  "storyCastFromChapters.story": "故事：{{title}}",
  "storyCastFromChapters.style": "風格：{{style}}",
  "storyCastFromChapters.chapters": "章節：\n{{chapters}}",
  "storyCastFromChapters.existingCast": "本故事已有（請沿用這些名字）：{{names}}",
  "storyCastFromChapters.returnJson": "只回傳 JSON 物件。",
  "videoPolish.system": "你為短劇 AI 圖生影片模型撰寫「一條」最終導演提示詞。\n只回傳提示詞正文——不要 markdown 代碼塊、標題或解釋。\n規則：\n- 提示詞全文用用戶介面語言書寫；角色姓名與對白語言要求須清楚標示。\n- 人物靜圖：身份鎖定（臉、髮、體型、服裝、顏色）。場景靜幀：空間鎖定（建築、材質、格局、招牌、色盤）。除非材料點名，否則勿新增角色臉。\n- 凡已提供且影響外形、動作、對白、氣氛或場地的人設／角色聖經／段落／地點資料均須用上；空白欄位可略。\n- 只按已提供材料補齊可拍細節；勿引入固定樣本世界、示範樣本故事、或材料未出現的事實。\n- 長篇角色聖經（soul.md）須濃縮為可拍的表演與身份要點，不可整篇照貼。\n- 片長跟材料之中的實際秒數。動作連貫。無字幕、標誌、浮水印、無關路人。\n- 除非劇情要求，否則解剖結構正常（雙手雙腳）。\n- 多角色時保持每位主體一致；主焦點優先。\n- 若材料含生成鐵則，必須保留並放在輸出最尾（最高優先）。\n- 對白鎖定必須保留：不得刪改或翻譯；語言代碼要寫成全名。每段跟角色主口語，禁止段與段轉語言，禁止翻譯對白。\n- 導演修訂可調整氣氛／動作，但不得違反生成鐵則。",
  "videoPolish.hardRulesKeep": "生成鐵則（最高優先——保留每一行；[角色 · 名] 等物件標籤不可刪）。必須將完整生成鐵則區塊放在輸出最尾。不得削弱、刪除或套錯主體。",
  "clip.task": "任務：短劇時間軸片段（圖生影片）。",
  "clip.hasRef": "可能附有參考靜圖——相關時鎖定身份／場地連續性。",
  "clip.characters": "角色：",
  "clip.scene": "場景：",
  "clip.prop": "道具：",
  "clip.action": "動作指導：",
  "clip.beat": "段落／對白：",
  "clip.prev": "前一段連續性：",
  "clip.revision": "導演修訂（必須遵守）：",
  "clip.templateDraft": "範本草稿（請改進）：",
  "intro.task": "任務：自我介紹選角短片（圖生影片）。",
  "intro.hasRef": "參考靜圖會交予影片 API——必須鎖定該圖身份。",
  "intro.noRef": "本文無靜圖路徑；仍須鎖定人設外貌／戲服。",
  "intro.dossier": "角色檔案：",
  "intro.templateDraft": "範本草稿（請改進；勿忽略檔案）：",
  "common.durationAspect": "時長：{{seconds}} 秒。畫面比例：{{aspect}}。",
  "common.templateDraft": "範本草稿：",
  "improve.mode": "改進模式：合併下方所有來源輸出完整結果。除非用戶明確要求改身份，否則保持核心一致。表單稀疏時以額外上下文為準；用戶明確要求更改時以指示為準。",
  "improve.draftDefault": "目前表單欄位（已填內容）：",
  "improve.userRequest": "用戶改進要求（可留空 = 全面潤飾並合併以上內容）：",
  "improve.emptyDefault": "（全面潤飾：適合短劇／出圖／出片畫面連續）",
  "improve.createDefault": "構想／方向：",
  "improve.explicitContext": "僅限本次請求明確附上的上下文（作畫面連續；勿引入其他樣本世界；與構想／表單衝突時以用戶為準）：",
  "improve.storyTitle": "故事標題：{{title}}",
  "improve.styleNote": "風格備註：{{style}}",
  "improve.closingDefault": "請立即輸出完整結果。",
  "storyMeta.system": "你是短劇主創／視覺總監。根據故事標題與構想，寫簡潔可拍的風格備註以及出圖／出片「生成鐵則」。只回傳 JSON（不要代碼塊）：{\"styleNote\":\"2–5 句：氣氛、光線、鏡頭、色調、節奏\",\"hardRules\":\"3–8 句必須／禁止\"}。要具體、適合 AI 影片／出圖延續。用提供的標題、構想、現有風格／鐵則與上下文。不要擅自發明風格。",
  "storyMeta.draftLabel": "目前故事欄位：",
  "storyMeta.createLabel": "故事構想／標題：",
  "storyMeta.emptyPolish": "（潤飾視覺風格備註與生成鐵則，利於 AI 出片畫面連續）",
  "storyMeta.closing": "只回傳 JSON：{\"styleNote\":\"…\",\"hardRules\":\"…\"}。兩個鍵都必填且非空。",
  "storyMeta.contextLabel": "故事上下文（角色／場景／道具）：",
  "character.system": "你是專業短劇角色設定師，專門為 AI 影片／短劇生成「可拍、可認、可一致」的角色聖經。用戶會給一段角色構想。角色可以是人類、動物、鬼靈、魔物、機械、虛擬形象或其他設計體——依構想而定，勿強行寫成人類。只輸出一個 JSON 物件。spokenLanguages：BCP-47 代碼陣列，例如 [\"yue\",\"en\"]。非語言角色用 []。避免空泛形容；用可拍攝的細節。同一角色必須視覺一致。",
  "character.draftLabel": "目前資料表欄位（已填內容）：",
  "character.soulLabel": "已連結角色聖經（soul.md）（主要身份與性格依據）：",
  "character.createLabel": "角色構想：",
  "character.emptyPolish": "（全面潤飾：將角色聖經與表單合併進完整資料表）",
  "character.closing": "請立即輸出完整 JSON。必填鍵：{{keys}}。visualTags 為逗號分隔字串（禁止標籤陣列）；spokenLanguages 可以是代碼陣列。",
  "scene.system": "你是短劇場景／場景空間設計師，服務 AI 影片畫面連續。請輸出可拍的地點聖經 + 本場可演劇本片段。只回傳一個 JSON 物件。title＝短地名；description＝建築、物料、地標；script＝本場對白／動作／鏡頭。",
  "scene.draftLabel": "目前場景表單欄位（已填內容）：",
  "scene.charsLabel": "故事角色：",
  "scene.propsLabel": "故事道具：",
  "scene.priorLabel": "既有場景（畫面連續）：",
  "scene.createLabel": "場景構想：",
  "scene.emptyPolish": "（全面潤飾地點與本場劇本，利於出片畫面連續）",
  "scene.closing": "請立即輸出完整 JSON。必填鍵：{{keys}}。缺鍵無效。visualTags 必須是逗號分隔字串，禁止陣列。",
  "prop.system": "你是短劇道具設計師，服務 AI 影片畫面連續。只回傳一個 JSON。description：可畫細節；material／sizeNotes／condition 具體。",
  "prop.draftLabel": "目前道具表單欄位（已填內容）：",
  "prop.createLabel": "道具構想：",
  "prop.emptyPolish": "（全面潤飾道具外觀，利於出片畫面連續）",
  "prop.closing": "請立即輸出完整 JSON。必填鍵：{{keys}}。缺鍵無效。visualTags 必須是逗號分隔字串，禁止陣列。",
  "prop.fallbackName": "道具",
  "action.system": "你是短劇動作指導。只輸出有效 JSON，描述一項可拍攝的動作指導。要具體：身體部位、節奏、力度、道具路徑、走位。不要 markdown。",
  "action.storyContext": "故事脈絡（可選）：{{title}}",
  "action.styleNote": "風格備註：{{style}}",
  "action.existingDraft": "現有草稿（請潤飾補全）：",
  "action.userIdea": "用戶構想：{{idea}}",
  "action.closing": "只回傳 JSON。必填鍵：{{keys}}。visualTags 為逗號分隔字串，禁止陣列。",
  "profile.mustEveryKey": "必須輸出列表中的每一個鍵：{{keys}}。",
  "profile.valuesAreStrings": "每個值必須是 JSON 字串（不可 null、不可用 JSON 陣列）。真的不知道才可空字串。",
  "profile.visualTagsRule": "visualTags：用用戶介面語言的單一逗號分隔字串——禁止 JSON 陣列。",
  "profile.fillConcrete": "各鍵請盡量填具體細節，利於短劇畫面連續。",
  "common.rules": "規則：",
  "common.none": "（無）",
  "intro.soul": "soul.md（作為表演／身份完整來源）：\n{{soul}}",
  "intro.matchBible": "（跟從角色人設語言）",
  "invent.sources": "依據來源（優先序）：（1）用戶構想／指示，（2）已填表單，（3）僅當本次提示詞已寫出的額外上下文（soul.md、選角、故事區塊等），（4）附上的參考圖。",
  "invent.create": "創作模式（表單空白／極少）：按構想／圖自由創作，補齊可拍攝的關鍵欄位，內容須與用戶構想相關——勿留空必填鍵。",
  "invent.improve": "改進模式（表單已有內容）：潤飾並補齊空白欄，與已填內容一致；除非用戶要求，否則勿改核心身份。",
  "invent.noImport": "不得從本次提示詞未出現的來源引入身份、劇情、天氣、職業、地點、時代或風格（禁止目前開啟的故事、示範樣本、應用預設世界觀）。",
  "invent.storyBlock": "若下方明確附有故事／風格區塊：僅作畫面連續；不可覆蓋用戶明確構想。",
  "character.keysLead": "只輸出一個 JSON 物件（不要 markdown），鍵名必須是：{{keys}}",
  "character.ruleSpoken": "spokenLanguages：角色使用的語言，JSON 字串陣列（可多選），BCP-47／ISO 代碼，例如 [\"yue\",\"en\"]。非語言角色用 []。",
  "character.ruleIdentity": "同一角色必須視覺一致，方便之後多角度參考圖與影片生成。",
  "scene.keysLead": "只回傳一個 JSON 物件（不要 markdown），鍵名：{{keys}}",
  "scene.suggestLead": "為故事「{{title}}」建議第 {{n}} 個可用場景（場地／環境設定）。",
  "scene.suggestPlotFocus": "劇情焦點：{{label}}",
  "scene.suggestStyle": "風格：{{style}}",
  "scene.suggestExisting": "庫內／故事已有場地：{{titles}}",
  "scene.suggestChars": "角色（上下文）：",
  "scene.suggestProps": "道具（上下文）：",
  "scene.suggestSegment": "選定劇情段落詳情：",
  "scene.suggestBeats": "故事場次／段落：",
  "scene.suggestClosing": "回傳完整場景 JSON。請設計一個可重複使用的獨立場地（全域場景庫資產），須貼合選定劇情焦點，並與已有場地有所區別。",
  "scene.fallbackName": "場景",
  "scene.ideaFromImage": "請根據附上的參考圖，完整填寫場景資料。",
  "scene.polishIdea": "全面潤飾",
  "prop.keysLead": "只回傳一個 JSON，鍵名：{{keys}}",
  "action.fieldsLead": "欄位：{{keys}}。",
  "soul.system": "你為短劇／影視角色撰寫製作用角色聖經（soul.md，單檔 Markdown）。\n只輸出完整 Markdown 文件（不要代碼塊圍欄、不要解說）。\n結構（請用以下 ## 標題）：\n# {角色名}\n## 身份\n## 外貌\n## 服裝與輪廓\n## 性格與聲線\n## 使用語言\n## 小習慣\n## 背景\n## 關係\n## 表演與對白風格\n## 一致性硬規則\n## 視覺標籤\n規則：\n- 短劇可拍、可辨認、可一致；細節須具體。\n- 依據：資料表單 + 現有角色聖經 + 用戶指示。除非所選配方允許，否則勿用本次未提供的來源臆造。\n- 對白／配音必須尊重資料表的 spokenLanguages。\n- 硬規則用 5–10 條 bullet，方便之後圖像／對白 AI 遵守。\n- 用用戶介面語言書寫（香港書面語優先，若介面是其他語言就跟介面）。\n- 可選開頭 YAML frontmatter（name / tags），非必須。",
  "soul.improveMode": "改進模式：合併資料表 + 現有 soul.md，輸出更新後完整 soul.md。除非要求改身份，否則保持核心一致。",
  "soul.createMode": "根據以下角色設定撰寫完整 soul.md（合理補齊空白；不要換成另一個人）：",
  "soul.profileFields": "資料表欄位（已填內容）：",
  "soul.existing": "現有 soul.md（合併／改進；勿丟有用細節）：",
  "soul.userRequest": "用戶指示：{{request}}",
  "soul.extraContext": "本次一併提供的上下文（有用就用；仍以資料表為準）：",
  "soul.returnOnly": "只輸出完整 soul.md Markdown 正文。",
  "wardrobe.system": "你是短劇服裝與視覺風格顧問。根據角色與劇情，提出一套完整外裝方案。只回傳一個 JSON 物件（不要 markdown 圍欄）：{\"name\":\"短名稱\",\"costume\":\"詳細外裝描述（供出圖／影片）\",\"artStyle\":\"下列其一\",\"rationale\":\"一兩句理由\"} artStyle 必須是：{{styleIds}} costume 要具體：材質、顏色、輪廓、鞋履、配件。年齡表述須得體；禁止對未成年做性化描述。保留既有外貌身份，只設計服裝與風格。用角色欄位與已提供的劇情／故事上下文。不要擅自發明造型世界。",
  "wardrobe.improveMode": "改進／建議模式：使用下方全部角色欄位與劇情上下文。",
  "wardrobe.characterForm": "角色（完整表單）：",
  "wardrobe.soulExcerpt": "soul.md 摘要：\n{{soul}}",
  "wardrobe.userRequest": "用戶指示：{{request}}",
  "wardrobe.storyContext": "故事／製作上下文（有就用；勿另起一個世界）：",
  "wardrobe.style": "風格：{{style}}",
  "wardrobe.segment": "選定劇情段落：{{label}}",
  "wardrobe.sceneContext": "場景／段落／對白摘錄：",
  "wardrobe.noScenes": "（尚無場景）",
  "wardrobe.proposeNew": "請提出一套符合劇情的新戲服（避免與已有造型重複）。",
  "fill.system": "你負責補齊短劇資產設定中「仍然空白」的欄位。\n只回傳一個 JSON 物件，且只能包含這些鍵：{{keys}}。\n每個值必須是非空 JSON 字串（不可 null、不可 JSON 陣列）。\n若含 visualTags：用用戶介面語言的逗號分隔字串（格式例：\"gold, necklace\"，勿照抄例子，須貼合本資產）——禁止陣列。\n只根據已有部分設定及參考圖補齊；勿另起未見於 partial／圖的劇情、地點或樣本世界。\n不要 markdown、不要解說。",
  "fill.userPartial": "已有部分設定（勿矛盾）：",
  "fill.userOnly": "只補齊這些空白鍵：{{keys}}。",
  "fill.userReturn": "只回傳含上述鍵的 JSON；每值為非空字串。",
  "imageGen.multiRef": "另有 {{n}} 張已選參考圖：主編輯底圖為第一張，其餘作身份一致輔助，勿換成另一物件／主體。",
  "residual.sceneLink": "第 {{n}} 場：{{short}}",
  "residual.beatSegment": "段落 {{n}} · {{who}}{{tail}}",
  "residual.unknown": "未指定",
  "residual.story": "故事",
  "beat.mood": "【心情】{{text}}",
  "beat.atmo": "【氣氛】{{text}}",
  "beat.camera": "【鏡頭】{{text}}",
  "beat.sfx": "【聲效】{{text}}",
  "beat.action": "【動作】{{text}}",
  "beat.actionWho": "【動作｜{{who}}】{{text}}",
  "beat.expr": "【表情】{{text}}",
  "beat.exprWho": "【表情｜{{who}}】{{text}}",
  "beat.dialogue": "【對白｜{{who}}】{{body}}",
  "beat.dialogueTone": "【對白｜{{who}}｜{{tone}}】{{body}}",
  "beat.whoUnknown": "？",
  "beat.template": "【心情】緊繃、猶豫\n【氣氛】門縫暖光；雨砸地\n【鏡頭】中景推進\n【聲效】雨、布料摩擦\n【動作｜角色名】摘下安全帽；盯門縫暖光；手伸進外套內袋\n【表情｜角色名】眉心緊鎖，呼吸一滯\n【對白｜角色名｜低聲沙啞】又是下雨……\n【對白｜角色名｜自語】（停半拍）你……還在嗎？",
  "vision.preamble": "已附上參考靜圖。請主要根據圖片填寫此{{what}}全部欄位；可結合構思／草稿潤飾。",
  "vision.character": "角色（名稱、外貌、戲服、年齡、性別、標籤等）",
  "vision.scene": "場景（標題、描述、光影、氣氛、佈景、標籤等）",
  "vision.prop": "道具（名稱、描述、材質、尺寸、狀態、標籤等）",
  "vision.action": "動作（名稱、說明、節奏、意圖、鏡頭備註、標籤等）",
  "vision.costume": "戲服（名稱、完整造型描述）",
  "still.header": "短劇畫面連續用單格靜圖（不是多格板）。產出一張對應下方鏡頭的主畫面。無文字、標誌、浮水印、介面邊框。清晰可製作。",
  "still.revision": "用戶改進要求（必須套用）：{{notes}}",
  "still.regenTask": "任務：修訂圖生影片導演提示詞，並保持可作靜圖拍攝指示。",
  "still.userImprove": "用戶改進要求：\n{{notes}}",
  "still.currentPrompt": "目前專業提示詞：",
  "still.hardRules": "生成鐵則（必須保留於輸出最尾；不得刪除或削弱）：",
  "mediaGen.writeOne": "請撰寫「一條」最終短劇靜圖／多格板生成提示詞。",
  "mediaGen.returnOnly": "只回傳提示詞正文——不要代碼圍欄、標題或解釋。",
  "mediaGen.singleComposite": "輸出描述「單一合成圖」（只匯出一張）。",
  "mediaGen.lockRefs": "附圖圖序與下方參考圖編號一致，須作視覺準據。身份／戲服／場景／道具必須鎖定附圖，禁止換成另一人、另一店或另一物。",
  "mediaGen.videoSystem": "你是短劇圖生影片導演提示詞撰寫者。只回傳一條提示詞正文。片長跟材料之中的實際秒數。只用已提供材料中的事實。若材料含鏡頭範本區塊，必須執行該運鏡與表演，禁止改回預設推近或手持。有生成鐵則則置於文末。",
  "mediaGen.videoMerge": "將材料合併為「一條」專業短片影片提示詞。",
  "mediaGen.videoInclude": "須含：身份鎖定、鏡頭運動、表演／對白、節奏、光影連續。",
  "mediaGen.videoFacts": "只用已提供材料中的事實；勿引入固定樣本世界或示範樣本故事。",
  "mediaGen.videoNoSwap": "有附圖時禁止換成另一演員、場景或道具。",
  "mediaGen.videoHardRules": "有生成鐵則則置於文末。",
  "mediaGen.imageSystem": "你是短劇靜圖／多格板提示詞導演。只回傳提示詞正文——不要代碼圍欄、標題或解釋。只用已提供材料中的事實；勿引入固定樣本世界或示範樣本故事。若材料含鏡頭範本區塊，必須執行該構圖與運鏡，禁止改回預設推近或手持。有生成鐵則則置於文末。",
  "mediaGen.imageMergeStills": "將用戶勾選材料與附圖合併為「一條」出圖提示詞。",
  "mediaGen.imageMergeText": "將用戶勾選文字材料合併為「一條」出圖提示詞。",
  "mediaGen.imagePriority": "最高優先：附圖中的臉／服裝／場景／道具必須一致。",
  "mediaGen.imageNoSwap": "有角色／場景靜圖時，禁止換成無關路人或另一場景。",
  "mediaGen.imageFacts": "只用已提供材料中的事實；勿引入固定樣本世界或示範樣本故事。",
  "mediaGen.imageLayout": "若要求多格板，保留精確格數與分隔。",
  "mediaGen.imagePackage": "若有出圖方案區塊，最終提示詞必須嚴格執行該版面（格數、姿勢、構圖）。",
  "mediaGen.imageHardRules": "有生成鐵則則置於文末。",
  "mediaGen.directorFallback": "圖生影片：以這張靜圖做短劇片段。身份、戲服、場景、構圖須鎖定該靜圖，由此畫面開始動。",
  "comic.taskHint": "故事「{{title}}」漫畫第 {{n}} 頁：一張完整漫畫頁，剛好 {{count}} 格。全頁角色身份、服裝、場景必須連貫。無浮水印、無介面邊框。",
  "comic.panelCount": "格數不可改：必須剛好 {{n}} 格。",
  "comic.lockSplash": "排版鎖定：整頁一格滿版。禁止加框、分格、拼貼。",
  "comic.lockYonkoma": "排版鎖定：直向四格，四行一列，由上至下。禁止二乘二網格或橫條。",
  "comic.lockGrid2x2": "排版鎖定：兩行兩列。禁止橫條、二乘三、單格滿版。",
  "comic.lockGrid2x3": "排版鎖定：兩行三列。上行一至三，下行四至六。禁止二乘二或三乘三。",
  "comic.lockGrid3x3": "排版鎖定：三行三列，共九格。禁止二乘二、二乘三，或少於九格。",
  "comic.lockStrip": "排版鎖定：單行橫向剛好 {{n}} 格。禁止多行網格。",
  "comic.layoutSplash1": "一張直向漫畫頁：剛好一格滿版，無分隔、無額外畫框。",
  "comic.layoutStrip2": "一張橫向漫畫頁：單行兩格並排，粗白分隔。",
  "comic.layoutStrip3": "一張橫向漫畫頁：單行三格，粗白分隔。",
  "comic.layoutYonkoma": "一張直向漫畫頁：四格漫畫直向疊放（四行一列），粗白分隔，由上至下閱讀。",
  "comic.layoutGrid2x2": "一張方形漫畫頁：二乘二網格，剛好四格，粗白分隔，先左至右再上至下。",
  "comic.layoutStrip4": "一張闊橫向漫畫頁：單行四格，粗白分隔。",
  "comic.layoutGrid2x3": "一張橫向漫畫頁：剛好六格，兩行三列（上 1-2-3、下 4-5-6），粗白分隔，先左至右再上至下。",
  "comic.layoutGrid3x3": "一張方形漫畫頁：三乘三網格，剛好九格，粗白分隔，先左至右再上至下。",
  "comic.layoutWidePlusTwo": "一張直向漫畫頁：上方約六成高為全寬大格，下方並排兩細格，粗白分隔。",
  "comic.layoutTwoPlusWide": "一張直向漫畫頁：上方並排兩細格，下方約六成高為全寬收勢格，粗白分隔。",
  "comic.layoutTallLeftTwo": "一張直向漫畫頁：左半頁一格直通全高，右半頁上下兩格，粗白分隔。",
  "comic.layoutHeroPlusThree": "一張直向漫畫頁：上半頁一格全寬大格，下半頁單行三細格，粗白分隔。",
  "comic.layoutFocusQuad": "一張直向漫畫頁：左上中格，右上兩細格直疊，下半頁一格全寬大格，粗白分隔。",
  "comic.layoutStaggerFour": "一張直向漫畫頁：兩行錯位——上行寬加窄，下行窄加寬，粗白分隔。",
  "comic.layoutDiagPairPlus": "一張直向漫畫頁：上半頁以斜分隔成兩楔形格，下半頁一格全寬橫格，粗白分隔。",
  "comic.layoutHeroPlusFour": "一張直向漫畫頁：上半頁一格全寬大格，下半頁二乘二共四細格，粗白分隔。",
  "comic.lockWidePlusTwo": "排版鎖定：上格為全寬大格。下方便好兩細格並排。禁止三等分橫條或二乘二。",
  "comic.lockTwoPlusWide": "排版鎖定：上方剛好兩細格。下方一格全寬收勢。禁止三等分橫條或二乘二。",
  "comic.lockTallLeftTwo": "排版鎖定：左格直通全頁高。右邊上下兩格。禁止等分二乘二或單行橫條。",
  "comic.lockHeroPlusThree": "排版鎖定：上半頁一格全寬大格。下方單行剛好三細格。禁止二乘二或四等格。",
  "comic.lockFocusQuad": "排版鎖定：左上中格、右上兩細格直疊、下半頁一大格。禁止等分二乘二。",
  "comic.lockStaggerFour": "排版鎖定：錯位大小——上行寬加窄，下行窄加寬。禁止四格等大方塊。",
  "comic.lockDiagPairPlus": "排版鎖定：上半頁必須斜分成兩楔形格；下半頁一格全寬橫格。禁止三等分橫條或二乘二。",
  "comic.lockHeroPlusFour": "排版鎖定：上半頁一格全寬大格；下半頁二乘二共四細格。全頁剛好五格。禁止三乘三或整頁二乘二。",
  "comic.readingYonkoma": "閱讀順序：只由上至下（直向四格）。",
  "comic.readingWidePlusTwo": "閱讀順序：先讀上方大格，再由左至右讀下方兩細格。",
  "comic.readingTwoPlusWide": "閱讀順序：先左後右讀上方兩格，再讀下方全寬格。",
  "comic.readingTallLeftTwo": "閱讀順序：先讀左邊直通格，再讀右上，再讀右下。",
  "comic.readingHeroPlusThree": "閱讀順序：先讀上方大格，再由左至右讀下方三細格。",
  "comic.readingFocusQuad": "閱讀順序：先讀左上中格，再由上至下讀右上兩細格，最後讀下方大格。",
  "comic.readingStaggerFour": "閱讀順序：左上、右上，再左下、右下。",
  "comic.readingDiagPairPlus": "閱讀順序：先讀左上楔形格，再讀右下楔形格，最後讀下方全寬格。",
  "comic.readingHeroPlusFour": "閱讀順序：先讀上方大格，再由左至右、上至下讀下方四細格。",
  "comic.readingOrder": "閱讀順序：先左至右，再上至下（直向四格只由上至下）。",
  "comic.panelNumbers": "每格左上角標小格號 1 至 {{n}}。",
  "comic.panelLine": "第 {{i}}／{{n}} 格（{{label}}）：{{cap}}",
  "comic.panelEmpty": "第 {{i}}／{{n}} 格（{{label}}）：一個獨立而連續的故事瞬間。",
  "comic.identity": "全頁各格角色身份、服裝、場景必須連貫。",
  "comic.finished": "這是一張完成的漫畫頁，不是無關照片拼貼，也不是介面草圖。",
  "comic.layoutLead": "版式：{{layout}}",
  "comic.prevPage": "上一頁漫畫。保持角色身份、服裝與場景連續，但不可複製上一頁的分格。",
  "comic.ownPage": "本頁既有成圖。修訂時可作身份／版式底圖。",
  "comic.galleryRef": "角色或場景身份靜圖。納入時須對準面容、服裝與場景。",
  "comic.profileLine": "故事「{{title}}」漫畫第 {{n}} 頁。",
  "comic.styleBible": "故事風格說明：{{note}}",
  "comic.artMedium": "畫風：{{art}}",
  "comic.fallbackClose": "完成的印刷漫畫頁。粗白分隔。小格號。無浮水印、無應用介面、無相簿拼貼。",
  "comic.hardRules": "生成鐵則",
  "comic.introTask": "圖生影片：以故事「{{title}}」第 {{n}} 頁完成漫畫頁（剛好 {{count}} 格）拍一段短片。身份、服裝、版式必須鎖定附圖。",
  "comic.introLock": "鎖定：面容、服裝、場景、分隔與格號必須與成圖一致。禁止換成另一頁或另一人。",
  "comic.introLayout": "保持此頁版式：{{layout}}",
  "comic.introCamera": "運鏡：慢推近，或依閱讀序輕輕掃過各格。只可有紙張／印刷感微動。禁止硬切成另一版式。",
  "comic.introClose": "無浮水印、無介面邊框；除頁上已畫的對白外，勿再疊字幕。",
  "comic.dramaStillLock": "身份、服裝、場景鎖定附上的漫畫頁成圖，但要當真人短劇鏡頭拍，不是在印刷格上掃過去。",
  "comic.dramaCamera": "運鏡與表演：短劇節奏、表演清楚、口型跟分格對白。有上一頁靜圖時須畫面連續。",
  "comic.formatLockTall": "開本鎖定：整頁必須為直向 9:16 漫畫頁，禁止橫向寬銀幕構圖。",
  "comic.formatLockSquare": "開本鎖定：整頁必須為方形 1:1 漫畫頁。",
  "comic.formatLockWide": "開本鎖定：整頁必須為橫向 16:9 漫畫頁。",
  "art.photoCinematic": "必須媒介：真人寫實電影靜幀。真實鏡頭質感、自然材質、電影調色，可有輕微膠片顆粒。必須像照片或電影畫面。禁止：動畫、賽璐璐、平面插畫、卡通勾線、黏土、塑膠電腦圖像。",
  "art.photoPortrait": "必須媒介：寫實棚拍肖像攝影。柔光箱光線、商業頭像清晰度、真實鏡頭散景。必須是照片。禁止：動畫、漫畫墨線、立體玩具渲染、平塗賽璐璐。",
  "art.photoDocumentary": "必須媒介：寫實紀實照片。現場自然光、誠實質感、低華麗感。必須像真機實拍。禁止：動畫、風格化電腦圖像、插畫。",
  "art.cgiFilm": "必須媒介：電影級立體電腦圖像角色渲染。物理材質、光線追蹤高光、輪廓清楚。必須是立體渲染，不是真照片，也不是平面動畫。禁止：真人攝影、動畫線稿、平塗漫畫墨線。",
  "art.cgiStylized": "必須媒介：風格化高品質立體（長片動畫電腦圖像）。圓潤可讀形體、柔和物理材質、表情化比例。必須是立體電腦圖像。禁止：寫實真人、平面動畫賽璐璐、潦草漫畫。",
  "art.cgiClay": "必須媒介：立體黏土／雕塑角色。柔和啞光黏土、雕塑形體、定格燈光。必須讀成黏土雕塑。禁止：寫實皮膚照片、動畫賽璐璐、墨線漫畫。",
  "art.animeModern": "必須媒介：現代日系電視動畫。乾淨數碼線稿、柔和賽璐璐、動畫眼與髮束、平塗或漸層。整張必須是平面動畫。禁止：寫實攝影、真實毛孔、立體渲染、純西式漫畫墨線、油畫。",
  "art.animeShonen": "必須媒介：少年向動畫主視覺。粗線、高反差賽璐璐、銳利動畫眼、動態剪影。必須是少年向平面動畫。禁止：寫實照片、立體電腦圖像、純柔和水彩。",
  "art.animeShoujo": "必須媒介：少女向動畫。細線、柔和漸層、明亮動畫眼、溫柔色調。必須是少女向動畫。禁止：寫實照片、硬立體渲染、粗礪漫畫墨線。",
  "art.animeGekiga": "必須媒介：劇畫／寫實系平面動畫。成熟線質、克制色盤，仍清楚是平面動畫。禁止：真人照片、Q 版、純立體電腦圖像。",
  "art.animeChibi": "必須媒介：Q 版／超變形動畫。頭大身小、可愛簡化五官、乾淨平塗。必須是 Q 版動畫。禁止：寫實比例、寫實立體、細緻真人。",
  "art.donghua": "必須媒介：國漫角色主視覺。服裝細節精細、輪廓優雅、高品質平面或二點五維動畫感。必須讀成國漫，不是荷里活照片。禁止：寫實真人、純西式報紙漫畫。",
  "art.manhwa": "必須媒介：韓漫／條漫全彩。柔和數碼上色、乾淨輪廓、光澤頭髮。必須是韓漫平面。禁止：寫實照片、黏土立體、純美式英雄墨線。",
  "art.comicWestern": "必須媒介：西式漫畫。肯定墨線、平塗或有限度賽璐璐色、圖形化形狀、設定稿漫畫風格。必須是漫畫插畫。禁止：寫實照片、純日系大眼、黏土渲染。",
  "art.conceptGame": "必須媒介：3A 遊戲角色原畫。上色設定稿、剪影清楚、製作級概念品質。必須像原畫，不是遊戲截圖，也不是真人照片。禁止：純寫實肖像照片、純 Q 版動畫。",
  "art.illustrationSoft": "必須媒介：柔和數碼插畫。輕柔筆觸、繪本式完成度、角色設計連貫。必須是手繪插畫。禁止：寫實相機照片、硬動畫賽璐璐、黏土立體。",
  "mediaGen.polishTask": "任務：{{hint}}",
  "mediaGen.polishKind": "種類：{{kind}}",
  "mediaGen.polishMaterials": "—— 材料 ——",
  "mediaGen.polishEndMaterials": "—— 材料完 ——",
  "mediaGen.polishRef": "參考圖{{n}} — {{title}}",
  "mediaGen.videoTaskHint": "由靜圖寫專業圖生影片導演詞（{{kind}}）。含鏡頭、表演、節奏；鎖定該靜圖。",
  "mediaGen.directorFallbackCam": "鏡頭運動與表演清楚；對白口型須跟腳本；無字幕、無浮水印。",
  "charIntro.task": "圖生影片：以參考圖中的同一人物，拍一段短劇選角用「自我介紹」短片。",
  "charIntro.identityLock": "身份鎖定：臉、髮型、體型、年齡感、服裝與顏色必須與參考靜幀一致，不可換成另一個人。",
  "charIntro.personality": "性格／氣場：{{personality}}。",
  "charIntro.backstory": "背景要點：{{backstory}}。",
  "charIntro.relationships": "關係要點：{{relationships}}。",
  "charIntro.soul": "角色聖經摘要（表演來源）：{{soul}}",
  "charIntro.performance": "習慣：{{manner}}。",
  "charIntro.speech": "對白：嘴唇自然開合像在簡短自我介紹；聲線：{{voice}}。",
  "charIntro.beat": "動作節奏：自然站定 → 微笑或輕點頭 → 簡短介紹手勢（可空手）→ 定格。",
  "charIntro.lighting": "光線與靜幀一致；無字幕、無標誌、無其他人入鏡。",
  "sceneIntro.task": "圖生影片：以參考靜幀中的同一場地，拍一段短劇用「場景介紹／建立鏡頭」短片。",
  "sceneIntro.spaceLock": "空間鎖定：建築、材質、招牌、格局與色彩語言必須與參考靜幀一致，不可換成另一個地方。",
  "sceneIntro.name": "地點名稱：{{name}}。",
  "sceneIntro.place": "場地描述：{{place}}。",
  "sceneIntro.spaceType": "空間類型：{{type}}。",
  "sceneIntro.time": "時段：{{time}}。",
  "sceneIntro.weather": "天氣：{{weather}}。",
  "sceneIntro.moodLight": "氣氛：{{mood}}。燈光：{{lighting}}。",
  "sceneIntro.palette": "色盤：{{palette}}。",
  "sceneIntro.setDressing": "陳設：{{set}}。",
  "sceneIntro.tags": "視覺標籤：{{tags}}。",
  "sceneIntro.art": "藝術風格：{{art}}。",
  "sceneIntro.ambient": "環境氛圍（無介面子幕）：{{sound}}。",
  "sceneIntro.scriptCue": "本場提示（只作氣氛，勿新增角色臉，除非靜幀已有）：{{cue}}。",
  "sceneIntro.camera": "運鏡：{{camera}}；連續輕微動態。除非材料已有，否則勿新增路人臉、標誌、字幕。",
  "sceneIntro.beat": "動作節奏：建立鏡頭定場 → 環境微動（光影、天氣粒子、已有的布料／樹影）→ 定格。",
  "propIntro.task": "圖生影片：以參考靜幀中的同一道具，拍一段短劇畫面連續用「道具介紹／主視覺」短片。",
  "propIntro.objectLock": "物件鎖定：輪廓、材質、顏色、刻字／紋樣、舊損與比例必須與參考圖一致，不可換成另一件。",
  "propIntro.name": "道具名稱：{{name}}。",
  "propIntro.look": "外觀描述：{{look}}。",
  "propIntro.material": "材質：{{material}}。",
  "propIntro.size": "尺寸筆記：{{size}}。",
  "propIntro.condition": "狀態／舊損：{{condition}}。",
  "propIntro.tags": "視覺標籤：{{tags}}。",
  "propIntro.art": "藝術風格：{{art}}。",
  "propIntro.camera": "運鏡：乾淨桌面／主視覺台，輕微環繞或慢推近；光線與靜幀一致。",
  "propIntro.beat": "動作節奏：主視覺定格 → 微光澤／微旋轉或材質閃爍（若圖中已有）→ 定格。",
  "propIntro.noHands": "除非靜幀已有，否則勿加手、角色臉、字幕、浮水印或額外道具。",
  "costumeIntro.task": "圖生影片：以參考靜幀中的同一戲服造型，拍一段短劇戲服庫用「造型介紹」短片。",
  "costumeIntro.wardrobeLock": "服裝鎖定：輪廓、布料、顏色、層次、配件與舊損必須與參考圖一致，不可換成另一套。",
  "costumeIntro.identityOrProduct": "若靜幀有人：鎖定臉與體型，布料可輕微擺動；若為人台／平鋪：保持產品構圖。",
  "costumeIntro.name": "造型名稱：{{name}}。",
  "costumeIntro.desc": "戲服描述：{{look}}。",
  "costumeIntro.art": "藝術風格：{{art}}。",
  "costumeIntro.camera": "運鏡：輕微推近或慢環繞；光線與靜幀一致。",
  "costumeIntro.beat": "動作節奏：定格 → 布料垂墜／袖口微動／五金反光 → 定格。",
  "costumeIntro.forbid": "勿新增角色臉、字幕、標誌或色情姿勢。",
  "costumeIntro.fallbackName": "造型",
  "actionIntro.lead": "短劇動作示範片：「{{name}}」。",
  "actionIntro.intention": "意圖：{{intention}}",
  "actionIntro.body": "肢體節奏：{{body}}",
  "actionIntro.camera": "鏡頭：{{camera}}",
  "actionIntro.closing": "動作連貫流暢，無字幕水印，緊跟該靜圖。",
  "sceneIntroPolish.task": "任務：場景介紹／建立鏡頭短片（圖生影片）。",
  "sceneIntroPolish.hasRef": "參考場景靜圖會交予影片 API——必須鎖定該圖空間身份。",
  "sceneIntroPolish.noRef": "本文無靜圖路徑；仍須鎖定地點聖經描述。",
  "sceneIntroPolish.dossier": "場景檔案：",
  "sceneIntroPolish.scriptCue": "劇本提示（只作氣氛）：\n{{script}}",
  "sceneIntroPolish.emptySet": "空鏡為主；除非靜幀已有，否則勿新增角色臉。無字幕、標誌。",
  "propIntroPolish.task": "任務：道具主視覺介紹短片（圖生影片）。",
  "propIntroPolish.hasRef": "參考道具靜圖會交予影片 API——必須鎖定該圖物件身份。",
  "propIntroPolish.noRef": "本文無靜圖路徑；仍須鎖定道具檔案描述。",
  "propIntroPolish.dossier": "道具檔案：",
  "propIntroPolish.noHands": "除非靜幀已有，否則勿新增手或角色臉。無字幕、標誌。",
  "costumeIntroPolish.task": "任務：戲服／造型介紹短片（圖生影片）。",
  "costumeIntroPolish.hasRef": "參考靜圖會交予影片 API——有人則鎖定身份＋服裝；人台／平鋪則鎖定服裝輪廓與材質。",
  "costumeIntroPolish.noRef": "本文無靜圖路徑；仍須鎖定戲服描述。",
  "costumeIntroPolish.dossier": "戲服檔案：",
  "costumeIntroPolish.fabric": "布料垂墜／微動即可；勿新增角色臉；無字幕、標誌。",
  "actionIntroPolish.task": "任務：動作指導介紹短片（圖生影片）。",
  "actionIntroPolish.hasRef": "參考靜圖已附——表演身份鎖定該幀。",
  "actionIntroPolish.templateKeepRules": "範本草稿（請改進；生成鐵則置於最尾）：",
  "cover.posterLead": "專業短劇海報／主視覺（16:9 靜幀）。不是介面草圖。無文字、標誌、浮水印、標題字幕。",
  "cover.titleMood": "故事標題（只取氣氛，畫面勿寫出文字）：{{title}}。",
  "cover.styleBible": "風格備註：{{style}}",
  "cover.extraDir": "額外方向：{{idea}}",
  "cover.establishing": "適合用作片庫封面的情緒建立鏡頭；強烈剪影、可讀氣氛。",
  "cover.medium": "依藝術風格 medium 出圖；構圖清晰。",
  "cover.editPrefix": "圖像編輯：以新構圖創作短劇海報。保留主體身份／氣氛（如有）。",
  "cover.label": "故事封面",
  "costumeFill.system": "你是影視造型指導。只回覆緊湊 JSON：{\"name\":\"短名稱\",\"description\":\"完整戲服描述（分層、布料、顏色、配飾；無品牌標誌）\",\"artStyle\":\"可選風格 id 或空字串\",\"hardRules\":\"3–8 句必須／禁止\"} 每個鍵必須是 JSON 字串（不可 null／陣列）。不要 markdown。若有參考圖，請按圖如實描述該造型，供短劇出圖使用。",
  "costumeFill.idea": "構思：{{idea}}",
  "costumeFill.polish": "潤飾以下戲服草稿。",
  "costumeFill.required": "必填鍵：name, description, artStyle, hardRules。缺鍵無效。",
  "costumeFill.fallbackName": "造型",
  "segment.entireStory": "全劇（所有場次）",
  "segment.noStory": "未選故事（僅角色資料）",
  "vision.inventFromImage": "請根據附上的參考圖，完整填寫{{kind}}資料。",
  "vision.polishAll": "全面潤飾並合併所有欄位",
  "story.untitled": "未命名短劇",
  "action.castIdentityNote": "已附 {{count}} 張參考素材（角色／道具等）：每格人物身份須與參考素材一致。",
  "tpl.system.polishOnly": "配方「只潤飾」：保持核心身份與世界。只潤飾措辭。不要發明時代、天氣、職業、地點或樣本世界。不要發明對白語言。不要把預設鐵則寫入檔。",
  "tpl.system.fillBlanks": "配方「只填空白」：只補空欄。已填欄位不要改寫。不要發明新世界。",
  "tpl.system.invent": "配方「自由創作」：用戶授權按構想自由補齊可拍細節，必填欄要齊。仍然不要引入示範樣本或本次未暗示的世界。",
  "tpl.system.fromStory": "配方「從故事建議」：只用本次請求已寫出的標題／風格／選角／場景做畫面連續。衝突時以用戶構想為準。",
  "tpl.system.followAsset": "配方「跟資產／故事」：跟已提供的風格與鐵則。除非材料有寫，不要強加電影感、空鏡或 6–10 秒。片長跟片段實際秒數。",
  "tpl.system.cinematicLock": "配方「電影感＋防幻覺」：電影短劇感；場地空鏡優先；無水印、標誌、多餘臉；人類恰好兩手兩臂兩腿（非人除外）。",
  "tpl.system.identityLock": "配方「鎖身份」：臉／體／服裝／場地／道具必須鎖定附圖。不要換成另一人、另一地或另一物。",
  "tpl.system.restyle": "配方「可改造型」：保持同一角色身份。服裝、場地陳設、時代可按用戶要求改。不要換成另一個人。",
  "pipeline.character.system": "你為短劇 AI 影片潤飾角色聖經。每位角色 3–5 行：外形、聲線、動機、招牌動作。只用本次請求已有事實。",
  "pipeline.scene.system": "你把短劇場景擴成視覺節拍表。每拍跟材料之中的實際片長，不要當 6–10 秒。只用已提供場景。",
  "pipeline.props.system": "你為短劇潤飾道具連續性。記顏色、尺寸、出場時機。名單以外不要發明道具。",
  "pipeline.script.system": "你是專業短劇編劇。每場寫一段適合 AI 影片的緊湊劇本。用故事實際片長，不要硬加 10 秒上限。每場格式：\n### SCENE <number> | id=<id>\n<script body>",
  "pipeline.script.noScenes": "（無場景 — 不要發明地點）",
  "keyArt.task": "故事「{{title}}」第 {{n}} 張劇照。一張完成的宣傳／劇照，不是漫畫分格，不要格號，不要應用介面。",
  "keyArt.lockCover": "封面海報：橫向故事卡關鍵視覺。預留安靜的標題安全區。面容可辨。不要自製商標或假演職員表。",
  "keyArt.lockPoster": "直立海報：一張直向單張。主體在電話畫面亦清楚。畫面內不要再放其他海報。",
  "keyArt.lockStill": "劇照：一格電影感定格，像從短劇抽出。表演自然、空間真實。不是拼貼。",
  "keyArt.lockPromo": "宣傳圖：角色與世界同框的市場用關鍵視覺。輪廓清楚，一種情緒。不是樣片拼板。",
  "keyArt.lockSocial": "社交直圖：直向 9:16 預告畫面。主體夠大。預留字幕邊距。",
  "keyArt.lockHeadshot": "主角大頭：一張正臉充滿畫面，面貌必須跟參考圖一致。可帶肩。不要其他人。",
  "keyArt.lockBust": "半身宣傳：胸上肖像，戲服領可見，望向鏡頭。",
  "keyArt.lockGroup": "群像：所有已點名角色同框，同一世界、同一光線。不要漏面或換面。",
  "keyArt.formatLockTall": "開本鎖定：整張必須是直向 9:16。不要橫向寬銀幕構圖。",
  "keyArt.formatLockSquare": "開本鎖定：整張必須是方形 1:1。",
  "keyArt.formatLockWide": "開本鎖定：整張必須是橫向 16:9。",
  "keyArt.methodFreshLock": "出圖方式：全新生成。參考圖只用來鎖定身份。不要沿用舊稿像素構圖。",
  "keyArt.methodEditLock": "出圖方式：改已附上的本張成圖。除非指示要求，否則保留構圖。",
  "keyArt.methodIdentityLock": "出圖方式：面貌鎖定參考角色。姿勢、裁切與服裝可以改變。",
  "keyArt.methodContinueLock": "出圖方式：延續上一張。同一批人、同一場景，同一場拍攝的下一拍。",
  "keyArt.briefLine": "拍攝指示：{{brief}}",
  "keyArt.beatLine": "綁定分鏡：{{beat}}",
  "keyArt.close": "完成的 {{aspect}} 靜圖。不要浮水印、不要介面邊框、不要額外字幕。",
  "charIntro.manner": "習慣：{{manner}}。",
  "charIntro.cameraDefault": "預設運鏡：輕微推近或手持微晃；角色望向鏡頭或略偏鏡頭。",
  "mediaGen.honorCameraTemplate": "若材料含鏡頭範本區塊，必須按該構圖與運鏡執行，禁止改回籠統的推近或手持。",
  "mediaGen.refRoles": "每張附圖只負責一項：身份（臉與戲服）、空間（白模走位與機位，禁止把黏土灰當成品外觀）、動作（節奏與姿勢）、風格（色調與光）。禁止一張圖包辦全部。",
  "sceneIntro.cameraNotes": "運鏡備註：{{camera}}。",
  "sceneIntro.cameraDefault": "預設運鏡：連續輕微動態。除非材料已有，否則勿新增路人臉、標誌、字幕。",
  "quality.family.photo": "畫質：眼睛或主臉銳利對焦，寫實媒介的微觀細節，專業棚燈（風格另有規定除外），50–85mm 鏡頭感，無動態模糊、無過重美顏、無浮水印或文字。",
  "quality.family.cgi": "畫質：乾淨立體角色、可讀材質、輪廓清楚、棚燈或三點電腦燈光，非黏土風格則勿顆粒，無浮水印文字，不是真照片。",
  "quality.family.anime": "畫質：乾淨平面設定稿、線條穩定、各格臉型一致、賽璐璐或柔和上色，避免寫實攝影與立體皮膚著色，無浮水印文字。",
  "quality.family.illust": "畫質：專業插畫設定稿清晰度、角色設計一致、剪影與服裝可讀，中性棚景，無浮水印、無介面字幕。",
  "sheet.lock.lead": "為短劇畫面連續製作角色參考靜圖。",
  "sheet.lock.sexPrefix": "性別鎖定（最高優先——低髻、鵝蛋臉、白皙或偏窄身材、袍服都不得改性別）：{{lock}}",
  "sheet.lock.identity": "身份鎖定：每格剛好一個角色主體（可為人、動物、生物、鬼靈、機械或其他設計體——但同一張表不得換物種或換設計）。",
  "sheet.lock.noSecond": "不要發明第二個角色；各格保持同一身體結構、紋樣、顏色與頭部設計。",
  "sheet.lock.head": "頭／臉（或對應部位）必須一致：同一眼睛或感測器、同一頭部剪影、同一表面顏色與關鍵識別。",
  "sheet.lock.camera": "鏡頭：穩定參考構圖，垂直線端正；除非版式要求，否則不要魚眼鏡。",
  "sheet.lock.background": "背景：潔淨淺灰或米白棚景，空、均勻；除非版式要求小件服裝／道具特寫，否則不要雜物。",
  "sheet.lock.forbidden": "禁止：浮水印、標誌、字幕、文字、介面邊框、多餘肢體、畸形末端（特寫手／細節格除外）。",
  "sheet.lock.subject": "主體名稱／構想：{{name}}",
  "sheet.lock.age": "年齡或成熟度：{{age}}",
  "sheet.lock.gender": "性別／呈現：{{gender}}",
  "sheet.lock.appearance": "外貌（必須吻合）：{{appearance}}",
  "sheet.lock.appearanceFaceOnly": "外貌——只鎖定臉／髮／體型（必須吻合）：{{appearance}}。此外貌描述中的衣服、外套、傘、袋、鞋、首飾或道具一律不要出現。",
  "sheet.lock.ignoreCostume": "此外層戲服／道具：本張完全忽略。不要傘、袋、外套或時裝。只出體型或底衫板。",
  "sheet.lock.costume": "戲服／外層設計（必須吻合）：{{costume}}",
  "sheet.lock.tags": "視覺標籤：{{tags}}",
  "sheet.lock.tagsIdentity": "視覺標籤（只取身份；去掉服裝／道具標籤）：{{tags}}",
  "sheet.lock.manner": "只作輕微姿勢／習慣提示（不要改身份）：{{manner}}",
  "sheet.scaffold.repeatMedium": "重申：最終媒介必須是風格 id「{{id}}」（{{family}}）。",
  "sheet.scaffold.wardrobeTag": "服裝層標記：{{tag}}。",
  "sheet.scaffold.layoutLead": "版式：{{layout}}",
  "sheet.scaffold.finalCheck": "最後檢查：若媒介不對，請用正確媒介重出：{{medium}}",
  "sheet.edit.task": "圖像編輯／改版式任務（最高優先——請讀完）：",
  "sheet.edit.target": "目標設定稿方案 id：「{{id}}」。服裝層：{{tag}}。",
  "sheet.edit.ignoreLayout": "完全忽略原圖版式：格數、分隔、鏡頭、裁切與構圖都不要照抄。",
  "sheet.edit.ignoreWardrobe": "若與下方目標服裝層衝突，忽略原圖服裝。",
  "sheet.edit.keepIdentity": "原圖只保留角色身份：臉／頭設計、髮、體型、物種／身體結構、膚色或表面紋、年齡感。",
  "sheet.edit.stripOuter": "去掉原圖所有外層衣甲。體型板：只留膚色連身底衣。底衫層：只留簡單底衣。不要保留原套裝。",
  "sheet.edit.applyProfileCostume": "可套用資料表戲服描述；不要只是把原圖戲服格改色或裁切。",
  "sheet.edit.changeMedium": "如需符合指定畫風，請徹底改渲染媒介。",
  "sheet.edit.noNewPerson": "不要發明另一個人。不要只裁切、放大或改色。",
  "sheet.edit.newComposition": "產出全新設定稿構圖，格數與姿勢必須符合版式區塊。",
  "sheet.edit.checklist": "最後核對：（1）身份對得上原圖臉身（2）版式跟方案「{{id}}」而不是原圖（3）服裝層 {{tag}}（4）媒介 = {{style}}。",
  "sheet.wardrobe.nude": "製作體型比例板（不是成人內容、不是裸拍）：中性臨床棚燈、純灰環幕、專業人體素描姿勢。不要時裝攝影、內衣造型、臥室或華麗佈景。主體穿無縫啞光膚色連身底衣／貼身底衣（或物種相應的啞光連身衣），露出準確體型剪影——臉與髮可見；不要外層戲服、標誌、道具、鞋或配件。底衣只作製作底層（如立體網格），不是外裝。保留臉、髮、體型與表面紋供之後服裝用。忽略此外層戲服描述。明確穿著底衣——絕不要裸身。",
  "sheet.wardrobe.halfBareUpper": "製作上半身局部參考（只限成年角色；臨床人體研究；非色情、非暗示）：中性臨床棚燈、純灰環幕、專業人台站姿。不要時裝攝影、內衣造型、臥室、性化鏡頭。上半身裸露：胸、肩、臂、頸；臉與髮完全可見。下半身只以簡單啞光不透明底褲或包巾覆蓋（製作遮蔽，不是時裝內衣，不要蕾絲或透視）。不要外層上衣、時裝胸衣、道具、鞋、配件或標誌。保留臉、髮、體型與表面紋。忽略此外層戲服描述。",
  "sheet.wardrobe.halfBareLower": "製作下半身局部參考（只限成年角色；臨床人體研究；非色情、非暗示）：中性臨床棚燈、純灰環幕、專業人台站姿。不要時裝攝影、內衣造型、臥室、性化鏡頭。下半身裸露：髖、大腿、腿、腳；臉與髮完全可見。私密處只留最少啞光不透明遮蔽（簡單底褲，製作用途，不是時裝內衣）。上半身只穿簡單啞光上衣（背心、汗衫或包巾，製作遮蔽，不要時裝造型或標誌）。不要外層戲服、道具、鞋或配件。保留臉、髮、體型與表面紋。忽略此外層戲服描述。",
  "sheet.wardrobe.bare": "製作成人解剖體型全裸參考（只限成年角色；臨床人體研究；非色情、非暗示）：中性臨床棚燈、純灰環幕、專業人台站姿。不要時裝攝影、內衣姿勢、臥室、性化鏡頭。主體完全無衣（完整裸身，或物種相應的裸露表面），只留臉與髮——不要衣服、局部遮擋、外層戲服、道具、鞋或配件。保留臉、髮、體型與表面紋。忽略此外層戲服描述。",
  "sheet.wardrobe.base": "製作底衫參考（換裝用底衣，非色情）：只穿簡單素色底衣或物種相應的底層遮蔽（例如平實底褲加汗衫，或簡單包巾）。不要外層戲服、標誌、時裝內衣造型或暗示姿勢。臨床棚燈、灰背景。保留身份供之後穿外裝。忽略此外層戲服描述。",
  "sheet.wardrobe.costume": "製作戲服參考：完整外層造型如描述；材質與剪影可讀，供影片畫面連續。",
  "sheet.layout.bible": "橫向 16:9 角色聖經，剛好三格直向等分由左至右：（1）全身正面站立，腳可見，手臂自然；（2）全身約 45 度；（3）頭肩肖像望鏡頭。每格人物填滿。三格同一張臉、髮、身、戲服。分隔清楚，棚拍。",
  "sheet.layout.turnaround": "橫向 16:9 四面轉，剛好四個全身同比例：正面、左 90 度、全背、右 90 度。中性 A 字站、手臂放鬆、腳著地。完整戲服。人物盡量高大。",
  "sheet.layout.expression": "方形 1:1 緊湊二乘二，剛好四格頭肩特寫：平靜、淺笑、怒、驚。每張臉約佔格九成；髮與衣領一致。不要全身。",
  "sheet.layout.costume": "直向 9:16 戲服板：上約六成大半身全身英雄鏡頭望鏡頭；下帶剛好兩格大特寫（布料／口袋 + 鞋或招牌配件）。材質可讀。",
  "sheet.layout.identity_lock": "橫向 16:9 身份鎖定，剛好兩格：左六成正面大特寫；右四成四分之三側臉。盡量放大五官細節供影片認人；不要全身。",
  "sheet.layout.face_id": "方形 1:1 單張正臉大頭（或主頭部）肖像，含上身，望鏡頭。五官銳利，完全用指定媒介。只一個角色。",
  "sheet.layout.hero": "直向 9:16 單張全身英雄站姿，平視，全身可見。居中自然站，棚景，完整戲服，指定媒介。",
  "sheet.layout.bust": "方形 1:1 半身（胸以上），身略側、臉向鏡頭。對白構圖，衣領可見。",
  "sheet.layout.three_quarter": "直向 9:16 膝上四分之三身，身轉 30–45 度，臉向鏡頭。戲服剪影清楚，手可見。",
  "sheet.layout.profile": "直向 9:16 純左側全身 90 度側影，望左，脊直。真剪影；完整戲服；只一個角色。",
  "sheet.layout.back": "直向 9:16 全身背影，背對鏡頭，髮與戲服背面可讀。出場連續用。",
  "sheet.layout.low_angle": "直向 9:16 英雄低機全身，鏡頭近腰略仰，站姿有力，臉仍清楚，完整戲服。",
  "sheet.layout.high_angle": "直向 9:16 高機四分之三身，鏡頭略高於視線下望，臉可讀，完整戲服。",
  "sheet.layout.action": "橫向 16:9 單人動作定格（走或伸手），銳利無動態模糊，完整戲服，柔和灰環境。",
  "sheet.layout.dialogue": "橫向 16:9 過肩對白：前景同一角色柔肩，後景清楚的臉望鏡頭左。只一個身份。",
  "sheet.layout.body_nude_turnaround": "橫向 16:9 體型四面轉，剛好四個全身同比例：正面、左 90、背、右 90。中性 A 字，臂略離軀幹，腳著地。只穿膚色底衣。臉與髮一致。",
  "sheet.layout.body_nude_front": "直向 9:16 單張全身正面體型板，平視，頭到腳可見，手臂放鬆。體型清楚供服裝。只穿膚色底衣。中性專業站姿。",
  "sheet.layout.body_nude_t_pose": "橫向 16:9 單張全身 T 或 A 字（臂平伸或下斜 30 度），正面，膚色底衣供綁定。腳與肩同寬，臉向前，臨床人台感。",
  "sheet.layout.body_half_bare_turnaround": "橫向 16:9 上半身半裸四面轉，剛好四個全身同比例。中性 A 字，臂略離軀幹。上半裸 + 簡單下裝。臉與髮一致。",
  "sheet.layout.body_half_bare_front": "直向 9:16 單張全身正面上半身半裸板，平視，頭到腳可見。上身裸、下裝簡單素色。體型清楚。中性專業站姿。",
  "sheet.layout.body_half_bare_t_pose": "橫向 16:9 單張全身 T 或 A 字，正面，上半裸供綁定。下裝簡單素色。腳與肩同寬，臉向前，臨床人台感。",
  "sheet.layout.body_half_bare_lower_turnaround": "橫向 16:9 下半身半裸四面轉，剛好四個全身同比例。中性 A 字，腿略分開。下半裸 + 簡單上衣。臉與髮一致。",
  "sheet.layout.body_half_bare_lower_front": "直向 9:16 單張全身正面下半身半裸板。腿裸；上衣簡單素色。體型清楚。中性專業站姿。",
  "sheet.layout.body_half_bare_lower_t_pose": "橫向 16:9 單張全身 T 或 A 字，正面，下半裸供綁定。上衣簡單素色。腳與肩同寬，臉向前，臨床人台感。",
  "sheet.layout.body_bare_turnaround": "橫向 16:9 解剖全身四面轉，剛好四個同比例：正面、左 90、背、右 90。中性 A 字。完全無衣。臉與髮一致。",
  "sheet.layout.body_bare_front": "直向 9:16 單張全身正面解剖板。完全無衣。體型清楚。中性專業站姿。",
  "sheet.layout.body_bare_t_pose": "橫向 16:9 單張全身 T 或 A 字，正面，完全無衣供綁定。腳與肩同寬，臉向前，臨床人台感。",
  "sheet.layout.base_layer_turnaround": "橫向 16:9 底衫四面轉，剛好四個全身：正面、左 90、背、右 90。只穿簡單底衣（素灰或米），不要外層。中性 A 字。",
  "sheet.layout.base_layer_hero": "直向 9:16 單張全身正面，只穿簡單底衣，中性站，頭到腳。剪影乾淨，供之後疊外裝。",
  "sheet.layout.costume_hero": "直向 9:16 單張全身正面，完整外層戲服，英雄站姿，頭到腳，材質可讀。",
  "sheet.layout.costume_turnaround": "橫向 16:9 完整戲服四面轉，剛好四個全身：正面、左 90、背、右 90。同比例 A 字，含鞋與外層。",
  "sheet.layout.costume_detail_board": "方形 1:1 細節板，剛好四格大特寫：布紋、扣件、鞋靴、招牌配件。不要全身；材質保真供服裝連續。",
  "sheet.layout.hands": "方形 1:1 手部特寫（可選小道具）。膚色／表面與身份一致；指節清楚。連續細節表。",
  "sheet.layout.feet_shoes": "方形 1:1 剛好兩大格：左裸足（或爪）立於無縫地板；右為對應設計鞋靴（若戲服有）。剪影清楚供換裝。",
  "sheet.layout.accessories": "方形 1:1 配件板：最多四格產品式特寫——帽、袋、武器、首飾或戲服描述中的招牌道具。潔淨棚拍，不要全身。",
  "sheet.layout.silhouette": "直向 9:16 純黑實心全身正面剪影，白或淺灰底，無內部細節，外輪廓可讀供換裝比例。空間夠可加淡側影——寧可單張強正面剪影。",
  "plate.scene.emptySet": "短劇畫面連續用空鏡場地板：不要主角臉、具名演員；最多遠處極小剪影作比例。保留建築、材質、招牌與關鍵陳設。",
  "plate.scene.lock.lead": "為短劇畫面連續製作場地參考靜圖。",
  "plate.scene.lock.identity": "空間身份鎖定：各格同一建築、材質、招牌與格局語言。",
  "plate.scene.lock.forbidden": "禁止：可辨認名人臉、具名角色肖像、擠擁的主角特寫、浮水印、介面字幕。",
  "plate.scene.lock.quality": "畫質：材質銳利、垂直穩定、專業美術攝影／原畫保真。",
  "plate.scene.lock.name": "地點名稱：{{name}}",
  "plate.scene.lock.place": "場地描述：{{place}}",
  "plate.scene.lock.type": "空間類型：{{type}}",
  "plate.scene.lock.time": "時段：{{time}}",
  "plate.scene.lock.weather": "天氣：{{weather}}",
  "plate.scene.lock.mood": "氣氛：{{mood}}",
  "plate.scene.lock.lighting": "燈光設計：{{lighting}}",
  "plate.scene.lock.palette": "色盤：{{palette}}",
  "plate.scene.lock.set": "陳設：{{set}}",
  "plate.scene.lock.tags": "視覺標籤：{{tags}}",
  "plate.scene.scaffold.repeatMedium": "重申：媒介必須是風格 id「{{id}}」（{{family}}）。",
  "plate.scene.scaffold.layer": "場地板層：{{layer}}。",
  "plate.scene.scaffold.finalCheck": "最後檢查：媒介 {{style}} 正確；沒有主角臉；場地身份鎖定。",
  "plate.scene.edit.task": "圖像編輯／場地改風格任務（最高優先）：",
  "plate.scene.edit.keep": "保留原圖場地身份：建築體量、材質、招牌、關鍵陳設格局。",
  "plate.scene.edit.change": "按下方場地板方案改媒介及／或鏡頭版式。",
  "plate.scene.edit.forbid": "不要發明另一個地方。不要加主角臉。",
  "plate.scene.layout.establishing": "橫向 16:9 建立鏡頭，拍完整外觀或主體量，地標可讀，地平或天花線穩定，有縱深。",
  "plate.scene.layout.hero_plate": "橫向 16:9 英雄場地靜圖——本場地的封面格。構圖有力，舞台地面或街道清楚，供之後走位。",
  "plate.scene.layout.three_quarter_space": "橫向 16:9 四分之三空間：前景框、中景表演區、背景縱深。適合對白舞台，不要臉。",
  "plate.scene.layout.identity_lock": "橫向 16:9 剛好兩等格同一場地：（1）正面主角度（2）約 45 度。同一材質、招牌、色盤。",
  "plate.scene.layout.low_angle": "直向 9:16 低機仰望建築／天花／棚頂，製造戲劇尺度。不要臉。",
  "plate.scene.layout.high_angle": "橫向 16:9 高機平面／街道幾何，供走位。不要臉。",
  "plate.scene.layout.pov_enter": "橫向 16:9 第一人稱由門口或巷口進入。門檻內空鏡。",
  "plate.scene.layout.over_shoulder_empty": "橫向 16:9 過肩空鏡：前景只有匿名肩剪影，後景場地清楚，供對白走位。",
  "plate.scene.layout.day_clear": "橫向 16:9 同一場地晴晝光，自然日向，影子可讀，表面乾燥。",
  "plate.scene.layout.golden_hour": "橫向 16:9 同一場地黃金時段：暖長影、琥珀輪廓光、浪漫短劇氣氛，不要臉。",
  "plate.scene.layout.night_neon": "橫向 16:9 同一場地夜晚實燈／霓虹／路燈，可有青洋紅溢光與濕地，不要臉。",
  "plate.scene.layout.rain_wet": "橫向 16:9 同一場地下雨：濕瀝青／倒影、雨絲、偏冷調，傘只作遠處道具，不要臉。",
  "plate.scene.layout.fog_mood": "橫向 16:9 同一場地霧／煙：柔和層次、低飽和、神秘，建築仍可讀，不要臉。",
  "plate.scene.layout.set_dressing": "方形 1:1 桌／櫃／架陳設板，本場地關鍵道具，不要人。",
  "plate.scene.layout.material_board": "方形 1:1 材質連續板：本場地牆、地、金屬／木、布。近距，不要臉、不要全身人物。",
  "plate.scene.layout.signage_prop": "方形 1:1 可讀招牌／地標道具特寫，鎖定場地身份。字形銳利（需要時可發明符號）。不要臉。",
  "plate.scene.layout.lighting_ref": "橫向 16:9 空鏡燈光參考：主光方向清楚、補光、實燈，不要角色。",
  "plate.prop.lock.lead": "為短劇畫面連續製作道具參考靜圖。",
  "plate.prop.lock.name": "道具名稱：{{name}}",
  "plate.prop.lock.desc": "描述（必須吻合）：{{desc}}",
  "plate.prop.lock.material": "材質：{{material}}",
  "plate.prop.lock.size": "尺寸筆記：{{size}}",
  "plate.prop.lock.condition": "狀態／舊損：{{condition}}",
  "plate.prop.lock.tags": "標籤：{{tags}}",
  "plate.prop.lock.forbidden": "禁止：名人臉、浮水印、干擾身份的多餘雜物。",
  "plate.prop.scaffold.repeatMedium": "重申：媒介必須是風格 id「{{id}}」。",
  "plate.prop.scaffold.finalCheck": "最後檢查：同一道具身份；媒介 {{style}}。",
  "plate.prop.edit.task": "圖像編輯／道具改風格：",
  "plate.prop.edit.keep": "保留原圖同一道具身份（剪影、材質、紋樣）。",
  "plate.prop.edit.change": "按需要改媒介／鏡頭。不要發明另一件物件。",
  "plate.prop.layout.hero": "方形 1:1 單件道具英雄靜圖，置中，潔淨灰環幕，材質銳利，不要人臉，整件可見。",
  "plate.prop.layout.three_quarter": "方形 1:1 同一道具四分之三角度，棚燈，剪影可讀；除非比例需要，否則不要手。",
  "plate.prop.layout.detail": "方形 1:1 道具招牌細節大特寫（刻字、扣、螢幕、舊損）。不要臉。",
  "plate.prop.layout.material": "方形 1:1 道具表面材質板：金屬／木／布紋，不要全身人物。",
  "plate.prop.layout.in_hand_scale": "橫向 16:9 比例參考：匿名手或剪影握道具。臉出畫或完全匿名。道具是主體。",
  "action.geometry.panelCount": "格數不可改：必須剛好 {{n}} 格。數清楚：{{list}}。",
  "action.geometry.lockGrid2x3": "排版鎖定：兩行三列共六格。上行必須 1、2、3。下行必須 4、5、6。禁止二乘二、四格、三乘二數錯、單張英雄鏡頭、較少格拼貼。若想只畫四格——停下來畫滿六格。",
  "action.geometry.lockGrid2x2": "排版鎖定：兩行兩列共四格。禁止二乘三六格、橫條、單格。",
  "action.geometry.lockStrip": "排版鎖定：單行橫向剛好 {{n}} 格（1 行 × {{n}} 列）。禁止二乘二、少於 {{n}} 格、未指定的多行疊放。",
  "action.geometry.order": "格序即動作時間：第 1 格＝第一拍，第 {{n}} 格＝最後一拍。",
  "action.geometry.reading": "閱讀順序：先左至右，再上至下（多行時）。",
  "action.geometry.numbers": "每格左上角大號粗體格號 1 至 {{n}}。1 到 {{n}} 每個數字必須出現一次。",
  "action.geometry.panelLine": "第 {{i}}／{{n}} 格（{{label}}）：一個獨立而連續的瞬間——姿勢／階段與其他格不同；不要複製姿勢。",
  "action.geometry.caption": "每格下方小字香港繁體說明，對應節拍標籤。",
  "action.geometry.identity": "全板各格角色身份、服裝、道具必須連貫。",
  "action.geometry.layout.strip-2": "一張橫向圖：單行兩格並排故事板（1 行 × 2 列），粗白分隔。",
  "action.geometry.layout.strip-3": "一張橫向圖：單行三格故事板（1 行 × 3 列），粗白分隔。",
  "action.geometry.layout.grid-2x2": "一張方形圖：二乘二故事板剛好四格，粗白分隔，先左至右再上至下。",
  "action.geometry.layout.strip-4": "一張闊橫向圖：單行四格故事板（1 行 × 4 列），粗白分隔。",
  "action.geometry.layout.strip-5": "一張闊橫向圖：單行五格故事板（1 行 × 5 列），粗白分隔。",
  "action.geometry.layout.grid-2x3": "一張橫向圖：剛好六格，兩行三列（上 1-2-3、下 4-5-6），粗白分隔，先左至右再上至下。",
  "swap.costume.task": "圖像編輯／換裝任務（最高優先——下筆前請讀完）：",
  "swap.costume.sameCharacter": "你只為原圖同一角色換上新的外層服裝。",
  "swap.costume.identity": "身份鎖定（不得改）：臉／頭形、眼、髮色髮型、體型、物種／身體結構、膚色或表面紋、年齡感。",
  "swap.costume.pose": "姿勢鎖定：保留原圖身體姿勢與鏡頭，除非下方版式要求多視圖。",
  "swap.costume.replace": "服裝替換（必須）：去掉原圖所有外層衣甲、外套、裙、制服、外裝與不合的鞋。",
  "swap.costume.paint": "然後只畫下方描述的新外層——覆蓋完整、剪影正確、材質可讀，鞋履與外層配件相符。",
  "swap.costume.new": "新外層戲服（必須吻合，高優先）：{{costume}}",
  "swap.costume.add": "若原圖是裸身或只有底衫：在保留解剖與底層邏輯下加上完整外層。",
  "swap.costume.complete": "若原圖已有戲服：徹底換掉——不要與舊裝混合、疊層或殘影。",
  "swap.costume.edges": "衣緣須正確落在肩、腰、腕、踝；不要漂浮布料、不要肢體融合。",
  "swap.costume.forbidden": "禁止：改物種、改年齡、改臉、改體型、第二人、色情姿勢、浮水印、字幕、介面邊框。",
  "swap.costume.nonHuman": "非人主體：按物種穿上符合戲服描述的外層／裝備。",
  "swap.costume.subject": "主體：{{name}}",
  "swap.costume.age": "年齡／成熟度：{{age}}",
  "swap.costume.gender": "性別／呈現：{{gender}}",
  "swap.costume.appearance": "外貌鎖定：{{appearance}}",
  "swap.costume.tags": "視覺標籤：{{tags}}",
  "swap.costume.manner": "只作習慣提示：{{manner}}",
  "swap.costume.checklist": "最後核對：（1）臉身與原圖相同（2）只見新戲服（3）媒介 = {{style}}（4）潔淨棚或中性背景。",
  "swap.costume.layout.hero_front": "直向 9:16 單張全身正面站姿，頭到腳可見，中性英雄站，手臂放鬆，腳著地。只一個角色。",
  "swap.costume.layout.three_quarter": "方形 1:1 單張約 45 度全身，盡量頭到腳，新戲服剪影可讀。",
  "swap.costume.layout.profile": "直向 9:16 單張全身真側影（90 度），頭到腳，中性站，側縫與剪影可讀。只一個角色。",
  "swap.costume.layout.back": "直向 9:16 單張全身背影，頭到腳，臂略離身，外套／裙／髮背面與後剪影清楚。只一個角色。",
  "swap.costume.layout.bust": "直向 3:4 單張半身（胸以上），衣領、領口、肩、外層與臉飾可讀；不是全身裁切。只一個角色。",
  "swap.costume.layout.detail_fabric": "方形 1:1 戲服細節板：只拍新外層的布紋、鈕、拉鏈、繡、皮帶五金與材質過渡；不要整場、不要第二人。",
  "swap.costume.layout.turnaround": "橫向 16:9 四面轉，剛好四個全身同比例：正面、左 90、背、右 90。中性 A 字，每面都是完整新戲服。",
  "swap.atmosphere.task": "圖像編輯／換氣氛任務（最高優先）：",
  "swap.atmosphere.keep": "保留原圖場地身份：建築體量、牆、平面線索、招牌、家具格局、鏡頭角度。",
  "swap.atmosphere.replace": "徹底替換：時段、天氣、天空、實燈顏色、濕度、霧、霓虹強度如描述。",
  "swap.atmosphere.new": "新氣氛（必須吻合）：{{atmo}}",
  "swap.atmosphere.forbidden": "禁止：把建築改成另一個地方、加主角臉、浮水印、字幕。",
  "swap.atmosphere.location": "地點：{{title}}",
  "swap.atmosphere.place": "場地：{{place}}",
  "swap.atmosphere.set": "陳設鎖定：{{set}}",
  "swap.atmosphere.tags": "標籤：{{tags}}",
  "swap.atmosphere.checklist": "最後核對：同一場地幾何；只改氣氛；媒介 {{style}}；不要主角臉。",
  "swap.atmosphere.repeatMedium": "重申：媒介必須是風格 id「{{id}}」（{{family}}）。",
  "swap.atmosphere.layout.wide": "橫向 16:9 全場構圖盡量貼近原圖。",
  "swap.atmosphere.layout.hero": "橫向 16:9 英雄場地靜圖，同一建築，只更新氣氛。",
  "swap.atmosphere.layout.detail": "方形 1:1 氣氛細節：濕面／實燈／天空，仍可認出同一場地。",
}
