import type { PromptCopyTable } from './keys'

export const zhHkPromptCopy: PromptCopyTable = {
  "speechLock.named": "SPEECH LOCK · 角色「{{who}}」：可聽語音與口型必須只用{{primaryName}}（{{primary}}）。禁止改講{{forbid}}或其他語言。每段都要同一種口白。不要翻譯對白。",
  "speechLock.unnamed": "SPEECH LOCK · 出場角色：可聽語音與口型必須只用{{primaryName}}（{{primary}}）。禁止改講{{forbid}}或其他語言。每段都要同一種口白。不要翻譯對白。",
  "speechLock.namedMulti": "SPEECH LOCK · 角色「{{who}}」：可聽語音與口型必須用{{primaryName}}（{{primary}}）。只有腳本該句已經是以下語言才可以講第二種：{{extras}}。禁止第三種語言。禁止每段轉換。禁止改講{{forbid}}。不要翻譯對白。",
  "speechLock.unnamedMulti": "SPEECH LOCK · 出場角色：可聽語音與口型必須用{{primaryName}}（{{primary}}）。只有腳本該句已經是以下語言才可以講第二種：{{extras}}。禁止第三種語言。禁止每段轉換。禁止改講{{forbid}}。不要翻譯對白。",
  "storyBeats.system": "你為短劇時間軸撰寫「劇情段落」——每一段 = 一小段 AI 影片的完整拍攝腳本，而非一句對白。\n每段必須有豐富表演內容：心情、氣氛、動作、表情、可選鏡頭／聲效，以及 0 至多句口白（常見 1–4 句）。\n只回傳 JSON 陣列（不要代碼塊）。每項形狀：\n{\"characterName\":\"…\",\"characterNames\":[\"…\"],\"sceneHint\":\"…\",\"propName\":\"…\",\"mood\":\"…\",\"atmosphere\":\"…\",\"camera\":\"…\",\"sfx\":\"…\",\"units\":[{\"type\":\"action\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"expression\",\"who\":\"…\",\"text\":\"…\"},{\"type\":\"dialogue\",\"who\":\"…\",\"line\":\"…\",\"tone\":\"…\",\"parenthetical\":\"…\"},{\"type\":\"note\",\"text\":\"…\"}]}\n規則：\n- dialogue.line 只寫角色講出口的話，不要把動作寫進口白。\n- 肢體動作放 action；表情微表演放 expression；語氣放 tone／parenthetical。\n- 一段可有多句對白（對話回合或自語）。\n- 允許純動作段（無對白）。\n- 寫 4–8 段。角色名必須用提供名單。\n- 要有衝突、可視動作、可拍細節。\n- 忠於已提供的標題、風格、選角與場景。不要擅自擴世界。\n- 口白：dialogue.line 必須用該角色主語言寫（見角色名單）。禁止段與段轉語言。除非角色名單寫明，否則不要改寫成其他語言。",
  "storyBeats.userLead": "生成完整「短片腳本」段落：使用下方全部選角、場景、道具、風格與構想。",
  "storyBeats.eachBeat": "每段要有心情、氣氛、動作／表情，以及可選的多句對白。",
  "storyBeats.story": "故事：{{title}}",
  "storyBeats.style": "風格：{{style}}",
  "storyBeats.userDir": "用戶指示：{{idea}}",
  "storyBeats.cast": "角色：",
  "storyBeats.scenes": "場景：",
  "storyBeats.props": "道具：{{props}}",
  "storyBeats.returnJson": "只回傳段落 JSON 陣列。",
  "storyBeats.noCast": "（無角色）",
  "storyBeats.noScenes": "（無場景 — sceneHint 可寫地點）",
  "storyBeats.none": "（無）",
  "videoPolish.system": "你為短劇 AI 圖生影片模型撰寫「一條」最終 image-to-video 導演提示詞。\n只回傳提示詞正文——不要 markdown 代碼塊、標題或解釋。\n規則：\n- 提示詞全文用用戶介面語言書寫；角色姓名與口白語言要求須清楚標示。\n- 人物靜圖：IDENTITY LOCK（臉、髮、體型、服裝、顏色）。場景靜幀：SPACE LOCK（建築、材質、格局、招牌、色盤）。除非材料點名，否則勿新增角色臉。\n- 凡已提供且影響外形、動作、口白、氣氛或場地的人設／soul／段落／地點資料均須用上；空白欄位可略。\n- 只按材料與 seed 補齊可拍細節；勿引入固定樣本世界、Demo 故事、或材料／seed 未出現的事實。\n- 長篇 soul.md 須濃縮為可拍的表演與身份要點，不可整篇照貼。\n- 片長跟材料之中的實際秒數。動作連貫。無字幕、logo、浮水印、無關路人。\n- 除非劇情要求，否則解剖結構正常（雙手雙腳）。\n- 多角色時保持每位主體一致；主焦點優先。\n- 若材料含 HARD RULES（生成鐵則），必須保留並放在輸出最尾（最高優先）。\n- SPEECH LOCK 必須保留：不得刪改或翻譯；語言代碼要寫成全名。每段跟角色主口語，禁止段與段轉語言，禁止翻譯對白。\n- 導演修訂可調整氣氛／動作，但不得違反 HARD RULES。",
  "videoPolish.hardRulesKeep": "HARD RULES／生成鐵則（最高優先——保留每一行；[Character · 名] 等物件標籤不可刪）。必須將完整 HARD RULES 區塊放在輸出最尾。不得削弱、刪除或套錯主體。",
  "clip.task": "任務：短劇時間軸片段（圖生影片）。",
  "clip.hasRef": "可能附有參考靜圖——相關時鎖定身份／場地連續性。",
  "clip.characters": "角色：",
  "clip.scene": "場景：",
  "clip.prop": "道具：",
  "clip.action": "動作指導：",
  "clip.beat": "段落／對白：",
  "clip.prev": "前一段連續性：",
  "clip.revision": "導演修訂（必須遵守）：",
  "clip.templateDraft": "模板草稿（請改進）：",
  "intro.task": "任務：自我介紹選角短片（圖生影片）。",
  "intro.hasRef": "參考靜圖會交予影片 API——必須鎖定該圖身份。",
  "intro.noRef": "本文無靜圖路徑；仍須鎖定人設外貌／戲服。",
  "intro.dossier": "角色檔案：",
  "intro.templateDraft": "模板草稿（請改進；勿忽略檔案）：",
  "common.durationAspect": "時長：{{seconds}} 秒。畫面比例：{{aspect}}。",
  "common.templateDraft": "模板草稿：",
  "improve.mode": "改進模式：合併下方所有來源輸出完整結果。除非用戶明確要求改身份，否則保持核心一致。表單稀疏時以額外上下文為準；用戶明確要求更改時以指示為準。",
  "improve.draftDefault": "目前表單欄位（已填內容）：",
  "improve.userRequest": "用戶改進要求（可留空 = 全面潤飾並合併以上內容）：",
  "improve.emptyDefault": "（全面潤飾：適合短劇／出圖／出片 continuity）",
  "improve.createDefault": "構想／方向：",
  "improve.explicitContext": "僅限本次請求明確附上的上下文（作 continuity；勿引入其他樣本世界；與 idea／表單衝突時以用戶為準）：",
  "improve.storyTitle": "故事標題：{{title}}",
  "improve.styleNote": "風格備註：{{style}}",
  "improve.closingDefault": "請立即輸出完整結果。",
  "storyMeta.system": "你是短劇主創／視覺總監。根據故事標題與構想，寫簡潔可拍的風格備註（Style bible）以及出圖／出片「生成鐵則」。只回傳 JSON（不要代碼塊）：{\"styleNote\":\"2–5 句：氣氛、光線、鏡頭、色調、節奏\",\"hardRules\":\"3–8 句必須／禁止\"}。要具體、適合 AI 影片／出圖延續。用提供的標題、構想、現有風格／鐵則與上下文。不要擅自發明風格。",
  "storyMeta.draftLabel": "目前故事欄位：",
  "storyMeta.createLabel": "故事構想／標題：",
  "storyMeta.emptyPolish": "（潤飾視覺風格備註與生成鐵則，利於 AI 出片 continuity）",
  "storyMeta.closing": "只回傳 JSON：{\"styleNote\":\"…\",\"hardRules\":\"…\"}。兩個鍵都必填且非空。",
  "storyMeta.contextLabel": "故事上下文（角色／場景／道具）：",
  "character.system": "你是專業短劇角色設定師，專門為 AI 影片／短劇生成「可拍、可認、可一致」的角色聖經。用戶會給一段角色 idea。角色可以是人類、動物、鬼靈、魔物、機械、虛擬形象或其他設計體——依 idea 而定，勿強行寫成人類。只輸出一個 JSON 物件。spokenLanguages：BCP-47 代碼陣列，例如 [\"yue\",\"en\"]。非語言角色用 []。避免空泛形容；用可拍攝的細節。同一角色必須視覺一致。",
  "character.draftLabel": "目前 Profile 表單欄位（已填內容）：",
  "character.soulLabel": "已連結 soul.md／角色聖經（主要身份與性格依據）：",
  "character.createLabel": "角色 idea：",
  "character.emptyPolish": "（全面潤飾：將 soul 與表單合併進完整 Profile）",
  "character.closing": "請立即輸出完整 JSON。必填鍵：{{keys}}。visualTags 為逗號分隔字串（禁止標籤陣列）；spokenLanguages 可以是代碼陣列。",
  "scene.system": "你是短劇場景／場景空間設計師，服務 AI 影片 continuity。請輸出可拍的地點聖經 + 本場可演劇本片段。只回傳一個 JSON 物件。title＝短地名；description＝建築、物料、地標；script＝本場對白／動作／鏡頭。",
  "scene.draftLabel": "目前場景表單欄位（已填內容）：",
  "scene.charsLabel": "故事角色：",
  "scene.propsLabel": "故事道具：",
  "scene.priorLabel": "既有場景（continuity）：",
  "scene.createLabel": "場景 idea：",
  "scene.emptyPolish": "（全面潤飾地點與本場劇本，利於出片 continuity）",
  "scene.closing": "請立即輸出完整 JSON。必填鍵：{{keys}}。缺鍵無效。visualTags 必須是逗號分隔字串，禁止陣列。",
  "prop.system": "你是短劇道具設計師，服務 AI 影片 continuity。只回傳一個 JSON。description：可畫細節；material／sizeNotes／condition 具體。",
  "prop.draftLabel": "目前道具表單欄位（已填內容）：",
  "prop.createLabel": "道具 idea：",
  "prop.emptyPolish": "（全面潤飾道具外觀，利於出片 continuity）",
  "prop.closing": "請立即輸出完整 JSON。必填鍵：{{keys}}。缺鍵無效。visualTags 必須是逗號分隔字串，禁止陣列。",
  "prop.fallbackName": "道具",
  "action.system": "你是短劇動作指導。只輸出有效 JSON，描述一項可拍攝的動作指導。要具體：身體部位、節奏、力度、道具路徑、走位。不要 markdown。",
  "action.storyContext": "故事脈絡（可選）：{{title}}",
  "action.styleNote": "風格備註：{{style}}",
  "action.existingDraft": "現有草稿（請潤飾補全）：",
  "action.userIdea": "用戶構想：{{idea}}",
  "action.closing": "只回傳 JSON。必填鍵：{{keys}}。visualTags 為逗號分隔字串，禁止陣列。",
  "profile.mustEveryKey": "必須輸出列表中的每一個鍵：{{keys}}。",
  "profile.valuesAreStrings": "每個值必須是 JSON 字串（不可 null、不可用 JSON 陣列）。真的不知道才可空字串。",
  "profile.visualTagsRule": "visualTags：用用戶介面語言的單一逗號分隔字串——禁止 JSON 陣列。",
  "profile.fillConcrete": "各鍵請盡量填具體細節，利於短劇 continuity。",
  "common.rules": "規則：",
  "common.none": "（無）",
  "intro.soul": "soul.md（作為表演／身份完整來源）：\n{{soul}}",
  "intro.matchBible": "（跟從角色人設語言）",
  "invent.sources": "依據來源（優先序）：（1）用戶 idea／指示，（2）已填表單，（3）僅當「本次 prompt 已寫出」的額外上下文（soul、選角、故事區塊等），（4）附上的參考圖。",
  "invent.create": "創作模式（表單空白／極少）：按 idea／圖自由創作，補齊可拍攝的關鍵欄位，內容須與用戶構想相關——勿留空必填鍵。",
  "invent.improve": "改進模式（表單已有內容）：潤飾並補齊空白欄，與已填內容一致；除非用戶要求，否則勿改核心身份。",
  "invent.noImport": "不得從「本次 prompt 未出現」的來源引入身份、劇情、天氣、職業、地點、時代或風格（禁止 active 故事、Demo 樣本、App 預設世界觀）。",
  "invent.storyBlock": "若下方明確附有故事／風格區塊：僅作 continuity；不可覆蓋用戶明確 idea。",
  "character.keysLead": "只輸出一個 JSON 物件（不要 markdown），鍵名必須是：{{keys}}",
  "character.ruleSpoken": "spokenLanguages：角色使用的語言，JSON 字串陣列（可多選），BCP-47／ISO 代碼，例如 [\"yue\",\"en\"]。非語言角色用 []。",
  "character.ruleIdentity": "同一角色必須視覺一致，方便之後多角度參考圖與影片生成。",
  "scene.keysLead": "只回傳一個 JSON 物件（不要 markdown），鍵名：{{keys}}",
  "scene.suggestLead": "為故事「{{title}}」建議第 {{n}} 個可用場景（場地／環境設定）。",
  "scene.suggestPlotFocus": "劇情焦點：{{label}}",
  "scene.suggestStyle": "風格：{{style}}",
  "scene.suggestExisting": "庫內／故事已有場地：{{titles}}",
  "scene.suggestChars": "角色（上下文）：",
  "scene.suggestProps": "道具（上下文）：",
  "scene.suggestSegment": "選定劇情段落詳情：",
  "scene.suggestBeats": "故事場次／段落：",
  "scene.suggestClosing": "回傳完整場景 JSON。請設計一個可重複使用的獨立場地（全域場景庫資產），須貼合選定劇情焦點，並與已有場地有所區別。",
  "scene.fallbackName": "場景",
  "scene.ideaFromImage": "請根據附上的參考圖，完整填寫場景資料。",
  "scene.polishIdea": "全面潤飾",
  "prop.keysLead": "只回傳一個 JSON，鍵名：{{keys}}",
  "action.fieldsLead": "欄位：{{keys}}。",
  "soul.system": "你為短劇／影視角色撰寫 production 用 soul.md（單檔 Markdown）。\n只輸出完整 Markdown 文件（不要代碼塊圍欄、不要解說）。\n結構（請用以下 ## 標題）：\n# {角色名}\n## 身份 Identity\n## 外貌 Appearance\n## 服裝與輪廓 Costume\n## 性格與聲線 Personality & voice\n## 使用語言 Spoken languages\n## 小習慣 Mannerisms\n## 背景 Backstory\n## 關係 Relationships\n## 表演與對白風格\n## 一致性硬規則 Hard rules\n## 視覺標籤 Visual tags\n規則：\n- 短劇可拍、可辨認、可一致；細節須具體。\n- 依據：Profile 表單 + 現有 soul + 用戶指示。除非所選配方允許，否則勿用本次未提供的來源臆造。\n- 對白／配音必須尊重 profile 的 spokenLanguages。\n- 硬規則用 5–10 條 bullet，方便之後圖像／對白 AI 遵守。\n- 用用戶介面語言書寫（香港書面語優先，若介面是其他語言就跟介面）。\n- 可選開頭 YAML frontmatter（name / tags），非必須。",
  "soul.improveMode": "改進模式：合併 Profile 表單 + 現有 soul，輸出更新後完整 soul.md。除非要求改身份，否則保持核心一致。",
  "soul.createMode": "根據以下角色設定撰寫完整 soul.md（合理補齊空白；不要換成另一個人）：",
  "soul.profileFields": "Profile 表單欄位（已填內容）：",
  "soul.existing": "現有 soul.md（合併／改進；勿丟有用細節）：",
  "soul.userRequest": "用戶指示：{{request}}",
  "soul.extraContext": "本次一併提供的上下文（有用就用；仍以 profile 為準）：",
  "soul.returnOnly": "只輸出完整 soul.md Markdown 正文。",
  "wardrobe.system": "你是短劇服裝與視覺風格顧問。根據角色與劇情，提出一套完整外裝方案。只回傳一個 JSON 物件（不要 markdown 圍欄）：{\"name\":\"短名稱\",\"costume\":\"詳細外裝描述（供出圖／影片）\",\"artStyle\":\"下列其一\",\"rationale\":\"一兩句理由\"} artStyle 必須是：{{styleIds}} costume 要具體：材質、顏色、輪廓、鞋履、配件。年齡表述須得體；禁止對未成年做性化描述。保留既有外貌身份，只設計服裝與風格。用角色欄位與已提供的劇情／故事上下文。不要擅自發明造型世界。",
  "wardrobe.improveMode": "改進／建議模式：使用下方全部角色欄位與劇情上下文。",
  "wardrobe.characterForm": "角色（完整表單）：",
  "wardrobe.soulExcerpt": "soul.md 摘要：\n{{soul}}",
  "wardrobe.userRequest": "用戶指示：{{request}}",
  "wardrobe.storyContext": "故事／製作上下文（有就用；勿另起一個世界）：",
  "wardrobe.style": "風格：{{style}}",
  "wardrobe.segment": "選定劇情段落：{{label}}",
  "wardrobe.sceneContext": "場景／段落／對白摘錄：",
  "wardrobe.noScenes": "（尚無場景）",
  "wardrobe.proposeNew": "請提出一套符合劇情的新戲服（避免與已有造型重複）。",
  "fill.system": "你負責補齊短劇資產設定中「仍然空白」的欄位。\n只回傳一個 JSON 物件，且只能包含這些鍵：{{keys}}。\n每個值必須是非空 JSON 字串（不可 null、不可 JSON 陣列）。\n若含 visualTags：用用戶介面語言的逗號分隔字串（格式例：\"gold, necklace\"，勿照抄例子，須貼合本資產）——禁止陣列。\n只根據已有部分設定及參考圖補齊；勿另起未見於 partial／圖的劇情、地點或樣本世界。\n不要 markdown、不要解說。",
  "fill.userPartial": "已有部分設定（勿矛盾）：",
  "fill.userOnly": "只補齊這些空白鍵：{{keys}}。",
  "fill.userReturn": "只回傳含上述鍵的 JSON；每值為非空字串。",
  "imageGen.multiRef": "另有 {{n}} 張已選參考圖：主編輯底圖為第一張，其餘作身份一致輔助，勿換成另一物件／主體。",
  "residual.sceneLink": "第 {{n}} 場：{{short}}",
  "residual.beatSegment": "段落 {{n}} · {{who}}{{tail}}",
  "residual.unknown": "未指定",
  "residual.story": "故事",
  "beat.mood": "【心情】{{text}}",
  "beat.atmo": "【氣氛】{{text}}",
  "beat.camera": "【鏡頭】{{text}}",
  "beat.sfx": "【聲效】{{text}}",
  "beat.action": "【動作】{{text}}",
  "beat.actionWho": "【動作｜{{who}}】{{text}}",
  "beat.expr": "【表情】{{text}}",
  "beat.exprWho": "【表情｜{{who}}】{{text}}",
  "beat.dialogue": "【對白｜{{who}}】{{body}}",
  "beat.dialogueTone": "【對白｜{{who}}｜{{tone}}】{{body}}",
  "beat.whoUnknown": "？",
  "beat.template": "【心情】緊繃、猶豫\n【氣氛】門縫暖光；雨砸地\n【鏡頭】中景，跟手推近\n【聲效】雨、布料摩擦\n【動作｜角色名】摘下安全帽；盯門縫暖光；手伸進外套內袋\n【表情｜角色名】眉心緊鎖，呼吸一滯\n【對白｜角色名｜低聲沙啞】又係落雨……\n【對白｜角色名｜自語】（停半拍）你……仲喺度？",
  "vision.preamble": "已附上參考靜圖。請主要根據圖片填寫此{{what}}全部欄位；可結合構思／草稿潤飾。",
  "vision.character": "角色（名稱、外貌、戲服、年齡、性別、標籤等）",
  "vision.scene": "場景（標題、描述、光影、氣氛、佈景、標籤等）",
  "vision.prop": "道具（名稱、描述、材質、尺寸、狀態、標籤等）",
  "vision.action": "動作（名稱、說明、節奏、意圖、鏡頭備註、標籤等）",
  "vision.costume": "戲服（名稱、完整造型描述）",
  "still.header": "SINGLE KEYFRAME STILL for short-drama video continuity（單格關鍵幀，不是多格板）。產出一張對應下方鏡頭的主畫面。無文字、logo、浮水印、UI。清晰可製作。",
  "still.revision": "用戶改進要求（必須套用）：{{notes}}",
  "still.regenTask": "任務：修訂 image-to-video 導演提示詞，並保持可作靜幀 keyframe 簡報。",
  "still.userImprove": "用戶改進要求：\n{{notes}}",
  "still.currentPrompt": "目前專業提示詞：",
  "still.hardRules": "HARD RULES／生成鐵則（必須保留於輸出最尾；不得刪除或削弱）：",
  "mediaGen.writeOne": "請撰寫「一條」最終短劇靜圖／多格指示圖生成 prompt。",
  "mediaGen.returnOnly": "只回傳 prompt 正文——不要 markdown 代碼塊、標題或解釋。",
  "mediaGen.singleComposite": "輸出描述「單一合成圖」（只 export 一張）。",
  "mediaGen.lockRefs": "附圖圖序與下方 Ref# 一致，須作視覺 ground truth。身份／戲服／場景／道具必須鎖定附圖，禁止換成另一人、另一店或另一物。",
  "mediaGen.videoSystem": "你是短劇 image-to-video 導演 prompt 撰寫者。",
  "mediaGen.videoMerge": "將材料合併為「一條」專業短片 video prompt。",
  "mediaGen.videoInclude": "須含：身份鎖定、鏡頭運動、表演／對白、節奏、光影連續。",
  "mediaGen.videoFacts": "只用材料與 seed 中的事實；勿引入固定樣本世界或 Demo 故事。",
  "mediaGen.videoNoSwap": "有附圖時禁止換成另一演員、場景或道具。",
  "mediaGen.videoHardRules": "有 HARD RULES 則置於文末。",
  "mediaGen.imageSystem": "你是短劇靜圖／指示圖 prompt 導演。",
  "mediaGen.imageMergeStills": "將用戶勾選材料與附圖合併為「一條」出圖 prompt。",
  "mediaGen.imageMergeText": "將用戶勾選文字材料合併為「一條」出圖 prompt。",
  "mediaGen.imagePriority": "最高優先：附圖中的臉／服裝／場景／道具必須一致。",
  "mediaGen.imageNoSwap": "有角色／場景靜圖時，禁止換成無關沙龍店員或另一間店。",
  "mediaGen.imageFacts": "只用材料與 seed 中的事實；勿引入固定樣本世界或 Demo 故事。",
  "mediaGen.imageLayout": "若要求多格板，保留精確格數與分隔。",
  "mediaGen.imagePackage": "若有 LAYOUT／出圖方案區塊，最終 prompt 必須嚴格執行該 layout（格數、姿勢、構圖）。",
  "mediaGen.imageHardRules": "有 HARD RULES 則置於文末。",
  "mediaGen.directorFallback": "圖生影片：以呢張關鍵幀做短劇片段。身份、戲服、場景、構圖須鎖定關鍵幀，由此畫面開始動。",
  "mediaGen.directorFallbackCam": "鏡頭運動與表演清楚；對白口型然後腳本；無字幕、無浮水印。",
  "charIntro.task": "圖生影片：以參考圖中的同一人物，拍一段短劇選角用「自我介紹」短片。",
  "charIntro.identityLock": "身份鎖定：臉、髮型、體型、年齡感、服裝與顏色必須與參考靜幀一致，不可換成另一個人。",
  "charIntro.personality": "性格／氣場：{{personality}}。",
  "charIntro.backstory": "背景要點：{{backstory}}。",
  "charIntro.relationships": "關係要點：{{relationships}}。",
  "charIntro.soul": "Soul 摘要（表演來源）：{{soul}}",
  "charIntro.performance": "表演：輕微推近或手持晃動；角色望向鏡頭或略偏鏡頭；{{manner}}。",
  "charIntro.speech": "口白：嘴唇自然開合像在簡短自我介紹；聲線：{{voice}}。",
  "charIntro.beat": "動作節奏：自然站定 → 微笑或輕點頭 → 簡短介紹手勢（可空手）→ 定格。",
  "charIntro.lighting": "光線與靜幀一致；無字幕、無 logo、無其他人入鏡。",
  "sceneIntro.task": "圖生影片：以參考靜幀中的同一場地，拍一段短劇用「場景介紹／建立鏡頭」短片。",
  "sceneIntro.spaceLock": "空間鎖定：建築、材質、招牌、格局與色彩語言必須與參考靜幀一致，不可換成另一個地方。",
  "sceneIntro.name": "地點名稱：{{name}}。",
  "sceneIntro.place": "場地描述：{{place}}。",
  "sceneIntro.spaceType": "空間類型：{{type}}。",
  "sceneIntro.time": "時段：{{time}}。",
  "sceneIntro.weather": "天氣：{{weather}}。",
  "sceneIntro.moodLight": "氣氛：{{mood}}。燈光：{{lighting}}。",
  "sceneIntro.palette": "色盤：{{palette}}。",
  "sceneIntro.setDressing": "陳設：{{set}}。",
  "sceneIntro.tags": "視覺標籤：{{tags}}。",
  "sceneIntro.art": "藝術風格：{{art}}。",
  "sceneIntro.ambient": "環境氛圍（無 UI 字幕）：{{sound}}。",
  "sceneIntro.scriptCue": "本場提示（只作氣氛，勿新增角色臉，除非靜幀已有）：{{cue}}。",
  "sceneIntro.camera": "運鏡：{{camera}}；連續輕微動態。除非材料已有，否則勿新增路人臉、logo、字幕。",
  "sceneIntro.beat": "動作節奏：建立鏡頭定場 → 環境微動（光影、天氣粒子、已有的布料／樹影）→ 定格。",
  "propIntro.task": "圖生影片：以參考靜幀中的同一道具，拍一段短劇 continuity 用「道具介紹／主視覺」短片。",
  "propIntro.objectLock": "物件鎖定：輪廓、材質、顏色、刻字／紋樣、舊損與比例必須與參考圖一致，不可換成另一件。",
  "propIntro.name": "道具名稱：{{name}}。",
  "propIntro.look": "外觀描述：{{look}}。",
  "propIntro.material": "材質：{{material}}。",
  "propIntro.size": "尺寸筆記：{{size}}。",
  "propIntro.condition": "狀態／舊損：{{condition}}。",
  "propIntro.tags": "視覺標籤：{{tags}}。",
  "propIntro.art": "藝術風格：{{art}}。",
  "propIntro.camera": "運鏡：乾淨桌面／主視覺台，輕微環繞或慢推近；光線與靜幀一致。",
  "propIntro.beat": "動作節奏：主視覺定格 → 微光澤／微旋轉或材質閃爍（若圖中已有）→ 定格。",
  "propIntro.noHands": "除非靜幀已有，否則勿加手、角色臉、字幕、浮水印或額外道具。",
  "costumeIntro.task": "圖生影片：以參考靜幀中的同一戲服造型，拍一段短劇戲服庫用「造型介紹」短片。",
  "costumeIntro.wardrobeLock": "服裝鎖定：輪廓、布料、顏色、層次、配件與舊損必須與參考圖一致，不可換成另一套。",
  "costumeIntro.identityOrProduct": "若靜幀有人：鎖定臉與體型，布料可輕微擺動；若為人台／平鋪：保持產品構圖。",
  "costumeIntro.name": "造型名稱：{{name}}。",
  "costumeIntro.desc": "戲服描述：{{look}}。",
  "costumeIntro.art": "藝術風格：{{art}}。",
  "costumeIntro.camera": "運鏡：輕微推近或慢環繞；光線與靜幀一致。",
  "costumeIntro.beat": "動作節奏：定格 → 布料垂墜／袖口微動／五金反光 → 定格。",
  "costumeIntro.forbid": "勿新增角色臉、字幕、logo 或色情姿勢。",
  "costumeIntro.fallbackName": "造型",
  "actionIntro.lead": "短劇動作示範片：「{{name}}」。",
  "actionIntro.intention": "意圖：{{intention}}",
  "actionIntro.body": "肢體節奏：{{body}}",
  "actionIntro.camera": "鏡頭：{{camera}}",
  "actionIntro.closing": "動作連貫流暢，無字幕水印，緊跟關鍵幀靜圖。",
  "sceneIntroPolish.task": "任務：場景介紹／建立鏡頭短片（圖生影片）。",
  "sceneIntroPolish.hasRef": "參考場景靜圖會交予影片 API——必須鎖定該圖空間身份。",
  "sceneIntroPolish.noRef": "本文無靜圖路徑；仍須鎖定地點聖經描述。",
  "sceneIntroPolish.dossier": "場景檔案：",
  "sceneIntroPolish.scriptCue": "劇本提示（只作氣氛）：\n{{script}}",
  "sceneIntroPolish.emptySet": "空鏡為主；除非靜幀已有，否則勿新增角色臉。無字幕、logo。",
  "propIntroPolish.task": "任務：道具主視覺介紹短片（圖生影片）。",
  "propIntroPolish.hasRef": "參考道具靜圖會交予影片 API——必須鎖定該圖物件身份。",
  "propIntroPolish.noRef": "本文無靜圖路徑；仍須鎖定道具檔案描述。",
  "propIntroPolish.dossier": "道具檔案：",
  "propIntroPolish.noHands": "除非靜幀已有，否則勿新增手或角色臉。無字幕、logo。",
  "costumeIntroPolish.task": "任務：戲服／造型介紹短片（圖生影片）。",
  "costumeIntroPolish.hasRef": "參考靜圖會交予影片 API——有人則鎖定身份＋服裝；人台／平鋪則鎖定服裝輪廓與材質。",
  "costumeIntroPolish.noRef": "本文無靜圖路徑；仍須鎖定戲服描述。",
  "costumeIntroPolish.dossier": "戲服檔案：",
  "costumeIntroPolish.fabric": "布料垂墜／微動即可；勿新增角色臉；無字幕、logo。",
  "actionIntroPolish.task": "任務：動作指導介紹短片（圖生影片）。",
  "actionIntroPolish.hasRef": "參考靜圖已附——表演身份鎖定該幀。",
  "actionIntroPolish.templateKeepRules": "模板草稿（請改進；HARD RULES 置於最尾）：",
  "cover.posterLead": "PROFESSIONAL SHORT-DRAMA POSTER / KEY ART（16:9 靜幀）。不是 UI 模型。無文字、logo、浮水印、標題字幕。",
  "cover.titleMood": "故事標題（只取氣氛，畫面勿寫出文字）：{{title}}。",
  "cover.styleBible": "風格備註：{{style}}",
  "cover.extraDir": "額外方向：{{idea}}",
  "cover.establishing": "適合用作片庫封面的情緒建立鏡頭；強烈剪影、可讀氣氛。",
  "cover.medium": "依藝術風格 medium 出圖；構圖清晰。",
  "cover.editPrefix": "IMAGE EDIT：以新構圖創作短劇海報。保留主體身份／氣氛（如有）。",
  "cover.label": "故事封面",
  "costumeFill.system": "你是影視造型指導。只回覆緊湊 JSON：{\"name\":\"短名稱\",\"description\":\"完整戲服描述（分層、布料、顏色、配飾；無品牌 Logo）\",\"artStyle\":\"可選風格 id 或空字串\",\"hardRules\":\"3–8 句必須／禁止\"} 每個鍵必須是 JSON 字串（不可 null／陣列）。不要 markdown。若有參考圖，請按圖如實描述該造型，供短劇出圖使用。",
  "costumeFill.idea": "構思：{{idea}}",
  "costumeFill.polish": "潤飾以下戲服草稿。",
  "costumeFill.required": "必填鍵：name, description, artStyle, hardRules。缺鍵無效。",
  "costumeFill.fallbackName": "造型",
  "segment.entireStory": "全劇（所有場次）",
  "segment.noStory": "未選故事（僅角色資料）",
  "vision.inventFromImage": "請根據附上的參考圖，完整填寫{{kind}}資料。",
  "vision.polishAll": "全面潤飾並合併所有欄位",
  "story.untitled": "未命名短劇",
  "action.castIdentityNote": "已附 {{count}} 張參考素材（角色／道具等）：每格人物身份須與參考素材一致。",
  "tpl.system.polishOnly": "配方「只潤飾」：保持核心身份與世界。只潤飾措辭。不要發明時代、天氣、職業、地點或樣本世界。不要發明口白語言。不要把預設鐵則寫入檔。",
  "tpl.system.fillBlanks": "配方「只填空白」：只補空欄。已填欄位不要改寫。不要發明新世界。",
  "tpl.system.invent": "配方「自由創作」：用戶授權按 idea 自由補齊可拍細節，必填欄要齊。仍然不要引入 Demo 或本次未暗示的世界。",
  "tpl.system.fromStory": "配方「從故事建議」：只用本次請求已寫出的標題／風格／選角／場景做 continuity。衝突時以用戶 idea 為準。",
  "tpl.system.followAsset": "配方「跟資產／故事」：跟已提供的風格與鐵則。除非材料有寫，不要強加電影感、空鏡或 6–10 秒。片長跟 clip 實際秒數。",
  "tpl.system.cinematicLock": "配方「電影感＋防幻覺」：電影短劇感；場地空鏡優先；無水印、logo、多餘臉；人類恰好兩手兩臂兩腿（非人除外）。",
  "tpl.system.identityLock": "配方「鎖身份」：臉／體／服裝／場地／道具必須鎖定附圖。不要換成另一人、另一地或另一物。",
  "tpl.system.restyle": "配方「可改造型」：保持同一角色身份。服裝、場地陳設、時代可按用戶要求改。不要換成另一個人。",
  "pipeline.character.system": "你為短劇 AI 影片潤飾角色聖經。每位角色 3–5 行：外形、聲線、動機、招牌動作。只用本次請求已有事實。",
  "pipeline.scene.system": "你把短劇場景擴成視覺節拍表。每拍跟材料之中的實際片長，不要當 6–10 秒。只用已提供場景。",
  "pipeline.props.system": "你為短劇潤飾道具連續性。記顏色、尺寸、出場時機。名單以外不要發明道具。",
  "pipeline.script.system": "你是專業短劇編劇。每場寫一段適合 AI 影片的緊湊劇本。用故事實際片長，不要硬加 10 秒上限。每場格式：\n### SCENE <number> | id=<id>\n<script body>",
  "pipeline.script.noScenes": "（無場景 — 不要發明地點）"
}